#ifdef SPANISH
	#define STR0001 "El asistente lo ayudara en el proceso de asociacion de plan de pago en lote para alumnos."
	#define STR0002 "El (los) servicio(s) y la(s) forma(s) de pago seleccionado(s) se asociaran a todos los responsables de los alunmos seleccionados."
	#define STR0003 "Asistente de plan de pago en lote"
	#define STR0004 "Plan de Pago en Lote"
	#define STR0005 "Curso y Servicios"
	#define STR0006 "Paso 01 - Seleccione el curso e el(los) servicio(s) que se consideraran en el procesamiento y haga clic en <Avanzar>"
	#define STR0007 "Curso"
	#define STR0008 "Cod. Curso"
	#define STR0009 "Desc. Curso"
	#define STR0010 "Per. Lectivo"
	#define STR0011 "Habilitacion"
	#define STR0012 "Desc. Habilitacion"
	#define STR0013 "Grupo"
	#define STR0014 "Servicios"
	#define STR0015 "Seleccione los servicios que se asociaran al plan de pago"
	#define STR0016 "Codigo"
	#define STR0017 "Descripcion"
	#define STR0018 "Seleccion de alumnos"
	#define STR0019 "Paso 02 - Seleccione el(los) alumno(s) deseado(s), y haga clic en <Avanzar>"
	#define STR0020 "Alumnos"
	#define STR0021 "Ordenar por:"
	#define STR0022 "1=R.A."
	#define STR0023 "2=Nombre"
	#define STR0024 "¿Calcula Desc. de beca de estudio?"
	#define STR0025 "1=Si"
	#define STR0026 "2=No"
	#define STR0027 "¿Cuestiona Desc. de beca de estudio?"
	#define STR0028 "Leyenda"
	#define STR0029 "Seleccione el(los) alumno(s) deseado(s):"
	#define STR0030 "RA"
	#define STR0031 "Nombre"
	#define STR0032 "Seleccion de forma de pago"
	#define STR0033 "Paso 03 - Seleccione la forma de pago deseada, y haga clic en <Avanzar>"
	#define STR0034 "Formas de Pago"
	#define STR0035 "Seleccione la forma de pago deseada para cada servicio siguiente:"
	#define STR0036 "Finalizado"
	#define STR0037 "Procesamiento finalizado con exito. Haga clic en <Finalizar>"
	#define STR0038 "Atencion"
	#define STR0039 "Solamente es posible seleccionar cursos cuya financiacion este configurada como Formas de Pago."
	#define STR0040 "El curso informado no esta configurado para cobrar valor."
	#define STR0041 "No existe este periodo lectivo para el curso informado."
	#define STR0042 "No existe esta habilitacion para el curso y periodo lectivo informado."
	#define STR0043 "No existe este grupo para el curso y periodo lectivo informado."
	#define STR0044 "Informe el curso deseado."
	#define STR0045 "Informe el periodo lectivo deseado."
	#define STR0046 "Informe el grupo deseado."
	#define STR0047 "Debe seleccionarse por lo menos un servicio."
	#define STR0048 "Buscando alumnos..."
	#define STR0049 "No se encontraron alumnos para los datos informados."
	#define STR0050 "No se encontraron alunmos que aun no tiene(n) el(los) servicio(s) seleccionado(s)."
	#define STR0051 "La seleccion del servicio "
	#define STR0052 " no se considerara, pues no se encontraron alumnos que aun no tienen este servicio."
	#define STR0053 "Informe si debe calcular el descuento de beca de estudio."
	#define STR0054 "Informe si debe cuestionar sobre descuento de beca de estudio."
	#define STR0055 "Debe seleccionarse por lo menos un alumno."
	#define STR0056 " no se considerara, pues todos los alumnos seleccionados ya tienen este servicio."
	#define STR0057 "Retorne y seleccione por lo menos un servicio."
	#define STR0058 "No existen Formas de Pago disponibles para el(los) servicio(s) seleccionado(s)."
	#define STR0059 "No existen Formas de Pago disponibles para el servicio "
	#define STR0060 "Forma de pago"
	#define STR0061 "Espere el procesamiento..."
	#define STR0062 "Grabando datos..."
	#define STR0063 "La situacion de los alumnos seleccionados que estaban como MATRICULADOS PREVIAMENTE se modifico a MATRICULADO"
	#define STR0064 "Alumno"
	#define STR0065 "Matriculado"
	#define STR0066 "Matriculado previamente"
#else
	#ifdef ENGLISH
		#define STR0001 "Wizard will help you in the process of payment plan association in lot for students."
		#define STR0002 "Service(s) and payment mode chosen will be associated with all responsible for the students selected."
		#define STR0003 "Payment in Lot Plan Assistant"
		#define STR0004 "Payment in Lot Plan"
		#define STR0005 "Course and Services"
		#define STR0006 "Step 01 - Select the course and the service(s) to be considered and click <Next>"
		#define STR0007 "Course"
		#define STR0008 "Code Course"
		#define STR0009 "Description Course"
		#define STR0010 " School Year"
		#define STR0011 "Qualification"
		#define STR0012 "Description Specialization"
		#define STR0013 "Class"
		#define STR0014 "Services"
		#define STR0015 "Select the services to be linked in the payment plan"
		#define STR0016 "Code"
		#define STR0017 "Description"
		#define STR0018 "Students selection"
		#define STR0019 "Step 02 - Select the desired student(s) and click <Next>"
		#define STR0020 "Students"
		#define STR0021 "Classify by:"
		#define STR0022 "1=E.N."
		#define STR0023 "2=Name"
		#define STR0024 "Calculate discount  for scholarship?"
		#define STR0025 "1=Yes"
		#define STR0026 "2=No"
		#define STR0027 "Question discount for scholarship?"
		#define STR0028 "Caption"
		#define STR0029 "Select the desired student(s):"
		#define STR0030 "EN"
		#define STR0031 "Name"
		#define STR0032 "Select payment form"
		#define STR0033 "Step 03 - Select the desired payment form and click <Next>"
		#define STR0034 "Payment Terms:"
		#define STR0035 "Select the payment form desired for each service below: "
		#define STR0036 "Concluded"
		#define STR0037 "Processing concluded successfully.  Click <Finish>"
		#define STR0038 "Attention"
		#define STR0039 "Courses can only be selected when installment is configured as Payment Forms. "
		#define STR0040 "The course entered is not configured to charge."
		#define STR0041 "There is no school year for the course entered. "
		#define STR0042 "There is no specialization for the course and school year entered. "
		#define STR0043 "There is no class for the course and school year entered. "
		#define STR0044 "Enter the course desired."
		#define STR0045 "Enter the desired school year. "
		#define STR0046 "Enter the desired class."
		#define STR0047 "At least one service must be selected."
		#define STR0048 "Searching students..."
		#define STR0049 "No students were found for the data entered."
		#define STR0050 "No students, whose service(s) are not selected, were found."
		#define STR0051 "Service selection "
		#define STR0052 " is disconsidered, as no students that still have this service were found. "
		#define STR0053 "Enter if scholarship discount must be granted. "
		#define STR0054 "Enter if scholarship discount must be questioned. "
		#define STR0055 "At least one service must be selected."
		#define STR0056 " It is disconsidered, since all students already have this service."
		#define STR0057 "Return. At least one service must be selected."
		#define STR0058 "There are no available Payment Forms for the service(s) selected."
		#define STR0059 "There are no available Payment Forms for the service "
		#define STR0060 "Payment Form"
		#define STR0061 "Wait processing..."
		#define STR0062 "Saving data..."
		#define STR0063 "PRE-ENROLLED selected students are now considered ENROLLED"
		#define STR0064 "Student"
		#define STR0065 "Enrolled"
		#define STR0066 "Pre-Enrolled"
	#else
		#define STR0001 "O assistente irá auxiliá-lo no processo de associação de plano de pagamento em lote para alunos."
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "O(s) serviço(s) e a(s) forma(s) de pagamento escolhido(s) serão associados a todos os responsáveis dos alunos seleccionados.", "O(s) serviço(s) e a(s) forma(s) de pagamento escolhido(s) serão associados a todos os responsáveis dos alunos selecionados." )
		#define STR0003 "Assistente de plano de pagamento em lote"
		#define STR0004 "Plano de Pagamento em Lote"
		#define STR0005 "Curso e Serviços"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Passo 01 - Seleccione o curso e o(s) serviço(s) que serão considerados no processamento, e clique em <Avançar>", "Passo 01 - Selecione o curso e o(s) serviço(s) que serão considerados no processamento, e clique em <Avançar>" )
		#define STR0007 "Curso"
		#define STR0008 "Cód. Curso"
		#define STR0009 "Desc. Curso"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Per. Lectivo", "Per. Letivo" )
		#define STR0011 "Habilitação"
		#define STR0012 "Desc. Habilitação"
		#define STR0013 "Turma"
		#define STR0014 "Serviços"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Seleccione os serviços a serem associados no plano de pagamento", "Selecione os serviços a serem associados no plano de pagamento" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Código", "Codigo" )
		#define STR0017 "Descrição"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Selecção de alunos", "Seleção de alunos" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Passo 02 - Seleccione o(s) aluno(s) desejado(s), e clique em <Avançar>", "Passo 02 - Selecione o(s) aluno(s) desejado(s), e clique em <Avançar>" )
		#define STR0020 "Alunos"
		#define STR0021 "Ordenar por:"
		#define STR0022 "1=R.A."
		#define STR0023 "2=Nome"
		#define STR0024 "Calcula desc. de bolsa de estudo?"
		#define STR0025 "1=Sim"
		#define STR0026 "2=Não"
		#define STR0027 "Questiona desc. de bolsa de estudo?"
		#define STR0028 "Legenda"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Seleccione o(s) aluno(s) desejado(s):", "Selecione o(s) aluno(s) desejado(s):" )
		#define STR0030 "RA"
		#define STR0031 "Nome"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Selecção da forma de pagamento", "Seleção da forma de pagamento" )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Passo 03 - Seleccione a forma de pagamento desejada, e clique em <Avançar>", "Passo 03 - Selecione a forma de pagamento desejada, e clique em <Avançar>" )
		#define STR0034 "Formas de Pagamento"
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Seleccione a forma de pagamento desejada para cada serviço abaixo:", "Selecione a forma de pagamento desejada para cada serviço abaixo:" )
		#define STR0036 "Concluído"
		#define STR0037 "Processamento finalizado com sucesso. Clique em <Finalizar>"
		#define STR0038 "Atenção"
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Somente é possível seleccionar cursos cujo parcelamento esteja configurado como Formas de Pagamento.", "Somente é possível selecionar cursos cujo parcelamento esteja configurado como Formas de Pagamento." )
		#define STR0040 "O curso informado não está configurado para cobrar valor."
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Não existe este período lectivo para o curso informado.", "Não existe este período letivo para o curso informado." )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Não existe esta habilitação para o curso e período lectivo informado.", "Não existe esta habilitação para o curso e período letivo informado." )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Não existe esta turma para o curso e período lectivo informado.", "Não existe esta turma para o curso e período letivo informado." )
		#define STR0044 "Informe o curso desejado."
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Informe o período lectivo desejado.", "Informe o período letivo desejado." )
		#define STR0046 "Informe a turma desejada."
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Deve ser seleccionado pelo menos um serviço.", "Deve ser selecionado pelo menos um serviço." )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "A Buscar alunos...", "Buscando alunos..." )
		#define STR0049 "Não foram encontrados alunos para os dados informados."
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Não foram encontrados alunos que ainda não possuem o(s) serviço(s) seleccionado(s).", "Não foram encontrados alunos que ainda não possuem o(s) serviço(s) selecionado(s)." )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "A selecção do serviço ", "A seleção do serviço " )
		#define STR0052 " será desconsiderada, pois não foram encontrados alunos que ainda não possuem este serviço."
		#define STR0053 "Informe se deve calcular o desconto de bolsa de estudo."
		#define STR0054 "Informe se deve questionar sobre desconto de bolsa de estudo."
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Deve ser seleccionado pelo menos um aluno.", "Deve ser selecionado pelo menos um aluno." )
		#define STR0056 If( cPaisLoc $ "ANG|PTG", " será desconsiderada, pois todos os alunos seleccionados já possuem este serviço.", " será desconsiderada, pois todos os alunos selecionados já possuem este serviço." )
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Retorne e seleccione pelo menos um serviço.", "Retorne e selecione pelo menos um serviço." )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Não existem Formas de Pagamento disponíveis para o(s) serviço(s) seleccionado(s).", "Não existe Formas de Pagamento disponíveis para o(s) serviço(s) selecionado(s)." )
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Não existem Formas de Pagamento disponíveis para o serviço ", "Não existe Formas de Pagamento disponíveis para o serviço " )
		#define STR0060 "Forma de pagamento"
		#define STR0061 "Aguarde o processamento..."
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "A gravar dados...", "Gravando dados..." )
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "A situação dos alunos seleccionados que estavam como PRÉ-MATRICULADOS foi alterada para MATRICULADO", "A situação dos alunos selecionados que estavam como PRÉ-MATRICULADOS foi alterada para MATRICULADO" )
		#define STR0064 "Aluno"
		#define STR0065 "Matriculado"
		#define STR0066 "Pré-Matriculado"
	#endif
#endif
