#ifdef SPANISH
	#define STR0001 "Movimiento del alumno"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Matricular"
	#define STR0005 "Modificar"
	#define STR0006 "Revertir"
	#define STR0007 "Leyenda"
	#define STR0008 "Asignación del alumno"
	#define STR0009 "Indexando el archivo de trabajo"
	#define STR0010 "Indexando el archivo JBL (Ítems del plan curricular)"
	#define STR0011 "Datos financieros"
	#define STR0012 "Documentos"
	#define STR0013 "Número"
	#define STR0014 "Cuota"
	#define STR0015 "Prefijo"
	#define STR0016 "Tipo"
	#define STR0017 "Valor"
	#define STR0018 "Vencimiento"
	#define STR0019 "Saldo"
	#define STR0020 "Número RA"
	#define STR0021 "Código curso"
	#define STR0022 "Documento"
	#define STR0023 "Alumno"
	#define STR0024 "Efectivo"
	#define STR0025 "Provisional"
	#define STR0026 "Financiero"
	#define STR0027 "Título dado de baja"
	#define STR0028 "Título pendiente"
	#define STR0029 "Documento OK"
	#define STR0030 "Documento pendiente"
	#define STR0031 "Cursos disponibles"
	#define STR0032 "Matriculado"
	#define STR0033 "Alumno matriculado previamente"
	#define STR0034 "Alumno sin reserva"
	#define STR0035 "Alumno con reserva"
	#define STR0036 "Materias"
	#define STR0037 "Normal"
	#define STR0038 "Exonerada"
	#define STR0039 "Lunes"
	#define STR0040 "Martes"
	#define STR0041 "Miércoles"
	#define STR0042 "Jueves"
	#define STR0043 "Viernes"
	#define STR0044 "Sabado"
	#define STR0045 "Domingo"
	#define STR0046 "Descripción"
	#define STR0047 "Aprovechamiento de estudios"
	#define STR0048 "Otras mallas curriculares"
	#define STR0049 "Reprobaciones"
	#define STR0050 "Exonerar"
	#define STR0051 "Modificar la situación de la materia"
	#define STR0052 "DP Origen"
	#define STR0053 "Curso"
	#define STR0054 "Período"
	#define STR0055 "Grupo"
	#define STR0056 "Profesor 2"
	#define STR0057 "Profesor 3"
	#define STR0058 "Situación"
	#define STR0059 "Período lectivo"
	#define STR0060 "Turno"
	#define STR0061 "Unidad"
	#define STR0062 "Año"
	#define STR0063 "Seleccionando horario de clases del curso..."
	#define STR0064 "Problema"
	#define STR0065 "No existe vacante disponible para ninguna materia de ese horario de clases."
	#define STR0066 "La materia no puede desmarcarse porque existe movimiento registrado."
	#define STR0067 "Existe título dado de baja referente a esta materia. ¿Desea continuar?"
	#define STR0068 "Curso : "
	#define STR0069 "Materias sin vacantes"
	#define STR0070 "La situación del alumno es "
	#define STR0071 ". ¿Desea exonerar la materia de todos modos?"
	#define STR0072 "Matriculado - Regular"
	#define STR0073 "Matriculado - Materia reprobada"
	#define STR0074 "Inactivo "
	#define STR0075 "Transferido "
	#define STR0076 "Interrumpido "
	#define STR0077 "Graduado"
	#define STR0078 "Prematrícula "
	#define STR0079 "Código"
	#define STR0080 "Seleccionando horarios de clase disponibles..."
	#define STR0081 "No existe vacante disponible para esa materia en ningún horario de clases."
	#define STR0082 "Hora 1"
	#define STR0083 "Hora 2"
	#define STR0084 "Materia"
	#define STR0085 "Profesor"
	#define STR0086 "Nombre"
	#define STR0087 "Existe conflicto de horario en la malla curricular, no podrá modificarse la situación"
	#define STR0088 "La reversión de la matricula no podrá efectuarse. Utilice la rutina Solicitud de requerimientos."
	#define STR0089 "La exoneración no podrá deshacerse, pues existe un conflicto de horarios con la malla curricular actual."
	#define STR0090 "Anulado"
	#define STR0091 "Abandono"
	#define STR0092 "Muerte"
	#define STR0093 "Matriculado - Regular por acción judicial Dep."
	#define STR0094 "Existen materias obligatorias sin ninguna clase seleccionada en la malla curricular."
	#define STR0095 "Matriculado - Regular por acción judicial Fin."
	#define STR0096 "Matriculado - Repetición por acción judicial Fin."
	#define STR0097 "Matriculado - Regular por acción judicial Dep. y Fin."
	#define STR0098 "Débitos financieros"
	#define STR0099 "Orden preliminar anulada"
	#define STR0100 "Integrado"
	#define STR0101 "Registrado"
	#define STR0102 "Este alumno fue archivado. Para activarlo es necesario recuperarlo utilizando el Archivo de alumnos."
	#define STR0103 "Problema"
	#define STR0104 "La situación solamente puede modificarse a Tutoría a partir de la situacion Desaprobado. "
	#define STR0105 "Habilitación"
	#define STR0106 "Descripción"
	#define STR0107 "Habilitación: "
	#define STR0108 "Situación de la materia"
	#define STR0109 "Seleccione la situación en la que se cursará la materia."
	#define STR0110 "DEP"
	#define STR0111 "TUT"
	#define STR0112 "Asignación"
	#define STR0113 "Aprob.Est."
	#define STR0114 "Mallas curriculares"
	#define STR0115 "DP"
	#define STR0116 "Situación"
	#define STR0117 "La situación solamente puede modificarse a Desaprobado siempre y cuando la materia sea de otra malla curricular.  "
	#define STR0118 "Atención"
	#define STR0119 "El alumno fue dispensado de esta materia y por eso no podrá seleccionarse."
	#define STR0120 "Verifique el aprovechamiento de estudio del alumno."
	#define STR0121 "Este curso vigente no tiene materia deaprobada, esta configurado como reprobación"
	#define STR0122 "Recortar"
	#define STR0123 "Copiar"
	#define STR0124 "Calc"
	#define STR0125 "Agenda"
	#define STR0126 "Spool"
	#define STR0127 "Help"
	#define STR0128 "OK"
	#define STR0129 "Pegar"
	#define STR0130 "Selecione el tipo de curso: "
	#define STR0131 "Todos los cursos"
	#define STR0132 "Pool de materias"
	#define STR0133 "Espere"
	#define STR0134 "Seleccionando otros mapas curriculares"
	#define STR0135 "El correquisito "
	#define STR0136 "de la materia "
	#define STR0137 "no se seleccionó. No se permitirá la operación."
	#define STR0138 "Equivalencias especiales"
	#define STR0139 "Eqv.Esp."
	#define STR0140 "No es posiblel seleccionar otras mallas curriculares antes de hacer efectiva la matrícula del alumno."
	#define STR0141 "Este alumno fue aprobado en esta materia en otro período lectivo. ¿Confirma la selección?"
	#define STR0142 "&Sí"
	#define STR0143 "&No"
	#define STR0144 "Forma de pago"
	#define STR0145 "El curso seleccionado no tiene cursos vigentes disponibles para"
	#define STR0146 " en la consulta realizada. ¡Los Cursos vigentes que permanecerán a continuación puede o no estar en relación con el Curso estándar en enfoque!"
	#define STR0147 "Código "
	#define STR0148 "Descripción "
	#define STR0149 "Alumno con plazo de curso excedido"
	#define STR0150 "El alumno se encuentra con el plazo del curso excedido. ¿Desea activar la matricula del alumno nuevamente?"
	#define STR0151 "Sí"
	#define STR0152 "No"
	#define STR0153 "Seleccione un Subgrupo."
	#define STR0154 "Subgrupos disponibles"
	#define STR0155 "La matrícula no puede realizarse, pues la fecha esta fuera del calendario de matrículas."
	#define STR0156 "Alumno no solicitó requerimiento para la matrícula"
	#define STR0157 "El alumno solicitó un requerimiento, pero está con pago pendiente o ya se utilizó."
	#define STR0158 "Plazo para matrícula excedido."
	#define STR0159 "La matrícula no puede realizarse, pues no se encontraron ítems de matrícula y/o matrícula fuera del plazo en el Calendario académico."
	#define STR0160 "El usuario no tiene autorización para realizar esta matrícula fuera del plazo."
	#define STR0161 "Modalidad"
	#define STR0162 "Subgrupo"
	#define STR0163 "No puede realizarse borrado de materia, pues la fecha está fuera del calendario de la materia."
	#define STR0164 "No existe requisito desponible para el borrado de la materia."
	#define STR0165 "Alumno no solicitó requisito para el borrado de la materia."
	#define STR0166 "Plazo para el borrado está excedido."
	#define STR0167 "No puede realizarse el borrado de la materia, pues no se encontraron ítems de borrado de materias en el Calendario académico."
	#define STR0168 "No puede realizarse inclusión de materia, pues la fecha esta fuera del calendario de inclusión de materia."
	#define STR0169 "No existe requerimiento disponible para inclusión de la materia."
	#define STR0170 "Alumno no solicitó requerimiento para inclusión de la materia"
	#define STR0171 "Plazo para inclusión de materias excedido."
	#define STR0172 "No puede realizarse inclusión de materia, pues no se encontraron ítems de inclusión de materia en el Calendario académico."
	#define STR0173 "Desea vincular el curso"
	#define STR0174 "a la Beca de estudios "
	#define STR0175 " Versión "
	#define STR0176 "Exoneración simple"
	#define STR0177 "Exoneración por aprovechamiento de estudios"
	#define STR0178 "Es obligatorio informar la Nota o Concepto de la materia"
	#define STR0179 "¡La materia no fue exonerada!"
	#define STR0180 "Carga horaria"
	#define STR0181 "Curso"
	#define STR0182 "Materia"
	#define STR0183 "Archivo de materinas externas (Otras instituciones) "
	#define STR0184 "Cód. Materia"
	#define STR0185 "La situación solamente puede modificarse a Adaptación siempre y cuando la materia fuera de otro mapa curricular."
	#define STR0186 "No es posible modificar el Componente antes de hacer efectiva la matrícula del alumno."
	#define STR0187 "Componentes"
	#define STR0188 "Planes de pago"
	#define STR0189 "Pl.Pago"
	#define STR0190 "Este alumno no está matriculado."
	#define STR0191 "El parámetro que autoriza la matrícula fuera del plazo MV_ACCLMAT, "
	#define STR0192 "está con valor 2 = No. Con lo cual no se permite el borrado"
	#define STR0193 "Usuario sin autorización para realizar inclusión/borrado de materia fuera del plazo"
	#define STR0194 "No es posible modificar el Componente antes de hacer efectiva la matrícula del alumno."
	#define STR0195 "Componentes"
	#define STR0196 "Compon."
	#define STR0197 "Mantenimiento de componente curricular"
	#define STR0198 "Activo"
	#define STR0199 "1=Sí"
	#define STR0200 "5=Graduado "
	#define STR0201 "¡El alumno solamente podrá graduarse después de cumplir todos los componentes!"
	#define STR0202 "No se permite la interrupción de materias individuales."
	#define STR0203 "Alumno matriculado en este curso. ¡Por favor realice promoción para este curso!"
	#define STR0204 "Alumno no asignado"
	#define STR0205 "¿Matrícula de acuerdo con el mapa Cur.?"
	#define STR0206 "Aviso"
	#define STR0207 "El valor para descuento de la materia es de R$ "
	#define STR0208 ". ¿Confirma el descuento en los títulos de matrícula y mensualidad del alumno?"
	#define STR0209 "Valor de la beca superior al valor de la cuota (R$ "
	#define STR0210 "). Informe un valor inferior."
	#define STR0211 "El valor de la beca no puede ser negativo"
	#define STR0212 "Valor de la beca no puede ser superior al valor del título."
	#define STR0213 "Marca todas las materias"
	#define STR0214 "Marcar"
	#define STR0215 "Desmarca todas las materias"
	#define STR0216 "Desmarcar"
	#define STR0217 "Aulas no desmarcadas"
	#define STR0218 "Día de la semana"
	#define STR0219 "Hora 1"
	#define STR0220 "Hora 2"
	#define STR0221 "Materia"
	#define STR0222 "Descripción"
	#define STR0223 "Motivo"
	#define STR0224 "La materia no puede modificarse, pues el mapa curricular del curso/período lectivo no lo permite."
	#define STR0225 "La materia no puede desmarcarse, pues es obligatoria."
	#define STR0226 "Aulas no marcadas"
	#define STR0227 "La materia no puede seleccionarse, pues fue exonerada."
	#define STR0228 "La materia está registrada en el mapa curricular actual."
	#define STR0229 "Existe un conflicto de horario con el mapa curricular actual del alumno."
	#define STR0230 "La materia tiene movimiento registrado."
	#define STR0231 "Existe un título dado de baja referente a esta materia."
	#define STR0232 "El alumno tiene una matrícula en el curso "
	#define STR0233 " con estatus "
	#define STR0234 "Esta acción permitirá que el alumno quede 'ACTIVO' en el curso y que las materias se actualicen a 'EN CURSO'."
	#define STR0235 "¿Desea continuar?"
	#define STR0236 "Atención"
	#define STR0237 "No es posible exonerar la materia. Por favor, matricule al alumno y seleccione un plan de pago para que pueda efectuarse el cálculo/reembolso."
	#define STR0238 "Año Lectivo+Período"
	#define STR0239 "Curso vigente"
	#define STR0240 "Índice"
	#define STR0241 "Anular"
	#define STR0242 "Existe(n) materia(s) obligatoria(s) no registada(s) en el horario de clases"
	#define STR0243 "Actividades"
	#define STR0244 " No es posible modificar la situación de la materia a: "
	#define STR0245 ". Utilice el requerimiento"
	#define STR0246 "El alumno no se matriculó en el(los) período(s) anterior(es)."
#else
	#ifdef ENGLISH
		#define STR0001 "Student´s Movement"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Enroll"
		#define STR0005 "Change"
		#define STR0006 "Reversal"
		#define STR0007 "Caption"
		#define STR0008 "Student´s Allocation"
		#define STR0009 "Indexing Work File"
		#define STR0010 "Indexing JBL File (Items of the Schedule Classes)"
		#define STR0011 "Financial Data"
		#define STR0012 "Documents"
		#define STR0013 "Number"
		#define STR0014 "Installment"
		#define STR0015 "Prefix"
		#define STR0016 "Type"
		#define STR0017 "Value"
		#define STR0018 "Due Date"
		#define STR0019 "Balance"
		#define STR0020 "AR Number"
		#define STR0021 "Course Code"
		#define STR0022 "Document"
		#define STR0023 "Current"
		#define STR0024 "Temporary"
		#define STR0025 "Student"
		#define STR0026 "Financials"
		#define STR0027 "Bill Posted"
		#define STR0028 "Pending Bill"
		#define STR0029 "Document OK"
		#define STR0030 "Pending Document"
		#define STR0031 "Available Courses"
		#define STR0032 "Enrolled"
		#define STR0033 "Pre-Registered Student"
		#define STR0034 "Student w/o Reservation"
		#define STR0035 "Student with Reservation"
		#define STR0036 "Exempt"
		#define STR0037 "Regular"
		#define STR0038 "Subjects"
		#define STR0039 "Monday"
		#define STR0040 "Tuesday"
		#define STR0041 "Wednesday"
		#define STR0042 "Thursday"
		#define STR0043 "Friday"
		#define STR0044 "Saturday"
		#define STR0045 "Sunday"
		#define STR0046 "Description"
		#define STR0047 "Studies Already Taken"
		#define STR0048 "Other Curricular Schedules"
		#define STR0049 "Failed Subjects"
		#define STR0050 "Exempt"
		#define STR0051 "Change of Subject Status"
		#define STR0052 "Failed Subject of Origin"
		#define STR0053 "Course"
		#define STR0054 "Period"
		#define STR0055 "Division"
		#define STR0056 "Teacher 2"
		#define STR0057 "Teacher 3"
		#define STR0058 "Status"
		#define STR0059 "School Year"
		#define STR0060 "Shift"
		#define STR0061 "Branch"
		#define STR0062 "Year"
		#define STR0063 "Selecting the schedule of course classes..."
		#define STR0064 "Problem"
		#define STR0065 "There is no available place for any subject of this schedule of class."
		#define STR0066 "The subject cannot be unmarked as there is already registered movement."
		#define STR0067 "There is bill posted referring to this subject. Continue?"
		#define STR0068 "Course : "
		#define STR0069 "Subjects w/o place"
		#define STR0070 "Student´s status is "
		#define STR0071 ". Do you want to exempt the subject anyway?"
		#define STR0072 "Registered - Current"
		#define STR0073 "Registered - Failed Subject "
		#define STR0074 "Inactive "
		#define STR0075 "Transferred "
		#define STR0076 "Cancelled "
		#define STR0077 "Graduated "
		#define STR0078 "Pre-Registration "
		#define STR0079 "Code"
		#define STR0080 "Selecting schedules of available classes..."
		#define STR0081 "There is no available place for this subject in any schedule of class."
		#define STR0082 "Hour 1"
		#define STR0083 "Hour 2"
		#define STR0084 "Subject"
		#define STR0085 "Teacher"
		#define STR0086 "Name"
		#define STR0087 "There is a timetable overlap, the status change cannot be accomplished"
		#define STR0088 "The reversal of registration cannot be executed. Use the Application Request routine."
		#define STR0089 "Dismissal cannot be undone as there is a timetable overlap in relation to the current curricular schedule."
		#define STR0090 "Cancelled"
		#define STR0091 "Discontinuance"
		#define STR0092 "Death"
		#define STR0093 "Registered - Current acc. Legal Action Dep."
		#define STR0094 "There are required subjects with no class selected on the schedule."
		#define STR0095 "Registered - Current acc. Legal Action Fin."
		#define STR0096 "Registered - Failed Subject under Legal Action Fin."
		#define STR0097 "Registered - Current acc. Legal Action Failed Subject and Fin."
		#define STR0098 "Financial Debits"
		#define STR0099 "Injunction Revoked"
		#define STR0100 "Integrated"
		#define STR0101 "Filed"
		#define STR0102 "This student was already filed. It is necessary to recover the student from the student´s file, in case you require to move him."
		#define STR0103 "Problem "
		#define STR0104 "The status can only be changed from the Failed Subject status to Tutorship."
		#define STR0105 "Capacitation"
		#define STR0106 "Descript."
		#define STR0107 "Capacitation: "
		#define STR0108 "Subject Status"
		#define STR0109 "Select the status in which the subject will be studied."
		#define STR0110 "DEP"
		#define STR0111 "TUT"
		#define STR0112 "Allocation"
		#define STR0113 "Forecast Approval"
		#define STR0114 "Schedules"
		#define STR0115 "Failed Subjects"
		#define STR0116 "Status"
		#define STR0117 "Status can only be changed to Failed Subject whenever the subject is from other grid.       "
		#define STR0118 "Attn.  "
		#define STR0119 "This subject is discharged for the student, therefore, it cannot be selected.             "
		#define STR0120 "Check the study utilization of the student.      "
		#define STR0121 "This course has no failed subject, it is configured as failure. "
		#define STR0122 "Cut"
		#define STR0123 "Copy"
		#define STR0124 "Calc"
		#define STR0125 "Schedule"
		#define STR0126 "Spool"
		#define STR0127 "Help"
		#define STR0128 "OK"
		#define STR0129 "Paste"
		#define STR0130 "Select course type: "
		#define STR0131 "All the courses"
		#define STR0132 "Discipline Pool"
		#define STR0133 "Wait"
		#define STR0134 "Selecting other curricular grades"
		#define STR0135 "Requirement "
		#define STR0136 "of discipline "
		#define STR0137 "was not selected. Operation will not be allowed."
		#define STR0138 "Special equivalences"
		#define STR0139 "Spc.Equ."
		#define STR0140 "Unable to select other grids before enrolling the student.                        "
		#define STR0141 "This student has already passed this subject another school period. Confirm selection?  "
		#define STR0142 "&Yes"
		#define STR0143 "&No"
		#define STR0144 "Payment mode"
		#define STR0145 "Selected course has no available current courses for "
		#define STR0146 " in the query made! The current courses that will remain below may or may not be related to the standard course in focus! "
		#define STR0147 "Code "
		#define STR0148 "Description "
		#define STR0149 "Retired student"
		#define STR0150 "The student is retired. Will you activate the student's registration again? "
		#define STR0151 "Yes"
		#define STR0152 "No"
		#define STR0153 "Select sub-group."
		#define STR0154 "Sub-groups available "
		#define STR0155 "Registration cannot be made because the date is beyond the registrations schedule. "
		#define STR0156 "Student has not requested requirement for registration."
		#define STR0157 "Student requested a requisition but its payment is pending or has already been used. "
		#define STR0158 "Deadline for registration already exceeded."
		#define STR0159 "Enrollment cannot be finished, since items of enrollment and/or enrollment after the deadline were not found in the Academic Calendar."
		#define STR0160 "User has no authorization to make this registration beyond the deadline. "
		#define STR0161 "Modality "
		#define STR0162 "Sub-group"
		#define STR0163 "Deletion of subject cannot be completed because this date is beyond the calendar of the subject. "
		#define STR0164 "Deletion of subject cannot be completed because this date is beyond the calendar of the subject. "
		#define STR0165 "Student has not requested requirement for deletion of the subject"
		#define STR0166 "Deadline for deletion already exceeded."
		#define STR0167 "Deletion of the subject cannot be made because no subject deletion items were found in the School Year Calendar."
		#define STR0168 "Addition of subject cannot be made because this date is beyond the subject addition calendar."
		#define STR0169 "No requirement available for addition of subject."
		#define STR0170 "Student has not requested requirement for addition of the subject"
		#define STR0171 "Deadline to add subjects already exceeded."
		#define STR0172 "Subject insertion cannot be performed, since the insertion items of subject were not found in the Academic Calendar."
		#define STR0173 "Will you link the course "
		#define STR0174 " to the Scholarship "
		#define STR0175 " Version "
		#define STR0176 "Simple discharge"
		#define STR0177 "Discharge due to good grades "
		#define STR0178 "You must enter a Grade or Mark of the Subject "
		#define STR0179 "The subject has not been dismissed !"
		#define STR0180 "Hour load "
		#define STR0181 "Course "
		#define STR0182 "Subject "
		#define STR0183 "External Subject File (other institutions) "
		#define STR0184 "Subject code "
		#define STR0185 "The status can only be changed to Adaptation since the subject belongs to other grid.     "
		#define STR0186 "It is not possible to edit the Component before concluding the student enrollment."
		#define STR0187 "Components "
		#define STR0188 "Payment plans "
		#define STR0189 "PymntPlan"
		#define STR0190 "This student is not enrolled.   "
		#define STR0191 "The parameter that authorizes enrollment beyond the term MV_ACCLMAT, "
		#define STR0192 "has the value 2 = No. Because of this, deletion is not possible"
		#define STR0193 "User not authorized to add/delete subjects beyond the term                     "
		#define STR0194 "It is not possible to change the Component before the enrollment of the student."
		#define STR0195 "Components "
		#define STR0196 "Compon."
		#define STR0197 "Curricular Component Maintenance   "
		#define STR0198 "Active"
		#define STR0199 "1=Yes"
		#define STR0200 "5=Graduated "
		#define STR0201 "The student can only be graduated after meeting all the components!"
		#define STR0202 "It is not allowed to Break the Studies of Individual Subjects."
		#define STR0203 "Student already registered in this course. Create promotion for this course!"
		#define STR0204 "Student not placed"
		#define STR0205 "Enrollm. accord. sched. class?"
		#define STR0206 "Warning"
		#define STR0207 "Rebate amount for the subject is R$ "
		#define STR0208 ". Confirm deduction in registration bills and monthly payment of student?"
		#define STR0209 "Scholarship amount is greater than installment amount (R$ "
		#define STR0210 "). Add a lower value. "
		#define STR0211 "Scholarship amount cannot be negative "
		#define STR0212 "Scholarship cannot be greater than bill amount."
		#define STR0213 "Check all subjects"
		#define STR0214 "Check"
		#define STR0215 "Uncheck all subjects"
		#define STR0216 "Uncheck"
		#define STR0217 "Classes not unchecked"
		#define STR0218 "Day of the week"
		#define STR0219 "Time 1"
		#define STR0220 "Time 2"
		#define STR0221 "Subject"
		#define STR0222 "Description"
		#define STR0223 "Reason"
		#define STR0224 "Subject cannot be modified because the course/school year curricular grid does not allow."
		#define STR0225 "Subject cannot be unchecked because it is compulsory."
		#define STR0226 "Classes not scheduled"
		#define STR0227 "Subject cannot be unchecked because it was exempted."
		#define STR0228 "Subject already registered in current curricular grid."
		#define STR0229 "There is a schedule conflict with the student current grid."
		#define STR0230 "Subject already has transactions registered."
		#define STR0231 "There is a posted bill relating to this subject."
		#define STR0232 "Student already registered into the course "
		#define STR0233 " status "
		#define STR0234 "This action makes the student to be 'ACTIVE' in the course and the subjects to be updated for 'IN COURSE'."
		#define STR0235 "Do you want to continue?"
		#define STR0236 "Attention"
		#define STR0237 "Subject cannot be discharged. Please enroll student and select a payment plan for calculation/rebate to be performed ."
		#define STR0238 "School Year+Period"
		#define STR0239 "Current Course"
		#define STR0240 "Index"
		#define STR0241 "Cancel"
		#define STR0242 "There are mandatory subjects not registered in class schedule."
		#define STR0243 "Activities"
		#define STR0244 " Subject status cannot be changed to: "
		#define STR0245 ". Use petition"
		#define STR0246 "Student was not enrolled in previous period(s)."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Movimentação Do Aluno", "Movimentação do Aluno" )
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Matricular"
		#define STR0005 "Alterar"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Devolução", "Estorno" )
		#define STR0007 "Legenda"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Colocação Do Aluno", "Alocação do Aluno" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "A Indexar Ficheiro De Trabalho", "Indexando Arquivo de Trabalho" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Indexando Arquivo Jbl (elementos Do Plano De Aulas)", "Indexando Arquivo JBL (Itens da Grade de Aulas)" )
		#define STR0011 "Dados Financeiros"
		#define STR0012 "Documentos"
		#define STR0013 "Número"
		#define STR0014 "Parcela"
		#define STR0015 "Prefixo"
		#define STR0016 "Tipo"
		#define STR0017 "Valor"
		#define STR0018 "Vencimento"
		#define STR0019 "Saldo"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Número Ra", "Número RA" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Código De Curso", "Código Curso" )
		#define STR0022 "Documento"
		#define STR0023 "Aluno"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Efectivo", "Efetivo" )
		#define STR0025 "Provisório"
		#define STR0026 "Financeiro"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Título liquidado", "Título Baixado" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Título Em Aberto", "Título em Aberto" )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Documento Ok", "Documento OK" )
		#define STR0030 "Documento Pendente"
		#define STR0031 "Cursos Disponíveis"
		#define STR0032 "Matriculado"
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Aluno Pré-matriculado", "Aluno Pré-Matriculado" )
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Aluno Sem Reserva", "Aluno sem Reserva" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Aluno Com Reserva", "Aluno com Reserva" )
		#define STR0036 "Disciplinas"
		#define STR0037 "Normal"
		#define STR0038 "Dispensada"
		#define STR0039 "Segunda"
		#define STR0040 "Terça"
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Quarta-feira", "Quarta" )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Quinta-feira", "Quinta" )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Sexta-feira", "Sexta" )
		#define STR0044 "Sábado"
		#define STR0045 "Domingo"
		#define STR0046 "Descrição"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Aproveitamento De Estudo", "Aproveitamento de Estudo" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Outros Planos Curriculares", "Outras Grades Curriculares" )
		#define STR0049 "Dependências"
		#define STR0050 "Dispensar"
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Alteração De Situação Da Disciplina", "Alteração da Situação da Disciplina" )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Dp De Origem", "DP Origem" )
		#define STR0053 "Curso"
		#define STR0054 "Período"
		#define STR0055 "Turma"
		#define STR0056 "Professor 2"
		#define STR0057 "Professor 3"
		#define STR0058 "Situação"
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Período Lectivo", "Período Letivo" )
		#define STR0060 "Turno"
		#define STR0061 "Unidade"
		#define STR0062 "Ano"
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "A seleccionar plano de aulas do curso...", "Selecionando grade de aulas do curso..." )
		#define STR0064 "Problema"
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Não existe vaga disponível para nenhuma disciplina deste plano de aulas.", "Não existe vaga disponível para nenhuma disciplina dessa grade de aulas." )
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "A disciplina não poderá ser desmarcada por já existir movimentação registada.", "A disciplina não poderá ser desmarcada por já existir movimentação cadastrada." )
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Existe título levantado referente a esta disciplina. deseja continuar?", "Existe título baixado referente a esta disciplina. Deseja continuar?" )
		#define STR0068 "Curso : "
		#define STR0069 "Disciplinas sem vagas"
		#define STR0070 "A situação do aluno é "
		#define STR0071 If( cPaisLoc $ "ANG|PTG", ". deseja dispensar a disciplina mesmo assim?", ". Deseja dispensar a disciplina mesmo assim?" )
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Registado - Regular", "Matriculado - Regular" )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Matriculado - dependência ", "Maticulado - Dependência " )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Inactivo ", "Inativo " )
		#define STR0075 "Transferido "
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Bloqueado ", "Trancado " )
		#define STR0077 "Formado "
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "Pré-matrícula ", "Pré-Matricula " )
		#define STR0079 "Código"
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "A seleccionar grelhas de aulas disponíveis...", "Selecionando grades de aulas disponíveis..." )
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "Não existe vaga disponível para esta disciplina em nenhuma grelha de aulas.", "Não existe vaga disponível para essa disciplina em nenhuma grade de aulas." )
		#define STR0082 "Hora 1"
		#define STR0083 "Hora 2"
		#define STR0084 "Disciplina"
		#define STR0085 "Professor"
		#define STR0086 "Nome"
		#define STR0087 If( cPaisLoc $ "ANG|PTG", "Existe sobreposição de horário no plano, alteração da situação não poderá ser efectuada", "Existe conflito de horario na grade, alteração da situação não poderá ser efetuada" )
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "O Devolução Da Registo Não Pode Ser Realizado. Utilize O Procedimento De Solicitação De Requerimentos.", "O estorno da matrícula não pode ser realizado. Utilize a rotina de Solicitação de Requerimentos." )
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "A dispensa não pode ser desfeita, pois existe uma sobreposição de horário com o plano curricular actual.", "A dispensa não pode ser desfeita, pois existe um conflito de horário com a grade curricular atual." )
		#define STR0090 "Cancelado"
		#define STR0091 "Desistência"
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "óbito", "Óbito" )
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "Matriculado - Regular Por Acção Judicial Dep.", "Matriculado - Regular por Ação Judicial Dep." )
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Existem disciplinas obrigatórias sem nenhuma aula seleccionada no plano.", "Existem disciplinas obrigatórias sem nenhuma aula selecionada na grade." )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Matriculado - Regular Por Acção Judicial Fin.", "Matriculado - Regular por Ação Judicial Fin." )
		#define STR0096 If( cPaisLoc $ "ANG|PTG", "Matriculado - Dependência Por Acção Judicial Fin.", "Matriculado - Dependência por Ação Judicial Fin." )
		#define STR0097 If( cPaisLoc $ "ANG|PTG", "Matriculado - Regular Por Acção Judicial Dep. E Fin.", "Matriculado - Regular por Ação Judicial Dep. e Fin." )
		#define STR0098 "Débitos Financeiros"
		#define STR0099 If( cPaisLoc $ "ANG|PTG", "Eliminação Anulada", "Liminar Cassada" )
		#define STR0100 If( cPaisLoc $ "ANG|PTG", "Integrado", "Integralizado" )
		#define STR0101 "Arquivado"
		#define STR0102 If( cPaisLoc $ "ANG|PTG", "Este aluno já foi arquivado. para movimentá-lo é necessário recuperá-lo pelo registo de alunos.", "Este aluno já foi arquivado. Para movimentá-lo é necessário recuperá-lo pelo cadastro de alunos." )
		#define STR0103 "Problema"
		#define STR0104 If( cPaisLoc $ "ANG|PTG", "A Situação Só Pode Ser Alterada Para Tutoria A Partir Da Situação Dependência.", "A situacäo so pode ser alterada para Tutoria a partir da situacäo Dependencia." )
		#define STR0105 "Habilitação"
		#define STR0106 "Descrição"
		#define STR0107 "Habilitação: "
		#define STR0108 If( cPaisLoc $ "ANG|PTG", "Situação Da Disciplina", "Situacäo da Disciplina" )
		#define STR0109 If( cPaisLoc $ "ANG|PTG", "Seleccione a situação na qual a disciplina será frequentada.", "Selecione a situacäo na qual a disciplina sera cursada." )
		#define STR0110 If( cPaisLoc $ "ANG|PTG", "Dep", "DEP" )
		#define STR0111 If( cPaisLoc $ "ANG|PTG", "Tut", "TUT" )
		#define STR0112 If( cPaisLoc $ "ANG|PTG", "Alocação", "Alocacäo" )
		#define STR0113 If( cPaisLoc $ "ANG|PTG", "Aprov.est.", "Aprov.Est." )
		#define STR0114 If( cPaisLoc $ "ANG|PTG", "Grelhas", "Grades" )
		#define STR0115 If( cPaisLoc $ "ANG|PTG", "Dps", "DPs" )
		#define STR0116 If( cPaisLoc $ "ANG|PTG", "Situação", "Situacäo" )
		#define STR0117 If( cPaisLoc $ "ANG|PTG", "A situação só pode ser alterada para dependentes desde que a disciplina seja de outra grelha.", "A situacäo so pode ser alterada para Dependencia desde que a disciplina seja de outra grade." )
		#define STR0118 If( cPaisLoc $ "ANG|PTG", "Atenção", "Atencäo" )
		#define STR0119 If( cPaisLoc $ "ANG|PTG", "Esta disciplina encontra-se dispensada para o aluno e por isso não poderá ser seleccionada.", "Esta disciplina encontra-se dispensada para o aluno e por isso näo podera ser selecionada." )
		#define STR0120 "Verifique os aproveitamentos de estudos do aluno."
		#define STR0121 If( cPaisLoc $ "ANG|PTG", "Este curso vigente não possui dependência, está configurado como reprovação.", "Este curso vigente nao possui dependencia, esta configurado como reprovacao." )
		#define STR0122 If( cPaisLoc $ "ANG|PTG", "Cortar", "Recortar" )
		#define STR0123 "Copiar"
		#define STR0124 If( cPaisLoc $ "ANG|PTG", "Cálc", "Calc" )
		#define STR0125 "Agenda"
		#define STR0126 "Spool"
		#define STR0127 If( cPaisLoc $ "ANG|PTG", "Ajuda", "Help" )
		#define STR0128 If( cPaisLoc $ "ANG|PTG", "Ok", "OK" )
		#define STR0129 "Colar"
		#define STR0130 If( cPaisLoc $ "ANG|PTG", "Seleccione o tipo de curso: ", "Selecione o tipo de curso: " )
		#define STR0131 "Todos os cursos"
		#define STR0132 If( cPaisLoc $ "ANG|PTG", "Disciplinas", "Pool de disciplinas" )
		#define STR0133 "Aguarde"
		#define STR0134 If( cPaisLoc $ "ANG|PTG", "A seleccionar outras grelhas curriculares", "Selecionando outras grades curriculares" )
		#define STR0135 "O co-requisito "
		#define STR0136 If( cPaisLoc $ "ANG|PTG", "Da disciplina ", "da disciplina " )
		#define STR0137 If( cPaisLoc $ "ANG|PTG", "Não foi selecionado. não será permitida a operação.", "não foi selecionado. Não será permitida a operação." )
		#define STR0138 "Equivalências Específicas"
		#define STR0139 If( cPaisLoc $ "ANG|PTG", "Eqv.esp.", "Eqv.Esp." )
		#define STR0140 If( cPaisLoc $ "ANG|PTG", "Não será possível seleccionar outras grelhas antes de efectuar o registo do aluno.", "Não será possível selecionar outras grades antes de efetivar a matrícula do aluno." )
		#define STR0141 If( cPaisLoc $ "ANG|PTG", "Este aluno já foi aprovado nesta disciplina noutro período lectivo. confirma a selecção?", "Este aluno já foi aprovado nesta disciplina em outro período letivo. Confirma a seleção?" )
		#define STR0142 If( cPaisLoc $ "ANG|PTG", "&sim", "&Sim" )
		#define STR0143 If( cPaisLoc $ "ANG|PTG", "&não", "&Não" )
		#define STR0144 If( cPaisLoc $ "ANG|PTG", "Forma de pagto", "Forma pagto" )
		#define STR0145 If( cPaisLoc $ "ANG|PTG", "Curso seleccionado não possui cursos vigentes disponíveis para ", "Curso Selecionado não possui Cursos Vigentes disponíveis para " )
		#define STR0146 If( cPaisLoc $ "ANG|PTG", " na consulta realizada ! os cursos vigentes que permanecerão abaixo podem ou não ter relação com o curso padrão em foco !", " na consulta realizada ! Os Cursos Vigentes que permanecerão abaixo podem ou não fazer relação com o Curso Padrão em foco !" )
		#define STR0147 If( cPaisLoc $ "ANG|PTG", "Código  ", "Código " )
		#define STR0148 "Descrição "
		#define STR0149 "Aluno Jubilado"
		#define STR0150 If( cPaisLoc $ "ANG|PTG", "O aluno encontra-se jubilado. deseja activar a matrícula do aluno novamente ?", "O aluno encontra-se jubilado. Você deseja ativar a matricula do aluno novamente ?" )
		#define STR0151 "Sim"
		#define STR0152 "Não"
		#define STR0153 If( cPaisLoc $ "ANG|PTG", "Seleccionar Uma Sub-turma.", "Selecione uma Sub-Turma." )
		#define STR0154 If( cPaisLoc $ "ANG|PTG", "Sub-turmas Disponíveis", "Sub-Turmas Disponiveis" )
		#define STR0155 If( cPaisLoc $ "ANG|PTG", "Matrícula não pode ser realizada, pois a data está fora do calendário de matrículas.", "Matricula nao pode ser realizada, pois a data esta  fora do calendario de matriculas." )
		#define STR0156 If( cPaisLoc $ "ANG|PTG", "Aluno não solicitou requerimento para a matrícula", "Aluno nao solicitou requerimento para a matricula" )
		#define STR0157 If( cPaisLoc $ "ANG|PTG", "O aluno solicitou um requerimento, mas o mesmo está com pagamento pendente ou já foi utilizado.", "O aluno solicitou um requerimento, mas o mesmo esta com pagamento pendente ou ja foi utilizado." )
		#define STR0158 If( cPaisLoc $ "ANG|PTG", "Prazo para matrícula já ultrapassado.", "Prazo para matricula ja ultrapassado." )
		#define STR0159 If( cPaisLoc $ "ANG|PTG", "Matrícula Não Pode Ser Realizada, Pois Não Foram Encontrados Itens De Matrícula E/ou Matrícula Fora Do Prazo No Calendário Académico.", "Matricula nao pode ser realizada, pois nao foram encontrados itens de matricula e/ou matricula fora do prazo no Calendario Academico." )
		#define STR0160 If( cPaisLoc $ "ANG|PTG", "O utilizador não possui autorização para realizar esta matrícula fora do prazo.", "O usuario nao possui autorizacao para realizar essa matricula fora do prazo." )
		#define STR0161 "Modalidade"
		#define STR0162 If( cPaisLoc $ "ANG|PTG", "Subturma", "Sub Turma" )
		#define STR0163 If( cPaisLoc $ "ANG|PTG", "Exclusão de disciplina não pode ser realizada, pois a data está fora do calendário de disciplina.", "Exclusao de disciplina nao pode ser realizada, pois a data esta  fora do calendario de disciplina." )
		#define STR0164 If( cPaisLoc $ "ANG|PTG", "Não existe requerimento disponível para a exclusão da disciplina.", "Nao existe requerimento disponivel para a Exclusão da disciplina." )
		#define STR0165 If( cPaisLoc $ "ANG|PTG", "Aluno não solicitou requerimento para a exclusão da disciplina.", "Aluno nao solicitou requerimento para a Exclusao da disciplina." )
		#define STR0166 If( cPaisLoc $ "ANG|PTG", "Prazo para exclusão já ultrapassado.", "Prazo para Exclusao ja ultrapassado." )
		#define STR0167 If( cPaisLoc $ "ANG|PTG", "Exclusão Da Disciplina Não Pode Ser Realizada, Pois Não Foram Encontrados Itens De Exclusão De Disciplinas No Calendário Académico.", "Exclusao da disciplina nao pode ser realizada, pois nao foram encontrados itens de exclusao de disciplinas no Calendario Academico." )
		#define STR0168 If( cPaisLoc $ "ANG|PTG", "Inclusão de disciplina não pode ser realizada, pois a data está  fora do calendário de inclusão de disciplina.", "Inclusao de disciplina nao pode ser realizada, pois a data esta  fora do calendario de inclusao de disciplina." )
		#define STR0169 If( cPaisLoc $ "ANG|PTG", "Não existe requerimento disponível para a inclusão da disciplina.", "Nao existe requerimento disponivel para a inclusao da disciplina." )
		#define STR0170 If( cPaisLoc $ "ANG|PTG", "Aluno não solicitou requerimento para a inclusão da disciplina", "Aluno nao solicitou requerimento para a inclusao da disciplina" )
		#define STR0171 If( cPaisLoc $ "ANG|PTG", "Prazo para inclusão de disciplinas já ultrapassado.", "Prazo para Inclusao de disciplinas ja ultrapassado." )
		#define STR0172 If( cPaisLoc $ "ANG|PTG", "Inclusão De Disciplina Não Pode Ser Realizada, Pois Não Foram Encontrados Itens De Inclusão De Disciplina No Calendário Académico.", "Inclusao de disciplina nao pode ser realizada, pois nao foram encontrados itens de inclusao de disciplina no Calendario Academico." )
		#define STR0173 "Deseja associar o curso "
		#define STR0174 If( cPaisLoc $ "ANG|PTG", " à bolsa de estudos ", " a Bolsa de Estudos " )
		#define STR0175 If( cPaisLoc $ "ANG|PTG", " versão ", " Versao " )
		#define STR0176 "Dispensa Simples"
		#define STR0177 If( cPaisLoc $ "ANG|PTG", "Dispensa Por Aproveitamento De Estudos", "Dispensa por Aproveitamento de Estudos" )
		#define STR0178 If( cPaisLoc $ "ANG|PTG", "Obrigatório Indicar A Nota Ou Elem. Critério Da Disciplina", "Obrigatorio informar a Nota ou Conceito da Disciplina" )
		#define STR0179 If( cPaisLoc $ "ANG|PTG", "A disciplina não foi dispensada !", "A Disciplina nao foi Dispensada !" )
		#define STR0180 If( cPaisLoc $ "ANG|PTG", "Carga Horária", "Carga Horaria" )
		#define STR0181 "Curso "
		#define STR0182 "Disciplina "
		#define STR0183 If( cPaisLoc $ "ANG|PTG", "Registo de disciplinas externas (outras instituições) ", "Cadastro de Disciplinas Externas (Outras Instituicoes) " )
		#define STR0184 If( cPaisLoc $ "ANG|PTG", "Cód. Disciplina", "Cod. Disciplina" )
		#define STR0185 "A situacäo só pode ser alterada para Adaptação desde que a disciplina seja de outra grade."
		#define STR0186 If( cPaisLoc $ "ANG|PTG", "Não será possível alterar o componente antes de efectuar a matrícula do aluno.", "Nao sera possivel alterar o Componente antes de efetivar a matricula do aluno." )
		#define STR0187 "Componentes"
		#define STR0188 "Planos de pagamento"
		#define STR0189 If( cPaisLoc $ "ANG|PTG", "Pl.pagto", "Pl.Pagto" )
		#define STR0190 "Este aluno não está matriculado."
		#define STR0191 "O parâmetro que libera a matrícula fora do prazo MV_ACCLMAT, "
		#define STR0192 If( cPaisLoc $ "ANG|PTG", "Está com o valor 2 = não. por isso a exclusão não é permitida", "esta com o valor 2 = Não. Com isso a exclusão não é permitia" )
		#define STR0193 If( cPaisLoc $ "ANG|PTG", "Utilizador não autorizado a realizar inclusão/exclusão de disciplina fora do prazo", "Usuário não autorizado a realizar inclusão/exclusão de disciplina fora do prazo" )
		#define STR0194 If( cPaisLoc $ "ANG|PTG", "Não será possível alterar o componente antes de efectuar a matrícula do aluno.", "Nao sera possivel alterar o Componente antes de efetivar a matricula do aluno." )
		#define STR0195 "Componentes"
		#define STR0196 "Compon."
		#define STR0197 If( cPaisLoc $ "ANG|PTG", "Manutenção De Componente Curricular", "Manutencao de Componente Curricular" )
		#define STR0198 If( cPaisLoc $ "ANG|PTG", "Activo", "Ativo" )
		#define STR0199 If( cPaisLoc $ "ANG|PTG", "1=sim", "1=Sim" )
		#define STR0200 If( cPaisLoc $ "ANG|PTG", "5=formado ", "5=Formado " )
		#define STR0201 "O aluno só poderá ser formado após cumprir todos os componentes!"
		#define STR0202 If( cPaisLoc $ "ANG|PTG", "Não é Permitido O Bloqueio De Disciplinas Individuais.", "Não é permitido o Trancamento de Disciplinas Individuais." )
		#define STR0203 If( cPaisLoc $ "ANG|PTG", "Aluno já matriculado nesse curso. por favor realizar promoção para esse curso!", "Aluno já matriculado nesse curso. Favor realizar promoção para esse curso!" )
		#define STR0204 "Aluno não alocado"
		#define STR0205 "Matrícula conforme grade cur.?"
		#define STR0206 "Aviso"
		#define STR0207 If( cPaisLoc $ "ANG|PTG", "O valor para reembolso da disciplina é de € ", "O valor para abatimento da disciplina é de R$ " )
		#define STR0208 If( cPaisLoc $ "ANG|PTG", ". confirma o reembolso nos títulos de matrícula e mensalidade do aluno?", ". Confirma o abatimento nos títulos de matrícula e mensalidade do aluno?" )
		#define STR0209 If( cPaisLoc $ "ANG|PTG", "Valor de bolsa maior que o valor da parcela (€ ", "Valor de bolsa maior que o valor da parcela (R$ " )
		#define STR0210 If( cPaisLoc $ "ANG|PTG", "). insira um valor menor.", "). Insira um valor menor." )
		#define STR0211 "O valor da bolsa não pode ser negativo"
		#define STR0212 If( cPaisLoc $ "ANG|PTG", "Valor da bolsa não pode ser maior que o valor do título.", "Valor da bolsa não pode ser maior que o valor do titulo." )
		#define STR0213 "Marca todas as disciplinas"
		#define STR0214 "Marcar"
		#define STR0215 "Desmarca todas as disciplinas"
		#define STR0216 "Desmarcar"
		#define STR0217 "Aulas não desmarcadas"
		#define STR0218 "Dia da semana"
		#define STR0219 "Hora 1"
		#define STR0220 "Hora 2"
		#define STR0221 "Disciplina"
		#define STR0222 "Descrição"
		#define STR0223 "Motivo"
		#define STR0224 "A disciplina não pode ser alterada, pois a grade curricular do curso/período letivo não permite."
		#define STR0225 If( cPaisLoc $ "ANG|PTG", "A disciplina não pode ser desmarcada, pois e obrigatória.", "A disciplina não pode ser desmarcada, pois é obrigatória." )
		#define STR0226 "Aulas não marcadas"
		#define STR0227 "A disciplina não pode ser selecionada, pois foi dispensada."
		#define STR0228 If( cPaisLoc $ "ANG|PTG", "A disciplina já esta registada na grade curricular atual.", "A disciplina já está cadastrada na grade curricular atual." )
		#define STR0229 If( cPaisLoc $ "ANG|PTG", "Existe um conflito de horario com a grade curricular atual do aluno.", "Existe um conflito de horário com a grade curricular atual do aluno." )
		#define STR0230 If( cPaisLoc $ "ANG|PTG", "A disciplina já possui movimentação registada.", "A disciplina já possui movimentação cadastrada." )
		#define STR0231 "Existe título baixado referente à esta disciplina."
		#define STR0232 If( cPaisLoc $ "ANG|PTG", "O aluno já possui um  registo na formação ", "Aluno já possui uma matricula no curso " )
		#define STR0233 If( cPaisLoc $ "ANG|PTG", " com estado ", " com status " )
		#define STR0234 "Esta ação fará com que o aluno fique 'ATIVO' no curso e as disciplinas sejam atualizadas para 'CURSANDO'."
		#define STR0235 "Deseja continuar?"
		#define STR0236 "Atenção"
		#define STR0237 If( cPaisLoc $ "ANG|PTG", "Não é possível dispensar a disciplina.Favor matricular o aluno e seleccionar um plano de pagamento para que possa ser efectuado o cálculo/abatimento .", "Não é possível dispensar a disciplina.Favor matricular o aluno e selecionar um plano de pagamento para que possa ser efetuado o cálculo/abatimento ." )
		#define STR0238 If( cPaisLoc $ "ANG|PTG", "Ano Lectivo+Período", "Ano Letivo+Periodo" )
		#define STR0239 "Curso Vigente"
		#define STR0240 If( cPaisLoc $ "ANG|PTG", "Índice", "Indice" )
		#define STR0241 "Cancelar"
		#define STR0242 If( cPaisLoc $ "ANG|PTG", "Existe(m) disciplina(s) obrigatória(s) não regista(s) na grelha de aula", "Existe(m) disciplina(s) obrigatória(s) não cadastrada(s) na grade de aula" )
		#define STR0243 If( cPaisLoc $ "ANG|PTG", "Actividades", "Atividades" )
		#define STR0244 " Não é possivel alterar a situação da disciplina para: "
		#define STR0245 ". Utilize o requerimento"
		#define STR0246 "Aluno não foi matriculado no(s) período(s) anterior(es)."
	#endif
#endif
