#ifdef SPANISH
	#define STR0001 "Aprobacion de solicitud"
	#define STR0002 "¡Esta solicitud paso del proceso de aprobacion!"
	#define STR0003 "Solamente aprobadores pueden utilizar la rutina de aprobacion"
	#define STR0004 "¡Solamente aprobadores de nivel 1 pueden liberar la primera aprobacion!"
	#define STR0005 "¡Solamente aprobadores de nivel 2 pueden liberar la segunda aprobacion!"
	#define STR0006 "¡Usuario ("
	#define STR0007 ") no encontrado en el archivo de viajantes/aprobadores!"
	#define STR0008 "¡Esta solicitud fue aprobada por el aprobador 1!"
	#define STR0009 "¡Esta solicitud fue reprobada por el aprobador 1!"
	#define STR0010 "El aprobador 1 aun no aprobo esta solicitud. Operacion bloqueada."
	#define STR0011 "Verifique si la solicitud se envio para aprobacion y si ya fue aprobada por el Aprobador 1!"
	#define STR0012 "¡Esta solicitud fue aprobada por el aprobador 2!"
	#define STR0013 "¡Esta solicitud fue reprobada por el aprobador 2!"
	#define STR0014 "Solicitud de Viaje  -  "
	#define STR0015 "Solicitante / Pais"
	#define STR0016 "Antecipaciona"
	#define STR0017 "Fecha da Emision"
	#define STR0018 "1-Administrativa"
	#define STR0019 "2-Viaje"
	#define STR0020 "Gasto"
	#define STR0021 "1-Anticipo"
	#define STR0022 "2-Reembolso"
	#define STR0023 "Tipo de la Solicitud"
	#define STR0024 "Colaborador"
	#define STR0025 "Nombre"
	#define STR0026 "Aprobador I   "
	#define STR0027 "Aprobador II"
	#define STR0028 "Empresa / Cliente"
	#define STR0029 "Lugar de Viaje"
	#define STR0030 "Motivo"
	#define STR0031 "Motivo del Viaje"
	#define STR0032 "Observaciones"
	#define STR0033 "Observaciones Generales"
	#define STR0034 "Periodo"
	#define STR0035 "a"
	#define STR0036 "Nº Cheques Hospedaje"
	#define STR0037 "Nº Estadias"
	#define STR0038 "Nº Vuelo Ida"
	#define STR0039 "Hora"
	#define STR0040 "Trans/Cia"
	#define STR0041 "Nº Vuelo Ret"
	#define STR0042 "Cliente"
	#define STR0043 "No Factura"
	#define STR0044 "Franquicia"
	#define STR0045 "Ok"
	#define STR0046 "Anticipo"
	#define STR0047 "SI-Anticipo"
	#define STR0048 "NO-Anticipo"
	#define STR0049 "Pasaje"
	#define STR0050 "SI-Pasaje Aerea"
	#define STR0051 "NO-Pasaje Aerea"
	#define STR0052 "Hospedaje"
	#define STR0053 "SI-Hospedaje"
	#define STR0054 "NO-Hospedaje"
	#define STR0055 "Valor R$"
	#define STR0056 "Valor US$"
	#define STR0057 "Obs."
	#define STR0058 "Banco"
	#define STR0059 "Ag."
	#define STR0060 "Cuenta"
	#define STR0061 "Hotel"
	#define STR0062 "Solicitado por"
	#define STR0063 "Aprobado por "
	#define STR0064 "Reprobado por"
	#define STR0065 "Solicitante Depto Viaje"
	#define STR0066 "Reprobado Depto Financiero"
	#define STR0067 "Aprobador Depto Financiero"
	#define STR0068 "Solicitado a las "
	#define STR0069 "Aprobado a las  "
	#define STR0070 "Reprobado a las "
	#define STR0071 "Solicitud Depto Viaje a las"
	#define STR0072 "Reprobado Depto Financiero a las"
	#define STR0073 "Aprobado Depto Financiero a las"
	#define STR0074 "Aprobar"
	#define STR0075 "¿Desea aprobar la solicitud?"
	#define STR0076 "SI"
	#define STR0077 "NO"
	#define STR0078 "Reprobar"
	#define STR0079 "¿Desea reprobar la solicitud?"
	#define STR0080 "Colaborador no tiene permiso para aprobacion/reprobacion"
#else
	#ifdef ENGLISH
		#define STR0001 "Request Approval"
		#define STR0002 "This request is no longer in approval request!"
		#define STR0003 "Only approvers can use approval routine"
		#define STR0004 "Only approvers level 1 can release the first approval!"
		#define STR0005 "Only approvers level 2 can release the second approval!"
		#define STR0006 "This user ("
		#define STR0007 ") was not found in Travelers/Approvers file."
		#define STR0008 "This request was already approved by approver 1!"
		#define STR0009 "This request was failed by approver 1!"
		#define STR0010 "Approver 1 did not approve this request yet. Operation blocked."
		#define STR0011 "Check if the request was sent for approval and if it was already approved by Approver 1!"
		#define STR0012 "This request was already approved by approver 2!"
		#define STR0013 "This request was denied by approver 2!"
		#define STR0014 "Trip Request -   "
		#define STR0015 "Requestor / Country"
		#define STR0016 "Antecedence"
		#define STR0017 "Issue Date"
		#define STR0018 "1-Administrative"
		#define STR0019 "2-Trip"
		#define STR0020 "Expense"
		#define STR0021 "1-Advance"
		#define STR0022 "2-Reimbursement"
		#define STR0023 "Request Type"
		#define STR0024 "Employee"
		#define STR0025 "Name"
		#define STR0026 "Approver I   "
		#define STR0027 "Approver II"
		#define STR0028 "Company / Customer"
		#define STR0029 "Trip Location"
		#define STR0030 "Reason"
		#define STR0031 "Reason for the Trip"
		#define STR0032 "Notes"
		#define STR0033 "General Comments"
		#define STR0034 "Period"
		#define STR0035 "to"
		#define STR0036 "No. Accommodation Checks"
		#define STR0037 "No. Stays"
		#define STR0038 "Flight No. - Departure"
		#define STR0039 "Time"
		#define STR0040 "Trans/Company"
		#define STR0041 "Flight No. - Return"
		#define STR0042 "Customer"
		#define STR0043 "No Billing"
		#define STR0044 "Franchise"
		#define STR0045 "OK"
		#define STR0046 "Advance"
		#define STR0047 "YES-Advance"
		#define STR0048 "NO-Advance"
		#define STR0049 "Ticket"
		#define STR0050 "YES - Airline Ticket"
		#define STR0051 "NO - Airline Ticket"
		#define STR0052 "Accommodation"
		#define STR0053 "YES - Accommodation"
		#define STR0054 "NO - Accommodation"
		#define STR0055 "Value R$"
		#define STR0056 "Value US$"
		#define STR0057 "Note"
		#define STR0058 "Bank"
		#define STR0059 "Branch:"
		#define STR0060 "Account"
		#define STR0061 "Hotel"
		#define STR0062 "Requested by"
		#define STR0063 "Approved by "
		#define STR0064 "Failed by"
		#define STR0065 "Requestor Trip Department"
		#define STR0066 "Failed Financial Department"
		#define STR0067 "Approver Financial Department"
		#define STR0068 "Request at "
		#define STR0069 "Approved at  "
		#define STR0070 "Denied at "
		#define STR0071 "Traveling Department requested at"
		#define STR0072 "Financial Department denied at"
		#define STR0073 "Financial Department approved at"
		#define STR0074 "Approve"
		#define STR0075 "Do you wish to approve request?"
		#define STR0076 "YES"
		#define STR0077 "NO"
		#define STR0078 "Refusal"
		#define STR0079 "Do you wish to deny this request?"
		#define STR0080 "Collaborator does not have permission to approve/deny"
	#else
		#define STR0001 "Aprovação de solicitação"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Esta solicitação já passou do proccesso de aprovação!", "Esta solicitação já passou do processo de aprovação!" )
		#define STR0003 "Somente aprovadores podem utilizar a rotina de aprovação"
		#define STR0004 "Somente aprovadores do nível 1 podem liberar a primeira aprovação!"
		#define STR0005 "Somente aprovadores do nível 2 podem liberar a segunda aprovação!"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Este usuário (", "Este usuario (" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", ") não foi encontrado no registo de viajantes/aprovadores!", ") não foi encontrado no cadastro de viajantes/aprovadores!" )
		#define STR0008 "Esta solicitação já foi aprovada pelo aprovador 1!"
		#define STR0009 "Esta solicitação foi reprovada pelo aprovador 1!"
		#define STR0010 "O aprovador 1 ainda não aprovou esta solicitação. Operação bloqueada."
		#define STR0011 "Verifique se a solicitação foi enviada para aprovação e se já foi aprovada pelo Aprovador 1!"
		#define STR0012 "Esta solicitação já foi aprovada pelo aprovador 2!"
		#define STR0013 "Esta solicitação foi reprovada pelo aprovador 2!"
		#define STR0014 "Solicitação de Viagem  -  "
		#define STR0015 "Solicitante / País"
		#define STR0016 "Antecedência"
		#define STR0017 "Data da Emissão"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "1-Administractiva", "1-Administrativa" )
		#define STR0019 "2-Viagem"
		#define STR0020 "Despesa"
		#define STR0021 "1-Adiantamento"
		#define STR0022 "2-Reembolso"
		#define STR0023 "Tipo da Solicitação"
		#define STR0024 "Colaborador"
		#define STR0025 "Nome"
		#define STR0026 "Aprovador I   "
		#define STR0027 "Aprovador II"
		#define STR0028 "Empresa / Cliente"
		#define STR0029 "Local da Viagem"
		#define STR0030 "Motivo"
		#define STR0031 "Motivo da Viagem"
		#define STR0032 "Observações"
		#define STR0033 "Observações Gerais"
		#define STR0034 "Período"
		#define STR0035 "à"
		#define STR0036 "Nr. Cheques Hospedagem"
		#define STR0037 "Nr. Estadias"
		#define STR0038 "N.Voo Ida"
		#define STR0039 "Hora"
		#define STR0040 "Trans/Cia"
		#define STR0041 "N.Voo Ret"
		#define STR0042 "Cliente"
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Não Factura", "Não Fatura" )
		#define STR0044 "Franquia"
		#define STR0045 "Ok"
		#define STR0046 "Adiantamento"
		#define STR0047 "SIM-Adiantamento"
		#define STR0048 "NÃO-Adiantamento"
		#define STR0049 "Passagem"
		#define STR0050 "SIM-Passagem Aérea"
		#define STR0051 "NÃO-Passagem Aérea"
		#define STR0052 "Hospedagem"
		#define STR0053 "SIM-Hospedagem"
		#define STR0054 "NÃO-Hospedagem"
		#define STR0055 "Valor R$"
		#define STR0056 "Valor US$"
		#define STR0057 "Obs."
		#define STR0058 "Banco"
		#define STR0059 "Ag."
		#define STR0060 "Conta"
		#define STR0061 "Hotel"
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "Soliccitado por", "Solicitado por" )
		#define STR0063 "Aprovado por "
		#define STR0064 "Reprovado por"
		#define STR0065 "Solicitante Depto Viagem"
		#define STR0066 "Reprovado Depto Financeiro"
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Aprovador depto financeiro", "Aprovador Depto Financeiro" )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Soliccitado às ", "Solicitado às " )
		#define STR0069 "Aprovado às  "
		#define STR0070 "Reprovado às "
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Soliccitado Depto Viagem às", "Solicitado Depto Viagem às" )
		#define STR0072 "Reprovado Depto Financeiro às"
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Aprovado depto financeiro às", "Aprovado Depto Financeiro às" )
		#define STR0074 "Aprovar"
		#define STR0075 "Deseja aprovar a solicitação?"
		#define STR0076 "SIM"
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "NÃO", "NAO" )
		#define STR0078 "Reprovar"
		#define STR0079 "Deseja reprovar a solicitação?"
		#define STR0080 "Colaborador não possui permissão para aprovação/reprovação"
	#endif
#endif
