#ifdef SPANISH
	#define STR0001 "AtuSX - Gerenciador de Base de Dados"
	#define STR0002 "Salir"
	#define STR0003 "Historial"
	#define STR0004 "Diccionario de Datos"
	#define STR0005 "Grupo de Campos"
	#define STR0006 "Tablas Genericas"
	#define STR0007 "Parametros"
	#define STR0008 "Preguntas"
	#define STR0009 "Consultas estándar"
	#define STR0010 "Mantenimiento de CHs"
	#define STR0011 "Diccionario de Datos"
	#define STR0012 "Incluir"
	#define STR0013 "Visualizar"
	#define STR0014 "Editar"
	#define STR0015 "Borrar"
	#define STR0016 "Importacion"
	#define STR0017 "Grupo de Campos"
	#define STR0018 "Incluir"
	#define STR0019 "Visualizar"
	#define STR0020 "Editar"
	#define STR0021 "Borrar"
	#define STR0022 "Importacion"
	#define STR0023 "Tablas Genericas"
	#define STR0024 "Incluir"
	#define STR0025 "Visualizar"
	#define STR0026 "Editar"
	#define STR0027 "Borrar"
	#define STR0028 "Importacion"
	#define STR0029 "Parametros"
	#define STR0030 "Incluir"
	#define STR0031 "Visualizar"
	#define STR0032 "Editar"
	#define STR0033 "Borrar"
	#define STR0034 "Importacion"
	#define STR0035 "Preguntas"
	#define STR0036 "Incluir"
	#define STR0037 "Visualizar"
	#define STR0038 "Editar"
	#define STR0039 "Borrar"
	#define STR0040 "Importacion"
	#define STR0041 "Consultas estándar"
	#define STR0042 "Incluir"
	#define STR0043 "Visualizar"
	#define STR0044 "Editar"
	#define STR0045 "Borrar"
	#define STR0046 "Distribuir"
	#define STR0047 "Importacion"
	#define STR0048 "Mantenimiento de CHs"
	#define STR0049 "Incluir"
	#define STR0050 "Visualizar"
	#define STR0051 "Editar"
	#define STR0052 "Borrar"
	#define STR0053 "Generar Ch."
	#define STR0054 "Replicar"
	#define STR0055 "Aguarde, cargando los proyectos..."
	#define STR0056 "¡Uso de Comillas no permitido en la busqueda !"
	#define STR0057 "¡Item no encontrado !"
	#define STR0058 "Atencion"
	#define STR0059 "editar"
	#define STR0060 "Borrar"
	#define STR0061 "Distribuir"
	#define STR0062 "copiar"
	#define STR0063 "¡Atencion!"
	#define STR0064 "No es posible "
	#define STR0065 " este registro pues existe una version mas actual del mismo en el proyecto :"
	#define STR0066 "¡Atencion!"
	#define STR0067 "No es posible "
	#define STR0068 " este registro pues existe una version mas actual del mismo en el paquete:"
	#define STR0069 "¡Atencion!"
	#define STR0070 "Este registro puede visualizarse, pero no es el registro activo. Existe una version mas actual del mismo en el proyecto :"
	#define STR0071 "¡Atencion!"
	#define STR0072 "Este registro puede visualizarse, pero no es el registro activo. Existe una version mas actual del mismo en el paquete :"
	#define STR0073 "¡Atencion!"
	#define STR0074 "¡No es posible borrar! La version en uso y la version del registro son divergentes."
	#define STR0075 "Crear Include por el fuente"
	#define STR0076 "Componentes del paquete"
	#define STR0077 "Rastrear incorporaciones"
	#define STR0078 "Asuntos pendientes de aprobación"
	#define STR0079 "Este ítem tiene asuntos pendientes de aprobación DBA."
	#define STR0080 "Este ítem tiene asuntos pendientes de aprobación de sistemas."
	#define STR0081 "Este ítem no tiene asuntos pendientes de aprobación."
#else
	#ifdef ENGLISH
		#define STR0001 "AtuSX - Database Manager"
		#define STR0002 "Exit"
		#define STR0003 "History"
		#define STR0004 "Data Dictionary"
		#define STR0005 "Field Group"
		#define STR0006 "Generic Tables"
		#define STR0007 "Parameters"
		#define STR0008 "Questions"
		#define STR0009 "Default Queries"
		#define STR0010 "CH Maintenance"
		#define STR0011 "Data Dictionary"
		#define STR0012 "Add"
		#define STR0013 "View"
		#define STR0014 "Edit"
		#define STR0015 "Delete"
		#define STR0016 "Import"
		#define STR0017 "Field Group"
		#define STR0018 "Add"
		#define STR0019 "View"
		#define STR0020 "Edit"
		#define STR0021 "Delete"
		#define STR0022 "Import"
		#define STR0023 "Generic Tables"
		#define STR0024 "Add"
		#define STR0025 "View"
		#define STR0026 "Edit"
		#define STR0027 "Delete"
		#define STR0028 "Import"
		#define STR0029 "Parameters"
		#define STR0030 "Add"
		#define STR0031 "View"
		#define STR0032 "Edit"
		#define STR0033 "Delete"
		#define STR0034 "Import"
		#define STR0035 "Questions"
		#define STR0036 "Add"
		#define STR0037 "View"
		#define STR0038 "Edit"
		#define STR0039 "Delete"
		#define STR0040 "Import"
		#define STR0041 "Default Queries"
		#define STR0042 "Add"
		#define STR0043 "View"
		#define STR0044 "Edit"
		#define STR0045 "Delete"
		#define STR0046 "Distribute"
		#define STR0047 "Import"
		#define STR0048 "CH Maintenance"
		#define STR0049 "Add"
		#define STR0050 "View"
		#define STR0051 "Edit"
		#define STR0052 "Delete"
		#define STR0053 "Generate CH."
		#define STR0054 "Replicate"
		#define STR0055 "Wait, loading projects..."
		#define STR0056 "Inverted commas are not allowed in query!"
		#define STR0057 "Item not found!"
		#define STR0058 "Attention"
		#define STR0059 "edit"
		#define STR0060 "delete"
		#define STR0061 "distribute"
		#define STR0062 "copy"
		#define STR0063 "Attention!"
		#define STR0064 "Not possible to "
		#define STR0065 " this record because there is a newer version of it in the project:"
		#define STR0066 "Attention!"
		#define STR0067 "Not possible to "
		#define STR0068 " this record because there is a newer version of it in the package:"
		#define STR0069 "Attention!"
		#define STR0070 "This record can be viewed, but it is not the active record. There is a newer version of it in the project:"
		#define STR0071 "Attention!"
		#define STR0072 "This record can be viewed, but it is not the active record. There is a newer version of it in the package:"
		#define STR0073 "Attention!"
		#define STR0074 "Editing not possible! The version in use and the version of the record a different."
		#define STR0075 "Create Include through source"
		#define STR0076 "Package components"
		#define STR0077 "Track embeddings"
		#define STR0078 "Pending approval"
		#define STR0079 "This item has pending DBA approval"
		#define STR0080 "This item has pending systems approval"
		#define STR0081 "This item does not have pending approval"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "AtuSX - Administrador de Base de Dados", "AtuSX - Gestão de Base de Dados" )
		#define STR0002 "Sair"
		#define STR0003 "Histórico"
		#define STR0004 "Dicionário de Dados"
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Grupo de Campos", "Grupo de Campo" )
		#define STR0006 "Tabelas Genéricas"
		#define STR0007 "Parâmetros"
		#define STR0008 "Perguntas"
		#define STR0009 "Consultas Padrão"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Manutenção de CHs", "Manutenção CH" )
		#define STR0011 "Dicionário de Dados"
		#define STR0012 "Incluir"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Visualizar", "Visão" )
		#define STR0014 "Editar"
		#define STR0015 "Excluir"
		#define STR0016 "Importação"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Grupo de Campos", "Grupo de Campo" )
		#define STR0018 "Incluir"
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Visualizar", "Visão" )
		#define STR0020 "Editar"
		#define STR0021 "Excluir"
		#define STR0022 "Importação"
		#define STR0023 "Tabelas Genéricas"
		#define STR0024 "Incluir"
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Visualizar", "Visão" )
		#define STR0026 "Editar"
		#define STR0027 "Excluir"
		#define STR0028 "Importação"
		#define STR0029 "Parâmetros"
		#define STR0030 "Incluir"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Visualizar", "Visão" )
		#define STR0032 "Editar"
		#define STR0033 "Excluir"
		#define STR0034 "Importação"
		#define STR0035 "Perguntas"
		#define STR0036 "Incluir"
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Visualizar", "Visão" )
		#define STR0038 "Editar"
		#define STR0039 "Excluir"
		#define STR0040 "Importação"
		#define STR0041 "Consultas Padrão"
		#define STR0042 "Incluir"
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Visualizar", "Visão" )
		#define STR0044 "Editar"
		#define STR0045 "Excluir"
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Distribuir", "Distribuição" )
		#define STR0047 "Importação"
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Manutenção de CHs", "Manutenção CH" )
		#define STR0049 "Incluir"
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Visualizar", "Visão" )
		#define STR0051 "Editar"
		#define STR0052 "Excluir"
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Gerar Ch.", "Gerar CH" )
		#define STR0054 "Replicar"
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Aguarde, a carregar os projectos...", "Espere, carregando projetos..." )
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "Uso de aspas não permitido na pesquisa.", "Aspas não são permitidas na consulta!" )
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Item não encontrado.", "Item não encontrado!" )
		#define STR0058 "Atenção"
		#define STR0059 "editar"
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "excluir", "deletar" )
		#define STR0061 "distribuir"
		#define STR0062 "copiar"
		#define STR0063 "Atenção!"
		#define STR0064 "Não é possível "
		#define STR0065 If( cPaisLoc $ "ANG|PTG", " este registo, pois existe uma versão mais actual do mesmo no projecto:", " neste registro porque há uma nova versão disso no projeto:" )
		#define STR0066 "Atenção!"
		#define STR0067 "Não é possível "
		#define STR0068 If( cPaisLoc $ "ANG|PTG", " este registo, pois existe uma versão mais actual do mesmo no pacote:", " neste registro porque há uma nova versão disso no pacote:" )
		#define STR0069 "Atenção!"
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Este registo pode ser visualizado, mas não é o registo activo. Existe uma versão mais actual do mesmo no projecto:", "Este registro pode ser visualizado, mas não é um registro ativo. Há uma nova versão disso no projeto." )
		#define STR0071 "Atenção!"
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Este registo pode ser visualizado, mas não é o registo activo. Existe uma versão mais actual do mesmo no pacote:", "Este registro pode ser visualizado, mas não é um registro ativo. Há uma nova versão disso no pacote." )
		#define STR0073 "Atenção!"
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Não e possível editar. A versão em uso e versão do registo são divergentes.", "Alteração não permitida! A versão em uso e a versão do registro são diferentes!" )
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Criar Include pelo fonte", "Criar Include através da fonte" )
		#define STR0076 "Componentes do pacote"
		#define STR0077 "Rastrear incorporações"
		#define STR0078 "Pendências de aprovação"
		#define STR0079 "Este item possui pendências de aprovação DBA."
		#define STR0080 "Este item possui pendências de aprovação sistemas."
		#define STR0081 "Este item não possui pendências de aprovação."
	#endif
#endif
