#ifdef SPANISH
	#define STR0001 "Archivo de templates de campos"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Imprimir"
	#define STR0007 "Copiar"
	#define STR0008 "Items de templates"
	#define STR0009 "Datos generales"
	#define STR0010 "Distribucion por pais"
	#define STR0011 "Obligat (Utilizado)"
	#define STR0012 "Campos que utilizan"
	#define STR0013 "Este registro ya existe."
	#define STR0014 "Verifique la base de datos."
	#define STR0015 "Atencion"
	#define STR0016 "Inconsistencia en la linea "
	#define STR0017 "Linea "
	#define STR0018 "Este template esta siendo utilizado."
	#define STR0019 "Primero, borre los vinculos a este template."
	#define STR0020 "Complete el campo pais antes de informar la consulta estandar"
	#define STR0021 "No es posible utilizar esta consulta, pues se utilizo el pais 'ALL' en el item, pero la consulta no esta distribuida entre todos los paises."
	#define STR0022 "No es posible utilizar esta consulta, pues se utilizo el pais 'ALL' en el item, pero la consulta no esta distribuida entre todos los paises."
	#define STR0023 "No es posible definir um item 'ALL' en conjunto con otro pais."
	#define STR0024 "Codigo"
	#define STR0025 "Descripcion"
	#define STR0026 "Ninguno"
	#define STR0027 "Campo"
	#define STR0028 "Confirmar"
	#define STR0029 "Salir"
	#define STR0030 "Visualizar"
	#define STR0031 "Opcion invalida en la inclusion."
	#define STR0032 "Campos que utilizan el template "
	#define STR0033 "Consulta templates de campos"
	#define STR0034 "Campos"
#else
	#ifdef ENGLISH
		#define STR0001 "Register of field templates"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Print"
		#define STR0007 "Copy"
		#define STR0008 "Templates Items"
		#define STR0009 "General data"
		#define STR0010 "Distribution per country"
		#define STR0011 "Mandat (Used)"
		#define STR0012 "Fields that use"
		#define STR0013 "This register already exists."
		#define STR0014 "Check database."
		#define STR0015 "Attention!"
		#define STR0016 "Inconsistency in row "
		#define STR0017 "Row "
		#define STR0018 "This template is being used."
		#define STR0019 "First, delete the bindings to this template."
		#define STR0020 "Fill out the field country before indicating the standard search!"
		#define STR0021 "This search cannot be used because the the country 'ALL' was used in the item, but the search is not distributed for all the countries!"
		#define STR0022 "This table cannot be used because the the country 'ALL' was used in the item, but the search is not distributed for all the countries!"
		#define STR0023 "An 'ALL' item cannot be defined with another country!"
		#define STR0024 "Code"
		#define STR0025 "Description"
		#define STR0026 "None"
		#define STR0027 "Field"
		#define STR0028 "Confirm"
		#define STR0029 "Quit"
		#define STR0030 "View"
		#define STR0031 "Invalid option in inclusion!"
		#define STR0032 "Fields that use the template "
		#define STR0033 "Field Templates Search"
		#define STR0034 "Fields"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Registo de templates de campos", "Cadastro de templates de campos" )
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Imprimir"
		#define STR0007 "Copiar"
		#define STR0008 "Itens de Templates"
		#define STR0009 "Dados gerais"
		#define STR0010 "Distribuição por país"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Obrigat.(Usado)", "Obrigat (Usado)" )
		#define STR0012 "Campos que utilizam"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Este registo já existe.", "Já existe este registro." )
		#define STR0014 "Verifique a base de dados."
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Atenção!", "Atenção !" )
		#define STR0016 "Inconsistência na linha "
		#define STR0017 "Linha "
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Este template está a ser utilizado.", "Este template está sendo utilizado." )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Primeiro, exclua as amarrações deste template.", "Exclua primeiro as amarrações a este template." )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Efectue o preenchimento do campo país antes de informar a consulta padrão.", "Efetue o preenchimento do campo país antes de informar a consulta padrão !" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Não é possível utilizar esta consulta, pois foi usado o país 'ALL' no item, mas a consulta não está distribuída para todos os países.", "Não é possível utilizar esta consulta pois foi utilizado o país 'ALL' no item, mas a consulta não está distribuída para todos os países!" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Não é possível utilizar esta tabela (SX5), pois foi usado o país 'ALL' no item, mas a tabela não está distribuída para todos os países.", "Não é possível utilizar esta tabela (SX5) pois foi utilizado o país 'ALL' no item, mas a tabela não está distribuída para todos os países!" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Não é possível definir um item 'ALL' em conjunto com outro país.", "Não é possível definir um item 'ALL' em conjunto com outro país !" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Código", "Codigo" )
		#define STR0025 "Descrição"
		#define STR0026 "Nenhum"
		#define STR0027 "Campo"
		#define STR0028 "Confirmar"
		#define STR0029 "Abandonar"
		#define STR0030 "Visualizar"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Opção inválida na inclusão.", "Opção inválida na inclusão !" )
		#define STR0032 "Campos que utilizam o template "
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Consulta templates de campos", "Consulta Templates de campos" )
		#define STR0034 "Campos"
	#endif
#endif
