#ifdef SPANISH
	#define STR0001 'Existen activos de gestión de Costo/Provisión que no se están considerando para los saldos de Costo/Provisión.'
	#define STR0002 '¿Desea continuar aun así?'
	#define STR0003 'Activos de Costo/Provisión'
	#define STR0004 "Esta modificación implicaré en la pérdida de los datos digitados. ¿Desea continuar?"
	#define STR0005 "Presentación"
	#define STR0006 "Codigo base:"
	#define STR0007 "Ítem:"
	#define STR0008 "Placa:"
	#define STR0009 "Descripción:"
	#define STR0010 "Selección de los bienes"
	#define STR0011 "Conversión de métodos de depreciación"
	#define STR0012 "Procesando conversión..."
	#define STR0013 "Procesando anulación de la conversión..."
	#define STR0014 "Parámetros"
	#define STR0015 "De Código del bien"
	#define STR0016 "A Código del bien"
	#define STR0017 "De Ítem:"
	#define STR0018 "A Ítem"
	#define STR0019 "De Grupo"
	#define STR0020 "A Grupo"
	#define STR0021 "De Fecha de adquisición"
	#define STR0022 "A Fecha de adquisición"
	#define STR0023 "Bloquea/Desbloq"
	#define STR0024 "Desbloqueando"
	#define STR0025 "Bloqueando"
	#define STR0026 "Espere"
	#define STR0027 "Activo"
	#define STR0028 "No se encontraron bienes de acuerdo con los parámetros informados"
	#define STR0029 "o los bienes no han podido desbloquearse."
	#define STR0030 "o los bienes no han podido bloquearse."
	#define STR0031 "Ningún bien fue desbloqueado."
	#define STR0032 "Ningún bien fue bloqueado."
	#define STR0033 "Los siguientes bienes fueron desbloqueados:"
	#define STR0034 "Los siguientes bienes fueron bloqueados:"
	#define STR0035 "Bloqueo / Desbloqueo de bienes"
	#define STR0036 " Los siguientes activos no se hicieron efectivo porque están en proceso de inventario. "
	#define STR0037 "Los siguientes activos no se hicieron efectivo porque los locales registrados están bloqueados "
	#define STR0038 "Inicio"
	#define STR0039 "Log de procesamiento de Imp. CSV"
	#define STR0040 "Archivo para importación"
	#define STR0041 "Borra clasificación anterior"
	#define STR0042 "Archivos .CSV |*.CSV"
	#define STR0043 "Sí"
	#define STR0044 "No"
	#define STR0045 "Importar Clasificación activo"
	#define STR0046 "Clasificación del código "
	#define STR0047 "Ítem:"
	#define STR0048 'Crea automático'
	#define STR0049 'Número de bienes'
	#define STR0050 "La Fecha inicial de depreciación no puede ser inferior que la fecha del último cálculo = "
	#define STR0051 " Los siguientes activos no se hicieron efectivo porque los locales registrados están bloqueados "
	#define STR0052 "Los siguientes activos no se hicieron efectivo porque están en proceso de inventario."
	#define STR0053 "Los siguientes bienes fueron bloqueados"
	#define STR0054 "Desbloqueados:"
	#define STR0055 "Bloqueo / Desbloqueo de bienes"
	#define STR0056 "Laudo"
	#define STR0057 " Conversión de método de depreciación "
	#define STR0058 "Anulación de conversión de método de depreciación"
	#define STR0059 "Buscar"
	#define STR0060 "Visualizar"
	#define STR0061 "Incluir"
	#define STR0062 "Modificar"
	#define STR0063 "Borrar"
	#define STR0064 "Borrar lote"
	#define STR0065 "Copia"
	#define STR0066 "Conocimiento"
	#define STR0067 "Leyenda"
	#define STR0068 "Convierte método"
	#define STR0069 "Anul.Método"
	#define STR0070 "Convierte Dep."
	#define STR0071 "Anula Dep."
	#define STR0072 "Bloquear/Desb"
	#define STR0073 "Contr. Terceros"
	#define STR0074 "Contr.en Terceros"
	#define STR0075 "Import. Clasificación"
	#define STR0076 "Log Proc"
	#define STR0077 "Confirmar"
	#define STR0078 "Margen de gestión"
	#define STR0079 "Cálculo AVP"
	#define STR0080 "Múltiples"
	#define STR0081 "Prorrateo"
	#define STR0082 "Responsables"
	#define STR0083 "Contr.Terceros"
	#define STR0084 "Cont.en Terceros"
	#define STR0085 "Actualizacion de activos fijos"
	#define STR0086 "Saldo y valores"
	#define STR0087 'Desbloquea'
	#define STR0088 'Bloquea'
	#define STR0089 "Tracker contable"
	#define STR0090 "¿Confirma modificacion?"
	#define STR0091 "Atencion"
	#define STR0092 'Actualizacion de activos fijos'
	#define STR0093 'Desbloquea'
	#define STR0094 "Bloquea"
	#define STR0095 'Solo los tipos'
	#define STR0096 " pueden registrarse en conjunto con el tipo de activo "
	#define STR0097 "Control de terceros no disponible para este bien."
	#define STR0098 "Evaluar las configuraciones del campo Tipo de control."
	#define STR0099 "No existe control de terceros para este bien."
	#define STR0100 "Efectuar mantenimiento por el archivo de control de terceros."
	#define STR0101 "Control de terceros no disponible para este bien."
	#define STR0102 "Evaluar las configuraciones del campo Tipo de control."
	#define STR0103 "Control de bienes en terceros"
	#define STR0104 "Existe un control de terceros activo para este bien."
	#define STR0105 "Mantenimientos deben realizarse por el archivo de control de terceros."
	#define STR0106 "Opciones disponibles por el archivo del bien:"
	#define STR0107 "Visualizar"
	#define STR0108 "Salir"
	#define STR0109 "No existe control de terceros para este bien."
	#define STR0110 "Efectuar mantenimiento por el archivo de control de terceros."
	#define STR0111 "El bien tiene un CIAP asociado, ¿desea continuar el borrado?"
	#define STR0112 "Atención"
	#define STR0113 "Tipo de activo no es un tipo base"
	#define STR0114 "Generando fichas de activos..."
	#define STR0115 "La fecha de adquisición del bien es igual o inferior a la fecha de bloqueo de movimiento: "
	#define STR0116 'La modificación del campo "#1[Tipo deprec.]#" de la ampliación debe ocurrir por medio del tipo de activo "Depreciación fiscal".'
	#define STR0117 "La conversión del valor original en la Moneda 1 para las siguientes monedas, supera el tamaño máximo permitido: "
	#define STR0118 "La fecha de adquisición del bien es igual o inferior a la fecha de bloqueo de movimiento: "
	#define STR0119 'Bien planificado solamente podra borrarse por medio de reversión de la efectivización en la rutina de planificación de activo (ATFA310)'
	#define STR0120 "Informe una fecha prevista de ejecución superior a la fecha inicial AVP."
	#define STR0121 "No se digitó el valor del bien en la moneda legal."
	#define STR0122 "El campo Cuenta (N3_CCONTAB) no se completó."
	#define STR0123 "Informe por lo menos un valor del tipo 10 (Depreciación de gestión/Contable) para realizar el cálculo AVP."
	#define STR0124 "Informe correctamente los datos en la solapa 'AVP'."
	#define STR0125 "¡Es necesario registrar datos de tercero!"
	#define STR0126 "¡Es necesario registrar datos de bienes en tercero!"
	#define STR0127 "Por favor, marque un tipo de bien "
	#define STR0128 "Convirtiendo bien, espere"
	#define STR0129 "¿Calcula valor actual del bien?"
	#define STR0130 "¡El índice seleccionado esta bloqueado!"
	#define STR0131 "Este ítem no se puede borrar."
	#define STR0132 "Ítems de Tipo 10 solamente pueden borrarse si no existen ítems de Tipo 14"
	#define STR0133 "e ítems de Tipo 14 no pueden borrarse manualmente."
	#define STR0134 "Bien originado del proceso de transferencia. En la rutina de transferencia, utilice la opcion de anulación de transferencia."
	#define STR0135 "Calendario contable bloqueado. Verifique el proceso."
	#define STR0136 "El valor máximo de depreciación no puede ser superior al valor original en la moneda configurada en el parámetro MV_ATFMDMX "
	#define STR0137 "El activo está con el siguiente participante como responsable: "
	#define STR0138 " ¿Procede con la operación?"
	#define STR0139 "La fecha inicial de depreciación no puede modificarse para período igual o anterior al último cálculo de depreciación."
	#define STR0140 "La fecha inicial de depreciación no puede ser inferior a la fecha de adquisición del bien o de la fecha de adquisición del tipo de saldo."
	#define STR0141 "Fecha inicial de depreciación no puede ser inferior a la fecha de adquisición"
	#define STR0142 "¿Realmente desea cambiar el campo Tasa de depreciación?"
	#define STR0143 "¿Realmente desea actualizar el campo Período de depreciación anual?"
	#define STR0144 "Este campo no se utiliza por el método de depreciación seleccionado, el valor informado no se considerará."
	#define STR0145 "El campo "
	#define STR0146 " no se informó."
	#define STR0147 "En la grilla de Balances y valores existen uno o más ítems con un período de depreciación fuera del intervalo del grupo."
	#define STR0148 "El período de depreciación está fuera del intervalo del grupo de depreciación"
	#define STR0149 "Èñòîğèÿ"
	#define STR0150 "Êîíñåğâàöèÿ"
	#define STR0151 "Äåêîíñåğâàöèÿ"
	#define STR0152 " no informado."
	#define STR0153 "Informe el campo "
	#define STR0154 " existe en el sistema."
	#define STR0155 "Defina un nuevo código en el campo "
	#define STR0156 "Fecha de la depreciación no debe ser inferior a la fecha de adquisición del activo, digite una fecha mayor o igual a la fecha de adquisición"
	#define STR0157 'No es posible definir el activo como "Bloqueado por local" (N1_STATUS), sin informar un local bloqueado (N1_LOCAL).'
	#define STR0158 "Åñëè Òèï àìîğòèçàöèè (n3_tpdepr) ğàâåí 1, 2 èëè 6, ñòàâêà àìîğòèçàöèè (n3_perdepr) ÿâëÿåòñÿ îáÿçàòåëüíîé"
	#define STR0159 "Íåò âõîäÿùåé íàêëàäíîé äëÿ äàííîãî îñíîâíîãî ñğåäñòâà"
	#define STR0160 "Âõîä. íàêëàäíàÿ"
	#define STR0161 "Debe informar el Tipo de documento en el catálogo de proveedores."
	#define STR0162 "Êîëè÷åñòâî ÿâëÿåòñÿ îáÿçàòåëüíûì äëÿ íå ñïèñàííûõ îñíîâíûõ ñğåäñòâ"
	#define STR0163 "Este campo no puede modificarse."
	#define STR0164 "Si esta operación fuera inevitable, borre e incluya nuevamente el registro o utilice la rutina de transferencia."
	#define STR0165 "¿Modifica el valor original descontando la alícuota de PIS y COFINS?"
	#define STR0166 "Estatus utilizado solamente si estuviera Activo, incluso por Factura de entrada - N1_STATUS"
	#define STR0167 "El campo [Meses Cl.Pis] debe estar en cero para la condición de cálculo de PIS igual a (SÍ o NO)"
	#define STR0168 "Es obligatorio completar el campo [Meses Cl.Pis] con un valor válido, verifique el parámetro MV_ATFMAPR."
	#define STR0169 "Cuenta contable no informada a la empresa"
	#define STR0170 "Îñí. ñğ-âà "
	#define STR0171 "Ñîçäàíèå"
	#define STR0172 "Èçìåíåíèå"
	#define STR0173 "Ïî äàííîìó Îíñíîâíîìó ñğåäñòâó áûëè âûïîëíåíû îïåğàöèè. Óäàëåíèå íåâîçìîæíî."
	#define STR0174 "Óäàëåíèå âîçìîæíî òîëüêî â ñòàòóñå Çàïëàíèğîâàíî"
	#define STR0175 "Îñíîâíûå ñğåäñòâà è ÍÌÀ"
	#define STR0176 "Solicite al administrador ajustar el tamaño del campo en el diccionario de datos."
	#define STR0177 "Parámetro MV_ATFMOED configurado incorrectamente"
	#define STR0178 "Bien Tipo construcción solamente permite tipo de Activo 03"
	#define STR0179 "No es posible agregar una nueva línea en el componente de un bien en construcción"
	#define STR0180 "El Bien debe ser Tipo en construcción"
	#define STR0181 "Modifique el Tipo de activo a 03"
	#define STR0182 "Bien en construcción tiene vínculos. Borre los componentes para después borrar el bien"
	#define STR0183 "No es posible agregar una nueva línea en un bien en construcción"
	#define STR0184 "El componente debe tener CIAP"
	#define STR0185 "Seleccione con F3 un Bien en construcción para vincular. Solapa Bien en construcción"
#else
	#ifdef ENGLISH
		#define STR0001 'There are asset management Costs/Provisions that are not being considered in the balance of Costs/Provisions.'
		#define STR0002 'Do you want to proceed anyway?'
		#define STR0003 'Asset Costs/Provisions'
		#define STR0004 "This change implies loss of entered data, continue?"
		#define STR0005 "Presentation"
		#define STR0006 "Base Code:"
		#define STR0007 "Item:"
		#define STR0008 "Plate:"
		#define STR0009 "Description:"
		#define STR0010 "Asset Selection"
		#define STR0011 "Depreciation Method Conversion"
		#define STR0012 "Processing Conversion..."
		#define STR0013 "Processing Conversion Cancellation..."
		#define STR0014 "Parameters"
		#define STR0015 "From Asset Code"
		#define STR0016 "To Assets Code"
		#define STR0017 "From Item"
		#define STR0018 "To Item"
		#define STR0019 "From Group"
		#define STR0020 "To Group"
		#define STR0021 "From Acquisition Date"
		#define STR0022 "To Acquisition Date"
		#define STR0023 "Block/Unblock"
		#define STR0024 "Unblocking"
		#define STR0025 "Blocking"
		#define STR0026 "Wait"
		#define STR0027 "Active"
		#define STR0028 "Assets according to the parameters entered were not found"
		#define STR0029 "or the assets cannot be blocked."
		#define STR0030 "or the assets cannot be blocked."
		#define STR0031 "No asset was unblocked."
		#define STR0032 "No asset was blocked."
		#define STR0033 "The following assets were unblocked:"
		#define STR0034 "The following assets were blocked:"
		#define STR0035 "Blockage / unblockage of assets"
		#define STR0036 " The following assets are not effective because they are in inventory process: "
		#define STR0037 "The following assets are not effective because the registered locations are blocked "
		#define STR0038 "Start"
		#define STR0039 "CSV Imp. processing log"
		#define STR0040 "File for import"
		#define STR0041 "Deletes previous classification"
		#define STR0042 "Files .CSV |*.CSV"
		#define STR0043 "Yes"
		#define STR0044 "No"
		#define STR0045 "Import Asset Classification"
		#define STR0046 "Classification of Code "
		#define STR0047 "Item:"
		#define STR0048 'Creates Automatic'
		#define STR0049 'Assets number'
		#define STR0050 "Depreciation Initial Date cannot be earlier than last calculation date = "
		#define STR0051 " The following assets were not made effective because the registered locations are blocked "
		#define STR0052 "The following assets were not made effective because they are in inventory process."
		#define STR0053 "The following assets were blocked"
		#define STR0054 "Unblocked"
		#define STR0055 "Block / Unblock assets"
		#define STR0056 "Report"
		#define STR0057 " Conversion of Depreciation Method "
		#define STR0058 "Cancel Depreciation Method conversion"
		#define STR0059 "Search"
		#define STR0060 "View"
		#define STR0061 "Add"
		#define STR0062 "Edit"
		#define STR0063 "Delete"
		#define STR0064 "Delete Lot"
		#define STR0065 "Copy"
		#define STR0066 "Knowledge"
		#define STR0067 "Caption"
		#define STR0068 "Convert Method"
		#define STR0069 "Canc.Method"
		#define STR0070 "Convert Dep."
		#define STR0071 "Cancel Dep."
		#define STR0072 "Block/Unblock"
		#define STR0073 "Thir Party Contr."
		#define STR0074 "Thir Party Contr."
		#define STR0075 "Import Classification"
		#define STR0076 "Proc Log"
		#define STR0077 "Confirm"
		#define STR0078 "Management Margin"
		#define STR0079 "AVP Calculation"
		#define STR0080 "Multiple"
		#define STR0081 "Apportionment"
		#define STR0082 "People in Charge"
		#define STR0083 "Thir Party Contr."
		#define STR0084 "Thir Party Contr."
		#define STR0085 "Update Fixed Assets"
		#define STR0086 "Balance and Values"
		#define STR0087 'Unlock'
		#define STR0088 'Lock'
		#define STR0089 "Accounting Tracker"
		#define STR0090 "Confirm Change?"
		#define STR0091 "Attention"
		#define STR0092 'Fixed Assets Update'
		#define STR0093 'Unlock'
		#define STR0094 "Lock"
		#define STR0095 'Only types'
		#define STR0096 " can be registered with the asset type "
		#define STR0097 "Third-party control is not available for this asset."
		#define STR0098 "Evaluate the configuration of the field Control Type."
		#define STR0099 "There is no third party control for this asset."
		#define STR0100 "Conduct maintenance through the third-party control register."
		#define STR0101 "Control in third parties not available for this asset."
		#define STR0102 "Evaluate the configuration of the field Control Type."
		#define STR0103 "Control of assets in third parties"
		#define STR0104 "There is already a third party control active for this asset."
		#define STR0105 "Maintenance must be conducted through the third-party control register."
		#define STR0106 "Options available through the asset register:"
		#define STR0107 "View"
		#define STR0108 "Exit"
		#define STR0109 "There is no third party control for this asset."
		#define STR0110 "Conduct maintenance through the third-party control register."
		#define STR0111 "The asset has associated CIAP. Do you wish to continue with deletion?"
		#define STR0112 "Attention"
		#define STR0113 "Type of asset is not a base type"
		#define STR0114 "Generating asset types..."
		#define STR0115 "The asset acquisition date is equal to or earlier than the transaction stoppage date: "
		#define STR0116 'The edition of field "#1[Tipo deprec.]#" of the extension must occur happen of "Tax Depreciation" asset.'
		#define STR0117 "The conversion of the Original value in Currency 1 to the following currencies, surpasses the maximum allowed size: "
		#define STR0118 "The asset acquisition date is equal to or earlier than the transaction stoppage date: "
		#define STR0119 'Well planned it can only be deleted be reversing the effectiveness of the asset planning routine (ATFA310)'
		#define STR0120 "Enter a Estimate Date of Execution later than the AVP Date."
		#define STR0121 "The asset value of the legal currency was not entered."
		#define STR0122 "The field Account (N3_CCONTAB) was not filled out."
		#define STR0123 "Enter at least one value type 10 (Managerial/Accounting Depreciation) to perform the calculation AVP."
		#define STR0124 "Enter properly data in tab AVP."
		#define STR0125 "You need to register third party data!"
		#define STR0126 "You need to register data of assets in third parties!"
		#define STR0127 "Select a type of asset "
		#define STR0128 "Converting asset Wait"
		#define STR0129 "Is current asset value calculated?"
		#define STR0130 "The selected index is blocked!"
		#define STR0131 "This item cannot be deleted."
		#define STR0132 "Item Type 10 can only be deleted if there are items Type 14"
		#define STR0133 "and items Type 14 cannot be manually deleted."
		#define STR0134 "Asset originated from transfer process. In the transfer routine, use the transfer cancellation option."
		#define STR0135 "Accounting Calendar Blocked. Check the process."
		#define STR0136 "Maximum Depreciation Value cannot be greater than the original value in the currency setup on parameter MV_ATFMDMX "
		#define STR0137 "Asset has the following employee is responsible party: "
		#define STR0138 " Proceed with the operation?"
		#define STR0139 "Cannot change depreciation start date for period equal to or previous to last depreciation calculation."
		#define STR0140 "Depreciation start date cannot be before the asset acquisition date or the balance type acquisition date."
		#define STR0141 "Depreciation Start Date cannot be before acquisition date"
		#define STR0142 "Do you really want to alter the field Depreciation Rate"
		#define STR0143 "Do you really want to update the field Annual Depreciation Period?"
		#define STR0144 "This field is not used by the selected method of depreciation, the entered value is not considered."
		#define STR0145 "The field "
		#define STR0146 " was not entered."
		#define STR0147 "In the Balances and Values grid there are one or more items with the period of depreciation out of group interval"
		#define STR0148 "The period of depreciation is out of depreciation group interval"
		#define STR0149 "History"
		#define STR0150 "Conservation"
		#define STR0151 "Desconservation"
		#define STR0152 " not entered."
		#define STR0153 "Fill field"
		#define STR0154 " already exists in the system."
		#define STR0155 "Set a new code in the field"
		#define STR0156 "Depreciation Date cannot be earlier than the date of purchase of the asset, enter a date of Depreciation later than the purchase date"
		#define STR0157 'Cannot define asset as 'Blocked by Location' (N1_STATUS), without entering a blocked location (N1_LOCAL).'
		#define STR0158 "If type of depreciation (N3_TPDEPR) is 1, 2 or 6, rate of depreciation (N3_PERDEPR) is mandatory"
		#define STR0159 "No comertial invoice for this fixed asset"
		#define STR0160 "Purchase Invoice"
		#define STR0161 "Debe informar el Tipo de documento en el catálogo de proveedores."
		#define STR0162 "Quantity is mandatory for non writen-off fixed assets"
		#define STR0163 "This field cannot be changed."
		#define STR0164 "If this operation is unavoidable, delete and register again or use the transfer routine."
		#define STR0165 "Changes the original value discounting PIS and COFINS rate? "
		#define STR0166 "Status Used only when Asset included by Inbound Invoice - N1_STATUS"
		#define STR0167 "O campo [Meses Cl.Pis] deve estar zerado para a condição de cálculo de PIS igual a (SIM ou NÃO)"
		#define STR0168 "É obrigatório o preenchimento do campo [Meses Cl.Pis] com um valor válido, verifique o parâmetro MV_ATFMAPR."
		#define STR0169 "Ledger Account not informed for company "
		#define STR0170 "Fixed Assets"
		#define STR0171 "Creation"
		#define STR0172 "Update"
		#define STR0173 "Operations were performed on this fixed asset It is imposible to delete it."
		#define STR0174 "Delition is posible on status schedule."
		#define STR0175 "Fixed Assets and Intangible assets"
		#define STR0176 " Request admin to adjust the size of the field in the data dictionary. "
		#define STR0177 "Parameter MV_ATFMOED improperly configured"
		#define STR0178 "Asset Type Construction only allow type of Asset 03"
		#define STR0179 "You cannot add a new row in the component of an asset in construction"
		#define STR0180 "The Asset must be Type in construction"
		#define STR0181 "Switch Type of Asset to 03"
		#define STR0182 "Asset in construction has bindings. Delete components to delete asset"
		#define STR0183 "Unable to add a new row in an asset in construction"
		#define STR0184 "The Component must have CIAP"
		#define STR0185 "Select an Asset in construction, using F3, for binding. Asset in construction tab"
	#else
		#define STR0001 'Existem ativos gerenciais de Custo/Provisão que não estão sendo considerados para os saldos de Custo/Provisão.'
		#define STR0002 'Deseja continuar assim mesmo?'
		#define STR0003 'Ativos de Custo/Provisão'
		#define STR0004 "Essa alteração implicará na perda dos dados digitados, deseja continuar?"
		#define STR0005 "Apresentação"
		#define STR0006 "Código Base:"
		#define STR0007 "Item:"
		#define STR0008 "Chapa:"
		#define STR0009 "Descrição:"
		#define STR0010 "Seleção dos bens"
		#define STR0011 "Conversão de Métodos de depreciação"
		#define STR0012 "Processando Conversão..."
		#define STR0013 "Processando Cancelamento da Conversão..."
		#define STR0014 "Parâmetros"
		#define STR0015 "Do Código do Bem"
		#define STR0016 "Até o Código do Bem"
		#define STR0017 "Do Item"
		#define STR0018 "Até o Item"
		#define STR0019 "Do Grupo"
		#define STR0020 "Até o Grupo"
		#define STR0021 "Da Data de Aquisição"
		#define STR0022 "Até a Data de Aquisição"
		#define STR0023 "Bloqueia/Desbloq"
		#define STR0024 "Desbloqueando"
		#define STR0025 "Bloqueando"
		#define STR0026 "Aguarde"
		#define STR0027 "Ativo"
		#define STR0028 "Não foram encontrados bens de acordo com os parâmetros informados"
		#define STR0029 "ou os bens não puderam ser desbloqueados."
		#define STR0030 "ou os bens não puderam ser bloqueados."
		#define STR0031 "Nenhum bem foi desbloqueado."
		#define STR0032 "Nenhum bem foi bloqueado."
		#define STR0033 "Os seguintes bens foram desbloqueados:"
		#define STR0034 "Os seguintes bens foram bloqueados:"
		#define STR0035 "Bloqueio / Desbloqueio de bens"
		#define STR0036 " Os seguintes ativos não foram efetivados porque estão em processo de inventário. "
		#define STR0037 "Os seguintes ativos não foram efetivados porque os locais cadastrados estão bloqueados "
		#define STR0038 "Inicio"
		#define STR0039 "Log de processamento de Imp. CSV"
		#define STR0040 "Arquivo para importação"
		#define STR0041 "Exclui classificação anterior"
		#define STR0042 "Arquivos .CSV |*.CSV"
		#define STR0043 "Sim"
		#define STR0044 "Não"
		#define STR0045 "Importar Classificação Ativo"
		#define STR0046 "Classificacao do Código "
		#define STR0047 "Item:"
		#define STR0048 'Cria Automático'
		#define STR0049 'Número de Bens'
		#define STR0050 "A Data Inicial de Depreciação não pode ser menor que a data do último calculo = "
		#define STR0051 " Os seguintes ativos não foram efetivados porque os locais cadastrados estão bloqueados "
		#define STR0052 "Os seguintes ativos não foram efetivados porque estão em processo de inventário."
		#define STR0053 "Os seguintes bens foram bloqueados"
		#define STR0054 "Desbloqueados:"
		#define STR0055 "Bloqueio / Desbloqueio de bens"
		#define STR0056 "Laudo"
		#define STR0057 " Conversão de Método de Depreciação "
		#define STR0058 "Cancelamento da conversão de Método de Depreciação"
		#define STR0059 "Pesquisar"
		#define STR0060 "Visualizar"
		#define STR0061 "Incluir"
		#define STR0062 "Alterar"
		#define STR0063 "Excluir"
		#define STR0064 "Excluir Lote"
		#define STR0065 "Copia"
		#define STR0066 "Conhecimento"
		#define STR0067 "Legenda"
		#define STR0068 "Converte Método"
		#define STR0069 "Canc.Método"
		#define STR0070 "Converte Dep."
		#define STR0071 "Cancela Dep."
		#define STR0072 "Bloquear/Desb"
		#define STR0073 "Contr. Terceiros"
		#define STR0074 "Contr.em Terceiros"
		#define STR0075 "Import. Classificação"
		#define STR0076 "Log Proc"
		#define STR0077 "Confirmar"
		#define STR0078 "Margem Gerencial"
		#define STR0079 "Cálculo AVP"
		#define STR0080 "Múltiplos"
		#define STR0081 "Rateio"
		#define STR0082 "Responsáveis"
		#define STR0083 "Contr.Terceiros"
		#define STR0084 "Cont.em Terceiros"
		#define STR0085 "Atualização de Ativos Imobilizados"
		#define STR0086 "Saldo e Valores"
		#define STR0087 'Desbloqueia'
		#define STR0088 'Bloqueia'
		#define STR0089 "Tracker Contábil"
		#define STR0090 "Confirma Alteracao?"
		#define STR0091 "Atenção"
		#define STR0092 'Atualização de Ativos Imobilizados'
		#define STR0093 'Desbloqueia'
		#define STR0094 "Bloqueia"
		#define STR0095 'Apenas os tipos'
		#define STR0096 " podem ser cadastrados em conjunto com o tipo de ativo "
		#define STR0097 "Controle de terceiros nao disponivel para este bem."
		#define STR0098 "Avaliar as configuracao do campo Tipo de Controle."
		#define STR0099 "Nao existe controle de terceiros para este bem."
		#define STR0100 "Efetuar manutencao pelo cadastro de controle de terceiros."
		#define STR0101 "Controle em terceiros nao disponivel para este bem."
		#define STR0102 "Avaliar as configuracao do campo Tipo de Controle."
		#define STR0103 "Controle de bens em terceiros"
		#define STR0104 "Ja existe um controle de terceiros ativo para este bem."
		#define STR0105 "Manutencoes devem ser realizadas pelo cadastro de controle de terceiros."
		#define STR0106 "Opcoes disponiveis pelo cadastro do bem:"
		#define STR0107 "Visualizar"
		#define STR0108 "Sair"
		#define STR0109 "Nao existe controle de terceiros para este bem."
		#define STR0110 "Efetuar manutencao pelo cadastro de controle de terceiros."
		#define STR0111 "O Bem possui um CIAP associado deseja Continuar a exclusão ?"
		#define STR0112 "Atenção"
		#define STR0113 "Tipo de ativo não é um tipo base"
		#define STR0114 "Gerando fichas de ativos ..."
		#define STR0115 "A data de aquisição do bem é igual ou menor que a data de bloqueio de movimentação : "
		#define STR0116 'A alteração do campo "#1[Tipo deprec.]#" da ampliação deve ocorrer por meio do tipo de ativo "Depreciação Fiscal".'
		#define STR0117 "A conversão do valor Original na Moeda 1 para as seguintes moedas, ultrapassara o tamanho maximo permitido: "
		#define STR0118 "A data de aquisição do bem é igual ou menor que a data de bloqueio de movimentação : "
		#define STR0119 'Bem planejado somente poderá ser excluido através do estorno da efetivação na rotina de planejamento de ativo (ATFA310)'
		#define STR0120 "Informe uma Data Prevista de Execucao maior que a Data Inicio AVP."
		#define STR0121 "O valor do bem na moeda legal não foi digitado."
		#define STR0122 "O campo Conta (N3_CCONTAB) não foi preenchido."
		#define STR0123 "Informe ao menos um valor do tipo 10 (Depreciação Gerencial/Contabil) para realizar o cálculo AVP."
		#define STR0124 "Informe corretamente os dados na aba 'AVP'."
		#define STR0125 "É Necessário cadastrar dados de terceiro!"
		#define STR0126 "É Necessário cadastrar dados de bens em terceiro!"
		#define STR0127 "Por favor, marque um tipo de bem "
		#define STR0128 "Convertendo Bem Aguarde"
		#define STR0129 "Calcula valor atual do bem?"
		#define STR0130 "O Indice selecionado está bloqueado!"
		#define STR0131 "Este item não pode ser excluído."
		#define STR0132 "Itens de Tipo 10 só podem ser eliminados se não existirem itens de Tipo 14"
		#define STR0133 "e itens de Tipo 14 não podem ser eliminados manualmente."
		#define STR0134 "Bem originado do processo de transferência. Na rotina de transferência, utilize a opção de cancelamento de transferência."
		#define STR0135 "Calendário Contábil Bloqueado. Verfique o processo."
		#define STR0136 "Valor Máximo de Deprecição não pode ser maior que o valor original na moeda configurada no parametro MV_ATFMDMX "
		#define STR0137 "O ativo está com o seguinte participante como responsável: "
		#define STR0138 " Procede com a operação?"
		#define STR0139 "A data de inicio da depreciação não pode ser alterada para período igual ou anterior ao último cálculo de depreciação."
		#define STR0140 "A data de ínicio da depreciação não poderá ser inferior à data de aquisição do bem ou da data de aquisição do tipo de saldo."
		#define STR0141 "Data de início de depreciação não pode ser menor que a data de aquisição"
		#define STR0142 If( cPaisLoc $ "ANG|PTG", "Do you really want to alter the field Depreciation Rate", "Quer mesmo mudar o campo Taxa de Depreciação" )
		#define STR0143 If( cPaisLoc $ "ANG|PTG", "Do you really want to update the field Annual Depreciation Period?", "Quer mesmo atualizar o campo Período de Depreciação Anual?" )
		#define STR0144 "Esse campo não é utilizado pelo método de depreciação selecionado, o valor informado não será considerado."
		#define STR0145 "O campo "
		#define STR0146 " não foi preenchido."
		#define STR0147 If( cPaisLoc $ "ANG|PTG", "In the Balances and Values grid there are one or more items with the period of depreciation out of group interval", "No grid de Balanços e Valores, há um ou mais items com um período de depreciação fora do intervalo do grupo." )
		#define STR0148 If( cPaisLoc $ "ANG|PTG", "The period of depreciation is out of depreciation group interval", "O período de depreciação está fora do intervalo do grupo de depreciação" )
		#define STR0149 "Èñòîğèÿ"
		#define STR0150 "Êîíñåğâàöèÿ"
		#define STR0151 "Äåêîíñåğâàöèÿ"
		#define STR0152 " não informado."
		#define STR0153 "Preencha o campo "
		#define STR0154 " já existente no sistema."
		#define STR0155 "Defina um novo código no campo "
		#define STR0156 "Data de Depreciação não pode ser inferior a data da aquisição do ativo, digite uma data de Depreciação maior ou igual a data da aquisição"
		#define STR0157 'Não é possivel definir o ativo como "Bloqueado por Local" (N1_STATUS), sem informar um local bloqueado (N1_LOCAL).'
		#define STR0158 "Åñëè Òèï àìîğòèçàöèè (n3_tpdepr) ğàâåí 1, 2 èëè 6, ñòàâêà àìîğòèçàöèè (n3_perdepr) ÿâëÿåòñÿ îáÿçàòåëüíîé"
		#define STR0159 "Íåò âõîäÿùåé íàêëàäíîé äëÿ äàííîãî îñíîâíîãî ñğåäñòâà"
		#define STR0160 "Âõîä. íàêëàäíàÿ"
		#define STR0161 "Debe informar el Tipo de documento en el catálogo de proveedores."
		#define STR0162 "Êîëè÷åñòâî ÿâëÿåòñÿ îáÿçàòåëüíûì äëÿ íå ñïèñàííûõ îñíîâíûõ ñğåäñòâ"
		#define STR0163 "Este campo não pode ser alterado. "
		#define STR0164 "Se esta operação for inevitável, exclua e inclua novamente o registro ou utilize a rotina de transferência. "
		#define STR0165 "Altera o valor original descontando a aliquota de PIS e COFINS? "
		#define STR0166 "Status Utilizado apenas quando Ativo incluso por Nota Fiscal de Entrada - N1_STATUS"
		#define STR0167 "O campo [Meses Cl.Pis] deve estar zerado para a condição de cálculo de PIS igual a (SIM ou NÃO)"
		#define STR0168 "É obrigatório o preenchimento do campo [Meses Cl.Pis] com um valor válido, verifique o parâmetro MV_ATFMAPR."
		#define STR0169 "Conta Contábil não informada para a empresa "
		#define STR0170 "Îñí. ñğ-âà "
		#define STR0171 "Ñîçäàíèå"
		#define STR0172 "Èçìåíåíèå"
		#define STR0173 "Ïî äàííîìó Îíñíîâíîìó ñğåäñòâó áûëè âûïîëíåíû îïåğàöèè. Óäàëåíèå íåâîçìîæíî."
		#define STR0174 "Óäàëåíèå âîçìîæíî òîëüêî â ñòàòóñå Çàïëàíèğîâàíî"
		#define STR0175 "Îñíîâíûå ñğåäñòâà è ÍÌÀ"
		#define STR0176 " Solicite ao administrador ajustar o tamanho do campo no dicionario de dados. "
		#define STR0177 "Parâmetro MV_ATFMOED configurado incorretamente"
		#define STR0178 "Bem Tipo Construção só permite tipo de Ativo 03"
		#define STR0179 "Não é possível adicionar uma nova linha no componente de um bem em construção"
		#define STR0180 "O Bem deve ser Tipo em construção"
		#define STR0181 "Altere o Tipo do Ativo para 03"
		#define STR0182 "Bem em Construção possui amarrações. Exclua os componentes para logo excluir o bem"
		#define STR0183 "Não é possível adicionar uma nova linha num bem em construção"
		#define STR0184 "O Componente deve possuir CIAP"
		#define STR0185 "Selecione com F3 um Bem em construção para amarração. Aba Bem em construção"
	#endif
#endif
