#ifdef SPANISH
	#define STR0001 "EMPRESA : "
	#define STR0002 "                            M A P A   D E   R E I N T E G R A C I O N E S   "
	#define STR0003 "NUMERO DE INDETIFICACION FISCAL "
	#define STR0004 "                    M E T O D O   D E  C U O T A S  D E G R E S I V A S "
	#define STR0005 "ACTIVIDAD PRINCIPAL "
	#define STR0006 "EjERCICIO DE "
	#define STR0007 "M O D E L O"
	#define STR0008 "PERIODO DE TRIBUTACION"
	#define STR0009 " DE "
	#define STR0010 " A "
	#define STR0011 "              (a)_________________________________________________________________________"
	#define STR0012 "CODIGO CAE "
	#define STR0013 "   32.2"
	#define STR0014 "|CODIGO DE ACUERDO "
	#define STR0015 "|          DESCRIPCION           "
	#define STR0016 "|      FECHA      "
	#define STR0017 "|ACTIVO INMOVILIZADO"
	#define STR0018 "|    VALOR      "
	#define STR0019 "|REINTEGRACIONES DEL EJERCICIO"
	#define STR0020 "| REINTEGRA-"
	#define STR0021 "|  ACTIVO   "
	#define STR0022 "|    TASAS      "
	#define STR0023 "|      VALORIZACIONES       "
	#define STR0024 "|   REINTEGRACIONES Y     "
	#define STR0025 "|CON LA TABLA ANE "
	#define STR0026 "|                              "
	#define STR0027 "|ADQUIS"
	#define STR0028 "|  INICIO  "
	#define STR0029 "|VALOR DE ADQUISICION"
	#define STR0030 "|     NO       "
	#define STR0031 "|    TASAS     "
	#define STR0032 "|           "
	#define STR0033 "|   CIONES    "
	#define STR0034 "|INMOVILIZADO"
	#define STR0035 "|   PERDIDIDAS    "
	#define STR0036 "|     NO TRIBUTADAS     "
	#define STR0037 "|    AMORTIZACOES       "
	#define STR0038 "|SA AL DEC. REG.  "
	#define STR0039 "|     "
	#define STR0040 "|UTILIZACION"
	#define STR0041 "|  O DE PRODUCCION  "
	#define STR0042 "|  REINTEGRADO  "
	#define STR0043 "|DECRETO "
	#define STR0044 "|CORRI"
	#define STR0045 "|  VALORES  "
	#define STR0046 "|ACUMULADAS "
	#define STR0047 "| (VALORES  "
	#define STR0048 "|  ACUMULADAS   "
	#define STR0049 "|                        "
	#define STR0050 "|     SIN ENDOSOS       "
	#define STR0051 "|Nº 2/90 DE 12/01  "
	#define STR0052 "| ANO "
	#define STR0053 "| MES "
	#define STR0054 "| ANO"
	#define STR0055 "|                  "
	#define STR0056 "|               "
	#define STR0057 "|  REG.  "
	#define STR0058 "|GIDAS"
	#define STR0059 "| NETOS) "
	#define STR0060 "|  ANO  "
	#define STR0061 "|    IMPORTE    "
	#define STR0062 "|                       "
	#define STR0063 "TOTAL GENERAL O POR TRANSPORTAR"
#else
	#ifdef ENGLISH
		#define STR0001 "SIGNAT.:  "
		#define STR0002 "                            R E I N T E G R A T I O N S   M A P   "
		#define STR0003 "TAX IDENTIFICATION NUMBER "
		#define STR0004 "                    D E G R E S S I V E   S H A R E S   M E T H O D "
		#define STR0005 "MAIN ACTIVITY "
		#define STR0006 "YEAR "
		#define STR0007 "M O D E L  "
		#define STR0008 "TAXATION PERIOD"
		#define STR0009 " FR "
		#define STR0010 " TO "
		#define STR0011 "              (a)_________________________________________________________________________"
		#define STR0012 "CAE CODE   "
		#define STR0013 "   32.2"
		#define STR0014 "|AGREEMENT CODE "
		#define STR0015 "|          DESCRIPTION         "
		#define STR0016 "|      DATE      "
		#define STR0017 "|FIXED ASSETS"
		#define STR0018 "|    VALUE      "
		#define STR0019 "|REINTEGRATIONS OF THE YEAR"
		#define STR0020 "| REINTEGRATE-"
		#define STR0021 "|  ASSETS   "
		#define STR0022 "|    RATES      "
		#define STR0023 "|      SURPLUS       "
		#define STR0024 "|   REINTEGRATIONS AND    "
		#define STR0025 "|WITH TABLE ANNEXED "
		#define STR0026 "|                              "
		#define STR0027 "|ACQUIS"
		#define STR0028 "|  START  "
		#define STR0029 "|AQUISITION VALUE"
		#define STR0030 "|     NO       "
		#define STR0031 "|    RATES     "
		#define STR0032 "|           "
		#define STR0033 "|   TIONS    "
		#define STR0034 "|FIXED"
		#define STR0035 "|   LOST    "
		#define STR0036 "|     NON-TAXED     "
		#define STR0037 "|    AMORTIZATION       "
		#define STR0038 "|TO DEC. REG.  "
		#define STR0039 "|     "
		#define STR0040 "|USE"
		#define STR0041 "|  OR PRODUCTION  "
		#define STR0042 "|  REINTEGRATED  "
		#define STR0043 "|DECREE "
		#define STR0044 "|COR"
		#define STR0045 "|  VALUES  "
		#define STR0046 "|ACCRUED "
		#define STR0047 "| (VALUES  "
		#define STR0048 "|  ACCRUED   "
		#define STR0049 "|                        "
		#define STR0050 "|     NO ACCEPTANCES       "
		#define STR0051 "|NR. 2/90 FROM 12/01  "
		#define STR0052 "| YEAR "
		#define STR0053 "| MONTH "
		#define STR0054 "| YEAR"
		#define STR0055 "|                  "
		#define STR0056 "|               "
		#define STR0057 "|  REC.  "
		#define STR0058 "|RECTED"
		#define STR0059 "| NET) "
		#define STR0060 "|  YEAR  "
		#define STR0061 "|    AMOUNT    "
		#define STR0062 "|                       "
		#define STR0063 "GRAND TOTAL OR TOTAL TO BE TRANSPORTED"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", 'FIRMA :', "FIRMA : " )
		#define STR0002 "                            M A P A   D E   R E I N T E G R A C O E S   "
		#define STR0003 If( cPaisLoc $ "ANG|PTG", 'NÚMERO DE INDETIFICAÇÃO FISCAL', "NUMERO DE INDETIFICACAO FISCAL " )
		#define STR0004 "                    M E T O D O   D A S  Q U O T A S  D E G R E S S I V A S "
		#define STR0005 If( cPaisLoc $ "ANG|PTG", 'ACTIVIDADE PRINCIPAL', "ACTIVIDADE PRINCIPAL " )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "EXERCICIO DE :", "EXERCICIO DE " )
		#define STR0007 "M O D E L O"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "PERÍODO DE TRIBUTAÇÃO", "PERIODO DE TRIBUTACAO" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", " de ", " DE " )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", " a ", " A " )
		#define STR0011 "              (a)_________________________________________________________________________"
		#define STR0012 If( cPaisLoc $ "ANG|PTG", 'CÓDIGO CAE', "CODIGO CAE " )
		#define STR0013 "   32.2"
		#define STR0014 "|CODIGO DE ACORDO "
		#define STR0015 "|          DESCRICAO           "
		#define STR0016 "|      DATA      "
		#define STR0017 "|ACTIVO IMOBILIZADO"
		#define STR0018 "|    VALOR      "
		#define STR0019 "|REINTEGRACOES DO EXERCICIO"
		#define STR0020 "| REINTEGRA-"
		#define STR0021 "|  ACTIVO   "
		#define STR0022 "|    TAXAS      "
		#define STR0023 "|      MAIS-VALIAS       "
		#define STR0024 "|   REINTEGRACOES E     "
		#define STR0025 "|COM A TABELA ANE "
		#define STR0026 "|                              "
		#define STR0027 "|AQUIS"
		#define STR0028 "|  INICIO  "
		#define STR0029 "|VALOR DE AQUISICAO"
		#define STR0030 "|     NAO       "
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "|    TAXAS      ", "|    TAXAS     " )
		#define STR0032 "|           "
		#define STR0033 "|   COES    "
		#define STR0034 "|IMOBILIZADO"
		#define STR0035 "|   PERDIDAS    "
		#define STR0036 "|     NAO TRIBUTADAS     "
		#define STR0037 "|    AMORTIZACOES       "
		#define STR0038 "|XA AO DEC. REG.  "
		#define STR0039 "|     "
		#define STR0040 "|UTILIZACAO"
		#define STR0041 "|  OU DE PRODUCAO  "
		#define STR0042 "|  REINTEGRADO  "
		#define STR0043 "|DECRETO "
		#define STR0044 "|CORRI"
		#define STR0045 "|  VALORES  "
		#define STR0046 "|ACUMULADAS "
		#define STR0047 "| (VALORES  "
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "|  ACUMULADAS     ", "|  ACUMULADAS   " )
		#define STR0049 "|                        "
		#define STR0050 "|     NAO ACEITES       "
		#define STR0051 "|N 2/90 DE 12/01  "
		#define STR0052 "| ANO "
		#define STR0053 "| MES "
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "| ANO ", "| ANO" )
		#define STR0055 "|                  "
		#define STR0056 "|               "
		#define STR0057 "|  REG.  "
		#define STR0058 "|GIDAS"
		#define STR0059 "| LIQUIDOS) "
		#define STR0060 "|  ANO  "
		#define STR0061 "|    MONTANTE    "
		#define STR0062 "|                       "
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "TOTAL CRIAL OU A TRASNPORTAR", "TOTAL GERAL OU A TRANSPORTAR" )
	#endif
#endif
