#ifdef SPANISH
	#define STR0001 "Estrategia"
	#define STR0002 "Estrategias"
	#define STR0003 "Nombre"
	#define STR0004 "Inicio"
	#define STR0005 "Final"
	#define STR0006 "Aprendizaje y Crecimiento"
	#define STR0007 "Para alcanzar nuestra visión, ¿como sustentaremos nuestra capacidad de cambiar y mejorar?"
	#define STR0008 "Proceso Interno"
	#define STR0009 "Para satisfacer a nuestros accionistas y clientes, ¿en que processos de negocios debemos alcanzar la perfeccion?"
	#define STR0010 "Cliente"
	#define STR0011 "Para alcanzar nuestra deseo, ¿como nos deben visualizar nuestros clientes?"
	#define STR0012 "Financiera"
	#define STR0013 "Para que tengamos exito financieramente, ¿como nos deben visualizar nuestros accionistas?"
	#define STR0014 "Compartido"
	#define STR0015 "Contribuidor"
#else
	#ifdef ENGLISH
		#define STR0001 "Strategy"
		#define STR0002 "Strategies"
		#define STR0003 "Name"
		#define STR0004 "Start"
		#define STR0005 "End"
		#define STR0006 "Learning and Development"
		#define STR0007 "To achieve our vision, how shall we sustain our capacity to change and evolve?"
		#define STR0008 "Internal Process"
		#define STR0009 "For us to please our shareholders and customers, in which business process should we achieve excellence?"
		#define STR0010 "Customer"
		#define STR0011 "To achieve our vision, how should we be perceived by our customers?"
		#define STR0012 "Financial"
		#define STR0013 "To be financially successful, how should we be perceived by our stockholders?"
		#define STR0014 "Shared       "
		#define STR0015 "Contributive"
	#else
		#define STR0001 "Estratégia"
		#define STR0002 "Estratégias"
		#define STR0003 "Nome"
		#define STR0004 "Início"
		#define STR0005 "Final"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Aprendido E Em Crescimento", "Aprendizado e Crescimento" )
		#define STR0007 "Para alcançarmos nossa visão, como sustentaremos nossa capacidade de mudar e melhorar?"
		#define STR0008 "Processo Interno"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Para satisfazermos os nossos accionistas e clientes, em que processos de negócios deveremos alcançar a excelência?", "Para satisfazermos nossos acionistas e clientes, em que processos de negocios devemos alcancar a excelencia?" )
		#define STR0010 "Cliente"
		#define STR0011 "Para alcançarmos nossa visão, como deveríamos ser vistos pelos nossos clientes?"
		#define STR0012 "Financeira"
		#define STR0013 "Para sermos bem sucedidos financeiramente, como deveríamos ser vistos pelos nossos acionistas?"
		#define STR0014 "Compartilhado"
		#define STR0015 "Contributivo"
	#endif
#endif
