#IFDEF SPANISH
	#define STR0001 'Criterios de Valorizacion para Calidad de la Leche'
	#define STR0002 'bUscar'
	#define STR0003 'Visualizar'
	#define STR0004 'Incluir'
	#define STR0005 'Modificar'
	#define STR0006 'Borrar'
	#define STR0007 "Código"
	#define STR0008 "Leche"
	#define STR0009 "De"
	#define STR0010 "A"
	#define STR0011 "Valor+/Litro"
    #define STR0012 "Ultima act."
    #define STR0013 "Tb.en vigor"
    #define STR0014 "Descripcion"

#ELSE
	#IFDEF ENGLISH
        #define STR0001 'Criteria to value milk quality'
		#define STR0002 'Search'
		#define STR0003 'View'
		#define STR0004 'Insert'
		#define STR0005 'Edit'
		#define STR0006 'Delete'
        #define STR0007 "Table Code"
        #define STR0008 "Milk type"
        #define STR0009 "From"
        #define STR0010 "To"
        #define STR0011 "Value+/Liter"
        #define STR0012 "Last update"
        #define STR0013 "Tb.in force"  // tabela em vigor
        #define STR0014 "Description"
	#ELSE
        #define STR0001 "Critérios para Valorização da Qualidade do Leite"
		#define STR0002 'Pesquisar'
		#define STR0003 'Visualizar'
		#define STR0004 'Incluir'
		#define STR0005 'Alterar'
		#define STR0006 'Excluir'
        #define STR0007 "Código"
        #define STR0008 "Leite"
        #define STR0009 "De"
        #define STR0010 "Até"
        #define STR0011 "R$/Litro"
        #define STR0012 "Ult.Atualiz."
        #define STR0013 "Tab.em vigor"
        #define STR0014 "Descricao"
	#ENDIF
#ENDIF
