#IFDEF SPANISH
   #define STR0001 "Pesquisar"
   #define STR0002 "Visualizar"
   #define STR0003 "Incluir"
   #define STR0004 "Alterar"
   #define STR0005 "Excluir"
   #define STR0006 "Classificacao do Leite C"
   #define STR0007 "Codigo Linha"
   #define STR0008 "Data Classif"
   #define STR0009 "Nao existem lancamentos nesta data!!!"
   #define STR0010 "Atencao!"
   #define STR0011 "Ja foi feita uma classificacao nesta data..."
   #define STR0012 "Nenhuma propriedade encontrada  na linha"
   #define STR0013 "Nao existe preco para Estado = "
   #define STR0014 " Leite = "
   #define STR0015 "Nao foi possivel classificar"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Classificacao do Leite C"
      #define STR0007 "Codigo Linha"
      #define STR0008 "Data Classif"
      #define STR0009 "Nao existem lancamentos nesta data!!!"
      #define STR0010 "Atencao!"
      #define STR0011 "Ja foi feita uma classificacao nesta data..."
      #define STR0012 "Nenhuma propriedade encontrada  na linha"
      #define STR0013 "Nao existe preco para Estado = "
      #define STR0014 " Leite = "
      #define STR0015 "Nao foi possivel classificar"
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Classificacao do Leite C"
      #define STR0007 "Codigo Linha"
      #define STR0008 "Data Classif"
      #define STR0009 "Nao existem lancamentos nesta data!!!"
      #define STR0010 "Atencao!"
      #define STR0011 "Ja foi feita uma classificacao nesta data..."
      #define STR0012 "Nenhuma propriedade encontrada  na linha"
      #define STR0013 "Nao existe preco para Estado = "
      #define STR0014 " Leite = "
      #define STR0015 "Nao foi possivel classificar"
   #ENDIF
#ENDIF
