#ifdef SPANISH
	#define STR0001 'Servicios utilizados por la aplicación del módulo Gestión de contratos, referentes a la rutina de mantenimiento de contratos.'
	#define STR0002 'Devuelve la lista de clientes disponibles para filtrar los contratos mostrados.'
	#define STR0003 'No se encontraron registros para la requisición.'
	#define STR0004 'Devuelve la lista de proveedores disponibles para filtrar los contratos mostrados.'
	#define STR0005 'Devuelve la lista de contratos disponibles para consulta.'
	#define STR0006 'Devuelve los detalles de un contrato.'
	#define STR0007 'Devuelve los valores previstos y realizados de la planilla.'
	#define STR0008 "Devuelve la cantidad total de contratos."
	#define STR0009 "Proyección financiera para los próximos 6 meses."
	#define STR0010 "día"
	#define STR0011 "días"
	#define STR0012 "mes"
	#define STR0013 "meses"
	#define STR0014 "año"
	#define STR0015 "años"
	#define STR0016 'Devuelve lista de índices de reajuste'
	#define STR0017 "Devuelve lista de productos"
	#define STR0018 "Devuelve la lista de centro de costos"
	#define STR0019 "Devuelve la lista de cuentas contables"
	#define STR0020 "Devuelve la lista de ítems contables"
	#define STR0021 "Devuelve la lista de clases de valor"
	#define STR0022 'Devuelve las cuotas del cronograma financiero'
	#define STR0023 "Devuelve condiciones de pago"
	#define STR0024 "Devuelve grupos de aprobación"
	#define STR0025 "Devuelve lista de monedas"
	#define STR0026 "Devuelve los tipos de contrato"
	#define STR0027 "Devuelve los tipos de planilla"
	#define STR0028 "Incluye contrato"
	#define STR0029 "Devuelve las áreas de los contratos"
	#define STR0030 "Error en la creación del archivo"
	#define STR0031 "Documento adjuntado al contrato con éxito."
	#define STR0032 "Error al grabar el archivo."
	#define STR0033 "Error al realizar el parse del archivo json."
	#define STR0034 "Cuerpo del mensaje vacío."
	#define STR0035 "Adjunta un documento al contrato."
	#define STR0036 "Contrato no se encontró."
	#define STR0037 "Modifica un contrato."
	#define STR0038 "¡Borrado realizado con éxito!"
	#define STR0039 "Borrar un contrato."
	#define STR0040 "No se permite modificar la situación actual del contrato para la nueva situación."
	#define STR0041 "Modifica la situación del contrato."
	#define STR0042 "Devuelve el historial de revisiones del contrato."
	#define STR0043 "Devuelve el documento solicitado en el formato base64."
	#define STR0044 "Error en la apertura del archivo."
	#define STR0045 "Documento no encontrado."
	#define STR0046 "Borrar un documento adjunto al contrato."
	#define STR0047 "Devuelve el número de revisión y su tipo"
	#define STR0048 "Crea una revisión para el contrato"
	#define STR0049 "Aprobación de la revisión efectuada con éxito."
	#define STR0050 "Aprueba la revisión de un contrato."
	#define STR0051 "Reajusta los valores del contrato con base en un índice económico"
	#define STR0052 "Revisión de reajuste por índice económico."
	#define STR0053 "Reinicia un contrato paralizado."
	#define STR0054 "Informe o verifique el tipo de revisión por medio del parámetro MV_GCTRVRN."
	#define STR0055 "Informe o verifique el tipo de revisión por medio del parámetro MV_GCTRVRJ."
	#define STR0056 "Informe o verifique el tipo de revisión por medio del parámetro MV_GCTRVAB."
	#define STR0057 "Devuelve lista de naturalezas."
	#define STR0058 "Devuelve las tasas de la moneda de acuerdo con las fechas especificadas."
	#define STR0059 "Devuelve los códigos de los planes de cuentas adicionales."
	#define STR0060 "Devuelve los entes contables de acuerdo con el plan de cuentas informado."
	#define STR0061 "Devuelve la lista de los motivos de la paralización."
	#define STR0062 "Devuelve los números de las cuotas para atribución en el cronograma financiero."
	#define STR0063 "El tamaño del campo CNF_PARCEL no permite la configuración de la cantidad de cuotas incluida."
#else
	#ifdef ENGLISH
		#define STR0001 'Services used by the application of the Management of Contracts module, related to the routine of maintenance of contracts.'
		#define STR0002 'Returns the list of customers available to filter the contracts displayed.'
		#define STR0003 'No records found for request.'
		#define STR0004 'Returns the list of suppliers available to filter the contracts displayed.'
		#define STR0005 'Returns the list of contracts available for query'
		#define STR0006 'Returns details of a contract.'
		#define STR0007 'It returns the values estimated and realized of spreadsheet.'
		#define STR0008 "Returns the total quantity of contracts."
		#define STR0009 "Financial projection for the next 6 months."
		#define STR0010 "day"
		#define STR0011 "days"
		#define STR0012 "month"
		#define STR0013 "months"
		#define STR0014 "year"
		#define STR0015 "years"
		#define STR0016 'Return list of adjustment indexes'
		#define STR0017 "Return product list"
		#define STR0018 "Return cost center list"
		#define STR0019 "Returns ledger accounts list"
		#define STR0020 "Returns accounting items list"
		#define STR0021 "Returns value class list"
		#define STR0022 'Returns the financial schedule of installments'
		#define STR0023 "Returns payment terms"
		#define STR0024 "Returns approval groups"
		#define STR0025 "Returns currencies list"
		#define STR0026 "Returns types of contract"
		#define STR0027 "Returns types of spreadsheet"
		#define STR0028 "Adds contract"
		#define STR0029 "Returns contract areas"
		#define STR0030 "Error creating file."
		#define STR0031 "Document successfully attached to the contract."
		#define STR0032 "Error by saving file."
		#define STR0033 "Error executing json file parse."
		#define STR0034 "Copy of message blank."
		#define STR0035 "Attaches a document to the contract."
		#define STR0036 "Contract not found."
		#define STR0037 "Edits contract."
		#define STR0038 "Successfully deleted!"
		#define STR0039 "Deletes contract."
		#define STR0040 "You cannot change current status of the contract for the new status."
		#define STR0041 "Edits a contract status."
		#define STR0042 "Returns history of contract reviews."
		#define STR0043 "Returns document requested in base64 format."
		#define STR0044 "Error opening file."
		#define STR0045 "Document not found."
		#define STR0046 "Deletes a document attached to the contract."
		#define STR0047 "Returns the number of review and type"
		#define STR0048 "Creates a revision for the contract."
		#define STR0049 "Approval of revision successful."
		#define STR0050 "Approves the revision of a contract."
		#define STR0051 "Adjusts values of a contract based on an economic index."
		#define STR0052 "Adjustment Revision by economic index."
		#define STR0053 "Restarts a frozen contract."
		#define STR0054 "Inform or check the type of review using the MV_GCTRVRN parameter."
		#define STR0055 "Inform or check the type of review using the MV_GCTRVRJ parameter."
		#define STR0056 "Inform or check the type of review using the MV_GCTRVAB parameter."
		#define STR0057 "Return nature list."
		#define STR0058 "It returns the currency rates according to dates specified."
		#define STR0059 "It returns the codes of the additional chart of accounts."
		#define STR0060 "It returns the accounting entries according to the chart of accounts informed."
		#define STR0061 "It returns the list of stoppage reasons."
		#define STR0062 "Returns the installment numbers for allocation in the financial schedule."
		#define STR0063 "The size of field CNF_PARCEL does not enable configuration of installment amount added."
	#else
		#define STR0001 'Serviços utilizados pelo aplicativo do modulo Gestão de Contratos, referentes a rotina de manutencao de contratos.'
		#define STR0002 'Retorna a lista de clientes disponíveis para filtrar os contratos exibidos.'
		#define STR0003 'Não foram encontrados registros para a requisição.'
		#define STR0004 'Retorna a lista de fornecedores disponíveis para filtrar os contratos exibidos.'
		#define STR0005 'Retorna a lista de contratos disponíveis para consulta.'
		#define STR0006 'Retorna os detalhes de um contrato.'
		#define STR0007 'Retorna os valores previstos e realizados da planilha.'
		#define STR0008 "Retorna a quantidade total de contratos."
		#define STR0009 "Projecao financeira para os proximos 6 meses."
		#define STR0010 "dia"
		#define STR0011 "dias"
		#define STR0012 "mês"
		#define STR0013 "meses"
		#define STR0014 "ano"
		#define STR0015 "anos"
		#define STR0016 'Retorna lista de índices de reajuste'
		#define STR0017 "Retorna lista de produtos"
		#define STR0018 "Retorna a lista de centro de custos"
		#define STR0019 "Retorna a lista de contas contábeis"
		#define STR0020 "Retorna a lista de items contábeis"
		#define STR0021 "Retorna a lista de classes de valor"
		#define STR0022 'Retorna as parcelas do cronograma financeiro'
		#define STR0023 "Retorna condições de pagamento"
		#define STR0024 "Retorna grupos de aprovação"
		#define STR0025 "Retorna lista de moedas"
		#define STR0026 "Retorna os tipos de contrato"
		#define STR0027 "Retorna os tipos de planilha"
		#define STR0028 "Inclui um contrato"
		#define STR0029 "Retorna as áreas dos contratos"
		#define STR0030 "Erro na criação do arquivo."
		#define STR0031 "Documento anexado ao contrato com sucesso."
		#define STR0032 "Erro ao salvar o arquivo."
		#define STR0033 "Erro ao realizar o parse do arquivo json."
		#define STR0034 "Corpo da mensagem vazio."
		#define STR0035 "Anexa um documento ao contrato."
		#define STR0036 "Contrato não encontrado."
		#define STR0037 "Altera um contrato."
		#define STR0038 "Exclusao realizada com sucesso!"
		#define STR0039 "Exclui um contrato."
		#define STR0040 "Não é permitida a alteração da situação atual do contrato para a nova situação."
		#define STR0041 "Altera a situação do contrato."
		#define STR0042 "Retorna o histórico de revisões do contrato."
		#define STR0043 "Retorna o documento solicitado no formato base64."
		#define STR0044 "Erro na abertura do arquivo."
		#define STR0045 "Documento não encontrado."
		#define STR0046 "Exclui um documento anexado ao contrato."
		#define STR0047 "Retorna o número da revisão e seu tipo"
		#define STR0048 "Cria uma revisão para o contrato"
		#define STR0049 "Aprovação da revisão efetuada com sucesso."
		#define STR0050 "Aprova a revisão de um contrato."
		#define STR0051 "Reajusta os valores do contrato com base em um índice econômico"
		#define STR0052 "Revisão de Reajuste por índice econômico."
		#define STR0053 "Reinicia um contrato paralisado."
		#define STR0054 "Informe ou verifique o tipo de revisão por meio do parâmetro MV_GCTRVRN."
		#define STR0055 "Informe ou verifique o tipo de revisão por meio do parâmetro MV_GCTRVRJ."
		#define STR0056 "Informe ou verifique o tipo de revisão por meio do parâmetro MV_GCTRVAB."
		#define STR0057 "Retorna lista de naturezas."
		#define STR0058 "Retorna as taxas da moeda de acordo com as datas especificadas."
		#define STR0059 "Retorna os codigos dos planos de contas adicionais."
		#define STR0060 "Retorna as entidades contabeis de acordo com o plano de contas informado."
		#define STR0061 "Retorna lista dos motivos de paralização."
		#define STR0062 "Retorna os números das parcelas para atribuição no cronograma financeiro."
		#define STR0063 "O tamanho do campo CNF_PARCEL não permite a configuração da quantidade de parcelas inserida."
	#endif
#endif
