#ifdef SPANISH
	#define STR0001 "Contactos del CRM"
	#define STR0002 "Devuelve los contactos del usuario del CRM"
	#define STR0003 "Incluye contacto"
	#define STR0004 "Modifica contacto"
	#define STR0005 "Borra contacto"
	#define STR0006 "Verifique si los parámetros de paginación están negativos..."
	#define STR0007 "Contacto incluido con éxito..."
	#define STR0008 "Contacto modificado con éxito..."
	#define STR0009 "Código del contacto no válido para modificación o datos del contacto no es el mismo utilizado en el parámetro..."
	#define STR0010 "Datos para actualización no se informaron..."
	#define STR0011 "Contacto borrado con éxito..."
	#define STR0012 "Contacto no se ubicó..."
	#define STR0013 "Id del contacto no se informó como parámetro en la URL..."
	#define STR0013 "Id del contacto no se informó como parámetro en la URL..."
	#define STR0013 "Id del contacto no se informó como parámetro en la URL..."
	#define STR0013 "Id del contacto no se informó como parámetro en la URL..."
	#define STR0013 "Id del contacto no se informó como parámetro en la URL..."
	#define STR0013 "Id del contacto no se informó como parámetro en la URL..."
	#define STR0014 "Este contacto no se podrá borrar..."
#else
	#ifdef ENGLISH
		#define STR0001 "CRM contacts"
		#define STR0002 "Returns roles of CRM user"
		#define STR0003 "Add Contact"
		#define STR0004 "Edit Contact"
		#define STR0005 "Delete Contact"
		#define STR0006 "Check whether paging parameters are negative..."
		#define STR0007 "Contact successfully added..."
		#define STR0008 "Contact successfully changed..."
		#define STR0009 "Code of contact invalid for the edition or contact data is not the same used in parameter..."
		#define STR0010 "Data for the updating was not informed..."
		#define STR0011 "Contact successfully deleted..."
		#define STR0012 "Contact not found..."
		#define STR0013 "Contact Id not informed as parameter in URL..."
		#define STR0013 "Contact Id not informed as parameter in URL..."
		#define STR0013 "Contact Id not informed as parameter in URL..."
		#define STR0013 "Contact Id not informed as parameter in URL..."
		#define STR0013 "Contact Id not informed as parameter in URL..."
		#define STR0013 "Contact Id not informed as parameter in URL..."
		#define STR0014 "This contact cannot be deleted..."
	#else
		#define STR0001 "Contatos do CRM"
		#define STR0002 "Retorna os contatos do usuário do CRM"
		#define STR0003 "Inclui Contato"
		#define STR0004 "Altera Contato"
		#define STR0005 "Exclui Contato"
		#define STR0006 "Verifique se os parâmetros de paginacao estão negativos..."
		#define STR0007 "Contato incluído com sucesso..."
		#define STR0008 "Contato alterado com sucesso..."
		#define STR0009 "Código do contato inválido para alteração ou dados do contato não é o mesmo utilizado no parâmetro..."
		#define STR0010 "Dados para atualização não foi informado..."
		#define STR0011 "Contato excluído com sucesso..."
		#define STR0012 "Contato não localizado..."
		#define STR0013 "Id do contato não foi informado como parâmetro na URL..."
		#define STR0013 "Id do contato não foi informado como parâmetro na URL..."
		#define STR0013 "Id do contato não foi informado como parâmetro na URL..."
		#define STR0013 "Id do contato não foi informado como parâmetro na URL..."
		#define STR0013 "Id do contato não foi informado como parâmetro na URL..."
		#define STR0013 "Id do contato não foi informado como parâmetro na URL..."
		#define STR0014 "Este contato não poderá ser excluído..."
	#endif
#endif
