#ifdef SPANISH
	#define STR0001 "Crystal - Database Config"
	#define STR0002 "Informe el usuario y contraseña del Protheus para realizar el login."
	#define STR0003 "Usuario:"
	#define STR0004 "Contraseña:"
	#define STR0005 "El usuario informado no es Administrador del sistema."
	#define STR0006 "Datos para login incorrectos."
	#define STR0007 "Informe el usuario y contraseña para acceso a la base del Protheus."
	#define STR0008 "Usuario para acceso a la base:"
	#define STR0009 "Contraseña para acceso a la base:"
	#define STR0010 "Archivo de configuración grabado con éxito"
	#define STR0011 "Datos necesarios para la configuración no fueron suministrados."
#else
	#ifdef ENGLISH
		#define STR0001 "Crystal - Database Config"
		#define STR0002 "Enter Protheus user and password to log in."
		#define STR0003 "User:"
		#define STR0004 "Password:"
		#define STR0005 "User entered is not the System Admin."
		#define STR0006 "Incorrect login data."
		#define STR0007 "Enter user and password to access Protheus database."
		#define STR0008 "User to access database:"
		#define STR0009 "Password to access database:"
		#define STR0010 "Configuration file successfully saved"
		#define STR0011 "Data needed for the configuration were not provided."
	#else
		#define STR0001 "Crystal - Database Config"
		#define STR0002 "Informe o usuário e senha do Protheus para realizar o login."
		#define STR0003 "Usuário:"
		#define STR0004 "Senha:"
		#define STR0005 "O usuário informado não é Administrador do sistema."
		#define STR0006 "Dados para login incorretos."
		#define STR0007 "Informe o usuário e senha para acesso ao banco do Protheus."
		#define STR0008 "Usuário para acesso ao banco:"
		#define STR0009 "Senha para acesso ao banco:"
		#define STR0010 "Arquivo de configuração salvo com sucesso"
		#define STR0011 "Dados necessários para a configuração não foram fornecidos."
	#endif
#endif
