#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Asiento contable - Automático"
	#define STR0007 "Portada de lote: asientos contables automáticos"
	#define STR0008 "Fecha"
	#define STR0009 "Lote"
	#define STR0010 "Doc"
	#define STR0011 "Asto.Estánd"
	#define STR0012 "Selec. Asto.Estánd"
	#define STR0013 "Selec.Prorrateo"
	#define STR0014 "Valor a Prorr."
	#define STR0015 "Totales"
	#define STR0016 If( cPaisLoc == "MEX", "Cargo", "Débito" )
	#define STR0017 If( cPaisLoc == "MEX", "Abono", "Crédito" )
	#define STR0018 "Registrado"
	#define STR0019 "Moneda"
	#define STR0020 "Tipo saldo"
	#define STR0021 "Total informado: "
	#define STR0022 "Total registrado: "
	#define STR0023 If( cPaisLoc == "MEX", "Total cargo: ", "Total débito: " )
	#define STR0024 If( cPaisLoc == "MEX", "Total abono: ", "Total crédito: " )
	#define STR0025 "Total informado lote"
	#define STR0026 "Descrip. de la entidad:"
	#define STR0027 "Historial inteligente"
	#define STR0028 "Sublote"
	#define STR0029 "Leyenda"
	#define STR0030 "Portada de lote: asientos contables"
	#define STR0031 If( cPaisLoc == "MEX", "Cuenta cargo", "Cuenta débito" )
	#define STR0032 If( cPaisLoc == "MEX", "Cuenta abono", "Cuenta crédito" )
	#define STR0033 "Historial"
	#define STR0034 "Total informado Docto."
	#define STR0035 "Correlativo"
	#define STR0036 "No es posible modificar/borrar documento generado por determinación de ganancias/pérdidas.."
	#define STR0037 "Por favor active la rutina de reversión de determinación de ganancias/pérdidas.."
	#define STR0038 "Existe valor en alguna moneda que no tiene calendario contable registrado"
	#define STR0039 "¿ESTÁ SEGURO QUE DESEA BORRAR EL ASIENTO?"
	#define STR0040 "No será posible borrar este asiento. Por favor desbloquee el período.."
	#define STR0041 "Totales del lote y documento (otras monedas)"
	#define STR0042 "Total Doc. "
	#define STR0043 "Total lote "
	#define STR0044 "Diferencia en "
	#define STR0045 " del "
	#define STR0046 "Rastrear"
	#define STR0047 "Inconsistencia anterior"
	#define STR0048 "Próxima inconsistencia"
	#define STR0049 "Ubicar"
	#define STR0050 "Revertir"
	#define STR0051 "Copiar"
	#define STR0052 "Anterior"
	#define STR0053 "Próxima"
	#define STR0054 "Detalles del registro marcado"
	#define STR0055 "Detalles"
	#define STR0056 "Replicar el contenido del campo marcado"
	#define STR0057 "Replicar"
	#define STR0058 "Documento"
	#define STR0059 "Registros"
	#define STR0060 "¡Atención!"
	#define STR0061 "¿Confirma borrado de los registros seleccionados?"
	#define STR0062 "Sí"
	#define STR0063 "No"
	#define STR0064 "Replicar contenido del campo en todas las líneas anteriores"
	#define STR0065 "Replicar contenido del campo en todas las líneas abajo"
	#define STR0066 "Condición"
	#define STR0067 "Replicar "
	#define STR0068 "¿Confirma sustitución del contenido en los campos seleccionados?"
	#define STR0069 "Log Borrado"
	#define STR0070 "¿Desea realizar la reversión por lote?"
	#define STR0071 "Reversión de asiento por lote"
	#define STR0072 "Invierte selección"
	#define STR0073 "Fecha/Lote/Sublote/Documento"
	#define STR0074 "Seleccionando registros..."
	#define STR0075 "Período bloqueado. Verificar calendario contable. "
	#define STR0076 "Log Validación Reversión/Borrado por lote"
	#define STR0077 "Este informe imprimirá el informe de inconsistencias"
	#define STR0078 "de los asientos que deberían borrarse/revertirse."
	#define STR0079 "A rayas"
	#define STR0080 "Administración"
	#define STR0081 "FECHA        LOTE     SUBLOTE     DOC      INCONSISTENCIA"
	#define STR0082 "Reversión generada con éxito."
	#define STR0083 "Sublote"
	#define STR0084 "Verificar si los entes contables están correctos."
	#define STR0085 "Verificar si alguno de los entes contables está bloqueado."
	#define STR0086 "¿Desea realizar el borrado por lote?"
	#define STR0087 "Borrado realizado con éxito."
	#define STR0088 "Ningún lote se borró o revirtió."
	#define STR0089 "Asientos de determinación no podrán borrarse o revertirse."
	#define STR0090 "Recalculando totales..."
	#define STR0091 "Rec.Totales"
	#define STR0092 "¿Mostrar mensajes de actualización de flags de contabilidad durante el procesamiento?"
	#define STR0093 "Borrado por lote"
	#define STR0094 "No es posible utilizar una LP definida como punto de asiento"
	#define STR0095 "¡Documento en uso por otro usuario!"
	#define STR0096 "Esta operación no se permite para asientos complementarios."
	#define STR0097 "Si desea realizarla, hágala en el asiento principal."
	#define STR0098 "Asiento complementario"
	#define STR0099 "Copia no permitida. Copia solo en la sucursal actual."
	#define STR0100 "Cerrar"
	#define STR0101 "El campo Historial excedió el límite de: "
	#define STR0102 " caracteres."
	#define STR0103 "Cantidad digitada: "
	#define STR0104 "Historial"
	#define STR0105 "REVERSIÓN"
	#define STR0106 "Bloqueado Verificar Moneda vs. Calend. vs. Tp.Saldo. "
	#define STR0107 "Tp.Saldo: "
	#define STR0108 "Copia sucursal"
	#define STR0109 "Copia para sucursal"
	#define STR0110 "Sucursal"
	#define STR0111 "Sucursal no existe."
	#define STR0112 "Usuario"
	#define STR0113 "El sistema no ubicó los registros para el envío de los datos."
	#define STR0114 "Aviso de contabilidad manual"
	#define STR0115 "Usuario sin acceso a inclusión. Entre en contacto con el administrador del sistema."
	#define STR0116 "Acceso negado - CTBAACCBLQ"
	#define STR0117 "Alias WT"
	#define STR0118 "Recno WI"
	#define STR0119 "Asto.Extemp"
	#define STR0120 "Origen: Campo obligatorio"
	#define STR0121 "Debe existir al menos una secuencia activa en el AE informado"
	#define STR0122 "Asto. Transf. Saldo"
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Insert"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Accounting Entry - Automatic"
		#define STR0007 "Lot Cover: Automatic Accounting Entries"
		#define STR0008 "Date"
		#define STR0009 "Lot"
		#define STR0010 "Doc."
		#define STR0011 "Stand.Entry"
		#define STR0012 "Choose Std.Entry"
		#define STR0013 "Choose Prorate"
		#define STR0014 "Value to Pror."
		#define STR0015 "Totals"
		#define STR0016 "Debit"
		#define STR0017 "Credit"
		#define STR0018 "Entered"
		#define STR0019 "Curr."
		#define STR0020 "Bal. Type"
		#define STR0021 "Total Informed: "
		#define STR0022 "Total Entered: "
		#define STR0023 "Total Debit: "
		#define STR0024 "Total Credit: "
		#define STR0025 "Total Entered Lot"
		#define STR0026 "Entity Description:"
		#define STR0027 "Intelligent History"
		#define STR0028 "SubLot"
		#define STR0029 "Caption"
		#define STR0030 "Lot Cover: Accounting Entries"
		#define STR0031 "Debit Account"
		#define STR0032 "Credit Account"
		#define STR0033 "History"
		#define STR0034 "Total Entered Doc."
		#define STR0035 "Correlative"
		#define STR0036 "Can´t edit/delete document generated by the calculation of profits/losses.."
		#define STR0037 "Run the routine of profits/losses calculation reversal.."
		#define STR0038 "There is a value in a currency that has no registered accounting calendar."
		#define STR0039 "ARE YOU SURE YOU WANT TO DELETE THE ENTRY?"
		#define STR0040 "Can´t delete this entry. Please, unlock the period.."
		#define STR0041 "Lot and document totals (other currencies)"
		#define STR0042 "Document Total "
		#define STR0043 "Lot Total  "
		#define STR0044 "Difference on  "
		#define STR0045 " of "
		#define STR0046 "Track"
		#define STR0047 "Previous inconsistency "
		#define STR0048 "Next inconsistency    "
		#define STR0049 "Localize "
		#define STR0050 "Reverse "
		#define STR0051 "Copy "
		#define STR0052 "Previous"
		#define STR0053 "Next "
		#define STR0054 "Details of positioned entry "
		#define STR0055 "Details "
		#define STR0056 "Duplicate positioned field content "
		#define STR0057 "Duplicate"
		#define STR0058 "Document "
		#define STR0059 "Entries "
		#define STR0060 "Warning!"
		#define STR0061 "Confirm deletion of the selected entries? "
		#define STR0062 "Yes"
		#define STR0063 "No"
		#define STR0064 "Duplicate field content in all rows above "
		#define STR0065 "Duplicate field content in all rows below "
		#define STR0066 "Condition"
		#define STR0067 "Duplicate "
		#define STR0068 "Confirm replacement of the content in the selected fields? "
		#define STR0069 "Deletion log"
		#define STR0070 "Will you perform the reversal by lot?"
		#define STR0071 "Entry reversal by lot "
		#define STR0072 "Flip selection "
		#define STR0073 "Date/Lot/Sub-lot/Document "
		#define STR0074 "Selecting records ... "
		#define STR0075 "Period blocked. Check accounting calendar. "
		#define STR0076 "Log Validation Reversal/Deletion by Lot"
		#define STR0077 "This report will print the report of inconsistencies "
		#define STR0078 "of the entries that should be deleted/reversed. "
		#define STR0079 "Z.form "
		#define STR0080 "Management "
		#define STR0081 "DATE         LOT      SUB-LOT     DOC      INCONSISTENCE "
		#define STR0082 "Reversal generated successfully."
		#define STR0083 "Sub-lot"
		#define STR0084 "Check if accounting entities are correct. "
		#define STR0085 "Check if any accounting entity is blocked. "
		#define STR0086 "Will you perform deletion by lot? "
		#define STR0087 "Deletion complete successfully."
		#define STR0088 "No lot deleted or reversed. "
		#define STR0089 "Calculation entries cannot be deleted or reversed. "
		#define STR0090 "Recalculating totals..."
		#define STR0091 "Rec.Totals"
		#define STR0092 "Display update message of accounting flags during processing"
		#define STR0093 "Batch deletion"
		#define STR0094 "Unable to use an LP defined as point of entry"
		#define STR0095 "Document in use by another user"
		#define STR0096 "Operation not allowed for complementary entries."
		#define STR0097 "If you want to perform it, do it in main entry."
		#define STR0098 "Compl. Entry"
		#define STR0099 "Copy not allowed. Copy only in the current branch."
		#define STR0100 "Close"
		#define STR0101 "The History field exceeded the limit of: "
		#define STR0102 " characters."
		#define STR0103 "Amount entered: "
		#define STR0104 "History"
		#define STR0105 "REVERSAL"
		#define STR0106 "Blocked Check Currency x Calendar x Balance Tp. "
		#define STR0107 "Balance Tp: "
		#define STR0108 "Branch Copy"
		#define STR0109 "Copy to Branch"
		#define STR0110 "Branch"
		#define STR0111 "Branch does not exist."
		#define STR0112 "User"
		#define STR0113 "The system have not found entries for data submit."
		#define STR0114 "Manual Accounting Warning"
		#define STR0115 "User has no access to inclusion. Contact system administrator."
		#define STR0116 "Access denied - CTBAACCBLQ"
		#define STR0117 "Alias WT"
		#define STR0118 "Recno WT"
		#define STR0119 "Extemporaneous Entry"
		#define STR0120 "Origin: Mandatory Field"
		#define STR0121 "There must be at least one active sequence in the LP informed"
		#define STR0122 "Balance Transf. Entry"
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Lançamento Contabilístico - Automático", "Lançamento Contábil - Automático" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Capacidade do Lote: Lançamentos Contabilísticos Automáticos", "Capa de Lote: Lançamentos Contábeis Automáticos" )
		#define STR0008 "Data"
		#define STR0009 "Lote"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Doc.", "Docto" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Lcto Padrão", "Lçto.Padrão" )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Escolher Lançamento Padrão", "Escolha Lanç.Padrão" )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Escolher Rateio", "Escolha Rateio" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Valor A Ratear", "Valor a Ratear" )
		#define STR0015 "Totais"
		#define STR0016 "Débito"
		#define STR0017 "Crédito"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Introduzido", "Digitado" )
		#define STR0019 "Moeda"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Tipo De Saldo", "Tipo Saldo" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Total digitado: ", "Total Informado: " )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Total digitado: ", "Total Digitado: " )
		#define STR0023 If( cPaisLoc $ "ANG|EQU|HAI", "Total Débito: ", If( cPaisLoc $ "MEX|PTG", "Total de débito: ", "Total Débito: " ) )
		#define STR0024 If( cPaisLoc $ "ANG|EQU|HAI", "Total Crédito: ", If( cPaisLoc $ "MEX|PTG", "Total de crédito: ", "Total Crédito: " ) )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Total Indicado Lote", "Total Informado Lote" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Descrição Da Entidade:", "Descrição da Entidade:" )
		#define STR0027 "Histórico Inteligente"
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Sub-lote", "Sublote" )
		#define STR0029 "Legenda"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Capacidade do Lote: Lançamentos Contabilísticos", "Capa de Lote: Lançamentos Contábeis" )
		#define STR0031 "Conta Débito"
		#define STR0032 "Conta Crédito"
		#define STR0033 "Histórico"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Total Digitado Do Docto", "Total Informado Docto" )
		#define STR0035 "Correlativo"
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Não é possível a alteração/eliminação de documento criado pelo apuro de lucros/perdas..", "Não é possivel a alteração/exclusão de documento gerado pela apuração de lucros/perdas.." )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Favor rodar o procedimento de estorno de apuro de lucros/perdas..", "Favor rodar a rotina de estorno de apuração de lucros/perdas.." )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Existe valor nalguma moeda que não tem calendário contabilístico registado", "Existe valor em alguma moeda que não tem calendário contábil cadastrado" )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Tem Certeza Que Deseja Excluir O Lançamento?", "TEM CERTEZA QUE DESEJA EXCLUIR O LANÇAMENTO?" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Não será possível eliminar este lançamento. Desbloquear o período..", "Não será possível excluir esse lançamento. Favor desbloquear o período.." )
		#define STR0041 "Totais do lote e documento (outras moedas)"
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Total doc. ", "Total Doc. " )
		#define STR0043 "Total lote "
		#define STR0044 "Diferença em "
		#define STR0045 " do "
		#define STR0046 "Rastrear"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", 'INconsistência Anterior', "Inconsistência Anterior" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", 'PRóxima Inconsistência', "Próxima Inconsistência" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", 'A localizar', "Localizar" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "&estornar", "Es&tornar" )
		#define STR0051 "Copiar"
		#define STR0052 "Anterior"
		#define STR0053 "Próxima"
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Detalhes do movimento posicionado", "Detalhes do lançamento posicionado" )
		#define STR0055 "Detalhes"
		#define STR0056 "Replicar o conteúdo do campo posicionado"
		#define STR0057 "Replicar"
		#define STR0058 "Documento"
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Movimentos", "Lançamentos" )
		#define STR0060 "Atenção!"
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Confirmar exclusão dos movimentos seleccionados ?", "Confirma exclusão dos lançamentos selecionados ?" )
		#define STR0062 "Sim"
		#define STR0063 "Não"
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "Replicar conteúdo do campo em todas linhas anteriores", "Replicar conteúdo do campo em todas as linhas anteriores" )
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Replicar conteúdo do campo em todas linhas abaixo", "Replicar conteúdo do campo em todas as linhas abaixo" )
		#define STR0066 "Condição"
		#define STR0067 "Replicar "
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Confirmar substituição do conteúdo nos campos seleccionados ?", "Confirma substituição do conteúdo nos campos selecionados ?" )
		#define STR0069 "Log Exclusão"
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Deseja realizar o devolução por lote?", "Deseja realizar o estorno por lote?" )
		#define STR0071 "Estorno de lançamento por lote"
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Inverter Selecção", "Inverte Seleção" )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Data/lote/sublote/documento", "Data/Lote/Sublote/Documento" )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "A Seleccionar Registos...", "Selecionando Registros..." )
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Período bloqueado.verficar calendário contabilístico ", "Período bloqueado.Verficar calendário contábil. " )
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Log Válidação Devolução/exclusão Por Lote", "Log Validação Estorno/Exclusão por Lote" )
		#define STR0077 "Este relatório irá imprimir o relatório de inconsistências"
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "dos lançamentos que deveriam ser excluídos/estornados.", "dos lançamentos que devem ser excluídos/estornados." )
		#define STR0079 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0080 "Administração"
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "Data         Lote     Sublote     Doc      Inconsistência", "DATA         LOTE     SUBLOTE     DOC      INCONSISTÊNCIA" )
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Devolução criado com sucesso.", "Estorno gerado com sucesso." )
		#define STR0083 "Sublote"
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Verificar se as entidades contabilísticas estão correctas.", "Verificar se as entidades contábeis estão corretas." )
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "Verificar se alguma das entidades contabilísticas está bloqueada.", "Verificar se alguma das entidades contábeis está bloqueada." )
		#define STR0086 "Deseja realizar a exclusão por lote?"
		#define STR0087 "Exclusão realizada com sucesso."
		#define STR0088 "Nenhum lote foi excluído ou estornado."
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "Lançamentos de apuramento não poderão ser excluídos ou estornados.", "Lançamentos de apuração não poderão ser excluídos ou estornados." )
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "A recalcular totais...", "Recalculando totais..." )
		#define STR0091 If( cPaisLoc $ "ANG|PTG", "Rec.totais", "Rec.Totais" )
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "Exibir mensagens de actualização de marcas de contabilização durante o processamento?", "Exibir mensagens de atualização de flags de contabilização durante o processamento?" )
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "Exclusão Por Lote", "Exclusão por Lote" )
		#define STR0094 "Não é possível utilizar uma LP definida como ponto de lançamento"
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Documento em uso por outro utilizador!", "Documento em uso por outro usuário!" )
		#define STR0096 "Esta operação não é permitida para lançamentos complementares."
		#define STR0097 "Se deseja realizá-la, faça-a no lançamento principal."
		#define STR0098 "Lançamento complementar"
		#define STR0099 "Cópia não permitida. Cópia somente na filial corrente."
		#define STR0100 "Fechar"
		#define STR0101 If( cPaisLoc $ "ANG|PTG", "O campo histórico excedeu o limite de: ", "O campo Histórico excedeu o limite de: " )
		#define STR0102 " caracteres."
		#define STR0103 "Quantidade digitada: "
		#define STR0104 "Histórico"
		#define STR0105 "ESTORNO"
		#define STR0106 "Bloqueado. Verificar Moeda x Calend. x Tp.Saldo. "
		#define STR0107 "Tp.Saldo: "
		#define STR0108 "Cópia Filial"
		#define STR0109 "Cópia para Filial"
		#define STR0110 "Filial"
		#define STR0111 "Filial não existe."
		#define STR0112 "Usuário"
		#define STR0113 "O Sistema não localizou lançamentos para envio dos dados."
		#define STR0114 "Aviso de Contabilização Manual"
		#define STR0115 "Usuário sem acesso a inclusão. Contate o administrador do sistema."
		#define STR0116 "Acesso Negado - CTBAACCBLQ"
		#define STR0117 "Alias WT"
		#define STR0118 If( cPaisLoc $ "ANG|PTG", "Recno WT", "Recno WI" )
		#define STR0119 "Lçt.Extemp"
		#define STR0120 "Origem: Campo Obrigatório"
		#define STR0121 "Deve existir pelo menos uma sequência ativa no LP informado"
		#define STR0122 "Lct Transf. Saldo"
	#endif
#endif
