#ifdef SPANISH
	#define STR0001 "Libro mayor plan referencial"
	#define STR0002 "Este programa  imprimira el libro mayor del plan de cuentas referencial"
	#define STR0003 "Cta.Ref.Deb."
	#define STR0004 "Cta.Ref.Cred."
	#define STR0005 "Cuenta"
	#define STR0006 "Cuenta Ref."
	#define STR0007 "Lote/Sublote/Doc./Linea"
	#define STR0008 "Tipo"
	#define STR0009 "Plan Ref. y Version no registrados en el Arch. Plan referencial."
	#define STR0010 "Plan referencial y/o version no completados. "
	#define STR0011 "Cuenta Ref. sin movimiento"
	#define STR0012 " T O T A L "
	#define STR0013 " Total del informe "
	#define STR0014 " Total debito  "
	#define STR0015 " Total credito"
	#define STR0016 " Total de la cuenta referencial "
	#define STR0017 "Descripcion"
	#define STR0018 "Fecha"
	#define STR0019 "Valor"
	#define STR0020 "Funcion disponible solamente para que TReport verifique parametro MV_TREPORT"
	#define STR0021 "Partida doble"
	#define STR0022 "Saldo"
	#define STR0023 "Saldo actual"
	#define STR0024 "Débito"
	#define STR0025 "Crédito"
	#define STR0026 "Historial"
	#define STR0027 "Version"
#else
	#ifdef ENGLISH
		#define STR0001 "Referential Plan Ledger"
		#define STR0002 "This program prints the reference chart of accounts ledger"
		#define STR0003 "Deb Ref Acc"
		#define STR0004 "Cred Ref Acc"
		#define STR0005 "Account"
		#define STR0006 "Ref Account"
		#define STR0007 "Batch/Sub-batch/Doc/Row"
		#define STR0008 "Type"
		#define STR0009 "Ref Plan and Version not registered in Referential Plan Register."
		#define STR0010 "Referential Plan and/or Version not completed. "
		#define STR0011 "Ref. Acc without transaction"
		#define STR0012 "T O T A L"
		#define STR0013 " Report Total "
		#define STR0014 " Debit Total  "
		#define STR0015 " Credit Total"
		#define STR0016 " Referential Account Total "
		#define STR0017 "Description"
		#define STR0018 "Date"
		#define STR0019 "Value"
		#define STR0020 "Function available TReport only. Check MV_TREPORT parameter"
		#define STR0021 "Counter Entry"
		#define STR0022 "Balance"
		#define STR0023 "Current balance"
		#define STR0024 "Debit"
		#define STR0025 "Credit"
		#define STR0026 "History"
		#define STR0027 "Version"
	#else
		#define STR0001 "Razão Plano Referencial"
		#define STR0002 "Este programa ira  imprimir o razão do plano de contas referencial"
		#define STR0003 "Cta.Ref.Deb."
		#define STR0004 "Cta.Ref.Cred."
		#define STR0005 "Conta"
		#define STR0006 "Conta Ref."
		#define STR0007 "Lote/SubLote/Doc./Linha"
		#define STR0008 "Tipo"
		#define STR0009 "Plano Ref. e Versao não cadastrados no Cad. Plano Referencial."
		#define STR0010 "Plano Referencial e/ou Versão não preenchidos. "
		#define STR0011 "Conta Ref. sem movimento"
		#define STR0012 " T O T A L "
		#define STR0013 " Total do Relatório "
		#define STR0014 " Total Débito  "
		#define STR0015 " Total Crédito"
		#define STR0016 " Total da conta referencial "
		#define STR0017 "Descrição"
		#define STR0018 "Data"
		#define STR0019 "Valor"
		#define STR0020 "Função disponível apenas TReport, verificar parametro MV_TREPORT"
		#define STR0021 "Conta Partida"
		#define STR0022 "Saldo"
		#define STR0023 "Saldo atual"
		#define STR0024 "Débito"
		#define STR0025 "Crédito"
		#define STR0026 "Historico"
		#define STR0027 "Versão"
	#endif
#endif
