#ifdef SPANISH
	#define STR0001 "Visualizar"
	#define STR0002 "Incluir"
	#define STR0003 "Modificar"
	#define STR0004 "Borrar"
	#define STR0005 "Borrar en lote"
	#define STR0006 "Importar plan de cuentas"
	#define STR0007 "Importación no ejecutada - Ya existen registros incluidos para el intervalo definido"
	#define STR0008 "Efectuando la grabación de los registros del bloque K200"
	#define STR0009 "Importación concluida con éxito"
	#define STR0010 "Eliminación concluida con éxito"
	#define STR0011 "Eliminación no permitida, porque la cuenta está en uso"
	#define STR0012 "Registro del bloque K030 no informado - Parámetro 01"
	#define STR0013 "Borrando intervalo seleccionado."
	#define STR0014 "Verificando registros de saldos (K300)."
	#define STR0015 "Grabando registros en las tablas del bloque K200."
	#define STR0016 "Borrando registros para el bloque K200."
	#define STR0017 "Verifique registros incluidos en el bloque K300."
	#define STR0018 "Verifique intervalo informado."
	#define STR0019 "Archivo del Bloque K - Plan de cuentas consolidado"
	#define STR0020 "Bloque K200 - Plan de cuentas consolidado"
	#define STR0021 "Registro K200: plan de cuentas consolidado"
	#define STR0022 "Registro K210: mapeo del plan de cuentas de empresas consolidadas"
	#define STR0023 "El intervalo de cuentas no se informó correctamente."
	#define STR0024 "Complete el parámetro A cuenta"
	#define STR0025 "Registro K030 no informado."
	#define STR0026 "Complete el parámetro Registro K030"
	#define STR0027 " Espere..."
	#define STR0028 "Borrado de registros"
	#define STR0029 "Consulta CQU"
	#define STR0030 "Grabando K200"
	#define STR0031 "Cuenta sintética no permite inclusión del panel K210"
	#define STR0032 "Verifique la modalidad de la cuenta."
	#define STR0033 "No es posible incluir el panel K210 sin tener el ID del bloque K informado."
	#define STR0034 "Complete el campo Id.Bloque K (CQU_IDBLK)."
	#define STR0035 "Registro K210 no modificado."
	#define STR0036 "Verifique la cuenta incluida manualmente. Esta permitirá modificar si fuera igual a la cuenta del K200."
	#define STR0037 "Los registros K210 ya se informaron anteriormente."
	#define STR0038 "¿Desea sobrescribir la columna de la cuenta de la empresa (cuyas cuentas se informaron automáticamente) con la nueva cuenta informada?"
	#define STR0039 "Importante: No será así con las cuentas del bloque K210 que se completaron manualmente."
	#define STR0040 "Campo Flag"
#else
	#ifdef ENGLISH
		#define STR0001 "View"
		#define STR0002 "Add"
		#define STR0003 "Edit"
		#define STR0004 "Delete"
		#define STR0005 "Delete in Lots"
		#define STR0006 "Import Chart of Accounts"
		#define STR0007 "Import not executed - Some records already exist for the interval set"
		#define STR0008 "Saving block K200 records"
		#define STR0009 "Import successfully completed"
		#define STR0010 "Deletion successfully completed"
		#define STR0011 "Deletion not allowed, because the account is in use"
		#define STR0012 "Record of block K030 not entered - Parameter 01"
		#define STR0013 "Deleting selected interval."
		#define STR0014 "Checking balance records (K300)."
		#define STR0015 "Saving records in block K200 tables."
		#define STR0016 "Deleting records for block K200."
		#define STR0017 "Check records registered in block K300."
		#define STR0018 "Check entered interval."
		#define STR0019 "Block K Register - Consolidated Chart of Accounts"
		#define STR0020 "Block K200 - Consolidated Chart of Accounts"
		#define STR0021 "Record K200: Consolidated Chart of Accounts"
		#define STR0022 "Record K210: Consolidated Companies Chart of Accounts Mapping"
		#define STR0023 "Accounts interval not correctly entered."
		#define STR0024 "Fill out parameter Account To"
		#define STR0025 "Record K030 not entered."
		#define STR0026 "Fill out parameter Record K030"
		#define STR0027 " Wait..."
		#define STR0028 "Deletion of Records"
		#define STR0029 "CQU Query"
		#define STR0030 "Saving K200"
		#define STR0031 "Synthetic Account does not allow the inclusion of the K210 panel"
		#define STR0032 "Check the nature of the account."
		#define STR0033 "You cannot enter K210 panel without having the ID of the Block K entered."
		#define STR0034 "Enter field Id.Block K (CQU_IDBLK)."
		#define STR0035 "K210 Record not changed."
		#define STR0036 "Check account manually added. It will allow the modification in case it is equal to K200."
		#define STR0037 "Records K210 already filled out previously."
		#define STR0038 "Overwrite the Company Account column (the accounts of which were automatically filled out) with the new account entered?"
		#define STR0039 "Important: Block K210 accounts filled out manually will not be overwritten."
		#define STR0040 "Flag Field"
	#else
		#define STR0001 "Visualizar"
		#define STR0002 "Incluir"
		#define STR0003 "Alterar"
		#define STR0004 "Excluir"
		#define STR0005 "Excluir em Lote"
		#define STR0006 "Importar Plano de Contas"
		#define STR0007 "Importação não executada - Já existem registros cadastrados para o intervalo definido"
		#define STR0008 "Efetuando gravação dos registros do bloco K200"
		#define STR0009 "Importação concluída com sucesso"
		#define STR0010 "Deleção concluída com sucesso"
		#define STR0011 "Deleção não permitida, pois a conta esta em uso"
		#define STR0012 "Registro do bloco K030 não informado - Parâmetro 01"
		#define STR0013 "Excluíndo intervalo selecionado."
		#define STR0014 "Verificando registros de saldos (K300)."
		#define STR0015 "Gravando registros nas tabelas do bloco K200."
		#define STR0016 "Excluíndo registros para bloco K200."
		#define STR0017 "Verifique registros cadastrados no bloco K300."
		#define STR0018 "Verifique intervalo informado."
		#define STR0019 "Cadastro do Bloco K - Plano de Contas Consolidado"
		#define STR0020 "Bloco K200 - Plano de Contas Consolidado"
		#define STR0021 "Registro K200: Plano de Contas Consolidado"
		#define STR0022 "Registro K210: Mapeamento Plano de Contas Empresas Consolidadas"
		#define STR0023 "Intervalo de contas não foi informado corretamente."
		#define STR0024 "Preencha o parâmetro Conta Até"
		#define STR0025 "Registro K030 não informado."
		#define STR0026 "Preencha o parâmetro Registro K030"
		#define STR0027 " Aguarde..."
		#define STR0028 "Exclusão de Registros"
		#define STR0029 "Consulta CQU"
		#define STR0030 "Gravando K200"
		#define STR0031 "Conta Sintética não permite inclusão do painel K210"
		#define STR0032 "Verifique a natureza da conta."
		#define STR0033 "Não é possivel incluir o painel K210 sem possuir o ID do bloco K informado."
		#define STR0034 "Preencha o campo Id.Bloco K (CQU_IDBLK)."
		#define STR0035 "Registro K210 não alterado."
		#define STR0036 "Verifique a conta inserida manualmente. Ela permitirá alteração se for igual a conta do K200."
		#define STR0037 "Os registros K210 já foram preenchidos anteriormente."
		#define STR0038 "Deseja Sobrescrever a coluna de Conta da Empresa (cujas contas foram preenchidas automaticamente) com a nova conta informada? "
		#define STR0039 "Importante: Contas do bloco K210 que foram preenchidas manualmente, não serão."
		#define STR0040 "Campo Flag"
	#endif
#endif
