#ifdef SPANISH
	#define STR0001 "Semaforo de procesamiento... intento "
	#define STR0002 "Espere, otro usuario está creando el semáforo."
	#define STR0003 "Creacion de semaforo de procesamiento."
	#define STR0004 "No fue posible acceso exclusivo para crear el semaforo de procesamiento."
	#define STR0005 "Repetir"
	#define STR0006 "Cerrar"
	#define STR0007 "¡Atencion!"
	#define STR0008 "Este proceso esta siendo utilizado con parametros en conflicto (mismo periodo o carteras) con el usuario "
	#define STR0009 " en este momento. Verifique el periodo y los parametros seleccionados para el procesamiento o intente nuevamente mas tarde."
	#define STR0010 "Se realizaron "
	#define STR0011 " intentos de actualizacion de saldo sin exito."
	#define STR0012 "Es posible grabar los asientos dejando la actualizacion de saldos para ejecucion, por medio del 'Reprocesamiento de saldos'."
	#define STR0013 "Seleccione 'Ok' para grabar asientos sin actualizar saldos (recomendado), o, "
	#define STR0014 "Seleccione 'Anular' para intentar nuevamente la grabacion con la actualizacion de saldos."
	#define STR0015 "Esperando la liberacion de registros...Intento: "
	#define STR0016 "¡Cuentas en uso por otro usuario!"
	#define STR0017 "¡Error en la creación del semáforo de procesamientos concurrentes, semáforo deshabilitado!"
	#define STR0018 "¡Error en la apertura del semáforo de procesamientos concurrentes, semáforo deshabilitado!"
	#define STR0019 "Informe la Fechas inicial y final para el Procesamiento o verifique si la Fecha inicial no es mayor que la Fecha final."
#else
	#ifdef ENGLISH
		#define STR0001 "Process semaphore... attempt "
		#define STR0002 "Wait, semaphore being created by another user."
		#define STR0003 "Semaphore Creation Process."
		#define STR0004 "Unable to obtain exclusive access to create process semaphore."
		#define STR0005 "Repeat"
		#define STR0006 "Close"
		#define STR0007 "Attention!"
		#define STR0008 "This process is being used with conflicting parameters ( same term or portfolios ) with the user "
		#define STR0009 " at the moment. Check the term and parameters selected for processing or try again later."
		#define STR0010 "Were performed "
		#define STR0011 " balance update attempts with no luck !"
		#define STR0012 "It is possible to record entries leaving the balance update for execution via 'Balance Reprocessing'."
		#define STR0013 "Select 'Ok' to record entries without updating balances (recommended), or, "
		#define STR0014 "Select 'Cancel' to try to record again with balance update."
		#define STR0015 "Awaiting record release...Attempt: "
		#define STR0016 "Accounts in use by another user !"
		#define STR0017 "Error at creation of competitor processing traffic light. Traffic light disabled."
		#define STR0018 "Error opening concurrent processing semaphore. Semaphore disabled."
		#define STR0019 "Enter Start and End Dates for the processing or check if Start Date is Not Later than End!"
	#else
		#define STR0001 "Semaforo de processamento... tentativa "
		#define STR0002 "Aguarde, semaforo sendo criado por outro usuário."
		#define STR0003 "Criação de Semaforo de processamento."
		#define STR0004 "Não foi possivel acesso exclusivo para criar o semaforo de processamento."
		#define STR0005 "Repetir"
		#define STR0006 "Fechar"
		#define STR0007 "Atenção!"
		#define STR0008 "Este processo esta sendo utilizado com parametros conflitantes ( mesmo periodo ou carteiras ) com o usuário "
		#define STR0009 " no momento. Verifique o período e os parametros selecionados para o processamento ou tente novamente mais tarde."
		#define STR0010 "Foram efetuadas "
		#define STR0011 " tentativas de atualização de saldo sem sucesso !"
		#define STR0012 "É possível gravar os lançamento deixando a atualização de saldos para execução através do 'Reprocessamento de Saldos'."
		#define STR0013 "Selecione 'Ok' para gravar lançamentos sem atualizar saldos (recomendado), ou, "
		#define STR0014 "Selecione 'Cancelar' para tentar novamente a gravação com atualização de saldos."
		#define STR0015 "Aguardando liberação de registros...Tentativa: "
		#define STR0016 "Conta(s) em uso por outro usuário !"
		#define STR0017 "Erro na criação do semaforo de processamentos concorrentes, semaforo desabilitado !"
		#define STR0018 "Erro na abertura do semaforo de processamentos concorrentes, semaforo desabilitado !"
		#define STR0019 "Informar as Datas Inicio e Fim para o Processamento ou verificar se Data Início Não é Maior que a Data Fim !"
	#endif
#endif
