#ifdef SPANISH
	#define STR0001 "Verificación Recepción"
	#define STR0002 "Recepción"
	#define STR0003 "No Iniciado"
	#define STR0004 "En ejecucion"
	#define STR0005 "Verificado"
	#define STR0006 "Montaje"
	#define STR0007 "Monitor"
	#define STR0008 "Borrar"
	#define STR0009 "Registrar"
	#define STR0010 "¿Confirma la liberación del producto sin verificación?"
	#define STR0011 "Finalizar verificación"
	#define STR0012 "Reabrir verificación"
	#define STR0013 "Informe CHECK-OUT"
	#define STR0014 "Revertir verificación"
	#define STR0015 "Documentos"
	#define STR0016 "Incluir"
	#define STR0017 "Productos"
	#define STR0018 "¿Confirma la reversión de todo el proceso de verificación?"
	#define STR0019 "¿Confirma la reapertura del proceso de verificación?"
	#define STR0020 "Operadores"
	#define STR0021 "Existen divergencias en la verificacion que impiden la finalizacion"
	#define STR0022 "¿Confirma la finalización del proceso de verificación?"
	#define STR0023 "Finalización no permitida. No se verificó ninguna cantidad."
	#define STR0024 "Cobro verificado, ¡operacion no permitida!"
	#define STR0025 "¡Finalizacion permitida solo para cobro en ejecucion!"
	#define STR0026 "¡Reversion permitida solo para cobro en ejecucion!"
	#define STR0027 "¡Reapertura permitida solo para cobro conferido!"
	#define STR0028 "Reapertura no permitida, ¡cobro tiene documento ya almacenado!"
	#define STR0029 "Borrado del documento no permitido, ¡borre el cobro!"
	#define STR0030 "¡Borrado permitido únicamente para verificación no iniciada!"
	#define STR0031 "¡No hay cantidad verificada para el producto!"
	#define STR0032 "¡Verificación finalizada por otro proceso!"
	#define STR0033 "Se encontraron divergencias en el conteo. ¿Confirma finalización?"
	#define STR0034 "Visualizar"
	#define STR0035 "Liberar producto"
	#define STR0036 "Liberación sin verificación permitida únicamente cuando no existe ninguna cantidad verificada para el producto."
	#define STR0037 "Efectúe la reapertura de la verificación de recepción para poder incluir un nuevo documento."
	#define STR0038 "¡Finalizacion permitida solamente para cobro con cantidad verificada mayor que cero!"
	#define STR0039 "Verificado con divergencia"
	#define STR0040 "Revertir producto"
	#define STR0041 "Revertir ítem"
	#define STR0042 "Conferir ítem"
	#define STR0043 "Revertir operador"
	#define STR0044 "No fue posible finalizar la verificación."
	#define STR0045 "Efectúe la reapertura de la verificación de recepción para poder revertir el proceso."
	#define STR0046 "Revierta la cantidad verificada para este producto."
	#define STR0047 "Elija otro producto que tenga una cantidad verificada."
	#define STR0048 "No es posible que exista un proceso de verificación de recepción sin ningún documento vinculado."
	#define STR0049 "Revierta todo el proceso de verificación de recepción, para después borrar el proceso."
	#define STR0050 "Efectúe la reapertura de la verificación de recepción para poder borrar el documento actual."
	#define STR0051 "Efectúe la reapertura de la verificación de recepción para poder verificar un nuevo ítem."
	#define STR0052 "Efectúe la reapertura de la verificación de recepción para liberar el producto sin verificación."
#else
	#ifdef ENGLISH
		#define STR0001 "Receipt Check"
		#define STR0002 "Receipt"
		#define STR0003 "Not Started"
		#define STR0004 "In progress"
		#define STR0005 "Checked"
		#define STR0006 "Creation"
		#define STR0007 "Monitor"
		#define STR0008 "Delete"
		#define STR0009 "Register"
		#define STR0010 "Confirm approval of product without checking?"
		#define STR0011 "End Checking"
		#define STR0012 "Reopen Checking"
		#define STR0013 "CHECK-OUT Report"
		#define STR0014 "Reverse Checking"
		#define STR0015 "Documents"
		#define STR0016 "Add"
		#define STR0017 "Products"
		#define STR0018 "Confirm reverse of the entire checking process?"
		#define STR0019 "Confirm reopen of checking process?"
		#define STR0020 "Operators"
		#define STR0021 "When checking, divergences were found, preventing completion."
		#define STR0022 "Confirm termination of the checking process?"
		#define STR0023 "Termination not allowed. No amount was checked."
		#define STR0024 "Receiving checked, operation not allowed!"
		#define STR0025 "Termination allowed for receiving in progress only!"
		#define STR0026 "Reversal allowed for receiving in progress only!"
		#define STR0027 "Reopening allowed for checked receiving only!"
		#define STR0028 "Reopening not allowed, receiving has document already stored!"
		#define STR0029 "Document exclusion not allowed, delete the receiving!"
		#define STR0030 "Deletion allowed only for checking not started!"
		#define STR0031 "There is no checked amount for the product!"
		#define STR0032 "Checking already performed by another process!"
		#define STR0033 "Divergences found in count. Confirm closing?"
		#define STR0034 "View"
		#define STR0035 "Release Product"
		#define STR0036 "Release with no checking allowed only when there is no amount checked for the product!"
		#define STR0037 "Reopen the receipt checking to include a new document."
		#define STR0038 "Termination allowed only for receiving with quantity checked greater than zero!"
		#define STR0039 "Checking presents deviation"
		#define STR0040 "Reverse Product"
		#define STR0041 "Reverse Item"
		#define STR0042 "Check Item"
		#define STR0043 "Reverse Operator"
		#define STR0044 "Unable to complete checking."
		#define STR0045 "Reopen the receipt checking to reverse the process."
		#define STR0046 "Reverse the amount checked for this product."
		#define STR0047 "Select another product with checked amount."
		#define STR0048 "Unable to exist a receipt checking process with any associated documented."
		#define STR0049 "Reverse the whole receipt conference process, and then delete the process."
		#define STR0050 "Reopen the receipt checking to delete the current document."
		#define STR0051 "Reopen the receipt checking to check a new item."
		#define STR0052 "Reopen the receipt checking to release the product without checking."
	#else
		#define STR0001 "Conferência Recebimento"
		#define STR0002 "Recebimento"
		#define STR0003 "Não iniciado"
		#define STR0004 "Em andamento"
		#define STR0005 "Conferido"
		#define STR0006 "Montagem"
		#define STR0007 "Monitor"
		#define STR0008 "Excluir"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Registar", "Registrar" )
		#define STR0010 "Confirma a liberação do produto sem conferência?"
		#define STR0011 "Finalizar Conferência"
		#define STR0012 "Reabrir Conferência"
		#define STR0013 "Relatório CHECK-OUT"
		#define STR0014 "Estornar Conferência"
		#define STR0015 "Documentos"
		#define STR0016 "Incluir"
		#define STR0017 "Produtos"
		#define STR0018 "Confirma o estorno de todo o processo de conferência?"
		#define STR0019 "Confirma a reabertura do processo de conferência?"
		#define STR0020 "Operadores"
		#define STR0021 "Existem divergências na conferência que impedem a finalização"
		#define STR0022 "Confirma a finalização do processo de conferência?"
		#define STR0023 "Finalização não permitida. Não foi conferido nenhuma quantidade."
		#define STR0024 "Recebimento conferido, operação não permitida!"
		#define STR0025 "Finalização permitida somente para recebimento em andamento!"
		#define STR0026 "Estorno permitido somente para recebimento em andamento!"
		#define STR0027 "Reabertura permitida somente para recebimento conferido!"
		#define STR0028 "Reabertura não permitida, recebimento possui documento já armazenado!"
		#define STR0029 "Exclusão documento não permitida, exclua o recebimento!"
		#define STR0030 "Exclusão permitida somente para conferência não iniciada!"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Não há quantidade conferida para o artigo.", "Não há quantidade conferida para o produto!" )
		#define STR0032 "Conferencia já finalizada por outro processo!"
		#define STR0033 "Foram encontradas divergencias na contagem. Confirma encerramento?"
		#define STR0034 "Visualizar"
		#define STR0035 "Liberar Produto"
		#define STR0036 "Liberação sem conferência permitida somente quando não existe nenhuma quantidade conferida para o produto!"
		#define STR0037 "Efetue a reabertura da conferência de recebimento para poder incluir um novo documento."
		#define STR0038 "Finalização permitida somente para recebimento com quantidade conferida maior que zero!"
		#define STR0039 "Conferido com divergência"
		#define STR0040 "Estornar Produto"
		#define STR0041 "Estornar Item"
		#define STR0042 "Conferir Item"
		#define STR0043 "Estornar Operador"
		#define STR0044 "Não foi possível finalizar a conferência."
		#define STR0045 "Efetue a reabertura da conferência de recebimento para poder estornar o processo."
		#define STR0046 "Estorne a quantidade conferida para este produto."
		#define STR0047 "Escolha outro produto que possua quantidade conferida."
		#define STR0048 "Não é possivel existir um processo de conferência de recebimento sem nenhum documento associado."
		#define STR0049 "Estorne todo o processo de conferência do recebimento, para então excluir o processo."
		#define STR0050 "Efetue a reabertura da conferência de recebimento para poder excluir o documento atual."
		#define STR0051 "Efetue a reabertura da conferência de recebimento para poder conferir um novo item."
		#define STR0052 "Efetue a reabertura da conferência de recebimento para liberar o produto sem conferência."
	#endif
#endif
