#ifdef SPANISH
	#define STR0001 "Relatório de pré-escopo"
	#define STR0002 "Zebrado"
	#define STR0003 "Administracao"
	#define STR0004 "Atenção"
	#define STR0005 "Proposta informada não encontrada!"
	#define STR0006 "Aguarde analisando projeto informado..."
	#define STR0007 "Nao existes itens no projeto"
	#define STR0008 "EDT/TAREFA"
	#define STR0009 "Descricao"
	#define STR0010 "Quantidade"
	#define STR0011 "Proposta Comercial: "
	#define STR0012 " Simulação: "
	#define STR0013 " - Versão: "
	#define STR0014 "Deseja exportar projeto novamente?"
	#define STR0015 "Não há dados!"
	#define STR0016 "Proposta informado não possui projeto criado"
	#define STR0017 "Este relatório imprime o escopo e as funcionalidades conforme estrutura da EDT."
	#define STR0018 "Aguarde..."
	#define STR0019 "Processando registros..."
	#define STR0020 "Proposta comercial informada não possui serviço (simulador de horas) vinculada!"
#else
	#ifdef ENGLISH
		#define STR0001 "Pre scope report"
		#define STR0002 "Z-form"
		#define STR0003 "Management"
		#define STR0004 "Attention"
		#define STR0005 "Proposal entered not found!"
		#define STR0006 "Wait, analyzing project..."
		#define STR0007 "No items in the project"
		#define STR0008 "EDT/TASK"
		#define STR0009 "Description"
		#define STR0010 "Quantity"
		#define STR0011 "Commercial Proposal: "
		#define STR0012 " Simulation "
		#define STR0013 " - Version: "
		#define STR0014 "Export project again?"
		#define STR0015 "There are no data!"
		#define STR0016 "Proposal entered does not have created project"
		#define STR0017 "This report prints the scope and features according to EDT structure."
		#define STR0018 "Wait..."
		#define STR0019 "Processing records..."
		#define STR0020 "Business proposal indicated does not have service (hours simulator) linked."
	#else
		#define STR0001 "Relatório de pré-escopo"
		#define STR0002 "Zebrado"
		#define STR0003 "Administracao"
		#define STR0004 "Atenção"
		#define STR0005 "Proposta informada não encontrada!"
		#define STR0006 "Aguarde analisando projeto informado..."
		#define STR0007 "Nao existes itens no projeto"
		#define STR0008 "EDT/TAREFA"
		#define STR0009 "Descricao"
		#define STR0010 "Quantidade"
		#define STR0011 "Proposta Comercial: "
		#define STR0012 " Simulação: "
		#define STR0013 " - Versão: "
		#define STR0014 "Deseja exportar projeto novamente?"
		#define STR0015 "Não há dados!"
		#define STR0016 "Proposta informado não possui projeto criado"
		#define STR0017 "Este relatório imprime o escopo e as funcionalidades conforme estrutura da EDT."
		#define STR0018 "Aguarde..."
		#define STR0019 "Processando registros..."
		#define STR0020 "Proposta comercial informada não possui serviço (simulador de horas) vinculada!"
	#endif
#endif
