#ifdef SPANISH
	#define STR0001 "Presupuesto vs. Ajustado"
	#define STR0002 "                                                                                                     Horas propuesta      Horas originales    "
	#define STR0003 "A rayas"
	#define STR0004 "Administracion"
	#define STR0005 "Atencion"
	#define STR0006 "¡Propuesta informada no encontrada!"
	#define STR0007 "Espere analizando proyecto original..."
	#define STR0008 "Espere analizando proyecto informado..."
	#define STR0009 "No existen items en el proyecto"
	#define STR0010 "EDT/TAREA"
	#define STR0011 "Descripcion"
	#define STR0012 "Horas propuesta"
	#define STR0013 "Horas originales"
	#define STR0014 "Propuesta comercial: "
	#define STR0015 " Simulacion: "
	#define STR0016 " - Version: "
	#define STR0017 "¿Desea exportar proyecto nuevamente?"
	#define STR0018 "¡No hay datos!"
	#define STR0019 "Propuesta informada no tiene proyecto creado"
	#define STR0020 "Este informe imprime Presupuestado vs. Ajustado de acuerdo con la estructura de la EDT."
	#define STR0021 "Espere..."
	#define STR0022 "Procesando registros..."
#else
	#ifdef ENGLISH
		#define STR0001 "Quoted x Adjusted"
		#define STR0002 "                                                                                                     Hours Proposal             Original Hours    "
		#define STR0003 "Z-form"
		#define STR0004 "Management"
		#define STR0005 "Attention"
		#define STR0006 "Proposal entered not found!"
		#define STR0007 "Wait, analyzing original project..."
		#define STR0008 "Wait, analyzing project..."
		#define STR0009 "No items in the project"
		#define STR0010 "EDT/TASK"
		#define STR0011 "Description"
		#define STR0012 "Proposal Hours"
		#define STR0013 "Original Hours"
		#define STR0014 "Commercial Proposal: "
		#define STR0015 " Simulation "
		#define STR0016 " - Version: "
		#define STR0017 "Export project again?"
		#define STR0018 "There are no data!"
		#define STR0019 "Proposal entered does not have created project"
		#define STR0020 "This report prints Quoted x Adjusted according to EDT structure."
		#define STR0021 "Wait..."
		#define STR0022 "Processing records..."
	#else
		#define STR0001 "Orçado X Ajustado"
		#define STR0002 "                                                                                                     Horas Proposta      Horas Originais    "
		#define STR0003 "Zebrado"
		#define STR0004 "Administracao"
		#define STR0005 "Atenção"
		#define STR0006 "Proposta informada não encontrada!"
		#define STR0007 "Aguarde analisando projeto original..."
		#define STR0008 "Aguarde analisando projeto informado..."
		#define STR0009 "Nao existes itens no projeto"
		#define STR0010 "EDT/TAREFA"
		#define STR0011 "Descricao"
		#define STR0012 "Horas Proposta"
		#define STR0013 "Horas Originais"
		#define STR0014 "Proposta Comercial: "
		#define STR0015 " Simulação: "
		#define STR0016 " - Versão: "
		#define STR0017 "Deseja exportar projeto novamente?"
		#define STR0018 "Não há dados!"
		#define STR0019 "Proposta informado não possui projeto criado"
		#define STR0020 "Este relatório imprime Orçado X Ajustado conforme estrutura da EDT."
		#define STR0021 "Aguarde..."
		#define STR0022 "Processando registros..."
	#endif
#endif
