#ifdef SPANISH
	#define STR0001 "Formas de pago"
	#define STR0002 "Ausencia de tabla FJS - Ejecute compatibilizador"
	#define STR0003 "Buscar"
	#define STR0004 "Visualizar"
	#define STR0005 "Incluir"
	#define STR0006 "Modificar"
	#define STR0007 "Borrar"
	#define STR0008 "Este processo reclasificara la configuracion de Doc. de Tercereos de los Modos de Pago."
	#define STR0009 "Reclasificación"
	#define STR0010 "Actualizando Modo de Pago: "
	#define STR0011 "Conf. de Documento de Tercero invalida para la cartera "
	#define STR0012 "por Cobrar"
	#define STR0013 "por Pagar"
	#define STR0014 "El tipo interno que se configuro no acepta pago electronico."
	#define STR0015 "Para tipos que generan movimientos bancarios, se debe informar el tipo de banco."
	#define STR0016 "El tipo de valor debe informarse para los cheques."
	#define STR0017 "El tipo de valor diferido debe informarse para los documentos."
	#define STR0018 "El tipo de valor en efectivo debe informarse para pagos en efectivo."
	#define STR0019 "Para el tipo configurado, no es necesario informaro el tipo de valor."
	#define STR0020 "El Modo de pago no puede borrarse pues ya se utilizó"
#else
	#ifdef ENGLISH
		#define STR0001 "Payment Terms"
		#define STR0002 "Absence of table FJS - Run compatibility program"
		#define STR0003 "Search"
		#define STR0004 "View"
		#define STR0005 "Add"
		#define STR0006 "Edit"
		#define STR0007 "Delete"
		#define STR0008 "This process will reclassify the configuration of Third Parties of Payment Term."
		#define STR0009 "Reclassification"
		#define STR0010 "Updating Payment Term: "
		#define STR0011 "Conf. of Third Party Document invalid for the portfolio "
		#define STR0012 "Receivable"
		#define STR0013 "Payable"
		#define STR0014 "The configured internal type does not accept elect.payment."
		#define STR0015 "For types that generate bank transactions, bank type must be entered."
		#define STR0016 "The value type must be entered for checks."
		#define STR0017 "The deferred value type must be entered for documents."
		#define STR0018 "The cash value type must be entered for payments in cash."
		#define STR0019 "For the configures type, value type must not be entered."
		#define STR0020 "The Payment Mode cannot be deleted because it has been used"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Formas de pagamento", "Formas de Pagamento" )
		#define STR0002 "Ausência da tabela FJS - Execute compatibilizador"
		#define STR0003 "Pesquisar"
		#define STR0004 "Visualizar"
		#define STR0005 "Incluir"
		#define STR0006 "Alterar"
		#define STR0007 "Excluir"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Este processo reclassificará a configuração de Doc. de Terceiros dos Modos de Pagamento.", "Este processo irá reclassificar a configuração de Doc. de Terceiros dos Modos de Pago." )
		#define STR0009 "Reclassficação"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "A Actualizar Modo de Pagamento: ", "Atualizando Modo de Pago: " )
		#define STR0011 "Conf. de Documento de Terceiro inválida para a carteira "
		#define STR0012 "a Receber"
		#define STR0013 "a Pagar"
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "O tipo interno configurado não aceita pagamento electrónico.", "O tipo interno configurado não aceita pagamento eletrônico." )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Para tipos que geram movimentos bancários, deve-se informar o tipo de banco.", "Para tipos que geram movimientos bancarios, deve-se informar o tipo de banco." )
		#define STR0016 "O tipo de valor deve ser informado para os cheques."
		#define STR0017 "O tipo de valor diferido deve ser informado para os documentos."
		#define STR0018 "O tipo de valor à vista deve ser informado para pagamentos em dinheiro."
		#define STR0019 "Para o tipo configurado, não é necessário informar o tipo de valor."
		#define STR0020 "O Modo de Pago não pode ser excluido pois ja foi utilizado"
	#endif
#endif
