#ifdef SPANISH
	#define STR0001 "Procesando - DARF"
	#define STR0002 "Mensaje"
	#define STR0003 "No existen datos en el periodo informado"
	#define STR0004 "OK"
	#define STR0005 "Vencimiento inicial"
	#define STR0006 "Vencimiento final"
	#define STR0007 "Código SRF inicial"
	#define STR0008 "Código SRF final"
	#define STR0009 "Agrupa por"
	#define STR0010 "Periodo de cálculo"
	#define STR0011 "Número de referencia"
	#define STR0012 "Sucursal centralizadora"
	#define STR0013 "Modelo"
	#define STR0014 "Ingreso bruto"
	#define STR0015 "Porcentaje"
	#define STR0016 "Periodicidad"
	#define STR0017 "CNPJ de la incorporadora"
	#define STR0018 "1.Proveed./Cod.SRF"
	#define STR0019 "2.Apenas Cod. SRF"
	#define STR0020 "1. Comun"
	#define STR0021 "2. Sencillo"
	#define STR0022 "1. Diario"
	#define STR0023 "2. Semanal"
	#define STR0024 "3. Cada diez dias"
	#define STR0025 "4. Quincenal"
	#define STR0026 "5. Mensual"
	#define STR0027 "6. Trimestral"
	#define STR0028 "7. Cuatrimestral"
	#define STR0029 "8. Semestral"
	#define STR0030 "9. Anual"
	#define STR0031 "Selecciona Sucursales ?"
	#define STR0032 "1.Si"
	#define STR0033 "2.No"
	#define STR0034 "Sucursal: "
	#define STR0035 "El DARF no puede generarse con valor igual o inferior al mínimo definido en el parámetro MV_VLRETIR."
	#define STR0036 "Para la emisión de la DARF se considerará el RCPJ de la sucursal centralizadora. ¿Confirma la operación?"
	#define STR0037 "RCPJ no se ubicó el registro de la empresa, el DARF se emitirá en la sucursal Centralizadora. Confirma la operación."
	#define STR0038 "RCPJ informado no coincide con el RCPJ de la Sucursal centralizadora, el DARF se emitirá en la sucursal correspondiente al RCPJ informado. Confirma la operación."
	#define STR0039 "¿Considera el RCPJ del título?"
	#define STR0040 "1.Filtrar"
	#define STR0041 "2.Sustituido"
	#define STR0042 "Emisión DARF"
#else
	#ifdef ENGLISH
		#define STR0001 "Processing - DARF"
		#define STR0002 "Message"
		#define STR0003 "There are no data within the period informed"
		#define STR0004 "Ok"
		#define STR0005 "Initial Due Date"
		#define STR0006 "Final Due Date"
		#define STR0007 "Initial SRF Code"
		#define STR0008 "Final SRF Code"
		#define STR0009 "Groups by"
		#define STR0010 "Calculation Period"
		#define STR0011 "Reference Number"
		#define STR0012 "Center branch"
		#define STR0013 "Model"
		#define STR0014 "Gross Income"
		#define STR0015 "Percentage"
		#define STR0016 "Periodicity"
		#define STR0017 "CNPJ of merging company"
		#define STR0018 "1.SRF Cod./Supplier"
		#define STR0019 "2.only Code SRF"
		#define STR0020 "1.Common"
		#define STR0021 "2.Simple"
		#define STR0022 "1.Daily"
		#define STR0023 "2.Weekly"
		#define STR0024 "3.Every 10 days"
		#define STR0025 "4.Every 15 days"
		#define STR0026 "5.Monthly"
		#define STR0027 "6.Quarterly"
		#define STR0028 "7.Every 4 months"
		#define STR0029 "8.Semiannually"
		#define STR0030 "9.Annually"
		#define STR0031 "Select Branches ?"
		#define STR0032 "1.Yes"
		#define STR0033 "2.No"
		#define STR0034 "Branch: "
		#define STR0035 "DARF cannot be generated with value equal to or lower than the minimum set in parameter MV_VLRETIR"
		#define STR0036 "CNPJ of centralizing branch is considered for issue of DARF. Confirm operation?"
		#define STR0037 "CNPJ not located in the company's register. DARF is issued in centralizing branch. Confirm operation"
		#define STR0038 "CNPJ entered does not match the CNPJ of centralizing branch. DARF is issued in the branch corresponding to the CNPJ entered. Confirm operation"
		#define STR0039 "Consider CNPJ of bill?"
		#define STR0040 "1.Filter"
		#define STR0041 "2.Replaced"
		#define STR0042 "DARF Issue"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "A Processar - Darf", "Processando - DARF" )
		#define STR0002 "Mensagem"
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Não há dados no período inserido", "Nao há dados no periodo informado" )
		#define STR0004 "Ok"
		#define STR0005 "Vencimento inicial"
		#define STR0006 "Vencimento final"
		#define STR0007 "Codigo SRF inicial"
		#define STR0008 "Codigo SRF final"
		#define STR0009 "Agrupa por"
		#define STR0010 "Período de apuração"
		#define STR0011 "Numero de referência"
		#define STR0012 "Filial centralizadora"
		#define STR0013 "Modelo"
		#define STR0014 "Receita bruta"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Percentagem", "Percentual" )
		#define STR0016 "Periodicidade"
		#define STR0017 "CNPJ da incorporadora"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "1.Fornec./Cód.SRF", "1.Fornec./Cod.SRF" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "2.Apenas Cód. SRF", "2.Apenas Cod. SRF" )
		#define STR0020 "1.Comum"
		#define STR0021 "2.Simples"
		#define STR0022 "1.Diário"
		#define STR0023 "2.Semanal"
		#define STR0024 "3.Decendial"
		#define STR0025 "4.Quinzenal"
		#define STR0026 "5.Mensal"
		#define STR0027 "6.Trimestral"
		#define STR0028 "7.Quadrimestral"
		#define STR0029 "8.Semestral"
		#define STR0030 "9.Anual"
		#define STR0031 "Seleciona Filiais ?"
		#define STR0032 "1.Sim"
		#define STR0033 "2.Não"
		#define STR0034 "Filial : "
		#define STR0035 "DARF não pode ser gerada com valor igual ou inferior ao minimo definido no parâmetro MV_VLRETIR."
		#define STR0036 "Para emissão da DARF será considerado o CNPJ da filial centralizadora. Confirma a operação?"
		#define STR0037 "CNPJ não foi localizado do cadastro da empresa, DARF será emitida na  filial Centralizadora, Confirma a operação"
		#define STR0038 "CNPJ informado não confere com o CNPJ da Filial Centralizadora, DARF será emitida na  filial correspondente ao CNPJ informado, Confirma a operação"
		#define STR0039 "Considera CNPJ do título?"
		#define STR0040 "1.Filtrar"
		#define STR0041 "2.Substituido"
		#define STR0042 "Emissão DARF"
	#endif
#endif
