#ifdef SPANISH
	#define STR0001 "Atención"
	#define STR0002 "1- Proveedor"
	#define STR0003 "2- Cliente"
	#define STR0004 "3- Ambos"
	#define STR0005 "Dcto. 1205/2015 - IIBB - Padrón Sujetos No Pasibles de Percepción "
	#define STR0006 "Inf. Preliminar"
	#define STR0007 "Archivo"
	#define STR0008 "Impuesto: "
	#define STR0009 "Percepción"
	#define STR0010 "Retención"
	#define STR0011 "&Importación del Archivo CSV"
	#define STR0012 "Esta opción tiene como objetivo importar el archivo"
	#define STR0013 "Proveedor / Cliente  vs. Impuesto de acuerdo con el archivo CSV"
	#define STR0014 "Puesto a disposición del gobierno "
	#define STR0015 "Fecha inicial de vigencia:"
	#define STR0016 "&Importar"
	#define STR0017 "&Resumen"
	#define STR0018 "&Salir"
	#define STR0019 "Archivos (*.CSV) |*.CSV|"
	#define STR0020 "Resumen"
	#define STR0021 "Grabar como..."
	#define STR0022 "Seleccionar archivo"
	#define STR0023 "Archivo | *.CSV"
	#define STR0024 "Leyendo archivo. Espere..."
	#define STR0025 "Actualización de alícuotas"
	#define STR0026 " Período informado no corresponde al período del archivo. ("
	#define STR0027 "Período"
	#define STR0028 "Registro"
	#define STR0029 "Incluyendo Cliente"
	#define STR0030 "Modif. Alíc."
	#define STR0031 "Incluyendo Proveedor"
	#define STR0032 "Sucursal"
	#define STR0033 "Se Modificaron: "
	#define STR0034 " registros"
	#define STR0035 "Inicio: "
	#define STR0036 "     Final: "
	#define STR0037 "El archivo "
	#define STR0038 "No puede abrirse"
	#define STR0039 "Verificando clientes/Proveedores. Espere..."
	#define STR0040 "Creando registros"
	#define STR0041 "Archivo importado"
	#define STR0042 "Este tipo de importación solamente es compatible con la base de datos MSSQL."
	#define STR0043 "Seleccionar archivo"
	#define STR0044 "La importación no se realizó por no existir información en el archivo informado."
	#define STR0045 "Verifique si se foi informó el archivo correcto para importación"
	#define STR0046 "El Cuit de la empresa no está en el archivo"
	#define STR0047 "Archivo de cliente y proveedores importado"
	#define STR0048 "solamente se importó el archivo de cliente, Cuit de la empresa no se encuentra en el arquivo CSV."
	#define STR0049 "Período informado diferente del período del archivo (Mes + Año)."
	#define STR0050 "Proveedores , ¡Archivo importado!"
#else
	#ifdef ENGLISH
		#define STR0001 "Attention"
		#define STR0002 "1-Supplier"
		#define STR0003 "2-Customer"
		#define STR0004 "3- Both"
		#define STR0005 "Dcto. 1205/2015 - IIBB - Padrón Sujetos No Pasibles de Percepción"
		#define STR0006 "Preliminary Inf."
		#define STR0007 "File"
		#define STR0008 "Tax:"
		#define STR0009 "Perception"
		#define STR0010 "Withholding"
		#define STR0011 "&Import of CSV file"
		#define STR0012 "Option to import the file"
		#define STR0013 "Supplier/ Customer  vs. Tax according to CVS file"
		#define STR0014 "Station available to the government"
		#define STR0015 "Validity start date"
		#define STR0016 "&Import"
		#define STR0017 "&Resume"
		#define STR0018 "&Exit"
		#define STR0019 "Files (*.CSV) |*.CSV|"
		#define STR0020 "Resume"
		#define STR0021 "Save as..."
		#define STR0022 "Select file"
		#define STR0023 "File | *.CSV"
		#define STR0024 "Reading file. Wait..."
		#define STR0025 "Rate update"
		#define STR0026 "Period entered does not match the period of the file. ("
		#define STR0027 "Period"
		#define STR0028 "Record"
		#define STR0029 "Adding Customer"
		#define STR0030 "Edit Rate"
		#define STR0031 "Adding Supplier"
		#define STR0032 "End"
		#define STR0033 "Edited:"
		#define STR0034 "records"
		#define STR0035 "Start:"
		#define STR0036 "End:"
		#define STR0037 "File"
		#define STR0038 "Cannot be opened"
		#define STR0039 "Checking customers/supplies. Wait..."
		#define STR0040 "Creating records"
		#define STR0041 "File imported"
		#define STR0042 "This type of import only supports MSSQL database."
		#define STR0043 "Select file"
		#define STR0044 "Import not performed because the file entered has no data."
		#define STR0045 "Check if the correct file was entered"
		#define STR0046 "Cuit of company is not in the file"
		#define STR0047 "Imported file of customer and suppliers"
		#define STR0048 "only customer file imported, Cuit of company is not in CSV file."
		#define STR0049 "Period entered different from period of the file (Month+Yes)"
		#define STR0050 "Suppliers, imported file "
	#else
		#define STR0001 "Atenção"
		#define STR0002 "1- Fornecedor"
		#define STR0003 "2- Cliente"
		#define STR0004 "3- Ambos"
		#define STR0005 "Dcto. 1205/2015 - IIBB - Padrón Sujetos No Pasibles de Percepción "
		#define STR0006 "Inf. Preliminar"
		#define STR0007 "Arquivo"
		#define STR0008 "Imposto: "
		#define STR0009 "Percepção"
		#define STR0010 "Retenção"
		#define STR0011 "&Importação do Arquivo CSV"
		#define STR0012 "Esta opção tem como objetivo importar o arquivo"
		#define STR0013 "Fornecedor / Cliente  vs. Imposto de acordo com o arquivo CSV"
		#define STR0014 "Posto a disposição do governo "
		#define STR0015 "Fecha Inicio de Vigencia:"
		#define STR0016 "&Importar"
		#define STR0017 "&Resume"
		#define STR0018 "&Sair"
		#define STR0019 "Arquivos (*.CSV) |*.CSV|"
		#define STR0020 "Resume"
		#define STR0021 "Salvar Como..."
		#define STR0022 "Selecionar Arquivo"
		#define STR0023 "Arquivo | *.CSV"
		#define STR0024 "Lendo Arquivo, Espere..."
		#define STR0025 "Atualizacão de alicuotas"
		#define STR0026 " Periodo Informado nao corresponde ao periodo do arquivo. ("
		#define STR0027 "Periodo"
		#define STR0028 "Registro"
		#define STR0029 "Incluindo Cliente"
		#define STR0030 "Modif. Alic."
		#define STR0031 "Incluindo Fornecedor"
		#define STR0032 "Final"
		#define STR0033 "Se Modificaram: "
		#define STR0034 " registros"
		#define STR0035 "Inicio: "
		#define STR0036 "     Final: "
		#define STR0037 "O arquivo "
		#define STR0038 "Não pode ser aberto"
		#define STR0039 "Verificando clientes/Fornecedores. Espere..."
		#define STR0040 "Criando Registros"
		#define STR0041 "Arquivo importado"
		#define STR0042 "Este tipo de importação só suporta base de dados MSSQL."
		#define STR0043 "Selecionar arquivo"
		#define STR0044 "A importação não foi realizada por não existirem informações no arquivo informado."
		#define STR0045 "Verifique se foi informado o arquivo correto para importação"
		#define STR0046 "O Cuit da empresa não esta no arquivo"
		#define STR0047 "Arquivo de cliente e fornecedores importado"
		#define STR0048 "somente importado arquivo de cliente, Cuit da empresa nao se encontra no arquivo CSV."
		#define STR0049 "Periodo Informado diferente do periodo do arquivo (Mes + Ano)."
		#define STR0050 "Fornecedores , Arquivo importado !"
	#endif
#endif
