#ifdef SPANISH
	#define STR0001 "Validez de las alícuotas"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Incluir"
	#define STR0005 "Alterar"
	#define STR0006 "Excluir"
	#define STR0007 "Imprimir"
	#define STR0008 "Copiar"
	#define STR0009 "La fecha inicial debe ser mayor que la fecha final de la línea superior."
	#define STR0010 "La fecha de vigencia final debe ser mayor o igual a la fecha inicial."
#else
	#ifdef ENGLISH
		#define STR0001 "Aliquot validity"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Add"
		#define STR0005 "Edit"
		#define STR0006 "Delete"
		#define STR0007 "Print"
		#define STR0008 "Copy"
		#define STR0009 "Start date must be later than the end date on line above."
		#define STR0010 "The effective date must be later or equal to start date."
	#else
		#define STR0001 "Validade das aliquotas"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Excluir"
		#define STR0007 "Imprimir"
		#define STR0008 "Copiar"
		#define STR0009 "A data inicial tem que ser maior que a data final da linha superior."
		#define STR0010 "A data de vigência final tem que ser maior ou igual a data inicial."
	#endif
#endif
