#ifdef SPANISH
	#define STR0001 "Rutina responsable por generar e importar el Archivo de la FCI."
	#define STR0002 "Para ejecutar el procesamiento del periodo seleccionado, haga clic en el boton abajo y espere la conclusion del proceso."
	#define STR0003 "Log de Procesos: Log de todos los procesos ejecutados de esta rutina"
	#define STR0004 "Genera TXT: Funcion responsable por la generacion del Archivo Texto."
	#define STR0005 "Importacion: Funcion responsable por importar los codigos respondidos por la Sefaz."
	#define STR0006 "Informe: Funcion responsable por imprimir el informe de verificacion."
	#define STR0007 "Genera Txt"
	#define STR0008 "Importacion"
	#define STR0009 "Informe"
	#define STR0010 "Esta funcion importara archivo magnetico de la FCI respondido por la Sefaz "
	#define STR0011 "después del Contribuyente transmitir. Los codigos respondidos se importaran para utilizarse en "
	#define STR0012 "Este seguro de que el archivo que se está importando es el correcto. ¿Desea continuar?"
	#define STR0013 "Importacion de archivo texto: "
	#define STR0014 "Los codigos de este archivo se utilizaran en "
	#define STR0015 ". Confirme abajo si desea continuar."
	#define STR0016 " de "
	#define STR0017 "Importacion realizada con exito. Periodo para utilizar los codigos FCI: "
	#define STR0018 "No se encontraron codigos para importacion. Periodo para utilizar los codigos FCI: "
	#define STR0019 "¡Importacion realizada con exito!"
	#define STR0020 "¡No se encontraron los codigos para importacion!"
	#define STR0021 "No se encontro el archivo"
	#define STR0022 "¡Error!"
	#define STR0023 "Arquivo generado con exito."
	#define STR0024 "Esta funcion generara el archivo magnetico de la FCI basado en las informacion que se proceso en la tabla CFD - Ficha de Contenido de Importacion."
	#define STR0025 "Confirme, abajo, el periodo base en que se procesara la informacion y, si necesario, ajuste los parametros de la rutina."
	#define STR0026 "Periodo: "
	#define STR0027 "¿Desea continuar?"
	#define STR0028 "Atencion"
	#define STR0029 "Archivo texto generado. Periodo calculado: "
	#define STR0030 "; Archivo: "
	#define STR0031 "Esta funcion procesara el contenido de importacion de los valores practicados en el ultimo periodo de calculo."
	#define STR0032 "Periodo que se calculara: "
	#define STR0033 "Verifique en el Log de Procesos si ya se calculo este periodo. Si hace clic en continuar, se borraran los datos procesados."
	#define STR0034 "Preparando entorno..."
	#define STR0035 "Calculando producto: "
	#define STR0036 " para la sucursal: "
	#define STR0037 "Registros procesados. Periodo calculado: "
	#define STR0038 "¡Registros procesados con exito!"
	#define STR0039 "No se encontraron registros para el periodo: "
	#define STR0040 "Rutina no disponible para el entorno DBF."
	#define STR0041 "¡No se encontraron registros para los parametros informados!"
	#define STR0042 "Tabla CFD no encontrada en el diccionario."
	#define STR0043 "Parametro MV_FCITR no tiene contenido."
	#define STR0044 "Parametro MV_FCIVE no tiene contenido."
	#define STR0045 "Parametro MV_FCICL no tiene contenido."
	#define STR0046 "Parametro MV_FCIALIQ no tiene contenido."
	#define STR0047 "Parametro MV_FCIVI no tiene contenido."
	#define STR0048 "No se selecciono ninguna sucursal para el procesamiento. Se considerara la sucursal actual"
	#define STR0049 "Para la correcta ejecucion de la rutina, verifique las siguientes ocurrencias:"
	#define STR0050 "Aviso"
	#define STR0051 "Importando Codigos de la FCI..."
	#define STR0052 "Procesando producto: "
	#define STR0053 "Informe anulado por el usuario"
	#define STR0054 "Parametros definidos"
	#define STR0055 "GENERANDO INFORME, ESPERE."
	#define STR0056 "No existen datos por mostrarse."
	#define STR0057 "Empresa."
	#define STR0058 "Unidad de negocio."
	#define STR0059 "Sucursal."
	#define STR0060 "Para continuar el procesamiento, las tablas CFD y SB1 deben tener el mismo tipo de uso compartido en el "
	#define STR0061 "nivel de "
	#define STR0062 "Los productos con Código de FCI ya importados no se consideraran en el reprocesamiento."
	#define STR0063 "Parametro MV_FCIMI no tiene contenido."
	#define STR0064 "El campo rellenado en el parametro MV_FCIGTIN no pertenece a la tabla SB1."
	#define STR0065 "Metodo de calculo no se definio correctamente por medio del parametro MV_FCICALC."
	#define STR0066 "Se selecciono el metodo de calculo por medio del campo D3_PERIMP, pero el campo no existe en el diccionario."
	#define STR0067 "Para continuar el proceso de Calculo de la FCI, es necesario creaar el campo CFD_ORIGEM para la tabla CFD."
	#define STR0068 "Ejecutando Calculo Previo (Tabla SA8)..."
	#define STR0069 "Verificando reprocesamiento..."
	#define STR0070 "FICHA DE CONTENIDO DE IMPORTACION"
	#define STR0071 "Para el metodo de calculo seleccionado, sera necesario crear la tabla SA8 - Calculo Previo FCI."
	#define STR0072 "Verifique si el diccionario de datos esta de acuerdo con la opcion seleccionada en el parametro MV_FCIPRV"
	#define STR0073 "Fecha inicial / final no complementada. El procesamiento se interrumpirá."
	#define STR0074 "El registro: "
	#define STR0075 "no puede grabarse, porque el contenido de importación (CFD_CONIMP)"
	#define STR0076 "sobrepasa lo soportado por el layout, OK para continuar el cálculo de la FCI "
	#define STR0077 "Verificando estatus de las Threads..."
	#define STR0078 "Thread "
	#define STR0079 ": Procesamiento finalizado."
	#define STR0080 ": Procesando. Esperando finalización..."
	#define STR0081 ": Finalizada por error en el procesamiento."
	#define STR0082 " Finalizada."
	#define STR0083 "Finalizando Threads..."
	#define STR0084 "Threads Finalizadas."
	#define STR0085 "Ocurrieron errores en el procesamiento."
	#define STR0086 "Por favor, contacte al soporte TOTVS en pose de los archivos de LOG."
	#define STR0087 "Último producto procesado: "
	#define STR0088 "Inicializando Threads..."
	#define STR0089 "Threads inicializadas."
	#define STR0090 "Una o más Threads no se pudieron inicializar."
	#define STR0091 "El proceso se interrumpirá."
	#define STR0092 "PRODUCTOS PROCESADOS: "
	#define STR0093 "************* ERROR DE PROCESAMIENTO *************"
	#define STR0094 "Cálculo previo para :"
	#define STR0095 "Período:"
	#define STR0096 "en ejecución por el Usuario:"
	#define STR0097 ", imposible ejecución simultánea"
	#define STR0098 "El archivo"
	#define STR0099 "debe estar en directorio diferente de STARTPATH del entorno. El procesamiento se interrumpirá."
	#define STR0100 "La fecha inicial es inferior a la fecha final. El procesamiento se interrumpirá."
	#define STR0101 "Rutina anulada."
	#define STR0102 "Por favor, verifique esta información"
	#define STR0103 "Es necesario informar un directorio local válido para generación del archivo."
	#define STR0104 "No es posible la generación del archivo en la carpeta System, informe otro directorio local."
	#define STR0105 "La rutina de importación se finalizará, para ejecutarla nuevamente, salga de la rutina y redefina los parámetros en la rutina principal."
#else
	#ifdef ENGLISH
		#define STR0001 "Routine responsible for generation and import of FCI File."
		#define STR0002 "To execute the processing of the selected period, click the button below and wait for the process to finish."
		#define STR0003 "Process Log: Log of all the processes executed in this routine"
		#define STR0004 "Generate TXT: Function responsible for Text File generation."
		#define STR0005 "Import: Function responsible for importing codes returned by Sefaz."
		#define STR0006 "Report: Function responsible for printing the checking report."
		#define STR0007 "Generate TXT"
		#define STR0008 "Import"
		#define STR0009 "Report"
		#define STR0010 "This function imports the FCI magnetic file returned by Sefaz "
		#define STR0011 "after transmission by the Taxpayer. The returned codes are imported for use in "
		#define STR0012 "Make sure to import the correct file. Continue?"
		#define STR0013 "Importing text file: "
		#define STR0014 "The codes of this file are used in "
		#define STR0015 ". Confirm below if you wish to continue!"
		#define STR0016 " from "
		#define STR0017 "Import successful. Period for use of FCI codes: "
		#define STR0018 "No codes found for import. Period for use of FCI codes: "
		#define STR0019 "Imported successfully!"
		#define STR0020 "No codes were found to import!"
		#define STR0021 "File not found."
		#define STR0022 "Error!"
		#define STR0023 "File successfully generated!"
		#define STR0024 "This function generates the FCI magnetic file based on information processed on table CFD - Import Content File."
		#define STR0025 "Confirm below the base period in which the information is processed and, if needed, adjust the routine parameters."
		#define STR0026 "Period: "
		#define STR0027 "Continue?"
		#define STR0028 "Attention"
		#define STR0029 "Text File generated. Calculated Period: "
		#define STR0030 "; File: "
		#define STR0031 "This function Processes the Import Contents of the amounts used in the last Calculation Period."
		#define STR0032 "Calculation period: "
		#define STR0033 "Check in the Processes Log whether this period is already calculated. If you click Next, the already processed data are deleted."
		#define STR0034 "Preparing Environment..."
		#define STR0035 "Calculating Product: "
		#define STR0036 " for Branch: "
		#define STR0037 "Records Processed. Calculated Period: "
		#define STR0038 "Records successfully processed!"
		#define STR0039 "No records found for the Period: "
		#define STR0040 "Routine not available for DBF environment."
		#define STR0041 "Records not found for the parameters entered!"
		#define STR0042 "CFD Table not found in dictionary."
		#define STR0043 "MV_FCITR parameter has no content."
		#define STR0044 "MV_FCIVE parameter has no content."
		#define STR0045 "MV_FCICL parameter has no content."
		#define STR0046 "MV_FCIALIQ parameter has no content."
		#define STR0047 "MV_FCIVI parameter has no content."
		#define STR0048 "No branch was selected for this processing. The current branch will be considered"
		#define STR0049 "To correctly run the routine, check the occurrences below:"
		#define STR0050 "Warning!"
		#define STR0051 "Importing FCI Codes..."
		#define STR0052 "Processing Product: "
		#define STR0053 "Report Canceled by User"
		#define STR0054 "Parameters already defined!"
		#define STR0055 "GENERATING REPORT, WAIT."
		#define STR0056 "There is no data to be displayed."
		#define STR0057 "Company."
		#define STR0058 "Business Unit."
		#define STR0059 "Branch."
		#define STR0060 "To continue processing, the CFD and SB1 tables must have the same type of sharing in the "
		#define STR0061 "level of "
		#define STR0062 "The FCI Code products already imported are not regarded in the reprocessing!"
		#define STR0063 "MV_FCIMI parameter has no content."
		#define STR0064 "The field completed on parameter MV_FCIGTIN does not belong to table SB1."
		#define STR0065 "Calculation method was not properly defined through MV_FCICALC parameter."
		#define STR0066 "The calculation method was selected through field D3_PERIMP, but the field does not exist in the dictionary."
		#define STR0067 "To continue the process of FCI Calculation, you must create field CFD_ORIGEM for CFD table."
		#define STR0068 "Executing Pre-Calculation (Table SA8)..."
		#define STR0069 "Checking Reprocessing..."
		#define STR0070 "IMPORT CONTENT FORM"
		#define STR0071 "For the selected calculation method, you must create SA8 table - FCI Pre Calculation table."
		#define STR0072 "Check whether data dictionary is in accordance with the selected option in parameter MV_FCIPRV"
		#define STR0073 "End/Start date not filled out. Process will be interrupted."
		#define STR0074 "The record: "
		#define STR0075 "cannot be saved, as the import content (CFD_CONIMP)"
		#define STR0076 "exceeds the supported by layout, OK to continue the FCI calculation "
		#define STR0077 "Checking thread statuses..."
		#define STR0078 "Thread"
		#define STR0079 "Processing Finished."
		#define STR0080 ": Processing. Waiting to Finish..."
		#define STR0081 ": Closed due to Processing Error."
		#define STR0082 " Closed."
		#define STR0083 "Finishing Threads..."
		#define STR0084 "Threads Finished."
		#define STR0085 "Errors occurred in processing."
		#define STR0086 "Please contact TOTVS support with the LOG files at hand."
		#define STR0087 "Last product processed: "
		#define STR0088 "Starting Threads..."
		#define STR0089 "Threads started."
		#define STR0090 "Could not start one or more threads."
		#define STR0091 "Process will be interrupted."
		#define STR0092 "PRODUCTS PROCESSED: "
		#define STR0093 "************* PROCESSING ERROR *************"
		#define STR0094 "Pre-calculation for: "
		#define STR0095 " Period: "
		#define STR0096 " in execution by User: "
		#define STR0097 ", impossible simultaneous execution"
		#define STR0098 "File"
		#define STR0099 "must be in a different directory than the environment STARTPATH. Processing will be stopped."
		#define STR0100 "Start date later than end date. Processing will be stopped."
		#define STR0101 "Routine cancelled."
		#define STR0102 "Check the following information"
		#define STR0103 "Enter a valid local directory for file generation."
		#define STR0104 "File cannot be generated in System folder. Enter another local directory."
		#define STR0105 "The import routine will be finished. To re-run it, exit the routine and redefine the parameters in the main routine."
	#else
		#define STR0001 "Rotina responsável pela geração e importação do Arquivo da FCI."
		#define STR0002 "Para executar o processamento do período selecionado, clique no botão abaixo e aguarde a conclusão do processo."
		#define STR0003 "Log de Processos: Log de todos os processos executados desta rotina"
		#define STR0004 "Gera Txt: Função responsável pela geração do Arquivo Texto."
		#define STR0005 "Importação: Função responsável pela importação dos códigos retornados pela Sefaz."
		#define STR0006 "Relatório: Função responsável pela impressão do relatório de conferência."
		#define STR0007 "Gera Txt"
		#define STR0008 "Importação"
		#define STR0009 "Relatório"
		#define STR0010 "Esta função irá importar arquivo magnético da FCI retornado pela Sefaz "
		#define STR0011 "após transmissão pelo Contribuinte. Os códigos retornados serão importados para utilização em "
		#define STR0012 "Esteja certo de que o arquivo que está sendo importado é o correto. Deseja continuar?"
		#define STR0013 "Importando arquivo texto: "
		#define STR0014 "Os códigos deste arquivo serão utilizados em "
		#define STR0015 ". Confirme abaixo se deseja continuar!"
		#define STR0016 " de "
		#define STR0017 "Importação realizada com sucesso; Período para utilização dos códigos FCI: "
		#define STR0018 "Não foram encontrados códigos para importação; Período para utilização dos códigos FCI: "
		#define STR0019 "Importação realizada com sucesso!"
		#define STR0020 "Não foram encontrados códigos para importação!"
		#define STR0021 "Arquivo não encontrado"
		#define STR0022 "Erro!"
		#define STR0023 "Arquivo gerado com sucesso!"
		#define STR0024 "Esta função irá gerar o arquivo magnético da FCI baseado nas informações processada na tabela CFD - Ficha de Conteúdo de Importação."
		#define STR0025 "Confirme abaixo o período base em que as informações serão processadas e, se necessário, ajuste os parâmetros da rotina."
		#define STR0026 "Período: "
		#define STR0027 "Deseja continuar?"
		#define STR0028 "Atenção"
		#define STR0029 "Arquivo Texto gerado; Período Apurado: "
		#define STR0030 "; Arquivo: "
		#define STR0031 "Esta função irá Processar o Conteúdo de Importação dos valores praticados no último Período de Apuração."
		#define STR0032 "Período que será apurado: "
		#define STR0033 "Verifique no Log de Processos se este período já foi apurado. Caso clique em continuar, os dados já processados serão apagados."
		#define STR0034 "Preparando ambiente..."
		#define STR0035 "Calculando Produto: "
		#define STR0036 " para a Filial: "
		#define STR0037 "Registros Processados; Período Apurado: "
		#define STR0038 "Registros processados com sucesso!"
		#define STR0039 "Não foram encontrados registros para o Período: "
		#define STR0040 "Rotina não disponível para ambiente DBF."
		#define STR0041 "Não foram encontrados registros para os parâmetros informados!"
		#define STR0042 "Tabela CFD não encontrada no dicionário."
		#define STR0043 "Parâmetro MV_FCITR não possui conteúdo."
		#define STR0044 "Parâmetro MV_FCIVE não possui conteúdo."
		#define STR0045 "Parâmetro MV_FCICL não possui conteúdo."
		#define STR0046 "Parâmetro MV_FCIALIQ não possui conteúdo."
		#define STR0047 "Parâmetro MV_FCIVI não possui conteúdo."
		#define STR0048 "Nenhuma filial foi selecionada para o processamento. Sera considerada a filial corrente"
		#define STR0049 "Para correta execução da rotina, verificar ocorrências abaixo:"
		#define STR0050 "Aviso!"
		#define STR0051 "Importando Códigos da FCI..."
		#define STR0052 "Processando Produto: "
		#define STR0053 "Relatório Cancelado pelo Usuário"
		#define STR0054 "Parâmetros já definidos!"
		#define STR0055 "GERANDO RELATÓRIO, AGUARDE."
		#define STR0056 "Não existem Dados a serem exibidos."
		#define STR0057 "Empresa."
		#define STR0058 "Unidade de Negócio."
		#define STR0059 "Filial."
		#define STR0060 "Para continuar o processamento, as tabelas CFD e SB1 devem possuir o mesmo tipo de compartilhamento no "
		#define STR0061 "nível de "
		#define STR0062 "Os produtos com Código de FCI já importados não serão considerados no reprocessamento!"
		#define STR0063 "Parâmetro MV_FCIMI não possui conteúdo."
		#define STR0064 "O campo preenchido no parâmetro MV_FCIGTIN não pertence a tabela SB1."
		#define STR0065 "Método de cálculo não foi definido corretamente através do parâmetro MV_FCICALC."
		#define STR0066 "Foi selecionado o método de cálculo através do campo D3_PERIMP, porém o campo não existe no dicionário."
		#define STR0067 "Para continuar o processo de Apuração da FCI, é necessário a criação do campo CFD_ORIGEM para a tabela CFD."
		#define STR0068 "Executando Pré-Apuração (Tabela SA8)..."
		#define STR0069 "Verificando Reprocessamento..."
		#define STR0070 "FICHA DE CONTEÚDO DE IMPORTAÇÃO"
		#define STR0071 "Para o método de cálculo selecionado será necessário a criação da tabela SA8 - Pré-Apuração FCI."
		#define STR0072 "Verifique se o dicionário de dados está de acordo com a opção selecionada no parâmetro MV_FCIPRV"
		#define STR0073 "Data inicial / final não preenchida. O processamento será interrompido."
		#define STR0074 "O Registro: "
		#define STR0075 "não pode ser gravado, pois o conteúdo de importação (CFD_CONIMP)"
		#define STR0076 "excede o suportado pelo layout, OK para continuar a apuração da FCI "
		#define STR0077 "Verificando status das threads..."
		#define STR0078 "Thread "
		#define STR0079 ": Processamento Finalizado."
		#define STR0080 ": Processando. Aguardando Finalização..."
		#define STR0081 ": Encerrada por Erro no Processamento."
		#define STR0082 " Encerrada."
		#define STR0083 "Finalizando Threads..."
		#define STR0084 "Threads Finalizadas."
		#define STR0085 "Ocorreram erros no processamento."
		#define STR0086 "Por favor acione o suporte TOTVS em posse dos arquivos de LOG."
		#define STR0087 "Último produto processado: "
		#define STR0088 "Inicializando Threads..."
		#define STR0089 "Threads inicializadas."
		#define STR0090 "Uma ou mais threads não puderam ser inicializadas."
		#define STR0091 "O Processamento será interrompido."
		#define STR0092 "PRODUTOS PROCESSADOS: "
		#define STR0093 "************* ERRO DE PROCESSAMENTO *************"
		#define STR0094 "Pre-apuração para : "
		#define STR0095 " Periodo : "
		#define STR0096 " em execução pelo Usuario : "
		#define STR0097 ", impossivel execução simultanea"
		#define STR0098 "O arquivo "
		#define STR0099 " deve estar em diretorio diferente do STARTPATH do ambiente. O processamento sera interrompido."
		#define STR0100 "Data inicial menor que Data final. O processamento será interrompido."
		#define STR0101 "Rotina Cancelada."
		#define STR0102 "Por favor verifique estas informações"
		#define STR0103 "É necessário informar um diretório local válido para geração do arquivo."
		#define STR0104 "Não é possível a geração do arquivo na pasta System, informe outro diretório local."
		#define STR0105 "A rotina de importação sera finalizada, para executa-la novamente, saia da rotina e redefina os parametros na rotina principal."
	#endif
#endif
