#ifdef SPANISH
	#define STR0001 "Carga tributaria"
	#define STR0002 "FISA070"
	#define STR0003 "Mercaderias"
	#define STR0004 "Servicio"
	#define STR0005 "Tablas CGA y/o CGB no se encontraron en el sistema"
	#define STR0006 "Carga de tributos"
	#define STR0007 "Porcentajes por tributo"
	#define STR0008 "Totalizador"
	#define STR0009 "Campo NCM o Codigo del ISS no se informo."
	#define STR0010 "Para esta opção existe informacion registrada."
	#define STR0011 "Total de los tributos"
	#define STR0012 "¡Codigo de ISS no informado!"
	#define STR0013 "Recalculo"
	#define STR0014 "Recalculo efectuado con exito."
	#define STR0015 "Confirme la modificacion para efectivar los valores."
#else
	#ifdef ENGLISH
		#define STR0001 "Tax Load"
		#define STR0002 "FISA070"
		#define STR0003 "Goods"
		#define STR0004 "Service"
		#define STR0005 "CGA and/or CGB tables not found on the system"
		#define STR0006 "Tax Load"
		#define STR0007 "Tax Percentage"
		#define STR0008 "Totalizer"
		#define STR0009 "NCM Field or JSS Code not entered!"
		#define STR0010 "There is a registered option for this option!"
		#define STR0011 "Total taxes"
		#define STR0012 "ISS code not informed!"
		#define STR0013 "Recalculation"
		#define STR0014 "Recalculation successfully performed."
		#define STR0015 "Confirm editing to avoid values."
	#else
		#define STR0001 "Carga Tributária"
		#define STR0002 "FISA070"
		#define STR0003 "Mercadorias"
		#define STR0004 "Serviço"
		#define STR0005 "Tabelas CGA e/ou CGB não encontradas no sistema"
		#define STR0006 "Carga de Tributos"
		#define STR0007 "Percentuais por Tributo"
		#define STR0008 "Totalizador"
		#define STR0009 "Campo NCM ou Código do ISS não informado!"
		#define STR0010 "Para esta opção já existem informações cadastradas!"
		#define STR0011 "Total dos tributos"
		#define STR0012 "Código de ISS não informado!"
		#define STR0013 "Recálculo"
		#define STR0014 "Recálculo Efetuado com Sucesso."
		#define STR0015 "Confirme a alteração para efetivar os valores."
	#endif
#endif
