#ifdef SPANISH
	#define STR0001 "Parámetros del apunte no se enviaron o no son válidos."
	#define STR0002 "Código del formulario de apunte no informado."
	#define STR0003 "Descripción del formulario de apunte no informado."
	#define STR0004 "Ícono del formulario de apunte no informado."
	#define STR0005 "Programa de apunte no informado"
	#define STR0006 "Registro duplicado. ¡Inclusión no permitida!"
	#define STR0007 "Programa de apunte no válido. Las opciones permitidas son: 1 = MATA250, 2 = MATA680, 3 = MATA681 , 4 = SFCA314"
	#define STR0008 "El campo código del formulario está informado con un contenido mayor que el definido en la base de datos"
	#define STR0009 "El campo Programa de apunte está informado con un contenido mayor que el definido en la base de datos"
	#define STR0010 "El campo Imagen está informado con un contenido mayor que el definido en la base de datos"
	#define STR0011 "El campo Descripción del formulario está informado con un contenido mayor que el definido en la base de datos"
	#define STR0012 "Formulario no encontrado."
	#define STR0013 "No se permite modificar el programa de apunte."
	#define STR0014 "Servicio REST para manejo del Archivo de formularios del apunte"
	#define STR0015 "Recupera los formularios de apunte"
	#define STR0016 "Incluye nuevos registros de formularios de apunte"
	#define STR0017 "Modifica un formulario de apunte"
	#define STR0018 "Borra un formulario de apunte"
	#define STR0019 "Usuário não informado."
	#define STR0020 "No existen formularios de apunte registrados para el usuario."
	#define STR0021 "¡Tabla SOX o SOY o SOZ no registrada en el sistema!"
	#define STR0022 "Campo Apunte de parada está informado con contenido no válido. Valores válidos: 1-Sí, 2-No"
	#define STR0023 "Solo se permite informar el campo Apunte de parada para el tipo de apunte 4 - SFCA314."
	#define STR0024 "Campo Utilizar cronómetro está informado con contenido no válido. Valores válidos: 1-Sí, 2-No"
	#define STR0025 "Solamente se permite informar el campo Utilizar cronómetro para el tipo de apunte 4 - SFCA314."
	#define STR0026 "Campo Tipo de progreso está informado con contenido no válido. Valores válidos: 1-Progresivo, 2-Regresivo, 3-Ninguno"
	#define STR0027 "Solamente se permite informar el campo Tipo de progreso si el campo Utilizar cronómetro fuera igual a 1 - Sí."
#else
	#ifdef ENGLISH
		#define STR0001 "Annotation parameters not sent or not valid."
		#define STR0002 "Annotation Form Code not entered."
		#define STR0003 "Annotation Form Description not entered."
		#define STR0004 "Annotation Form Icon not entered."
		#define STR0005 "Annotation Program not entered"
		#define STR0006 "Duplicate record. Inclusion not allowed."
		#define STR0007 "Invalid Annotation Program. Allowed options are: 1 = MATA250, 2 = MATA680, 3 = MATA681, 4 = SFCA314"
		#define STR0008 "Content of field Form Code is bigger than that set in the database"
		#define STR0009 "Content of field Annotation Program is bigger than that set in the database"
		#define STR0010 "Content of field Image is bigger than that set in the database"
		#define STR0011 "Content of field Form Description is bigger than that set in the database"
		#define STR0012 "Form not found."
		#define STR0013 "You cannot edit the Annotation Program."
		#define STR0014 "REST Service for handling the Form Register of the annotation"
		#define STR0015 "Recovers annotation forms"
		#define STR0016 "Includes new annotation form records"
		#define STR0017 "Edits an annotation form"
		#define STR0018 "Deletes an annotation form"
		#define STR0019 "User not entered."
		#define STR0020 "No annotation forms registered for user."
		#define STR0021 "Table SOX or SOY or SOZ not registered in the system!"
		#define STR0022 "Stop Annotation field has invalid content. Valid values: 1 - Yes; 2 - No."
		#define STR0023 "It is allowed to inform the Stop Annotation field only for the type 4 - SFCA314."
		#define STR0024 "Content of field Use Chronometer is not valid. Valid values: 1 - Yes; 2 - No"
		#define STR0025 "You can fill out field Use Chronometer only for annotation type 4 - SFCA314."
		#define STR0026 "Content of field Progress Type is not valid. Valid values: 1-Progressive, 2-Regressive, 3-None"
		#define STR0027 "You can fill out field Progress Type only when field Use Chronometer is equal to 1 - Yes."
	#else
		#define STR0001 "Parâmetros do apontamento não enviados ou inválidos."
		#define STR0002 "Código do Formulário de Apontamento não informado."
		#define STR0003 "Descrição do Formulário de Apontamento não informado."
		#define STR0004 "Ícone do Formulário de Apontamento não informado."
		#define STR0005 "Programa de Apontamento não informado"
		#define STR0006 "Registro duplicado. Inclusão não permitida!"
		#define STR0007 "Programa de Apontamento inválido. Opções permitidas são: 1 = MATA250, 2 = MATA680, 3 = MATA681 , 4 = SFCA314"
		#define STR0008 "Campo Código do Formulário está informado com um conteúdo maior que o definido no banco de dados"
		#define STR0009 "Campo Programa de Apontamento está informado com um conteúdo maior que o definido no banco de dados"
		#define STR0010 "Campo Imagem está informado com um conteúdo maior que o definido no banco de dados"
		#define STR0011 "Campo Descrição do Formulário está informado com um conteúdo maior que o definido no banco de dados"
		#define STR0012 "Formulário não encontrado."
		#define STR0013 "Não é permitido alterar o Programa de Apontamento."
		#define STR0014 "Serviço REST para manipulação do Cadastro de Formulários do apontamento"
		#define STR0015 "Recupera os formulários de apontamento"
		#define STR0016 "Inclui novos registros de formulários de apontamento"
		#define STR0017 "Altera um formulário de apontamento"
		#define STR0018 "Exclui um formulário de apontamento"
		#define STR0019 "Usuário não informado."
		#define STR0020 "Não há formulários de apontamento cadastrados para o usuário."
		#define STR0021 "Tabela SOX ou SOY ou SOZ não cadastrada no sistema!"
		#define STR0022 "Campo Apontamento de Parada está informado com conteúdo inválido. Valores válidos: 1-Sim, 2-Não"
		#define STR0023 "É permitido informar o campo Apontamento de Parada somente para o tipo de apontamento 4 - SFCA314."
		#define STR0024 "Campo Usar Cronômetro está informado com conteúdo inválido. Valores válidos: 1-Sim, 2-Não"
		#define STR0025 "É permitido informar o campo Usar Cronômetro somente para o tipo de apontamento 4 - SFCA314."
		#define STR0026 "Campo Tipo de Progresso está informado com conteúdo inválido. Valores válidos: 1-Progressivo, 2-Regressivo, 3-Nenhum"
		#define STR0027 "É permitido informar o campo Tipo de Progresso somente quando o campo Usar Cronômetro estiver igual a 1 - Sim."
	#endif
#endif
