#ifdef SPANISH
	#define STR0001 "Espere...Verificando NCC pendiente..."
	#define STR0002 "La busqueda de las NCC pendiente no se realizo. La venta continuara normalmente."
	#define STR0003 "¡Sin comunicacion con el WebService (Busqueda de la NCC)!"
	#define STR0004 "Espere... Dando de baja NCC pendiente..."
	#define STR0005 "¡Sin comunicacion con el WebService!"
	#define STR0006 "Atencion"
	#define STR0007 "Espere...Revertiendo la NCC del cliente..."
	#define STR0008 "WEBSERVICE INDISPONIBLE EN LA TRANSACCION DE NCC"
	#define STR0009 "¡Avisar al Supervisor/Administrador!"
	#define STR0010 "Datos de la venta siguiente:"
	#define STR0011 "Cliente: "
	#define STR0012 "Tienda: "
	#define STR0013 "Numero/Serie de la venta correspondiente: "
	#define STR0014 "NCC que necesita verificarse manualmente:"
	#define STR0015 "------------------------------------------------"
	#define STR0016 "Titulo de la NCC : "
	#define STR0017 "Prefijo de la NCC: "
	#define STR0018 "Cuota de la NCC: "
	#define STR0019 "Tipo de la NCC   : "
	#define STR0020 "Se creo el LOG en la carpeta: \AUTOCOM\NCC"
	#define STR0021 "Operacion del WebSerice indisponible: BAJA de la NCC"
	#define STR0022 "Operacion del WebSerice indisponible: REVERSION de la NCC"
	#define STR0023 "¡Las NCC usadas en la venta, necesitan darse de baja manualmente! ¡Avisar al Supervisor!"
	#define STR0024 "¡Sin comunicacion con el WebService (Baja de la NCC)!"
	#define STR0025 "¡No fue posible revertir la baja de las NCC, es necesario realizar manualmente! ¡Avisar al Supervisor!"
	#define STR0026 "¡Sin comunicacion con el WebService (Reversion de la NCC)!"
	#define STR0027 "¡Sin comunicacion con el WebService!"
	#define STR0028 "Nota de Credito al Cliente"
	#define STR0029 "Sobrara un credito por el valor de: "
	#define STR0030 "Ok"
	#define STR0031 "Seleccione la(s) forma(s) de pago"
	#define STR0032 "Haciendo el calculo del descuento y el nuevo calculo de los impuestos..."
	#define STR0033 "Descuento en el total del comprobante"
	#define STR0034 "Valor / Porcentaje"
	#define STR0035 "El valor del descuento supera el valor total de la venta descontado a la NCC"
	#define STR0036 "NCC se verificaran automaticamente :"
	#define STR0037 "Valor utilizado de NCC: "
	#define STR0038 "Saldo restante de NCC: "
	#define STR0039 "Descuento en el total del comprobante: ANULADO"
#else
	#ifdef ENGLISH
		#define STR0001 "Please wait, checking pending NCC."
		#define STR0002 "Open NCC search was not done. Sale will proceed normally."
		#define STR0003 "No communication with WebService (NCC Search)!"
		#define STR0004 "Please, wait, downloading pending NCC."
		#define STR0005 "No WebService communication!"
		#define STR0006 "Attention"
		#define STR0007 "Please, wait, reversing customer NCC."
		#define STR0008 "UNAVAILABLE WEBSERVICE IN NCC TRANSACTION"
		#define STR0009 "Notice Supervisor/Administrator!"
		#define STR0010 "Information of following sale:"
		#define STR0011 "Customer: "
		#define STR0012 "Unit: "
		#define STR0013 "Number/Series of corresponding sale: "
		#define STR0014 "NCCs that must be verified manually:"
		#define STR0015 "------------------------------------------------"
		#define STR0016 "NCC Bill: "
		#define STR0017 "NCC Prefix: "
		#define STR0018 "NCC Installmente: "
		#define STR0019 "Type of NCC: "
		#define STR0020 "Creating LOG in folder: \AUTOCOM\NCC"
		#define STR0021 "WebService operation unavailable. NCC POSTING"
		#define STR0022 "WebService operation unavailable. NCC REVERSE"
		#define STR0023 "NCCs used in sale must be posted manually! Inform Supervisor!"
		#define STR0024 "No communication with WebService (NCC POSTING)!"
		#define STR0025 "Reverse of NCCs posting was not possible, please do it manually! Inform Supervisor!"
		#define STR0026 "No communication with WebService (NCC Reverse)!"
		#define STR0027 "No communication with WebService!"
		#define STR0028 "Customer Credit Note"
		#define STR0029 "It will remain a credit of: "
		#define STR0030 "OK"
		#define STR0031 "Choose payment term(s)"
		#define STR0032 "Making discount calculation and tax recalculation..."
		#define STR0033 "Discount on voucher total"
		#define STR0034 "Value / Percentage"
		#define STR0035 "Discount value is higher than sale total with NCC deducted"
		#define STR0036 "NCCs are checked automatically:"
		#define STR0037 "Value used NCC: "
		#define STR0038 "NCC left balance: "
		#define STR0039 "Discount in total of coupon : CANCELED"
	#else
		#define STR0001 "Aguarde...Verificando NCC em aberto..."
		#define STR0002 "A pesquisa das NCC em aberto não foi realizada. A venda prosseguirá normalmente."
		#define STR0003 "Sem comunicação com o WebService (Pesquisa da NCC)!"
		#define STR0004 "Aguarde...Baixando NCC em aberto..."
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Sem Comunicação Com O Webservice!", "Sem comunicação com o WebService!" )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Atenção", "Atencao" )
		#define STR0007 "Aguarde...Estornando a NCC do cliente..."
		#define STR0008 If( cPaisLoc $ "ANG|PTG", 'WEBSERVICE INDISPONÍVEL NA TRANSAÇÃO DE NCC', "WEBSERVICE INDISPONÍVEL NA TRANSAÇÃO DE NCC" )
		#define STR0009 "Avisar o Supervidor/Administrador!"
		#define STR0010 "Dados da venda abaixo:"
		#define STR0011 "Cliente: "
		#define STR0012 "Loja: "
		#define STR0013 If( cPaisLoc $ "ANG|PTG", 'Número/Série da venda correspondente:', "Número/Serie da venda correspondente: " )
		#define STR0014 "NCCs que precisam ser verificadas manualmente:"
		#define STR0015 "------------------------------------------------"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", 'Título da NCC :', "Título da NCC : " )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", 'PRefixo da NCC:', "Prefixo da NCC: " )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", 'PArcela da NCC:', "Parcela da NCC: " )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", 'TIpo da NCC   :', "Tipo da NCC   : " )
		#define STR0020 "Criado o LOG na pasta: \AUTOCOM\NCC"
		#define STR0021 "Operação do WebSerice indisponivel: BAIXA da NCC"
		#define STR0022 "Operação do WebSerice indisponivel: ESTORNO da NCC"
		#define STR0023 "As NCCs usadas na venda, precisam ser baixadas manualmente! Avisar o Supervidor!"
		#define STR0024 "Sem comunicação com o WebService (Baixa da NCC)!"
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Não foi possível estornar a liquidação das NCCs, necessário realizar manualmente! Avisar o Supervisor!", "Não foi possível estornar a baixa das NCCs, necessário realizar manualmente! Avisar o Supervisor!" )
		#define STR0026 "Sem comunicação com o WebService (Estorno da NCC)!"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Sem Comunicação Com O Webservice!", "Sem comunicação com o WebService!" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Nota De Crédito Ao Cliente", "Nota de Crédito ao Cliente" )
		#define STR0029 "Irá restar um crédito no valor de: "
		#define STR0030 "Ok"
		#define STR0031 "Escolha a(s) forma(s) de pagamento"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Fazendo o cálculo do desconto e o recálculo dos impostos...", "Fazendo o calculo do desconto e o recalculo dos impostos..." )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Desconto no total do cartão", "Desconto no total do cupom" )
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Valor / Percentagem", "Valor / Percentual" )
		#define STR0035 "O valor do desconto supera o valor total da venda abatido a NCC"
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "NCCs serão verificadas automaticamente :", "NCCs serão verificadas automáticamente :" )
		#define STR0037 "Valor utilizado de NCC: "
		#define STR0038 "Saldo restante de NCC: "
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Desconto no total do cupão : CANCELADO", "Desconto no total do cupom : CANCELADO" )
	#endif
#endif
