#ifdef SPANISH
	#define STR0001 "Proceso de licitación"
	#define STR0002 "Abierto"
	#define STR0003 "Finalizado"
	#define STR0004 "Restante"
	#define STR0005 "Impugnado"
	#define STR0006 "Fracasado / Desierto"
	#define STR0007 "Obsoleto"
	#define STR0008 "Por Lote"
	#define STR0009 "Por Item"
	#define STR0010 "Visualizar"
	#define STR0011 "Modificar"
	#define STR0012 "Incluir"
	#define STR0013 "Borrar"
	#define STR0014 "Imprimir"
	#define STR0015 "Copiar proceso de licitación"
	#define STR0016 "Conocimiento"
	#define STR0017 "En marcha"
	#define STR0018 "Impugnar"
	#define STR0019 "Cuestionar"
	#define STR0020 "Remanente"
	#define STR0021 "Generar Analisis"
	#define STR0022 "Etapas/Checklist"
	#define STR0023 "Solicitudes"
	#define STR0024 "Documentos"
	#define STR0025 "Comision Licitacion"
	#define STR0026 "Impugnacion / Cuestionamiento"
	#define STR0027 "Contrato"
	#define STR0028 "Pedido de Compra"
	#define STR0029 "Licitantes"
	#define STR0030 "Productos"
	#define STR0031 "Impugnacion \ Cuestionamiento"
	#define STR0032 "Comision de licitacion"
	#define STR0033 "CheckList"
	#define STR0034 "Pedidos de Compra"
	#define STR0035 "Contratos"
	#define STR0036 "Reglas de la licitacion"
	#define STR0037 "Leyenda"
	#define STR0038 "¡El proceso de licitación ya se publicó, esta funcionalidad está desactivada!"
	#define STR0039 "Checklist obligatorio"
	#define STR0040 "Linea: "
	#define STR0041 "¡Informe el canal de Publicacion!"
	#define STR0042 "Existen proveedores inhabilitados en el archivo, ¿desea continuar de todas maneras? "
	#define STR0043 "Informe la observacion para los licitantes con estatus Revocado o Anulado"
	#define STR0044 "El completado de los campos Derecho y Obligacion es obligatorio en el caso de Entrega Inmediata"
	#define STR0045 "El completado del camo Obligacion y Obligacion es obligatorio en el caso de Entrega Inmediata"
	#define STR0046 "El completado del campo Derecho es obligatorio en el caso de Entrega Inmediata"
	#define STR0047 "El tipo de modalidad seleccionado no es valido para la modalidad"
	#define STR0048 ". Esta modalidad admite los siguientes tipos de modalidad:"
	#define STR0049 "Tipo y modalidad no compatibles"
	#define STR0050 "Copiar"
	#define STR0051 "Documentos"
	#define STR0052 " se encuentra en la Etapa "
	#define STR0053 "El proceso de licitación "
	#define STR0054 " se encuentra en la Etapa "
	#define STR0055 "Proceso "
	#define STR0056 "¿La modificacion afectara la formulacion de las propuestas?"
	#define STR0057 "Ley 8.666 Art. 21 inciso III parrafo 4o."
	#define STR0058 "¿La solicitud de impugnación se origina de un licitante de este proceso de licitación?"
	#define STR0059 "El plazo de impugnación de este proceso de licitación venció."
	#define STR0060 "¿Confirma la impugnación de la licitación?"
	#define STR0061 "Atencion"
	#define STR0062 "¿Confirma el cuestionamiento de la licitación?"
	#define STR0063 "¿Desea importar los participantes del Analisis de Mercado?"
	#define STR0064 "Generacion de Licitacion"
	#define STR0065 " ,porque este ya se publicó!"
	#define STR0066 "No es posible incluir Análisis de Mercado por medio del proceso de licitación "
	#define STR0067 "Proceso de licitación"
	#define STR0068 "EN MARCHA"
	#define STR0069 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso I Alinea a) - 45 dias"
	#define STR0070 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso I Alinea b) - 45 dias"
	#define STR0071 "Ley 8.666/93, Art. 6 Inciso I"
	#define STR0072 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso I Alinea b) - 45 dias"
	#define STR0073 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso II Alinea a) - 30 dias"
	#define STR0074 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso II Alinea b) - 30 dias"
	#define STR0075 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso III - 15 dias"
	#define STR0076 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso III - 15 dias"
	#define STR0077 "Ley 8.666/93, Art. 21, Parrafo 2o, Inciso IV - 5 dias"
	#define STR0078 "Ley 10.520/02, Art. 4, Inciso V"
	#define STR0079 "HABILITADO"
	#define STR0080 "IMPUGNADO"
	#define STR0081 "REVOCADO / ANULADO"
	#define STR0082 "INHABILITADO"
	#define STR0083 "ANULADO"
	#define STR0084 "LEYENDA"
	#define STR0085 " con Modalidad "
	#define STR0086 ", devera comenzar en "
	#define STR0087 "Para el uso de ese parrafo de exencion es necesario que la especie sea Obras y Servicio de Ingenieria."
	#define STR0088 "Para el uso de ese parrafo de exencion es necesario que la especie sea Compras y Otros."
	#define STR0089 "Para el uso de ese parrafo de exencion es necesario que la vigencia sea menor a 180 dias."
	#define STR0090 "Para el uso de ese parrafo de exencion es necesario que la licitacion sea una copia de otra."
	#define STR0091 "Para el uso de ese parrafo de exencion es necesario realizar un analisis de mercado previamente."
	#define STR0092 "En marcha"
	#define STR0093 "El margen de preferencia es mas indicado para la contratacion. ¿Aun asi, desea continuar? "
	#define STR0094 "Completar la Justificacion"
	#define STR0095 "Ley 8.666/1993 - Art.45 Ley 10.520/2002 - Art.4, Inciso X y XVII"
	#define STR0096 "Es obligatorio justificar la eleccion del licitante de mayor valor."
	#define STR0097 "La justificacion informada es muy corta."
	#define STR0098 "Informe una justificacion de como minimo treinta (30) caracteres."
	#define STR0099 "Contrato"
	#define STR0100 "Pedido de Compra"
	#define STR0101 "Pedido de Venta"
	#define STR0102 "Desea realmente generar "
	#define STR0103 "Aviso"
	#define STR0104 "¡La opción fue anulada por el usuario! "
	#define STR0105 "El proceso de licitación ya se encuentra en el proceso de remanente"
	#define STR0106 "El proceso de remanente no se aplica a la Exencion o No exigibilidad"
	#define STR0107 "El proceso de remanente solo se aplica a procesos de licitación finalizados"
	#define STR0108 "No hay saldo para efectuar el remanente en ese producto"
	#define STR0109 "Este lote no posee ningun producto con saldo"
	#define STR0110 " ¿satifacera las mismas condiciones del vencedor anterior?"
	#define STR0111 "El proveedor "
	#define STR0112 " se considerara fracasado por falta de vencedores"
	#define STR0113 "El lote "
	#define STR0114 " se considerara fracasado por falta de vencedores"
	#define STR0115 "El producto "
	#define STR0116 "Ningun producto fue marcado con la opcion de remanente."
	#define STR0117 "LICITANTE VENCEDOR"
	#define STR0118 "Es necesario completar el parametro MV_TPPLA con un Tipo de Planilla valido para la generacion de los contratos"
	#define STR0119 "No se permite informar valores superiores a la consulta de mercado"
	#define STR0120 "Integracion - Gestion de Certamen"
	#define STR0121 "Existen proveedores previos en el proceso de licitación, estos no se enviarán para la integración. ¿Desea continuar?"
	#define STR0122 "Atencion"
	#define STR0123 "Proceso de licitación se encuentra en  'Integración - Gestión de Certamen'. Solo se permite visualización."
	#define STR0124 "Existen licitantes registrados en el proceso de licitación, el cambio de documentos generado causará la pérdida de estos. ¿Desea continuar?"
	#define STR0125 "No fue posible realizar la integracion, intente nuevamente"
	#define STR0126 "Para el Proceso de Licitación con la finalidad de generar documentos de venta, no es posible cargar solicitudes de compra."
	#define STR0127 "Esta Funcionalidad se desactiva durante la copia del proceso de licitación."
	#define STR0128 "La fecha de publicacion es superior a la fecha de recepcion de las popuestas."
	#define STR0129 "Ocurrio un error en la grabacion del Historial. Verifique si la se relleno la informacion correctamente."
	#define STR0130 "Es necesario completar el parámetro MV_TPPLA con un Tipo de planilla valido para generar los contratos"
	#define STR0131 "Tipo de planilla "
	#define STR0132 " no registrado. Registrarlo para continuar el proceso."
	#define STR0133 "¡Operacion anulada por el usuario!"
	#define STR0134 "Datos no encontrados"
	#define STR0135 "Existen datos que no se encontraron en la(s) sucursal(es) de generacion del contrato: "
	#define STR0136 "Existen solicitudes de compra registradas en el proceso de licitación, el cambio de modalidad causara la pérdida de las estas. ¿Desea continuar? "
	#define STR0137 "No existen reglas de licitaciones configuradas para elaborar el proceso de licitación. Por favor, configure las reglas de la licitación en el archivo de reglas."
	#define STR0138 "El proceso de remanente no se aplica a documentos de venta"
	#define STR0139 "Opción no disponible con el proceso de licitación en la actual etapa"
	#define STR0140 "Opcion disponible solamente en la etapa de Apertura de los sobres"
	#define STR0141 " La facha de recepcion debe ser superior qa 20 dias de la fecha de apertura."
	#define STR0142 "Es necesario que el organismo administrador este en todos los productos. Producto: "
	#define STR0143 "Es necesario que el organismo administrador este en todos los productos. Lote: "
	#define STR0144 "La cantidad licitada no es compatible con la cantidad total. Productos: "
	#define STR0145 "La cantidad licitada no es compatible con la cantidad total. Lotes: "
	#define STR0146 "Si hubiera incluido un miembro de la comisión de licitación equivocadamente y este registro se hubiera retirado, por favor, borre la linea"
	#define STR0147 "Existen preguntas no respondidos. Por favor, verifique."
	#define STR0148 "Opcion disponible solamente en la etapa de Impugnacion"
	#define STR0149 "Solicitudes"
	#define STR0150 "Pedidos"
	#define STR0151 "Acta"
	#define STR0152 "Organismos participantes"
	#define STR0153 "¿Se realizo audiencia publica, de acuerdo con el Art.39 ley 8.666/93?"
	#define STR0154 "Ley 8.666/93 Art. 39"
	#define STR0155 "Ley 8.666/93 Art. 18 En la concurrencia para la venta de bienes inmuebles, la etapa de habilitacion se limitara a la comprobacion del pago del valor correspondiente al 5% (cinco por ciento) de la evaluacion."
	#define STR0156 "Ley 8.666/93 Art. 18"
	#define STR0157 "PRODUCTOS/LICITANTES"
	#define STR0158 "RESTANTE"
	#define STR0159 " - Participante del proceso de Restante"
	#define STR0160 "Inclusion"
	#define STR0161 "Impugnacion"
	#define STR0162 "Pregunta"
	#define STR0163 "Segimiento"
	#define STR0164 "Modificacion"
	#define STR0165 "Proceso restante"
	#define STR0166 "Fecha apertura: "
	#define STR0167 ", Modalidad: "
	#define STR0168 ", Tipo: "
	#define STR0169 ", Regla: "
	#define STR0170 "Generacion de contrato "
	#define STR0171 " de "
	#define STR0172 "Generacion de contrato(s)"
	#define STR0173 "Sucursal: "
	#define STR0174 " - Producto: "
	#define STR0175 " - Und. Medida: "
	#define STR0176 " - Proveedor: "
	#define STR0177 " - Tipo de planilla: "
	#define STR0178 "Tienda: "
	#define STR0179 "Productos: "
	#define STR0180 "Und. Medida: "
	#define STR0181 "Proveedores: "
	#define STR0182 "Tipos de planilla: "
	#define STR0183 "Ley 10.520/2002 - Art.4, Inciso X y XVII"
	#define STR0184 "Ley 8.666/1993 - Art.45"
	#define STR0185 "El licitante vencedor fue seleccionado, sin embargo hay licitantes con mejor oferta, por eso debe informar una justificacion."
	#define STR0186 "Impugnacion"
	#define STR0187 "Seguimiento"
	#define STR0188 "Si se hubiera incluido un miembro de la comision de convocatoria equivocadamente y este registro se hubiera retirado. ¿Desea que el sistema no lo considere?"
	#define STR0189 "Historial del proceso de licitación"
	#define STR0190 "Realmente desea generar/modificar "
	#define STR0191 "El licitante vencedor fue seleccionado, sin embargo, no hay licitantes con mejor oferta. ¿Desea continuar?"
	#define STR0192 "Disponible la modificacion del proveedor ganador."
	#define STR0193 "Licitador no clasificado entre los tres primeros colocados en la Etapa de Juicio de las Propuestas – Modo de Disputa Combinado."
	#define STR0194 "Integrando ComprasNet"
	#define STR0195 "Integracion"
	#define STR0196 "No se pudo iniciar el proceso."
	#define STR0197 "No se permite la integración entre el Fluig y el Proceso de Licitación con lote."
	#define STR0198 "Cuestionamientos"
	#define STR0199 "Errata"
	#define STR0200 "Revocar / Anular"
	#define STR0201 "Resultado Compras Net"
	#define STR0202 "Anular Int. Compras Net"
	#define STR0203 "La opcion de analisis de mercado no esta disponible para la modalidad subasta."
	#define STR0204 "Seleccione otro proceso de licitación."
	#define STR0205 "No se puede seleccionar el tipo de modalidad deseado participantes."
	#define STR0206 "Proceso de licitación de venta"
	#define STR0207 "No se puede importar los participantes del Analisis de mercado porque esta modalidad genera un edicto de venta."
	#define STR0208 "OK"
	#define STR0209 "¿Existen análisis de mercado vinculadas a este Proceso de Licitación, desea borrar realmente?"
	#define STR0210 "Historial / Errata "
	#define STR0211 "Ocurrió falla de validación al cargar los datos para el proceso de licitación: "
	#define STR0212 "Para esta configuración el valor sugerido es superior a R$ 1.500.000,00 (un millón quinientos mil reais), según Art. 23 Inciso I de la LEY Nº 8.666, DEL 21 DE JUNIO DE 1993. ¿Desea continuar?"
	#define STR0213 "Para esta configuración el valor sugerido es superior a R$ 650.000,00 (seiscientos cincuenta mil reais), según Art. 23 Inciso I de la LEY Nº 8.666, DEL 21 DE JUNIO DE 1993. ¿Desea continuar?"
	#define STR0214 "Retroceder etapa"
	#define STR0215 "Factura de reserva"
	#define STR0216 "Resolución de registro de precio"
	#define STR0217 "Proceso de licitación anulado"
	#define STR0218 "Proceso de licitación anulado"
	#define STR0219 "Proceso de licitación revocado"
	#define STR0220 "Proceso de licitación suspendido"
	#define STR0221 "Para proseguir informe el artículo 5A de la Ley Federal Nº 8666, del 21 de Junio de 1993."
	#define STR0222 "Suspensión/Activación"
	#define STR0223 "Suspendido"
	#define STR0224 "Activo"
	#define STR0225 "Fecha inválida, fecha de suspensión tiene que estar entre la fecha de apertura y la fecha base del sistema"
	#define STR0226 "Fecha inválida, fecha de activación tiene que estar entre la fecha de apertura y la fecha base del sistema"
	#define STR0227 "No es posible suspender este proceso de licitación, seleccione un proceso de licitación que esté abierto."
	#define STR0228 "Suspender/Activar Proceso de licitación"
	#define STR0229 "Proceso de licitación suspendido, permitiendo solamente visualización."
	#define STR0230 "No se permite volver etapas del proceso de licitación que inició el proceso de remanente."
	#define STR0231 "No es posible realizar el proceso en marcha para la Modalidad y Tipo seleccionado."
	#define STR0232 "Utilice un plazo de vigencia que sumado a la fecha de publicación sea superior a "
	#define STR0233 " días hábiles."
	#define STR0234 "No existe saldo del acta para realizar el progreso del remanente."
	#define STR0235 "El tipo de modalidad es mayor que la oferta. Puede utilizarse en conjunto con la modalidad Subasta solo cuando se utiliza la especie 3 (Enajenación de bienes/Concesión)."
	#define STR0236 "Desea realizar lo restante "
	#define STR0237 "No se ha seleccionado el proveedor remanente."
	#define STR0238 'Val.Est.Edit.'
	#define STR0239 "Automatización"
	#define STR0240 'Prueba Bitmap'
	#define STR0241 'Valor estimado del Proc. de Licitación'
	#define STR0242 "Locales de entrega"
	#define STR0243 'Artículos'
	#define STR0244 "Tracker"
	#define STR0245 "¡Digite un valor sugerido correcto!"
	#define STR0246 "¡SC(s) indisponible(s) para continuar con el Proceso de licitación!"
	#define STR0247 '¡Para anular un Proc. de Licitación es obligatorio informar alguna justificativa en la solapa Historial!'
	#define STR0248 '¡Para anular un Proc. de Licitación es obligatorio informar alguna justificativa en la solapa Historial!'
	#define STR0249 '¡Para volver el Proc. de Licitación a elaboración, es obligatorio informar alguna justificación en la solapa Historial!'
	#define STR0250 '¡Valor estimado no se informó!'
	#define STR0251 "Complete el campo Fecha de publicación."
	#define STR0252 "Complete el campo Fecha de recepción en la carpeta Elaboración."
	#define STR0253 'Progreso ['
	#define STR0254 '] anterior a la apertura de sobres ['
	#define STR0255 '] no permitida'
	#define STR0256 'Informe la justificación para volver a la etapa.'
	#define STR0257 "¡No existe etapa anterior!"
	#define STR0258 'No es posible modificar el estatus de proveedor con porcentaje de victoria completado'
	#define STR0259 'Para la definición de los vencedores del Ítem, complete el porcentaje de los vencedores'
	#define STR0260 "No es posible generar Acta de registro de precio para la Regla seleccionada."
	#define STR0261 "¡Plazo no válido! Digite un valor correcto."
	#define STR0262 'Definición del cuestionamiento solamente durante el progreso'
	#define STR0263 "Revocar o Anular"
	#define STR0264 "Seleccione la opción que desea realizar"
	#define STR0265 '¡Proc. De Licitación no publicado, finalizado o generó documento, no siendo posible anular!'
	#define STR0266 'Proc. de Licitación publicado. ¡No es posible anular!'
	#define STR0267 '¡Para proseguir informe el artículo 48 de la Ley complementaria Nº 123, del 14 de diciembre de 2006, inciso I II o III!'
	#define STR0268 '¡Para proseguir informe el artículo 48(inciso I II o III) o 49(inciso II o III) de la Ley complementaria Nº 123, del 14 de diciembre de 2006!'
	#define STR0269 "Anular proceso de licitación"
	#define STR0270 "Cancelar proceso de licitación"
	#define STR0271 "Revocar proceso de licitación"
	#define STR0272 "Se digitó un valor negativo en el campo CO2_VLESTI. ¡Digite un valor positivo!"
	#define STR0273 'Existen licitantes que no son Microempresa o Empresa de pequeño porte. ¿Desea continuar?'
	#define STR0274 "Fch. Publ. Subasta "
	#define STR0275 "El plazo mínimo hasta la recepción de las propuestas es de 15 días para la Modalidad de subasta (Ley 8.666/93, Art. 21). Informe una Fecha de Publicación a partir de"
	#define STR0276 "Fch. Publ."
	#define STR0277 "La Fecha de publicación no debe ser inferior a la Fecha de apertura del proceso de licitación. Informe una Fecha de Publicación a partir de"
	#define STR0278 "Cantidad del organismo inferior a la suma de las cantidades"
	#define STR0279 "Proc. de Licitación finalizado, no es posible retroceder etapas!"
	#define STR0280 "Convocatoria publicada. No es posible volver a la etapa de publicación."
	#define STR0281 "¿Desea volver al proceso de la etapa anterior?"
	#define STR0282 "Consola"
	#define STR0283 'El porcentaje de los proveedores para el Producto'
	#define STR0284 'debe sumar el 100%.'
	#define STR0285 'El porcentaje de los proveedores para el Lote'
	#define STR0286 "Reversión Cancelar/Anular/Revocar"
	#define STR0287 'Para productos del tipo de beneficio III, la cantidad debe ser superior a 3'
	#define STR0288 'Para lotes del tipo de beneficio III, la cantidad debe ser superior a 3'
	#define STR0289 'Existe licitante vencedor con el porcentaje de'
	#define STR0290 "El proveedor seleccionado no se encuadra entre micro y pequeña empresa"
	#define STR0291 'el porcentaje informado debe estar entre 0, 25 o 75.'
	#define STR0292 'Para productos del tipo de beneficio III, la cantidad de los participantes debe ser superior a 3'
	#define STR0293 "¿Desea volver a la convocatoria para elaboración?"
	#define STR0294 "."
	#define STR0295 "En esta etapa es obligatoria la cumplimentación del valor unitario de cada participante."
	#define STR0296 "Para proveedor Microempresa o Empresa de pequeño porte, el porcentaje debe estar entre 0 a 25."
	#define STR0297 "El porcentaje total de los proveedores sobrepasa el 100%."
	#define STR0298 "El porcentaje informado debe estar entre 0% y 100%."
	#define STR0299 "El porcentaje de los proveedores para el Lote"
	#define STR0300 "Ítem o Lote parcialmente atendidos"
	#define STR0301 "A200HomItem"
	#define STR0302 "Es obligatoriamente informar al menos un ítem o"
	#define STR0303 "lote para homologación."
	#define STR0304 "GCPHMPARC"
	#define STR0305 "Convocatoria con homologación parcial no puede volver a la etapa de deliberación de propuestas."
	#define STR0306 "Convocatoria de homologación parcial: ¿desea devolver el proceso a la etapa de deliberación de propuestas?"
	#define STR0307 "GCP200PA"
	#define STR0308 "No permite desmarcar la homologación de ítem que ya generó un Contrato o Pedido."
	#define STR0309 "No se permite borrar la Convocatoria en esta etapa."
	#define STR0310 "El lote"
	#define STR0311 "está revocado. ¿Anula la revocación?"
	#define STR0312 "El producto"
#else
	#ifdef ENGLISH
		#define STR0001 "Bidding Process"
		#define STR0002 "Open"
		#define STR0003 "Closed"
		#define STR0004 "Remaining"
		#define STR0005 "Refuted"
		#define STR0006 "Failed / Deserted"
		#define STR0007 "Obsolete"
		#define STR0008 "Per batch"
		#define STR0009 "Per Item"
		#define STR0010 "View"
		#define STR0011 "Modify"
		#define STR0012 "Add"
		#define STR0013 "Delete"
		#define STR0014 "Print"
		#define STR0015 "Copy Bidding Process"
		#define STR0016 "Bill of lading"
		#define STR0017 "In progress"
		#define STR0018 "Oppose"
		#define STR0019 "Ask"
		#define STR0020 "Remaining"
		#define STR0021 "Generate Analysis"
		#define STR0022 "Stages/Checklist"
		#define STR0023 "Requests"
		#define STR0024 "Documents"
		#define STR0025 "Bid Commission"
		#define STR0026 "Opposition / Questioning"
		#define STR0027 "Contract"
		#define STR0028 "Purchase request"
		#define STR0029 "Bidders"
		#define STR0030 "Products"
		#define STR0031 "Opposition / Questioning"
		#define STR0032 "Bid Commission"
		#define STR0033 "Checklist"
		#define STR0034 "Purchase Orders"
		#define STR0035 "Contracts"
		#define STR0036 "Bid rules"
		#define STR0037 "Caption"
		#define STR0038 "The bidding process was already published, this functionality is disabled!"
		#define STR0039 "Mandatory ckecklist"
		#define STR0040 "Row: "
		#define STR0041 "Enter the Publication channel!"
		#define STR0042 "There are disabled suppliers in the register, continue? "
		#define STR0043 "Enter note for bidders with status Repealed or Canceled"
		#define STR0044 "Filling out the fields Right and Obligation is mandatory in case of immediate Delivery"
		#define STR0045 "Filling out the field Obligation is mandatory in case of immediate Delivery"
		#define STR0046 "Filling out the field Right is mandatory in case of immediate Delivery"
		#define STR0047 "The modality type selected is not valid for the modality"
		#define STR0048 ". This modality accepts the following modality types:"
		#define STR0049 "Type and modality not compatible"
		#define STR0050 "Copy"
		#define STR0051 "Documents"
		#define STR0052 " is found on the Stage "
		#define STR0053 "The Bidding Process "
		#define STR0054 " is found on the Stage "
		#define STR0055 "Process "
		#define STR0056 "The change will influence the formulation of proposals?"
		#define STR0057 "Law 8,666, Art. 21, item III 4th paragraph."
		#define STR0058 "The refutation Request comes from a Bidder of this Bidding Process?"
		#define STR0059 "The refutation Term of this bidding process has expired."
		#define STR0060 "Confirm Bidding refusal?"
		#define STR0061 "Warning"
		#define STR0062 "Confirm Bidding questioning?"
		#define STR0063 "Import participants from Market Analysis?"
		#define STR0064 "Announcement Generation"
		#define STR0065 " , as it has been published!"
		#define STR0066 "Market Analysis cannot be added through bidding process "
		#define STR0067 "Bidding Process"
		#define STR0068 "PROGRESS"
		#define STR0069 "Law 8,666/93 art. 21, 2nd Paragraph, Item I Subitem a) - 45 days"
		#define STR0070 "Law 8,666/93 art. 21, 2nd Paragraph, Item I Subitem b) - 45 days"
		#define STR0071 "Law 8,666/93 art. 6 Item I"
		#define STR0072 "Law 8,666/93 art. 21, 2nd Paragraph, Item I Subitem b) - 45 days"
		#define STR0073 "Law 8,666/93 art. 21, 2nd Paragraph, Item II Subitem a) - 30 days"
		#define STR0074 "Law 8,666/93 art. 21, 2nd Paragraph, Item II Subitem b) - 30 days"
		#define STR0075 "Law 8,666/93 art. 21, 2nd Paragraph, Item III - 15 days"
		#define STR0076 "Law 8,666/93 art. 21, 2nd Paragraph, Item III - 15 days"
		#define STR0077 "Law 8,666/93 art. 21, 2nd Paragraph, Item IV - 5 days"
		#define STR0078 "Law 10,520/02 art. 4, Item V"
		#define STR0079 "ENABLED"
		#define STR0080 "REFUTED"
		#define STR0081 "REVOKED / NULLIFIED"
		#define STR0082 "DISABLED"
		#define STR0083 "CANCELED"
		#define STR0084 "CAPTION"
		#define STR0085 " with Modality "
		#define STR0086 ", should start in "
		#define STR0087 "To use this exemption paragraph, it is necessary that the species has Engineering Works and Services."
		#define STR0088 "To use this exemption paragraph, it is necessary that the species has Purchases and Others."
		#define STR0089 "To use this exemption paragraph, it is necessary that the duration is lower than 180 days."
		#define STR0090 "To use this exemption paragraph, it is necessary that the announcement is a copy of others."
		#define STR0091 "To use this exemption paragraph is necessary to make a previous market analysis."
		#define STR0092 "Progress"
		#define STR0093 "The preference margin is entered for hiring. Do you want to proceed anyway? "
		#define STR0094 "Please complete the Reason"
		#define STR0095 "Law 8,666/1993 - Art.45 Law 10,520/2002 - Art.4, Item X and XVII"
		#define STR0096 "The reason of the highest value bidder choice is mandatory."
		#define STR0097 "The entered reason is very short."
		#define STR0098 "Please enter a reason with at least 30 (thirty) characters."
		#define STR0099 "Contract"
		#define STR0100 "Purchase Order"
		#define STR0101 "Sales Order"
		#define STR0102 "Do you really want to generate "
		#define STR0103 "Warning"
		#define STR0104 "Operation was cancelled by the user! "
		#define STR0105 "The bidding process is already in the remaining process"
		#define STR0106 "The remaining process is not applicable for exemption or Non-requirement"
		#define STR0107 "The remaining process is only applicable for finished bidding process"
		#define STR0108 "There is no balance to run the remaining of this product"
		#define STR0109 "This lot does not have a product with balance"
		#define STR0110 " serve the same conditions of the previous winner?"
		#define STR0111 "The supplier "
		#define STR0112 " will fail by lack of winners"
		#define STR0113 "Lot "
		#define STR0114 " will fail by lack of winners"
		#define STR0115 "Product "
		#define STR0116 "No product marked with the remaining option."
		#define STR0117 "WINNER BIDDER"
		#define STR0118 "It is necessary fill out the parameter MV_TPPLA with one type of valid Spreadsheet for contract generation"
		#define STR0119 "Not allowed enter values greater for market inquiry"
		#define STR0120 "Integration - Event Management"
		#define STR0121 "There are Pre-Suppliers on the Bidding Process, they will not be sent for integration. Continue?"
		#define STR0122 "Warning"
		#define STR0123 "The Bidding Process is found in Integration - Event Management. Only one view is allowed."
		#define STR0124 "There are registered Bidders on the Bidding Process, change generated documents will cause its loss. Continue?"
		#define STR0125 "It was not possible to run the integration, try again"
		#define STR0126 "For the Bidding Process with the purpose of generate sales documents, it is not possible to load purchase requests."
		#define STR0127 "This Functionality is disabled during the copy of the bidding process."
		#define STR0128 "Publication date is greater than receiving proposals."
		#define STR0129 "There is an error on recording the History, check if information was correctly filled out."
		#define STR0130 "It is necessary fill out the parameter MV_TPPLA with one type of valid Spreadsheet for contract generation"
		#define STR0131 "Spreadsheet Type "
		#define STR0132 " not registered. Register it, before continuing the process."
		#define STR0133 "Operation canceled by user!"
		#define STR0134 "Data not found"
		#define STR0135 "There are data not found on branches on contract generation: "
		#define STR0136 "There are registered purchase Requests on the bidding process, the modality exchange will cause its loss. Continue? "
		#define STR0137 "There are not bidding rules configured in the notice elaboration. Configure the bidding rules in the rule register."
		#define STR0138 "The remaining process is not applicable to sales documents"
		#define STR0139 "Option available with Bidding Process in the current stage"
		#define STR0140 "Option available only in the Envelopes Opening stage"
		#define STR0141 " Receipt date must be later than 20 days of opening date."
		#define STR0142 "The managerial organ must be in all products. Product: "
		#define STR0143 "The managerial organ must be in all products. Lot: "
		#define STR0144 "The bidding quantity is not compatible with the total quantity. Product(s): "
		#define STR0145 "The bidding quantity is not compatible with the total quantity. Batches: "
		#define STR0146 "If a bidding commission member is added by accident, and this register is removed, please delete the row"
		#define STR0147 "There are not answered questions. Please verify."
		#define STR0148 "Option available only in the Refutation stage"
		#define STR0149 "Requests"
		#define STR0150 "Orders"
		#define STR0151 "Minutes"
		#define STR0152 "Participating Agencies"
		#define STR0153 "Was a public hearing performed, according to Art.39, law 8.666/93?"
		#define STR0154 "Law 8,666/93 art. 39"
		#define STR0155 "Law 8,666/93 art. 18 During competition property assets sale, you must prove having paid amount corresponding to 5% (five per cent) of the evaluation."
		#define STR0156 "Law 8,666/93 art. 18"
		#define STR0157 "PRODUCTS/BIDDER"
		#define STR0158 "REMAINING"
		#define STR0159 " - Participant of Remaining process"
		#define STR0160 "Addition"
		#define STR0161 "Refutation"
		#define STR0162 "Questioning"
		#define STR0163 "Progress"
		#define STR0164 "Change"
		#define STR0165 "Remaining Process"
		#define STR0166 "Opening date: "
		#define STR0167 ", Modality: "
		#define STR0168 ", Type: "
		#define STR0169 ", Rule: "
		#define STR0170 "Generating Contract "
		#define STR0171 " from "
		#define STR0172 "Generating Contract(s)"
		#define STR0173 "Branch: "
		#define STR0174 " - Product: "
		#define STR0175 " - Measure Unit "
		#define STR0176 " - Supplier: "
		#define STR0177 " - Spreadsheet Type: "
		#define STR0178 "Store: "
		#define STR0179 "Products: "
		#define STR0180 "Measure Unit: "
		#define STR0181 "Suppliers: "
		#define STR0182 "Spreadsheet Type: "
		#define STR0183 "Law 10.520/2002 - Art.4, Item X and XVII"
		#define STR0184 "Law 8.666/1993 - Art.45"
		#define STR0185 "The winner bidder was selected, but there are bidders with better offers, so a justification must be entered."
		#define STR0186 "Refutation"
		#define STR0187 "Progress"
		#define STR0188 "If a bidding commission member is added by accident, and this register is removed. Do you want the system to disregard it?"
		#define STR0189 "Bidding Process History"
		#define STR0190 "Do you really want to generate/edit "
		#define STR0191 "The winning bidder was selected, but some bidders have a better offer. Continue?"
		#define STR0192 "Available the change of the winning supplier."
		#define STR0193 "Bidder not classified among the three first ones in the Proposal Assessment Stage - Combined Dispute Mode."
		#define STR0194 "Integrating ComprasNet"
		#define STR0195 "Integration"
		#define STR0196 "Process could not be started."
		#define STR0197 "Integration not allowed between Fluig and Bidding Process with batch."
		#define STR0198 "Questioning"
		#define STR0199 "Errata"
		#define STR0200 "Revoke / Cancel"
		#define STR0201 "Compras Net Result"
		#define STR0202 "Cancel Int. Compras Net"
		#define STR0203 "The market analysis option is not available for the Auction modality."
		#define STR0204 "Select another Bidding Process."
		#define STR0205 "It is not possible to select the modality type wanted with participants."
		#define STR0206 "Sales Bidding Process"
		#define STR0207 "You cannot import the participants of the Market Analysis, as this modality generates a sales public note."
		#define STR0208 "OK"
		#define STR0209 "There are market analysis bound to this Bidding Process do you really want to delete?"
		#define STR0210 "History / Errata "
		#define STR0211 "A validation error occurred while loading data to the Bidding Process: "
		#define STR0212 "For this configuration the value suggested is over R$ 1,500,000.00 (one million and five hundred thousand reais), according Art. 23 Item I of LAW No. 8,666, AS OF JUNE 21, 1993. Continue?"
		#define STR0213 "For this configuration the value suggested is over R$ 650,000.00 (six hundred and fifty thousand reais), according Art. 23 Item I of LAW No. 8,666, AS OF JUNE 21, 1993. Continue?"
		#define STR0214 "Return Stage"
		#define STR0215 "Allocation Credit"
		#define STR0216 "Price Register Minutes"
		#define STR0217 "Bidding Process Void"
		#define STR0218 "Bidding Process Canceled"
		#define STR0219 "Bidding Process Revoked"
		#define STR0220 "Bidding Process Suspended "
		#define STR0221 "To proceed, inform article 5A of Federal Law no. 8666 of June 21, 1993. "
		#define STR0222 "Suspension/Activation"
		#define STR0223 "Suspended"
		#define STR0224 "Active"
		#define STR0225 "Invalid date. Suspension date must be between opening date and base date of the system. "
		#define STR0226 "Invalid date. Activation date must be between opening date and base date of the system."
		#define STR0227 "Unable to suspend this bidding process. Chose an open bidding process."
		#define STR0228 "Suspend/Activate Bidding Process"
		#define STR0229 "Bidding process suspended. Viewing only."
		#define STR0230 "Cannot return stages of bidding process that started the remainder process."
		#define STR0231 "Cannot perform progress for the Modality and Type selected."
		#define STR0232 "Use a period of validity that, when added to the publishing date, is longer than "
		#define STR0233 " work days."
		#define STR0234 "No balance of minute found to proceed with the remainder."
		#define STR0235 "The Type of Modality Major Offer can be used along with the Trading Floor modality, only when nature 3 is used (Alienation of assets/concession)."
		#define STR0236 "Execute remaining "
		#define STR0237 "No remaining supplier selected."
		#define STR0238 'Edit Est Vl'
		#define STR0239 "Automation"
		#define STR0240 'Bitmap Test'
		#define STR0241 'Bidding Process Estimate Value'
		#define STR0242 "Delivery Places"
		#define STR0243 'Articles'
		#define STR0244 "Tracker"
		#define STR0245 "Enter a proper suggested value!"
		#define STR0246 "SC(s) available to continue the Bidding Process!"
		#define STR0247 'To Cancel a Bidding Process, enter justification in the History tab!'
		#define STR0248 'To Cancel a Bidding Process, enter justification in the History tab!'
		#define STR0249 'To get back to the Bidding Process for elaboration, enter justification in the History tab!'
		#define STR0250 'Estimated value not informed!'
		#define STR0251 "Fill out Publishing Data Field."
		#define STR0252 "Fill out Receipt Date Field in the Elaboration folder."
		#define STR0253 'Progress ['
		#define STR0254 '] before to the opening of envelopes ['
		#define STR0255 '] not allowed'
		#define STR0256 'Enter justification to return stage.'
		#define STR0257 "No previous stage!"
		#define STR0258 'Supplier with percentage of inspection filled out, you cannot edit status'
		#define STR0259 'For the definition of the winners of the Item, fill out the percentage of winners'
		#define STR0260 "Unable to generate Minute of Price Record for selected Rule."
		#define STR0261 "Invalid term! Enter a correct value."
		#define STR0262 'Definition of question only during progress'
		#define STR0263 "Revoke or Cancel"
		#define STR0264 "Choose option to execute"
		#define STR0265 'Bidding Process not published, closed or document already generated, so you cannot annul it!'
		#define STR0266 'Bidding Process already Published. Unable to Cancel!'
		#define STR0267 'To proceed, enter article 48 of Complementary Law No. 123, from 14 of December of 2006, item I II or III!'
		#define STR0268 'To proceed, enter article 48(item I II or III) or 49 (item II or III) of Complementary Law No. 123, from 14 of December of 2006!'
		#define STR0269 "Annul Bidding Process"
		#define STR0270 "Cancel Bidding Process"
		#define STR0271 "Revoke Bidding Process"
		#define STR0272 "Negative value was typed in the field CO2_VLESTI, enter positive value!!!"
		#define STR0273 'There are biddings that are not Micro company or Small Size Company. Proceed?'
		#define STR0274 "Public Auction Dt."
		#define STR0275 "The minimum period until the receipt of proposals is of 15 days for the Auction Modality (Law 8.666/93, Art. 21). Enter a Publishing Date from "
		#define STR0276 "Publ. Dt."
		#define STR0277 "Publishing Date cannot be earlier than Opening Date of the bidding process. Enter Publishing Date from "
		#define STR0278 "Quantity of the Issuing Agency lower than the sum of quantities"
		#define STR0279 "Bidding process finalized, you cannot get back to stages!"
		#define STR0280 "Public Notice already published. You cannot get back to the publishing stage."
		#define STR0281 "Get back process to the previous stage?"
		#define STR0282 "Console"
		#define STR0283 'The percentage of suppliers for Product '
		#define STR0284 ' must sum 100%'
		#define STR0285 'The percentage of suppliers for Batch '
		#define STR0286 "Reverse Cancel/Annul/Revoke"
		#define STR0287 'For products benefit III type, the quantity must be greater than 3'
		#define STR0288 'For batches benefit III type, the quantity must be greater than 3'
		#define STR0289 'There already is winner bidding with percentage of '
		#define STR0290 "The supplier selected does not fit between micro and small-size company"
		#define STR0291 'the percentage informed must be between 0, 25, or 75.'
		#define STR0292 'For products benefit III type, the quantity of participants must be greater than 3'
		#define STR0293 "Return to public notice for elaboration?"
		#define STR0294 "."
		#define STR0295 "In this phase, the completion of the unitary value of each participant is required."
		#define STR0296 "For Microbusiness or Small-size business supplier, the percentage must be between 0 to 25."
		#define STR0297 "The percentage of the suppliers exceed 100%"
		#define STR0298 "The percentage informed must be between 0 and 100%"
		#define STR0299 "The percentage of suppliers for Batch"
		#define STR0300 "Item or Batch partially serviced"
		#define STR0301 "A200HomItem"
		#define STR0302 "Thank you for entering at least one item or"
		#define STR0303 "batch to be approved."
		#define STR0304 "GCPHMPARC"
		#define STR0305 "Public Notice with partial approval cannot return to Proposal Assessment stage."
		#define STR0306 "Public Notice of Partial Approval: Do you wish to reverse the process to Proposals Assessment stage?"
		#define STR0307 "GCP200PA"
		#define STR0308 "Unable to deselect approval of item that already generated Contract or Order."
		#define STR0309 "Não é permitido excluir o Edital nesta etapa."
		#define STR0310 "Batch"
		#define STR0311 "is revoked. Cancel revoking process?"
		#define STR0312 "Product"
	#else
		#define STR0001 "Processo Licitatório"
		#define STR0002 "Aberto"
		#define STR0003 "Encerrado"
		#define STR0004 "Remanescente"
		#define STR0005 "Impugnado"
		#define STR0006 "Fracassado / Deserto"
		#define STR0007 "Obsoleto"
		#define STR0008 "Por Lote"
		#define STR0009 "Por Item"
		#define STR0010 "Visualizar"
		#define STR0011 "Alterar"
		#define STR0012 "Incluir"
		#define STR0013 "Excluir"
		#define STR0014 "Imprimir"
		#define STR0015 "Copiar Processo Licitatório"
		#define STR0016 "Conhecimento"
		#define STR0017 "Andamento"
		#define STR0018 "Impugnar"
		#define STR0019 "Questionar"
		#define STR0020 "Remanescente"
		#define STR0021 "Gerar Analise"
		#define STR0022 "Etapas/Checklist"
		#define STR0023 "Solicitações"
		#define STR0024 "Documentos"
		#define STR0025 "Comissão Licitação"
		#define STR0026 "Impugnação / Questionamento"
		#define STR0027 "Contrato"
		#define STR0028 "Pedido de Compra"
		#define STR0029 "Licitantes"
		#define STR0030 "Produtos"
		#define STR0031 "Impugnação \ Questionamento"
		#define STR0032 "Comissão de Licitação"
		#define STR0033 "CheckList"
		#define STR0034 "Pedidos de Compra"
		#define STR0035 "Contratos"
		#define STR0036 "Regras da licitação"
		#define STR0037 "Legenda"
		#define STR0038 "O processo licitatório já foi publicado, esta funcionalidade esta desativada!"
		#define STR0039 "Checklist obrigatório"
		#define STR0040 "Linha: "
		#define STR0041 "Informe o canal de Publicação!"
		#define STR0042 "Existem fornecedores inabilitados no cadastro, deseja continuar mesmo assim? "
		#define STR0043 "Informe a observação para os licitantes com status Revogado ou Anulado"
		#define STR0044 "Preenchimento dos campos Direito e Obrigação é obrigatório no caso de Entrega Imediata"
		#define STR0045 "Preenchimento do campo Obrigação é obrigatório no caso de Entrega Imediata"
		#define STR0046 "Preenchimento do campo Direito é obrigatório no caso de Entrega Imediata"
		#define STR0047 "O tipo de modalidade selecionado não é valido para a modalidade"
		#define STR0048 ". Esta modalidade adimite os seguintes tipos de modalidade:"
		#define STR0049 "Tipo e modalidade não compatíveis"
		#define STR0050 "Copiar"
		#define STR0051 "Documentos"
		#define STR0052 " se encontra na Etapa "
		#define STR0053 "O Processo Licitatório "
		#define STR0054 " se encontra na Etapa "
		#define STR0055 "Processo "
		#define STR0056 "A alteração afetará a formulação das propostas?"
		#define STR0057 "Lei 8.666 Art. 21 inciso III paragrafo 4o."
		#define STR0058 "A Solicitação de impugnação origina-se de um Licitante deste Processo Licitatório?"
		#define STR0059 "O Prazo impugnação deste processo licitatório expirou."
		#define STR0060 "Confirma a Impugnação da Licitação?"
		#define STR0061 "Atenção"
		#define STR0062 "Confirma o Questionamento da Licitação?"
		#define STR0063 "Deseja importar os participantes da Análise de Mercado?"
		#define STR0064 "Geração de Edital"
		#define STR0065 " ,pois o mesmo já foi publicado!"
		#define STR0066 "Não é possível incluir Análise de Mercado por meio do processo licitatório "
		#define STR0067 "Processo Licitatório"
		#define STR0068 "ANDAMENTO"
		#define STR0069 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso I Alinea a) - 45 dias"
		#define STR0070 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso I Alinea b) - 45 dias"
		#define STR0071 "Lei 8.666/93, Art. 6 Inciso I"
		#define STR0072 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso I Alinea b) - 45 dias"
		#define STR0073 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso II Alinea a) - 30 dias"
		#define STR0074 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso II Alinea b) - 30 dias"
		#define STR0075 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso III - 15 dias"
		#define STR0076 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso III - 15 dias"
		#define STR0077 "Lei 8.666/93, Art. 21, Paragrafo 2o, Inciso IV - 5 dias"
		#define STR0078 "Lei 10.520/02, Art. 4, Inciso V"
		#define STR0079 "HABILITADO"
		#define STR0080 "IMPUGNADO"
		#define STR0081 "REVOGADO / ANULADO"
		#define STR0082 "INABILITADO"
		#define STR0083 "CANCELADO"
		#define STR0084 "LEGENDA"
		#define STR0085 " com Modalidade "
		#define STR0086 ", deverá iniciar em "
		#define STR0087 "Para a utilização desse parágrafo de dispensa é necessário que a espécie seja Obras e Serviço de Engenharia."
		#define STR0088 "Para a utilização desse parágrafo de dispensa é necessário que a espécie seja Compras e Outros."
		#define STR0089 "Para a utilização desse parágrafo de dispensa é necessário que a vigência seja menor que 180 dias."
		#define STR0090 "Para a utilização desse parágrafo de dispensa é necessário que o edital seja uma cópia de outro."
		#define STR0091 "Para a utilização desse parágrafo de dispensa é necessário fazer uma análise de mercado previamente."
		#define STR0092 "Andamento"
		#define STR0093 "A margem de preferência é mais indicada para a contratação. Deseja continuar assim mesmo? "
		#define STR0094 "Favor preencher a Justificativa"
		#define STR0095 "Lei 8.666/1993 - Art.45 Lei 10.520/2002 - Art.4, Inciso X e XVII"
		#define STR0096 "É obrigatório justificar a escolha do licitante de maior valor."
		#define STR0097 "A justificativa informada é muito curta."
		#define STR0098 "Informe por favor uma justificativa com no mínimo trinta (30) caracteres."
		#define STR0099 "Contrato"
		#define STR0100 "Pedido de Compra"
		#define STR0101 "Pedido de Venda"
		#define STR0102 "Deseja realmente gerar "
		#define STR0103 "Aviso"
		#define STR0104 "A opção foi cancelada pelo usuário! "
		#define STR0105 "O processo licitatório ja se encontra no processo de remanescente"
		#define STR0106 "O processo de remanescente não se aplica para Dispensa ou Inexigibilidade"
		#define STR0107 "O processo de remanescente somente se aplica a processo licitatório finalizados"
		#define STR0108 "Não há saldo para efetuar o remanescente nesse produto"
		#define STR0109 "Este lote não possui nenhum produto com saldo"
		#define STR0110 " atenderá as mesmas condições do vencedor anterior?"
		#define STR0111 "O fornecedor "
		#define STR0112 " será fracassado por falta de vencedores"
		#define STR0113 "O lote "
		#define STR0114 " será fracassado por falta de vencedores"
		#define STR0115 "O produto "
		#define STR0116 "Nenhum produto foi marcado com a opção de remanescente."
		#define STR0117 "LICITANTE VENCEDOR"
		#define STR0118 "É necessário preencher o parâmetro MV_TPPLA com um Tipo de Planilha válido para a geração dos contratos"
		#define STR0119 "Não é permitido informar valores superiores à consulta de mercado"
		#define STR0120 "Integração - Gestão de Certame"
		#define STR0121 "Existem Pre-Fornecedores no Processo Licitatório, os mesmos não serão enviados para a integração. Deseja continuar?"
		#define STR0122 "Atenção"
		#define STR0123 "Processo Licitatório encontra-se em  'Integração - Gestão de Certame'. Somente é permitido visualização."
		#define STR0124 "Existem Licitantes cadastrado no Processo Licitatório, a troca de documento gerado causará a perda dos mesmos. Deseja Continuar ?"
		#define STR0125 "Não foi possivel realizar a integração, tente novamente"
		#define STR0126 "Para Processo Licitatório com a finalidade de gerar documentos de venda, não é possível carregar solicitações de compra."
		#define STR0127 "Esta Funcionalida é desativada durante a copia do processo licitatório."
		#define STR0128 "A data de publicação é maior que a data de recebimento das popostas."
		#define STR0129 "Ocorreu um erro na gravação do Histórico, verifique se as informações foram preenchidas corretamente."
		#define STR0130 "É necessário preencher o parâmetro MV_TPPLA com um Tipo de Planilha válido para a geração dos contratos"
		#define STR0131 "Tipo de Planilha "
		#define STR0132 " não cadastrado. Favor cadastrá-lo para continuar o processo."
		#define STR0133 "Operação cancelada pelo Usuario!"
		#define STR0134 "Dados não encontrados"
		#define STR0135 "Existem dados que não foram encontrados na(s) filial(is) de geração do contrato: "
		#define STR0136 "Existem Solicitações de compra cadastradas no processo licitatório, a troca de modalidade causará a perda das mesmas. Deseja Continuar ? "
		#define STR0137 "Não existem regras de licitações configuradas para elaboração do processo licitatório, favor configurar as regras da licitação no cadastro de regras."
		#define STR0138 "O processo de remanescente não se aplica a documentos de venda"
		#define STR0139 "Opção indisponivel com o Processo Licitatório na atual etapa"
		#define STR0140 "Opção disponivel somente na etapa de Abertura dos Envelopes"
		#define STR0141 " A data de recebimento deve ser maior que 20 dias da data de abertura."
		#define STR0142 "É necessário que o órgão gerenciador esteja em todos os produtos. Produto: "
		#define STR0143 "É necessário que o órgão gerenciador esteja em todos os produtos. Lote: "
		#define STR0144 "A quantidade licitada não é compativel com a quantidade total. Produto(s): "
		#define STR0145 "A quantidade licitada não é compativel com a quantidade total. Lote(s): "
		#define STR0146 "Caso tenha incluido um membro da comissão de licitação equivocadamente, e esse registro tenha sido removido, favor excluir a linha"
		#define STR0147 "Existem questionamentos não respondidos. Favor verificar."
		#define STR0148 "Opção disponivel somente na etapa de Impugnação"
		#define STR0149 "Solicitações"
		#define STR0150 "Pedidos"
		#define STR0151 "Ata"
		#define STR0152 "Orgãos Participantes"
		#define STR0153 "Foi realizado audiência publica, conforme Art.39 lei 8.666/93 ?"
		#define STR0154 "Lei 8.666/93 Art. 39"
		#define STR0155 "Lei 8.666/93 Art. 18 Na concorrência para a venda de bens imóveis, a fase de habilitação limitar-se-á à comprovação do recolhimento de quantia correspondente a 5% (cinco por cento) da avaliação."
		#define STR0156 "Lei 8.666/93 Art. 18"
		#define STR0157 "PRODUTOS/LICITANTES"
		#define STR0158 "REMANESCENTE"
		#define STR0159 " - Participante do processo de Remanescente"
		#define STR0160 "Inclusão"
		#define STR0161 "Impugnação"
		#define STR0162 "Questionamento"
		#define STR0163 "Andamento"
		#define STR0164 "Alteração"
		#define STR0165 "Processo Remanescente"
		#define STR0166 "Data Abertura: "
		#define STR0167 ", Modalidade: "
		#define STR0168 ", Tipo: "
		#define STR0169 ", Regra: "
		#define STR0170 "Gerando Contrato "
		#define STR0171 " de "
		#define STR0172 "Gerando Contrato(s)"
		#define STR0173 "Filial: "
		#define STR0174 " - Produto: "
		#define STR0175 " - Und. Medida: "
		#define STR0176 " - Fornecedor: "
		#define STR0177 " - Tipo de Planilha: "
		#define STR0178 "Loja: "
		#define STR0179 "Produtos: "
		#define STR0180 "Und. Medida: "
		#define STR0181 "Fornecedores: "
		#define STR0182 "Tipos de Planilha: "
		#define STR0183 "Lei 10.520/2002 - Art.4, Inciso X e XVII"
		#define STR0184 "Lei 8.666/1993 - Art.45"
		#define STR0185 "O licitante vencedor foi selecionado, porem ha licitantes com melhor oferta e por isso deverá informar uma justificativa."
		#define STR0186 "Impugnação"
		#define STR0187 "Andamento"
		#define STR0188 "Caso tenha incluido um membro da comissão de licitação equivocadamente e esse registro tenha sido removido. Deseja que o Sistema desconsidere o mesmo?"
		#define STR0189 "Histórico do Processo Licitatório"
		#define STR0190 "Deseja realmente gerar/alterar "
		#define STR0191 "O licitante vencedor foi selecionado, porém há licitantes com melhor oferta. Deseja prosseguir?"
		#define STR0192 "Disponível a alteração do fornecedor ganhador."
		#define STR0193 "Licitante não classificado entre os três primeiros colocados na Etapa de Julgamento das Propostas – Modo de Disputa Combinado."
		#define STR0194 "Integrando ComprasNet"
		#define STR0195 "Integração"
		#define STR0196 "Não foi possivel inicializar o processo."
		#define STR0197 "Não é permitida a integração entre Fluig e Processo Licitatório com lote."
		#define STR0198 "Questionamentos"
		#define STR0199 "Errata"
		#define STR0200 "Revogar / Cancelar"
		#define STR0201 "Resultado Compras Net"
		#define STR0202 "Cancelar Int. Compras Net"
		#define STR0203 "A opção de Analise de mercado não está disponivel para a modalidade Leilão."
		#define STR0204 "Selecione um outro Processo Licitatório."
		#define STR0205 "Não é possivel selecionar o tipo de modalidade desejado com participantes."
		#define STR0206 "Processo Licitatório de Venda"
		#define STR0207 "Não é possível importar os participantes da Análise de Mercado pois esta modalidade gera um edital de venda."
		#define STR0208 "OK"
		#define STR0209 "Existem análises de mercado vinculadas a esse Processo Licitatório, deseja realmente excluir?"
		#define STR0210 "Histórico / Errata "
		#define STR0211 "Ocorreu falha de validação ao carregar os dados para o Processo Licitatório: "
		#define STR0212 "Para esta configuração o valor sugerido é acima de R$ 1.500.000,00 (um milhão e quinhentos mil reais), conforme Art. 23 Inciso I da LEI Nº 8.666, DE 21 DE JUNHO DE 1993. Deseja continuar?"
		#define STR0213 "Para esta configuração o valor sugerido é acima de R$ 650.000,00 (seiscentos e cinqüenta mil reais), conforme Art. 23 Inciso I da LEI Nº 8.666, DE 21 DE JUNHO DE 1993. Deseja continuar?"
		#define STR0214 "Voltar Etapa"
		#define STR0215 "Nota de Empenho"
		#define STR0216 "Ata de Registro de Preço"
		#define STR0217 "Processo Licitatório Anulado"
		#define STR0218 "Processo Licitatório Cancelado"
		#define STR0219 "Processo Licitatório Revogado"
		#define STR0220 "Processo Licitatório Suspenso"
		#define STR0221 "Para prosseguir informe o artigo 5A da Lei Federal Nº 8666, de 21 de Junho de 1993!"
		#define STR0222 "Suspensão/Ativação"
		#define STR0223 "Suspenso"
		#define STR0224 "Ativo"
		#define STR0225 "Data inválida, data de suspensão tem que estar entre a data de abertura e a data base do sistema"
		#define STR0226 "Data inválida, data de ativação tem que estar entre a data de abertura e a data base do sistema"
		#define STR0227 "Não é possivel suspender este processo licitatório, escolha um processo licitatório que esteja em aberto."
		#define STR0228 "Suspender/Ativar Processo Licitatório"
		#define STR0229 "Processo licitatório suspenso, permitido apenas visualização."
		#define STR0230 "Não é permitido voltar etapas de processo licitatório que iniciou o processo de remanescente."
		#define STR0231 "Não é possível realizar o andamento para a Modalidade e Tipo selecionado."
		#define STR0232 "Utilize um prazo de vigência que somado a data de publicação seja maior que "
		#define STR0233 " dias úteis."
		#define STR0234 "Não existe saldo da Ata para realizar o andamento do remanescente."
		#define STR0235 "O Tipo de Modalidade Maior Oferta pode ser utiizado em conjuto com a modalidade Pregão, somente quando for utilizada a espécie 3 (Alienação de bens / Concessão)."
		#define STR0236 "Deseja realizar o remanescente "
		#define STR0237 "Não foi selecionado o fornecedor remanescente."
		#define STR0238 'Vl.Est.Edit.'
		#define STR0239 "Automação"
		#define STR0240 'Teste Bitmap'
		#define STR0241 'Valor Estimado do Proc. Licitatório'
		#define STR0242 "Locais de Entrega"
		#define STR0243 'Artigos'
		#define STR0244 "Tracker"
		#define STR0245 "Digite uma valor sugerido correto!"
		#define STR0246 "SC(s) indisponível(is) para continuar o Processo Licitatório!"
		#define STR0247 'Para Cancelar um Proc. Licitatório é obrigatório informar alguma justificativa na aba Histórico!'
		#define STR0248 'Para Anular um Proc. Licitatório é obrigatório informar alguma justificativa na aba Histórico!'
		#define STR0249 'Para voltar o Proc. Licitatório para elaboração é obrigatório informar alguma justificativa na aba Histórico!'
		#define STR0250 'Valor estimado não foi informado!'
		#define STR0251 "Preencha o Campo Data de Publicação."
		#define STR0252 "Preencha o Campo Data de Recebimento na pasta Elaboração."
		#define STR0253 'Andamento ['
		#define STR0254 '] anterior à abertura de envelopes ['
		#define STR0255 '] não permitida'
		#define STR0256 'Informe a justificativa para retornar a etapa.'
		#define STR0257 "Não existe etapa anterior!"
		#define STR0258 'Fornecedor com o percentual de vitória preenchido, não será possivel alterar seu status'
		#define STR0259 'Para definição dos vencedores do Item preencha o percentual dos vencedores'
		#define STR0260 "Não é possível gerar Ata de Registro de Preço para a Regra selecionada."
		#define STR0261 "Prazo Inválido! Digite um valor correto."
		#define STR0262 'Definição do questionamento somente durante o andamento'
		#define STR0263 "Revogar ou Cancelar"
		#define STR0264 "Escolha a opção que deseja realizar"
		#define STR0265 'Proc. Licitatório não publicado, encerrado ou já gerou documento, Não sendo possivel anular!'
		#define STR0266 'Proc. Licitatório já Publicado. Não é possível Cancelar!'
		#define STR0267 'Para prosseguir informe o artigo 48 da Lei Complementar Nº 123, de 14 de Dezembro de 2006, inciso I II ou III!'
		#define STR0268 'Para prosseguir informe o artigo 48(inciso I II ou III) ou 49(inciso II ou III) da Lei Complementar Nº 123, de 14 de Dezembro de 2006!'
		#define STR0269 "Anular  processo licitatório"
		#define STR0270 "Cancelar  processo licitatório"
		#define STR0271 "Revogar  processo licitatório"
		#define STR0272 "Foi Digitado um valor negativo no campo CO2_VLESTI, digite um valor positivo!!!"
		#define STR0273 'Existem licitantes que não são Microempresa ou Empresa de Pequeno Porte. Deseja prosseguir?'
		#define STR0274 "Dt. Publ. Leilão"
		#define STR0275 "O prazo mínimo até o recebimento das propostas é de 15 dias para a Modalidade Lelão (Lei 8.666/93, Art. 21). Informe uma Data de Publicação a partir de "
		#define STR0276 "Dt. Publ"
		#define STR0277 "A Data de Publicação não deve ser menor que a Data de Abertura do  processo licitatório.  Informe uma Data de Publicação a partir de "
		#define STR0278 "Quantidade do Orgão menor que a soma das quantidades"
		#define STR0279 "Proc. Licitatório finalizado, não será possivel voltar etapas!"
		#define STR0280 "Edital já publicado. Não é possível voltar para a etapa de publicação."
		#define STR0281 "Deseja voltar o processo  para a etapa anterior?"
		#define STR0282 "Console"
		#define STR0283 'O percentual dos fornecedores para o Produto '
		#define STR0284 ' deve somar 100%.'
		#define STR0285 'O percentual dos fornecedores para o Lote '
		#define STR0286 "Estorno Cancelar/Anular/Revogar"
		#define STR0287 'Para produtos do tipo de benefício III, a quantidade deve ser maior que 3'
		#define STR0288 'Para lotes do tipo de benefício III, a quantidade deve ser maior que 3'
		#define STR0289 'Já existe licitante vencedor com o percentual de '
		#define STR0290 "O fornecedor selecionado não se enquadra entre micro e pequena empresa"
		#define STR0291 'o percentual informado deve estar entre 0, 25 ou 75.'
		#define STR0292 'Para produtos do tipo de benefício III, a quantidade dos particiapntes deve ser maior que 3'
		#define STR0293 "Deseja voltar o edital para elaboração?"
		#define STR0294 "."
		#define STR0295 "Nesta etapa, é obrigatório o preenchimento do valor unitário de cada participante."
		#define STR0296 "Para fornecedor Micro Empresa ou Empresa Pequeno Porte o percentual deve estar entre 0 à 25."
		#define STR0297 "O percentual total dos fornecedores ultrapassa 100%."
		#define STR0298 "O percentual informado deve estar entre 0% e 100%."
		#define STR0299 "O percentual dos fornecedores para o Lote "
		#define STR0300 "Item ou Lote parcialmente atendidos"
		#define STR0301 "A200HomItem"
		#define STR0302 "Obrigado informar pelo menos um item ou "
		#define STR0303 "lote para ser homologado."
		#define STR0304 "GCPHMPARC"
		#define STR0305 "Edital com Homologacao parcial nao pode voltar a etapa de Julgamento das Propostas."
		#define STR0306 "Edital de Homologação Parcial: Deseja voltar o processo para a etapa de Julgamento das Propostas?"
		#define STR0307 "GCP200PA"
		#define STR0308 "Não permite desmarcar homologacao de item que ja gerou Contrato ou Pedido."
		#define STR0309 "Não é permitido excluir o Edital nesta etapa."
		#define STR0310 "O Lote "
		#define STR0311 " está revogado. Cancela a revogação? "
		#define STR0312 "O Produto "
	#endif
#endif
