#ifdef SPANISH
	#define STR0001 "Desc. Prod"
	#define STR0002 "Descripcion del producto"
	#define STR0003 "Mantenimiento de Saldo"
	#define STR0004 "Acta"
	#define STR0005 "Participantes"
	#define STR0006 "Reservas"
	#define STR0007 "Desc. Producto"
	#define STR0008 "Descripcion del Producto"
	#define STR0009 "Leyenda"
	#define STR0010 "El proveedor:"
	#define STR0011 " Tienda:"
	#define STR0012 " no posee condicion de pago registrado. Por favor, registre para generar pedido de compra."
	#define STR0013 "Generando Pedido de Compra para el Organismo: "
	#define STR0014 "Participante"
	#define STR0015 "Aventon"
	#define STR0016 "Leyenda"
	#define STR0017 "Organismo"
	#define STR0018 "Gerenciador"
	#define STR0019 "Parámetro MV_TPPLA (Tipo de planilla) no informado."
	#define STR0020 "Tipo de planilla:"
	#define STR0021 "Condición de pago no registrada para el proveedor:"
	#define STR0022 "Proveedor:"
	#define STR0023 "Condición de pago: "
	#define STR0024 "Producto: "
	#define STR0025 "Und. Medida: "
	#define STR0026 "Existen datos que no se encontraron en la(s) sucursal(es) de generación de los documentos"
	#define STR0027 "El saldo informado del producto"
	#define STR0028 "difiere del saldo total del Acta:"
	#define STR0029 "Saldo total:"
	#define STR0030 "Saldo informado:"
	#define STR0031 "Sucursal:"
	#define STR0032 "Datos compartidos:"
	#define STR0033 "Atención"
	#define STR0034 "Saldo consumido con éxito sin generar documentos para el(os) participante(s): "
	#define STR0035 "Los documentos se generarán solamente para el organismo de gestión."
#else
	#ifdef ENGLISH
		#define STR0001 "Desc. Prod"
		#define STR0002 "Product description"
		#define STR0003 "Balance Maintenance"
		#define STR0004 "Minutes"
		#define STR0005 "Participants"
		#define STR0006 "Reserves"
		#define STR0007 "Desc. Product"
		#define STR0008 "Product Description"
		#define STR0009 "Caption"
		#define STR0010 "The supplier:"
		#define STR0011 " Store:"
		#define STR0012 " It has no registered payment methods. Please, register to generate payment order."
		#define STR0013 "Generating Purchase Order for the Agency: "
		#define STR0014 "Employee"
		#define STR0015 "Ride"
		#define STR0016 "Caption"
		#define STR0017 "Agency"
		#define STR0018 "Manager"
		#define STR0019 "Parameter MV_TPPLA (Type of Spreadsheet) not entered."
		#define STR0020 "Spreadsheet Type:"
		#define STR0021 "Payment term not registered for the Supplier:"
		#define STR0022 "Supplier:"
		#define STR0023 "Payment term: "
		#define STR0024 "Product: "
		#define STR0025 "Measure Unit: "
		#define STR0026 "There are data not found in the branch(es) documents generation"
		#define STR0027 "The balance entered of the product"
		#define STR0028 "differs from the total balance of the Minute:"
		#define STR0029 "Total Balance:"
		#define STR0030 "Entered Balance:"
		#define STR0031 "Branch:"
		#define STR0032 "Shared Data:"
		#define STR0033 "Attention"
		#define STR0034 "Balance consumed with success without the generation of documents for participant(s): "
		#define STR0035 "The documents are only generated for the managerial body."
	#else
		#define STR0001 "Desc. Prod"
		#define STR0002 "Descrição do produto"
		#define STR0003 "Manutenção de Saldo"
		#define STR0004 "Ata"
		#define STR0005 "Participantes"
		#define STR0006 "Reservas"
		#define STR0007 "Desc. Produto"
		#define STR0008 "Descrição do Produto"
		#define STR0009 "Legenda"
		#define STR0010 "O fornecedor:"
		#define STR0011 " Loja:"
		#define STR0012 " não possui condição de pagamento cadastrada. Por Favor cadastre para gerar pedido de compra."
		#define STR0013 "Gerando Pedido de Compra para o Orgao: "
		#define STR0014 "Participante"
		#define STR0015 "Carona"
		#define STR0016 "Legenda"
		#define STR0017 "Orgao"
		#define STR0018 "Gerenciador"
		#define STR0019 "Parâmetro MV_TPPLA (Tipo de Planilha) não informado."
		#define STR0020 "Tipo de Planilha:"
		#define STR0021 "Condição de pagamento não cadastrada para o Fornecedor:"
		#define STR0022 "Fornecedor:"
		#define STR0023 "Condição de pagamento: "
		#define STR0024 "Produto: "
		#define STR0025 "Und. Medida: "
		#define STR0026 "Existem dados que não foram encontrados na(s) filial(is) de geração dos documentos"
		#define STR0027 "O saldo informado do produto"
		#define STR0028 "difere do saldo total da Ata:"
		#define STR0029 "Saldo Total:"
		#define STR0030 "Saldo Informado:"
		#define STR0031 "Filial:"
		#define STR0032 "Dados Compartilhados:"
		#define STR0033 "Atenção"
		#define STR0034 "Saldo consumido com sucesso sem geração de documentos para o(s) participante(s): "
		#define STR0035 "Os documentos serão gerados somente para o órgão gerenciador."
	#endif
#endif
