#ifdef SPANISH
	#define STR0001 "Fracasado"
	#define STR0002 "Item"
	#define STR0003 "Cod. Producto"
	#define STR0004 "Descr. Producto"
	#define STR0005 "Cantidad"
	#define STR0006 "Proveedores"
	#define STR0007 "Eleccion del ganador"
	#define STR0008 "Clientes"
	#define STR0009 "Fracasado"
	#define STR0010 "No Fracasado"
	#define STR0011 " Productos del Edital "
	#define STR0012 " del Producto del Edital "
	#define STR0013 "Situacion"
	#define STR0014 "Item"
	#define STR0015 "Cod. Producto"
	#define STR0016 "Descr. Producto"
	#define STR0017 "Cantidad"
	#define STR0018 "Tipo"
	#define STR0019 "Codigo"
	#define STR0020 "Tienda:"
	#define STR0021 "Nombre"
	#define STR0022 "Ganadores Ok"
	#define STR0023 "Ganadores Fracasados"
	#define STR0024 "Proveedor"
	#define STR0025 "Pre-Proveedor"
	#define STR0026 "Cliente"
	#define STR0027 "Pre-Cliente"
	#define STR0028 "No se informaron ganadores para todos los productos. ¿Aun asi, salir?"
	#define STR0029 "Confirmacion"
	#define STR0030 "Existe "
	#define STR0031 " seleccionado ¿Aun asi, salir y anular las selecciones?"
	#define STR0032 "Revocado"
	#define STR0033 "No Revocado"
	#define STR0034 "Ganadores Anulados"
	#define STR0035 "Todos los productos se revocaron, anulando el proceso de licitación, ¿Confirma operación?"
	#define STR0036 "Debe modificarse cliente debido al proceso de sobrante."
	#define STR0037 "Debe modificarse el proveedor previo debido al proceso de Sobrante."
	#define STR0038 "Debe modificarse el proveedor debido al processo de sobrante."
	#define STR0039 "El "
	#define STR0040 " fue el ganador, pues:"
	#define STR0041 "Informe solo un ganador"
	#define STR0042 "Informe la orden de clasificacion para todos los participantes"
	#define STR0043 "Justificacion de la Eleccion del Licitante"
	#define STR0044 " Informe el Motivo de la eleccion del licitante de mayor valor"
	#define STR0045 "El Motivo es obligatorio."
	#define STR0046 "El Motivo informado es muy corto."
	#define STR0047 "Lote"
	#define STR0048 "Proceso"
	#define STR0049 "Proceso de licitación"
	#define STR0050 "¿Acepta el suministro por el valor de "
	#define STR0051 " asumido por el ganador anterior ? "
	#define STR0052 "Ley 8.666/1993 - Art.45"
	#define STR0053 "Ley 10.520/2002 - Art.4, Inciso X y XVII"
	#define STR0054 "El licitante vendedor fue seleccionado, sin embargo, hay licitantes con mejor oferta y por ello debera justificar la eleccion del licitante de mayor valor."
	#define STR0055 "Ley 8.666/1993 - Art.45"
	#define STR0056 "Ley 10.520/2002 - Art.4, Inciso X y XVII"
	#define STR0057 "Es obligatorio justificar la eleccion del licitante de mayor valor."
	#define STR0058 "El Ganador debera informar el valor unitario real para cada producto"
	#define STR0059 "Informe el Valor Unitario Real para los Productos"
	#define STR0060 "No se informo el valor unitario para el producto "
	#define STR0061 "Operacion anulada por el usuario"
	#define STR0062 "Informe un valor "
	#define STR0063 "Mayor"
	#define STR0064 "Menor"
	#define STR0065 " o igual a "
#else
	#ifdef ENGLISH
		#define STR0001 "Failed"
		#define STR0002 "Item"
		#define STR0003 "Product Code"
		#define STR0004 "Product Description"
		#define STR0005 "Amount"
		#define STR0006 "Suppliers"
		#define STR0007 "Winner choice"
		#define STR0008 "Customers"
		#define STR0009 "Failed"
		#define STR0010 "Not failed"
		#define STR0011 "Notice products "
		#define STR0012 "of the product of the notice "
		#define STR0013 "Status"
		#define STR0014 "Item"
		#define STR0015 "product Code"
		#define STR0016 "Product Description"
		#define STR0017 "Amount"
		#define STR0018 "Type"
		#define STR0019 "Code"
		#define STR0020 "Store"
		#define STR0021 "Name"
		#define STR0022 "Winners OK"
		#define STR0023 "Failed Winners"
		#define STR0024 "Supplier"
		#define STR0025 "Pre-Supplier"
		#define STR0026 "Customer"
		#define STR0027 "Pre-Customer"
		#define STR0028 "Winners were not entered for all products. Exit?"
		#define STR0029 "Confirmation"
		#define STR0030 "There is "
		#define STR0031 " selected one. Quit anyway and cancel selections?"
		#define STR0032 "Revoked"
		#define STR0033 "Not Revoked"
		#define STR0034 "Winners Revoked"
		#define STR0035 "All products have been repealed, thus canceling the public notice. Do you confirm the operation?"
		#define STR0036 "Customer must be modified due to the Remainder process."
		#define STR0037 "Presupplier must be modified due to Remainder process."
		#define STR0038 "Supplier must be modified due to Remainder process."
		#define STR0039 "The "
		#define STR0040 " was the winner, as:"
		#define STR0041 "Enter only one winner"
		#define STR0042 "Enter the classification order for all participants"
		#define STR0043 "Bidder Choice Justification"
		#define STR0044 " Enter the reason of the highest value bidder choice"
		#define STR0045 "The field Reason is mandatory."
		#define STR0046 "The informed Reason is too short."
		#define STR0047 "Lot"
		#define STR0048 "Process"
		#define STR0049 "Bidding Process"
		#define STR0050 "Accepts the supply for the following value "
		#define STR0051 " assumed by the previous winner? "
		#define STR0052 "Law 8.666/1993 - Art.45"
		#define STR0053 "Law 10.520/2002 - Art.4, Item X and XVII"
		#define STR0054 "The winner bidder was selected, but there are bidders with better offers - justify the choice of the highest value bidder. "
		#define STR0055 "Law 8.666/1993 - Art.45"
		#define STR0056 "Law 10.520/2002 - Art.4, Item X and XVII"
		#define STR0057 "The reason of the highest value bidder choice is mandatory."
		#define STR0058 "The Winner must enter the real unitary value for each product"
		#define STR0059 "Enter Real Unitary Value for Products"
		#define STR0060 "Unitary value for product was not informed "
		#define STR0061 "Operation canceled by user"
		#define STR0062 "Enter a value "
		#define STR0063 "Greater than"
		#define STR0064 "Smaller than"
		#define STR0065 " or equal to "
	#else
		#define STR0001 "Fracassado"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Elem.", "Item" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Cód.Artigo", "Cod.Produto" )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Descr.Artigo", "Descr.Produto" )
		#define STR0005 "Quantidade"
		#define STR0006 "Fornecedores"
		#define STR0007 "Escolha do ganhador"
		#define STR0008 "Clientes"
		#define STR0009 "Fracassado"
		#define STR0010 "Não Fracassado"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", " Artigos do Edital ", " Produtos do Edital " )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", " do Artigo do Edital ", " do Produto do Edital " )
		#define STR0013 "Situação"
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Loja", "Item" )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Cód.Artigo", "Cod.Produto" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Descr.Artigo", "Descr.Produto" )
		#define STR0017 "Quantidade"
		#define STR0018 "Tipo"
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Código", "Codigo" )
		#define STR0020 "Loja"
		#define STR0021 "Nome"
		#define STR0022 "Ganhadores Ok"
		#define STR0023 "Ganhadores Fracassados"
		#define STR0024 "Fornecedor"
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Pré-Fornecedor", "Pre-Fornecedor" )
		#define STR0026 "Cliente"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Pré-Cliente", "Pre-Cliente" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Não foram informados ganhadores para todos os artigos. Sair mesmo assim?", "Não foram informados ganhadores para todos os produtos. Sair mesmo assim?" )
		#define STR0029 "Confirmação"
		#define STR0030 "Existe "
		#define STR0031 If( cPaisLoc $ "ANG|PTG", " seleccionado. Sair mesmo assim e cancelar as selecções?", " selecionado. Sair mesmo assim e cancelar as seleções?" )
		#define STR0032 "Revogado"
		#define STR0033 "Não Revogado"
		#define STR0034 "Ganhadores Revogados"
		#define STR0035 "Todos os produtos foram revogados, cancelando o processo licitatório, Confirma operação?"
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Cliente deve ser alterado devido ao processo de remanescente.", "Cliente deve ser alterado devido ao processo de Remanescente." )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Pré-fornecedor deve ser alterado devido ao processo de remanescente.", "Pré-Fornecedor deve ser alterado devido ao processo de Remanescente." )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Fornecedor deve ser alterado devido ao processo de remanescente.", "Fornecedor deve ser alterado devido ao processo de Remanescente." )
		#define STR0039 "O "
		#define STR0040 " foi o ganhador, pois:"
		#define STR0041 "Informe apenas um ganhador"
		#define STR0042 "Informe a ordem de classificação para todos os participantes"
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Justificativa da escolha do licitante", "Justificativa da Escolha do Licitante" )
		#define STR0044 If( cPaisLoc $ "ANG|PTG", " Informe o motivo da escolha do licitante de maior valor", " Informe o Motivo da escolha do licitante de maior valor" )
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "O motivo é obrigatório.", "O Motivo é obrigatório." )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "O motivo informado é muito curto.", "O Motivo informado é muito curto." )
		#define STR0047 "Lote"
		#define STR0048 "Processo"
		#define STR0049 "Processo Licitatório"
		#define STR0050 "Aceita o fornecimento pelo valor de "
		#define STR0051 " assumido pelo ganhador anterior ? "
		#define STR0052 "Lei 8.666/1993 - Art.45"
		#define STR0053 "Lei 10.520/2002 - Art.4, Inciso X e XVII"
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "O licitante vencedor foi seleccionado, porém há licitantes com melhor oferta e por isso a escolha do licitante de maior valor devera ser justificada.", "O licitante vencedor foi selecionado, porem ha licitantes com melhor oferta e por isso deverá justificar a escolha do licitante de maior valor." )
		#define STR0055 "Lei 8.666/1993 - Art.45"
		#define STR0056 "Lei 10.520/2002 - Art.4, Inciso X e XVII"
		#define STR0057 "É obrigatório justificar a escolha do licitante de maior valor."
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "O ganhador deverá informar o valor unitário real para cada artigo", "O Ganhador deverá informar o valor unitário real para cada produto" )
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Informe o valor unitário real para os artigos", "Informe o Valor Unitario Real para os Produtos" )
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Não foi informado o valor unitário para o artigo ", "Não foi informado o valor unitário para o produto " )
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Operação cancelada pelo utilizador", "Operação cancelada pelo usuário" )
		#define STR0062 "Informe um valor "
		#define STR0063 "Maior"
		#define STR0064 "Menor"
		#define STR0065 " ou igual a "
	#endif
#endif
