#ifdef SPANISH
	#define STR0001 "Mantenimiento del Acta"
	#define STR0002 "En Analisis"
	#define STR0003 "Aguardando Firma"
	#define STR0004 "Publicada"
	#define STR0005 "Suspendida"
	#define STR0006 "Anulado"
	#define STR0007 "Finalizada"
	#define STR0008 "Aguardando Publicacion"
	#define STR0009 "Encabezado del Acta"
	#define STR0010 "Productos"
	#define STR0011 "Licitantes"
	#define STR0012 "Participantes"
	#define STR0013 "No Participantes"
	#define STR0014 "Mantenimiento del Saldo"
	#define STR0015 "Visualizar"
	#define STR0016 "Suspender"
	#define STR0017 "Retomar"
	#define STR0018 "Anular"
	#define STR0019 "Publicar"
	#define STR0020 "No fue posible encontrar el estado relacionado con ese Acta."
	#define STR0021 "Fecha de Publicacion"
	#define STR0022 "Proceso Remanente"
	#define STR0023 "El Acta se modifico"
	#define STR0024 "De"
	#define STR0025 "Para"
	#define STR0026 "Por"
	#define STR0027 "En"
	#define STR0028 "Justificacion"
	#define STR0029 "¡El Acta esta suspendida!"
	#define STR0030 "Informe la Justificacion de la Suspension del Acta"
	#define STR0031 "Informe la Justificacion de Anulacion del Acta"
	#define STR0032 "No sera posible retomar el Acta, ¡pues no esta suspendida!"
	#define STR0033 "¡El Acta esta Publicada!"
	#define STR0034 "Informe la Vigencia del Acta"
	#define STR0035 "No sera posible modificar la situacion del Acta, pues su estatus esta: "
	#define STR0036 "¡El Acta excedio el plazo de vigencia y sera Anulada!"
	#define STR0037 "El Acta excedio el plazo de 90 dias sin Publicacion, la misma se modificara a ¡Aguardando Publicacion!"
	#define STR0038 "La contratacion no puede exceder el 100% del cuantitativo total registrado en acta."
	#define STR0039 "La totalidad de las contrataciones no puede exceder 5 veces el cuantitativo total."
	#define STR0040 "Repactar"
	#define STR0041 "Pantalla para repactacion de precios"
	#define STR0042 "Ajuste Sld."
	#define STR0043 "Pantalla para Mantenimiento de Saldo"
	#define STR0044 "Repacto de preciso esta disponible solo para los licitantes vencedores"
	#define STR0045 "La fecha de la publicacion debe ser mayor o igual a: "
	#define STR0046 "Historial del Acta"
	#define STR0047 "1º Publicacion"
	#define STR0048 "2º Publicacion"
	#define STR0049 "3º Publicacion"
	#define STR0050 "4º Publicacion"
	#define STR0051 "Leyenda"
	#define STR0052 "¡Atencion!"
	#define STR0053 "Justificacion Repacto"
	#define STR0054 "Participante"
	#define STR0055 "Aventon"
	#define STR0056 "Organismo"
	#define STR0057 "Incluir"
	#define STR0058 "Gerenciador"
	#define STR0059 "Conocimiento"
	#define STR0060 "La fecha final no puede ser inferior a la fecha final actual"
	#define STR0061 "La fecha final no puede ser inferior a la fecha inicial del acta"
	#define STR0062 "¡Vigencia del acta no puede ser superior a 365 días! "
	#define STR0063 "La fecha final del acta no puede superar dos años de su publicación, informe una fecha inferior o igual a "
	#define STR0064 "Generar nota de reserva"
	#define STR0065 "Adicional"
	#define STR0066 "Por ítem"
	#define STR0067 "Por lote"
	#define STR0068 "Solicitudes"
	#define STR0069 "Canal de publicación"
	#define STR0070 "Automatización"
	#define STR0071 "Organismos"
	#define STR0072 "Control de saldo"
	#define STR0073 "Prueba Bitmap"
	#define STR0074 "Saldo"
	#define STR0075 "Documentos"
	#define STR0076 "Actualiza"
	#define STR0077 "Precio"
	#define STR0078 "Referencia"
	#define STR0079 "Botón para realizar el ajuste en el valor de referencia"
	#define STR0080 "Justificación para nuevo acuerdo"
	#define STR0081 'Es necesario distribuir correctamente el saldo del producto'
	#define STR0082 'entre los participantes'
	#define STR0083 "Saldo por distribuir"
	#define STR0084 "Saldo de los participantes"
	#define STR0085 "No existen solicitudes no reservadas"
	#define STR0086 "Adicional"
	#define STR0087 "La cantidad del producto no puede sobrepasar"
	#define STR0088 "(125% de la cantidad licitada del producto)"
	#define STR0089 "La cantidad no puede ser menor que la cantidad licitada."
	#define STR0090 "La cantidad no puede ser menor que la cantidad actual"
	#define STR0091 "Nuevo acuerdo"
	#define STR0092 "¡Adicional solamente se permite para acta con estatus igual a Publicada!"
	#define STR0093 "Existen lotes con más de un ganador seleccionado."
	#define STR0094 "Existen ítems con más de un ganador seleccionado."
#else
	#ifdef ENGLISH
		#define STR0001 "Minutes Maintenance"
		#define STR0002 "Under Analysis"
		#define STR0003 "Waiting Signature"
		#define STR0004 "Published"
		#define STR0005 "Suspended"
		#define STR0006 "Canceled"
		#define STR0007 "Finished"
		#define STR0008 "Waiting Publication"
		#define STR0009 "Minutes Header"
		#define STR0010 "Products"
		#define STR0011 "Bidders"
		#define STR0012 "Participants"
		#define STR0013 "Not Participants"
		#define STR0014 "Balance Maintenance"
		#define STR0015 "View"
		#define STR0016 "Suspend"
		#define STR0017 "Return"
		#define STR0018 "Cancel"
		#define STR0019 "Publish"
		#define STR0020 "You cannot find the state related to this Minute."
		#define STR0021 "Publication Date"
		#define STR0022 "Remaining Process"
		#define STR0023 "Minutes edited"
		#define STR0024 "From"
		#define STR0025 "To"
		#define STR0026 "By"
		#define STR0027 "In"
		#define STR0028 "Explanation"
		#define STR0029 "Minutes suspended!"
		#define STR0030 "Enter Reason for Minutes Suspension"
		#define STR0031 "Enter a Reason for Minutes Cancellation"
		#define STR0032 "You cannot return the Minutes, as it is suspended!"
		#define STR0033 "Minutes published!"
		#define STR0034 "Enter Minutes Validity"
		#define STR0035 "You cannot edit Minutes status, as it is: "
		#define STR0036 "Minutes exceeded validity date and is Canceled!"
		#define STR0037 "Minutes exceeded 90 days validity date without Publication. It is edited for Waiting Publication!"
		#define STR0038 "Hiring cannot exceed 100% of total amount registered in the minutes."
		#define STR0039 "The hiring totality cannot exceed 5 times the total amount. "
		#define STR0040 "Reprice"
		#define STR0041 "Screen for reprice"
		#define STR0042 "Blc. Adjustment"
		#define STR0043 "Screen for Balance Maintenance"
		#define STR0044 "Reprice is available only for winner bidders"
		#define STR0045 "Payment date must be after or equal to: "
		#define STR0046 "Minutes History"
		#define STR0047 "1st Publication"
		#define STR0048 "2nd Publication"
		#define STR0049 "3rd Publication"
		#define STR0050 "4th Publication"
		#define STR0051 "Caption"
		#define STR0052 "Attention!"
		#define STR0053 "Renegotiation Justification"
		#define STR0054 "Employee"
		#define STR0055 "Ride"
		#define STR0056 "Agency"
		#define STR0057 "Add"
		#define STR0058 "Manager"
		#define STR0059 "Knowledge"
		#define STR0060 "End date cannot be before current end date"
		#define STR0061 "End date cannot be before Minute start date"
		#define STR0062 "Minute Validity cannot be over 365 days"
		#define STR0063 "Minute end date cannot exeeced two years from its publication, enter a date before os the same as"
		#define STR0064 "Generate Allocation Invoice"
		#define STR0065 "Addendum"
		#define STR0066 "By Item"
		#define STR0067 "By Batch"
		#define STR0068 "Requests"
		#define STR0069 "Publication Channel"
		#define STR0070 "Automation"
		#define STR0071 "Bodies"
		#define STR0072 "Balance Control"
		#define STR0073 "Bitmap Test"
		#define STR0074 "Balance"
		#define STR0075 "Documents"
		#define STR0076 "Update"
		#define STR0077 "Price"
		#define STR0078 "Reference"
		#define STR0079 "Button for the adjustment in the reference value"
		#define STR0080 "Renegotiation Justification"
		#define STR0081 'Distribute properly the product balance'
		#define STR0082 'among the participants'
		#define STR0083 "Balance to be distributed"
		#define STR0084 "Balance of participants"
		#define STR0085 "No requests allocated"
		#define STR0086 "Addendum"
		#define STR0087 "The amount of the product cannot exceed"
		#define STR0088 "(125% of the product bid quantity)"
		#define STR0089 "The quantity cannot be earlier than the bid quantity."
		#define STR0090 "The quantity cannot be earlier than current date"
		#define STR0091 "Renegotiation"
		#define STR0092 "Prepayment is only allowed for minute with Published status!"
		#define STR0093 "There are lots with more than one winner"
		#define STR0094 "There are items with more than one winner"
	#else
		#define STR0001 "Manutenção da Ata"
		#define STR0002 "Em Análise"
		#define STR0003 "Aguardando Assinatura"
		#define STR0004 "Publicada"
		#define STR0005 "Suspensa"
		#define STR0006 "Cancelada"
		#define STR0007 "Finalizada"
		#define STR0008 "Aguardando Publicação"
		#define STR0009 "Cabeçalho da Ata"
		#define STR0010 "Produtos"
		#define STR0011 "Licitantes"
		#define STR0012 "Participantes"
		#define STR0013 "Não Participantes"
		#define STR0014 "Manutenção do Saldo"
		#define STR0015 "Visualizar"
		#define STR0016 "Suspender"
		#define STR0017 "Retomar"
		#define STR0018 "Cancelar"
		#define STR0019 "Publicar"
		#define STR0020 "Não foi possível encontrar o estado relacionado com essa Ata."
		#define STR0021 "Data de Publicação"
		#define STR0022 "Processo Remanescente"
		#define STR0023 "A Ata foi alterada"
		#define STR0024 "De"
		#define STR0025 "Para"
		#define STR0026 "Por"
		#define STR0027 "Em"
		#define STR0028 "Justificativa"
		#define STR0029 "A Ata está suspensa!"
		#define STR0030 "Informe a Justificativa da Suspensão da Ata"
		#define STR0031 "Informe a Justificativa do Cancelamento da Ata"
		#define STR0032 "Não será possível retomar a Ata, pois ela não está suspensa!"
		#define STR0033 "A Ata está Publicada!"
		#define STR0034 "Informe a Vigência da Ata"
		#define STR0035 "Não será possível alterar a situação da Ata, pois seu status está: "
		#define STR0036 "A Ata excedeu o prazo de vigência e será Cancelada!"
		#define STR0037 "A Ata excedeu o prazo de 90 dias sem Publicação, a mesma será alterada para Aguardando Publicalção!"
		#define STR0038 "A contratação não pode exceder 100% do quantitativo total registrado em ata."
		#define STR0039 "A totalidade das contratações não pode exceder 5 vezes o quantitativo total."
		#define STR0040 "Repactuar"
		#define STR0041 "Tela para repactução de preços"
		#define STR0042 "Ajuste Sld."
		#define STR0043 "Tela para Manutenção do saldo"
		#define STR0044 "A Repactuação de preços está disponível apenas para os licitantes vencedores"
		#define STR0045 "A data da publicação deve ser maior ou igual a: "
		#define STR0046 "Histórico da Ata"
		#define STR0047 "1º Publicação"
		#define STR0048 "2º Publicação"
		#define STR0049 "3º Publicação"
		#define STR0050 "4º Publicação"
		#define STR0051 "Legenda"
		#define STR0052 "Atenção!"
		#define STR0053 "Justificativa Repactuação"
		#define STR0054 "Participante"
		#define STR0055 "Carona"
		#define STR0056 "Orgão"
		#define STR0057 "Incluir"
		#define STR0058 "Gerenciador"
		#define STR0059 "Conhecimento"
		#define STR0060 "A data fim não pode ser menor do que a data fim atual"
		#define STR0061 "A data fim não pode ser menor do que a data de inicio da Ata"
		#define STR0062 "Vigencia da Ata não pode ser superior a 365 dias! "
		#define STR0063 "A data fim da Ata não pode ultrapassar dois anos de sua publicação, informe uma data menor ou igual a "
		#define STR0064 "Gerar Nota de Empenho"
		#define STR0065 "Aditamento"
		#define STR0066 "Por item"
		#define STR0067 "Por Lote"
		#define STR0068 "Solicitações"
		#define STR0069 "Canal de Publicação"
		#define STR0070 "Automação"
		#define STR0071 "Orgãos"
		#define STR0072 "Controle de saldo"
		#define STR0073 "Teste Bitmap"
		#define STR0074 "Saldo"
		#define STR0075 "Documentos"
		#define STR0076 "Atualiza"
		#define STR0077 "Preço"
		#define STR0078 "Referência"
		#define STR0079 "Botão para realizar ajuste no valor de referência"
		#define STR0080 "Justificativa Repactuação"
		#define STR0081 'Necessário distribuir corretamente o saldo do produto'
		#define STR0082 'entre os participantes'
		#define STR0083 "Saldo a distribuir"
		#define STR0084 "Saldo dos participantes"
		#define STR0085 "Não existem solicitações não empenhadas"
		#define STR0086 "Aditamento"
		#define STR0087 "A quantidade do produto não pode ultrapassar"
		#define STR0088 "(125% da quantidade licitada do produto)"
		#define STR0089 "A quantidade não pode ser menor do que a quantidade licitada."
		#define STR0090 "A quantidade não pode ser menor do que a quantidade atual"
		#define STR0091 "Repactuação"
		#define STR0092 "Aditamento só é permitido para ata com status igual a Publicada!"
		#define STR0093 "Existem lotes com mais de um ganhador selecionado."
		#define STR0094 "Existem itens com mais de um ganhador selecionado."
	#endif
#endif
