#ifdef SPANISH
	#define STR0001 'Condición de venta'
	#define STR0002 'Cuota'
	#define STR0003 'Vencto'
	#define STR0004 'Tipo cuota'
	#define STR0005 'Valor de título'
	#define STR0006 'Valor principal'
	#define STR0007 'Valor intereses Fcto'
	#define STR0008 'Valor total:'
	#define STR0009 'Plan'
	#define STR0010 'Análisis'
	#define STR0011 'Valor venta: '
	#define STR0012 'Total intereses fcto: '
	#define STR0013 'Total a plazo: '
	#define STR0014 'Tasa de descuento (Anual): '
	#define STR0015 'Tasa de descuento (Mensual): '
	#define STR0016 'Valor actual neto: '
	#define STR0017 'Certificado habítese: '
	#define STR0018 'Cuota del habítese: '
	#define STR0019 'Principal hasta el habítese: '
	#define STR0020 'Nuevo cálculo'
	#define STR0021 'Confirma'
	#define STR0022 'Salir'
	#define STR0023 'Valor no puede ser superior a'
	#define STR0024 'Fecha de 1o. vencimiento no informada.'
	#define STR0025 'Tasa anual no informada.'
	#define STR0026 'Informe la fecha de inicio de intereses.'
	#define STR0027 'Día de corrección monetaria no se informó.'
	#define STR0028 'Diferencia de '
	#define STR0029 ' entre el valor del pedido de venta con la suma de los valores de las cuotas.'
	#define STR0030 'No se informó la condición de venta.'
	#define STR0031 ' entre el valor del pedido y la suma de los valores de la condición de venta.'
	#define STR0032 'Archivo de solidarios'
	#define STR0033 'Solidarios'
	#define STR0034 'Template GEM'
	#define STR0035 'La unidad '
	#define STR0036 ' está reservada en el pedido: '
	#define STR0037 'Ok'
	#define STR0038 ' fue vendido en el contrato: '
	#define STR0039 ' ya fue vendida.'
	#define STR0040 'El producto informado no se refiere a unidad de emprendimiento.'
	#define STR0041 'Existe cantidad en ceros de cuota en algún ítem de esta condición. Favor verificar.'
#else
	#ifdef ENGLISH
		#define STR0001 'Sales Condition'
		#define STR0002 'Installment'
		#define STR0003 'Due date'
		#define STR0004 'Installment Type'
		#define STR0005 'Bill Value'
		#define STR0006 'Main Value'
		#define STR0007 'Financing Interest Value'
		#define STR0008 'Total Value:'
		#define STR0009 'Plan'
		#define STR0010 'Analysis'
		#define STR0011 'Sales Value: '
		#define STR0012 'Financing Interest Total: '
		#define STR0013 'Total in Installments: '
		#define STR0014 'Discount Rate (Yearly): '
		#define STR0015 'Discount Rate (Monthly): '
		#define STR0016 'Net Present Value: '
		#define STR0017 'Occupancy permit: '
		#define STR0018 'Occupancy permit Installment: '
		#define STR0019 'Main until Occupancy Permit: '
		#define STR0020 'Recalculate'
		#define STR0021 'Confirm'
		#define STR0022 'Exit'
		#define STR0023 'Value cannot be greater than'
		#define STR0024 '1st expiration date not entered.'
		#define STR0025 'Yearly rate not entered.'
		#define STR0026 'Enter the Interest start date.'
		#define STR0027 'Indexation day not entered.'
		#define STR0028 'Difference of '
		#define STR0029 ' enter the Sales Order value with the sum of installments values.'
		#define STR0030 'Sales condition not entered.'
		#define STR0031 ' enter the Order value and the sum of values of the sales condition.'
		#define STR0032 'Solidarity Register'
		#define STR0033 'Solidarity'
		#define STR0034 'GEM Template'
		#define STR0035 'The unit '
		#define STR0036 ' is reserved on order: '
		#define STR0037 'Ok'
		#define STR0038 ' was sold on contract: '
		#define STR0039 ' was already sold.'
		#define STR0040 'The product entered does not refer to the venture unit.'
		#define STR0041 'There is zeroed installment amount in some item of this condition. Please verify.'
	#else
		#define STR0001 'Condição de Venda'
		#define STR0002 'Parcela'
		#define STR0003 'Vencto'
		#define STR0004 'Tipo Parcela'
		#define STR0005 'Valor do Titulo'
		#define STR0006 'Valor Principal'
		#define STR0007 'Valor Juros Fcto'
		#define STR0008 'Valor Total:'
		#define STR0009 'Plano'
		#define STR0010 'Análise'
		#define STR0011 'Valor Venda: '
		#define STR0012 'Total Juros Fcto: '
		#define STR0013 'Total a Prazo: '
		#define STR0014 'Taxa de Desconto (Anual): '
		#define STR0015 'Taxa de Desconto (Mensal): '
		#define STR0016 'Valor Presente Liquido: '
		#define STR0017 'Habite-se: '
		#define STR0018 'Parcela do Habite-se: '
		#define STR0019 'Principal até o Habite-se: '
		#define STR0020 'Recalculo'
		#define STR0021 'Confirma'
		#define STR0022 'Sair'
		#define STR0023 'Valor não pode ser superior a'
		#define STR0024 'Data do 1o. vencimento nao informada.'
		#define STR0025 'Taxa anual nao informada.'
		#define STR0026 'Informe a data de inicio do Juros.'
		#define STR0027 'Dia da Correçao monetaria nao foi informado.'
		#define STR0028 'Diferenca de '
		#define STR0029 ' entre o valor do Pedido de Venda com a soma dos valores das parcelas.'
		#define STR0030 'Não foi informado a condicao de venda.'
		#define STR0031 ' entre o valor do Pedido e a soma dos valores da condicao de venda.'
		#define STR0032 'Cadastro de Solidarios'
		#define STR0033 'Solidarios'
		#define STR0034 'Template GEM'
		#define STR0035 'A unidade '
		#define STR0036 ' está reservada no pedido: '
		#define STR0037 'Ok'
		#define STR0038 ' foi vendido no contrato: '
		#define STR0039 ' já foi vendida.'
		#define STR0040 'O produto informado não se refere a unidade do empreendimento.'
		#define STR0041 'Existe quantidade zerada de parcela em algum item desta condição. Favor verificar.'
	#endif
#endif
