#ifdef SPANISH
	#define STR0001 "Flete Embarcador"
	#define STR0002 "Integración"
	#define STR0003 "Documento"
	#define STR0004 "Ctd Unitiz"
	#define STR0005 "Considerar Negociacion"
	#define STR0006 "Agrupadores"
	#define STR0007 "Documentos de Flete"
	#define STR0008 "Items de Carga"
	#define STR0009 "Trechos"
	#define STR0010 "Calculos 01"
	#define STR0011 "DISPARA SIMULACION"
	#define STR0012 "Agrupador"
	#define STR0013 "Trecho"
	#define STR0014 "Documentos de Carga"
	#define STR0015 "Calculos"
	#define STR0016 "Otras Informaciones"
	#define STR0017 "Simular"
	#define STR0018 "Considera Neg"
	#define STR0019 "¿Considera Negociacion?"
	#define STR0020 "Si"
	#define STR0021 "No"
	#define STR0022 "Numero Calculo"
	#define STR0023 "Tp Calculo"
	#define STR0024 "Tp Flete"
	#define STR0025 "Ciudad Recoleccion"
	#define STR0026 "Ciudad Calculo"
	#define STR0027 "Valor PIS"
	#define STR0028 "Valor COFINS"
	#define STR0029 "VALOR ICMS/ISS"
	#define STR0030 "Valor Flete"
	#define STR0031 "Calculo01"
	#define STR0032 "Clas Flete"
	#define STR0033 "Tipo Operacion"
	#define STR0034 "Emit Tabla"
	#define STR0035 "Nr tabla "
	#define STR0036 "Nr Negoc"
	#define STR0037 "Ruta"
	#define STR0038 "Fecha Validez"
	#define STR0039 "Rango"
	#define STR0040 "Tipo Vehiculo"
	#define STR0041 "Calculo02"
	#define STR0042 "Componente"
	#define STR0043 "Categoria"
	#define STR0044 "Ctd Calculo"
	#define STR0045 "Total Flete"
	#define STR0046 "Calculo03"
	#define STR0047 "Nr de la Tabla"
	#define STR0048 "Negociacion"
	#define STR0049 "Nr del Calculo"
	#define STR0050 "Emisor"
	#define STR0051 "¿Vigencia?"
	#define STR0052 "¿Rango?"
	#define STR0053 "¿Tipo Vehiculo?"
	#define STR0054 "¿Ruta?"
	#define STR0055 "Otras Informaciones 01"
	#define STR0056 "Descripcion"
	#define STR0057 "¿Seleccionada?"
	#define STR0058 "Otras Informaciones 02"
	#define STR0059 "Seleccionando Registros..."
	#define STR0060 "Flete Unidad"
	#define STR0061 "Flete Valor"
	#define STR0062 "Tasas"
	#define STR0063 "Peaje"
	#define STR0064 "Problemas de la Simulacion "
	#define STR0065 "El Documento de Carga "
	#define STR0066 " no tiene Items informados."
	#define STR0067 "El Documento de Carga "
	#define STR0068 " no tiene Trechos informados."
	#define STR0069 "El Agrupador "
	#define STR0070 " no tiene Documento de Carga relacionados."
	#define STR0071 "Es necesario que haya informacion en la solapa Documentos de Cargas"
	#define STR0072 "Un Documento de Carga no tiene agrupador relacionado en la  solapa 'Agrupadores' "
	#define STR0073 "El Item de la linea "
	#define STR0074 " no tiene documento de carga relacionado en la solapa 'Documentos de Carga'"
	#define STR0075 "El Trecho de la linea "
	#define STR0076 " tiene la misma ciudad del trecho "
	#define STR0077 "El Trecho de la linea "
	#define STR0078 " no tiene documento de carga relacionado en la solapa 'Documentos de Carga'"
	#define STR0079 "Se encontro una Lista de Embarque con la clave  informada."
	#define STR0080 "¿Desea traer los documentos relacionados? Este proceso va a borrar Documentos de Carga que no esten relacionados a un Agrupador registrado en el sistema."
	#define STR0081 "Lista de Embarque Encontrada"
	#define STR0082 "Se encontro un Documento de Carga con la clave informada."
	#define STR0083 "¿Desea traer los items relacionados? Este proceso va a borrar trechos e items que no esten relacionados a un Documento de Carga registrado en el sistema."
	#define STR0084 "Documento de Carga"
	#define STR0085 "Agrupador informado ya existe."
	#define STR0086 "Simulacion de Flete"
	#define STR0087 "¿Desea borrar todos los datos de simulacion?"
#else
	#ifdef ENGLISH
		#define STR0001 "Shipper Freight"
		#define STR0002 "Integration"
		#define STR0003 "Document"
		#define STR0004 "Unitiz. Amt"
		#define STR0005 "Consider Negotiation"
		#define STR0006 "Groupers"
		#define STR0007 "Freight Documents"
		#define STR0008 "Shipping Items"
		#define STR0009 "Distances"
		#define STR0010 "Calculation 01"
		#define STR0011 "TRIGGERS SIMULATION"
		#define STR0012 "Grouping"
		#define STR0013 "Distance"
		#define STR0014 "Shipping Documents"
		#define STR0015 "Calculation"
		#define STR0016 "Other information"
		#define STR0017 "Simulate"
		#define STR0018 "Consider Neg"
		#define STR0019 "Consider Negotiation?"
		#define STR0020 "Yes"
		#define STR0021 "No"
		#define STR0022 "Calculation Number"
		#define STR0023 "Calculation Tp"
		#define STR0024 "Freight Tp"
		#define STR0025 "Collection City"
		#define STR0026 "Calculation City"
		#define STR0027 "PIS Value"
		#define STR0028 "COFINS Value"
		#define STR0029 "ICMS/ISS Value"
		#define STR0030 "Freight Value"
		#define STR0031 "Calculation01"
		#define STR0032 "Freight Class."
		#define STR0033 "Operation Type"
		#define STR0034 "Issues Table"
		#define STR0035 "Table No. "
		#define STR0036 "Neg No."
		#define STR0037 "Route"
		#define STR0038 "Due Date "
		#define STR0039 "Range"
		#define STR0040 "Vehicle Type"
		#define STR0041 "Calculation02"
		#define STR0042 "Component"
		#define STR0043 "Category"
		#define STR0044 "Calculation Amt"
		#define STR0045 "Freight Total"
		#define STR0046 "Calculation03"
		#define STR0047 "Table No."
		#define STR0048 "Negotiation"
		#define STR0049 "Calculation No."
		#define STR0050 "Issuer"
		#define STR0051 "Effective Date?"
		#define STR0052 "Range?"
		#define STR0053 "Vehicle Type?"
		#define STR0054 "Route?"
		#define STR0055 "Other Information 01"
		#define STR0056 "Description"
		#define STR0057 "Selected?"
		#define STR0058 "Other Information 02"
		#define STR0059 "Selecting Records..."
		#define STR0060 "Unit Freight"
		#define STR0061 "Freight Amount"
		#define STR0062 "Rates"
		#define STR0063 "Toll"
		#define STR0064 "Simulation Issues "
		#define STR0065 "Shipping Document "
		#define STR0066 " does not have items entered."
		#define STR0067 "Shipping Document "
		#define STR0068 " does not have distances entered."
		#define STR0069 "Grouper "
		#define STR0070 " does not have related Shipping Documents."
		#define STR0071 "Information must be in the Shipping Documents tab"
		#define STR0072 "A Shipping Document does not have grouper related in the Groupers tab "
		#define STR0073 "Row item "
		#define STR0074 " does not have shipping document related in the Shipping Documents tab"
		#define STR0075 "Row distance "
		#define STR0076 " has the same distance city "
		#define STR0077 "Row distance "
		#define STR0078 " does not have shipping document related in the Shipping Documents tab"
		#define STR0079 "A Packing List was found with the key entered ."
		#define STR0080 "Do you want to bring related documents? This process deletes Load Documents not related to a Grouper registered in the system."
		#define STR0081 "Packing list found"
		#define STR0082 "A Shipping Document was found with the key entered ."
		#define STR0083 "Do you want to bring related items? This process deletes segments and items not related to a Load Document registered in the system."
		#define STR0084 "Shipping Document"
		#define STR0085 "Grouper entered already exists."
		#define STR0086 "Simulation of Freight"
		#define STR0087 "Do you wish to delete all simulation data?"
	#else
		#define STR0001 "Frete Embarcador"
		#define STR0002 "Integração"
		#define STR0003 "Documento"
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Qtd. Unitiz", "Qtd Unitiz" )
		#define STR0005 "Considerar Negocição"
		#define STR0006 "Agrupadores"
		#define STR0007 "Documentos de Frete"
		#define STR0008 "Itens de Carga"
		#define STR0009 "Trechos"
		#define STR0010 "Cálculos 01"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "DISPARA SIMULAÇÃO", "DISPARA SIMULACAO" )
		#define STR0012 "Agrupador"
		#define STR0013 "Trecho"
		#define STR0014 "Documentos de Carga"
		#define STR0015 "Cálculos"
		#define STR0016 "Outras Informações"
		#define STR0017 "Simular"
		#define STR0018 "Considera Neg"
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Considera negociação?", "Considera Negociação?" )
		#define STR0020 "Sim"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Não", "Nao" )
		#define STR0022 "Número Cálculo"
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Tp. Cálculo", "Tp Cálculo" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Tp. Frete", "Tp Frete" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Concelho Recolha", "Cidade Coleta" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Concelho Cálculo", "Cidade Cálculo" )
		#define STR0027 "Valor PIS"
		#define STR0028 "Valor COFINS"
		#define STR0029 "Valor ICMS/ISS"
		#define STR0030 "Valor Frete"
		#define STR0031 "Calculo01"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Class. Frete", "Class Frete" )
		#define STR0033 "Tipo Operação"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Emit. Tabela", "Emit Tabela" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Nr. tabela ", "Nr tabela " )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Nr. Negoc.", "Nr Negoc" )
		#define STR0037 "Rota"
		#define STR0038 "Data Validade"
		#define STR0039 "Faixa"
		#define STR0040 "Tipo Veículo"
		#define STR0041 "Calculo02"
		#define STR0042 "Componente"
		#define STR0043 "Categoria"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Qtd. Cálculo", "Qtde Cálculo" )
		#define STR0045 "Total Frete"
		#define STR0046 "Calculo03"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Nr. da Tabela", "Nr da Tabela" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Negociação", "Negociacao" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Nr.do Cálculo", "Nr do Calculo" )
		#define STR0050 "Emitente"
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Vigência?", "Vigencia?" )
		#define STR0052 "Faixa?"
		#define STR0053 "Tipo Veículo?"
		#define STR0054 "Rota?"
		#define STR0055 "Outras Informações 01"
		#define STR0056 "Descrição"
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Seleccionada?", "Selecionada?" )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Outras informações 02", "Outras Informações 02" )
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "A seleccionar registos...", "Selecionando Registros..." )
		#define STR0060 "Frete Unidade"
		#define STR0061 "Frete Valor"
		#define STR0062 "Taxas"
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "Pedágio", "Pedagio" )
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "Problemas da Simulação ", "Problemas da Simulacao " )
		#define STR0065 "O Documento de Carga "
		#define STR0066 If( cPaisLoc $ "ANG|PTG", " não possui itens informados.", " não possui Itens informados." )
		#define STR0067 "O Documento de Carga "
		#define STR0068 If( cPaisLoc $ "ANG|PTG", " não possui trechos informados.", " não possui Trechos informados." )
		#define STR0069 "O Agrupador "
		#define STR0070 If( cPaisLoc $ "ANG|PTG", " não possui documento de carga relacionados.", " não possui Documento de Carga relacionados." )
		#define STR0071 "É necessário que haja informações na aba Documentos de Cargas"
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Um documento de carga não possui agrupador relacionado na aba 'Agrupadores' ", "Um Documento de Carga não possui agrupador relacionado na aba 'Agrupadores' " )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "O item da linha ", "O Item da linha " )
		#define STR0074 " não possui documento de carga relacionado na aba 'Documentos de Carga'"
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "O trecho da linha ", "O Trecho da linha " )
		#define STR0076 If( cPaisLoc $ "ANG|PTG", " possui o mesmo concelho do trecho ", " possui a mesma cidade do trecho " )
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "O trecho da linha ", "O Trecho da linha " )
		#define STR0078 " não possui documento de carga relacionado na aba 'Documentos de Carga'"
		#define STR0079 "Foi encontrado um Romaneio com a chave informada."
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "Deseja trazer os documentos relacionados? Este processo apagará documentos de carga que não estejam relacionados a um agrupador registado no sistema.", "Deseja trazer os documentos relacionados? Este processo irá apagar Documentos de Carga que não estejam relacionados a um Agrupador cadastrado no sistema." )
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "Romaneio encontrado", "Romaneio Encontrado" )
		#define STR0082 "Foi encontrado um Documento de Carga com a chave informada."
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "Deseja trazer os itens relacionados? Este processo apagará trechos e itens que não estejam relacionados a um documento de carga registado no sistema.", "Deseja trazer os itens relacionados? Este processo irá apagar trechos e itens que não estejam relacionados a um Documento de Carga cadastrado no sistema." )
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Documento de carga", "Documento de Carga" )
		#define STR0085 "Agrupador informado já existe."
		#define STR0086 "Simulação de Frete"
		#define STR0087 "Deseja apagar todos os dados de simulação?"
	#endif
#endif
