#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Archivo de materias"
	#define STR0007 "Consulta grupo de equivalencia"
	#define STR0008 "Grupo de equivalencia"
	#define STR0009 "Esta disciplina forma parte de un grupo de equivalencia. ¿Confirma la modificación?"
	#define STR0010 "Copiar"
	#define STR0011 "¡El campo de Carga horaria se configuró para no permitir la inclusión de una materia con carga horaria en cero!"
	#define STR0012 "Aviso"
	#define STR0013 "Segmentos"
	#define STR0014 "Atención"
	#define STR0015 "Ejecute el compatibilizador U_UPDGE45."
	#define STR0016 "OK"
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Subject Register"
		#define STR0007 "Search Equivalence Groups"
		#define STR0008 "Equivalence Group"
		#define STR0009 "This discipline belongs to an Equivalence Group Confirm change?"
		#define STR0010 "Replicate"
		#define STR0011 "Field Class Hours was set to not allow including a discipline with empty class hours"
		#define STR0012 "Warning"
		#define STR0013 "Segments"
		#define STR0014 "Attention"
		#define STR0015 "Execute the compatibility program U_UPDGE45"
		#define STR0016 "OK"
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Cadastro de Disciplinas"
		#define STR0007 "Consulta Grupos de Equivalência"
		#define STR0008 "Grupo de Equivalência"
		#define STR0009 "Essa disciplina faz parte de um Grupo de Equivalencia. Confirma a alteracao ?"
		#define STR0010 "Replicar"
		#define STR0011 "O campo de Carga horaria foi configurado para nao permitir a inclusao de uma disciplina com carga horaria zerada!!!"
		#define STR0012 "Aviso"
		#define STR0013 "Segmentos"
		#define STR0014 "Atencäo"
		#define STR0015 "Execute o compatibilizador U_UPDGE45"
		#define STR0016 "OK"
	#endif
#endif
