#ifdef SPANISH
	#define STR0001 "Servicio genérico para devolución de la información de Archivo de ausencias"
	#define STR0002 "Incluya un registro en el archivo de ausencias, en el módulo Gestión de personas"
	#define STR0003 "Borre un registro en el archivo de ausencias, en el módulo Gestión de personas"
	#define STR0004 "Modifique un registro en el archivo de ausencias, en el módulo Gestión de personas"
	#define STR0005 "No fue posible reconocer el paquete recibido. Verifique la información y envíe nuevamente."
	#define STR0006 "¡Error desconocido en el proceso!"
	#define STR0007 "Verifique la TAG ("
	#define STR0008 ") pues esta es obligatoria para el manejo de este proceso."
	#define STR0009 "Ocurrió una falla en la devolución de la información."
	#define STR0010 "Verifique el contenido de la TAG ("
	#define STR0011 ") pues no fue posible encontrar esta información en el Protheus."
	#define STR0012 "No fue posible finalizar la operación. ¡Verifique!"
	#define STR0013 ") pues la información está diferente del formato correcto: 1 o 2 o 3"
	#define STR0014 "Información leaveOfAbsenceId ausente o no válida."
	#define STR0015 "Error en la validación de la recepción del mensaje"
	#define STR0016 ") pues la hora no está en el formato correcto: 'HH:MM'"
	#define STR0017 "¡Operación realizada con éxito!"
	#define STR0018 ") pues está diferente del formado esperado: (yyyy-mm-ddThh:mm:ss)."
#else
	#ifdef ENGLISH
		#define STR0001 "Generic service for return of Absences Register information"
		#define STR0002 "Enter a record in absences register in Personnel Management module"
		#define STR0003 "Delete a record in absences register in Personnel Management module"
		#define STR0004 "Edit a record in absences register in Personnel Management module"
		#define STR0005 "The received package could not be recognized. Check the information and send again."
		#define STR0006 "Unknown error in the process."
		#define STR0007 "Check TAG ("
		#define STR0008 ") because it is required for handling this process."
		#define STR0009 "Failed to return information."
		#define STR0010 "Check content of TAG ("
		#define STR0011 ") because it was not possible to find this information in Protheus."
		#define STR0012 "Unable to finish this operation. Check it!"
		#define STR0013 ") as the information differs from the correct format: 1 or 2 or 3"
		#define STR0014 "Information leaveOfAbsenceId absent or not valid."
		#define STR0015 "Error validating message receipt"
		#define STR0016 ") because the time is not in the correct format: 'HH:MM."
		#define STR0017 "Operation successfully completed!"
		#define STR0018 ") as it differs from the expected format: (yyyy-mm-ddThh:mm:ss)."
	#else
		#define STR0001 "Serviço genérico para retorno das informações de Cadastro de Ausencias"
		#define STR0002 "Insere um registro no cadastro de ausências no módulo de Gestão de Pessoas"
		#define STR0003 "Exclui um registro no cadastro de ausências no módulo de Gestão de Pessoas"
		#define STR0004 "Altera um registro no cadastro de ausências no módulo de Gestão de Pessoas"
		#define STR0005 "Não foi possível reconhecer o pacote recebido. Verifique a informação e envie novamente."
		#define STR0006 "Erro desconhecido no processo!"
		#define STR0007 "Verifique a TAG ("
		#define STR0008 ") pois ela é obrigatória para a manipulação deste processo."
		#define STR0009 "Ocorreu uma falha no retorno da informação."
		#define STR0010 "Verifique o conteúdo da TAG ("
		#define STR0011 ") pois não foi possível encontrar esta informação no Protheus."
		#define STR0012 "Não poi possível concluir esta operação. Verifique!"
		#define STR0013 ") pois a informação está diferente do formato correto: 1 ou 2 ou 3"
		#define STR0014 "Informação leaveOfAbsenceId ausente ou inválida."
		#define STR0015 "Erro na validação do recebimento da mensagem"
		#define STR0016 ") pois a hora não está no formato correto: 'HH:MM."
		#define STR0017 "Operação realizada com sucesso!"
		#define STR0018 ") pois está diferente do formado esperado: (yyyy-mm-ddThh:mm:ss)."
	#endif
#endif
