#ifdef SPANISH
	#define STR0001 "Archivo de mnemonicos"
	#define STR0002 "Buscar   "
	#define STR0003 "Visualizar"
	#define STR0004 "Incluir"
	#define STR0005 "Modificar"
	#define STR0006 "Borrar"
	#define STR0007 "Salir"
	#define STR0008 "Confirma"
	#define STR0009 "¿Con respecto al borrado?"
	#define STR0010 "Ahora, el sistema efectuara la verificacion para ver si el mnemonico seleccionado "
	#define STR0011 "para el proceso de borrado esta en uso. ¡La verificaion quizas demore!"
	#define STR0012 "¿Confirma borrado de mnemonicos?"
	#define STR0013 "¡Atencion! "
	#define STR0014 "El mnemonico "
	#define STR0015 "no puede borrarse pues esta en uso, segun el seguiente detalle! "
	#define STR0016 "Archivo "
	#define STR0017 "Log de ocurrencias en el borrado de mnemonicos"
	#define STR0018 "¡Los Mnemonicos de sistema no pueden borrarse !"
	#define STR0019 "Leyenda"
	#define STR0020 "Mnemonico de Sistema"
	#define STR0021 "Mnemonico definido por usuario"
	#define STR0022 "Leyenda del archivo Mnemonico"
	#define STR0023 "Estaran disponibles solamente para visualizacion"
	#define STR0024 "Tipo y contenido del Mnemonico no son compatibles"
	#define STR0025 "El modo de acceso del Archivo  Mnemonicos debe ser OBLIGATORIAMENTE"
	#define STR0026 "compartido. Modifique el modo de acceso por el configurador."
	#define STR0027 "Generar Mnemon"
	#define STR0028 "Seleccione el Directorio"
	#define STR0029 "¡El archivo ya existe! ¿Desea sobrescribir?"
	#define STR0030 "Error de Grabacion del Archivo - Codigo DOS: "
	#define STR0031 "El/los Tipos(s) de Mnemonico(s)"
	#define STR0032 "no esta(n) registrado(s) en el ComboBox del Campo RCA_Tipo."
	#define STR0033 "El Programa"
	#define STR0034 " para Archivo de Mnemonicos Estandar se genero con exito."
	#define STR0035 "¡El archivo no se genero!"
	#define STR0036 "Mnemonico (Tipo parametro): Sistema"
	#define STR0037 "Cargando los Mnemonicos estandar"
	#define STR0038 "¿Incluir Mnemonico del Tipo parametro?"
	#define STR0039 "Privada"
	#define STR0040 "Publica"
	#define STR0041 "Local"
	#define STR0042 "Array"
	#define STR0043 "Bloque"
	#define STR0044 "Caracter"
	#define STR0045 "Fecha"
	#define STR0046 "Logico"
	#define STR0047 "Numerico"
	#define STR0048 "Indefinido"
	#define STR0049 "No es posible incluir Mnemonico pues ya"
	#define STR0050 " existe funcion, variable, mnemonico o "
	#define STR0051 " alias (tabla) con el mismo nombre del "
	#define STR0052 " Mnemonico informado. O el primer carac-"
	#define STR0053 "ter del mnemonico es invalido o existen"
	#define STR0054 " caracteres invalidos en el Mnemonico."
	#define STR0055 "Objeto"
	#define STR0056 "Localizar"
	#define STR0057 "Tablas"
	#define STR0058 "Texto localizado: "
	#define STR0059 "Buscar texto"
	#define STR0060 "Case sensitive"
	#define STR0061 "Donde buscar"
	#define STR0062 "Tabla"
	#define STR0063 "Campos"
	#define STR0064 "Filtros"
	#define STR0065 "Editar Filtro"
	#define STR0066 "Resultado Busqueda"
	#define STR0067 "Buscar"
	#define STR0068 "¡Verifique si se selecciono la Tabla o los Campos!"
	#define STR0069 "¡Texto para busqueda inferior a 5 caracteres!"
	#define STR0070 "Ocurrencias encontradas"
	#define STR0071 "Registro"
	#define STR0072 "Localizando... "
	#define STR0073 "Imprimir"
	#define STR0074 "Localizar Referencia Cruzada"
	#define STR0075 "Seleccione los Campos por Imprimir"
	#define STR0076 "A Rayas"
	#define STR0077 "Administracion"
	#define STR0078 "Reservado"
	#define STR0079 "Operador"
	#define STR0080 "Archivo"
	#define STR0081 "Los Mnemonicos del tipo Reservado y Operadores no pueden modificarse o borrarse."
	#define STR0082 "No se permite la inclusion o modificacion de mnemonicos del tipo Reservado y Operadores."
	#define STR0083 "Mnemonico Reservado"
	#define STR0084 "Operador"
	#define STR0085 "Mnemonico caractere, fecha, logico, num. ou arc."
	#define STR0086 "El codigo del mnemonico no puede "
	#define STR0087 " contener mas de 10 caracteres."
	#define STR0088 "No puede tener coma en el contenido."
	#define STR0089 "Utilice solo (punto) para separar las casas decimales."
	#define STR0090 "Se digito el valor en formato invalido."
	#define STR0091 "Mnemonico Invalido."
	#define STR0092 "Violacion de Integridad, con tabla RC2 - Encabezado de Formulas."
	#define STR0093 "¡Para el tipo archivo se debe incluir el alias y campo!"
	#define STR0094 "Mnemonico de Sistema ( Tipo Parametro )"
	#define STR0095 "El mnemnico lDissidio es de uso interno del sistema y no puede poseer contenido .T."
	#define STR0096 "El contenido del mnemonico LAXINSS esta vacio. Verifique"
	#define STR0097 "El contenido del mnemonico NDAXINSS aun esta con 15 dias. Verifique"
	#define STR0098 "Atencion, tiene licencias registradas en su base con fecha inicial a partir del Mnemonico DDTAXINSS"
	#define STR0099 "que se incluyeron antes de la aplicacion del patch referente a MP 664."
	#define STR0100 "Para actualizar automaticamente estas licencias utilizando las reglas de la MP 664, ejecute el compatibilizador: "
	#define STR0101 "En su base de datos se encontraron:"
	#define STR0102 "1 - Licencias del tipo O o P iniciados a partir de la fecha "
	#define STR0103 ", con dias empresa diferente del mnemonico NDAXINSS"
	#define STR0104 "2 - Licencias, con continuacion, que se inician a partir de la fecha "
	#define STR0105 ", siendo que la primera licencia de la secuencia se inicicio antes de la MP 664."
	#define STR0106 "Si quiere que el campo Dias Empresa se recalcule con base en la cantidad "
	#define STR0107 ", utilice el compatibilizador: "
	#define STR0108 "Este Mnemónico es del tipo fecha y no se rellenó correctamente, "
	#define STR0109 "favor informe una fecha en el formato DD/MM/AAAA."
	#define STR0110 "O rellene con // cuando no quiera informar una fecha."
	#define STR0111 "El archivo"
	#define STR0112 "ya existe. ¿Desea sobrescribir?"
	#define STR0113 "All (todos los países)"
	#define STR0114 "(conforme base en uso)"
	#define STR0115 "El campo Todos los Países (RCA_ALL) es de complemento obligatorio en la inclusión."
#else
	#ifdef ENGLISH
		#define STR0001 "Mnemonics File "
		#define STR0002 "Search   "
		#define STR0003 "View      "
		#define STR0004 "Insert "
		#define STR0005 "Edit   "
		#define STR0006 "Delete "
		#define STR0007 "Quit"
		#define STR0008 "Confirm"
		#define STR0009 "About Deletion?"
		#define STR0010 "The System will now verify if the Mnemonic selected"
		#define STR0011 "is being used. Verification can take time !! "
		#define STR0012 "Confirm deletion of Mnemonic?"
		#define STR0013 "Warning!"
		#define STR0014 "Mnemonic "
		#define STR0015 "cannot be deleted as it is being used as shown below! "
		#define STR0016 "File "
		#define STR0017 "Mnemonics deletion occurrences Log "
		#define STR0018 "System mnemonics cannot be deleted!"
		#define STR0019 "Caption"
		#define STR0020 "System Mnemonics"
		#define STR0021 "Mnemonics Defined by the User"
		#define STR0022 "Caption of Mnemonic Record"
		#define STR0023 "Will be available only for viewing"
		#define STR0024 "Mnemonics Type and Contents are incompatible"
		#define STR0025 "The Access Mode for Mnemonics File must be COMPULSORY"
		#define STR0026 "Shared. Change the Access Mode Through the Configurator."
		#define STR0027 "Generate Mnemon"
		#define STR0028 "Select the Directory"
		#define STR0029 "File already exists! Overwrite it?"
		#define STR0030 "Error Ehile Saving File - DOS Code: "
		#define STR0031 "The Type(s)of Mnemonic(s)"
		#define STR0032 "is (are) not registered in ComboBox of RCA_Tipo Field."
		#define STR0033 "Program"
		#define STR0034 " for Registration of Standard Mnemonics successfully generated."
		#define STR0035 "File not generated!"
		#define STR0036 "Mnemonic (Parameter type): System"
		#define STR0037 "Loading standard Mnemonics"
		#define STR0038 "Add Mnemonic of parameter Type?"
		#define STR0039 "Private"
		#define STR0040 "Public"
		#define STR0041 "Location"
		#define STR0042 "Array"
		#define STR0043 "Block"
		#define STR0044 "Character"
		#define STR0045 "Date"
		#define STR0046 "Logical"
		#define STR0047 "Numeric"
		#define STR0048 "Undefined"
		#define STR0049 "Unable to add Mnemonic, as there is"
		#define STR0050 " already a function, variable, mnemonic or "
		#define STR0051 " alias (table) with the same name as the "
		#define STR0052 " Mnemonic entered. The first mnemonic"
		#define STR0053 "character is invalid or there are"
		#define STR0054 " invalid characters for the Mnemonic."
		#define STR0055 "Object"
		#define STR0056 "Find"
		#define STR0057 "Tables"
		#define STR0058 "Text found: "
		#define STR0059 "Search for text"
		#define STR0060 "Case sensitive"
		#define STR0061 "Where to search for"
		#define STR0062 "Table"
		#define STR0063 "Fields"
		#define STR0064 "Filters"
		#define STR0065 "Edit Filter"
		#define STR0066 "Search Result"
		#define STR0067 "Search"
		#define STR0068 "Check selection of Table or Fields!"
		#define STR0069 "Text for search contains less than 5 characters!"
		#define STR0070 "Occorrences found"
		#define STR0071 "Record"
		#define STR0072 "Finding... "
		#define STR0073 "Print"
		#define STR0074 "Find Cross Reference"
		#define STR0075 "Select Fields to Print"
		#define STR0076 "Z.form"
		#define STR0077 "Administration"
		#define STR0078 "Reserved"
		#define STR0079 "Operator"
		#define STR0080 "File"
		#define STR0081 "Mnemonics of Reserved and Operator type cannot be edited or deleted."
		#define STR0082 "You cannot add or edit mnemonics of Reserved and Operators type."
		#define STR0083 "Reserved Mnemonic"
		#define STR0084 "Operator"
		#define STR0085 "Character, date, logical, num. or file Mnemonic."
		#define STR0086 "Mnemonic code cannot "
		#define STR0087 " contain more than 10 characters."
		#define STR0088 "Cannot contain comma."
		#define STR0089 "Use only (dot) to separate decimal places."
		#define STR0090 "Invalid format for value entered."
		#define STR0091 "Invalid Mnemonic."
		#define STR0092 "Violation of Integrity with table RC2 - Formula Header."
		#define STR0093 "For the File Type, add Alias and Field!"
		#define STR0094 "System Mnemonic (Parameter Type)"
		#define STR0095 "The mnemonic lDissidio is for internal usage of the system and cannot have content .T."
		#define STR0096 "Mnemonic content LAXINSS is empty. Check it"
		#define STR0097 "Mnemonic content NVDAXINSS still has 15 days. Check it"
		#define STR0098 "Attention, you have leaves registered in its base with Start date from the Mnemonic DDTAXINSS"
		#define STR0099 "included before the patch application referring to MP 664."
		#define STR0100 "To automatically update these leaves using MP 664 rules, run the compatibility program: "
		#define STR0101 "Found in your Database:"
		#define STR0102 "1 - Leaves of the O or P type started from date "
		#define STR0103 ", with Company Days different from the mnemonic NVDAXINSS"
		#define STR0104 "2 - Leaves, with continuation, starting from the date "
		#define STR0105 ", considering that the first sequence leave started before MP 664."
		#define STR0106 "If you want the Company Days field to be recalculated based on quantity "
		#define STR0107 ", run the compatibility program: "
		#define STR0108 "This Mnemonic is of the date type and not properly completed, "
		#define STR0109 "please enter a date on format DD/MM/YYYY."
		#define STR0110 "Or enter // if you do not wish to enter a date."
		#define STR0111 "File"
		#define STR0112 "already exists. Overwrite it ?"
		#define STR0113 "All (all countries)"
		#define STR0114 "(according to base in use)"
		#define STR0115 "The All Countries field (RCA_ALL) is of mandatory completion on inclusion."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Registo Mnemónicas", "Cadastro de Mnemonicos" )
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Excluir"
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Abandonar", "Abandona" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Confirma", "confirma" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Quanto à eliminação ?", "Quanto a Exclusäo ?" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "O Sistema irá agora efectuar a verificaçäo para ver se o mnemónico seleccionado", "O Sistema agora ira efetuar a Verificacäo para ver se o Mnemonico selecionado" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", 'eStá a ser utilizado. A verificação pode ser demorada !!', "está sendo utilizado. A verificaçäo pode ser demorada !! " )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Confirma a exclusão da Mnemónica?", "Confirma a exclusäo do Mnemonico?" )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Atenção !", "Atençäo !" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "O Mnemónico ", "O Mnemonico " )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", 'não pode ser excluído pois está a ser utilizado conforme  abaixo!', "näo pode ser excluido pois está sendo utilizado conforme  abaixo! " )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Ficheiro ", "Arquivo " )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Log de Ocorrências na Exclusão de Mnemónicas", "Log de Ocorrências na Exclusäo de Mnemonicos" )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Os Mnemónicos de sistema não podem ser eliminados.", "Os Mnemonicos de sistema näo podem ser excluidos !" )
		#define STR0019 "Legenda"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Mnemónico de sistema", "Mnemonico de Sistema" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Mnemónica Definida Pelo Utilizador", "Mnemonico Definido Pelo Usuario" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Legenda do Registo de Mnemónica", "Legenda do Cadastro de Mnemonico" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Serão Disponibilizados Apenas Para Visualização", "Seräo disponibilizados apenas para Visualizacäo" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Tipo e Conteúdo da Mnemónica nao säo compatíveis", "Tipo e Conteudo do Mnemonico nao säo compativeis" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "O Modo de Acesso do Registo de Mnemónicas deve ser OBRIGATORIAMENTE", "O Modo de Acesso do Cadastro de Mnemonicos deve ser OBRIGATORIAMENTE" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Partilhado. Altere O Modo De Acesso Através Do Configurador.", "Compartilhado. Altere o Modo de Acesso Atraves do Configurador." )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Criar Mnemon", "Gerar Mnemon" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Seleccione O Directório", "Selecione o Diretório" )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "O ficheiro já existe!! deseja sobrescrever?", "O arquivo já existe!! Deseja sobrescrever?" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Erro de gravação do ficheiro - código dos: ", "Erro de Gravação do Arquivo - Código DOS: " )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "O(s) tipos(s) de memorização(s)", "O(s) Tipos(s) de Mnemônico(s)" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Não esta(o) registado(s) no combobox do campo rca_tipo.", "não esta(o) cadastrado(s) no ComboBox do Campo RCA_Tipo." )
		#define STR0033 "O Programa"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", " para registo de mnemónicos padrões foi criado com sucesso.", " para Cadastro de Mnemônicos Padrões foi gerado com sucesso." )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "O ficheiro não foi criado!", "O arquivo não foi gerado!" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Mnemónico (Tipo parâmetro): Sistema", "Mnemônico (Tipo parâmetro): Sistema" )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "A carregar os memorizaçãos padroes", "Carregando os Mnemônicos padrões" )
		#define STR0038 "Incluir Mnemônico do Tipo parâmetro?"
		#define STR0039 "Privada"
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Publica", "Pública" )
		#define STR0041 "Local"
		#define STR0042 "Array"
		#define STR0043 "Bloco"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Carácter", "Caracter" )
		#define STR0045 "Data"
		#define STR0046 "Lógico"
		#define STR0047 "Numérico"
		#define STR0048 "Indefinido"
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Não e possível inserir memorização pois ja", "Não é possível incluir Mnemônico pois já" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", " existe função, variável, mnemónica ou ", " existe função, variável, mnemônico ou " )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", " álias (tabela) com o mesmo nome do ", " alias (tabela) com o mesmo nome do " )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", " Mnemónica informada. Ou o primeiro carac-", " Mnemônico informado. Ou o primeiro carac-" )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "tere da mnemónica é inválido ou existem", "tere do mnemônico é inválido ou existem" )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", " caracteres inválidos na Mnemónica.", " caracteres inválidos no Mnemônico." )
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Objecto", "Objeto" )
		#define STR0056 "Localizar"
		#define STR0057 "Tabelas"
		#define STR0058 "Texto localizado: "
		#define STR0059 "Pesquisar texto"
		#define STR0060 "Case sensitive"
		#define STR0061 "Onde pesquisar"
		#define STR0062 "Tabela"
		#define STR0063 "Campos"
		#define STR0064 "Filtros"
		#define STR0065 "Editar Filtro"
		#define STR0066 "Resultado Pesquisa"
		#define STR0067 "Pesquisar"
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Verificar Se Foi Selecciionado A Tabela Ou Os Campos!", "Verifique se foi seleciionado a Tabela ou os Campos!" )
		#define STR0069 "Texto para pesquisa menor que 5 caracteres!"
		#define STR0070 "Ocorrências encontradas"
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Registo", "Registro" )
		#define STR0072 "Localizando... "
		#define STR0073 "Imprimir"
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Localizar referencia cruzada", "Localizar Referência Cruzada" )
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Seleccionar Os Campos A Imprimir", "Selecione os Campos a Imprimir" )
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0077 "Administração"
		#define STR0078 "Reservado"
		#define STR0079 "Operador"
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "Ficheiro", "Arquivo" )
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "Os memorizaçãos do tipo reservado e operadores não podem ser alterados ou excluidos.", "Os Mnemônicos do tipo Reservado e Operadores não podem ser alterados ou excluídos." )
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Não e permitido a inclusão ou alteração  de memorizaçãos do tipo reservado e operadores.", "Não é permitido a inclusão ou alteração de mnemônicos do tipo Reservado e Operadores." )
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "Mnemónico Reservado", "Mnemônico Reservado" )
		#define STR0084 "Operador"
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "Memorização caractere, data, lógico, num. ou arq.", "Mnemônico caractere, data, lógico, num. ou arq." )
		#define STR0086 If( cPaisLoc $ "ANG|PTG", "O código  do memorização não pode ", "O código do mnemônico não pode " )
		#define STR0087 " conter mais de 10 caracteres."
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "O conteúdo não pode conter vírgula.", "Não pode conter vírgula no conteúdo." )
		#define STR0089 "Utilize apenas (ponto) para separar as casas decimais."
		#define STR0090 "Valor digitado em formato inválido."
		#define STR0091 If( cPaisLoc $ "ANG|PTG", "Mnemónico Inválido.", "Mnemônico Inválido." )
		#define STR0092 "Violação de Integridade, com tabela RC2 - Cabeçalho de Fórmulas."
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "Para o Tipo Ficheiro, deve-se incluir alias e campo.", "Para o Tipo Arquivo deve-se incluir Alias e Campo!" )
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Mnemónico de sistema ( Tipo parâmetro )", "Mnemonico de Sistema ( Tipo Parametro )" )
		#define STR0095 "O mnemônico lDissidio é de uso interno do sistema e não pode possuir conteúdo .T."
		#define STR0096 "O conteúdo do mnemônico LAXINSS está vazio. Verifique"
		#define STR0097 "O conteúdo do mnemônico NDAXINSS ainda está com 15 dias. Verifique"
		#define STR0098 "Atenção, você tem afastamentos cadastrados em sua base com data de Inicio a partir do Mnemônico DDTAXINSS"
		#define STR0099 "que foram incluídos antes da aplicação do patch referente a MP 664."
		#define STR0100 "Para atualizar automaticamente esses afastamentos utilizando as regras da MP 664, execute o compatibilizador: "
		#define STR0101 "Em sua base de Dados foram encontrados:"
		#define STR0102 "1 - Afastamentos do tipo O ou P iniciados a partir da data "
		#define STR0103 ", com Dias Empresa diferente do mnemônico NDAXINSS"
		#define STR0104 "2 - Afastamentos, com continuação, que se iniciam a partir da data "
		#define STR0105 ", sendo que o primeiro afastamento da sequencia, iniciou-se antes da MP 664."
		#define STR0106 "Caso queira que o campo Dias Empresa seja recalculado com base na quantidade "
		#define STR0107 ", utilize o compatibilizador: "
		#define STR0108 "Este Mnemônico é do tipo data e não foi preenchido corretamente, "
		#define STR0109 "favor informar uma data no formato DD/MM/AAAA."
		#define STR0110 "Ou preencher com // caso não queira informar uma data."
		#define STR0111 "O arquivo"
		#define STR0112 "já existe. Deseja Sobrescrever ?"
		#define STR0113 "All (todos os países)"
		#define STR0114 "(conforme base em uso)"
		#define STR0115 "O campo Todos os Países (RCA_ALL) é de preenchimento obrigatório na inclusão."
	#endif
#endif
