#ifdef SPANISH
	#define STR0001 "Combinacion de clave y operacion del mensaje son invalidas"
	#define STR0002 "Codigo del concepto no encontrado"
	#define STR0003 "Codigo del Centro de costo no informado en el mensaje"
	#define STR0004 "Codigo de Centro de Costo no identificado. "
	#define STR0005 "Item numero "
	#define STR0006 "Estructura del Xml invalida"
	#define STR0007 "Actualice EAI"
	#define STR0008 "Falla al manejar el XML"
	#define STR0009 "Adapter no trata la version "
	#define STR0010 "Las versiones disponibles son: "
	#define STR0011 "No se envio el contenido de devolucion para el registro de de-a"
	#define STR0012 "No es posible grabar de-a por causa de un error en la lectura de devolucion"
	#define STR0013 "Error en el procesamiento por la otra aplicacion"
	#define STR0014 "Error en el procesamiento, pero sin detalles del error por la otra aplicacion"
	#define STR0015 "Falla en la lectura de la respuesta, no se grabara de-a"
#else
	#ifdef ENGLISH
		#define STR0001 "Combination of key and operation of message not valid"
		#define STR0002 "Funds code not found"
		#define STR0003 "Cost Center Code not indicated in the message"
		#define STR0004 "Cost Center Code not identified. "
		#define STR0005 "Number item "
		#define STR0006 "Xml structure not valid"
		#define STR0007 "Update EAI"
		#define STR0008 "Failure when loading XML"
		#define STR0009 "Adapter does not treat the version "
		#define STR0010 "The available versions are: "
		#define STR0011 "Return content for from-to register not sent"
		#define STR0012 "You cannot save from-to due to return reading error"
		#define STR0013 "Error in processing by the other application"
		#define STR0014 "Error in processing, by without details of error by other application"
		#define STR0015 "Failure in answer reading, from-to is not saved"
	#else
		#define STR0001 "Combinação de chave e operação da mensagem não são válidas"
		#define STR0002 "Código da verba não encontrado"
		#define STR0003 "Codigo do Centro de custo não informado na mensagem"
		#define STR0004 "Código de Centro de Custo não identificado. "
		#define STR0005 "Item numero "
		#define STR0006 "Estrutura do Xml inválida"
		#define STR0007 "Atualize EAI"
		#define STR0008 "Falha ao manipular o XML"
		#define STR0009 "Adapter não trata a versão "
		#define STR0010 "As versões disponíveis são: "
		#define STR0011 "Não enviado conteúdo de retorno para cadastro de de-para"
		#define STR0012 "Não é possível gravar de-para por causa de erro na leitura do retorno"
		#define STR0013 "Erro no processamento pela outra aplicação"
		#define STR0014 "Erro no processamento, mas sem detalhes do erro pela outra aplicação"
		#define STR0015 "Falha na leitura da resposta, de-para não será gravado"
	#endif
#endif
