#ifdef SPANISH
	#define STR0001 "Processamento Benefícios"
	#define STR0002 "Permitir realizar a atualização do(s) benefício(s) dos funcionários de acordo com o que foi definido "
	#define STR0003 "no relacionamento entre entidade e  benefícios para controle do plano de saúde e execução"
	#define STR0004 "do cálculo automático de benefícios."
	#define STR0005 " "
	#define STR0006 "Parametrização"
	#define STR0007 "Selecione os parâemtros que serão utilizados na pesquisa"
	#define STR0008 "Seleção de funcionários"
	#define STR0009 "Selecione os funcionários que deverão ter os planos atualizados"
	#define STR0010 "Cod. Atual"
	#define STR0011 "Cod. Criterio"
	#define STR0012 "Plano Atual"
	#define STR0013 "Plano Criterio"
	#define STR0014 "Funcionário : "
	#define STR0015 "Processando"
	#define STR0016 "Atualizando Plano de Saúde conforme funcionários selecionados."
	#define STR0017 "Funcionários"
	#define STR0018 "Atenção"
	#define STR0019 "Deseja efetuar a atualização dos benefícios ?"
	#define STR0020 "Processamento cancelado pelo usuário"
	#define STR0021 "Informacoes do Processamento"
	#define STR0022 "Inicio do Processamento:"
	#define STR0023 " de "
	#define STR0024 "********* Plano atualizado com sucesso ***********"
	#define STR0025 "********* Plano NÃO atualizado ***********"
	#define STR0026 "Processamento Finalizado, consulte o LOG"
	#define STR0027 "Log de Ocorrencias no Processo de Calculo"
	#define STR0028 "Total de Dependentes  : "
	#define STR0029 "Dependentes Atualizados : "
	#define STR0030 "Titular - Plano Atual  : "
	#define STR0031 "Titular - Plano Devido  : "
	#define STR0032 "Titular - Plano Inativado  : "
	#define STR0033 "Fornecedor: "
	#define STR0034 "Tipo Plano: "
	#define STR0035 "Plano"
	#define STR0036 "Dependente - Plano Atual  : "
	#define STR0037 "Dependente - Plano Devido  : "
	#define STR0038 "Dependente - Plano Inativado  : "
	#define STR0039 "Mensagem do erro: "
	#define STR0040 "Agregado - Plano Atual  : "
	#define STR0041 "Agregado - Plano Devido  : "
	#define STR0042 "Agregado - Plano Inativado  : "
	#define STR0043 "Nenhum funcionario selecionado"
	#define STR0044 "Funcionários selecionados : "
	#define STR0045 "Funcionários processados com sucesso : "
	#define STR0046 "Atualizando Cadastro"
	#define STR0047 "Atualizando Titular"
	#define STR0048 "Atualizando Dependente"
	#define STR0049 "Atualizando Agregado"
#else
	#ifdef ENGLISH
		#define STR0001 "Benefits Processing"
		#define STR0002 "Allow update of employees update according to what was defined "
		#define STR0003 "in the relationship between entity and benefits for health care plan control and execution"
		#define STR0004 "of benefits automatic calculation."
		#define STR0005 " "
		#define STR0006 "Parameterization"
		#define STR0007 "Select the parameters that are used during the search"
		#define STR0008 "Employees selection"
		#define STR0009 "Select employees that must have their plans updated"
		#define STR0010 "Current Code"
		#define STR0011 "Criterion Code"
		#define STR0012 "Current Plan"
		#define STR0013 "Criterion Plan"
		#define STR0014 "Employee: "
		#define STR0015 "Processing"
		#define STR0016 "Updating Health Care Plan according to selected employees."
		#define STR0017 "Employees"
		#define STR0018 "Attention"
		#define STR0019 "Do you want to update benefits?"
		#define STR0020 "Process canceled by user"
		#define STR0021 "Processing information"
		#define STR0022 "Processing start:"
		#define STR0023 " from "
		#define STR0024 "********* Plan successfully updated ********* "
		#define STR0025 "********* Plan NOT updated ***********"
		#define STR0026 "Finished Processing, query LOG"
		#define STR0027 "Occurrences Log in the Calculation Process"
		#define STR0028 "Total of Dependents: "
		#define STR0029 "Updated Dependents: "
		#define STR0030 "Holder - Current Plan: "
		#define STR0031 "Holder - Owed Plan: "
		#define STR0032 "Holder - Inactive Plan: "
		#define STR0033 "Supplier: "
		#define STR0034 "Plan Type: "
		#define STR0035 "Plan"
		#define STR0036 "Dependent - Current Plan: "
		#define STR0037 "Dependent - Owed Plan: "
		#define STR0038 "Dependent - Inactive Plan "
		#define STR0039 "Error message: "
		#define STR0040 "Aggregated - Current Plan: "
		#define STR0041 "Aggregated - Owed Plan: "
		#define STR0042 "Aggregated - Inactive Plan: "
		#define STR0043 "No employee selected."
		#define STR0044 "Selected employees: "
		#define STR0045 "Employees successfully processed: "
		#define STR0046 "Updating Register"
		#define STR0047 "Updating Holder"
		#define STR0048 "Updating Dependent"
		#define STR0049 "Updating Household Member"
	#else
		#define STR0001 "Processamento Benefícios"
		#define STR0002 "Permitir realizar a atualização do(s) benefício(s) dos funcionários de acordo com o que foi definido "
		#define STR0003 "no relacionamento entre entidade e  benefícios para controle do plano de saúde e execução"
		#define STR0004 "do cálculo automático de benefícios."
		#define STR0005 " "
		#define STR0006 "Parametrização"
		#define STR0007 "Selecione os parâemtros que serão utilizados na pesquisa"
		#define STR0008 "Seleção de funcionários"
		#define STR0009 "Selecione os funcionários que deverão ter os planos atualizados"
		#define STR0010 "Cod. Atual"
		#define STR0011 "Cod. Criterio"
		#define STR0012 "Plano Atual"
		#define STR0013 "Plano Criterio"
		#define STR0014 "Funcionário : "
		#define STR0015 "Processando"
		#define STR0016 "Atualizando Plano de Saúde conforme funcionários selecionados."
		#define STR0017 "Funcionários"
		#define STR0018 "Atenção"
		#define STR0019 "Deseja efetuar a atualização dos benefícios ?"
		#define STR0020 "Processamento cancelado pelo usuário"
		#define STR0021 "Informacoes do Processamento"
		#define STR0022 "Inicio do Processamento:"
		#define STR0023 " de "
		#define STR0024 "********* Plano atualizado com sucesso ***********"
		#define STR0025 "********* Plano NÃO atualizado ***********"
		#define STR0026 "Processamento Finalizado, consulte o LOG"
		#define STR0027 "Log de Ocorrencias no Processo de Calculo"
		#define STR0028 "Total de Dependentes  : "
		#define STR0029 "Dependentes Atualizados : "
		#define STR0030 "Titular - Plano Atual  : "
		#define STR0031 "Titular - Plano Devido  : "
		#define STR0032 "Titular - Plano Inativado  : "
		#define STR0033 "Fornecedor: "
		#define STR0034 "Tipo Plano: "
		#define STR0035 "Plano"
		#define STR0036 "Dependente - Plano Atual  : "
		#define STR0037 "Dependente - Plano Devido  : "
		#define STR0038 "Dependente - Plano Inativado  : "
		#define STR0039 "Mensagem do erro: "
		#define STR0040 "Agregado - Plano Atual  : "
		#define STR0041 "Agregado - Plano Devido  : "
		#define STR0042 "Agregado - Plano Inativado  : "
		#define STR0043 "Nenhum funcionario selecionado"
		#define STR0044 "Funcionários selecionados : "
		#define STR0045 "Funcionários processados com sucesso : "
		#define STR0046 "Atualizando Cadastro"
		#define STR0047 "Atualizando Titular"
		#define STR0048 "Atualizando Dependente"
		#define STR0049 "Atualizando Agregado"
	#endif
#endif
