#ifdef SPANISH
	#define STR0001 "Sucursal + Evento + Clave ERP + RCPJ Destino"
	#define STR0002 "Procesar"
	#define STR0003 "Procesar eventos e-Social"
	#define STR0004 "Eventos procesados:"
	#define STR0005 "Importado Terc."
	#define STR0006 "Atención"
	#define STR0007 "Ningún evento se seleccionó."
	#define STR0008 "Ocurrió un error en la grabación del registro en la tabla RJE Eventos"
	#define STR0009 "Registro del evento S-1000 no encontrado en la base de datos"
	#define STR0010 "Registro del evento S-1000 no se transmitió al gobierno"
	#define STR0011 "Registro del evento S-1000 esperando respuesta del gobierno"
	#define STR0012 "Registro del evento S-1000 devuelto con error del gobierno"
	#define STR0013 "Problema con el evento S-1000"
	#define STR0014 "Eventos"
	#define STR0015 "Log de ocurrencias"
	#define STR0016 "Monitoreo del(os) evento(s):"
	#define STR0017 "Evento(s) procesado(s):"
	#define STR0018 "Key:"
	#define STR0019 "Sucursal:"
	#define STR0020 "Evento:"
	#define STR0021 "Estatus:"
	#define STR0022 "Inscripción:"
	#define STR0023 "No hay registros"
	#define STR0024 "Evento(s) no procesado(s):"
	#define STR0025 "Motivo:"
	#define STR0026 "Log de procesamiento de eventos"
	#define STR0027 "procesado con éxito."
	#define STR0028 "Recibo:"
	#define STR0029 "Evento:"
	#define STR0030 "no procesado porque ya existe información del recibo:"
	#define STR0031 "en la tabla RJE."
	#define STR0032 "con el ID del gobierno:"
	#define STR0033 "no tiene número de recibo y no se procesará"
	#define STR0034 "No se encontró ningún registro."
	#define STR0035 "en el Middleware."
	#define STR0036 "[FALLA] No fue posible encontrar el registro del empleado"
	#define STR0037 "CPF:"
	#define STR0038 "El campo RJE_IDMDEV no se incorporó a la tabla RJE. El procesamiento de los eventos periódicos no se finalizará."
	#define STR0039 "[FALLA] No se encontró el registro S-1299 para el período informado."
	#define STR0040 "en la base de datos."
	#define STR0041 "[FALLA] No se encontró el registro de la licencia para el empleado"
	#define STR0042 "Para utilizar el migrador, la empresa debe operar con el Middleware activado."
#else
	#ifdef ENGLISH
		#define STR0001 "Branch + Event + ERP key + Target EIN"
		#define STR0002 "Process"
		#define STR0003 "Process eSocial events"
		#define STR0004 "Processed Events:"
		#define STR0005 "Third-p. imported"
		#define STR0006 "Attention"
		#define STR0007 "No event selected."
		#define STR0008 "Error saving record in RJE table. Event:"
		#define STR0009 "Record of event S-1000 not found in database"
		#define STR0010 "Record of event S-1000 not transmitted to government"
		#define STR0011 "Record of event S-1000 expecting government return"
		#define STR0012 "Record of event S-1000 returned from government with error"
		#define STR0013 "Issue with Event S-1000"
		#define STR0014 "Event"
		#define STR0015 "Occurrence Log"
		#define STR0016 "Event Monitoring:"
		#define STR0017 "Events Processed:"
		#define STR0018 "Key:"
		#define STR0019 "Branch:"
		#define STR0020 "Event:"
		#define STR0021 "Status:"
		#define STR0022 "Registration:"
		#define STR0023 "No records"
		#define STR0024 "Events Not Processed:"
		#define STR0025 "Reason:"
		#define STR0026 "Event Processing Log"
		#define STR0027 "processed successfully."
		#define STR0028 "Receipt:"
		#define STR0029 "Event:"
		#define STR0030 "not processed because information already exists for receipt:"
		#define STR0031 "in the RJE table."
		#define STR0032 "with the government ID:"
		#define STR0033 "lacks receipt number and will not be processed"
		#define STR0034 "No record found."
		#define STR0035 "in Middleware."
		#define STR0036 "[FAILURE] Unable to find the Employee’s record"
		#define STR0037 "SSN:"
		#define STR0038 "RJE_IDMDEV field not incorporated to the RJE table. The periodic events processing will not be completed."
		#define STR0039 "[FAILURE] Record S-1299 not found for the period."
		#define STR0040 "in database."
		#define STR0041 "[FAILURE] Leave record not found for employee"
		#define STR0042 "To use the migrator, the company must run it with the Middleware activated."
	#else
		#define STR0001 "Filial + Evento + Chave ERP + CNPJ Destino"
		#define STR0002 "Processar"
		#define STR0003 "Processar Eventos e-Social"
		#define STR0004 "Eventos Processados:"
		#define STR0005 "Importado Terc."
		#define STR0006 "Atenção"
		#define STR0007 "Nenhum evento foi selecionado."
		#define STR0008 "Ocorreu um erro na gravação do registro na tabela RJE.  Evento: "
		#define STR0009 "Registro do evento S-1000 não localizado na base de dados"
		#define STR0010 "Registro do evento S-1000 não transmitido para o governo"
		#define STR0011 "Registro do evento S-1000 aguardando retorno do governo"
		#define STR0012 "Registro do evento S-1000 retornado com erro do governo"
		#define STR0013 "Problema com o Evento S-1000"
		#define STR0014 "Evento"
		#define STR0015 "Log de Ocorrências"
		#define STR0016 "Monitoramento do(s) Evento(s): "
		#define STR0017 "Evento(s) Processado(s): "
		#define STR0018 "Key: "
		#define STR0019 "Filial: "
		#define STR0020 "Evento: "
		#define STR0021 "Status: "
		#define STR0022 "Inscrição: "
		#define STR0023 "Não há registros"
		#define STR0024 "Evento(s) Não Processado(s): "
		#define STR0025 "Motivo: "
		#define STR0026 "Log de Processamento de Eventos"
		#define STR0027 " processado com sucesso."
		#define STR0028 " Recibo: "
		#define STR0029 "Evento: "
		#define STR0030 " não processado pois já existe informação do recibo: "
		#define STR0031 " na tabela RJE."
		#define STR0032 " com o ID do governo: "
		#define STR0033 " não possui número de recibo e não será processado"
		#define STR0034 "Nenhum registro encontrado."
		#define STR0035 " no Middleware."
		#define STR0036 "[FALHA] Não foi possivel encontrar o registro do Funcionário"
		#define STR0037 "Cpf: "
		#define STR0038 "Campo RJE_IDMDEV não incorporado a tabela RJE. O processamento dos eventos periódicos não será concluido."
		#define STR0039 "[FALHA] Não encontrado registro S-1299 para o periodo informado."
		#define STR0040 " na base de dados."
		#define STR0041 "[FALHA] Não encontrado registro do afastamento para o funcionário "
		#define STR0042 "Para utilização do migrador, a empresa deverá operar com o Middleware ativado."
	#endif
#endif
