#ifdef SPANISH
	#define STR0001 "Informe de otros beneficios se imprimira de acuerdo con los parametros informados por el usuario."
	#define STR0002 "Informe de otros beneficios"
	#define STR0003 "Matricula"
	#define STR0004 "Nombre"
	#define STR0005 "C. Costo + Matricula"
	#define STR0006 "C. Costo + Nombre"
	#define STR0007 "Depto. + Matricula"
	#define STR0008 "Depto. Nombre"
	#define STR0009 "Esta rutina genera un informe con las informaciones del calculo de otros beneficios"
	#define STR0010 "Empleado"
	#define STR0011 "Tipo de beneficio"
	#define STR0012 "Cod. del beneficio"
	#define STR0013 "Valor beneficio"
	#define STR0014 "Valor Desc. Empl."
	#define STR0015 "Valor pagado Emp."
	#define STR0016 "Total"
	#define STR0017 "       TOTAL C.COSTO "
	#define STR0018 "VALOR TOTAL"
	#define STR0019 "       TOTAL DEPARTAMENTO "
	#define STR0020 "       TOTAL SUCURSAL "
	#define STR0021 "Base Calculo"
	#define STR0022 "¡Periodo no encontrado!"
	#define STR0023 "¡Atencion!"
	#define STR0024 "Proceso + Periodo + Numero de Pago no encontrado"
#else
	#ifdef ENGLISH
		#define STR0001 "Report of Other Benefits is printed in accordance with the parameters entered by the user."
		#define STR0002 "Register of Other Benefits"
		#define STR0003 "Registration"
		#define STR0004 "Name"
		#define STR0005 "Cost C. + Registration"
		#define STR0006 "Cost C. + Name"
		#define STR0007 "Department + Registration"
		#define STR0008 "Department +Name"
		#define STR0009 "This routine generates a report with information of Other Benefits calculation"
		#define STR0010 "Employee"
		#define STR0011 "Benefit Type"
		#define STR0012 "Benefit Code"
		#define STR0013 "Benefit Value"
		#define STR0014 "Empl Disc Value"
		#define STR0015 "Comp. Paid Value"
		#define STR0016 "Total"
		#define STR0017 "       COST C. TOTAL "
		#define STR0018 "TOTAL AMOUNT"
		#define STR0019 "       DEPARTMENT TOTAL "
		#define STR0020 "       BRANCH TOTAL "
		#define STR0021 "Calc Base"
		#define STR0022 "Period not found."
		#define STR0023 "Attention!"
		#define STR0024 "Process + Period + Payment Number not found"
	#else
		#define STR0001 "Relatório de Outros Beneficios será impresso de acordo com os parâmetros informados pelo usuário."
		#define STR0002 "Relatório de Outros Beneficios"
		#define STR0003 "Matrícula"
		#define STR0004 "Nome"
		#define STR0005 "C. Custo + Matrícula"
		#define STR0006 "C. Custo + Nome"
		#define STR0007 "Depto. + Matrícula"
		#define STR0008 "Depto. + Nome"
		#define STR0009 "Esta rotina gera um relatório com as informações do cálculo de Outros Beneficios"
		#define STR0010 "Funcionário"
		#define STR0011 "Tipo de Beneficio"
		#define STR0012 "Cód. do Beneficio"
		#define STR0013 "Valor Beneficio"
		#define STR0014 "Valor Desc. Func."
		#define STR0015 "Valor Pago Emp."
		#define STR0016 "Total"
		#define STR0017 "       TOTAL C.CUSTO "
		#define STR0018 "VALOR TOTAL"
		#define STR0019 "       TOTAL DEPARTAMENTO "
		#define STR0020 "       TOTAL FILIAL "
		#define STR0021 "Base Cálculo"
		#define STR0022 "Periodo nao encontrado!"
		#define STR0023 "Atenção!"
		#define STR0024 "Processo + Período + Número de Pagamento não encontrado"
	#endif
#endif
