#ifdef SPANISH
	#define STR0001 "FORMULARIO DE APORTE DE FONDO SOLIDARIO"
	#define STR0002 "Se imprimira de acuerdo con los parametros solicitados por el usuario."
	#define STR0003 "Obs.: Se debe imprimir un Formulario mensual para cada sucursal."
	#define STR0004 "Sucursal + Matricula"
	#define STR0005 "Sucursal + C. Costo"
	#define STR0006 "Sucursal + Nombre"
	#define STR0007 "ANO/MES/DIA : "
	#define STR0008 "ITEM"
	#define STR0009 "TIPO"
	#define STR0010 "NUMERO"
	#define STR0011 "NOMBRE PATERNO"
	#define STR0012 "NOMBRE MATERNO"
	#define STR0013 "NOMBRES"
	#define STR0014 "I/R/L/S"
	#define STR0015 "FECHA"
	#define STR0016 "DIAS"
	#define STR0017 "INGRESO BASE"
	#define STR0018 "TOTAL GANADO"
	#define STR0019 "SOLIDARIO SIN"
	#define STR0020 "SOLIDARIO MENOS"
	#define STR0021 "BS"
	#define STR0022 "CONSIDERAR TOP"
	#define STR0023 "FORMULARIO DE PAGO DE CONTRIBUCIONES"
	#define STR0024 "Formulario de  Contribucion  Fondo Solidario AFP PrevisiOn"
	#define STR0025 "FONDO SOLIDARIO"
	#define STR0026 "Formulario de Contribucion Fondo Solidario AFP"
	#define STR0027 "MODIFICACION"
	#define STR0028 "COTIZ."
	#define STR0029 "TOTAL GENERAL : "
	#define STR0030 "Antes de continuar, es necesario ejecutar la actualizacion '171' disponible para el modulo SIGAGPE en el compatibilizador RHUPDMOD."
	#define STR0031 "Atencion"
	#define STR0032 "60 SMN"
	#define STR0033 "Antes de continuar, es necesario ejecutar la actualizacion '229' disponible para el modulo SIGAGPE en el compatibilizador RHUPDMOD."
	#define STR0034 "No"
	#define STR0035 "TIPO"
	#define STR0036 "EXTENSIÓN"
	#define STR0037 "NUA/CUA"
	#define STR0038 "1er. APELLIDO (PATERNO)"
	#define STR0039 "2do. APELLIDO (MATERNO)"
	#define STR0040 "APELLIDO CASADA"
	#define STR0041 "PRIMER NOMBRE"
	#define STR0042 "SEGUNDO NOMBRE"
	#define STR0043 "DEPARTAMENTO"
	#define STR0044 "NOVEDAD I/R/L/S"
	#define STR0045 "FECH-NOVEDAD"
	#define STR0046 "DIAS COTIZADOS"
	#define STR0047 "TOTAL GANADO SOLIDARIO (SIN CONSIDERAR TOPE DE 60 SALARIOS MÍNIMOS NACIONALES"
	#define STR0048 "TOTAL GANADO SOLIDARIO MENOS BS. 13,000 (SI LA DIFERENCIA ES POSITIVA"
	#define STR0049 "TOTAL GANADO SOLIDARIO MENOS BS. 25,000 (SI LA DIFERENCIA ES POSITIVA)"
	#define STR0050 "TOTAL GANADO SOLIDARIO MENOS BS. 35,000 (SI LA DIFERENCIA ES POSITIVA)"
#else
	#ifdef ENGLISH
		#define STR0001 "FORM OF SOLIDARIO FUND APPORTIONMENT"
		#define STR0002 "It will be printed according to the parameters requested by the user."
		#define STR0003 "Note: You must print a monthly Form for each branch."
		#define STR0004 "Branch + Registration"
		#define STR0005 "Branch +Cost C."
		#define STR0006 "Branch + Name"
		#define STR0007 "YEAR/MONTH/DAY : "
		#define STR0008 "ITEM"
		#define STR0009 "TYPE"
		#define STR0010 "NUMBER"
		#define STR0011 "PATERNAL NAME"
		#define STR0012 "MATERNAL NAME"
		#define STR0013 "NAMES"
		#define STR0014 "I/R/L/S"
		#define STR0015 "DATE"
		#define STR0016 "DAYS"
		#define STR0017 "BASE REVENUE"
		#define STR0018 "TOTAL EARNED"
		#define STR0019 "NO SOLIDARIO"
		#define STR0020 "LESS SOLIDARIO"
		#define STR0021 "BS"
		#define STR0022 "CONSIDER TOP"
		#define STR0023 "CONTRIBUTION PAYMENT FORM"
		#define STR0024 "Contribution Form - Bolivia AFP Prevision Solidario Fund"
		#define STR0025 "SOLIDARIO FUND"
		#define STR0026 "Contribution Form - AFP Solidario Fund"
		#define STR0027 "CHANGE"
		#define STR0028 "QUOT."
		#define STR0029 "GRAND TOTAL : "
		#define STR0030 "Before continuing, run the update 171 available for SIGAGPE module in the compatibility program RHUPDMOD."
		#define STR0031 "Attention!"
		#define STR0032 "60 SMN"
		#define STR0033 "Before continuing, run the update 229 available for SIGAGPE module in the compatibility program RHUPDMOD."
		#define STR0034 "No"
		#define STR0035 "TYPE"
		#define STR0036 "EXTENSION"
		#define STR0037 "NUA/CUA"
		#define STR0038 "1ST SURNAME (PATERNAL)"
		#define STR0039 "2ND LAST NAME (MATERNAL)"
		#define STR0040 "LAST NAME MARRIED"
		#define STR0041 "FIRST NAME"
		#define STR0042 "MIDDLE NAME"
		#define STR0043 "DEPARTMENT"
		#define STR0044 "NOVELTY I/R/L/S"
		#define STR0045 "NOVELTY DATE dd/mm/yyyy"
		#define STR0046 "DAYS QUOTED"
		#define STR0047 "TOTAL SOLIDARIO EARNED (NOT CONSIDERED THE TOP 60 NATIONAL MINIMUM WAGES)"
		#define STR0048 "TOTAL SOLIDARIO EARNED LESS BS 1300 (IF THE DIFFERENCE IS POSITIVE)"
		#define STR0049 "TOTAL SOLIDARIO EARNED LESS BS 25000 (IF THE DIFFERENCE IS POSITIVE)"
		#define STR0050 "TOTAL SOLIDARIO EARNED LESS BS 35000 (IF THE DIFFERENCE IS POSITIVE)"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "FORMULÁRIO DE APORTE DE FUNDO SOLIDÁRIO", "FORMULÁRIO DE APORTE DE FUNDO SOLIDARIO" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Será impresso de acordo com os parâmetros solicitados pelo utilizador.", "Será impresso de acordo com os parâmetros solicitados pelo usuário." )
		#define STR0003 "Obs.: Deve-se imprimir um Formulário mensal para cada filial."
		#define STR0004 "Filial + Matrícula"
		#define STR0005 "Filial + C. Custo"
		#define STR0006 "Filial + Nome"
		#define STR0007 "ANO/MÊS/DIA : "
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "ITEM", "ÍTEM" )
		#define STR0009 "TIPO"
		#define STR0010 "NÚMERO"
		#define STR0011 "NOME PATERNO"
		#define STR0012 "NOME MATERNO"
		#define STR0013 "NOMES"
		#define STR0014 "I/R/L/S"
		#define STR0015 "DATA"
		#define STR0016 "DIAS"
		#define STR0017 "RECEITA BASE"
		#define STR0018 "TOTAL GANHO"
		#define STR0019 "SOLIDARIO SEM"
		#define STR0020 "SOLIDARIO MENOS"
		#define STR0021 "BS"
		#define STR0022 "CONSIDERAR TOP"
		#define STR0023 "FORMULARIO DE PAGAMENTO DE CONTRIBUIÇÕES"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Formulário de  Contribuição Fundo Solidário AFP´s Previsión", "Formulário de  Contribuição  Fundo Solidario AFP´s Previsión" )
		#define STR0025 "FUNDO SOLIDARIO"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Formulário de Contribuição Fundo Solidário AFP´s", "Formulário de Contribuição Fundo Solidario AFP´s" )
		#define STR0027 "ALTERAÇÃO"
		#define STR0028 "COTIZ."
		#define STR0029 "TOTAL GERAL : "
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Antes de prosseguir, é necessário executar a actualização '171' disponível para o módulo SIGAGPE no compatibilizador RHUPDMOD.", "Antes de prosseguir, é necessário executar a atualização '171' disponível para o módulo SIGAGPE no compatibilizador RHUPDMOD." )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Atenção!", "Atencao!" )
		#define STR0032 "60 SMN"
		#define STR0033 "Antes de continuar, é necessário executar a atualização '229' disponível para o módulo SIGAGPE no compatibilizador RHUPDMOD."
		#define STR0034 "No"
		#define STR0035 "TIPO"
		#define STR0036 "EXTENSÃO"
		#define STR0037 "NUA/CUA"
		#define STR0038 "1º SOBRENOME (PATERNO)"
		#define STR0039 "2º. ÚLTIMO (MATERNO)"
		#define STR0040 "ÚLTIMO NOME CASADO"
		#define STR0041 "PRIMEIRO NOME"
		#define STR0042 "NOME DO MEIO"
		#define STR0043 "DEPARTAMENTO"
		#define STR0044 "NOVIDADE I/R/L/S"
		#define STR0045 "DATA-NOVIDADE dd/mm/aaaa"
		#define STR0046 "DIAS COTIZADOS"
		#define STR0047 "TOTAL SOLIDÁRIO GANHADO (SEM CONSIDERAR O TOP DOS 60 SALÁRIOS MÍNIMOS NACIONAIS)"
		#define STR0048 "A SOLIDARIEDADE TOTAL GANHOU MENOS BS. 13000 (SE A DIFERENÇA É POSITIVA)"
		#define STR0049 "A SOLIDARIEDADE GANHOU TOTAL MENOS BS. 25000 (SE A DIFERENÇA É POSITIVA)"
		#define STR0050 "TOTAL GANHOU SOLIDARIEDADE MENOS BS. 35000 (SE A DIFERENÇA É POSITIVA)"
	#endif
#endif
