#ifdef SPANISH
	#define STR0001 "кхлхр йнмбепрюжхх дмеи нросяйю б бшокюрс"
	#define STR0002 "пюявер днокюрш й нросяйс"
	#define STR0003 "пЕЦСКЪПМШИ ПЮЯВЕР"
	#define STR0004 "юБЮМЯНБШИ ПЮЯВЕР"
	#define STR0005 "пЮЯВЕР ОПХ СБНКЭМЕМХХ"
	#define STR0006 "пЮЯВЕР НРОСЯЙНБ"
	#define STR0007 "опнбепйю рпеаселшу бхднб нокюр"
	#define STR0008 "опнжемр > 0"
	#define STR0009 "опнбепйю дюрш бшокюрш юбюмяю"
	#define STR0010 "мнплхпнбюммши пюявер юбюмяю"
	#define STR0011 "яанпйю аюгш пюяверю юбюмяю"
	#define STR0012 "пецхярпюжхъ═ юбюмянб"
	#define STR0013 "бшвхякемхе аюгш мдтк я юбюмяю"
	#define STR0014 "яанп дно. дюммшу пюяверю юбюмяю"
	#define STR0015 "пюявер мдтк я юбюмяю"
	#define STR0016 "гюохяэ мдтк я юбюмяю"
	#define STR0017 "гюохяэ аюгш пюяверю мдтк я юбюмяю"
	#define STR0018 "гюохяэ мюкнцнбшу бшвернб я юбюмяю"
	#define STR0019 "гюохяэ ясллш юбюмяю"
	#define STR0020 "ондцнрнбйю хрнцнбшу гмювемхи юбюмяю"
	#define STR0021 "гюцпсгйю ярюбнй ярпюунбшу бгмнянб"
	#define STR0022 "гюцпсгйю свремнцн нрпюанрюммнцн бпелемх"
	#define STR0023 "гюцпсгйю дно дюммшу пюяверю═"
	#define STR0024 "пюявер нрпюанрюммшу дмеи"
	#define STR0025 "пюявер ясллш гю нрпюанрюммше дмх"
	#define STR0026 "яанп бхднб нокюр дкъ пюяверю сбнкэмемхъ"
	#define STR0027 "пюявер япедмху"
	#define STR0028 "пюявер нрпюа.═ дмеи дкъ опеондюбюрекеи"
	#define STR0029 "гюохяэ нрпюа.═ дмеи дкъ опеондюбюрекеи"
	#define STR0030 "пюявер дно нйкюднб═ опх сбнкэмемхх"
	#define STR0031 "пюявер йнлоемяюжхи опх сбнкэмемхх"
	#define STR0032 "гюохяэ йнлоемяюжхи опх сбнкэмемхх"
	#define STR0033 "пюявер опюбю мю нросяймше опх сбнкэмемхх"
	#define STR0034 "пюявер он мехяонкэгнбюммшл нросяйюл"
	#define STR0035 "яанп сбеднлкемхъ н янйпюыемхх ьрюрю"
	#define STR0036 "пюявер днокюр мехяонкэгнбюммшу нросяйнб"
	#define STR0037 "пюявер нросяймшу опх сбнкэмемхх"
	#define STR0038 "пюявер 13и гюпокюрш опх сбнкэмемхх"
	#define STR0039 "пюявер бшокюр опх янйпюыемхх ьрюрю"
	#define STR0040 "опнбепйю сякнбхи япнвмнцн йнмрпюйрю═"
	#define STR0041 "пюявер бшокюр он сякнбхъл йнмрпюйрю"
	#define STR0042 "опнбепйю сякнбхи аеяяпнвмнцн йнмрпюйрю═"
	#define STR0043 "пюявер дняпнвмнцн пюярнпфемхъ йнмрпюйрю"
	#define STR0044 "пюявер дняпнвмнцн пюярнпфемхъ йнмрпюйрю2"
	#define STR0045 "яанп бшокювеммшу дн сбнкэмемхъ яслл"
	#define STR0046 "пюявер он люрепхмярбс опх сбнкэмемхх"
	#define STR0047 "пюявер бшокюр он ножхнмюл опх сбнкэмемхх"
	#define STR0048 "пюявер юкхлемрнб опх сбнкэмемхх"
	#define STR0049 "пюявер юкхлемрнб опх сбнкэмемхх - 13ъ го"
	#define STR0050 "пюявер бгмнянб отп опх сбнкэмемхх"
	#define STR0051 "пюявер дно бгмнянб отп опх сбнкэмемхх"
	#define STR0052 "пюявер янжхюкэмшу бшокюр опх сбнкэмемхх"
	#define STR0053 "сбнкэмемхе дн дюрш бшокюрш гюпокюрш"
	#define STR0054 "сбнкэмемхе дн дюрш бшокюрш гюпокюрш 2"
	#define STR0055 "пюявер вхярни ясллш бшокюр он сбнкэмемхч"
	#define STR0056 "пюявер аюкюмяю сдепфюмхи/мювхякемхи"
	#define STR0057 "цемепюжхъ аюкюмяю сдепфюмхи/мювхякемхи"
	#define STR0058 "пюявер ясллш й бшокюре опх сбнкэмемхх"
	#define STR0059 "пюявер днокюр опх сбнкэмемхх"
	#define STR0060 "пюявер сдепфюмхи опх сбнкэмемхх"
	#define STR0061 "гюцпсгйю дюммшу пюяверю нросяйю"
	#define STR0062 "пюявер нросяймшу япедмху"
	#define STR0063 "пюявер днонкмхрекэрмнцн нросяйю он бнся"
	#define STR0064 "пюявер дно. нросяймшу он бнся"
	#define STR0065 "пюявер ярюфеи опх пюявере нросяйю"
	#define STR0066 "яанп дюммшу он япедмхл дкъ нросяймшу"
	#define STR0067 "гюохяэ ясллш нросяймшу"
	#define STR0068 "гюохяэ дюммшу он япедмхл дкъ нросяймшу"
	#define STR0069 "гюохяэ аюкюмяю нросяймшу дмеи"
	#define STR0070 "опнбепйю опнтя. мюдаюбнй й нросяймшл"
	#define STR0071 "пюявер нокювхбюелшу бшундмшу нросяйю"
	#define STR0072 "гюохяэ нокювхбюелшу бшундмшу нросяйю"
	#define STR0073 "йнмбепрюжхъ дмеи нросяйю б бшокюрс"
	#define STR0074 "ясллхпнбюмхе нросяймшу бшокюр"
	#define STR0075 "опнбепйю бшокюр йнккейрхбмнцн нросяйю"
	#define STR0076 "пюявер опняпнвеммшу нросяйнб"
	#define STR0077 "гюохяэ бшокюр он опняпнвеммнлс нросяйс"
	#define STR0078 "пюявер дно. опняпнвеммшу нросяйнб"
	#define STR0079 "пюявер бшокюрш 13и го б нросяймше"
	#define STR0080 "опнбепйю бшокюрш 13и го б нросяймше"
	#define STR0081 "опнбепйю опюб онксвемхъ нросяйю"
	#define STR0082 "пюявер 13и гюпокюрш дкъ нросяйю"
	#define STR0083 "гюохяэ 13и гюпокюрш дкъ нросяйю"
	#define STR0084 "опнбепйю цпютхйю бшундмшу дмеи"
	#define STR0085 "пюявер яслл тяя я нросяймшу"
	#define STR0086 "нопедекемхе цпютхйю бшундмшу дмеи"
	#define STR0087 "яанп ясллш мювхякемхи дкъ нросяймшу"
	#define STR0088 "яанп ясллш сдепфюмхи я нросяймшу"
	#define STR0089 "ондцнрнбйю хрнцнбшу гмювемхи нросяймшу"
	#define STR0090 "гюцпсгйю дюммшу оепхндю"
	#define STR0091 "гюцпсгйю рюакхж дкъ пюяверю"
	#define STR0092 "гюцпсгйю дюммшу дкъ пюяверю"
	#define STR0093 "гюцпсгйю дюммшу он ярюрсяс опеашбюмхъ"
	#define STR0094 "опнбепйю нрпюанрюммшу вюянб"
	#define STR0095 "яанпйю ефелеяъвмни гюпокюрш"
	#define STR0096 "яанпйю онвюянбни гюпокюрш"
	#define STR0097 "яанпйю ефедмебмни гюпокюрш"
	#define STR0098 "яанпйю аюгнбни гюпокюрш"
	#define STR0099 "пюявер бпелеммнцн ямхфемхъ го═"
	#define STR0100 "пюявер бпелеммнцн сбекхвемхъ го═"
	#define STR0101 "гюцпсгйю пюмее пюявхрюммшу гмювемхи"
	#define STR0102 "пюявер йнщттхжхемрю хмдейяюжхх го"
	#define STR0103 "пюявер хмдейяюжхх гюпокюрш"
	#define STR0104 "пюявер асдсыху бекхвхм"
	#define STR0105 "пюанвхе дмх"
	#define STR0106 "дмх нрясрярбхъ"
	#define STR0107 "пюявер тхйяхпнбюммшу бшокюр/сдепфюмхи"
	#define STR0108 "пюявер бшундмшу дмеи"
	#define STR0109 "пюявер гюпокюрш"
	#define STR0110 "опнбепйю ярюрсяю янрпсдмхйю"
	#define STR0111 "цемепюжхъ рюпхтнб"
	#define STR0112 "пюявер бшундмшу дкъ рюпхтмни нокюрш"
	#define STR0113 "хмхжхюкхгюжхъ пюяверю дкъ опеонднбюрекеи"
	#define STR0114 "аюгнбюъ ярюбйю дкъ опеондюбюрекеи"
	#define STR0115 "гюохяэ бшундмшу дкъ опеондюбюрекеи"
	#define STR0116 "пюявер вюянб пюанрш опеондюбюрекъ"
	#define STR0117 "гюохяэ вюянб пюанрш опеондюбюрекъ"
	#define STR0118 "йнлонмнбйю гюпокюрш опеондюбюрекъ"
	#define STR0119 "опнонпжхнмюкэмши пюявер го опеондюбюрекъ"
	#define STR0120 "оепелеммши опнонпжхнмюкэмши пюявер"
	#define STR0121 "япнвмши йнмрпюйр - 13ъ гюпокюрю"
	#define STR0122 "япнвмши йнмрпюйр - нросяй"
	#define STR0123 "бйкчвемхе опнонпжхнмюкэмнцн пюяверю"
	#define STR0124 "хмхжхюкхгюжхъ дюммшу он рейсыелс ярюфс"
	#define STR0125 "пюявер бшокюрш гю оепбши цнд"
	#define STR0126 "пюявер бшокюрш гю брнпни цнд"
	#define STR0127 "пюявер бшокюрш гю рперхи цнд"
	#define STR0128 "пюявер бшокюрш гю вербепрши цнд"
	#define STR0129 "пюявер бшокюрш гю оърши цнд"
	#define STR0130 "пюявер леяъвмни бшкюрш гю ярюф"
	#define STR0131 "пюявер леяъвмни бшкюрш гю люрепхмярбн"
	#define STR0132 "нрйкчвемхе═ опнонпжхнмюкэмнцн пюяверю"
	#define STR0133 "пюявер мюдаюбйх гю кнъкэмнярэ"
	#define STR0134 "гюохяэ мюдаюбйх гю кнъкэмнярэ"
	#define STR0135 "гюохяэ мюдаюбнй гю люрепхмярбн"
	#define STR0136 "пюявер цюпюмрхпнбюмшу бшокюр"
	#define STR0137 "пюявер мюдаюбйх гю кнъкэмнярэ"
	#define STR0138 "гюохяэ мюдаюбйх гю кнъкэмнярэ"
	#define STR0139 "гюохяэ пекнйюжхнммшу бшокюр дкъ ахп"
	#define STR0140 "цемепюжхъ дно ефелеяъвмшу бшокюр"
	#define STR0141 "пюявер бшокюрш бнся"
	#define STR0142 "гюохяэ бшокюрш бнся"
	#define STR0143 "гюохяэ бшокюр бнся дкъ дейп. нросяйнб"
	#define STR0144 "цемепюжхъ ефелеяъвмшу мювхякемхи гю бнся"
	#define STR0145 "аюгю пюяверю дкъ анкэмхвмшу"
	#define STR0146 "пюявер лхм ясллш дкъ анкэмхвмшу"
	#define STR0147 "гюохяэ лхм ясллш дкъ анкэмхвмшу"
	#define STR0148 "пюявер япедмху дкъ анкэмхвмшу"
	#define STR0149 "гюохяэ япедмху дкъ анкэмхвмшу"
	#define STR0150 "пюявер люйяхлюкэмни ясллш он анкэмхвмнлс"
	#define STR0151 "гюохяэ люйяхлюкэмни ясллш он анкэмхвмнлс"
	#define STR0152 "гюохяэ ясллш анкэмхвмнцн он люрепхмярбс"
	#define STR0153 "цемепюжхъ бшокюр он анкэмхвмшл"
	#define STR0154 "опнвхе оепепюанрйх б бшундмше"
	#define STR0155 "пюявер опнбнднй асдсыху оепхнднб"
	#define STR0156 "пюявер цюпюмрхпнбюмни го йнлхяяхнмепнб"
	#define STR0157 "гюохяэ пюяверю он бхдюл нокюр"
	#define STR0158 "гюохяэ йнппеяондхпсчыху бхднб нокюр"
	#define STR0159 "мнплхпнбюмши свер"
	#define STR0160 "пюявер пюгкхвмшу нросяйнб"
	#define STR0161 "йкюяяхтхйюжхъ нокювхбюелшу нрясярбхи"
	#define STR0162 "пюявер ярпсйрспмнцн япедмецн"
	#define STR0163 "пюявер вюянб пюанрш б бшундмше"
	#define STR0164 "пюявер днокюрш гю ярюф 1 цнд"
	#define STR0165 "пюявер днокюрш гю ярюф 2 цндю"
	#define STR0166 "пюявер днокюрш гю ярюф 3 цндю"
	#define STR0167 "пюявер днокюрш гю ярюф 4 цндю"
	#define STR0168 "пюявер днокюрш гю ярюф 5 кер"
	#define STR0169 "цемепюыхъ яоежхюкэмшу бшокюр"
	#define STR0170 "пюявер леяъвмни бшкюрш гю люрепхмярбн"
	#define STR0171 "пюявер анкэмхвмшу"
	#define STR0172 "гюохяэ анкэмхвмшу"
	#define STR0173 "гюохяэ дейпермшу анкэмхвмшу"
	#define STR0174 "цемепюжхъ анкэмхвмшу гю оепхнд"
	#define STR0175 "пюявер бнся"
	#define STR0176 "гюохяэ бнся"
	#define STR0177 "гюохяэ бнся дкъ дейпермшу нросяйнб"
	#define STR0178 "пюявер бнся гю оепхнд"
	#define STR0179 "пюявер нрясрярбхи"
	#define STR0180 "яелеимюъ гюпокюрю"
	#define STR0181 "пюявер нрвхякемхи для"
	#define STR0182 "аюгю пюяверю опнтянчгмшу бгмнянб"
	#define STR0183 "опнтянчгмши бгмня"
	#define STR0184 "ефелеяъвмне нрвхякемхе б опнтянчг"
	#define STR0185 "бгмняш б тнмд люрепхюкэмни онлных"
	#define STR0186 "бгмняш б опнтянчгмсч йнмтедепюжхч"
	#define STR0187 "пюявер люрепхюкэмни онлных"
	#define STR0188 "пюявер тяя"
	#define STR0189 "цемепюжхъ дейпермшу бшокюр"
	#define STR0190 "пюявер опнт. бгмнянб дкъ нрясрярбхи"
	#define STR0191 "пюявер тяя - 13ъ гюпокюрю"
	#define STR0192 "пюявер юкхлемрнб"
	#define STR0193 "пюявер мдтк"
	#define STR0194 "пюявер мдтк - нросяйю"
	#define STR0195 "пюявер мдтк - 13 гюпокюрю"
	#define STR0196 "пюявер бгмнянб отп"
	#define STR0197 "пюявер бгмнянб отп - 13ъ═ гюпокюрю"
	#define STR0198 "пюявер нйпсцкеммшу яслл й бшокюре"
	#define STR0199 "пюявер тяя - днонкмхрекэмши пюявер"
	#define STR0200 "пюяопедекемхе он жемрпюл гюрпюр"
	#define STR0201 "гюохяэ аюгнбни гюпокюрш гю оепхнд"
	#define STR0202 "днонкмхрекэмши пюявер"
	#define STR0203 "пюявер янблеярхрекэярбю"
	#define STR0204 "опнлефсрнвмше япедмхе"
	#define STR0205 "яебепмюъ мюдаюбйю"
	#define STR0206 "пецхнмюкэмши йнщттхжхемр"
	#define STR0207 "гюохяэ пегскэрюрнб пюяверю"
	#define STR0208 "кэцнрш дкъ лнкндшу яоежхюкхярнб"
	#define STR0209 "опнялнрп яннаыемхи на ньхайюу б пюявере"
#else
	#ifdef ENGLISH
		#define STR0001 "VACATION DAYS CONVERSION LIMIT"
		#define STR0002 "VACATION SUPPLEMENT CALCULATION"
		#define STR0003 "Regular settlement"
		#define STR0004 "Advance settlement"
		#define STR0005 "Settlement upon dismissal"
		#define STR0006 "Vacation calculation"
		#define STR0007 "CHECKING THE REQUIRED TYPES OF PAYMENT"
		#define STR0008 "опнжемр > 0"
		#define STR0009 "CHECKING THE ADVANCE PAYMENT DATE"
		#define STR0010 "NORMAL ADVANCE CALCULATION"
		#define STR0011 "ASSEMBLING THE ADVANCE CALCULATION BASE"
		#define STR0012 "ADVANCE REGISTRATION"
		#define STR0013 "CALCULATING THE PIT BASE WITH ADVANCE"
		#define STR0014 "COLLECTION OF ADDITIONAL DATA FOR CALCULATION OF ADVANCE"
		#define STR0015 "PIT CALCULATION WITH ADVANCE"
		#define STR0016 "ENTRY OF PERSONAL INITIATION WITH ADVANCE"
		#define STR0017 "REGISTRATION OF THE BASE FOR CALCULATING PERSONAL INITIATIVE DOMESTIC IN ADVANCE"
		#define STR0018 "RECORDING TAX DEDUCTIONS FROM ADVAN"
		#define STR0019 "RECORD ADVANCE AMOUNT"
		#define STR0020 "PREPARATION OF TOTAL ADVANCE VALUES"
		#define STR0021 "DOWNLOAD INSURANCE PREMIUM RATES"
		#define STR0022 "LOADING THE ACCOUNTED HOURS"
		#define STR0023 "LOADING ADDITIONAL CALCULATION DATA"
		#define STR0024 "CALCULATION OF WORKING DAYS"
		#define STR0025 "CALCULATION OF AMOUNT FOR WORKED DAYS"
		#define STR0026 "COLLECTING TYPES OF PAYMENTS FOR CALCULATION OF DISMISSAL"
		#define STR0027 "CALCULATE AVERAGES"
		#define STR0028 "CALCULATING EXTRACTED DAYS FOR TEACHERS"
		#define STR0029 "RECORDING WORK DAYS FOR TEACHERS"
		#define STR0030 "CALCULATION OF ADDITIONAL SALARY WHEN DISMISSED"
		#define STR0031 "CALCULATION OF COMPENSATIONS WHEN DISMISSING"
		#define STR0032 "RECORDING COMPENSATIONS ON FIRING"
		#define STR0033 "CALCULATION OF VACATION ELIGIBILITY ON DISCHARGE"
		#define STR0034 "CALCULATION ON UNUSED HOLIDAYS"
		#define STR0035 "COLLECTION OF STAFF NOTICE"
		#define STR0036 "CALCULATION OF UNUSED VACATION SUPPLEMENTS"
		#define STR0037 "VACATION CALCULATION ON STOPPING"
		#define STR0038 "CALCULATION OF THE 13TH SALARY WHEN DISCONTINUED"
		#define STR0039 "REDUCED STAFF PAYMENTS CALCULATION"
		#define STR0040 "CHECKING THE TERMS OF URGENT CONTRACT"
		#define STR0041 "CALCULATION OF PAYMENTS UNDER CONTRACT TERMS"
		#define STR0042 "CHECKING THE TERMS OF THE UNLIMITED CONTRACT"
		#define STR0043 "CALCULATION OF EARLY TERMINATION OF THE CONTRACT"
		#define STR0044 "CALCULATION OF EARLY TERMINATION OF A CONTRACT2"
		#define STR0045 "COLLECTION OF THE AMOUNTS PAID BEFORE THE EXECUTION"
		#define STR0046 "MOTHERALITY CALCULATION ON Dismissal"
		#define STR0047 "CALCULATION OF PAYMENTS BY OPTIONS WHEN DISMISSING"
		#define STR0048 "CALCULATION OF ALIMENTS WHEN FIRING"
		#define STR0049 "CALCULATION OF ALIMENTS WHEN FIRING - 13th salary"
		#define STR0050 "CALCULATION OF PFR CONTRIBUTIONS WHEN DISCONTINUED"
		#define STR0051 "CALCULATION OF ADDITIONAL PFR CONTRIBUTIONS WHEN DISCONTINUED"
		#define STR0052 "CALCULATION OF SOCIAL PAYMENTS ON DISCHARGE"
		#define STR0053 "RESCUE BEFORE THE DATE OF PAYMENT"
		#define STR0054 "DIRECTION BEFORE THE DATE OF SALARY PAYMENT 2"
		#define STR0055 "CALCULATION OF THE NET AMOUNT OF Dismissal payments"
		#define STR0056 "RETENTION / ACCOUNT BALANCE CALCULATION"
		#define STR0057 "RETENTION / ACCOUNT BALANCE GENERATION"
		#define STR0058 "CALCULATION OF THE AMOUNT TO BE PAYED AT THE DISCHARGE"
		#define STR0059 "CALCULATION OF SUPPLEMENTS FOR DISCHARGE"
		#define STR0060 "CALCULATION OF RETENTION RESPONSE"
		#define STR0061 "DOWNLOAD HOLIDAY CALCULATION DATA"
		#define STR0062 "VACATION AVERAGE CALCULATION"
		#define STR0063 "CALCULATION OF ADDITIONAL LEAVE VOES"
		#define STR0064 "CALCULATION OF ADDITIONAL VACATION ACCORDING TO VOS"
		#define STR0065 "CALCULATION OF EXPERIENCES WHEN CALCULATING HOLIDAYS"
		#define STR0066 "VACATION DATA COLLECTION"
		#define STR0067 "RECORD VACATION AMOUNT"
		#define STR0068 "RECORD DATA ON VACATION AVERAGE"
		#define STR0069 "RECORD VACATION BALANCE"
		#define STR0070 "CHECK PROFESSIONAL ADDITIVE TO VACATION"
		#define STR0071 "CALCULATION OF PAID WEEKEND HOLIDAYS"
		#define STR0072 "RECORD PAID WEEKEND VACATION"
		#define STR0073 "VACATION DAYS TO PAYMENT CONVERSION"
		#define STR0074 "SUMMING VACATION PAYMENTS"
		#define STR0075 "COLLECTIVE HOLIDAY PAYMENT CHECK"
		#define STR0076 "LATE HOLIDAYS CALCULATION"
		#define STR0077 "RECORD PAYMENTS ON EXTENDED HOLIDAYS"
		#define STR0078 "CALCULATING EXTRA EXTENDED HOLIDAYS"
		#define STR0079 "CALCULATION OF THE 13TH WAY PAYMENT ON VACATION"
		#define STR0080 "CHECKING THE PAYMENT OF THE 13TH WAY ON VACATION"
		#define STR0081 "HOLIDAY RIGHTS VERIFICATION"
		#define STR0082 "13TH VACATION SALARY CALCULATION"
		#define STR0083 "RECORD 13TH SALARY FOR VACATION"
		#define STR0084 "WEEKEND SCHEDULE CHECK"
		#define STR0085 "CALCULATION OF FSS AMOUNTS WITH VACATION"
		#define STR0086 "DEFINING WEEKEND SCHEDULE"
		#define STR0087 "COLLECTING THE AMOUNT OF ACCOUNT FOR VACATION"
		#define STR0088 "COLLECTING VACATION DECLINE"
		#define STR0089 "PREPARATION OF TOTAL HOLIDAYS"
		#define STR0090 "DOWNLOAD PERIOD DATA"
		#define STR0091 "LOADING TABLES FOR CALCULATION"
		#define STR0092 "LOADING DATA FOR CALCULATION"
		#define STR0093 "DOWNLOADING DATA ON STATUS OF RESIDENCE"
		#define STR0094 "CHECKING WORKED HOURS"
		#define STR0095 "ASSEMBLING MONTHLY SALARY"
		#define STR0096 "HOURLY WAGE ASSEMBLY"
		#define STR0097 "DAILY SALARY ASSEMBLY"
		#define STR0098 "BASIC WAGE ASSEMBLY"
		#define STR0099 "CALCULATION OF TEMPORARY WAY REDUCTION"
		#define STR0100 "CALCULATION OF TEMPORARY WAY INCREASE"
		#define STR0101 "LOADING PREVIOUS VALUES"
		#define STR0102 "CALCULATION OF THE ZP INDEXING COEFFICIENT"
		#define STR0103 "CALCULATION OF WAGE INDEX"
		#define STR0104 "CALCULATION OF FUTURE VALUES"
		#define STR0105 "WORKING DAYS"
		#define STR0106 "DAYS AWAY"
		#define STR0107 "CALCULATION OF FIXED PAYMENTS / WITHDRAWALS"
		#define STR0108 "WEEKEND CALCULATION"
		#define STR0109 "SALARY CALCULATION"
		#define STR0110 "CHECKING EMPLOYEE STATUS"
		#define STR0111 "TARIFF GENERATION"
		#define STR0112 "CALCULATION OF WEEKEND FOR TARIFF PAYMENT"
		#define STR0113 "INITIALIZATION OF CALCULATION FOR TEACHERS"
		#define STR0114 "BASIC RATE FOR TEACHERS"
		#define STR0115 "RECORDING WEEKEND FOR TEACHERS"
		#define STR0116 "TEACHER HOURS CALCULATION"
		#define STR0117 "RECORD TEACHER HOURS"
		#define STR0118 "TEACHER'S SALARY LAYOUT"
		#define STR0119 "PROPORTIONAL CALCULATION OF THE TEACHER'S WAGE"
		#define STR0120 "VARIABLE PROPORTIONAL CALCULATION"
		#define STR0121 "URGENT CONTRACT - 13TH SALARY"
		#define STR0122 "URGENT CONTRACT - VACATION"
		#define STR0123 "ENABLE PROPORTIONAL CALCULATION"
		#define STR0124 "CURRENT DATA INITIALIZATION"
		#define STR0125 "FIRST YEAR PAYMENT CALCULATION"
		#define STR0126 "SECOND YEAR PAYMENT CALCULATION"
		#define STR0127 "CALCULATION OF PAYMENT FOR THE THIRD YEAR"
		#define STR0128 "FOURTH YEAR PAYMENT CALCULATION"
		#define STR0129 "FIFTH YEAR PAYMENT CALCULATION"
		#define STR0130 "CALCULATION OF MONTHLY EXPERIENCE REMUNERATION"
		#define STR0131 "CALCULATION OF MONTHLY MATERNITY CHARGE"
		#define STR0132 "DISABLING PROPORTIONAL CALCULATION"
		#define STR0133 "CALCULATION OF LOYALTY SUPPLEMENT"
		#define STR0134 "ENTRY LOYALTY SUPPLEMENT"
		#define STR0135 "SUPPLEMENTATION FOR MOTHERNESS"
		#define STR0136 "CALCULATION OF GUARANTEED PAYMENTS"
		#define STR0137 "CALCULATION OF LOYALTY SUPPLEMENT"
		#define STR0138 "ENTRY LOYALTY SUPPLEMENT"
		#define STR0139 "RECORDING RELOCATION PAYMENTS FOR BEERS"
		#define STR0140 "GENERATION OF ADDITIONAL MONTHLY PAYMENTS"
		#define STR0141 "VOC PAYMENT CALCULATION"
		#define STR0142 "RECORDING PAYMENT OF VOC"
		#define STR0143 "RECORDING VOU PAYMENTS FOR DEC. VACATIONS"
		#define STR0144 "GENERATION OF MONTHLY ACCOUNTS FOR VOU"
		#define STR0145 "CALCULATION BASE FOR HOSPITALS"
		#define STR0146 "CALCULATION OF THE MINIMUM AMOUNT FOR HOSPITALS"
		#define STR0147 "ENTRY MINIMUM AMOUNT FOR HOSPITALS"
		#define STR0148 "CALCULATION OF MEDIUM FOR HOSPITALS"
		#define STR0149 "RECORDING MEDIUM FOR HOSPITALS"
		#define STR0150 "CALCULATION OF THE HOSPITAL MAXIMUM AMOUNT"
		#define STR0151 "RECORD HOSPITAL MAXIMUM AMOUNT"
		#define STR0152 "RECORD HOSPITAL AMOUNT BY MOTHERNESS"
		#define STR0153 "GENERATION OF HOSPITAL BENEFITS"
		#define STR0154 "OTHER WEEKEND PROCESSING"
		#define STR0155 "CALCULATION OF WIRES FOR FUTURE PERIODS"
		#define STR0156 "CALCULATION OF GUARANTEED PAYMENT OF COMMISSIONERS"
		#define STR0157 "RECORD CALCULATION BY PAYMENT TYPES"
		#define STR0158 "RECORD CORRESPONDING PAYMENT TYPES"
		#define STR0159 "NORMAL ACCOUNTING"
		#define STR0160 "CALCULATION OF VARIOUS VACATIONS"
		#define STR0161 "CLASSIFICATION OF PAIDABILITY"
		#define STR0162 "STRUCTURAL AVERAGE CALCULATION"
		#define STR0163 "WEEKEND HOURS CALCULATION"
		#define STR0164 "CALCULATION OF SUPPLEMENT FOR 1 YEAR EXPERIENCE"
		#define STR0165 "2 YEAR EXPERIENCE CALCULATION"
		#define STR0166 "3 YEAR EXPERIENCE CALCULATION"
		#define STR0167 "4 YEAR EXPERIENCE CALCULATION"
		#define STR0168 "CALCULATION OF EXTRA PAYMENT FOR 5 YEARS EXPERIENCE"
		#define STR0169 "GENERATING SPECIAL PAYMENTS"
		#define STR0170 "CALCULATION OF MONTHLY MATERNITY CHARGE"
		#define STR0171 "CALCULATION OF HOSPITALS"
		#define STR0172 "RECORD HOSPITAL"
		#define STR0173 "RECORD OF DOCTRINE HOSPITALS"
		#define STR0174 "GENERATION OF HOSPITALS PER PERIOD"
		#define STR0175 "VOC CALCULATION"
		#define STR0176 "RECORD VOUS"
		#define STR0177 "VOUS RECORDING FOR DECRETARY VACATIONS"
		#define STR0178 "VOU CALCULATION FOR A PERIOD"
		#define STR0179 "CALCULATE MISSING"
		#define STR0180 "FAMILY SALARY"
		#define STR0181 "VHI CALCULATION"
		#define STR0182 "BASE FOR CALCULATION OF TRADE UNION CONTRIBUTIONS"
		#define STR0183 "TRADE UNION FEE"
		#define STR0184 "MONTHLY DISTRIBUTION TO THE TRADE UNION"
		#define STR0185 "CONTRIBUTIONS TO THE MATERIAL ASSISTANCE FUND"
		#define STR0186 "UNION CONFEDERATION CONTRIBUTIONS"
		#define STR0187 "CALCULATION OF MATERIAL AID"
		#define STR0188 "FSS CALCULATION"
		#define STR0189 "GENERATION OF DECRETARY PAYMENTS"
		#define STR0190 "CALCULATION OF PROF. FEES FOR ABSENCE"
		#define STR0191 "FSS CALCULATION - 13TH SALARY"
		#define STR0192 "CALCULATION OF ALIMONIES"
		#define STR0193 "PIT CALCULATION"
		#define STR0194 "PIT CALCULATION - VACATION"
		#define STR0195 "PIT CALCULATION - 13 WAGE"
		#define STR0196 "CALCULATION OF PFR CONTRIBUTIONS"
		#define STR0197 "CALCULATION OF PFR CONTRIBUTIONS - 13TH SALARY"
		#define STR0198 "CALCULATION OF ROUND AMOUNTS TO PAYOUT"
		#define STR0199 "FSS CALCULATION - ADDITIONAL CALCULATION"
		#define STR0200 "DISTRIBUTION BY COST CENTER"
		#define STR0201 "RECORD BASIC WAGE FOR A PERIOD"
		#define STR0202 "ADDITIONAL CALCULATION"
		#define STR0203 "JOINT CALCULATION"
		#define STR0204 "INTERMEDIATE MEDIUM"
		#define STR0205 "NORTHERN ADDITIVE"
		#define STR0206 "REGIONAL RATIO"
		#define STR0207 "RECORDING CALCULATION RESULTS"
		#define STR0208 "BENEFITS FOR YOUNG SPECIALISTS"
		#define STR0209 "VIEWING CALCULATION ERRORS"
	#else
		#define STR0001 "кхлхр йнмбепрюжхх дмеи нросяйю б бшокюрс"
		#define STR0002 "пюявер днокюрш й нросяйс"
		#define STR0003 "пЕЦСКЪПМШИ ПЮЯВЕР"
		#define STR0004 "юБЮМЯНБШИ ПЮЯВЕР"
		#define STR0005 "пЮЯВЕР ОПХ СБНКЭМЕМХХ"
		#define STR0006 "пЮЯВЕР НРОСЯЙНБ"
		#define STR0007 "опнбепйю рпеаселшу бхднб нокюр"
		#define STR0008 "опнжемр > 0"
		#define STR0009 "опнбепйю дюрш бшокюрш юбюмяю"
		#define STR0010 "мнплхпнбюммши пюявер юбюмяю"
		#define STR0011 "яанпйю аюгш пюяверю юбюмяю"
		#define STR0012 "пецхярпюжхъ═ юбюмянб"
		#define STR0013 "бшвхякемхе аюгш мдтк я юбюмяю"
		#define STR0014 "яанп дно. дюммшу пюяверю юбюмяю"
		#define STR0015 "пюявер мдтк я юбюмяю"
		#define STR0016 "гюохяэ мдтк я юбюмяю"
		#define STR0017 "гюохяэ аюгш пюяверю мдтк я юбюмяю"
		#define STR0018 "гюохяэ мюкнцнбшу бшвернб я юбюмяю"
		#define STR0019 "гюохяэ ясллш юбюмяю"
		#define STR0020 "ондцнрнбйю хрнцнбшу гмювемхи юбюмяю"
		#define STR0021 "гюцпсгйю ярюбнй ярпюунбшу бгмнянб"
		#define STR0022 "гюцпсгйю свремнцн нрпюанрюммнцн бпелемх"
		#define STR0023 "гюцпсгйю дно дюммшу пюяверю═"
		#define STR0024 "пюявер нрпюанрюммшу дмеи"
		#define STR0025 "пюявер ясллш гю нрпюанрюммше дмх"
		#define STR0026 "яанп бхднб нокюр дкъ пюяверю сбнкэмемхъ"
		#define STR0027 "пюявер япедмху"
		#define STR0028 "пюявер нрпюа.═ дмеи дкъ опеондюбюрекеи"
		#define STR0029 "гюохяэ нрпюа.═ дмеи дкъ опеондюбюрекеи"
		#define STR0030 "пюявер дно нйкюднб═ опх сбнкэмемхх"
		#define STR0031 "пюявер йнлоемяюжхи опх сбнкэмемхх"
		#define STR0032 "гюохяэ йнлоемяюжхи опх сбнкэмемхх"
		#define STR0033 "пюявер опюбю мю нросяймше опх сбнкэмемхх"
		#define STR0034 "пюявер он мехяонкэгнбюммшл нросяйюл"
		#define STR0035 "яанп сбеднлкемхъ н янйпюыемхх ьрюрю"
		#define STR0036 "пюявер днокюр мехяонкэгнбюммшу нросяйнб"
		#define STR0037 "пюявер нросяймшу опх сбнкэмемхх"
		#define STR0038 "пюявер 13и гюпокюрш опх сбнкэмемхх"
		#define STR0039 "пюявер бшокюр опх янйпюыемхх ьрюрю"
		#define STR0040 "опнбепйю сякнбхи япнвмнцн йнмрпюйрю═"
		#define STR0041 "пюявер бшокюр он сякнбхъл йнмрпюйрю"
		#define STR0042 "опнбепйю сякнбхи аеяяпнвмнцн йнмрпюйрю═"
		#define STR0043 "пюявер дняпнвмнцн пюярнпфемхъ йнмрпюйрю"
		#define STR0044 "пюявер дняпнвмнцн пюярнпфемхъ йнмрпюйрю2"
		#define STR0045 "яанп бшокювеммшу дн сбнкэмемхъ яслл"
		#define STR0046 "пюявер он люрепхмярбс опх сбнкэмемхх"
		#define STR0047 "пюявер бшокюр он ножхнмюл опх сбнкэмемхх"
		#define STR0048 "пюявер юкхлемрнб опх сбнкэмемхх"
		#define STR0049 "пюявер юкхлемрнб опх сбнкэмемхх - 13ъ го"
		#define STR0050 "пюявер бгмнянб отп опх сбнкэмемхх"
		#define STR0051 "пюявер дно бгмнянб отп опх сбнкэмемхх"
		#define STR0052 "пюявер янжхюкэмшу бшокюр опх сбнкэмемхх"
		#define STR0053 "сбнкэмемхе дн дюрш бшокюрш гюпокюрш"
		#define STR0054 "сбнкэмемхе дн дюрш бшокюрш гюпокюрш 2"
		#define STR0055 "пюявер вхярни ясллш бшокюр он сбнкэмемхч"
		#define STR0056 "пюявер аюкюмяю сдепфюмхи/мювхякемхи"
		#define STR0057 "цемепюжхъ аюкюмяю сдепфюмхи/мювхякемхи"
		#define STR0058 "пюявер ясллш й бшокюре опх сбнкэмемхх"
		#define STR0059 "пюявер днокюр опх сбнкэмемхх"
		#define STR0060 "пюявер сдепфюмхи опх сбнкэмемхх"
		#define STR0061 "гюцпсгйю дюммшу пюяверю нросяйю"
		#define STR0062 "пюявер нросяймшу япедмху"
		#define STR0063 "пюявер днонкмхрекэрмнцн нросяйю он бнся"
		#define STR0064 "пюявер дно. нросяймшу он бнся"
		#define STR0065 "пюявер ярюфеи опх пюявере нросяйю"
		#define STR0066 "яанп дюммшу он япедмхл дкъ нросяймшу"
		#define STR0067 "гюохяэ ясллш нросяймшу"
		#define STR0068 "гюохяэ дюммшу он япедмхл дкъ нросяймшу"
		#define STR0069 "гюохяэ аюкюмяю нросяймшу дмеи"
		#define STR0070 "опнбепйю опнтя. мюдаюбнй й нросяймшл"
		#define STR0071 "пюявер нокювхбюелшу бшундмшу нросяйю"
		#define STR0072 "гюохяэ нокювхбюелшу бшундмшу нросяйю"
		#define STR0073 "йнмбепрюжхъ дмеи нросяйю б бшокюрс"
		#define STR0074 "ясллхпнбюмхе нросяймшу бшокюр"
		#define STR0075 "опнбепйю бшокюр йнккейрхбмнцн нросяйю"
		#define STR0076 "пюявер опняпнвеммшу нросяйнб"
		#define STR0077 "гюохяэ бшокюр он опняпнвеммнлс нросяйс"
		#define STR0078 "пюявер дно. опняпнвеммшу нросяйнб"
		#define STR0079 "пюявер бшокюрш 13и го б нросяймше"
		#define STR0080 "опнбепйю бшокюрш 13и го б нросяймше"
		#define STR0081 "опнбепйю опюб онксвемхъ нросяйю"
		#define STR0082 "пюявер 13и гюпокюрш дкъ нросяйю"
		#define STR0083 "гюохяэ 13и гюпокюрш дкъ нросяйю"
		#define STR0084 "опнбепйю цпютхйю бшундмшу дмеи"
		#define STR0085 "пюявер яслл тяя я нросяймшу"
		#define STR0086 "нопедекемхе цпютхйю бшундмшу дмеи"
		#define STR0087 "яанп ясллш мювхякемхи дкъ нросяймшу"
		#define STR0088 "яанп ясллш сдепфюмхи я нросяймшу"
		#define STR0089 "ондцнрнбйю хрнцнбшу гмювемхи нросяймшу"
		#define STR0090 "гюцпсгйю дюммшу оепхндю"
		#define STR0091 "гюцпсгйю рюакхж дкъ пюяверю"
		#define STR0092 "гюцпсгйю дюммшу дкъ пюяверю"
		#define STR0093 "гюцпсгйю дюммшу он ярюрсяс опеашбюмхъ"
		#define STR0094 "опнбепйю нрпюанрюммшу вюянб"
		#define STR0095 "яанпйю ефелеяъвмни гюпокюрш"
		#define STR0096 "яанпйю онвюянбни гюпокюрш"
		#define STR0097 "яанпйю ефедмебмни гюпокюрш"
		#define STR0098 "яанпйю аюгнбни гюпокюрш"
		#define STR0099 "пюявер бпелеммнцн ямхфемхъ го═"
		#define STR0100 "пюявер бпелеммнцн сбекхвемхъ го═"
		#define STR0101 "гюцпсгйю пюмее пюявхрюммшу гмювемхи"
		#define STR0102 "пюявер йнщттхжхемрю хмдейяюжхх го"
		#define STR0103 "пюявер хмдейяюжхх гюпокюрш"
		#define STR0104 "пюявер асдсыху бекхвхм"
		#define STR0105 "пюанвхе дмх"
		#define STR0106 "дмх нрясрярбхъ"
		#define STR0107 "пюявер тхйяхпнбюммшу бшокюр/сдепфюмхи"
		#define STR0108 "пюявер бшундмшу дмеи"
		#define STR0109 "пюявер гюпокюрш"
		#define STR0110 "опнбепйю ярюрсяю янрпсдмхйю"
		#define STR0111 "цемепюжхъ рюпхтнб"
		#define STR0112 "пюявер бшундмшу дкъ рюпхтмни нокюрш"
		#define STR0113 "хмхжхюкхгюжхъ пюяверю дкъ опеонднбюрекеи"
		#define STR0114 "аюгнбюъ ярюбйю дкъ опеондюбюрекеи"
		#define STR0115 "гюохяэ бшундмшу дкъ опеондюбюрекеи"
		#define STR0116 "пюявер вюянб пюанрш опеондюбюрекъ"
		#define STR0117 "гюохяэ вюянб пюанрш опеондюбюрекъ"
		#define STR0118 "йнлонмнбйю гюпокюрш опеондюбюрекъ"
		#define STR0119 "опнонпжхнмюкэмши пюявер го опеондюбюрекъ"
		#define STR0120 "оепелеммши опнонпжхнмюкэмши пюявер"
		#define STR0121 "япнвмши йнмрпюйр - 13ъ гюпокюрю"
		#define STR0122 "япнвмши йнмрпюйр - нросяй"
		#define STR0123 "бйкчвемхе опнонпжхнмюкэмнцн пюяверю"
		#define STR0124 "хмхжхюкхгюжхъ дюммшу он рейсыелс ярюфс"
		#define STR0125 "пюявер бшокюрш гю оепбши цнд"
		#define STR0126 "пюявер бшокюрш гю брнпни цнд"
		#define STR0127 "пюявер бшокюрш гю рперхи цнд"
		#define STR0128 "пюявер бшокюрш гю вербепрши цнд"
		#define STR0129 "пюявер бшокюрш гю оърши цнд"
		#define STR0130 "пюявер леяъвмни бшкюрш гю ярюф"
		#define STR0131 "пюявер леяъвмни бшкюрш гю люрепхмярбн"
		#define STR0132 "нрйкчвемхе═ опнонпжхнмюкэмнцн пюяверю"
		#define STR0133 "пюявер мюдаюбйх гю кнъкэмнярэ"
		#define STR0134 "гюохяэ мюдаюбйх гю кнъкэмнярэ"
		#define STR0135 "гюохяэ мюдаюбнй гю люрепхмярбн"
		#define STR0136 "пюявер цюпюмрхпнбюмшу бшокюр"
		#define STR0137 "пюявер мюдаюбйх гю кнъкэмнярэ"
		#define STR0138 "гюохяэ мюдаюбйх гю кнъкэмнярэ"
		#define STR0139 "гюохяэ пекнйюжхнммшу бшокюр дкъ ахп"
		#define STR0140 "цемепюжхъ дно ефелеяъвмшу бшокюр"
		#define STR0141 "пюявер бшокюрш бнся"
		#define STR0142 "гюохяэ бшокюрш бнся"
		#define STR0143 "гюохяэ бшокюр бнся дкъ дейп. нросяйнб"
		#define STR0144 "цемепюжхъ ефелеяъвмшу мювхякемхи гю бнся"
		#define STR0145 "аюгю пюяверю дкъ анкэмхвмшу"
		#define STR0146 "пюявер лхм ясллш дкъ анкэмхвмшу"
		#define STR0147 "гюохяэ лхм ясллш дкъ анкэмхвмшу"
		#define STR0148 "пюявер япедмху дкъ анкэмхвмшу"
		#define STR0149 "гюохяэ япедмху дкъ анкэмхвмшу"
		#define STR0150 "пюявер люйяхлюкэмни ясллш он анкэмхвмнлс"
		#define STR0151 "гюохяэ люйяхлюкэмни ясллш он анкэмхвмнлс"
		#define STR0152 "гюохяэ ясллш анкэмхвмнцн он люрепхмярбс"
		#define STR0153 "цемепюжхъ бшокюр он анкэмхвмшл"
		#define STR0154 "опнвхе оепепюанрйх б бшундмше"
		#define STR0155 "пюявер опнбнднй асдсыху оепхнднб"
		#define STR0156 "пюявер цюпюмрхпнбюмни го йнлхяяхнмепнб"
		#define STR0157 "гюохяэ пюяверю он бхдюл нокюр"
		#define STR0158 "гюохяэ йнппеяондхпсчыху бхднб нокюр"
		#define STR0159 "мнплхпнбюмши свер"
		#define STR0160 "пюявер пюгкхвмшу нросяйнб"
		#define STR0161 "йкюяяхтхйюжхъ нокювхбюелшу нрясярбхи"
		#define STR0162 "пюявер ярпсйрспмнцн япедмецн"
		#define STR0163 "пюявер вюянб пюанрш б бшундмше"
		#define STR0164 "пюявер днокюрш гю ярюф 1 цнд"
		#define STR0165 "пюявер днокюрш гю ярюф 2 цндю"
		#define STR0166 "пюявер днокюрш гю ярюф 3 цндю"
		#define STR0167 "пюявер днокюрш гю ярюф 4 цндю"
		#define STR0168 "пюявер днокюрш гю ярюф 5 кер"
		#define STR0169 "цемепюыхъ яоежхюкэмшу бшокюр"
		#define STR0170 "пюявер леяъвмни бшкюрш гю люрепхмярбн"
		#define STR0171 "пюявер анкэмхвмшу"
		#define STR0172 "гюохяэ анкэмхвмшу"
		#define STR0173 "гюохяэ дейпермшу анкэмхвмшу"
		#define STR0174 "цемепюжхъ анкэмхвмшу гю оепхнд"
		#define STR0175 "пюявер бнся"
		#define STR0176 "гюохяэ бнся"
		#define STR0177 "гюохяэ бнся дкъ дейпермшу нросяйнб"
		#define STR0178 "пюявер бнся гю оепхнд"
		#define STR0179 "пюявер нрясрярбхи"
		#define STR0180 "яелеимюъ гюпокюрю"
		#define STR0181 "пюявер нрвхякемхи для"
		#define STR0182 "аюгю пюяверю опнтянчгмшу бгмнянб"
		#define STR0183 "опнтянчгмши бгмня"
		#define STR0184 "ефелеяъвмне нрвхякемхе б опнтянчг"
		#define STR0185 "бгмняш б тнмд люрепхюкэмни онлных"
		#define STR0186 "бгмняш б опнтянчгмсч йнмтедепюжхч"
		#define STR0187 "пюявер люрепхюкэмни онлных"
		#define STR0188 "пюявер тяя"
		#define STR0189 "цемепюжхъ дейпермшу бшокюр"
		#define STR0190 "пюявер опнт. бгмнянб дкъ нрясрярбхи"
		#define STR0191 "пюявер тяя - 13ъ гюпокюрю"
		#define STR0192 "пюявер юкхлемрнб"
		#define STR0193 "пюявер мдтк"
		#define STR0194 "пюявер мдтк - нросяйю"
		#define STR0195 "пюявер мдтк - 13 гюпокюрю"
		#define STR0196 "пюявер бгмнянб отп"
		#define STR0197 "пюявер бгмнянб отп - 13ъ═ гюпокюрю"
		#define STR0198 "пюявер нйпсцкеммшу яслл й бшокюре"
		#define STR0199 "пюявер тяя - днонкмхрекэмши пюявер"
		#define STR0200 "пюяопедекемхе он жемрпюл гюрпюр"
		#define STR0201 "гюохяэ аюгнбни гюпокюрш гю оепхнд"
		#define STR0202 "днонкмхрекэмши пюявер"
		#define STR0203 "пюявер янблеярхрекэярбю"
		#define STR0204 "опнлефсрнвмше япедмхе"
		#define STR0205 "яебепмюъ мюдаюбйю"
		#define STR0206 "пецхнмюкэмши йнщттхжхемр"
		#define STR0207 "гюохяэ пегскэрюрнб пюяверю"
		#define STR0208 "кэцнрш дкъ лнкндшу яоежхюкхярнб"
		#define STR0209 "опнялнрп яннаыемхи на ньхайюу б пюявере"
	#endif
#endif
