#ifdef SPANISH
	#define STR0001 "Sucursal de referencia por Estado/Prov/Reg"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Datos"
	#define STR0007 "Estado/Prov/Reg de la Sucursal seleccionada difiere del Estado/Prov/Reg informado"
	#define STR0008 "Seleccione una sucursal del Estado/Prov/Reg informado"
	#define STR0009 "Estado/Prov/Reg registrado"
	#define STR0010 "Seleccione un Estado/Prov/Reg diferente"
	#define STR0011 'Cliente/Tienda no válidos.'
	#define STR0012 "Diccionario desactualizado."
	#define STR0013 "Atención"
	#define STR0014 "Sucursal no existe."
	#define STR0015 "Seleccione una sucursal válida"
#else
	#ifdef ENGLISH
		#define STR0001 "Reference branch by State"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Data"
		#define STR0007 "Branch state selected is different from the state entered"
		#define STR0008 "Select a branch from the state entered"
		#define STR0009 "State already registered"
		#define STR0010 "Select a different State"
		#define STR0011 'Invalid Customer/Store'
		#define STR0012 "Dictionary outdated."
		#define STR0013 "Attention"
		#define STR0014 "Branch not exist"
		#define STR0015 "Select a registered branch"
	#else
		#define STR0001 "Filial de Referência por UF"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Dados"
		#define STR0007 "UF da Filial selecionada difere da UF informada"
		#define STR0008 "Selecione uma filial do estado informado"
		#define STR0009 "UF já cadastrada"
		#define STR0010 "Selecione uma UF diferente"
		#define STR0011 'Client/Loja inválidos'
		#define STR0012 "Dicionário desatualizado."
		#define STR0013 "Atenção"
		#define STR0014 "Filial Inexistente"
		#define STR0015 "Selecione uma filial válida"
	#endif
#endif
