#ifdef SPANISH
	#define STR0001 "Visualizar"
	#define STR0002 "Incluir"
	#define STR0003 "Modificar"
	#define STR0004 "Borrar"
	#define STR0005 "Imprimir"
	#define STR0006 "Copiar"
	#define STR0007 "Presupuesto de contrato"
	#define STR0008 "Datos del presupuesto de contrato"
	#define STR0009 "Itinerarios"
	#define STR0010 "Costos"
	#define STR0011 "Trayecto"
	#define STR0012 "De registro"
	#define STR0013 "Costos adicionales / Cortesía"
	#define STR0014 "Determinación de precios / Itinerario"
	#define STR0015 "Datos de la linea"
	#define STR0016 "Costos operativos"
	#define STR0017 "Base de datos desactualizado, no es posible iniciar la rutina"
	#define STR0018 "Anulando contrato...."
	#define STR0019 "Anulación de contrato permitido únicamente para contrato generado."
	#define STR0020 "Atención"
	#define STR0021 "Contrato generado con éxito"
	#define STR0022 "Generando contrato..."
	#define STR0023 "Creación de contrato permitida únicamente para registros con el estatus 'Pendiente'"
	#define STR0024 'Generar contrato'
	#define STR0025 'Anular contrato'
	#define STR0026 "Es necesario que la última línea del itinerario finalice con la localidad final de la línea"
	#define STR0027 "Línea duplicada"
	#define STR0028 "Secuencia ya utilizada"
	#define STR0029 "Modificación indebida"
	#define STR0030 "No puede modificarse, porque no es la última línea."
	#define STR0031 "Producto duplicado"
	#define STR0032 "Solo se puede un producto por línea"
	#define STR0033 "Producto no encontrado"
	#define STR0034 "Seleccione algún producto que exista"
	#define STR0035 "Producto informado se encuentra bloqueado"
	#define STR0036 "Informe un producto válido"
	#define STR0037 "Tipo de producto no válido."
	#define STR0038 "El tipo de producto debe ser tipo servicio 'SV'"
	#define STR0039 "Cálculo de costo"
	#define STR0040 "Listado de pasajeros"
	#define STR0041 "En presupuesto"
	#define STR0042 "Contrato vigente"
	#define STR0043 "Anulado"
	#define STR0044 "Código no se encontró"
	#define STR0045 "Utilice un código válido"
	#define STR0046 "Generar viajes"
	#define STR0047 "Consultar viajes"
	#define STR0048 "¿Desea generar los viajes ahora?"
	#define STR0049 "Viajes extras"
	#define STR0050 "Totalizadores"
	#define STR0051 "Adicional"
	#define STR0052 "Operativo"
	#define STR0053 "Total"
	#define STR0054 "Val. Ítem"
	#define STR0055 "Extra"
	#define STR0056 "Total general"
	#define STR0057 "Totales por línea"
	#define STR0058 "Visualizar contrato"
	#define STR0059 "Contrato"
	#define STR0060 "Buscando Contrato"
	#define STR0061 "No se generó contrato"
	#define STR0062 "Atención"
	#define STR0063 "Este registro no se debe modificar o borrar."
	#define STR0064 "Contrato generado"
	#define STR0065 "Clase de tipo de contrato diferente de Venta"
	#define STR0066 "Contrato seleccionado no debe ser del tipo fijo"
	#define STR0067 "Contrato seleccionado debe estar configurado con Previsión Financiera igual a 'No'"
	#define STR0068 "Contrato seleccionado debe estar configurado con Medición Eventual igual a 'Sí'"
	#define STR0069 "Medición eventual del tipo de planilla no debe estar configurada como 'No'"
	#define STR0070 "Tipo de planilla debe estar configurada como 'Fijo' o 'Conforme Contrato'"
	#define STR0071 "Previsión financiera del tipo de planilla debe estar configurada como 'No' o 'Conforme Contrato'"
	#define STR0072 "Finalizado"
	#define STR0073 "Finalizar contrato"
	#define STR0074 "Estatus del presupuesto de contrato no permite su finalización"
	#define STR0075 "Opción válida solamente para contratos con estatus 'Contrato generado'"
	#define STR0076 "Error al finalizar el contrato"
	#define STR0077 "Finalizando contrato..."
	#define STR0078 "Estatus del presupuesto de contrato no permite su anulación"
	#define STR0079 "Producto sin TES"
	#define STR0080 "El campo TES del producto no se completó."
	#define STR0081 "En revisión"
	#define STR0082 "Revisión vigente"
	#define STR0083 "Obsoleto"
	#define STR0084 "Iniciar revisión"
	#define STR0085 "Concretar revisión"
	#define STR0086 "No se registró la línea para este presupuesto"
	#define STR0087 "Estatus actual del presupuesto no permite revisión"
	#define STR0088 "Tipo de revisión no se informó"
	#define STR0089 "'Tipo de revisión obligatoria"
	#define STR0090 "Justificación de la revisión no se informó"
	#define STR0091 "Justificación de la revisión obligatoria"
	#define STR0092 "Contrato no se encontró"
	#define STR0093 "Revisión generada con éxito"
	#define STR0094 "Pendiente"
	#define STR0095 "Reajuste"
	#define STR0096 "Contrato ya tiene una revisión en proceso"
	#define STR0097 "Generando revisión..."
	#define STR0098 "Error en la generación de la revisión"
	#define STR0099 "Revisión"
	#define STR0100 "No se informó ningún porcentaje de reajuste"
	#define STR0101 "Informe los porcentajes antes de hacer efectiva la revisión"
	#define STR0102 "Opción válida solamente para contratos en revisión"
	#define STR0103 "Error en la aprobación del contrato"
	#define STR0104 "Impresión del contrato"
	#define STR0105 "Configuración del contrato no permite reajustes"
	#define STR0106 "Aprobando revisión..."
#else
	#ifdef ENGLISH
		#define STR0001 "View"
		#define STR0002 "Add"
		#define STR0003 "Edit"
		#define STR0004 "Delete"
		#define STR0005 "Print"
		#define STR0006 "Copy"
		#define STR0007 "Contract Budget"
		#define STR0008 "Contract Budget Data"
		#define STR0009 "Itineraries"
		#define STR0010 "Costs"
		#define STR0011 "Route"
		#define STR0012 "Cadastral"
		#define STR0013 "Additional Costs / Gratuity"
		#define STR0014 "Pricing / Itinerary"
		#define STR0015 "Line Data"
		#define STR0016 "Operating Costs"
		#define STR0017 "Database outdated. Unable to start routine."
		#define STR0018 "Canceling Contract..."
		#define STR0019 "Contract cancellation allowed only for generated contract."
		#define STR0020 "Attention"
		#define STR0021 "Contact successfully generated"
		#define STR0022 "Generating Contract..."
		#define STR0023 "Contract creation allowed only for records with status 'Pending'"
		#define STR0024 'Generate Contract'
		#define STR0025 'Cancel Contract'
		#define STR0026 "The last line of itinerary must end with the final location of line"
		#define STR0027 "Duplicated line"
		#define STR0028 "Sequence already used"
		#define STR0029 "Undue change"
		#define STR0030 "You cannot edit because this is not the last line"
		#define STR0031 "Duplicated product"
		#define STR0032 "Only one product per line is allowed"
		#define STR0033 "Product not found"
		#define STR0034 "Select an existing product"
		#define STR0035 "Product entered is blocked"
		#define STR0036 "Enter a valid product"
		#define STR0037 "Product Type not valid."
		#define STR0038 "The type of product must be SV service type"
		#define STR0039 "Cost Calculation"
		#define STR0040 "Passengers List"
		#define STR0041 "In budget"
		#define STR0042 "Valid contract"
		#define STR0043 "Canceled"
		#define STR0044 "Code not found"
		#define STR0045 "Use a valid code"
		#define STR0046 "Generate Travels"
		#define STR0047 "Search Trips"
		#define STR0048 "Generate trips now?"
		#define STR0049 "Extra Trips"
		#define STR0050 "Totalizers"
		#define STR0051 "Additional"
		#define STR0052 "Operational"
		#define STR0053 "Total"
		#define STR0054 "Item Vl."
		#define STR0055 "Extra"
		#define STR0056 "Grand Total"
		#define STR0057 "Total per row"
		#define STR0058 "View Contract"
		#define STR0059 "Contract"
		#define STR0060 "Searching Contract"
		#define STR0061 "No contract generated"
		#define STR0062 "Attention"
		#define STR0063 "This record cannot be edited or deleted."
		#define STR0064 "Contract generated"
		#define STR0065 "Type of contract different than the sales"
		#define STR0066 "Contract selected cannot be fixed type"
		#define STR0067 "Contract selected must be set as Financial Estimation equal to ‘No’"
		#define STR0068 "Contract selected must be configured with Eventual Measure equal to 'Yes'"
		#define STR0069 "Eventual measure of spreadsheet type cannot be set as ‘No’"
		#define STR0070 "Type of spreadsheet must be set as ‘Fixed’ or ‘According to Contract’"
		#define STR0071 "Financial Type of spreadsheet must be set as ‘No’ or ‘According to Contract’"
		#define STR0072 "Finished"
		#define STR0073 "Finished Contract"
		#define STR0074 "Contract Budget status does not allow its ending"
		#define STR0075 "Option valid only for contracts with status 'Contract generated'"
		#define STR0076 "Error finishing contract"
		#define STR0077 "Finishing contract..."
		#define STR0078 "Contract budget status does not allow its cancellation"
		#define STR0079 "Product without TIO"
		#define STR0080 "Product TIO field is blank."
		#define STR0081 "In Review"
		#define STR0082 "Valid revision"
		#define STR0083 "Obsolete"
		#define STR0084 "Start Review"
		#define STR0085 "Perform Review"
		#define STR0086 "No row registered for this budget"
		#define STR0087 "Budget's current status does not allow revision"
		#define STR0088 "Revision Type not entered"
		#define STR0089 "Revision Type mandatory"
		#define STR0090 "Revision Justification not entered"
		#define STR0091 "Revision justification mandatory"
		#define STR0092 "Contract not found"
		#define STR0093 "Revision successfully generated"
		#define STR0094 "Open"
		#define STR0095 "Readjustment"
		#define STR0096 "Contract already has a revision in process"
		#define STR0097 "Generating Revision..."
		#define STR0098 "Error in revision generation"
		#define STR0099 "Revision"
		#define STR0100 "No adjustment percentage entered"
		#define STR0101 "Enter percentages before activating revision"
		#define STR0102 "Option valid only for contracts under revision"
		#define STR0103 "Error in contract approval"
		#define STR0104 "Contract Printing"
		#define STR0105 "Contract configuration does not allow adjustments"
		#define STR0106 "Approving Revision..."
	#else
		#define STR0001 "Visualizar"
		#define STR0002 "Incluir"
		#define STR0003 "Alterar"
		#define STR0004 "Excluir"
		#define STR0005 "Imprimir"
		#define STR0006 "Copiar"
		#define STR0007 "Orçamento de Contrato"
		#define STR0008 "Dados do Orçamento de Contrato"
		#define STR0009 "Itinerários"
		#define STR0010 "Custos"
		#define STR0011 "Percurso"
		#define STR0012 "Cadastral"
		#define STR0013 "Custos adicionais / Cortesia"
		#define STR0014 "Precificaçao / Itinerário"
		#define STR0015 "Dados da Linha"
		#define STR0016 "Custos Operacionais"
		#define STR0017 "Banco de dados desatualizado, não é possível iniciar a rotina"
		#define STR0018 "Cancelando Contrato...."
		#define STR0019 "Cancelamento de contrato permitido apenas para contrato gerado."
		#define STR0020 "Atenção"
		#define STR0021 "Contrato gerado com sucesso"
		#define STR0022 "Gerando Contrato...."
		#define STR0023 "Criação de contrato permitido apenas para registros com o status 'Em Aberto'"
		#define STR0024 'Gerar Contrato'
		#define STR0025 'Cancelar Contrato'
		#define STR0026 "Necessário que a ultima linha do itnerario finalize com a localidade final da linha"
		#define STR0027 "Linha duplicada"
		#define STR0028 "Sequência já utilizada"
		#define STR0029 "Alteração indevida"
		#define STR0030 "Não pode alterar, por não ser ultima linha."
		#define STR0031 "Produto duplicado"
		#define STR0032 "Só pode um produto por linha"
		#define STR0033 "Produto não encontrado"
		#define STR0034 "Selecione algum produto que exista"
		#define STR0035 "Produto informado se encontra bloqueado"
		#define STR0036 "Informe um produto valido"
		#define STR0037 "Tipo de Produto inválido."
		#define STR0038 "O tipo do produto de ser do tipo serviço 'SV'"
		#define STR0039 "Cálculo Custo"
		#define STR0040 "Listagem passageiros"
		#define STR0041 "Em orçamento"
		#define STR0042 "Contrato vigente"
		#define STR0043 "Cancelado"
		#define STR0044 "Código não encontrado"
		#define STR0045 "Utilize um código válido"
		#define STR0046 "Gerar Viagens"
		#define STR0047 "Consultar Viagens"
		#define STR0048 "Deseja gerar as viagens agora?"
		#define STR0049 "Viagens Extras"
		#define STR0050 "Totalizadores"
		#define STR0051 "Adicional"
		#define STR0052 "Operacional"
		#define STR0053 "Total"
		#define STR0054 "Vlr. Item"
		#define STR0055 "Extra"
		#define STR0056 "Total Geral"
		#define STR0057 "Totais por Linha"
		#define STR0058 "Visualizar contrato"
		#define STR0059 "Contrato"
		#define STR0060 "Buscando Contrato"
		#define STR0061 "Não foi gerado contrato"
		#define STR0062 "Atenção"
		#define STR0063 "Este registro não pode ser alterado ou excluído."
		#define STR0064 "Contrato gerado"
		#define STR0065 "Espécie do tipo de contrato diferente de Venda"
		#define STR0066 "Contrato selecionado não pode ser do tipo fixo"
		#define STR0067 "Contrato selecionado deve estar configurado com Previsão Financeira igual a 'Não'"
		#define STR0068 "Contrato selecionado deve estar configurado com Medição Eventual igual a 'Sim'"
		#define STR0069 "Medição eventual do tipo de planilha não pode estar configurada como 'Não'"
		#define STR0070 "Tipo de planilha deve estar configurada como 'Fixo' ou 'Conforme Contrato'"
		#define STR0071 "Previsão financeira do tipo de planilha deve estar configurada como 'Não' ou 'Conforme Contrato'"
		#define STR0072 "Finalizado"
		#define STR0073 "Finalizar Contrato"
		#define STR0074 "Status do orçamento de contrato não permite o seu encerramento"
		#define STR0075 "Opção válida apenas para contratos com status 'Contrato gerado'"
		#define STR0076 "Erro ao finalizar o contrato"
		#define STR0077 "Finalizando contrato..."
		#define STR0078 "Status do orçamento de contrato não permite o seu cancelamento"
		#define STR0079 "Produto sem TES"
		#define STR0080 "O campo TES do produto não foi preenchido."
		#define STR0081 "Em Revisão"
		#define STR0082 "Revisão vigente"
		#define STR0083 "Obsoleto"
		#define STR0084 "Iniciar Revisão"
		#define STR0085 "Efetivar Revisão"
		#define STR0086 "Não foi cadastrado linha para esse orçamento"
		#define STR0087 "Status atual do orçamento não permite revisão"
		#define STR0088 "Tipo de revisão não informado"
		#define STR0089 "'Tipo de revisão obrigatório"
		#define STR0090 "Justificativa da revisão não informada"
		#define STR0091 "Justificativa da revisão obrigatória"
		#define STR0092 "Contrato não encontrado"
		#define STR0093 "Revisão gerada com sucesso"
		#define STR0094 "Aberta"
		#define STR0095 "Reajuste"
		#define STR0096 "Contrato já possui uma revisão em andamento"
		#define STR0097 "Gerando Revisão..."
		#define STR0098 "Erro na geração da revisão"
		#define STR0099 "Revisão"
		#define STR0100 "Nenhum percentual de reajuste foi informado"
		#define STR0101 "Informe os percentuais antes de efetivar a revisão"
		#define STR0102 "Opção válida apenas para contratos em revisão"
		#define STR0103 "Erro na aprovação do contrato "
		#define STR0104 "Impressão do Contrato"
		#define STR0105 "Configuração do contrato não permite reajustes"
		#define STR0106 "Aprovando Revisão..."
	#endif
#endif
