#ifdef SPANISH
	#define STR0001 "Comisión de contratos de turismo"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Imprimir"
	#define STR0007 "Copiar"
	#define STR0008 "Comisión de contratos de turismo"
	#define STR0009 "Comisión por producto"
	#define STR0010 "Activo"
	#define STR0011 "Inactivo"
	#define STR0012 "Código de la agencia ( "
	#define STR0013 ") inexistente."
	#define STR0014 "Informe un código de la agencia existente."
	#define STR0015 ")"
	#define STR0016 "Informe un código de la agencia activo."
	#define STR0017 "Para este código de agencia("
	#define STR0018 ") y vendedor ("
	#define STR0019 ") existe un registro activo ("
	#define STR0020 "Modifique el código de registro activo."
	#define STR0021 "Este registro esta inactivo."
	#define STR0022 "Registros no activos no se deben modificar."
	#define STR0023 "Cumplimentación incorrecta"
	#define STR0024 "Complete el campo %Comisión. Se permitió porcentajes mayores que 0.00% limitado al 100%"
	#define STR0025 "Código no registrado"
	#define STR0026 "Informe un código existente. Haga clic en la lupa para buscar"
	#define STR0027 "Existe por lo menos un procesamiento de comisión ( Código "
	#define STR0028 " vendedor "
	#define STR0029 ") calculada basada en este registro, por lo tanto, este registro no se podrá borrar."
	#define STR0030 "Evalúe la posibilidad de borrar el cálculo de la comisión, si esta no se ha exportado a la planilla de haberes."
	#define STR0031 "Solamente la agencia del tipo propia podrá utilizar este registro."
	#define STR0032 "Revise el registro de la agencia."
	#define STR0033 "Código del vendedor "
	#define STR0034 " bloqueado/inactivo."
	#define STR0035 "Informe un código de vendedor activo."
#else
	#ifdef ENGLISH
		#define STR0001 "Commission of Tourism Contracts"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Print"
		#define STR0007 "Copy"
		#define STR0008 "Commission of Tourism Contracts"
		#define STR0009 "Commission per Product"
		#define STR0010 "Active"
		#define STR0011 "Inactive"
		#define STR0012 "Branch Code ( "
		#define STR0013 ") does not exist."
		#define STR0014 "Enter an existing agency code."
		#define STR0015 ")"
		#define STR0016 "Enter an active agency code."
		#define STR0017 "For this agency code("
		#define STR0018 ") and sales representative ("
		#define STR0019 ") there is an active register ("
		#define STR0020 "Change code of active register."
		#define STR0021 "This register is inactive."
		#define STR0022 "Inactive registers cannot be changed."
		#define STR0023 "Incorrect completion"
		#define STR0024 "Enter field %Commission. Percentages greater than 0.00% limited to 100% allowed"
		#define STR0025 "Code not registered"
		#define STR0026 "Enter an existing code. Click in the Magnifier to search."
		#define STR0027 "There is at least a commission processing (Code "
		#define STR0028 " sales representative "
		#define STR0029 ") calculated based on this register, therefore, this register can be deleted."
		#define STR0030 "Evaluate the possibility of deleting the calculation of the commission, if i has not been exported to payroll."
		#define STR0031 "Only own type agency can use this register."
		#define STR0032 "Review agency register."
		#define STR0033 "Sales representative code "
		#define STR0034 " blocked/inactive."
		#define STR0035 "Enter an active sales representative code."
	#else
		#define STR0001 "Comissão de Contratos de Turismo"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Imprimir"
		#define STR0007 "Copiar"
		#define STR0008 "Comissão de Contratos de Turismo"
		#define STR0009 "Comissão por Produto"
		#define STR0010 "Ativo"
		#define STR0011 "Inativo"
		#define STR0012 "Código da agência ( "
		#define STR0013 ") inexistente."
		#define STR0014 "Informar um código da agência existente."
		#define STR0015 ")"
		#define STR0016 "Informar um código da agência ativo."
		#define STR0017 "Para este código de agência("
		#define STR0018 ") e vendedor ("
		#define STR0019 ") existe um cadastro ativo ("
		#define STR0020 "Alterar o código de cadastro ativo."
		#define STR0021 "Este cadastro esta inativo."
		#define STR0022 "Cadastros inativos não podem ser modificados."
		#define STR0023 "Preenchimento incorreto"
		#define STR0024 "Preencher o campo %Comissão. Permitido percentuais maiores que 0.00% limitado a 100%"
		#define STR0025 "Código não cadastrado"
		#define STR0026 "Informar um codigo existente. Clique na Lupa para pesquisar."
		#define STR0027 "Existe pelo menos um processamento de comissão ( Código "
		#define STR0028 " vendedor "
		#define STR0029 ") calculada baseada neste cadastro, portanto, este cadastro não poderá ser excluído."
		#define STR0030 "Avaliar a possibilidade de excluir o calculo de comissão, caso o mesmo não tenha sido exportada para a folha de pagamento."
		#define STR0031 "Somente agência do tipo própria poderá utilizar este cadastro."
		#define STR0032 "Revisar o cadastro da agência."
		#define STR0033 "Código do vendedor "
		#define STR0034 " bloqueado/inativo."
		#define STR0035 "Informar um código de vendedor ativo."
	#endif
#endif
