#ifdef SPANISH
	#define STR0001 "Total"
	#define STR0002 "DAPE"
	#define STR0003 "Ejecutando la carga de parámetros del módulo ..."
	#define STR0004 "Complete el parámetro "
	#define STR0005 "Inclusión"
	#define STR0006 "Ya existe vínculo de la ficha de envío vs. dape."
	#define STR0007 "Modificación"
	#define STR0008 "Visualización"
	#define STR0009 "Borrado"
	#define STR0010 "No existe vínculo para ficha de envío seleccionada"
	#define STR0011 "El estatus de la ficha de envío no permite continuar con la operación"
#else
	#ifdef ENGLISH
		#define STR0001 "Total"
		#define STR0002 "DAPE"
		#define STR0003 "Running the parameters load of module..."
		#define STR0004 "Complete the parameter "
		#define STR0005 "Addition"
		#define STR0006 "Binding of shipment x dape form already exists."
		#define STR0007 "Edition"
		#define STR0008 "View"
		#define STR0009 "Deletion"
		#define STR0010 "No binding exists for the remittance form selected"
		#define STR0011 "The status of remittance form does not allow to proceed with the operation"
	#else
		#define STR0001 "Total"
		#define STR0002 "DAPE"
		#define STR0003 "Executando a carga de parâmetros do módulo ..."
		#define STR0004 "Preencha o parâmetro "
		#define STR0005 "Inclusão"
		#define STR0006 "Já existe amarração da ficha de remessa x dape."
		#define STR0007 "Alteração"
		#define STR0008 "Visualização"
		#define STR0009 "Exclusão"
		#define STR0010 "Não existe amarração para ficha de remessa selecionada"
		#define STR0011 "O status da ficha de remessa não permite prosseguir com a operação"
	#endif
#endif
