#ifdef SPANISH
	#define STR0001 "Informe de tasas"
	#define STR0002 "Anulado"
	#define STR0003 "Abierto"
	#define STR0004 "Cerrado"
	#define STR0005 "Ítems del informe de tasas"
	#define STR0006 "No existe vínculo entre el usuario/colaborador "
	#define STR0007 " y el registro de agencia o agencia vinculada al usuario/colaborador está inactiva."
	#define STR0008 "Acceda a la rutina Registro de Agencias y vincule el usuario a la agencia."
	#define STR0009 "Buscar"
	#define STR0010 "&Visualizar"
	#define STR0011 "&Incluir"
	#define STR0012 "&Modificar"
	#define STR0013 "&Borrar"
	#define STR0014 "Campos agrupadores"
	#define STR0015 "Totales"
	#define STR0016 "Anulación"
	#define STR0017 "Cierre"
	#define STR0018 "Log"
	#define STR0019 "Fecha fuera del período de la ficha de envío número: "
	#define STR0020 "Informe una fecha entre "
	#define STR0021 "No liberados - Registro de tasas."
	#define STR0022 "Verifique si existen tasas registradas y/o si las mismas están vinculadas a una Ficha Remesa y Cerradas."
	#define STR0023 "Número de control de documento no existe"
	#define STR0024 "Acceda a la rutina Control de Documento y verifique."
	#define STR0025 "Ya existe un Comprobante de Tasas para esta agencia utilizando esta numeración de lote de documento."
	#define STR0026 "Encontrar el comprobante de la tasa y hacer clic en la opción Modificar."
	#define STR0027 "Cierre existente para este número de Comprobante."
	#define STR0028 "Verifique la posibilidad de reabrirlo."
	#define STR0029 "Documento no vinculado a una ficha de remesa, no cerrado, y/o no asignado para esta agencia."
	#define STR0030 "Verifique a través del registro de tasas o asignación de documentos."
	#define STR0031 "Informe un motivo de anulación."
	#define STR0032 "Verifique si el campo motivo está informado. Cumplimentación obligatoria para el comprobante que se anulará."
	#define STR0033 "Justifique el motivo de la anulación con una frase de 20 caracteres como mínimo."
	#define STR0034 "Verifique la cumplimentación."
	#define STR0035 "Informe la fecha de anulación."
	#define STR0036 "Verifique si el campo Data de anulación está informado. Cumplimentación obligatoria para el comprobante que se anulará."
	#define STR0037 "Fecha inferior a la inclusión del comprobante."
	#define STR0038 "Informe una fecha superior o igual a la fecha de emisión del comprobante."
	#define STR0039 "Valor del ajuste igual al valor original."
	#define STR0040 "Informe el valor del ajuste solamente si es diferente del valor original."
	#define STR0041 "Valor del ajuste negativo."
	#define STR0042 "Informe el valor del ajuste correctamente."
	#define STR0043 "El comprobante de la tasa está cerrado."
	#define STR0044 "Visualice o verifique el campo 'Fecha de Cierre' y solicite orientación al responsable."
	#define STR0045 "El comprobante de la tasa está anulado."
	#define STR0046 "Visualice y verifique los campos 'Anulado', 'Fecha de Anulación' y 'Motivo' y solicite orientación al responsable."
	#define STR0047 "Campos vinculados a la anulación no están informados correctamente."
	#define STR0048 "Informe los campos de 'Fecha de anulación' y 'Motivo de anulación'."
	#define STR0049 "Dado de baja"
	#define STR0050 "¿Cargar las tasas pendientes? <F4>"
	#define STR0051 "¿'Marcar todas las tasas?<F5>"
	#define STR0052 "¿Desmarcar todas las tasas?<F6>"
	#define STR0053 "¿Desea cargar automáticamente todos los registros de tasas pendientes?"
	#define STR0054 "Pendientes - Registro de tasa"
	#define STR0055 "Agencia no registrada."
	#define STR0056 "Verifique a través del registro de la agencia."
	#define STR0057 "No existen fichas de envío pendientes."
	#define STR0058 "Solicite al responsable la apertura de una ficha Envío para esta agencia."
	#define STR0059 "Fecha inicial"
	#define STR0060 "Fecha final"
	#define STR0061 "Espere"
	#define STR0062 "Verificando existencia de tasas pendientes...."
	#define STR0063 "Para el período informado no existen tasas registradas."
	#define STR0064 "Verifique a través del registro de tasas."
	#define STR0065 "Cargamento automático anulado"
	#define STR0066 "Anulado"
	#define STR0067 "Cumplimentación incorrecta."
	#define STR0068 "Informe el código de la agencia y el número."
	#define STR0069 "No existen ítems para actualizar/vincular."
	#define STR0070 "Sin modificaciones"
	#define STR0071 "Desea realmente "
	#define STR0072 "marcar<->desmarcar (revierte el marcado de cada línea) "
	#define STR0073 "marcar"
	#define STR0074 "desmarcar"
	#define STR0075 " todas las tasas?"
	#define STR0076 "Marcar o desmarcar"
	#define STR0077 "Teclas de atajo no disponibles en la pantalla principal"
	#define STR0078 "Incluya o Modifique un comprobante de la tasa para activar las teclas de atajo."
	#define STR0079 "Se debe-vincular por lo menos un registro de la tasa"
	#define STR0080 "Activar la opción Borrar si desea eliminar totalmente los registros de tasas vinculados, consecuentemente borrando el comprobante de la tasa."
	#define STR0081 "Intervalo de fecha no válido."
	#define STR0082 "Revisar el intervalo de fecha."
	#define STR0083 " a "
	#define STR0084 "Para esta fecha "
	#define STR0085 " ya existe un comprobante pendiente/entregado."
	#define STR0086 "Encuentre el comprobante de la tasa y haga clic en Modificar."
	#define STR0087 "Fecha fuera del período de la(s) Ficha(s) de Envío(s) pendiente o entregado"
	#define STR0088 "Informe una fecha vinculada a una Ficha de Envío que esté con estatus Pendiente o Entregado."
#else
	#ifdef ENGLISH
		#define STR0001 "Rate Statement"
		#define STR0002 "Canceled"
		#define STR0003 "Open"
		#define STR0004 "Closed"
		#define STR0005 "Items of rate statement"
		#define STR0006 "No relationship between user/employee "
		#define STR0007 " and the branch register or the branch linked to the user/employee is inactive."
		#define STR0008 "Access routine of Register of Bank Branches and link user to bank branch."
		#define STR0009 "Search"
		#define STR0010 "View"
		#define STR0011 "Add"
		#define STR0012 "Edit"
		#define STR0013 "&Delete"
		#define STR0014 "Grouping fields"
		#define STR0015 "Totals"
		#define STR0016 "Cancellation"
		#define STR0017 "Closing"
		#define STR0018 "Log"
		#define STR0019 "Date out of the period of Remittance Form number: "
		#define STR0020 "Enter date between "
		#define STR0021 "Not released - Rate register"
		#define STR0022 "Check if there are rates registered and/or if they are associated with a shipment form and closed."
		#define STR0023 "Non-existent document control number"
		#define STR0024 "Access document control routine and check."
		#define STR0025 "A rate statement for this branch already exists using this document lot numbering."
		#define STR0026 "Find rate statement and click Edit."
		#define STR0027 "Existing closure for this statement number."
		#define STR0028 "Check the possibility of reopening it."
		#define STR0029 "Document not associated with a shipment form, not closed, and/or not allocated for this branch."
		#define STR0030 "Check through the rate register or document allocation."
		#define STR0031 "Enter a reason for cancellation."
		#define STR0032 "Check if field Reason is filled. You must fill it to cancel the statement."
		#define STR0033 "Justify the reason for cancellation with at least one 20-character sentence."
		#define STR0034 "Check completion."
		#define STR0035 "Enter cancellation date."
		#define STR0036 "Check if field Cancellation Date is filled. You must fill it to cancel the statement."
		#define STR0037 "Date before inclusion of statement"
		#define STR0038 "Enter a date greater than or equal to the issue date of the statement."
		#define STR0039 "Value of adjustment equal to original value."
		#define STR0040 "Enter the value of adjustment only if it is different from original value."
		#define STR0041 "Negative adjustment value"
		#define STR0042 "Enter correct adjustment value"
		#define STR0043 "Rate statement closed"
		#define STR0044 "View or check field Closing Date field and request guidance from the person in charge."
		#define STR0045 "Rate statement canceled"
		#define STR0046 "View and check fields Canceled, Cancellation Date and Reason and request guidance from the person in charge."
		#define STR0047 "Cancellation related fields not filled out correctly."
		#define STR0048 "Fill fields Cancellation Date and Cancellation Reason."
		#define STR0049 "Written Off"
		#define STR0050 "Load Pending Rates? <F4>"
		#define STR0051 "'Select all rates?<F5>"
		#define STR0052 "Clear all rates?<F6>"
		#define STR0053 "Automatically load all registers of Pending rates?"
		#define STR0054 "Pending - Rate Register"
		#define STR0055 "Bank branch not registered."
		#define STR0056 "Check through the bank branch register."
		#define STR0057 "No pending Remittance Forms."
		#define STR0058 "Request the opening of a Remittance Form to the responsible party for this bank branch."
		#define STR0059 "Start Date"
		#define STR0060 "End Date"
		#define STR0061 "Wait"
		#define STR0062 "Checking the existence of pending rates..."
		#define STR0063 "For the period informed, there are no registered rates."
		#define STR0064 "Check through Rates Register."
		#define STR0065 "Automatic loading canceled"
		#define STR0066 "Canceled"
		#define STR0067 "Incorrect completion."
		#define STR0068 "Complete code of Bank Branch and Number."
		#define STR0069 "There are no items to be updated/linked."
		#define STR0070 "No changes"
		#define STR0071 "Do you really want to "
		#define STR0072 "select<->clear (reverts marking of each line) "
		#define STR0073 "mark"
		#define STR0074 "clear"
		#define STR0075 " all rates?"
		#define STR0076 "Selected or Clear"
		#define STR0077 "Shortcut keyboards not available on the main screen"
		#define STR0078 "Add or Edit a Rate Statement to add shortcut keyboards."
		#define STR0079 "Associate, at least, a Rate register"
		#define STR0080 "Add option Deleted to totally delete the registers of rates linked, then deleting the Rate Statement."
		#define STR0081 "Date interval not valid."
		#define STR0082 "Review date interval."
		#define STR0083 " to "
		#define STR0084 "For this date "
		#define STR0085 " there already is a pending/delivered statement."
		#define STR0086 "Find Statement of Rate then click Edit."
		#define STR0087 "Date out of the period of pending or delivered Remittance Form(s) "
		#define STR0088 "Enter an associated date to a Remittance Form that has pending or delivered."
	#else
		#define STR0001 "Demonstrativo de Taxas"
		#define STR0002 "Cancelado"
		#define STR0003 "Aberto"
		#define STR0004 "Fechado"
		#define STR0005 "Itens do Demonstrativo de Taxas"
		#define STR0006 "Não há vínculo entre o usuário/colaborador "
		#define STR0007 " e o cadastro de agência ou a agência vinculada ao usuário/colaborador esta inativa."
		#define STR0008 "Acessar a rotina Cadastro de Agências e vincular o usuário com a agência."
		#define STR0009 "Pesquisar"
		#define STR0010 "&Visualizar"
		#define STR0011 "&Incluir"
		#define STR0012 "&Alterar"
		#define STR0013 "&Excluir"
		#define STR0014 "Campos Aglutinadores"
		#define STR0015 "Totais"
		#define STR0016 "Cancelamento"
		#define STR0017 "Fechamento"
		#define STR0018 "Log"
		#define STR0019 "Data fora do período da Ficha Remessa número: "
		#define STR0020 "Informar uma data entre "
		#define STR0021 "Não liberados - Cadastro de taxas."
		#define STR0022 "Verificar se existem Taxas cadastradas e/ou se as mesmas estão associadas a uma Ficha Remessa e Fechadas."
		#define STR0023 "Número de Controle de Documento inexistente"
		#define STR0024 "Acessar a rotina Controle de Documento e verificar."
		#define STR0025 "Já existe um Demonstrativo de Taxas para esta agência utilizando esta numeração de lote de documento."
		#define STR0026 "Localizar o Demonstrativo de Taxa e clicar no botão Alterar."
		#define STR0027 "Fechamento existente para o este número de Demonstrativo."
		#define STR0028 "Verificar a possibilitadade de reabri-lo."
		#define STR0029 "Documento não associado a uma ficha Remessa, não fechado, e/ou não alocado para esta agência."
		#define STR0030 "Verificar através do Cadastro de Taxas ou Alocação de Documentos."
		#define STR0031 "Informe um motivo de cancelamento."
		#define STR0032 "Verificar se o campo motivo esta preenchido. Preenchimento obrigatório para Demonstrativo a ser cancelado."
		#define STR0033 "Justifique o motivo do cancelamento com no mínimo uma frase com 20 caracteres."
		#define STR0034 "Verificar preenchimento."
		#define STR0035 "Informe a data do cancelamento."
		#define STR0036 "Verificar se o campo Data do Cancelamento esta preenchido. Preenchimento obrigatório para Demonstrativo a ser cancelado."
		#define STR0037 "Data inferior a inclusão do Demonstrativo."
		#define STR0038 "Informar uma data superior ou igual a Data de Emissão do Demonstrativo."
		#define STR0039 "Valor do acerto igual ao valor original."
		#define STR0040 "Informar o valor do acerto somente se for diferente do valor original."
		#define STR0041 "Valor do acerto negativo."
		#define STR0042 "Informar o valor do acerto corretamente."
		#define STR0043 "O Demonstrativo de Taxa esta fechado."
		#define STR0044 "Visualizar ou verificar o campo 'Data de Fechamento' e solicitar orientação ao responsável."
		#define STR0045 "O Demonstrativo de Taxa esta cancelado."
		#define STR0046 "Visualizar e verificar os campos 'Cancelado', 'Data de Cancelamento' e 'Motivo' e solicitar orientação ao responsável."
		#define STR0047 "Campos relacionados ao cancelamento não estão preenchidos corretamente."
		#define STR0048 "Preencher os campos de 'Data de Cancelamento' e 'Motivo de Cancelamento'."
		#define STR0049 "Baixado"
		#define STR0050 "Carregar as Taxas Pendentes? <F4>"
		#define STR0051 "'Marcar todas as taxas?<F5>"
		#define STR0052 "Desmarcar todas as taxas?<F6>"
		#define STR0053 "Deseja carregar automaticamente todos os cadastros de taxas Pendentes?"
		#define STR0054 "Pendentes - Cadastro de Taxa"
		#define STR0055 "Agência não cadastrada."
		#define STR0056 "Verificar através do cadastro de agência."
		#define STR0057 "Não existem Fichas de Remessa em aberto."
		#define STR0058 "Solicitar ao responsável a abertura de um Ficha Remessa para esta agência."
		#define STR0059 "Data Inicial"
		#define STR0060 "Data Final"
		#define STR0061 "Aguarde"
		#define STR0062 "Verificando existência de taxas pendentes...."
		#define STR0063 "Para o período informado não existem taxas cadastradas."
		#define STR0064 "Verificar através do Cadastro de Taxas."
		#define STR0065 "Carregameto automático cancelado"
		#define STR0066 "Cancelado"
		#define STR0067 "Preenchimento incorreto."
		#define STR0068 "Preencher o código da Agência e o Número."
		#define STR0069 "Não existem itens a serem atualizados/vinculados."
		#define STR0070 "Sem alterações"
		#define STR0071 "Deseja realmente "
		#define STR0072 "marcar<->desmarcar (reverte a marcação de cada linha) "
		#define STR0073 "marcar"
		#define STR0074 "desmarcar"
		#define STR0075 " todas as taxas?"
		#define STR0076 "Marcar ou Desmarcar"
		#define STR0077 "Teclas de atalho indisponiveis na tela principal"
		#define STR0078 "Incluir ou Alterar um Demonstrativo de Taxa para acionar as teclas de atalho."
		#define STR0079 "Deve-se associar pelo menos um cadastro de Taxa"
		#define STR0080 "Acionar a opção Excluir caso queira excluir totalmente os cadastros de taxas vinculados, consequentemente excluindo o Demonstrativo de Taxa."
		#define STR0081 "Intervalo de data inválido."
		#define STR0082 "Revisar o intervalo de data."
		#define STR0083 " até "
		#define STR0084 "Para esta data "
		#define STR0085 " já existe um Demonstrativo em aberto/entregue."
		#define STR0086 "Localizar o Demonstrativo de Taxa e clicar em alterar."
		#define STR0087 "Data fora do período da(s) Ficha(s) Remessa(s) em aberta ou entregue"
		#define STR0088 "Informar uma data associada a uma Ficha Remessa que esteja no status aberta ou entregue."
	#endif
#endif
