#ifdef SPANISH
	#define STR0001 "Informe los servicios del pasaje"
	#define STR0002 "Lista de pasajes"
	#define STR0003 "Código"
	#define STR0004 "Tabla temporal de pasajes"
	#define STR0005 "Archivo"
	#define STR0006 "Camino y nombre del archivo"
	#define STR0010 "¡Ya existe este pasaje, Servicio, Línea y Colaborador registrado!"
	#define STR0011 " Estos datos se importaron en el archivo Nº ECF: "
	#define STR0012 "Agregar servicios"
	#define STR0013 "Servicio:"
	#define STR0014 "Registro no válido"
	#define STR0015 "El viaje/servicio "
	#define STR0016 " talvez no exista registrado o no se adhiere a la fecha, horario ni sentido del billete."
	#define STR0017 "Verifique los registros de horario y viaje de esta línea, sentido y horario."
	#define STR0018 "Inclusión/Actualización de servicios"
	#define STR0019 "1=Ida"
	#define STR0020 "2=Vuelta"
	#define STR0021 "Imp. Lista"
	#define STR0022 "Confirmar"
	#define STR0023 "Anular"
#else
	#ifdef ENGLISH
		#define STR0001 "Enter ticket services"
		#define STR0002 "Ticket List"
		#define STR0003 "Code"
		#define STR0004 "Ticket temporary table"
		#define STR0005 "File"
		#define STR0006 "Path and name of file"
		#define STR0010 "Ticket, Service, Line, and Employee already registered."
		#define STR0011 " Data imported to file no. ECF: "
		#define STR0012 "Add services"
		#define STR0013 "Service:"
		#define STR0014 "Invalid Record"
		#define STR0015 "The trip/service "
		#define STR0016 " is probably not registered or does not adhere to the date, schedule and direction of the ticket."
		#define STR0017 "Check the records of Schedule and Trip for this line, direction and schedule."
		#define STR0018 "Addition/Updating of Services"
		#define STR0019 "1=Go"
		#define STR0020 "2=Back"
		#define STR0021 "Imp. Lista"
		#define STR0022 "Confirmar"
		#define STR0023 "Cancelar"
	#else
		#define STR0001 "Informar os Serviços do Bilhetes"
		#define STR0002 "Lista de Passagens"
		#define STR0003 "Codigo"
		#define STR0004 "Tabela Temporária de Bilhetes"
		#define STR0005 "Arquivo"
		#define STR0006 "Caminho e Nome do Arquivo"
		#define STR0010 "Já existe este Bilhete, Serviço, Linha e Colaborador cadastrado!"
		#define STR0011 " Estes dados foram importados no arquivo de Nro. ECF: "
		#define STR0012 "Inserir Serviços"
		#define STR0013 "Serviço:"
		#define STR0014 "Registro Inválido"
		#define STR0015 "A viagem/serviço "
		#define STR0016 " talvez não exista cadastrado ou não adere à data, horário e sentido do bilhete."
		#define STR0017 "Verifique os cadastros de Horário e Viagem para esta Linha, sentido e horário."
		#define STR0018 "Inclusão/Atualização de Serviços"
		#define STR0019 "1=Ida"
		#define STR0020 "2=Volta"
		#define STR0021 "Imp. Lista"
		#define STR0022 "Confirmar"
		#define STR0023 "Cancelar"
	#endif
#endif
