#ifdef SPANISH
	#define STR0001 "Verificando Sistemas y Servicios estandar."
	#define STR0002 "Creando tabla de control de tiempo."
	#define STR0003 "Verificando estatus del JOB."
	#define STR0004 "Mantenimiento Handheld"
	#define STR0005 "S&istemas"
	#define STR0006 "&Tablas"
	#define STR0007 "Servicios"
	#define STR0008 "&Usuarios"
	#define STR0009 "&Grupo"
	#define STR0010 "&Control"
	#define STR0011 "&Auditor"
	#define STR0012 "&Estadisticas"
	#define STR0013 "Actualizar"
	#define STR0014 "&Salir"
	#define STR0015 "Handheld"
	#define STR0016 "Sistemas Handheld"
	#define STR0017 "Sistemas:"
	#define STR0018 "&Incluir"
	#define STR0019 "&Modificar"
	#define STR0020 "&Borrar"
	#define STR0021 "Desea borrar el sistema "
	#define STR0022 "Sistema Handheld"
	#define STR0023 "Archivo Sistemas Handheld"
	#define STR0024 "Codigo:"
	#define STR0025 "Descripcion:"
	#define STR0026 "Tabla Base:"
	#define STR0027 "&OK"
	#define STR0028 "&Anular"
	#define STR0029 "Informe un Codigo."
	#define STR0030 "Atencion"
	#define STR0031 "Codigo ya Existe"
	#define STR0032 "Mantenimiento Sistema("
	#define STR0033 "Tablas Handheld"
	#define STR0034 "Tablas:"
	#define STR0035 "1-Si"
	#define STR0036 "2-No"
	#define STR0037 "Desea borrar la tabla "
	#define STR0038 "Tabla Handheld"
	#define STR0039 "Mantenimiento Tabla("
	#define STR0040 "Archivo Tabelas Handheld"
	#define STR0041 "Alias:"
	#define STR0042 "Retorna"
	#define STR0043 "Generico:"
	#define STR0044 "Filtrar Empresa"
	#define STR0045 "Version:"
	#define STR0046 "Campo ID:"
	#define STR0047 "Compartida entre empresas"
	#define STR0048 "El campo ID indicado no esta registrado en el diccionario de datos."
	#define STR0049 "El campo ID debe rellenarse para tablas no genericas"
	#define STR0050 "No existe ninguna tabla registrada"
	#define STR0051 "Atencion"
	#define STR0052 "Servicios Handheld"
	#define STR0053 "Servicios:"
	#define STR0054 "1 - Handheld->Protheus"
	#define STR0055 "2 - Protheus->Handheld"
	#define STR0056 "1 - Individual"
	#define STR0057 "2 - Generico"
	#define STR0058 "Desea borrar el servico "
	#define STR0059 "Tablas"
	#define STR0060 "Archivo de Servicios Handheld"
	#define STR0061 "Funccion:"
	#define STR0062 "Tipo:"
	#define STR0063 "Codigo"
	#define STR0064 "Tabla"
	#define STR0065 "Alias"
	#define STR0066 "Servicio Existe"
	#define STR0067 "Informe una Funcion."
	#define STR0068 "Funcion no Encontrada en el Repositorio."
	#define STR0069 "Mantenimiento Servicio("
	#define STR0070 "Archivo Handheld"
	#define STR0071 "Usuarios:"
	#define STR0072 "1 - Palm OS"
	#define STR0073 "2 - Pocket PC/ARM"
	#define STR0074 "3 - Pocket PC/SH3"
	#define STR0075 "Esta opreracion borra al usuario y todos sus archivros en los grupos de Handheld. Confirma borrado del handheld "
	#define STR0076 "Mantenimiento Handheld("
	#define STR0077 "Archivo Handhelds"
	#define STR0078 "Numero de Serie:"
	#define STR0079 "Nombre Usuario:"
	#define STR0080 "Codigo Usuario:"
	#define STR0081 "Dispositivo:"
	#define STR0082 "Informe un Numero de Serie."
	#define STR0083 "Handheld ya Existe"
	#define STR0084 "Archivo Grupos de Handheld"
	#define STR0085 "Grupos:"
	#define STR0086 "1 - Minutos"
	#define STR0087 "2 - Horas"
	#define STR0088 "3 - Dias"
	#define STR0089 "Seleccione un grupo."
	#define STR0090 "¿Confima borrado del grupo?"
	#define STR0091 "Mantenimiento Grupo("
	#define STR0092 "Servicios"
	#define STR0093 "Archivo Grupos"
	#define STR0094 "Codigo:"
	#define STR0095 "Descripcion:"
	#define STR0096 "Sistema:"
	#define STR0097 "Empresa/Sucursal:"
	#define STR0098 "Frecuencia:"
	#define STR0099 "Script:"
	#define STR0100 "Sufijo:"
	#define STR0101 "Servicio"
	#define STR0102 "Descripcion"
	#define STR0103 "Nº Serie"
	#define STR0104 "Nombre"
	#define STR0105 "Codigo"
	#define STR0106 "&Rec. Base"
	#define STR0107 "Rec. &Todos"
	#define STR0108 "Espere..."
	#define STR0109 "Recreando la base para todos los vendedores."
	#define STR0110 "&Importacion"
	#define STR0111 "&Visualizar"
	#define STR0112 "No existe ningun sistema registrado"
	#define STR0113 "No existe ningun servicio registrado"
	#define STR0114 "1-Libre"
	#define STR0115 "2-Job"
	#define STR0116 "3-Handheld"
	#define STR0117 "4-Procesando"
	#define STR0118 "5-Bloqueado"
	#define STR0119 "6-Sinc. Parcial"
	#define STR0120 "No existe ningun handheld registrado"
	#define STR0121 "Codigo Base:"
	#define STR0122 "Grupo Existe"
	#define STR0123 "Handheld no relacionado a un codigo base. Por favor, verificar registros de Grupo vs. Handheld"
	#define STR0124 "Esta modificacion implica el borrado de la base de datos del usuario "
	#define STR0125 ", Numero de Serie "
	#define STR0126 "Si existieran informaciones no importadas al Protheus, estas se perderan."
	#define STR0127 "¿Desea continuar?"
	#define STR0128 "Borrar Base"
	#define STR0129 "Usuario "
	#define STR0130 " esta con el estatus "
	#define STR0131 ". La importacion no puede iniciarse."
	#define STR0132 "Esta rutina ejecuta los servicios de Importacion (Handheld -> Protheus) para el usuario  "
	#define STR0133 "Iniciar Importaciones"
	#define STR0134 "Importacion iniciada para "
	#define STR0135 "Cargando Logs...."
	#define STR0136 "0003 - Error en la Autenticacion del Usuario"
	#define STR0137 "1010 - Exito en la Importacion del Pedido"
	#define STR0138 "1011 - Error en la Importacion del Pedido"
	#define STR0139 "1020 - Exito en la Importacion de Cliente (Inclusion)"
	#define STR0140 "1021 - Exito en la Importacion de Cliente (Modificacion)"
	#define STR0141 "1022 - Error en la Importacion de Cliente"
	#define STR0142 "1030 - Exito en la Importacion de Contactos (Inclusion)"
	#define STR0143 "1031 - Exito en la Importacion de Contactos (Modificacion)"
	#define STR0144 "1032 - Error en la Importacion de Contactos"
	#define STR0145 "1040 - Exito en la Importacion de Mensaje"
	#define STR0146 "1041 - Error en la Importacion de Mensaje"
	#define STR0147 "1050 - Exito en la Importacion de Ocurrencias"
	#define STR0148 "1051 - Error en la l Importacion de Ocurrencia"
	#define STR0149 "2010 - Mantenimiento de Sistemas"
	#define STR0150 "2020 - Mantenimiento de Servicios"
	#define STR0151 "2030 - Mantenimiento de Usuarios"
	#define STR0152 "2040 - Mantenimiento de Tablas"
	#define STR0153 "2050 - Mantenimiento de Grupos"
	#define STR0154 "2060 - Borra base de usuario"
	#define STR0155 "2070 - Creacion de la base del usuario"
	#define STR0156 "2080 - Modificacion de Estatus del Usuario"
	#define STR0157 "2090 - Inicio de importaciones manualmente"
	#define STR0158 "Conexiones"
	#define STR0159 "Logs"
	#define STR0160 "Disparadores"
	#define STR0161 "Estadisticas"
	#define STR0162 "Control Handheld"
	#define STR0163 "Orden:"
	#define STR0164 "Filtro"
	#define STR0165 "Codigo de Operacion:"
	#define STR0166 "&Cerrar"
	#define STR0167 "Grupo"
	#define STR0168 "Numero de Serie"
	#define STR0169 "Cod. Base"
	#define STR0170 "Estatus"
	#define STR0171 "Orden"
	#define STR0172 "Fecha"
	#define STR0173 "Hora 1"
	#define STR0174 "Operacion 1"
	#define STR0175 "Hora 2"
	#define STR0176 "Operacion 2"
	#define STR0177 "Observacion"
	#define STR0178 "Archivo"
	#define STR0179 "Hora"
	#define STR0180 "Empresa"
	#define STR0181 "Sucursal"
	#define STR0182 "Nombre de la Empresa"
	#define STR0183 "Actualiza Grafico"
	#define STR0184 "Nº Serie"
	#define STR0185 "Operacion"
	#define STR0186 "Estadistica"
	#define STR0187 "Total"
	#define STR0188 "Completas"
	#define STR0189 "Incompletas"
	#define STR0190 "Importaciones"
	#define STR0191 "Pedidos"
	#define STR0192 "Con Exito"
	#define STR0193 "Con Error"
	#define STR0194 "Ocurrencias"
	#define STR0195 "Clientes"
	#define STR0196 "Contactos"
	#define STR0197 "Mensajes"
	#define STR0198 "Modificacion de Estatus"
	#define STR0199 "Estatus:"
	#define STR0200 "El estatus "
	#define STR0201 " no puede seleccionarse manualmente."
	#define STR0202 "Handheld Estatus"
	#define STR0203 "Libre"
	#define STR0204 "La modificacion del Estatus del vendedor de "
	#define STR0205 " a "
	#define STR0206 "Base del usuario borrada - "
	#define STR0207 " implica la recreacion de las informaciones del handheld seleccionado, para todas las empresas y sucursales. "
	#define STR0208 "Estatus modificado de "
	#define STR0209 "JOB se esta ejecutando."
	#define STR0210 "Existen "
	#define STR0211 " handhelds sin operacion."
	#define STR0212 " handhelds actualizando archivos."
	#define STR0213 " handhelds bloqueados. ¡Verificar!"
	#define STR0214 " handhelds en sincronismo."
	#define STR0215 " handhelds procesando servicios de importacion."
	#define STR0216 "JOB no se esta ejecutando."
	#define STR0217 "Archivo de script no encontrado en el camino "
	#define STR0218 "Vendedor"
	#define STR0219 "Rutas"
	#define STR0220 "Productos"
	#define STR0221 "Transportadoras"
	#define STR0222 "Condiciones de Pago"
	#define STR0223 "Pedidos de Venta"
	#define STR0224 "Configuraciones"
	#define STR0225 "Importacion de Clientes"
	#define STR0226 "Importacion de Pedidos de Venta"
	#define STR0227 "Importacion de Contactos"
	#define STR0228 "Importacion de Mensajes"
	#define STR0229 "Grupo de Productos"
	#define STR0230 "Stock de Productos"
	#define STR0231 "Lista de precios"
	#define STR0232 "Facturas de Credito"
	#define STR0233 "Tipos de Pago"
	#define STR0234 "Reglas de Descuento"
	#define STR0235 "Reglas de Bonificacion"
	#define STR0236 "Reglas de Negocio"
	#define STR0237 "Proveed vs. Prod"
	#define STR0238 "Categorias"
	#define STR0239 "Metas"
	#define STR0240 "Procedimiento"
	#define STR0241 "Titulos"
	#define STR0242 "Consumo"
	#define STR0243 "Inventario"
	#define STR0244 "Atencion"
	#define STR0245 "Grupos"
	#define STR0246 "Encab. Lista de Precio"
	#define STR0247 "It. Lista de Precio"
	#define STR0248 "Condicion"
	#define STR0249 "Tablas Genericas"
	#define STR0250 "Encab. Pedidos de Venta"
	#define STR0251 "It. Pedidos de Venta"
	#define STR0252 "Apuntes"
	#define STR0253 "Encab. Regla de Descuentos"
	#define STR0254 "It. Regla de Descuentos"
	#define STR0255 "Encab. Regla de Bonificacion"
	#define STR0256 "It. Regla de Bonificacion"
	#define STR0257 "Encab. Regla de Negocios"
	#define STR0258 "It. Regla de Negocio"
	#define STR0259 "Categ vs. Prod"
	#define STR0260 "Esta modificacion implica el borrado de la base de datos de los usuarios pertenecientes a este grupo. "
	#define STR0261 "Importacion de Apuntes"
	#define STR0262 "Ejecutando servicio generico"
	#define STR0263 " handheld(s) con sincronismo parcial."
	#define STR0264 "Marca Todos"
	#define STR0265 "Invertir Seleccion"
	#define STR0266 "Aplicar"
	#define STR0267 "Informe la Descripcion"
	#define STR0268 "&Wizard"
	#define STR0269 "Asitente de configuracion del SFA."
	#define STR0270 "Esta rutina tiene como finalidad auxiliarlo en la configuracion inicial de los Procesos de Retaguardia del SFA vs. Protheus."
	#define STR0271 "Configuracion Inicial de los Servicios"
	#define STR0272 "Marcar Todos"
	#define STR0273 "Desmarcar Todos"
	#define STR0274 "Servicios Obligatorios"
	#define STR0275 "Servicios Opcionales seleccionados"
	#define STR0276 "Servicios Opcionales no seleccionados"
	#define STR0277 "Definicion de Servicio"
	#define STR0278 "Servicio - Proceso de actualizacion (importacion o "
	#define STR0279 "exportacion) de las informaciones de las Tablas del SFA y"
	#define STR0280 "sus respectivas tablas equivalentes en el Protheus."
	#define STR0281 'Ej.: El servicio "Pedido de Venta" actualiza las'
	#define STR0282 "tablas de encabezados de Pedidos de Venta y"
	#define STR0283 "Items de Pedidos de Venta con las informaciones"
	#define STR0284 "de sus tablas equivalentes en el Protheus."
	#define STR0285 "Configuracion Inicial de los Parametros"
	#define STR0286 "Configure los parametros del Sistema utilizados por el SFA."
	#define STR0287 "Parametros"
	#define STR0288 "Editar"
	#define STR0289 "Confirmar"
	#define STR0290 "El archivo de sistemas se utiliza para  identificar los sistemas que pueden utilizarse en la integracion con el Protheus."
	#define STR0291 "El  archivo  de  tablas  graba  todas  las  tablas  utilizadas  en el  mobile, conteniendo informaciones sobre su funcionamiento."
	#define STR0292 "Los servicios son las  funciones  responsables por la diplicacion de la tabla, tanto del estandar al duplicado como al contrario."
	#define STR0293 "El  archivo  de  usuarios  guarda  las  informaciones  de  cada  Hand-Held  registrado,  cuya clave principal es el numero de serie del equipo."
	#define STR0294 "En este  archivo  es  posible  crear  grupos  de  vendedores  separados  y  diferentes  entre  si. Tambien se efectua la relacion de los grupos con los servicios que se utilizaran."
#else
	#ifdef ENGLISH
		#define STR0001 "Checking Systems and Standard Services."
		#define STR0002 "Creating table of time control."
		#define STR0003 "Checking the JOB status."
		#define STR0004 "Handheld Maintenance."
		#define STR0005 "S&ystems"
		#define STR0006 "&Tables"
		#define STR0007 "Services"
		#define STR0008 "&Users"
		#define STR0009 "&Group"
		#define STR0010 "&Control"
		#define STR0011 "&Auditor"
		#define STR0012 "&Statistics"
		#define STR0013 "Update"
		#define STR0014 "&Quit"
		#define STR0015 "Handheld"
		#define STR0016 "Handheld Systems"
		#define STR0017 "Systems:"
		#define STR0018 "&Add"
		#define STR0019 "&Edit"
		#define STR0020 "&Delete"
		#define STR0021 "Do you want do delete the system "
		#define STR0022 "Handheld System"
		#define STR0023 "Handheld System Register"
		#define STR0024 "Code:"
		#define STR0025 "Description:"
		#define STR0026 "Base Table:"
		#define STR0027 "&OK"
		#define STR0028 "&Cancel"
		#define STR0029 "Enter a Code."
		#define STR0030 "Attention"
		#define STR0031 "This code already exists."
		#define STR0032 "System Maintenance ("
		#define STR0033 "Handheld Tables"
		#define STR0034 "Tables:"
		#define STR0035 "1-Yes"
		#define STR0036 "2-No"
		#define STR0037 "Do you want to delete the table "
		#define STR0038 "Handheld Table"
		#define STR0039 "Maintenance Table ("
		#define STR0040 "Handheld Tables Register"
		#define STR0041 "Alias:"
		#define STR0042 "Go back"
		#define STR0043 "Generic:"
		#define STR0044 "Filter Company:"
		#define STR0045 "Version:"
		#define STR0046 "ID Field:"
		#define STR0047 "Shared between companies"
		#define STR0048 "The ID field indicated is not registered in data dictionary."
		#define STR0049 "The ID field must be filled in for nongeneric tables."
		#define STR0050 "There is no table registered."
		#define STR0051 "Attention"
		#define STR0052 "Handheld Services"
		#define STR0053 "Services:"
		#define STR0054 "1 - Handheld->Protheus"
		#define STR0055 "2 - Protheus->Handheld"
		#define STR0056 "1 - Individual"
		#define STR0057 "2 - Generic"
		#define STR0058 "Do you want to delete the service "
		#define STR0059 "Tables"
		#define STR0060 "Handheld Services Register"
		#define STR0061 "Function:"
		#define STR0062 "Type:"
		#define STR0063 "Code"
		#define STR0064 "Table"
		#define STR0065 "Alias"
		#define STR0066 "This service already exists."
		#define STR0067 "Enter a Function."
		#define STR0068 "This Function was not found in the Repository."
		#define STR0069 "Maintenance Service("
		#define STR0070 "Handheld Register"
		#define STR0071 "Users:"
		#define STR0072 "1 - Palm OS"
		#define STR0073 "2 - Pocket PC/ARM"
		#define STR0074 "3 - Pocket PC/SH3"
		#define STR0075 "This operation deletes the user and all his registers in Handheld groups. Confirm Handheld exclusion? "
		#define STR0076 "Maintenance Handheld("
		#define STR0077 "Handheld Register"
		#define STR0078 "Series Number:"
		#define STR0079 "User Name:"
		#define STR0080 "User Code:"
		#define STR0081 "Device:"
		#define STR0082 "Enter a Series Number:"
		#define STR0083 "This Handheld already exists."
		#define STR0084 "Handheld Group Register"
		#define STR0085 "Groups:"
		#define STR0086 "1 - Minutes"
		#define STR0087 "2 - Hours"
		#define STR0088 "3 - Days"
		#define STR0089 "Select a group."
		#define STR0090 "Confirm the group exclusion?"
		#define STR0091 "Maintenance Group("
		#define STR0092 "Services"
		#define STR0093 "Group Register"
		#define STR0094 "Code:"
		#define STR0095 "Description:"
		#define STR0096 "System:"
		#define STR0097 "Company/Branch:"
		#define STR0098 "Attendance:"
		#define STR0099 "Script:"
		#define STR0100 "Suffix:"
		#define STR0101 "Service"
		#define STR0102 "Description"
		#define STR0103 "Series Nr."
		#define STR0104 "Name"
		#define STR0105 "Code"
		#define STR0106 "&Rec. Base"
		#define STR0107 "Rec. &All"
		#define STR0108 "Please, wait..."
		#define STR0109 "Recreating the base to all salesmen."
		#define STR0110 "&Import"
		#define STR0111 "&View"
		#define STR0112 "There is no system registered."
		#define STR0113 "There is no service registered."
		#define STR0114 "1-Free"
		#define STR0115 "2-Job"
		#define STR0116 "3-Handheld"
		#define STR0117 "4-Processing"
		#define STR0118 "5-Blocked"
		#define STR0119 "6-Sinc. Partial"
		#define STR0120 "There is no handheld registered."
		#define STR0121 "Base Code Base:"
		#define STR0122 "This Group already exists."
		#define STR0123 "This Handheld is not related to a base code. Please check Group vs. Handheld registers."
		#define STR0124 "This change causes the exclusion of the user's database. "
		#define STR0125 ", Series Number "
		#define STR0126 "If there are information that were not imported to Protheus, they will be lost."
		#define STR0127 "Do you want to continue?"
		#define STR0128 "Delete Base"
		#define STR0129 "User's "
		#define STR0130 " status is "
		#define STR0131 ". Import cannot be started."
		#define STR0132 "This routine runs Import services (Handheld -> Protheus) for the user  "
		#define STR0133 "Start Imports"
		#define STR0134 "Import started for "
		#define STR0135 "Loading Logs..."
		#define STR0136 "0003 - Error in Authentication of User"
		#define STR0137 "1010 - Success in Import of Order"
		#define STR0138 "1011 - Error in Import of Order"
		#define STR0139 "1020 - Success in Import of Customer (Inclusion)"
		#define STR0140 "1021 - Success in Import of Customer (Change)"
		#define STR0141 "1022 - Error in Import of Customer"
		#define STR0142 "1030 - Success in Import of Contacts (Inclusion)"
		#define STR0143 "1031 - Success in Import of Contacts (Change)"
		#define STR0144 "1032 - Error in Import of Contacts"
		#define STR0145 "1040 - Success in Import of Message"
		#define STR0146 "1041 - Error in Import of Message"
		#define STR0147 "1050 - Success in Import of Occurrences"
		#define STR0148 "1051 - Error in Import of Occurrence"
		#define STR0149 "2010 - Maintenance of Systems"
		#define STR0150 "2020 - Maintenance of Services"
		#define STR0151 "2030 - Maintenance of Users"
		#define STR0152 "2040 - Maintenance of Tables"
		#define STR0153 "2050 - Maintenance of Groups"
		#define STR0154 "2060 - Delete User Base"
		#define STR0155 "2070 - Creation of User Base"
		#define STR0156 "2080 - Change in User Status"
		#define STR0157 "2090 - Imports started manually"
		#define STR0158 "Connections"
		#define STR0159 "Logs"
		#define STR0160 "Triggers"
		#define STR0161 "Statistics"
		#define STR0162 "Handheld Control"
		#define STR0163 "Order:"
		#define STR0164 "Filter"
		#define STR0165 "Operation Code:"
		#define STR0166 "&Close"
		#define STR0167 "Group"
		#define STR0168 "Series Number"
		#define STR0169 "Code Base"
		#define STR0170 "Status"
		#define STR0171 "Order"
		#define STR0172 "Date"
		#define STR0173 "Hour 1"
		#define STR0174 "Operation 1"
		#define STR0175 "Hour 2"
		#define STR0176 "Operation 2"
		#define STR0177 "Observation"
		#define STR0178 "File"
		#define STR0179 "Hour"
		#define STR0180 "Company"
		#define STR0181 "Branch"
		#define STR0182 "Company Name"
		#define STR0183 "Update Chart"
		#define STR0184 "Series  Number"
		#define STR0185 "Operation"
		#define STR0186 "Statistics"
		#define STR0187 "Total"
		#define STR0188 "Complete"
		#define STR0189 "Incomplete"
		#define STR0190 "Imports"
		#define STR0191 "Orders"
		#define STR0192 "With success"
		#define STR0193 "With error"
		#define STR0194 "Occurrences"
		#define STR0195 "Customers"
		#define STR0196 "Contacts"
		#define STR0197 "Messages"
		#define STR0198 "Status Change"
		#define STR0199 "Status:"
		#define STR0200 "The status "
		#define STR0201 " cannot be selected manually."
		#define STR0202 "Handheld Status"
		#define STR0203 "Free"
		#define STR0204 "The change of salesman status from "
		#define STR0205 " to "
		#define STR0206 "User base deleted - "
		#define STR0207 " causes the recreation of information from the selected handheld, for all companies and branches. "
		#define STR0208 "Status changed from "
		#define STR0209 "The JOB is being executed."
		#define STR0210 "There are "
		#define STR0211 " handhelds with no operation."
		#define STR0212 " handhelds updating filed."
		#define STR0213 " handhelds blocked. Check!"
		#define STR0214 " handhelds in synchronism."
		#define STR0215 " handhelds processing import services."
		#define STR0216 "The JOB is not being executed."
		#define STR0217 "Script file not found in path "
		#define STR0218 "Salesman"
		#define STR0219 "Routes"
		#define STR0220 "Products"
		#define STR0221 "Carriers"
		#define STR0222 "Payment Terms"
		#define STR0223 "Sales Orders"
		#define STR0224 "Configurations"
		#define STR0225 "Customer Import"
		#define STR0226 "Purchase Order Import"
		#define STR0227 "Contact Import"
		#define STR0228 "Message Import"
		#define STR0229 "Product Group"
		#define STR0230 "Product Stock"
		#define STR0231 "Price List"
		#define STR0232 "Trade Note"
		#define STR0233 "Payment Types"
		#define STR0234 "Discount Rules"
		#define STR0235 "Bonus Rules"
		#define STR0236 "Business Rules"
		#define STR0237 "Sup x Prod"
		#define STR0238 "Categories"
		#define STR0239 "Goals"
		#define STR0240 "Schedule"
		#define STR0241 "Bills"
		#define STR0242 "Consumption"
		#define STR0243 "Inventory"
		#define STR0244 "Service"
		#define STR0245 "Groups"
		#define STR0246 "Cab. Price List"
		#define STR0247 "It. Price List"
		#define STR0248 "Condition"
		#define STR0249 "Generic Tables"
		#define STR0250 "Cab. Sales Orders"
		#define STR0251 "It. Sales Orders"
		#define STR0252 "Annotations"
		#define STR0253 "Cab. Discount Rule"
		#define STR0254 "It. Discount Rule"
		#define STR0255 "Cab. Bonus Rule "
		#define STR0256 "It. Bonus Rule "
		#define STR0257 "Cab. Business Rule"
		#define STR0258 "It. Business Rule"
		#define STR0259 "Categ x Prod"
		#define STR0260 "This change causes the exclusion of database of users who belong to this group. "
		#define STR0261 "Annotation Import"
		#define STR0262 "Performing generic service"
		#define STR0263 " handheld(s) partial synchronism."
		#define STR0264 "Check All"
		#define STR0265 "Invert Selection"
		#define STR0266 "Apply"
		#define STR0267 "Enter the Description"
		#define STR0268 "&Wizard"
		#define STR0269 "SFA Configuration Wizard."
		#define STR0270 "This routine will help you in the initial configuration of Back Office Processes of SFA x Protheus."
		#define STR0271 "Initial Service Configuration"
		#define STR0272 "Check All"
		#define STR0273 "Uncheck All"
		#define STR0274 "Mandatory Services"
		#define STR0275 "Optional Services selected"
		#define STR0276 "Optional Services not selected"
		#define STR0277 "Service Definition"
		#define STR0278 "Service - Update Process (import or  "
		#define STR0279 "export) of information of SFA Tables and"
		#define STR0280 "its respective tables equivalent in Protheus."
		#define STR0281 'Ex.: The service "Sales Order" updates '
		#define STR0282 "tables of  Sales Order headers and "
		#define STR0283 "Items of Sales Orders with information"
		#define STR0284 "of its tables equivalent in Protheus."
		#define STR0285 "Initial Configuration of Parameters"
		#define STR0286 "Configure the System parameters that are used by SFA."
		#define STR0287 "Parameters"
		#define STR0288 "Edit"
		#define STR0289 "Confirm"
		#define STR0290 "The system register is used to identify the systems that can be used in integration with Protheus."
		#define STR0291 "The table register stores all tables used in the mobile, containing information about its functioning."
		#define STR0292 "The services are responsible for the mirroring of the table, from the standard to the mirror and vice versa."
		#define STR0293 "The user register stores information of each Handheld registered, whose main key is the equipment series number."
		#define STR0294 "In this register you can create groups of salesmen separated and different from each other. Here, the relationship of groups with the services to be used is also made."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "A verificar Sistemas e Serviços padrão.", "Verificando Sistemas e Serviços padrão." )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "A criar tabela de controlo de tempo.", "Criando tabela de controle de tempo." )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "A verificar estado do JOB.", "Verificando status do JOB." )
		#define STR0004 "Manutenção Handheld"
		#define STR0005 "S&istemas"
		#define STR0006 "&Tabelas"
		#define STR0007 "Serviços"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "&Utilizadores", "&Usuários" )
		#define STR0009 "&Grupo"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "&Controlo", "&Controle" )
		#define STR0011 "&Auditor"
		#define STR0012 "&Estatisticas"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Actualizar", "Atualizar" )
		#define STR0014 "&Sair"
		#define STR0015 "Handheld"
		#define STR0016 "Sistemas Handheld"
		#define STR0017 "Sistemas:"
		#define STR0018 "&Incluir"
		#define STR0019 "&Alterar"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "&Eliminar", "&Excluir" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Deseja eliminar o sistema ", "Deseja excluir o sistema " )
		#define STR0022 "Sistema Handheld"
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Registo de Sistemas Handheld", "Cadastro de Sistemas Handheld" )
		#define STR0024 "Código:"
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Descrição:", "Descricao:" )
		#define STR0026 "Tabela Base:"
		#define STR0027 "&OK"
		#define STR0028 "&Cancelar"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Informe um Código.", "Informe um Codigo." )
		#define STR0030 "Atenção"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Código já Existe", "Codigo já Existe" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Manutenção Sistema(", "Manutencao Sistema(" )
		#define STR0033 "Tabelas Handheld"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "TABELAS", "Tabelas:" )
		#define STR0035 "1-Sim"
		#define STR0036 "2-Não"
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Deseja eliminar a tabela ", "Deseja excluir a tabela " )
		#define STR0038 "Tabela Handheld"
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Manutenção Tabela(", "Manutencao Tabela(" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Registo de Tabelas Handheld", "Cadastro de Tabelas Handheld" )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Aliás:", "Alias:" )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Devolve", "Retorna" )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Genérico:", "Generico:" )
		#define STR0044 "Filtrar Empresa"
		#define STR0045 "Versão:"
		#define STR0046 "Campo ID:"
		#define STR0047 "Compartilhada entre empresas"
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "O campo ID indicado não está registado no dicionário de dados.", "O campo ID indicado não está cadastrado no dicionário de dados." )
		#define STR0049 "O campo ID deve ser preenchido para tabelas não genéricas"
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Nao existe nenhuma tabela registada", "Nao existe nenhuma tabela cadastrado" )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Atenção", "Atencao" )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Serviços Handheld", "Servicos Handheld" )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Serviços:", "Servicos:" )
		#define STR0054 "1 - Handheld->Protheus"
		#define STR0055 "2 - Protheus->Handheld"
		#define STR0056 "1 - Individual"
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "2 - Genérico", "2 - Generico" )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Deseja eliminar o serviço ", "Deseja excluir o servico " )
		#define STR0059 "Tabelas"
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Registo de Serviços Handheld", "Cadastro de Serviços Handheld" )
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Função:", "Funcao:" )
		#define STR0062 "Tipo:"
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "Código", "Codigo" )
		#define STR0064 "Tabela"
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Aliás:", "Alias" )
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "Serviço já Existe", "Servico ja Existe" )
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Informe uma Função.", "Informe uma Funcao." )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Função não Encontrada no Repositório.", "Funcao nao Encontrada no Repositorio." )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Manutenção Serviço(", "Manutencao Servico(" )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Registo de Handheld", "Cadastro de Handheld" )
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Utilizadores:", "Usuarios:" )
		#define STR0072 "1 - Palm OS"
		#define STR0073 "2 - Pocket PC/ARM"
		#define STR0074 "3 - Pocket PC/SH3"
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Esta operação exclui o utilizador e todos os seus registos nos grupos de Handheld. Confirma exclusão do handheld ", "Está opreração exclui o usuário e todos os seus cadastros nos grupos de Handheld. Confirma exclusão do handheld " )
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Manutenção Handheld(", "Manutencao Handheld(" )
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "Registo de Handhelds", "Cadastro de Handhelds" )
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "Número de Série:", "Numero de Serie:" )
		#define STR0079 If( cPaisLoc $ "ANG|PTG", "Nome Utilizador:", "Nome Usuário:" )
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "Código Utilizador:", "Código Usuário:" )
		#define STR0081 "Dispositivo:"
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Informe um Número de Série.", "Informe um Numero de Serie." )
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "Handheld já Existe", "Handheld ja Existe" )
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Registo de grupos de Handheld", "Cadastro de Grupos de Handheld" )
		#define STR0085 "Grupos:"
		#define STR0086 "1 - Minutos"
		#define STR0087 "2 - Horas"
		#define STR0088 "3 - Dias"
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "Seleccione um grupo.", "Selecione um grupo." )
		#define STR0090 "Confima exclusão do grupo ?"
		#define STR0091 If( cPaisLoc $ "ANG|PTG", "Manutenção Grupo(", "Manutencao Grupo(" )
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "Serviços", "Servicos" )
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "Registo de Grupos", "Cadastro de Grupos" )
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Código:", "Codigo:" )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Descrição:", "Descriçao:" )
		#define STR0096 "Sistema:"
		#define STR0097 "Empresa/Filial:"
		#define STR0098 "Frequência:"
		#define STR0099 "Script:"
		#define STR0100 "Sufixo:"
		#define STR0101 "Serviço"
		#define STR0102 If( cPaisLoc $ "ANG|PTG", "Descrição", "Descricao" )
		#define STR0103 If( cPaisLoc $ "ANG|PTG", "No Série", "No Serie" )
		#define STR0104 "Nome"
		#define STR0105 "Código"
		#define STR0106 "&Rec. Base"
		#define STR0107 "Rec. &Todos"
		#define STR0108 "Aguarde..."
		#define STR0109 If( cPaisLoc $ "ANG|PTG", "A recriar a base para todos os vendedores.", "Recriando a base para todos os vendedores." )
		#define STR0110 "&Importação"
		#define STR0111 "&Visualizar"
		#define STR0112 If( cPaisLoc $ "ANG|PTG", "Não existe nenhum sistema registado", "Nao existe nenhum sistema cadastrado" )
		#define STR0113 If( cPaisLoc $ "ANG|PTG", "Não existe nenhum serviço registado", "Nao existe nenhum serviço cadastrado" )
		#define STR0114 "1-Livre"
		#define STR0115 "2-Job"
		#define STR0116 "3-Handheld"
		#define STR0117 If( cPaisLoc $ "ANG|PTG", "4-A processar", "4-Processando" )
		#define STR0118 "5-Bloqueado"
		#define STR0119 If( cPaisLoc $ "ANG|PTG", "6-Sinc Parcial", "6-Sinc. Parcial" )
		#define STR0120 If( cPaisLoc $ "ANG|PTG", "Não existe nenhum serviço registado", "Nao existe nenhum handheld cadastrado" )
		#define STR0121 "Código Base:"
		#define STR0122 If( cPaisLoc $ "ANG|PTG", "Grupo já Existe", "Grupo ja Existe" )
		#define STR0123 If( cPaisLoc $ "ANG|PTG", "Handheld não relacionado a um código base. Favor verificar registos de Grupo x Handheld", "Handheld não relacionado a um código base. Favor verificar cadastros de Grupo x Handheld" )
		#define STR0124 If( cPaisLoc $ "ANG|PTG", "Esta alteração implica na exclusão da base de dados do utilizador ", "Esta alteração implica na exclusão da base de dados do usuário " )
		#define STR0125 If( cPaisLoc $ "ANG|PTG", ", Número de série ", ", Numero de Serie " )
		#define STR0126 If( cPaisLoc $ "ANG|PTG", "Caso existam informações não importadas ao Protheus estas serão perdidas.", "Caso existam informações não importadas para o Protheus estas serão perdidas." )
		#define STR0127 If( cPaisLoc $ "ANG|PTG", "Deseja continuar?", "Deseja continuar ?" )
		#define STR0128 If( cPaisLoc $ "ANG|PTG", "Eliminar Base", "Excluir Base" )
		#define STR0129 If( cPaisLoc $ "ANG|PTG", "Utilizador ", "Usuario " )
		#define STR0130 If( cPaisLoc $ "ANG|PTG", " está com o estado ", " está com o status " )
		#define STR0131 ". A importação não pode ser iniciada."
		#define STR0132 If( cPaisLoc $ "ANG|PTG", "Esta rotina executa os serviços de Importação (Handheld -> Protheus) para o utilizador  ", "Esta rotina executa os serviços de Importação (Handheld -> Protheus) para o usuário  " )
		#define STR0133 "Iniciar Importações"
		#define STR0134 If( cPaisLoc $ "ANG|PTG", "Importação iniciada para ", "Importacao iniciada para " )
		#define STR0135 If( cPaisLoc $ "ANG|PTG", "A carregar logs...", "Carregando Logs...." )
		#define STR0136 If( cPaisLoc $ "ANG|PTG", "0003 - Erro na Autenticação do Utilizador", "0003 - Erro na Autenticacao do Usuario" )
		#define STR0137 "1010 - Sucesso na Importação do Pedido"
		#define STR0138 "1011 - Erro na Importação do Pedido"
		#define STR0139 If( cPaisLoc $ "ANG|PTG", "1020 - Sucesso na Importação de Cliente (Inclusão)", "1020 - Sucesso na Importação de Cliente (Inclusao)" )
		#define STR0140 If( cPaisLoc $ "ANG|PTG", "1021 - Sucesso na Importação de Cliente (Alteração)", "1021 - Sucesso na Importação de Cliente (Alteracao)" )
		#define STR0141 "1022 - Erro na Importação de Cliente"
		#define STR0142 If( cPaisLoc $ "ANG|PTG", "1030 - Sucesso na Importação de Contactos (Inclusão)", "1030 - Sucesso na Importação de Contatos (Inclusao)" )
		#define STR0143 If( cPaisLoc $ "ANG|PTG", "1031 - Sucesso na Importação de Contactos (Alteração)", "1031 - Sucesso na Importação de Contatos (Alteracao)" )
		#define STR0144 If( cPaisLoc $ "ANG|PTG", "1032 - Erro na Importação de Contactos", "1032 - Erro na Importação de Contatos" )
		#define STR0145 "1040 - Sucesso na Importação de Mensagem"
		#define STR0146 "1041 - Erro na Importação de Mensagem"
		#define STR0147 If( cPaisLoc $ "ANG|PTG", "1050 - Sucesso na Importação de Ocorrências", "1050 - Sucesso na Importação de Ocorrencias" )
		#define STR0148 If( cPaisLoc $ "ANG|PTG", "1051 - Erro na Importação de Ocorrências", "1051 - Erro na Importação de Ocorrencia" )
		#define STR0149 If( cPaisLoc $ "ANG|PTG", "2010 - Manutenção de Sistemas", "2010 - Manutencao de Sistemas" )
		#define STR0150 If( cPaisLoc $ "ANG|PTG", "2020 - Manutenção de Serviços", "2020 - Manutencao de Servicos" )
		#define STR0151 If( cPaisLoc $ "ANG|PTG", "2030 - Manutenção de Utilizadores", "2030 - Manutencao de Usuarios" )
		#define STR0152 If( cPaisLoc $ "ANG|PTG", "2040 - Manutenção de Tabelas", "2040 - Manutencao de Tabelas" )
		#define STR0153 If( cPaisLoc $ "ANG|PTG", "2050 - Manutenção de Grupos", "2050 - Manutencao de Grupos" )
		#define STR0154 If( cPaisLoc $ "ANG|PTG", "2060 - Apaga base de utilizador", "2060 - Apaga base de usuario" )
		#define STR0155 If( cPaisLoc $ "ANG|PTG", "2070 - Criação da base do utilizador", "2070 - Criacao da base do usuario" )
		#define STR0156 If( cPaisLoc $ "ANG|PTG", "2080 - Alteração de Estado do Utilizador", "2080 - Alteração de Status do Usuario" )
		#define STR0157 "2090 - Iniciado importações manualmente"
		#define STR0158 "Conexões"
		#define STR0159 "Logs"
		#define STR0160 "Gatilhos"
		#define STR0161 If( cPaisLoc $ "ANG|PTG", "Estatísticas", "Estatisticas" )
		#define STR0162 If( cPaisLoc $ "ANG|PTG", "Controlo Handheld", "Controle Handheld" )
		#define STR0163 "Ordem:"
		#define STR0164 "Filtro"
		#define STR0165 "Código de Operação:"
		#define STR0166 "&Fechar"
		#define STR0167 "Grupo"
		#define STR0168 If( cPaisLoc $ "ANG|PTG", "Número de Série", "Numero de Serie" )
		#define STR0169 If( cPaisLoc $ "ANG|PTG", "Cód. Base", "Cod. Base" )
		#define STR0170 If( cPaisLoc $ "ANG|PTG", "Estado", "Status" )
		#define STR0171 "Ordem"
		#define STR0172 "Data"
		#define STR0173 "Hora 1"
		#define STR0174 If( cPaisLoc $ "ANG|PTG", "Operação 1", "Operacao 1" )
		#define STR0175 "Hora 2"
		#define STR0176 If( cPaisLoc $ "ANG|PTG", "Operação 2", "Operacao 2" )
		#define STR0177 If( cPaisLoc $ "ANG|PTG", "Observação", "Observacao" )
		#define STR0178 If( cPaisLoc $ "ANG|PTG", "Ficheiro", "Arquivo" )
		#define STR0179 "Hora"
		#define STR0180 "Empresa"
		#define STR0181 "Filial"
		#define STR0182 "Nome da Empresa"
		#define STR0183 If( cPaisLoc $ "ANG|PTG", "Actualiza Gráfico", "Atualiza Gráfico" )
		#define STR0184 If( cPaisLoc $ "ANG|PTG", "Núm. Série", "Num. Série" )
		#define STR0185 "Operação"
		#define STR0186 If( cPaisLoc $ "ANG|PTG", "Estatística", "Estatistica" )
		#define STR0187 "Total"
		#define STR0188 "Completas"
		#define STR0189 "Incompletas"
		#define STR0190 "Importações"
		#define STR0191 "Pedidos"
		#define STR0192 "Com Sucesso"
		#define STR0193 "Com Erro"
		#define STR0194 If( cPaisLoc $ "ANG|PTG", "Ocorrências", "Ocorrencias" )
		#define STR0195 "Clientes"
		#define STR0196 If( cPaisLoc $ "ANG|PTG", "Contactos", "Contatos" )
		#define STR0197 "Mensagens"
		#define STR0198 If( cPaisLoc $ "ANG|PTG", "Alteração de Estado", "Alteraçao de Status" )
		#define STR0199 If( cPaisLoc $ "ANG|PTG", "Estado:", "Status:" )
		#define STR0200 If( cPaisLoc $ "ANG|PTG", "O estado ", "O status " )
		#define STR0201 If( cPaisLoc $ "ANG|PTG", " não pode ser seleccionado manualmente.", " não pode ser selecionado manualmente." )
		#define STR0202 If( cPaisLoc $ "ANG|PTG", "Handheld Estado", "Handheld Status" )
		#define STR0203 "Livre"
		#define STR0204 If( cPaisLoc $ "ANG|PTG", "A alteração do estado do vendedor de ", "A alteração do Status do vendedor de " )
		#define STR0205 " para "
		#define STR0206 If( cPaisLoc $ "ANG|PTG", "Base do utilizador apagada - ", "Base do usuario apagada - " )
		#define STR0207 If( cPaisLoc $ "ANG|PTG", " implica na recriação das informações do handheld seleccionado, para todas as empresas e filiais. ", " implica na recriação das informações do handheld selecionado, para todas as empresas e filiais. " )
		#define STR0208 If( cPaisLoc $ "ANG|PTG", "Estado alterado de ", "Status alterado de " )
		#define STR0209 If( cPaisLoc $ "ANG|PTG", "JOB está a ser executado.", "JOB está sendo executado." )
		#define STR0210 "Existem "
		#define STR0211 " handhelds sem operação."
		#define STR0212 If( cPaisLoc $ "ANG|PTG", " handhelds a actualizar os ficheiros.", " handhelds atualizando os arquivos." )
		#define STR0213 If( cPaisLoc $ "ANG|PTG", " handhelds bloqueados. Verificar!", " handhelds bloqueados. Verificar !!!" )
		#define STR0214 " handhelds em sincronismo."
		#define STR0215 If( cPaisLoc $ "ANG|PTG", " handhelds a processar serviços de importação.", " handhelds processando serviços de importação." )
		#define STR0216 If( cPaisLoc $ "ANG|PTG", "JOB está a ser executado.", "JOB não está sendo executado." )
		#define STR0217 If( cPaisLoc $ "ANG|PTG", "Ficheiro de script não encontrado no caminho ", "Arquivo de script não encontrado no caminho " )
		#define STR0218 "Vendedor"
		#define STR0219 "Rotas"
		#define STR0220 If( cPaisLoc $ "ANG|PTG", "Artigos", "Produtos" )
		#define STR0221 "Transportadoras"
		#define STR0222 "Condições de Pagamento"
		#define STR0223 "Pedidos de Venda"
		#define STR0224 "Configurações"
		#define STR0225 "Importação de Clientes"
		#define STR0226 "Importação de Pedidos de Venda"
		#define STR0227 If( cPaisLoc $ "ANG|PTG", "Importação de Contactos", "Importação de Contatos" )
		#define STR0228 "Importação de Mensagens"
		#define STR0229 If( cPaisLoc $ "ANG|PTG", "Grupo de Artigos", "Grupo de Produtos" )
		#define STR0230 If( cPaisLoc $ "ANG|PTG", "Estoque de Artigos", "Estoque de Produtos" )
		#define STR0231 "Tabela de preços"
		#define STR0232 If( cPaisLoc $ "ANG|PTG", "Duplicados", "Duplicatas" )
		#define STR0233 "Tipos de Pagamento"
		#define STR0234 "Regras de Descontos"
		#define STR0235 If( cPaisLoc $ "ANG|PTG", "Regras de Bonificações", "Regras de Bonificacoes" )
		#define STR0236 If( cPaisLoc $ "ANG|PTG", "Regras de Negócios", "Regras de Negocios" )
		#define STR0237 "Forn x Prod"
		#define STR0238 "Categorias"
		#define STR0239 "Metas"
		#define STR0240 "Roteiro"
		#define STR0241 If( cPaisLoc $ "ANG|PTG", "Títulos", "Titulos" )
		#define STR0242 "Consumo"
		#define STR0243 If( cPaisLoc $ "ANG|PTG", "Inventário", "Inventario" )
		#define STR0244 If( cPaisLoc $ "ANG|PTG", "Atendimento ", "Atendimento" )
		#define STR0245 "Grupos"
		#define STR0246 If( cPaisLoc $ "ANG|PTG", "Cab. Tabela de Preço", "Cab. Tabela de Preco" )
		#define STR0247 If( cPaisLoc $ "ANG|PTG", "It. Tabela de Preço", "It. Tabela de Preco" )
		#define STR0248 If( cPaisLoc $ "ANG|PTG", "Condição", "Condicao" )
		#define STR0249 If( cPaisLoc $ "ANG|PTG", "Tabelas Genéricas", "Tabelas Genericas" )
		#define STR0250 "Cab. Pedidos de Venda"
		#define STR0251 "It. Pedidos de Venda"
		#define STR0252 "Apontamentos"
		#define STR0253 "Cab. Regra de Descontos"
		#define STR0254 "It. Regra de Descontos"
		#define STR0255 If( cPaisLoc $ "ANG|PTG", "Cab. Regra de Bonificação", "Cab. Regra de Bonificacao" )
		#define STR0256 If( cPaisLoc $ "ANG|PTG", "It. Regra de Bonificação", "It. Regra de Bonificacao" )
		#define STR0257 If( cPaisLoc $ "ANG|PTG", "Cab. Regra de Negócios", "Cab. Regra de Negocios" )
		#define STR0258 If( cPaisLoc $ "ANG|PTG", "It. Regra de Negócio", "It. Regra de Negocio" )
		#define STR0259 "Categ x Prod"
		#define STR0260 If( cPaisLoc $ "ANG|PTG", "Esta alteração implica na exclusão da base de dados dos utilizadores pertencentes a este grupo. ", "Esta alteração implica na exclusão da base de dados dos usuários pertencentes a este grupo. " )
		#define STR0261 "Importação de Apontamentos"
		#define STR0262 If( cPaisLoc $ "ANG|PTG", "A executar serviço genérico", "Executando serviço genérico" )
		#define STR0263 " handheld(s) com sincronismo parcial."
		#define STR0264 "Marca Todos"
		#define STR0265 If( cPaisLoc $ "ANG|PTG", "Inverter Selecção", "Inverter Seleção" )
		#define STR0266 "Aplicar"
		#define STR0267 "Informe a Descrição"
		#define STR0268 "&Wizard"
		#define STR0269 "Assitente de configuração do SFA."
		#define STR0270 If( cPaisLoc $ "ANG|PTG", "Esta rotina tem como finalidade auxiliá-lo na configuração inicial dos Processos de Retaguarda do SFA x Protheus.", "Esta rotina tem como finalidade auxilia-lo na configuração inicial dos Processos de Retaguarda do SFA x Protheus." )
		#define STR0271 "Configuração Inicial dos Serviços"
		#define STR0272 "Marcar Todos"
		#define STR0273 "Desmarcar Todos"
		#define STR0274 "Serviços Obrigatórios"
		#define STR0275 If( cPaisLoc $ "ANG|PTG", "Serviços Opcionais seleccionados", "Serviços Opcionais selecionados" )
		#define STR0276 If( cPaisLoc $ "ANG|PTG", "Serviços Opcionais não seleccionados", "Serviços Opcionais não selecionados" )
		#define STR0277 "Definicão de Serviço"
		#define STR0278 If( cPaisLoc $ "ANG|PTG", "Serviço - Processo de actualização (importação ou ", "Serviço - Processo de atualização (importação ou " )
		#define STR0279 "exportação) das informações das Tabelas do SFA e"
		#define STR0280 "suas respectivas tabelas equivalentes no Protheus."
		#define STR0281 If( cPaisLoc $ "ANG|PTG", 'Ex.: O serviço "Pedido de Venda" actualiza as', 'Ex.: O serviço "Pedido de Venda" atualiza as' )
		#define STR0282 "tabelas de cabeçalhos de Pedidos de Venda e"
		#define STR0283 "Itens de Pedidos de Venda com as informações"
		#define STR0284 "da suas tabelas equivalentes no Protheus."
		#define STR0285 "Configuração Inicial dos Parâmetros"
		#define STR0286 "Configure os parâmetros do Sistema que são utilizados pelo SFA."
		#define STR0287 "Parâmetros"
		#define STR0288 "Editar"
		#define STR0289 "Confirmar"
		#define STR0290 If( cPaisLoc $ "ANG|PTG", "O registo de sistemas é utilizado para  identificar os sistemas que podem ser utilizados em integração com o Protheus.", "O cadastro de sistemas é utilizado para  identificar os sistemas que podem ser utilizados em integração com o Protheus." )
		#define STR0291 If( cPaisLoc $ "ANG|PTG", "O  registo de  tabelas  guarda  todas  as  tabelas  utilizadas  no  mobile, e contém informações sobre seu funcionamento.", "O  cadastro  de  tabelas  guarda  todas  as  tabelas  utilizadas  no  mobile, contendo informações sobre seu funcionamento." )
		#define STR0292 "Os serviços são as  funções  responsáveis pelo espelhamento da  tabela,  tanto do padrão para o espelho como para o  inverso."
		#define STR0293 If( cPaisLoc $ "ANG|PTG", "O  registo de utilizadores guarda  as  informações  de  cada  Hand-Held  registado,  cuja chave principal é o numero de série do equipamento.", "O  cadastro  de  usuários  guarda  as  informações  de  cada  Hand-Held  cadastrado,  cuja chave principal é o numero de série do equipamento." )
		#define STR0294 If( cPaisLoc $ "ANG|PTG", "Neste  registo  é  possível  criar  grupos  de  vendedores  separados  e  diferentes  entre  si. Aqui  também é  feito o  relacionamento dos grupos com os serviços que serão utilizados.", "Neste  cadastro  é  possível  criar  grupos  de  vendedores  separados  e  diferentes  entre  si. Aqui  também é  feito o  relacionamento dos grupos com os serviços que serão utilizados." )
	#endif
#endif
