#ifdef SPANISH
	#define STR0001 "Extracción de datos Integración Logix vs. Protheus"
	#define STR0002 "La extracción de los datos considerará el período informado para rastrear los documentos de entrada, documentos de cobertura, pedidos de venta integradas con el Protheus. Los archivos se generarán en el directorio del parámetro MV_WMSDOC."
	#define STR0003 "Para posterior comparación de la información y validación de la integridad de los entornos Logix y Protheus, debe ejecutar el informe wms6874 (Trazabilidad Documentos Logix vs. Protheus) en el Logix."
	#define STR0004 "Fecha inicial:"
	#define STR0005 "Fecha final:"
	#define STR0006 "Directorio:"
	#define STR0007 "Extracción de satos"
	#define STR0008 "Espere iniciar el procesamiento"
	#define STR0009 "Procesando documentos"
	#define STR0010 "Confirme la anulación de la extracción, el archivo quedará incompleto."
	#define STR0011 "¡Extracción anulada!"
	#define STR0012 "Extracción finalizada."
	#define STR0013 "No se encontró el directorio: "
	#define STR0014 "Falla en el borrado del archivo inputdocument"
	#define STR0015 "Falla en el borrado del archivo coveragedocument."
	#define STR0016 "Falla en el borrado del archivo salesorder."
#else
	#ifdef ENGLISH
		#define STR0001 "Extraction of Logix x Protheus Integration data"
		#define STR0002 "Data extraction considers the period informed to track inbound documents, coverage documents, sales orders integrated to Protheus. The files are generated in the directory of the parameter MV_WMSDOC."
		#define STR0003 "For later comparison of information and validation of integration of Logix and Protheus environments, execute report wms6874 (Traceability Logix x Protheus Documents) in Logix."
		#define STR0004 "Start Date:"
		#define STR0005 "End Date:"
		#define STR0006 "Directory:"
		#define STR0007 "Data Extraction"
		#define STR0008 "Wait start processing"
		#define STR0009 "Processing Documents"
		#define STR0010 "Confirm cancellation of extraction, file is incomplete."
		#define STR0011 "Canceled Extraction!"
		#define STR0012 "Extraction Concluded."
		#define STR0013 "No found in the directory: "
		#define STR0014 "Failure deleting inputdocument file"
		#define STR0015 "Failure in the deletion of coveragedocument file."
		#define STR0016 "Failure in the deletion of salesorder file."
	#else
		#define STR0001 "Extração de dados Integração Logix x Protheus"
		#define STR0002 "A extração dos dados irá considerar o período informado para rastrear os documentos de entrada, documentos de cobertura, pedidos de venda integradas com o Protheus. Os arquivos serão gerados no diretório do parâmetro MV_WMSDOC."
		#define STR0003 "Para posterior comparação das informações e validação da integridade dos ambientes Logix e Protheus, deverá executar o relatório wms6874 (Rastreabilidade Documentos Logix x Protheus) no Logix."
		#define STR0004 "Data Inicial:"
		#define STR0005 "Data Final:"
		#define STR0006 "Diretório:"
		#define STR0007 "Extração de Dados"
		#define STR0008 "Aguarde iniciar o processamento"
		#define STR0009 "Processando Documentos"
		#define STR0010 "Confirmar cancelamento da extração, o arquivo ficará incompleto."
		#define STR0011 "Extração Cancelada!"
		#define STR0012 "Extração Concluída."
		#define STR0013 "Não foi encontrado o diretório: "
		#define STR0014 "Falha na exclusão do arquivo inputdocument"
		#define STR0015 "Falha na exclusão do arquivo coveragedocument."
		#define STR0016 "Falha na exclusão do arquivo salesorder."
	#endif
#endif
