#ifdef SPANISH
	#define STR0001 "Integração SIGAPFS/SISCOSERV"
	#define STR0002 "Esta funcionalidade tem como objetivo fazer a integração das faturas com o módulo de SISCOSERV, conforme parametros definidos."
	#define STR0003 "Integracion SISCOSERV esta desactivada"
	#define STR0004 "No existen facturas para integrarse con el modulo SISCOSERV"
	#define STR0005 "Filtro de Sucursal incorrecto. Valor 'de Sucursal' esta rellenado y Valor 'A Sucursal' no."
	#define STR0006 "Filtro de Sucursal incorrecto. Valor 'de Sucursal' es mayor que Valor 'A sucursal'."
	#define STR0007 "Filtro de Fecha incorrecto. Valor 'De fecha' esta rellenado y Valor 'A fecha' no."
	#define STR0008 "Filtro de Fecha incorrecto. Valor 'De fecha' es mayor que Valor 'A fecha'."
	#define STR0009 "Filtro de Cliente y Tienda incorrecto. Valores 'De Cliente y Tienda' esta rellenado y Valores 'A Cliente y Tienda' no."
	#define STR0010 "Filtro de Cliente y Tienda incorrecto. Valores 'De Cliente y Tienda' son mayores que Valores 'A Cliente y Tienda'."
	#define STR0011 "Filtro de Cliente y Tienda incorrecto. Rellene siempre cliente y tienda."
	#define STR0012 "Integracion Realizada con exito"
	#define STR0013 "Realizando Integracion."
	#define STR0014 "Verifique Parametro MV_JNBS y rellene correctamente."
	#define STR0015 "Verifique el rellenado de los campos que indican NBS y Modo de prestacion de Servicios en caso da factura. Verifique el rellenado de los parametros que indican NBS y Modo de prestacion de Servicios en situacion de ausencia del rellenado en el registro del caso. (Parametros  MV_JNBS y MV_JMODO)"
	#define STR0016 "Realizando "
	#define STR0017 "Inclusion"
	#define STR0018 "Exclusion"
	#define STR0019 " de Factura: "
	#define STR0020 " / Oficina: "
	#define STR0021 "Hubo error en la integracion de la factura. Verifique observacion incluida en la factura: "
	#define STR0022 "Informe de verificacion de la integracion de las facturas"
	#define STR0023 "Filtro de Fecha de Emision incorrecto. Complete los campos 'De fecha' y 'A Fecha'."
	#define STR0024 "Filtro de Fecha de Emision incorrecto. Valor 'De fecha' es mayor que Valor 'A fecha'."
	#define STR0025 "Filtro de fecha de anulacion incorrecto. Complete los campos 'De fecha' y 'A Fecha'."
	#define STR0026 "Filtro de fecha de anulacion incorrecto. Valor 'De fecha' es mayor que Valor 'A fecha'."
	#define STR0027 "Facturas con Error: "
	#define STR0028 "J137: Error al crear archivo "
	#define STR0029 "Factura: "
	#define STR0030 "Oficina: "
	#define STR0031 "Error: "
	#define STR0032 "J137: Error de apertura "
	#define STR0033 "No fue posible abrir el archivo. Archivo o directorio no existe. "
	#define STR0034 "No fue posible abrir el archivo. Acceso negado. "
	#define STR0035 "No fue posible abrir el archivo. Drive no esta listo. "
	#define STR0036 "No fue posible abrir el archivo. Falla general. "
	#define STR0037 "No fue posible abrir el archivo. Violacion de compartimiento."
	#define STR0038 "No fue posible abrir el archivo. Falla de red. "
	#define STR0039 "No fue posible abrir el archivo. El archivo no esta asociado a un programa, directorio no existe, archivo no existe u ocurrio algun error no identificado."
	#define STR0040 "Filtro para integracion con SISCOSERV"
	#define STR0041 "Ocurrieron errores en la ejecucion. ¿Desea abrir el archivo de log?"
	#define STR0042 "Archivo generado el: "
	#define STR0043 "Creando Proceso, RVS y Facturas"
	#define STR0044 "Alterando Proceso, RVS y Facturas"
	#define STR0045 "Finalizando operacion"
	#define STR0046 "No se seleccionaron facturas para integracion"
	#define STR0047 "Seleccionando facturas a integrar"
	#define STR0048 "Integrando Facturas"
	#define STR0049 "Integracion de Facturas"
	#define STR0050 "Inclusion"
	#define STR0051 "Anulacion"
	#define STR0052 "Generando interfaz de seleccion de facturas"
	#define STR0053 "Integrando Factura: "
	#define STR0054 " / Factura: "
	#define STR0055 "Cliente Pagador: "
	#define STR0056 "Tienda: "
	#define STR0057 "Caso: "
	#define STR0058 "Visualizar"
	#define STR0059 "Integrar"
#else
	#ifdef ENGLISH
		#define STR0001 "SIGAPFS/SISCOSERV integration"
		#define STR0002 "This feature integrates the invoices with the SISCOSERV module, according to defined parameters."
		#define STR0003 "SISCOSERV integration is disabled"
		#define STR0004 "No invoices available for integration with the SISCOSERV module"
		#define STR0005 "Incorrect Branch Filter. 'Branch from' Value is filled out and 'Branch to' Value is not."
		#define STR0006 "Incorrect Branch Filter. 'Branch from' Value is greater than the 'Branch to' Value."
		#define STR0007 "Incorrect Date Filter. 'Date from' Value is filled out and 'Date to' Value is not."
		#define STR0008 "Incorrect Date Filter. 'Date from' Value is greater than the 'Date to' Value."
		#define STR0009 "Incorrect Customer and Store Filter. 'Customer and Store from' Values are filled out and 'Customer and Store to' Values are not."
		#define STR0010 "Incorrect Customer and Store Filter. 'Customer and Store from' Values are greater than 'Customer and Store to' Values."
		#define STR0011 "Incorrect Customer and Store Filter. Always fill out customer and store."
		#define STR0012 "Integration Successful"
		#define STR0013 "Performing Integration."
		#define STR0014 "Check the MV_JNBS parameter and fill it out correctly."
		#define STR0015 "Check the completion of fields indicating NBS and Services Rendering Mode in case of invoice. Check the completion of parameters indicating NBS and Services Rendering Mode in case the registration of the case lacks completion. (Parameters MV_JNBS and MV_JMODO)"
		#define STR0016 "Performing "
		#define STR0017 "Addition"
		#define STR0018 "Deletion"
		#define STR0019 " of Invoice: "
		#define STR0020 " / Firm: "
		#define STR0021 "An error occurred in invoice integration. Check note entered in Invoice: "
		#define STR0022 "Invoice Integration Checking Report"
		#define STR0023 "Incorrect Issue Date Filter. Fill out fields 'Date from' and ' Date to'."
		#define STR0024 "Incorrect Issue Date Filter. 'Date from' Value is greater than the 'Date to' Value."
		#define STR0025 "Incorrect Cancellation Date Filter. Fill out fields 'Date from' and ' Date to'."
		#define STR0026 "Incorrect Cancellation Date Filter. 'Date from' Value is greater than the 'Date to' Value."
		#define STR0027 "Invoice with Error: "
		#define STR0028 "J137: Error creating file "
		#define STR0029 "Invoice: "
		#define STR0030 "Firm: "
		#define STR0031 "Error: "
		#define STR0032 "J137: Opening error "
		#define STR0033 "File could not be opened. File or directory does not exist. "
		#define STR0034 "File could not be opened. Access denied. "
		#define STR0035 "File could not be opened. Drive is not ready. "
		#define STR0036 "File could not be opened. General Failure. "
		#define STR0037 "File could not be opened. Sharing violation. "
		#define STR0038 "File could not be opened. Network Failure. "
		#define STR0039 "File could not be opened. The file is not associated with a program; the directory does not exist; the file does not exist; or an unknown error has occurred. "
		#define STR0040 "Filter for integration with SISCOSERV"
		#define STR0041 "There were execution errors. Do you want to open the log?"
		#define STR0042 "File generated in: "
		#define STR0043 "Creating Process, RVS and Invoices"
		#define STR0044 "Changing Process, RVS and Invoices"
		#define STR0045 "Finishing operation"
		#define STR0046 "Invoices were not selected for integration"
		#define STR0047 "Selecting invoices to be integrated"
		#define STR0048 "Integrating Invoices"
		#define STR0049 "Invoices Integration"
		#define STR0050 "Inclusion"
		#define STR0051 "Cancellation"
		#define STR0052 "Generating interface of invoices selection"
		#define STR0053 "Integrating Invoice: "
		#define STR0054 " / Firm: "
		#define STR0055 "Customer Payer: "
		#define STR0056 "Store: "
		#define STR0057 "Case: "
		#define STR0058 "View"
		#define STR0059 "Integrate"
	#else
		#define STR0001 "Integração SIGAPFS/SISCOSERV"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Esta funcionalidade tem como objectivo fazer a integração das facturas com o módulo de SISCOSERV, conforme os parâmetros definidos.", "Esta funcionalidade tem como objetivo fazer a integração das faturas com o módulo de SISCOSERV, conforme parametros definidos." )
		#define STR0003 "Integração SISCOSERV está desabilitada"
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Não existem facturas a serem integradas com o módulo SISCOSERV", "Não existem faturas a serem integradas com o módulo SISCOSERV" )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Filtro de Filial incorrecto. Valor 'De filial' está preenchido e Valor 'Até filial' não.", "Filtro de Filial incorreto. Valor 'Filial de' está preenchido e Valor 'Filial até' não." )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Filtro de Filial incorrecto. Valor 'De filial' é maior que Valor 'Até filial'.", "Filtro de Filial incorreto. Valor 'Filial de' é maior que Valor 'Filial até'." )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Filtro de Data incorrecto. Valor 'De data' está preenchido e Valor 'Até data' não.", "Filtro de Data incorreto. Valor 'Data de' está preenchido e Valor 'Data até' não." )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Filtro de Data incorrecto. Valor 'De data' é maior que Valor 'Até data'.", "Filtro de Data incorreto. Valor 'Data de' é maior que Valor 'Data até'." )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Filtro de Cliente e Loja incorrecto. Valores 'De Cliente e Loja' estão preenchidos e Valores 'Até Cliente e Loja' não.", "Filtro de Cliente e Loja incorreto. Valores 'Cliente e Loja de' estão preenchidos e Valores 'Cliente e Loja até' não." )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Filtro de Cliente e Loja incorrecto. Valores 'De Cliente e Loja' são maiores que Valores 'Até Cliente e Loja'.", "Filtro de Cliente e Loja incorreto. Valores 'Cliente e Loja de' são maiores que Valores 'Cliente e Loja até'." )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Filtro de Cliente e Loja incorrecto. Preencha sempre cliente e loja.", "Filtro de Cliente e Loja incorreto. Preencha sempre cliente e loja." )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Integração realizada com sucesso", "Integração Realizada com Sucesso" )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "A realizar integração.", "Realizando Integração." )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Verifique o parâmetro MV_JNBS e preencha-o correctamente.", "Verifique Parâmetro MV_JNBS e preencha corretamente." )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Verifique o preenchimento dos campos que indicam NBS e Modo de prestação de Serviços no caso da factura. Verifique o preenchimento dos parâmetros que indicam NBS e Modo de prestação de Serviços em situação de ausência do preenchimento no registo do caso. (Parâmetros  MV_JNBS e MV_JMODO)", "Verifique o preenchimento dos campos que indicam NBS e Modo de prestação de Serviços no caso da fatura. Verifique o preenchimento dos parâmetros que indicam NBS e Modo de prestação de Serviços em situação de ausência do preenchimento no cadastro do caso. (Parâmetros  MV_JNBS e MV_JMODO)" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "A realizar ", "Realizando " )
		#define STR0017 "Inclusão"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Eliminação", "Exclusão" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", " da Factura: ", " da Fatura: " )
		#define STR0020 " / Escritório: "
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Houve erro na integração da factura. Verifique observação inserida na factura: ", "Houve erro na integração da fatura. Verifique observação inserida na Fatura: " )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Relatório de conferência da integração das facturas", "Relatório de conferência da integração das Faturas" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Filtro de data de emissão incorrecto. Preencha os campos 'De data' e 'Até data'.", "Filtro de Data de Emissão incorreto. Preencha os campos 'Data de' e 'Data Até'." )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Filtro de data de emissão incorrecto. Valor 'De data' é maior que Valor 'Até data'.", "Filtro de Data de Emissão incorreto. Valor 'Data de' é maior que Valor 'Data até'." )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Filtro de data de cancelamento incorrecto. Preencha os campos 'De data' e 'Até data'.", "Filtro de Data de Cancelamento incorreto. Preencha os campos 'Data de' e 'Data Até'." )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Filtro de data de cancelamento incorrecto. Valor 'De data' é maior que Valor 'Até data'.", "Filtro de Data de Cancelamento incorreto. Valor 'Data de' é maior que Valor 'Data até'." )
		#define STR0027 "Faturas com Erro: "
		#define STR0028 "J137: Erro ao criar arquivo "
		#define STR0029 "Fatura: "
		#define STR0030 "Escritório: "
		#define STR0031 "Erro: "
		#define STR0032 "J137: Erro de abertura "
		#define STR0033 "Não foi possível abrir o arquivo. Arquivo ou diretório não existe. "
		#define STR0034 "Não foi possível abrir o arquivo. Acesso negado. "
		#define STR0035 "Não foi possível abrir o arquivo. Drive não esta pronto. "
		#define STR0036 "Não foi possível abrir o arquivo. Falha Geral. "
		#define STR0037 "Não foi possível abrir o arquivo. Violação de compartilhamento. "
		#define STR0038 "Não foi possível abrir o arquivo. Falha de rede. "
		#define STR0039 "Não foi possível abrir o arquivo. O arquivo não está associado a um programa, diretório não existe, arquivo não existe ou ocorreu algum erro não identificado. "
		#define STR0040 "Filtro para integração com SISCOSERV"
		#define STR0041 "Ocorreram erros na execução. Deseja abrir o arquivo de log?"
		#define STR0042 "Arquivo gerado em: "
		#define STR0043 "Criando Processo, RVS e Faturas"
		#define STR0044 "Alterando Processo, RVS e Faturas"
		#define STR0045 "Finalizando operação"
		#define STR0046 "Não foram selecionadas faturas para integração"
		#define STR0047 "Selecionando faturas a serem integradas"
		#define STR0048 "Integrando Faturas"
		#define STR0049 "Integração de Faturas"
		#define STR0050 "Inclusão"
		#define STR0051 "Cancelamento"
		#define STR0052 "Gerando interface de seleção de faturas"
		#define STR0053 "Integrando Fatura: "
		#define STR0054 " / Escritório: "
		#define STR0055 "Cliente Pagador: "
		#define STR0056 "Loja: "
		#define STR0057 "Caso: "
		#define STR0058 "Visualizar"
		#define STR0059 "Integrar"
	#endif
#endif
