#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Limpiar"
	#define STR0007 "Busqueda"
	#define STR0008 "Salir"
	#define STR0009 "Configuraciones"
	#define STR0010 "DATO"
	#define STR0011 "Buscando..."
	#define STR0012 "Ningun registro encontrado."
	#define STR0013 "Cantidad de Registros:"
	#define STR0014 "Configuracion invalida o perfil de busqueda no esta vinculado a ningun tipo de asunto juridico. ¡Operacion anulada!"
	#define STR0015 "Cargando...."
	#define STR0016 "Asunto Juridico"
	#define STR0017 "Es necesario seleccionar una configuracion de busqueda"
	#define STR0018 "Codigo"
	#define STR0019 "Descripcion"
	#define STR0020 "Leyenda del Tipo de Asunto"
	#define STR0021 "Montaje da clausula del campo "
	#define STR0022 " ¡esta incorrecta! (Falta #)"
	#define STR0023 "DADO_GRUPO"
	#define STR0024 "Seleccione el Tipo de Asunto Juridico"
	#define STR0025 "Exportacion Personalizada"
	#define STR0026 "Error al generar el informe"
	#define STR0027 "Error al incluir los registros en la cola de impresion"
	#define STR0028 "Error al limpiar la cola de impresion"
	#define STR0029 "Incluir el proceso en la cola de impresion"
	#define STR0030 "Incluir todos los procesos en la cola de impresion"
	#define STR0031 "Borrar el proceso de la cola de impresion"
	#define STR0032 "Borrar todos los procesos de la cola de impresion"
	#define STR0033 "Imprimir procesos de la cola de impresion"
	#define STR0034 "Cola de Impresion"
	#define STR0035 "Cant. Cola de impresion:"
	#define STR0036 "Correccion Valores"
	#define STR0037 "Es necesario realizar la busqueda de los registros que se corregiran"
	#define STR0038 "1 = Incidentes (Todos los niveles)"
	#define STR0039 "2 = Procesos Vinculados (Todos los niveles)"
	#define STR0040 "3 = Incidentes y Procesos vinculados"
	#define STR0041 "¿Incidentes Activos?"
	#define STR0042 "¿Vinculados Activos?"
	#define STR0043 "Parametros de Informes"
	#define STR0044 "Config. Informe"
	#define STR0045 "Imprimir Proseguimiento"
	#define STR0046 "Imprimir nº de Pagina"
	#define STR0047 "Procesos Vinculados"
	#define STR0048 "Solo Proseguimiento p/ Cliente"
	#define STR0049 "Los ultimos vs. Proseguimientos"
	#define STR0050 "Cantidad"
	#define STR0051 "Intervalo entre Fechas"
	#define STR0052 "Fecha inicial"
	#define STR0053 "Fecha final"
	#define STR0054 "Es necesario seleccionar una configuracion para generacion del informe"
	#define STR0055 "Es necesario rellenar la cantidad de proseguimientos"
	#define STR0056 "Es necesario rellenar los dos campos de intervalos entre fechas"
	#define STR0057 "El caso "
	#define STR0058 " fue remanejado para el caso "
	#define STR0059 ". ¿Desea ser remetido al nuevo caso?"
	#define STR0060 "DADO_GRUPOEMP"
	#define STR0061 "Modificaciones realizadas con exito"
	#define STR0062 "Es necesario seleccionar una configuracion de busqueda"
	#define STR0063 "No es posible incluir procesos de asuntos juridicos diferentes en la cola de impresion."
	#define STR0064 "Imprime garantias"
	#define STR0065 "¿Ya se ejecuto la rutina de 'Correccion Valores'?"
	#define STR0066 "Operacion no permitida."
	#define STR0067 "Configuracion invalida o perfil de busqueda no esta vinculado a ningun tipo de asunto juridico.  ¡Operacion anulada!"
	#define STR0068 "Cola..."
	#define STR0069 "Ingresando en la cola..."
	#define STR0070 "Espere..."
	#define STR0071 "Incluyendo "
	#define STR0072 " de "
	#define STR0073 "Informe de concesiones"
	#define STR0074 "Es necesario rellenar el parametro MV_JRELCON para emitir el informe. Verifique."
	#define STR0075 "Imprimir concesiones de la Cola de impresion"
	#define STR0076 "Es necesario completar el parametro MV_JSOCAND para emision del informe. ¡Verifique!"
	#define STR0077 "Inclusion"
	#define STR0078 "Borrado"
	#define STR0079 "Extracto de Garantias"
	#define STR0080 "En Procesos"
	#define STR0081 "Informes"
	#define STR0082 "Relevamiento"
	#define STR0083 "Informe Follow-Up"
	#define STR0084 "Informe Pauta Compromiso"
	#define STR0085 "Garantias"
	#define STR0086 "Follow-Ups"
	#define STR0087 "Busqueda de Garantias"
	#define STR0088 "Busqueda de Follow-Ups"
	#define STR0089 "Estatus Follow Up"
	#define STR0090 "BR_VERDE"
	#define STR0091 "BR_VERMELHO"
	#define STR0092 "BR_CINZA"
	#define STR0093 "BR_AMARELO"
	#define STR0094 "BR_AZUL"
	#define STR0095 "Efectuado"
	#define STR0096 "Pendiente - En Atraso"
	#define STR0097 "Anulado"
	#define STR0098 "Pendiente - En Marcha"
	#define STR0099 "Reprogramado"
	#define STR0100 "Estatus"
	#define STR0101 "La planilla no puede exportarse."
	#define STR0102 "Microsoft Excel no instalado."
	#define STR0103 "Codigo"
	#define STR0104 "Tienda"
	#define STR0105 "Razón Social"
	#define STR0106 "Codigo+Tienda"
	#define STR0107 "Clientes"
	#define STR0108 "Follow-ups"
	#define STR0109 "Informe el camino"
	#define STR0110 "Nombre del Archivo"
	#define STR0111 "Seleccione el Directorio p/ generar el Archivo"
	#define STR0112 "Quiebra"
	#define STR0113 "Log"
	#define STR0114 "Proceso"
	#define STR0115 "Proceso"
	#define STR0116 "Cant.Proces."
	#define STR0117 "Procesando Follow-Ups"
	#define STR0118 "Generando Archivo Excel"
	#define STR0119 "Es necesario completar los campos de Cliente y Tienda para determinar si el numero del caso es valido"
	#define STR0120 "Leyenda de la Garantia"
	#define STR0121 "El caso "
	#define STR0122 " fue remanejado para el caso "
	#define STR0123 ". ¿Desea que se remita al nuevo caso?"
	#define STR0124 "Busqueda de Procesos en Marcha"
	#define STR0125 "Leyenda de los Procesos en Marcha"
	#define STR0126 "Busqueda de Procesos"
	#define STR0127 "DADO_LIKE"
	#define STR0128 "Es necesario configurar la grilla de busqueda."
	#define STR0129 "Grabar como"
	#define STR0130 "Modelo de integracion con MS-Word (.DOT / .DOTX) no encontrado."
	#define STR0131 "No es posible borrar el archivo de modelo del MS-Word (.DOT) de la carpeta temporaria"
	#define STR0132 "No es posible transferir para carpeta temporaria el archivo de modelo del MS-Word (.DOT)."
	#define STR0133 "Se emitio 1 documento."
	#define STR0134 "Se emitieron #1 documentos."
	#define STR0135 "Todos"
	#define STR0136 "No"
	#define STR0137 "Si"
	#define STR0138 "Por favor, verifique el modo de acceso/unidades de negocio de las tablas: NQ9 y NQY."
	#define STR0139 "Para generar el informe es necesario que estas esten con la misma configuracion: Compartida o Exclusiva. "
	#define STR0140 "Imprime documento"
	#define STR0141 "Es necesario ejecutar el paquete de actualizacion del llamado TPCJNI, debido a la nueva estructura de tipos de asuntos jurídicos. Verifique en el portal del cliente."
	#define STR0142 "Usuario no posee acceso para editar Multiples Sucursales"
	#define STR0143 "Mensaje de Error"
	#define STR0144 "¡Tabla SX9 desactualizada! "
	#define STR0145 "No se encontro la relacion de los alias ("
	#define STR0146 "¡Ninguna informacion se retornara!"
	#define STR0147 "Volver"
	#define STR0148 "Titulos"
	#define STR0149 "Liberacion de Dctos"
	#define STR0150 "Ano-Mes Actualizacion:"
	#define STR0151 "Historial de Valores"
	#define STR0152 "Nuevo calculo"
	#define STR0153 "No fue posible crear el directorio temporal en: "
	#define STR0154 "Seleccione el modelo"
	#define STR0155 "¡Modelo borrado con exito!"
	#define STR0156 "Incluir con modelo"
	#define STR0157 "Borrar Modelo"
	#define STR0158 "Espere..."
	#define STR0159 "Incluyendo procesos en la cola de impresion..."
	#define STR0160 "No es posible incluir procesos de asuntos jurídicos diferentes en la cola de impresión."
	#define STR0161 "Clave #1, no se ubicó en el appserver.ini"
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Change"
		#define STR0005 "Delete"
		#define STR0006 "Clear"
		#define STR0007 "Search"
		#define STR0008 "Quit"
		#define STR0009 "Configurations:"
		#define STR0010 "DATA"
		#define STR0011 "Searching..."
		#define STR0012 "No record found."
		#define STR0013 "Number of Records:"
		#define STR0014 "Configuration invalid or search profile is not linked to any legal subject type. Operation canceled!"
		#define STR0015 "Loading..."
		#define STR0016 "Legal Subject"
		#define STR0017 "A search configuration must be selected"
		#define STR0018 "Code"
		#define STR0019 "Description"
		#define STR0020 "Subject Type Caption"
		#define STR0021 "Assembling of field clause "
		#define STR0022 " is wrong!(Remaining #)"
		#define STR0023 "DATUM_GROUP"
		#define STR0024 "Select the Legal Subject Type"
		#define STR0025 "Customized Export"
		#define STR0026 "Error while generating the report"
		#define STR0027 "Error while adding records to the print queue"
		#define STR0028 "Error while clearing the print queue"
		#define STR0029 "Add the process to the print queue"
		#define STR0030 "Add all processes to the print queue"
		#define STR0031 "Delete the process from the print queue"
		#define STR0032 "Delete all processes from the print queue"
		#define STR0033 "Print processes from the print queue"
		#define STR0034 "Print Queue"
		#define STR0035 "Print Queue Qty:"
		#define STR0036 "Value Adjustment"
		#define STR0037 "Search the records to be adjusted"
		#define STR0038 "1 = Incidents (all levels)"
		#define STR0039 "2 = Associated Lawsuits (all levels)"
		#define STR0040 "3 = Incidents and Associated Lawsuits"
		#define STR0041 "Active Incidents?"
		#define STR0042 "Active Associated?"
		#define STR0043 "Report parameters"
		#define STR0044 "Config. Report"
		#define STR0045 "Print Progresses"
		#define STR0046 "Print page nr"
		#define STR0047 "Attached Processes"
		#define STR0048 "Progress f/ Customer Only"
		#define STR0049 "The last x progresses"
		#define STR0050 "Quantity"
		#define STR0051 "Interval between dates"
		#define STR0052 "Start Date"
		#define STR0053 "End Date"
		#define STR0054 "Select one configuration to generate the report"
		#define STR0055 "Fill out the quantity of progresses"
		#define STR0056 "Fill out the two fields of intervals between dates"
		#define STR0057 "The case "
		#define STR0058 " has been transferred to the case "
		#define STR0059 ". Do you want to be referred to the new case?"
		#define STR0060 "DATUM_COMPGROUP"
		#define STR0061 "Changes successfully performed"
		#define STR0062 "A search configuration must be selected"
		#define STR0063 "Different legal matters cannot be added to printing queue."
		#define STR0064 "Print Warranties"
		#define STR0065 "Was the 'Value Correction' routine executed?"
		#define STR0066 "Operation not allowed."
		#define STR0067 "Configuration invalid or search profile is not linked to any legal subject type. Operation canceled!"
		#define STR0068 "Queue..."
		#define STR0069 "Adding to Queue..."
		#define STR0070 "Wait..."
		#define STR0071 "Including "
		#define STR0072 " from "
		#define STR0073 "Concession Report"
		#define STR0074 "Enter MV_JRELCON parameter to issue the report. Check it out !"
		#define STR0075 "Print Concessions of Print Queue"
		#define STR0076 "Fill out MV_JSOCAND  parameter to issue the report. Check it out !"
		#define STR0077 "Addition"
		#define STR0078 "Deletion"
		#define STR0079 "Statement of Warranties"
		#define STR0080 "Progress"
		#define STR0081 "Reports"
		#define STR0082 "Survey"
		#define STR0083 "Follow-up Report"
		#define STR0084 "Report Docket Appointment"
		#define STR0085 "Guarantees"
		#define STR0086 "Follow-ups"
		#define STR0087 "Warranties Survey"
		#define STR0088 "Follow-ups Survey"
		#define STR0089 "Follow Up Status"
		#define STR0090 "BR_GREEN"
		#define STR0091 "BR_RED"
		#define STR0092 "BR_GRAY"
		#define STR0093 "BR_YELLOW"
		#define STR0094 "BR_BLUE"
		#define STR0095 "Performed"
		#define STR0096 "Pending - Past due"
		#define STR0097 "Canceled"
		#define STR0098 "Pending - In progress"
		#define STR0099 "Rescheduled"
		#define STR0100 "Status"
		#define STR0101 "Spreadsheet cannot be exported."
		#define STR0102 "Microsoft Excel is not installed."
		#define STR0103 "Code"
		#define STR0104 "Store"
		#define STR0105 "Company Name"
		#define STR0106 "Code+Store"
		#define STR0107 "Customers"
		#define STR0108 "Follow-ups"
		#define STR0109 "Enter the path!"
		#define STR0110 "File name"
		#define STR0111 "Select the directory to generate the file"
		#define STR0112 "Break"
		#define STR0113 "Log"
		#define STR0114 "Process"
		#define STR0115 "Progress"
		#define STR0116 "Progr.Amt."
		#define STR0117 "Processing Follow-ups"
		#define STR0118 "Generating excel file"
		#define STR0119 "Customer and Store fields must be filled to define if the case number is valid"
		#define STR0120 "Warranty Caption"
		#define STR0121 "The case "
		#define STR0122 " has been transferred to the case "
		#define STR0123 ". Do you want to be referred to the new case?"
		#define STR0124 "Progress Survey"
		#define STR0125 "Progress Caption"
		#define STR0126 "Survey of Processes"
		#define STR0127 "DATUM_LIKE"
		#define STR0128 "A search grid must be set"
		#define STR0129 "Save as"
		#define STR0130 "Model of integration with MS-Word (.DOT / .DOTX) not found."
		#define STR0131 "You cannot delete model file of MS-Word (.DOT) of temporary folder"
		#define STR0132 "You cannot transfer model file of MS-Word (.DOT) for temporary folder."
		#define STR0133 "1 document was issued."
		#define STR0134 "#1 documents were issued."
		#define STR0135 "All"
		#define STR0136 "No"
		#define STR0137 "Yes"
		#define STR0138 "Please check the access mode/business units of tables NQ9 and NQY."
		#define STR0139 "To generate the report, their configuration must be the same: Shared or Exclusive. "
		#define STR0140 "Print Document"
		#define STR0141 "It is necessary run the update package of ticket TPCJNI, due to the new structure of legal matters type. Check in Client Portal."
		#define STR0142 "User does not have access to edit Multiple Branches"
		#define STR0143 "Error Message"
		#define STR0144 "Outdated SX9 table! "
		#define STR0145 "Relationship alias not found ("
		#define STR0146 "No information entered!"
		#define STR0147 "Back"
		#define STR0148 "Bills"
		#define STR0149 "Doct Release"
		#define STR0150 "Year-Month Update:"
		#define STR0151 "History Values"
		#define STR0152 "Recalculation"
		#define STR0153 "Unable to created the temporary directory in: "
		#define STR0154 "Select the model"
		#define STR0155 "Model successfully deleted!"
		#define STR0156 "Add with Model"
		#define STR0157 "Delete Model"
		#define STR0158 "Wait..."
		#define STR0159 "Adding process(es) in printing queue..."
		#define STR0160 "Unable to add different legal matters processes on the printing queue."
		#define STR0161 "Key #1, not located in appserver.ini"
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Eliminar", "Excluir" )
		#define STR0006 "Limpar"
		#define STR0007 "Pesquisa"
		#define STR0008 "Sair"
		#define STR0009 "Configurações:"
		#define STR0010 "DADO"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "A pesquisar...", "Pesquisando..." )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Nenhum registo encontrado.", "Nenhum registro encontrado." )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Quantidade de registos:", "Quantidade de Registros:" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Configuração inválida ou perfil de pesquisa não vinculado a nenhum tipo de assunto jurídico. Operação cancelada.", "Configuração inválida ou perfil de pesquisa não está vinculado a nenhum tipo de assunto jurídico. Operação cancelada!" )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "A carregar...", "Carregando..." )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Assunto jurídico", "Assunto Jurídico" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "É necessário seleccionar uma configuração de pesquisa", "É necessário selecionar uma configuração de pesquisa" )
		#define STR0018 "Código"
		#define STR0019 "Descrição"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Legenda do tipo de assunto", "Legenda do Tipo de Assunto" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Montagem da cláusula do campo ", "Montagem da clausula do campo " )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", " está incorrecta.(Falta #)", " esta incorreta!(Falta #)" )
		#define STR0023 "DADO_GRUPO"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Seleccione o tipo de assunto jurídico", "Selecione o Tipo de Assunto Jurídico" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Exportação personalizada", "Exportação Personalizada" )
		#define STR0026 "Erro ao gerar o relatório"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Erro ao incluir os registos na fila de impressão", "Erro ao incluir os registros na fila de impressão" )
		#define STR0028 "Erro ao limpar a fila de impressão"
		#define STR0029 "Inserir o processo na fila de impressão"
		#define STR0030 "Inserir todos os processos na fila de impressão"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Eliminar o processo da fila de impressão", "Excluir o processo da fila de impressão" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Eliminar todos os processos da fila de impressão", "Excluir todos os processos da fila de impressão" )
		#define STR0033 "Imprimir processos da fila de impressão"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Fila de impressão", "Fila de Impressão" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Qtd. fila de impressão:", "Qtd. Fila de Impressão:" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Correcção valores", "Correção Valores" )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "É necessário realizar a pesquisa dos registos a serem corrigidos", "É necessário realizar a pesquisa dos registros a serem corrigidos" )
		#define STR0038 "1 = Incidentes (Todos os níveis)"
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "2 = Processos vinculados (Todos os níveis)", "2 = Processos Vinculados (Todos os níveis)" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "3 = Incidentes e processos vinculados", "3 = Incidentes e  Processos Vinculados" )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Incidentes activos?", "Incidentes Ativos?" )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Vinculados activos?", "Vinculados Ativos?" )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Parametros do relatórios", "Parâmetros do Relatórios" )
		#define STR0044 "Config. Relatório"
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Imprimir andamentos", "Imprimir Andamentos" )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Imprimir nº de página", "Imprimir nº de Página" )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Processos vinculados", "Processos Vinculados" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Apenas andamento p/ cliente", "Apenas Andamento p/ Cliente" )
		#define STR0049 "Os últimos x Andamentos"
		#define STR0050 "Quantidade"
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Intervalo entre datas", "Intervalo entre Datas" )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Data inicial", "Data Inicial" )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Data final", "Data Final" )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "É necessário seleccionar uma configuração para geração do relatório", "É necessário selecionar uma configuração para geração do relatório" )
		#define STR0055 "É necessário preencher a quantidade de andamentos"
		#define STR0056 "É necessário preencher os dois campos do intervalos entre datas"
		#define STR0057 "O caso "
		#define STR0058 " foi remanejado para o caso "
		#define STR0059 ". Deseja ser remetido ao novo caso?"
		#define STR0060 "DADO_GRUPOEMP"
		#define STR0061 "Alterações realizadas com sucesso"
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "É necessário seleccionar uma configuração de pesquisa", "É necessário selecionar uma configuração de pesquisa" )
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "Não é possível incluir processos de assuntos jurídicos diferentes na fila de impressão.", "Não é possivel incluir processos de assuntos juridicos diferentes na fila de impressão." )
		#define STR0064 "Imprimir Garantias"
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Já foi executado o procedimento de 'Correcção valores'?", "Já foi executada a rotina de 'Correção Valores'?" )
		#define STR0066 "Operação não permitida."
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Configuração inválida ou perfil de pesquisa não está vinculado a nenhum tipo de assunto jurídico. Operação cancelada.", "Configuração inválida ou perfil de pesquisa não está vinculado a nenhum tipo de assunto jurídico. Operação cancelada!" )
		#define STR0068 "Fila..."
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "A inserir na fila...", "Inserindo na fila..." )
		#define STR0070 "Aguarde..."
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "A incluir ", "Incluindo " )
		#define STR0072 " de "
		#define STR0073 "Relatório de Concessões"
		#define STR0074 "É necessário preencher o parâmetro MV_JRELCON para emissão do relatório. Verifique !"
		#define STR0075 "Imprimir Concessões da Fila de Impressão"
		#define STR0076 "É necessário preencher o parâmetro MV_JSOCAND para emissão do relatório. Verifique !"
		#define STR0077 "Inclusão"
		#define STR0078 "Exclusão"
		#define STR0079 "Extrato de Garantias"
		#define STR0080 "Andamentos"
		#define STR0081 "Relatórios"
		#define STR0082 "Levantamento"
		#define STR0083 "Relatório Follow-Up"
		#define STR0084 "Relatório Pauta Compromisso"
		#define STR0085 "Garantias"
		#define STR0086 "Follow-Ups"
		#define STR0087 "Pesquisa de Garantias"
		#define STR0088 "Pesquisa de Follow-Ups"
		#define STR0089 "Status Follow Up"
		#define STR0090 "BR_VERDE"
		#define STR0091 "BR_VERMELHO"
		#define STR0092 "BR_CINZA"
		#define STR0093 "BR_AMARELO"
		#define STR0094 "BR_AZUL"
		#define STR0095 "Efetuado"
		#define STR0096 "Pendente - Em Atraso"
		#define STR0097 "Cancelado"
		#define STR0098 "Pendente - Em Andamento"
		#define STR0099 "Reagendado"
		#define STR0100 "Status"
		#define STR0101 "A planilha não pode ser exportada."
		#define STR0102 "Microsoft Excel não instalado."
		#define STR0103 "Código"
		#define STR0104 "Loja"
		#define STR0105 "Razão Social"
		#define STR0106 "Código+Loja"
		#define STR0107 "Clientes"
		#define STR0108 "Follow-ups"
		#define STR0109 "Informe o caminho"
		#define STR0110 "Nome do Arquivo"
		#define STR0111 "Selecione o Diretório p/ gerar o Arquivo"
		#define STR0112 "Quebra"
		#define STR0113 "Log"
		#define STR0114 "Processo"
		#define STR0115 "Andamento"
		#define STR0116 "Qtd.Andam."
		#define STR0117 "Processando Follow-Ups"
		#define STR0118 "Gerando Arquivo Excel"
		#define STR0119 "É necessário preencher os campos de Cliente e Loja para determinar se o número do caso é válido"
		#define STR0120 "Legenda da Garantia"
		#define STR0121 "O caso "
		#define STR0122 " foi remanejado para o caso "
		#define STR0123 ". Deseja ser remetido ao novo caso?"
		#define STR0124 "Pesquisa de Andamentos"
		#define STR0125 "Legenda do Andamento"
		#define STR0126 "Pesquisa de Processos"
		#define STR0127 "DADO_LIKE"
		#define STR0128 "É necessário configurar o grid de pesquisa."
		#define STR0129 "Salvar como"
		#define STR0130 "Modelo de integração com MS-Word (.DOT / .DOTX) não encontrado."
		#define STR0131 "Não foi possível deletar o arquivo de modelo do MS-Word (.DOT) da pasta temporária"
		#define STR0132 "Não foi possível transferir para pasta temporária o arquivo de modelo do MS-Word (.DOT)."
		#define STR0133 "Foi emitido 1 documento."
		#define STR0134 "Foram emitidos #1 documentos."
		#define STR0135 "Todos"
		#define STR0136 "Não"
		#define STR0137 "Sim"
		#define STR0138 "Favor verificar o modo de acesso/unidades de negócio das tabelas: NQ9 e NQY."
		#define STR0139 "Para gerar o relatório é necessário que estas estejam com a mesma configuração: Compartilhada ou Exclusiva. "
		#define STR0140 "Imprimir Documento"
		#define STR0141 "É necessário rodar o pacote de atualização do chamado TPCJNI, devido a nova estrutura de tipos de assuntos jurídicos. Verifique no portal do cliente."
		#define STR0142 "Usuário não possui acesso para editar Múltiplas Filiais"
		#define STR0143 "Mensagem de Erro"
		#define STR0144 "Tabela SX9 desatualizada! "
		#define STR0145 "Não encontrado o relacionamento dos alias ("
		#define STR0146 "Nenhuma informação será retornada!"
		#define STR0147 "Voltar"
		#define STR0148 "Títulos"
		#define STR0149 "Liberação de Dctos"
		#define STR0150 "Ano-Mês Atualização:"
		#define STR0151 "Valores Históricos"
		#define STR0152 "Recálculo"
		#define STR0153 "Não foi possivel criar o diretório temporário em: "
		#define STR0154 "Selecione o modelo"
		#define STR0155 "Modelo excluido com sucesso!"
		#define STR0156 "Incluir com Modelo"
		#define STR0157 "Excluir Modelo"
		#define STR0158 "Aguarde..."
		#define STR0159 "Inserindo processo(s) na fila de impressão..."
		#define STR0160 "Não é possivel incluir processos de assunto juridicos diferentes na fila de impressão."
		#define STR0161 "Chave #1, não localizada no appserver.ini"
	#endif
#endif
