#ifdef SPANISH
	#define STR0001 "Documentos Anexos(*.XML)|*.XML| Archivos Texto(*.Txt)|*.TXT|"
	#define STR0002 "Procergs"
	#define STR0003 "Da-Justi"
	#define STR0004 "Destaque"
	#define STR0005 "Publicaciones Conciliadas"
	#define STR0006 "Publicaciones Localizadas"
	#define STR0007 "Publicaciones No localizadas"
	#define STR0008 "Publicaciones Duplicadas"
	#define STR0009 "Publicaciones Borradas"
	#define STR0010 "Importacion de Publicaciones"
	#define STR0011 "Localizacion / Tipo de Archivos"
	#define STR0012 "Tipo de Publicacion"
	#define STR0013 "Camino:"
	#define STR0014 "Seleccione el Archivo"
	#define STR0015 "&Importar archivo"
	#define STR0016 "¡Camino no informado!"
	#define STR0017 "Informe el camino"
	#define STR0018 "Estatus del archivo XML"
	#define STR0019 "Cant de Publicaciones Importadas"
	#define STR0020 "Cant de Publicaciones Localizadas"
	#define STR0021 "Cant de Publicaciones Duplicadas"
	#define STR0022 "Cant de Publicaciones Conciliadas"
	#define STR0023 "Cant de Publicaciones No Localizadas"
	#define STR0024 "Cant de Publicaciones Borradas"
	#define STR0025 "Filtro de Busqueda"
	#define STR0026 "Fecha Inicial"
	#define STR0027 "Fecha Final"
	#define STR0028 "Mostrar con palabras clave"
	#define STR0029 "Nombre del Documento"
	#define STR0030 "Mostrar solo el ultimo XML importado"
	#define STR0031 "Detalle del Proceso"
	#define STR0032 "Conciliar"
	#define STR0033 "Buscar"
	#define STR0034 "Limpiar"
	#define STR0035 "Salir"
	#define STR0036 "Procesando conciliacion"
	#define STR0037 "Espere"
	#define STR0038 "Palavra Clave"
	#define STR0039 "Cod del Asunto Juridico"
	#define STR0040 "Fch.Borrado"
	#define STR0041 "Usuario borrado"
	#define STR0042 "Invierte seleccion"
	#define STR0043 "Importacion de publicaciones"
	#define STR0044 "No hay archivos importados para consultar"
	#define STR0045 "Archivos importados"
	#define STR0046 "Buscar"
	#define STR0047 "Archivo"
	#define STR0048 "Fc.Import."
	#define STR0049 "Tipo de Archivo"
	#define STR0050 "Fecha de la importacion:"
	#define STR0051 "Importado anteriormente."
	#define STR0052 "Archivo no encontrado"
	#define STR0053 "Verifique"
	#define STR0054 "Archivo no compatible con el Tipo de archivo XML"
	#define STR0055 "Acto Procesal"
	#define STR0056 "Conciliacion"
	#define STR0057 "Proceso efectuado con exito"
	#define STR0058 "Visualizar proceso"
	#define STR0059 "Inf.Import.XML Publicacion"
	#define STR0060 "Inf.Import.XML Folder Activa Publicacion"
	#define STR0061 "Borrar"
	#define STR0062 "Vincular proceso"
	#define STR0063 "Restaurar"
	#define STR0064 "Inf.Import.XML Full Publicacion "
	#define STR0065 "Seleccione el proceso correspondiente al del archivo XML"
	#define STR0066 "Cliente"
	#define STR0067 "Proceso"
	#define STR0068 "Autor"
	#define STR0069 "Reo"
	#define STR0070 "Tipo de accion"
	#define STR0071 "Caso"
	#define STR0072 "Comarca"
	#define STR0073 "Foro / Tribunal"
	#define STR0074 "Jurisdiccion / Organismo"
	#define STR0075 "Texto de la publicacion"
	#define STR0076 "Cod.Interno"
	#define STR0077 "Codigo proceso"
	#define STR0078 "vinculado al numero proceso"
	#define STR0079 "Atencion"
	#define STR0080 "rellenado. El vinculo no se efectuara por el codigo "
	#define STR0081 "Cod.Imp."
	#define STR0082 "Cod.Proceso"
	#define STR0083 "Informe importaciones XML"
	#define STR0084 "Informe de las importaciones XML importadas para publicaciones"
	#define STR0085 "JURR020"
	#define STR0086 "Importacion publicacion"
	#define STR0087 "Cod.Imp."
	#define STR0088 "Publicaciones"
	#define STR0089 "Seleccionando Registros:"
	#define STR0090 "Num.Proceso"
	#define STR0091 "Tienda"
	#define STR0092 "No se localizaron publicaciones con proeso vinculado para realizar el vinculo."
	#define STR0093 "No existe ningun proceso seleccionado en las Publicaciones Localizadas"
	#define STR0094 "Importacion realiza, pero no se identifico la Instancia Actual en los siguientes procesos,"
	#define STR0095 "antes de conciliar verificar el archivo a identificar la Instancia Actual de los numeros de los siguientes procesos:"
	#define STR0096 "Error al abrir el archivo XML"
	#define STR0097 "¡Al realizar esta operacion el sistema grabara todas las modificaciones hechas en la pantalla! ¿Desea continuar?"
	#define STR0098 "Refresh"
	#define STR0099 "Id del formulario de origen: "
	#define STR0100 "Id del campo de origen: "
	#define STR0101 "Id del formulario de error: "
	#define STR0102 "Id del campo de error: "
	#define STR0103 "Id del error: "
	#define STR0104 "Mensaje de error: "
	#define STR0105 "Mensaje de solucion: "
	#define STR0106 "Valor atribuido: "
	#define STR0107 "Valor anterior: "
	#define STR0108 "Error en la conciliacion: "
	#define STR0109 "Escoja el tipo de importacion"
	#define STR0110 "Importacion XML"
	#define STR0111 "Importacion de archivo XML. Se necesita seleccionar el documento si ya existan publicaciones importadas."
	#define STR0112 "Importación #1"
	#define STR0113 "Importación de datos vía #1. Seleccione un período con intervalo máximo de 30 días para filtro."
	#define STR0114 "Documentos adjuntos"
	#define STR0115 "Archivos texto"
	#define STR0116 "Visualizar"
	#define STR0117 "Incluir"
	#define STR0118 "Modificar"
	#define STR0119 "Borrado"
	#define STR0120 "Camino:"
	#define STR0121 "Camino importacion"
	#define STR0122 "Archivo XML"
	#define STR0123 "Tipo Archivo XML"
	#define STR0124 "Cant. Localizadas"
	#define STR0125 "Ctd. Publicaciones localizadas"
	#define STR0126 "Cant. Borradas"
	#define STR0127 "Ctd. Publicaciones borradas"
	#define STR0128 "Cant. Probables"
	#define STR0129 "Ctd. Publicaciones probables"
	#define STR0130 "Cant. Importadas"
	#define STR0131 "Ctd. Publicaciones importadas"
	#define STR0132 "Cant. No localizadas"
	#define STR0133 "Ctd. Publicaciones no localizadas"
	#define STR0134 "Cant. Duplicados"
	#define STR0135 "Ctd. Procesos duplicados"
	#define STR0136 "Publicaciones importadas"
	#define STR0137 "Publicaciones localizadas"
	#define STR0138 "Publicaciones no localizadas"
	#define STR0139 "Procesos duplicados"
	#define STR0140 "Publicaciones borradas"
	#define STR0141 "Publicaciones probables"
	#define STR0142 "Camino"
	#define STR0143 "Informaciones publicaciones"
	#define STR0144 "Rellene el documento para importacion"
	#define STR0145 "Rellene las fechas"
	#define STR0146 "Filtro incorrecto. Fecha inicial esta mayor que fecha final"
	#define STR0147 "Periodo maximo para filtro es de 30 dias. ¡Verifique!"
	#define STR0148 "Hay mas de una publicacion marcada para visualizacion. Marque solamente una."
	#define STR0149 "Operacion no permitida para publicaciones en esta situacion."
	#define STR0150 "APERTURA DE LA FACTURA: "
	#define STR0151 "ABOGADOS DEL PROCESO: "
	#define STR0152 "PARTES DEL PROCESO: "
	#define STR0153 "DESCRIPCION: "
	#define STR0154 "APERTURA DE LA FACTURA: "
	#define STR0155 " ¡Archivo importado con exito! "
	#define STR0156 "No se permite esta operacion porque no se indico publicacion importada para modificaciones. ¡Importe una publicacion o informe una para que se realice esa operacion!"
	#define STR0157 "Palabra-Clave"
	#define STR0158 "Rellene tambien el campo de tienda para realizar ese filtro"
	#define STR0159 "Rellene tambien el campo de cliente para realizar ese filtro"
	#define STR0160 "No se localizo proceso para visualizacion."
	#define STR0161 "No se selecciono ninguna publicacion para vinculo. ¡Verifique!"
	#define STR0162 "Existe publicacion seleccionada que no esta vinculada al proceso. Vincule para que sea posible realizar la conciliacion."
	#define STR0163 "No hay esa palabra en el archivo de palabra clave, por lo tanto ese filtro se desconsiderara."
	#define STR0164 "¿Desea actualizar el número del proceso?"
	#define STR0165 "Informe un código de la etapa procesual válido en el parámetro 'MV_JNT4FAS'."
	#define STR0166 " Operación de conciliación anulada. "
	#define STR0167 "Informe un valor válido para el parámetro 'MV_JNT4CLI'."
	#define STR0168 "Para ejecutar esta rutina es necesario solicitar el paquete del llamado TQJAI6. Aplicar el patch y ejecutar el update de base 78, de acuerdo con el boletín técnico de este llamado."
	#define STR0169 "Filtrar por palabra clave"
	#define STR0170 "¡Ninguna palabra clave seleccionada o digitada!"
	#define STR0171 "Total de registros filtrados: "
	#define STR0172 "Filtro de palabra clave"
	#define STR0173 "DOS CLIC PARA SELECCIONAR LA PALABRA CLAVE:"
	#define STR0174 "DIGITE LAS PALABRAS CLAVES SEPARADAS POR COMA:"
	#define STR0175 "Resultado de la prueba de filtrado:"
	#define STR0176 "Probar"
	#define STR0177 "Filtrar"
	#define STR0178 "Anular"
	#define STR0179 "[¡Ninguna palabra clave registrada!]"
	#define STR0180 "Reprocesar"
	#define STR0181 "Error en la eliminación del archivo"
	#define STR0182 "No se permiten caracteres especiales"
	#define STR0183 "Actualizando registros"
	#define STR0184 "Cliente no localizado, ¡verifique la digitación del código del Cliente y tienda!"
	#define STR0185 "¡No se localizó ningún asunto jurídico con los parámetros solicitados!"
	#define STR0186 "Actualizando las informaciones de la pantalla"
	#define STR0187 "Cargando informaciones de las publicaciones no localizadas"
	#define STR0188 "Procesando las publicaciones no localizadas"
	#define STR0189 "Conciliando publicación #1 de #2"
	#define STR0190 "Código de palabra-clave inválido"
	#define STR0191 "¿Utilizar operador de agrupación <OU> ?"
	#define STR0192 "FIltro de agrupadores"
	#define STR0193 "HAGA DOS CLIC PARA SELECCIONAR EL AGRUPADOR"
	#define STR0194 "Filtrar por agrupadores"
	#define STR0195 "Agrupadores"
	#define STR0196 "[Ningún agrupador registrado.]"
	#define STR0197 "¡El agrupador seleccionado no existe!"
	#define STR0198 "¡No existen registros para los filtros seleccionados!"
	#define STR0199 "Marcar todos"
	#define STR0200 "Desmarca todos"
	#define STR0201 "Invertir selección"
	#define STR0202 "Acto procesal automático"
	#define STR0203 "Manual"
	#define STR0204 "Automático"
	#define STR0205 "Algunas publicaciones no se conciliaron porque no se encontró el Acto procesal automático."
	#define STR0206 "Utilice la opción Conciliar Manual, para conciliar."
	#define STR0207 "Ningún registro encontrado."
	#define STR0208 "Borrando publicaciones seleccionadas"
	#define STR0209 "Restaurando publicaciones seleccionadas"
	#define STR0210 "Vinculando publicaciones seleccionadas"
	#define STR0211 "Contando publicaciones..."
	#define STR0212 "Aplicando filtro..."
	#define STR0213 "Para conciliar Informe un acto procesal."
	#define STR0214 "Para conciliar registre por lo menos una palabra clave, en acto procesal automático."
	#define STR0215 "Archivo"
	#define STR0216 "Grabar como"
	#define STR0217 "Publicaciones"
	#define STR0218 "¿Desea abrir el archivo #1?"
	#define STR0219 "El archivo #1 no puede abrirse"
	#define STR0220 "Archivo generado con éxito, camino:"
	#define STR0221 "Error al efectuar download del archivo"
	#define STR0222 "Error al generar el archivo"
	#define STR0223 "Exportar publicaciones"
#else
	#ifdef ENGLISH
		#define STR0001 "Attached Documents(*.XML)|*.XML| File Texts(*.Txt)|*.TXT|"
		#define STR0002 "Procergs"
		#define STR0003 "Da-Justi"
		#define STR0004 "Highlight"
		#define STR0005 "Reconciled Publications"
		#define STR0006 "Localized Publications"
		#define STR0007 "Non localized Publications"
		#define STR0008 "Duplicate Publications"
		#define STR0009 "Deleted Publications"
		#define STR0010 "Publication Import"
		#define STR0011 "Localization / File Type"
		#define STR0012 "Publication Type"
		#define STR0013 "Path:"
		#define STR0014 "Select the File"
		#define STR0015 "Import File"
		#define STR0016 "Path not entered!"
		#define STR0017 "Enter the path!"
		#define STR0018 "XML file status"
		#define STR0019 "Amt of Imported Publications"
		#define STR0020 "Amt of Localized Publications"
		#define STR0021 "Amt of Duplicate Publications"
		#define STR0022 "Amt of Reconciled Publications"
		#define STR0023 "Amt of Non Localized Publications"
		#define STR0024 "Amt of Deleted Publications"
		#define STR0025 "Search Filter"
		#define STR0026 "Start Date"
		#define STR0027 "End Date"
		#define STR0028 "Display with key words"
		#define STR0029 "Document Number"
		#define STR0030 "Display only last XML imported"
		#define STR0031 "Progress Detail"
		#define STR0032 "Reconcile"
		#define STR0033 "Search"
		#define STR0034 "Clear"
		#define STR0035 "Exit"
		#define STR0036 "Processing Conciliation"
		#define STR0037 "Wait"
		#define STR0038 "Key Word"
		#define STR0039 "Legal Matter Code"
		#define STR0040 "Exclusion Dt."
		#define STR0041 "Exclusion User"
		#define STR0042 "Invert Selection"
		#define STR0043 "Import publishing"
		#define STR0044 "There are no imported files to search"
		#define STR0045 "Imported files"
		#define STR0046 "Search"
		#define STR0047 "File"
		#define STR0048 "ImportDt."
		#define STR0049 "Type of file"
		#define STR0050 "Import date:"
		#define STR0051 "Previously imported"
		#define STR0052 "File not found"
		#define STR0053 "Check it"
		#define STR0054 "File not compatible with XML File Type"
		#define STR0055 "Proceedings"
		#define STR0056 "Reconciliation"
		#define STR0057 "Process successfully finished."
		#define STR0058 "View Process"
		#define STR0059 "Import ReportXMLImportRep."
		#define STR0060 "Publication Active Folder XMLImportRep."
		#define STR0061 "Delete"
		#define STR0062 "Link Process"
		#define STR0063 "Restore"
		#define STR0064 "Full Publication XMLImportRep. "
		#define STR0065 "Select process corresponding to XML file"
		#define STR0066 "Customer"
		#define STR0067 "Process"
		#define STR0068 "Author"
		#define STR0069 "Defendant"
		#define STR0070 "Action Type"
		#define STR0071 "Case"
		#define STR0072 "Jud.District"
		#define STR0073 "Venue / Court"
		#define STR0074 "Court / Body"
		#define STR0075 "Publication text"
		#define STR0076 "Internal Cd."
		#define STR0077 "Process Code"
		#define STR0078 "linked to Process Number"
		#define STR0079 "Attention"
		#define STR0080 "filled out. Binding not made by the Code "
		#define STR0081 "Imp.Cd."
		#define STR0082 "ProcessCd."
		#define STR0083 "XML Import Report"
		#define STR0084 "Report of XML imported to publications"
		#define STR0085 "JURR020"
		#define STR0086 "Publication Import"
		#define STR0087 "Imp.Cd."
		#define STR0088 "Publications"
		#define STR0089 "Selecting records:"
		#define STR0090 "Process Nr."
		#define STR0091 "Store"
		#define STR0092 "Publications were not found with linked process."
		#define STR0093 "There is no process selected in Localized Publications"
		#define STR0094 "Imported, however the Current Instance was not found in the process bellow,"
		#define STR0095 "before reconciling, check the file and identify the Current Instance of the following number of process(es):"
		#define STR0096 "Error when opening XML file"
		#define STR0097 "By making this operation, all the changes made on the screen are saved! Continue?"
		#define STR0098 "Refresh"
		#define STR0099 "Id of the origin form: "
		#define STR0100 "Id of the origin field: "
		#define STR0101 "Id of error form: "
		#define STR0102 "Error field Id: "
		#define STR0103 "Error Id: "
		#define STR0104 "Error message: "
		#define STR0105 "Solution message: "
		#define STR0106 "Value given: "
		#define STR0107 "Previous Value: "
		#define STR0108 "Error in reconciliation: "
		#define STR0109 "Choose type of import"
		#define STR0110 "Import XML"
		#define STR0111 "XML File Import. It is necessary select document in case there are imported publications."
		#define STR0112 "Import #1"
		#define STR0113 "Data import via #1. Select a period with maximum interval of 30 days for filter."
		#define STR0114 "Attached Documents"
		#define STR0115 "Text Files"
		#define STR0116 "View"
		#define STR0117 "Add"
		#define STR0118 "Edit"
		#define STR0119 "Deletion"
		#define STR0120 "Path:"
		#define STR0121 "Import Path"
		#define STR0122 "XML File"
		#define STR0123 "XML File Type"
		#define STR0124 "Amt. Localized"
		#define STR0125 "Amt. Localized Publishings"
		#define STR0126 "Amt. Deleted"
		#define STR0127 "Amt. Deleted Publishings"
		#define STR0128 "Amt. Probable"
		#define STR0129 "Amt. Probable Publishings"
		#define STR0130 "Amt. Imported"
		#define STR0131 "Amt. Imported Publishings"
		#define STR0132 "Amt. Not Localized"
		#define STR0133 "Amt not Localized Publishings"
		#define STR0134 "Amt. Duplicated"
		#define STR0135 "Amt Doubled Processes"
		#define STR0136 "Imported Publishings"
		#define STR0137 "Localized Publications"
		#define STR0138 "Not Localized Publishings"
		#define STR0139 "Doubled Processes"
		#define STR0140 "Deleted Publishings"
		#define STR0141 "Probable Publishings"
		#define STR0142 "Path"
		#define STR0143 "Publication Information"
		#define STR0144 "Select document to import"
		#define STR0145 "Complete the dates"
		#define STR0146 "Incorrect Filter. Initial data greater than final date"
		#define STR0147 "The maximum period for the filter is 30 days. Check it!"
		#define STR0148 "There is more than one publication marked to view. Mark only one."
		#define STR0149 "Operation not allowed for publication in this situation."
		#define STR0150 "INVOICE OPENING: "
		#define STR0151 "PROCESS LAWYERS: "
		#define STR0152 "PROCESS PARTS: "
		#define STR0153 "DESCRIPTION: "
		#define STR0154 "INVOICE OPENING: "
		#define STR0155 " File successfully imported! "
		#define STR0156 "This operation is not allowed as imported publications is not indicated for changes. Import a publication or enter one to perform this operations!"
		#define STR0157 "Key word"
		#define STR0158 "Fill out the store field to do this filter too"
		#define STR0159 "Fill out the customer field to do this filter too"
		#define STR0160 "No process found for viewing."
		#define STR0161 "No publication selected for linking. Check it!"
		#define STR0162 "A selected publication not linked to process exists. Link it so you may perform the reconciliation."
		#define STR0163 "Word does not exist in the key-word register, therefore, this filter is disregarded."
		#define STR0164 "Update process number?"
		#define STR0165 "Enter code of valid procedure stage in parameter 'MV_JNT4FAS'."
		#define STR0166 " Conciliation operation canceled. "
		#define STR0167 "Enter value valid for parameter 'MV_JNT4CLI'."
		#define STR0168 "To run this routine, request package of ticket TQJAI6. Apply patch and run update  of basis 78, according to technical newsletter of this ticket."
		#define STR0169 "Filter by Keyword"
		#define STR0170 "No key word selected or typed!"
		#define STR0171 "Total of records filtered: "
		#define STR0172 "Keyword Filter"
		#define STR0173 "DOUBLE-CLICK TO SELECT KEY WORD:"
		#define STR0174 "ENTER KEY WORDS SEPARATED BY COMMAS:"
		#define STR0175 "Filtering test result"
		#define STR0176 "Test"
		#define STR0177 "Filter"
		#define STR0178 "Cancel"
		#define STR0179 "[No key word registered!]"
		#define STR0180 "Reprocess"
		#define STR0181 "Error while deleting the file"
		#define STR0182 "Special characters are not allowed"
		#define STR0183 "Updating Records"
		#define STR0184 "Customer not found, check typing of Customer and store code!"
		#define STR0185 "No legal subject with requested parameters!"
		#define STR0186 "Update screen information"
		#define STR0187 "Loading information of publication not located"
		#define STR0188 "Processing publishing not lcoated"
		#define STR0189 "Reconciling publication #1 to #2"
		#define STR0190 "Invalid Key Word Code"
		#define STR0191 "Use grouping operator <OU> ?"
		#define STR0192 "Group Filter"
		#define STR0193 "DOUBLE-CLICK TO SELECT GROUP"
		#define STR0194 "Filter by Group"
		#define STR0195 "Group"
		#define STR0196 "[No employee registered!]"
		#define STR0197 "The consolidator selected does not exist!"
		#define STR0198 "No records found for the filters selected!"
		#define STR0199 "Select All"
		#define STR0200 "Uncheck All"
		#define STR0201 "Invert Selection"
		#define STR0202 "Automatic Proceeding Act"
		#define STR0203 "Manual"
		#define STR0204 "Automatic"
		#define STR0205 "Some postings were not reconciled because the Automatic Procedure Act was not found"
		#define STR0206 "Use option Manual Reconciliation."
		#define STR0207 "No record found"
		#define STR0208 "Deleting selected publications"
		#define STR0209 "Restoring selected publications"
		#define STR0210 "Binding selected publications"
		#define STR0211 "Accounting publications..."
		#define STR0212 "Applying filter..."
		#define STR0213 "To reconcile, enter procedural act."
		#define STR0214 "To reconcile, register at least a key word, in automatic procedural act."
		#define STR0215 "File"
		#define STR0216 "Save As"
		#define STR0217 "Publications"
		#define STR0218 "Open file #1?"
		#define STR0219 "#1 file cannot be opened "
		#define STR0220 "File successfully generated, path: "
		#define STR0221 "Error when downloading file"
		#define STR0222 "Error when creating file"
		#define STR0223 "Export Publications"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Documentos Anexos(*.XML)|*.XML| Ficheiros Texto(*.Txt)|*.TXT|", "Documentos Anexos(*.XML)|*.XML| Arquivos Texto(*.Txt)|*.TXT|" )
		#define STR0002 "Procergs"
		#define STR0003 "Da-Justi"
		#define STR0004 "Destaque"
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Publicações conciliadas", "Publicações Conciliadas" )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Publicações localizadas", "Publicações Localizadas" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Publicações não localizadas", "Publicações Não localizadas" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Publicações duplicadas", "Publicações Duplicadas" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Publicações excluídas", "Publicações Excluidas" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Importação de publicações", "Importação de Publicações" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Localização / Tipo de Ficheiros", "Localização / Tipo de Arquivos" )
		#define STR0012 "Tipo de Publicação"
		#define STR0013 "Caminho:"
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Seleccione o ficheiro", "Selecione o Arquivo" )
		#define STR0015 "Importar Arquivo"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Caminho não informado.", "Caminho não informado!!!" )
		#define STR0017 "Informe o caminho"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Estado do ficheiro XML", "Status do Arquivo XML" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Qtd. de publicações importadas", "Qtde de Publicações Importadas" )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Qtd. de publicações localizadas", "Qtde de Publicações Localizadas" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Qtd. de publicações duplicadas", "Qtde de Publicações Duplicadas" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Qtd. de publicações conciliadas", "Qtde de Publicações Conciliadas" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Qtd. de publicações não localizadas", "Qtde de Publicações Não localizadas" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Qtd. de publicações excluídas", "Qtde de Publicações Excluidas" )
		#define STR0025 "Filtro de Pesquisa"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Data inicial", "Data Inicial" )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Data final", "Data Final" )
		#define STR0028 "Exibir com palavras-chave"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Nome do documento", "Nome do Documento" )
		#define STR0030 "Exibir apenas o último XML importado"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Detalhamento do andamento", "Detalhamento do Andamento" )
		#define STR0032 "Conciliar"
		#define STR0033 "Pesquisar"
		#define STR0034 "Limpar"
		#define STR0035 "Sair"
		#define STR0036 "Processando Conciliação"
		#define STR0037 "Aguarde"
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Palavra-chave", "Palavra Chave" )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Cód.do assunto jurídico", "Cod do Assunto Juridico" )
		#define STR0040 "Dt.Exclusão"
		#define STR0041 "Usuário Exclusão"
		#define STR0042 "Inverte Selecão"
		#define STR0043 "Importação de publicações"
		#define STR0044 "Não há arquivos importados para consultar"
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Ficheiros importados", "Arquivos importados" )
		#define STR0046 "Pesquisar"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Ficheiro", "Arquivo" )
		#define STR0048 "Dt.Import."
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Tipo de ficheiro", "Tipo de Arquivo" )
		#define STR0050 "Data da Importação:"
		#define STR0051 "Importado anteriormente."
		#define STR0052 "Arquivo não encontrado"
		#define STR0053 "Verifique"
		#define STR0054 "Arquivo não compativel com o Tipo de Arquivo XML"
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Acto Processual", "Ato Processual" )
		#define STR0056 "Conciliação"
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Processo efectuado com sucesso.", "Processo efetuado com sucesso." )
		#define STR0058 "Visualizar processo"
		#define STR0059 "Rel.Import.XML Publicação"
		#define STR0060 "Rel.Import.XML Folder Ativa Publicação"
		#define STR0061 "Excluir"
		#define STR0062 "Vincular processo"
		#define STR0063 "Restaurar"
		#define STR0064 "Rel.Import.XML Full Publicação "
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Seleccione o processo correspondente ao do ficheiro XML", "Selecione o processo correspondente ao do arquivo XML" )
		#define STR0066 "Cliente"
		#define STR0067 "Processo"
		#define STR0068 "Autor"
		#define STR0069 "Réu"
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Tipo de acção", "Tipo de ação" )
		#define STR0071 "Caso"
		#define STR0072 "Comarca"
		#define STR0073 "Foro / Tribunal"
		#define STR0074 "Vara / Órgão"
		#define STR0075 "Texto da publicação"
		#define STR0076 "Cód.Interno"
		#define STR0077 "Código Processo"
		#define STR0078 "vinculado ao Número Processo"
		#define STR0079 "Atenção"
		#define STR0080 "preenchido. O vínculo não será efetuado pelo Código "
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "Cód.Imp.", "Cod.Imp." )
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Cód.Processo", "Cod.Processo" )
		#define STR0083 "Relatório Importações XML"
		#define STR0084 "Relatório das Importações XML importadas para publicações"
		#define STR0085 "JURR020"
		#define STR0086 "Importação Publicação"
		#define STR0087 If( cPaisLoc $ "ANG|PTG", "Cód.Imp.", "Cod.Imp." )
		#define STR0088 "Publicações"
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "A seleccionar registos:", "Selecionando Registros:" )
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "No.Processo", "Num.Processo" )
		#define STR0091 "Loja"
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "Não foram localizadas as publicações com processo vinculado para realizar o vínculo.", "Não foram lozalizados publicações com processo vinculado para realizar o vinculo." )
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "Não há nenhum processo seleccionado nas Publicações Localizadas", "Não há nenhum processo selecionado nas Publicações Localizadas" )
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Importação realizada, mas não identificou-se a Instância Actual nos processo(s) abaixo,", "Importação realiza, mas não foi identificado a Instância Atual nos processo(s) abaixo," )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "antes de conciliar, verificar o registo e idenficar a Instância Actual do(s) número(s) de processo(s) a seguir:", "antes de conciliar verificar o cadastro e idenficar a Instância Atual do(s) número(s) de processo(s) a seguir:" )
		#define STR0096 "Erro ao abrir o arquivo XML"
		#define STR0097 "Ao realizar esta operação o sistema salvará todas as alterações feitas na tela! Deseja continuar?"
		#define STR0098 "Refresh"
		#define STR0099 "Id do formulário de origem: "
		#define STR0100 "Id do campo de origem: "
		#define STR0101 "Id do formulário de erro: "
		#define STR0102 "Id do campo de erro: "
		#define STR0103 "Id do erro: "
		#define STR0104 "Mensagem do erro: "
		#define STR0105 "Mensagem da solução: "
		#define STR0106 "Valor atribuido: "
		#define STR0107 "Valor anterior: "
		#define STR0108 "Erro na conciliação: "
		#define STR0109 "Escolha o tipo de importação"
		#define STR0110 "Importação XML"
		#define STR0111 "Importação de arquivo XML. É necessário selecionar o documento caso já existam publicações importadas."
		#define STR0112 "Importação #1"
		#define STR0113 "Importação de dados via #1. Selecione um período com intervalo máximo de 30 dias para filtro."
		#define STR0114 "Documentos Anexos"
		#define STR0115 "Arquivos Texto"
		#define STR0116 "Visualizar"
		#define STR0117 "Incluir"
		#define STR0118 "Alterar"
		#define STR0119 "Exclusão"
		#define STR0120 "Caminho:"
		#define STR0121 "Caminho importação"
		#define STR0122 "Arquivo XML"
		#define STR0123 "Tipo Arquivo XML"
		#define STR0124 "Qtd. Localizadas"
		#define STR0125 "Qtd Publicações Localizadas"
		#define STR0126 "Qtd. Excluídas"
		#define STR0127 "Qtd Publicações Excluídas"
		#define STR0128 "Qtd. Prováveis"
		#define STR0129 "Qtd Publicações Prováveis"
		#define STR0130 "Qtd. Importadas"
		#define STR0131 "Qtd Publicações Importadas"
		#define STR0132 "Qtd. Não Localizadas"
		#define STR0133 "Qtd Publicações não Localizadas"
		#define STR0134 "Qtd. Duplicados"
		#define STR0135 "Qtd Processos Duplicados"
		#define STR0136 "Publicações Importadas"
		#define STR0137 "Publicações Localizadas"
		#define STR0138 "Publicações não Localizadas"
		#define STR0139 "Processos Duplicados"
		#define STR0140 "Publicações Excluídas"
		#define STR0141 "Publicações Prováveis"
		#define STR0142 "Caminho"
		#define STR0143 "Informações Publicações"
		#define STR0144 "Preencha o documento para importação"
		#define STR0145 "Preencha as datas"
		#define STR0146 "Filtro incorreto. Data inicial está maior que data final"
		#define STR0147 "Periodo máximo para filtro é de 30 dias. Verifique!"
		#define STR0148 "Existe mais de uma publicação marcada para visualização. Marque apenas uma."
		#define STR0149 "Operação não permitida para publicações nesta situação."
		#define STR0150 "ABERTURA DA NOTA: "
		#define STR0151 "ADVOGADOS DO PROCESSO: "
		#define STR0152 "PARTES DO PROCESSO: "
		#define STR0153 "DESCRICAO: "
		#define STR0154 "ABERTURA DA NOTA: "
		#define STR0155 " Arquivo importado com sucesso! "
		#define STR0156 "Esta operação não é permitida pois não foi indicada publicação importada para modificações. Importe uma publicação ou informe uma para realizar essa operação!"
		#define STR0157 "Palavra-Chave"
		#define STR0158 "Preencha também o campo de loja para realizar esse filtro"
		#define STR0159 "Preencha também o campo de cliente para realizar esse filtro"
		#define STR0160 "Não foi localizado processo para visualização."
		#define STR0161 "Não foi selecionada nenhuma publicação para vínculo. Verifique!"
		#define STR0162 "Existe publicação selecionada que não está vinculada a processo. Vincule para que seja possível realizar a conciliação."
		#define STR0163 "Palavra não existe no cadastro de palavra-chave, portanto esse filtro será desconsiderado."
		#define STR0164 "Deseja atualizar o número do processo?"
		#define STR0165 "Informe um código de fase processual válido no parametro 'MV_JNT4FAS'."
		#define STR0166 " Operacao de conciliação cancelada. "
		#define STR0167 "Informe um valor válido para o parametro 'MV_JNT4CLI'."
		#define STR0168 "Para executar esta rotina é necessário solicitar o pacote do chamado TQJAI6. Aplicar o patch e executar o update de base 78, conforme boletim técnico deste chamado."
		#define STR0169 "Filtrar por Palavra-chave"
		#define STR0170 "Nenhuma palavra-chave selecionada ou digitada!"
		#define STR0171 "Total de registros filtrados: "
		#define STR0172 "Filtro de Palavra-chave"
		#define STR0173 "DOIS CLIQUES PARA SELECIONAR A PALAVRA-CHAVE:"
		#define STR0174 "DIGITE AS PALAVRAS-CHAVES SEPARADAS POR VÍRGULA:"
		#define STR0175 "Resultado do teste de filtragem:"
		#define STR0176 "Testar"
		#define STR0177 "Filtrar"
		#define STR0178 "Cancelar"
		#define STR0179 "[Nenhuma palavra chave cadastrada!]"
		#define STR0180 "Reprocessar"
		#define STR0181 "Erro na eliminação do arquivo"
		#define STR0182 "Caracteres especiais não são permitidos"
		#define STR0183 "Atualizando Registros"
		#define STR0184 "Cliente não localizado, verifique a digitação do codigo do Cliente e loja!"
		#define STR0185 "Não foi localizado nenhum assunto jurídico com os parâmetros solicitados!"
		#define STR0186 "Atualizando as informações da tela"
		#define STR0187 "Carregando informações das publicações não localizadas"
		#define STR0188 "Processando as publicações não localizadas"
		#define STR0189 "Conciliando publicação #1 de #2"
		#define STR0190 "Código de Palavra-Chave inválido"
		#define STR0191 "Utilizar operador de agrupamento <OU> ?"
		#define STR0192 "FIltro de Agrupadores"
		#define STR0193 "DOIS CLIQUES PARA SELECIONAR O AGRUPADOR"
		#define STR0194 "Filtrar por Agrupadores"
		#define STR0195 "Agrupadores"
		#define STR0196 "[Nenhum agrupador cadastrado!]"
		#define STR0197 "O Agrupador selecionado não existe!"
		#define STR0198 "Não existem registros para os filtros selecionados!"
		#define STR0199 "Marcar Todos"
		#define STR0200 "Desmarcar Todos"
		#define STR0201 "Inverter Seleção"
		#define STR0202 "Ato Processual Automático"
		#define STR0203 "Manual"
		#define STR0204 "Automático"
		#define STR0205 "Algumas Publicações não foram conciliadas, porque não foi encontrado o Ato Processual Automático."
		#define STR0206 "Utilize a apção Conciliar Manual, para concilia-las."
		#define STR0207 "Nenhum registro encontrado"
		#define STR0208 "Excluíndo publicações selecionadas"
		#define STR0209 "Restaurando publicações selecionadas"
		#define STR0210 "Vinculando publicações selecionadas"
		#define STR0211 "Contando publicações..."
		#define STR0212 "Aplicando filtro..."
		#define STR0213 "Para conciliar Informe um ato processual."
		#define STR0214 "Para conciliar cadastre ao menos uma palavra chave, em ato processual automatico."
		#define STR0215 "Arquivo"
		#define STR0216 "Salvar como"
		#define STR0217 "Publicações"
		#define STR0218 "Deseja abrir o arquivo #1 ?"
		#define STR0219 "O arquivo #1 não pode ser aberto "
		#define STR0220 "Arquivo gerado com sucesso, caminho: "
		#define STR0221 "Erro ao efetuar o download do arquivo"
		#define STR0222 "Erro ao gerar arquivo"
		#define STR0223 "Exportar Publicações"
	#endif
#endif
