#ifdef SPANISH
	#define STR0001 "Operacion de Prefacturas"
	#define STR0002 "Prefacturas"
	#define STR0003 "Contratos"
	#define STR0004 "Casos"
	#define STR0005 "Analisis"
	#define STR0006 "Minuta"
	#define STR0007 "Definitivo"
	#define STR0008 "Time-Sheet"
	#define STR0009 "Gastos"
	#define STR0010 "Asiento Controlado"
	#define STR0011 "Envio"
	#define STR0012 "Retorno"
	#define STR0013 "Emitir Factura"
	#define STR0014 "Emitir Minuta"
	#define STR0015 "Marcar"
	#define STR0016 "Desmarcar"
	#define STR0017 "Buscar"
	#define STR0018 "Visualizar"
	#define STR0019 "Modificar"
	#define STR0020 "Nuevos"
	#define STR0021 "Situacion"
	#define STR0022 "Revision"
	#define STR0023 "Todos"
	#define STR0024 "Anular"
	#define STR0025 "Rehacer"
	#define STR0026 "Prefactura"
	#define STR0027 "Fact. Adicional"
	#define STR0028 "Historial"
	#define STR0029 "Fijo"
	#define STR0030 "Profesionales"
	#define STR0031 "Exito"
	#define STR0032 "Copiar Red. PF."
	#define STR0033 "Redaccion"
	#define STR0034 "Val. Original"
	#define STR0035 "Modelo de Datos de prefactura"
	#define STR0036 "Datos de la prefactura"
	#define STR0037 "Datos de los Fijo de la Prefactura"
	#define STR0038 "Datos de los Time Sheets de los Casos de la prefactura"
	#define STR0039 "Datos de los Exitos de los Casos de la prefactura"
	#define STR0040 "Datos de los Asientos Tabla de los Casos de la Prefactura"
	#define STR0041 "Datos de las Facturaciones Adicionales"
	#define STR0042 "Datos de los Gastos de los Casos de la prefactura"
	#define STR0043 "Datos de los Casos de la Prefactura"
	#define STR0044 "Datos de los Profesionales de los Casos de la prefactura"
	#define STR0045 "Datos de los Historiales de la Prefactura"
	#define STR0046 "Datos de los Contratos de la Prefactura"
	#define STR0047 "Operacion de la Prefactura"
	#define STR0048 "¿Confirma la cancelacion?"
	#define STR0049 "¡Atencion! Todas las prefacturas marcadas seran canceladas."
	#define STR0050 "Espere"
	#define STR0051 "Anulando la factura previa..."
	#define STR0052 "Anulacion terminada."
	#define STR0053 "Error al actualizar limpiar flag de marcacion para "
	#define STR0054 "Error: ["
	#define STR0055 "No es posible modificar la situación de la(s) siguiente(s) factura(s) previa(s)."
	#define STR0056 "Error al actualizar para situacion "
	#define STR0057 "Operación solo se permite para facturas previas en situación "
	#define STR0058 "Informar"
	#define STR0059 "Fecha"
	#define STR0060 "La fecha no puede estar en blanco."
	#define STR0061 "Hora"
	#define STR0062 "La hora no puede estar en blanco."
	#define STR0063 "Revisor"
	#define STR0064 "Sit. Cobro"
	#define STR0065 "Emitir Factura"
	#define STR0066 "Emitir"
	#define STR0067 "No se permite rehacer prefactura en esta situacion"
	#define STR0068 "Rehacer la prefactura: "
	#define STR0069 "Resultado"
	#define STR0070 "Es necesario informar el tipo de resultado para rehacer la factura previa."
	#define STR0071 "¡Error al rehacer la prefactura!"
	#define STR0072 "Origem da Redação "
	#define STR0073 "Descripcion de los Time Sheets"
	#define STR0074 "Factura"
	#define STR0075 "Caso"
	#define STR0076 "Oficina"
	#define STR0077 "Ok"
	#define STR0078 "Informe la factura."
	#define STR0079 "Analisis"
	#define STR0080 "Confirma el cambio para situacion "
	#define STR0081 "¡Atencion! Todas las prefacturas marcadas se cambiaran."
	#define STR0082 "¿Confirma la copia de la redaccion para los casos originales?"
	#define STR0083 "Componer redaccion de prefactura"
	#define STR0084 "Componer redaccion del caso"
	#define STR0085 "Vuelta valor original de toda prefactura"
	#define STR0086 "Vuelta valor original del caso"
	#define STR0087 "¿Confirma la operacion?"
	#define STR0088 "Se restauraran los valores emitidos de los asientos seleccionados de toda la prefactura. "
	#define STR0089 "Se restauraran los valores emitidos de los asientos seleccionados del caso "
	#define STR0090 "No se permite modificacion de tiempo para tipo de actividad de participacion directa. "
	#define STR0091 "Para esta operacion, anular prefactura"
	#define STR0092 "Para desvincular la factura adicional es necesario anular la prefactura"
	#define STR0093 "¡Es necesario marcar las prefacturas en situacion valida para la operacion de anular!"
	#define STR0094 "Es necesario marcar las prefacturas para efectuar la modificacion en el estatus de la Revision"
	#define STR0095 "Corr Txt TS"
	#define STR0096 "OBS Caso"
	#define STR0097 "¡No es posible efectuar la modificacion, pues el valor nuevo es mayor que el antiguo!"
	#define STR0098 "Error al atribuir el valor"
	#define STR0099 "Alias invalido para esta operacion"
	#define STR0100 "Verificacion"
	#define STR0101 "Impresora"
	#define STR0102 "Pantalla"
	#define STR0103 "Pagadores"
	#define STR0104 "Enviar p/ Fila"
	#define STR0105 "Operaciones"
	#define STR0106 "Tipo de Operaciónes"
	#define STR0107 "Retirar"
	#define STR0108 "WO"
	#define STR0109 "Transferir"
	#define STR0110 "Dividir TS"
	#define STR0111 "Total del porcentaje debe ser igual a 100%"
	#define STR0112 "Total del Porcentaje no puede ser mayor a 100%"
	#define STR0113 "Transferir lo(s) Asiento(s) seleccionado(s) a:"
	#define STR0114 "Grupo"
	#define STR0115 "Cliente"
	#define STR0116 "Tienda"
	#define STR0117 "Caso"
	#define STR0118 "Complete correctamente las informaciones "
	#define STR0119 "La información de etapa, tarea y actividad e-billing no son válidas."
	#define STR0120 "El Caso destino está vinculado a la factura previa '#1' con la situación '#2'."
	#define STR0121 "El Caso destino puede vincularse a la factura previa '#1' con la situación '#2'."
	#define STR0122 "Es necesario marcar las prefacturas para modificar la situacion. "
	#define STR0123 "Salir"
	#define STR0124 "PDF"
	#define STR0125 "Excel"
	#define STR0126 "Word"
	#define STR0127 "¡Operacion concluida!"
	#define STR0128 "No fue posible aplicar las modificaciones"
	#define STR0129 "Ninguno"
	#define STR0130 "Prefactura realizada de nuevo con exito"
	#define STR0131 "No fue posible atribuir valor via recursividad al campo: "
	#define STR0132 "¡Al realizar esta operacion, el sistema guardara todas las modificaciones realizadas en la pantalla!"
	#define STR0133 "ATENCION"
	#define STR0134 "La cantidad de horas para el TS supera el tamano del campo, no sera posible modificar el valor del TS. Anular el procedimiento."
	#define STR0135 "Este contacto no esta activo y no puede ser utilizado."
	#define STR0136 "¡Registro modificado con exito!"
	#define STR0137 "OBS Cliente"
	#define STR0138 "Observacion"
	#define STR0139 "Observacion de Facturacion del Cliente"
	#define STR0140 "Observacion del Caso"
	#define STR0141 "¡Copia efectuada!"
	#define STR0142 "Esta pre posee solo TS, anular o realizar WO del mismo."
	#define STR0143 "Valor debe ser mayor que la suma de los TS con participacion de cliente."
	#define STR0144 "¡Es necesario marcar las prefacturas en situacion valida para la operacion de rehacer!"
	#define STR0145 "Anexos"
	#define STR0146 "Contrato"
	#define STR0147 "Espere..."
	#define STR0148 "Rehaciendo la prefactura..."
	#define STR0149 "Datos de la Division de Prefactura"
	#define STR0150 "Atencion, el valor hora del nuevo participante solo se calculara luego de la confirmacion, ¿continuar?"
	#define STR0151 "El participante no fue modificado"
	#define STR0152 "Filtro por caso"
	#define STR0153 "Filtrar por caso"
	#define STR0154 "Mostrar solo prefacturas anuladas y reemplazadas."
	#define STR0155 "¡No se encontraron prefacturas para el caso informado!"
	#define STR0156 "La factura previa se anuló porque no tiene más asientos."
	#define STR0157 "Error al recuperar el Valor Hora del participante."
	#define STR0158 "WO no efectuado."
	#define STR0159 "WO no efectuado, no se selecciono ningun asiento."
	#define STR0160 "Asientos enviados a WO:"
	#define STR0161 " Time Sheet(s)"
	#define STR0162 " Gasto(s)"
	#define STR0163 " Asiento Controlado(s)"
	#define STR0164 " Parc. Exito"
	#define STR0165 " Parc. Fijo"
	#define STR0166 "WO de Asientos"
	#define STR0167 "Actualizando asientos..."
	#define STR0168 "¡El valor informado es insuficiente para crear nuevos Time Sheets!"
	#define STR0169 "¡Informe un valor positivo!"
	#define STR0170 "Existem modificaciones de valor pendientes, para efectuar nuevas modificaciones, ¡confirme o anule las anteriores!"
	#define STR0171 "Solo se permite apuntar tiempos multiples de "
	#define STR0172 " minutos!"
	#define STR0173 "El sistema esta configurado para UT no fraccionada."
	#define STR0174 "El valor se ajustado a un multiplo de "
	#define STR0175 "Valor debe ser mayor que la suma de los Gastos con prorrateo."
	#define STR0176 "Valor debe ser mayor que la suma de los Gastos con situacion = Concluido."
	#define STR0177 "¡Elija un tipo de ajuste antes de modificar el valor!"
	#define STR0178 "¡Rutina de Prorrateo anulada por el usuario!"
	#define STR0179 "Ambos"
	#define STR0180 "¡No es posible modificar un pagador con factura emitida!"
	#define STR0181 "Existe al menos una pre-factura que no puede anularse pues posee factura(S) valida(S) para uno o mas pagadores!"
	#define STR0182 "Eliminar Filtro"
	#define STR0183 "Es necesario completar fase, tarea y actividad de ebilling en el/los time-sheet(s)."
	#define STR0184 "Observacion - WO"
	#define STR0185 "¡No fue posible actualizar el descuento en al menos uno de los casos de prefactura!"
	#define STR0186 "Indica si el usuario que inicio sesion puede revisar el caso"
	#define STR0187 "Solo es posible modificar el valor de TS si el usuario que inicio sesion es revisor de todos los casos o de la prefactura."
	#define STR0188 "El Descuento no puede ser mayor a 100%"
	#define STR0189 "¡El Descuento no puede ser mayor que la suma de Time Sheet y Fijo del caso!"
	#define STR0190 "¡La suma del valor de Time Sheet y Fijo debe ser mayor que el valor de descuento total!"
	#define STR0191 "Cotizaciones"
	#define STR0192 "Cotizaciones de la prefactura"
	#define STR0193 "Existem modificaciones no confirmadas."
	#define STR0194 "Es necesario informar los valores que se mostraran."
	#define STR0195 "Resumen de los valores de la prefactura"
	#define STR0196 "Totales de la prefactura"
	#define STR0197 "Totales de la Prefactura en la Moneda Nacional"
	#define STR0198 "OBS.: Impuestos no deducidos"
	#define STR0199 "Confirmar las modificaciones antes de activar esta funcionalidad."
	#define STR0200 "Resumen"
	#define STR0201 "Invertir seleccion"
	#define STR0202 "Recalculando Prefactura"
	#define STR0203 "Enviando asientos a WO"
	#define STR0204 "¡No se selecciono ningun TS para la division! Verifique."
	#define STR0205 "Valor de porcentual inválido. ¡Verifiquelo!"
	#define STR0206 "El valor total de descuentos no puede ser mayor que valor de honorarios."
	#define STR0207 "No fue posible dividir los siguiente(s) TimeSheet(s):"
	#define STR0208 "Incluir nuevo TS"
	#define STR0209 "El time sheet incluido no se vinculo a la prefactura porque el cliente, la tienda y el caso de este no se relacionan a la prefactura, o las condiciones de facturacion no permiten su vinculo, o  "
	#define STR0210 "su fecha esta fuera del periodo de referencia de la prefactura."
	#define STR0211 "¡Error al guardar el time-sheet!"
	#define STR0212 "Destino da Redaccion"
	#define STR0213 "¡El nuevo porcentual de aumento es mayor al valor maximo que el campo soporta!"
	#define STR0214 "Acciones en Lote TS"
	#define STR0215 "Emisión/actualización de la factura previa"
	#define STR0216 "Modificacion para definitivo"
	#define STR0217 "Emision de minuta"
	#define STR0218 "Emision de factura"
	#define STR0219 "Anulacion de la prefactura"
	#define STR0220 "Reactivacion de la prefactura por la anulacion de la factura"
	#define STR0221 "¡Esta accion solo se permite en la solapa Prefactura!"
	#define STR0222 "No es posible continuar esta operacion."
	#define STR0223 "El manejo de gastos esta desactivado en el SIGAPFS."
	#define STR0224 "¡El nuevo valor de aumento es mayor que el valor maximo soportado por el campo!"
	#define STR0225 "Esta factura previa se está rehaciendo, por favor aguarde."
	#define STR0226 "La factura previa '#1' esta con el estatus de '#2'."
	#define STR0227 " esta con estatus de "
	#define STR0228 "Inicio - Rehaciendo la factura previa: "
	#define STR0229 "Final - Rehaciendo la factura previa: "
	#define STR0230 "Iniciando la revision..."
	#define STR0231 "Desmarcar todo"
	#define STR0232 "Anulacion de la factura previa"
	#define STR0233 "¡Prefacturas anuladas con exito!"
	#define STR0234 "Una o mas prefacturas no pueden anularse, porque: "
	#define STR0235 "Caso no ajustado"
	#define STR0236 "Participante no ajustado"
	#define STR0237 "La información de cliente y caso no son válidas."
	#define STR0238 "La fecha del registro es posterior a '#1', fecha máxima permitida para digitar registros en el caso."
	#define STR0239 "El caso no permite digitar para este tipo de registro"
	#define STR0240 "Transferencia de registros"
	#define STR0241 " se transfirio(eron) con exito."
	#define STR0242 " se transfirio(eron) con exito."
	#define STR0243 "Redondear horas (e-billing)"
	#define STR0244 "No fue posible realizar el redondeo de las horas. Verifique si el parametro MV_JURTS3 está como .T., de tal manera que permita hora fraccionada."
	#define STR0245 "No fue posible realizar el redondeo."
	#define STR0246 "No hay casos con Time Sheets vinculados."
	#define STR0247 "Redondeo de horas de los Time Sheets."
	#define STR0248 "Obs.: Los registros no se vincularon automáticamente a la factura previa de destino y se encuentran disponibles en la opción 'Nuevos' en Operaciones de factura previa."
	#define STR0249 "La factura previa pasará a la situación '#1'."
	#define STR0250 "¡No se pudo realizar la transferencia!"
	#define STR0251 "Encaminamiento de factura"
	#define STR0252 "Total: "
	#define STR0253 "el timesheet #1"
	#define STR0254 "el gasto #1"
	#define STR0255 "el registro estipulado #1"
	#define STR0256 "No es posible reducir el valor del time sheet debido a otros registros del mismo caso que tienen participacion del cliente."
	#define STR0257 "No fue posible transferir #1 al cliente '#2' y caso '#3'."
	#define STR0258 "La factura previa #1 no tiene más asientos y se anulará."
	#define STR0259 "Transfiriendo los asientos"
	#define STR0260 "Nuevo(s) TimeSheet(s) : "
	#define STR0261 "El valor del timesheet del caso '#1' no puede ser inferior a la suma de sus asientos con participación del cliente."
	#define STR0262 " Informe un valor mayor o igual a #1."
	#define STR0263 " El valor del timesheet de este caso puede modificarse a un valor mayor o igual a #1."
	#define STR0264 "Você não tem permissão para alterar os seguintes Time Sheets: "
	#define STR0265 "Para dividir um Time Sheet, você deve marcá-lo."
	#define STR0266 "No tiene permiso para modificar el siguiente timesheet: "
	#define STR0267 "El revisor no se rellenó. ¡Verifique!"
	#define STR0268 "El participante no se rellenó. ¡Verifique!"
	#define STR0269 "Solapa "
	#define STR0270 "Modificación de prefactura"
	#define STR0271 "¡No fue posible realizar las modificaciones, el asiento tiene una factura previa en proceso de revisión!"
	#define STR0272 "Modificar casos a no revisados"
	#define STR0273 "La operación Modificar revisor solo está disponible para las facturas previas en situación 'Análisis', 'En revisión' o 'Modificada'. ¡Verifique!"
	#define STR0274 "Modificar revisor"
	#define STR0275 "¿Desea concluir la revisión de todos los casos de la factura previa?"
	#define STR0276 "Factura previa enviada para revisión."
	#define STR0277 "Revisión finalizada."
	#define STR0278 "No es posible borrar historiales incluidos por el sistema."
	#define STR0279 "Facturas previas no sincronizadas"
	#define STR0280 "Tiene instrucciones de revisión"
	#define STR0281 "Sin instrucciones de revisión"
	#define STR0282 "Operación anulada por el usuario."
	#define STR0283 "La hora informada no es una hora válida."
	#define STR0284 "Informe una hora válida antes de confirmar."
	#define STR0285 "Informe una fecha válida antes de confirmar."
	#define STR0286 "Envío para revisión."
	#define STR0287 "El tipo de resultado no se completó."
	#define STR0288 "Retirando asientos marcados..."
	#define STR0289 "Grabando asientos divididos..."
	#define STR0290 "Efectuando operaciones de sincronización..."
	#define STR0291 "Grabando cola de sincronización..."
	#define STR0292 "Para utilizar la versión más reciente del programa #1, ejecute la actualización del diccionario #2."
	#define STR0293 "No existen Time Sheets para modificación."
	#define STR0294 "No es posible modificar el Time Sheets con las siguientes condiciones:"
	#define STR0295 "1) Con participación del cliente."
	#define STR0296 "2) Con el valor 0 (cero)."
	#define STR0297 "3) No cobrable."
	#define STR0298 "4) Borrado de la cuadrícula."
	#define STR0299 "Los gastos '#1' = '#2' no pueden modificarse,  porque no fue posible modificar el desdoblamiento '#3', '#4' = '#5', que está vinculado a los gastos."
	#define STR0300 "No fue posible transferir los siguientes gastos debido al desdoblamiento vinculado a estos."
	#define STR0301 "Desbloqueo de la factura previa que estaba en proceso de revisión."
	#define STR0302 "No fue posible realizar la transferencia para el Cliente '#1', Tienda '#2' y Caso '#3'."
	#define STR0303 "Informe un Cliente, Tienda y Caso válido."
	#define STR0304 "Socios/Revisores"
	#define STR0305 "Confirme"
	#define STR0306 "Finalizar"
	#define STR0307 "Parcialmente revisada."
	#define STR0308 "Log de modificación -"
	#define STR0309 "Función de origen: #1 - Línea: #2"
	#define STR0310 "Modelo:"
	#define STR0311 "Campo:"
	#define STR0312 "Valor actual:"
	#define STR0313 "Nuevo valor:"
	#define STR0314 "Línea: #1 ID: #2"
	#define STR0315 "¡Campo: #1 no encontrado en la estructura!"
	#define STR0316 "Modo de edición del campo no respetado. Verifique la propiedad: #1 del campo: #2"
	#define STR0317 "#1 - #2 - ¡Falla al crear el archivo de log!"
	#define STR0318 "#1 - #2 - ¡Falla al crear el directorio de log!"
	#define STR0319 ''
	#define STR0320 ''
	#define STR0321 "No se puede modificar la factura previa: #1"
	#define STR0322 "No se pueden modificar solamente facturas previas con las situaciones:"
	#define STR0323 "Los valores de cotizaciones se restaurarán al valor original de cotización"
	#define STR0324 "diaria de la fecha de emisión de la factura previa."
	#define STR0325 "mensual."
	#define STR0326 "Operación no válida para la factura previa:"
	#define STR0327 "Debe completarse el código del usuario que está modificando el asiento para no cobrar (NVY_USRNCB)."
	#define STR0328 "Anulación de factura previa"
	#define STR0329 "La factura previa se está modificando vía pantalla, es necesario esperar la liberación del registro."
	#define STR0330 "Realice nuevo intento en algunos minutos."
	#define STR0331 "Actualizando caso #1 - #2 de #3."
	#define STR0332 "Actualizando valores de los asientos - #1 de #2."
	#define STR0333 "Grabando asientos divididos - #1 de #2."
	#define STR0334 "Cumplimentando valores de asientos."
	#define STR0335 "Sincronizando."
	#define STR0336 "Redondeando Time Sheets - #1 de #2."
	#define STR0337 "Verifique si existen casos pendientes de revisión en la(s) factura(s) previa(s): #1."
	#define STR0338 "Retirando vínculos de registros - #1 de #2."
	#define STR0339 "Anulando vínculos."
	#define STR0340 "Identificando registros para redondeo."
	#define STR0341 "Preparando registros - #1 de #2."
	#define STR0342 "Verifique la situación de la(s) factura(s) previa(s): #1."
	#define STR0343 "Verifique la cotización de la(s) factura(s) previa(s): #1."
	#define STR0344 "Devolución no válida en el punto de entrada 'J203BPRE'. Consulta la documentación."
	#define STR0345 "El total de descuentos en la factura previa no puede ser mayor que la suma del valor de timesheet y fijo."
	#define STR0346 "Registros NO enviados a WO:"
	#define STR0347 "El código del motivo de la revisión se debe enviar en conjunto con la observación de la revisión."
#else
	#ifdef ENGLISH
		#define STR0001 "Pre-invoice operation"
		#define STR0002 "Pre-invoices"
		#define STR0003 "Contracts"
		#define STR0004 "Cases"
		#define STR0005 "Analysis"
		#define STR0006 "Draft"
		#define STR0007 "Definite"
		#define STR0008 "Time-Sheet"
		#define STR0009 "Expenses"
		#define STR0010 "Fixed Entry"
		#define STR0011 "Sending"
		#define STR0012 "Return"
		#define STR0013 "Issue Invoice"
		#define STR0014 "Issue Draft"
		#define STR0015 "Mark"
		#define STR0016 "Clear"
		#define STR0017 "Search"
		#define STR0018 "View"
		#define STR0019 "Edit"
		#define STR0020 "New"
		#define STR0021 "Status"
		#define STR0022 "Review"
		#define STR0023 "All"
		#define STR0024 "Cancel"
		#define STR0025 "Redo"
		#define STR0026 "Pro Forma Invoice"
		#define STR0027 "Additional Inv."
		#define STR0028 "History"
		#define STR0029 "Fixed"
		#define STR0030 "Professionals"
		#define STR0031 "Success"
		#define STR0032 "Copy PF Inv. Red."
		#define STR0033 "Wording"
		#define STR0034 "Original Vl."
		#define STR0035 "Data Model of Pro Forma Invoice"
		#define STR0036 "Data of Pro Forma Invoice"
		#define STR0037 "Data of Pro Forma Invoice Fixed Vl."
		#define STR0038 "Data of Time Sheets of Pro Forma Invoice Cases"
		#define STR0039 "Data of Success of Pro Forma Invoice Cases"
		#define STR0040 "Data of Fixed Entries of Pro Forma Invoice Cases"
		#define STR0041 "Data of Additional Invoice"
		#define STR0042 "Data of Expenses of Pro Forma Invoice Cases"
		#define STR0043 "Data of Pro Forma Invoice Cases"
		#define STR0044 "Data of Professionals of Pro Forma Invoice Cases"
		#define STR0045 "Data of Pro Forma Invoice History"
		#define STR0046 "Data of Pro Forma Invoice Contracts"
		#define STR0047 "Pro Forma Invoice Operation"
		#define STR0048 "Do you confirm cancellation?"
		#define STR0049 "Attention! All the pro forma invoices selected will be canceled."
		#define STR0050 "Wait"
		#define STR0051 "Canceling proforma invoice..."
		#define STR0052 "Cancellation completed."
		#define STR0053 "Error while updating the selection flag clear to "
		#define STR0054 "Error: ["
		#define STR0055 "Unable to edit the status of the proforma invoice(s) below."
		#define STR0056 "Error while updating to status "
		#define STR0057 "Operation not allowed for proforma invoice in this situation. "
		#define STR0058 "Indicate"
		#define STR0059 "Date"
		#define STR0060 "Data cannot be blank."
		#define STR0061 "Time"
		#define STR0062 "Time cannot be blank."
		#define STR0063 "Reviewer"
		#define STR0064 "Collection Stat."
		#define STR0065 "Issue Invoice"
		#define STR0066 "Issue"
		#define STR0067 "You cannot redo pro forma invoices in this situation"
		#define STR0068 "Redo the pro forma invoice: "
		#define STR0069 "Result"
		#define STR0070 "Enter the type of result to redo pro forma invoice"
		#define STR0071 "Error while redoing the pro forma invoice!"
		#define STR0072 "Origem da Redação "
		#define STR0073 "Description of Time Sheets"
		#define STR0074 "Invoice"
		#define STR0075 "Case"
		#define STR0076 "Firm"
		#define STR0077 "OK"
		#define STR0078 "Enter invoice."
		#define STR0079 "Analysis"
		#define STR0080 "Confirms the change to status "
		#define STR0081 "Attention! All the pro forma invoices selected will be changed."
		#define STR0082 "Confirm the wording copy for original cases?"
		#define STR0083 "Make the pro forma invoice wording"
		#define STR0084 "Make the case wording"
		#define STR0085 "Returns the original value of pro forma invoice"
		#define STR0086 "Returns the case original value"
		#define STR0087 "Confirm operation?"
		#define STR0088 "The entered values of entries selected from the pro forma invoice are restored."
		#define STR0089 "The entered values of entries selected from the case are restored. "
		#define STR0090 "Time cannot be changed to the type of direct participation activity."
		#define STR0091 "For this operation, please cancel the pro forma invoice"
		#define STR0092 "To dissociate the additional invoice, cancel the pro forma invoice"
		#define STR0093 "Select the pro forma invoices in valid status for the operation of cancellation!"
		#define STR0094 "Select the pro forma invoices to make the change in the Review status"
		#define STR0095 "TS Txt Adj"
		#define STR0096 "Case Notes"
		#define STR0097 "Change cannot be made because the new value is higher than the old one!"
		#define STR0098 "Error while assigning the value"
		#define STR0099 "Alias invalid for this operation"
		#define STR0100 "Check"
		#define STR0101 "Printer"
		#define STR0102 "Screen"
		#define STR0103 "Payers"
		#define STR0104 "Send to Queue"
		#define STR0105 "Operations"
		#define STR0106 "Type of Operations"
		#define STR0107 "Remove"
		#define STR0108 "WO"
		#define STR0109 "Transfer"
		#define STR0110 "Share TS"
		#define STR0111 "Percentage total must be 100%"
		#define STR0112 "Percentage total cannot be higher than 100%"
		#define STR0113 "Transfer the selected entries to:"
		#define STR0114 "Group"
		#define STR0115 "Client"
		#define STR0116 "Store"
		#define STR0117 "Case"
		#define STR0118 "Enter data properly"
		#define STR0119 "Information of phase, task and e-billing activity not valid."
		#define STR0120 "Target case is linked to pre-invoice '#' 1 with status '#2'."
		#define STR0121 "Target case can be related to the pro forma invoice '#1' with status '#2'."
		#define STR0122 "Select the pro forma invoices to change the status"
		#define STR0123 "Quit"
		#define STR0124 "PDF"
		#define STR0125 "Excel"
		#define STR0126 "Word"
		#define STR0127 "Operation completed!"
		#define STR0128 "Changes could not be applied"
		#define STR0129 "None"
		#define STR0130 "Pro Forma Invoice successfully redone."
		#define STR0131 "Value could not be assigned to the field via recursion: "
		#define STR0132 "By making this operation, all the changes made on the screen are saved!"
		#define STR0133 "ATTENTION"
		#define STR0134 "The number of hours for the TS exceeds the field size, so TS value cannot be changed. Please cancel the procedure."
		#define STR0135 "This contact is inactive and cannot be used."
		#define STR0136 "Record successfully changed!"
		#define STR0137 "Client Notes"
		#define STR0138 "Note"
		#define STR0139 "Client Invoicing Notes"
		#define STR0140 "Case Notes"
		#define STR0141 "Copy completed!"
		#define STR0142 "This pro forma invoice only has TS. Please cancel or do its WO."
		#define STR0143 "Value must be higher than the sum of TS with client participation."
		#define STR0144 "Select the pro forma invoices in valid status for the operation of redoing!"
		#define STR0145 "Annexes"
		#define STR0146 "Contract"
		#define STR0147 "Wait..."
		#define STR0148 "Redoing the Pro Forma Invoice..."
		#define STR0149 "Data of Pro Forma Invoice Division"
		#define STR0150 "Attention:The hourly value of the new employee is only calculated after confirming the changes. Continue?"
		#define STR0151 "Employee not changed"
		#define STR0152 "Filter by Case"
		#define STR0153 "Filter by Case"
		#define STR0154 "Only displays canceled or replaced pro forma invoices."
		#define STR0155 "No pro forma invoices found for the case entered!"
		#define STR0156 "The proforma invoice was canceled because it had no entries."
		#define STR0157 "Error while recovering the employee Hourly Value."
		#define STR0158 "WO not made."
		#define STR0159 "WO not made. No entry selected."
		#define STR0160 "Entries sent to WO:"
		#define STR0161 " Time Sheet(s)"
		#define STR0162 " Expenses"
		#define STR0163 " Fixed Entries"
		#define STR0164 " Success Inst."
		#define STR0165 " Fixed Inst."
		#define STR0166 "Entry WO"
		#define STR0167 "Updating entries..."
		#define STR0168 "The entered value is not enough to create new Time Sheets!"
		#define STR0169 "Enter a positive value!"
		#define STR0170 "There are pending value changes, to perform new changes, confirm or cancel the previous ones!"
		#define STR0171 "You can only annotate time multiple of "
		#define STR0172 " minutes!"
		#define STR0173 "The system is configured for UT not split."
		#define STR0174 "Value is adjusted to a multiple of "
		#define STR0175 "Value must be higher than the sum of Expenses with Apportionment."
		#define STR0176 "Value must be higher than the sum of Expenses with Completed Status."
		#define STR0177 "Choose a type of adjustment before changing the value!"
		#define STR0178 "Apportionment routine canceled by the user!"
		#define STR0179 "Both"
		#define STR0180 "You cannot change a payer with invoice issued!"
		#define STR0181 "There is at least a pro forma invoice that cannot be canceled because it has invoice(s) valid for one or more payers!"
		#define STR0182 "Remove Filter"
		#define STR0183 "Enter stage, task and ebilling activity in the time-sheet(s)."
		#define STR0184 "Note - WO"
		#define STR0185 "Discount could not be updated in at least one of the pro forma invoice cases!"
		#define STR0186 "Indicates whether the logged user can review the case"
		#define STR0187 "You can only change the TS value if the logged user is the one that reviews all cases or pro forma invoices."
		#define STR0188 "Discount cannot be higher than 100%."
		#define STR0189 "The Discount cannot be greater than the sum of Time Sheet and Fixed of the case."
		#define STR0190 "The sum of the Time Sheet and Fixed must be greater than the total discount amount."
		#define STR0191 "Quotations"
		#define STR0192 "Pro forma invoice quotations"
		#define STR0193 "There are changes not confirmed."
		#define STR0194 "Enter the values to be displayed."
		#define STR0195 "Summary of pro forma invoice values"
		#define STR0196 "Pro Forma Invoice Totals"
		#define STR0197 "Pro Forma Invoice Totals in Domestic Currency"
		#define STR0198 "Notes: Taxes not deducted"
		#define STR0199 "Please confirm changes before enabling this functionality."
		#define STR0200 "Summary"
		#define STR0201 "Invert selection"
		#define STR0202 "Recalculating Pro Forma Invoice"
		#define STR0203 "Sending Entries to WO"
		#define STR0204 "No TS selected for the division! Check it out."
		#define STR0205 "Invalid percentage value. Check it out!"
		#define STR0206 "Total discount value cannot be higher than fee value."
		#define STR0207 "Unable to divide the following TimeSheet(s):"
		#define STR0208 "Add new TS"
		#define STR0209 "Added time sheet not related to the pro-forma invoice because the customer, store and sortlike are not related to the pro-forma invoice, invoicing conditions do not allow relation or "
		#define STR0210 "its date is out of pro forma invoice issue period!"
		#define STR0211 "Error while saving the time-sheet!"
		#define STR0212 "Wording Destination"
		#define STR0213 "The new increase percentage is higher than the maximum value supported by the field!"
		#define STR0214 "Actions in TS Lot"
		#define STR0215 "Pro forma invoice issue/update"
		#define STR0216 "Change to definite"
		#define STR0217 "Draft Issuance"
		#define STR0218 "Invoice Issue"
		#define STR0219 "Pre-invoice cancellation"
		#define STR0220 "Pre-invoice reactivation by invoice cancellation"
		#define STR0221 "This action is only allowed in the Pro Forma Invoice tab!"
		#define STR0222 "This operation cannot be continued."
		#define STR0223 "The manipulation of expenses is disabled in SIGAPFS."
		#define STR0224 "The new increase value is greater than the maximum value supported by the field!"
		#define STR0225 "This proforma invoice is being remade, please wait."
		#define STR0226 "Proforma invoice '#1' has status '#2'."
		#define STR0227 " has status "
		#define STR0228 "Start - Redoing the pro forma invoice: "
		#define STR0229 "End - Redoing the pro forma invoice: "
		#define STR0230 "Starting the Review..."
		#define STR0231 "Clear All"
		#define STR0232 "Pro Forma Invoice Cancellation"
		#define STR0233 "Proforma Invoice(s) successfully imported!"
		#define STR0234 "One or more pro-forma invoices cannot be canceled because: "
		#define STR0235 "Case not adjusted"
		#define STR0236 "Participant not adjusted"
		#define STR0237 "Information of customer and case are not valid."
		#define STR0238 "Entry date is later to '#1', maximum date allowed to enter entries in the case."
		#define STR0239 "The case does not allow this type of entry."
		#define STR0240 "Entry Transfer"
		#define STR0241 " transferred successfully!"
		#define STR0242 " transferred successfully!"
		#define STR0243 "Rounding hours (e-billing)"
		#define STR0244 "Hours could not be rounded. Check if parameter MV_JURTS3 is set to .T., enabling fractional time."
		#define STR0245 "Round off could not be performed."
		#define STR0246 "There are no cases with Time Sheets associated."
		#define STR0247 "Rounding the hours of Time Sheets."
		#define STR0248 "Note: The entries were not automatically associated to target proforma and are available in option 'New' in proforma operations."
		#define STR0249 "Proforma invoice for status '#1'."
		#define STR0250 "Transferring could not be performed!"
		#define STR0251 "Invoice follow up"
		#define STR0252 "Total: "
		#define STR0253 "the timesheet #1"
		#define STR0254 "the expense #1"
		#define STR0255 "the fixed entry #1"
		#define STR0256 "It is not possible to reduce time sheet value due to other same case transactions that have customer participation."
		#define STR0257 "Unable to transfer for # for Customer '#2' and Case '#3'."
		#define STR0258 "Pro-forma invoice #1 does not have transactions and will be canceled."
		#define STR0259 "Transfer transactions"
		#define STR0260 "New TimeSheet(s): "
		#define STR0261 "Timesheet value of case #1 cannot be lower than the sum of its entries with customer participation."
		#define STR0262 " Enter a value that is higher than or equal to #1."
		#define STR0263 " Timesheet value of this case can be changed to a value that is higher than or equal to #1."
		#define STR0264 "You cannot edit the following Timesheets: "
		#define STR0265 "To divide a Timesheet, select it."
		#define STR0266 "You cannot add timesheet: "
		#define STR0267 "The reviewer was not completed. Check it!"
		#define STR0268 "The employee was not completed. Check it!"
		#define STR0269 "Tab "
		#define STR0270 "Pre-invoice change"
		#define STR0271 "Unable to complete alterations, the entry has pre-invoice under Review!"
		#define STR0272 "Change Cases for not revised"
		#define STR0273 "Operation Change Reviser is only available for proforma invoices with status 'Analysis', 'Under Review' or 'Changed'. Check it!"
		#define STR0274 "Change Reviser"
		#define STR0275 "Conclude reviewing all proforma invoice cases?"
		#define STR0276 "Proforma sent for review."
		#define STR0277 "Review concluded."
		#define STR0278 "Unable to delete histories added by system."
		#define STR0279 "Proforma Invoices not synchronized"
		#define STR0280 "With review instructions"
		#define STR0281 "No review instructions"
		#define STR0282 "Operation canceled by user."
		#define STR0283 "Time entered is not valid."
		#define STR0284 "Enter a valid time before confirming."
		#define STR0285 "Enter a valid date before confirming."
		#define STR0286 "Send to review."
		#define STR0287 "Type of result not entered."
		#define STR0288 "Removing selected entries..."
		#define STR0289 "Saving split entries..."
		#define STR0290 "Performing synchronization operations..."
		#define STR0291 "Saving synchronization queue..."
		#define STR0292 "To use the most recent version of the program #1, run update of dictionary #2."
		#define STR0293 "No Time Sheets for modification."
		#define STR0294 "Unable to change Time Sheets with the following terms:"
		#define STR0295 "1) With the participation of the customer;"
		#define STR0296 "2) With the value 0 (zero);"
		#define STR0297 "3) Not collectible;"
		#define STR0298 "4) Deleted from the grid."
		#define STR0299 "A despesa '#1' = '#2' não pode ser alterada,  pois não foi possível alterar o desdobramento '#3', '#4' = '#5', que está vinculado na despesa."
		#define STR0300 "Não foi possível transferir as despesas abaixo devido a desdobramento vinculado na mesma."
		#define STR0301 "Unblock the proforma invoice that was in Review process."
		#define STR0302 "Unable to transfer for Customer '#1', Store '#2' and Case '#3'."
		#define STR0303 "Enter a valid Customer, Store and Case."
		#define STR0304 "Partners/Revisers"
		#define STR0305 "Confirm"
		#define STR0306 "Close"
		#define STR0307 "Partially reviewed."
		#define STR0308 "Edition log - "
		#define STR0309 "Function of Origin: #1 - Line: #2"
		#define STR0310 "Model: "
		#define STR0311 "Field: "
		#define STR0312 "Current value: "
		#define STR0313 "New value: "
		#define STR0314 "Line: #1 ID: #2"
		#define STR0315 "Field: #1 not found in the structure!"
		#define STR0316 "Edition mode of the field not respected. Check the propriety: #1 of the field: #2"
		#define STR0317 "#1 - #2 - Failure creating the log file!"
		#define STR0318 "#1 - #2 - Failure creating the log directory!"
		#define STR0319 ''
		#define STR0320 ''
		#define STR0321 "Unable to edit proforma invoice: #1"
		#define STR0322 "You can only edit proforma invoices with status: #1"
		#define STR0323 "The values of quotations are restored for daily quotation value "
		#define STR0324 "of the proforma invoice issue."
		#define STR0325 "monthly."
		#define STR0326 "Operation invalid for Proforma Invoice: #1"
		#define STR0327 "Enter the User Code editing the entry not to collect (NVY_USRNCB)."
		#define STR0328 "Pro Forma Invoice Cancellation"
		#define STR0329 "The pro forma invoice is being edited on screen. Wait for the release of the record."
		#define STR0330 "Try again in a few minutes."
		#define STR0331 "Updating case #1 - #2 of #3"
		#define STR0332 "Updating entry values - #1 of #2."
		#define STR0333 "Saving split entries - 1# of #2"
		#define STR0334 "Entering values."
		#define STR0335 "Synchronizing."
		#define STR0336 "Rouding Time Sheets - #1 of #2"
		#define STR0337 "Check if there are pending cases of review in the proforma invoice(s): #1."
		#define STR0338 "Deleting entry links - #1 of #2."
		#define STR0339 "Canceling links."
		#define STR0340 "Identifying entries to round."
		#define STR0341 "Preparing entries - 1# of #2"
		#define STR0342 "Verifique a situação da(s) pré-fatura(s): #1."
		#define STR0343 "Verifique a cotação da(s) pré-fatura(s): #1."
		#define STR0344 "Invalid return at entry point 'J203BPRE'. See documentation."
		#define STR0345 "The total discount on the pro forma invoice cannot be greater than the sum of the timesheet and fixed value."
		#define STR0346 "Entries NOT sent to WO:"
		#define STR0347 "The revision reason code must be submitted along with the revision note."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Operação de pré-facturas", "Operação de Pré-Faturas" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Pré-facturas", "Pré-Faturas" )
		#define STR0003 "Contratos"
		#define STR0004 "Casos"
		#define STR0005 "Análise"
		#define STR0006 "Minuta"
		#define STR0007 "Definitivo"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Time-sheet", "Time-Sheet" )
		#define STR0009 "Despesas"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Lanç.Tabelado", "Lanc. Tabelado" )
		#define STR0011 "Envio"
		#define STR0012 "Retorno"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Emitir factura", "Emitir Fatura" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Emitir minuta", "Emitir Minuta" )
		#define STR0015 "Marcar"
		#define STR0016 "Desmarcar"
		#define STR0017 "Pesquisar"
		#define STR0018 "Visualizar"
		#define STR0019 "Alterar"
		#define STR0020 "Novos"
		#define STR0021 "Situação"
		#define STR0022 "Revisão"
		#define STR0023 "Todos"
		#define STR0024 "Cancelar"
		#define STR0025 "Refazer"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Pré-factura", "Pré-Fatura" )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Fact. Adicional", "Fat. Adicional" )
		#define STR0028 "Histórico"
		#define STR0029 "Fixo"
		#define STR0030 "Profissionais"
		#define STR0031 "Êxito"
		#define STR0032 "Copiar Red. PF."
		#define STR0033 "Redação"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Vlr. Original", "Val. Original" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Modelo de dados de pré-factura", "Modelo de Dados de Pré Fatura" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Dados da pré-factura", "Dados da Pré-Fatura" )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Dados dos fixos da pré-factura", "Dados dos Fixo da Pré-Fatura" )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Dados dos time-sheets dos casos da pré-factura", "Dados dos Time Sheets dos Casos da Pré-Fatura" )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Dados dos êxitos dos casos da pré-factura", "Dados dos Existos dos Casos da Pré-Fatura" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Dados dos lanç. tabelado dos casos da pré-factura", "Dados dos Lanc. Tabelado dos Casos da Pré-Fatura" )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Dados das facturações adicionais", "Dados dos Faturamentos Adicionais" )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Dados das despesas dos casos da pré-factura", "Dados das Despesas dos Casos da Pré-Fatura" )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Dados dos casos da pré-factura", "Dados dos Casos da Pré-Fatura" )
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Dados dos profissionais dos casos da pré-factura", "Dados dos Profissionais dos Casos da Pré-Fatura" )
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Dados dos históricos da pré-factura", "Dados dos Históricos da Pré-Fatura" )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Dados dos contratos da pré-factura", "Dados dos Contratos da Pré-Fatura" )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Operação da pré-factura", "Operação da Pre-Fatura" )
		#define STR0048 "Confirma o cancelamento?"
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Atenção! Todas as pré-facturas marcadas serão canceladas.", "Atenção! Todas as pré-faturas marcadas serão canceladas." )
		#define STR0050 "Aguarde"
		#define STR0051 "Cancelando a pré-fatura..."
		#define STR0052 "Cancelamento terminado."
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Erro ao actualizar limpar flag de marcação para ", "Erro ao atualizar limpar flag de marcação para " )
		#define STR0054 "Erro: ["
		#define STR0055 "Não foi possível alterar a situação da(s) pré-fatura(s) abaixo."
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "Erro ao actualizar para situação ", "Erro ao atualizar para situação " )
		#define STR0057 "Operação só permitida para pré-faturas em situação "
		#define STR0058 "Informar"
		#define STR0059 "Data"
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "A data não pode estar em branco.", "Data não pode estar em branco." )
		#define STR0061 "Hora"
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "A hora não pode estar em branco.", "Hora não pode estar em branco." )
		#define STR0063 "Revisor"
		#define STR0064 "Sit. Cobrança"
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Emitir factura", "Emitir Fatura" )
		#define STR0066 "Emitir"
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Não é permitido refazer a pré-factura nesta situação", "Não é permitido Refazer pré-fatura nesta situação" )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Refazer a pré-factura: ", "Refazer a pré-fatura: " )
		#define STR0069 "Resultado"
		#define STR0070 "É preciso informar o tipo de resultado para refazer a pré-fartura."
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Erro ao refazer a pré-factura.", "Erro ao refazer a pré-fatura!" )
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Origem da redação", "Origem da Redação" )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Descrição dos time-sheets", "Descrição dos Time Sheets" )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Factura", "Fatura" )
		#define STR0075 "Caso"
		#define STR0076 "Escritório"
		#define STR0077 "Ok"
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "Informe a factura.", "Informe a fatura." )
		#define STR0079 "Análise"
		#define STR0080 "Confirma a troca para situação "
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "Atenção! Todas as pré-facturas marcadas serão trocadas.", "Atenção! Todas as pré-faturas marcadas serão trocadas." )
		#define STR0082 "Confirma a cópia da redação para os casos originais ?"
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "Compor redação da pré-factura", "Compor redação da pré-fatura" )
		#define STR0084 "Compor redação do caso"
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "Volta valor original de toda a pré-factura", "Volta valor original de toda pré-fatura" )
		#define STR0086 "Volta valor original do caso"
		#define STR0087 "Confirma a operação?"
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "Serão restaurados os valores lançados dos lançamentos seleccionados de toda a pré-factura.", "Serão restaurados os valores lançados dos lançamentos selecionados de toda a pré-fatura." )
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "Serão restaurados os valores lançados dos lançamentos seleccionados do caso ", "Serão restaurados os valores lançados dos lançamentos selecionados do caso " )
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "Não se permite a alteração de tempo para tipo de actividade de participação directa.", "Não permitida alteração de tempo para tipo de atividade de participação direta." )
		#define STR0091 If( cPaisLoc $ "ANG|PTG", "Para esta operação, por favor, cancele a pré-factura", "Para esta operação, favor cancelar a pre-fatura" )
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "Para desvincular a factura adicional, é necessário cancelar a pré-factura", "Para desvincular a fatura adicional é necessário cancelar a pré-fatura" )
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "É preciso marcar as pré-facturas em situação válida para a operação de cancelar.", "É preciso marcar as pré-faturas em situação válida para a operação de cancelar!" )
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "É preciso marcar as pré-facturas para efectuar a alteração no estado da Revisão", "É preciso marcar as pré-faturas para efetuar a alteração no status da Revisão" )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Corr.Txt TS", "Corr Txt TS" )
		#define STR0096 If( cPaisLoc $ "ANG|PTG", "OBS.Caso", "OBS Caso" )
		#define STR0097 If( cPaisLoc $ "ANG|PTG", "Não é possível efectuar a alteração pois o valor novo é maior do que o antigo.", "Não é possível efetuar a alteração, pois o valor novo é maior do que o antigo!" )
		#define STR0098 "Erro ao atribuir o valor"
		#define STR0099 "Alias inválido para esta operação"
		#define STR0100 "Conferência"
		#define STR0101 "Impressora"
		#define STR0102 If( cPaisLoc $ "ANG|PTG", "Ecrã", "Tela" )
		#define STR0103 "Pagadores"
		#define STR0104 If( cPaisLoc $ "ANG|PTG", "Enviar p/ fila", "Enviar p/ Fila" )
		#define STR0105 "Operações"
		#define STR0106 If( cPaisLoc $ "ANG|PTG", "Tipo de operações", "Tipo de Operações" )
		#define STR0107 "Retirar"
		#define STR0108 "WO"
		#define STR0109 "Transferir"
		#define STR0110 "Dividir TS"
		#define STR0111 If( cPaisLoc $ "ANG|PTG", "O total de percentagem deve ser igual a 100%", "Total da porcentagem deve ser igual a 100%" )
		#define STR0112 If( cPaisLoc $ "ANG|PTG", "O total da percentagem não pode ser maior que 100%", "Total da porcentagem não pode ser maior que 100%" )
		#define STR0113 If( cPaisLoc $ "ANG|PTG", "Transferir o(s) lançamento(s) marcado(s) para:", "Transferir o(s) Lançamento(s) marcado(s) para:" )
		#define STR0114 "Grupo"
		#define STR0115 "Cliente"
		#define STR0116 "Loja"
		#define STR0117 "Caso"
		#define STR0118 If( cPaisLoc $ "ANG|PTG", "Preencher correctamente as informações", "Preencher corretamente as informações" )
		#define STR0119 "As informações de fase, tarefa e atividade e-billing não são válidas."
		#define STR0120 "O Caso destino está vinculado na pré-fatura '#1' com a situação '#2'."
		#define STR0121 "O Caso destino pode ser vinculado à pré-fatura '#1' com a situação '#2'."
		#define STR0122 If( cPaisLoc $ "ANG|PTG", "É preciso marcar as pré-facturas para alterar a situação", "É preciso marcar as pré-faturas para alterar a situação" )
		#define STR0123 "Sair"
		#define STR0124 "PDF"
		#define STR0125 "Excel"
		#define STR0126 "Word"
		#define STR0127 If( cPaisLoc $ "ANG|PTG", "Operação concluída.", "Operação concluída!" )
		#define STR0128 "Não foi possível aplicar as alterações"
		#define STR0129 "Nenhum"
		#define STR0130 If( cPaisLoc $ "ANG|PTG", "Pré-factura refeita com sucesso", "Pré-Fatura refeita com sucesso" )
		#define STR0131 "Não foi possível atribuir valor via recursividade ao campo: "
		#define STR0132 If( cPaisLoc $ "ANG|PTG", "Ao realizar esta operação, o sistema gravará todas as alterações feitas no ecrã.", "Ao realizar esta operação o sistema salvará todas as alterações feitas na tela!" )
		#define STR0133 "ATENÇÃO"
		#define STR0134 If( cPaisLoc $ "ANG|PTG", "A quantidade de horas para o TS excede o tamanho do campo. Não será possível alterar o valor do TS. Por favor, cancelar o procedimento.", "A quantidade de horas para o TS excede o tamanho do campo, não será possível alterar o valor do TS. Favor cancelar o procedimento." )
		#define STR0135 If( cPaisLoc $ "ANG|PTG", "Este contacto não está activo e não pode ser utilizado.", "Este contato não está ativo e não pode ser utilizado." )
		#define STR0136 If( cPaisLoc $ "ANG|PTG", "Registo alterado com sucesso.", "Registro alterado com sucesso!" )
		#define STR0137 If( cPaisLoc $ "ANG|PTG", "OBS.Cliente", "OBS Cliente" )
		#define STR0138 "Observação"
		#define STR0139 If( cPaisLoc $ "ANG|PTG", "Observação de facturação do cliente", "Observação de Faturamento do Cliente" )
		#define STR0140 If( cPaisLoc $ "ANG|PTG", "Observação do caso", "Observação do Caso" )
		#define STR0141 If( cPaisLoc $ "ANG|PTG", "Cópia efectuada.", "Cópia efetuada!" )
		#define STR0142 If( cPaisLoc $ "ANG|PTG", "Esta pré-factura possui apenas TS. Por favor, cancelar ou fazer WO do mesmo.", "Esta pré possui apenas TS, favor cancelar ou fazer WO do mesmo." )
		#define STR0143 "Valor deve ser maior que a soma dos TS com participação de cliente."
		#define STR0144 If( cPaisLoc $ "ANG|PTG", "É preciso marcar as pré-facturas em situação válida para a operação de refazer.", "É preciso marcar as pré-faturas em situação válida para a operação de refazer!" )
		#define STR0145 "Anexos"
		#define STR0146 "Contrato"
		#define STR0147 "Aguarde..."
		#define STR0148 If( cPaisLoc $ "ANG|PTG", "A refazer a pré-factura...", "Refazendo a Pré-Fatura..." )
		#define STR0149 If( cPaisLoc $ "ANG|PTG", "Dados da divisão de pré-facturas", "Dados da Divisão de Pré-Faturas" )
		#define STR0150 If( cPaisLoc $ "ANG|PTG", "Atenção, o valor hora do novo participante só será calculado após a confirmação das alterações. Continuar?", "Atenção, o valor hora do novo participante só será calculado após a confirmação das alterações, continuar?" )
		#define STR0151 "O participante não foi alterado"
		#define STR0152 "Filtro por caso"
		#define STR0153 "Filtrar por caso"
		#define STR0154 If( cPaisLoc $ "ANG|PTG", "Exibir somente pré-facturas canceladas e substituídas.", "Exibir somente pré-faturas canceladas e substituidas." )
		#define STR0155 If( cPaisLoc $ "ANG|PTG", "Não foram encontradas pré-facturas para o caso informado.", "Não foram encontradas pré-faturas para o caso informado!" )
		#define STR0156 "A pré-fatura foi cancelada por não possuir mais lançamentos."
		#define STR0157 "Erro ao recuperar o Valor Hora do participante."
		#define STR0158 If( cPaisLoc $ "ANG|PTG", "WO não efectuado.", "WO não efetuado." )
		#define STR0159 If( cPaisLoc $ "ANG|PTG", "WO não efectuado. Nenhum lançamento foi seleccionado.", "WO não efetuado, nenhum lançamento foi selecionado." )
		#define STR0160 "Lançamentos enviados para WO:"
		#define STR0161 If( cPaisLoc $ "ANG|PTG", " Time-sheet(s)", " Time Sheet(s)" )
		#define STR0162 " Despesa(s)"
		#define STR0163 If( cPaisLoc $ "ANG|PTG", " Lanç. Tabelado(s)", " Lanc. Tabelado(s)" )
		#define STR0164 " Parc. Êxito"
		#define STR0165 " Parc. Fixo"
		#define STR0166 If( cPaisLoc $ "ANG|PTG", "WO de lançamentos", "WO de Lançamentos" )
		#define STR0167 If( cPaisLoc $ "ANG|PTG", "A actualizar lançamentos...", "Atualizando lançamentos..." )
		#define STR0168 If( cPaisLoc $ "ANG|PTG", "O valor informado é insuficiente para criar novos Time-sheets.", "O valor informado é insuficiente para criar novos Time Sheets!" )
		#define STR0169 If( cPaisLoc $ "ANG|PTG", "Informe um valor positivo.", "Informe um valor positivo!" )
		#define STR0170 If( cPaisLoc $ "ANG|PTG", "Existem alterações de valor pendentes. Para efectuar novas alterações, confirme ou cancele as anteriores.", "Existem alterações de valor pendentes, para efetuar novas alterações confirme ou cancele as anteriores!" )
		#define STR0171 "Só é permitido apontar tempos múltipos de "
		#define STR0172 If( cPaisLoc $ "ANG|PTG", " minutos.", " minutos!" )
		#define STR0173 If( cPaisLoc $ "ANG|PTG", "O sistema está configurado para UT não fraccionada.", "Sistema esta configurado para UT não fracionada." )
		#define STR0174 "O valor será ajustado para um múltiplo de "
		#define STR0175 If( cPaisLoc $ "ANG|PTG", "O valor deve ser maior que a soma das despesas com Rateio.", "Valor deve ser maior que a soma das Despesas com Rateio." )
		#define STR0176 If( cPaisLoc $ "ANG|PTG", "O valor deve ser maior que a soma das Despesas com situação = Concluído.", "Valor deve ser maior que a soma das Despesas com situação = Concluído." )
		#define STR0177 If( cPaisLoc $ "ANG|PTG", "Escolha um tipo de ajuste antes de alterar o valor.", "Escolha um tipo de ajuste antes de alterar o valor!" )
		#define STR0178 If( cPaisLoc $ "ANG|PTG", "Procedimento de rateio cancelada pelo utilizador.", "Rotina de Rateio cancelada pelo usuário!" )
		#define STR0179 "Ambos"
		#define STR0180 If( cPaisLoc $ "ANG|PTG", "Não é possível alterar um pagador com factura emitida.", "Não é possível alterar um pagador com fatura emitida!" )
		#define STR0181 "Existe pelo menos uma pré-fatura que não pode ser cancela pois possui fatura(S) valida(S) para um ou mais pagadores!"
		#define STR0182 If( cPaisLoc $ "ANG|PTG", "Remover filtro", "Remover Filtro" )
		#define STR0183 If( cPaisLoc $ "ANG|PTG", "É necessário preencher fase, tarefa e actividade de e-billing no(s) time-sheet(s).", "É necessário preencher fase, tarefa e atividade de ebilling no(s) time-sheet(s)." )
		#define STR0184 "Observação - WO"
		#define STR0185 If( cPaisLoc $ "ANG|PTG", "Não foi possível actualizar o desconto em pelo menos um dos casos da pré-factura.", "Não foi possivel atualizar o desconto em pelo menos um dos casos da pré-fatura!" )
		#define STR0186 If( cPaisLoc $ "ANG|PTG", "Indica se o utilizador conectado pode revisar o caso", "Indica se o usuário logado pode revisar o caso" )
		#define STR0187 If( cPaisLoc $ "ANG|PTG", "Só é possível alterar o valor de TS se o utilizador conectado for revisor de todos os casos ou da pré-factura.", "Só é possível alterar o valor de TS se o usuário logado for revisor de todos os casos ou da pré-fatura." )
		#define STR0188 If( cPaisLoc $ "ANG|PTG", "O desconto não pode ser maior que 100%.", "O Desconto não pode ser maior que 100%!" )
		#define STR0189 "O Desconto não pode ser maior que a soma de Time Sheet e Fixo do caso!"
		#define STR0190 "A soma do valor de Time Sheet e Fixo deve ser maior que o valor de desconto total!"
		#define STR0191 "Cotações"
		#define STR0192 If( cPaisLoc $ "ANG|PTG", "Cotações da pré-factura", "Cotações da pré-fatura" )
		#define STR0193 "Existem alterações não confirmadas."
		#define STR0194 "É necessário informar os valores a serem exibidos."
		#define STR0195 If( cPaisLoc $ "ANG|PTG", "Resumo dos valores da pré-factura", "Resumo dos valores da pré-fatura" )
		#define STR0196 If( cPaisLoc $ "ANG|PTG", "Totais da Pré-Factura", "Totais da Pré-Fatura" )
		#define STR0197 If( cPaisLoc $ "ANG|PTG", "Totais da pré-factura na moeda nacional", "Totais da Pré-Fatura na Moeda Nacional" )
		#define STR0198 "OBS.: Impostos não deduzidos"
		#define STR0199 If( cPaisLoc $ "ANG|PTG", "Por favor, confirme as alterações antes de accionar esta funcionalidade.", "Favor confirmar as alterações antes de acionar esta funcionalidade." )
		#define STR0200 "Resumo"
		#define STR0201 If( cPaisLoc $ "ANG|PTG", "Inverter selecção", "Inverter seleção" )
		#define STR0202 If( cPaisLoc $ "ANG|PTG", "A recalcular pré-factura", "Recalculando Pré-Fatura" )
		#define STR0203 If( cPaisLoc $ "ANG|PTG", "A enviar lançamentos para WO", "Enviando lançamentos para WO" )
		#define STR0204 If( cPaisLoc $ "ANG|PTG", "Não foi seleccionado nenhum TS para divisão. Verifique.", "Não foi selecionado nenhum TS para divisão! Verifique." )
		#define STR0205 If( cPaisLoc $ "ANG|PTG", "Valor de percentagem inválido. Verifique.", "Valor de percentual inválido. Verifique!" )
		#define STR0206 "O valor total de descontos não pode ser maior que o valor de honorários."
		#define STR0207 "Não foi possivel dividir os seguinte(s) TimeSheet(s): "
		#define STR0208 "Incluir novo TS"
		#define STR0209 "O time-sheet inserido não foi vinculado a pré-fatura pois o cliente, loja e caso do mesmo não está relacionado a pré-fatura, as condições de faturamento não permitem o seu vínculo ou ainda "
		#define STR0210 "a data do mesmo está fora do período de referência da pré-fatura!"
		#define STR0211 If( cPaisLoc $ "ANG|PTG", "Erro ao gravar o time-sheet.", "Erro ao salvar o time-sheet!" )
		#define STR0212 If( cPaisLoc $ "ANG|PTG", "Destino da redação", "Destino da Redação" )
		#define STR0213 If( cPaisLoc $ "ANG|PTG", "A nova percentagem de acréscimo é maior que o valor máximo suportado pelo campo.", "O novo percentual de acréscimo é maior que o valor máximo suportado pelo campo!" )
		#define STR0214 If( cPaisLoc $ "ANG|PTG", "Acções em lote TS", "Ações em Lote TS" )
		#define STR0215 "Emissão/atualização da pré-fatura"
		#define STR0216 "Alteração para definitivo"
		#define STR0217 "Emissão de minuta"
		#define STR0218 If( cPaisLoc $ "ANG|PTG", "Emissão de factura", "Emissão de fatura" )
		#define STR0219 If( cPaisLoc $ "ANG|PTG", "Cancelamento da pré-factura", "Cancelamento da pré-fatura" )
		#define STR0220 If( cPaisLoc $ "ANG|PTG", "Reactivação da pré-factura pelo cancelamento da factura", "Reativação da pré-fatura pelo cancelamento da fatura" )
		#define STR0221 If( cPaisLoc $ "ANG|PTG", "Esta acção somente é permitida na aba de pré-factura.", "Esta ação somente é permitida na aba de Pré-Fatura!" )
		#define STR0222 "Não é possível continuar essa operação."
		#define STR0223 "A manipulação de despesas está desabilitada no SIGAPFS."
		#define STR0224 If( cPaisLoc $ "ANG|PTG", "O novo valor de acréscimo é maior que o valor máximo suportado pelo campo.", "O novo valor de acréscimo é maior que o valor máximo suportado pelo campo!" )
		#define STR0225 If( cPaisLoc $ "ANG|PTG", "Esta pré-factura está a ser refeita. Por favor, aguarde.", "Esta pré-fatura está sendo refeita, favor aguardar." )
		#define STR0226 "A pré-fatura '#1' esta com o status de '#2'."
		#define STR0227 " está com o status de "
		#define STR0228 If( cPaisLoc $ "ANG|PTG", "Início - A refazer a pré-factura: ", "Início - Refazendo a pré-fatura: " )
		#define STR0229 If( cPaisLoc $ "ANG|PTG", "Final - A refazer a pré-factura: ", "Final - Refazendo a pré-fatura: " )
		#define STR0230 If( cPaisLoc $ "ANG|PTG", "A iniciar a revisão...", "Iniciando a Revisão..." )
		#define STR0231 If( cPaisLoc $ "ANG|PTG", "Desmarcar tudo", "Desmarcar Tudo" )
		#define STR0232 If( cPaisLoc $ "ANG|PTG", "Cancelamento de pré-factura", "Cancelamento de Pré-fatura" )
		#define STR0233 "Pré-Fatura(s) cancelada(s) com sucesso!"
		#define STR0234 "Uma ou mais pré-faturas não podem ser canceladas, pois: "
		#define STR0235 "Caso não ajustado"
		#define STR0236 "Participante não ajustado"
		#define STR0237 "As informações de cliente e caso não são válidas."
		#define STR0238 "A data do lançamento é posterior à '#1', data máxima permitida para digitar lançamentos no caso."
		#define STR0239 "O caso não permite digitar para esse tipo de lançamento."
		#define STR0240 If( cPaisLoc $ "ANG|PTG", "Transferência de lançamentos", "Transferência de Lançamentos" )
		#define STR0241 " transferido(s) com sucesso!"
		#define STR0242 " transferida(s) com sucesso!"
		#define STR0243 "Arredondar horas (e-billing)"
		#define STR0244 "Não foi possível realizar o arredondamento das horas. Verifique se o parâmetro MV_JURTS3 está como .T., de forma a permitir hora fracionada."
		#define STR0245 "Não foi possível realizar o arredondamento."
		#define STR0246 "Não há casos com Time Sheets vinculados."
		#define STR0247 "Arredondando as horas dos Time Sheets."
		#define STR0248 "Obs.: Os lançamentos não foram associados automaticamente à pré-fatura de destino e se encontram disponíveis na opção 'Novos' em Operações de Pré-fatura."
		#define STR0249 "A pré-fatura passará para a situação '#1'."
		#define STR0250 "Não foi possível realizar a transferência!"
		#define STR0251 "Encaminhamento de fatura"
		#define STR0252 "Total: "
		#define STR0253 "o timesheet #1"
		#define STR0254 "a despesa #1"
		#define STR0255 "o lançamento tabelado #1"
		#define STR0256 "Não é possível reduzir o valor do time sheet devido a outros lançamentos do mesmo caso que possuem participação do cliente."
		#define STR0257 "Não foi possível transferir #1 para o cliente '#2' e caso '#3'."
		#define STR0258 "A pré-fatura #1 não possui mais lançamentos e será cancelada."
		#define STR0259 "Transferindo os lançamentos"
		#define STR0260 "Novo(s) TimeSheet(s) : "
		#define STR0261 "O valor do timesheet do caso '#1' não pode ser inferior a soma de seus lançamentos com participação do cliente."
		#define STR0262 " Informe um valor maior ou igual a #1."
		#define STR0263 " O valor do timesheet desse caso pode ser alterado para um valor maior ou igual a #1."
		#define STR0264 "Você não tem permissão para alterar os seguintes Time Sheets: "
		#define STR0265 "Para dividir um Time Sheet, você deve marcá-lo."
		#define STR0266 "Você não tem permissão para incluir o seguinte timesheet: "
		#define STR0267 "O revisor não foi preenchido. Verifique!"
		#define STR0268 "O participante não foi preenchido. Verifique!"
		#define STR0269 "Aba "
		#define STR0270 "Alteração de pré-fatura"
		#define STR0271 "Não foi possível realizar as alterações, o lançamento possui pré-fatura em processo de Revisão!"
		#define STR0272 "Alterar Casos para não revisados"
		#define STR0273 "A operação de Alterar Revisor só está disponível para as pré-faturas em situação 'Análise', 'Em Revisão' ou 'Alterada'. Verifique!"
		#define STR0274 "Alterar Revisor"
		#define STR0275 "Deseja concluir a revisão de todos os casos da pré-fatura?"
		#define STR0276 "Pré-fatura enviada para revisão."
		#define STR0277 "Revisão concluída."
		#define STR0278 "Não é possível excluir históricos incluídos pelo sistema."
		#define STR0279 "Pré-faturas não sincronizadas"
		#define STR0280 "Possui instruções de revisão"
		#define STR0281 "Sem instruções de revisão"
		#define STR0282 "Operação cancelada pelo usuário."
		#define STR0283 "A hora informada não é uma hora válida."
		#define STR0284 "Informe uma hora válida antes de confirmar."
		#define STR0285 "Informe uma data válida antes de confirmar."
		#define STR0286 "Envio para revisão."
		#define STR0287 "O tipo de resultado não foi preenchido."
		#define STR0288 "Retirando lançamentos marcados..."
		#define STR0289 "Gravando lançamentos divididos..."
		#define STR0290 "Efetuando operações de sincronização..."
		#define STR0291 "Gravando fila de sincronização..."
		#define STR0292 "Para utilizar a versão mais recente do programa #1 execute a atualização de dicionário #2."
		#define STR0293 "Não existem Time Sheets passíveis para alteração."
		#define STR0294 "Não é possível alterar Time Sheets com as seguintes condições:"
		#define STR0295 "1) Com participação do cliente;"
		#define STR0296 "2) Com o valor 0 (zero);"
		#define STR0297 "3) Não cobrável;"
		#define STR0298 "4) Deletado do grid."
		#define STR0299 "A despesa '#1' = '#2' não pode ser alterada,  pois não foi possível alterar o desdobramento '#3', '#4' = '#5', que está vinculado na despesa."
		#define STR0300 "Não foi possível transferir as despesas abaixo devido a desdobramento vinculado na mesma."
		#define STR0301 "Desbloqueio da pré-fatura que estava em processo de Revisão."
		#define STR0302 "Não foi possível realizar a transferência para o Cliente '#1', Loja '#2' e Caso '#3'."
		#define STR0303 "Informe um Cliente, Loja e Caso válido."
		#define STR0304 "Sócios/Revisores"
		#define STR0305 "Confirmar"
		#define STR0306 "Fechar"
		#define STR0307 "Parcialmente revisada."
		#define STR0308 "Log de alteração - "
		#define STR0309 "Função de Origem: #1 - Linha: #2"
		#define STR0310 "Modelo: "
		#define STR0311 "Campo: "
		#define STR0312 "Valor atual: "
		#define STR0313 "Novo valor: "
		#define STR0314 "Linha: #1 ID: #2"
		#define STR0315 "Campo: #1 não encontrado na estrutura!"
		#define STR0316 "Modo de edição do campo não respeitado. Verifique a propriedade: #1 do campo: #2"
		#define STR0317 "#1 - #2 - Falha ao criar o arquivo de log!"
		#define STR0318 "#1 - #2 - Falha ao criar o dirétorio de log!"
		#define STR0319 ''
		#define STR0320 ''
		#define STR0321 "Não é possível alterar a pré-fatura: #1"
		#define STR0322 "É possivel alterar somente pré-faturas com as situações: #1"
		#define STR0323 "Os valores de cotações serão restaurados para o valor de cotação "
		#define STR0324 "diária da data de emissão da pré-fatura."
		#define STR0325 "mensal."
		#define STR0326 "Operação inválida para a Pré-Fatura: #1"
		#define STR0327 "O Código do Usuário que está alterando o lançamento para não cobrar deve ser preenchido (NVY_USRNCB)."
		#define STR0328 "Cancelamento de Pré-Fatura"
		#define STR0329 "A pré-fatura está sendo alterada via tela, necessário aguardar a liberação do registro."
		#define STR0330 "Realize nova tentativa em alguns minutos."
		#define STR0331 "Atualizando caso #1 - #2 de #3."
		#define STR0332 "Atualizando valores dos lançamentos - #1 de #2."
		#define STR0333 "Gravando lançamentos divididos - #1 de #2."
		#define STR0334 "Preenchendo valores dos lançamentos."
		#define STR0335 "Sincronizando."
		#define STR0336 "Arredondando Time Sheets - #1 de #2."
		#define STR0337 "Verifique se há casos pendentes de revisão na(s) pré-fatura(s): #1."
		#define STR0338 "Removendo vínculos de lançamentos - #1 de #2."
		#define STR0339 "Cancelando vínculos."
		#define STR0340 "Identificando lançamentos para arredondamento."
		#define STR0341 "Preparando lançamentos - #1 de #2."
		#define STR0342 "Verifique a situação da(s) pré-fatura(s): #1."
		#define STR0343 "Verifique a cotação da(s) pré-fatura(s): #1."
		#define STR0344 "Retorno inválido no ponto de entrada 'J203BPRE'. Consulta a documentação."
		#define STR0345 "O total de descontos na pré-fatura não poderá ser maior que a soma do valor de timesheet e fixo."
		#define STR0346 "Lançamentos NÃO enviados para WO:"
		#define STR0347 "O código do motivo da revisão deve ser enviado em conjunto com a observação da revisão."
	#endif
#endif
