#ifdef SPANISH
	#define STR0001 "Registro de rutinas personalizadas"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Incluir"
	#define STR0005 "Modificar"
	#define STR0006 "Borrar"
	#define STR0007 "Campos de filtro de la rutina personalizada"
	#define STR0008 "Descripción"
	#define STR0009 "Rutina informada no válida."
	#define STR0010 "Seleccione una rutina MVC válida"
	#define STR0011 "Campo seleccionado no se encontró."
	#define STR0012 "Seleccione un campo válido"
	#define STR0013 "El campo '#1' debe completarse si el Tipo de registro fuera 2-Rutinas."
	#define STR0014 "Não foi possivel encontrar a estrutura da rotina"
	#define STR0015 "O campo #1 não foi encontrado na estrutura do modelo selecionado"
#else
	#ifdef ENGLISH
		#define STR0001 "Customizable Routines Registration"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Add"
		#define STR0005 "Edit"
		#define STR0006 "Delete"
		#define STR0007 "Customizable Routine Filter Fields"
		#define STR0008 "Description"
		#define STR0009 "Invalid routine entered."
		#define STR0010 "Select a valid MVC routine"
		#define STR0011 "Selected field not found."
		#define STR0012 "Select a valid field."
		#define STR0013 "Field '#1" must be entered when Registration Type is 2-Routines."
		#define STR0014 "Unable to find structure of routine"
		#define STR0015 "Field #1 not found in structure of selected model"
	#else
		#define STR0001 "Cadastro de Rotinas Customizaveis"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Excluir"
		#define STR0007 "Campos de filtro da Rotina Customizavel"
		#define STR0008 "Descrição"
		#define STR0009 "Rotina informada invalida."
		#define STR0010 "Selecione uma rotina MVC válida"
		#define STR0011 "Campo selecionado não encontrado."
		#define STR0012 "Selecione um campo valido."
		#define STR0013 "O campo '#1' precisa ser preenchido quando o Tipo de Cadastro for 2-Rotinas."
		#define STR0014 "Não foi possivel encontrar a estrutura da rotina"
		#define STR0015 "O campo #1 não foi encontrado na estrutura do modelo selecionado"
	#endif
#endif
