#ifdef SPANISH
	#define STR0001 "Parámetros del schedule de avances automáticos: "
	#define STR0002 "#1 - Aviso: Parámetros incorrectos en el schedule de avances automáticos."
	#define STR0003 "#1 - Aviso: Rutina de avances automáticos ya lo está utilizando otra instancia."
	#define STR0004 "#1 - Aviso: Buscando andamentos automaticos."
	#define STR0005 "#1 - Aviso: Gravando avances automáticos."
	#define STR0006 "#1 - Aviso: No existen avances automáticos."
	#define STR0007 "#1 - Aviso: Fin del procesamiento de los avances automáticos."
	#define STR0008 "No se pudo incluir el proceso en al recepción de avances automáticos."
	#define STR0009 "Error: "
	#define STR0010 "Cliente no esta habilitado para utilizar la funcionalidad de recepción del avance automático."
	#define STR0011 "Proceso no se incluirá en la recepción automática de avances."
	#define STR0012 "Entre en contacto con TOTVS."
	#define STR0013 "No se pudo eliminar el proceso de la recepción de avances automáticos."
	#define STR0014 "Proceso no se eliminará de la recepción automática de avances."
	#define STR0015 "No se pudeo recibir los avances automáticos."
	#define STR0016 "Error al validar servicio de monitoreo TOTVS. (MTANDAMENTOS)"
	#define STR0017 "No se pudo incluir el avance automático."
	#define STR0018 "Es necesario actualizar el release."
	#define STR0019 "Atención"
	#define STR0020 "Este asistente lo auxiliara en la configuración del servicio de monitoreo TOTVS."
	#define STR0021 "Configuración del servicio de monitoreo TOTVS"
	#define STR0022 "En este asistente se configurará todo el modo de funcionamiento para acceder al servicio de monitoreo TOTVS, y así recibir los avances de manera automática."
	#define STR0023 "Usuario y contraseña"
	#define STR0024 "En este paso, se debe informar el usuario y contraseña registrado en el servicio de monitoreo de TOTVS."
	#define STR0025 "Usuario: "
	#define STR0026 "Contraseña.: "
	#define STR0027 "Desea recibir avances de procesos ya registrados"
	#define STR0028 "En este punto se definirán los procesos ya registrados que se incluirán en el servico de monitoreo TOTVS."
	#define STR0029 "Los procesos seleccionados aquí, tendrán sus avances recibidos de manera automática en la siguiente ventana de actualización del servicio."
	#define STR0030 "Solo instacias acuale"
	#define STR0031 "Solamente procesos en marcha"
	#define STR0032 "Configuración de parámetros"
	#define STR0033 "Como este servicio se activará por tipo de asunto jurídico, es necesario configurar algunos parámetros."
	#define STR0034 "Cód."
	#define STR0035 "Asunto"
	#define STR0036 "And. Automático"
	#define STR0037 "1=Sí; 2=No"
	#define STR0038 "Finalización"
	#define STR0039 "Modo"
	#define STR0040 "1=Por proceso;2=Por instancia"
	#define STR0041 "Acto"
	#define STR0042 "Justificación"
	#define STR0043 "And. Automático - Define si desea recibir procesos en marcha automáticamente"
	#define STR0044 "Finalización: Define si los procesos finalizados se deben retirar del servicio de monitoreo de TOTVS"
	#define STR0045 "Modo - Define cómo se incluirá el proceso en el servicio de monitoreo de TOTVS"
	#define STR0046 "1 = Por Proceso - Se registrarán todas las instancias del proceso"
	#define STR0047 "2 = Por Instancia - Se seleccionará manualmente la instancia que se debe registrar"
	#define STR0048 "Acto - Define el acto procesal que se debe utilizar para registrar los asuntos en marcha recibidos automáticamente"
	#define STR0049 "Justificación - Define el motivo de justificación que se debe informar para incluir asuntos en marcha como procesos finalizados"
	#define STR0050 "Resumen"
	#define STR0051 "Vea las configuraciones que se efectuarán"
	#define STR0052 "Procesos ya registrados que se incluirán en el servicio de monitoreo TOTVS:"
	#define STR0053 "Tipos de asunto jurídico que se habilitarán en el servicio de monitoreo TOTVS:"
	#define STR0054 "Configuración finalizada con éxito"
	#define STR0055 "Procesando... "
	#define STR0056 "Asunto Jurídico #1"
	#define STR0057 "Intente rehacer el procedimiento más tarde."
	#define STR0058 "No se pudo ubicar la sigla del tribunal(#1), verifique el número del proceso.(#2)"
	#define STR0059 "Modificación realizada por la inclusión del avance automático. (#1)"
	#define STR0060 "No se pudo incluir la justificación."
	#define STR0061 "#1 - Aviso: Analizando procesos recusados."
	#define STR0062 "Informe la justificación"
	#define STR0063 "Informe el Acto"
	#define STR0064 "Actualizando datos en el servicio de monitoreo TOTVS"
	#define STR0065 "Error al enviar el proceso recusado al servicio de monitoreo TOTVS. (MTRECUSADOS)"
	#define STR0066 "PROCESO REGISTRADO"
	#define STR0067 "Descripción no recibida"
	#define STR0068 "Procesos administrativos"
#else
	#ifdef ENGLISH
		#define STR0001 "Automatic progress schedule parameters: "
		#define STR0002 "#1 - Notification: Incorrect parameters in automatic progress schedule."
		#define STR0003 "#1 - Notification: Routine of automatic progress is already being used by another instance."
		#define STR0004 "#1 - Notification: Searching automatic progress."
		#define STR0005 "#1 - Notification: Saving automatic progress."
		#define STR0006 "#1 - Notification: No automatic progress."
		#define STR0007 "#1 - Notification: End of automatic progress processing."
		#define STR0008 "You cannot add process in automatic progress receipt."
		#define STR0009 "Error: "
		#define STR0010 "Customer is not enabled to use functionality of automatic progress receipt."
		#define STR0011 "Process is not added to progress automatic receipt."
		#define STR0012 "Contact TOTVS."
		#define STR0013 "You cannot delete process in automatic progress receipt."
		#define STR0014 "Process is not deleted to progress automatic receipt."
		#define STR0015 "You cannot receive automatic progress."
		#define STR0016 "Error validating TOTVS monitoring service (MTANDAMENTOS)"
		#define STR0017 "Could not add automatic progress."
		#define STR0018 "Update release."
		#define STR0019 "Attention"
		#define STR0020 "This wizard helps configuring TOTVS monitoring service."
		#define STR0021 "Configuration of TOTVS monitoring service"
		#define STR0022 "In this wizard, all working mode is set to access TOTVS monitoring service, so it automatically receives progress."
		#define STR0023 "User and password"
		#define STR0024 "In this step, enter User and Password registered along with TOTVS monitoring service."
		#define STR0025 "User: "
		#define STR0026 "Password: "
		#define STR0027 "Receive progress of processes already registered"
		#define STR0028 "In this point, the already registered processes that are added to TOTVS monitoring service are registered."
		#define STR0029 "Processes selected here have their Progress automatically receipt next window of service updating."
		#define STR0030 "Only current instances"
		#define STR0031 "Only Processes in Progress"
		#define STR0032 "Parameter Configuration"
		#define STR0033 "As this service is activate by Legal Subject Type, configure some parameters."
		#define STR0034 "Code"
		#define STR0035 "Subject"
		#define STR0036 "And. Automatic"
		#define STR0037 "1=Yes;2=No"
		#define STR0038 "Conclusion"
		#define STR0039 "Mode"
		#define STR0040 "1=Per process;2=Per instance"
		#define STR0041 "Act"
		#define STR0042 "Explanation"
		#define STR0043 "Automatic Progress - Defines whether to automatically receive progresses"
		#define STR0044 "Closing - Defines whether the closed processes must be removed from TOTVS monitoring service"
		#define STR0045 "Mode - Defines how the addition of process to TOTVS monitoring service is executed"
		#define STR0046 "1 = Per Process - All instances of the process are registered"
		#define STR0047 "2 = Per Instance - Instance that must be registered is manually selected"
		#define STR0048 "Act - Defines the process act that must be used to register the progress automatically received"
		#define STR0049 "Justification - Defines the justification reason that must be entered to add progress in closed processes"
		#define STR0050 "Summary"
		#define STR0051 "Configurations done"
		#define STR0052 "Processes already registered that are added to TOTVS monitoring service are registered."
		#define STR0053 "Types of Legal Subject that are enabled in TOTVS monitoring service:"
		#define STR0054 "Configuration successfully finished."
		#define STR0055 "Processing... "
		#define STR0056 "Legal Subject #1"
		#define STR0057 "Try to redo procedure later."
		#define STR0058 "Unable to find court acronym (#1), check process number. (#2)"
		#define STR0059 "Change performed by automatic progress addition. (#1)"
		#define STR0060 "Unable to add justification."
		#define STR0061 "#1 - Notification: Analysing rejected processes."
		#define STR0062 "Fill out the Explanation"
		#define STR0063 "Complete Act"
		#define STR0064 "Updating data in TOTVS monitoring service"
		#define STR0065 "Error sending rejected process to TOTVS monitoring service. (MTRECUSADOS)"
		#define STR0066 "PROCESS ALREADY REGISTERED"
		#define STR0067 "Description not received"
		#define STR0068 "Administrative Processes"
	#else
		#define STR0001 "Parametros do schedule de andamentos automaticos: "
		#define STR0002 "#1 - Aviso: Parametros incorretos no schedule de andamentos automaticos."
		#define STR0003 "#1 - Aviso: Rotina de andamentos automaticos já esta sendo utilizada por outra instancia."
		#define STR0004 "#1 - Aviso: Buscando andamentos automaticos."
		#define STR0005 "#1 - Aviso: Gravando andamentos automaticos."
		#define STR0006 "#1 - Aviso: Não existem andamentos automaticos."
		#define STR0007 "#1 - Aviso: Fim do processamento dos andamentos automaticos."
		#define STR0008 "Não foi possível incluir o processo no recebimento de andamentos automático."
		#define STR0009 "Erro: "
		#define STR0010 "Cliente não esta habilitado a utilizar a funcionalidade de recebimento de andamentos automático."
		#define STR0011 "Processo não será incluído no recebimento automático de andamentos."
		#define STR0012 "Entre em contato com a TOTVS."
		#define STR0013 "Não foi possível excluir o processo do recebimento de andamentos automático."
		#define STR0014 "Processo não será excluído do recebimento automático de andamentos."
		#define STR0015 "Não foi possível receber os andamentos automático."
		#define STR0016 "Erro ao validar serviço de monitoramento TOTVS. (MTANDAMENTOS)"
		#define STR0017 "Não foi possível incluir o andamento automático."
		#define STR0018 "É necessario a atualização do release."
		#define STR0019 "Atenção"
		#define STR0020 "Este assistente o auxiliara na configuração do serviço de monitoramento TOTVS."
		#define STR0021 "Configuração do serviço de monitoramento TOTVS"
		#define STR0022 "Neste assistente será configurado todo o modo de funcionamento para ter acesso ao serviço de monitoramento TOTVS, e assim receber os Andamentos de forma Automática."
		#define STR0023 "Usuário e Senha"
		#define STR0024 "Neste passo deve-se informar o Usuário e Senha cadastrado junto ao serviço de monitoramento TOTVS."
		#define STR0025 "Usuario: "
		#define STR0026 "Senha..: "
		#define STR0027 "Deseja receber andamentos de processos já cadastrados"
		#define STR0028 "Neste ponto serão definidos os processos já cadastrados que serão incluídos no serviço de monitoramento TOTVS."
		#define STR0029 "Os processos aqui selecionados terão seus Andamentos recebidos de forma Automática na próxima janela de atualização do serviço."
		#define STR0030 "Apenas instâncias atuais"
		#define STR0031 "Apenas processos em andamento"
		#define STR0032 "Configuração de Parâmetros"
		#define STR0033 "Como este serviço será ativado por Tipo de Assunto Jurídico, será necessário configurar alguns parâmetros."
		#define STR0034 "Cód"
		#define STR0035 "Assunto"
		#define STR0036 "And. Automático"
		#define STR0037 "1=Sim;2=Não"
		#define STR0038 "Encerramento"
		#define STR0039 "Modo"
		#define STR0040 "1=Por processo;2=Por instância"
		#define STR0041 "Ato"
		#define STR0042 "Justificativa"
		#define STR0043 "And. Automático - Define se deseja receber andamentos de forma automática"
		#define STR0044 "Encerramento - Define se os processos encerrados devem ser removidos do serviço de monitoramento TOTVS"
		#define STR0045 "Modo - Define o como irá ser feita a inclusão do processo no serviço de monitoramento TOTVS"
		#define STR0046 "1 = Por Processo - Todas as instâncias do processo serão cadastradas"
		#define STR0047 "2 = Por Instância - Será selecionada manualmente a instância que deve ser cadastrada"
		#define STR0048 "Ato - Define o ato processual que deve ser utilizado para cadastrar os andamentos recebidos de forma automática"
		#define STR0049 "Justificativa - Define qual motivo de justificativa deve ser informado para incluir andamentos em processos encerrados"
		#define STR0050 "Resumo"
		#define STR0051 "Veja as configurações que serão feitas"
		#define STR0052 "Processos já cadastrados que serão incluídos no serviço de monitoramento TOTVS:"
		#define STR0053 "Tipos de Assunto Jurídico que serão habilitados no serviço de monitoramento TOTVS:"
		#define STR0054 "Configuração finalizada com sucesso"
		#define STR0055 "Processando... "
		#define STR0056 "Assunto Jurídico #1"
		#define STR0057 "Tente refazer o procedimento mais tarde."
		#define STR0058 "Não foi possível localizar a sigla do tribunal(#1), verifique o número do processo.(#2)"
		#define STR0059 "Alteração feita pela inclusão do andamento automático. (#1)"
		#define STR0060 "Não foi possível íncluir a justificativa."
		#define STR0061 "#1 - Aviso: Analisando processos recusados."
		#define STR0062 "Preencha a Justificativa"
		#define STR0063 "Preencha o Ato"
		#define STR0064 "Atualizando dados no serviço de monitoramento TOTVS"
		#define STR0065 "Erro ao enviar processo recusado para o serviço de monitoramento TOTVS. (MTRECUSADOS)"
		#define STR0066 "PROCESSO JÁ CADASTRADO"
		#define STR0067 "Descrição não recebida"
		#define STR0068 "Processos Administrativos"
	#endif
#endif
