#ifdef SPANISH
	#define STR0001 "Este programa emitirá el informe de Impuestos "
	#define STR0002 "de acuerdo con parámetros del usuario"
	#define STR0003 "Impuestos"
	#define STR0004 "A rayas"
	#define STR0005 "Administración"
	#define STR0006 "¿De Sucursal?"
	#define STR0007 "¿A Sucursal?"
	#define STR0008 "¿De Fecha?"
	#define STR0009 "¿A Fecha?"
	#define STR0010 "¿De Documento?"
	#define STR0011 "¿A Documento?"
	#define STR0012 "¿% PIS/COFINS?"
	#define STR0014 "                          Serie/               TP                                                                                           "
	#define STR0015 "Fecha    Sucurs Vendedor  Documento  Cliente   Fact.       Valor bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0016 "Espere... Reuniendo información..."
	#define STR0017 "Operación anulada por el operador"
	#define STR0019 "Total vendedor:"
	#define STR0020 "Total sucursal:"
	#define STR0021 "Total fecha:"
	#define STR0022 "Total general:"
	#define STR0023 "Final del informe"
	#define STR0024 " Registro(s) procesado(s)"
	#define STR0025 "Fch/Sucursal/Vendedor"
	#define STR0026 "Fch/Sucursal/Cliente"
	#define STR0027 "Fecha/Sucursal/Factura"
	#define STR0028 "Vendedor/Fch/Sucursal"
	#define STR0029 "¿De Vendedor?"
	#define STR0030 "¿A Vendedor?"
	#define STR0031 "Total Cliente:"
	#define STR0032 "Total del documento:"
	#define STR0033 "                          Serie/               TP                                                                                "
	#define STR0034 "Fecha    Sucur. Cliente   Documento  Vendedor  Fact.       Valor bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0035 "                Serie/                         TP                                                                                "
	#define STR0036 "Fecha    Sucur. Documento  Vendedor  Cliente   Fact.       Valor bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0037 "                          Serie/               TP                                                                                "
	#define STR0038 "Vendedor Fecha    Sucur.  Documento  Cliente   Fact.       Valor bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0057 "¿Tipo del informe?"
	#define STR0060 "Analítico"
	#define STR0061 "Sintético"
	#define STR0066 "                                                           Valor                                                                            "
	#define STR0067 "Fecha    Sucur. Vendedor                                         Bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0068 "                                                           Valor                                                                 "
	#define STR0069 "Fecha    Sucur. Cliente                                          Bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0070 "                Serie/                                     Valor                                                                 "
	#define STR0071 "Fecha    Sucur. Documento                                        Bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0072 "                                                           Valor                                                                 "
	#define STR0073 "Vendedor Fecha    Sucursal                                       Bruto                  ICMS                   IPI                   ISS       Total retenciones      Valor facturado           PIS/COFINS     Valor neto   "
	#define STR0083 "                          Serie/               TP                                                                                           "
	#define STR0084 "Fecha    Sucur. Vendedor  Documento  Cliente   Fact        Valor bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0085 "                          Serie/               TP                                                                                "
	#define STR0086 "Fecha    Sucur. Cliente   Documento  Vendedor  Fact        Valor bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0087 "                Serie/                         TP                                                                                "
	#define STR0088 "Fecha    Sucur. Documento  Vendedor  Cliente   Fact        Valor bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0089 "                          Serie/               TP                                                                                "
	#define STR0090 "Vendedor Fecha    Sucur.  Documento  Cliente   Fact        Valor bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0091 "                                                           Valor                                                                            "
	#define STR0092 "Fecha    Sucur. Vendedor                                         Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0093 "                                                           Valor                                                                 "
	#define STR0094 "Fecha    Sucur. Cliente                                          Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0095 "                Serie/                                     Valor                                                                 "
	#define STR0096 "Fecha    Sucur. Documento                                        Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0097 "                                                           Valor                                                                 "
	#define STR0098 "Vendedor Fecha    Sucursal                                       Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor facturado                          Valor neto"
	#define STR0099 "Fecha/Suc./Docto de Salida "
#else
	#ifdef ENGLISH
		#define STR0001 "This program issues Taxes report"
		#define STR0002 "according to user parameters"
		#define STR0003 "Taxes"
		#define STR0004 "Z-form"
		#define STR0005 "Management"
		#define STR0006 "Branch   from        ?"
		#define STR0007 "Branch   to       ?"
		#define STR0008 "Date     from        ?"
		#define STR0009 "Date     to       ?"
		#define STR0010 "Document from     ?"
		#define STR0011 "Document to    ?"
		#define STR0012 "PIS/COFINS %       ?"
		#define STR0014 "                          Series/               TP                                                                                           "
		#define STR0015 "Date    Sl Rep Branch  Document  Customer  Inv         Gross Value                  ICMS                   IPI                   ISS       Withholding Total        Value Invoiced            PIS/COFINS     Net Value"
		#define STR0016 "Wait... Gathering information..."
		#define STR0017 "Operation canceled by the operator"
		#define STR0019 "Sales Representative Total:"
		#define STR0020 "Branch Total:"
		#define STR0021 "Date Total:"
		#define STR0022 "Grand Total:"
		#define STR0023 "Report End"
		#define STR0024 " Records Processed"
		#define STR0025 "Date/Branch/Sales Representative"
		#define STR0026 "Date/Branch/Customer"
		#define STR0027 "Date/Branch/Invoice"
		#define STR0028 "Sales Representative/Date/Branch"
		#define STR0029 "Sales Representative from        ?"
		#define STR0030 "Sales Representative to       ?"
		#define STR0031 "Customer Total:"
		#define STR0032 "Document total:"
		#define STR0033 "                          Series/               TP                                                                                "
		#define STR0034 "Date    Customer Branch  Document  Sl Rep  Inv         Gross Value                  ICMS                   IPI                   ISS       Withholding Total        Value Invoiced            PIS/COFINS     Net Value"
		#define STR0035 "                Series/                         TP                                                                                "
		#define STR0036 "Date    Document Branch  Sl Rep  Customer  Inv         Gross Value                  ICMS                   IPI                   ISS       Withholding Total        Value Invoiced            PIS/COFINS     Net Value"
		#define STR0037 "                          Series/               TP                                                                                "
		#define STR0038 "Sl Rep Date    Document Branch   Customer  Inv         Gross Value                  ICMS                   IPI                   ISS       Withholding Total        Value Invoiced            PIS/COFINS     Net Value"
		#define STR0057 "Type of Report  ?"
		#define STR0060 "Detailed"
		#define STR0061 "Summarized"
		#define STR0066 "                                                           Value                                                                            "
		#define STR0067 "Date     Sl Rep Branch                                         Gross                  ICMS                   IPI                   ISS       Withholding Total      Value Invoiced            PIS/COFINS     Net Value"
		#define STR0068 "                                                           Value                                                                 "
		#define STR0069 "Date     Customer Branch                                         Gross                  ICMS                   IPI                   ISS       Withholding Total      Value Invoiced            PIS/COFINS     Net Value"
		#define STR0070 "                Series/                                     Value                                                                 "
		#define STR0071 "Date     Document Branch                                        Gross                  ICMS                   IPI                   ISS       Withholding Total      Value Invoiced            PIS/COFINS     Net Value"
		#define STR0072 "                                                           Value                                                                 "
		#define STR0073 "Sl Rep Date     Branch                                        Gross                  ICMS                   IPI                   ISS       Withholding Total      Value Invoiced            PIS/COFINS     Net Value"
		#define STR0083 "                          Series/               TP                                                                                           "
		#define STR0084 "Date Branch/Sales Representative Document Customer Invoiced Gross Value Tax Value Disc. Tax Value Inc. Invoiced Value Net Value"
		#define STR0085 "                          Series/               TP                                                                                "
		#define STR0086 "Date Branch Customer Document Sales Representative Invoiced Gross Value Tax Value Disc. Tax Value Inc. Invoiced Value Net Value"
		#define STR0087 "                Series/                         TP                                                                                "
		#define STR0088 "Date Branch Document Sales Representative Customer Invoiced Gross Value Tax Value Disc. Tax Value Inc. Invoiced Value Net Value"
		#define STR0089 "                          Series/               TP                                                                                "
		#define STR0090 "Sales Representative/Date/Branch Document Customer Invoiced Gross Value Tax Value Disc. Tax Value Inc. Invoiced Value Net Value"
		#define STR0091 "                                                           Value                                                                            "
		#define STR0092 "Date Branch Sales Representative Gross Value Tax Value Disc. Tax Value Inc. Net Value"
		#define STR0093 "                                                           Value                                                                 "
		#define STR0094 "Date Branch Customer Gross Value Tax Value Disc. Tax Value Inc. Net Value"
		#define STR0095 "                Series/                                     Value                                                                 "
		#define STR0096 "Date Branch Document Gross Value Tax Value Disc. Tax Value Inc. Net Value"
		#define STR0097 "                                                           Value                                                                 "
		#define STR0098 "Sales Representative Date Branch Gross Value Tax Value Disc. Tax Value Inc. Net Value"
		#define STR0099 "Date/Brch/Outgoing Doc."
	#else
		#define STR0001 "Este programa emitirá o relatório de Impostos"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "conforme parâmetros do utilizador", "conforme parâmetros do usuário" )
		#define STR0003 "Impostos"
		#define STR0004 "Zebrado"
		#define STR0005 "Administração"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Filial   de        ?", "Filial De?" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Filial   até       ?", "Filial Até?" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Data     de        ?", "Data De?" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Data     até       ?", "Data  Até?" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Documento   de     ?", "Documento De?" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Documento   até    ?", "Documento Até?" )
		#define STR0012 "% PIS/COFINS       ?"
		#define STR0014 "                          Série/               TP                                                                                           "
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Data     Filial Vendedor  Documento  Cliente   F          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Data     Filial Vendedor  Documento  Cliente   NF          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Aguarde... A reunir informações...", "Aguarde... Reunindo Informações..." )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Operação cancelada pelo operador", "Operação Cancelada pelo Operador" )
		#define STR0019 "Total do Vendedor:"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Total da filial:", "Total da Filial:" )
		#define STR0021 "Total da Data:"
		#define STR0022 "Total Geral:"
		#define STR0023 "Fim do Relatório"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", " Registo(s) Processado(s)", " Registro(s) Processado(s)" )
		#define STR0025 "Data/Filial/Vendedor"
		#define STR0026 "Data/Filial/Cliente"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Data/Filial/Factura", "Data/Filial/Nota Fiscal" )
		#define STR0028 "Vendedor/Data/Filial"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Vendedor de        ?", "Vendedor De?" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Vendedor até       ?", "Vendedor Até?" )
		#define STR0031 "Total do Cliente:"
		#define STR0032 "Total do Documento:"
		#define STR0033 "                          Série/               TP                                                                                "
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Data     Filial Cliente   Documento  Vendedor  F          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Data     Filial Cliente   Documento  Vendedor  NF          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "                Série/                         TP                                                                                ", "                Serie/                         TP                                                                                " )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Data     Filial Documento  Vendedor  Cliente   F          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Data     Filial Documento  Vendedor  Cliente   NF          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0037 "                          Série/               TP                                                                                "
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Vendedor Data     Filial  Documento  Cliente   F          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Vendedor Data     Filial  Documento  Cliente   NF          Valor Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0057 "Tipo do Relatório  ?"
		#define STR0060 "Analítico"
		#define STR0061 "Sintético"
		#define STR0066 "                                                           Valor                                                                            "
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Data     Filial Vendedor                                         Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Data     Filial Vendedor                                         Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0068 "                                                           Valor                                                                 "
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Data     Filial Cliente                                          Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Data     Filial Cliente                                          Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0070 "                Série/                                     Valor                                                                 "
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Data     Filial Documento                                        Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Data     Filial Documento                                        Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0072 "                                                           Valor                                                                 "
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Vendedor Data     Filial                                         Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Facturado            PIS/COFINS     Valor Líquido", "Vendedor Data     Filial                                         Bruto                  ICMS                   IPI                   ISS       Total Retenções        Valor Faturado            PIS/COFINS     Valor Líquido" )
		#define STR0083 "                          Série/               TP                                                                                           "
		#define STR0084 "Data     Filial Vendedor  Documento  Cliente   Fat         Valor Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                          Valor Líquido"
		#define STR0085 "                          Série/               TP                                                                                "
		#define STR0086 "Data     Filial Cliente   Documento  Vendedor  Fat         Valor Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                          Valor Líquido"
		#define STR0087 "                Série/                         TP                                                                                "
		#define STR0088 "Data     Filial Documento  Vendedor  Cliente   Fat         Valor Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                           Valor Líquido"
		#define STR0089 "                          Série/               TP                                                                                "
		#define STR0090 "Vendedor Data     Filial  Documento  Cliente   Fat         Valor Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                           Valor Líquido"
		#define STR0091 "                                                           Valor                                                                            "
		#define STR0092 "Data     Filial Vendedor                                         Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                           Valor Líquido"
		#define STR0093 "                                                           Valor                                                                 "
		#define STR0094 "Data     Filial Cliente                                          Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                           Valor Líquido"
		#define STR0095 "                Série/                                     Valor                                                                 "
		#define STR0096 "Data     Filial Documento                                        Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                           Valor Líquido"
		#define STR0097 "                                                           Valor                                                                 "
		#define STR0098 "Vendedor Data     Filial                                         Bruto                             Valor Imp. Disc.                      Valor Imp. Inc.             Valor Faturado                           Valor Líquido"
		#define STR0099 "Data/Fil./Docto de Saída "
	#endif
#endif
