#ifdef SPANISH
	#define STR0001 "Aguarde...Verificando prazo..."
	#define STR0002 "Sem comunicação com o WebService!"
	#define STR0003 "Atenção."
#else
	#ifdef ENGLISH
		#define STR0001 "Aguarde...Verificando prazo..."
		#define STR0002 "Sem comunicação com o WebService!"
		#define STR0003 "Atenção."	
	#else
		#define STR0001 "Aguarde...Verificando prazo..."
		#define STR0002 "Sem comunicação com o WebService!"
		#define STR0003 "Atenção."	
	#endif
#endif
