#ifdef SPANISH
	#define STR0001 "Datos del evento"
	#define STR0002 "Lista de productos"
	#define STR0003 "Recolectar PDA"
	#define STR0004 "Cuenta corriente"
	#define STR0005 "Finalizar lista"
	#define STR0006 "Sugerencia"
	#define STR0007 "Entrega futura"
	#define STR0008 "Imprimir"
	#define STR0009 "Grabar"
	#define STR0010 "Finalizar"
	#define STR0011 "Lista de actores"
	#define STR0012 "Linea "
	#define STR0013 " duplicada."
	#define STR0014 "Lista de entregas programadas"
	#define STR0015 "Entregas programadas"
	#define STR0016 "Confirmar"
	#define STR0017 "Recalcular"
	#define STR0018 "¡La fecha de la secuencia "
	#define STR0019 " es invalida!"
	#define STR0020 "Para proseguir es necesario definir la fecha del evento, fecha inicial, fecha de disponibilidad y fecha de validez de la lista."
	#define STR0021 "La fecha de validez no puede ser inferior a la fecha inicial."
	#define STR0022 "La fecha del evento no puede ser inferior a la fecha inicial."
	#define STR0023 "La fecha de validez no puede ser inferior a la fecha del evento."
	#define STR0024 "La fecha de disponibilidad de la lista no puede ser inferior a la fecha inicial de la lista."
	#define STR0025 "La fecha de disponibilidad de la lista no puede ser superior a la fecha del evento."
	#define STR0026 "¡Para importar items, es necesario definir el organizador!"
	#define STR0027 "¿Desea seleccionar un vendedor para vincular los items por insertar?"
	#define STR0028 "Resultado del proceso de importacion de items"
	#define STR0029 "Total items"
	#define STR0030 "Total items importados"
	#define STR0031 "Total items creados"
	#define STR0032 "Total items incorporados"
	#define STR0033 "Total items bloqueados"
	#define STR0034 "Total items con codigo de producto inexistente"
	#define STR0035 "Total items rechazados por campo obligatorio ausente"
	#define STR0036 "Detalle"
	#define STR0037 "Items creados"
	#define STR0038 "Ningun item"
	#define STR0039 "Items incorporados"
	#define STR0040 "Items bloqueados"
	#define STR0041 "Items con codigo de producto inexistente"
	#define STR0042 "Items rechazados por campo obligatorio ausente"
	#define STR0043 "Procesamiento de importacion"
	#define STR0044 "¡Ausencia de informacion de archivo impide la ejecucion de la prueba de rutina automatica!"
	#define STR0045 "Buscar"
	#define STR0046 "Visualizar"
	#define STR0047 "Incluir"
	#define STR0048 "Modificar"
	#define STR0049 "Borrar"
	#define STR0050 "¡La lista se finalizo con exito!"
	#define STR0051 "Actores"
	#define STR0052 "Funciones"
	#define STR0053 "LJLISPREA"
	#define STR0054 "LJ843NREC"
	#define STR0055 "LJ843BLQ"
	#define STR0056 "LJ843PBL"
	#define STR0057 "LJ843AtV"
	#define STR0058 "NVAZIO"
	#define STR0059 "OBRIGAT"
	#define STR0060 "JAGRAVADO"
	#define STR0061 "LJ843NA1"
	#define STR0062 "LJ843NA2"
	#define STR0063 "LJ843NCL"
	#define STR0064 "LJ843DTDP"
	#define STR0065 "LJ843NCNT"
	#define STR0066 "LJ843ICNT"
	#define STR0067 "LJ843ECNT"
	#define STR0068 "LJ843PEP"
	#define STR0069 "LJ843PEE"
	#define STR0070 "LJ843SLD"
	#define STR0071 "LJ843NEX"
	#define STR0072 "LJ843LNE"
	#define STR0073 "LJ843PE2"
	#define STR0074 "LJ843PE3"
	#define STR0075 "LJ843PE1"
	#define STR0076 "LJ843VOB"
	#define STR0077 "Importar"
	#define STR0078 "Crear nueva"
	#define STR0079 "Sugerencia de lista de presentes"
	#define STR0080 "Registro de sugerencia de lista"
	#define STR0081 "OK"
	#define STR0082 "Anula"
	#define STR0083 "Es necesario informar el contenido de todos los campos obligatorios antes de la grabacion"
	#define STR0084 "Há produtos informados duas vezes nos itens da lista de presente. "
	#define STR0085 "Por favor exclua um dos produtos duplicados."
	#define STR0086 "Recoleccion finalizada con exito"
	#define STR0087 "Recoleccion no finalizada con exito"
	#define STR0088 "Con relacion al archivo importado, desea que se haga:"
	#define STR0089 "Backup"
	#define STR0090 "Borrar"
	#define STR0091 "Ignorar"
	#define STR0092 "No es posible modificar el tipo, porque ya existen movimientos para esta lista."
	#define STR0093 "Atención"
	#define STR0094 "Producto o código de barras no encontrado."
#else
	#ifdef ENGLISH
		#define STR0001 "Event data"
		#define STR0002 "Product list"
		#define STR0003 "Collect PDA"
		#define STR0004 "Checking Account"
		#define STR0005 "Close list"
		#define STR0006 "Suggestion"
		#define STR0007 "Future Delivery"
		#define STR0008 "Print"
		#define STR0009 "Save"
		#define STR0010 "Close"
		#define STR0011 "List of actors"
		#define STR0012 "Row "
		#define STR0013 " duplicate."
		#define STR0014 "List of scheduled deliveries"
		#define STR0015 "Scheduled Deliveries"
		#define STR0016 "Confirm"
		#define STR0017 "Recalculate"
		#define STR0018 "Sequence date "
		#define STR0019 " is invalid!"
		#define STR0020 "To continue, you must define event date, start date, availability date, and list due date."
		#define STR0021 "Due date cannot be before start date."
		#define STR0022 "Event date cannot be before start date."
		#define STR0023 "Due date cannot be before event date."
		#define STR0024 "List availability date cannot be before list start date."
		#define STR0025 "List availability date cannot be after event date."
		#define STR0026 "To import items, define the organizer!"
		#define STR0027 "Do you want to select a sales representative to link the items to add?"
		#define STR0028 "Result of item import process"
		#define STR0029 "Item total"
		#define STR0030 "Total of items imported"
		#define STR0031 "Total of items created"
		#define STR0032 "Total of items incorporated"
		#define STR0033 "Total of items blocked"
		#define STR0034 "Total of items with a product code that does not exist"
		#define STR0035 "Total of items rejected per empty mandatory field"
		#define STR0036 "Detail"
		#define STR0037 "Items created"
		#define STR0038 "No item"
		#define STR0039 "Items incorporated"
		#define STR0040 "Items blocked"
		#define STR0041 "Items with a product code that does not exist"
		#define STR0042 "Items rejected per empty mandatory field"
		#define STR0043 "Import Processing"
		#define STR0044 "Lack of register information does not enable automatic routine test!"
		#define STR0045 "Search"
		#define STR0046 "View"
		#define STR0047 "Add"
		#define STR0048 "Change"
		#define STR0049 "Delete"
		#define STR0050 "List was successfully closed!"
		#define STR0051 "Actors"
		#define STR0052 "Positions"
		#define STR0053 "LJLISPREA"
		#define STR0054 "LJ843NREC"
		#define STR0055 "LJ843BLQ"
		#define STR0056 "LJ843PBL"
		#define STR0057 "LJ843AtV"
		#define STR0058 "NEMPTY"
		#define STR0059 "MANDAT"
		#define STR0060 "ALREADYSAVED"
		#define STR0061 "LJ843NA1"
		#define STR0062 "LJ843NA2"
		#define STR0063 "LJ843NCL"
		#define STR0064 "LJ843DTDP"
		#define STR0065 "LJ843NCNT"
		#define STR0066 "LJ843ICNT"
		#define STR0067 "LJ843ECNT"
		#define STR0068 "LJ843PEP"
		#define STR0069 "LJ843PEE"
		#define STR0070 "LJ843SLD"
		#define STR0071 "LJ843NEX"
		#define STR0072 "LJ843LNE"
		#define STR0073 "LJ843PE2"
		#define STR0074 "LJ843PE3"
		#define STR0075 "LJ843PE1"
		#define STR0076 "LJ843VOB"
		#define STR0077 "Import"
		#define STR0078 "Create new"
		#define STR0079 "Gift List Suggestion"
		#define STR0080 "List Suggestion File"
		#define STR0081 "OK"
		#define STR0082 "Cancel"
		#define STR0083 "You must enter the content of all the mandatory fields before saving"
		#define STR0084 "There are products entered twice in the gifts list. "
		#define STR0085 "Please delete one of the duplicated products."
		#define STR0086 "Collection successfully finished."
		#define STR0087 "Collection successfully unfinished."
		#define STR0088 "Regarding the file imported, you want to:"
		#define STR0089 "Backup"
		#define STR0090 "Delete"
		#define STR0091 "Ignore"
		#define STR0092 "You cannot change type as there are movements for this list."
		#define STR0093 "Attention"
		#define STR0094 "Product or Bar Code not found."
	#else
		#define STR0001 "Dados do evento"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Lista de artigos", "Lista de produtos" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Recolher PDA", "Coletar PDA" )
		#define STR0004 "Conta corrente"
		#define STR0005 "Encerrar lista"
		#define STR0006 "Sugestão"
		#define STR0007 "Entrega futura"
		#define STR0008 "Imprimir"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Gravar", "Salvar" )
		#define STR0010 "Fechar"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Lista de actores", "Lista de atores" )
		#define STR0012 "Linha "
		#define STR0013 " duplicada."
		#define STR0014 "Lista de entregas programadas"
		#define STR0015 "Entregas programadas"
		#define STR0016 "Confirmar"
		#define STR0017 "Recalcular"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "A data da seqüência ", "A data da sequência " )
		#define STR0019 " é inválida!"
		#define STR0020 "Para prosseguir, é necessário definir a data do evento, data inicial, data de disponibilidade e data de validade da lista."
		#define STR0021 "A data de validade não pode ser menor que a data inicial."
		#define STR0022 "A data do evento não pode ser menor que a data inicial."
		#define STR0023 "A data de validade não pode ser menor que a data do evento."
		#define STR0024 "A data de disponibilidade da lista não pode ser menor que a data inicial da lista."
		#define STR0025 "A data de disponibilidade da lista não pode ser maior que a data do evento."
		#define STR0026 "Para importar itens, é necessário definir o organizador!"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Deseja seleccionar um vendedor para vincular os itens a inserir?", "Deseja selecionar um vendedor para vincular os itens à inserir?" )
		#define STR0028 "Resultado do processo de importação de itens"
		#define STR0029 "Total itens"
		#define STR0030 "Total itens importados"
		#define STR0031 "Total itens criados"
		#define STR0032 "Total itens incorporados"
		#define STR0033 "Total itens bloqueados"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Total itens com código de artigo inexistente", "Total itens com código de produto inexistente" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Total itens rejeitados por campo obrigatório ausente", "Total itens rejeitados por campo obrigatorio ausente" )
		#define STR0036 "Detalhamento"
		#define STR0037 "Itens criados"
		#define STR0038 "Nenhum item"
		#define STR0039 "Itens incorporados"
		#define STR0040 "Itens bloqueados"
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Itens com código de artigo inexistente", "Itens com código de produto inexistente" )
		#define STR0042 "Itens rejeitados por campo obrigatório ausente"
		#define STR0043 "Processamento de importação"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Ausência de informações de registo impedem a execução do teste de procedimento automatico.", "Ausencia de informações de cadastro impedem a execução do teste de rotina automatica!" )
		#define STR0045 "Pesquisar"
		#define STR0046 "Visualizar"
		#define STR0047 "Incluir"
		#define STR0048 "Alterar"
		#define STR0049 "Excluir"
		#define STR0050 "A lista foi encerrrada com sucesso!"
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Actores", "Atores" )
		#define STR0052 "Funções"
		#define STR0053 "LJLISPREA"
		#define STR0054 "LJ843NREC"
		#define STR0055 "LJ843BLQ"
		#define STR0056 "LJ843PBL"
		#define STR0057 "LJ843AtV"
		#define STR0058 "NVAZIO"
		#define STR0059 "OBRIGAT"
		#define STR0060 "JAGRAVADO"
		#define STR0061 "LJ843NA1"
		#define STR0062 "LJ843NA2"
		#define STR0063 "LJ843NCL"
		#define STR0064 "LJ843DTDP"
		#define STR0065 "LJ843NCNT"
		#define STR0066 "LJ843ICNT"
		#define STR0067 "LJ843ECNT"
		#define STR0068 "LJ843PEP"
		#define STR0069 "LJ843PEE"
		#define STR0070 "LJ843SLD"
		#define STR0071 "LJ843NEX"
		#define STR0072 "LJ843LNE"
		#define STR0073 "LJ843PE2"
		#define STR0074 "LJ843PE3"
		#define STR0075 "LJ843PE1"
		#define STR0076 "LJ843VOB"
		#define STR0077 "Importar"
		#define STR0078 "Criar nova"
		#define STR0079 "Sugestão de lista de presentes"
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "Registo de sugestão de lista", "Cadastro de sugestao de lista" )
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "OK", "Ok" )
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Cancelar", "Cancela" )
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "É necessário informar o conteúdo de todos os campos obrigatórios antes da gravação", "É necessário informar o conteúdo de todos os campos obrigatorios antes da gravação" )
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Há artigos informados duas vezes nos itens da lista de presente. ", "Há produtos informados duas vezes nos itens da lista de presente. " )
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "Por favor, exclua um dos artigos duplicados.", "Por favor exclua um dos produtos duplicados." )
		#define STR0086 If( cPaisLoc $ "ANG|PTG", "Recolhimento finalizado com sucesso", "Coleta finalizada com sucesso" )
		#define STR0087 If( cPaisLoc $ "ANG|PTG", "Recolhimento não finalizado com sucesso", "Coleta não finalizada com sucesso" )
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "En relação ao ficheiro importado, deseja que seja feito:", "Em relação ao arquivo importado deseja que seja feito:" )
		#define STR0089 "Backup"
		#define STR0090 "Apagar"
		#define STR0091 "Ignorar"
		#define STR0092 "Não é possível alterar o seu tipo pois já existe(m) movimentação(ões) para esta lista."
		#define STR0093 "Atenção"
		#define STR0094 "Produto ou Código de barras não encontrado."
	#endif
#endif
