#ifdef SPANISH
	#define STR0001 "Asistente de generacion de carga"
	#define STR0002 "Asistente de configuracion y generacion de carga del Control de Tiendas"
	#define STR0003 "Introduccion"
	#define STR0004 "Este asistente le ayudara en la configuracion y disposicion de la carga."
	#define STR0005 "En la pagina 'Seleccion de las tablas que se generaran' seleccionara las tablas que se generaran."
	#define STR0006 "Inmediatamente despues, en la pagina 'Seleccion de las sucursales que se generaran', seleccionara las sucursales que se generaran."
	#define STR0007 "Finalmente en la pagina 'Generacion de la carga' podra ejecutar la generacion de carga y asi poner a disposicion los archivos para que el terminal los baje por medio del Servidor de Archivos del Control de Tiendas."
	#define STR0008 "Creando lista de tablas."
	#define STR0009 "Espere..."
	#define STR0010 "Asistente de configuracion y generacion de carga del Control de Tiendas"
	#define STR0011 "Seleccion de las tablas que se generaran"
	#define STR0012 "Creando lista de sucursales."
	#define STR0013 "Tabla"
	#define STR0014 "Descripcion"
	#define STR0015 "Buscar:"
	#define STR0016 "Buscar"
	#define STR0017 "Buscando."
	#define STR0018 "Tablas que se generaran"
	#define STR0019 "Agregar"
	#define STR0020 "Agregando."
	#define STR0021 "Retirar"
	#define STR0022 "Retirando."
	#define STR0023 "Agregar todos"
	#define STR0024 "Retirar todos"
	#define STR0025 "Asistente de configuracion y generacion de carga del Control de Tiendas"
	#define STR0026 "Seleccion de las sucursales que se generaran"
	#define STR0027 "Empresa"
	#define STR0028 "Sucursal"
	#define STR0029 "Descripcion"
	#define STR0030 "Sucursales que se generaran"
	#define STR0031 "Asistente de configuracion y generacion de carga del Control de Tiendas"
	#define STR0032 "Generacion de la carga"
	#define STR0033 "Estado de la ultima carga dispuesta"
	#define STR0034 "Estatus:"
	#define STR0035 "Generado:"
	#define STR0036 "Tablas:"
	#define STR0037 "Sucursales:"
	#define STR0038 "Registros:"
	#define STR0039 "Progreso de la generacion de la carga"
	#define STR0040 "Estatus:"
	#define STR0041 "Tabla:"
	#define STR0042 "Velocidad:"
	#define STR0043 "Progreso:"
	#define STR0044 "Generar Carga"
	#define STR0045 "¿Desea iniciar la generacion de carga?"
	#define STR0046 "Hubo un error al intentar ejecutar la operacion."
	#define STR0047 "Generado"
	#define STR0048 "No generado"
	#define STR0049 "Camino del reposiorio del servidor de archivo no configurado."
	#define STR0050 "Tablas de la carga inicial no informadas."
	#define STR0051 "Sucursales de la carga inicial no informadas."
	#define STR0052 "Iniciado"
	#define STR0053 "Exportando"
	#define STR0054 "Compactando"
	#define STR0055 "Finalizado"
	#define STR0056 "Cargando grupos de tablas."
	#define STR0057 "Seleccion del grupo de tablas"
	#define STR0058 "Seleccione el grupo que se utilizara, o utilice los botones para renombrar o borrar el grupo seleccionado e incluir para agregar un nuevo grupo."
	#define STR0059 "Codigo"
	#define STR0060 "Nombre"
	#define STR0061 "Descripcion"
	#define STR0062 "Renombrar"
	#define STR0063 "Renombrando."
	#define STR0064 "Configurar"
	#define STR0065 "Configurando."
	#define STR0066 "Grabar"
	#define STR0067 "Anular"
	#define STR0068 "Parametros"
	#define STR0069 "Completo"
	#define STR0070 "Parcial"
	#define STR0071 "Especial"
	#define STR0072 "Configurar transferencia completa"
	#define STR0073 "Filtro:"
	#define STR0074 "Asistente"
	#define STR0075 "Sucursales:"
	#define STR0076 "Configurar transferencia parcial"
	#define STR0077 "Registros que se generaran"
	#define STR0078 "Indice"
	#define STR0079 "Registro"
	#define STR0080 "Clave"
	#define STR0081 "Indice:"
	#define STR0082 "Registro:"
	#define STR0083 "Asistente"
	#define STR0084 "Seleccione un grupo de tablas"
	#define STR0085 "Completo - Sustituye la tabla de destino"
	#define STR0086 "Parcial - Transfiere solaamente los registros seleccionados"
	#define STR0087 "Especial - Transferencias desarrolladas para tablas especiales"
	#define STR0088 "Seleccione el modo de transferencia."
	#define STR0089 "Informacion"
	#define STR0090 "Completo"
	#define STR0091 "Parcial"
	#define STR0092 "por lo menos una filial debe seleccionarse para esta tabla."
	#define STR0093 "Tipo"
	#define STR0094 "Carga Entera"
	#define STR0095 "Carga Incremental"
	#define STR0096 "Incremental"
	#define STR0097 "Entera"
	#define STR0098 "Analizando tabla a exportar"
	#define STR0099 "Actualizando registros exportados"
	#define STR0100 "Guardar Configuraciones"
	#define STR0101 "Para tablas compartidas no sera posible seleccionar la sucursal."
	#define STR0102 "Configuraciones guardadas con exito."
	#define STR0103 "Seleccion de la lista de precio"
	#define STR0104 "Seleccione la lista de precio que se considerara en la generación de carga de la tabla SBI."
	#define STR0105 "OK"
	#define STR0106 "Para proseguir con la generacion de la carga, debe informarse la lista de precio que se considera para generacion del precio en la lista SBI."
	#define STR0107 "Carga generada con éxito. "
	#define STR0108 "Desea agregar una tabla complemento del cliente AI0"
	#define STR0109 "Recuerde de ejecutar 'UPDCARGA - Facilitador para la creación de los campos reservados de la carga'."
	#define STR0110 "Programaciones de agenda"
	#define STR0111 "Cargando...."
	#define STR0112 "Para la utilización de la nueva programación en agenda su entorno debe estar actualizado. Verifique con el departamento de tecnología de la información de su empresa."
	#define STR0113 "No es posible continuar"
	#define STR0114 "No es posible incluir la Programación en agenda antes de grabar el Grupo de cargas. Haga clic en Avanzar / Grabar configuraciones y regrese a inclusión de programación en agenda."
	#define STR0115 "Seleccione el tipo de filtro:"
	#define STR0116 "por Clave"
	#define STR0117 "por Expresión"
	#define STR0118 "Para la carga parcial es necesario seleccionar e informar uno de los tipos de filtro."
#else
	#ifdef ENGLISH
		#define STR0001 "Wizard of load generation"
		#define STR0002 "Wizard of configuration and generation of Store Control load"
		#define STR0003 "Introduction"
		#define STR0004 "This wizard will help you configure the load and make it available."
		#define STR0005 "In page 'Selection of tables to be generated,' you will select tables to be generated."
		#define STR0006 "After that, in page 'Selection of branches to be generated,' you will select branches to be generated."
		#define STR0007 "Finally, in page 'Generation of load,' you can generate the load and make files available to be downloaded by the terminal, through the Store Control File Server."
		#define STR0008 "Creating list of tables."
		#define STR0009 "Wait..."
		#define STR0010 "Wizard of configuration and generation of Store Control load"
		#define STR0011 "Selection of tables to be generated"
		#define STR0012 "Creating list of branches."
		#define STR0013 "Table"
		#define STR0014 "Description"
		#define STR0015 "Search:"
		#define STR0016 "Search"
		#define STR0017 "Searching."
		#define STR0018 "Tables to be generated"
		#define STR0019 "Add"
		#define STR0020 "Adding."
		#define STR0021 "Remove"
		#define STR0022 "Removing."
		#define STR0023 "Add all"
		#define STR0024 "Remove all"
		#define STR0025 "Wizard of configuration and generation of Store Control load"
		#define STR0026 "Selection of branches to be generated"
		#define STR0027 "Company"
		#define STR0028 "Branch"
		#define STR0029 "Description"
		#define STR0030 "Branches to be generated"
		#define STR0031 "Wizard of configuration and generation of Store Control load"
		#define STR0032 "Load generation"
		#define STR0033 "Status of last load available"
		#define STR0034 "Status:"
		#define STR0035 "Generated:"
		#define STR0036 "Tables:"
		#define STR0037 "Branches:"
		#define STR0038 "Records:"
		#define STR0039 "Progress of load generation"
		#define STR0040 "Status:"
		#define STR0041 "Table:"
		#define STR0042 "Speed:"
		#define STR0043 "Progress:"
		#define STR0044 "Generate Load"
		#define STR0045 "Do you want to start generating load?"
		#define STR0046 "An error occurred while attempting to perform the operation."
		#define STR0047 "Generated"
		#define STR0048 "Not generated"
		#define STR0049 "Path of file server repository not configured."
		#define STR0050 "Tables of initial load not informed."
		#define STR0051 "Branches of initial load not informed."
		#define STR0052 "Started"
		#define STR0053 "Exporting"
		#define STR0054 "Compressing"
		#define STR0055 "Finished"
		#define STR0056 "Uploading groups of tables."
		#define STR0057 "Selection of group of tables"
		#define STR0058 "Select group to be used, or use the buttons to rename or delete group selected and to add a new group."
		#define STR0059 "Code"
		#define STR0060 "Name"
		#define STR0061 "Description"
		#define STR0062 "Rename"
		#define STR0063 "Renaming"
		#define STR0064 "Configure"
		#define STR0065 "Configuring."
		#define STR0066 "Save"
		#define STR0067 "Cancel"
		#define STR0068 "Parameters"
		#define STR0069 "Complete"
		#define STR0070 "Partial"
		#define STR0071 "Special"
		#define STR0072 "Configure complete transfer"
		#define STR0073 "Filter:"
		#define STR0074 "Wizard"
		#define STR0075 "Branches:"
		#define STR0076 "Configure partial transfer"
		#define STR0077 "Registrations to be generated"
		#define STR0078 "Index"
		#define STR0079 "Record"
		#define STR0080 "Key"
		#define STR0081 "Index:"
		#define STR0082 "Record:"
		#define STR0083 "Wizard"
		#define STR0084 "Select a group of tables"
		#define STR0085 "Complete - It replaces destination table;"
		#define STR0086 "Partial - It transfers only registration selected;"
		#define STR0087 "Special - Pre-developed transfers for special tables"
		#define STR0088 "Select transfer mode"
		#define STR0089 "Information"
		#define STR0090 "Complete"
		#define STR0091 "Partial"
		#define STR0092 "At least one branch must be selected for this table."
		#define STR0093 "Type"
		#define STR0094 "Full Load"
		#define STR0095 "Incremental Load"
		#define STR0096 "Incremental"
		#define STR0097 "Full"
		#define STR0098 "Analyzing table to export"
		#define STR0099 "Updating exported records"
		#define STR0100 "Save Configurations"
		#define STR0101 "For shared tables, the branch cannot be selected."
		#define STR0102 "Configurations saved successfully"
		#define STR0103 "Selection of price table"
		#define STR0104 "Select the price table to be considered when generating the SBI table load."
		#define STR0105 "OK"
		#define STR0106 "To continue with the load generation, enter the price table to be considered when generating price in SBI table."
		#define STR0107 "Load successfully generated "
		#define STR0108 "Add Table Complement of Customer AI0"
		#define STR0109 "Run 'UPDCARGA - Facilitator to create load reserved fields'."
		#define STR0110 "Schedules"
		#define STR0111 "Loading..."
		#define STR0112 "Your environment must be updated to use the new schedule. Check with your company's IT department."
		#define STR0113 "Unable to continue."
		#define STR0114 "Unable add the Schedule before saving the Cargo Group. Click Next / Save Settings and return to add the schedule."
		#define STR0115 "Select the type of filter:"
		#define STR0116 "per Key"
		#define STR0117 "per Expression"
		#define STR0118 "For the partial load, select and complete the types of filter."
	#else
		#define STR0001 "Assistente de geração de carga"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Assistente de configuração e geração de carga do Controlo de Lojas", "Assistente de configuração e geração de carga do Controle de Lojas" )
		#define STR0003 "Introdução"
		#define STR0004 "Esse assistente lhe auxiará na configuração e disponibilização da carga."
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Na página 'Selecção das tabelas a serem geradas' você selecionará as tabelas que serão geradas.", "Na página 'Seleção do grupo de tabelas' você irá selecionar o grupo de tabelas a ser utilizado." )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Logo em seguida, na página 'Selecção das filiais a serem geradas', você seleccionará as filiais que serão geradas.", "Logo em seguida, na página 'Seleção das tabelas a serem geradas' você irá selecionar as tabelas que serão geradas." )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Finalmente na página 'Geração da carga' poderá executar a geração de carga e assim disponibilizar os ficheiros para serem liquidados pelo terminal através do Servidor de Ficheiros do Controlo de Lojas.", "Finalmente na página 'Geração da carga' poderá executar a geração de carga e assim disponibilizar os arquivos para serem baixados pelo terminal através do Servidor de Arquivos do Controle de Lojas." )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "A criar lista de tabelas.", "Criando lista de tabelas." )
		#define STR0009 "Aguarde..."
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Assistente de configuração e geração de carga do Controlo de Lojas", "Assistente de configuração e geração de carga do Controle de Lojas" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Selecção das tabelas a serem geradas", "Seleção das tabelas a serem geradas" )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "A criar lista de filiais.", "Verificando estado da geração." )
		#define STR0013 "Tabela"
		#define STR0014 "Descrição"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Procurar:", "Procurar" )
		#define STR0016 "Procurar"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "A Procurar.", "Procurando." )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Tabelas que serão geradas", "Tabelas disponíveis" )
		#define STR0019 "Adicionar"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "A Adicionar.", "Adicionando." )
		#define STR0021 "Remover"
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "A Remover.", "Removendo." )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Adicionar todos", "Modo" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Remover todos", "Tabelas selecionadas" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Assistente de configuração e geração de carga do Controlo de Lojas", "Configurar grupo de tabelas" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Selecção das filiais a serem geradas", "Nome:" )
		#define STR0027 "Empresa"
		#define STR0028 "Filial"
		#define STR0029 "Descrição"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Filiais que serão geradas", "Descrição:" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Assistente de configuração e geração de carga do Controlo de Lojas", "Assistente de configuração e geração de carga do Controle de Lojas" )
		#define STR0032 "Geração da carga"
		#define STR0033 "Estado da última carga disponibilizada"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Estado:", "Status:" )
		#define STR0035 "Gerado:"
		#define STR0036 "Tabelas:"
		#define STR0037 "Filiais:"
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Registos:", "Registros:" )
		#define STR0039 "Progresso da geração da carga"
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Estado:", "Status:" )
		#define STR0041 "Tabela:"
		#define STR0042 "Velocidade:"
		#define STR0043 "Progresso:"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Gerar carga", "Gerar Carga" )
		#define STR0045 "Deseja iniciar a geração de carga?"
		#define STR0046 "Houve um erro ao tentar executar a operação."
		#define STR0047 "Gerado"
		#define STR0048 "Não gerado"
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Caminho do reposiório do servidor de ficheiro não configurado.", "Caminho do reposiório do servidor de arquivo não configurado." )
		#define STR0050 "Tabelas da carga inicial não informadas."
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Filiais da carga inicial não informadas.", "Especial" )
		#define STR0052 "Iniciado"
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "A Exportar", "Exportando" )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "A Compactar", "Compactando" )
		#define STR0055 "Finalizado"
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "A carregar grupos de tabelas.", "Carregando grupos de tabelas." )
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Selecção do grupo de tabelas", "Seleção do grupo de tabelas" )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Seleccione o grupo a ser utilizado, ou utilize os botões para renomear ou excluir o grupo seleccionado e incluir para adicionar um novo grupo.", "Selecione o grupo a ser utilizado, ou utilize os botões para renomear ou excluir o grupo selecionado e incluir para adicionar um novo grupo." )
		#define STR0059 "Código"
		#define STR0060 "Nome"
		#define STR0061 "Descrição"
		#define STR0062 "Renomear"
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "A renomear.", "Renomeando." )
		#define STR0064 "Configurar"
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "A configurar.", "Configurando." )
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "Gravar", "Salvar" )
		#define STR0067 "Cancelar"
		#define STR0068 "Parâmetros"
		#define STR0069 "Completo"
		#define STR0070 "Parcial"
		#define STR0071 "Especial"
		#define STR0072 "Configurar transferência completa"
		#define STR0073 "Filtro:"
		#define STR0074 "Assistente"
		#define STR0075 "Filiais:"
		#define STR0076 "Configurar transferência parcial"
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "Registos a serem gerados", "Registros a serem gerados" )
		#define STR0078 "Índice"
		#define STR0079 If( cPaisLoc $ "ANG|PTG", "Registo", "Registro" )
		#define STR0080 "Chave"
		#define STR0081 "Índice:"
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Registo:", "Registro:" )
		#define STR0083 "Assistente"
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Seleccione um grupo de tabelas", "Selecione um grupo de tabelas" )
		#define STR0085 "Completo - Substitui a tabela de destino;"
		#define STR0086 If( cPaisLoc $ "ANG|PTG", "Parcial - Transfere somente os registos seleccionados;", "Parcial - Transfere somente os registros selecionados;" )
		#define STR0087 "Especial - Transferências pré-desenvolvidas para tabelas especiais"
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "Seleccione o modo de transferência.", "Selecione o modo de transferência." )
		#define STR0089 "Informação"
		#define STR0090 "Completo"
		#define STR0091 "Parcial"
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "Pelo menos uma filial deve ser seleccionada para esta tabela.", "Pelo menos uma filial deve ser selecionada para esta tabela." )
		#define STR0093 "Tipo"
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Carga inteira", "Carga Inteira" )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Carga incremental", "Carga Incremental" )
		#define STR0096 "Incremental"
		#define STR0097 "Inteira"
		#define STR0098 If( cPaisLoc $ "ANG|PTG", "A analisar tabela a exportar", "Analisando tabela a exportar" )
		#define STR0099 If( cPaisLoc $ "ANG|PTG", "A actualizar registos exportados", "Atualizando registros exportados" )
		#define STR0100 If( cPaisLoc $ "ANG|PTG", "Gravar configurações", "Salvar Configurações" )
		#define STR0101 If( cPaisLoc $ "ANG|PTG", "Para tabelas compartilhadas, não será possível seleccionar a filial.", "Para tabelas compartilhadas não será possível selecionar a filial." )
		#define STR0102 If( cPaisLoc $ "ANG|PTG", "Configurações gravadas com sucesso.", "Configurações salvas com sucesso." )
		#define STR0103 If( cPaisLoc $ "ANG|PTG", "Selecção da tabela de preço", "Seleção da tabela de preço" )
		#define STR0104 If( cPaisLoc $ "ANG|PTG", "Seleccione a tabela de preço a ser considerada na geração de carga da tabela SBI.", "Selecione a tabela de preço a ser considerada na geração de carga da tabela SBI." )
		#define STR0105 "OK"
		#define STR0106 "Para prosseguir com a geração da carga, deve ser informada a tabela de preço a ser considerada para geração do preço na tabela SBI."
		#define STR0107 "Carga gerada com sucesso. "
		#define STR0108 "Deseja Adicionar Tabela Complemento de Cliente AI0"
		#define STR0109 "Lembre-se de executar o 'UPDCARGA - Facilitador para a criação dos campos reservados da carga'."
		#define STR0110 "Agendamentos"
		#define STR0111 "Carregando..."
		#define STR0112 "Para utilização do novo agendamento seu ambiente deve estar atualizado. Verifique com o departamento de tecnologia da informação da sua empresa."
		#define STR0113 "Não é possivel continuar"
		#define STR0114 "Não é possível incluir o Agendamento antes de salvar o Grupo de Cargas. Clique em Avançar / Salvar Configurações e retorne para inclusão de agendamento."
		#define STR0115 "Selecione o tipo de filtro:"
		#define STR0116 "por Chave"
		#define STR0117 "por Expressão"
		#define STR0118 "Para a carga parcial é preciso selecionar e preencher um dos tipos de filtro."
	#endif
#endif
