#ifdef SPANISH
	#define STR0001 "INICIO DEL PROCESO "
	#define STR0002 " - SCHEDULE - Tarea "
	#define STR0003 " - SMARTC/PILA LLAMADA "
	#define STR0004 " - EN: "
	#define STR0005 "FIN DE PROCESO "
	#define STR0006 "YA EXISTE EJECUCION DE LA RUTINA "
	#define STR0007 "<<ERROR>> "
	#define STR0008 "Presupuesto: "
	#define STR0009 " Pedido: "
	#define STR0010 " Anulado "
	#define STR0011 "¡Problema encontrado en borrado del presupuesto! Presupuesto: "
	#define STR0012 "Factura emitida"
	#define STR0013 "Presupuesto no puede excluirse. "
	#define STR0014 " Presupuesto no excluido (SL1)"
#else
	#ifdef ENGLISH
		#define STR0001 "PROCESS START "
		#define STR0002 " - SCHEDULE - Task "
		#define STR0003 " - SMARTC/CALL PILE "
		#define STR0004 " - IN: "
		#define STR0005 "PROCESS END "
		#define STR0006 "THERE ALREADY IS ROUTINE RUN "
		#define STR0007 "<<ERROR>> "
		#define STR0008 "Quotation: "
		#define STR0009 " Order: "
		#define STR0010 " canceled "
		#define STR0011 "Error found deleting Budget! Quotation: "
		#define STR0012 "Invoice Issued"
		#define STR0013 "Quotation cannot be deleted. "
		#define STR0014 " Quotation not deleted (SL1)"
	#else
		#define STR0001 "INICIO DO PROCESSO "
		#define STR0002 " - SCHEDULE - Tarefa "
		#define STR0003 " - SMARTC/PILHA CHAMADA "
		#define STR0004 " - EM: "
		#define STR0005 "FIM DO PROCESSO "
		#define STR0006 "JÁ EXISTE EXECUÇÃO DA ROTINA "
		#define STR0007 "<<ERRO>> "
		#define STR0008 "Orçamento: "
		#define STR0009 " Pedido: "
		#define STR0010 " cancelado "
		#define STR0011 "Problema encontrado na exclusão do Orçamento! Orçamento: "
		#define STR0012 "Nota Fiscal Emitida"
		#define STR0013 "Orçamento não pode ser excluído "
		#define STR0014 " Orçamento não excluído (SL1)"
	#endif
#endif
