#ifdef SPANISH
	#define STR0001 "No fue posible cargar la configuracion del SITEF, TEF Marcado(GP) y TEF Marcado(PayGo)."
	#define STR0002 "No existe configur. del TEF para la estac."
	#define STR0003 "Utilizac. del TEF"
	#define STR0004 "Habilitado"
	#define STR0005 "Deshabilitado"
	#define STR0006 "Configuraciones"
	#define STR0007 "Direcc. IP:"
	#define STR0008 "Terminal:"
	#define STR0009 "Empresa:"
	#define STR0010 "Tarjeta Credito/Debito"
	#define STR0011 "Cheque"
	#define STR0012 "Recarga de Celular"
	#define STR0013 "Correspondente Bancário"
	#define STR0014 "Banco de Brasil"
	#define STR0015 "PBM"
	#define STR0016 "Trn-Centre"
	#define STR0017 "Epharma"
	#define STR0018 "Visa/ Amex/ Redecard (Administrador Estandar)"
	#define STR0019 "Camino de la aplicacion:"
	#define STR0020 "Directorio de envio:"
	#define STR0021 "Directorio de respuesta:"
	#define STR0022 "Hipercard"
	#define STR0023 "Tecban"
	#define STR0024 "PayGo"
	#define STR0025 "Todos los Ejecutables"
	#define STR0026 "Seleccione un archivo"
	#define STR0027 "Todos los Archivos"
	#define STR0028 "Seleccione una carpeta"
	#define STR0029 "SiTef - Campo Direccion Ip no puede estar vacio"
	#define STR0030 "SiTef - Campo Direccion Ip invalido"
	#define STR0031 "SiTef - Campo Empresa tiene que tener obligatoriamente 8 caracteres"
	#define STR0032 "SiTef - Campo Terminal no puede estar vacio"
	#define STR0033 "SiTef - Campo Terminal tiene que tener obligatoriamente 8 caracteres"
	#define STR0034 "PayGo - Campo Camino de la Aplicacion no puede estar vacio"
	#define STR0035 "PayGo - Campo Directorio de envio no puede estar vacio"
	#define STR0036 "PayGo - Campo Directorio de respuesta no puede estar vacio"
	#define STR0037 "Campo Camino de la Aplicacion no puede estar vacio"
	#define STR0038 "Campo Directorio de envio no puede estar vacio"
	#define STR0039 "Campo Directorio de respuesta no puede estar vacio"
	#define STR0040 "Cielo Premia"
	#define STR0041 "Debe informarse el Código de la compañía"
	#define STR0042 "Debe informarse el Tenant"
	#define STR0043 "Debe informarse el Usuario"
	#define STR0044 "Debe informarse la contraseña"
	#define STR0045 "Debe informarse el Client ID"
	#define STR0046 "Debe informarse el Client Secret"
	#define STR0047 "No fue posible listar los terminales, pues debe(n) informarse el(los) siguiente(s) dato(s):"
	#define STR0048 "Verificando terminal..."
	#define STR0049 "Buscando terminales..."
	#define STR0050 "Espere"
	#define STR0051 "El terminal"
	#define STR0052 "no está activo. Debe seleccionarse un terminal que esté activo."
	#define STR0053 "No fue posible validar los terminales activos."
#else
	#ifdef ENGLISH
		#define STR0001 "Could not load configurations of SITEF, Dialed EFT (GP) and Dialed EFT (PayGo)."
		#define STR0002 "There is no EFT configuration for station"
		#define STR0003 "Use of EFT"
		#define STR0004 "Enabled"
		#define STR0005 "Disabled"
		#define STR0006 "Configurations"
		#define STR0007 "IP Address:"
		#define STR0008 "Terminal:"
		#define STR0009 "Company:"
		#define STR0010 "Credit/Debit Card"
		#define STR0011 "Check"
		#define STR0012 "Cell phone refill card"
		#define STR0013 "Bank Correspondent"
		#define STR0014 "Banco do Brasil"
		#define STR0015 "PBM"
		#define STR0016 "Trn-Centre"
		#define STR0017 "Epharma"
		#define STR0018 "Visa/ Amex/ Redecard (Default Manager)"
		#define STR0019 "Application path:"
		#define STR0020 "Sending directory:"
		#define STR0021 "Response directory:"
		#define STR0022 "Hipercard"
		#define STR0023 "Tecban"
		#define STR0024 "PayGo"
		#define STR0025 "All executable files"
		#define STR0026 "Select a file"
		#define STR0027 "All files"
		#define STR0028 "Select a folder."
		#define STR0029 "SiTef - Field IP Address cannot be empty."
		#define STR0030 "SiTef - Invalid field IP Address."
		#define STR0031 "SiTef - Field Company must have 8 characters."
		#define STR0032 "SiTef - Field Terminal cannot be empty."
		#define STR0033 "SiTef - Field Terminal must have 8 characters."
		#define STR0034 "PayGo - Field Application Path cannot be empty."
		#define STR0035 "PayGo - Field Sending Directory cannot be empty."
		#define STR0036 "PayGo - Field Response Directory cannot be empty."
		#define STR0037 "Field Application Path cannot be empty."
		#define STR0038 "Field Sending Directory cannot be empty."
		#define STR0039 "Field Sending Directory cannot be empty."
		#define STR0040 "Cielo Premia"
		#define STR0041 "Enter Company Code"
		#define STR0042 "Enter Tenant"
		#define STR0043 "Enter User"
		#define STR0044 "Enter Password"
		#define STR0045 "Enter Client ID"
		#define STR0046 "Enter Client Secret"
		#define STR0047 "Unable to list terminals. Enter the following data:"
		#define STR0048 "Checking terminal..."
		#define STR0049 "Searching terminals..."
		#define STR0050 "Wait"
		#define STR0051 "The terminal"
		#define STR0052 "is not active. Select an active terminal."
		#define STR0053 "Unable to validate active terminals."
	#else
		#define STR0001 "Não foi possível carregar as configuração do SITEF, TEF Discado(GP) e TEF Discado(PayGo)."
		#define STR0002 "Não existe configuração do TEF para a estação"
		#define STR0003 "Utilização do TEF"
		#define STR0004 "Habilitado"
		#define STR0005 "Desabilitado"
		#define STR0006 "Configurações"
		#define STR0007 "Endereço IP:"
		#define STR0008 "Terminal:"
		#define STR0009 "Empresa:"
		#define STR0010 "Cartão Crédito/Débito"
		#define STR0011 "Cheque"
		#define STR0012 "Recarga de Celular"
		#define STR0013 "Correspondente Bancário"
		#define STR0014 "Banco do Brasil"
		#define STR0015 "PBM"
		#define STR0016 "Trn-Centre"
		#define STR0017 "Epharma"
		#define STR0018 "Visa/ Amex/ Redecard (Gerenciador Padrão)"
		#define STR0019 "Caminho da aplicação:"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Directório de envio:", "Diretório de envio:" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Directório de resposta:", "Diretório de resposta:" )
		#define STR0022 "Hipercard"
		#define STR0023 "Tecban"
		#define STR0024 "PayGo"
		#define STR0025 "Todos os Executáveis"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Seleccione um ficheiro", "Selecione um arquivo" )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Todos os Ficheiros", "Todos os Arquivos" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Seleccione uma pasta", "Selecione uma pasta" )
		#define STR0029 "SiTef - Campo Endereço Ip nao pode ser vazio"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "SiTef - Campo Endereço Ip inválido", "SiTef - Campo Endereço Ip invalido" )
		#define STR0031 "SiTef - Campo Empresa tem que ter obrigatoriamente 8 caracteres"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "SiTef - Campo Terminal não pode ser vazio", "SiTef - Campo Terminal nao pode ser vazio" )
		#define STR0033 "SiTef - Campo Terminal tem que ter obrigatoriamente 8 caracteres"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "PayGo - Campo Caminho da Aplicação não pode ser vazio", "PayGo - Campo Caminho da Aplicação nao pode ser vazio" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "PayGo - Campo Directório de envio não pode ser vazio", "PayGo - Campo Diretório de envio nao pode ser vazio" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "PayGo - Campo Directório de reposta não pode ser vazio", "PayGo - Campo Diretório de reposta nao pode ser vazio" )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Campo Caminho da Aplicação não pode ser vazio", "Campo Caminho da Aplicação nao pode ser vazio" )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Campo Directório de envio não pode ser vazio", "Campo Diretório de envio nao pode ser vazio" )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Campo Directório de reposta não pode ser vazio", "Campo Diretório de reposta nao pode ser vazio" )
		#define STR0040 "Cielo Premia"
		#define STR0041 "Deve ser informado o Código da Companhia"
		#define STR0042 "Deve ser informado o Tenant"
		#define STR0043 "Deve ser informado o Usuário"
		#define STR0044 "Deve ser informada a Senha"
		#define STR0045 "Deve ser informado o Client ID"
		#define STR0046 "Deve ser informado o Client Secret"
		#define STR0047 "Não foi possível listar os terminais, pois o(s) seguinte(s) dado(s) deve(m) ser informado(s): "
		#define STR0048 "Verificando terminal..."
		#define STR0049 "Buscando terminais..."
		#define STR0050 "Aguarde"
		#define STR0051 "O terminal "
		#define STR0052 " não está ativo. Deve ser selecionado um terminal que esteja ativo."
		#define STR0053 "Não foi possível validar os terminais ativos."
	#endif
#endif
