#ifdef SPANISH
	#define STR0001 "  Este programa tiene como objetivo enviar aviso de disponibilidad del producto de una venta perdida."
	#define STR0002 "Se consideraran:"
	#define STR0003 "La venta debe haberse perdido por indisponibilidad del producto en stock."
	#define STR0004 "El movimiento de venta perdida debe estar con la opcion de envio de aviso activada."
	#define STR0005 "El aviso de disponibilidad del producto de la venta perdida no debe estar anulado"
	#define STR0006 "El producto no vendido debe estar disponible en stock"
	#define STR0007 "Aviso de disponibilidad del producto"
	#define STR0008 "Enviar aviso de disponibilidad"
	#define STR0009 "Datos del Movimiento de Venta Perdida"
	#define STR0010 "Aviso: Producto disponible"
	#define STR0011 "¡Ningun registro se marco!"
	#define STR0012 "E-mail de aviso de disponibilidad del producto"
	#define STR0013 "Contenido del e-mail"
	#define STR0014 "Asunto"
	#define STR0015 "Encabezamiento"
	#define STR0016 "Cuerpo"
	#define STR0017 "Pie de pagina"
	#define STR0018 "Visualizacion"
	#define STR0019 "AQUI SE EXHIBIRA EL NOMBRE DEL PROCDUTO"
	#define STR0020 "¿Confirma el envio del e-mail de aviso de disponibilidad para los clientes seleccionados?"
	#define STR0021 "Atencion"
	#define STR0022 "Falla en la conexion: "
	#define STR0023 "Falla en el envio del e-mail "
	#define STR0024 "Error:"
	#define STR0025 "Destinatario:"
	#define STR0026 "¡E-mail enviado con exito!"
	#define STR0027 "Uno o varios e-mails no se enviaron. ¡Verifique!"
#else
	#ifdef ENGLISH
		#define STR0001 "  This program sends a availability reminder for the product of a lost sale."
		#define STR0002 "It considers :"
		#define STR0003 "The sale must have been lost by unavailability of product in stock."
		#define STR0004 "Movement of lost sale must have the option send reminder enabled."
		#define STR0005 "Availability reminder for the lost sale product cannot be expired"
		#define STR0006 "Product not sold must be available in stock"
		#define STR0007 "Product availability reminder"
		#define STR0008 "Send availability reminder"
		#define STR0009 "Data of Movement of Lost Sale"
		#define STR0010 "Notice: Product Available"
		#define STR0011 "No record selected !"
		#define STR0012 "Product availability reminder e-mail"
		#define STR0013 "E-mail content"
		#define STR0014 "Subject"
		#define STR0015 "Header"
		#define STR0016 "Body"
		#define STR0017 "Footer"
		#define STR0018 "View"
		#define STR0019 "PRODUCT NAME IS DISPLAYED HERE"
		#define STR0020 "Confirm sending availability notice e-mail to selected customers ?"
		#define STR0021 "Attention"
		#define STR0022 "Connection failed : "
		#define STR0023 "Error sending the e-mail "
		#define STR0024 "Error :"
		#define STR0025 "Addressee :"
		#define STR0026 "E-mail successfully sent !"
		#define STR0027 "One or more e-mails were not sent. Check it out !"
	#else
		#define STR0001 "  Este programa tem como objetivo enviar aviso de disponibilidade do produto de uma venda perdida."
		#define STR0002 "Serão considerados :"
		#define STR0003 "A venda deve ter sido perdida por indisponibilidade do produto em estoque."
		#define STR0004 "O movimento de venda perdida deve estar com a opção de envio de aviso habilitada."
		#define STR0005 "O aviso de disponibilidade do produto da venda perdida não deve estar expirado"
		#define STR0006 "O produto não vendido deve estar disponivel em estoque"
		#define STR0007 "Aviso de disponibilidade do produto"
		#define STR0008 "Enviar aviso de disponibilidade"
		#define STR0009 "Dados do Movimento de Venda Perdida"
		#define STR0010 "Aviso: Produto Disponivel"
		#define STR0011 "Nenhum registro foi marcado !"
		#define STR0012 "E-mail de aviso de disponibilidade do produto"
		#define STR0013 "Conteúdo do e-mail"
		#define STR0014 "Assunto"
		#define STR0015 "Cabeçalho"
		#define STR0016 "Corpo"
		#define STR0017 "Rodapé"
		#define STR0018 "Visualização"
		#define STR0019 "AQUI SERA EXIBIDO O NOME DO PRODUTO"
		#define STR0020 "Confirma o envio do e-mail de aviso de disponibilidade para os clientes selecionados ?"
		#define STR0021 "Atenção"
		#define STR0022 "Falha na conexao : "
		#define STR0023 "Falha no Envio do e-mail "
		#define STR0024 "Erro :"
		#define STR0025 "Destinatário :"
		#define STR0026 "E-mail enviado com sucesso !"
		#define STR0027 "Um ou mais e-mails não foram enviados. Verifique !"
	#endif
#endif
