#ifdef SPANISH
	#define STR0001 "¡Error en el parser!"
	#define STR0002 "¡Version del mensaje no informada!"
	#define STR0003 "¡La version del mensaje informado no se implemento!"
	#define STR0004 "Marca no integrada al Protheus, verifique la marca de integracion"
	#define STR0005 "Estación no informada en la integración"
	#define STR0006 "Comprobante no informado, verificar la tag: DocumentCode."
	#define STR0007 "Cliente:"
	#define STR0008 "no integrado al Protheus, verifique la integración de clientes"
	#define STR0009 "Operador:"
	#define STR0010 "no integrado al Protheus, verifique integración de operador"
	#define STR0011 "Estacion: "
	#define STR0012 "no integrada al Protheus, verifique integración de Estación"
	#define STR0013 "Producto:"
	#define STR0014 "no integrado al Protheus, verifique integración de Producto"
	#define STR0015 "Documento:"
	#define STR0016 "Serie:"
	#define STR0017 "Tienda:"
	#define STR0018 "Operador no informado en la integración, verifique la Tag OperatorCode."
	#define STR0019 "no registrado en el Protheus, verifique el archivo de clientes."
	#define STR0020 "Campo obligatorio no se informó: Fecha de emisión, verifique la tag: IssueDateDocument."
	#define STR0021 "Campo obligatorio no se informó: Id Interno, verifique la tag: InternalId."
	#define STR0022 "Comprobante:"
	#define STR0023 "integrado al Protheus."
	#define STR0024 "Actualice EAI"
	#define STR0025 "Error en la grabación de la venta:"
	#define STR0026 "no se encontró en el Protheus, verifique el archivo o integración de Estación."
	#define STR0027 "Campo obligatorio no se informó: Valor total de la venta, verifique la tag: TotalPrice."
	#define STR0028 "Campo obligatorio no se informó: Valor neto de la venta, verifique la tag: NetPrice."
	#define STR0029 "Campo obligatorio no se informó: Valor bruto de la venta, verifique la tag: GrossPrice."
	#define STR0030 "Lista de productos vacía, verifique la lista SaleItem."
	#define STR0031 "Inconsistencia en el ítem"
	#define STR0032 "producto no informado en la integración, verifique la Tag ItemCode."
	#define STR0033 "producto:"
	#define STR0034 "no registrado en el Protheus, verifique la tag: ItemCode"
	#define STR0035 "campo obligatorio no se informó: Ítem, verifique la tag: ItemOrder."
	#define STR0036 "campo obligatorio no se informó: Cantidad, verifique la tag: Quantity."
	#define STR0037 "campo obligatorio no se informó: Precio unitario, verifique la tag: UnitPrice."
	#define STR0038 "campo obligatorio no se informó: Precio del ítem, verifique la tag: ItemPrice."
	#define STR0039 "campo obligatorio no se informó: CFOP, verifique la tag: OperationCode"
	#define STR0040 "TES no informada, verifique el Archivo de producto en el Protheus campo B1_TS y/o De-A de TES(XXF) y/o las configuraciones para TES Inteligente(DHJ y SFM) y/o parámetros MV_TESSERV y MV_TESVEND."
	#define STR0041 "Valor total divergente."
	#define STR0042 "verifique las tag TotalPrice y la suma de las tags: ItemPrice."
	#define STR0043 "Lista de forma de pagos vacía, verifique la lista SaleCondition."
	#define STR0044 "Inconsistencia en la forma  de pago"
	#define STR0045 "Forma de pago no se informó en la integración."
	#define STR0046 "Verifique las tags: PaymentMethodCode."
	#define STR0047 "Forma de pago:"
	#define STR0048 "no se encontró en el Protheus."
	#define STR0049 "Verifique el archivo de Forma de pago."
	#define STR0050 "Administradora financiera no válida o no encontrada en el De/A en el Protheus."
	#define STR0051 "Esta información es obligatoria para pagos en tarjeta, verifique la tag: FinancialManagerCode."
	#define STR0052 "Valor del pago no se informó o se dejó en cero en la integración, verifique la tag: PaymentValue."
	#define STR0053 "Valor de la venta divergente del total de pago"
	#define STR0054 "verifique las tags: NetPrice e PaymentValue."
	#define STR0055 "Versión no soportada."
	#define STR0056 "Las versiones soportadas son:"
	#define STR0057 "Venta:"
	#define STR0058 "¡No se encontró en de/a!"
	#define STR0059 "Se detectó que el campo referente al estado de cobranza(M0_ESTCOB) no está configurado."
	#define STR0060 "Efectúe la inclusión en el archivo de sucursales en el Protheus."
	#define STR0061 "Inconsistencia en la fecha de pago"
	#define STR0062 "Fecha de pago no informada, verifique la tag: DateOfPayment"
	#define STR0063 "CFOP inválida:"
	#define STR0064 "verifique el registro de CFOP"
	#define STR0065 "Campo obligatorio no informado para NFce: Informaciones adicionales, verifique la tag: ElectronicInvoiceComplement"
	#define STR0066 "InternalId del RA no informado"
	#define STR0067 "Esta información es obligatoria para pagos RA, verifique la tag: AccountReceivableDocumentInternalId"
	#define STR0068 "Campo obligatorio no se informó: MD-5, verifique la tag: Md5"
	#define STR0069 "Impuesto ISS obligatorio para la venta de servicio, verifique el tag: IssValue"
	#define STR0070 "Impuesto ICMS informado para la venta de servicio, verifique el tag: IcmsValue"
	#define STR0071 "Impuesto ICMS obligatorio para la venta de mercadería, verifique el tag: IcmsValue"
	#define STR0072 "Impuesto ISS informado para la venta de mercadería, verifique el Tag: IssValue"
	#define STR0073 "impuesto ISS obligatorio para el servicio, verifique el Tag: ItemIss"
	#define STR0074 "Impuesto ICMS obligatorio para la mercadería, verifique el Tag: ItemIcms"
	#define STR0075 "bloqueado, verifique el archivo de cliente en el Protheus."
	#define STR0076 "Serie no informada en la integración, información obligatoria para Factura manual o e-Fact, verifique la tag: SerieCode"
	#define STR0077 "Serie no registrada, verifique el campo Serie del Registro de Estaciones en el Protheus."
	#define STR0078 "Vendedor no informado, obligatorio para venta con comisión, verifique la Tag: SellerInternalId."
	#define STR0079 "Vendedor:"
	#define STR0080 "no integrado al Protheus, verifique la integración de vendedores."
	#define STR0081 "Evento incorrecto, para exclusión utilice la integración de anulación de venta."
	#define STR0082 "¡Evento no informado!"
	#define STR0083 "Serie no informada en la integración, información obligatoria para RPS, verifique la tag: SerieCode"
	#define STR0084 "Job LjSendEAI Iniciado para la sucursal"
	#define STR0085 "Job LjSendEAI ejecutado para la sucursal"
	#define STR0086 "El título de anticipo"
	#define STR0087 "Verifique la tag: AccountReceivableDocumentInternalId"
	#define STR0088 "no se integró con el Protheus"
	#define STR0089 "no se encontró en la base de datos Protheus"
	#define STR0090 "se envió un producto tipo mercadería en una RPS, verifique el campo B1_TIPO en el Protheus"
	#define STR0091 "se envió un producto tipo servicio en un Comprobante, verifique el campo B1_TIPO en el Protheus"
	#define STR0092 "se encuentra dado de baja"
	#define STR0093 "Es necesario deshacer la compensación en el financiero"
	#define STR0094 "Clave e-FactC no enviada, información obligatoria para venta e-FactC, verifique la tag KeyAcessNfe"
	#define STR0095 "Protocolo e-FactC no enviado, información obligatoria para venta e-FactC, verifique la tag NfceProtocol"
	#define STR0096 "Reserva no informada en la integración, información obligatoria para el evento de modificación de venta, verifique la tag: HotelAccountCode"
	#define STR0097 "Tipo de venta no informada, verifique la tag: KindOfDocument"
	#define STR0098 "Ente no informada o no integrada al Protheus para prorrateo, verifique la lista: ListOfFinancialNatureApportionment, tag: GenericEntityInternalId."
	#define STR0099 "Porcentaje de prorrateo no informado en el prorrateo, verifique la lista: ListOfFinancialNatureApportionment, tag: Porcentaje."
	#define STR0100 "La suma del porcentaje de prorrateo está diferente del 100%, verifique la lista: ListOfFinancialNatureApportionment, tag: Porcentaje."
	#define STR0101 "Centro de costo no informado, obligatorio cuando se utiliza prorrateo. Verifique el parámetro en el Protheus: MV_HTLCCRT"
	#define STR0102 "Para utilizar informaciones de prorrateo tag: ListOfFinancialNatureApportionment"
	#define STR0103 "es necesario habilitar el parámetro MV_MULNATR en el Protheus."
	#define STR0104 "Este mensaje tiene informaciones de prorrateo tag: ListOfFinancialNatureApportionment pero no es una RPS"
	#define STR0105 "Verifique la tag: KindOfDocument."
	#define STR0106 "Almacén:"
	#define STR0107 "sin integración al Protheus, verifique integración de almacenes"
	#define STR0108 "Código de identificación de tienda"
	#define STR0109 "no registrado en el Protheus"
	#define STR0110 "campo LJ_CCUSTO vacío"
	#define STR0111 "información obligatoria cuando se envía al centro de consumo: StoreIdentificationCode"
	#define STR0112 "campo LJ_ITEMCC vacío"
	#define STR0113 "campo LJ_CLVL vacío"
	#define STR0114 "no informada la fecha para verificar el Bloque F100"
	#define STR0115 "esta información es obligatoria cuando se informa la venta origen Bloque F100"
	#define STR0116 "Verifique la tag: DateOfMovement ubicada en la lista BoardBasisInformation"
	#define STR0117 "no informada la lista BoardBasisInformation"
	#define STR0118 "venta informada para verificar el Bloque F100 no integrada al Protheus"
	#define STR0119 "verifique la tag InternalId en la lista ListOfSaleItem"
	#define STR0120 "no se encontró en el De/A o su contenido se informó incorrectamente. El De/A está formado por EMPRESA|SUCURSAL|TES."
	#define STR0121 " verifique si el operador está registrado en la sucursal destino correcta."
	#define STR0122 "la venta con reserva necesita que se informe la identificación de la tienda, verifique la tag: StoreIdentificationCode"
	#define STR0123 "Error en el archivo del cliente"
	#define STR0124 "El valor del Descuento total proporcionado por ítem de la tag"
	#define STR0125 "está diferente del Descuento total de la tag"
	#define STR0126 "Número del comprobante no válido, verifique la tag: DocumentCode"
	#define STR0127 "Serie SAT no enviada, información obligatoria para venta SAT, verifique la tag SERIALNUMBERSATEQUIPAMENT"
	#define STR0128 "Clave e-FactC inferior al estándar, verifique la tag: KeyAcessNfe"
	#define STR0129 "Fecha de emisión inferior a la fecha de cierre del parámetro: MV_ULMES"
	#define STR0130 "Fecha de emisión inferior a la fecha de cierre del parámetro: MV_DBLQMOV"
	#define STR0131 "Transportadora #1 no integrada al Protheus, verifique la integración de Transportadoras."
	#define STR0132 "Transportadora"
	#define STR0133 "Estación"
	#define STR0134 "No fue posible realizar el registro del De\A del #1 AUTOMÁTICO."
	#define STR0135 "Operador"
	#define STR0136 "No fue posible configurar el operador AUTOMÁTICO. (#1)"
	#define STR0137 "Factura del tipo #1 sin proveedor identificado, verifique el RCPJ. #2"
	#define STR0138 "Inconsistencia en el ítem #1, no se informó la TAG #2, obligatoria para facturas de devolución."
	#define STR0139 "El CFOP #1 no se encontró en el de\pare o en la tabla DHJ, verifique."
	#define STR0140 "Dirección del stock: #1 no existe. (#2)"
	#define STR0141 "Numero de serie: #1 no existe, para el producto\dirección, (#2)"
	#define STR0142 "Reserva #1 - Fue utilizada o difiere con la cantidad reservada #2 con la cantidad #3 recibida en la TAG Quantity."
	#define STR0143 "Reserva #1 no existe para el producto #2"
	#define STR0144 "No se encontró de\a, para el #1 #2, verifique si la reserva se integró."
	#define STR0145 "No se informó el número de la reserva (#1), para el ítem #2. Para #3 3 o 4 la TAG es obligatoria."
	#define STR0146 "Error en la devolución, la TAG #1 es obligatoria."
	#define STR0147 "Evento de  la devolución no válido."
	#define STR0148 "Verifique las TAG:"
	#define STR0149 "¡El contenido de la TAG UniqueSerialNumber es mayor que lo soportado por los campos #1, verifique!"
	#define STR0150 "Este mensaje tiene información de impuestos en #1, pero su tipo de documento no se informó en #2."
	#define STR0151 "Función #1 no existe, actualice #2 para que se efectúe el cálculo de impuestos."
	#define STR0152 "Divergência de valores entre Cabeçalho, Itens + Frete dos Itens e Pagamentos, verifique as #1: #2, #3, #4 e #5"
	#define STR0153 "Se informó el valor del flete en la TAG FreightValue, pero, no se informó el valor del flete en la TAG FreightValueProrated en los productos. Esta TAG debe tener el valor del flete prorrateado por producto."
	#define STR0154 "Se informó el valor del flete en la TAG FreightValueProrated, sin embargo, no se informó el valor del flete en el encabezado de la venta en la TAG FreightValue."
	#define STR0155 "El valor del flete está divergente entre el valor informado en el encabezado de la venta (TAG FreightValue) con el valor informado en los ítems (TAG FreightValueProrated)."
	#define STR0156 "Para la generación del pedido de venta, el parámetro MV_LJPEDVE debe tener el contenido .T."
	#define STR0157 "El contenido del parámetro MV_LJCONDP debe informarse con el código de una condición de pago para la generación del pedido de venta"
	#define STR0158 "El contenido del parámetro MV_LJTESPE debe haberse completado con  el código de una TES que no genera el financiero, por favor, verifique el registro de la TES configurada en el parámetro"
	#define STR0159 "Los parámetros MV_LJECOMO y MV_LJECOMM obligatoriamente deben estar con el contenido .F. Si fuera una integración CiaShop / VTex"
	#define STR0160 "Después de la modificación del(de los) parámetro(s), es necesario reiniciar el(los) servicio(s) del Protheus."
	#define STR0161 "campo obligatorio no se informó: Precio de la tabla, verifique la tag: ItemTablePrice."
	#define STR0162 "no se informó campo obligatorio: Precio del producto, verifique la tag: ItemPrice."
	#define STR0163 "No se encontró la TES configurada en el parámetro MV_LJTESPE, por favor, confirme si realmente la TES está registrada"
	#define STR0164 "Tipo de flete informado en el parámetro MV_LJTPFRE no es válido, informe un tipo de flete válido. Después de la modificación, es necesario reiniciar los servicios del Protheus."
	#define STR0165 "La información contenida en la TAG DocumentCode es mayor que el tamaño del campo L1_DOCPED de la tabla SL1."
	#define STR0166 "La información contenida en la TAG DocumentCode es mayor que el tamaño de los campos L1_DOCPED (Tabla SL1) y E1_NUM (Tabla SE1)."
	#define STR0167 "El tamaño de los campos L1_DOCPED (Tabla SL1) y E1_NUM (Tabla SE1) tienen tamaños diferentes, por favor, estos campos deben contener el mismo tamaño."
	#define STR0168 "Error en devolución del punto de entrada LJI701O1, la devolución no es del tipo array."
	#define STR0169 "La información incluida en la TAG ECommerceOrder esta mayor que el tamaño del campo L1_ECPEDEC (Tabla SL1)."
	#define STR0170 "Almacén #1 devuelto en el De/A de la tag (WarehouseInternalid) no es el mismo almacén  (C0_LOCAL) #2 de la reserva numero: #3."
	#define STR0171 "El cálculo inverso de IPI generó una diferencia mayor que 0.50 entre el total pagado y el valor de pedido. Los ajustes de redondeos de cálculo inverso son limitados en R$ 0.50 centavos. Es necesario abrir un ticket con los datos de este pedido para análisis."
	#define STR0172 "Se encontraron diferencias entre el valor del pedido VTEX para calcular el IPI. Por favor verifique los parámetros MV_LJATIPI, MV_LJDTIPI."
	#define STR0173 "La tag PresencialIndicator recibió un valor no valido #1. Por favor verifique la información recibida y ajuste en la VTEX."
	#define STR0174 "En el ítem #1 se recibió la empresa de transportes #2, donde solo se permite la recepción en el encabezado o en el ítem. Por favor, solicite el ajuste del Json."
	#define STR0175 "O desconto recebido na tag DiscountValue com o valor #1. Será alterado para composição de valor total."
#else
	#ifdef ENGLISH
		#define STR0001 "Error in parser!"
		#define STR0002 "Message version not entered!"
		#define STR0003 "Version of message entered not implemented!"
		#define STR0004 "Brand not integrated to Protheus. Check integration brand."
		#define STR0005 "Station not entered in integration"
		#define STR0006 "Voucher not entered. Check tag: DocumentCode."
		#define STR0007 "Customer:"
		#define STR0008 "not integrated to Protheus, check customer integration"
		#define STR0009 "Operator:"
		#define STR0010 "not integrated to Protheus. Check operator integration."
		#define STR0011 "Station: "
		#define STR0012 "not integrated to Protheus. Check Station integration."
		#define STR0013 "Product:"
		#define STR0014 "not integrated to Protheus, check Product integration"
		#define STR0015 "Document:"
		#define STR0016 "Series:"
		#define STR0017 "Store:"
		#define STR0018 "Operator not entered in integration, check tag OperatorCode."
		#define STR0019 "not registered in Protheus. Check the customers register."
		#define STR0020 "Required field not entered: Issue date, check tag: IssueDateDocument."
		#define STR0021 "Required field not filled out: Internal ID. Check tag: InternalId."
		#define STR0022 "Receipt:"
		#define STR0023 "already integrated to Protheus!"
		#define STR0024 "Update EAI"
		#define STR0025 "Error recording sales:"
		#define STR0026 "not found in Protheus, check the Station register or integration."
		#define STR0027 "Required field not filled out: Total Sale Value. Check tag: TotalPrice."
		#define STR0028 "Required field not filled out: Net Sale Value. Check tag: NetPrice."
		#define STR0029 "Required field not filled out: Gross Sale Value. Check tag: GrossPrice."
		#define STR0030 "Products list empty. Check list: SaleItem."
		#define STR0031 "Inconsistency in item"
		#define STR0032 "Product not filled out in integration. Check tag: ItemCode."
		#define STR0033 "product:"
		#define STR0034 "not registered in Protheus. Check tag: ItemCode."
		#define STR0035 "Required field not filled out: Item. Check tag: ItemOrder."
		#define STR0036 "Required field not filled out: Quantity. Check tag: Quantity."
		#define STR0037 "required field not filled out: Unit Price. Check tag: UnitPrice."
		#define STR0038 "required field not filled out: Item Price. Check tag: ItemPrice."
		#define STR0039 "Required field not filled out: CFOP. Check tag: OperationCode."
		#define STR0040 "TIO not informed, check the Product Register in Protheus field B1_TS and/or TIO(XXF) From-To and/or the configurations for TIO Intelligent (DHJ and SFM) and/or parameters MV_TESSERV and MV_TESVEND."
		#define STR0041 "Total Value divergent."
		#define STR0042 "Check tag TotalPrice and the sum of tags: ItemPrice."
		#define STR0043 "Payment Methods List empty. Chekc list: SaleCondition."
		#define STR0044 "Payment Method not consistent."
		#define STR0045 "Payment Method not entered in integration."
		#define STR0046 "Check tags: PaymentMethodCode."
		#define STR0047 "Payment Method:"
		#define STR0048 "not found in Protheus."
		#define STR0049 "Check the Payment Methods register."
		#define STR0050 "Financial Administration Company invalid or not found in From To in Protheus."
		#define STR0051 "This information is required for card payments. Check tag: FinancialManagerCode."
		#define STR0052 "Payment Value not entered or null in integration. Check tag: PaymentValue."
		#define STR0053 "Sale value divergent from payment total."
		#define STR0054 "Check tags: NetPrice and PaymentValue."
		#define STR0055 "Version not supported."
		#define STR0056 "The supported versions are:"
		#define STR0057 "Sales:"
		#define STR0058 "not found in from/to!"
		#define STR0059 "Field related to state of billing (M0_ESTCOB) not configured."
		#define STR0060 "Add data to branches register of Protheus."
		#define STR0061 "Payment Date not consistent."
		#define STR0062 "Payment Date not entered. Check tag: DateOfPayment."
		#define STR0063 "CFOP not valid:"
		#define STR0064 "Check CFOP register."
		#define STR0065 "Required field not filled out for E-Invc: Additional Information. Check tag: ElectronicInvoiceComplement."
		#define STR0066 "RA InternalId not entered"
		#define STR0067 "This information is required for RA payments. Check tag: AccountReceivableDocumentInternalId."
		#define STR0068 "Required field not filled out: MD-5. Check tag: Md5."
		#define STR0069 "ISS Tax required for Service Sales. Check tag: IssValue."
		#define STR0070 "ICMS Tax entered for Service Sales. Check tag: IcmsValue."
		#define STR0071 "ICMS Tax required for Goods Sales. Check tag: IcmsValue."
		#define STR0072 "ISS Tax entered for Goods Sales. Check tag: IssValue."
		#define STR0073 "ISS tax required for service. Check tag: ItemIss."
		#define STR0074 "ICMS tax required for goods. Check tag: ItemIcms."
		#define STR0075 "blocked, check the Customers Register in Protheus."
		#define STR0076 "Series not entered on integration. Information required for Manual Note or e-INV. Check tag: SerieCode"
		#define STR0077 "Series not registered, check field Stations Register Series on Protheus."
		#define STR0078 "Salesperson not entered, mandatory for sales with commission, check the tag: SellerInternalId."
		#define STR0079 "Sales representative:"
		#define STR0080 "not integrated on Protheus, check customer integration."
		#define STR0081 "Event entered, for deletion use Sales Cancelation integration."
		#define STR0082 "Event not entered!"
		#define STR0083 "Series not entered on integration. Information required for RPS. Check tag: SerieCode."
		#define STR0084 "Job LjSendEAI started for branch"
		#define STR0085 "Job LjSendEAI executed for branch"
		#define STR0086 "Prepayment bill"
		#define STR0087 "Check tag: AccountReceivableDocumentInternalId"
		#define STR0088 "not integrated to Protheus"
		#define STR0089 "was not found in Protheus database."
		#define STR0090 "merchandise type product sent in a RPS, check field B1_TIPO in Protheus"
		#define STR0091 "service type product sent in a Receipt, check field B1_TIPO in Protheus"
		#define STR0092 "downloaded"
		#define STR0093 "Undo clearance in financial."
		#define STR0094 "e-INV key not sent. Information required for e-INV sale, check the tag KeyAcessNfe"
		#define STR0095 "e-INV protocol not sent. Information required for e-INV sale, check the tag NfceProtocol"
		#define STR0096 "Reservation not entered in the integration, mandatory information for  the event of sales change, check tag HotelAccountCode"
		#define STR0097 "Sales Type not entered. Check tag: KindOfDocument"
		#define STR0098 "Entity not entered or not integrated to Protheus for apportion, check list: ListOfFinancialNatureApportionment, tag: GenericEntityInternalId."
		#define STR0099 "Percentage of apportion not entered in apportion, check list: ListOfFinancialNatureApportionment, tag: Percentage."
		#define STR0100 "Sum of apportion percentage is different than 100%, check list: ListOfFinancialNatureApportionment, tag: Percentage."
		#define STR0101 "Cost Center not entered, mandatory when using apportion, check parameter in Protheus: MV_HTLCCRT"
		#define STR0102 "To use information of apportion tag: ListOfFinancialNatureApportionment"
		#define STR0103 "enable parameter MV_MULNATR in Protheus."
		#define STR0104 "This message has information of apportion tag: ListOfFinancialNatureApportionment but this is not a RPS"
		#define STR0105 "check tag: KindOfDocument."
		#define STR0106 "Warehouse:"
		#define STR0107 "not integrated to Protheus. Check warehouse integration"
		#define STR0108 "Store identification code"
		#define STR0109 "not registered in Protheus"
		#define STR0110 "field LJ_CCUSTO empty"
		#define STR0111 "information required with consumption center is sent: StoreIdentificationCode"
		#define STR0112 "field LJ_ITEMCC empty"
		#define STR0113 "field LJ_CLVL empty"
		#define STR0114 "date for verification of Block F100 not entered"
		#define STR0115 "this information is required when origin sales Block F100 is entered"
		#define STR0116 "check tag: DateOfMovement in the list BoardBasisInformation"
		#define STR0117 "BoardBasisInformation list not entered"
		#define STR0118 "sales entered for verification of Block F100 not integrated to Protheus"
		#define STR0119 "check tag InternalId in the ListOfSaleItem list"
		#define STR0120 "not found in From/To or its content was improperly filled out. The From/To is formed by COMPANY|BRANCH|TES."
		#define STR0121 " check if operator is registered in the correct target branch."
		#define STR0122 "sales with reservation needs the identification of the store to be informed, check tag: StoreIdentificationCode"
		#define STR0123 "Error in the customer´s register"
		#define STR0124 "Sum of Total Proportional Discount per item of tag"
		#define STR0125 "is different from Total Discount of tag"
		#define STR0126 "Number of voucher invalid, check tag: DocumentCode"
		#define STR0127 "SAT series not sent. Information required for SAT sale, check the tag SERIALNUMBERSATEQUIPAMENT"
		#define STR0128 "NFCe key is smaller than the pattern, check tag: KeyAcessNfe"
		#define STR0129 "Issue Date earlier than the closing date of parameter: MV_ULMES"
		#define STR0130 "Issue Date earlier than the closing date of parameter: MV_DBLQMOV"
		#define STR0131 "Carrier #1 not integrated in Protheus, check the integration of Carriers."
		#define STR0132 "Carrier"
		#define STR0133 "Station"
		#define STR0134 "Unable to register From\To of the #1 AUTOMATIC."
		#define STR0135 "Operator"
		#define STR0136 "Unable to configure AUTOMATIC operator. (#1)"
		#define STR0137 "Note of type #1 without provider identified, check CNPJ #2"
		#define STR0138 "Inconsistence in item #1, TAG #2 not informed required for Return Invoice."
		#define STR0139 "CFOP #1 not found in from\to or in DHJ table, check it."
		#define STR0140 "Address of stock: #1 does not exist. (#2)"
		#define STR0141 "Number of series: #1 does not exist, for product\address, (#2)"
		#define STR0142 "Reservation #1 - It has already been used or differs from the quantity reserved #2 with the quantity #3 received in the TAG Quantity."
		#define STR0143 "Reservation #1 does not exist for product #2"
		#define STR0144 "From\to found for #1#2, check if reservation was integrated."
		#define STR0145 "Reservation number (#1) not informed for item #2. For #3 3 or 4 the TAG is required."
		#define STR0146 "Error in return. TAG #1 is required."
		#define STR0147 "Invalid return event."
		#define STR0148 "Check tags: "
		#define STR0149 "The content of TAG UniqueSerialNumber is greater than what is supported by the fields #1, check it!"
		#define STR0150 "This message has tax information in #1, but its type of document was not informed in #2."
		#define STR0151 "Function #1 not exist, update #2 so the calculation of taxes is executed."
		#define STR0152 "Divergência de valores entre Cabeçalho, Itens + Frete dos Itens e Pagamentos, verifique as #1: #2, #3, #4 e #5"
		#define STR0153 "The value of the freight in the FreightValue TAG was informed, however, the value of the freight in the FreightValueProrated TAG in the products was not informed. This TAG must contain the freight value apportioned per product."
		#define STR0154 "The value of the freight in the FreightValueProrated TAG was informed, however, the value of the freight in the FreightValue TAG sales header was not informed."
		#define STR0155 "The freight value differs between the value informed in the sales header (FreightValue TAG) with the value informed in the items (FreightValueProrated TAG)."
		#define STR0156 "To generate a sales order, the content of parameter MV_LJPEDVE must be .T."
		#define STR0157 "The content of the MV_LJCONDP parameter must be entered with the code of a payment term for the generation of the sales order"
		#define STR0158 "The content of the MV_LJTESPE parameter must be filled with the code of a TIO that does not generate financial; check the TIO register configured in the parameter."
		#define STR0159 "The content of parameters MV_LJECOMO and MV_LJECOMM must be .F. when it is a CiaShop / VTex integration"
		#define STR0160 "After editing parameters, restart the Protheus services."
		#define STR0161 "required field not entered: Price List, check tag: ItemTablePrice."
		#define STR0162 "required field not entered: Product Price, check tag: ItemPrice."
		#define STR0163 "The TIO configured in the parameter MV_LJTESPE was not found; confirm that the TIO is actually registered."
		#define STR0164 "Freight type entered in the MV_LJTPFRE parameter is not valid; enter a valid freight type. After editing parameters, restart the Protheus services."
		#define STR0165 "The data found in TAG DocumentCode is larger than size of field L1_DOCPED of table SL1."
		#define STR0166 "The data found in TAG DocumentCode is larger than size of fields L1_DOCPED (Table SL1) and E_NUM (table SE1)."
		#define STR0167 "Sizes of fields L1_DOCPED (Table SL1) and E1_NUM (Table SE1) are different. Please, these fields must be of equal size."
		#define STR0168 "Error in return of entry point LJI701O1, the return was not array type."
		#define STR0169 "The data found in TAG ECommerceOrder is larger than size of field L1_ECPEDEC (Table SL1)."
		#define STR0170 "Warehouse #1 returned in the from/to of the tag (WarehouseInternalid) is not the same warehouse (C0_LOCAL) #2 of the reservation number: #3."
		#define STR0171 "The IPI reversal calculation generated a difference greater than 0.50 between the total paid and the order value. The round up adjustments of reversal calculation are limited to R$ 0.50. You need to open a ticket with the data of this order for analysis."
		#define STR0172 "Differences found between the VTEX order value for the IPI calculation. Check parameters MV_LJATIPI, MV_LJDTIPI."
		#define STR0173 "The tag PresencialIndicator received a non-valid value #1. Please check information received and adjust it in VTEX."
		#define STR0174 "In item #1 only carrier #2 was received, in which receipt is only allowed in header or in item. Please, request Json adjustment!"
		#define STR0175 "Discount received in tag DiscountValue with value #1. It will be changed to total value composition."
	#else
		#define STR0001 "Erro no parser!"
		#define STR0002 "Versao da mensagem nao informada!"
		#define STR0003 "A versao da mensagem informada nao foi implementada!"
		#define STR0004 "Marca nao integrada ao Protheus, verificar a marca da integracao"
		#define STR0005 "Estacao nao informada na integracao"
		#define STR0006 "Cupom nao informado, verificar a tag: DocumentCode."
		#define STR0007 "Cliente:"
		#define STR0008 "nao integrado ao Protheus, verificar integracao de clientes"
		#define STR0009 "Operador:"
		#define STR0010 "nao integrado ao Protheus, verificar integracao de operador"
		#define STR0011 "Estacao: "
		#define STR0012 "nao integrada no Protheus, verificar integracao de Estacao"
		#define STR0013 "Produto:"
		#define STR0014 "nao integrado ao Protheus, verificar integracao de Produto"
		#define STR0015 "Documento:"
		#define STR0016 "Serie:"
		#define STR0017 "Loja:"
		#define STR0018 "Operador nao informado na integracao, verifique a Tag OperatorCode."
		#define STR0019 "nao cadastrado no Protheus, verifique o cadastro de clientes."
		#define STR0020 "Campo obrigatorio nao informado: Data de Emissao, verifique a tag: IssueDateDocument."
		#define STR0021 "Campo obrigatorio nao informado: Id Interno, verifique a tag: InternalId."
		#define STR0022 "Cupom:"
		#define STR0023 "ja integrado no Protheus!"
		#define STR0024 "Atualize EAI"
		#define STR0025 "Erro na gravacao da venda:"
		#define STR0026 "nao encontrada no Protheus, verificar o cadastro ou integracao de Estacao."
		#define STR0027 "Campo obrigatorio nao informado: Valor Total da Venda, verifique a tag: TotalPrice."
		#define STR0028 "Campo obrigatorio nao informado: Valor Liquido da Venda, verifique a tag: NetPrice."
		#define STR0029 "Campo obrigatorio nao informado: Valor Bruto da Venda, verifique a tag: GrossPrice."
		#define STR0030 "Lista de produtos vazia, verifique a lista SaleItem."
		#define STR0031 "Inconsistencia no item"
		#define STR0032 "produto nao informado na integracao, verifique a Tag ItemCode."
		#define STR0033 "produto:"
		#define STR0034 "nao cadastrado no Protheus, verifique a tag: ItemCode"
		#define STR0035 "campo obrigatorio nao informado: Item, verifique a tag: ItemOrder."
		#define STR0036 "campo obrigatorio nao informado: Quantidade, verifique a tag: Quantity."
		#define STR0037 "campo obrigatorio nao informado: Preco Unitario, verifique a tag: UnitPrice."
		#define STR0038 "campo obrigatorio nao informado: Preco do Item, verifique a tag: ItemPrice."
		#define STR0039 "campo obrigatorio nao informado: CFOP, verifique a tag: OperationCode"
		#define STR0040 "TES nao informada, verifique o Cadastro de Produto no Protheus campo B1_TS e/ou De-Para de TES(XXF) e/ou as configurações para TES Inteligente(DHJ e SFM) e/ou parametros MV_TESSERV e MV_TESVEND."
		#define STR0041 "Valor Total divergente."
		#define STR0042 "verifique as tag TotalPrice e a soma das tags: ItemPrice."
		#define STR0043 "Lista de Forma de Pagamentos vazia, verifique a lista SaleCondition."
		#define STR0044 "Inconsistencia na forma de pagamento"
		#define STR0045 "Forma de Pagamento nao informado na integracao."
		#define STR0046 "Verifique as tags: PaymentMethodCode."
		#define STR0047 "Forma de Pagamento:"
		#define STR0048 "nao encontrado no Protheus."
		#define STR0049 "Verifique o cadastro de Forma de Pagamento."
		#define STR0050 "Administradora Financeira invalida ou nao encontrada no dePara no Protheus."
		#define STR0051 "Esta informacao e obrigatoria para pagamentos em cartao, verifique a tag: FinancialManagerCode."
		#define STR0052 "Valor do Pagamento nao informado ou zerado na integracao, verifique a tag: PaymentValue."
		#define STR0053 "Valor da venda divergente do total do pagamento"
		#define STR0054 "verifique as tags: NetPrice e PaymentValue."
		#define STR0055 "Versão nao suportada."
		#define STR0056 "As versoes suportadas sao:"
		#define STR0057 "Venda:"
		#define STR0058 "nao encontrado no de/para!"
		#define STR0059 "Foi detectado que o campo referente ao estado de cobranca(M0_ESTCOB) nao esta configurado."
		#define STR0060 "Efetue a inclusao no cadastro de filiais no Protheus."
		#define STR0061 "Inconsistencia na Data de Pagamento"
		#define STR0062 "Data de Pagamento nao informada, verifique a tag: DateOfPayment"
		#define STR0063 "CFOP invalida:"
		#define STR0064 "verifique o cadastro de CFOP"
		#define STR0065 "Campo obrigatório nao informado para Nfce: Informacoes Adicionais, verifique a tag: ElectronicInvoiceComplement"
		#define STR0066 "InternalId do RA nao informado"
		#define STR0067 "Esta informacao e obrigatoria para pagamentos RA, verifique a tag: AccountReceivableDocumentInternalId"
		#define STR0068 "Campo obrigatorio nao informado: MD-5, verifique a tag: Md5"
		#define STR0069 "Imposto ISS obrigatorio para Venda de Servico, verifique a tag: IssValue"
		#define STR0070 "Imposto ICMS informado para Venda de Servico, verifique a tag: IcmsValue"
		#define STR0071 "Imposto ICMS obrigatorio para Venda de Mercadoria, verifique a tag: IcmsValue"
		#define STR0072 "Imposto ISS informado para Venda de Mercadoria, verifique a tag: IssValue"
		#define STR0073 "imposto ISS obrigatorio para servico, verifique a tag: ItemIss"
		#define STR0074 "imposto ICMS obrigatorio para mercadoria, verifique a tag: ItemIcms"
		#define STR0075 "bloqueado, verifique o Cadastro de Clientes no Protheus."
		#define STR0076 "Serie nao informada na integracao, informacao obrigatoria para Nota Manual ou NFE, verifique a tag: SerieCode"
		#define STR0077 "Serie nao cadastrada, verifique o campo Serie do Cadastro de Estacoes no Protheus."
		#define STR0078 "Vendedor nao informado, obrigatorio para venda com comissao, verifique a tag: SellerInternalId."
		#define STR0079 "Vendedor:"
		#define STR0080 "nao integrado no Protheus, verifique a integracao de Vendedores."
		#define STR0081 "Evento incorreto, para exclusao utilize a integracao de Cancelamento de Venda."
		#define STR0082 "Evento nao informado!"
		#define STR0083 "Serie nao informada na integracao, informacao obrigatoria para RPS, verifique a tag: SerieCode"
		#define STR0084 "Job LjSendEAI Iniciado para a filial"
		#define STR0085 "Job LjSendEAI executado para a filial"
		#define STR0086 "O titulo de adiantamento"
		#define STR0087 "Verifique a tag: AccountReceivableDocumentInternalId"
		#define STR0088 "nao foi integrado ao Protheus"
		#define STR0089 "nao foi encontrado na base de dados Protheus"
		#define STR0090 "enviado produto do tipo mercadoria em uma RPS, verifique o campo B1_TIPO no Protheus"
		#define STR0091 "enviado produto do tipo servico em um Cupom, verifique o campo B1_TIPO no Protheus"
		#define STR0092 "encontra-se baixado"
		#define STR0093 "Necessário desfazer a compensação no financeiro"
		#define STR0094 "Chave NFCe nao enviada, informacao obrigatoria para venda NFCe, verifique a tag KeyAcessNfe"
		#define STR0095 "Protocolo NFCe nao enviado, informacao obrigatoria para venda NFCe, verifique a tag NfceProtocol"
		#define STR0096 "Reserva nao informada na integracao, informacao obrigatoria para o evento de altercao de venda, verifique a tag: HotelAccountCode"
		#define STR0097 "Tipo de venda nao informada, verifique a tag: KindOfDocument"
		#define STR0098 "Entidade nao informada ou nao integrada ao Protheus para rateio, verifique a lista: ListOfFinancialNatureApportionment, tag: GenericEntityInternalId."
		#define STR0099 "Percentual de rateio nao informado no rateio, verifique a lista: ListOfFinancialNatureApportionment, tag: Percentage."
		#define STR0100 "O somatorio do percentual de rateio esta diferente de 100 %, verifique a a lista: ListOfFinancialNatureApportionment, tag: Percentage."
		#define STR0101 "Centro de Custo nao informado, obrigatorio quando utilizado rateio, verifique no Protheus o parametro: MV_HTLCCRT"
		#define STR0102 "Para utilizar informacoes de rateio tag: ListOfFinancialNatureApportionment"
		#define STR0103 "é necessário habilitar o parametro MV_MULNATR no Protheus."
		#define STR0104 "Esta mensagem possui informacoes de rateio tag: ListOfFinancialNatureApportionment mas nao é uma RPS"
		#define STR0105 "verifique a tag: KindOfDocument."
		#define STR0106 "Armazem:"
		#define STR0107 "nao integrado ao Protheus, verificar integracao de armazens"
		#define STR0108 "Codigo de Identificacao de loja"
		#define STR0109 "nao cadastrado no Protheus"
		#define STR0110 "campo LJ_CCUSTO vazio"
		#define STR0111 "informacao obrigatoria quando enviado centro de consumo: StoreIdentificationCode"
		#define STR0112 "campo LJ_ITEMCC vazio"
		#define STR0113 "campo LJ_CLVL vazio"
		#define STR0114 "nao informada a data para verificacao do Bloco F100"
		#define STR0115 "esta informacao é obrigatoria quando informada a venda origem Bloco F100"
		#define STR0116 "verifique a tag: DateOfMovement localizada na lista BoardBasisInformation"
		#define STR0117 "nao informada a lista BoardBasisInformation"
		#define STR0118 "venda informada para verificacao do Bloco F100 nao integrada ao Protheus"
		#define STR0119 "verifique a tag InternalId na lista ListOfSaleItem"
		#define STR0120 "não foi encontrado no De/Para ou seu conteúdo foi preenchido incorretamente. O De/para é formado por EMPRESA|FILIAL|TES."
		#define STR0121 " verificar se o operador esta cadastrado na filial destino correta."
		#define STR0122 "venda com reserva necessita que seja informada a identificação de loja, verifique a tag: StoreIdentificationCode"
		#define STR0123 "Erro no cadastro do cliente"
		#define STR0124 "A somatoria do Desconto Total Proporcionalizado por item da tag"
		#define STR0125 "está diferente do Desconto Total da tag"
		#define STR0126 "Número do cupom inválido, verificar a tag: DocumentCode"
		#define STR0127 "Série SAT não enviada, informacao obrigatória para venda SAT, verifique a tag SERIALNUMBERSATEQUIPAMENT"
		#define STR0128 "Chave NFCe menor que o padrão, verifique a tag: KeyAcessNfe"
		#define STR0129 "Data de Emissao menor que a data do fechamento do parâmetro: MV_ULMES"
		#define STR0130 "Data de Emissao menor que a data do fechamento do parâmetro: MV_DBLQMOV"
		#define STR0131 "Transportadora #1 não integrada no Protheus, verifique a integração de Transportadoras."
		#define STR0132 "Transportadora"
		#define STR0133 "Estação"
		#define STR0134 "Não foi possível efetuar o cadastro do De\Para da(o) #1 AUTOMATICO."
		#define STR0135 "Operador"
		#define STR0136 "Não foi possível configurar o operador AUTOMATICO. (#1)"
		#define STR0137 "Nota do tipo #1 sem fornecedor identificado, verifique o CNPJ. #2"
		#define STR0138 "Inconsistência no item #1, não informada a TAG #2, obrigatária para Notas de Devolução."
		#define STR0139 "O CFOP #1 não foi encontrado no de\pare ou na tabela DHJ, verifique."
		#define STR0140 "Endereço de estoque: #1 não existe. (#2)"
		#define STR0141 "Número de série: #1 não existe, para o produto\endereço, (#2)"
		#define STR0142 "Reserva #1 - Já foi usada ou difere com a quantidade reservada #2 com a quantidade #3 recebida na TAG Quantity."
		#define STR0143 "Reserva #1 não existe para o produto #2"
		#define STR0144 "Não foi encontrado de\para, para o #1 #2, verifique se a reserva foi integrada."
		#define STR0145 "Não foi informado o número da reserva (#1), para o item #2. Para #3 3 ou 4 a TAG é obrigatória."
		#define STR0146 "Erro no retorno, a TAG #1 é obrigatória."
		#define STR0147 "Evento do retorno inválido."
		#define STR0148 "Verifique as TAGs: "
		#define STR0149 "O conteúdo da TAG UniqueSerialNumber é maior que o suportado pelos campos #1, verifique!"
		#define STR0150 "Esta mensagem possui informações de impostos na #1, mas seu tipo de documento não foi informado na #2."
		#define STR0151 "Função #1 não existe, atualize o #2 para que o cálculo de impostos seja efetuado."
		#define STR0152 "Divergência de valores entre Cabeçalho, Itens + Frete dos Itens e Pagamentos, verifique as #1: #2, #3, #4 e #5"
		#define STR0153 "Foi informado o valor do frete na TAG FreightValue, porém, não foi informado o valor do frete na TAG FreightValueProrated nos produtos. Nesta TAG devera conter o valor do frete rateado por produto."
		#define STR0154 "Foi informado o valor do frete na TAG FreightValueProrated, porém, não foi informado o valor do frete no cabeçalho da venda na TAG FreightValue."
		#define STR0155 "O valor do frete esta divergente entre o valor informado no cabeçalho da venda (TAG FreightValue) com o valor informado nos itens (TAG FreightValueProrated)."
		#define STR0156 "Para a geração do pedido de venda, o parâmetro MV_LJPEDVE deve ter o conteúdo .T. "
		#define STR0157 "O conteúdo do parâmetro MV_LJCONDP deve ser informado com o código de uma condição de pagamento para a geração do pedido de venda "
		#define STR0158 "O conteúdo do parâmetro MV_LJTESPE deve estar preenchido com o código de uma TES que não gera financeiro, por favor, verifique o cadastro da TES configurada no parâmetro "
		#define STR0159 "Os parâmetros MV_LJECOMO e MV_LJECOMM devem obrigatoriamente estar com o conteúdo .F. quando for uma integração CiaShop / VTex "
		#define STR0160 "Após a alteração do(s) parâmetro(s), é necessario reiniciar o(s) serviço(s) do Protheus. "
		#define STR0161 "campo obrigatório não informado: Preço de tabela, verifique a tag: ItemTablePrice."
		#define STR0162 "campo obrigatório não informado: Preço do produto, verifique a tag: ItemPrice."
		#define STR0163 "Não foi encontrada a TES configurada no parâmetro MV_LJTESPE, por favor, confirme se realmente a TES esta cadastrada "
		#define STR0164 "Tipo de frete informado no parâmetro MV_LJTPFRE não é valido, informe um tipo de frete valido. Após a alteração do parâmetro, é necessario reiniciar os serviços do Protheus."
		#define STR0165 "A informação contida na TAG DocumentCode esta maior que o tamanho do campo L1_DOCPED da tabela SL1."
		#define STR0166 "A informação contida na TAG DocumentCode esta maior que o tamanho dos campos L1_DOCPED (Tabela SL1) e E1_NUM (Tabela SE1)."
		#define STR0167 "O tamanho dos campos L1_DOCPED (Tabela SL1) e E1_NUM (Tabela SE1) estão com tamanhos diferentes, por favor, esses campos devem conter o mesmo tamanho."
		#define STR0168 "Erro no retorno do ponto de entrada LJI701O1, o retorno não foi do tipo array."
		#define STR0169 "A informação contida na TAG ECommerceOrder esta maior que o tamanho do campo L1_ECPEDEC (Tabela SL1)."
		#define STR0170 "Armazém #1 retornado no de/para da tag (WarehouseInternalid) não é o mesmo armazém (C0_LOCAL) #2 da reserva numero: #3."
		#define STR0171 "O calculo reverso de IPI gerou uma diferença maior que 0.50 entre o total pago e o valor de pedido. Os ajustes de arredondamentos de calculo reverso são limitados em R$ 0.50 centavos. Será necessario a abertura de chamado com os dados desse pedido para analise."
		#define STR0172 "Foram encontrados diferenças entre o valor do pedido VTEX para o calculo do IPI. Favor verificar os paramentros MV_LJATIPI, MV_LJDTIPI."
		#define STR0173 "A tag PresencialIndicator recebeu um valor não valido #1. Favor verificar a informação recebida e ajuste na VTEX."
		#define STR0174 "No item #1 foi recebido a transportadora #2, onde apenas é permitido o recebimento no cabeçalho ou no item. Favor solicitar o ajuste do Json!"
		#define STR0175 "O desconto recebido na tag DiscountValue com o valor #1. Será alterado para composição de valor total."
	#endif
#endif
