#ifdef SPANISH
	#define STR0001 "Falla al integrar con snowden. Error: FederalID no se encontró en el archivo totvslicenseagreement"
	#define STR0002 "Integración Snowden: Finalizada"
	#define STR0003 " Integración con snowden efectuada con éxito"
	#define STR0004 "Falla al integrar con snowden. Intento: #1 | URL:#2 | URI: #3 | Error: #4 "
	#define STR0005 "Falla al integrar con snowden. Error: Clave Error/Log no ubicado en el Json"
	#define STR0006 "Error en la persistencia de actualización del log #1 del snowden. Mensaje de error: #2"
	#define STR0007 "Persistencia de actualización del log #1 del snowden"
	#define STR0008 "Integración Snowden: Iniciada"
	#define STR0009 "Inicio de la transmisión de datos al Snowden"
	#define STR0010 "Fin de la transmisión de datos al Snowden"
	#define STR0011 "Falla en la integración con el snowden, no se encontró el TOTVSID en la instalación del License Server"
	#define STR0012 "Falla en la integración con el snowden, URI no se definió en el mensaje."
	#define STR0013 "Falla en la integración con el snowden. URL:#1 | URI: #2 | Error: #3"
	#define STR0014 "No fue posible obtener token para realizar la requisición."
	#define STR0015 "Falla en la integración con el snowden. Intento: #1 | Dirección #2 | error: #3"
#else
	#ifdef ENGLISH
		#define STR0001 "Failure integrating with snowden. Error: FederalID not found in totvslicenseagreement file"
		#define STR0002 "Integration Snowden: Finalized"
		#define STR0003 " Integration with snowden successfully performed"
		#define STR0004 "Failure integrating with snowden Attempt: #1 | URL:#2 | URI: #3 | Error: #4 "
		#define STR0005 "Failure integrating with snowden. Erro: Error Key/Log not found in Json"
		#define STR0006 "Error in the persistence of the updating of the log #1 of snowden. Error Message: #2"
		#define STR0007 "Persitenc of updating of log #1 of snowden"
		#define STR0008 "Integration Snowden: Started"
		#define STR0009 "Start of data transmission for Snowden"
		#define STR0010 "End of data transmission for TOTVS"
		#define STR0011 "Failure integrating with Snowden, not found in TOTVSID in the installation of the License Server"
		#define STR0012 "Failure in the integration with snowden, URI not defined in the message."
		#define STR0013 "Failure integrating with snowden. URL:#1 | URI: #2 | Error: #3"
		#define STR0014 "Unable to get token for request."
		#define STR0015 "Failure integrating with snowden. Attempt: #1 | Address #2 | error: #3"
	#else
		#define STR0001 "Falha na integracao com snowden. Erro: FederalID não encontrado no arquivo totvslicenseagreement"
		#define STR0002 "Integracao Snowden: Finalizada"
		#define STR0003 " Integracao com snowden efetuada com sucesso"
		#define STR0004 "Falha na integracao com snowden. Tentativa: #1 | URL:#2 | URI: #3 | Erro: #4 "
		#define STR0005 "Falha na integracao com snowden. Erro: Chave Error/Log não localizada no Json"
		#define STR0006 "Erro na persitência de atualização do log #1 do snowden. Mensagem de Erro: #2"
		#define STR0007 "Persitência de atualização do log #1 do snowden"
		#define STR0008 "Integracao Snowden: Iniciada"
		#define STR0009 "Inicio da transmissão dos dados para o Snowden"
		#define STR0010 "Fim da transmissão dos dados para o Snowden"
		#define STR0011 "Falha na integração com o snowden, não encontrado TOTVSID na instalação do License Server"
		#define STR0012 "Falha na integração com snowden, URI não definida na mensagem."
		#define STR0013 "Falha na integracao com snowden. URL:#1 | URI: #2 | Erro: #3"
		#define STR0014 "Não foi possivel obter token para realizar requisicao."
		#define STR0015 "Falha na integração com o snowden. Tentativa: #1 | Endereço #2 | erro: #3"
	#endif
#endif
