#ifdef SPANISH
	#define STR0001 "Mantenimiento de usuarios Intera"
	#define STR0002 "Vincular nuevo ID"
	#define STR0003 "Retirar ID"
	#define STR0004 "Visualizar ID"
	#define STR0005 "Usuarios disponibles para asociación de licencia Intera"
	#define STR0006 "Usuarios"
	#define STR0007 "OK"
	#define STR0008 "Inclusión de usuarios "
	#define STR0009 "Anular"
	#define STR0010 "Usuario licencia Intera"
	#define STR0011 "Usuario Intera"
	#define STR0012 "Usuarios Relacionados Identity"
	#define STR0013 "Buscar usuario"
	#define STR0014 "Usuario"
	#define STR0015 "Licencia"
	#define STR0016 "ID"
	#define STR0017 "Nombre"
	#define STR0018 "E-mail"
	#define STR0019 "ERP"
	#define STR0020 "Identity"
	#define STR0021 "Slot Intera"
	#define STR0022 "Descripción de licencia"
	#define STR0023 "No se encontró ningún usuario con los datos informados"
	#define STR0024 "El usuario #1 se encuentra vinculado a la licencia #2"
	#define STR0025 "La licencia #1 alcanzó el límite de usuarios contratado, no es posible vincular al usuario #2 en esta licencia."
	#define STR0026 "Persistencia del vínculo de intera#1 al usuario :#2"
	#define STR0027 "Persistencia de la desvinculación de intera del usuario :#1"
	#define STR0028 "Finalizar"
	#define STR0029 "Confirmar"
	#define STR0030 "Error en el borrado de usuarios excedentes del slot #1 Intera"
	#define STR0031 "Error en el borrado de usuarios excedentes de las licencias Intera #1"
	#define STR0032 'Otros usuarios vinculados al ID'
	#define STR0033 "Error al persistir vínculo de Intera. Usuario: #1 Linea de producto: #2 Slot: #3 Erro: #4"
	#define STR0034 "Error al persistir desvínculo del Intera. Usuario: #1 Línea de producto: #2 Error: #3"
	#define STR0035 "Borrando usuarios excedentes del slot #1 Intera"
	#define STR0036 "Borrando usuarios del slot #1 Intera que ya no existe en el agreement"
	#define STR0037 "Persistencia de actualización de IDM en el Intera. Usuario: #1 Línea de producto: #2"
	#define STR0038 "Error al persistir actualización de IDM en el Intera. Usuario: #1 Línea de producto: #2"
	#define STR0039 "No puede existir línea de producto duplicada en la lista de usuarios."
#else
	#ifdef ENGLISH
		#define STR0001 "Intera Maintenance of Users"
		#define STR0002 "Associate New ID"
		#define STR0003 "Remove ID"
		#define STR0004 "View ID"
		#define STR0005 "Users Available for the Association of Intera License"
		#define STR0006 "Users"
		#define STR0007 "OK"
		#define STR0008 "Adding Users "
		#define STR0009 "Cancel"
		#define STR0010 "Intera License User"
		#define STR0011 "Intera User"
		#define STR0012 "Identity Related Users"
		#define STR0013 "Search User"
		#define STR0014 "User"
		#define STR0015 "License"
		#define STR0016 "ID"
		#define STR0017 "Name"
		#define STR0018 "E-mail"
		#define STR0019 "ERP"
		#define STR0020 "Identity"
		#define STR0021 "Slot Intera"
		#define STR0022 "License Description"
		#define STR0023 "No user found with the data entered."
		#define STR0024 "User #1 is already associated to license #2"
		#define STR0025 "License #1 has already reached the limit of users contracted, unable to associate user #2 in this license."
		#define STR0026 "Persistence of the association of intera #1 to user :#2"
		#define STR0027 "Persistence of the association of intera :#1"
		#define STR0028 "Close"
		#define STR0029 "Confirm"
		#define STR0030 "Error deleting exceeding users of slot #1 Intera"
		#define STR0031 "Error deleting exceeding users of Intera licenses #1"
		#define STR0032 'Other Users Associated to ID'
		#define STR0033 "Error persisting association of Intera. User: #1 Product Line: #2 Slot: #3 Error: #4"
		#define STR0034 "Error persisting disassociation of Intera. User: #1 Product Line: #2 Error: #3"
		#define STR0035 "Deleting exceeding users of slot #1 Intera"
		#define STR0036 "Deleting users of slot #1 Intera that does not exist in agreement any longer"
		#define STR0037 "Persistence of IDM updating in Intera. User: #1 Product Line: #2"
		#define STR0038 "Persistence of IDM updating in Intera. User: #1 Product Line: #2"
		#define STR0039 "You cannot have doubled product line in the list of users."
	#else
		#define STR0001 "Manutenção Usuários Intera"
		#define STR0002 "Associar Novo ID"
		#define STR0003 "Remover ID"
		#define STR0004 "Visualizar ID"
		#define STR0005 "Usuarios Disponiveis para Associação de Licença Intera"
		#define STR0006 "Usuarios"
		#define STR0007 "OK"
		#define STR0008 "Inserindo Usuarios "
		#define STR0009 "Cancelar"
		#define STR0010 "Usuario Licenca Intera"
		#define STR0011 "Usuario Intera"
		#define STR0012 "Usuarios Relacionados Identity"
		#define STR0013 "Buscar Usuario"
		#define STR0014 "Usuario"
		#define STR0015 "Licença"
		#define STR0016 "ID"
		#define STR0017 "Nome"
		#define STR0018 "E-mail"
		#define STR0019 "ERP"
		#define STR0020 "Identity"
		#define STR0021 "Slot Intera"
		#define STR0022 "Descrição Licença"
		#define STR0023 "Não foi localizado nenhum usuário com os dados informados."
		#define STR0024 "O usuário #1 já se encontra associado a licença #2"
		#define STR0025 "A licença #1 já atingiu o limite de usuarios contratado, não é possível associar o usuario #2 nessa licença."
		#define STR0026 "Persistência da associação de intera#1 ao usuario :#2"
		#define STR0027 "Persistência da desassociação de intera do usuario :#1"
		#define STR0028 "Fechar"
		#define STR0029 "Confirmar"
		#define STR0030 "Erro na exclusão de usuarios excedentes do slot #1 Intera"
		#define STR0031 "Erro na exclusão de usuarios excedente das licenças Intera #1"
		#define STR0032 'Outros Usuarios Associados ao ID'
		#define STR0033 "Erro ao persistir associação de Intera. Usuario: #1 Linha de Produto: #2 Slot: #3 Erro: #4"
		#define STR0034 "Erro ao persistir desassociação de Intera. Usuario: #1 Linha de Produto: #2 Erro: #3"
		#define STR0035 "Excluido usuarios excedentes do slot #1 Intera"
		#define STR0036 "Excluido usuarios do slot #1 Intera que não existe mais no agreement"
		#define STR0037 "Persistência de atualização de IDM no Intera. Usuario: #1 Linha de Produto: #2"
		#define STR0038 "Erro ao persistir atualização de IDM no Intera. Usuario: #1 Linha de Produto: #2"
		#define STR0039 "Não pode existir linha de produto duplicada na relação de usuarios."
	#endif
#endif
