#ifdef SPANISH
	#define STR0001 "Tabla CDM (Control de Credito ICMS No Destacado) no se encontro en el diccionario."
	#define STR0002 "Tabla CDM es necesaria para la generacion de la rutina, por lo tanto, sera necesario efectuar los procedimientos destacados en el boletib del compatibilizador UPDFIS que crea esta tabla e informa como alimentarla en movimientos anteriores."
	#define STR0003 "¿Desea realmente reprocesar todo ?"
	#define STR0004 "¡ATENCION!"
	#define STR0005 "Reprocesando todo movimiento del periodo seleccionado"
	#define STR0006 "Espere...."
	#define STR0007 "Procesando Saldos iniciales ICMS ST"
	#define STR0008 "Procesando Documentos de Entrada"
	#define STR0009 "Procesando Documentos de Salida"
	#define STR0010 "Seleccionando registros"
	#define STR0011 "Fecha de "
	#define STR0012 "Fecha A "
	#define STR0013 "Si "
	#define STR0014 "No"
	#define STR0015 "¿Reprocesa todo?"
	#define STR0016 "Esta rutina va a calcular el valor del credito del ICMS que se pagara en los terminos del art.271"
	#define STR0017 "del Reglamento del ICMS del estado de Sao Paulo de 30/11/2000."
	#define STR0018 "¡Atencion!"
	#define STR0019 "Este credito solamente se aplica a los contribuyentes del ICMS del estado de Sao Paulo "
	#define STR0020 "y entre estos los que se incluyen a lo previsto en el articulo mencionado"
	#define STR0021 "Calculo Cred.ICMS ST"
	#define STR0022 "Procesando Devoluciones Compras"
	#define STR0023 "Procesando Devoluciones Ventas"
	#define STR0024 "Fecha Inicial para procesamiento de movimiento"
	#define STR0025 "Fecha Final para procesamiento de movimiento"
	#define STR0026 "Indica si debe procesar nuevamente toda el movimiento"
	#define STR0027 "Procesando Complementos Precios"
	#define STR0028 "Para utilizacion, habilitar parametros de la rutina segun Boletin tecnico Calculo Credito ICMS conf. Art.271 RICMS/SP"
	#define STR0029 "¡Procesamiento Concluido!"
	#define STR0030 "¡El periodo que se procesara debera estar dentro del mismo mes!"
	#define STR0031 "Procesando Ajuste Transferencias-Requisiciones"
	#define STR0032 "¿Considera Transf Sucursales?"
	#define STR0033 "Esta rutina sólo se aplica a los contribuyentes de ICMS del Estado de São Paulo"
	#define STR0034 "Indica si debve Considerar Transf Sucursales"
	#define STR0035 "Para su utilizacion habilite parametros de la rutina segun el Boletin tecnico Control para restitucion del ICMS-ST"
	#define STR0036 "Control para restitucion del ICMS-ST."
	#define STR0037 "¿Selecciona sucursales?"
	#define STR0038 "Indica si desea seleccionar mas de una sucursal para generacion del procesamiento de forma secuencial."
	#define STR0039 "Parametro activo solamente en entorno dbAccess."
	#define STR0040 "¿Agrupa por RCPJ + I.E.?"
	#define STR0041 "Indica si desea validar la seleccion de sucursales por RCPJ e I.E. para el procesamiento de mas de una sucursal."
#else
	#ifdef ENGLISH
		#define STR0001 "CDM table (Control of Not-Allocated ICMS Credit) was not found in dictionary."
		#define STR0002 "CDM table is necessary to routine generation; therefore, you must follow procedures emphasized in the newsletter of  UPDFIS compatibility program, which creates this table and informs how to insert data into it in previous movements. "
		#define STR0003 "Do you want to reprocess all?"
		#define STR0004 "ATTENTION!"
		#define STR0005 "Reprocessing all movement of selected period."
		#define STR0006 "Wait..."
		#define STR0007 "Processing ICMS 17 initial balances"
		#define STR0008 "Processing Receipt Documents"
		#define STR0009 "Processing Issue Documents"
		#define STR0010 "Selecting records"
		#define STR0011 "Date from "
		#define STR0012 "Date to "
		#define STR0013 "Yes "
		#define STR0014 "No"
		#define STR0015 "Reprocess all?"
		#define STR0016 "This routine calculates the ICMS credit value to be assumed in the terms of art. 271"
		#define STR0017 "of ICMS Rules of the state of São Paulo, from 11/30/00."
		#define STR0018 "Atention!!!"
		#define STR0019 "This credit is applied only to ICMS taxpayers of the state of São Paulo "
		#define STR0020 "and, among them, those included in the article mentioned"
		#define STR0021 "ST ICMS Cred. Calculation"
		#define STR0022 "Processing Purchase Returns"
		#define STR0023 "Processing Sale Returns"
		#define STR0024 "Initial Date for transaction processing"
		#define STR0025 "Final Date for transaction processing"
		#define STR0026 "It indicates whether the entire transaction must be processed."
		#define STR0027 "Processing Price Complements"
		#define STR0028 "To use it, you must enable routine parameters according to Technical Newsletter ICMS Credit Calculation acc.  Art. 271 of RICMS/SP."
		#define STR0029 "Processing finished!"
		#define STR0030 "The period to be processed must be within the same month!"
		#define STR0031 "Processing Adjustment Transfers-Requisition"
		#define STR0032 "Transfer Branches?"
		#define STR0033 "This routines applies only to ICMS taxpayers in the State of São Paulo"
		#define STR0034 "Indicates if Branch Transfer must be considered."
		#define STR0035 "To use, enable  routine parameters according to Technical Bulletin Control for ICMS-ST Reimbursement"
		#define STR0036 "ICMS-TS Refund Control."
		#define STR0037 "Select Branches?"
		#define STR0038 "Enter whether you wish to select more than one branch to generate process sequentially."
		#define STR0039 "Parameter active only in dbAccess environment."
		#define STR0040 "Group by CNPJ + I.E.?"
		#define STR0041 "Enter whether you wish to validate the selection of branches by CNPJ and I.E. to process more than one branch."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Tabela CDM (Controle do Crédito ICMS Não Destacado) não foi encontrada no dicionário.", "Tabela CDM (Controle do Credito ICMS Nao Destacado) não foi encontrada no dicionário." )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Tabela CDM é necessária para a criação do procedimento, portanto será necessário efectuar os procedimentos destacados no boletim do compatibilizador UPDFIS que cria esta tabela e informa como alimentá-la em movimentações anteriores.", "Tabela CDM é necessária para a geração da rotina, portanto será necessário efetuar os procedimentos destacados no boletim do compatibilizador UPDFIS que cria esta tabela e informa como alimentá-la em movimentações anteriores." )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Deseja realmente processar tudo ?", "Deseja realmente reprocessar tudo ?" )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "ATENÇÃO!", "ATENÇÃO !!!!" )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "A reprocessar toda movimentação do período seleccionado", "Reprocessando toda movimentacao do periodo selecionado" )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Aguarde...", "Aguarde...." )
		#define STR0007 "Processando Saldos iniciais ICMS ST"
		#define STR0008 "Processando Documentos de Entrada"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Processando Documentos de Saída", "Processando Documentos de Saida" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "A seleccionar registos", "Selecionado registros" )
		#define STR0011 "Data De "
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Data Até ", "Data Ate " )
		#define STR0013 "Sim "
		#define STR0014 "Não"
		#define STR0015 "Reprocessa tudo?"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Este procedimento irá calcular o valor do crédito do ICMS a ser apropriado nos termos art.271", "Esta rotina irá calcular o valor do crédito do ICMS a ser apropriado nos termos art.271" )
		#define STR0017 "do Regulamento do ICMS do estado de São Paulo de 30/11/2000."
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Atenção!", "Atenção!!!" )
		#define STR0019 "Este crédito só se aplica aos contribuintes do ICMS do estado de São Paulo e"
		#define STR0020 "e dentre estes os que se subsumam ao previsto no artigo mencionado"
		#define STR0021 "Cálculo Créd.ICMS ST"
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "A processar Devoluções Compras", "Processando Devoluções Compras" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "A processar Devoluções Vendas", "Processando Devoluções Vendas" )
		#define STR0024 "Data Inicial para processamento movimentação"
		#define STR0025 "Data Final para processamento movimentação"
		#define STR0026 "Indica se deve reprocessar toda a movimentação"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "A Processar Complementos Preços", "Processando Complementos Precos" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Para utilização habilitar parâmetros do procedimento segundo Boletim Técnico Cálculo Crédito ICMS conf. Art.271 RICMS/SP", "Para utilizacao habilitar parametros da rotina segundo Boletim tecnico Calculo Credito ICMS conf. Art.271 RICMS/SP" )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Processamento Concluido!", "Processamento Concluido !" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "O período a ser processado deverá estar dentro do mesmo mês!", "O periodo a ser processado devera estar dentro do mesmo mes!" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "A Processar Ajuste Transferências-Requisições", "Processando Ajuste Transferências-Requisições" )
		#define STR0032 "Considera Transf Filiais?"
		#define STR0033 "Esta rotina só se aplica aos contribuintes do ICMS do Estado de São Paulo"
		#define STR0034 "Indica se deve Considerar Transf Filiais"
		#define STR0035 "Para utilizacao habilitar parametros da rotina segundo Boletim tecnico Controle para Restituição do ICMS-ST"
		#define STR0036 "Controle para Restituição do ICMS-ST."
		#define STR0037 "Seleciona Filiais?"
		#define STR0038 "Indica se deseja selecionar mais de uma filial para geração do processamento de forma sequencial."
		#define STR0039 "Parâmetro ativo somente em ambiente dbAccess."
		#define STR0040 "Aglutina por CNPJ + I.E.?"
		#define STR0041 "Indica se deseja validar a seleção de filiais por CNPJ e I.E. para o processamento de mais de uma filial."
	#endif
#endif
