#ifdef SPANISH
	#define STR0001 "Num.Factura"
	#define STR0002 "Serie Factura"
	#define STR0003 "Proveedor"
	#define STR0004 "Buscar"
	#define STR0005 "Visualizar"
	#define STR0006 "Incluir"
	#define STR0007 "Clasificar"
	#define STR0008 "Borrar"
	#define STR0009 "Facturas de Compras"
	#define STR0010 "Factura de compras de mercaderias"
	#define STR0011 "Tipo"
	#define STR0012 "Impreso propio"
	#define STR0013 "Factura"
	#define STR0014 "Serie"
	#define STR0015 "Fecha"
	#define STR0016 "Cliente"
	#define STR0017 "Proveedor"
	#define STR0018 "Factura flete:"
	#define STR0019 "Tipo de documento"
	#define STR0020 "Cliente: "
	#define STR0021 "Proveedor: "
	#define STR0022 "Fch Entr:"
	#define STR0023 "Total factura"
	#define STR0024 "Proveedor"
	#define STR0025 "Cliente"
	#define STR0026 "Cliente: "
	#define STR0027 "Proveedor"
	#define STR0028 "Proveedor: "
	#define STR0029 "Datos contables financieros"
	#define STR0030 "Fecha contabilizacion"
	#define STR0031 "Cond. de pago"
	#define STR0032 "Pedidos de compras"
	#define STR0033 "Tienda"
	#define STR0034 "Pedido"
	#define STR0035 "Item"
	#define STR0036 "Saldo"
	#define STR0037 "Entrega"
	#define STR0038 "Descripcion"
	#define STR0039 "Tipo"
	#define STR0040 "Totales &Generales"
	#define STR0041 "&Impuestos"
	#define STR0042 "Libros &Fiscales"
	#define STR0043 "&Detalles"
	#define STR0044 "Prefijo"
	#define STR0045 "Numero"
	#define STR0046 "Orden"
	#define STR0047 "Vencimiento"
	#define STR0048 "Vlr. Titulo"
	#define STR0049 "Modalidad"
	#define STR0050 "IRRF"
	#define STR0051 "ISS"
	#define STR0052 "Moneda"
	#define STR0053 "Registro."
	#define STR0054 "&Gastos"
	#define STR0055 "Rut: "
	#define STR0056 "¿Muestra asientos ?"
	#define STR0057 "¿Aglomera asientos ?"
	#define STR0058 "¿Verif. Cotizacion ?"
	#define STR0059 "¿Aplicar reajuste  ?"
	#define STR0060 "¿Incluir vinculo   ?"
	#define STR0061 "¿Asientos On-Line  ?"
	#define STR0062 "¿Consd. Sucursal PC?"
	#define STR0063 "¿O. P. Triangular  ?"
	#define STR0064 "¿Factura por dif.  ?"
	#define STR0065 "Si"
	#define STR0066 "No"
	#define STR0067 "Por favor, espere..."
	#define STR0068 "Grabando facturas..."
	#define STR0069 'Pulse "Detalles" para calcular costos e impuestos...'
	#define STR0070 "Ejecutar detalles..."
	#define STR0071 "íAtencion! "
	#define STR0072 'Para actualizar el valor bruto, ejecutar "Detalles"...'
	#define STR0073 "Por favor espere..."
	#define STR0074 "Prorrateando costos " + CHR ( 10 ) + CHR ( 13 ) + "Recalculando impuestos y totales..."
	#define STR0075 "Tel. : "
	#define STR0076 "Fax : "
	#define STR0077 "Contacto : "
	#define STR0078 "Integracion caja chica"
	#define STR0079 "Caja "
	#define STR0080 "Beneficiado"
	#define STR0081 "Valor"
	#define STR0082 "Num.de Anticipo "
	#define STR0083 "Historial"
	#define STR0084 "Anticipos"
	#define STR0085 "¿Desea transferir el saldo remanente a la caja chica?"
	#define STR0086 "Anticipo con saldo remanente"
	#define STR0087 "Tasa "
	#define STR0088 "Actualizar archivo de monedas"
	#define STR0089 "Flete incluido"
	#define STR0090 "Porc. Flete"
	#define STR0091 "Si"
	#define STR0092 "No"
	#define STR0093 "Importacion"
	#define STR0094 "¿Desea clasificar Facturas de Importacion?"
	#define STR0095 "Considera proveedor en el pedido de compras"
	#define STR0096 "Esta factura no es de compra"
	#define STR0097 "Num. Correlativo"
	#define STR0098 " en blanco, ¿confirma?"
	#define STR0099 "Seleccione un tipo valido de factura: N = Normal o B = Beneficio"
	#define STR0100 "Hay una orden de produccion cerrada para algun item. Anule la producion da la OP.: "
	#define STR0101 "Facturas del proceso de importacion"
	#define STR0102 "Proceso:"
	#define STR0103 "¿Desea generar Guia de Despacho?"
	#define STR0104 "Gestion de proyectos - <F10> "
	#define STR0105 "Cargando la factura"
	#define STR0106 "Seleccionando "
	#define STR0107 "Preparando "
	#define STR0108 " de Compras"
	#define STR0109 "Finalizar"
	#define STR0110 "Valor"
	#define STR0111 "Historial"
	#define STR0112 "Valor el"
	#define STR0113 "Detalles de la baja"
	#define STR0114 "Cheque"
	#define STR0115 "Situación"
	#define STR0116 "Dep. el"
	#define STR0117 "Compensación"
	#define STR0118 "Usado en op"
	#define STR0119 "Acreditado el"
	#define STR0120 "Rechazado el"
	#define STR0121 "Desconocida"
	#define STR0122 "Detalles"
	#define STR0123 "Deuda financiera: "
	#define STR0124 "Acreditado: "
	#define STR0125 "Débito"
	#define STR0126 "Sin debitar "
	#define STR0127 "Debitado el "
	#define STR0128 "Vencido: "
	#define STR0129 "Por vencer: "
	#define STR0130 "Debitado: "
#else
	#ifdef ENGLISH
		#define STR0001 "Invoice Numb."
		#define STR0002 "Invoice Series "
		#define STR0003 "Vendor "
		#define STR0004 "Search   "
		#define STR0005 "View     "
		#define STR0006 "Add "
		#define STR0007 "Classify"
		#define STR0008 "Delete "
		#define STR0009 "Inflow Invoices"
		#define STR0010 "Inflow Invoice of Goods"
		#define STR0011 "Type"
		#define STR0012 "Own Form"
		#define STR0013 "Invoice"
		#define STR0014 "Series"
		#define STR0015 "Date"
		#define STR0016 "Customer  "
		#define STR0017 "Supplier"
		#define STR0018 "Waybill:"
		#define STR0019 "Type of Document"
		#define STR0020 "Customer: "
		#define STR0021 "Vendor:  "
		#define STR0022 "Dt Receiv"
		#define STR0023 "Invoice Total"
		#define STR0024 "Vendor "
		#define STR0025 "Customer "
		#define STR0026 "Customer: "
		#define STR0027 "Vendor  "
		#define STR0028 "Vendor: "
		#define STR0029 "Financial Accounting Data"
		#define STR0030 "Accounting Date"
		#define STR0031 "Payment Terms"
		#define STR0032 "Purchase Orders"
		#define STR0033 "Unit  "
		#define STR0034 "Order "
		#define STR0035 "Item"
		#define STR0036 "Balance"
		#define STR0037 "Delivery"
		#define STR0038 "Description"
		#define STR0039 "Type"
		#define STR0040 "&Grand Total"
		#define STR0041 "Taxes"
		#define STR0042 "Tax &Records"
		#define STR0043 "&Details "
		#define STR0044 "Prefix "
		#define STR0045 "Number"
		#define STR0046 "Order"
		#define STR0047 "Maturity"
		#define STR0048 "T. Note Value"
		#define STR0049 "Class"
		#define STR0050 "IRRF"
		#define STR0051 "ISS"
		#define STR0052 "Currency"
		#define STR0053 "Record."
		#define STR0054 "Expenses"
		#define STR0055 "FTR: "
		#define STR0056 "Show Entries       ?"
		#define STR0057 "Join Entries       ?"
		#define STR0058 "Check Quotation    ?"
		#define STR0059 "Apply Adjustment   ?"
		#define STR0060 "Add Binding     ?"
		#define STR0061 "Online Entries     ?"
		#define STR0062 "Consider P.C. Brch.?"
		#define STR0063 "Triangle Operation?"
		#define STR0064 "Invoice per Diff. ?"
		#define STR0065 "Yes"
		#define STR0066 "No"
		#define STR0067 "Please wait... "
		#define STR0068 "Saving Invoice...  "
		#define STR0069 "Run `Details` to calculate costs and taxes...        "
		#define STR0070 "Run Details...     "
		#define STR0071 "Attention! "
		#define STR0072 "To Update gross value, run Details..."
		#define STR0073 "Please wait...    "
		#define STR0074 "Apportioning costs  " + CHR ( 10 ) + CHR ( 13 ) + "Recalculanting taxes and totals..."
		#define STR0075 "Phone : "
		#define STR0076 "Fax Number: "
		#define STR0077 "Contact :  "
		#define STR0078 "Integration Petty Cash"
		#define STR0079 "Cash "
		#define STR0080 "Beneficiary"
		#define STR0081 "Value"
		#define STR0082 "Advance Number "
		#define STR0083 "History"
		#define STR0084 "Advances"
		#define STR0085 "Do you want to transfer remaining balance to Petty Cash?"
		#define STR0086 "Advance with remaining balance"
		#define STR0087 "Rate "
		#define STR0088 "Update currency file"
		#define STR0089 "Freight Included"
		#define STR0090 "Perc. Freight"
		#define STR0091 "Yes"
		#define STR0092 "No"
		#define STR0093 "Import"
		#define STR0094 "Do you want to classify Import Invoices?"
		#define STR0095 "Consider supplier in purchase order"
		#define STR0096 "This is not of a Purchase type invoice"
		#define STR0097 "Correlative No."
		#define STR0098 " not entered, confirm?"
		#define STR0099 "Select a valid type of invoice: N = Normal or B = Processing"
		#define STR0100 "There is a closed production order for some item. Please cancel de production for de PO.: "
		#define STR0101 "Invoive from Importation Process"
		#define STR0102 "Process:"
		#define STR0103 "Do you want to generaly Conduce?"
		#define STR0104 "Projects Management - <F10> "
		#define STR0105 "Invoice Loading"
		#define STR0106 "Selecting "
		#define STR0107 "Preparing "
		#define STR0108 " of Purchase"
		#define STR0109 "Close"
		#define STR0110 "Value"
		#define STR0111 "History"
		#define STR0112 "Value in"
		#define STR0113 "Write-off Details"
		#define STR0114 "Check"
		#define STR0115 "Status"
		#define STR0116 "Dep. in"
		#define STR0117 "Compensation"
		#define STR0118 "Used in po"
		#define STR0119 "Credited in"
		#define STR0120 "Rejected in"
		#define STR0121 "Unknown"
		#define STR0122 "Details"
		#define STR0123 "Financial Debt:"
		#define STR0124 "Credited:"
		#define STR0125 "Debit"
		#define STR0126 "No debit"
		#define STR0127 "Debited in"
		#define STR0128 "Overdue:"
		#define STR0129 "Falling due:"
		#define STR0130 "Debited:"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Número Da Factura", "Numero da NF" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Série da factura ", "Serie da NF " )
		#define STR0003 "Fornecedor  "
		#define STR0004 "Pesquisar"
		#define STR0005 "Visualizar"
		#define STR0006 "Incluir"
		#define STR0007 "Classificar"
		#define STR0008 "Excluir"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Notas Fiscais De Entrada", "Notas Fiscais de Entrada" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Factura De Entrada De Mercadorias", "Nota de Entrada de Mercadorias" )
		#define STR0011 "Tipo"
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Formulário próprio", "Formulário Próprio" )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Factura", "Nota Fiscal" )
		#define STR0014 "Série"
		#define STR0015 "Data"
		#define STR0016 "Cliente   "
		#define STR0017 "Fornecedor"
		#define STR0018 "Conhecimento :"
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Tipo De Documento", "Tipo de Documento" )
		#define STR0020 "Cliente: "
		#define STR0021 "Fornecedor: "
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Data De Entrada:", "Dt Entr:" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Total Da Factura", "Total da Nota" )
		#define STR0024 "Fornecedor"
		#define STR0025 "Cliente   "
		#define STR0026 "Cliente: "
		#define STR0027 "Fornecedor"
		#define STR0028 "Fornecedor: "
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Dados contabeis financeiros", "Dados Contábeis Financeiros" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Data De Contabilização", "Data Contabilização" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Condições De Pagamento", "Cond. de Pagto" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Pedidos De Compras", "Pedidos de Compras" )
		#define STR0033 "Loja"
		#define STR0034 "Pedido"
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Elemento", "Item" )
		#define STR0036 "Saldo"
		#define STR0037 "Entrega"
		#define STR0038 "Descrição"
		#define STR0039 "Tipo"
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Totais gerais", "Totais &Gerais" )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "&impostos", "&Impostos" )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Livros fiscais", "Livros &Fiscais" )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "&detalhes", "&Detalhes" )
		#define STR0044 "Prefixo"
		#define STR0045 "Número"
		#define STR0046 "Ordem"
		#define STR0047 "Vencimento"
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Valor Do Duplicado", "Vl. Duplicata" )
		#define STR0049 "Natureza"
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "IRS", "IRRF" )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Segurança social", "ISS" )
		#define STR0052 "Moeda"
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Registo.", "Registro." )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Despesas", "&Despesas" )
		#define STR0055 "Rut: "
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "Mostrar Lançamentos?", "Mostra Lançamentos?" )
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Reunir Lançamentos?", "Aglut. Lançamentos?" )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Verificar cotação    ?", "Verif. Cotação    ?" )
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Aplicar re-acordo  ?", "Aplicar Reajuste  ?" )
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Incluir ligação   ?", "Incluir Ligação   ?" )
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Movimento On-line?", "Lançamento On-Line?" )
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "Consid. filial pc  ?", "Consd. Filial PC  ?" )
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "O. p. triangular  ?", "O. P. Triangular  ?" )
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "Número fiscal por dif. ?", "N.Fiscal por Dif. ?" )
		#define STR0065 "Sim"
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "Não", "Nao" )
		#define STR0067 "Por favor, aguarde..."
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "A Gravar Notas Fiscais...", "Gravando N.Fiscais..." )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", 'Presione "detalhes" para calcular costos e impuestos...', 'Presione "Detalhes" para calcular costos e impuestos...' )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Executar Detalhes...", "Ejecutar Detalhes..." )
		#define STR0071 "Atenção! "
		#define STR0072 If( cPaisLoc $ "ANG|PTG", 'pAra actualizar o valor bruto, executar "detalhes"...', 'Para atualizar o valor bruto, executar "Detalhes"...' )
		#define STR0073 "Por favor aguarde..."
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Rateando custos " + chr ( 10 ) + chr ( 13 ) + "recalculando impostos e totais...", "Rateando custos " + CHR ( 10 ) + CHR ( 13 ) + "Recalculando impostos e totais..." )
		#define STR0075 "Tel. : "
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Fax : ", "FAX : " )
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "Contacto : ", "Contato : " )
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "Integração da caixa", "Integração caja chica" )
		#define STR0079 "Caixa "
		#define STR0080 "Beneficiado"
		#define STR0081 "Valor"
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Número de anticipo ", "Nro. de Anticipo " )
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "Histórico", "Historico" )
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Anticipo", "Anticipos" )
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "Deseja Transferir O Saldo Restante Para A Cajá Chica?", "Deseja transferir o saldo remanente para a Caja Chica?" )
		#define STR0086 If( cPaisLoc $ "ANG|PTG", "Anticipo com saldo restante", "Anticipo com saldo remanente" )
		#define STR0087 "Taxa "
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "A actualizar o ficheiro de moedas", "Atualizar arquivo de moedas" )
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "Frete Incluído", "Frete Incluido" )
		#define STR0090 "Perc. Frete"
		#define STR0091 "Sim"
		#define STR0092 "Não"
		#define STR0093 "Importação"
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Deseja Classificar As Notas Fiscais De Importação?", "Deseja classificar Notas Fiscais de Importacao?" )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Considerar o fornecedor no pedido de compras", "Considera fornecedor no pedido de compras" )
		#define STR0096 If( cPaisLoc $ "ANG|PTG", "Esta Factura Não é De Compra", "Esta Fatura nao e de Compra" )
		#define STR0097 If( cPaisLoc $ "ANG|PTG", "Número Correlativo", "Nro Correlativo" )
		#define STR0098 " em branco, confirma?"
		#define STR0099 If( cPaisLoc $ "ANG|PTG", "Seleccione Um Tipo De Nota Válido: N = Normal Ou B = Beneficiação", "Selecione um tipo de nota valido: N = Normal ou B = Beneficiamento" )
		#define STR0100 If( cPaisLoc $ "ANG|PTG", "Existe uma ordem de produção encerrada para algum item. cancele a produção da op.: ", "Existe uma order de producao encerrada para algum item. Cancele a producao da OP.: " )
		#define STR0101 If( cPaisLoc $ "ANG|PTG", "Notas Fiscais Do Proceso De Importação", "Notas Fiscais do Proceso de Importacao" )
		#define STR0102 "Processo:"
		#define STR0103 If( cPaisLoc $ "ANG|PTG", "Deseja Criar Uma Guia De Despacho?", "Deseja gerar Guia de Despacho?" )
		#define STR0104 If( cPaisLoc $ "ANG|PTG", "Gestão de projectos - <f10> ", "Gerenciamento de Projetos - <F10> " )
		#define STR0105 If( cPaisLoc $ "ANG|PTG", "A Carrregar A Factura", "Carrregando a Nota Fiscal" )
		#define STR0106 If( cPaisLoc $ "ANG|PTG", "A seleccionar ", "Selecionando " )
		#define STR0107 If( cPaisLoc $ "ANG|PTG", "A preparar ", "Preparando " )
		#define STR0108 If( cPaisLoc $ "ANG|PTG", " De Compras", " de Compras" )
		#define STR0109 "Fechar"
		#define STR0110 "Valor"
		#define STR0111 "Histórico"
		#define STR0112 "Valor em"
		#define STR0113 "Detalhes da Baixa"
		#define STR0114 "Cheque"
		#define STR0115 "Situacao"
		#define STR0116 "Dep. em"
		#define STR0117 "Compensação"
		#define STR0118 "Usado em op"
		#define STR0119 "Creditado em"
		#define STR0120 "Rejeitado em"
		#define STR0121 "Desconhecida"
		#define STR0122 "Detalhes"
		#define STR0123 "Dívida financeira: "
		#define STR0124 "Creditado: "
		#define STR0125 "Débito"
		#define STR0126 "Sem debitar "
		#define STR0127 "Debitado em "
		#define STR0128 "Vencido: "
		#define STR0129 "A vencer: "
		#define STR0130 "Debitado: "
	#endif
#endif
