#ifdef SPANISH
	#define STR0001 "Versión no se informó en el archivo del Adapter."
	#define STR0002 "¡Adapter no se encontró!"
	#define STR0003 "¡La versión del mensaje informado no se implementó!"
	#define STR0004 "Actualice el UPDINT01.prw para utilizar el log"
	#define STR0005 "Versión de la orden de producción incompatible."
	#define STR0006 "Las versiones compatibles son: 2.000"
	#define STR0007 "Error en el parser."
	#define STR0008 "El evento es obligatorio"
	#define STR0009 "El código del ProductionOrderUniqueID es obligatorio."
	#define STR0010 "No se encontró orden de producción para efectuar el borrado."
	#define STR0011 "Existe una orden de producción con la numeración '"
	#define STR0012 "'. Inclusión no permitida."
	#define STR0013 "Numeración de la orden de producción no válida."
	#define STR0014 "No se encontró orden de producción con la numeración '"
	#define STR0015 "'. Modificación no permitida."
	#define STR0016 "El código del producto es obligatorio."
	#define STR0017 "Cantidad de la orden de producción es obligatorio."
	#define STR0018 "Fecha inicial de la orden de producción informada en formato incorrecto. Utilice AAAA-MM-DD."
	#define STR0019 "Fecha inicial de la orden de producción es obligatoria."
	#define STR0020 "Fecha de entrega de la orden de producción informada en formato incorrecto. Utilice AAAA-MM-DD."
	#define STR0021 "Fecha de entrega de la orden de producción es obligatoria."
	#define STR0022 "'. Borrado no permitido."
	#define STR0023 "El evento informado no es válido. Utilice UPSERT o DELETE."
	#define STR0024 "Producto '"
	#define STR0025 "' no registrado."
	#define STR0026 "Fecha de emisión de la Orden de producción informada en formato incorrecto. Utilice AAAA-MM-DD."
	#define STR0027 "Orden de producción no encontrada en el DE/A. ->"
	#define STR0028 "es obligatorio."
	#define STR0029 "Orden de producción de la lista de materiales no pertenece a la orden de producción importada"
	#define STR0030 "Error en el parser."
	#define STR0031 "No es posible modificar las reservas de esta orden, pues se realizaron movimientos para la orden."
	#define STR0032 "Clase de valor no se registró."
	#define STR0033 "Código de la hacienda no se encontró."
	#define STR0034 "Código del cultivo no se encontró."
	#define STR0035 "Centro de costo no se encontró."
	#define STR0036 "Código del asunto fitosanitario no se encontró."
	#define STR0037 "No se permite informar sublotes diferentes para un mismo material."
#else
	#ifdef ENGLISH
		#define STR0001 "Version not entered in the adapter register."
		#define STR0002 "Adapter not found!"
		#define STR0003 "The version of the entered message was not implemented!"
		#define STR0004 "Update UPDINT01.prw to use the log"
		#define STR0005 "Version of production order not supported."
		#define STR0006 "The supported versions are: 2,000"
		#define STR0007 "Error in parser."
		#define STR0008 "The event is mandatory"
		#define STR0009 "Code ProductionOrderUniqueID is mandatory."
		#define STR0010 "No production order found to delete."
		#define STR0011 "There is already a production order with the number ‘"
		#define STR0012 "'. Inclusion not allowed."
		#define STR0013 "Production order number is invalid."
		#define STR0014 "No production order found with the number ‘"
		#define STR0015 "'. Editing not allowed."
		#define STR0016 "Product code is mandatory"
		#define STR0017 "Production order quantity is mandatory."
		#define STR0018 "Production order start date entered in incorrect format. Use YYYY-MM-DD."
		#define STR0019 "Production order start date is mandatory."
		#define STR0020 "Production order delivery date entered in incorrect format. Use YYYY-MM-DD."
		#define STR0021 "Production order delivery date is mandatory."
		#define STR0022 "'. Deletion not allowed."
		#define STR0023 "Event entered is not valid. Use UPSERT or DELETE."
		#define STR0024 "Product ‘"
		#define STR0025 "‘ not registered."
		#define STR0026 "Production order issue date entered in incorrect format. Use YYYY-MM-DD."
		#define STR0027 "Production order not found in FROM/TO. ->"
		#define STR0028 "is mandatory."
		#define STR0029 "Production order of material list does not belong to production order imported"
		#define STR0030 "Error in parser."
		#define STR0031 "Unable to change the allocations of this order, as transactions were made for this order."
		#define STR0032 "Value Class not registered. "
		#define STR0033 "Farm code not found."
		#define STR0034 "Culture code not found."
		#define STR0035 "Cost Center not found."
		#define STR0036 "Phytosanitary code not found."
		#define STR0037 "You cannot enter different sub-batches for the same material."
	#else
		#define STR0001 "Versão não informada no cadastro do adapter."
		#define STR0002 "Adapter não encontrado!"
		#define STR0003 "A versão da mensagem informada não foi implementada!"
		#define STR0004 "Atualize o UPDINT01.prw para utilizar o log"
		#define STR0005 "Versão da ordem de produção não suportada."
		#define STR0006 "As versões suportadas são: 2.000"
		#define STR0007 "Erro no parser."
		#define STR0008 "O evento é obrigatório"
		#define STR0009 "O código do ProductionOrderUniqueID é obrigatório."
		#define STR0010 "Não foi encontrada ordem de produção para efetuar a exclusão."
		#define STR0011 "Já existe uma ordem de produção com a numeração '"
		#define STR0012 "'. Inclusão não permitida."
		#define STR0013 "Numeração da ordem de produção inválida."
		#define STR0014 "Não foi encontrada ordem de produção com a numeração '"
		#define STR0015 "'. Alteração não permitida."
		#define STR0016 "O código do produto é obrigatório."
		#define STR0017 "Quantidade da ordem de produção é obrigatório."
		#define STR0018 "Data de início da Ordem de produção informada em formato incorreto. Utilize AAAA-MM-DD."
		#define STR0019 "Data de início da ordem de produção é obrigatório."
		#define STR0020 "Data de entrega da Ordem de produção informada em formato incorreto. Utilize AAAA-MM-DD."
		#define STR0021 "Data de entrega da ordem de produção é obrigatório."
		#define STR0022 "'. Exclusão não permitida."
		#define STR0023 "O evento informado é inválido. Utilize UPSERT ou DELETE."
		#define STR0024 "Produto '"
		#define STR0025 "' não cadastrado."
		#define STR0026 "Data de emissão da Ordem de produção informada em formato incorreto. Utilize AAAA-MM-DD."
		#define STR0027 "Ordem de produção não encontrada no DE/PARA. -> "
		#define STR0028 "é obrigatório."
		#define STR0029 "Ordem de produção da lista de materiais não pertence a ordem de produção importada"
		#define STR0030 "Erro no parser."
		#define STR0031 "Não é possível alterar os empenhos desta ordem, pois já foram realizadas movimentações para a ordem."
		#define STR0032 "Classe de valor não cadastrada. "
		#define STR0033 "Código da fazenda não encontrado."
		#define STR0034 "Código da cultura não encontrado."
		#define STR0035 "Centro de custo não encontrado."
		#define STR0036 "Código da fitossanidade não encontrado."
		#define STR0037 "Não é permitido informar sub-lotes diferentes para um mesmo material."
	#endif
#endif
