#ifdef SPANISH
	#define STR0001 "Libros fiscales"
	#define STR0002 "Preparando informacion para el libro de compras"
	#define STR0003 "Tipo de fact."
	#define STR0004 "NIT del proveedor"
	#define STR0005 "Nombre o Razon social"
	#define STR0006 "Nº de Factura"
	#define STR0007 "Nº de DUE"
	#define STR0008 "Numero de autorizacion"
	#define STR0009 "Fecha de la factura"
	#define STR0010 "Importe total de venta"
	#define STR0011 "Importe ICE/ IEHD/ Tasas"
	#define STR0012 "Ventas gravadas a Tasa cero"
	#define STR0013 "Credito fiscal"
	#define STR0014 "Importe base para credito fiscal"
	#define STR0015 "Codigo de control"
	#define STR0016 "Preparando la información para el libro de ventas"
	#define STR0017 "Importe base para debito fiscal"
	#define STR0018 "Debito fiscal"
	#define STR0019 "Estado"
	#define STR0020 "Libro de"
	#define STR0021 "Compras"
	#define STR0022 "Ventas"
	#define STR0023 "Nombre o Razon social"
	#define STR0024 "Sucursal"
	#define STR0025 "Direccion"
	#define STR0026 "Periodo"
	#define STR0027 "Presentacion"
	#define STR0028 "Folio"
	#define STR0029 "Nombre completo del responsable"
	#define STR0030 "Impresion del libro fiscal (compras/ventas)"
	#define STR0031 "Total"
	#define STR0032 "Impresion anulada por el usuario"
	#define STR0033 "Notas de credito/debito"
	#define STR0034 "Ano"
	#define STR0035 "Mes"
	#define STR0036 "Nº"
	#define STR0037 "Fecha nota de credito - debito"
	#define STR0038 "Nº de Nota de credito - debito"
	#define STR0039 "Nº de Autorizacion"
	#define STR0040 "NIT/CI Cliente"
	#define STR0041 "Nombre o Razon social cliente"
	#define STR0042 "Valor total de la Devolucion o Rescision"
	#define STR0043 "Credito fiscal"
	#define STR0044 "Codigo de controle de la Nota de credito - debito"
	#define STR0045 "Fecha factura original"
	#define STR0046 "Nº Factura original"
	#define STR0047 "Nº de Autorizacion factura original"
	#define STR0048 "Importe total factura original"
	#define STR0049 "Solamente podra informarse un periodo de fechas dentro del mismo Mes/Ano correspondientes"
	#define STR0050 "Recibida"
	#define STR0051 "Efectuada"
	#define STR0052 "NIT Proveedor"
	#define STR0053 "Nombre o Razón social proveedor"
	#define STR0054 "Debito fiscal"
	#define STR0055 "Fecha de la factura o DUE"
	#define STR0056 "Nº de la Factura"
	#define STR0057 "Importe total de la compra"
	#define STR0058 "Importe no sujeto a credito fiscal"
	#define STR0059 "Subtotal"
	#define STR0060 "Descuentos bonificaciones y rebajas obtenidas"
	#define STR0061 "Exportaciones y operaciones exentas"
	#define STR0062 "Descuentos bonificaciones y rebajas otorgadas"
	#define STR0063 "ANULADA"
#else
	#ifdef ENGLISH
		#define STR0001 "Tax Records"
		#define STR0002 "Preparing information for purchase book"
		#define STR0003 "Invoice type"
		#define STR0004 "Supplier NIT"
		#define STR0005 "Name or company name"
		#define STR0006 "Invoice Number "
		#define STR0007 "DUE Number "
		#define STR0008 "Authorization number"
		#define STR0009 "Invoice date"
		#define STR0010 "Sales Total Value"
		#define STR0011 "Value ICE/ IEHD/ Rates"
		#define STR0012 "Sales Saved at Zero Rate"
		#define STR0013 "Tax credit"
		#define STR0014 "Base Value for Tax Credit"
		#define STR0015 "Control code"
		#define STR0016 "Preparing information for sales book"
		#define STR0017 "Base Value for Tax Debit"
		#define STR0018 "Tax debit"
		#define STR0019 "State"
		#define STR0020 "Purchase"
		#define STR0021 "Sales"
		#define STR0022 "Book"
		#define STR0023 "Name or company name"
		#define STR0024 "Branch"
		#define STR0025 "Address"
		#define STR0026 "Period"
		#define STR0027 "Presentation"
		#define STR0028 "Folio"
		#define STR0029 "Full name of person in charge"
		#define STR0030 "Tax book print (purchases/sales)"
		#define STR0031 "Total"
		#define STR0032 "Print canceled by the user"
		#define STR0033 "Credit/Debit Notes"
		#define STR0034 "Year"
		#define STR0035 "Month"
		#define STR0036 "No."
		#define STR0037 "Credit - Debit Note Date"
		#define STR0038 "Credit - Debit Note Number"
		#define STR0039 "Authorization Number"
		#define STR0040 "NIT/CI Customer"
		#define STR0041 "Customer Name or Company Name"
		#define STR0042 "Total Value of Return or Termination"
		#define STR0043 "Tax credit"
		#define STR0044 "Credit - Debit Note Control Code"
		#define STR0045 "Original Invoice Date"
		#define STR0046 "Original Invoice Number"
		#define STR0047 "Original Invoice Authorization Number"
		#define STR0048 "Original Invoice Total Value"
		#define STR0049 "You can only enter a dates period within the same corresponding Month/Year"
		#define STR0050 "Received"
		#define STR0051 "Performed"
		#define STR0052 "Supplier NIT"
		#define STR0053 "Provider Name or Company Name"
		#define STR0054 "Tax Debit"
		#define STR0055 "Invoice Date or DUE"
		#define STR0056 "Invoice Number"
		#define STR0057 "Purchase Total Value"
		#define STR0058 "Value not Subject to Tax Credit"
		#define STR0059 "Subtotal"
		#define STR0060 "Obtained Discount Bonus and Deductions"
		#define STR0061 "Exempt Exports and Operations"
		#define STR0062 "Granted Discount Bonus and Deductions"
		#define STR0063 "NULL"
	#else
		#define STR0001 "Livros fiscais"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "A preparar as informações para o livro de compras", "Preparando as informacoes para o livro de compras" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Tipo de factura", "Tipo de fatura" )
		#define STR0004 "NIT do fornecedor"
		#define STR0005 "Nome ou Razão Social"
		#define STR0006 "Nº De Fatura"
		#define STR0007 "Nº de DUE"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Número de autorização", "Numero de autorizacao" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Data da factura", "Data da fatura" )
		#define STR0010 "Valor Total de Venda"
		#define STR0011 "Valor ICE/ IEHD/ Taxas"
		#define STR0012 "Vendas Gravadas a Taxa Zero"
		#define STR0013 "Credito Fiscal"
		#define STR0014 "Valor Base para Crédito Fiscal"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Código de controlo", "Codigo de controle" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "A preparar as informações para o livro de vendas", "Preparando as informacoes para o livro de vendas" )
		#define STR0017 "Valor Base para Debito Fiscal"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Débito fiscal", "Debito fiscal" )
		#define STR0019 "Estado"
		#define STR0020 "Livro de"
		#define STR0021 "Compras"
		#define STR0022 "Vendas"
		#define STR0023 "Nome ou Razao Social"
		#define STR0024 "Filial"
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Morada", "Endereco" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Período", "Periodo" )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Apresentação", "Apresentacao" )
		#define STR0028 "Folio"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Nome completo do responsável", "Nome completo do responsavel" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Impressão do livro fiscal (compras/vendas)", "Impressao do livro fiscal (compras/vendas)" )
		#define STR0031 "Total"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Impressão cancelada pelo utilizador", "Impressao cancelada pelo usuario" )
		#define STR0033 "Notas de Crédito/Débito"
		#define STR0034 "Ano"
		#define STR0035 "Mês"
		#define STR0036 "Nº"
		#define STR0037 "Data Nota de Crédito - Débito"
		#define STR0038 "Nº de Nota de Crédito - Débito"
		#define STR0039 "Nº de Autorização"
		#define STR0040 "NIT/CI Cliente"
		#define STR0041 "Nombre ou Razão Social Cliente"
		#define STR0042 "Valor total da Devolução ou Rescisão"
		#define STR0043 "Crédito Fiscal"
		#define STR0044 "Código de Controle da Nota de Crédito - Débito"
		#define STR0045 "Data Fatura Original"
		#define STR0046 "Nº Fatura Original"
		#define STR0047 "Nº de Autorização Fatura Original"
		#define STR0048 "Valor Total Fatura Original"
		#define STR0049 "Somente poderá ser informado um período de datas dentro do mesmo Mês/Ano correspondentes"
		#define STR0050 "Recebida"
		#define STR0051 "Efetuada"
		#define STR0052 "NIT Fornecedor"
		#define STR0053 "Nombre ou Razão Social Fornecedor"
		#define STR0054 "Débito Fiscal"
		#define STR0055 "Data da Fatura ou DUE"
		#define STR0056 "Nº da Fatura"
		#define STR0057 "Valor Total da Compra"
		#define STR0058 "Valor Não Sujeito a Crédito Fiscal"
		#define STR0059 "Subtotal"
		#define STR0060 "Descontos Bonificações e Abatimentos Obtidos"
		#define STR0061 "Exportações e Operações Isentas"
		#define STR0062 "Descontos Bonificações e Abatimentos Concedidos"
		#define STR0063 "ANULADA"
	#endif
#endif
