#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Ocurrencias por Empleado"
	#define STR0007 "Ocurrencias"
	#define STR0008 "Clientes"
	#define STR0009 "Rellena la fecha de la ocurrencia."
	#define STR0010 "Rellena la Gravedad"
	#define STR0011 "La fecha de la Ocurrencia no puede ser mayor que la Fecha Actual."
	#define STR0012 "¡ATENCION!"
	#define STR0013 "Coloque una Fecha igual o menor que la Fecha Actual."
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Insert"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Occurrence per Employee"
		#define STR0007 "Occorrences"
		#define STR0008 "Customers"
		#define STR0009 "Inform Occurrence Date."
		#define STR0010 "Inform Seriousness."
		#define STR0011 "Occurrence Date cannot be later than the Current Date."
		#define STR0012 "WARNING!"
		#define STR0013 "Enter a date equal to lower than Current Date."
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Ocorrencias Por Empregado", "Ocorrencias Por Funcionario" )
		#define STR0007 "Ocorrências"
		#define STR0008 "Clientes"
		#define STR0009 "Preencha a Data da Ocorrência"
		#define STR0010 "Preencha a Gravidade"
		#define STR0011 "A Data da Ocorrência não pode ser maior que a Data Atual."
		#define STR0012 "ATENÇÃO!"
		#define STR0013 "Colocar uma Data igual ou menor que a Data Atual."
	#endif
#endif
