#ifdef SPANISH
	#define STR0001 "Brigadas"
	#define STR0002 "BRIGADA"
	#define STR0003 "Clientes"
	#define STR0004 "Organigrama"
	#define STR0005 "Investigar"
	#define STR0006 "Visualizar"
	#define STR0007 "Incluir"
	#define STR0008 "Modificar"
	#define STR0009 "Borrar"
	#define STR0010 "Copiar"
	#define STR0011 "Visualización del Brigadista"
	#define STR0012 "Solicitud de Reserva de Capacitaciones"
	#define STR0013 "Solicitud"
	#define STR0014 "Ningún brigadista seleccionado."
	#define STR0015 "Leyenda - Brigadista"
	#define STR0016 "Incluir Brigadista"
	#define STR0017 "Modificar Brigadista"
	#define STR0018 "Borrar Brigadista"
	#define STR0019 "Aguarde..."
	#define STR0020 "Cargando Información..."
	#define STR0021 "Cargando Estructura..."
	#define STR0022 "Exámenes"
	#define STR0023 "Entrenamientos"
	#define STR0024 "Brigadista"
	#define STR0025 "Confirmar"
	#define STR0026 "Cancelar"
	#define STR0027 "Leyenda"
	#define STR0028 "Examen"
	#define STR0029 "Descripción"
	#define STR0030 "Fc. Prog."
	#define STR0031 "Fc. Resul."
	#define STR0032 "Entrenamiento"
	#define STR0033 "Código Curso"
	#define STR0034 "Desc. Curso"
	#define STR0035 "Nota"
	#define STR0036 "% Presencia"
	#define STR0037 "Informe al menos un brigadista para la generación del entrenam. o haga clic en el botón cancelar para salir"
	#define STR0038 "Brigadista ya agregado a la Brigada."
	#define STR0039 "Informar un código diferente."
	#define STR0040 "¿Realmente desea restaurar el participante?"
	#define STR0041 "Brigadista Activo"
	#define STR0042 "Brigadista Inactivo"
	#define STR0043 "No Realizado - A vencer"
	#define STR0044 "No Realizado - Vencido"
	#define STR0045 "Realizado"
	#define STR0046 "No Realizado"
	#define STR0047 "Realizado - Con Fecha Expirada"
	#define STR0048 "Inclusión del Brigadista"
	#define STR0049 "Modificación del Brigadista"
	#define STR0050 "¿Desea realmente borrar al participante?"
	#define STR0051 "ATENCIÓN"
	#define STR0052 "No es posible borrar brigadista pues él posee subordinados."
	#define STR0053 "Borre sus subordinados primero."
	#define STR0054 "Fecha no puede ser menor a la vigencia de la brigada"
	#define STR0055 "Informe una fecha válida entre la vigencia"
	#define STR0056 "Fecha no puede ser mayor a la vigencia de la brigada"
	#define STR0057 "Matrícula"
	#define STR0058 "Nombre"
	#define STR0059 "Función"
	#define STR0060 "Generar entrenamientos"
	#define STR0061 "Informe el entrentamiento que desea generar"
	#define STR0062 "Curso"
	#define STR0063 "Vacantes Restantes"
	#define STR0064 "Entrenamiento ya finalizado"
	#define STR0065 "Informe un entrenamiento/curso no finalizado"
	#define STR0066 "Número de brigadistas mayor al permitido"
	#define STR0067 "Informe un número menor de brigadistas que realizarán el entrenamiento"
	#define STR0068 "Restaurar Brigadista"
	#define STR0069 "Grabar"
	#define STR0070 "Grabar modificaciones ya realizadas"
	#define STR0071 "No es posible incluir subordinados a un brigadista excluido."
	#define STR0072 "Restaure el brigadista o seleccione otro."
	#define STR0073 "El(los) siguiente(s) empleado(s) esta(n) sin cargo: "
	#define STR0074 "Favor infomar cargo(s) para la(s) funcion(es) del(los) empleado(s)"
	#define STR0075 "Este Empleado esta relacionado a una o mas brigadas, ¿desea despedirlo?"
	#define STR0076 "Sucursal Matr."
#else
	#ifdef ENGLISH
		#define STR0001 "Brigades"
		#define STR0002 "BRIGADE"
		#define STR0003 "Customers"
		#define STR0004 "Organization Chart"
		#define STR0005 "Search"
		#define STR0006 "View"
		#define STR0007 "Add"
		#define STR0008 "Change"
		#define STR0009 "Delete"
		#define STR0010 "Copy"
		#define STR0011 "Brigade Member View"
		#define STR0012 "Request for Training Reservation"
		#define STR0013 "Request"
		#define STR0014 "No brigade member selected."
		#define STR0015 "Caption - Brigade Member"
		#define STR0016 "Add Brigade Member"
		#define STR0017 "Change Brigade Member"
		#define STR0018 "Delete Brigade Member"
		#define STR0019 "Wait..."
		#define STR0020 "Loading Information..."
		#define STR0021 "Loading Structure..."
		#define STR0022 "Examinations"
		#define STR0023 "Training"
		#define STR0024 "Brigade Member"
		#define STR0025 "Confirm"
		#define STR0026 "Cancel"
		#define STR0027 "Caption"
		#define STR0028 "Examination"
		#define STR0029 "Description"
		#define STR0030 "Sch. Dt"
		#define STR0031 "Resul. Dt"
		#define STR0032 "Training"
		#define STR0033 "Course Code"
		#define STR0034 "Course Desc."
		#define STR0035 "Invoice"
		#define STR0036 "Presence %"
		#define STR0037 "Enter at least one brigade member for training generation or click Cancel to exit"
		#define STR0038 "Brigade member already added to Brigade."
		#define STR0039 "Enter a different code."
		#define STR0040 "Do you really want to restore the participant?"
		#define STR0041 "Active Fire Brigade Member"
		#define STR0042 "Inactive Fire Brigade Member"
		#define STR0043 "Not Performed - To Fall Due"
		#define STR0044 "Not Performed - Due"
		#define STR0045 "Performed"
		#define STR0046 "Not Performed"
		#define STR0047 "Performed - With Expired Date"
		#define STR0048 "Brigade Member Inclusion"
		#define STR0049 "Brigade Member Change"
		#define STR0050 "Do you really want to delete the participant?"
		#define STR0051 "ATTENTION"
		#define STR0052 "You cannot delete the brigade member because he has subordinates."
		#define STR0053 "Delete the subordinates first."
		#define STR0054 "Date cannot be before the brigade validity"
		#define STR0055 "Enter a valid date between the validity"
		#define STR0056 "Date cannot be after the brigade validity"
		#define STR0057 "Registration"
		#define STR0058 "Name"
		#define STR0059 "Function"
		#define STR0060 "Generate Training"
		#define STR0061 "Enter the training you want to generate"
		#define STR0062 "Course"
		#define STR0063 "Remaining Vacancies"
		#define STR0064 "Training already finished"
		#define STR0065 "Enter a training/course not finished"
		#define STR0066 "Number of brigade members higher than the one allowed"
		#define STR0067 "Enter a lower number of brigade members that did the training"
		#define STR0068 "Restore Fire Brigade Member"
		#define STR0069 "Save"
		#define STR0070 "Save changes made"
		#define STR0071 "You cannot include subordinates to a deleted fire brigade member."
		#define STR0072 "Restore the fire brigade member or select another."
		#define STR0073 "The following employee(s) lack a position: "
		#define STR0074 "Please enter position(s) for the function(s) of the employee(s)"
		#define STR0075 "This employee is related to one or more brigades, do you want to dismiss the employee?"
		#define STR0076 "H. Off. Branch"
	#else
		#define STR0001 "Brigadas"
		#define STR0002 "BRIGADA"
		#define STR0003 "Clientes"
		#define STR0004 "Organograma"
		#define STR0005 "Pesquisar"
		#define STR0006 "Visualizar"
		#define STR0007 "Incluir"
		#define STR0008 "Alterar"
		#define STR0009 "Excluir"
		#define STR0010 "Copiar"
		#define STR0011 "Visualização do Brigadista"
		#define STR0012 "Solicitação de Reserva de Treinamentos"
		#define STR0013 "Solicitação"
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Nenhum brigadista seleccionado.", "Nenhum brigadista selecionado." )
		#define STR0015 "Legenda - Brigadista"
		#define STR0016 "Incluir Brigadista"
		#define STR0017 "Alterar Brigadista"
		#define STR0018 "Excluir Brigadista"
		#define STR0019 "Aguarde..."
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "A carregar informações...", "Carregando Informações..." )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "A carregar estrutura...", "Carregando Estrutura..." )
		#define STR0022 "Exames"
		#define STR0023 "Treinamentos"
		#define STR0024 "Brigadista"
		#define STR0025 "Confirmar"
		#define STR0026 "Cancelar"
		#define STR0027 "Legenda"
		#define STR0028 "Exame"
		#define STR0029 "Descrição"
		#define STR0030 "Dt. Prog."
		#define STR0031 "Dt. Resul."
		#define STR0032 "Treinamento"
		#define STR0033 "Código Curso"
		#define STR0034 "Desc. Curso"
		#define STR0035 "Nota"
		#define STR0036 "% Presença"
		#define STR0037 "Informe ao menos um brigadista para geração do treinamento ou clique no botão cancelar para sair"
		#define STR0038 "Brigadista já adicionado a Brigada."
		#define STR0039 "Informar um código diferente."
		#define STR0040 "Deseja realmente restaurar o participante?"
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Brigadista Activo", "Brigadista Ativo" )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Brigadista Inactivo", "Brigadista Inativo" )
		#define STR0043 "Não Realizado - A vencer"
		#define STR0044 "Não Realizado - Vencido"
		#define STR0045 "Realizado"
		#define STR0046 "Não Realizado"
		#define STR0047 "Realizado - Com Data Expirada"
		#define STR0048 "Inclusão do Brigadista"
		#define STR0049 "Alteração do Brigadista"
		#define STR0050 "Deseja realmente excluir o participante?"
		#define STR0051 "ATENÇÃO"
		#define STR0052 "Não é possível excluir brigadista pois ele possui subordinados."
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Exclua seus subordinados primeiramente.", "Exclua seus subordinádos primeiramente." )
		#define STR0054 "Data não pode ser menor que a vigência da brigada"
		#define STR0055 "Informe uma data válida entre a vigência"
		#define STR0056 "Data não pode ser maior que a vigência da brigada"
		#define STR0057 "Matrícula"
		#define STR0058 "Nome"
		#define STR0059 "Função"
		#define STR0060 "Gerar Treinamentos"
		#define STR0061 "Informe o treinamento que deseja gerar"
		#define STR0062 "Curso"
		#define STR0063 "Vagas Restantes"
		#define STR0064 "Treinamento já finalizado"
		#define STR0065 "Informe um treinamento/curso não finalizado"
		#define STR0066 "Número de brigadistas maior que o permitido"
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Informe um número menor de brigadistas que farão o treinamento", "Informe um número menor de brigadistas que irão fazer o treinamento" )
		#define STR0068 "Restaurar Brigadista"
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Gravar", "Salvar" )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Gravar alterações já realizadas", "Salvar alterações já realizadas" )
		#define STR0071 "Não é possível incluir subordinados a um brigadista excluído."
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Restaure o brigadista ou seleccione outro.", "Restaure o brigadista ou selecione outro." )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "O(s) seguinte(s) colaborador(es) está(ão) sem cargo: ", "O(s) seguinte(s) funcionário(s) está(ão) sem cargo: " )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Por favor, infomar cargo(s) para a(s) função(ões) do(s) colaborador(es)", "Favor infomar cargo(s) para a(s) função(ões) do(s) funcionário(s)" )
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Este colaborador está relacionado a uma ou mais brigadas. Deseja demiti-lo?", "Este funcionário está relacionado a uma ou mais brigadas, deseja demiti-lo?" )
		#define STR0076 "Filial Matr."
	#endif
#endif
