#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "EPI"
	#define STR0004 "Provedor de EPI"
	#define STR0005 "Proveedor"
	#define STR0006 "Nombre"
	#define STR0007 "Tienda"
	#define STR0008 "Direccion"
	#define STR0009 "Ciudad"
	#define STR0010 "CP"
	#define STR0011 "Telefono"
	#define STR0012 "Clientes"
	#define STR0013 "Este dato no podra borrarse, pues este Epi consta en el archivo de Epi vs. Funcion"
	#define STR0014 "Este dato no podra borrarse, pues este Epi consta en el archivo de Epi vs. "
	#define STR0015 "Centro de Costo"
	#define STR0016 "ATENCION"
	#define STR0017 "Este dato no podrá borrarse, pues este Epi consta en los Epi entregados "
	#define STR0018 "de algun empleado."
	#define STR0019 "Autorizados"
	#define STR0020 "La fecha de evaluacio de EPI debe ser menor o igual a la fecha de vencimiento."
	#define STR0021 "Favor informar la cantidad de dias de utilizacion del EPI."
	#define STR0022 "Por favor informe el tipo de Durabilidad del EPI."
	#define STR0023 "Buscar C.A. en el MTE"
	#define STR0024 "MTE"
	#define STR0025 "No se podra modificar este Epi, pues se lo entrego a algun empleado."
	#define STR0026 "Este Epi se entrego empleados con el C.A. en blanco."
	#define STR0027 " ¿Desea actualizar el C.A. en los registros con lo que se relleno en seguida?"
	#define STR0028 "Busca Epi"
	#define STR0029 "Objeto de Busqueda"
	#define STR0030 "Valor por buscar"
	#define STR0031 "Localizar Anterior"
	#define STR0032 "Buscar / Proximo"
	#define STR0033 "Codigo"
	#define STR0034 "No se localizaron EPI con este codigo."
	#define STR0035 "Descripcion"
	#define STR0036 "No se localizaron EPI con esta descripcion."
	#define STR0037 "Nr. C.A."
	#define STR0038 "No se localizaron EPI con este Certificado de Aprobacion."
	#define STR0039 "Fecha Venc. C.A."
	#define STR0040 "No se localizaron EPI con esta fecha de vencimiento para el Certificado de Aprobacion."
	#define STR0041 "EPI  -  Equipos de Proteccion Individual"
	#define STR0042 "El campo '¿Generico ?' está en blanco."
	#define STR0043 "Complete el campo para continuar los registros."
	#define STR0044 "Grupo de EPI"
	#define STR0045 "El EPI informado es el mismo EPI generico."
	#define STR0046 "Informe un EPI secundario diferente para ser vinculado al EPI: "
	#define STR0047 "El EPI informado ya se vinculo a ese proveedor."
	#define STR0048 "No hay EPI generico vinculado al proveedor."
	#define STR0049 "Seleccion los EPI secundarios"
	#define STR0050 "EPI generico:"
	#define STR0051 "Indique para cual EPI generico vinculado al proveedor se desea vincular los EPI secundarios."
	#define STR0052 "Epi"
	#define STR0053 "Ok"
	#define STR0054 "No se informo el codigo del EPI."
	#define STR0055 "No se informo el numero del certificado de aprobacion."
	#define STR0056 "No se informo la fecha inicial del suministro del EPI para ese proveedor."
	#define STR0057 "Fecha de inicio superior a la fecha cierre del suministro del EPI."
	#define STR0058 "Informe una fecha igual o inferior a la fecha final."
	#define STR0059 "Fecha de finalizacion inferior a la fecha de inicio del suministro del EPI."
	#define STR0060 "Informe una fecha igual o superior a la fecha inicial."
	#define STR0061 "Ese es un EPI generico y tiene EPI secundarios vinculados. Desvincule los EPIs secundarios antes de borrarlo."
	#define STR0062 "El registro del EPI secundario no se puede modificar pues la fecha fin se informo."
	#define STR0063 "Informe el objeto de busqueda que desea para la busqueda. Opciones: Codigo, Descripcion, Num. C.A. y Fch. Vencto. C.A."
	#define STR0064 "Informe el codigo de acuerdo con el objeto de busqueda utilizado para buscar."
	#define STR0065 "Objeto de Busqueda"
	#define STR0066 "Valor por Buscar"
	#define STR0067 "Tarea"
	#define STR0068 "Atencion"
	#define STR0069 "Este EPI Generico ya tiene secundarios registrados."
	#define STR0070 "Primero se debe borrar los EPIs secundarios."
	#define STR0071 "EPI secundario ya registrado."
	#define STR0072 "Informe otro codigo de EPI u otro numero de CA."
	#define STR0073 "Este EPI ya está registrado como genérico."
	#define STR0074 "Por favor, infórmelo como genérico o informe otro EPI."
	#define STR0075 "Este EPI está registrado como no genérico."
	#define STR0076 "Por favor, infórmelo como no genérico o informe otro EPI."
	#define STR0077 "Generar XML eSocial"
	#define STR0078 "Inconsistencias de los equipamientos de protección"
	#define STR0079 "Los siguientes campos están vacíos/en cero o tienen inconsistencia con relación al formato estándar del eSocial:"
	#define STR0080 "Monitoreo de envío de eventos"
	#define STR0081 "Log de ocurrencias"
	#define STR0082 "Tabla de equipamientos de protección"
	#define STR0083 "Existen inconsistencias en el envío del registro al eSocial"
	#define STR0084 "¿Desea continuar, aun así?"
	#define STR0085 "Por favor, verifique las inconsistencias"
	#define STR0086 "EPI registrado con C.A. no vencido para este proveedor. ¿Desea registrar aún así?"
	#define STR0087 "Renovación de C.A."
	#define STR0088 "Para renovar el C.A. debe modificarse la fecha del registro original."
#else
	#ifdef ENGLISH
		#define STR0001 "Searhc"
		#define STR0002 "View"
		#define STR0003 "PPE"
		#define STR0004 "EPI vendor"
		#define STR0005 "Vendor"
		#define STR0006 "Name"
		#define STR0007 "Unit"
		#define STR0008 "Location"
		#define STR0009 "City"
		#define STR0010 "ZIP"
		#define STR0011 "Telephone"
		#define STR0012 "Customers"
		#define STR0013 "This data cannot be deleted, as this Ipe is on the Ipe x Function file"
		#define STR0014 "This data cannot be deleted, as this Ipe is on the register Ipe x  "
		#define STR0015 "Cost Center"
		#define STR0016 "ATTENTION"
		#define STR0017 "This data cannot be deleted, as this Ipe is within the Ipes delivered "
		#define STR0018 "of some employee."
		#define STR0019 "Members"
		#define STR0020 "IPE evaluation date must be before or the same as the due date."
		#define STR0021 "Please, indicate the number of days of use of IPE."
		#define STR0022 "Please, indicate the type of IPE Durability."
		#define STR0023 "Search C.A. in MTE"
		#define STR0024 "MTE"
		#define STR0025 "This PPE cannot be changed. It has already been given to an employee."
		#define STR0026 "This Ppe was already given to employees with blank C.A."
		#define STR0027 " Update C.A. in the entered records with which is entered next?"
		#define STR0028 "Search Ppe's"
		#define STR0029 "Search Object"
		#define STR0030 "Value to search"
		#define STR0031 "Find Previous"
		#define STR0032 "Search / Next"
		#define STR0033 "Code"
		#define STR0034 "No PPE's found with this code."
		#define STR0035 "Description"
		#define STR0036 "No PPE's found with this description."
		#define STR0037 "C.A. Nr."
		#define STR0038 "No PPE's found with this Certificate of Approval."
		#define STR0039 "A.C. Due Date"
		#define STR0040 "No PPE's found with this expiry date for the Certificate of Approval."
		#define STR0041 "PPEs  -  Personal Protective Equipment"
		#define STR0042 "The Generic? field is blank."
		#define STR0043 "Fill out the field to proceed with the registers."
		#define STR0044 "PPE Group"
		#define STR0045 "The PPE entered is the same as generic PPE."
		#define STR0046 "Enter a different child PPE to be related to PPE: "
		#define STR0047 "The PPE entered has already been related to this supplier."
		#define STR0048 "There is no generic PPE related to the supplier."
		#define STR0049 "Selection of child PPE(s)"
		#define STR0050 "Generic PPE:"
		#define STR0051 "Indicate to which generic PPE associated with the supplier you want to relate child PPEs."
		#define STR0052 "IPE"
		#define STR0053 "OK"
		#define STR0054 "PPE code not entered."
		#define STR0055 "Approval certificate number not entered."
		#define STR0056 "Start date of PPE supply not entered for this supplier."
		#define STR0057 "Start date after end date of PPE supply."
		#define STR0058 "Enter a date equal to or before end date."
		#define STR0059 "End date before start date of PPE supply."
		#define STR0060 "Enter a date equal to or after start date."
		#define STR0061 "This is a generic EPI and it has child EPI, unlink the child EPI before deleting."
		#define STR0062 "Child EPI register cannot be edited because end date has already been entered."
		#define STR0063 "Enter the query object that you wish to query. Options: Code, Description, Num. C.A. and Due Date C.A."
		#define STR0064 "Enter code according to the query object used to query."
		#define STR0065 "Search Object"
		#define STR0066 "Value to Search"
		#define STR0067 "Task"
		#define STR0068 "Attention"
		#define STR0069 "This Generic PPE has registered children."
		#define STR0070 "First delete child PPE´s."
		#define STR0071 "Child PPE already registered."
		#define STR0072 "Enter a new PPE code ou other CA number."
		#define STR0073 "This EPI is registered as generic."
		#define STR0074 "Enter as generic or enter another EPI."
		#define STR0075 "This EPI is registered as non-generic."
		#define STR0076 "Enter as non-generic or enter another EPI."
		#define STR0077 "Generate eSocial XML"
		#define STR0078 "Inconsistencies of Protection Equipments"
		#define STR0079 "The fields below are blank/zeroed or have inconsistency in relation to the standard format of eSocial: "
		#define STR0080 "Monitoring Submission of Events"
		#define STR0081 "Events Log"
		#define STR0082 "Table of Protection Equipments"
		#define STR0083 "Inconsistencies in the submission of the record to eSocial"
		#define STR0084 "Proceed?"
		#define STR0085 "Check inconsistencies"
		#define STR0086 "EPI already registered with CA valid for this supplier. Register anyway?"
		#define STR0087 "C.A. Renewal"
		#define STR0088 "To renew the C.A., change the original record date."
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Epis", "EPIs" )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Fornecedor De Epis", "Fornecedor de EPIs" )
		#define STR0005 "Fornecedor"
		#define STR0006 "Nome"
		#define STR0007 "Loja"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Morada", "Endereco" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Concelho", "Cidade" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Código postal", "CEP" )
		#define STR0011 "Telefone"
		#define STR0012 "Clientes"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Este dado não poderá ser excluido, pois este epi consta no registo de epi x função", "Este dado não poderá ser excluído, pois este Epi consta no cadastro de Epi x Função" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Este dado não poderá ser excluido, pois este epi consta no registo de epi x ", "Este dado não poderá ser excluído, pois este Epi consta no cadastro de Epi x " )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Centro De Custo", "Centro de Custo" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Atenção", "ATENÇÃO" )
		#define STR0017 "Este dado não poderá ser excluído, pois este Epi consta nos Epi's entregues "
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "De algum empregado.", "de algum funcionário." )
		#define STR0019 "Credenciados"
		#define STR0020 "A data de avaliação do EPI precisa menor ou igual à data de vencimento."
		#define STR0021 "Favor informar a quantidade de dias de utilização do EPI."
		#define STR0022 "Favor informar o tipo de Durabilidade do EPI."
		#define STR0023 "Pesquisar C.A. no MTE"
		#define STR0024 "MTE"
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Este Epi não poderá ser alterado, pois já foi entregue para algum colaborador.", "Este Epi não poderá ser alterado, pois já foi entregue para algum funcionário." )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Este Epi já foi entregue a colaboradores com o C.A. em branco.", "Este Epi já foi entregue a funcionários com o C.A. em branco." )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", " Deseja actualizar o C.A. nos registos lançados, com o que for preenchido em seguida?", " Deseja atualizar o C.A. nos registros lançados, com o que for preenchido em seguida?" )
		#define STR0028 "Pesquisa de Epi's"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Objecto de Pesquisa", "Objeto de Pesquisa" )
		#define STR0030 "Valor a procurar"
		#define STR0031 "Localizar Anterior"
		#define STR0032 "Buscar / Próximo"
		#define STR0033 "Código"
		#define STR0034 "Não foram localizados EPI's com este código."
		#define STR0035 "Descrição"
		#define STR0036 "Não foram localizados EPI's com esta descrição."
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Nr. C.A.", "Num. C.A." )
		#define STR0038 "Não foram localizados EPI's com este Certificado de Aprovação."
		#define STR0039 "Data Venc. C.A."
		#define STR0040 "Não foram localizados EPI's com esta data de vencimento para o Certificado de Aprovação."
		#define STR0041 "EPIs  -  Equipamentos de Proteção Individual"
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "O campo 'Genérico ?' está em branco.", "O campo 'Generico ?' está em branco." )
		#define STR0043 "Preencha o campo para prosseguir os cadastros."
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Grupo de EPI", "Grupo de EPIs" )
		#define STR0045 "O EPI informado é o mesmo EPI genérico."
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Informe um EPI secundário diferente para ser relacionado ao EPI: ", "Informe um EPI filho diferente para ser relacionado ao EPI: " )
		#define STR0047 "O EPI informado já foi relacionado a esse fornecedor."
		#define STR0048 "Não há EPI genérico relacionado ao fornecedor."
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Selecção os EPI(s) secundário(s)", "Seleção os EPI(s) filho(s)" )
		#define STR0050 "EPI genérico:"
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Indique a qual EPI genérico vinculado ao fornecedor deseja relacionar os EPI secundários.", "Indique para qual EPI genérico vinculado ao fornecedor que deseja relacionar os EPIs Filhos." )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "EPI", "Epi" )
		#define STR0053 "Ok"
		#define STR0054 "Não foi informado o código do EPI."
		#define STR0055 "Não foi informado o número do certificado de aprovação."
		#define STR0056 "Não foi informada a data inicial do fornecimento do EPI para esse forncedor."
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Data de início superior à data encerramento do fornecimento do EPI.", "Data de inicio superior a data encerramento do fornecimento do EPI." )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Informe uma data igual ou menor à data final.", "Informe uma data igual ou menor a data final." )
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Data de término inferior à data de início do fornecimento do EPI.", "Data de termino inferior a data de inicio do fornecimento do EPI." )
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Informe uma data igual ou maior à data inicial.", "Informe uma data igual ou maior a data inicial." )
		#define STR0061 "Esse é um EPI genérico e possuí EPI filhos relacionados, desvincule os EPIs filhos antes de excluir."
		#define STR0062 "O Registro do EPI filho não pode ser alterado pois a data fim já foi informada."
		#define STR0063 "Informe o objeto de pesquisa que deseja para a pesquisa. Opções: Código, Descrição, Num. C.A. e Dt. Vencto. C.A."
		#define STR0064 "Informe o código de acordo com o objeto de pesquisa utilizado para pesquisar."
		#define STR0065 "Objeto de Pesquisa"
		#define STR0066 "Valor a Procurar"
		#define STR0067 "Tarefa"
		#define STR0068 "Atenção"
		#define STR0069 "Este EPI Genérico, já possui filhos cadastrados."
		#define STR0070 "Você deverá primeiro excluir os EPIs filhos."
		#define STR0071 "EPI Filho já cadastrado."
		#define STR0072 "Informe outro código de EPI ou outro número de CA."
		#define STR0073 "Este EPI já está cadastrado como genérico."
		#define STR0074 "Favor informa-lo como genérico ou informar outro EPI."
		#define STR0075 "Este EPI já está cadastrado como não genérico."
		#define STR0076 "Favor informa-lo como não genérico ou informar outro EPI."
		#define STR0077 "Gerar XML eSocial"
		#define STR0078 "Inconsistências dos Equipamentos de Proteção"
		#define STR0079 "Os campos abaixo estão vazios/zerados ou possuem inconsistência com relação ao formato padrão do eSocial: "
		#define STR0080 "Monitoramento Envio de Eventos"
		#define STR0081 "Log de Ocorrências"
		#define STR0082 "Tabela de Equipamentos de Proteção"
		#define STR0083 "Existem inconsistências no envio do registro ao eSocial"
		#define STR0084 "Deseja continuar mesmo assim?"
		#define STR0085 "Favor verificar as inconsistências"
		#define STR0086 "EPI já cadastrado com C.A. não vencido para esse fornecedor. Deseja cadastrar mesmo assim?"
		#define STR0087 "Renovação de C.A."
		#define STR0088 "Para renovar o C.A. deve ser alterada a data do registro original."
	#endif
#endif
