#ifdef SPANISH
	#define STR0001 "Salir"
	#define STR0002 "Confirmar"
	#define STR0003 "Reescribir"
	#define STR0004 "Buscar"
	#define STR0005 "Visualizar"
	#define STR0006 "Agenda"
	#define STR0007 "Atencion Medica"
	#define STR0008 "BUscar  "
	#define STR0009 "Visualizar  "
	#define STR0010 "Diagnostico "
	#define STR0011 "Medicamentos"
	#define STR0012 "ASO         "
	#define STR0013 "Leyenda     "
	#define STR0014 "Agenda Medica"
	#define STR0015 "Examenes del Empleado"
	#define STR0016 "Ocurrencias de Ficha Medica"
	#define STR0017 "Receta Medica"
	#define STR0018 " El ASO solo se podra efectuar para examenes NR7"
	#define STR0019 " Paciente"
	#define STR0020 " No Atendido"
	#define STR0021 " Ya Atendido"
	#define STR0022 "Historial corrido del Paciente"
	#define STR0023 "Cuestionario Medico"
	#define STR0024 "Respuestas al Cuestionario Medico"
	#define STR0025 "Transferencia"
	#define STR0026 "No se podra transferir la consulta, pues la atencion ya esta concluida."
	#define STR0027 "ATENCIÓN"
	#define STR0028 "Transferencia de consulta"
	#define STR0029 "Ficha medica"
	#define STR0030 "Nombre"
	#define STR0031 "Examen"
	#define STR0032 "Motivo"
	#define STR0033 "Medico actual"
	#define STR0034 "Transferir a medico"
	#define STR0035 "Medico"
	#define STR0036 "Fecha Consulta"
	#define STR0037 "Hora Consulta"
	#define STR0038 "no es empleado del ambulatorio."
	#define STR0039 "Ya existe consulta marcada para esta fecha y hora en la agenda del "
	#define STR0040 "Médico: "
	#define STR0041 "no puede atender consultas en este horario."
	#define STR0042 "Verifique el calendario de atencion del Medico."
	#define STR0043 "Certificado Medico"
	#define STR0044 "Historial de Medicamentos"
	#define STR0045 "Problema: No se encontró el calendario en que se basa la agenda del medico."
	#define STR0046 "Solución: Verifique en el registro de calendarios si el código"
	#define STR0047 "existe en la tabla. En caso que no exista, registrarlo."
	#define STR0048 "Riesgos del Empleado"
	#define STR0049 "DELGADEZ SEVERA"
	#define STR0050 "DELGADEZ MODERADA"
	#define STR0051 "DELGADEZ LEVE"
	#define STR0052 "PESO SALUDABLE"
	#define STR0053 "PREOBESIDAD"
	#define STR0054 "OBESIDAD GRADO 1"
	#define STR0055 "OBESIDAD GRADO 2"
	#define STR0056 "OBESIDAD GRADO 3"
	#define STR0057 "Riesgo"
	#define STR0058 "Agente"
	#define STR0059 "Nombre Agente"
	#define STR0060 "Fuente"
	#define STR0061 "Nombre Fuente"
	#define STR0062 "Fecha Reconocimiento"
	#define STR0063 "Fecha evaluacion"
	#define STR0064 "Encaminamiento de Examenes"
	#define STR0065 "y"
	#define STR0066 "El empleado ya tiene ASO para el día "
	#define STR0067 ", de modalidad "
	#define STR0068 "¿Desea realmente incluir nuevo Aso?"
	#define STR0069 "El contenido del campo 'CID Principal' no esta de acuerdo con el CID informado en el "
	#define STR0070 "registro de Accidentes."
	#define STR0071 "CID Principal: "
	#define STR0072 "CID del Accidente: "
	#define STR0073 "ATENCION"
	#define STR0074 "El diagnóstico no se podrá modificar. Entre en contacto con el administrador del sistema para "
	#define STR0075 "habilitar esta opción."
	#define STR0076 "Incluir"
	#define STR0077 "Modificar"
	#define STR0078 "Borrar"
	#define STR0079 "Imprimir"
	#define STR0080 "Certificado médico"
	#define STR0081 "Certificado Med."
	#define STR0082 "Diagnósticos realizados del empleado"
	#define STR0083 "Historial de cuestionarios médicos"
	#define STR0084 "El ASO solamente podra realizarse para examenes NR7."
	#define STR0085 "Conocimiento"
	#define STR0086 "Detalles Ficha"
	#define STR0087 "Buscar C.I.D."
	#define STR0088 "C.I.D."
	#define STR0089 "Examenes"
	#define STR0090 "Sucursal Empl."
	#define STR0091 "Historial de consultas del medico"
	#define STR0092 "Se transfirió la consulta programada en agenda al"
	#define STR0093 "Matrícula"
	#define STR0094 "Horario Nuevo:"
	#define STR0095 "Horario Antiguo:"
	#define STR0096 "Seleccione la Ficha Medica!"
	#define STR0097 "Realizacion"
	#define STR0098 "Cuestionario"
	#define STR0099 "Ficha Medica + Fecha Real + Cuestionario"
	#define STR0100 "Historial del Registro"
	#define STR0101 "Usuario no posee agenda medica registrada."
	#define STR0102 "Favor registrar agenda medica."
	#define STR0103 "Hist. Borr."
	#define STR0104 "Es necesario informar la Fecha de la atencion."
	#define STR0105 "O Acidente "
	#define STR0106 " possui o CID "
	#define STR0107 ", deseja incluir o mesmo CID no Diagnóstico?"
	#define STR0108 "Es necesario informar la hora de la atención."
	#define STR0109 "No es posible incluir en un horario reservado o  bloqueado."
	#define STR0110 "Por favor, informe otro horario."
	#define STR0111 "El horario de la devolución es inferior al horario de la atención."
	#define STR0112 "Por favor, informe un horario superior."
	#define STR0113 "La rutina Atención Médica( MDTA160) fue descontinuada. "
	#define STR0114 "Por favor, utilice la Agenda Médica Mod. 2(MDTA076) o la rutina Ficha Médica (MDTA410). "
	#define STR0115 "No se puede incluir un envío de examen a un empleado que no tiene ficha médica."
	#define STR0116 "Incluye una ficha medica para el empleado."
	#define STR0117 "No se puede incluir un certificado médico para un empleado que no tiene ficha medica."
	#define STR0118 "Empleado"
	#define STR0119 "candidato"
#else
	#ifdef ENGLISH
		#define STR0001 "Quit"
		#define STR0002 "Confirm"
		#define STR0003 "Retype"
		#define STR0004 "Search"
		#define STR0005 "View"
		#define STR0006 "Schedule"
		#define STR0007 "Medical Attendance"
		#define STR0008 "Search "
		#define STR0009 "View "
		#define STR0010 "Diagnosis "
		#define STR0011 "Medicines"
		#define STR0012 "OHC         "
		#define STR0013 "Caption     "
		#define STR0014 "Medical Agenda"
		#define STR0015 "Employee´s Exams"
		#define STR0016 "Medical Report Occurrences "
		#define STR0017 "Medical Prescription"
		#define STR0018 " The ASO can be executed only for NR7 exams"
		#define STR0019 " Patient"
		#define STR0020 " Not Attended"
		#define STR0021 " Already Attended"
		#define STR0022 "Patient report"
		#define STR0023 "Medical Questionnaire"
		#define STR0024 "Answers to the Medical Questionnaire"
		#define STR0025 "Transference"
		#define STR0026 "It will not be possible to transfer the doctor appointment, as the attendance has already been finished."
		#define STR0027 "ATTENTION"
		#define STR0028 "Appointment Transfer"
		#define STR0029 "Medical Record"
		#define STR0030 "Name"
		#define STR0031 "Exam"
		#define STR0032 "Reason"
		#define STR0033 "Current Doctor"
		#define STR0034 "Transfer to Doctor"
		#define STR0035 "Doctor"
		#define STR0036 "Doctor Appointment Date"
		#define STR0037 "Doctor Appointment Time"
		#define STR0038 "does not serve the policlinic."
		#define STR0039 "Query selected for this date and schedule of "
		#define STR0040 "doctor: "
		#define STR0041 "cannot have appointments this schedule."
		#define STR0042 "Check Doctor service schedule."
		#define STR0043 "Medical Certificate"
		#define STR0044 "Medicine History"
		#define STR0045 "Problem: The calendar in which the doctor schedule is based on was not found."
		#define STR0046 "Solution: Check in Calendar register if the code"
		#define STR0047 "exists on the table. If it does not exist register it."
		#define STR0048 "Employees Risks      "
		#define STR0049 "SEVERE THINNESS"
		#define STR0050 "MODERATE THINNESS"
		#define STR0051 "LIGHT THINNESS"
		#define STR0052 "HEALTHY WGHT."
		#define STR0053 "PRE OBESITY  "
		#define STR0054 "OBESITY LEVEL 1 "
		#define STR0055 "OBESITY LEVEL 2 "
		#define STR0056 "OBESITY LEVEL 3 "
		#define STR0057 "Risk "
		#define STR0058 "Agent "
		#define STR0059 "Agent Name "
		#define STR0060 "Source"
		#define STR0061 "Source Name"
		#define STR0062 "Bill of Lading Date"
		#define STR0063 "Evaluation Date"
		#define STR0064 "Direction of the Exams  "
		#define STR0065 " and"
		#define STR0066 "Employee already has OHC for day "
		#define STR0067 ", of class "
		#define STR0068 "Are you sure you require a new ASO?"
		#define STR0069 "'Main ICD' field content does not match with the informed ICD "
		#define STR0070 "in the accident file."
		#define STR0071 "Main ICD: "
		#define STR0072 "Accident ICD: "
		#define STR0073 "ATTENTION"
		#define STR0074 "The Supplier can not be edited. Contact the system administrator to "
		#define STR0075 "enable this option."
		#define STR0076 "Insert "
		#define STR0077 "Edit   "
		#define STR0078 "Delete "
		#define STR0079 "Print   "
		#define STR0080 "Medical Certificate"
		#define STR0081 "Med.Certificate"
		#define STR0082 "Employee Performed Diagnosis"
		#define STR0083 "Medical Form History"
		#define STR0084 "ASO can only be performed for NR7 exams."
		#define STR0085 "Knowledge"
		#define STR0086 "Form details"
		#define STR0087 "Search ICD"
		#define STR0088 "ICD"
		#define STR0089 "Examinations"
		#define STR0090 "Empl. Branch"
		#define STR0091 "Doctor appointment history"
		#define STR0092 "Scheduled appointment was transferred to"
		#define STR0093 "Registration"
		#define STR0094 "New Time:"
		#define STR0095 "Former Time:"
		#define STR0096 "Select medical record!"
		#define STR0097 "Execution"
		#define STR0098 "Questionnaire"
		#define STR0099 "Medical Record + Actual Date + Questionnaire"
		#define STR0100 "History of Register"
		#define STR0101 "The user has no medical schedule registered."
		#define STR0102 "Please register medical schedule."
		#define STR0103 "Exc. Hist."
		#define STR0104 "You must enter the Service Date."
		#define STR0105 "The Accident "
		#define STR0106 " has ICD "
		#define STR0107 ", add the same ICD in Diagnosis?"
		#define STR0108 "Enter Service Time."
		#define STR0109 "Add a reservation or block time."
		#define STR0110 "Please enter another schedule."
		#define STR0111 "The return schedule is earlier than service schedule."
		#define STR0112 "Enter a more extensive schedule."
		#define STR0113 "The routine Medical Service (MDTA160) was discontinued. "
		#define STR0114 "Please use Medical Schedule Mod. 2(MDTA076) or routine Medical Form(MDTA410). "
		#define STR0115 "Unable to forward an exam to an employee without a medical record"
		#define STR0116 "Add a medical record for an employee."
		#define STR0117 "Unable to add a medical certificate for an employee with a medical record"
		#define STR0118 "employee"
		#define STR0119 "candidate"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Abandonar", "Abandona" )
		#define STR0002 "Confirma"
		#define STR0003 "Redigita"
		#define STR0004 "Pesquisar"
		#define STR0005 "Visualizar"
		#define STR0006 "Agenda"
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Atendimento Médico", "Atendimento Medico" )
		#define STR0008 "Pesquisar  "
		#define STR0009 "Visualizar  "
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Diagnóstico ", "Diagnostico " )
		#define STR0011 "Medicamentos"
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Rastreio médico         ", "ASO         " )
		#define STR0013 "Legenda     "
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Agenda Médica", "Agenda Medica" )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Exames Do Empregado", "Exames do Funcionario" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Ocorrências Da Ficha Médica", "Ocorrencias da Ficha Medica" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Receita Médica", "Receita Medica" )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", " O Aso Só Poderá Ser Realizado Para Exames Nr7", " O ASO so podera ser realizado para exames NR7" )
		#define STR0019 " Paciente"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", " Não Atendido", " Nao Atendido" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", " Já Atendido", " Ja  Atendido" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Histórico Corrido Do Paciente", "Historico corrido do Paciente" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Questionário Médico", "Questionario Medico" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Respostas Ao Questionário Médico", "Respostas ao Questionario Medico" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Transferência", "Transferencia" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Não será possível transferir a consulta, pois o atendimento já foi concluido.", "Nao sera possivel transferir a consulta, pois o atendimento ja foi concluido." )
		#define STR0027 "ATENÇÃO"
		#define STR0028 "Transferência de Consulta"
		#define STR0029 "Ficha Médica"
		#define STR0030 "Nome"
		#define STR0031 "Exame"
		#define STR0032 "Motivo"
		#define STR0033 "Médico Atual"
		#define STR0034 "Transferir para Médico"
		#define STR0035 "Médico"
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Data Da Consulta", "Data Consulta" )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Hora Da Consulta", "Hora Consulta" )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Não é atendente do ambulatório.", "nao e atendente do ambulatorio." )
		#define STR0039 "Já existe consulta marcada para esta data e hora na agenda do "
		#define STR0040 "médico: "
		#define STR0041 "não pode atender consultas nesse horário."
		#define STR0042 "Verificar o calendário de atendimento do Médico."
		#define STR0043 "Atestado Médico"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Histórico de medicamentos", "Histórico de Medicamentos" )
		#define STR0045 "Problema: O calendário na qual a agenda do medico baseia-se, nao foi encontrado."
		#define STR0046 "Solução: Verificar no cadastro de Calendarios se o codigo"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Existe na tabela. caso não exista, registá-lo.", "existe na tabela. Caso nao exista, cadastra-lo." )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Riscos Do Empregado", "Riscos do Funcionario" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Magreza Severa", "MAGREZA SEVERA" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Magreza Moderada", "MAGREZA MODERADA" )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Magreza Leve", "MAGREZA LEVE" )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Peso Saudável", "PESO SAUDAVEL" )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Pré-obesidade", "PRE OBESIDADE" )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Obesidade grau 1", "OBESIDADE GRAU 1" )
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Obesidade grau 2", "OBESIDADE GRAU 2" )
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "Obesidade grau 3", "OBESIDADE GRAU 3" )
		#define STR0057 "Risco"
		#define STR0058 "Agente"
		#define STR0059 "Nome Agente"
		#define STR0060 "Fonte"
		#define STR0061 "Nome Fonte"
		#define STR0062 "Data Reconhecimento"
		#define STR0063 "Data Avaliação"
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "Encaminhamento De Exames", "Encaminhamento de Exames" )
		#define STR0065 " e"
		#define STR0066 "O funcionário ja possui Aso para o dia "
		#define STR0067 ", de natureza "
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Tem Certeza Que Deseja Incluir Novo Aso?", "Tem certeza que deseja incluir novo Aso?" )
		#define STR0069 "O conteudo do campo 'CID Principal' näo esta de acordo com o CID informado no "
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Registo De Acidentes.", "cadastro de Acidentes." )
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Cid principal: ", "CID Principal: " )
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Cid do acidente: ", "CID do Acidente: " )
		#define STR0073 "ATENÇÃO"
		#define STR0074 "O diagnóstico não podera ser alterado. Contate o Administrador do sistema para "
		#define STR0075 "habilitar está opção."
		#define STR0076 "Incluir"
		#define STR0077 "Alterar"
		#define STR0078 "Excluir"
		#define STR0079 "Imprimir"
		#define STR0080 "Atestado Médico"
		#define STR0081 "Atestado Med."
		#define STR0082 "Diagnósticos Realizados do Funcionário"
		#define STR0083 "Histórico de Questionários Médicos"
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "A Triagem Médica Só Poderá Ser Realizada Para Exames Nº7.", "O ASO só podera ser realizado para exames NR7." )
		#define STR0085 "Conhecimento"
		#define STR0086 "Detalhes Ficha"
		#define STR0087 If( cPaisLoc $ "ANG|PTG", "Pesquisar C.i.d.", "Pesquisar C.I.D." )
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "C.i.d.", "C.I.D." )
		#define STR0089 "Exames"
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "Filial Colab.", "Filial Func." )
		#define STR0091 "Histórico de consultas do médico"
		#define STR0092 "Foi transferida a consulta agendada para o"
		#define STR0093 "Matrícula"
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Horário novo:", "Horário Novo:" )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Horário antigo:", "Horário Antigo:" )
		#define STR0096 If( cPaisLoc $ "ANG|PTG", "Seleccione a ficha médica.", "Selecione a Ficha Médica!" )
		#define STR0097 "Realização"
		#define STR0098 "Questionário"
		#define STR0099 If( cPaisLoc $ "ANG|PTG", "Ficha Médica + Data Real + Questionário", "Ficha Medica + Data Real + Questionario" )
		#define STR0100 If( cPaisLoc $ "ANG|PTG", "Histórico do registo", "Histórico do Registro" )
		#define STR0101 "Usuário não possui agenda médica cadastrada."
		#define STR0102 "Favor cadastrar agenda médica."
		#define STR0103 "Hist. Exc."
		#define STR0104 "É necessario informar a Data do Atendimento."
		#define STR0105 "O Acidente "
		#define STR0106 " possui o CID "
		#define STR0107 ", deseja incluir o mesmo CID no Diagnóstico?"
		#define STR0108 "É necessario informar a Hora do Atendimento."
		#define STR0109 "Não é possível incluir sobre um horário de reserva ou bloqueio."
		#define STR0110 "Favor informar outro horário."
		#define STR0111 "O horário do retorno é menor que horário do atendimento."
		#define STR0112 "Favor informar um horário maior."
		#define STR0113 "A rotina de Atendimento Médico(MDTA160) foi descontinuada. "
		#define STR0114 "Favor utilizar a Agenda Médica Mod. 2(MDTA076) ou a rotina de Prontuário Médico(MDTA410). "
		#define STR0115 "Não é possível incluir um encaminhamento de exame para um funcionário que não possui ficha médica."
		#define STR0116 "Incluir uma ficha médica para o funcionário."
		#define STR0117 "Não é possível incluir um atestado médico para um funcionário que não possui ficha médica."
		#define STR0118 "funcionário"
		#define STR0119 "candidato"
	#endif
#endif
