#ifdef SPANISH
	#define STR0001 "Empleado"
	#define STR0002 "Accidente"
	#define STR0003 "Emisor"
	#define STR0004 "Empresa"
	#define STR0005 "Tipo de inscripción"
	#define STR0006 "En blanco"
	#define STR0007 "Validación"
	#define STR0008 "Debe ser igual a 1 (RCPJ) o 2 (RCPF)"
	#define STR0009 "Número de inscripción"
	#define STR0010 "Debe ser un número de RCPJ válido"
	#define STR0011 "Debe ser un número de RCPF válido"
	#define STR0012 "El accidente seleccionado no tiene ninguna ficha médica vinculada"
	#define STR0013 "RCPF"
	#define STR0014 "Categoría"
	#define STR0015 "Debe ser un código válido y existente en la Tabla 01 del eSocial"
	#define STR0016 "Fecha del accidente"
	#define STR0017 "Debe ser una fecha válida y"
	#define STR0018 "Igual o anterior a la fecha actual"
	#define STR0019 "Igual o posterior a la fecha de ingreso del trabajador"
	#define STR0020 "Igual o posterior a la fecha inicial de obligatoriedad del eSocial."
	#define STR0021 "Tipo del accidente"
	#define STR0022 "Debe ser igual a 1- Típico, 2- Enfermedad 3- Trayecto"
	#define STR0023 "Hora del accidente"
	#define STR0024 "Horas trabajadas antes del accidente"
	#define STR0025 "Tipo de CAT"
	#define STR0026 "Debe ser igual a 1- Inicial, 2- Reapertura o 3- Comunicación de fallecimiento"
	#define STR0027 "Indicativo de fallecimiento"
	#define STR0028 "Debe ser igual a S=Sí o N=No"
	#define STR0029 "Si el Tipo de CAT es igual a 3-Comunicado de defunción, el campo ‘Hubo muerte’ debe ser igual a 'Si'."
	#define STR0030 "Si el Tipo de CAT es igual a 2- Reapertura, el campo 'Hubo Muerte' debe ser igual a 'No'"
	#define STR0031 "Fecha de defunción"
	#define STR0032 "Igual o posterior a la fecha del accidente"
	#define STR0033 "Indicativo de comunicación a la autoridad policial"
	#define STR0034 "Código de la situación generadora"
	#define STR0035 "Debe ser un código válido y existente en la tabla 15 o 16 del eSocial"
	#define STR0036 "Tipo de lugar del accidente"
	#define STR0037 "Debe ser igual a"
	#define STR0038 "1- Establecimiento del empleador en Brasil"
	#define STR0039 "2- Establecimiento del empleador en el exterior"
	#define STR0040 "3- Establecimiento de terceros donde el empleador presta servicios"
	#define STR0041 "4- Vía pública"
	#define STR0042 "5- Área rural"
	#define STR0043 "6- Embarcación"
	#define STR0044 "9- Otros"
	#define STR0045 "Tipo de via publica"
	#define STR0046 "Debe ser un código válido y existente en la Tabla 20 del eSocial"
	#define STR0047 "Descripción de la dirección"
	#define STR0048 "CP"
	#define STR0049 "Municipio"
	#define STR0050 "Est/Prov/Reg"
	#define STR0051 "País"
	#define STR0052 "Debe ser un código válido y existente en la Tabla 06 del eSocial"
	#define STR0053 "Código de la dirección postal"
	#define STR0054 "Tipo de inscripción del lugar del accidente"
	#define STR0055 "Debe ser igual a 1 (RCPJ), 3 (RAEPF), o 4 (RNO)"
	#define STR0056 "Inscripción del lugar del accidente"
	#define STR0057 "1) Debe constar en la tabla S-1005 si el lugar del accidente fuera igual a 'Establecimiento del empleador en Brasil'."
	#define STR0058 "2) Debe ser diferente de los establecimientos informados en la Tabla S-1005 si el lugar del accidente fuera igual a 'Establecimiento de"
	#define STR0059 "terceros' y diferente del RCPJ base indicado en S1000 si el tipo de inscripción del lugar del accidente fuera igual a RCPJ."
	#define STR0060 "Parte(s) del cuerpo afectada(s)"
	#define STR0061 "Debe ser un código válido y existente en la Tabla 13 del eSocial"
	#define STR0062 "Lateralidad de la parte afectada"
	#define STR0063 "No existen partes afectadas relacionadas al accidente"
	#define STR0064 "Motivo de la causa del accidente"
	#define STR0065 "Debe ser un código válido y existente en la tabla 14 o 15 del eSocial"
	#define STR0066 "No existen agentes causadores relacionados al accidente"
	#define STR0067 "Fecha de la atención"
	#define STR0068 "Debe ser una fecha válida, igual o anterior a la fecha actual."
	#define STR0069 "Hora de atención"
	#define STR0070 "Indicativo de internación"
	#define STR0071 "Indicativo de licencia"
	#define STR0072 "Si el campo 'Hubo muerte' es igual a 'Sí', el indicativo de 'Licencia' debe ser igual a 'No'"
	#define STR0073 "Código de descripción de la naturaleza de la lesión"
	#define STR0074 "Debe ser un código válido y existente en la Tabla 17 del eSocial"
	#define STR0075 "CIE"
	#define STR0076 "Nombre"
	#define STR0077 "Organismo de clase"
	#define STR0078 "Debe ser igual a 1- CRM, 2- CRO o 3- RMS"
	#define STR0079 "Número de inscripción del organismo de clase"
	#define STR0080 "Estado/Prov/Reg del organismo de clase"
	#define STR0081 "Número de recibo de la CAT origen"
	#define STR0082 "Al registrar una CAT del tipo Origen u Óbito, se deben informar los campos CAT Origen y Fch. CAT Or."
	#define STR0083 "El país seleccionado está extinto de acuerdo con el layout del eSocial"
#else
	#ifdef ENGLISH
		#define STR0001 "Employee"
		#define STR0002 "Accident"
		#define STR0003 "Issuer"
		#define STR0004 "Company"
		#define STR0005 "Registration Type"
		#define STR0006 "Blank"
		#define STR0007 "Validation"
		#define STR0008 "It must be 1- EIN or 2- SSN"
		#define STR0009 "Registration Number"
		#define STR0010 "It must be a valid EIN number"
		#define STR0011 "It must be a valid SSN number"
		#define STR0012 "Accident selected does not have any medical form linked"
		#define STR0013 "SSN"
		#define STR0014 "Category"
		#define STR0015 "It must be a valid code existing in the tables 01 of the eSocial"
		#define STR0016 "Accident Date"
		#define STR0017 "It must be valid date and"
		#define STR0018 "Equal to or later than the current date"
		#define STR0019 "Equal to or later than the worker’s admission date"
		#define STR0020 "equal to or later than the start date of eSocial requirement"
		#define STR0021 "Accident Type"
		#define STR0022 "It must equal to 1- Typical, 2- Illness or 3- Commuting"
		#define STR0023 "Accident Time"
		#define STR0024 "Hours Worked before accident"
		#define STR0025 "Type of CAT"
		#define STR0026 "It must be equal to 1- Initial, 2- Reopening or 3- Communication of death"
		#define STR0027 "Indicative of Death"
		#define STR0028 "It must be equal to S- Yes or N- No"
		#define STR0029 "If CAT type is equal to 3 - Communication of Death, the field ‘Death” must be ‘Yes’"
		#define STR0030 "If CAT type is equal to 2 - Reopening, the field ‘Death” must be ‘No’"
		#define STR0031 "Death Date"
		#define STR0032 "Equal to or later than accident date"
		#define STR0033 "Indicative of Communication to the Police"
		#define STR0034 "Code of Generating Situation"
		#define STR0035 "It must be a valid code existing in the tables 15 and 16 of the eSocial"
		#define STR0036 "Accident Location Type"
		#define STR0037 "It must be equal to"
		#define STR0038 "1- Employer Site in Brazil"
		#define STR0039 "2- Employer Site Abroad"
		#define STR0040 "3- Site of Third Party where the employer renders services"
		#define STR0041 "4- Public Area"
		#define STR0042 "5- Rural Area"
		#define STR0043 "6- Shipping"
		#define STR0044 "9- Others"
		#define STR0045 "Type of Public Area"
		#define STR0046 "It must be a valid code existing in the tables 20 of the eSocial"
		#define STR0047 "Description of Public Area"
		#define STR0048 "Postal Code"
		#define STR0049 "City"
		#define STR0050 "State"
		#define STR0051 "Country"
		#define STR0052 "It must be a valid code existing in the tables 06 of the eSocial"
		#define STR0053 "Postal Code"
		#define STR0054 "Registration Type of Accident Location"
		#define STR0055 "It must be 1- EIN, 3- CAEPF or 4- CNO"
		#define STR0056 "Accident Location Registration"
		#define STR0057 "1) The S-1005 table must indicate if the accident location is equal to 'Employer Site in Brazil'."
		#define STR0058 "2) It must be different than the sites entered in the S-1005 table in case the accident location is equal to ‘Third Party Site’"
		#define STR0059 "and different than the EIN base indicate in S-1000 if the registration type of the accident location is equal to EIN."
		#define STR0060 "Part of Body Injured"
		#define STR0061 "It must be a valid code existing in table 13 of the eSocial"
		#define STR0062 "Laterality of the Injured Part"
		#define STR0063 "No injured parts related to the accident"
		#define STR0064 "Accident Causing Agent"
		#define STR0065 "It must be a valid code existing in tables 14 or 15 of the eSocial"
		#define STR0066 "No causing agents related to the accident"
		#define STR0067 "Appointment Date"
		#define STR0068 "It must be a valid date equal to or earlier than the current date"
		#define STR0069 "Appointment Time"
		#define STR0070 "Hospitalization Indicative"
		#define STR0071 "Leave Indicative"
		#define STR0072 "If the field “Death’ is ‘Yes’, the indicative of ‘Leave’ must be ‘No’"
		#define STR0073 "Code of Injury Nature Description"
		#define STR0074 "It must be a valid code existing in the tables 17 of the eSocial"
		#define STR0075 "ICD"
		#define STR0076 "Name"
		#define STR0077 "Bargaining Unit"
		#define STR0078 "It must be 1- CRM, 2- CRO or 3- RMS"
		#define STR0079 "Registration Number of Bargaining Unit"
		#define STR0080 "Bargaining Unit State"
		#define STR0081 "Number of Origin CAT Receipt"
		#define STR0082 "When registering an Origin or Death type CAT, enter the fields Origin CAT and Or.CAT Dt."
		#define STR0083 "Selected country is extinct according to e-Social layout"
	#else
		#define STR0001 "Funcionário"
		#define STR0002 "Acidente"
		#define STR0003 "Emitente"
		#define STR0004 "Empresa"
		#define STR0005 "Tipo de Inscrição"
		#define STR0006 "Em branco"
		#define STR0007 "Validação"
		#define STR0008 "Deve ser igual a 1- CNPJ ou 2- CPF"
		#define STR0009 "Número de Inscrição"
		#define STR0010 "Deve ser um número de CNPJ válido"
		#define STR0011 "Deve ser um número de CPF válido"
		#define STR0012 "O acidente selecionado não possui nenhuma ficha médica vinculada"
		#define STR0013 "CPF"
		#define STR0014 "Categoria"
		#define STR0015 "Deve ser um código válido e existente na tabela 01 do eSocial"
		#define STR0016 "Data do Acidente"
		#define STR0017 "Deve ser uma data válida e"
		#define STR0018 "Igual ou anterior à data atual"
		#define STR0019 "Igual ou posterior à data de admissão do trabalhador"
		#define STR0020 "Igual ou posterior à data de início de obrigatoriedade do eSocial"
		#define STR0021 "Tipo do Acidente"
		#define STR0022 "Deve ser igual a 1- Típico, 2- Doença ou 3- Trajeto"
		#define STR0023 "Hora do Acidente"
		#define STR0024 "Horas Trabalhadas Antes do Acidente"
		#define STR0025 "Tipo de CAT"
		#define STR0026 "Deve ser igual a 1- Inicial, 2- Reabertura ou 3- Comunicação de óbito"
		#define STR0027 "Indicativo de Óbito"
		#define STR0028 "Deve ser igual a S- Sim ou N- Não"
		#define STR0029 "Se o Tipo de CAT for igual a 3- Comunicação de óbito, o campo 'Houve Morte' deve ser igual a 'Sim'"
		#define STR0030 "Se o Tipo de CAT for igual a 2- Reabertura, o campo 'Houve Morte' deve ser igual a 'Não'"
		#define STR0031 "Data do Óbito"
		#define STR0032 "Igual ou posterior à data do acidente"
		#define STR0033 "Indicativo de Comunicação à Autoridade Policial"
		#define STR0034 "Código da Situação Geradora"
		#define STR0035 "Deve ser um código válido e existente na tabela 15 ou 16 do eSocial"
		#define STR0036 "Tipo de Local do Acidente"
		#define STR0037 "Deve ser igual a"
		#define STR0038 "1- Estabelecimento do empregador no Brasil"
		#define STR0039 "2- Estabelecimento do empregador no exterior"
		#define STR0040 "3- Estabelecimento de terceiros onde o empregador presta serviços"
		#define STR0041 "4- Via pública"
		#define STR0042 "5- Área rural"
		#define STR0043 "6- Embarcação"
		#define STR0044 "9- Outros"
		#define STR0045 "Tipo de Logradouro"
		#define STR0046 "Deve ser um código válido e existente na tabela 20 do eSocial"
		#define STR0047 "Descrição do Logradouro"
		#define STR0048 "CEP"
		#define STR0049 "Município"
		#define STR0050 "UF"
		#define STR0051 "País"
		#define STR0052 "Deve ser um código válido e existente na tabela 06 do eSocial"
		#define STR0053 "Código de Endereçamento Postal"
		#define STR0054 "Tipo de Inscrição do Local do Acidente"
		#define STR0055 "Deve ser igual a 1- CNPJ, 3- CAEPF ou 4- CNO"
		#define STR0056 "Inscrição do Local do Acidente"
		#define STR0057 "1) Deve constar na tabela S-1005 se o local do acidente for igual a 'Estabelecimento do Empregador no Brasil'."
		#define STR0058 "2) Deve ser diferente dos estabelecimentos informados na Tabela S-1005 se o local do acidente for igual a 'Estabelecimento de"
		#define STR0059 "Terceiros' e diferente do CNPJ base indicado em S-1000 se o tipo de inscrição do local do acidente for igual a CNPJ."
		#define STR0060 "Parte do Corpo Atingida"
		#define STR0061 "Deve ser um código válido e existente na tabela 13 do eSocial"
		#define STR0062 "Lateralidade da Parte Atingida"
		#define STR0063 "Não existem partes atingidas relacionadas ao acidente"
		#define STR0064 "Agente Causador do Acidente"
		#define STR0065 "Deve ser um código válido e existente na tabela 14 ou 15 do eSocial"
		#define STR0066 "Não existem agentes causadores relacionados ao acidente"
		#define STR0067 "Data do Atendimento"
		#define STR0068 "Deve ser uma data válida, igual ou anterior à data atual"
		#define STR0069 "Hora do Atendimento"
		#define STR0070 "Indicativo de Internação"
		#define STR0071 "Indicativo de Afastamento"
		#define STR0072 "Se o campo 'Houve Morte' for igual a 'Sim', o indicativo de 'Afastamento' deve ser igual a 'Não'"
		#define STR0073 "Código de Descrição da Natureza da Lesão"
		#define STR0074 "Deve ser um código válido e existente na tabela 17 do eSocial"
		#define STR0075 "CID"
		#define STR0076 "Nome"
		#define STR0077 "Órgão de Classe"
		#define STR0078 "Deve ser igual a 1- CRM, 2- CRO ou 3- RMS"
		#define STR0079 "Número de Inscrição do Órgão de Classe"
		#define STR0080 "UF do Órgão de Classe"
		#define STR0081 "Número de Recibo da CAT Origem"
		#define STR0082 "Ao cadastrar uma CAT do tipo Origem ou Óbito, devem ser informados os campos CAT Origem e Dt. CAT Or."
		#define STR0083 "O país selecionado está extinto de acordo com o leiaute do eSocial"
	#endif
#endif
