#ifdef SPANISH
	#define STR0001 "Tabla de dimensionamiento del Sesmt"
	#define STR0002 "A rayas"
	#define STR0003 "Administracion"
	#define STR0004 "¿Fecha de referencia?"
	#define STR0005 "¿De sucursal ?"
	#define STR0006 "¿A sucursal ?"
	#define STR0007 "¿Imprimir cuadro?"
	#define STR0008 "Fecha que se utilizara como referencia en la impresion del Cuadro comparativo."
	#define STR0009 "Menor codigo de sucursal considerado en la rutina."
	#define STR0010 "El campo puede permanecer vacio para considerar desde la primera sucursal."
	#define STR0011 "Mayor codigo de sucursal considerado en la rutina."
	#define STR0012 "Se puede completar el campo con 'ZZ' o '99' para que se considere hasta la ultima sucursal."
	#define STR0013 "El Cuadro Fijo muestra el Cuadro contenido en la NR29, item 29.2.1.2,Cuadro I."
	#define STR0014 "El cuadro comparativo hace una comparacion entre el cuadro fijo con los datos de las sucursales seleccionadas, identificando los usuarios Sesmt que estan faltando."
	#define STR0015 "¿De Cliente?"
	#define STR0016 "¿De Tienda?"
	#define STR0017 "¿A Cliente?"
	#define STR0018 "¿A Tienda?"
	#define STR0019 "ATENCION"
	#define STR0020 "No existen datos para elaborar el cuadro comparativo."
	#define STR0021 "DIMENSION DETALLADA DEL SESMT SESSTP"
	#define STR0022 "NIVEL"
	#define STR0023 "DE"
	#define STR0024 "RIESGO"
	#define STR0025 "Técnicas"
	#define STR0026 "Nº de empleados"
	#define STR0027 "en el establecimiento"
	#define STR0028 "Superior a 3.500"
	#define STR0029 "Para cada grupo"
	#define STR0030 "De 2.000 o fraccion"
	#define STR0031 "superior a 500(**)"
	#define STR0032 "a"
	#define STR0033 "Tecnico Seg. "
	#define STR0034 "Ingeniero Seg. "
	#define STR0035 "Aux. Enferm. del "
	#define STR0036 "Enfermero del "
	#define STR0037 "Medico del "
	#define STR0038 "(*) Tiempo parcial (mínimo de tres horas)"
	#define STR0039 "(**) La dimension detallada total se debe hacer"
	#define STR0040 "tomando en cuenta la dimension detallada"
	#define STR0041 "de intervalos entre 3.501 a 5.000 mas la dimension detallada"
	#define STR0042 "de los grupos de 4.000 o fraccion superior a 2.000."
	#define STR0043 " Hospitales, Ambulatorios, Maternidad, Casas de"
	#define STR0044 "Salud y reposo, clinicas y establecimientos similares"
	#define STR0045 "con mas de 500 (quinientos) empleados deben"
	#define STR0046 "contratar un enfermero por periodo integral"
	#define STR0047 "Sucursal: "
	#define STR0048 "Nivel de riesgo: "
	#define STR0049 "Total de empleados: "
	#define STR0050 "registro CNPJ de la empresa"
	#define STR0051 "Necesidad"
	#define STR0052 "Realidad"
	#define STR0053 "Trabajo"
	#define STR0054 "OBS:"
	#define STR0055 "Leyenda: "
	#define STR0056 "Negro - Dentro de los conformes"
	#define STR0057 "Rojo - Fuera de los conformes"
	#define STR0058 "¿Inicio de operacion?"
	#define STR0059 "¿Estimacion Trab. Tomados ano?"
	#define STR0060 "OGMO?"
	#define STR0061 "¿Nº Trab. Autonomo ano Ant. ?"
	#define STR0062 "¿Nº dias efect. trab. ano ant.?"
	#define STR0063 "¿Promed. mens. trab. ano civ. ant.?"
	#define STR0064 "Profesionales especializados"
	#define STR0065 "Profes. Especializados"
	#define STR0066 "Este parametro tiene validez solamente cuando el '¿Inicio operacion?' esta como 'Si'."
	#define STR0067 "Este parametro tiene validez solamente cuando el parametro '¿Inicio operacion?' esta como 'No' y el 'OGMO?' esta como 'Si'."
	#define STR0068 "Este parametro tiene validez solamente cuando el MDT no esta integrado al GPE."
	#define STR0069 "Este parametro tiene validez solamente cuando el parametro '¿Inicio operacion?' esta como 'Si' y 'OGMO?' esta como 'No'."
	#define STR0070 "Consid. Hrs."
	#define STR0071 "Si"
	#define STR0072 "No"
	#define STR0073 "Determina si se verificara el calendario medico."
	#define STR0074 "¿Consid. Horas?"
	#define STR0075 "¿Inicio de operacion?"
	#define STR0076 "Si o No."
	#define STR0077 "Numero de estimacion de trabajadores que se tomaran en el ano."
	#define STR0078 "Organismo gestor de mano de obra."
	#define STR0079 "Numero de trabajadores por hora escalados en el ano anterior."
	#define STR0080 "Numero de dias efectivamente trabajados en el ano anterior."
	#define STR0081 "Promedio mensual de trabajadores en el ano civil anterior."
	#define STR0082 "Parametro valido solo si el MDT no esta integrado con el GPE."
	#define STR0083 "Determina si se verificara el calendario medico."
#else
	#ifdef ENGLISH
		#define STR0001 "Sesmt Dimensioning List"
		#define STR0002 "Z-form"
		#define STR0003 "Administration"
		#define STR0004 "Reference Date?"
		#define STR0005 "From Branch?"
		#define STR0006 "To Branch?"
		#define STR0007 "Print Chart?"
		#define STR0008 "Date used as printing reference of Comparison Chart."
		#define STR0009 "Smaller branch code considered in the routine."
		#define STR0010 "The field may remain blank to consider since the first branch."
		#define STR0011 "Larger branch code considered in the routine."
		#define STR0012 "The field can be filled in with 'ZZ' or '99' to consider until the last branch."
		#define STR0013 "The Fixed Chart displays the Chart in the NR29, Item 29.2.1.2, Chart I."
		#define STR0014 "Comparison Chart compares Fixed Chart with data from selected branches, identifying missing Sesmt users."
		#define STR0015 "From Customer?"
		#define STR0016 "From Store?"
		#define STR0017 "To Customer?"
		#define STR0018 "To Store?"
		#define STR0019 "ATTENTION"
		#define STR0020 "There are no data to generate the Comparison Chart."
		#define STR0021 "SESMT SESSTP DIMENSIONING"
		#define STR0022 "LEVEL"
		#define STR0023 "FROM"
		#define STR0024 "RISK"
		#define STR0025 "Techniques"
		#define STR0026 "Number of Employees"
		#define STR0027 "in the Establishment"
		#define STR0028 "Above 3,500 "
		#define STR0029 "For each Group"
		#define STR0030 "From 2,000 or fraction"
		#define STR0031 "above 500 (**)"
		#define STR0032 "to"
		#define STR0033 "Safety Technician "
		#define STR0034 "Safety Engineer "
		#define STR0035 "Nursing Assistant "
		#define STR0036 "Nurse from "
		#define STR0037 "Doctor from "
		#define STR0038 "(*) Partial time (minimum of three hours)"
		#define STR0039 "(**) The total dimensioning must be performed"
		#define STR0040 "regarding the dimensioning"
		#define STR0041 "of ranges 3,501 to 5,000 plus dimensioning"
		#define STR0042 "of the group(s) of 4,000 or fraction above 2,000"
		#define STR0043 " Hospitals, Polyclinic, Maternity, Nursing"
		#define STR0044 "Home, Medical Centers and other similar establishments"
		#define STR0045 "with more than 500 (five hundred) employees must"
		#define STR0046 "hire a full time nurse"
		#define STR0047 "Branch: "
		#define STR0048 "Risk Level: "
		#define STR0049 "Total of Employees: "
		#define STR0050 "Company Status"
		#define STR0051 "Need"
		#define STR0052 "Reality"
		#define STR0053 "Work"
		#define STR0054 "NOTE:"
		#define STR0055 "Caption: "
		#define STR0056 "Black - In compliance with"
		#define STR0057 "Red - Out of compliance with"
		#define STR0058 "Start of operation?"
		#define STR0059 "Work estimative taken per year?"
		#define STR0060 "OGMO?"
		#define STR0061 "Number of Temporary Employees previous year ?"
		#define STR0062 "Number of days worked previous year?"
		#define STR0063 "Work monthly average previous calendar year?"
		#define STR0064 "Specialized Professionals"
		#define STR0065 "Specialized Prof."
		#define STR0066 "This parameter is only valid when start operation? is Yes."
		#define STR0067 "This parameter only is valid when parameters Start operation? is No and OGMO? is Yes."
		#define STR0068 "This parameter only is valid when the MDT is not integrated with GPE."
		#define STR0069 "This parameter only is valid when parameters Start operation? is No and OGMO? is Yes."
		#define STR0070 "Hours Consid."
		#define STR0071 "Yes"
		#define STR0072 "No"
		#define STR0073 "Determines if medical calendar is verified."
		#define STR0074 "Consid. Hours?"
		#define STR0075 "Start of operation."
		#define STR0076 "Yes or No."
		#define STR0077 "Workers estimation number to be taken in the year."
		#define STR0078 "Labor Management"
		#define STR0079 "Number of temporary workers hired in the previous year."
		#define STR0080 "Number of days worked in the previous year."
		#define STR0081 "Monthly average of workers in the previous calendar year."
		#define STR0082 "Parameter valid only if MDT is not integrated with GPE."
		#define STR0083 "Define whether the medical form is checked."
	#else
		#define STR0001 "Tabela de Dimensionamento do Sesmt"
		#define STR0002 "Zebrado"
		#define STR0003 "Administração"
		#define STR0004 "Data de Referência ?"
		#define STR0005 "De Filial ?"
		#define STR0006 "Ate Filial ?"
		#define STR0007 "Imprimir Quadro ?"
		#define STR0008 "Data que será usada como referência na impressão do Quadro Comparativo."
		#define STR0009 "Menor código de filial considerado na rotina."
		#define STR0010 "O campo pode permanecer vazio para considerar desde a primeira filial."
		#define STR0011 "Maior código de filial considerado na rotina."
		#define STR0012 "O campo pode ser preenchido com 'ZZ' ou '99' para considerar até a última filial."
		#define STR0013 "O Quadro Fixo mostra o Quadro contido na NR29, item 29.2.1.2,Quadro I."
		#define STR0014 "O Quadro Comparativo compara o Quadro Fixo com os dados das filiais selecionadas, identificando quais usuários Sesmt estão faltando."
		#define STR0015 "De Cliente ?"
		#define STR0016 "De Loja ?"
		#define STR0017 "Até Cliente ?"
		#define STR0018 "Até Loja ?"
		#define STR0019 "ATENÇÃO"
		#define STR0020 "Não existem dados para montar o Quadro Comparativo."
		#define STR0021 "DIMENSIONAMENTO DO SESMT SESSTP"
		#define STR0022 "GRAU"
		#define STR0023 "DE"
		#define STR0024 "RISCO"
		#define STR0025 "Técnicas"
		#define STR0026 "Nº de Empregados"
		#define STR0027 "no Estabelecimento"
		#define STR0028 "Acima de 3.500"
		#define STR0029 "Para cada Grupo"
		#define STR0030 "De 2.000 ou fração"
		#define STR0031 "acima de 500(**)"
		#define STR0032 "a"
		#define STR0033 "Técnico Seg. "
		#define STR0034 "Engenheiro Seg. "
		#define STR0035 "Aux. Enferm. do "
		#define STR0036 "Enfermeiro do "
		#define STR0037 "Médico do "
		#define STR0038 "(*) Tempo parcial (mínimo de três horas)"
		#define STR0039 "(**) O dimensionamento total deverá ser feito"
		#define STR0040 "levando-se em consideração o dimensionamento"
		#define STR0041 "de faixas 3.501 a 5.000 mais o dimensionamento"
		#define STR0042 "do(s) grupo(s) de 4.000 ou fração acima de 2.000."
		#define STR0043 " Hospitais, Ambulatórios, Maternidade, Casas de"
		#define STR0044 "Saúde e Repouso, Clínicas e estabelecimentos similares"
		#define STR0045 "com mais de 500 (quinhentos) empregados deverão"
		#define STR0046 "contratar um enfermeiro em tempo integral"
		#define STR0047 "Filial: "
		#define STR0048 "Grau de Risco: "
		#define STR0049 "Total de Funcionários: "
		#define STR0050 "Situação da Empresa"
		#define STR0051 "Necessidade"
		#define STR0052 "Realidade"
		#define STR0053 "Trabalho"
		#define STR0054 "OBS:"
		#define STR0055 "Legenda: "
		#define STR0056 "Preto - Dentro dos Conformes"
		#define STR0057 "Vermelho - Fora dos Conformes"
		#define STR0058 "Inicio de operação?"
		#define STR0059 "Estimativa trab. tomados ano ?"
		#define STR0060 "OGMO?"
		#define STR0061 "Num. trab. avulsos ano ant. ?"
		#define STR0062 "Num. dias efet. do ano ant.?"
		#define STR0063 "Méd. mens. do ano civ. ant.?"
		#define STR0064 "Profissionais Especializados"
		#define STR0065 "Profis. Especializados"
		#define STR0066 "Esse parâmetro somente é valido quando o 'Inicio operação?' for 'Sim'."
		#define STR0067 "Esse parâmetro somente é valido quando o parâmetros 'Inicio operação?' for 'Não' e o 'OGMO?' forem 'Sim'."
		#define STR0068 "Esse parâmetro somente é valido quando o MDT não esta integrado com o GPE."
		#define STR0069 "Esse parâmetro somente é valido quando o parâmetro 'Inicio operação?' for 'Sim' e 'OGMO?' for 'Não'."
		#define STR0070 "Consid. Hrs."
		#define STR0071 "Sim"
		#define STR0072 "Não"
		#define STR0073 "Determina se será verificado o calendário médico."
		#define STR0074 "Consid. Horas ?"
		#define STR0075 "Início de operação."
		#define STR0076 "Sim ou Não."
		#define STR0077 "Número da estimativa de trabalhadores a serem tomados no ano."
		#define STR0078 "Órgão Gestor de Mão de Obra."
		#define STR0079 "Número de Trabalhadores avulsos escalados no ano anterior."
		#define STR0080 "Número de dias efetivamente trabalhados no ano anterior."
		#define STR0081 "Média mensal de trabalhadores no ano civil anterior."
		#define STR0082 "Parâmetro válido somente se o MDT não estiver integrado com o GPE."
		#define STR0083 "Determina se será verificado o calendário médico."
	#endif
#endif
