#ifdef SPANISH
	#define STR0001 "Importación de abastecimiento."
	#define STR0002 "Atención"
	#define STR0003 "Siga atentamente los pasos de este asistente"
	#define STR0004 "Fin del procesamiento."
	#define STR0005 "Por medio de este asistente será posible realizar la importación de registros de abastecimiento para los layouts"
	#define STR0006 " configurados previamente en el sistema."
	#define STR0007 "Antes de confirmar la ejecución del proceso, se recomienda realizar una copia de seguridad de los"
	#define STR0008 " archivos/tablas TR6 en uso. Si ocurre algún problema durante la ejecución del proceso, las copias"
	#define STR0009 " de seguridad deben restaurarse."
	#define STR0010 "El proceso puede demorar algún tiempo para ejecutarse."
	#define STR0011 "Haga clic en avanzar para continuar."
	#define STR0012 "Utilice la siguiente consulta para seleccionar el tipo de layout de abastecimiento que se importará."
	#define STR0013 "Después de seleccionar el layout, haga clic en avanzar para seleccionar el archivo."
	#define STR0014 "Registro incluido con éxito. Haga clic en finalizar para salir."
	#define STR0015 "Seleccione el código del layout"
	#define STR0016 "ATENCIÓN"
	#define STR0017 "Seleccione el archivo (Bienes)."
	#define STR0018 "No fue posible copiar el archivo en la carpeta temporal: "
	#define STR0019 "Archivo "
	#define STR0020 " no se encontró."
	#define STR0021 "El proceso se anulará."
	#define STR0022 "Espere...Importando abastecimiento."
	#define STR0023 "Abastecimiento "
	#define STR0024 " Importada con éxito."
	#define STR0025 "Importando registro: "
	#define STR0026 "Cantidad de campos del archivo es incompatible con la configuración del layout"
	#define STR0027 "Ya existe un abastecimiento con el número de abastecimiento: "
	#define STR0028 "La importación no se concluyó. Haga clic en finalizar para salir."
	#define STR0029 "Se encontraron errores en la importación."
	#define STR0030 "¿Desea imprimir?"
	#define STR0031 "El archivo importado tiene menos campos que el layout informado. Verifique las configuraciones."
	#define STR0032 "Se encontró un error inesperado en la ejecución de la importación. Estos puede haber ocurrido por mal funcionamiento del sistema, función de usuario o por importar un archivo diferente del layout informado. Por favor, entre en contacto con el administrador del sistema."
	#define STR0033 "Ya existe un abastecimiento para este vehículo."
	#define STR0034 "Estándar del campo numérico inválido."
	#define STR0035 "Error en la importación"
	#define STR0036 "Separado por "
	#define STR0037 "Cód. Layout..: "
	#define STR0038 "Tabla Prin...: "
	#define STR0039 "Formato fecha: "
	#define STR0040 "Sep. Decimal.: "
	#define STR0041 "Línea"
	#define STR0042 "Mensaje"
	#define STR0043 "Registro"
	#define STR0044 "Formato de fecha inválido o fecha inexistente."
	#define STR0045 " no importado"
	#define STR0046 "No existen líneas para importar, de acuerdo con el layout."
	#define STR0047 "Tamaño del TXT es mayor que la aceptación por el layout. Por favor, verifique las configuraciones."
	#define STR0048 "El estándar del campo no es numérico."
	#define STR0049 "Programa disponible en build superior a 7.00.131227A con fecha de generación superior al 08/09/2014."
#else
	#ifdef ENGLISH
		#define STR0001 "Refueling Import"
		#define STR0002 "Attention"
		#define STR0003 "Carefully follow the steps presented by this wizard."
		#define STR0004 "End of Processing"
		#define STR0005 "Through this wizard you may import fueling records for the layouts."
		#define STR0006 " preset in the system."
		#define STR0007 "Before confirming execution of the process, back up"
		#define STR0008 " TR6 files/tables in use.  If there is any problems during the process, back-ups"
		#define STR0009 " must be restored."
		#define STR0010 "This process may take a while to finish."
		#define STR0011 "Click Next to proceed."
		#define STR0012 "Use query below to select a type of refueling layout to import."
		#define STR0013 "After selecting the layout, click Next to select file."
		#define STR0014 "Record successfully added. Click Finish to exit."
		#define STR0015 "Select Layout Code"
		#define STR0016 "ATTENTION"
		#define STR0017 "Select the File (Assets)"
		#define STR0018 "File could not be copied to the temporary folder: "
		#define STR0019 "File "
		#define STR0020 " not found."
		#define STR0021 "Process will be canceled."
		#define STR0022 "Wait... Importing refueling."
		#define STR0023 "Refueling "
		#define STR0024 " Successfully Imported."
		#define STR0025 "Importing Record: "
		#define STR0026 "Number of fields of the file is not compatible with layout configuration"
		#define STR0027 "There is a refueling with refueling number: "
		#define STR0028 "Import not completed. Click Finish to exit."
		#define STR0029 "Errors were found during import."
		#define STR0030 "Print?"
		#define STR0031 "Imported file has fewer fields than layout. Check configurations."
		#define STR0032 "There was an unexpected error during import. It may be due to system malfunction, user role or importing a file different from the layout entered. Try again or contact the system administrator."
		#define STR0033 "There is already a refueling for this vehicle"
		#define STR0034 "Numeric field default not valid"
		#define STR0035 "Error in import"
		#define STR0036 "Separated by "
		#define STR0037 "Layout Code: "
		#define STR0038 "Main table: "
		#define STR0039 "Date format: "
		#define STR0040 "Decimal sep.: "
		#define STR0041 "Row"
		#define STR0042 "Message"
		#define STR0043 "Record"
		#define STR0044 "Invalid date format or inexistent date."
		#define STR0045 " not imported"
		#define STR0046 "There are no rows to import according to the layout."
		#define STR0047 "Size of TXT is greater than the accepted by the layout. Check configuration."
		#define STR0048 "Field default is not numeric."
		#define STR0049 "Program only available in build later than 7.00.131227A with generation date later than 09/08/2014"
	#else
		#define STR0001 "Importação de Abastecimento."
		#define STR0002 "Atenção"
		#define STR0003 "Siga atentamente os passos deste assistente"
		#define STR0004 "Término do Processamento."
		#define STR0005 "Através desse assistente será possível realizar a importação de registros de abastecimento para os layouts"
		#define STR0006 " pré-configurados no sistema."
		#define STR0007 "Antes de confirmar a execução do processo recomenda-se realizar uma cópia de segurança dos"
		#define STR0008 " arquivos/tabelas TR6 em uso. Caso ocorra algum problema durante a execução do processo, as cópias"
		#define STR0009 " de segurança devem ser restauradas."
		#define STR0010 "O processo pode demorar algum tempo para ser executado."
		#define STR0011 "Clique em avançar para continuar."
		#define STR0012 "Utilize a consulta abaixo para selecionar o tipo de layout de abastecimento a ser importado."
		#define STR0013 "Após selecionar o Layout clique em avançar para selecionar o arquivo."
		#define STR0014 "Registro incluido com sucesso. Clique em finalizar para sair."
		#define STR0015 "Selecione o Código de Layout"
		#define STR0016 "ATENCAO"
		#define STR0017 "Selecione o Arquivo (Bens)."
		#define STR0018 "Não foi possível copiar o arquivo para a pasta temporária: "
		#define STR0019 "Arquivo "
		#define STR0020 " não encontrado."
		#define STR0021 "O processo sera cancelado."
		#define STR0022 "Aguarde...Importanto Abastecimento."
		#define STR0023 "Abastecimento "
		#define STR0024 " importado com sucesso."
		#define STR0025 "Importando Registro: "
		#define STR0026 "Quantidade de campos do arquivo incompativel com a configuração do layout"
		#define STR0027 "Já existe um abastecimento com o número de abastecimento: "
		#define STR0028 "A importação não foi concluída. Clique em finalizar para sair."
		#define STR0029 "Foram encontrados erros na importacao."
		#define STR0030 "Deseja Imprimir?"
		#define STR0031 "O Arquivo importado possui menos campos que o layout informado. Verifique as configurações."
		#define STR0032 "Foi encontrado um erro inesperado na execução da importação. Isso pode ter ocorrido por mau funcionamento do sistema, função de usúario ou por importar um arquivo diferente do layout informado. Tente novamente, ou entre em contato com o administrador do sistema."
		#define STR0033 "Já existe um abastecimento para esse veículo."
		#define STR0034 "Padrão do Campo Numérico Inválido."
		#define STR0035 "Erro na Importação"
		#define STR0036 "Separado por "
		#define STR0037 "Cód. Layout..: "
		#define STR0038 "Tabela Prin...: "
		#define STR0039 "Formato Data: "
		#define STR0040 "Sep. Decimal.: "
		#define STR0041 "Linha"
		#define STR0042 "Mensagem"
		#define STR0043 "Registro"
		#define STR0044 "Formato da Data Inválido ou data inexistente."
		#define STR0045 " não importado"
		#define STR0046 "Não existem linhas para serem importadas de acordo com o Layout."
		#define STR0047 "Tamanho do TXT é maior que o aceito pelo layout. Favor verificar as configurações."
		#define STR0048 "O Padrão do campo não é númerico."
		#define STR0049 "Programa disponível somente em build superior a 7.00.131227A com data de geração superior a 08/09/2014."
	#endif
#endif
