#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Multa de Transito"
	#define STR0007 "Multa por Producto Peligroso"
	#define STR0008 "Debe rellenarse el campo Nº Factura"
	#define STR0009 "Debe rellenarse el campo Fecha Emis. Factura"
	#define STR0010 "Debe rellenarse el campo Sucursal Fatur"
	#define STR0011 "¡Deben rellenarse todos los campos de la carpeta!"
	#define STR0012 "No podran registrarse multas con Fecha, Hora, Infraccion y Placa iguales"
	#define STR0013 "ATENCION"
	#define STR0014 "Infraccion informada debe ser del tipo (Multa por Accidente)"
	#define STR0015 "Infraccion informada debe ser del tipo (Multa por Producto Peligroso)"
	#define STR0016 "Conductor"
	#define STR0017 "Empresa"
	#define STR0018 "Persona Fisica"
	#define STR0019 "Persona Juridica y fisica"
	#define STR0020 "Aseguradora"
	#define STR0021 "Clasificacion de la Multa"
	#define STR0022 "¿Tipo Multa?"
	#define STR0023 "Confirmar"
	#define STR0024 "Identificacion del Tipo de multa en el codigo es invalida. La Primera posicion del Codigo de la Multa debe ser T(Multa por Accidente) O P(Multa por Producto Peligroso)"
	#define STR0025 "Identificacion del Tipo de multa en el codigo es invalido. La Primera posicion del Codigo da Multa debe ser T(Multa por Accidente)"
	#define STR0026 "Identificacion del Tipo de multa en el codigo es invalido. La Primera posicion del Codigo de la Multa debe ser P(Multa por Producto Peligroso)"
	#define STR0027 "Campo 'Fch. Ef. Rest' debe ser superior al campo 'Fch Solicit.'"
	#define STR0028 "¡Campo 'Fch. Ef. Rest' debe rellenarse!"
	#define STR0029 "Fecha de Indicacion del Conductor no puede ser inferior a la Fecha de la Infraccion!"
	#define STR0030 "Fecha de Entrada de Recurso no puede ser inferior a la Fecha de la Infraccion!"
	#define STR0031 "¡Fecha de Entr Rec. 2 no puede ser inferior a la Fecha Fin Rec.!"
	#define STR0032 "¡Fecha de Solicitud da Restitucion debe ser superior a la Fecha de Finalizacion del Recurso en primeera instancia!"
	#define STR0033 "¡Fecha de Solicitud de la Restitucion debe ser superior a la Fecha de Finalizacion del Recurso en segunda instancia!"
	#define STR0034 "¡Fecha de Entr Recurso no podra ser superior a la Fecha Fin Rec.!"
	#define STR0035 "¡Fecha de Entr Rec. 2 no podra ser superior a la Fecha Fin Rec2!"
	#define STR0036 "Transportista"
	#define STR0037 "Expedidor"
	#define STR0038 "Facturas"
	#define STR0039 "Leyenda"
	#define STR0040 "¿El viaje es con tercero?"
	#define STR0041 "TRANSITO"
	#define STR0042 "PRODUCTO PELIGROSO"
	#define STR0043 "¡Vehiculos terceros/agregados no podran aceptarse en Multa de Transito!"
	#define STR0044 "Multa pagada sin recurso"
	#define STR0045 "Multa pagada con recurso Pendiente"
	#define STR0046 "Multa pagada con recurso Deferido"
	#define STR0047 "Multa no pagada sin recurso"
	#define STR0048 "Multa no pagada con recurso Pendiente"
	#define STR0049 "Multa no pagada con recurso Deferido"
	#define STR0050 "Consulta de Facturas solo para Multas por Productos Peligrosos."
	#define STR0051 "Tránsito"
	#define STR0052 "Prod. Peligroso"
	#define STR0053 "El campo Tp Infraccion debe ser igual a "
	#define STR0054 "Esta multa  se registro para la sucursal "
	#define STR0055 "Factura"
	#define STR0056 "¡Ya existe una multa con el codigo informado!"
	#define STR0057 "El Sistema de Mantenimiento de Activos vs. Gestión de Flotas tiene"
	#define STR0058 "incompatibilidad de diccionario."
	#define STR0059 "Por favor, ejecute la funcion UPDMNT39. Para más informaciones, consulte el"
	#define STR0060 "Boletin Tecnico numero 18102/2009"
	#define STR0061 "NO CONFORMIDAD"
	#define STR0062 "El campo "
	#define STR0063 " debe rellenarse."
	#define STR0064 "Cuando no hay recurso este campo no debe informarse"
	#define STR0065 "Ya existe recurso habilitado para la multa."
	#define STR0066 "Ya existe pedido de restitucion habilitado para la multa."
	#define STR0067 "¿Desea continuar?"
	#define STR0068 "El Valor de la Multa se modificara."
	#define STR0069 "El Responsable por la Multa diverge del Responsable por la Infraccion."
	#define STR0070 "Multa: "
	#define STR0071 "Infraccion: "
	#define STR0072 "¿Confirmar?"
	#define STR0073 "La fecha del pago debe ser igual o superior a la fecha de la infraccion e igual o inferior a la fecha actual."
	#define STR0074 "Incluya una fecha de pago que este entre la fecha de la infraccion y la fecha actual."
	#define STR0075 "Multa no pagada con recurso Denegado"
	#define STR0076 "Multa pagada con un recurso denegado"
	#define STR0077 "El Organismo fiscalizador seleccionado no tiene Proveedor."
	#define STR0078 "Informe un organismo fiscalizador con proveedor o haga el registro por medio de la rutina Organismos fiscalizadores (MNTA775)."
	#define STR0079 "Fecha de emision no puede ser menor que la Fecha de la infraccion."
	#define STR0080 "Cuotas"
	#define STR0081 "NOTIFICACION"
	#define STR0082 "No se cumplieron las condiciones necesarias para la generacion de las cuotas."
	#define STR0083 "Informe la Condicion de pago, Fecha de emision y el Valor."
	#define STR0084 "No existen cuotas vinculadas al registro actual."
	#define STR0085 "Confirme las cuotas"
	#define STR0086 "El valor de las cuotas "
	#define STR0087 "R$"
	#define STR0088 " difiere del valor total "
	#define STR0089 "La Fecha de vencimiento no debe ser menor que la Fecha de emision."
	#define STR0090 "La Fecha de vencimiento de la cuota actual debe ser mayor que la de la cuota anterior."
	#define STR0091 "La "
	#define STR0092 " esta vinculada a una Multa."
	#define STR0093 "¿Desea cargar los datos de la notificacion?"
	#define STR0094 "DESC. "
	#define STR0095 " HASTA EL VENC."
	#define STR0096 "Seleccionando registros..."
	#define STR0097 "Algun campo obligatorio"
	#define STR0098 "para generar la Cuenta por Pagar no se relleno."
	#define STR0099 "El porcentaje de descuento informado no puede ser mayor o igual al 100%."
	#define STR0100 "El valor de descuento informado no puede ser mayor o igual al valor de la multa."
	#define STR0101 "Conocimiento"
	#define STR0102 "Multa no se debe borrar porque la fecha de emisión es menor que la fecha límite de cierre financiero."
	#define STR0103 "NOTIFICACIÓN"
	#define STR0104 "El tamaño del campo TRX_MULTA está diferente del tamaño del campo TSO_MULTA , lo cual puede ocasionar errores. Por favor, corrija los tamaños vía configurador."
	#define STR0105 "Restituição só poderá ser igual a '2 - Não' quando a multa não conter um recurso ou um recurso com situação igual a 'PENDENTE' "
	#define STR0106 "Restituição só poderá ser igual a '1 - Sim' quando a multa conter um recurso com situação diferente de 'PENDENTE' "
	#define STR0107 "Esta rutina pasó recientemente por una actualización importante."
	#define STR0108 "Se solicita la aplicación del paquete de diccionario indicado en la FAQ MNT0124."
	#define STR0109 "Analizando Módulo Financiero"
	#define STR0110 "Espere"
	#define STR0111 "Este Nº  Título se está utilizando."
	#define STR0112 "El tipo informado no es válido."
	#define STR0113 "Es necesario debido al proceso de movilidad (MV_NGINTMB)."
	#define STR0114 "No es posible modificar el descuento, pues ya existe una cuota pagada u otra factura generada."
	#define STR0115 "No es posible agrupar títulos generados por el módulo de mantenimiento de activos."
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Traffic Fine"
		#define STR0007 "Fine by Dangerous Product"
		#define STR0008 "Invoice field must be filled in."
		#define STR0009 "Invoice Issue Dt. field must be filled in."
		#define STR0010 "Inv. Branch field must be filled in."
		#define STR0011 "All fields from Payment folder must be filled in!"
		#define STR0012 "Fines with the Date, Time, Violation and Plate cannot be registered"
		#define STR0013 "ATTENTION"
		#define STR0014 "Violation entered must be Fine by Accident"
		#define STR0015 "Violation entered must be Fine by Dangerous Product"
		#define STR0016 "Driver"
		#define STR0017 "Company"
		#define STR0018 "Natural Person"
		#define STR0019 "Legal entity and natural person"
		#define STR0020 "Insurance company"
		#define STR0021 "Fine Classification"
		#define STR0022 "Fine Type ?"
		#define STR0023 "Confirm"
		#define STR0024 "Identification of fine type in code is invalid. Firt position of the Fine Code must be T(Fine by Accident) or P(Fine by Dangerous Product)"
		#define STR0025 "Identification of fine type in code is invalid. Firt position of the Fine Code must be T(Fine by Accident)"
		#define STR0026 "Identification of fine type in code is invalid. Firt position of the Fine Code must be P(Fine by Dangerous Product)"
		#define STR0027 "The 'Reimb. Dt.' field must be higher than the 'Req. Dt.'"
		#define STR0028 "Fill in the field 'Reimb. Dt.'!"
		#define STR0029 "Driver Indication Date cannot be earlier than the Violation Date!"
		#define STR0030 "Appeal Entry Date cannot be earilier than the Violation Date!"
		#define STR0031 "Appeal Entry Date 2 cannot be earlier than the End Appeal Date!"
		#define STR0032 "Reimbursement Request Date cannot be later than the Appeal Finishing Date in first stage!"
		#define STR0033 "Reimbursement Request Date cannot be later than the Appeal Finishing Date in second stage!"
		#define STR0034 "Appeal Entry Date cannot be later than the End Appeal Date!"
		#define STR0035 "Appeal Entry Date 2 cannot be later than the End Appeal Date 2!"
		#define STR0036 "Carrier"
		#define STR0037 "Dispatcher"
		#define STR0038 "Invoices"
		#define STR0039 "Caption"
		#define STR0040 "Trip is with a third party?"
		#define STR0041 "TRAFFIC"
		#define STR0042 "DANGEROUS PRODUCT"
		#define STR0043 "Third parties/associated vehicles are not accepted in Traffic Fine!"
		#define STR0044 "Fine paid with no appeal"
		#define STR0045 "Fine paid with pending appeal"
		#define STR0046 "Fine paid with Granted appeal"
		#define STR0047 "Fine not paid without appeal"
		#define STR0048 "Fine not paid with Pending appeal"
		#define STR0049 "Fine not paid with Granted appeal"
		#define STR0050 "Invoice Query only for Fines by Dangerous Products."
		#define STR0051 "Traffic"
		#define STR0052 "Dangerous Prod."
		#define STR0053 "The Violation Tp field must be equal to "
		#define STR0054 "This fine is already registered for branch "
		#define STR0055 "invoice"
		#define STR0056 "There is already a fine with the code indicated!"
		#define STR0057 "System of Fleet Management x Active Maintenance shows"
		#define STR0058 "dictionary incompatibility."
		#define STR0059 "Please, run function UPDMNT39. For further information, check"
		#define STR0060 "Technical Newsletter number 18102/2009"
		#define STR0061 "NON-COMPLIANCE"
		#define STR0062 "The field "
		#define STR0063 " must be filled out."
		#define STR0064 "When there is no resource, this field must not be entered"
		#define STR0065 "There is already an enabled resource for the fine."
		#define STR0066 "There is already an enabled reimbursement order for the fine."
		#define STR0067 "Do you want to continue?"
		#define STR0068 "The fine amount will be changed."
		#define STR0069 "The responsible for the Ticket is different from the responsible for the Infraction."
		#define STR0070 "Fine:  "
		#define STR0071 "Infraction: "
		#define STR0072 "Confirm?"
		#define STR0073 "Payment Date must be later than or equal to the Violation Date and earlier than or equal to the Current Date."
		#define STR0074 "Enter a Payment Date between the Violation Date and the Current Date."
		#define STR0075 "Fine not paid with Rejected resource"
		#define STR0076 "Fine paid with Denied appeal"
		#define STR0077 "Notifying Authority selected does not have Supplier."
		#define STR0078 "Enter a notifying authority with a supplier, or register it in the Notifying Authority (MNTA775)."
		#define STR0079 "Issue Date cannot be earlier than Violation Date."
		#define STR0080 "Installments"
		#define STR0081 "NOTIFICATION"
		#define STR0082 "The necessary conditions to generate the installments were not fulfilled."
		#define STR0083 "Enter the Payment Terms, the Issue Date and Value."
		#define STR0084 "There are no installments associated to the current record."
		#define STR0085 "Confirm the installments"
		#define STR0086 "Installment value "
		#define STR0087 "R$"
		#define STR0088 " differs from the total "
		#define STR0089 "Due Date cannot be earlier than the Issue Date."
		#define STR0090 "Installment Due Date cannot be earlier than the date of the previous installments."
		#define STR0091 "The "
		#define STR0092 " is already associated to a Ticket!"
		#define STR0093 "Do you want to load data from the notification?"
		#define STR0094 "DISC. "
		#define STR0095 " Until Due Date"
		#define STR0096 "Selecting Records..."
		#define STR0097 "Some required field"
		#define STR0098 "for Account Payable generation is not completed!"
		#define STR0099 "The entered percentage discount cannot be greater or equal to 100%."
		#define STR0100 "Planned AVP value entered cannot be greater than or equal to the original value."
		#define STR0101 "Knowledge"
		#define STR0102 "The fine cannot be deleted because the issue date is earlier than the limit date of finance closure."
		#define STR0103 "NOTIFICATION"
		#define STR0104 "Size of field TRX_MULTA is different from size of TSO_MULTA, which mat cause errors. Correct sizes via Configurator."
		#define STR0105 "Refund can only be equal to '2 - No' when the fine does not contain an appeal or an appeal with status 'PENDING' "
		#define STR0106 "Refund can only be equal to '1 - Yes' when the fine does not contain an appeal with status other than 'PENDING' "
		#define STR0107 "This routine was recently updated."
		#define STR0108 "We request the application of the dictionary package indicated in FAQ MNT0124."
		#define STR0109 "Analyzing Financial Module"
		#define STR0110 "Wait"
		#define STR0111 "This Bill No. is already being used."
		#define STR0112 "The type informed is invalid."
		#define STR0113 "It is needed due to the process of mobility (MV_NGINTMB)."
		#define STR0114 "Unable to change discount because an installment is already paid or another invoice generated."
		#define STR0115 "Unable to combine bills generated by the asset maintenance module."
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Multa De Trânsito", "Multa de Trânsito" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Multa Por Artigo Perigoso", "Multa por Produto Perigoso" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "O campo nr. factura deverá ser preenchido", "O campo Nro Nota Fis deverá ser preenchido" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "O campo dt. emis. factura deverá ser preenchido", "O campo Dt. Emis. NF deverá ser preenchido" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "O campo filial factura deverá ser preenchido", "O campo Filial Fatur deverá ser preenchido" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Todos os campos da folha de pagamento deverão ser preenchidos!", "Todos campos do folder Pagamento deverão ser preenchidos!" )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Não poderão ser registadas multas com data, hora, infracção e matrícula iguais", "Não poderão ser registradas multas com Data, Hora, Infração e Placa iguais" )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Atenção", "ATENÇÃO" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "A Infracção Digitada Deve Ser Do Tipo (multa Por Acidente)", "Infração informada deve ser do tipo (Multa por Acidente)" )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "A Infracção Digitada Deve Ser Do Tipo (multa Por Artigo Perigoso)", "Infração informada deve ser do tipo (Multa por Produto Perigoso)" )
		#define STR0016 "Motorista"
		#define STR0017 "Empresa"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Pessoa Física", "Pessoa Fisica" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Pessoa colectiva e singular", "Pessoa Juridica e fisica" )
		#define STR0020 "Seguradora"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Classificação Da Multa", "Classificação da Multa" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Tipo de multa ?", "Tipo Multa ?" )
		#define STR0023 "Confirmar"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "A Identificação Do Tipo De Multa No Código é Inválida. A Primeira Posição Do Código Da Multa Deve Ser T(multa Por Acidente) Ou P(multa Por Artigo Perigoso)", "Identificado do Tipo de multa no código é inválido. A Primeira posição do Código da Multa deve ser T(Multa por Acidente) Ou P(Multa por Produto Perigoso)" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "A Identificação Do Tipo De Multa No Código é Inválida. A Primeira Posição Do Código Da Multa Deve Ser T(multa Por Acidente)", "Identificado do Tipo de multa no código é inválido. A Primeira posição do Código da Multa deve ser T(Multa por Acidente)" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "A Identificação Do Tipo De Multa No Código é Inválido. A Primeira Posição Do Código Da Multa Deve Ser P(multa Por Artigo Perigoso)", "Identificado do Tipo de multa no código é inválido. A Primeira posição do Código da Multa deve ser P(Multa por Produto Perigoso)" )
		#define STR0027 "Campo 'Dt. Ef. Rest' deverá ser maior que campo 'Dt Solicit.'"
		#define STR0028 "Campo 'Dt. Ef. Rest' deverá ser preenchido!"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "A Data De Identificação Do Condutor Não Pode Ser Anterior à Data Da Infracção!", "Data de Indicação do Condutor não pode ser menor que a Data da Infração!" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "A Data De Entrada De Recurso Não Pode Ser Anterior à Data Da Infracção!", "Data de Entrada de Recurso não pode ser menor que a Data da Infração!" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "A Data De Entrada De Recurso 2 Não Pode Ser Anterior à última Data Do Recurso!", "Data de Entr Rec. 2 não pode ser menor que a Data Fim Rec.!" )
		#define STR0032 "Data de Solicitação da Restituição deverá ser maior que Data de Finalização do Recurso em primeira instância!"
		#define STR0033 "Data de Solicitação da Restituição deverá ser maior que Data de Finalização do Recurso em segunda instância!"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "A Data De Entr. Recurso Não Poderá Ser Posterior à última Data Do Rec.!", "Data de Entr Recurso não poderá ser maior que a Data Fim Rec.!" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "A Data De Entr. Rec. 2 Não Poderá Ser Posterior à última Data Do Rec. 2!", "Data de Entr Rec. 2 não poderá ser maior que a Data Fim Rec2!" )
		#define STR0036 "Transportador"
		#define STR0037 "Expedidor"
		#define STR0038 "Notas Fiscais"
		#define STR0039 "Legenda"
		#define STR0040 "A viagem é com terceiro?"
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Trânsito", "TRANSITO" )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Artigo Perigoso", "PRODUTO PERIGOSO" )
		#define STR0043 "Veículos terceiros/agregados não poderão serem aceitos em Multa de Trânsito!"
		#define STR0044 "Multa paga sem recurso"
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Multa Paga Com Recurso Pendente", "Multa paga com recurso Pendente" )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Multa Paga Com Recurso Deferido", "Multa paga com recurso Deferido" )
		#define STR0047 "Multa não paga sem recurso"
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Multa Não Paga Com Recurso Pendente", "Multa não paga com recurso Pendente" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Multa Não Paga Com Recurso Deferido", "Multa não paga com recurso Deferido" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Consulta De Facturas Apenas Para Multas De Artigos Perigosos.", "Consulta de Notas Fiscais apenas para Multas por Produtos Perigosos." )
		#define STR0051 "Trânsito"
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Artigo Perigoso", "Prod. Perigoso" )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "O campo tp infracção deverá ser igual a ", "O campo Tp Infracao deverá ser igual a " )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Essa multa já esta registada para a filial ", "Essa multa já esta cadastrada para a filial " )
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Nr. Fiscal", "N. Fiscal" )
		#define STR0056 "Já existe uma multa com o código informado!"
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "O Sistema de Manutenção de Activos x Gestão de Frotas possui", "O Sistema de Manutenção de Ativos x Gestão de Frotas possui" )
		#define STR0058 "incompatibilidade de dicionário."
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Favor execute a função UPDMNT39. Para mais informações consulte o", "Favor execute a função UPDMNT39. Para maiores informações consulte o" )
		#define STR0060 "Boletim Técnico de número 18102/2009"
		#define STR0061 "NÃO CONFORMIDADE"
		#define STR0062 "O campo "
		#define STR0063 " deverá ser preenchido."
		#define STR0064 "Quando não há recurso esse campo não deve ser informado"
		#define STR0065 "Já existe recurso habilitado para a multa."
		#define STR0066 "Já existe pedido de restituição habilitado para a multa."
		#define STR0067 "Deseja prosseguir?"
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "O valor da multa será modificado.", "O Valor da Multa será alterado." )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "O Responsável pela Multa diverge do Responsável pela Infracção.", "O Responsável pela Multa diverge do Responsável pela Infração." )
		#define STR0070 "Multa: "
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Infracção: ", "Infração: " )
		#define STR0072 "Confirmar?"
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "A Data do Pagamento deve ser igual ou superior à Data da Infracção e igual ou inferior a Data Actual.", "A Data do Pagamento deve ser igual ou superior a Data da Infração e igual ou inferior a Data Atual." )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Insira uma Data de Pagamento que esteja entre a Data de Infracção e a Data Actual.", "Insira uma Data de Pagamento que esteja entre a Data de Infração e a Data Atual." )
		#define STR0075 "Multa não paga com recurso Indeferido"
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Multa paga com recurso indeferido", "Multa paga com recurso Indeferido" )
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "O órgão autuador seleccionado não possui fornecedor.", "O Orgão Autuador selecionado não possui Fornecedor." )
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "Informe um órgão autuador com fornecedor ou registe através do procedimento de Órgãos Autuadores (MNTA775).", "Informe um órgão autuador com fornecedor, ou cadastre através da rotina de Órgãos Autuadores (MNTA775)." )
		#define STR0079 If( cPaisLoc $ "ANG|PTG", "Data de emissão não pode ser menor que a data da infração.", "Data de Emissão não pode ser menor que a Data da Infração." )
		#define STR0080 "Parcelas"
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "NOTIFICAÇÃO", "NOTIFICACAO" )
		#define STR0082 "As condições necessárias para a geração das parcelas não foram atendidas."
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "Informe a condição de pagamento, data de emissão e o valor.", "Informe a Condição de Pagamento, Data de Emissão e o Valor." )
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Não existem parcelas relacionadas ao registo actual.", "Não existem parcelas relacionadas ao registro atual." )
		#define STR0085 "Confirme as parcelas"
		#define STR0086 "O valor das parcelas "
		#define STR0087 "R$"
		#define STR0088 " difere do valor total "
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "A data de vencimento não deverá ser menor que data de emissão.", "A Data de Vencimento não deverá ser menor que Data de Emissão." )
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "A data de vencimento da parcela actual deverá ser maior que a da parcela anterior.", "A Data de Vencimento da parcela atual deverá ser maior que a da parcela anterior." )
		#define STR0091 "A "
		#define STR0092 If( cPaisLoc $ "ANG|PTG", " já está relacionada a uma multa.", " já está relacionada à uma Multa!" )
		#define STR0093 "Deseja carregar os dados da notificação?"
		#define STR0094 "DESC. "
		#define STR0095 If( cPaisLoc $ "ANG|PTG", " ATÉ VENC.", " ATE VENC." )
		#define STR0096 If( cPaisLoc $ "ANG|PTG", "A seleccionar registos...", "Selecionando Registros..." )
		#define STR0097 "Algum campo obrigatório"
		#define STR0098 If( cPaisLoc $ "ANG|PTG", "para a geração de Conta a Pagar não foi preenchido.", "para a geração de Conta a Pagar não foi preenchido!" )
		#define STR0099 "A porcentagem de desconto informada não pode ser maior ou igual que 100%."
		#define STR0100 "O valor de desconto informado não pode ser maior ou igual que o valor da multa."
		#define STR0101 "Conhecimento"
		#define STR0102 "Multa não pode ser deletada pois a data de emissão é menor que a data limite de fechamento financeiro."
		#define STR0103 "NOTIFICACAO"
		#define STR0104 "O tamanho do campo TRX_MULTA está diferente do tamanho do campo TSO_MULTA o que pode ocasionar erros. Favor corrigir os tamanhos via configurador."
		#define STR0105 "Restituição só poderá ser igual a '2 - Não' quando a multa não conter um recurso ou um recurso com situação igual a 'PENDENTE' "
		#define STR0106 "Restituição só poderá ser igual a '1 - Sim' quando a multa conter um recurso com situação diferente de 'PENDENTE' "
		#define STR0107 "Essa rotina passou recentemente por uma atualização importante."
		#define STR0108 "Solicita-se a aplicação do pacote de dicionário indicado na FAQ MNT0124."
		#define STR0109 "Analisando Módulo Financeiro"
		#define STR0110 "Aguarde"
		#define STR0111 "Este No. Título já está sendo utilizado."
		#define STR0112 "O tipo informado é inválido."
		#define STR0113 "Necessário devido ao processo de mobilidade (MV_NGINTMB)."
		#define STR0114 "Não é possível alterar o desconto pois já existe uma parcela paga ou outra fatura gerada."
		#define STR0115 "Não é possível aglutinar títulos gerados pelo módulo de manutenção de ativos."
	#endif
#endif
