#ifdef SPANISH
	#define STR0001 "Visualizar"
	#define STR0002 "Incluir"
	#define STR0003 "Modificar"
	#define STR0004 "Revertir"
	#define STR0005 "Borrar"
	#define STR0006 "Atencion"
	#define STR0007 "Para utilizar esta rutina, es obligatorio que el sistema este con la integracion con el Stock habilitado."
	#define STR0008 "Transferencias de Combustible"
	#define STR0009 "Datos de la Transferencia"
	#define STR0010 "Puesto Origen"
	#define STR0011 "Puerto destino"
	#define STR0012 "Situacion del Producto en el Stock de Origen:"
	#define STR0013 "Saldo a Debitar:"
	#define STR0014 "Saldo a Acreditar:"
	#define STR0015 "Saldo luego de la Transferencia:"
	#define STR0016 "Saldo Transferido:"
	#define STR0017 "Solo el Responsable de la Transferencia, o un usuario con autorizacion de Administrador, puede ejecutar esta accion."
	#define STR0018 "Ya existe un asiento para el Contador de la Bomba en esta fecha y hora de la Transferencia."
	#define STR0019 "Este asiento es invalido pues el Contador de la Bomba supero su limite."
	#define STR0020 "Contador:"
	#define STR0021 "Limite:"
	#define STR0022 "La cantidad de combustible para transferir es mayor que la Capacidad Maxima del Puesto del Origen."
	#define STR0023 "La cantidad de combustible para transferir es mayor que la Capacidad Maxima del Puesto del Destino."
	#define STR0024 "Cantidad:"
	#define STR0025 "Capacidad:"
	#define STR0026 "El campo"
	#define STR0027 "no puede contener una fecha mayor que la Fecha Actual del sistema."
	#define STR0028 "no puede contener una fecha mayor que la Hora Actual del sistema."
	#define STR0029 "La Empresa seleccionada es invalida pues no se encuentra en el Archivo de Empresas (SIGAMAT)."
	#define STR0030 "La transferencia solo puede realizarse entre Puestos Internos."
	#define STR0031 "La Bomba debera informarse cuando la Salida de Combustible es por la Bomba."
	#define STR0032 "Informacion: Puesto Origen"
	#define STR0033 "Informacion: Puerto destino"
	#define STR0034 "El saldo de Stock quedara negativo. ¡Operacion invalida!"
	#define STR0035 "Nombre Fantasia: "
	#define STR0036 "Favor informar una hora menor que la actual."
	#define STR0037 "No es posible realizar reversion del registro de transferencia, pues no hubo movimiento de stock."
	#define STR0038 "Operacion invalida"
	#define STR0039 "No existe un registro de Motivo de Transferencia igual al que se definio en el parametro MV_NGMOTTR (Codigo del Motivo de Transferencias de Combustible)."
	#define STR0040 "Configure correctamente el parametro para continuar."
	#define STR0041 "Para el correcto funcionamiento del proceso ExcelBr, el parametro MV_NGDPST9 que indica si podra duplicarse el codigo del Bien debe configurarse con el valor 2(Por Sucursal)."
	#define STR0042 "No es posible realizar la transferencia de combustible al mismo almacen."
	#define STR0043 "El producto de origen que se esta transfiriendo es diferente del produto de destino."
	#define STR0044 "Producto origen :  "
	#define STR0045 "Producto destino:  "
	#define STR0046 "¿Desea continuar asi mismo?"
	#define STR0047 "Modifique el producto de origen o el producto de destino."
	#define STR0048 "Existe(n) estación(es) relacionada(s) a este producto, "
	#define STR0049 " ¿desea actualizar el contador de la bomba?"
	#define STR0050 "Transferencia de combustible."
	#define STR0051 "No se ha seleccionado ninguna estación."
	#define STR0052 "Seleccione una Estación/Tienda para retirar el combustible."
	#define STR0053 "¿Desea no realizar la salida de combustible? "
	#define STR0054 "Si no se realiza, se puede hacer por medio de la rutina de salida de combustible en el módulo de mantenimiento de activos."
#else
	#ifdef ENGLISH
		#define STR0001 "View"
		#define STR0002 "Add"
		#define STR0003 "Edit"
		#define STR0004 "Reverse"
		#define STR0005 "Delete"
		#define STR0006 "Attention"
		#define STR0007 "To use this routine, the system must have the integration with Stock enabled."
		#define STR0008 "Fuel Transfer"
		#define STR0009 "Transfer Data"
		#define STR0010 "Origin Station"
		#define STR0011 "Destination Station"
		#define STR0012 "Status of the Product in the Origin Stock:"
		#define STR0013 "Balance to Debit:"
		#define STR0014 "Balance to Credit:"
		#define STR0015 "Balance after Transfer:"
		#define STR0016 "Transferred Balance:"
		#define STR0017 "Only the person responsible for the Transfer, or a user with administrator rights, may perform this action."
		#define STR0018 "There is already an entry for the Pump Gauge on this transfer date and time."
		#define STR0019 "This entry is invalid since the Pump Gauge has reached its limit."
		#define STR0020 "Counter:"
		#define STR0021 "Limit:"
		#define STR0022 "The amount of fuel to transfer is greater than the Origin Station Maximum Capacity."
		#define STR0023 "The amount of fuel to transfer is greater than the Destination Station Maximum Capacity."
		#define STR0024 "Amount:"
		#define STR0025 "Capacity:"
		#define STR0026 "The field"
		#define STR0027 "cannot have a date later than the system current date."
		#define STR0028 "cannot have a time later than the system current time."
		#define STR0029 "The selected company is invalid since it is not in the Company Register (SIGAMAT)."
		#define STR0030 "Transfere may only be performed between Internal Stations."
		#define STR0031 "The Pump must be indicated when the Fuel Outflow is through the Pump."
		#define STR0032 "Information: Origin Station"
		#define STR0033 "Information: Destination Station"
		#define STR0034 "Inventory Balance will be negative. Invalid operation."
		#define STR0035 "Trade Name: "
		#define STR0036 "Please enter a Time before the current one."
		#define STR0037 "You cannot reverse the transfer record, because no stock transaction occurred."
		#define STR0038 "Invalid operation."
		#define STR0039 "There is no registered Reason for Transfer record equal to the one defined in the MV_NGMOTTR parameter (Code of Reason for Fuel Transfers)."
		#define STR0040 "Correctly configure the parameter to continue."
		#define STR0041 "For the ExcelBr process to work correctly, the MV_NGDPST9 parameter, which indicates whether the Asset code can be duplicated, must be configured with the value 2 (Per Branch)."
		#define STR0042 "Transferring of fuel to the same warehouse is not possible."
		#define STR0043 "The origin product that is transferred is different than the destination product."
		#define STR0044 "Origin Product:  "
		#define STR0045 "Destination Product:  "
		#define STR0046 "Do you want to proceed anyway?"
		#define STR0047 "Change the origin product or the destination product."
		#define STR0048 "There are stations related to this product "
		#define STR0049 " update pump meter?"
		#define STR0050 "Fuel Transfer"
		#define STR0051 "No station selected."
		#define STR0052 "Select station/store for fuel outflow"
		#define STR0053 "Fuel outflow? "
		#define STR0054 "If not, do it through the fuel outflow routine in the asset maintenance module"
	#else
		#define STR0001 "Visualizar"
		#define STR0002 "Incluir"
		#define STR0003 "Alterar"
		#define STR0004 "Estornar"
		#define STR0005 "Excluir"
		#define STR0006 "Atenção"
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Para utilizar este procedimento, é obrigatório que o sistema esteja com a Integração com o Stock habilitada.", "Para utilizar esta rotina, é obrigatório que o sistema esteja com a Integração com o Estoque habilitada." )
		#define STR0008 "Transferências de Combustível"
		#define STR0009 "Dados da Transferência"
		#define STR0010 "Posto Origem"
		#define STR0011 "Posto Destino"
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Situação do artigo no stock de origem:", "Situação do Produto no Estoque de Origem:" )
		#define STR0013 "Saldo a Debitar:"
		#define STR0014 "Saldo a Creditar:"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Saldo após a transferência:", "Saldo após a Transferência:" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Saldo transferido:", "Saldo Transferido:" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Somente o responsável pela transferência ou um utilizador com permissão de administrador pode executar esta acção.", "Somente o Responsável pela Transferência, ou um usuário com permissão de Administrador, pode executar esta ação." )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Já existe um lançamento para o Contador da Bomba nesta data e hora da transferência.", "Já existe um lançamento para o Contador da Bomba nesta data e hora da Transferência." )
		#define STR0019 "Este lançamento é inválido pois o Contador da Bomba superou o seu limite."
		#define STR0020 "Contador:"
		#define STR0021 "Limite:"
		#define STR0022 "A quantidade de combustível a transferir é maior que Capacidade Máxima do Posto de Origem."
		#define STR0023 "A quantidade de combustível a transferir é maior que Capacidade Máxima do Posto de Destino."
		#define STR0024 "Quantidade:"
		#define STR0025 "Capacidade:"
		#define STR0026 "O campo"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "não pode conter uma data maior que a Data Actual do sistema.", "não pode conter uma data maior que a Data Atual do sistema." )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "não pode conter uma hora maior que a Hora Actual do sistema.", "não pode conter uma hora maior que a Hora Atual do sistema." )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "A Empresa seleccionada é inválida pois não se encontra no Registo de Empresas (SIGAMAT).", "A Empresa selecionada é inválida pois não se encontra no Cadastro de Empresas (SIGAMAT)." )
		#define STR0030 "A transferência somente pode ser realizada entre Postos Internos."
		#define STR0031 "A Bomba deverá ser informada quando a Saída de Combustível for pela Bomba."
		#define STR0032 "Informações: Posto Origem"
		#define STR0033 "Informações: Posto Destino"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Saldo do stock ficará negativo. Operação inválida.", "Saldo do Estoque ficará negativo. Operação Inválida." )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Nome comercial: ", "Nome Fantasia: " )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Por favor, informe uma hora menor que a actual.", "Favor informar uma hora menor que a atual." )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Não é possível realizar estorno do registo de transferência, pois não houve movimentação de stock.", "Não é possível realizar estorno do registro de transferência, pois não houve movimentação de estoque." )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Operação inválida", "Operação Inválida" )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Não foi registado um Motivo de Transferência igual ao definido no parâmetro MV_NGMOTTR (Código do Motivo de Transferências de Combustível).", "Não existe cadastrado um registro de Motivo de Transferência igual ao definido no parametro MV_NGMOTTR (Código do Motivo de Transferências de Combustível)." )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Configure correctamente o parâmetro para continuar.", "Configure corretamente o parâmetro para continuar." )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Para o correcto funcionamento do processo ExcelBr, o parâmetro MV_NGDPST9 que indica se poderá duplicar código do Bem deve estar configurado com o valor 2(Por filial).", "Para o correto funcionamento do processo ExcelBr, o parâmetro MV_NGDPST9 que indica se podera duplicar código do Bem deve estar configurado com o valor 2(Por Filial)." )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Não é possível realizar a transferência de combustível para o mesmo armazém.", "Não é possível realizar a transferência de combustível para o mesmo armazem." )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "O artigo de origem que está a ser transferido é diferente do artigo de destino.", "O produto de origem que está sendo transferido é diferente do produto de destino." )
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Artigo origem :  ", "Produto Origem :  " )
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Artigo destino:  ", "Produto Destino:  " )
		#define STR0046 "Deseja continuar assim mesmo?"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Altere o artigo de origem ou o artigo de destino.", "Altere o produto de origem ou o produto de destino." )
		#define STR0048 "Existe Posto(s) relacionado(s) a este produto, "
		#define STR0049 " deseja atualizar o contador da bomba?"
		#define STR0050 "Transferencia de Combustivel"
		#define STR0051 "Nenhuma posto foi selecionado."
		#define STR0052 "Selecione um Posto/Loja para retirada de combustivel."
		#define STR0053 "Deseja não realizar a saida de combustivel ? "
		#define STR0054 "Caso não realizar, pode ser feita pela rotina de saida de combustivel no módulo de manutenção de ativos."
	#endif
#endif
