#ifdef SPANISH
	#define STR0001 "¡No se rellenó el campo de causa!"
	#define STR0002 "Para garantizar la integridad del historial de estatus es necesario informar la fecha de instalación del bien."
	#define STR0003 "La posición informada no puede ser mayor que el límite del contador."
	#define STR0004 "La variación día informada no puede ser mayor que la de la familia. (Contador 1)"
	#define STR0005 "La variación día informada no puede ser mayor que la de la familia. (Contador 2)"
	#define STR0006 "La fecha de compra informada no puede ser mayor que la fecha de garantía."
	#define STR0007 "Categoría del estatus no corresponde a la categoría del bien."
	#define STR0008 "El bien sólo puede asumir situación 'Transferido' a través del proceso de Transferencia."
	#define STR0009 "Para desactivación del mantenimiento es necesario que se finalicen las órdenes de servicio preventivas en abierto."
	#define STR0010 "Para desactivación del bien es necesario que se finalicen las órdenes de servicio en abierto."
	#define STR0011 "Bien está activo en la empresa "
	#define STR0012 " y Sucursal "
	#define STR0013 "Operación no aceptada. El bien forma parte de una estructura."
	#define STR0014 "El bien debe estar inactivo para ser vendido."
	#define STR0015 "El mantenimiento debe estar inactivo para que el bien se venda."
	#define STR0016 "La venta del bien no podrá efectuarse, pues existe(n) OS(s) abierta(s) para él. "
	#define STR0017 "El proceso de exclusión de bienes no se permite cuando la integración del proceso de movilidad esté activada. Verifique el parámetro MV_NGINTMB."
	#define STR0018 "Espere integración con backoffice..."
	#define STR0019 'Problema en el proceso de integración con backoffice.'
	#define STR0020 "El tamaño del campo descripción difiere en las tablas ST9 y SN1, para la integración es necesario que los campos tengan el mismo tamaño."
	#define STR0021 "Al informar un Proveedor, debe completarse el campo Tienda."
#else
	#ifdef ENGLISH
		#define STR0001 "The field cause was not filled out!"
		#define STR0002 "To assure integrity of the status history, you must enter the assets installation date."
		#define STR0003 "Position cannot be greater than counter limit."
		#define STR0004 "Variation day cannot be later than family. (Counter 1)"
		#define STR0005 "Variation day cannot be later than family. (Counter 2)"
		#define STR0006 "Purchase date cannot be after warranty date!"
		#define STR0007 "Status category not corresponding to Asset category."
		#define STR0008 "Assets can only have status Transferred through transfer process."
		#define STR0009 "For the maintenance deactivation, it is necessary to finish the open preventive work orders."
		#define STR0010 "For the asset deactivation, it is necessary to finish the open work orders."
		#define STR0011 "Asset is active in Company "
		#define STR0012 " and branch "
		#define STR0013 "Operation not allowed. The asset is part of a structure."
		#define STR0014 "Asset needs to be inactive to be sold."
		#define STR0015 "Maintenance needs to be inactive for the asset to be sold."
		#define STR0016 "Asset sales cannot be executed, as there are pending SOs."
		#define STR0017 "Deletion process of assets is not allowed if integration of mobility process is enabled. Check the parameter MV_NGINTMB."
		#define STR0018 "Wait integration with backoffice..."
		#define STR0019 'Problem in integration process with backoffice.'
		#define STR0020 "The size of the field description differs in the ST9 and SN1 table, for integration, the fields must have the same size."
		#define STR0021 "When you enter the Supplier, enter the Store as well."
	#else
		#define STR0001 "O campo de causa não foi preenchido"
		#define STR0002 "Para garantir a integridade do historico de status é necessario informar a data de instalação do bem."
		#define STR0003 "A posição informada não pode ser maior que o limite do contador."
		#define STR0004 "A variação dia informada não pode ser maior que a da família. (Contador 1)"
		#define STR0005 "A variação dia informada não pode ser maior que a da família. (Contador 2)"
		#define STR0006 "A data de compra informada não pode ser maior que a data de garantia."
		#define STR0007 "Categoria do Status não corresponde à categoria do Bem."
		#define STR0008 "O bem só pode assumir situação 'Transferido' através do processo de Transferência."
		#define STR0009 "Para inativação da manutenção é necessário que sejam finalizadas as ordens de serviço preventivas em aberto."
		#define STR0010 "Para inativação do bem é necessário que sejam finalizadas as ordens de serviço em aberto."
		#define STR0011 "Bem está ativo na Empresa "
		#define STR0012 " e Filial "
		#define STR0013 "Operacao nao aceita. O bem faz parte de uma estrutura."
		#define STR0014 "O bem precisa estar inativo para ser vendido."
		#define STR0015 "A manutenção precisa estar inativa para o bem ser vendido."
		#define STR0016 "A venda do bem não poderá ser efetuada, pois existe(m) OS(s) aberta(s) para o mesmo"
		#define STR0017 "O processo de exclusão de bens não é permitido caso a integração do processo de mobilidade esteja habilitada. Verifique o parâmetro MV_NGINTMB."
		#define STR0018 "Aguarde integração com backoffice..."
		#define STR0019 'Problema no processo de integração com backoffice.'
		#define STR0020 "O tamanho do campo descrição difere nas tabelas ST9 e SN1, para a integração é necessario que os campos possuam o mesmo tamanho."
		#define STR0021 "Ao informar um Fornecedor deverá preencher o campo Loja."
	#endif
#endif
