#ifdef SPANISH
	#define STR0001 "Horas trabajadas en el mantenimiento"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "¿De periodo?"
	#define STR0005 "¿A periodo?"
	#define STR0006 "¿De Centro Costo   ?"
	#define STR0007 "¿A  Centro Costo   ?"
	#define STR0008 "¿De Especialidad   ?"
	#define STR0009 "¿A  Especialidad   ?"
	#define STR0010 "¿De empleado?"
	#define STR0011 "¿A empleado?"
	#define STR0012 "¿Tipo              ?"
	#define STR0013 "Por Centro Costo"
	#define STR0014 "Por Especialidad"
	#define STR0015 "Por empleado"
	#define STR0016 "Centro Costo"
	#define STR0017 "Especialidad"
	#define STR0018 "Empleado"
	#define STR0019 "Horas disponibles vs Horas realizadas"
	#define STR0020 "&Grafico"
	#define STR0021 "&Imprimir"
	#define STR0022 "Nombre "
	#define STR0023 "Hr. disponibles"
	#define STR0024 "Hr.Realizadas"
	#define STR0025 "DISPONIBLE"
	#define STR0026 "REALIZADO"
	#define STR0027 "No existen datos para montar el grafico."
	#define STR0028 "ATENCION"
	#define STR0029 "Horas disponibles vs Horas trabajadas"
	#define STR0030 "A Rayas"
	#define STR0031 "Administracion"
	#define STR0032 "No existen datos para imprimir..."
	#define STR0033 "C.Costo   Nombre                    Disponible      Realizado        %"
	#define STR0034 "Especia.  Nombre                    Disponible      Realizado        %"
	#define STR0035 "Emplead.  Nombre                    Disponible      Realizado        %"
	#define STR0036 "ANULADO POR EL OPERADOR"
	#define STR0037 "Disponibilidade por "
	#define STR0038 "Total general"
	#define STR0039 "Calendario/Turno"
	#define STR0040 "del empleado"
	#define STR0041 "no registrado"
	#define STR0042 "El proceso se anulara."
	#define STR0043 "Segun especificacion de los parametros,"
	#define STR0044 "no existen datos para mostrarse."
	#define STR0045 "Seleccionando Registros..."
	#define STR0046 "MDO por"
	#define STR0047 "Fecha inicio:"
	#define STR0048 "Data Final:"
	#define STR0049 "Diferencia"
	#define STR0050 "Horas disponibles vs Horas realizadas (por Empleado/Fecha)"
	#define STR0051 "Utilizacion del empleado:"
	#define STR0052 "Fecha"
	#define STR0053 "Horas disponibles vs Horas realizadas (por Empleado)"
	#define STR0054 "Utilizacion por"
	#define STR0055 "Analisis de utilizacion de MDO - Disponible vs Realizado"
	#define STR0056 "Analisis de utilizacion de MDO - Disponible vs Realizado por empleado"
	#define STR0057 "Analisis de utilizacion de MDO - Disponible vs Realizado por Empleado/Fecha"
	#define STR0058 "Código     Nomb          Hrs Disponib.  Bloqueos       Disponib.    Hrs Realiz.   Diferencia             Porcentaje      Horas extras"
	#define STR0059 "Fecha         Horas disponibles     Bloqueos      Disponibilidad      Horas realizadas     Diferencia    Porcentaje     Horas extras"
	#define STR0060 "Hr. Extras"
	#define STR0061 "EXTRA"
	#define STR0062 "Bloqueos"
	#define STR0063 "Disponibilidad"
	#define STR0064 "No existen datos para elaborar la consulta de Disponibilidad."
	#define STR0065 "Porcentaje (%)"
	#define STR0066 "&Salir"
#else
	#ifdef ENGLISH
		#define STR0001 "Hours Worked in Maintenance"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Period from?"
		#define STR0005 "Period To?"
		#define STR0006 "From Cost Center   ?"
		#define STR0007 "To Cost Center     ?"
		#define STR0008 "From Speciality    ?"
		#define STR0009 "To Speciality      ?"
		#define STR0010 "From Employee?"
		#define STR0011 "To Employee?"
		#define STR0012 "Type               ?"
		#define STR0013 "Through Cost Center"
		#define STR0014 "Through Speciality"
		#define STR0015 "By Employee"
		#define STR0016 "Cost Center"
		#define STR0017 "Speciality"
		#define STR0018 "Employee"
		#define STR0019 "Available Hours x Performed Hours"
		#define STR0020 "&Chart"
		#define STR0021 "Pr&int"
		#define STR0022 "Name   "
		#define STR0023 "Available Hr"
		#define STR0024 "Factual Hours"
		#define STR0025 "AVAILABLE"
		#define STR0026 "ACCOMPLISHED"
		#define STR0027 "There are no data to generate the graph."
		#define STR0028 "ATTENTION"
		#define STR0029 "Available Hours x Worked Hours"
		#define STR0030 "Z.Form"
		#define STR0031 "Administration"
		#define STR0032 "There is no data to print..."
		#define STR0033 "Cost C.              Name             Available        Performed             %"
		#define STR0034 "Special.              Name             Available       Accompli.              %"
		#define STR0035 "Employ.             Name              Available       Accompl.             %"
		#define STR0036 "CANCELLED BY THE OPERATOR"
		#define STR0037 "Availability by "
		#define STR0038 "Grand Total"
		#define STR0039 "Schedule/Shift"
		#define STR0040 "employee"
		#define STR0041 "not registered"
		#define STR0042 "The process will be canceled."
		#define STR0043 "According to parameter specification,"
		#define STR0044 "there are no data to be shown."
		#define STR0045 "Selecting Records ...    "
		#define STR0046 "MDO by "
		#define STR0047 "Start Date:"
		#define STR0048 "Final Date:"
		#define STR0049 "Difference"
		#define STR0050 "Available Hours x Performed Hours (per Employee/Date)"
		#define STR0051 "Employee usage:"
		#define STR0052 "Date"
		#define STR0053 "Available Hours x Performed Hours (per Employee)"
		#define STR0054 "Usage by"
		#define STR0055 "Usage analysis MDO - Available x Realized"
		#define STR0056 "Usage analysis MDO - Available x Realized per Employee"
		#define STR0057 "Usage analysis MDO - Available x Realized per Employee/Date"
		#define STR0058 "Code     Name          Hrs Available  Blocks      Available    Hrs. Performed   Difference      Percentage     Overtime"
		#define STR0059 "Date          Available Hours        Blocks         Availability         Realized Hours        Difference     Percentage    Overtime"
		#define STR0060 "Extra Hr."
		#define STR0061 "EXTRA"
		#define STR0062 "Blocked"
		#define STR0063 "Availability"
		#define STR0064 "No data to assemble the Availability query."
		#define STR0065 "Percentage (%)"
		#define STR0066 "&Exit"
	#else
		#define STR0001 "Horas Trabalhadas Na Manutenção"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Do Período         ?"
		#define STR0005 "Até Período        ?"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Do centro de custo    ?", "De Centro Custo    ?" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Até centro custo   ?", "Ate Centro Custo   ?" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "De especialidade   ?", "De Especialidade   ?" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Até especialidade  ?", "Ate Especialidade  ?" )
		#define STR0010 "Do Funcionário     ?"
		#define STR0011 "Ate Funcionário    ?"
		#define STR0012 "Tipo               ?"
		#define STR0013 "Por Centro Custo"
		#define STR0014 "Por Especialidade"
		#define STR0015 "Por Funcionário"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Centro De Custo", "Centro Custo" )
		#define STR0017 "Especialidade"
		#define STR0018 "Funcionário"
		#define STR0019 "Horas Disponíveis X Horas Realizadas"
		#define STR0020 "&Gráfico"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "&imprimir", "&Imprimir" )
		#define STR0022 "Nome   "
		#define STR0023 "Hr.Disponíveis"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Hr.realizadas", "Hr.Realizadas" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Disponível", "DISPONIVEL" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Realizado", "REALIZADO" )
		#define STR0027 "Não existem dados para montar o gráfico."
		#define STR0028 "ATENÇÃO"
		#define STR0029 "Horas Disponíveis X Horas Trabalhadas"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0031 "Administração"
		#define STR0032 "Não existem dados para imprimir..."
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "C.custo              nome             disponivel      realizado              %", "C.Custo              Nome             Disponivel      Realizado              %" )
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Especia.             nome             disponivel      realizado              %", "Especia.             Nome             Disponivel      Realizado              %" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Funcio.              nome             disponivel      realizado              %", "Funcio.              Nome             Disponivel      Realizado              %" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Cancelado Pelo Operador", "CANCELADO PELO OPERADOR" )
		#define STR0037 "Disponibilidade por "
		#define STR0038 "Total Geral"
		#define STR0039 "Calendário/Turno"
		#define STR0040 "do funcionário"
		#define STR0041 "não cadastrado"
		#define STR0042 "O processo será cancelado.."
		#define STR0043 "Segundo especificação dos parâmetros,"
		#define STR0044 "não existem dados para serem mostrados."
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "A Seleccionar Registos...", "Selecionando Registros..." )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Mod por", "MDO por" )
		#define STR0047 "Data Início:"
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Data Do Fim:", "Data Fim:" )
		#define STR0049 "Diferença"
		#define STR0050 "Horas Disponíveis X Horas Realizadas (por Funcionário/Data)"
		#define STR0051 "Utilização do Funcionário.:"
		#define STR0052 "Data"
		#define STR0053 "Horas Disponíveis X Horas Realizadas (por Funcionário)"
		#define STR0054 "Utilização por"
		#define STR0055 "Análise de utilização de MDO - Disponível X Realizado"
		#define STR0056 "Análise de utilização de MDO - Disponível X Realizado por Funcionário"
		#define STR0057 "Análise de utilização de MDO - Disponível X Realizado por Funcionário/Data"
		#define STR0058 "Código   Nome            Hrs Disponív.  Bloqueios      Disponib.    Hrs Realiz.   Diferença             Percentual      Horas Extras"
		#define STR0059 "Data          Horas Disponíveis     Bloqueios     Disponibilidade     Horas Realizadas     Diferença     Percentual     Horas Extras"
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Horas Extras", "Hr. Extras" )
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Extra", "EXTRA" )
		#define STR0062 "Bloqueios"
		#define STR0063 "Disponibilidade"
		#define STR0064 "Não existem dados para montar a consulta de Disponibilidade."
		#define STR0065 "Percentual (%)"
		#define STR0066 "&Sair"
	#endif
#endif
