#ifdef SPANISH
	#define STR0001 "Emision Orden de Servicio Mantenimiento. Usuario puede seleccionar"
	#define STR0002 "los campos que deberan mostrarse en O.S. e informar"
	#define STR0003 "parametros seleccion para impresion."
	#define STR0004 "A rayas"
	#define STR0005 "Administrac"
	#define STR0006 "Orden Servicio Mantenim"
	#define STR0007 "ANULADO POR OPERADOR"
	#define STR0008 "|------------------------------Bien/Ubicacion--------------------------------|"
	#define STR0009 "Prior.:"
	#define STR0010 "|Princ..:"
	#define STR0011 "|C.Costo..:"
	#define STR0012 "|C.Trab..:"
	#define STR0013 "Detalles.:"
	#define STR0014 "Descripcn:"
	#define STR0015 "|---------------------------------Mantenim-----------------------------------|"
	#define STR0016 "|Servicio:"
	#define STR0017 "Manten. Ant.:"
	#define STR0018 "Secuencia:"
	#define STR0019 "Nomb Mant...:"
	#define STR0020 "|Area.....:"
	#define STR0021 "Contador:"
	#define STR0022 "|Tipo.....:"
	#define STR0023 "|Parada...: Antes:"
	#define STR0024 "Desp.:"
	#define STR0025 "|----------------------------------Tarea---------------------------------------|"
	#define STR0026 "|Codigo:"
	#define STR0027 "Prevision Inic..:"
	#define STR0028 "Fin..:"
	#define STR0029 "Real     Inicio..:"
	#define STR0030 "Sin Especificacion Tarea"
	#define STR0031 "|   -------------------------------Etapas-----------------------------------   |"
	#define STR0032 "|   -------------------------------Insumos----------------------------------   |"
	#define STR0033 "Nomb"
	#define STR0034 "Fch.Prv.    Hora    Cant.  Consumo    Und      Cant.  Consumo   Und"
	#define STR0035 "Espe"
	#define STR0036 "Prod"
	#define STR0037 "Func"
	#define STR0038 "Herr"
	#define STR0039 "Terc"
	#define STR0040 "|--------------------------------Ocurrencias-----------------------------------|"
	#define STR0041 "| Tarea         Ocurrencia             Causa                   Soluc        |"
	#define STR0042 "|  Mantenimiento.: ____/____/____    Contador..: _____________ Fin.: _____________|"
	#define STR0043 "|  Fecha......: ____/____/____    Firma: ______________________________________|"
	#define STR0044 "Inicio:"
	#define STR0045 "Fin:"
	#define STR0046 "Emis.:"
	#define STR0047 "Ejecución: Inicio: ____/____/____ __:__"
	#define STR0048 "Prioridad manten.:"
	#define STR0049 "|          Fin...: ____/____/____ __:__"
	#define STR0050 "|   ---------------Etapas No Relacionadas a Insumos------------------------   |"
	#define STR0051 "Tarea"
	#define STR0052 "Descripcion O.S:"
	#define STR0053 "|-----------------------------Piezas Repuesto-------------------------------|"
	#define STR0054 "Codigo           Descripc                 Fc.U.Uso   Contador    Proxma   Fc.Prox."
	#define STR0055 "Segundo Contador"
	#define STR0056 "Solicitud servicio"
	#define STR0057 "Mantenim Preventivo"
	#define STR0058 "Cont."
	#define STR0059 "Proy."
	#define STR0060 "¿Lista piezas reposic?"
	#define STR0061 "¿Lista Base Conocimiento?"
	#define STR0062 "No"
	#define STR0063 "Si"
	#define STR0064 "|Ident....:"
	#define STR0065 "NºProced.:"
	#define STR0066 "Observac..:"
	#define STR0067 "Espere... procesando.."
	#define STR0068 "Bien/Ubicacion"
	#define STR0069 "Emi.:"
	#define STR0070 "Mantenim"
	#define STR0071 "Etapas"
	#define STR0072 "Insumos"
	#define STR0073 "No Relacionadas a"
	#define STR0074 "Piezas Repuesto"
	#define STR0075 "Ocurrencias"
	#define STR0076 "Pag."
	#define STR0077 "¿Base Conocimiento?"
	#define STR0078 "De OS"
	#define STR0079 "De Mantenim"
	#define STR0080 "Ambos"
	#define STR0081 "Servicio/Bien Ppal"
	#define STR0082 "|Nombre Cod"
	#define STR0083 "|   Fch Prev.   Hora   Cant.   Consumo   Unid.  Cant.   Consumo   Unid.     |"
	#define STR0084 "| Tarea    Ocurrencia            Causa                  Solucion             |"
	#define STR0085 "Codigo"
	#define STR0086 "|------------------------------Motivo de atraso--------------------------------|"
	#define STR0087 "Hora"
	#define STR0088 "Modelo Impresion"
	#define STR0089 "Normal"
	#define STR0090 "Grafica"
	#define STR0091 "Opcion"
	#define STR0092 "Estd"
	#define STR0093 "Completa"
	#define STR0094 "Descripc"
	#define STR0095 "Solicitante: "
	#define STR0096 "Fc.Solic.: "
	#define STR0097 "Hr.Solic.: "
	#define STR0098 "Fc.U.Uso"
	#define STR0099 "Contador"
	#define STR0100 "Proxima"
	#define STR0101 "Fc.Prox."
	#define STR0102 "¿Lista Opciones Etapa ?"
	#define STR0103 "Define si informe listara opciones de las etapas:"
	#define STR0104 "Ubicacion"
	#define STR0105 "Lugar....:"
	#define STR0106 "|Lugar....:"
	#define STR0107 "Fcha Prev"
	#define STR0108 "Cant."
	#define STR0109 "Consumo"
	#define STR0110 "Unid."
	#define STR0111 "¿Lista Descr. Mant.?"
	#define STR0112 "Nomb"
	#define STR0113 "¿De plan mantenim?"
	#define STR0114 "¿A plan de mantenim?"
	#define STR0115 "Correctiv"
	#define STR0116 "¿Imprime O.S.?"
	#define STR0117 "Emis.:"
	#define STR0118 "|----------------------------------Observac----------------------------------|"
	#define STR0119 "Observac"
	#define STR0120 "Codigo"
	#define STR0121 "Orden"
	#define STR0122 "Servic/Bien"
	#define STR0123 "Centro costos"
	#define STR0124 "Fecha O.S."
	#define STR0125 "En disco"
	#define STR0126 "¿Lista descripc bien?"
	#define STR0127 "¿Lista detalle bien?"
	#define STR0128 "¿De centro costo?"
	#define STR0129 "¿A centro costo?"
	#define STR0130 "¿De centro trabajo?"
	#define STR0131 "¿A centro trabajo?"
	#define STR0132 "¿De area mantenim?"
	#define STR0133 "¿A area mantenim?"
	#define STR0134 "¿De orden servicio?"
	#define STR0135 "¿A orden servicio?"
	#define STR0136 "¿De fch mantenimto?"
	#define STR0137 "¿A fch mantenim?"
	#define STR0138 "¿Clasificacion?"
	#define STR0139 "¿Lista descr. O.S.?"
	#define STR0140 "¿Tipo impresion?"
	#define STR0141 "Aprobada"
	#define STR0142 "Pendiente"
	#define STR0143 "Todas"
	#define STR0144 "Indique a partir Plan de Mantenimiento debe constar en informe. Presione tecla [F3]+[Enter] para seleccionar Plan de Mantenimiento o deje en blanco para seleccionar a partir del primer disponible."
	#define STR0145 "Indique hasta que Plan de mantenimiento debe constar en el informe. Presione la tecla [F3] para seleccionar un Plan de mantenimiento o digite ZZZZZZ en este campo y el arriba en blanco para considerar todos los Planes de mantenimiento."
	#define STR0146 "Informe el tipo de impresion:"
	#define STR0147 "- Via spool"
	#define STR0148 "Si en el campo arriba se selecciono 'Si'"
	#define STR0149 "informe la origen del Banco de conocimiento."
	#define STR0150 "Informe si debe imprimir la localizacion:"
	#define STR0151 "Informe que tipo de O.S. se debe imprimir:"
	#define STR0152 "|----------------------------------Sintomas------------------------------------|"
	#define STR0153 "Cod. Sintoma: "
	#define STR0154 "Desc. Sintoma: "
	#define STR0155 "Bloquea resolucion:"
	#define STR0156 "Ruedas Guias Trasera"
	#define STR0157 "Rodillo Superior 1º"
	#define STR0158 "Rodillos Superior 2º"
	#define STR0159 "Rodillos de Cinta 1º"
	#define STR0160 "Flange"
	#define STR0161 "Rodillos de Cinta 2º"
	#define STR0162 "Rodillos de Cinta 3º"
	#define STR0163 "Rodillos de Cinta 4º"
	#define STR0164 "Rodillos de Cinta 5º"
	#define STR0165 "Rodillos de Cinta 6º"
	#define STR0166 "Rodillos de Cinta 7º"
	#define STR0167 "Rodillos de Cinta 8º"
	#define STR0168 "Ruedas Motrices"
	#define STR0169 "Comentarios:"
	#define STR0170 "Componentes del Material Rodante"
	#define STR0171 "Equipo Principal....: "
	#define STR0172 "O.S.: "
	#define STR0173 "Componentes secundarios: "
	#define STR0174 "Izquierda: "
	#define STR0175 "Derecha.: "
	#define STR0176 "Conjuntos                    Dimensiones                                         Porcentaje"
	#define STR0177 "                             Iniciales                   Encontradas             Desgaste"
	#define STR0178 "                             Izq.      Der.      UM       Izq.       Der.       Izq.       Der.        Medidor           Observac."
	#define STR0179 "Flange: Simple( )  Doble( )"
	#define STR0180 "Eslabones"
	#define STR0181 "Bujes"
	#define STR0182 "Zapatas"
	#define STR0183 "Ruedas Guias Delant."
	#define STR0184 "Bien.....:"
	#define STR0185 "Matric...:"
	#define STR0186 "Codigo...:"
	#define STR0187 "Sintomas"
	#define STR0188 "|Codigo...:"
	#define STR0189 "|Matric...:"
	#define STR0190 "Entre:"
	#define STR0191 "Y:"
	#define STR0192 "¿Lista etapas?"
	#define STR0193 "Informe a partir del centro de costos que debe constar en el informe. Pulse la tecla [F3]+[Enter] para seleccionar un centro de costos o deje en blanco para seleccionar a partir del primero disponible."
	#define STR0194 "Informe hasta el centro de costos que debe constar en el informe. Pulse la tecla [F3] para seleccionar un Centro de Costos o digite ZZZZZZ en este campo y el de arriba déjelo en blanco para considerar todos los centros de costos."
	#define STR0195 "Informe a partir del centro de trabajo que debe constar en el informe. Pulse la tecla [F3]+[Enter] para seleccionar un centro de costos o deje en blanco para seleccionar a partir del primero disponible."
	#define STR0196 "Informe hasta el centro de costos que debe constar en el informe. Pulse la tecla [F3] para seleccionar un Centro de Costos o digite ZZZZZZ en este campo y el de arriba déjelo en blanco para considerar todos los centros de trabajo."
	#define STR0197 "Informe a partir del área de mantenimiento que debe constar en el informe. Pulse la tecla [F3]+[Enter] para seleccionar un Área de Mantenimiento o déjelo en blanco para seleccionar a partir del primero disponible."
	#define STR0198 "Informe hasta el área de mantenimiento que desea hacer constar en el informe. Pulse la tecla [F3] para seleccionar un área de mantenimiento o digite ZZZZZZ en este campo y el de arriba déjelo en blanco para considerar todas las áreas de mantenimiento."
	#define STR0199 "Informe a partir de que orden de servicio debe constar en el informe. Pulse la tecla [F3]+[Enter] para seleccionar una orden de servicio o déjelo en blanco para seleccionar a partir del primero disponible."
	#define STR0200 "Indique hasta la orden de servicio que debe constar en el informe. Pulse la tecla [F3] para seleccionar una orden de servicio o digite ZZZZZZ en este campo y el de arriba déjelo en blanco para considerar todas las órdenes de servicio."
	#define STR0201 "Indique a partir de la fecha de mantenimiento que debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar una fecha de mantenimiento."
	#define STR0202 "Indique hasta la fecha de mantenimiento que debe constar en el informe. Pulse la tecla [F3] para seleccionar una fecha de mantenimiento."
	#define STR0203 "Informe la clasificación que se debe mostrar en el informe."
	#define STR0204 'Sucursal:'
	#define STR0205 'Plan:'
	#define STR0206 "Fin...: ____/____/____ __:__"
	#define STR0207 "Ejecución: Inicio: ____/____/____ __:__"
#else
	#ifdef ENGLISH
		#define STR0001 "Issue a Maintenance Service Order. The user can select"
		#define STR0002 "which fields must be shown on O.S., as well as inform"
		#define STR0003 "the parameters to select printing."
		#define STR0004 "Z.Form"
		#define STR0005 "Administration"
		#define STR0006 "Maintenance Service Order"
		#define STR0007 "CANCELLED BY THE OPERATOR"
		#define STR0008 "|------------------------------Asset/Location----------------------------------|"
		#define STR0009 "Prior.:"
		#define STR0010 "|Main.....:"
		#define STR0011 "|C.Center.:"
		#define STR0012 "|W.Center.:"
		#define STR0013 "Details..:"
		#define STR0014 "Description:"
		#define STR0015 "|---------------------------------Maintenance-----------------------------------|"
		#define STR0016 "| Service..:"
		#define STR0017 "Prev Maint:"
		#define STR0018 "|Sequence:"
		#define STR0019 "Maint. Name.:"
		#define STR0020 "|Area.....:"
		#define STR0021 "Counter.:"
		#define STR0022 "|Type.....:"
		#define STR0023 "|Inoperat.:Before:"
		#define STR0024 "After.:"
		#define STR0025 "|----------------------------------Task----------------------------------------|"
		#define STR0026 "|Code:"
		#define STR0027 "Estimated Start..:"
		#define STR0028 "End..:"
		#define STR0029 "Actual     Start  :"
		#define STR0030 "No Task Specification"
		#define STR0031 "|   -------------------------------Stages-----------------------------------   |"
		#define STR0032 "|   -------------------------------Inputs-----------------------------------   |"
		#define STR0033 "Name"
		#define STR0034 "Antic. Dt.     Hour    Amt    Consumption    Unit      Amt    Consumption   Unit"
		#define STR0035 "Spec"
		#define STR0036 "Prod"
		#define STR0037 "Empl"
		#define STR0038 "Tool"
		#define STR0039 "3rdP"
		#define STR0040 "|--------------------------------Events-----------------------------------|"
		#define STR0041 "| Task         Event             Cause                   Solution        |"
		#define STR0042 "| Maintenance.: ____/____/____  Accountant..: _____________ End.: _____________|"
		#define STR0043 "|  Date.......: ____/____/____    Signature: _________________________________|"
		#define STR0044 "Start:"
		#define STR0045 "End:"
		#define STR0046 "Issuer:"
		#define STR0047 "|Execution: Start: ____/____/____ __:__"
		#define STR0048 "Priority Mainten.:"
		#define STR0049 "|          End...: ____/____/____ __:__"
		#define STR0050 "|   ---------------Steps Not Related to Inputs------------------------------   |"
		#define STR0051 "Task"
		#define STR0052 "S.O. description:"
		#define STR0053 "|-----------------------------Replacement Parts--------------------------------|"
		#define STR0054 "Code             Description                Dt.U.Use   Accountant  Next      Next Dt."
		#define STR0055 "Second Counter  "
		#define STR0056 "Service request"
		#define STR0057 "Preventive Maintenance"
		#define STR0058 "Acc."
		#define STR0059 "Proj."
		#define STR0060 "List of Replacement Parts?"
		#define STR0061 "List knowledge base?"
		#define STR0062 "No"
		#define STR0063 "Yes"
		#define STR0064 "|Ident....:"
		#define STR0065 "Procedure #:"
		#define STR0066 "Note..:"
		#define STR0067 "Wait... processing.."
		#define STR0068 "Asset/Location"
		#define STR0069 "Iss.:"
		#define STR0070 "Maintenance"
		#define STR0071 "Staged"
		#define STR0072 "Inputs"
		#define STR0073 "Not Related to"
		#define STR0074 "Replacement Parts"
		#define STR0075 "Events"
		#define STR0076 "Paym."
		#define STR0077 "Knowledge Bank?"
		#define STR0078 "Of SO"
		#define STR0079 "Of Maintenance"
		#define STR0080 "Both"
		#define STR0081 "Parent Service/Asset"
		#define STR0082 "|Name Code"
		#define STR0083 "|   Est. Date   Hour   Amt.   Consumption   Unit  Amt.   Consumption   Unit     |"
		#define STR0084 "| Task     Occurrence            Cause                  Solution               |"
		#define STR0085 "Code"
		#define STR0086 "|------------------------------Delay Reasons--------------------------------|"
		#define STR0087 "Hour"
		#define STR0088 "Print Model"
		#define STR0089 "Regular"
		#define STR0090 "Graphic"
		#define STR0091 "Options"
		#define STR0092 "Standard"
		#define STR0093 "Complete"
		#define STR0094 "Description"
		#define STR0095 "Requestor: "
		#define STR0096 "Req.Date: "
		#define STR0097 "Req.Hour: "
		#define STR0098 "Dt.LastUse"
		#define STR0099 "Counter"
		#define STR0100 "Next"
		#define STR0101 "Dt.Next"
		#define STR0102 "List Step Options?"
		#define STR0103 "Establishes if report will list the steps options:"
		#define STR0104 "Location"
		#define STR0105 "Location..:"
		#define STR0106 "|Location..:"
		#define STR0107 "Estimated Date"
		#define STR0108 "Amt."
		#define STR0109 "Consumption"
		#define STR0110 "Unit"
		#define STR0111 "Maint. Descrip. List ?"
		#define STR0112 "Name"
		#define STR0113 "From Maintenance Plan?"
		#define STR0114 "To Maintenance Plan?"
		#define STR0115 "Corrective"
		#define STR0116 "Print S.O. ?"
		#define STR0117 "Issuer:"
		#define STR0118 "|----------------------------------Note----------------------------------|"
		#define STR0119 "Note"
		#define STR0120 "Code"
		#define STR0121 "Order"
		#define STR0122 "Service/Asset"
		#define STR0123 "Cost Center"
		#define STR0124 "Date of the S.O."
		#define STR0125 "In disk"
		#define STR0126 "Asset Description List?"
		#define STR0127 "Asset Detail List?"
		#define STR0128 "From Cost Center?"
		#define STR0129 "To Cost Center?"
		#define STR0130 "From Work Center?"
		#define STR0131 "To Work Center?"
		#define STR0132 "From maintenance Area?"
		#define STR0133 "To Maintenance Area?"
		#define STR0134 "From Service Order?"
		#define STR0135 "To Service Order?"
		#define STR0136 "From Maintenance Date?"
		#define STR0137 "To Maintenance Date?"
		#define STR0138 "Classification?"
		#define STR0139 "S.O. description list?"
		#define STR0140 "Print Type?"
		#define STR0141 "Released"
		#define STR0142 "Pending"
		#define STR0143 "All"
		#define STR0144 "Enter from which Maintenance Plan it must be displayed in the report. Press F3+Enter to select a Maintenance Plan or leave blank to select from the first available."
		#define STR0145 "Enter until which Maintenance Plan it must be displayed in the report. Press F3 to select a Maintenance Plan or type ZZZZZZ in this field and leave the field above blank to consider all Maintenance Plans."
		#define STR0146 "Enter print type:"
		#define STR0147 "- Via spool"
		#define STR0148 "If field above is chosen Yes"
		#define STR0149 "enter Bank Knowledge origin."
		#define STR0150 "Inform if it must print the location:"
		#define STR0151 "Inform with S.O. type must be printed:"
		#define STR0152 "|----------------------------------Symptoms------------------------------------|"
		#define STR0153 "Code Sintoma: "
		#define STR0154 "Symptom Descr.: "
		#define STR0155 "Blocks Gateway:"
		#define STR0156 "Trailing Wheels"
		#define STR0157 "Higher Roller 1st"
		#define STR0158 "Higher Roller 2nd"
		#define STR0159 "Belt Roller 1st"
		#define STR0160 "Flange"
		#define STR0161 "Belt Roller 2nd"
		#define STR0162 "Belt Roller 3rd"
		#define STR0163 "Belt Roller 4th"
		#define STR0164 "Belt Roller 5th"
		#define STR0165 "Belt Roller 6th"
		#define STR0166 "Belt Roller 7th"
		#define STR0167 "Belt Roller 8th"
		#define STR0168 "Driving Wheels"
		#define STR0169 "Comments:"
		#define STR0170 "Components of Rolling Material"
		#define STR0171 "Main Equipment...: "
		#define STR0172 "S.O.: "
		#define STR0173 "Secondary Components: "
		#define STR0174 "Left: "
		#define STR0175 "Right: "
		#define STR0176 "Sets                    Dimensions                                           Percentage"
		#define STR0177 "                             Initiais                   Found             Wear"
		#define STR0178 "                             Left      Right      UM       Left       Right       Left       Right        Measuring         Note"
		#define STR0179 "Flange: Simple( )  Double( )"
		#define STR0180 "Links"
		#define STR0181 "Bushings"
		#define STR0182 "Shoes"
		#define STR0183 "Leading Wheels"
		#define STR0184 "Asset....:"
		#define STR0185 "License..:"
		#define STR0186 "Code...:"
		#define STR0187 "Simptomes"
		#define STR0188 "|Code...:"
		#define STR0189 "|License..:"
		#define STR0190 "Between:"
		#define STR0191 "AND:"
		#define STR0192 "Lists Stages?"
		#define STR0193 "Enter from which Cost Center it must be displayed in the report. Press [F3]+[Enter] keyboard to select a Costs Center or leave in blank to select from the first one available."
		#define STR0194 "Enter up to which Cost Center it must be displayed in the report. Press [F3] to select a Cost Center or type ZZZZZZ in this field and leave the one above blank to consider all Cost Centers."
		#define STR0195 "Enter from which Working Center it must be displayed in the report. Press [F3] to select a Working Center or leave blank to select from the first available."
		#define STR0196 "Enter until which Cost Center it must be displayed in the report. Press [F3] to select a working center or, to consider them all, type ZZZZZZZZZ in this field and leave the field above blank."
		#define STR0197 "Enter from which Maintenance Area it must be displayed in the report. Press [F3] to select a Maintenance Plan or leave blank to select from the first available."
		#define STR0198 "Enter until which Maintenance Area it must be displayed in the report. Press [F3] to select a Maintenance Area or type ZZZZZZ in this field and leave the field above blank to consider all Maintenance Area."
		#define STR0199 "Enter from which Service Order it must be displayed in the report. Press [F3]+[Enter] to select a Service Order or leave blank to select from the first available."
		#define STR0200 "Enter until which Service Order it must be displayed in the report. Press [F3] to select the desired Service Order or type ZZZZZZ in this field and leave the one above in blank to consider all Service Orders."
		#define STR0201 "Enter from which Maintenance Date it must be displayed in the report. Press [F3]+[Enter] to select a Maintenance Date."
		#define STR0202 "Enter until which Maintenance Plan it must be displayed in the report. Press [F3] to select an Maintenance Date."
		#define STR0203 "Enter what classification that must be displayed in the report."
		#define STR0204 'Branch:'
		#define STR0205 'Plan:'
		#define STR0206 "End: ____/____/____ __:__"
		#define STR0207 "Execution: Start: ____/____/____ __:__"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Emissão de Ordem de serviço de manutenção. O utilizador pode seleccionar", "Emissão de Ordem de Serviço de Manutenção. O Usuário pode selecionar" )
		#define STR0002 "quais os campos que deverão ser mostrados na O.S., bem como informar"
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "parâmetros de selecção para a impressão.", "parâmetros de seleção para a impressão." )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0005 "Administração"
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Ordem de Serviço de Manutenção", "Ordem De Serviço De Manutenção" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Cancelado Pelo Operador", "CANCELADO PELO OPERADOR" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "|------------------------------bem/localização---------------------------------|", "|------------------------------Bem/Localização---------------------------------|" )
		#define STR0009 "Prior.:"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "|pai......:", "|Pai......:" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "|c.custo..:", "|C.Custo..:" )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "|c.trab...:", "|C.Trab...:" )
		#define STR0013 "Detalhes.:"
		#define STR0014 "Descrição:"
		#define STR0015 "|---------------------------------Manutenção-----------------------------------|"
		#define STR0016 "|Serviço..:"
		#define STR0017 "Manut. Ant.:"
		#define STR0018 "|Sequência:"
		#define STR0019 "Nome Manut..:"
		#define STR0020 "|Área.....:"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Contabilista:", "Contador:" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "|tipo.....:", "|Tipo.....:" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "|paragem...: Antes:", "|Parada...: Antes:" )
		#define STR0024 "Depois:"
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "|----------------------------------tarefa--------------------------------------|", "|----------------------------------Tarefa--------------------------------------|" )
		#define STR0026 "|Código:"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Previsão início..:", "Previsão Início..:" )
		#define STR0028 "Fim..:"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Real  início..:", "Real     Início..:" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Sem especificação de tarefa", "Sem Especificação De Tarefa" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "|   -------------------------------etapas-----------------------------------   |", "|   -------------------------------Etapas-----------------------------------   |" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "|   -------------------------------recursos----------------------------------   |", "|   -------------------------------Insumos----------------------------------   |" )
		#define STR0033 "Nome"
		#define STR0034 "Dt.Prev.     Hora    Qtd    Consumo    Uni      Qtd    Consumo   Uni"
		#define STR0035 "Espe"
		#define STR0036 "Prod"
		#define STR0037 "Func"
		#define STR0038 "Ferr"
		#define STR0039 "Terc"
		#define STR0040 "|--------------------------------Ocorrências-----------------------------------|"
		#define STR0041 "| Tarefa         Ocorrência             Causa                   Solução        |"
		#define STR0042 "|  Manutenção.: ____/____/____    Contador..: _____________ Fim.: _____________|"
		#define STR0043 "|  Data.......: ____/____/____    Assinatura: _________________________________|"
		#define STR0044 "Início:"
		#define STR0045 "Fim:"
		#define STR0046 "Emis.:"
		#define STR0047 "|Execução: Início: ____/____/____ __:__"
		#define STR0048 "Prioridade Manut.:"
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "|          fim...: ____/____/____ __:__", "|          Fim...: ____/____/____ __:__" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "|   ---------------Etapas não relacionadas a insumos------------------------   |", "|   ---------------Etapas Não Relacionadas a Insumos------------------------   |" )
		#define STR0051 "Tarefa"
		#define STR0052 "Descrição da O.S:"
		#define STR0053 "|-----------------------------Peças de Reposição-------------------------------|"
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Código           Descrição                  Dt.U.Uso   Contador    Próxima   Dt.Próx.", "Código           Descrição                  Dt.U.Uso   Contador    Próxima   Dt.Prox." )
		#define STR0055 "Segundo Contador"
		#define STR0056 "Solicitação de serviço"
		#define STR0057 "Manutenção Preventiva"
		#define STR0058 "Cont."
		#define STR0059 "Proj."
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Lista peças reposição?", "Lista Peças Reposição?" )
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Listar Banco Conhecimento?", "Lista Banco Conhecimento?" )
		#define STR0062 "Não"
		#define STR0063 "Sim"
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "|ident....:", "|Ident....:" )
		#define STR0065 "NºProced.:"
		#define STR0066 "Observação..:"
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Aguarde...A processar..", "Aguarde... processando.." )
		#define STR0068 "Bem/Localização"
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Em.:", "Emi.:" )
		#define STR0070 "Manutenção"
		#define STR0071 "Etapas"
		#define STR0072 "Insumos"
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Não relacionadas a", "Não Relacionadas a" )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Peças de reposição", "Peças de Reposição" )
		#define STR0075 "Ocorrências"
		#define STR0076 "Pag."
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "Banco do conhecimento?", "Banco do Conhecimento ?" )
		#define STR0078 "Da OS"
		#define STR0079 "Da Manutenção"
		#define STR0080 "Ambos"
		#define STR0081 "Serviço/Bem Pai"
		#define STR0082 "|Nome Código"
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "|   Data Prev.   Hora   Qtd.   Consumo   Unid.  Qtd.   Consumo   Unid.     |", "|   Data Prev.   Hora   Quant.   Consumo   Unid.  Quant.   Consumo   Unid.     |" )
		#define STR0084 "| Tarefa   Ocorrência            Causa                  Solução                |"
		#define STR0085 "Código"
		#define STR0086 "|------------------------------Motivo de Atraso--------------------------------|"
		#define STR0087 "Hora"
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "Modelo de impressão", "Modelo de Impressão" )
		#define STR0089 "Normal"
		#define STR0090 "Gráfica"
		#define STR0091 "Opções"
		#define STR0092 "Padrão"
		#define STR0093 "Completa"
		#define STR0094 "Descrição"
		#define STR0095 "Solicitante: "
		#define STR0096 "Dt.Solic.: "
		#define STR0097 "Hr.Solic.: "
		#define STR0098 "Dt.U.Uso"
		#define STR0099 "Contador"
		#define STR0100 "Próxima"
		#define STR0101 If( cPaisLoc $ "ANG|PTG", "Dt.Próx.", "Dt.Prox." )
		#define STR0102 If( cPaisLoc $ "ANG|PTG", "Lista opções da etapa ?", "Lista Opções da Etapa ?" )
		#define STR0103 If( cPaisLoc $ "ANG|PTG", "Define se o relatório listará as opções das etapas:", "Define se o relatório irá listar as opções das etapas:" )
		#define STR0104 "Localização"
		#define STR0105 "Local....:"
		#define STR0106 "|Local....:"
		#define STR0107 If( cPaisLoc $ "ANG|PTG", "Data prev.", "Data Prev." )
		#define STR0108 If( cPaisLoc $ "ANG|PTG", "Qtd.", "Quant." )
		#define STR0109 "Consumo"
		#define STR0110 "Unid."
		#define STR0111 "Lista Descr. Manut. ?"
		#define STR0112 "Nome"
		#define STR0113 If( cPaisLoc $ "ANG|PTG", "De plano de manutenção ?", "De Plano de Manutenção ?" )
		#define STR0114 If( cPaisLoc $ "ANG|PTG", "Até plano de manutenção ?", "Até Plano de Manutenção ?" )
		#define STR0115 If( cPaisLoc $ "ANG|PTG", "Correctiva", "Corretiva" )
		#define STR0116 "Imprimir O.S. ?"
		#define STR0117 "Emis.:"
		#define STR0118 "|----------------------------------Observação----------------------------------|"
		#define STR0119 "Observação"
		#define STR0120 "Código"
		#define STR0121 "Ordem"
		#define STR0122 "Serviço/Bem"
		#define STR0123 "Centro Custos"
		#define STR0124 "Data da O.S."
		#define STR0125 "Em Disco"
		#define STR0126 "Lista Descricao Bem ?"
		#define STR0127 "Lista Detalhes  Bem ?"
		#define STR0128 "De  Centro de Custo ?"
		#define STR0129 "Ate Centro de Custo ?"
		#define STR0130 "De  Centro Trabalho ?"
		#define STR0131 "Ate Centro Trabalho ?"
		#define STR0132 "De  Area Manutencao ?"
		#define STR0133 "Ate Area Manutencao ?"
		#define STR0134 "De  Ordem Servico ?"
		#define STR0135 "Ate Ordem Servico ?"
		#define STR0136 "De  Data Manutencao ?"
		#define STR0137 "Ate Data Manutencao ?"
		#define STR0138 "Classificacao ?"
		#define STR0139 "Lista descr. da O.s ?"
		#define STR0140 "Tipo de Impressao ?"
		#define STR0141 "Liberada"
		#define STR0142 "Pendente"
		#define STR0143 "Todas"
		#define STR0144 "Informe a partir de qual Plano de Manutenção deve constar no relatório. Pressione a tecla [F3]+[Enter] para selecionar um Plano de Manutenção ou deixe em branco para selecionar a partir do primeiro disponivel."
		#define STR0145 "Informe até qual Plano de Manutenção deve constar no relatório. Pressione a tecla [F3] para selecionar um Plano de Manutenção ou digite ZZZZZZ neste campo e o acima em branco para considerar todos os Planos de Manutenção."
		#define STR0146 "Informe o tipo de impressão:"
		#define STR0147 "- Via spool"
		#define STR0148 "Se no campo acima foi escolhido 'Sim'"
		#define STR0149 "informe a origem do Banco do Conhecimento."
		#define STR0150 "Informe se deve imprimir a localização:"
		#define STR0151 "Informe que tipo de O.S. deve ser impressa:"
		#define STR0152 "|----------------------------------Sintomas------------------------------------|"
		#define STR0153 "Cód. Sintoma: "
		#define STR0154 "Desc. Sintoma: "
		#define STR0155 "Bloqueia Portaria:"
		#define STR0156 "Rodas Guias Traseira"
		#define STR0157 "Roletes Superior 1º"
		#define STR0158 "Roletes Superior 2º"
		#define STR0159 "Roletes de Esteira 1º"
		#define STR0160 "Flange"
		#define STR0161 "Roletes de Esteira 2º"
		#define STR0162 "Roletes de Esteira 3º"
		#define STR0163 "Roletes de Esteira 4º"
		#define STR0164 "Roletes de Esteira 5º"
		#define STR0165 "Roletes de Esteira 6º"
		#define STR0166 "Roletes de Esteira 7º"
		#define STR0167 "Roletes de Esteira 8º"
		#define STR0168 "Rodas Motrizes"
		#define STR0169 "Comentários:"
		#define STR0170 "Componentes do Material Rodante"
		#define STR0171 "Equipamento Pai....: "
		#define STR0172 "O.S.: "
		#define STR0173 "Componentes Filhos: "
		#define STR0174 "Esquerda: "
		#define STR0175 "Direita.: "
		#define STR0176 "Conjuntos                    Dimensões                                           Percentual"
		#define STR0177 "                             Iniciais                   Encontradas             Desgaste"
		#define STR0178 "                             Esq.      Dir.      UM       Esq.       Dir.       Esq.       Dir.        Medidor           Observação"
		#define STR0179 "Flange: Simples( )  Dupla( )"
		#define STR0180 "Elos"
		#define STR0181 "Buchas"
		#define STR0182 "Sapatas"
		#define STR0183 "Rodas Guias Dianteira"
		#define STR0184 "Bem......:"
		#define STR0185 "Placa....:"
		#define STR0186 "Código...:"
		#define STR0187 "Sintomas"
		#define STR0188 "|Código...:"
		#define STR0189 "|Placa....:"
		#define STR0190 "Entre:"
		#define STR0191 "E:"
		#define STR0192 "Lista Etapas ?"
		#define STR0193 "Informe a partir de qual Centro de Custos deve constar no relatório. Pressione a tecla [F3]+[Enter] para selecionar um Centro de Custos ou deixe em branco para selecionar a partir do primeiro disponível."
		#define STR0194 "Informe até qual Centro de Custos deve constar no relatório. Pressione a tecla [F3] para selecionar um Centro de Custos ou digite ZZZZZZ neste campo e o acima em branco para considerar todos os Centro de Custos."
		#define STR0195 "Informe a partir de qual Centro de Trabalho deve constar no relatório. Pressione a tecla [F3]+[Enter] para selecionar um Centro de Trabalho ou deixe em branco para selecionar a partir do primeiro disponível."
		#define STR0196 "Informe até qual Centro de Trabalho deve constar no relatório. Pressione a tecla [F3] para selecionar um Centro de Trabalho ou digite ZZZZZZ neste campo e o acima em branco para considerar todos os Centro de Trabalho."
		#define STR0197 "Informe a partir de qual Área de Manutenção deve constar no relatório. Pressione a tecla [F3]+[Enter] para selecionar uma Área de Manutenção ou deixe em branco para selecionar a partir da primeira disponível."
		#define STR0198 "Informe até qual Área de Manutenção deve constar no relatório. Pressione a tecla [F3] para selecionar uma Área de Manutenção ou digite ZZZZZZ neste campo e o acima em branco para considerar todas as Área de Manutenção."
		#define STR0199 "Informe a partir de qual Ordem de Serviço deve constar no relatório. Pressione a tecla [F3]+[Enter] para selecionar uma Ordem de Serviço ou deixe em branco para selecionar a partir da primeira disponível."
		#define STR0200 "Informe até qual Ordem de Serviço deve constar no relatório. Pressione a tecla [F3] para selecionar uma Ordem de Serviço ou digite ZZZZZZ neste campo e o acima em branco para considerar todas as Ordens de Serviço."
		#define STR0201 "Informe a partir de qual Data de Manutenção deve constar no relatório. Pressione a tecla [F3]+[Enter] para selecionar uma Data de Manutenção."
		#define STR0202 "Informe até qual Data de Manutenção deve constar no relatório. Pressione a tecla [F3] para selecionar uma Data de Manutenção."
		#define STR0203 "Informe qual a classificação que deve ser exibida no relatório."
		#define STR0204 'Filial: '
		#define STR0205 'Plano: '
		#define STR0206 "Fim...: ____/____/____ __:__"
		#define STR0207 "Execução: Início: ____/____/____ __:__"
	#endif
#endif
