#ifdef SPANISH
	#define STR0001 "Informe de ajustes del clic de la derecha en rutinas MVC"
	#define STR0002 "A rayas"
	#define STR0003 "Administracion"
	#define STR0004 "Inconsistencias en el Clic de la Derecha que deben corregirse en el sistema."
	#define STR0005 "Las actualizaciones deben hacerse en: Miscelanea -> Sistema -> Clic de la Derecha"
	#define STR0006 "Cambiar de "
	#define STR0007 " para el View:GetValue('"
	#define STR0008 "Para mayor entendimiento y detalle sobre como funcionan las rutinas en MVC, "
	#define STR0009 "usted puede acceder al siguiente enlace: "
	#define STR0010 "Donde esta localizado el material sobre MVC, disponible a traves de TOTVS."
#else
	#ifdef ENGLISH
		#define STR0001 "Report of right-click adjustments in MVC routines"
		#define STR0002 "Z-form"
		#define STR0003 "Administration"
		#define STR0004 "Inconsistencies in Right Click that must be corrected in the System."
		#define STR0005 "Updates must be made in: Miscellaneous -> System -> Right Click"
		#define STR0006 "Change from "
		#define STR0007 " to oView:GetValue('"
		#define STR0008 "For better understanding and detailing on how MVC routines work, "
		#define STR0009 "you can access the following link: "
		#define STR0010 "In which the material on MVC is located, offered by TOTVS."
	#else
		#define STR0001 "Relatório de ajustes do click da direita em rotinas MVC"
		#define STR0002 "Zebrado"
		#define STR0003 "Administração"
		#define STR0004 "Inconsistências no Click da Direita que devem ser corrigidas no Sistema."
		#define STR0005 "As atualizações devem ser feitas em: Miscelanea -> Sistema -> Click da Direita"
		#define STR0006 "Trocar de "
		#define STR0007 " para oView:GetValue('"
		#define STR0008 "Para maior entendimento e detalhamento sobre como funcionam as rotinas em MVC, "
		#define STR0009 "você pode acessar o seguinte link: "
		#define STR0010 "Onde está localizado o material sobre MVC, disponibilizado pela TOTVS."
	#endif
#endif
