#ifdef SPANISH
	#define STR0001 "Informe de costos del Plan de Mantenimiento"
	#define STR0002 "Este progr. selecc. por default OS finalizadas y las"
	#define STR0003 "pendientes, segun el param. seleccionado."
	#define STR0004 "A rayas"
	#define STR0005 "Administracion"
	#define STR0006 "Informe de costo del plan"
	#define STR0007 "¿De Plan          ?"
	#define STR0008 "¿A  Plan          ?"
	#define STR0009 "¿De Fch. Mantenim.?"
	#define STR0010 "¿A  Fch. Mantenim.?"
	#define STR0011 "¿De Servicio      ?"
	#define STR0012 "¿A  Servicio      ?"
	#define STR0013 "¿Consd. Producto  ?"
	#define STR0014 "Si"
	#define STR0015 "No"
	#define STR0016 "¿Consd. Herramienta?"
	#define STR0017 "¿Consd.Mano de Obra?"
	#define STR0018 "¿Considerar Tercero?"
	#define STR0019 "¿Orden             ?"
	#define STR0020 "Bien"
	#define STR0021 "Servicio"
	#define STR0022 "¿Tipo de Costo      ?"
	#define STR0023 "Promedio"
	#define STR0024 "Estandar"
	#define STR0025 "¿Costo Maq. Parada  ?"
	#define STR0026 "¿Aglomera M.D.O     ?"
	#define STR0027 "Tipo"
	#define STR0028 "ANULADO POR EL OPERADOR"
	#define STR0029 "*** Total de Bien"
	#define STR0030 "*** Total de Servicio"
	#define STR0031 "Bien..: "
	#define STR0032 "Serv.: "
	#define STR0033 "Orden: "
	#define STR0034 "Bien..: "
	#define STR0035 "Fecha..: "
	#define STR0036 "Descripc. de OS.: "
	#define STR0037 "Costo Hora Parada de Bien "
	#define STR0038 "*** Total de O.S. "
	#define STR0039 "*** Total del Plan"
	#define STR0040 "Plan........: "
	#define STR0041 "Fecha Plan..: "
	#define STR0042 "De.: "
	#define STR0043 "A...: "
	#define STR0044 "Cant."
	#define STR0045 "*** Total General"
	#define STR0046 "Seleccionando Registros..."
	#define STR0047 "¿Considera OS  ?"
	#define STR0048 "Liberada"
	#define STR0049 "Pendien."
	#define STR0050 "Ambas"
	#define STR0051 "Ninguna"
	#define STR0052 "Informe a partir de que Localizacion debe constar en el informe. Presione las teclas [F3]+[Enter] para seleccionar una Localizacion."
	#define STR0053 "Informe hasta que Localizacion debe constar en el informe. Presione las teclas [F3]+[Enter] para seleccionar la Localizacion deseada o digite ZZZZZZ en este campo y el anterior en blanco para considerar todas las Localizaciones."
	#define STR0054 "Local: "
	#define STR0055 "¿Imprimir Localizacion?"
	#define STR0056 "Si"
	#define STR0057 "No"
	#define STR0058 "Informe si debe imprimir la localizacion:"
	#define STR0059 "1-Si"
	#define STR0060 "2-No"
	#define STR0061 "¿De Centro de Costo ?"
	#define STR0062 "¿A Centro Costo ?"
	#define STR0063 "Informe a partir de que Centro de Costo debe constar en el informe. Presione las teclas [Enter]+[F3] para seleccionar un Centro de Costo."
	#define STR0064 "Informe hasta que Centro de Costo debe constar en el informe. Presione las teclas [Enter]+[F3] para seleccionar el Centro de Costo deseado o digite ZZZZZZZZZ en este campo y el anterior en blanco para considerar todos los Centros de Costos."
	#define STR0065 "Sucursal: "
	#define STR0066 "¿Considera fecha?"
	#define STR0067 "¿Considera especialidad?"
	#define STR0068 "¿De ubicación?"
	#define STR0069 "¿A ubicación?"
	#define STR0070 "Pendiente"
	#define STR0071 "Finalizada"
	#define STR0072 "De familia de bienes "
	#define STR0073 "A familia de bienes "
	#define STR0074 "De la O.S."
	#define STR0075 "Del insumo"
	#define STR0076 "Informe a partir de qué Sucursal debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar una sucursal."
	#define STR0077 "Escriba hasta qué sucursal debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar la sucursal deseada o escriba ZZZZZZZZZ en este campo y deje el anterior en blanco para considerar todas las Sucursales."
	#define STR0078 "Indique a partir de qué Plan de mantenimiento debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar un Plan de mantenimiento."
	#define STR0079 "Indique hasta qué Plan de mantenimiento debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar el Plan de mantenimiento deseado o digite ZZZZZZ en este campo y arriba en blanco para considerar todos los Planes de mantenimiento."
	#define STR0080 "Informe un determinado período de fecha inicial del mantenimiento."
	#define STR0081 "Informe un determinado período de fecha final del mantenimiento."
	#define STR0082 "Indique a partir de qué familia del bien debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar una Familia de bien."
	#define STR0083 "Indique hasta qué familia de bien debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar la Familia de bien deseada o digite ZZZZZZ en este campo y arriba en blanco para considerar todas las Familias de bien."
	#define STR0084 "Escriba a partir de qué Servicio debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar un Servicio."
	#define STR0085 "Informe hasta qué servicio debe constar en el informe. Pulse las teclas [F3]+[Enter] para seleccionar el Servicio deseado o digite ZZZZZZ en este campo y arriba en blanco para considerar todos los Servicios."
	#define STR0086 "Informe si se debe listar el Producto: "
	#define STR0087 "Informe si se debe listar Herramientas:"
	#define STR0088 "Informe si se debe listar Mano de obra: "
	#define STR0089 "Informe si se debe listar Tercero: "
	#define STR0090 "Informe qué tipo de costo se debe listar en el informe: "
	#define STR0091 "Informe cómo se debe listar la Orden del informe: "
	#define STR0092 "Informe si se debe listar el Costo de la máquina:"
	#define STR0093 "Informe si se agrupa Mano de obra: "
	#define STR0094 "Indique el tipo de informe que se imprimirá: "
	#define STR0095 "Informe si se considera Fecha:"
	#define STR0096 "De Orden de servicio"
	#define STR0097 "De insumo"
	#define STR0098 "Informe si se considera Orden de servicio: "
	#define STR0099 "Informe si se debe listar Especialidad: "
	#define STR0100 "De sucursal "
	#define STR0101 "A sucursal "
	#define STR0102 "Informe el tipo de informe: "
	#define STR0103 "Detallado"
	#define STR0104 "Resumido"
	#define STR0105 "Detallado o resumido"
	#define STR0106 "Código insumo:"
	#define STR0107 "Nombre insumo"
	#define STR0108 "...................Previsto..................."
	#define STR0109 "................Realizado................"
	#define STR0110 "Costo"
	#define STR0111 "Unid."
	#define STR0112 "Diferencia"
	#define STR0113 "Var.%"
#else
	#ifdef ENGLISH
		#define STR0001 "Maintenance Plan Costs Report"
		#define STR0002 "By default, this program selects finished and open "
		#define STR0003 "S.O., according to the parameter selected."
		#define STR0004 "Z.Form"
		#define STR0005 "Management"
		#define STR0006 "Plan Costs"
		#define STR0007 "From Plan          ?"
		#define STR0008 "To Plan            ?"
		#define STR0009 "From Mainten. Date ?"
		#define STR0010 "To Maintenance Date?"
		#define STR0011 "From Service       ?"
		#define STR0012 "To Service         ?"
		#define STR0013 "Consider Product   ?"
		#define STR0014 "Yes"
		#define STR0015 "No"
		#define STR0016 "Consider Tool      ?"
		#define STR0017 "Consider Lab.Force ?"
		#define STR0018 "Consider 3rd Party ?"
		#define STR0019 "Order              ?"
		#define STR0020 "Asset"
		#define STR0021 "Service"
		#define STR0022 "Cost Type          ?"
		#define STR0023 "Average"
		#define STR0024 "Standard"
		#define STR0025 "Inop.Machine Cost  ?"
		#define STR0026 "Group Labour Force ?"
		#define STR0027 "Type"
		#define STR0028 "CANCELLED BY THE OPERATOR"
		#define STR0029 "*** Total of Asset"
		#define STR0030 "*** Total of Service"
		#define STR0031 "Asset: "
		#define STR0032 "Serv.: "
		#define STR0033 "Order: "
		#define STR0034 "Asset: "
		#define STR0035 "Date..: "
		#define STR0036 "SO Description..: "
		#define STR0037 "Asset Inoper. Hour Cost  "
		#define STR0038 "*** Total of S.O. "
		#define STR0039 "*** Total of Plan "
		#define STR0040 "Plan........: "
		#define STR0041 "Plan Date...: "
		#define STR0042 "From.: "
		#define STR0043 "To..: "
		#define STR0044 "Amount"
		#define STR0045 "*** Grand Total"
		#define STR0046 "Selecting records ...    "
		#define STR0047 "Consider  S.O. ?"
		#define STR0048 "Released"
		#define STR0049 "Pending"
		#define STR0050 "Both"
		#define STR0051 "None"
		#define STR0052 "Enter from which Location it must be displayed in the report. Press [F3]+[Enter] to select a Location."
		#define STR0053 "Enter until which Location it must be displayed in the report. Press [F3]+[Enter] to select the desired Location or enter ZZZZZZ in this field, and the one above must be blank to consider all Locations."
		#define STR0054 "Location: "
		#define STR0055 "Print Location?"
		#define STR0056 "Yes"
		#define STR0057 "No"
		#define STR0058 "Inform if location must be printed:"
		#define STR0059 "1-Yes"
		#define STR0060 "2-No"
		#define STR0061 "From Cost Center?"
		#define STR0062 "To Cost Center?"
		#define STR0063 "Enter from which Cost Center it must be displayed in the report. Press [Enter]+[F3] to select a Cost Center."
		#define STR0064 "Indicate up to which Cost Center the Report must include data. Press [Enter]+[F3] to select the desired Cost Center or enter ZZZZZZZZZ in this field and leave the one above in blank to consider all Cost Centers."
		#define STR0065 "Branch......: "
		#define STR0066 "Consider Date?"
		#define STR0067 "Consider Speciality ?"
		#define STR0068 "From Localization?"
		#define STR0069 "To Location?"
		#define STR0070 "Open"
		#define STR0071 "Completed"
		#define STR0072 "From Asset Family "
		#define STR0073 "To Asset Family "
		#define STR0074 "From S.O"
		#define STR0075 "From Input"
		#define STR0076 "Indicate from which Branch the report must be issued. Press [F3]+[Enter] to select a Branch."
		#define STR0077 "Choose until which branch the report must be issued. Press [F3]+[Enter] to select a Branch or type ZZZZZZ in this field and leave the field above blank to consider all Branches."
		#define STR0078 "Enter from which Maintenance Plan it must be displayed in the report. Press [F3]+[Enter] to select a Maintenance Plan."
		#define STR0079 "Enter until which Maintenance Plan it must be displayed in the report. Press [F3]+[Enter] to select a Maintenance Plan or type ZZZZZZ in this field and leave the field above blank to consider all Maintenance Plans."
		#define STR0080 "Enter a specific period of Maintenance start date."
		#define STR0081 "Enter a specific period of Maintenance end date."
		#define STR0082 "Enter from which Asset Family it must be displayed in the report. Press [F3]+[Enter] to select an Asset Group."
		#define STR0083 "Enter until which Asset Family it must be displayed in the report. Press [F3]+[Enter] to select the desired Asset Group or type ZZZZZZ in this field and leave the one above in blank to consider all Asset groups."
		#define STR0084 "Enter from which Service it must be displayed in the report. Press [F3]+[Enter] to select a Service."
		#define STR0085 "Choose until which Service it must be displayed in the report. Press [F3]+[Enter] to select the desired Service or type ZZZZZZ in this field and leave the one above in blank to consider all Services."
		#define STR0086 "Enter if it must list Product: "
		#define STR0087 "Enter if it must list Tools:"
		#define STR0088 "Enter if it must list Labor: "
		#define STR0089 "Enter if it must list Outsourced: "
		#define STR0090 "Enter which cost type must be listed on the report: "
		#define STR0091 "Enter how the Report order must be listed: "
		#define STR0092 "Enter if it must list the Machine Cost:"
		#define STR0093 "Enter if it Groups Labor: "
		#define STR0094 "Enter the report type to be printed: "
		#define STR0095 "Enter it if Considers Date:"
		#define STR0096 "Of Service Order"
		#define STR0097 "From Input"
		#define STR0098 "Enter if it Considers Service Order: "
		#define STR0099 "Enter if it must list Specialty: "
		#define STR0100 "From Branch "
		#define STR0101 "To Branch "
		#define STR0102 "Enter the report type: "
		#define STR0103 "Detailed"
		#define STR0104 "Summarized"
		#define STR0105 "Detailed or Summarized"
		#define STR0106 "Input Code"
		#define STR0107 "Input Name"
		#define STR0108 ".........Estimated........"
		#define STR0109 "................Accomplished.............."
		#define STR0110 "Cost"
		#define STR0111 "Unit"
		#define STR0112 "Difference"
		#define STR0113 "Var.%"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Relatório De Custos Do Plano De Manutenção", "Relatorio de Custos do Plano de Manutencao" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Este programa selecciona por defeito as finalizadas e as", "Este programa seleciona por default OS finalizadas e as" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Em aberto conforme parâmetro seleccionado.", "em aberto conforme parametro selecionado." )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Administração", "Administracao" )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Custos Do Plano", "Custos do Plano" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "De  plano          ?", "De  Plano          ?" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Até plano          ?", "Ate Plano          ?" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "De  Data Manutenção?", "De  Data Manutencao?" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Até Data Manutenção?", "Ate Data Manutencao?" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "De  serviço        ?", "De  Servico        ?" )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Até serviço        ?", "Ate Servico        ?" )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Considerar produto ?", "Considerar Produto ?" )
		#define STR0014 "Sim"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Não", "Nao" )
		#define STR0016 "Considerar Ferramen?"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Considerar Mão-obra?", "Considerar Mao-Obra?" )
		#define STR0018 "Considerar Terceiro?"
		#define STR0019 "Ordem              ?"
		#define STR0020 "Bem"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Serviço", "Servico" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Tipo de custo      ?", "Tipo de Custo      ?" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Médio", "Medio" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Padrão", "Standard" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Custo máq. parada  ?", "Custo Maq. Parada  ?" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Aglutina m.d.o     ?", "Aglutina M.D.O     ?" )
		#define STR0027 "Tipo"
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Cancelado Pelo Operador", "CANCELADO PELO OPERADOR" )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "*** Total Do Bem", "*** Total do Bem" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "*** Total Do Serviço", "*** Total do Servico" )
		#define STR0031 "Bem..: "
		#define STR0032 "Serv.: "
		#define STR0033 "Ordem: "
		#define STR0034 "Bem..: "
		#define STR0035 "Data..: "
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Descrição da os.: ", "Descricao da OS.: " )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Custo hora parada do bem ", "Custo Hora Parada do Bem " )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "*** total da o.s. ", "*** Total da O.S. " )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "*** Total Do Plano", "*** Total do Plano" )
		#define STR0040 "Plano.......: "
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Data plano..: ", "Data Plano..: " )
		#define STR0042 "De.: "
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Até.: ", "Ate.: " )
		#define STR0044 "Quantid."
		#define STR0045 "*** Total Geral"
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "A Seleccionar Registos...", "Selecionando Registros..." )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Considerar os   ?", "Considera OS   ?" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Libertada", "Liberada" )
		#define STR0049 "Pendente"
		#define STR0050 "Ambas"
		#define STR0051 "Nenhuma"
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Informe a partir de qual localização deve constar no relatório. Pressione as teclas [F3]+[Enter] para seleccionar uma localização.", "Informe a partir de qual Localização deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar uma Localização." )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Informe até que localização deve constar no relatório. Pressione as teclas [F3]+[Enter] para seleccionar a localização desejada ou digite ZZZZZZ neste campo, e deixe acima em branco para considerar todas as localizações.", "Informe até qual Localização deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar a Localização desejada ou digite ZZZZZZ neste campo e o acima em branco para considerar todas as Localizações." )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Local ", "Local: " )
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Imprimir localização ?", "Imprimir Localização ?" )
		#define STR0056 "Sim"
		#define STR0057 "Não"
		#define STR0058 "Informe se deve imprimir a localização:"
		#define STR0059 "1-Sim"
		#define STR0060 "2-Não"
		#define STR0061 "De Centro Custo ?"
		#define STR0062 "Até Centro Custo ?"
		#define STR0063 "Informe a partir de qual Centro de Custo deve constar no relatório. Pressione as teclas [Enter]+[F3] para selecionar um Centro de Custo."
		#define STR0064 "Informe até qual Centro Custo deve constar no relatório. Pressione as teclas [Enter]+[F3] para selecionar o Centro de Custo desejado ou digite ZZZZZZZZZ neste campo e o acima em branco para considerar todos os Centros de Custos."
		#define STR0065 "Filial......: "
		#define STR0066 "Considera Data ?"
		#define STR0067 "Considera Especialidade ?"
		#define STR0068 "De Localização ?"
		#define STR0069 "Até Localização ?"
		#define STR0070 "Aberta"
		#define STR0071 "Finalizada"
		#define STR0072 "De Família de Bens "
		#define STR0073 "Até Família de Bens "
		#define STR0074 "Da O.S"
		#define STR0075 "Do Insumo"
		#define STR0076 "Informe a partir de qual Filial deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar uma Filial."
		#define STR0077 "Informe até qual Filial deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar a Filial desejada ou digite ZZZZZZ neste campo e o acima em branco para considerar todos as Filiais."
		#define STR0078 "Informe a partir de qual Plano de Manutenção deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar um Plano de Manutenção."
		#define STR0079 "Informe até qual Plano de Manutenção deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar o Plano de Manutenção desejado ou digite ZZZZZZ neste campo e o acima em branco para considerar todos os Planos de Manutenção."
		#define STR0080 "Informe um determinado período de data inicio da Manutenção."
		#define STR0081 "Informe um determinado período de data fim da Manutenção."
		#define STR0082 "Informe a partir de qual Família de Bem deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar uma Família de Bem."
		#define STR0083 "Informe até qual Família de Bem deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar a Família de Bem desejada ou digite ZZZZZZ neste campo e o acima em branco para considerar todas as Famílias de Bem."
		#define STR0084 "Informe a partir de qual Serviço deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar um Serviço."
		#define STR0085 "Informe até qual Serviço deve constar no relatório. Pressione as teclas [F3]+[Enter] para selecionar o Serviço desejado ou digite ZZZZZZ neste campo e o acima em branco para considerar todos os Serviços."
		#define STR0086 "Informe se deve listar o Produto: "
		#define STR0087 "Informe se deve listar o Ferramentas:"
		#define STR0088 "Informe se deve listar Mão de Obra: "
		#define STR0089 "Informe se deve listar Terceiro: "
		#define STR0090 "Informe qual tipo de custo deve listar no relatório: "
		#define STR0091 "Informe como deve listar a Ordem do relatório: "
		#define STR0092 "Informe se deve listar o Custo da Máquina:"
		#define STR0093 "Informe se Aglutina Mão-de-Obra: "
		#define STR0094 "Informe o tipo do relatório a ser impresso: "
		#define STR0095 "Informe se Considera Data:"
		#define STR0096 "Da Ordem de Serviço"
		#define STR0097 "Do Insumo"
		#define STR0098 "Informe se Considera Ordem De Serviço: "
		#define STR0099 "Informe se deve listar Especialidade: "
		#define STR0100 "De Filial "
		#define STR0101 "Até Filial "
		#define STR0102 "Informe o tipo de relatório: "
		#define STR0103 "Detalhado"
		#define STR0104 "Resumido"
		#define STR0105 "Detalhado ou Resumido"
		#define STR0106 "Codigo Insumo"
		#define STR0107 "Nome Insumo"
		#define STR0108 "...................Previsto..................."
		#define STR0109 "................Realizado................"
		#define STR0110 "Custo"
		#define STR0111 "Unid."
		#define STR0112 "Diferenca"
		#define STR0113 "Var.%"
	#endif
#endif
