#ifdef SPANISH
	#define STR0001 "Devuelve todas las demandas del MRP"
	#define STR0002 "Devuelve un registro específico de demandas"
	#define STR0003 "Modifica una demanda específica"
	#define STR0004 "Realiza modificación en varias demandas"
	#define STR0005 "Incluye o actualiza una o más demandas del MRP"
	#define STR0006 "Borra una o más demandas del MRP"
	#define STR0007 "Registros incluidos con éxito"
	#define STR0008 "Error al borrar demanda."
	#define STR0009 "Registro no encontrado."
	#define STR0010 "Registros modificados con éxito"
	#define STR0011 "Registros no modificados"
	#define STR0012 "Registro con Sucursal ="
	#define STR0013 ", y Id ="
	#define STR0014 "¡No se encontró!"
	#define STR0015 "Registro borrado con éxito"
	#define STR0016 "No fue posible interpretar los datos recibidos."
	#define STR0017 "Demanda no existe. Borrado no efectuado."
	#define STR0018 "Atributo"
	#define STR0019 "no recibido en la requisición."
	#define STR0020 "enviado en formato incorrecto."
	#define STR0021 "enviado sin ningún dato para procesar."
	#define STR0022 "no se informó."
	#define STR0023 "Cantidad no puede ser menor que 0."
	#define STR0024 "no se informó para los opcionales."
	#define STR0025 "No se pudo obtener acceso exclusivo para incluir los datos. Intente nuevamente."
	#define STR0026 "No se pudo procesar los ítems."
	#define STR0027 "Verifique los errores ocurridos en cada ítem para obtener detalles."
	#define STR0028 "No se pudo procesar el mensaje."
	#define STR0029 "Demandas del MRP"
	#define STR0030 "Sincronización de las demandas del MRP"
#else
	#ifdef ENGLISH
		#define STR0001 "Return all MRP demands"
		#define STR0002 "Return a specific record of demands"
		#define STR0003 "Edit a specific demand"
		#define STR0004 "Edit in several demands"
		#define STR0005 "Add or update one or more MRP demands"
		#define STR0006 "Delete one or more MRP demands"
		#define STR0007 "Records successfully registered"
		#define STR0008 "Error deleting demand!"
		#define STR0009 "Record not found"
		#define STR0010 "Records successfully changed!"
		#define STR0011 "Records not edited!"
		#define STR0012 "Record with Branch = "
		#define STR0013 ", and Id ="
		#define STR0014 " not found!"
		#define STR0015 "Record successfully deleted"
		#define STR0016 "Unable to interpret date received."
		#define STR0017 "Demand not exist. Deletion not executed."
		#define STR0018 "Attribute"
		#define STR0019 "not received in the request."
		#define STR0020 "sent in incorrect format."
		#define STR0021 "sent without any date to process."
		#define STR0022 "not entered."
		#define STR0023 "Quantity cannot be lower than 0."
		#define STR0024 "not informed for optionals."
		#define STR0025 "Unable to have exclusive access to data entry. Try again."
		#define STR0026 "Unable to process items."
		#define STR0027 "Check errors in each item to obtain details."
		#define STR0028 "Unable to process the message."
		#define STR0029 "MRP Demands"
		#define STR0030 "MRP demands synchronization"
	#else
		#define STR0001 "Retorna todas as demandas do MRP"
		#define STR0002 "Retorna um registro específico de demandas"
		#define STR0003 "Altera uma demanda específica"
		#define STR0004 "Realiza alteração em várias demandas"
		#define STR0005 "Inclui ou atualiza uma ou mais demandas do MRP"
		#define STR0006 "Exclui uma ou mais demandas do MRP"
		#define STR0007 "Registros cadastrados com sucesso"
		#define STR0008 "Erro ao exlcuir demanda !"
		#define STR0009 "Registro não encontrado"
		#define STR0010 "Registros alterados com sucesso !"
		#define STR0011 "Registros não alterados !"
		#define STR0012 "Registro com Filial = "
		#define STR0013 ", e Id ="
		#define STR0014 " não encontrado !"
		#define STR0015 "Registro Excluído com Sucesso"
		#define STR0016 "Não foi possível interpretar os dados recebidos."
		#define STR0017 "Demanda não existe. Exclusão não efetuada."
		#define STR0018 "Atributo"
		#define STR0019 "não recebido na requisição."
		#define STR0020 "enviado em formato incorreto."
		#define STR0021 "enviado sem nenhum dado para processar."
		#define STR0022 "não foi informado."
		#define STR0023 "Quantidade não pode ser menor que 0."
		#define STR0024 "não informado para os opcionais."
		#define STR0025 "Não foi possível obter acesso exclusivo para inclusão dos dados. Tente novamente."
		#define STR0026 "Não foi possível processar os itens."
		#define STR0027 "Verifique os erros ocorridos em cada item para obter detalhes."
		#define STR0028 "Não foi possível processar a mensagem."
		#define STR0029 "Demandas do MRP"
		#define STR0030 "Sincronização das demandas do MRP"
	#endif
#endif
