#ifdef SPANISH
	#define STR0001 "Esta rutina no puede ejecutarse a partir del menu."
	#define STR0002 "Debe ejecutarse via IDE."
	#define STR0003 "¡Aviso!"
	#define STR0004 "Esta rutina actualiza el entorno para el modulo "
	#define STR0005 " y debe usarse en modo exclusivo."
	#define STR0006 "Atualizacion del Diccionario de Datos"
	#define STR0007 "Verificando el entorno. Espere..."
	#define STR0008 "Empresa no utiliza Gestion de Flotas"
	#define STR0009 "¡Finalizado!"
	#define STR0010 "En espera"
	#define STR0011 "Procesando"
	#define STR0012 "Finalizado"
	#define STR0013 "Con Errores"
	#define STR0014 "Procesado"
	#define STR0015 "No Procesado"
	#define STR0016 "Empresa"
	#define STR0017 "Registro de actualizacion"
	#define STR0018 "Operacion"
	#define STR0019 "Verificando Parametros"
	#define STR0020 "Verificando Consultas"
	#define STR0021 "Verificando Disparadores"
	#define STR0022 "Verificando Tablas"
	#define STR0023 "Verificando Indices"
	#define STR0024 "Verificando diccionario de datos"
	#define STR0025 "Actualizando base de datos. "
	#define STR0026 "Finalizando las actualizaciones"
	#define STR0027 "Modificacion en las tablas: "
	#define STR0028 "Campos:"
	#define STR0029 "Indices en el orden:"
	#define STR0030 "Parametros: "
	#define STR0031 "Proceso finalizado. ¡Ejecute Update en modo Exclusivo!"
	#define STR0032 ") - Tabla Creada"
	#define STR0033 ") - Tuvo su Clave Unica modificada"
	#define STR0034 " - Creado"
	#define STR0035 " - Existente"
	#define STR0036 " - Se modifico Clave del Orden "
	#define STR0037 " - Campo creado"
	#define STR0038 " - Validacion modificada"
	#define STR0039 " - Modificado F3 del campo "
	#define STR0040 " - Tamano del campo modificado"
	#define STR0041 "Parametro creado "
	#define STR0042 "Existe Parametro "
	#define STR0043 " Tabla: "
	#define STR0044 "Atencion"
	#define STR0045 "¡Imposible abrir la tabla de empresas de forma exclusiva!"
	#define STR0046 "Imposible abrir archivo "
	#define STR0047 ". ¿Desea continuar el update en las demas empresas?"
	#define STR0048 "Si"
	#define STR0049 "No"
	#define STR0050 "Proceso finalizado. Problema con archivo "
	#define STR0051 "Problema con archivo "
	#define STR0052 "Arqchvos Texto (*.TXT) |*.txt|"
	#define STR0053 "Actualizacion de Datos"
	#define STR0054 "Proceso finalizado"
	#define STR0055 "Grabar Como..."
	#define STR0056 " - El campo ya existe"
	#define STR0057 "Se creo el disparador para el campo "
	#define STR0058 "Disparadores: "
	#define STR0059 "Ya existe disparador para el campo "
	#define STR0060 "Se creo una consulta  "
	#define STR0061 "Ya existe una consulta "
	#define STR0062 "Consultas: "
	#define STR0063 "¿Desea continuar la operacion?"
	#define STR0064 "Se recomienda hacer una copia de seguridad del diccionario y de la base de datos."
	#define STR0065 "Validando informaciones para la actualizacion."
	#define STR0066 "Este update es de uso exclusivo del modulo de Mantenimiento de activos con Gestion de flotas."
	#define STR0067 "No se pudo actualizar en el banco de datos la tabla "
	#define STR0068 "Favor actualizar la tabla manualmente."
	#define STR0069 " - Modificado formato del campo "
	#define STR0070 "Inicio: "
	#define STR0071 "Verificando Relaciones"
	#define STR0072 "Relaciones SX9"
	#define STR0073 "Creando relacion "
	#define STR0074 " con "
	#define STR0075 "Ya creado relacion "
	#define STR0076 " - Tamano del campo modificado"
	#define STR0077 "Detalles del proceso."
	#define STR0078 " - Se modifico el titulo del campo."
	#define STR0079 " - Ya se modifico el titulo del campo."
	#define STR0080 " - Se modifico la utilizacion del campo."
	#define STR0081 " - Ya se modifico la utilizacion del campo."
	#define STR0082 "Inconsistencias:"
	#define STR0083 "¡La empresa "
	#define STR0084 " no esta autorizada!"
#else
	#ifdef ENGLISH
		#define STR0001 "This routine cannot be executed through the menu."
		#define STR0002 "It must be executed through IDE."
		#define STR0003 "Warning!"
		#define STR0004 "This routine updates the environment for module "
		#define STR0005 " and must be used exclusevly. "
		#define STR0006 "Update of Data Dictionary"
		#define STR0007 "Verifying the environment. Please, wait..."
		#define STR0008 "The company does not have Fleet Management."
		#define STR0009 "Finished!"
		#define STR0010 "On hold"
		#define STR0011 "Processing"
		#define STR0012 "Finished"
		#define STR0013 "With errors"
		#define STR0014 "Processed"
		#define STR0015 "Not processed"
		#define STR0016 "Company"
		#define STR0017 "Update Registry"
		#define STR0018 "Operation"
		#define STR0019 "Checking Parameters"
		#define STR0020 "Checking Queries"
		#define STR0021 "Checking Triggers"
		#define STR0022 "Checking Tables"
		#define STR0023 "Checking Indexes"
		#define STR0024 "Checking data dictionary"
		#define STR0025 "Updating database "
		#define STR0026 "Finishing updates"
		#define STR0027 "Change in tables: "
		#define STR0028 "Fields:"
		#define STR0029 "Indexes in order:"
		#define STR0030 "Parameters: "
		#define STR0031 "Process closed. Update in exclusive mode!"
		#define STR0032 ") - Table created"
		#define STR0033 ") - It had its only key changed"
		#define STR0034 " - Created"
		#define STR0035 " - Already existing"
		#define STR0036 " - Order Key Changed "
		#define STR0037 " - Field created"
		#define STR0038 " - Validation changed"
		#define STR0039 " - Field F3 changed "
		#define STR0040 " - Field size changed "
		#define STR0041 "Parameter created "
		#define STR0042 "Parameter already exists. "
		#define STR0043 " Table: "
		#define STR0044 "Attention"
		#define STR0045 "Opening company table is impossible in exclusive mode!"
		#define STR0046 "Opening file is impossible "
		#define STR0047 ". Do you want to continue updating in other companies?"
		#define STR0048 "Yes"
		#define STR0049 "No"
		#define STR0050 "Process closed. Problem with file "
		#define STR0051 "Problem with file "
		#define STR0052 "Text files (*.TXT) |*.txt|"
		#define STR0053 "Data Update"
		#define STR0054 "Process concluded"
		#define STR0055 "Save as..."
		#define STR0056 " - Existing field"
		#define STR0057 "Trigger generated for the field "
		#define STR0058 "Triggers: "
		#define STR0059 "Existing Trigger for the field "
		#define STR0060 "Query generated   "
		#define STR0061 "Existing query "
		#define STR0062 "Queries "
		#define STR0063 "Do you wish to continue operation?"
		#define STR0064 "It is recommended to backup the dictionary and the database. "
		#define STR0065 "Validating data for the update."
		#define STR0066 "This update is used exclusively by Asset Maint with Fleet Mgmt module."
		#define STR0067 "Could not update in database table "
		#define STR0068 "Please update the table manually."
		#define STR0069 " - Field format changed "
		#define STR0070 "Start: "
		#define STR0071 "Checking Relationships"
		#define STR0072 "SX9 Relationships"
		#define STR0073 "Relationship created "
		#define STR0074 " with "
		#define STR0075 "Relationship already created "
		#define STR0076 " - Field size already changed"
		#define STR0077 "Process details."
		#define STR0078 " - Field Title changed."
		#define STR0079 " - Field Title already changed."
		#define STR0080 " - Field Used changed."
		#define STR0081 " - Field Used already changed."
		#define STR0082 "Inconsistencies:"
		#define STR0083 "The company "
		#define STR0084 " is not authorized!"
	#else
		#define STR0001 "Esta rotina não pode ser executada a partir do menu."
		#define STR0002 "Deverá ser executada via IDE."
		#define STR0003 "Aviso!"
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Esta rotina actualiza o ambiente para o módulo ", "Esta rotina atualiza o ambiente para o módulo " )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", " e deve ser usada em modo exclusivo. Deseja continuar a operação?", " e deve ser usada em modo exclusivo." )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Actualização do dicionário de dados", "Atualização do Dicionário de Dados" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "A verificar o ambiente. Aguarde...", "Verificando o ambiente. Aguarde..." )
		#define STR0008 "Empresa não utiliza Gestão de Frotas"
		#define STR0009 "Concluído!"
		#define STR0010 "Em espera"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "A processar", "Processando" )
		#define STR0012 "Finalizado"
		#define STR0013 "Com Erros"
		#define STR0014 "Processado"
		#define STR0015 "Não Processado"
		#define STR0016 "Empresa"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Registro de actualização", "Registro de atualização" )
		#define STR0018 "Operação"
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "A verificar os parâmetros", "Verificando Parâmetros" )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "A verificar as consultas", "Verificando Consultas" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "A verificar os gatilhos", "Verificando Gatilhos" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "A verificar as tabelas", "Verificando Tabelas" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "A verificar os índices", "Verificando Índices" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "A verificar o dicionário de dados.", "Verificando dicionário de dados" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "A actualizar base de dados. ", "Atualizando banco de dados. " )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "A finalizar as actualizações", "Finalizando as atualizações" )
		#define STR0027 "Alteração nas tabelas: "
		#define STR0028 "Campos:"
		#define STR0029 "Índices na ordem:"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Parâmetros ", "Parâmetros: " )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Processo encerrado Execute Update em modo Exclusivo!", "Processo encerrado. Execute Update em modo Exclusivo!" )
		#define STR0032 ") - Tabela Criada"
		#define STR0033 ") - Teve sua Chave Única alterada"
		#define STR0034 " - Criado"
		#define STR0035 " - Já existente"
		#define STR0036 If( cPaisLoc $ "ANG|PTG", " - Alterada Chave da Ordem ", " - Alterado Chave da Ordem " )
		#define STR0037 " - Campo criado"
		#define STR0038 If( cPaisLoc $ "ANG|PTG", " - Alterada validação", " - Alterado validação" )
		#define STR0039 " - Alterado F3 do campo "
		#define STR0040 " - Alterado tamanho do campo "
		#define STR0041 "Criado Parâmetro "
		#define STR0042 "Já existe Parâmetro "
		#define STR0043 " Tabela: "
		#define STR0044 "Atenção"
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Impossível abrir a tabela de empresas de forma exclusiva!", "Impossível abrir a tabela de empresas de forma exclusiva !" )
		#define STR0046 "Impossível abrir arquivo "
		#define STR0047 ". Deseja continuar o update nas demais empresas?"
		#define STR0048 "Sim"
		#define STR0049 "Não"
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Processo encerrado Problema com arquivo ", "Processo encerrado. Problema com arquivo " )
		#define STR0051 "Problema com arquivo "
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Ficheiros Texto (*.TXT) |*.txt|", "Arquivos Texto (*.TXT) |*.txt|" )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Actualização de dados", "Atualizacao de Dados" )
		#define STR0054 "Processo concluído"
		#define STR0055 "Salvar Como..."
		#define STR0056 " - Campo já existe"
		#define STR0057 "Criado Gatilho para campo "
		#define STR0058 "Gatilhos: "
		#define STR0059 "Já existe Gatilho para campo "
		#define STR0060 "Criada consulta  "
		#define STR0061 "Já existe Consulta "
		#define STR0062 "Consultas: "
		#define STR0063 "Deseja continuar a operação?"
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "É recomendado fazer uma cópia de segurança do dicionário e base de dados.", "É recomendado fazer uma cópia de segurança do dicionário e banco de dados." )
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Validando informações para a actualização.", "Validando informações para a atualização." )
		#define STR0066 "Este update é de uso exclusivo do módulo de Manutenção de Ativos com Gestão de Frotas."
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Não foi possível actualizar na base de dados tabela ", "Não foi possível atualizar no banco de dados tabela " )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Favor actualizar tabela manualmente.", "Favor atualizar tabela manualmente." )
		#define STR0069 " - Alterado formato do campo "
		#define STR0070 "Início: "
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "A Verificar Relações", "Verificando Relacionamentos" )
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Relações SX9", "Relacionamentos SX9" )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Criada relação ", "Criado relacionamento " )
		#define STR0074 " com "
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Já criada relação ", "Já criado relacionamento " )
		#define STR0076 " - Tamanho do campo já alterado"
		#define STR0077 "Detalhes do processo."
		#define STR0078 If( cPaisLoc $ "ANG|PTG", " - Alterado o tíitulo do campo.", " - Alterado Titulo do campo." )
		#define STR0079 If( cPaisLoc $ "ANG|PTG", " - Já alterado título do campo.", " - Já alterado Titulo do campo." )
		#define STR0080 If( cPaisLoc $ "ANG|PTG", " - Alterado usado do campo.", " - Alterado Usado do campo." )
		#define STR0081 If( cPaisLoc $ "ANG|PTG", " - Já alterado usado do campo.", " - Já alterado Usado do campo." )
		#define STR0082 "Inconsistências:"
		#define STR0083 "A empresa "
		#define STR0084 " não está autorizada!"
	#endif
#endif
