#ifdef SPANISH
	#define STR0001 "El parámetro"
	#define STR0002 "El indicador"
	#define STR0003 "Tipo de valor no válido para el campo"
	#define STR0004 "El campo"
	#define STR0005 "es obligatorio."
	#define STR0006 "Registro del campo"
	#define STR0007 "no se encontró."
	#define STR0008 "Valor del campo"
	#define STR0009 "no válido."
	#define STR0010 "Valor no válido para campos De/A."
	#define STR0011 "Valor"
	#define STR0012 "no se encontró en la tabla"
	#define STR0013 "Atención"
	#define STR0014 "no se encontró en la tabla de Tipos de parámetro. Por favor, modifique el parámetro informado o realice la inclusión en la tabla de Tipos de parámetro."
	#define STR0015 "no se encontró."
#else
	#ifdef ENGLISH
		#define STR0001 "Parameter"
		#define STR0002 "The indicator"
		#define STR0003 "Type of value invalid for the field "
		#define STR0004 "The field "
		#define STR0005 " is mandatory."
		#define STR0006 "Field record "
		#define STR0007 " not found."
		#define STR0008 "Field Value "
		#define STR0009 " invalid."
		#define STR0010 "Valor inválido para campos De/Até."
		#define STR0011 "Value "
		#define STR0012 " does not found in the table "
		#define STR0013 "Attention"
		#define STR0014 "not found in the table of Types of Parameter. Please, edit the parameter informed or add to the Types of Parameters table."
		#define STR0015 "was not found."
	#else
		#define STR0001 "O parâmetro"
		#define STR0002 "O indicador "
		#define STR0003 "Tipo de valor inválido para o campo "
		#define STR0004 "O campo "
		#define STR0005 " é obrigatório."
		#define STR0006 "Registro do campo "
		#define STR0007 " não encontrado."
		#define STR0008 "Valor do campo "
		#define STR0009 " inválido."
		#define STR0010 "Valor inválido para campos De/Até."
		#define STR0011 "Valor "
		#define STR0012 " não econtrado na tabela "
		#define STR0013 "Atenção"
		#define STR0014 "não foi encontrado na tabela de Tipos de Parâmetro. Por favor alterar o parâmetro informado ou realizar a inclusão na tabela de Tipos de Parâmetros."
		#define STR0015 " não foi localizado."
	#endif
#endif
