#ifdef SPANISH
	#define STR0001 "Nº Fact."
	#define STR0002 "Serie"
	#define STR0003 "Fact. se clasificó"
	#define STR0004 "Factura no se encontró"
	#define STR0005 "Producto no se encontró ¡Imposible continuar!"
	#define STR0006 "Actualizando Factura previa"
	#define STR0007 "Procesando"
	#define STR0008 "¡Factura previa actualizada con éxito!"
	#define STR0009 "Error: "
	#define STR0010 "Informe la Factura previa para vincular con el pedido de compra JD."
	#define STR0011 "Proveedor"
	#define STR0012 "Tienda"
	#define STR0013 "No fue posible ubicar un Pedido con cantidad suficiente para bajar. Producto: "
	#define STR0014 " Ítem del pedido: "
	#define STR0015 " Cantidad: "
	#define STR0016 "Actualice el pedido mediante el OFINJD10 para poder dar entrada de la factura normalmente."
	#define STR0017 "¡Usuario no tiene acceso al WebService, verifique!"
	#define STR0018 "¡Atención!"
	#define STR0019 "La factura no se encontró por el Webservice de John Deere. ¡Por favor, verifique! "
	#define STR0020 "Número y serie de la factura: "
	#define STR0021 "Esta rutina se activa de forma interna por el proceso de recepción de factura de entrada de piezas denominado IMPXML. ¡De esta manera, esta rutina no puede ejecutarse directamente por el menú del módulo!"
	#define STR0022 "Pedido de fábrica:"
	#define STR0023 "no encontrado en la base, talvez el pedido aun no esté adecuado en el jdprism."
	#define STR0024 "Devolución del WebService"
#else
	#ifdef ENGLISH
		#define STR0001 "Tax Invoice No"
		#define STR0002 "Series"
		#define STR0003 "Invoice already classified"
		#define STR0004 "Invoice not found"
		#define STR0005 "Product not found, you cannot continue!"
		#define STR0006 "Updating Pro Forma Invoice"
		#define STR0007 "Processing"
		#define STR0008 "Pro Forma Invoice successfully updated!"
		#define STR0009 "Error: "
		#define STR0010 "Enter pro forma invoice to related with JD purchase order."
		#define STR0011 "Supplier"
		#define STR0012 "Store"
		#define STR0013 "Unable to find Order with quantity enough to write-off. Product: "
		#define STR0014 " Order Item: "
		#define STR0015 " Quantity: "
		#define STR0016 "Update order through OFINJD10 to enter invoice"
		#define STR0017 "User does not have access to WebService, check it!"
		#define STR0018 "Attention!"
		#define STR0019 "Invoice not found by Webservice of John Deere. Please check it! "
		#define STR0020 "Number of invoice and series: "
		#define STR0021 "This routine is internally called by the receipt process of inbound invoice for parts called IMPXML. Thus, you cannot run this routine directly through module menu!"
		#define STR0022 "Factory Order: "
		#define STR0023 " not found in the base, maybe the order is not suitable in the jdprism."
		#define STR0024 "WebService return"
	#else
		#define STR0001 "Nro.NF"
		#define STR0002 "Série"
		#define STR0003 "NF já foi classificada"
		#define STR0004 "Nota Fiscal não encontrada"
		#define STR0005 "Produto não encontrado, impossível continuar!"
		#define STR0006 "Atualizando Pré-Nota"
		#define STR0007 "Processando"
		#define STR0008 "Pré-Nota atualizada com sucesso!"
		#define STR0009 "Error: "
		#define STR0010 "Informe a pré-nota para relacionar com o pedido de compra JD."
		#define STR0011 "Fornecedor"
		#define STR0012 "Loja"
		#define STR0013 "Não foi possível localizar Pedido com quantidade suficiente para baixar. Produto: "
		#define STR0014 " Item do Pedido: "
		#define STR0015 " Quantidade: "
		#define STR0016 "Atualize pedido via OFINJD10 para poder dar entrada normalmente da nota"
		#define STR0017 "Usuário não tem acesso ao WebService, verifique!"
		#define STR0018 "Atenção!"
		#define STR0019 "A nota fiscal não foi encontrada pelo Webservice da John Deere. Por favor, verifique! "
		#define STR0020 "Número da nota fiscal e série: "
		#define STR0021 "Esta rotina é chamada de forma interna pelo processo de recebimento de nota fiscal de entrada de peças denominado IMPXML. Desta forma, esta rotina não pode ser executada diretamente por menu de módulo!"
		#define STR0022 "Pedido de fábrica: "
		#define STR0023 " não encontrado na base, talvez o pedido não esteja ainda adequado no jdprism."
		#define STR0024 "Retorno do WebService"
	#endif
#endif
