#ifdef SPANISH
	#define STR0001 "Esta rutina realiza la extraccion manual y configuracion de parametros"
	#define STR0002 "de la informacion de piezas para control de reposicion de stock."
	#define STR0003 "DPMEXT - Dealer Parts Management - John Deere - 2013"
	#define STR0004 "DPMEXT - Dealer Parts Management"
	#define STR0005 "Aguarde..."
	#define STR0006 "Exportando archivo texto."
	#define STR0007 "La operacion fue realizada con exito"
	#define STR0008 "Atencion"
	#define STR0009 "Directorio"
	#define STR0010 "Tipo de Extraccion"
	#define STR0011 "Delta"
	#define STR0012 "Inicializacion"
	#define STR0013 "Carga de Datos"
	#define STR0014 "Parts Locator"
	#define STR0015 "JDPoint"
	#define STR0016 "Ambos"
	#define STR0017 "Grupos Considerados"
	#define STR0018 "Ultimo DPMORD"
	#define STR0019 "Ultimo DPMXFER"
	#define STR0020 "Extraccion de datos realizada con Exito"
	#define STR0021 "Fc/hr Ult. Ext"
	#define STR0022 " Nro de la Cuenta Principal"
	#define STR0023 "¿Lleva stock?"
	#define STR0024 "Si"
	#define STR0025 "No"
	#define STR0026 "Liberado"
	#define STR0027 "Enviado"
	#define STR0028 "Recibido"
	#define STR0029 "OFINJD06 No se puede generar debido a una falla en el procesamiento de datos diario(OFINJD12/OFINJD31 en el prism)."
#else
	#ifdef ENGLISH
		#define STR0001 "In this routine, you can perform manually extraction and parameter configuration"
		#define STR0002 "of information on inventory replacement control spare parts."
		#define STR0003 "DPMEXT - Dealer Parts Management - John Deere - 2013"
		#define STR0004 "DPMEXT - Dealer Parts Management"
		#define STR0005 "Wait..."
		#define STR0006 "Exporting text file."
		#define STR0007 "Operation successfully performed"
		#define STR0008 "Attention"
		#define STR0009 "Directory"
		#define STR0010 "Extraction Type"
		#define STR0011 "Delta"
		#define STR0012 "Initialization"
		#define STR0013 "Data Loading"
		#define STR0014 "Parts Locator"
		#define STR0015 "JDPoint"
		#define STR0016 "Both"
		#define STR0017 "Considered Groups"
		#define STR0018 "Last DPMORD"
		#define STR0019 "Last DPMXFER"
		#define STR0020 "Data Extraction Successfully Performed"
		#define STR0021 "Ext Last Dt/hr  "
		#define STR0022 " Main Account Number"
		#define STR0023 "Take Stock?"
		#define STR0024 "Yes"
		#define STR0025 "No"
		#define STR0026 "Released"
		#define STR0027 "Sent"
		#define STR0028 "Received"
		#define STR0029 "OFINJD06 Unable to generate due to failure in daily data processing (OFINJD12/OFINJD31 no prism)."
	#else
		#define STR0001 "Essa rotina realiza a extração manual e configuração de parâmetros"
		#define STR0002 "das informações de peças para controle de reposição de estoque."
		#define STR0003 "DPMEXT - Dealer Parts Management - John Deere - 2013"
		#define STR0004 "DPMEXT - Dealer Parts Management"
		#define STR0005 "Aguarde..."
		#define STR0006 "Exportando arquivo texto."
		#define STR0007 "A operação foi realizada com sucesso"
		#define STR0008 "Atenção"
		#define STR0009 "Diretório"
		#define STR0010 "Tipo de Extração"
		#define STR0011 "Delta"
		#define STR0012 "Inicialização"
		#define STR0013 "Carregamento Dados"
		#define STR0014 "Parts Locator"
		#define STR0015 "JDPoint"
		#define STR0016 "Ambos"
		#define STR0017 "Grupos Considerados"
		#define STR0018 "Último DPMORD"
		#define STR0019 "Último DPMXFER"
		#define STR0020 "Extração de Dados Realizada com Sucesso"
		#define STR0021 "Dt/hr Ult. Ext"
		#define STR0022 " Nro da Conta Principal"
		#define STR0023 "Leva Estoque?"
		#define STR0024 "Sim"
		#define STR0025 "Não"
		#define STR0026 "Liberado"
		#define STR0027 "Enviado"
		#define STR0028 "Recebido"
		#define STR0029 "OFINJD06 Não pode ser gerado devido a falha no processamento de dados diário(OFINJD12/OFINJD31 no prism)."
	#endif
#endif
