#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Solicitar"
	#define STR0003 "Modificar"
	#define STR0004 "Solicitud de Servicios"
	#define STR0005 "Filtro"
	#define STR0006 "Servicio"
	#define STR0007 "Apunte Manual"
	#define STR0008 "Codigo Servicio + Secuencia + Fecha Inicial + Hora"
	#define STR0009 "Codigo del Mecanico + Fecha Inicial + Hora"
	#define STR0010 "Fecha Inicial + Hora"
	#define STR0011 "&Duplicar"
	#define STR0012 "Herramientas"
	#define STR0013 "Servicios"
	#define STR0014 "Piezas"
	#define STR0015 "Agrupado"
	#define STR0016 "Presupuesto"
	#define STR0017 "Agrupamiento de Servicio"
	#define STR0018 "Codigo"
	#define STR0019 "Descripcion"
	#define STR0020 "Cantidad"
	#define STR0021 "¡Solicita Pieza Automaticamente!"
	#define STR0022 "&Leyenda"
	#define STR0023 "Suborden"
	#define STR0024 "Hora..: "
	#define STR0025 "Emision: "
	#define STR0026 "OS.: "
	#define STR0027 "Num.Req.:"
	#define STR0028 "Abierta en "
	#define STR0029 " a las "
	#define STR0030 "Box: "
	#define STR0031 "Marca: "
	#define STR0032 "Modelo: "
	#define STR0033 "Matricula: "
	#define STR0034 " Km"
	#define STR0035 "Conductor: "
	#define STR0036 "Cliente: "
	#define STR0037 "Chasis: "
	#define STR0038 "Flota:"
	#define STR0039 "Servicio por Ejecutar"
	#define STR0040 "Mecanicos Habilitados"
	#define STR0041 "Num.Veces Codigo Nombre"
	#define STR0042 "Servicio "
	#define STR0043 "Tipo"
	#define STR0044 "Seccion"
	#define STR0045 "Grupo"
	#define STR0046 "Tp Estandar"
	#define STR0047 "Herramientas-Descripcion"
	#define STR0048 "AP."
	#define STR0049 "RP."
	#define STR0050 "Servicio----------Descripcion"
	#define STR0051 "Ejecutado por:"
	#define STR0052 "Jefe Taller:"
	#define STR0053 "Detalle de la Descripcion"
	#define STR0054 "Itemes Solicitados en la OS - Modificar"
	#define STR0055 "Tipo de Tiempo + Cliente + Codigo del Servicio"
	#define STR0056 "Cliente + Tipo de Tiempo + Codigo del Servicio"
	#define STR0057 "Tipo Tiempo"
	#define STR0058 "Cod Cliente"
	#define STR0059 "Tienda"
	#define STR0060 "Dep Interno"
	#define STR0061 "Dep Garantia"
	#define STR0062 "Itemes"
	#define STR0063 "Tiempo"
	#define STR0064 "Orden"
	#define STR0065 "Se modificaran todos los clientes de tipo de tiempo"
	#define STR0066 "¡Atencion!"
	#define STR0067 "¿Confirma retorno?"
	#define STR0068 "Retorno de Servicio"
	#define STR0069 "Num.OS"
	#define STR0070 "Servicio"
	#define STR0071 "Tp Srv"
	#define STR0072 "Fch Aplic"
	#define STR0073 "Fch Cierra"
	#define STR0074 "Kilometraje"
	#define STR0075 "Tp"
	#define STR0076 "Num.Fact"
	#define STR0077 "Productivos"
	#define STR0078 "Nombre"
	#define STR0079 "Tp Trab"
	#define STR0080 "Tp Cobr"
	#define STR0081 "Vlr Srv"
	#define STR0082 "Valor"
	#define STR0083 "Transferencia de las piezas del servicio agrupado"
	#define STR0084 "Codigo Productivo"
	#define STR0085 "¿Crea servicios de franquicia?"
	#define STR0086 "Grp Inconv"
	#define STR0087 "Inconveniente"
	#define STR0088 "¿Inicializa Servicio?"
	#define STR0089 "¿Finaliza Servicio?"
	#define STR0090 "Orden de Servicio On-line"
	#define STR0091 "¡Tipo de servicio no podra modificarse! Estatus incompatibles."
	#define STR0092 "Pieza ya seleccionada para Requisicion"
	#define STR0093 "Pendiente"
	#define STR0094 "Liberada"
	#define STR0095 "Cerrada"
	#define STR0096 "Anulada"
	#define STR0097 "Leyenda"
	#define STR0098 "¡Usuario no autorizado!"
	#define STR0099 "Tiempo total de la etapa("
	#define STR0100 ") superior al tiempo total estandar("
	#define STR0101 "OS: "
	#define STR0102 "Tipo Tiempo: "
	#define STR0103 "Tp.Tiempo Franquicia: "
	#define STR0104 "¡Cliente bloqueado!"
	#define STR0105 "&Solicitud de Servicio"
	#define STR0106 "Sin escala"
	#define STR0107 "Fuera del Turno"
	#define STR0108 "Ausente"
	#define STR0109 "Disponible"
	#define STR0110 "En ejecucion"
	#define STR0111 "Productivo"
	#define STR0112 "Necesario informar el Kilometraje"
	#define STR0113 "Existe pedido de compra para este servicio."
	#define STR0114 "¡Tipo de tiempo invalido!"
	#define STR0115 "¡Grupo de servicio invalido!"
	#define STR0116 "¡Servicio invalido!"
	#define STR0117 "¡Tipo de Servicio invalido!"
	#define STR0118 "¡Seccion invalida!"
	#define STR0119 "¡Mecanico con hora abierta!"
	#define STR0120 "Nro OS....:"
	#define STR0121 "Servicio..."
	#define STR0122 "Productivo.:"
	#define STR0123 "Fecha Inicial:"
	#define STR0124 "Hora Inicial:"
	#define STR0125 "Fecha Final...:"
	#define STR0126 "Hora Final...:"
	#define STR0127 "Valor informado no permitido."
	#define STR0128 "Valor informado"
	#define STR0129 "Valor de la hora"
	#define STR0130 "Porcentaje permitido"
	#define STR0131 "Valor Min/Max permitido"
	#define STR0132 "a"
	#define STR0133 "El tipo de servicio no necesita de apunte o no existen servicios requisitados."
	#define STR0134 "Mecanico con hora marcada en este horario"
	#define STR0135 "Mecanico: "
	#define STR0136 "Fecha: "
	#define STR0137 "Hora: "
	#define STR0138 "Apunte de Servicio"
	#define STR0139 "Grabando servicios"
	#define STR0140 "Informar departamento de la garantia"
	#define STR0141 "Informar departamento interno"
	#define STR0142 "Tipo de Tiempo no encontrado"
	#define STR0143 "No existe tipo de tiempo con apunte automatico para orden de servicio"
	#define STR0144 "Sin apunte"
	#define STR0145 "En Ejecucion"
	#define STR0146 "Finalizado"
	#define STR0147 "Busq.Avanzada"
	#define STR0148 "Control de Srv. Tercero"
	#define STR0149 "¡no pertenece a esta sucursal , verifique!"
	#define STR0150 "Seleccionar un registro para apunte."
	#define STR0151 "Intente nuevamente."
	#define STR0152 "Tipo de tiempo no encontrado en la matriz del apunte."
	#define STR0153 "Se modifico la situacion del tipo de tiempo."
	#define STR0154 "El tecnico no es un mecanico"
	#define STR0155 "¡Se realizaran Apuntes por otra rutina que imposibilitan esta grabacion!"
	#define STR0156 "Productivo trabajando en otro servicio"
	#define STR0157 "Es una pausa del servicio"
	#define STR0158 "Atencion"
	#define STR0159 " Detuvo OS: "
	#define STR0160 ", TT: "
	#define STR0161 ", Srv:"
	#define STR0162 ", Mot:"
	#define STR0163 "Mec.:"
	#define STR0164 "El prorrateo esta divergente para el productivo."
	#define STR0165 "La suma de los porcentajes no puede ser superior al 100%."
	#define STR0166 "Complete el codigo del productivo."
	#define STR0167 "Usuario sin acceso para informar"
	#define STR0168 "valor fijo de servicio."
	#define STR0169 "Valor fijo de servicio informado"
	#define STR0170 "no permitido."
	#define STR0171 "Marca / Modelo"
	#define STR0172 "Código del servicio"
	#define STR0173 "Descripción Servicio"
	#define STR0174 "Grupo del servicio"
	#define STR0175 "¡Grupo de servicio no esta vinculado al Código de servicio!"
	#define STR0176 "Grupo informado:"
	#define STR0177 "Grupo correcto:"
	#define STR0178 "Vincular campaña"
	#define STR0179 "Servicio no se encontró entre los servicios solicitados."
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "Request"
		#define STR0003 "Edit"
		#define STR0004 "Services Requisition"
		#define STR0005 "Filter"
		#define STR0006 "Service"
		#define STR0007 "Mannual Annotation"
		#define STR0008 "Service Code + Sequence + Initial Date + Time"
		#define STR0009 "Mechanic Code + Initial Date + Time"
		#define STR0010 "Initial Date + Time"
		#define STR0011 "&Duplicate"
		#define STR0012 "Tools"
		#define STR0013 "Services"
		#define STR0014 "Parts"
		#define STR0015 "Grouped"
		#define STR0016 "Quotation"
		#define STR0017 "Service Grouping"
		#define STR0018 "Code"
		#define STR0019 "Description"
		#define STR0020 "Quantity"
		#define STR0021 "Request Part Automatically!"
		#define STR0022 "&Caption"
		#define STR0023 "Sub-Order"
		#define STR0024 "Time..: "
		#define STR0025 "Issue: "
		#define STR0026 "SO.: "
		#define STR0027 "Req.Nbr.:"
		#define STR0028 "Opened on "
		#define STR0029 " at "
		#define STR0030 "Box: "
		#define STR0031 "Brand: "
		#define STR0032 "Model: "
		#define STR0033 "Plate no.  : "
		#define STR0034 " Km"
		#define STR0035 "Driver: "
		#define STR0036 "Customer: "
		#define STR0037 "Chassis: "
		#define STR0038 "Fleet:"
		#define STR0039 "Service to Execute"
		#define STR0040 "Qualified Mechanics"
		#define STR0041 "No. of Times Code Name"
		#define STR0042 "Service "
		#define STR0043 "Type"
		#define STR0044 "Section "
		#define STR0045 "Group"
		#define STR0046 "Standard Tp."
		#define STR0047 "Tools-Description"
		#define STR0048 "AP"
		#define STR0049 "RP"
		#define STR0050 "Service----------Description"
		#define STR0051 "Executed by:"
		#define STR0052 "Repair Shop Responsible:"
		#define STR0053 "Description Detailing"
		#define STR0054 "SO Requested Items - Edit"
		#define STR0055 "Type of Time + Customer + Service Code"
		#define STR0056 "Customer + Type of Time + Service Code"
		#define STR0057 "Type of Time"
		#define STR0058 "Customer Code"
		#define STR0059 "Unit"
		#define STR0060 "Internal Dep."
		#define STR0061 "Warranty Dep."
		#define STR0062 "Items"
		#define STR0063 "Time"
		#define STR0064 "Order"
		#define STR0065 "All customers related to time type will be updated"
		#define STR0066 "Attention!"
		#define STR0067 "Confirm return?"
		#define STR0068 "Service Return"
		#define STR0069 "SO Nbr"
		#define STR0070 "Service"
		#define STR0071 "Srv.Tp."
		#define STR0072 "Appl.Dt."
		#define STR0073 "Clos.Dt."
		#define STR0074 "Kilometers  "
		#define STR0075 "Tp."
		#define STR0076 "Inv.No."
		#define STR0077 "Labor Force"
		#define STR0078 "Name"
		#define STR0079 "Work Tp."
		#define STR0080 "Collec.Tp."
		#define STR0081 "Srv.Val."
		#define STR0082 "Value"
		#define STR0083 "Grouped service parts transfer"
		#define STR0084 "Production Worker Code"
		#define STR0085 "Create franchising services?"
		#define STR0086 "Grp Inconv"
		#define STR0087 "Inconvenient"
		#define STR0088 "Start Service?"
		#define STR0089 "End Service?"
		#define STR0090 "On Line Service Order"
		#define STR0091 "Service type cannot be changed! Incompatible Status."
		#define STR0092 "Part already selected for Request"
		#define STR0093 "Open"
		#define STR0094 "Released"
		#define STR0095 "Closed"
		#define STR0096 "Canceled"
		#define STR0097 "Caption"
		#define STR0098 "User not authorized!"
		#define STR0099 "Total time of the stage ("
		#define STR0100 ") is after the standard total time ("
		#define STR0101 "Service Order: "
		#define STR0102 "Time Type: "
		#define STR0103 "Franchising Time Type: "
		#define STR0104 "Customer Blocked!"
		#define STR0105 "Service Request"
		#define STR0106 "Without Scale"
		#define STR0107 "Out of Shift"
		#define STR0108 "Absent"
		#define STR0109 "Available"
		#define STR0110 "In progress"
		#define STR0111 "Productive"
		#define STR0112 "It is necessary to enter mileage"
		#define STR0113 "There is purchase order for this service."
		#define STR0114 "Type of time invalid!"
		#define STR0115 "Service Group invalid!"
		#define STR0116 "Invalid service!"
		#define STR0117 "Invalid type of service!"
		#define STR0118 "Invalid section!"
		#define STR0119 "Productive with pending hour!!"
		#define STR0120 "SO No."
		#define STR0121 "Service...:"
		#define STR0122 "Productive.:"
		#define STR0123 "Initial Dt.:"
		#define STR0124 "Initial Hr.:"
		#define STR0125 "Final Dt.:"
		#define STR0126 "Final Hr.:"
		#define STR0127 "Value entered is not allowed."
		#define STR0128 "Value Entered"
		#define STR0129 "Hour Value"
		#define STR0130 "Allowed Percentage"
		#define STR0131 "Min/max allowed value"
		#define STR0132 "to"
		#define STR0133 "Type of service does not request annotation or there are no services requested."
		#define STR0134 "Mechanism with time scheduled at this time!"
		#define STR0135 "Mechanic: "
		#define STR0136 "Date: "
		#define STR0137 "Time: "
		#define STR0138 "Service Annotation"
		#define STR0139 "Recording services"
		#define STR0140 "Enter department of guarantee"
		#define STR0141 "Enter internal department"
		#define STR0142 "Type of time was not found"
		#define STR0143 "There is no type of time with automatic annotation for service order!"
		#define STR0144 "No annotation"
		#define STR0145 "In progress"
		#define STR0146 "Finished"
		#define STR0147 "Advanced Search"
		#define STR0148 "Control of Third Party Service"
		#define STR0149 "does not belong to this branch, check it!"
		#define STR0150 "Select a record for note."
		#define STR0151 "Try again."
		#define STR0152 "Type of Time not found in note matrix."
		#define STR0153 "Type of Time situation modified."
		#define STR0154 "Technician is not productive"
		#define STR0155 "Annotations have been made by another routine that do not allow this saving!"
		#define STR0156 "Labor force working at another service"
		#define STR0157 "It is a break in service"
		#define STR0158 "Attention"
		#define STR0159 " paused SO: "
		#define STR0160 ", TT: "
		#define STR0161 ", Srv:"
		#define STR0162 ", Rea:"
		#define STR0163 "prod:"
		#define STR0164 "Apportionment differs from productive."
		#define STR0165 "Percentage sum cannot be larger than 100%"
		#define STR0166 "Fill out productive code."
		#define STR0167 "User without access to enter"
		#define STR0168 "fixed value of the service."
		#define STR0169 "Fixed value of the service entered"
		#define STR0170 "not allowed."
		#define STR0171 "Brand / Model"
		#define STR0172 "Service Code"
		#define STR0173 "Service Description"
		#define STR0174 "Service Group"
		#define STR0175 "Service group not related to service code"
		#define STR0176 "Group entered:"
		#define STR0177 "Correct group:"
		#define STR0178 "Relate Campaign"
		#define STR0179 "Service not found among the services requested."
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Requisitar"
		#define STR0003 "Alterar"
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Requisição De Serviços", "Requisicao de Servicos" )
		#define STR0005 "Filtro"
		#define STR0006 "Serviço"
		#define STR0007 "Apontamento Manual"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Código De Serviço + Seqüência + Data Inicial + Hora", "Codigo Servico + Sequencia + Data Inicial + Hora" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Código Do Mecânico + Data Inicial + Hora", "Codigo do Mecanico + Data Inicial + Hora" )
		#define STR0010 "Data Inicial + Hora"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Duplicar", "&Duplicar" )
		#define STR0012 "Ferramentas"
		#define STR0013 "Serviços"
		#define STR0014 "Peças"
		#define STR0015 "Agrupado"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Orçamento", "Orcamento" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Agrupamento De Serviço", "Agrupamento de Servico" )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Código", "Codigo" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Descrição", "Descricao" )
		#define STR0020 "Quantidade"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Requisitar Peças De Forma Automática!", "Requisita Peca Automaticamente!" )
		#define STR0022 "&Legenda"
		#define STR0023 "Sub Ordem"
		#define STR0024 "Hora..: "
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Emissão: ", "Emissao: " )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Os.: ", "OS.: " )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Número Requisitado:", "Nro Req.:" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "aBerta em ", "Aberta em " )
		#define STR0029 " as "
		#define STR0030 "Box: "
		#define STR0031 "Marca: "
		#define STR0032 "Modelo: "
		#define STR0033 "Placa: "
		#define STR0034 " Km"
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Condutor : ", "Motorista: " )
		#define STR0036 "Cliente: "
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Chassis: ", "Chassi: " )
		#define STR0038 "Frota:"
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Serviço A Executar", "Servico a Executar" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Mecânicos Habilitados", "Mecanicos Habilitados" )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Nº Vezes Código Nome", "Nr. Vezes Codigo Nome" )
		#define STR0042 "Serviço "
		#define STR0043 "Tipo"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Secção", "Secao" )
		#define STR0045 "Grupo"
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Tp Padrão", "Tp Padrao" )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Ferramentas - descrição", "Ferramentas-Descricao" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Ap", "AP" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Rp", "RP" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Serviço----------descrição", "Servico----------Descricao" )
		#define STR0051 "Executado por:"
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "Chefe Da Oficina:", "Chefe Oficina:" )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Detalhes Da Descrição", "Detalhamento da Descricao" )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Itens Requisitados Na Os - Alterar", "Itens Requisitados na OS - Alterar" )
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Tipo De Tempo + Cliente + Código Do Serviço", "Tipo de Tempo + Cliente + Codigo do Servico" )
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "Cliente + Tipo De Tempo + Código Do Serviço", "Cliente + Tipo de Tempo + Codigo do Servico" )
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Tipo De Tempo", "Tipo Tempo" )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Cód. Cliente", "Cod Cliente" )
		#define STR0059 "Loja"
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Dep. Interno", "Dep Interno" )
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Dep. Garantia", "Dep Garantia" )
		#define STR0062 "Itens"
		#define STR0063 "Tempo"
		#define STR0064 "Ordem"
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Todos os clientes do tipo de tempo serão alterados", "Sera Alterado todos os clientes do tipo de tempo" )
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "Atenção!!!", "Atencao!!!" )
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Confirmar a devolução?", "Confirma retorno?" )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Devolução De Serviço", "Retorno de Servico" )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Nr. Os", "Nro OS" )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Serviço", "Servico" )
		#define STR0071 "Tp Srv"
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Data Aplicável", "Dt Aplic" )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Data Do Fecho", "Dt Fecha" )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Quilometragem", "Kilometragem" )
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Tp.", "Tp" )
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Nº Da Factura", "Nro Nf" )
		#define STR0077 "Produtivos"
		#define STR0078 "Nome"
		#define STR0079 "Tp Trab"
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "Tipo De Cobrança", "Tp Cobr" )
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "Valor Do Serviço", "Vlr Srv" )
		#define STR0082 "Valor"
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "Transferência das peças do serviço agrupado", "Transferencia das pecas do servico agrupado" )
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "Código Produtivo", "Codigo Produtivo" )
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "Criar serviços de franquia?", "Cria servicos de franquia?" )
		#define STR0086 If( cPaisLoc $ "ANG|PTG", "Grupo Inconveniente", "Grp Inconv" )
		#define STR0087 "Inconveniente"
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "Inicializar O Serviço?", "Inicializa Servico?" )
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "Finalizar O Serviço?", "Finaliza Servico?" )
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "Ordem De Serviço On Line", "Ordem de Servico On Line" )
		#define STR0091 If( cPaisLoc $ "ANG|PTG", "Tipo de serviço   não poderá ser alterado! estado incompativeis.", "Tipo de servico nao podera ser alterado! Status incompativeis." )
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "Peça ja seleccionada para Requisição.", "Peca ja selecionada para Requisicao" )
		#define STR0093 "Aberta"
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Autorizada", "Liberada" )
		#define STR0095 "Fechada"
		#define STR0096 "Cancelada"
		#define STR0097 "Legenda"
		#define STR0098 If( cPaisLoc $ "ANG|PTG", "Utilizador não autoriazado!", "Usuario nao autorizado!" )
		#define STR0099 "Tempo total da fase("
		#define STR0100 If( cPaisLoc $ "ANG|PTG", ") maior que o tempo total padrão(", ") maior que o tempo total padrao(" )
		#define STR0101 "OS: "
		#define STR0102 "Tipo Tempo: "
		#define STR0103 "Tp.Tempo Franquia: "
		#define STR0104 "Cliente Bloqueado!"
		#define STR0105 If( cPaisLoc $ "ANG|PTG", "Requisição de Serviço", "Requisicao de Servico" )
		#define STR0106 "Sem escala"
		#define STR0107 "Fora do Turno"
		#define STR0108 "Ausente"
		#define STR0109 If( cPaisLoc $ "ANG|PTG", "Disponível", "Disponivel" )
		#define STR0110 "Em Andamento"
		#define STR0111 "Produtivo"
		#define STR0112 If( cPaisLoc $ "ANG|PTG", "É necessário informar a Kilometragem", "Necessario informar a Kilometragem" )
		#define STR0113 If( cPaisLoc $ "ANG|PTG", "Existe pedido de compra para esse serviço.", "Existe pedido de compra para esse servico." )
		#define STR0114 If( cPaisLoc $ "ANG|PTG", "Tipo de tempo inválido!", "Tipo de tempo invalido!" )
		#define STR0115 If( cPaisLoc $ "ANG|PTG", "Grupo de serviço inválido!", "Grupo de servico invalido!" )
		#define STR0116 If( cPaisLoc $ "ANG|PTG", "Serviço inválido!", "Servico invalido!" )
		#define STR0117 If( cPaisLoc $ "ANG|PTG", "Tipo de Serviço inválido!", "Tipo de Servico invalido!" )
		#define STR0118 If( cPaisLoc $ "ANG|PTG", "Secção inválida!", "Secao invalida!" )
		#define STR0119 "Produtivo com hora aberta!"
		#define STR0120 If( cPaisLoc $ "ANG|PTG", "Nr. Os....:", "Nro Os....:" )
		#define STR0121 If( cPaisLoc $ "ANG|PTG", "Serviço...:", "Servico...:" )
		#define STR0122 "Produtivo.:"
		#define STR0123 If( cPaisLoc $ "ANG|PTG", "Dt.Inicial:", "Dt Inicial:" )
		#define STR0124 If( cPaisLoc $ "ANG|PTG", "Hr.Inicial:", "Hr Inicial:" )
		#define STR0125 If( cPaisLoc $ "ANG|PTG", "Dt.Final..:", "Dt Final..:" )
		#define STR0126 If( cPaisLoc $ "ANG|PTG", "Hr.Final..:", "Hr Final..:" )
		#define STR0127 "Valor informado não permitido."
		#define STR0128 "Valor informado"
		#define STR0129 "Valor da hora"
		#define STR0130 "Percentual permitido"
		#define STR0131 "Valor Min/Max permitido"
		#define STR0132 "a"
		#define STR0133 If( cPaisLoc $ "ANG|PTG", "O tipo de serviço não necessita de apontamento ou não existem serviços requisitados.", "O tipo de servico nao necessita de apontamento ou nao existem servicos requisitados." )
		#define STR0134 If( cPaisLoc $ "ANG|PTG", "Mecânico com hora marcada neste horário!", "Mecanico com hora marcada neste horario!" )
		#define STR0135 If( cPaisLoc $ "ANG|PTG", "Mecânico: ", "Mecanico: " )
		#define STR0136 "Data: "
		#define STR0137 "Hora: "
		#define STR0138 "Apontamento de Serviço"
		#define STR0139 If( cPaisLoc $ "ANG|PTG", "A gravar serviços", "Gravando servicos" )
		#define STR0140 "Informar departamento da garantia"
		#define STR0141 "Informar departamento interno"
		#define STR0142 "Tipo de Tempo não encontrado"
		#define STR0143 If( cPaisLoc $ "ANG|PTG", "Não existe tipo de tempo com apontamento automático para ordem de serviço!", "Nao existe tipo de tempo com apontamento automatico para ordem de servico!" )
		#define STR0144 "Sem apontamento"
		#define STR0145 "Em Andamento"
		#define STR0146 "Finalizado"
		#define STR0147 "Pesq.Avançada"
		#define STR0148 If( cPaisLoc $ "ANG|PTG", "Controlo de Srv. Terceiro", "Controle de Srv. Terceiro" )
		#define STR0149 If( cPaisLoc $ "ANG|PTG", "não pertence a esta filial. Verifique!", "não pertence a esta filial , verifique!" )
		#define STR0150 If( cPaisLoc $ "ANG|PTG", "Seleccionar um registo para apontamento.", "Selecionar um registro para apontamento." )
		#define STR0151 "Tente novamente."
		#define STR0152 If( cPaisLoc $ "ANG|PTG", "Tipo de tempo não encontrado na matriz de apontamento.", "Tipo de Tempo não encontrado na matriz de apontamento." )
		#define STR0153 If( cPaisLoc $ "ANG|PTG", "A situação do tipo de tempo foi alterada.", "A situação do Tipo de Tempo foi alterada." )
		#define STR0154 If( cPaisLoc $ "ANG|PTG", "O técnico não é um productivo", "Técnico não é um produtivo" )
		#define STR0155 "Foram realizados Apontamentos por outra rotina que impossibilitam essa gravação!"
		#define STR0156 If( cPaisLoc $ "ANG|PTG", "Produtivo a trabalhar em outro serviço", "Produtivo trabalhando em outro serviço" )
		#define STR0157 "É uma pausa do serviço"
		#define STR0158 "Atenção"
		#define STR0159 " pausou OS: "
		#define STR0160 ", TT: "
		#define STR0161 ", Srv:"
		#define STR0162 ", Mot:"
		#define STR0163 "prod:"
		#define STR0164 "O rateio está divergente para o produtivo."
		#define STR0165 "A soma dos percentuais não pode ser maior que 100%"
		#define STR0166 "Preencha o código do produtivo."
		#define STR0167 "Usuário sem acesso para informar"
		#define STR0168 "valor fixo de serviço."
		#define STR0169 "Valor fixo de serviço informado"
		#define STR0170 "não permitido."
		#define STR0171 "Marca / Modelo"
		#define STR0172 "Código do Serviço"
		#define STR0173 "Descrição Serviço"
		#define STR0174 "Grupo de Serviço"
		#define STR0175 "Grupo de Serviço não esta relacionado ao Código do Serviço!"
		#define STR0176 "Grupo Informado:"
		#define STR0177 "Grupo Correto:"
		#define STR0178 "Relacionar Campanha"
		#define STR0179 "Serviço não encontrado entre os serviços requisitados."
	#endif
#endif
