#ifdef SPANISH
	#define STR0001 "Digitac. Inventario"
	#define STR0002 "¿Qué ubicación?"
	#define STR0003 "Seleccione la ubicación"
	#define STR0004 "¿Pone en cero NO Digitados?"
	#define STR0005 "¿Qué ítem?"
	#define STR0006 "Seleccionar el ítem"
	#define STR0007 "Inventario no está en la etapa de Digitación."
	#define STR0008 "No existe Inventario en etapa de Digitación."
	#define STR0009 "Ubicación no se encontró en este inventario."
	#define STR0010 "Ítem no se encontró en este Inventario/Ubicación."
	#define STR0011 "Ítem no se encontró en Archivo de productos."
	#define STR0012 "¿Cantidad?"
	#define STR0013 "¿Poner en cero TODOS los ítems que NO se digitaron en TODAS las ubicaciones?"
	#define STR0014 "¿Poner en cero TODOS los ítems que NO se digitaron en la ubicación?"
	#define STR0015 "ítems dejados en cero con éxito."
	#define STR0016 "No se encontró ningún ítem."
	#define STR0017 "Inventario"
	#define STR0018 "Ubicación"
	#define STR0019 "Informe el Cód. Barras"
	#define STR0020 "Atención"
#else
	#ifdef ENGLISH
		#define STR0001 " Inventory"
		#define STR0002 "Which Address?"
		#define STR0003 "Select Address"
		#define STR0004 "Clear NOT Entered?"
		#define STR0005 "Which Item?"
		#define STR0006 "Select Item"
		#define STR0007 "Inventory not in Typing phase"
		#define STR0008 "No Inventory in Typing phase."
		#define STR0009 "Address not found in this Inventory."
		#define STR0010 "Item not found in this Inventory/Address."
		#define STR0011 "Item not found in Product Register."
		#define STR0012 "Quantity?"
		#define STR0013 "Clear ALL items that were NOT entered in ALL addresses?"
		#define STR0014 "Clear ALL items that were NOT entered in the address?"
		#define STR0015 "Items successfully zeroed."
		#define STR0016 "No item found."
		#define STR0017 "Inventory"
		#define STR0018 "Address"
		#define STR0019 "Beep Barcodes"
		#define STR0020 "Attention"
	#else
		#define STR0001 "Digitac. Inventario"
		#define STR0002 "Qual Endereco?"
		#define STR0003 "Selecionar Endereco"
		#define STR0004 "Zera NAO Digitados?"
		#define STR0005 "Qual Item?"
		#define STR0006 "Selecionar Item"
		#define STR0007 "Inventario nao esta na fase de Digitacao."
		#define STR0008 "Nao existe Inventario em fase de Digitacao."
		#define STR0009 "Endereco nao encontrado neste Inventario."
		#define STR0010 "Item nao encontrado neste Inventario/Endereco."
		#define STR0011 "Item nao encontrado no Cadastro de Produtos."
		#define STR0012 "Quantidade?"
		#define STR0013 "Zerar TODOS os Itens que NAO foram Digitados em TODOS os Enderecos?"
		#define STR0014 "Zerar TODOS os Itens que NAO foram Digitados no Endereco?"
		#define STR0015 "Itens zerados com sucesso."
		#define STR0016 "Nenhum Item encontrado."
		#define STR0017 "Inventario"
		#define STR0018 "Endereco"
		#define STR0019 "Bipar Cod.Barras"
		#define STR0020 "Atencao"
	#endif
#endif
