#ifdef SPANISH
	#define STR0001 "Pedidos de Transferencia de Piezas"
	#define STR0002 "Buscar"
	#define STR0003 "Aceptar Transf."
	#define STR0004 "Rechazar Transf."
	#define STR0005 "T.E.S."
	#define STR0006 "Pedido atendido"
	#define STR0007 "Leyenda"
	#define STR0008 "Pedido rechazado"
	#define STR0009 "Factura emitida"
	#define STR0010 "Entrada confirmada"
	#define STR0011 "¿Desea aceptar la transferencia?"
	#define STR0012 "¿Desea RECHAZAR la transferencia?"
	#define STR0013 "Atencion"
	#define STR0014 "Observacion"
	#define STR0015 "El item no posee stock en ninguna sucursal."
	#define STR0016 "Cantidad Solicitada"
	#define STR0017 "La cantidad solicitada es superior a la cantidad de la pieza en el presupuesto."
	#define STR0018 "Piezas en Exceso"
	#define STR0019 "Cantidad Faltante :"
	#define STR0020 "Saldos en exceso para el producto "
	#define STR0021 "Sucursal"
	#define STR0022 "Saldo"
	#define STR0023 "Solicitada"
	#define STR0024 "Pedido Pendiente"
#else
	#ifdef ENGLISH
		#define STR0001 "Part Transfer Orders"
		#define STR0002 "Search"
		#define STR0003 "Accept Transfer"
		#define STR0004 "Reject Transfer"
		#define STR0005 "TIO"
		#define STR0006 "Order Fulfilled"
		#define STR0007 "Caption"
		#define STR0008 "Order rejected"
		#define STR0009 "Invoice issued"
		#define STR0010 "Inflow confirmed"
		#define STR0011 "Do you want to accept the transfer?"
		#define STR0012 "Do you want to REJECT the transfer?"
		#define STR0013 "Attention"
		#define STR0014 "Note"
		#define STR0015 "No item stock in all branches."
		#define STR0016 "Quantity Requested"
		#define STR0017 "The quantity requested is larger than the part quantity in the quotation."
		#define STR0018 "Parts in Excess"
		#define STR0019 "Missing Quantity:"
		#define STR0020 "Exceeding balance for the product "
		#define STR0021 "Branch"
		#define STR0022 "Balance"
		#define STR0023 "Requested"
		#define STR0024 "Pending Order"
	#else
		#define STR0001 "Pedidos de Transferência de Peças"
		#define STR0002 "Pesquisar"
		#define STR0003 "Aceitar Transf."
		#define STR0004 "Rejeitar Transf."
		#define STR0005 "T.E.S."
		#define STR0006 "Pedido atendido"
		#define STR0007 "Legenda"
		#define STR0008 "Pedido rejeitado"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Fact. emitida", "NF emitida" )
		#define STR0010 "Entrada confirmada"
		#define STR0011 "Deseja aceitar a transferência ?"
		#define STR0012 "Deseja REJEITAR a transferência ?"
		#define STR0013 "Atenção"
		#define STR0014 "Observação"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "O item não possui stock em nenhuma filial.", "O item não possui estoque em nenhuma filial." )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Quantidade solicitada", "Quantidade Solicitada" )
		#define STR0017 "Quantidade solicitada é maior que a quantidade da peça no orçamento."
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Peças em excesso", "Peças em Excesso" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Quantidade faltante :", "Quantidade Faltante :" )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Saldos em excesso para o artigo ", "Saldos em excesso para o produto " )
		#define STR0021 "Filial"
		#define STR0022 "Saldo"
		#define STR0023 "Solicitada"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Pedido pendente", "Pedido Pendente" )
	#endif
#endif
