#ifdef SPANISH
	#define STR0001 "Esta rutina tiene como finalidad la generacion"
	#define STR0002 "del archivo con informacion denominada como AUTOSERVICE. La informacion sera"
	#define STR0003 "obtenida del sistema para envio a la ensambladora Volkswagen."
	#define STR0004 "Este informe muestra la informacion incluida en el archivo que se genero"
	#define STR0005 "para atender la solicitud de AUTOSERVICE de la marca Volkswagen."
	#define STR0006 "Exportacion Autoservice VW"
	#define STR0007 "Espere..."
	#define STR0008 "Exportando archivo texto."
	#define STR0009 "Fecha del movimiento"
	#define STR0010 "Tiempo remunerado"
	#define STR0011 "Tpo Disp.Srv Generales-Productivo"
	#define STR0012 "Tpo Disp.Srv Rapido-Productivo"
	#define STR0013 "Tpo Disp.Srv Carroc.Mec.-Chap."
	#define STR0014 "Tpo Disp.Srv Carroc.Mec.-Pint"
	#define STR0015 "Tasa de mano de obra publica"
	#define STR0016 "Servicios - Gerente"
	#define STR0017 "Jefe de taller"
	#define STR0018 "Servicios - Consultor tecnico"
	#define STR0019 "Servicios - Aprendiz"
	#define STR0020 "Servicios - Soporte"
	#define STR0021 "Servicios generales - Mecanicos"
	#define STR0022 "Servicios Rapido - Mecanicos"
	#define STR0023 "Srv.Carroc.Mecanicos-chapistas  "
	#define STR0024 "Srv.Carroc.Mecanicos-Pintores "
	#define STR0025 "Srv.Lavadores / Lubricadores"
	#define STR0026 "Servicios - terceros"
	#define STR0027 "Piezas - Gerente"
	#define STR0028 "Piezas - Soporte (Apoyo)"
	#define STR0029 "Piezas - Vendedor - Minorista"
	#define STR0030 "Piezas - Vendedor - Taller"
	#define STR0031 "Piezas - Vendedor Mayorista"
	#define STR0032 "Piezas - Vendedor accesorios"
	#define STR0033 "Lugares de trabajo-Srv Generales"
	#define STR0034 "Lugares de trabajo-Srv Rapido"
	#define STR0035 "Lugares de trabajo-Srv Chapisteria"
	#define STR0036 "Lugares de trabajo-Srv Pintura"
	#define STR0037 "Lugares de Trab.Lavado y Lubric"
	#define STR0038 "Lugares de Trab.Utiliz.p/Terc."
	#define STR0039 "Mes y Ano de Referencia"
	#define STR0040 "TOTVS S/A"
	#define STR0041 "El archivo existe en el directorio especificado. ¿Desea reprocesar el archivo y sobreescribir?"
	#define STR0042 "Atencion"
	#define STR0043 "Archivo generado con exito."
	#define STR0044 "Diccionario SX1 actualizado"
	#define STR0045 "Fecha inicial"
	#define STR0046 "Fecha final  "
	#define STR0047 "¿Envia datos complementarios?"
	#define STR0048 "No"
	#define STR0049 "Si"
	#define STR0050 "DN de la concesionaria"
	#define STR0051 "TT Cliente"
	#define STR0052 "TT Interno Ventas"
	#define STR0053 "TT Interno Utilizados"
	#define STR0054 "TT Interno Piezas"
	#define STR0055 "TT Interno Administracion"
	#define STR0056 "TT Taller"
	#define STR0057 "TT Garantia Taller"
	#define STR0058 "TT Garantia VW"
	#define STR0059 "TT DN Vendedor Vehiculos"
	#define STR0060 "TT Seguro"
	#define STR0061 "TT Promociones"
	#define STR0062 "TT Otros"
	#define STR0063 "TT Revision de entrega del Vehiculo"
	#define STR0064 "TT Revision Garantia"
	#define STR0065 "TT Revision Normal"
	#define STR0066 "TT Fletista"
	#define STR0067 "Seccion Mecanica"
	#define STR0068 "Seccion Chapist/Pin"
	#define STR0069 "Dir Ger del Archivo <ENTER>"
	#define STR0070 "Actualizando Preguntas (SX1)..."
	#define STR0071 "Marca"
#else
	#ifdef ENGLISH
		#define STR0001 "This routine aims at generating"
		#define STR0002 "a file with information called AUTOSERVICE. Information is"
		#define STR0003 "got from the system to be sent to Volkswagen assembly."
		#define STR0004 "This report displays information in the file that has been generated"
		#define STR0005 "to answer a request of AUTOSERVICE of Volkswagen."
		#define STR0006 "Autoservice VW Export"
		#define STR0007 "Wait..."
		#define STR0008 "Exporting text file."
		#define STR0009 "Transaction Date"
		#define STR0010 "Time Compensated"
		#define STR0011 "Tp Av. Serv Gener-Productive"
		#define STR0012 "Tp Av. Serv Fast-Productive"
		#define STR0013 "Tp Av.Serv TruckBody.Prod-Bodywork"
		#define STR0014 "Tp Av.Serv TruckBody Prod-Paint"
		#define STR0015 "Public labor force fee"
		#define STR0016 "Services - Management"
		#define STR0017 "Repair Shop Chief"
		#define STR0018 "Services Technical Consultant"
		#define STR0019 "Services - Management"
		#define STR0020 "Services - Support"
		#define STR0021 "General Services - Productive"
		#define STR0022 "Fast Services - Productive"
		#define STR0023 "Serv. Truck Body Productive-tinsmith"
		#define STR0024 "Serv. Truck Body Productive - Painters"
		#define STR0025 "Serv. Washer / Lubricators"
		#define STR0026 "Services - Third Party"
		#define STR0027 "Spare Parts - Management"
		#define STR0028 "Spare Parts - Support "
		#define STR0029 "Spare Parts - Clerk - Retail Sales"
		#define STR0030 "Spare Parts - Clerk - Repair Shop"
		#define STR0031 "Spare Parts - Sales Representative Wholesale"
		#define STR0032 "Spare Parts - Sales Representative Accessories"
		#define STR0033 "Work Places - General Services"
		#define STR0034 "Work Places - Fast Services"
		#define STR0035 "Work Places - Bodywork Services"
		#define STR0036 "Work Places - Painting Services"
		#define STR0037 "Work Places - Washing and Lubricant"
		#define STR0038 "Work Places used by Third Party"
		#define STR0039 "Reference Month and Year"
		#define STR0040 "TOTVS    S / A"
		#define STR0041 "File exists in the directory specified. Do you wish to reprocess the file and overwrite it?"
		#define STR0042 "Attention"
		#define STR0043 "File successfully generated."
		#define STR0044 "Dictionary SX1 Already updated"
		#define STR0045 "Start Date"
		#define STR0046 "End Date  "
		#define STR0047 "Send Additional Data?"
		#define STR0048 "No"
		#define STR0049 "Yes"
		#define STR0050 "DN of car dealer"
		#define STR0051 "Customer TT"
		#define STR0052 "Sales Internal TT"
		#define STR0053 "Sales Used TT"
		#define STR0054 "Spare Parts Internal TT"
		#define STR0055 "Administrative Internal TT"
		#define STR0056 "Repair shop TT"
		#define STR0057 "Repair shop Guarantee TT"
		#define STR0058 "VW Guarantee TT"
		#define STR0059 "Vehicle Sales Representative DN TT"
		#define STR0060 "Insurance TT"
		#define STR0061 "Promotions TT"
		#define STR0062 "Others TT"
		#define STR0063 "Vehicle Delivery Maintenance Inspection TT"
		#define STR0064 "Guarantee Maintenance Inspection TT"
		#define STR0065 "Regular Maintenance Inspection TT"
		#define STR0066 "Fleet Owner TT"
		#define STR0067 "Mechanical Section"
		#define STR0068 "Bodywork/Painting Section"
		#define STR0069 "File Gen Dir <ENTER>"
		#define STR0070 "Updating Questions (SX1)..."
		#define STR0071 "Brand"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Este procedimento tem como finalidade gerar", "Esta rotina tem como finalidade a geração" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "o ficheiro com informações denominadas como AUTOSERVICE. As informações serão", "do arquivo com informações denominadas como AUTOSERVICE. As informações serão" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "obtidas do sistema para envio à montadora Volkswagen.", "obtidas do sistema para envio a montadora Volkswagen." )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Este relatório exibirá informações contidas no ficheiro que foram geradas", "Este relatório exibirá informações contidas no arquivo que foram geradas" )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "para atender à solicitação de AUTOSERVICE da marca Volkswagen.", "para atender a solicitação de AUTOSERVICE da marca Volkswagen." )
		#define STR0006 "Exportação Autoservice VW"
		#define STR0007 "Aguarde..."
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "A exportar ficheiro texto.", "Exportando arquivo texto." )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Data do movimento", "Data do Movimento" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Tempo remunerado", "Tempo Remunerado" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Tp.Disp.Srv.Gerais-Produtivo", "Tpo Disp.Srv Gerais-Produtivo" )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Tp.Disp.Srv.Rápido-Produtivo", "Tpo Disp.Srv Rápido-Produtivo" )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Tp.Disp.Srv.Carroc.Prod-Funil", "Tpo Disp.Srv Carroc.Prod-Funil" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Tp.Disp.Srv.Carroc.Prod-Pint", "Tpo Disp.Srv Carroc.Prod-Pint" )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Taxa de mão de obra pública", "Taxa de mão de obra publico" )
		#define STR0016 "Serviços - Gerente"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Chefe de oficina", "Chefe de Oficina" )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Serviços - Consultor técnico", "Serviços - Consultor Técnico" )
		#define STR0019 "Serviços - Aprendiz"
		#define STR0020 "Serviços - Suporte"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Serviços gerais - Produtivos", "Serviços Gerais - Produtivos" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Serviços rápido - Produtivos", "Serviços Rápido - Produtivos" )
		#define STR0023 "Srv.Carroc.Produtivos-funileiros"
		#define STR0024 "Srv.Carroc.Produtivos-Pintores"
		#define STR0025 "Srv.Lavadores / Lubrificadores"
		#define STR0026 "Serviços - terceiros"
		#define STR0027 "Peças - Gerente"
		#define STR0028 "Peças - Suporte (Apoio)"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Peças - Balconista - Retalho", "Peças - Balconista - Varejo" )
		#define STR0030 "Peças - Balconista - Oficina"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Peças - Vendedor atacado", "Peças - Vendedor Atacado" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Peças - Vendedor acessórios", "Peças - Vendedor Acessórios" )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Locais de trabalho-Srv.Gerais", "Locais de Trabalho-Srv Gerais" )
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Locais de trabalho-Srv.Rápido", "Locais de Trabalho-Srv Rápido" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Locais de trabalho-Srv.Funilaria", "Locais de Trabalho-Srv Funilaria" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Locais de trabalho-Srv.Pintura", "Locais de Trabalho-Srv Pintura" )
		#define STR0037 "Locais de Trab.Lavagem e Lubrif"
		#define STR0038 "Locais de Trab.Utiliz.p/Terc."
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Mês e ano de referência", "Mês e Ano de Referência" )
		#define STR0040 "TOTVS S/A"
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "O ficheiro existe no directório especificado. Deseja reprocessar o ficheiro e sobreescrever?", "O arquivo existe no diretório especificado. Deseja reprocessar o arquivo e sobreescrever?" )
		#define STR0042 "Atenção"
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Ficheiro gerado com sucesso.", "Arquivo gerado com sucesso." )
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Dicionário SX1 já actualizado", "Dicionario SX1 Já atualizado" )
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Data inicial", "Data Inicial" )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Data final  ", "Data Final  " )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Envia dados complementares?", "Envia Dados Complementares?" )
		#define STR0048 "Não"
		#define STR0049 "Sim"
		#define STR0050 "DN da concessionária"
		#define STR0051 "TT Cliente"
		#define STR0052 "TT Interno Vendas"
		#define STR0053 "TT Interno Usados"
		#define STR0054 "TT Interno Peças"
		#define STR0055 "TT Interno Administração"
		#define STR0056 "TT Oficina"
		#define STR0057 "TT Garantia Oficina"
		#define STR0058 "TT Garantia VW"
		#define STR0059 "TT DN Vendedor Veículos"
		#define STR0060 "TT Seguro"
		#define STR0061 "TT Promoções"
		#define STR0062 "TT Outros"
		#define STR0063 "TT Revisão de Entrega do Veículo"
		#define STR0064 "TT Revisão Garantia"
		#define STR0065 "TT Revisão Normal"
		#define STR0066 "TT Frotista"
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Secção Mecânica", "Seção Mecanica" )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Secção Funil/Pin", "Seção Funil/Pin" )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Dir.Ger.do ficheiro <ENTER>", "Dir Ger do Arquivo <ENTER>" )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "A actualizar Perguntas (SX1)...", "Atualizando Perguntas (SX1)..." )
		#define STR0071 "Marca"
	#endif
#endif
