#ifdef SPANISH
	#define STR0001 "Entes"
	#define STR0002 "Propio"
	#define STR0003 "Cooperado"
	#define STR0004 "Tercero"
	#define STR0005 "Buscar"
	#define STR0006 "Visualizar"
	#define STR0007 "Incluir"
	#define STR0008 "Modificar"
	#define STR0009 "Borrar"
	#define STR0010 "Imprimir"
	#define STR0011 "Copiar"
	#define STR0012 "Ente"
	#define STR0013 "Datos del ente"
	#define STR0014 "Datos bancarios"
	#define STR0015 "¡No pueden haber dos entes representando la misma empresa, unidad de negocio y sucursal!"
	#define STR0016 "Ayuda"
	#define STR0017 "¡No pueden haber dos entes representando el mismo proveedor!"
	#define STR0018 "¡No pueden haber dos entes representando el mismo cliente!"
	#define STR0019 "Cliente vinculado al RCPJ/RCPF + Inscripcion estatal no ubicada en el archivo de Cliente (SA1): "
	#define STR0020 "Proveedor vinculado al RCPJ/RCPF + Inscripcion estatal no ubicado en el archivo de Proveedor (SA2): "
	#define STR0021 "El RCPJ/RCPF del Entidad difiere del RCPJ/RCPF del Proveedor vinculado: "
	#define STR0022 "La Ins.Estat. de la Entidad difiere de la Ins.Estat. del Proveedor vinculado: "
	#define STR0023 "Proveedor no ubicado en el archivo de Proveedor (SA2): "
	#define STR0024 "¡Ente ya utilizado en la tabla de -Lista de empaques-!"
	#define STR0025 "El RCPJ/RCPF de la Entidad difiere del RCPJ/RCPF del Cliente vinculado: "
	#define STR0026 "La Ins.Estat. de la Entidad difiere de la Ins.Estat. del Cliente vinculado: "
	#define STR0027 "Cliente no ubicado en el archivo de Cliente (SA1): "
	#define STR0028 "Archivo inactivo"
	#define STR0029 "¿Desea continuar?"
	#define STR0030 "Ente informado está registrado"
	#define STR0031 "El RUC de la Entidad difiere del RUC del Cliente vinculado: "
	#define STR0032 "El RUC de la Entidad difiere del RUC del Proveedor vinculado: "
	#define STR0033 "Cliente vinculado al RUC + Inscripción estatal no se encontró en el Archivo de cliente (SA1): "
	#define STR0034 "Proveedor vinculado al RUC + Inscripción estatal no se encontró en el archivo de Proveedor (SA2): "
	#define STR0035 "Importar productor"
	#define STR0036 "Creación del ente a partir del productor"
	#define STR0037 "Generando nuevo ente"
	#define STR0038 "Importando datos del productor"
	#define STR0039 "Entidad integrada con Archivo de Cliente y/o Proveedor"
	#define STR0040 "Carga Ente"
	#define STR0041 "Entidad vinculada al proveedor tiene contrato abierto o iniciado"
	#define STR0042 "Entidad vinculada al cliente tiene contrato abierto o iniciado"
	#define STR0043 "¿Desea realizar la carga automática de datos de Clientes/Proveedores?"
	#define STR0044 "Procesamiento"
	#define STR0045 "Sincronizando archivos"
	#define STR0046 "Proveedor "
	#define STR0047 "Cliente "
	#define STR0048 " con Error: "
	#define STR0049 "Id del formulario de origen: "
	#define STR0050 "Id del campo de origen.....: "
	#define STR0051 "Id del formulario de error..: "
	#define STR0052 "Id del campo de error.......: "
	#define STR0053 "Id del error................: "
	#define STR0054 "Mensaje del error..........: "
	#define STR0055 "Mensaje de la solución.......: "
	#define STR0056 "Reglas de calidad por clientes"
#else
	#ifdef ENGLISH
		#define STR0001 "Entities"
		#define STR0002 "Own"
		#define STR0003 "Cooperated"
		#define STR0004 "Third Party"
		#define STR0005 "Search"
		#define STR0006 "View"
		#define STR0007 "Add"
		#define STR0008 "Edit"
		#define STR0009 "Delete"
		#define STR0010 "Print"
		#define STR0011 "Copy"
		#define STR0012 "Entity"
		#define STR0013 "Entity Data"
		#define STR0014 "Bank Data"
		#define STR0015 "You cannot have two entities representing the same company, business unit and branch!"
		#define STR0016 "Help"
		#define STR0017 "You cannot have two entities representing the same supplier!"
		#define STR0018 "You cannot have two entities representing the same customer!"
		#define STR0019 "Customer related to CNPJ/CPF + State Registration not found in Customer Register (SA1): "
		#define STR0020 "Supplier related to CNPJ/CPF + State Registration not found in Supplier Register (SA2): "
		#define STR0021 "Entity CNPJ/CPF differs from CNPJ/CPF of related Supplier: "
		#define STR0022 "Entity State Registration differs from State Registration of related Supplier: "
		#define STR0023 "Supplier not found in Supplier register (SA2): "
		#define STR0024 "Entity used in Packing Slip table!"
		#define STR0025 "Entity CNPJ/CPF differs from CNPJ/CPF of related Customer: "
		#define STR0026 "Entity State Registration differs from State Registration of related Customer: "
		#define STR0027 "Customer not found in Customer Register (SA1): "
		#define STR0028 "Register not active"
		#define STR0029 "Continue?"
		#define STR0030 "Entity entered already registered"
		#define STR0031 "RUC of entity different from RUC of customer associated:"
		#define STR0032 "RUC of entity different from RUC of supplier associated:"
		#define STR0033 "Customer associated with RUC + State registration not found in customer registration (SA1):"
		#define STR0034 "Supplier associated with RUC + State registration not found in supplier registration (SA2):"
		#define STR0035 "Import producer"
		#define STR0036 "Creating entity from producer"
		#define STR0037 "Generating new entity"
		#define STR0038 "Importing producer data"
		#define STR0039 "Entity integrated to Customer Register and/or Supplier"
		#define STR0040 "Entity Load"
		#define STR0041 "Entity related to supplier has contract open or started"
		#define STR0042 "Entity related to customer has contract open or started"
		#define STR0043 "Automatically load customer/supplier data?"
		#define STR0044 "Processing"
		#define STR0045 "Synchronizing registers"
		#define STR0046 "Supplier "
		#define STR0047 "Customer "
		#define STR0048 " with Error: "
		#define STR0049 "Id of origin form: "
		#define STR0050 "Id of the source field: "
		#define STR0051 "Id of error form: "
		#define STR0052 "Id of error field: "
		#define STR0053 "Id of error: "
		#define STR0054 "Error message: "
		#define STR0055 "Solution message: "
		#define STR0056 "Quality Rules per Customers"
	#else
		#define STR0001 "Entidades"
		#define STR0002 "Próprio"
		#define STR0003 "Cooperado"
		#define STR0004 "Terceiro"
		#define STR0005 "Pesquisar"
		#define STR0006 "Visualizar"
		#define STR0007 "Incluir"
		#define STR0008 "Alterar"
		#define STR0009 "Excluir"
		#define STR0010 "Imprimir"
		#define STR0011 "Copiar"
		#define STR0012 "Entidade"
		#define STR0013 "Dados da Entidade"
		#define STR0014 "Dados Bancarios"
		#define STR0015 "Não pode haver duas entidades representando a mesma empresa, unidade de negocio e filial!"
		#define STR0016 "Ajuda"
		#define STR0017 "Não pode haver duas entidades representando o mesmo fornecedor!"
		#define STR0018 "Não pode haver duas entidades representando o mesmo cliente!"
		#define STR0019 "Cliente associado ao CNPJ/CPF + Inscrição Estadual não localizado no cadastro de Cliente (SA1): "
		#define STR0020 "Fornecedor associado ao CNPJ/CPF + Inscrição Estadual não localizado no cadastro de Fornecedor (SA2): "
		#define STR0021 "O CNPJ/CPF da Entidade difere do CNPJ/CPF do Fornecedor associado: "
		#define STR0022 "A Ins.Estad. da Entidade difere da Ins.Estad. do Fornecedor associado: "
		#define STR0023 "Fornecedor não localizado no cadastro de Fornecedor (SA2): "
		#define STR0024 "Entidade ja utilizada na tabela de -Romaneios-!"
		#define STR0025 "O CNPJ/CPF da Entidade difere do CNPJ/CPF do Cliente associado: "
		#define STR0026 "A Ins.Estad. da Entidade difere da Ins.Estad. do Cliente associado: "
		#define STR0027 "Cliente não localizado no cadastro de Cliente (SA1): "
		#define STR0028 "Cadastro inativo"
		#define STR0029 "Deseja continuar?"
		#define STR0030 "Entidade informada já está cadastrada"
		#define STR0031 "O RUC da Entidade difere do RUC do Cliente associado: "
		#define STR0032 "O RUC da Entidade difere do RUC do Fornecedor associado: "
		#define STR0033 "Cliente associado ao RUC + Inscrição Estadual não localizado no cadastro de Cliente (SA1): "
		#define STR0034 "Fornecedor associado ao RUC + Inscrição Estadual não localizado no cadastro de Fornecedor (SA2): "
		#define STR0035 "Importar Produtor"
		#define STR0036 "Criação Entidade a partir do Produtor"
		#define STR0037 "Gerando nova entidade"
		#define STR0038 "Importando dados produtor"
		#define STR0039 "Entidade integrada com Cadastro de Cliente e/ou Fornecedor"
		#define STR0040 "Carga Entidade"
		#define STR0041 "Entidade relacionada ao Fornecedor possui Contrato aberto ou iniciado"
		#define STR0042 "Entidade relacionada ao Cliente possui Contrato aberto ou iniciado"
		#define STR0043 "Deseja realizar a carga automática de dados de Clientes/Fornecedores?"
		#define STR0044 "Processamento"
		#define STR0045 "Sincronizando Cadastros"
		#define STR0046 "Fonecedor "
		#define STR0047 "Cliente "
		#define STR0048 " com Erro: "
		#define STR0049 "Id do formulário de origem: "
		#define STR0050 "Id do campo de origem.....: "
		#define STR0051 "Id do formulário de erro..: "
		#define STR0052 "Id do campo de erro.......: "
		#define STR0053 "Id do erro................: "
		#define STR0054 "Mensagem do erro..........: "
		#define STR0055 "Mensagem da solução.......: "
		#define STR0056 "Regras de Qualidade por Clientes"
	#endif
#endif
