#ifdef SPANISH
	#define STR0001 "Cierre de servicios de almacenamiento"
	#define STR0002 "Generado"
	#define STR0003 "Anulado"
	#define STR0004 "Vinculado"
	#define STR0005 "Visualizar"
	#define STR0006 "Movimientos"
	#define STR0007 "Revertir"
	#define STR0008 "Reversion de cierre de calculo de servicio"
	#define STR0009 "¿Esta seguro que desea revertir el cierre de calculo del servicio seleccionado?"
	#define STR0010 "Datos de cierre de servicio de almacenamiento"
	#define STR0011 "Cierre de servicios de almacenamiento"
	#define STR0012 "Ayuda"
	#define STR0013 "Cierre seleccionado ya se anulo."
	#define STR0014 "Lista de embarque confirmada con factura. Antes es necesario anular la factura."
	#define STR0015 "La factura generada debe anularse."
#else
	#ifdef ENGLISH
		#define STR0001 "Storage Services Closings"
		#define STR0002 "Generated"
		#define STR0003 "Canceled"
		#define STR0004 "Associated"
		#define STR0005 "View"
		#define STR0006 "Transactions"
		#define STR0007 "Reverse"
		#define STR0008 "Reverse of Service Calculation Closing"
		#define STR0009 "Are you sure that you want to reverse the service calculation closing selected?"
		#define STR0010 "Storage Services Closing Data"
		#define STR0011 "Storage Services Closing"
		#define STR0012 "Help"
		#define STR0013 "Closing selected already canceled."
		#define STR0014 "Manifest confirmed with invoice. You must cancel the invoice first."
		#define STR0015 "Invoice generated must be canceled."
	#else
		#define STR0001 "Fechamentos Serviços de Armazenagem"
		#define STR0002 "Gerado"
		#define STR0003 "Cancelado"
		#define STR0004 "Vinculado"
		#define STR0005 "Visualizar"
		#define STR0006 "Movimentos"
		#define STR0007 "Estornar"
		#define STR0008 "Estorno de Fechamento de Cálculo de Serviço"
		#define STR0009 "Tem certeza que deseja estornar o fechamento de cálculo de serviço selecionado?"
		#define STR0010 "Dados Fechamento Serviços de Armazenagem"
		#define STR0011 "Fechamento Serviços de Armazenagem"
		#define STR0012 "Ajuda"
		#define STR0013 "Fechamento selecionado já foi cancelado."
		#define STR0014 "Romaneio confirmado com nota fiscal. É necessário antes cancelar nota fiscal."
		#define STR0015 "Nota Fiscal gerada deve ser cancelada."
	#endif
#endif
