#ifdef SPANISH
	#define STR0001 "El modo de visualización no permite incluir fardos."
	#define STR0002 "Fardo"
	#define STR0003 "Etiqueta"
	#define STR0004 "Bloque"
	#define STR0005 "Instrucción de embarque"
	#define STR0006 "Vínculo de fardos en la lista de embarque"
	#define STR0007 "Fardos de la instrucción de embarque"
	#define STR0008 "Fardos seleccionados"
	#define STR0009 "Búsqueda"
	#define STR0010 "Sucursal"
	#define STR0011 "Cosecha"
	#define STR0012 "Espere"
	#define STR0013 "Peso bruto"
	#define STR0014 "Peso neto"
	#define STR0015 "Vincular marcados"
	#define STR0016 "Desvincular marcados"
	#define STR0017 "Cantidad"
	#define STR0018 "Peso total"
	#define STR0019 "¡Atención!"
	#define STR0020 "Por favor, seleccione fardos."
	#define STR0021 "Actualizando tabla de datos."
	#define STR0022 "Cantidad de fardos del bloque sobrepasó el límite disponible: "
	#define STR0023 "Espere"
	#define STR0024 "Ajustando stock..."
	#define STR0025 "El total del peso neto de los fardos vinculados es superior a lo permitido en la instrucción de embarque."
	#define STR0026 "Instrucción de embarque: "
	#define STR0027 "El total do peso vinculado está por encima del peso máximo del container informado en la instrucción de embarque."
	#define STR0028 "Estatus del contenedor no permite secado de granos"
	#define STR0029 "Para iniciar el secado de granos es necesario completar el campo contenedor"
	#define STR0030 "¿Le gustaría finalizar el secado de granos?"
	#define STR0031 "Cant. Máx. permitida en la Instrucción de embarque: "
	#define STR0032 "Cant. Vinculada: "
	#define STR0033 "Peso Máx. Contenedor: "
	#define STR0034 "Total de peso de los fardos: "
	#define STR0035 "Operación no permitida para Listas de embarque con estatus "
	#define STR0036 "Serie Fact."
	#define STR0037 "Nº Fact."
	#define STR0038 "IE: "
	#define STR0039 "Bloque: "
	#define STR0040 "Ctd Anterior "
	#define STR0041 "Para vincular fardos es necesario que la lista de embarque esté vinculada a una instrucción de embarque."
	#define STR0042 "Peso de llegada"
	#define STR0043 "Peso de salida"
	#define STR0044 "Peso certificado"
	#define STR0045 "No fue posible vincular este fardo. El container está reservado para secado de la sucursal "
	#define STR0046 "Vínculo de fardos en el container"
	#define STR0047 "Solamente containers con estatus '1-Disponible' y '2-En estufado' pueden estufarse."
	#define STR0048 "Campo container no se informó."
	#define STR0049 "Ajuste la cantidad de fardos en la instrucción de embarque o en el container."
	#define STR0050 "No se marcaron fardos en la pantalla."
	#define STR0051 "Es necesario marcar los fardos."
	#define STR0052 "Vincule solamente fardos de la sucursal"
	#define STR0053 "Cantidad superior:"
	#define STR0054 "Ajuste el peso vinculado en el container o ajuste el peso en la instrucción de embarque."
#else
	#ifdef ENGLISH
		#define STR0001 "The view mode does not allow addition of bales."
		#define STR0002 "Bale"
		#define STR0003 "Label"
		#define STR0004 "Block"
		#define STR0005 "Shipment Instruction"
		#define STR0006 "Bound of Bales to Packing List"
		#define STR0007 "Bales of Shipment Instruction"
		#define STR0008 "Selected Bales"
		#define STR0009 "Search"
		#define STR0010 "Branch"
		#define STR0011 "Crop"
		#define STR0012 "Wait"
		#define STR0013 "Gross Weight"
		#define STR0014 "Net Weight"
		#define STR0015 "Associate the Selected ones"
		#define STR0016 "Dissociate the Selected ones"
		#define STR0017 "Quantity"
		#define STR0018 "Total Weight"
		#define STR0019 "Attention!"
		#define STR0020 "Select bales."
		#define STR0021 "Updating data table"
		#define STR0022 "Number of bales of block exceeded the available limit: "
		#define STR0023 "Wait"
		#define STR0024 "Adjusting stock..."
		#define STR0025 "Total of Net Weight of bales bound below the amount allowed in the Shipping Instruction."
		#define STR0026 "Shipping Instruction: "
		#define STR0027 "Full linked weight is above maximum weight of container entered in shipping instruction."
		#define STR0028 "Container status does not allow stuffing"
		#define STR0029 "Fill the container field to start stuffing"
		#define STR0030 "Finish stuffing?"
		#define STR0031 "Max qty allowed in shipping instruction: "
		#define STR0032 "Qty. Associated: "
		#define STR0033 "Max weight Container: "
		#define STR0034 "Total bale weight: "
		#define STR0035 "Operation not allowed for packing lists with status "
		#define STR0036 "Invoice Series"
		#define STR0037 "Num. Inv."
		#define STR0038 "SI: "
		#define STR0039 "Block: "
		#define STR0040 "Qty Above: "
		#define STR0041 "To bind bales, packing list must be bound to a boarding instruction."
		#define STR0042 "Arrival Weight"
		#define STR0043 "Departure Weight"
		#define STR0044 "Certified Weight"
		#define STR0045 "Bind this bale is not possible. Container is reserved for branch stowing "
		#define STR0046 "Binding of bales in the container"
		#define STR0047 "Only containers with status '1-Available' and '2-In stuffing' can be stuffed."
		#define STR0048 "Field Container not filled out."
		#define STR0049 "Adjust the quantity of bales in shipping instruction or in container."
		#define STR0050 "No bales selected onscreen."
		#define STR0051 "Selection of bales is required."
		#define STR0052 "Link only branch bales"
		#define STR0053 "Above quantity:"
		#define STR0054 "Adjust weight linked in container or adjust weight in shipping instruction."
	#else
		#define STR0001 "O modo de visualização não permite a inclusão de fardos"
		#define STR0002 "Fardo"
		#define STR0003 "Etiqueta"
		#define STR0004 "Bloco"
		#define STR0005 "Instrução de Embarque"
		#define STR0006 "Vínculo de Fardos no Romaneio"
		#define STR0007 "Fardos da Instrução de Embarque"
		#define STR0008 "Fardos Selecionados"
		#define STR0009 "Pesquisa"
		#define STR0010 "Filial"
		#define STR0011 "Safra"
		#define STR0012 "Aguarde"
		#define STR0013 "Peso Bruto"
		#define STR0014 "Peso Líquido"
		#define STR0015 "Vincular Marcados"
		#define STR0016 "Desvincular Marcados"
		#define STR0017 "Quantidade"
		#define STR0018 "Peso Total"
		#define STR0019 "Atenção!"
		#define STR0020 "Favor selecionar fardos."
		#define STR0021 "Atualizando tabela de dados"
		#define STR0022 "Quantidade de fardos do bloco ultrapassou o limite disponivel: "
		#define STR0023 "Aguarde"
		#define STR0024 "Ajustando estoque..."
		#define STR0025 "Total do Peso Líquido dos fardos vinculados acima do permitido na Instrução de Embarque."
		#define STR0026 "Instrução de Embarque: "
		#define STR0027 "O total do peso vinculado está acima do peso máximo do container informado na instrução de embarque. "
		#define STR0028 "Status do container não permite Estufagem"
		#define STR0029 "Para iniciar a estufagem é necessário preencher o campo container"
		#define STR0030 "Gostaria de finalizar a estufagem?"
		#define STR0031 "Qtd. Máx. permitida na Instrução de Embarque: "
		#define STR0032 "Qtd. Vinculada: "
		#define STR0033 "Peso Máx. Container: "
		#define STR0034 "Total de Peso dos Fardos: "
		#define STR0035 "Operação não permitida para Romaneios com status "
		#define STR0036 "Serie NF"
		#define STR0037 "Num. NF"
		#define STR0038 "IE: "
		#define STR0039 "Bloco: "
		#define STR0040 "Qtd Acima: "
		#define STR0041 "Para vincular fardos é necessário que o romaneio esteja vinculado a uma instrução de embarque."
		#define STR0042 "Peso Chegada"
		#define STR0043 "Peso Saída"
		#define STR0044 "Peso Certificado"
		#define STR0045 "Não foi possivel vincular este fardo. O Container esta reservado para estufagem da filial "
		#define STR0046 "Vínculo de Fardos no Container"
		#define STR0047 "Somente containers com status '1-Disponível' e '2-Em estufagem' podem ser estufados."
		#define STR0048 "Campo Container não foi preeenchido."
		#define STR0049 "Ajuste a quantidade de fardos na instrução de embarque ou no container."
		#define STR0050 "Não foram marcados fardos na tela."
		#define STR0051 "Necessário marcar os fardos."
		#define STR0052 "Vincule somente fardos da filial "
		#define STR0053 "Quantidade acima: "
		#define STR0054 "Ajuste o peso vinculado no container ou ajuste o peso na instrução de embarque."
	#endif
#endif
