#ifdef SPANISH
	#define STR0001 "Orden de cobro"
	#define STR0002 "Programada"
	#define STR0003 "Parcialmente ejecutada"
	#define STR0004 "Totalmente Ejecutada"
	#define STR0005 "Buscar"
	#define STR0006 "Visualizar"
	#define STR0007 "Incluir"
	#define STR0008 "Borrar"
	#define STR0009 "Imprimir"
	#define STR0010 "Copiar"
	#define STR0011 "Datos de la orden de cobro"
	#define STR0012 "Datos de los favorecidos"
	#define STR0013 "AYUDA"
	#define STR0014 "¡Para OPs normales es obligatoria la seleccion de una fijacion!"
	#define STR0015 "¡Cantidad para cobro superior a cantidad de entrega en la Fijacion para este tipo!"
	#define STR0016 "¡Para OCs normales es obligatoria la seleccion de una fijacion!"
	#define STR0017 "¡Cantidad para cobro superior a cantidad de entrega en la Fijacion!"
	#define STR0018 "Valor de anticipo superior al credito del contrato!"
	#define STR0019 "¡Cantidad para anticipo superior a cantidad del contrato!"
	#define STR0020 "¡Cantidad para cobro superior a cantidad de la fijacion!"
	#define STR0021 "¡Orden de cobro ya -Ejecutada-! Entre en contacto con la tesoreria."
	#define STR0022 "Cobro contrato:"
	#define STR0023 ", Fijacion:"
	#define STR0024 ", al favorecido de la C.C.:"
	#define STR0025 "Ant. Contrato:"
#else
	#ifdef ENGLISH
		#define STR0001 "Receipt Order"
		#define STR0002 "Scheduled"
		#define STR0003 "Partially Performed"
		#define STR0004 "Totally Performed"
		#define STR0005 "Search"
		#define STR0006 "View"
		#define STR0007 "Add"
		#define STR0008 "Delete"
		#define STR0009 "Print"
		#define STR0010 "Copy"
		#define STR0011 "Receipt Order Data"
		#define STR0012 "Beneficiary data"
		#define STR0013 "HELP"
		#define STR0014 "For Regular OPs, select a setting!"
		#define STR0015 "Quantity for Receipt Higher than Quantity Delivered in This Type Setting!"
		#define STR0016 "For Regular ORs, select a setting!"
		#define STR0017 "Quantity for Receipt Higher than Quantity Delivered in Setting!"
		#define STR0018 "Prepayment Value Higher than Contract Credit!"
		#define STR0019 "Quantity for Payment Higher than Contract Quantity!"
		#define STR0020 "Quantity for Receipt Higher than Quantity in Setting!"
		#define STR0021 "Receipt Order already performed! Contact Treasury."
		#define STR0022 "Contract Rec:"
		#define STR0023 "Setting:"
		#define STR0024 ", to C.C. Benefit:"
		#define STR0025 "Contract Prepay:"
	#else
		#define STR0001 "Ordem de Recebimento"
		#define STR0002 "Programada"
		#define STR0003 "Parcialmente Executada"
		#define STR0004 "Totalmente Executada"
		#define STR0005 "Pesquisar"
		#define STR0006 "Visualizar"
		#define STR0007 "Incluir"
		#define STR0008 "Excluir"
		#define STR0009 "Imprimir"
		#define STR0010 "Copiar"
		#define STR0011 "Dados da Ordem de Recebimento"
		#define STR0012 "Dados dos Favorecidos"
		#define STR0013 "AJUDA"
		#define STR0014 "Para OPs Normais é obrigatório a seleção de uma fixação!"
		#define STR0015 "Quantidade para Recebimento Superior a Quantidade da Entregue na Fixação para Este Tipo!"
		#define STR0016 "Para ORs Normais é obrigatório a seleção de uma fixação!"
		#define STR0017 "Quantidade para Recebimento Superior a Quantidade da Entregue na Fixação!"
		#define STR0018 "Valor de Adiantamento Superior ao Credito do Contrato!"
		#define STR0019 "Quantidade para Adiantamento Superior a Quantidade do Contrato!"
		#define STR0020 "Quantidade para Recebimento Superior a Quantidade da Fixação!"
		#define STR0021 "Ordem de Recebimento ja -Executada-! Entre em contato com a Tesouraria."
		#define STR0022 "Recto Contrato:"
		#define STR0023 ", Fixação:"
		#define STR0024 ", ao Favorecido da C.C.:"
		#define STR0025 "Adto Contrato:"
	#endif
#endif
