#ifdef SPANISH
	#define STR0001 "Transferencia"
	#define STR0002 "Contratos"
	#define STR0003 "Confirme"
	#define STR0004 "Detalles"
	#define STR0005 "Filtro"
	#define STR0006 "Salir"
	#define STR0007 "Cant.Disp.Transf"
	#define STR0008 "Cant. Ent. Fij."
	#define STR0009 "Cant. por fijar"
	#define STR0010 "Dif. Fiscal"
	#define STR0011 "Ayuda"
	#define STR0012 "Contrato já tem Romaneio de devolução gerado, portanto, não pode ser desmarcado."
	#define STR0013 "Contrato no tiene saldo."
	#define STR0014 "Cálculo de Serviços Origem"
	#define STR0015 "Calculando tarifa..."
	#define STR0016 "Cálculo de Serviços Destino"
	#define STR0017 "Contrato"
	#define STR0018 "Procesando"
	#define STR0019 "Lista de embarque"
	#define STR0020 "Simulando calculo de servicios..."
	#define STR0021 "Transferencia ya efectuada."
	#define STR0022 "No puede efectuarse la transferencia de servicio. Es necesario transferir propiedades."
	#define STR0023 "Atención"
#else
	#ifdef ENGLISH
		#define STR0001 "Transfer"
		#define STR0002 "Contracts"
		#define STR0003 "Confirm"
		#define STR0004 "Details"
		#define STR0005 "Filter"
		#define STR0006 "Exit"
		#define STR0007 "Transf.Avail.Qty"
		#define STR0008 "Qty.Ent.Fix."
		#define STR0009 "Qty. to Set"
		#define STR0010 "Dif. Fiscal"
		#define STR0011 "Help"
		#define STR0012 "Contract already has Packing list of return generated, therefore, it cannot be unselected."
		#define STR0013 "Contract does not have balance."
		#define STR0014 "Origin Service Calculation"
		#define STR0015 "Calculating Fee..."
		#define STR0016 "Destination Service Calculation"
		#define STR0017 "Contract"
		#define STR0018 "Processing"
		#define STR0019 "Packing List"
		#define STR0020 "Simulating Service Calculation..."
		#define STR0021 "Transfer already made."
		#define STR0022 "Unable to Transfer Service. Transfer of properties needed."
		#define STR0023 "Attention"
	#else
		#define STR0001 "Transferência"
		#define STR0002 "Contratos"
		#define STR0003 "Confirmar"
		#define STR0004 "Detalhes"
		#define STR0005 "Filtro"
		#define STR0006 "Sair"
		#define STR0007 "Qtd.Disp.Transf"
		#define STR0008 "Qtd. Ent. Fix."
		#define STR0009 "Qtd. a Fixar"
		#define STR0010 "Dif. Fiscal"
		#define STR0011 "Ajuda"
		#define STR0012 "Contrato já tem Romaneio de devolução gerado, portanto, não pode ser desmarcado."
		#define STR0013 "Contrato não possui saldo."
		#define STR0014 "Cálculo de Serviços Origem"
		#define STR0015 "Calculando Tarifa..."
		#define STR0016 "Cálculo de Serviços Destino"
		#define STR0017 "Contrato"
		#define STR0018 "Processando"
		#define STR0019 "Romaneio"
		#define STR0020 "Simulando Cálculo de Serviços..."
		#define STR0021 "Transferência já efetuada."
		#define STR0022 "Transferência de Serviço não pode ser efetuada. Necessário transferir propriedades."
		#define STR0023 "Atenção"
	#endif
#endif
