#ifdef SPANISH
	#define STR0001 "Sel"
	#define STR0002 "Asunto pendiente"
	#define STR0003 "Sucursal"
	#define STR0004 "Cód de Lista de embarque"
	#define STR0005 "Ítem de Lista de embarque"
	#define STR0006 "Creando tablas"
	#define STR0007 "Obteniendo datos"
	#define STR0008 "Asuntos pendientes del contrato"
	#define STR0009 "Listas de embarque con asunto pendiente"
	#define STR0010 "Solucionar asuntos pendientes"
	#define STR0011 "Salir"
	#define STR0012 "Fijación"
	#define STR0013 "Cotización"
	#define STR0014 "Cotización y fijación"
	#define STR0015 "Asuntos pendientes resueltos"
	#define STR0016 "Atención"
	#define STR0017 "Este contrato tiene asunto pendiente de fijación por el valor de R$:"
	#define STR0018 "Generando Fact de Complemento."
	#define STR0019 "Calculando los valores de los asuntos pendientes seleccionadas"
	#define STR0020 "No existe cotización disponible para la moneda '"
	#define STR0021 "' en la fecha:"
	#define STR0022 "Debe registrarse cotización para la moneda en la fecha."
	#define STR0023 "Cantidad fijada insuficiente, operación de solución no puede finalizarse."
	#define STR0024 "Contrato sin fijación, operación de solución no puede finalizarse."
	#define STR0025 "Procesando Agio y Desagio"
	#define STR0026 "Sit."
	#define STR0027 "Asunto pendiente fue resuelto y está esperando aprobación."
	#define STR0028 "Seleccione una de las siguientes opciones:"
	#define STR0029 "Finalizar"
	#define STR0030 "Generar NDC"
	#define STR0031 "Generar complemento"
	#define STR0032 "Solución de asunto pendiente"
	#define STR0033 "¿Desea generar un Nota de crédito (NCC)?"
#else
	#ifdef ENGLISH
		#define STR0001 "Sel"
		#define STR0002 "Pending"
		#define STR0003 "Branch"
		#define STR0004 "Pack List Code"
		#define STR0005 "Pack List Item"
		#define STR0006 "Creating Tables"
		#define STR0007 "Fetching Data"
		#define STR0008 "Contract Pending Items"
		#define STR0009 "Packing Lists with Pending Item"
		#define STR0010 "Solve Pending Items"
		#define STR0011 "Exit"
		#define STR0012 "Fixing"
		#define STR0013 "Quotation"
		#define STR0014 "Quotation and Fixing"
		#define STR0015 "Pending Items Solved"
		#define STR0016 "Attention"
		#define STR0017 "This Contract has pending item in Fixing in the amount of R$:"
		#define STR0018 "Generating Complement Invoice"
		#define STR0019 "Calculating values of selected pendencies"
		#define STR0020 "No quotation available for the currency"
		#define STR0021 "on the date: "
		#define STR0022 "Register quotation for the currency on the date."
		#define STR0023 "Quantity fixed insufficient, operation of solution cannot be concluded."
		#define STR0024 "Contract without fixing, operation of solution cannot be concluded."
		#define STR0025 "Processing Premium and Discount"
		#define STR0026 "Stat."
		#define STR0027 "Pending item already solved and waiting for approval."
		#define STR0028 "Select one of the following options: "
		#define STR0029 "Close"
		#define STR0030 "Generate NDC"
		#define STR0031 "Generate Complement"
		#define STR0032 "Solution of Pending Item"
		#define STR0033 "Generate Credit Note (NDC)?"
	#else
		#define STR0001 "Sel"
		#define STR0002 "Pendência"
		#define STR0003 "Filial"
		#define STR0004 "Cod Rom"
		#define STR0005 "Item Rom"
		#define STR0006 "Criando Tabelas"
		#define STR0007 "Obtendo Dados"
		#define STR0008 "Pendências do Contrato"
		#define STR0009 "Romaneios com Pendência"
		#define STR0010 "Solucionar Pendências"
		#define STR0011 "Sair"
		#define STR0012 "Fixação"
		#define STR0013 "Cotação"
		#define STR0014 "Cotação e Fixação"
		#define STR0015 "Pendências Resolvidas"
		#define STR0016 "Atenção"
		#define STR0017 "Este Contrato possui pendência de Fixação no valor de R$:"
		#define STR0018 "Gerando NF de Complemento."
		#define STR0019 "Calculando os valores das pendências selecionadas"
		#define STR0020 "Não há cotação disponível para a moeda '"
		#define STR0021 "' na data: "
		#define STR0022 "Deverá ser cadastrada cotação para a moeda na data."
		#define STR0023 "Quantidade Fixada insuficiente, operação de solução não pode ser concluída."
		#define STR0024 "Contrato sem fixação, operação de solução não pode ser concluída."
		#define STR0025 "Processando Ágio e Deságio"
		#define STR0026 "Sit."
		#define STR0027 "Pendência já foi resolvida e está aguardando aprovação."
		#define STR0028 "Escolha uma das opções abaixo:"
		#define STR0029 "Fechar"
		#define STR0030 "Gerar NDC"
		#define STR0031 "Gerar Complemento"
		#define STR0032 "Solução de Pendência"
		#define STR0033 "Deseja gerar um Nota de Crédito (NCC)?"
	#endif
#endif
