#ifdef SPANISH
	#define STR0001 "Plan de ventas"
	#define STR0002 "Datos del plan de ventas"
	#define STR0003 "Buscar"
	#define STR0004 "Visualizar"
	#define STR0005 "Incluir"
	#define STR0006 "Modificar"
	#define STR0007 "Borrar"
	#define STR0008 "Imprimir"
	#define STR0009 "Copiar"
	#define STR0010 "Ítems del plan de ventas"
	#define STR0011 "Importar"
	#define STR0012 "Importación"
	#define STR0013 "Iniciando proceso"
	#define STR0014 "Archivos separados por punto y coma"
	#define STR0015 "Seleccione Archivo"
	#define STR0016 "Archivo informado no existe."
	#define STR0017 "El archivo debe tener la extensión .CSV"
	#define STR0018 "Realizando la lectura del archivo..."
	#define STR0019 "Archivo aparenta estar vacío o no tiene información para importación. Certifíquese que las columnas y los datos necesarios están en el archivo para importación."
	#define STR0020 "Columnas obligatorias no encontradas en el archivo"
	#define STR0021 "Validando las líneas del archivo"
	#define STR0022 "Tiene una cantidad de columnas diferente del encabezado.Verifique."
	#define STR0023 "archivo aparenta estar vacío o no tiene carácter separador de columnas"
	#define STR0024 "es obligatorio (a)"
	#define STR0025 "El componente"
	#define STR0026 "no se encontró."
	#define STR0027 "Error(es) en la línea"
	#define STR0028 "¡El archivo se importó con éxito!"
	#define STR0029 "Errores"
	#define STR0030 "Una o más líneas del archivo no se importaron con éxito."
	#define STR0031 "Haga clic en 'Errores' para más detalles."
	#define STR0032 "Suma del % Venta totalizó más que el 100% para Fecha, Sucursal, Grupo de producto y Producto. El registro se importó, sin embargo el porcentaje se puso en cero."
	#define STR0033 "Procesando líneas del archivo."
	#define STR0034 "Confirmar plan de ventas"
	#define STR0035 "Observación:"
	#define STR0036 "Confirmar"
	#define STR0037 "Historial"
	#define STR0038 "Condiciones de cobranza"
	#define STR0039 "Actualizar"
	#define STR0040 "AYUDA"
	#define STR0041 "Producto no es compatible con el Grupo de producto informado. Producto debe pertenecer al Grupo de producto."
	#define STR0042 "Suma del % de cobranza diferente del 100% para el"
	#define STR0043 "Vol Disp Plan de ventas"
	#define STR0044 "Estatus del plan de ventas no permite modificación."
	#define STR0045 "Suma del % de venta diferente del 100% para la Sucursal:"
	#define STR0046 "Grupo de producto:"
	#define STR0047 ", Producto:"
	#define STR0048 ", Suma del % de venta de los ítems:"
	#define STR0049 "Ajuste los porcentajes de los ítems del plan de vendas antes de confirmar."
	#define STR0050 "Finalizar plan de ventas"
	#define STR0051 "Reabrir plan de ventas"
	#define STR0052 "Finalizar"
	#define STR0053 "Reabrir"
	#define STR0054 "Actualizar plan"
	#define STR0055 "Pendiente"
	#define STR0056 "Confirmado"
	#define STR0057 "Finalizado"
	#define STR0058 ", Mercado:"
	#define STR0059 ", Moneda:"
	#define STR0060 ", Suma del %:"
	#define STR0061 "Ajuste los porcentajes de cobranza antes de proseguir."
	#define STR0062 "Fecha no válida"
	#define STR0063 "Informe una fecha que esté entre la fecha inicial y final del Plan de ventas."
	#define STR0064 "Comp. Precio plan"
	#define STR0065 "Panel de seguimiento"
	#define STR0066 "Actualizando plan de ventas..."
	#define STR0067 "Debe informarse componente de precio de tipo(s):"
	#define STR0068 "Informe"
	#define STR0069 "Negociado"
	#define STR0070 "para el Grupo de producto:"
	#define STR0071 "Efectúe el registro antes de Confirmar."
	#define STR0072 "No se informó la condición de pago"
	#define STR0073 "No se encontraron Ítems del plan de ventas. Informe los Ítems del plan para continuar."
	#define STR0074 "Realizar programación"
	#define STR0075 "Aviso. Esta rutina está descontinuada."
#else
	#ifdef ENGLISH
		#define STR0001 "Sales Plan"
		#define STR0002 "Sales Plan Data"
		#define STR0003 "Search"
		#define STR0004 "View"
		#define STR0005 "Add"
		#define STR0006 "Edit"
		#define STR0007 "Delete"
		#define STR0008 "Print"
		#define STR0009 "Copy"
		#define STR0010 "Sales Plan Items"
		#define STR0011 "Import"
		#define STR0012 "Import"
		#define STR0013 "Starting Process"
		#define STR0014 "Files separated by semicolon"
		#define STR0015 "Select file"
		#define STR0016 "File does not exist"
		#define STR0017 "Extension of file must be .CSV"
		#define STR0018 "Reading file"
		#define STR0019 "File seems to be blank or does not have information to import. Check whether columns and necessary data are in the file to import."
		#define STR0020 "Required columns not found in the file"
		#define STR0021 "Validating file rows"
		#define STR0022 "has a number of columns different from the header. Check."
		#define STR0023 "file seems to be empty or does not have a character separating the columns"
		#define STR0024 "is mandatory"
		#define STR0025 "Component"
		#define STR0026 "was not found."
		#define STR0027 "Error(s) in row"
		#define STR0028 "File successfully imported"
		#define STR0029 "Errors"
		#define STR0030 "One or more rows of the file were not imported properly."
		#define STR0031 "Click 'Errors' for further details."
		#define STR0032 "Total of sales % exceeded 100% for Date, Branch, Product Group and Group. Record was imported but the percentage was cleared."
		#define STR0033 "Processing file rows."
		#define STR0034 "Confirm Sales Plan"
		#define STR0035 "Note:"
		#define STR0036 "Confirm"
		#define STR0037 "History"
		#define STR0038 "Receipt term"
		#define STR0039 "Update"
		#define STR0040 "HELP"
		#define STR0041 "Product not compatible with Product Group entered. Product must belong to the Product Group."
		#define STR0042 "Total of sales % not 100% for"
		#define STR0043 "Sales Plan Avail Vol"
		#define STR0044 "Unable to edit Sales Plan Status"
		#define STR0045 "Total of sales % not 100% for Branch:"
		#define STR0046 "Product Group:"
		#define STR0047 ", Product:"
		#define STR0048 ", Total sales % of items:"
		#define STR0049 "Adjust the percentages of the sales plan items before confirming."
		#define STR0050 "Close Sales Plan"
		#define STR0051 "Reopen Sales Plan"
		#define STR0052 "Close"
		#define STR0053 "Reopen"
		#define STR0054 "Update Plan"
		#define STR0055 "Pending"
		#define STR0056 "Confirmed"
		#define STR0057 "Closed"
		#define STR0058 ", Market:"
		#define STR0059 ", Currency:"
		#define STR0060 ", Total %:"
		#define STR0061 "Adjust percentages before continuing."
		#define STR0062 "Invalid Date"
		#define STR0063 "Enter a date between the start and end dates of the Sales Plan."
		#define STR0064 "Comp. Plan Price"
		#define STR0065 "Monitoring Panel"
		#define STR0066 "Updating Sales Plan..."
		#define STR0067 "Enter Component of Price of Type(s): "
		#define STR0068 "Statement"
		#define STR0069 "Negotiated"
		#define STR0070 "for Product Group: "
		#define STR0071 "Register before Confirming."
		#define STR0072 "No Receipt Term "
		#define STR0073 "No Items of Sales Plan. Enter Items of Plan to continue."
		#define STR0074 "To Schedule"
		#define STR0075 "Warning. This routine is discontinued."
	#else
		#define STR0001 "Plano de Vendas"
		#define STR0002 "Dados do Plano de Vendas"
		#define STR0003 "Pesquisar"
		#define STR0004 "Visualizar"
		#define STR0005 "Incluir"
		#define STR0006 "Alterar"
		#define STR0007 "Excluir"
		#define STR0008 "Imprimir"
		#define STR0009 "Copiar"
		#define STR0010 "Itens do Plano de Vendas"
		#define STR0011 "Importar"
		#define STR0012 "Importação"
		#define STR0013 "Iniciando Processo"
		#define STR0014 "Arquivos separados por Ponto-e-Vírgula"
		#define STR0015 "Escolher arquivo"
		#define STR0016 "Arquivo informado não existe."
		#define STR0017 "Arquivo deve possuir a extensão .CSV"
		#define STR0018 "Realizando leitura do arquivo..."
		#define STR0019 "Arquivo aparenta estar vazio ou não possui as informações para importação. Certifique-se que as colunas e os dados necessários estão no arquivo para importação."
		#define STR0020 "Colunas obrigatórias não localizadas no arquivo"
		#define STR0021 "Validando as linhas do arquivo"
		#define STR0022 "possui uma quantidade de colunas diferente do cabeçalho.Verifique."
		#define STR0023 "arquivo aparenta estar vazio ou não possui caracter separador de colunas"
		#define STR0024 "é obrigatório (a)"
		#define STR0025 "O componente "
		#define STR0026 " não foi localizado."
		#define STR0027 "Erro(s) na linha "
		#define STR0028 "O arquivo foi importado com sucesso!"
		#define STR0029 "Erros"
		#define STR0030 "Um ou mais linhas do arquivo não foram importadas com sucesso."
		#define STR0031 " Clique em 'Erros' para mais detalhes."
		#define STR0032 "Soma do % Venda totalizou mais que 100% para Data, Filial, Grupo de Produto e Produto. O registro foi importado, porém o percentual foi zerado."
		#define STR0033 "Processando linhas do arquivo."
		#define STR0034 "Confirmar Plano de Vendas"
		#define STR0035 "Observação:"
		#define STR0036 "Confirmar"
		#define STR0037 "Histórico"
		#define STR0038 "Condições de Recebimento"
		#define STR0039 "Atualizar"
		#define STR0040 "AJUDA"
		#define STR0041 "Produto não é compatível com o Grupo de Produto informado. Produto deve pertencer ao Grupo de Produto."
		#define STR0042 "Soma do % de recebimento diferente de 100% para o"
		#define STR0043 "Vol Disp Plano de Vendas"
		#define STR0044 "Status do Plano de Vendas não permite alteração."
		#define STR0045 "Soma do % de venda diferente de 100% para a Filial: "
		#define STR0046 "Grupo de Produto: "
		#define STR0047 ", Produto: "
		#define STR0048 ", Soma do % venda dos Itens: "
		#define STR0049 "Ajuste os percentuais dos itens do plano vendas antes de confirmar."
		#define STR0050 "Encerrar Plano de Vendas"
		#define STR0051 "Reabrir Plano de Vendas"
		#define STR0052 "Encerrar"
		#define STR0053 "Reabrir"
		#define STR0054 "Atualizar Plano"
		#define STR0055 "Pendente"
		#define STR0056 "Confirmado"
		#define STR0057 "Encerrado"
		#define STR0058 ", Mercado: "
		#define STR0059 ", Moeda: "
		#define STR0060 ", Soma do %: "
		#define STR0061 "Ajuste os percentuais de recebimento antes de prosseguir."
		#define STR0062 "Data Inválida"
		#define STR0063 "Informe uma data que esteja entre a data inicial e final do Plano de Vendas."
		#define STR0064 "Comp. Preço Plano"
		#define STR0065 "Painel de Acompanhamento"
		#define STR0066 "Atualizando Plano de Vendas..."
		#define STR0067 "Deve ser informado Componente de Preço do(s) Tipo(s): "
		#define STR0068 "Demonstrativo"
		#define STR0069 "Negociado"
		#define STR0070 "para o Grupo de Produto : "
		#define STR0071 "Efetue o cadastro antes de Confirmar."
		#define STR0072 "Não foi informada Condição de Recebimento "
		#define STR0073 "Não foram encontrados Itens do Plano de Vendas. Informe os Itens do Plano para continuar."
		#define STR0074 "Realizar Programação"
		#define STR0075 "Aviso. Essa rotina está descontinuada."
	#endif
#endif
