#ifdef SPANISH
	#define STR0001 "Registro de peso y calidad en el destino"
	#define STR0002 "Peso y calidad en el destino"
	#define STR0003 "Buscar"
	#define STR0004 "Visualizar"
	#define STR0005 "Incluir"
	#define STR0006 "Registrar Peso / Calidad destino"
	#define STR0007 "Borrar"
	#define STR0008 "Imprimir"
	#define STR0009 "Principal"
	#define STR0010 "Peso en el destino"
	#define STR0011 "Conocimiento"
	#define STR0012 "Peso neto en el destino"
	#define STR0013 "Informe de desembarque (Proveedor)"
	#define STR0014 "Informe de desembarque (Cliente)"
	#define STR0015 "Pes Net Dest"
	#define STR0016 "Un Méd Prc"
	#define STR0017 "Aprobar peso"
	#define STR0018 "Pendiente"
	#define STR0019 "Esperando aprobación"
	#define STR0020 "Aprobado"
	#define STR0021 "AYUDA"
	#define STR0022 "Peso en el destino no se informó"
	#define STR0023 "Estatus debe ser igual a 'Esperando aprobación"
	#define STR0024 "¡Acción no permitida!"
	#define STR0025 "Usuario no tiene permiso para realizar esta acción de acuerdo con el rango de tolerancia mínima:"
	#define STR0026 "máxima:"
	#define STR0027 "La variación entre el peso informado y peso de la invoice fue de:"
	#define STR0028 "Ajuste el peso informado o aumente el rango de aprobación del usuario en el archivo de Aprobadores del proceso."
	#define STR0029 "Historial"
	#define STR0030 "Peso Invoice:"
	#define STR0031 "Peso en el destino:"
	#define STR0032 "Calidad en el destino"
	#define STR0033 "Tasas de servicio"
	#define STR0034 "Resultado calidad en el destino"
	#define STR0035 "Acción:"
	#define STR0036 "Aprobar"
	#define STR0037 "Rechazar"
	#define STR0038 "Rechazar peso"
	#define STR0039 "La variación entre el valor calculado en las divergencias de calidad y el valor de la invoice fue de:"
	#define STR0040 "Ajuste los resultados de calidad o aumente el rango de aprobación del usuario en el archivo de Aprobadores del proceso."
	#define STR0041 "Valor Invoice"
	#define STR0042 "Total descuentos calidad"
	#define STR0043 "Modificación no permitida"
	#define STR0044 "Existen resultados informados para este tipo de calidad"
	#define STR0045 "Aprobar calidad"
	#define STR0046 "Rechazar calidad"
	#define STR0047 "No se identificaron descuentos referentes a la calidad."
	#define STR0048 "La variación entre la consolidación peso y calidad en el destino y el valor de la invoice fue de:"
	#define STR0049 "Ajuste los resultados de peso, calidad o servicios o aumente el rango de aprobación del usuario en el archivo de Aprobadores del proceso."
	#define STR0050 "Aprobar Consolidación Peso y Cal. en el Dest."
	#define STR0051 "Rechazar Consolidación Peso y Cal. En el Dest."
	#define STR0052 "No se identificaron descuentos referentes a Peso, Calidad o servicios."
	#define STR0053 "Total descuentos consolidado"
	#define STR0054 "General"
	#define STR0055 "Pérdida o Ganancia de Peso y Calidad - Consolidado"
	#define STR0056 "Cálculo del resultado"
	#define STR0057 "Cierre de Cuentas Invoice"
	#define STR0058 "Para acceder a esta funcionalidad es necesario actualizar el diccionario de datos."
#else
	#ifdef ENGLISH
		#define STR0001 "Record of Weight and Quality at the Destination"
		#define STR0002 "Weight and Quality at the Destination"
		#define STR0003 "Search"
		#define STR0004 "View"
		#define STR0005 "Add"
		#define STR0006 "Register Weight/Quality at the Destination"
		#define STR0007 "Delete"
		#define STR0008 "Print"
		#define STR0009 "Main"
		#define STR0010 "Weight at the Destination"
		#define STR0011 "Waybill"
		#define STR0012 "Net Weight at the Destination"
		#define STR0013 "Landing Report (Supplier)"
		#define STR0014 "Landing Report (Customer)"
		#define STR0015 "Net Wght Dest"
		#define STR0016 "Meas Unit Perc"
		#define STR0017 "Approve Weight"
		#define STR0018 "Pending"
		#define STR0019 "Waiting for Approval"
		#define STR0020 "Approved"
		#define STR0021 "HELP"
		#define STR0022 "Weight at the Destination not entered."
		#define STR0023 "Status must be ‘Waiting for Approval"
		#define STR0024 "Action not allowed!"
		#define STR0025 "User is not allowed to perform this action according to the minimum tolerance range:"
		#define STR0026 "maximum:"
		#define STR0027 "Variation between the weight entered and the weight in the invoice is:"
		#define STR0028 "Adjust the weight or increase the user approval range in the Process Approver register."
		#define STR0029 "History"
		#define STR0030 "Invoice Weight:"
		#define STR0031 "Weight at the Destination:"
		#define STR0032 "Quality at the Destination"
		#define STR0033 "Service Rates"
		#define STR0034 "Result of quality at destination"
		#define STR0035 "Action: "
		#define STR0036 "Approve"
		#define STR0037 "Reject"
		#define STR0038 "Reject Weight"
		#define STR0039 "Variation between calculated value in the divergences of quality and invoice value was: "
		#define STR0040 "Adjust results of quality or increase the user approval range in the Process Approver register."
		#define STR0041 "Invoice Amount"
		#define STR0042 "Quality Discounts Total"
		#define STR0043 "Editing not allowed"
		#define STR0044 "There already are results informed for this type of quality"
		#define STR0045 "Approve Quality"
		#define STR0046 "Reject Quality"
		#define STR0047 "No discounts related to quality were identified."
		#define STR0048 "Variation between weight consolidation and the quality in the destination and invoice value was: "
		#define STR0049 "Adjust the results of the weight, quality or services or increase the user approval range in the Process Approver register."
		#define STR0050 "Approve Consolidation Weight and Qual. in the Dest."
		#define STR0051 "Reject Consolidation Weight and Qual. in the Dest."
		#define STR0052 "No discounts related to Weight, Quality or Services were identified."
		#define STR0053 "Consolidated Discounts Total"
		#define STR0054 "General"
		#define STR0055 "Loss or Gain of Weight and Quality - Consolidated"
		#define STR0056 "Result Calculation"
		#define STR0057 "Invoice Offsetting of Accounts"
		#define STR0058 "Update the data dictionary to access this functionality."
	#else
		#define STR0001 "Registro de Peso e Qualidade no Destino"
		#define STR0002 "Peso e Qualidade no Destino"
		#define STR0003 "Pesquisar"
		#define STR0004 "Visualizar"
		#define STR0005 "Incluir"
		#define STR0006 "Registrar Peso / Qualidade Destino"
		#define STR0007 "Excluir"
		#define STR0008 "Imprimir"
		#define STR0009 "Principal"
		#define STR0010 "Peso no Destino"
		#define STR0011 "Conhecimento"
		#define STR0012 "Peso Líquido no Destino"
		#define STR0013 "Relatório de Desembarque (Fornecedor)"
		#define STR0014 "Relatório de Desembarque (Cliente)"
		#define STR0015 "Pes Liq Dest"
		#define STR0016 "Un Med Prc"
		#define STR0017 "Aprovar Peso"
		#define STR0018 "Pendente"
		#define STR0019 "Aguardando Aprovação"
		#define STR0020 "Aprovado"
		#define STR0021 "AJUDA"
		#define STR0022 "Peso no Destino não foi informado"
		#define STR0023 "Status deve ser igual a 'Aguardando Aprovação"
		#define STR0024 "Ação não permitida!"
		#define STR0025 "Usuário não tem permissão para realizar esta ação conforme faixa de tolerância miníma: "
		#define STR0026 "máxima: "
		#define STR0027 "A variação entre o peso informado e peso da invoice foi de: "
		#define STR0028 "Ajuste o peso informado ou aumente a faixa de aprovação do usuário no cadastro de Aprovadores do Processo."
		#define STR0029 "Histórico"
		#define STR0030 "Peso Invoice: "
		#define STR0031 "Peso no Destino: "
		#define STR0032 "Qualidade no Destino"
		#define STR0033 "Taxas de Serviço"
		#define STR0034 "Resultado Qualidade no Destino"
		#define STR0035 "Ação: "
		#define STR0036 "Aprovar"
		#define STR0037 "Rejeitar"
		#define STR0038 "Rejeitar Peso"
		#define STR0039 "A variação entre o valor calculado nas divergencias de qualidade e o valor da invoice foi de: "
		#define STR0040 "Ajuste os resultados de qualidade ou aumente a faixa de aprovação do usuário no cadastro de Aprovadores do Processo."
		#define STR0041 "Valor Invoice"
		#define STR0042 "Total Descontos Qualidade"
		#define STR0043 "Alteração não permitida"
		#define STR0044 "Já existem resultados informados para este tipo de qualidade"
		#define STR0045 "Aprovar Qualidade"
		#define STR0046 "Rejeitar Qualidade"
		#define STR0047 "Não foram identificados descontos referentes a qualidade."
		#define STR0048 "A variação entre a consolidação peso e qualidade no destino e o valor da invoice foi de: "
		#define STR0049 "Ajuste os resultados de peso, qualidade ou serviços ou aumente a faixa de aprovação do usuário no cadastro de Aprovadores do Processo."
		#define STR0050 "Aprovar Consolidação Peso e Qual. no Dest."
		#define STR0051 "Rejeitar Consolidação Peso e Qual. no Dest."
		#define STR0052 "Não foram identificados descontos referente a Peso, Qualidade ou serviços."
		#define STR0053 "Total Descontos Consolidado"
		#define STR0054 "Geral"
		#define STR0055 "Perda ou Ganho de Peso e Qualidade - Consolidado"
		#define STR0056 "Apuração do Resultado"
		#define STR0057 "Enc. de Contas Invoice"
		#define STR0058 "Para acessar esta funcionalidade é necessário atualizar o dicionário de dados."
	#endif
#endif
