#ifdef SPANISH
	#define STR0001 "Unidad PRC"
	#define STR0002 "Cantidad de la reserva por escrito en la UmPRC"
	#define STR0003 "Municipio"
	#define STR0004 "Inscripción estatal"
	#define STR0005 "Est/Prov/Reg"
	#define STR0006 "Cantidad de la reserva por escrito en la UM"
	#define STR0007 "Almacén"
	#define STR0008 "Precio unitario"
	#define STR0009 "Fecha Actual"
	#define STR0010 "Cantidad de la reserva en UmPRC"
	#define STR0011 "Nombre tienda"
	#define STR0012 "Ciudad"
	#define STR0013 "Reserva no tiene"
	#define STR0014 "Informe el camino y el nombre del Arch. Origen (.dot)"
	#define STR0015 "¿Camino/Archivo dot Word?"
	#define STR0016 "Informe el camino destino del archivo"
	#define STR0017 '¿Camino del archivo de salida?'
	#define STR0018 "¡La integración word funciona solamente con windows!"
	#define STR0019 "¡Atención!"
	#define STR0020 "Ayuda"
	#define STR0021 "Archivo modelo inválido, por favor, informe el camino y el nombre del archivo modelo con su extensión"
	#define STR0022 "Por favor, informe la carpeta destino, para grabar el archivo"
	#define STR0023 "¡No fue posible imprimir el archivo!"
	#define STR0024 "Archivo Dot | *.Dot|"
	#define STR0025 "Archivo .Dotx |*.Dotx|"
	#define STR0026 "Seleccione el archivo modelo"
	#define STR0027 "Archivo word ||"
	#define STR0028 "Local de grabación"
	#define STR0029 "Integración con Ms-word"
	#define STR0030 "Impresión de documentos en el word."
	#define STR0031 "Se imprimirán de acuerdo con la selección de los parámetros."
	#define STR0032 "Impr. _Variables"
	#define STR0033 "Impr. _Documento"
	#define STR0034 "Variable"
	#define STR0035 "Descripción de la variable"
	#define STR0036 "Código de barras"
	#define STR0037 "Administración"
	#define STR0038 "Informe de las variables del archivo Word"
	#define STR0039 "Se imprimirá de acuerdo con los parámetros solicitados por el"
	#define STR0040 "Utilizador"
	#define STR0041 "Variables                     Descripción"
#else
	#ifdef ENGLISH
		#define STR0001 "Unit PRC"
		#define STR0002 "Reservation Quantity Written in UmPRC"
		#define STR0003 "City"
		#define STR0004 "State Registration"
		#define STR0005 "State"
		#define STR0006 "Qty of reservation written in UM"
		#define STR0007 "Warehouse"
		#define STR0008 "Unitary Value"
		#define STR0009 "Current Date"
		#define STR0010 "Qty of Reservation in UmPRC"
		#define STR0011 "Store Name"
		#define STR0012 "City"
		#define STR0013 "Reservation does not have"
		#define STR0014 "Enter path and origin file name (.dot)"
		#define STR0015 "Path/File dot Word  ?"
		#define STR0016 "Enter target patch of file"
		#define STR0017 'Path outbound file?'
		#define STR0018 "Integration word only works with windows!!!"
		#define STR0019 "Attention !"
		#define STR0020 "Help"
		#define STR0021 "File model invalid, please inform path and name of model file with extension"
		#define STR0022 "Enter Target folder to save file"
		#define STR0023 "Unable to print file!"
		#define STR0024 "File Dot | *.Dot|"
		#define STR0025 "File .Dotx |*.Dotx|"
		#define STR0026 "Select Model File"
		#define STR0027 "File word ||"
		#define STR0028 "Record Location"
		#define STR0029 "Integration with Ms-word"
		#define STR0030 "Printing documents in Word."
		#define STR0031 "Print according to Parameters Selection."
		#define STR0032 "Print _Variables"
		#define STR0033 "Print_Document"
		#define STR0034 "Variable"
		#define STR0035 "Description of Variable"
		#define STR0036 "Bar Codes"
		#define STR0037 "Administration"
		#define STR0038 "Report of Variable of Word file"
		#define STR0039 "Printed in accordance qith parameters requested by"
		#define STR0040 "Utilizer."
		#define STR0041 "Variable                      Description"
	#else
		#define STR0001 "Unidade PRC"
		#define STR0002 "Qtidade da reserva Por extenso na UmPRC"
		#define STR0003 "Município"
		#define STR0004 "Inscrição Estadual"
		#define STR0005 "Estado"
		#define STR0006 "Qtidade da reserva por extenso na UM"
		#define STR0007 "Armazém"
		#define STR0008 "Preço Unitário"
		#define STR0009 "Data atual"
		#define STR0010 "Qtidade da reserva na UmPRC"
		#define STR0011 "Nome Loja"
		#define STR0012 "Cidade"
		#define STR0013 "Reserva não possui"
		#define STR0014 "Informe caminho e o nome do arq. origem (.dot)"
		#define STR0015 "Caminho/Arquivo dot Word  ?"
		#define STR0016 "Informe o caminho destino do arquivo"
		#define STR0017 'Caminho do arquivo de Saida?'
		#define STR0018 "A integração word funciona somente com windows!!!"
		#define STR0019 "Atenção !"
		#define STR0020 "Ajuda"
		#define STR0021 "Arquivo modelo invalido, favor informal o caminho e o nome do arquivo modelo com sua extensão"
		#define STR0022 "Favor informar a Pasta destino, para salvar o arquivo"
		#define STR0023 "Não foi possivel imprimir o arquivo!"
		#define STR0024 "Arquivo Dot | *.Dot|"
		#define STR0025 "Arquivo .Dotx |*.Dotx|"
		#define STR0026 "Selecione o Arquivo de Modelo"
		#define STR0027 "Arquivo word ||"
		#define STR0028 "Local de gravação"
		#define STR0029 "Integração Com Ms-word"
		#define STR0030 "Impressão de documentos no Word."
		#define STR0031 "Serão impressos de acordo com a Seleção Dos Parâmetros."
		#define STR0032 "Impr. _Variáveis"
		#define STR0033 "Impr. _Documento"
		#define STR0034 "Variável"
		#define STR0035 "Descrição Da Variável"
		#define STR0036 "Código de barras"
		#define STR0037 "Administração"
		#define STR0038 "Relatório Das Variáveis do arqduivo Word"
		#define STR0039 "Será impresso de acordo com os parâmetros solicitados pelo"
		#define STR0040 "Utilizador."
		#define STR0041 "Variáveis                      Descrição"
	#endif
#endif
