#ifdef SPANISH
	#define STR0001 "Plan de ventas actualizado con éxito."
	#define STR0002 "Iniciando actualización de plan de ventas"
	#define STR0003 "Ocurrieron errores en la actualización del plan de ventas"
	#define STR0004 "Actualización del plan de ventas"
	#define STR0005 "ESPERE"
	#define STR0006 "Estimado"
	#define STR0007 "Volumen vendido mayor que Disponible por Comercializar"
	#define STR0008 "Por favor, evalúe."
	#define STR0009 "Unidad de negocio:"
	#define STR0010 "Cosecha:"
	#define STR0011 "Producto:"
	#define STR0012 "Volumen vendido:"
	#define STR0013 "Disponible para comercialización:"
	#define STR0014 "Atentamente"
	#define STR0015 "No se pudo enviar el e-mail"
	#define STR0016 "¡No válido!"
	#define STR0017 "no permite modificar."
	#define STR0018 "Importación"
	#define STR0019 "Iniciando proceso"
	#define STR0020 "Archivos separados por punto y coma"
	#define STR0021 "Seleccione Archivo"
	#define STR0022 "Archivo informado no existe."
	#define STR0023 "El archivo debe tener la extensión .CSV"
	#define STR0024 "Realizando la lectura del archivo..."
	#define STR0025 "Archivo aparenta estar vacío o no tiene información para importación. Certifíquese que las columnas y los datos necesarios están en el archivo para importación."
	#define STR0026 "Validando las líneas del archivo..."
	#define STR0027 "Tiene una cantidad de columnas diferente del encabezado.Verifique."
	#define STR0028 "archivo aparenta estar vacío o no tiene carácter separador de columnas"
	#define STR0029 "Procesando líneas del archivo..."
	#define STR0030 "Línea"
	#define STR0031 "Error(es) en la línea"
	#define STR0032 "¡El archivo se importó con éxito!"
	#define STR0033 "Ítems del plan de ventas"
	#define STR0034 "Errores"
	#define STR0035 "Una o más líneas del archivo no se importaron con éxito."
	#define STR0036 "Haga clic en 'Errores' para más detalles."
	#define STR0037 "Suma del % Venta totalizó más que el 100% para Fecha, Sucursal, Grupo de producto y Producto. El registro se importó, sin embargo el porcentaje se puso en cero."
	#define STR0038 "Fecha no válida"
	#define STR0039 "Informe una fecha que esté entre la fecha inicial y final del Plan de ventas."
	#define STR0040 "El registro de la línea"
	#define STR0041 "del archivo .csv no se encontró en la base de datos para actualizarlo!"
	#define STR0042 "Id del formulario de origen:"
	#define STR0043 "Id del campo de origen:"
	#define STR0044 "Id del formulario de error:"
	#define STR0045 "Id del campo de error:"
	#define STR0046 "Id del error:"
	#define STR0047 "Mensaje de error:"
	#define STR0048 "Mensaje de la solución:"
	#define STR0049 "Valor atribuido:"
#else
	#ifdef ENGLISH
		#define STR0001 "Sales Plan successfully updated."
		#define STR0002 "Starting Updating of Sales Plan"
		#define STR0003 "Errors in the updating of Sales Plan"
		#define STR0004 "Updating Sales Plan"
		#define STR0005 "WAIT"
		#define STR0006 "Dear"
		#define STR0007 "Volume Sold greater than the Available to Trade "
		#define STR0008 "Please evaluate."
		#define STR0009 "Business Unit: "
		#define STR0010 "Crop: "
		#define STR0011 "Product: "
		#define STR0012 "Volume Sold: "
		#define STR0013 "Available for Trading: "
		#define STR0014 "Sincerely yours, "
		#define STR0015 "Unable to send e-mail"
		#define STR0016 " Invalid!"
		#define STR0017 " does not allow changes."
		#define STR0018 "Import"
		#define STR0019 "Starting Process"
		#define STR0020 "Files separated by semicolon"
		#define STR0021 "Select file"
		#define STR0022 "File does not exist"
		#define STR0023 "Extension of file must be .CSV"
		#define STR0024 "Reading file"
		#define STR0025 "File seems to be empty or does not have data to import. Be sure the columns and data necessary are in the file to import."
		#define STR0026 "Validating file rows..."
		#define STR0027 "has a number of columns different from the header. Check."
		#define STR0028 "file seems to be empty or does not have a character separating the columns"
		#define STR0029 "Processing file rows..."
		#define STR0030 "Line "
		#define STR0031 "Error(s) in row "
		#define STR0032 "File successfully imported"
		#define STR0033 "Sales Plan Items"
		#define STR0034 "Errors"
		#define STR0035 "One or more rows of the file were not imported successfully."
		#define STR0036 " Click 'Errors' for further details."
		#define STR0037 "Total of sales % exceeded 100% for Date, Branch, Product Group and Group. Record was imported but the percentage was cleared."
		#define STR0038 "Invalid Date "
		#define STR0039 "Enter a date between the start and end dates of the Sales Plan."
		#define STR0040 "Register of line "
		#define STR0041 " of the .csv file was not found in the database to be updated!"
		#define STR0042 "Origin form ID:"
		#define STR0043 "Origin field ID: "
		#define STR0044 "Error form ID: "
		#define STR0045 "Error field ID: "
		#define STR0046 "Error ID: "
		#define STR0047 "Error message: "
		#define STR0048 "Solution message: "
		#define STR0049 "Value assigned: "
	#else
		#define STR0001 "Plano de Vendas atualizado com sucesso."
		#define STR0002 "Iniciando Atualização Plano de Vendas"
		#define STR0003 "Ocorreram erros na atualização do Plano de Vendas"
		#define STR0004 "Atualização do Plano de Vendas"
		#define STR0005 "AGUARDE"
		#define STR0006 "Prezado"
		#define STR0007 "Volume Vendido maior que Disponível a Comercializar "
		#define STR0008 "Favor avaliar."
		#define STR0009 "Unidade de Negócio: "
		#define STR0010 "Safra: "
		#define STR0011 "Produto: "
		#define STR0012 "Volume Vendido: "
		#define STR0013 "Disponível para Comercialização: "
		#define STR0014 "Atenciosamente "
		#define STR0015 "Não foi possível enviar o e-mail"
		#define STR0016 " Inválido!"
		#define STR0017 " não permite alteração."
		#define STR0018 "Importação"
		#define STR0019 "Iniciando Processo"
		#define STR0020 "Arquivos separados por Ponto-e-Vírgula"
		#define STR0021 "Escolher Arquivo"
		#define STR0022 "Arquivo informado não existe."
		#define STR0023 "Arquivo deve possuir a extensão .CSV"
		#define STR0024 "Realizando leitura do arquivo..."
		#define STR0025 "Arquivo aparenta estar vazio ou não possui as informações para importação. Certifique-se que as colunas e os dados necessários estão no arquivo para importação."
		#define STR0026 "Validando as linhas do arquivo..."
		#define STR0027 "possui uma quantidade de colunas diferente do cabeçalho.Verifique."
		#define STR0028 "arquivo aparenta estar vazio ou não possui caracter separador de colunas"
		#define STR0029 "Processando as linhas do arquivo..."
		#define STR0030 "Linha "
		#define STR0031 "Erro(s) na linha "
		#define STR0032 "O arquivo foi importado com sucesso!"
		#define STR0033 "Itens do Plano de Vendas"
		#define STR0034 "Erros"
		#define STR0035 "Uma ou mais linhas do arquivo não foram importadas com sucesso."
		#define STR0036 " Clique em 'Erros' para mais detalhes."
		#define STR0037 "Soma do % Venda totalizou mais que 100% para Data, Filial, Grupo de Produto e Produto. O registro foi importado, porém o percentual foi zerado."
		#define STR0038 "Data Inválida "
		#define STR0039 "Informe uma data que esteja entre a data inicial e final do Plano de Vendas."
		#define STR0040 "O registro da linha "
		#define STR0041 " do arquivo .csv não foi encontrado na base de dados para ser atualizado!"
		#define STR0042 "Id do formulário de origem:"
		#define STR0043 "Id do campo de origem: "
		#define STR0044 "Id do formulário de erro: "
		#define STR0045 "Id do campo de erro: "
		#define STR0046 "Id do erro: "
		#define STR0047 "Mensagem do erro: "
		#define STR0048 "Mensagem da solução: "
		#define STR0049 "Valor atribuído: "
	#endif
#endif
