#ifdef SPANISH
	#define STR0001 "Método de pagamento PIX não foi encontrado, verifique se a opção esta ativa no portal de configuração!"
	#define STR0002 "Carteras digitales :D"
	#define STR0003 "Error al intentar crear el archivo ("
	#define STR0004 "No fue posible obtener métodos de pago disponibles"
	#define STR0005 "Valor:"
	#define STR0006 "Próxima página"
	#define STR0007 "Página anterior"
	#define STR0008 "No fue posible crear/chequear los directorios"
	#define STR0009 "Metodo:"
	#define STR0010 "No está disponible por el momento."
	#define STR0011 "Método de pago:"
	#define STR0012 "Valor R$:"
	#define STR0013 "Esperando pago"
	#define STR0014 "Copiar enlace para pago"
	#define STR0015 "Copiado al área de transferencia."
	#define STR0016 "Enlace de pago no está disponible"
	#define STR0017 "Anular"
	#define STR0018 "Volver"
	#define STR0019 "Imprimir QR-Code"
	#define STR0020 "¡Pago realizado!"
	#define STR0021 "No fue posible realizar el Parse de devolución de la API, ERROR."
#else
	#ifdef ENGLISH
		#define STR0001 "PIX payment method not found. Check whether option is active in configuration portal!"
		#define STR0002 "Digital wallets :D"
		#define STR0003 "Error trying to create file ("
		#define STR0004 "Could not get available payment methods"
		#define STR0005 "Amount:"
		#define STR0006 "Next page"
		#define STR0007 "Previous page"
		#define STR0008 "Could not create/check the directories"
		#define STR0009 "Method:"
		#define STR0010 "Not available at the moment."
		#define STR0011 "Payment method:"
		#define STR0012 "Amount R$:"
		#define STR0013 "Awaiting payment"
		#define STR0014 "Copy payment Link"
		#define STR0015 "Copied to clipboard."
		#define STR0016 "Payment link not available."
		#define STR0017 "Cancel"
		#define STR0018 "Return"
		#define STR0019 "Print QR Code"
		#define STR0020 "Payment completed!"
		#define STR0021 "Could not parse the API return, ERROR:"
	#else
		#define STR0001 "Método de pagamento PIX não foi encontrado, verifique se a opção esta ativa no portal de configuração!"
		#define STR0002 "Carteiras digitais :D"
		#define STR0003 "Erro ao tentar criar o arquivo ("
		#define STR0004 "Não foi possivel obter metodos de pagamentos disponiveis"
		#define STR0005 "Valor:"
		#define STR0006 "Proxima pagina"
		#define STR0007 "Pagina Anterior"
		#define STR0008 "Não foi possivel criar/checar os diretorios "
		#define STR0009 "Metodo:  "
		#define STR0010 " Não esta disponivel no momento. "
		#define STR0011 "Método de pagamento:  "
		#define STR0012 "Valor R$:  "
		#define STR0013 "Aguardando pagamento "
		#define STR0014 "Copiar Link para pagamento "
		#define STR0015 "Copiado para area de transferencia. "
		#define STR0016 "Link de pagamento não está disponivel "
		#define STR0017 "Cancelar "
		#define STR0018 "Retornar "
		#define STR0019 "Imprimir QR-Code "
		#define STR0020 "Pagamento realizado! "
		#define STR0021 "Não foi possivel realizar o Parse do retorno da API, ERRO:  "
	#endif
#endif
