#ifdef SPANISH
	#define STR0001 "Finalizar"
	#define STR0002 "Estructura inconsistente: "
	#define STR0003 "Planificación y control presupuestario"
	#define STR0004 "Atención"
	#define STR0005 "Confirma"
	#define STR0006 "Anula"
	#define STR0007 "No se digitó cuenta presupuestaria"
	#define STR0008 "Atención"
	#define STR0009 "Error al definir nombre del archivo: "
	#define STR0010 " . Existente.)"
	#define STR0011 "Error en la copia"
	#define STR0012 "No se encontró el objeto correspondiente al "
	#define STR0013 "Copiando objeto"
	#define STR0014 "Espere..."
	#define STR0015 "Ente - "
	#define STR0016 " - Clave de búsqueda no se informó."
	#define STR0017 "Confirma la configuración del campo"
	#define STR0018 "Clave Identificador"
	#define STR0019 "Ente (Tabla)"
	#define STR0020 "Índice"
	#define STR0021 "Sucursal"
	#define STR0022 "Clave al buscar"
	#define STR0023 "Verifique la configuración del campo"
	#define STR0024 " Donde las posiciones:"
	#define STR0025 "Configuración inválida"
	#define STR0026 "Confirma configuración"
	#define STR0027 "Otros"
	#define STR0028 "Error al grabar el archivo de imagen. Intente nuevamente"
	#define STR0029 "El archivo [ "
	#define STR0030 ".BMP ] generado con éxito."
	#define STR0031 "Imprimir"
	#define STR0032 "Digite el nombre del archivo"
	#define STR0033 "Archivo en formato BMP"
	#define STR0034 "Grabar los archivos en formato .BMP generados "
	#define STR0035 "Se modificaron algunos valores de este ítem presupuestario después de la lectura. Los datos se actualizarán."
	#define STR0036 "Sí"
	#define STR0037 "No"
	#define STR0038 "Seleccione el directorio "
	#define STR0039 "Período final informado es superior al período inicial."
#else
	#ifdef ENGLISH
		#define STR0001 "Close"
		#define STR0002 "Inconsistent Structure: "
		#define STR0003 "Budgetary Control and Planning"
		#define STR0004 "Attention"
		#define STR0005 "Confirm"
		#define STR0006 "Cancel"
		#define STR0007 "Budgetary account not entered"
		#define STR0008 "Attention"
		#define STR0009 "Error defining file name: "
		#define STR0010 " . Already existent!)"
		#define STR0011 "Error in Copy"
		#define STR0012 "Unable to find object corresponding to "
		#define STR0013 "Copying object"
		#define STR0014 "Wait..."
		#define STR0015 "Entity - "
		#define STR0016 " - Search key not entered."
		#define STR0017 "Confirms field configuration"
		#define STR0018 "ID Key"
		#define STR0019 "Entity (Table)"
		#define STR0020 "Index"
		#define STR0021 "Branch"
		#define STR0022 "Searchable Key"
		#define STR0023 "Check field configuration"
		#define STR0024 " Where Positions:"
		#define STR0025 "Invalid Configuration"
		#define STR0026 "Confirms Configuration"
		#define STR0027 "Other"
		#define STR0028 "Error saving image file. Try again"
		#define STR0029 "File [ "
		#define STR0030 ".BMP ] successfully generated."
		#define STR0031 "Print"
		#define STR0032 "Enter File Name"
		#define STR0033 "File in BMP format"
		#define STR0034 "Save files generated in BMP format "
		#define STR0035 "Some values of this budgetary item were changed after reading. Data will be updated."
		#define STR0036 "Yes"
		#define STR0037 "No"
		#define STR0038 "Select directory "
		#define STR0039 "Ending term entered is longer than starting term."
	#else
		#define STR0001 "Fechar"
		#define STR0002 "Estrutura Inconsistente : "
		#define STR0003 "Planejamento e Controle Orçamentário"
		#define STR0004 "Atencao"
		#define STR0005 "Confirma"
		#define STR0006 "Cancela"
		#define STR0007 "Nao digitado conta orcamentaria"
		#define STR0008 "Atenção"
		#define STR0009 "Erro ao definir nome do arquivo: "
		#define STR0010 " . Ja existente!)"
		#define STR0011 "Erro na Copia"
		#define STR0012 "Nao encontrado o objeto correspondente ao "
		#define STR0013 "Copiando objeto"
		#define STR0014 "Aguarde..."
		#define STR0015 "Entidade - "
		#define STR0016 " - Chave de pesquisa não informado."
		#define STR0017 "Confirma a configuracao do campo"
		#define STR0018 "Chave Identificador"
		#define STR0019 "Entidade (Tabela)"
		#define STR0020 "Indice"
		#define STR0021 "Filial"
		#define STR0022 "Chave a Pesquisar"
		#define STR0023 "Verifique a configuração do campo"
		#define STR0024 " Onde as Posicões:"
		#define STR0025 "Configuração Inválida"
		#define STR0026 "Confirma Configuração"
		#define STR0027 "Demais"
		#define STR0028 "Erro ao gravar o arquivo de imagem. Tente novamente"
		#define STR0029 "O arquivo [ "
		#define STR0030 ".BMP ] gerado com sucesso."
		#define STR0031 "Imprimir"
		#define STR0032 "Digite Nome do Arquivo"
		#define STR0033 "Arquivo em formato BMP"
		#define STR0034 "Salvar os arquivos em formato .BMP gerados "
		#define STR0035 "Foram alterados alguns valores deste item orcamentario apos a leitura. Dados serao atualizados."
		#define STR0036 "Sim"
		#define STR0037 "Nao"
		#define STR0038 "Selecione o diretório "
		#define STR0039 "Período final informado é maior que o período inicial."
	#endif
#endif
