#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Mantenimiento del Plan Maestro de Producción"
	#define STR0007 "Leyenda"
	#define STR0008 "Esperando ejecución"
	#define STR0009 "Ejecutado"
	#define STR0010 "Registro"
	#define STR0011 "Documentos"
	#define STR0012 "Importar"
	#define STR0013 "Eliminación de los PMP"
	#define STR0014 "De Documento"
	#define STR0015 "A Documento"
	#define STR0016 "De Fch. Previsión"
	#define STR0017 "A Fch. Previsión"
	#define STR0018 "Confirma"
	#define STR0019 "Anula"
	#define STR0020 "Botón Opcionales"
	#define STR0021 "PMP ya ejecutado. Eliminación no permitida."
	#define STR0022 "Importación de los PMP"
	#define STR0023 "Informe el lugar donde se encuentra el archivo para importación:"
	#define STR0024 "&Abrir..."
	#define STR0025 "Informe la posición de las columnas en el archivo que se importará y que corresponden a los siguientes campos:"
	#define STR0026 "Datos que compondrán el PMP:"
	#define STR0027 "Columna:"
	#define STR0028 "Por digitación"
	#define STR0029 "Por importación"
	#define STR0030 "&Importar"
	#define STR0031 "&Anular"
	#define STR0032 "Informe el archivo que se importará."
	#define STR0033 "Atención"
	#define STR0034 "No se encontró el archivo seleccionado para importación."
	#define STR0035 "Es obligatorio informar los campos resaltados en azul."
	#define STR0036 "Espere"
	#define STR0037 "Procesando la lectura del archivo..."
	#define STR0038 "¡No hay registros para importación!"
	#define STR0039 "Finalizado"
	#define STR0040 "Se importarán"
	#define STR0041 "registro(s) de"
	#define STR0042 "registro(s) leído(s). ¿Confirma?"
	#define STR0043 "Procesando la grabación del(os) registro(s) leído(s)..."
	#define STR0044 "Archivo CSV"
	#define STR0045 "¡Registros importados con éxito!"
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Maintenance of Production Master Plan"
		#define STR0007 "Caption"
		#define STR0008 "Waiting for execution"
		#define STR0009 "Executed"
		#define STR0010 "Record"
		#define STR0011 "Documents"
		#define STR0012 "Import"
		#define STR0013 "PMPs Deletion"
		#define STR0014 "Document:"
		#define STR0015 "To Document"
		#define STR0016 "From Estimation Dt"
		#define STR0017 "To Estimation Dt"
		#define STR0018 "Confirm"
		#define STR0019 "Cancel"
		#define STR0020 "Optional Buttons"
		#define STR0021 "PMP already run. Deletion not allowed."
		#define STR0022 "Import of PMPs"
		#define STR0023 "Enter location where the file is to import:"
		#define STR0024 "&Open..."
		#define STR0025 "Enter option of the columns in the file that is imported corresponding to the fields below:"
		#define STR0026 "Data compounding PMP:"
		#define STR0027 "Column:"
		#define STR0028 "By data entry"
		#define STR0029 "By import"
		#define STR0030 "&Import"
		#define STR0031 "&Cancel"
		#define STR0032 "Enter file to be imported."
		#define STR0033 "Attention"
		#define STR0034 "The file selected to import was not found."
		#define STR0035 "The fields highlighted in blue are required."
		#define STR0036 "Wait"
		#define STR0037 "Processing reading of file..."
		#define STR0038 "There are no records to import!"
		#define STR0039 "Finished"
		#define STR0040 "We import "
		#define STR0041 " record(s) of "
		#define STR0042 " records read. Confirm it?"
		#define STR0043 "Processing the recording of the record(s) read..."
		#define STR0044 "CSV File"
		#define STR0045 "Registers successfully imported!"
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Manutençäo do Plano Mestre de Produçäo"
		#define STR0007 "Legenda"
		#define STR0008 "Aguardando execução"
		#define STR0009 "Executado"
		#define STR0010 "Registro"
		#define STR0011 "Documentos"
		#define STR0012 "Importar"
		#define STR0013 "Exclusão de PMP's"
		#define STR0014 "Documento de"
		#define STR0015 "Documento até"
		#define STR0016 "Dt. Previsão de"
		#define STR0017 "Dt. Previsão até"
		#define STR0018 "Confirma"
		#define STR0019 "Cancela"
		#define STR0020 "Botão Opcionais"
		#define STR0021 "PMP já executado. Exclusão não permitida."
		#define STR0022 "Importação de PMP's"
		#define STR0023 "Informe o local onde se encontra o arquivo para importação:"
		#define STR0024 "&Abrir..."
		#define STR0025 "Informe a posição das colunas no arquivo que será importado que correspondem aos campos abaixo:"
		#define STR0026 "Dados que irão compor o PMP:"
		#define STR0027 "Coluna:"
		#define STR0028 "Por digitação"
		#define STR0029 "Por importação"
		#define STR0030 "&Importar"
		#define STR0031 "&Cancelar"
		#define STR0032 "Informe o arquivo a ser importado."
		#define STR0033 "Atenção"
		#define STR0034 "O arquivo selecionado para importação não foi encontrado."
		#define STR0035 "Os campos destacados em azul são de preenchimento obrigatório."
		#define STR0036 "Aguarde"
		#define STR0037 "Processando a leitura do arquivo..."
		#define STR0038 "Não há registros para importação!"
		#define STR0039 "Finalizado"
		#define STR0040 "Serão importados "
		#define STR0041 " registro(s) de "
		#define STR0042 " registro(s) lido(s). Confirma?"
		#define STR0043 "Processando a gravação do(s) registro(s) lido(s)..."
		#define STR0044 "Arquivo CSV"
		#define STR0045 "Registros importados com sucesso!"
	#endif
#endif
