#ifdef SPANISH
	#define STR0001 'Relacion TISS vs. Protheus'
	#define STR0002 'Archivo de Terminos TISS'
	#define STR0003 'Encabezamiento del Termino'
	#define STR0004 'Relacion TISS vs. Protheus'
	#define STR0005 "Errores en la importacion."
	#define STR0006 "No existen archivos para importacion"
	#define STR0007 "El archivo XSD no se localizo en la carpeta seleccionada."
	#define STR0008 "Archivo XML invalido."
	#define STR0009 "No fue posible recuperar el item de la tabla: "
	#define STR0010 "Importando Tabla: "
	#define STR0011 "Tabla importada: "
	#define STR0012 "Item importado: "
	#define STR0013 "Importando terminologia: "
	#define STR0014 "Tabla no encontrada: "
	#define STR0015 "¡Importacion realizada con exito!"
	#define STR0016 "Los XMLs se borraron de la carpeta informada."
	#define STR0017 "Archivo XML invalido."
	#define STR0018 "Importando"
	#define STR0019 "Importando XML..."
	#define STR0020 "VISUALICE LOS LOGS DE IMPORTACION EN LA CARPETA /LOGPLS"
	#define STR0021 " --------------------"
	#define STR0022 " DataBase...........: "
	#define STR0023 " Fecha / Hora Inicio.: "
	#define STR0024 " Environment........: "
	#define STR0025 " StartPath..........: "
	#define STR0026 " RootPath...........: "
	#define STR0027 " Version.............: "
	#define STR0028 " Usuario TOTVS .....: "
	#define STR0029 " Computer Name......: "
	#define STR0030 " Datos Thread"
	#define STR0031 " Usuario de Red....: "
	#define STR0032 " Estacion............: "
	#define STR0033 " Programa inicial...: "
	#define STR0034 " Conexion............: "
	#define STR0035 " Fecha / Hora Final.: "
	#define STR0036 "Actualizacion concluida."
	#define STR0037 "Archivos XML |*.xml|"
	#define STR0038 "Seleccione el directorio de archivos XML"
	#define STR0039 "SERVIDOR\"
	#define STR0040 "Verifique la version de TISS en el Cad. ¡Operadora actual!"
	#define STR0041 "Si no existe el campo: Version TISS (BA0_TISVER), ejecute los compatibilizadores UPDPLSBC, UPDPLSBH del paquete TISS 3.0 conforme boletin tecnico."
	#define STR0042 "Salir"
#else
	#ifdef ENGLISH
		#define STR0001 'Relationship TISS x Protheus'
		#define STR0002 'TISS Terms Register'
		#define STR0003 'Term Header'
		#define STR0004 'Relationship TISS x Protheus'
		#define STR0005 "Error in importing."
		#define STR0006 "There are no files to be imported."
		#define STR0007 "The XSD file was not located in the selected folder."
		#define STR0008 "XML file invalid."
		#define STR0009 "Could not recover table item: "
		#define STR0010 "Importing table: "
		#define STR0011 "Imported table: "
		#define STR0012 "Imported item: "
		#define STR0013 "Importing terminology: "
		#define STR0014 "Table not found: "
		#define STR0015 "Imported successfully!"
		#define STR0016 "XMLs deleted from the entered folder."
		#define STR0017 "XML file invalid."
		#define STR0018 "Importing"
		#define STR0019 "Importing XML..."
		#define STR0020 "VIEW IMPORT LOGS ON THE FOLDER/LOGPLS"
		#define STR0021 " --------------------"
		#define STR0022 " Base date...........: "
		#define STR0023 " Start Date/Time.: "
		#define STR0024 " Environment........: "
		#define STR0025 " StartPath..........: "
		#define STR0026 " RootPath...........: "
		#define STR0027 " Version.............: "
		#define STR0028 " TOTVS User.....: "
		#define STR0029 " Computer Name......: "
		#define STR0030 " Thread Data"
		#define STR0031 " Network User....: "
		#define STR0032 " Station............: "
		#define STR0033 " Initial Program...: "
		#define STR0034 " Connection............: "
		#define STR0035 " End Date/Time: "
		#define STR0036 "Update completed."
		#define STR0037 "XML files |*.xml|"
		#define STR0038 "Select the XML file directory"
		#define STR0039 "SERVER\"
		#define STR0040 "Check TISS version in the current Operators Reg. "
		#define STR0041 "If there is no field: TISS Version (BA0_TISVER), run compatibility UPDPLSBC, UPDPLSBH of package TISS 3.0 according to technical inspection."
		#define STR0042 "Exit"
	#else
		#define STR0001 'Relação TISS x Protheus'
		#define STR0002 'Cadastro de Termos TISS'
		#define STR0003 'Cabeçalho do Termo'
		#define STR0004 'Relaçãoo TISS x Protheus'
		#define STR0005 "Erro na importação."
		#define STR0006 "Não existem arquivos para serem importados."
		#define STR0007 "O arquivo XSD não foi localizado na pasta selecionada."
		#define STR0008 "Arquivo XML inválido."
		#define STR0009 "Não foi possível recuperar o item da tabela: "
		#define STR0010 "Importando Tabela: "
		#define STR0011 "Tabela importada: "
		#define STR0012 "Item importado: "
		#define STR0013 "Importando terminologia: "
		#define STR0014 "Tabela não encontrada: "
		#define STR0015 "Importação realizada com sucesso!"
		#define STR0016 "Os XMLs foram deletados da pasta informada."
		#define STR0017 "Arquivo XML inválido."
		#define STR0018 "Importando"
		#define STR0019 "Importando XML..."
		#define STR0020 "VISUALIZE OS LOGS DE IMPORTAÇÃO NA PASTA /LOGPLS"
		#define STR0021 " --------------------"
		#define STR0022 " DataBase...........: "
		#define STR0023 " Data / Hora Inicio.: "
		#define STR0024 " Environment........: "
		#define STR0025 " StartPath..........: "
		#define STR0026 " RootPath...........: "
		#define STR0027 " Versao.............: "
		#define STR0028 " Usuario TOTVS .....: "
		#define STR0029 " Computer Name......: "
		#define STR0030 " Dados Thread"
		#define STR0031 " Usuario da Rede....: "
		#define STR0032 " Estacao............: "
		#define STR0033 " Programa Inicial...: "
		#define STR0034 " Conexao............: "
		#define STR0035 " Data / Hora Final.: "
		#define STR0036 "Atualizacao concluida."
		#define STR0037 "Arquivos XML |*.xml|"
		#define STR0038 "Selecione o diretorio de arquivos XML"
		#define STR0039 "SERVIDOR\"
		#define STR0040 "Verifique a versão da TISS no Cad. Operadora corrente!"
		#define STR0041 "Caso não exista o campo: Versão TISS (BA0_TISVER), execute os compatibilizadores UPDPLSBC, UPDPLSBH do pacote TISS 3.0 conforme boletim técnico."
		#define STR0042 "Sair"
	#endif
#endif
