#ifdef SPANISH
	#define STR0001 "Procedimientos relacionados"
	#define STR0002 "Existe más de un procedimiento principal registrado en este paquete."
	#define STR0003 "Atención"
	#define STR0004 "La fecha de vigencia inicial no debe ser mayor que la fecha final."
	#define STR0005 "Procedimiento no válido"
	#define STR0006 "Procedimiento principal ya existe en un paquete"
	#define STR0007 "Ok"
	#define STR0008 "¿Desea vincular el paquete"
	#define STR0009 "con la(s) RDA seleccionada(s)?"
	#define STR0010 "El vínculo del paquete"
	#define STR0011 "con la(s) RDA seleccionadas se realizó con éxito."
	#define STR0012 "Para realizar el vínculo, debe tenerse por lo menos una RDA seleccionada."
	#define STR0013 "¡Registro no se no se encontró!"
#else
	#ifdef ENGLISH
		#define STR0001 "Related Procedures"
		#define STR0002 "There is more than a Main procedure registered in this package."
		#define STR0003 "Attention"
		#define STR0004 "Start validity date cannot be after end date."
		#define STR0005 "Procedure invalid"
		#define STR0006 "Main procedure already exists in a package."
		#define STR0007 "Ok"
		#define STR0008 "Do you want to link to the package"
		#define STR0009 "To the Service Networks selected ?"
		#define STR0010 "The link of the Package"
		#define STR0011 "to the Service Network selected was successfully performed."
		#define STR0012 "to link, at least one Service Network must be selected."
		#define STR0013 "Records not found"
	#else
		#define STR0001 "Procedimentos Relacionados"
		#define STR0002 "Existe mais de um procedimento Principal cadastrado neste pacote."
		#define STR0003 "Atencao"
		#define STR0004 "A data de validade inicial não pode ser maior do que a data final."
		#define STR0005 "Procedimento Invalido"
		#define STR0006 "Procedimento principal ja existe em um pacote! "
		#define STR0007 "Ok"
		#define STR0008 "Deseja vincular o pacote "
		#define STR0009 "com a(s) RDA(s) selecionada(s) ?"
		#define STR0010 "O vínculo do Pacote "
		#define STR0011 " com a(s) RDA(s) selecionadas foi realizado com sucesso !"
		#define STR0012 "Para realizar o vínculo, deve-se ter pelo menos uma RDA selecionada."
		#define STR0013 "Registros não encontrado !"
	#endif
#endif
