#ifdef SPANISH
	#define STR0001 "Debitos/Creditos Redes de Atencion"
	#define STR0002 "Este registro no puede borrarse por que se genero de forma automatica por otra rutina del sistema."
	#define STR0003 "Este registro no puede borrarse por que ya se proceso por la rutina de pago."
	#define STR0004 "Este registro no puede modificarse por que se genero de forma automatica por otra rutina del sistema."
	#define STR0005 "Este regsitro no puede modificarse por que ya se proceso por la rutina de pago."
	#define STR0006 "Buscar"
	#define STR0007 "Visualizar"
	#define STR0008 "Incluir"
	#define STR0009 "Modificar"
	#define STR0010 "Borrar"
#else
	#ifdef ENGLISH
		#define STR0001 "Health Attendance Network Debits/Credits"
		#define STR0002 "You cannot delete the entry as it was automatically generated by another system routine."
		#define STR0003 "You cannot delete the entry as it was already processed by the payment routine."
		#define STR0004 "You cannot edit the entry as it was automatically generated by another system routine."
		#define STR0005 "You cannot edit the entry as it was already processed by the payment routine."
		#define STR0006 "Search"
		#define STR0007 "View"
		#define STR0008 "Add"
		#define STR0009 "Edit"
		#define STR0010 "Delete"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Débitos/créditos Redes De Atendimento", "Debitos/Creditos Redes de Atendimento" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Este lançamento    não pode ser excluido porque foi criado de forma automática por outro procedimento do sistema.", "Este lançamento não pode ser excluído porque foi gerado de forma automática por outra rotina do sistema." )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Este lançamento    não pode ser excluido porque já foi processado pelo procedimento de pagamento.", "Este lançamento não pode ser excluído porque já foi processado pela rotina de pagamento." )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Este lançamento    não pode ser alterado porque foi criado de forma automática por outro procedimento do sistema.", "Este lançamento não pode ser alterado porque foi gerado de forma automática por outra rotina do sistema." )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Este lançamento    não pode ser alterado porque já foi processado pelo procedimento de pagamento.", "Este lançamento não pode ser alterado porque já foi processado pela rotina de pagamento." )
		#define STR0006 "Pesquisar"
		#define STR0007 "Visualizar"
		#define STR0008 "Incluir"
		#define STR0009 "Alterar"
		#define STR0010 "Excluir"
	#endif
#endif
