#define __aCdCri001 {"035","Usuario nao possui cobertura para este procedimento."}
#define __aCdCri002 {"001","Idade do usuario incompativel com a idade limite para o procedimento."}
#define __aCdCri003 {"002","Procedimento em carencia para este usuario."}
#define __aCdCri004 {"003","Sexo invalido para este procedimento."}
#define __aCdCri005 {"502","Unidade da Rede de atendimento bloqueada."}
#define __aCdCri006 {"503","Rede de Atendimento sem local de atendimento cadastrado."}
#define __aCdCri007 {"504","Local de atendimento invalido para o produto do usuario."}
#define __aCdCri008 {"505","Familia bloqueada."}
#define __aCdCri009 {"506","Usuario bloqueado."}
#define __aCdCri010 {"507","Operadora invalida para este usuario."}
#define __aCdCri011 {"508","Matricula do usuario: Invalida."}
#define __aCdCri012 {"509","Operadora da Rede de atendimento: Invalida."}
#define __aCdCri013 {"510","Matricula da Rede de atendimento: Invalida."}
#define __aCdCri014 {"511","Rede de atendimento nao permitida para a operadora informada."}
#define __aCdCri015 {"512","Rede de atendimento sem local de atendimento cadastrado."}
#define __aCdCri016 {"513","Rede de atendimento sem especialidade cadastrada"}
#define __aCdCri017 {"004","Critica Financeira."}
#define __aCdCri018 {"005","Procedimento em carencia para este usuario (PREEXISTENCIA)."}
#define __aCdCri019 {"514","Existe uma internacao para este usuario cuja data de alta encontra-se sem preenchimento."}
#define __aCdCri020 {"006","RDA nao autorizada a executar o procedimento (Campo Executa/Solicita/Ambos)"}
#define __aCdCri021 {"007","Procedimento bloqueado na especialidade de Rede de atendimento."}
#define __aCdCri022 {"008","Idade do usuario incompativel com a idade limite para a especialidade."}
#define __aCdCri023 {"009","Sexo invalido para a especialidade."}
#define __aCdCri024 {"010","A data do evento e anterior a data de inclusao do usuario."}
#define __aCdCri025 {"044","Nao existe calendario de pagamento para a data do evento informada OU nao existe U.S mensais para o calendario de pagamento."}
#define __aCdCri026 {"050","Abrangencia de atendimento nao permitida para este produto."}
#define __aCdCri027 {"517","Nao foi encontrada nenhuma ocorrencia para o Codigo da Tabela de Honorarios a ser utilizada."}
#define __aCdCri028 {"518","Nao existe composicao para esse procedimento."}
#define __aCdCri029 {"519","A expressao para o Calculo da US em Procedimentos Autorizados na Especialidade da RDA, nao foi informado corretamente."}
#define __aCdCri030 {"520","A expressao para o Calculo da US em Especialidades na RDA, nao foi informado corretamente."}
#define __aCdCri031 {"521","A expressao para o Calculo da US no Local de Atendimento na RDA, nao foi informado corretamente."}
#define __aCdCri033 {"049","Data limite para recebimento de guias de intercambio vencida."}  
#define __aCdCri034 {"524","Nao foi informado nenhum valor para a US."}
#define __aCdCri035 {"525","Nao foi informado nenhum valor para o Filme."}
#define __aCdCri036 {"526","Nao foi informado nenhum valor para o Porte Anestesico."}
#define __aCdCri037 {"527","Nao foi informado nenhum valor para o auxiliar."}
#define __aCdCri038 {"530","Digite verificador da matricula invalido"}
#define __aCdCri039 {"012","Solicitante nao autorizado a solicitar este procedimento (Campo Executa/Solicita/Ambos)"}
#define __aCdCri040 {"013","Obrigatorio informar o CID para este procedimento."}
#define __aCdCri041 {"014","Obrigatorio a informacao do medico solicitante para este tipo de guia"}
#define __aCdCri044 {"528","O Procedimento foi negado para ser executado por este prestador no local da atendimento e especialidade."}
#define __aCdCri045 {"529","A parametrizacao dos niveis de cobranca esta invalida."}
#define __aCdCri046 {"017","Limite de Quantidade ultrapassada."}
#define __aCdCri047 {"018","Limite de Periodicidade ultrapassada."}
#define __aCdCri048 {"019","Limite de Grupo de Quantidade ultrapassada."}
#define __aCdCri050 {"021","Para este procedimento necessita Guia da Operadora."}
#define __aCdCri051 {"025","Para este procedimento necessita Auditoria."}
#define __aCdCri052 {"022","Para este procedimento necessita Guia da Empresa."}
#define __aCdCri053 {"023","Para este procedimento necessita Guia da Operadora e Empresa."}
#define __aCdCri054 {"024","Para este procedimento necessita Avaliacao Contratual."}
#define __aCdCri055 {"026","Procedimento informado nao existe na tabela padrao."}
#define __aCdCri056 {"027","Para este procedimento devera ser efetuado o pagamento do procedimento no ato da emissao da guia"}
#define __aCdCri057 {"028","Procedimento incompativel com um dos procedimentos da guia"}
#define __aCdCri058 {"029","Cid incompativel com um dos procedimentos da guia"}
#define __aCdCri059 {"531","Nao foi encontrada nenhuma tabela de pagamento para esta guia"}
#define __aCdCri060 {"030","Procedimento bloqueado pela Operadora para atendimento."}
#define __aCdCri061 {"031","limite de CH por guia emitida ultrapassado conforme parametrizacao feito no subcontrato."}
#define __aCdCri062 {"032","A Rede de Atendimento nao pode atender a usuarios deste produto."}
#define __aCdCri063 {"532","Nao foi informado nenhum valor para o Tempo Cirurgico."}
#define __aCdCri064 {"533","Gerenciador de comunicacao OnLine nao esta ativo."}
#define __aCdCri065 {"534","Time out.Operadora fora do Ar."}
#define __aCdCri066 {"535","Verificar tabela PTU"}
#define __aCdCri067 {"033","Data limite de atendimento informado na familia ultrapassado"}
#define __aCdCri068 {"034","Procedimento invalido para lancamentos como eventos (analitico/sintetico)"}
#define __aCdCri069 {"036","Foi ultrapassado o limite parametrizado para autorizacao de intercambio eventual on-line."}
#define __aCdCri071 {"537","CID informado invalido."}
#define __aCdCri072 {"538","Data de validade do cartao da empresa vencida."}
#define __aCdCri073 {"037","Data de validade do cartao do usuario vencido."}
#define __aCdCri074 {"038","Produto do usuario nao permite atendimento por esta Rede de Atendimento."}    
#define __aCdCri075 {"539","Falha no retorno dos parametros na funcao PLSESPNIV."}
#define __aCdCri076 {"039","Via de cartao magnetico nao existente."}    
#define __aCdCri077 {"040","Via de cartao magnetico bloqueada."}    
#define __aCdCri078 {"041","Via de cartao magnetico vencida."}    
#define __aCdCri079 {"042","Via de cartao magnetico invalida."}	
#define __aCdCri080 {"043","Critica por Time out na resposta da transacao."}    
#define __aCdCri081 {"045","Dente extraido/inutilizado para este procedimento."}  
#define __aCdCri082 {"046","Codigo corespondente ao dente no procedimento invalido."}     
#define __aCdCri083 {"047","Especialidade bloqueada para esta RDA."}  
#define __aCdCri084 {"048","Local de Atendimento bloqueado para esta RDA."}  
#define __aCdCri085 {"051","O usuario nao possui cobertura para este tipo de internacao"} 
#define __aCdCri107 {"703","Processo de autorizacao On-Line (Cancelado)"} 
#define __aCdCri104 {"705","Rede de atendimento de Alto Custo"  }
#define __aCdCri106 {"707","Data de atendimento informada na transacao de internacao (On-Line)"  }
#define __aCdCri184 {"09J","Atendimento domiciliar necessita liberação atenção a saude." }     
#define __aCdCri185 {"09K","Regime de atendimento não comporta fator multiplicador."}
#define __aCdCri186 {"09L","Procedimento já existente no pacote."}
#define __aCdCri187 {"573","Demanda por requerimento"}
#define __aCdCri188 {"567","Procedimento incompativel com um dos procedimentos da guia - Auditar"}
#define __aCdCri189 {"568","Pre-requisito nao encontrado dentro do periodo maximo exigido."}
#define __aCdCri190 {"569","Pre-requisito nao cumpriu periodo minimo exigido."}
#define __aCdCri191 {"09M","Não permite Reembolso para o Usuário!"}
#define __aCdCri192 {"571","Procedimento incompativel com um dos procedimentos da guia - Reduzir a UCO"} 
#define __aCdCri193 {"572","Procedimento incompativel com um dos procedimentos da guia - Criticar"}
#define __aCdCri194 {"574","Auditoria Participativa"}
#define __aCdCri195 {"09N","Data de entrega fora do prazo"}
#define __aCdCri196 {"09O","Evento ja pago ou incidencia excede a quantidade autorizada"}
#define __aCdCri197 {"09P","Habilita checagem de regra para procedimentos incompatíveis!"}
#define __aCdCri198 {"09Q","Habilita checagem DE/PARA TUSS!"}
#define __aCdCri199 {"576","Nao encontrou o usuario informado - Ptu Online"}
#define __aCdCri200 {"580","Procedimento do tipo 'Pacote' em autorização PTU On-line"}
#define __aCdCri201 {"577","Nao encontrou o prestador informado - Ptu Online"}
#define __aCdCri202 {"578","Registro DS_OBSERVA informado, guia automaticamente enviada para Auditoria"}
#define __aCdCri203 {"579","Registro DS_OPME informado, serviço não existe na tabela de Intercâmbio Nacional"}
