#ifdef SPANISH
	#define STR0001 "GENERADO POR LA RUTINA DE LOTE DE COBRANZA"
	#define STR0002 "¡No se encontro Condicion de pago!"
#else
	#ifdef ENGLISH
		#define STR0001 "GENERATED BY THE ROUTINE OF COLLECTION LOT"
		#define STR0002 "Payment Condition not found!"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "GERADO PELA ROTINA DE LOTE DE COBRANÇA", "GERADO PELA ROTINA DE LOTE DE COBRANCA" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Não encontrada condição de pagamento!", "Não Encontrada Condição de pagamento!!" )
	#endif
#endif
