#ifdef SPANISH
	#define STR0001 "Gestión de avisos - Envío"
	#define STR0002 "Pend. Envío aviso"
	#define STR0003 "Aviso enviado"
	#define STR0004 "Aviso recibido"
	#define STR0005 "Buscar"
	#define STR0006 "Detallar"
	#define STR0007 "Procesar"
	#define STR0008 "Generar archivo"
	#define STR0009 "Importa Arch. Devolución"
	#define STR0010 "Procesa glosa total"
	#define STR0011 "Exportar PTU A530"
	#define STR0012 "Borrar"
	#define STR0013 "Lote"
	#define STR0014 "Formularios del lote"
	#define STR0015 "Eventos del formulario"
	#define STR0016 "El envío de aviso se procesó en:"
	#define STR0017 "¿Desea procesar nuevamente?"
	#define STR0018 "Atención"
	#define STR0019 "No se permite generar Envío de aviso para el estatus actual."
	#define STR0020 "Solamente se permiten borrar registros con el Estatus [1] - Pend. Envío aviso"
	#define STR0021 "Procesa Archivo de envío"
	#define STR0022 "Esta es la opción que efectuará la lectura de las tablas de cuentas médicas del PLS,"
	#define STR0023 "identIficar y procesar atenciones de intercambio eventual realizados para"
	#define STR0024 "beneficiarios habituales."
	#define STR0025 "Procesar"
	#define STR0026 "Anular"
	#define STR0027 "Procesando"
	#define STR0028 "Espere..."
	#define STR0029 "De Operadora"
	#define STR0030 "A Operadora"
	#define STR0031 "De Comprobante"
	#define STR0032 "A Comprobante"
	#define STR0033 "De Matrícula"
	#define STR0034 "A Matrícula"
	#define STR0035 "De fecha"
	#define STR0036 "A fecha"
	#define STR0037 "Parámetros - Procesa archivo de envío"
	#define STR0038 "Corrija los siguientes ítems antes de proseguir:"
	#define STR0039 "Parámetros 'De/A Operadoras' completados incorrectamente"
	#define STR0040 "Parámetros 'De/A Comprobante' completados incorrectamente"
	#define STR0041 "Parámetros 'De/A Matrículas' completados incorrectamente"
	#define STR0042 "Parámetro 'De Fecha' completado incorrectamente"
	#define STR0043 "Parámetro 'A Fecha' completado incorrectamente"
	#define STR0044 "Procesando lote:"
	#define STR0045 "Procesando de:"
	#define STR0046 "Se procesaron:"
	#define STR0047 "Formulario(s)."
	#define STR0048 "¡Registro no se no se encontró!"
	#define STR0049 "Tipo de formulario"
	#define STR0050 "Clave de formulario"
	#define STR0051 "Clave de beneficiario"
	#define STR0052 "Procedimiento"
	#define STR0053 "Crítica"
	#define STR0054 "RESUMEN DE CRÍTICAS"
	#define STR0055 "Resumen"
	#define STR0056 "RESUMEN DEL PROCESAMIENTO"
	#define STR0057 "Procesa análisis de formularios glosados"
	#define STR0058 "Esta es l a opción que efectuará la lectura de las tablas de cuentas médicas del PLS e"
	#define STR0059 "identificar los registros con valores de participación financiera en cero y que"
	#define STR0060 "se exportaron a la Operadora origen en la rutina de Gestión de avisos."
	#define STR0061 "Exportación del PTU A530 - Glosa total"
	#define STR0062 "Esta es la opción que efectuará la comunicación vía WebService y enviar el"
	#define STR0063 "PTU A530 - Glosa total."
	#define STR0064 "De Oper. Origen"
	#define STR0065 "A Oper. Origen"
	#define STR0066 "De Lote"
	#define STR0067 "A Lote"
	#define STR0068 "De Fecha de envío"
	#define STR0069 "A Fecha de envío"
	#define STR0070 "¿Procesa enviados?"
	#define STR0071 "No"
	#define STR0072 "Sí"
	#define STR0073 "Parámetros - Procesa formularios glosados"
	#define STR0074 "Corrija los siguientes ítems antes de proseguir:"
	#define STR0075 "Parámetros 'De/A Lotes' completados incorrectamente"
	#define STR0076 "Parámetro 'De Fecha de envío’ completado incorrectamente"
	#define STR0077 "Parámetro 'A Fecha de envío' completado incorrectamente"
	#define STR0078 "Procesando formularios de envío con glosa:"
	#define STR0079 "registros."
	#define STR0080 "Buscando..."
#else
	#ifdef ENGLISH
		#define STR0001 "Notices Management - Delivery"
		#define STR0002 "Pend. Notice Delivery"
		#define STR0003 "Notice Sent"
		#define STR0004 "Notice Received"
		#define STR0005 "Search"
		#define STR0006 "Detail"
		#define STR0007 "Process"
		#define STR0008 "Generate File"
		#define STR0009 "Imports Return File"
		#define STR0010 "Processes Total Disallowance"
		#define STR0011 "Export PTU A530"
		#define STR0012 "Delete"
		#define STR0013 "Batch"
		#define STR0014 "Batch Forms"
		#define STR0015 "Form Events"
		#define STR0016 "Notice Submission already processed in: "
		#define STR0017 "Do you want to process it again?"
		#define STR0018 "Attention"
		#define STR0019 "Unable to generate Notice Submission for the current status."
		#define STR0020 "Only allowed delete records with Status [1} - Pend. Notice Submission"
		#define STR0021 "Processes Submission File"
		#define STR0022 "This option reads tables of medical accounts of PLS,"
		#define STR0023 "identify and process services of eventual exchange for "
		#define STR0024 "customary beneficiaries."
		#define STR0025 "Process"
		#define STR0026 "Cancel"
		#define STR0027 "Processing"
		#define STR0028 "Wait..."
		#define STR0029 "Cooperative From"
		#define STR0030 "Cooperative To"
		#define STR0031 "Protocol From"
		#define STR0032 "Protocol To"
		#define STR0033 "Registration From"
		#define STR0034 "Registration To"
		#define STR0035 "Date from"
		#define STR0036 "Date to"
		#define STR0037 "Parameters - Processes Submission File"
		#define STR0038 "Fix the following items before continuing:"
		#define STR0039 "Parameters 'Operators Date From/To' incorrectly filled out"
		#define STR0040 "Parameters 'Protocols Date From/To' incorrectly filled out"
		#define STR0041 "Parameters 'Registrations Date From/To' incorrectly filled out"
		#define STR0042 "Parameter 'Date From' incorrectly filled out"
		#define STR0043 "Parameter 'Date To' incorrectly filled out"
		#define STR0044 "Processing Batch: "
		#define STR0045 "Processing From: "
		#define STR0046 "Processed: "
		#define STR0047 " Form(s)."
		#define STR0048 "Records not found!"
		#define STR0049 "Tab Type"
		#define STR0050 "Tab Key"
		#define STR0051 "Beneficiary Key"
		#define STR0052 "Procedure"
		#define STR0053 "Severe"
		#define STR0054 "FEEDBACK SUMMARY"
		#define STR0055 "Summary"
		#define STR0056 "PROCESSING SUMMARY"
		#define STR0057 "Processes analysis of disallowance forms"
		#define STR0058 "This option reads tables of medical accounts of PLS and"
		#define STR0059 "identify records with values of financial participation zeroed and that  "
		#define STR0060 "already exported for Origin Operator in the routine of Notices Management."
		#define STR0061 "Export of PTU A530 - Total Disallowance"
		#define STR0062 "This is the option to communicate through WebService and send "
		#define STR0063 "PTU A530 - Total Disallowance"
		#define STR0064 "Origin Oper. from"
		#define STR0065 "Origin Oper. to"
		#define STR0066 "Batch from"
		#define STR0067 "Batch to"
		#define STR0068 "Submission Date From"
		#define STR0069 "Submission Date To"
		#define STR0070 "Processes Sent?"
		#define STR0071 "No"
		#define STR0072 "Yes"
		#define STR0073 "Parameters - Processes disallowance forms"
		#define STR0074 "Fix the following items before continuing:"
		#define STR0075 "Parameters 'Batch From/To' incorrectly filled out"
		#define STR0076 "Parameter 'Submission Date From' incorrectly filled out"
		#define STR0077 "Parameter 'Submission Date From' incorrectly filled out"
		#define STR0078 "Processing Forms of Delivery with Disallowance: "
		#define STR0079 "records."
		#define STR0080 "Searching..."
	#else
		#define STR0001 "Gestão de Avisos - Envio"
		#define STR0002 "Pend. Envio Aviso"
		#define STR0003 "Aviso Enviado"
		#define STR0004 "Aviso Recebido"
		#define STR0005 "Pesquisar"
		#define STR0006 "Detalhar"
		#define STR0007 "Processar"
		#define STR0008 "Gerar Arquivo"
		#define STR0009 "Importa Arq. Retorno"
		#define STR0010 "Processa Glosa Total"
		#define STR0011 "Exportar PTU A530"
		#define STR0012 "Excluir"
		#define STR0013 "Lote"
		#define STR0014 "Guias do Lote"
		#define STR0015 "Eventos da Guia"
		#define STR0016 "O Envio de Aviso já foi processado em: "
		#define STR0017 "Deseja processar novamente?"
		#define STR0018 "Atenção"
		#define STR0019 "Não é permitido gerar Envio de Aviso para o status atual."
		#define STR0020 "Permitido apenas excluir registros com o Status [1] - Pend. Envio Aviso"
		#define STR0021 "Processa Arquivo de Envio"
		#define STR0022 "Esta é a opção que irá efetuar a leitura das tabelas de contas médicas do PLS,"
		#define STR0023 "identIficar e processar atendimentos de intercâmbio eventual realizados para "
		#define STR0024 "beneficiários habituais."
		#define STR0025 "Processar"
		#define STR0026 "Cancelar"
		#define STR0027 "Processando"
		#define STR0028 "Aguarde..."
		#define STR0029 "Operadora De"
		#define STR0030 "Operadora Ate"
		#define STR0031 "Protocolo De"
		#define STR0032 "Protocolo Até"
		#define STR0033 "Matricula De"
		#define STR0034 "Matricula Até"
		#define STR0035 "Data De"
		#define STR0036 "Data Até"
		#define STR0037 "Parâmetros - Processa Arquivo de Envio"
		#define STR0038 "Corrija os itens abaixo antes de prosseguir:"
		#define STR0039 "Parâmetros 'Operadoras De/Até' preenchidos incorretamente"
		#define STR0040 "Parâmetros 'Protocolos De/Até' preenchidos incorretamente"
		#define STR0041 "Parâmetros 'Matrículas De/Até' preenchidos incorretamente"
		#define STR0042 "Parâmetro 'Data De' preenchido incorretamente"
		#define STR0043 "Parâmetro 'Data Até' preenchido incorretamente"
		#define STR0044 "Processando Lote: "
		#define STR0045 "Processando De: "
		#define STR0046 "Foram processados: "
		#define STR0047 " Guia(s)."
		#define STR0048 "Registros não encontrado !!!"
		#define STR0049 "Tipo da Guia"
		#define STR0050 "Chave da Guia"
		#define STR0051 "Chave Beneficiário"
		#define STR0052 "Procedimento"
		#define STR0053 "Critica"
		#define STR0054 "RESUMO DE CRÍTICAS"
		#define STR0055 "Resumo"
		#define STR0056 "RESUMO DO PROCESSAMENTO"
		#define STR0057 "Processa análise de guias glosadas"
		#define STR0058 "Esta é a opção que irá efetuar a leitura das tabelas de contas médicas do PLS e"
		#define STR0059 "identificar os registros com valores de participação financeira zerados e que  "
		#define STR0060 "já foram exportados para a Operadora Origem na rotina de Gestão de Avisos."
		#define STR0061 "Exportação do PTU A530 - Glosa Total"
		#define STR0062 "Esta é a opção que irá efetuar a comunicação via WebService e enviar o "
		#define STR0063 "PTU A530 - Glosa Total."
		#define STR0064 "Oper. Origem De"
		#define STR0065 "Oper. Origem Ate"
		#define STR0066 "Lote De"
		#define STR0067 "Lote Até"
		#define STR0068 "Data Envio De"
		#define STR0069 "Data Envio Até"
		#define STR0070 "Processa Enviados?"
		#define STR0071 "Não"
		#define STR0072 "Sim"
		#define STR0073 "Parâmetros - Processa guias glosadas"
		#define STR0074 "Corrija os itens abaixo antes de prosseguir:"
		#define STR0075 "Parâmetros 'Lote De/Até' preenchidos incorretamente"
		#define STR0076 "Parâmetro 'Data Envio De' preenchido incorretamente"
		#define STR0077 "Parâmetro 'Data Envio Até' preenchido incorretamente"
		#define STR0078 "Processando Guias de Envio com Glosa: "
		#define STR0079 "registros."
		#define STR0080 "Pesquisando..."
	#endif
#endif
