#ifdef SPANISH
	#define STR0001 "Plan de Desarrollo Personal"
	#define STR0002 "Planificacion y Seguimiento de Metas"
	#define STR0003 "Actualmente Pendientes"
	#define STR0004 "Plan"
	#define STR0005 "Periodo"
	#define STR0006 "Nombre"
	#define STR0007 "Evaluador"
	#define STR0008 "Tipo de Certificacion"
	#define STR0009 "Certificacion"
	#define STR0010 "Valor"
	#define STR0011 If( cPaisLoc == "BRA", "R$", "$" )
	#define STR0012 "Duracion"
	#define STR0013 "h"
	#define STR0014 "Plazo de Realizacion"
	#define STR0015 "de"
	#define STR0016 "a"
	#define STR0017 "Relevancia"
	#define STR0018 "Descripcion"
	#define STR0019 "Limpiar"
	#define STR0020 "Grabar"
	#define STR0021 "Realizacion"
	#define STR0022 "Pendiente"
	#define STR0023 "Revisar"
	#define STR0024 "Aprobado"
	#define STR0025 "Rechazado"
	#define STR0026 "Modificar"
	#define STR0027 "Borrar"
	#define STR0028 "Aprobar"
	#define STR0029 "Reprobar"
	#define STR0030 "Volver"
	#define STR0031 "No existen items registrados"
	#define STR0032 "Seleccione un tipo de certificacion"
	#define STR0033 "Seleccione una certificacion"
	#define STR0034 "Rellene el campo valor"
	#define STR0035 "Rellene el campo duracion"
	#define STR0036 "Campo plazo inicial de conclusion invalido"
	#define STR0037 "Campo final del plazo de conclusion invalido"
	#define STR0038 "Fecha inicial debe ser menor que la fecha final"
	#define STR0039 "Digite una descripcion para el item"
	#define STR0040 "Solo se permite el borrado del item por el autor del mismo"
	#define STR0041 "Utilice la opcion Modificar"
	#define STR0042 "Alcanzado"
	#define STR0043 "Completo"
	#define STR0044 "Lider Jerarquico"
	#define STR0045 "Consejero"
	#define STR0046 "¿Está seguro de que desea APROBAR los ítems seleccionados?"
	#define STR0047 "¿Está seguro de que desea REAPROBAR los ítems seleccionados?"
	#define STR0048 "La fecha inicial debe estar comprendida entre "
	#define STR0049 " y "
	#define STR0050 "La fecha final debe estar comprendida entre "
	#define STR0051 "Leyenda"
	#define STR0052 "Obs. Evaluador"
	#define STR0053 "Anular"
	#define STR0054 "Solamente se permite la anulación del ítem por su autor"
	#define STR0055 "Por favor, digite una descripción para el ítem."
	#define STR0056 "Valor de relevancia supera el valor permitido en el archivo de Ítems de escala."
	#define STR0057 "Cantidad de metas superó la cantidad permitida."
#else
	#ifdef ENGLISH
		#define STR0001 "Personal Development plan"
		#define STR0002 "Planning and following of Goals"
		#define STR0003 "Current disputes"
		#define STR0004 "Plan"
		#define STR0005 "Period"
		#define STR0006 "Name"
		#define STR0007 "Assessor"
		#define STR0008 "Certification type"
		#define STR0009 "Certificatn."
		#define STR0010 "Value"
		#define STR0011 If( cPaisLoc == "BRA", "R$", "$" )
		#define STR0012 "Duration"
		#define STR0013 "(H)"
		#define STR0014 "Term for Conclusion"
		#define STR0015 "from"
		#define STR0016 " to"
		#define STR0017 "Relevance"
		#define STR0018 "Descriptn"
		#define STR0019 "Clear"
		#define STR0020 "Save"
		#define STR0021 "Accompl."
		#define STR0022 "Pending"
		#define STR0023 "Review"
		#define STR0024 "Approved"
		#define STR0025 "Rejected"
		#define STR0026 "Modify"
		#define STR0027 "Delete"
		#define STR0028 "Approve"
		#define STR0029 "Reject"
		#define STR0030 "Back"
		#define STR0031 "There are no registered items"
		#define STR0032 "Select a certification type"
		#define STR0033 "Select a certification"
		#define STR0034 "Fill the field amount"
		#define STR0035 "Fill the field duration"
		#define STR0036 "Field of the initial term of conclusion is invalid."
		#define STR0037 "Field of the final term of conclusion is invalid."
		#define STR0038 "Initial date must be earlier than the final one."
		#define STR0039 "Enter a description for the item"
		#define STR0040 "The deletion of the item can be performed only by its author."
		#define STR0041 "Use the Modify option"
		#define STR0042 "Reached "
		#define STR0043 "Filled in "
		#define STR0044 "Hierarchical Leader"
		#define STR0045 "Mentor"
		#define STR0046 "APPROVE the selected items anyway?"
		#define STR0047 "REJECT the selected items anyway?"
		#define STR0048 "Initial date must be between "
		#define STR0049 " and "
		#define STR0050 "The end date must be between "
		#define STR0051 "Caption"
		#define STR0052 "Evaluator Note"
		#define STR0053 "Cancel"
		#define STR0054 "You can only cancel an item by its author."
		#define STR0055 "Please, enter item description."
		#define STR0056 "Relevance value surpasses the value allowed in Schedule Items register"
		#define STR0057 "Quantity of Goals surpasses the allowed quantity."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Plano De Desenvolvimento Pessoal", "Plano de Desenvolvimento Pessoal" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Planeamento E Acompanhamento De Metas", "Planejamento e Acompanhamento de Metas" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Pendências actuais", "Pendências Atuais" )
		#define STR0004 "Plano"
		#define STR0005 "Período"
		#define STR0006 "Nome"
		#define STR0007 "Avaliador"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Tipo de certificação", "Tipo de Certificação" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Certificado", "Certificação" )
		#define STR0010 "Valor"
		#define STR0011 If( cPaisLoc == "BRA", "R$", "$" )
		#define STR0012 "Duração"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "H", "h" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Prazo de realização", "Prazo de Realização" )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "De", "de" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Actu", "até" )
		#define STR0017 "Relevância"
		#define STR0018 "Descrição"
		#define STR0019 "Limpar"
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Guardar", "Salvar" )
		#define STR0021 "Realização"
		#define STR0022 "Pendente"
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Rever", "Revisar" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Autorizado", "Aprovado" )
		#define STR0025 "Rejeitado"
		#define STR0026 "Alterar"
		#define STR0027 "Excluir"
		#define STR0028 "Aprovar"
		#define STR0029 "Reprovar"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Voltar atrás", "Voltar" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Não existem itens registados", "Não existem itens cadastrados" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Seleccione um tipo de certificação", "Selecione um tipo de certificação" )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Seleccione uma certificação", "Selecione uma certificação" )
		#define STR0034 "Preencha o campo valor"
		#define STR0035 "Preencha o campo duração"
		#define STR0036 "Campo prazo inicial de conclusão inválido"
		#define STR0037 "Campo final do prazo de conclusão inválido"
		#define STR0038 "Data inicial deve ser menor que a data final"
		#define STR0039 "Digite uma descrição para o item"
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Só é permitida a eliminação do item pelo autor do mesmo", "Só é permitida a exclusão do item pelo autor do mesmo" )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Utilizar a opção modificar", "Utilizar a opção Modificar" )
		#define STR0042 "Atingido"
		#define STR0043 "Preenchido"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Lider hierárquico", "Líder Hierárquico" )
		#define STR0045 "Mentor"
		#define STR0046 "Tem certeza que deseja APROVAR os itens selecionados?"
		#define STR0047 "Tem certeza que deseja REPROVAR os itens selecionados?"
		#define STR0048 "A data inicial deve estar compreendida entre "
		#define STR0049 " e "
		#define STR0050 "A data final deve estar compreendida entre "
		#define STR0051 "Legenda"
		#define STR0052 "Obs. Avaliador"
		#define STR0053 "Cancelar"
		#define STR0054 "Só é permitido o cancelamento do item pelo autor do mesmo."
		#define STR0055 "Favor digitar uma descrição para o item."
		#define STR0056 "Valor de Relevância ultrapassa o valor permitido no cadastro de Itens de Escala."
		#define STR0057 "Quantidade de Metas ultrapassou a quantidade permitida."
	#endif
#endif
