#ifdef SPANISH
	#define STR0001 "Установить дату поставки"
	#define STR0002 "Заказ № "
	#define STR0003 "Клиент "
	#define STR0004 "Подразделение "
	#define STR0005 "OK"
	#define STR0006 "Заполните данные заголовка"
	#define STR0007 "Список накладных"
	#define STR0008 "Обновление таблицы документа "
	#define STR0009 "Выберите оригинальный документ"
	#define STR0010 "Ни одного оригинального документа не найдено"
	#define STR0011 "Изменение даты накладной"
	#define STR0012 "Желаете пересчитать по курсу от новой даты?"
	#define STR0013 "Дата документа не может быть больше даты накладной"
	#define STR0014 "Модель "
	#define STR0015 " не "
	#define STR0016 " является объектом."
	#define STR0017 " активирована."
	#define STR0018 "Изменяемые поля:"
	#define STR0019 "На этом шаге необходимо выбрать поля, которые будут массово изменяться в документе."
	#define STR0020 "Фильтр:"
	#define STR0021 "На этом шаге можно добавить фильтр, чтобы отобрать нужные поля для изменения. Шаг является не обязательным к заполнению."
	#define STR0022 "Группировка:"
	#define STR0023 "На этом шаге мы создаем группировку полей для изменения выбранной информации. Группировка интерфейсно отображает значения выбранных полей, для детальной выборки."
	#define STR0024 "Изменение:"
	#define STR0025 "На этом шаге мы изменяем поля на новые значения."
	#define STR0026 "Итоги:"
	#define STR0027 "На этом шаге система показывает нам все параметры выбора и будущих изменений."
	#define STR0028 "Вы подтверждаете обновление данных согласно сводной таблицы?"
	#define STR0029 "Внимание"
	#define STR0030 "Поля для изменения"
	#define STR0031 "Поиск"
	#define STR0032 "Фильтр"
	#define STR0033 "Поле группировки"
	#define STR0034 "Сводка"
	#define STR0035 "Группировка"
	#define STR0036 "Подготовка данных..."
	#define STR0037 "Подготовка обновления"
	#define STR0038 "ЗАКЛЮЧЕНИЕ: В каталоге STARTPATH создана копия данных, отображаемых на экране, файл "
	#define STR0039 "Отсутствует"
	#define STR0040 "СТАТУС: Обновление не выполнено, так как шаги 4/5 не содержат изменений."
	#define STR0041 "Ошибка обновления"
	#define STR0042 "Обновление..."
	#define STR0043 "Не найдены записи для последующих обновлений. Проверьте конфигурации в предыдущих окнах мастера процедуры."
	#define STR0044 "Проверьте сводку, выбрав одну из опций слева."
	#define STR0045 "Были выбраны следующие поля для изменения: "
	#define STR0046 " (обозреватель шагов 4/5) будут сохранены в таблице "
	#define STR0047 " (поля "
	#define STR0048 " ), подтверждая измененение данного процесса."
	#define STR0049 "В мастере настройки был выбран фильтр, указывающий что только поля из таблицы '"
	#define STR0050 "' соответствующие условию '"
	#define STR0051 "' должны быть обновлены во время работы программы."
	#define STR0052 "Для группировки использовались следующие поля: "
	#define STR0053 "' по '"
	#define STR0054 "(Новый)"
	#define STR0055 "(Старый)"
	#define STR0056 "' эта группа учитывается при обновлении. В ней хранятся изменённые на предыдущем шаге (4/5) данные и обновляются в соответствии с указанной группой."
	#define STR0057 "Для изменения склада и адреса хранения, необходимо установить флажки на поля, которые будут изменяться в документе поступления. Обязательным условием изменения адреса хранения, пользователь должен установить флажок напротив поля склада, поскольку адрес хранения привязан к складу."
	#define STR0058 "При выборе фильтра для массового изменения, пользователь может отобрать нужные ему материалы или другие характеристики, которые будут выборочно изменяться. Настраивается фильтр по признаку, впоследствии массовое изменение применяется только для строк, которые указаны в фильтре."
	#define STR0059 "При выборе полей группировки, пользователь ограничивает итоговые результаты по массовому изменению. Поля группируются в том случае, если используется фильтр из предыдущего окна. Значения из фильтра группируются по другим полям системы и отображаются в следующем окне. В случает отсутствия фильтра и потребности группировки, нажмите кнопку «Дальше»."
	#define STR0060 "Выберите код склада, куда выполняется приемка товара, после этого выберите адрес хранения (спецификация), куда будут размещаться материалы."
	#define STR0061 "Это окно отображает итоги всех предыдущих шагов, какие поля мы использовали, фильтры и группировки. Окно является ознакомительным, если вы уверены в своих данных, нажмите 'Завершить', после чего система приступит к массовому изменению."
	#define STR0062 "Из-за проблем с валидацией следующая строка не была обновлена: "
	#define STR0063 "Массовое изменение"
	#define STR0064 "Массовое изменение – адресация материалов."
	#define STR0065 "Этот инструмент предназначен для массового изменения полей в таблицах документа. Инструмент позволяет быстро заполнить поля по всем строкам документа, согласно критериям выбора."
	#define STR0066 "Выбор"
	#define STR0067 "Поле"
	#define STR0068 "Описание"
	#define STR0069 "Отсутствуют объекты для редактирования."
	#define STR0070 "Все строки были успешно обновлены."
	#define STR0071 "Позиция "
	#define STR0072 "Проверка изменений"
	#define STR0073 "Cвязанных авансов не найдено"
	#define STR0074 "Авансовые платежи"
	#define STR0075 "Дата:"
	#define STR0076 "Накладная"
	#define STR0077 "Выбранные значения"
	#define STR0078 "Текущий курс"
	#define STR0079 "Проверка выбранных записей..."
	#define STR0080 "Группировка элементов..."
#else
	#ifdef ENGLISH
		#define STR0001 "Set Delivery Date"
		#define STR0002 "Order № "
		#define STR0003 "Client "
		#define STR0004 "Branch"
		#define STR0005 "OK"
		#define STR0006 "Please complete the headingґs data"
		#define STR0007 "Invoices"
		#define STR0008 "Updating item "
		#define STR0009 "Select Original Document"
		#define STR0010 "No Original Documents found"
		#define STR0011 "Invoice date was changed"
		#define STR0012 "Would you like to recalculate rate values?"
		#define STR0013 "Date of document which was included could not be greater than Invoice date"
		#define STR0014 "Model is "
		#define STR0015 " not "
		#define STR0016 " an object."
		#define STR0017 " activated."
		#define STR0018 "Fields to be modified..."
		#define STR0019 "1/6 - In this step you must select the fields to be modified in the respective register"
		#define STR0020 "Filter..."
		#define STR0021 "2/5 - In this step we can enter a filter in order to restrain changes in file."
		#define STR0022 "Group..."
		#define STR0023 "3/5 - In this step we created a group to edit the selected information."
		#define STR0024 "Editing: "
		#define STR0025 "In this step, we are changing the fields to new values."
		#define STR0026 "Summary: "
		#define STR0027 "At this step, the system shows us all the options for selection and future changes."
		#define STR0028 "Do you confirm updating the data according to the summary table?"
		#define STR0029 "Attention"
		#define STR0030 "Fields to be edited"
		#define STR0031 "Search"
		#define STR0032 "Filter"
		#define STR0033 "Grouping field"
		#define STR0034 "Resume"
		#define STR0035 "Group"
		#define STR0036 "Prepare data ..."
		#define STR0037 "Processing update"
		#define STR0038 "CONCLUSION: A copy of content displayed in screen of system directory STARTPATH was created, file "
		#define STR0039 "None"
		#define STR0040 "STATUS: Update NOT made because there was NO change in board 4/5 edition."
		#define STR0041 "Problem With Update"
		#define STR0042 "Update ..."
		#define STR0043 "No records found for later updates. Check the configurations provided in the previous frames of the routine wizard."
		#define STR0044 "Check the summary by clicking one of the options on the left."
		#define STR0045 "The following fields have been selected to change: "
		#define STR0046 "(frame 4/5 browser) will be recorded on table"
		#define STR0047 " (fields "
		#define STR0048 " ), confirming the modification of this process."
		#define STR0049 "A filter was selected in the routine wizard and identified that only the records in table '"
		#define STR0050 "' meeting the condition '"
		#define STR0051 "' must be updated when processing the routine."
		#define STR0052 "The following fields were used for grouping: "
		#define STR0053 "' by '"
		#define STR0054 "(New)"
		#define STR0055 " (Old)"
		#define STR0056 "  this group is respected when update takes place, where the data edited in previous frame (4/5) are kept and updated according to the group displayed."
		#define STR0057 "To change the warehouse and storage address, you must select the check boxes for the fields that will change in the receipt document. A prerequisite for changing the storage address is the user must check the box opposite the warehouse field, since the storage address is tied to the warehouse."
		#define STR0058 "When choosing a filter for mass change, the user can select the materials he needs or other characteristics that will be selectively changed. A filter is configured by attribute, subsequently the mass change is applied only for the rows that are specified in the filter."
		#define STR0059 "When selecting the grouping fields, the user limits the total results by mass change. The fields are grouped if the filter from the previous window is used. The values from the filter are grouped by other system fields and displayed in the next window. If there is no filter and grouping needs, click the 'Next' button."
		#define STR0060 "Select the code of the warehouse where the goods are received, then select the storage address (specification) where the materials will be placed."
		#define STR0061 "This window displays a summary of all the previous steps, what fields we used, filters and groupings. The window is for informational purposes, if you are sure of your data, click 'Finish', and then the system will start the bulk change."
		#define STR0062 "Due to validation issues, the following line has not been updated: "
		#define STR0063 "Facilitator"
		#define STR0064 "cMsg"
		#define STR0065 "This technical staff enables simplified maintenance of registration information of certain tables, according to criteria defined in execution of routine wizard."
		#define STR0066 "Selection"
		#define STR0067 "Field"
		#define STR0068 "Description"
		#define STR0069 "There are no items to be edited"
		#define STR0070 "All lines were updated suscefuly"
		#define STR0071 "Item "
		#define STR0072 "Changes validation"
		#define STR0073 "Prepayments are not found"
		#define STR0074 "Prepayment Visualization"
		#define STR0075 "Date:"
		#define STR0076 "Invoice"
		#define STR0077 "Selected Values"
		#define STR0078 "Standard Exchange rate"
		#define STR0079 "Checking selected records..."
		#define STR0080 "Grouping items..."
	#else
		#define STR0001 "Установить дату поставки"
		#define STR0002 "Заказ № "
		#define STR0003 "Клиент "
		#define STR0004 "Подразделение "
		#define STR0005 "OK"
		#define STR0006 "Заполните данные заголовка"
		#define STR0007 "Список накладных"
		#define STR0008 "Обновление таблицы документа "
		#define STR0009 "Выберите оригинальный документ"
		#define STR0010 "Ни одного оригинального документа не найдено"
		#define STR0011 "Изменение даты накладной"
		#define STR0012 "Желаете пересчитать по курсу от новой даты?"
		#define STR0013 "Дата документа не может быть больше даты накладной"
		#define STR0014 "Модель "
		#define STR0015 " не "
		#define STR0016 " является объектом."
		#define STR0017 " активирована."
		#define STR0018 "Изменяемые поля:"
		#define STR0019 "На этом шаге необходимо выбрать поля, которые будут массово изменяться в документе."
		#define STR0020 "Фильтр:"
		#define STR0021 "На этом шаге можно добавить фильтр, чтобы отобрать нужные поля для изменения. Шаг является не обязательным к заполнению."
		#define STR0022 "Группировка:"
		#define STR0023 "На этом шаге мы создаем группировку полей для изменения выбранной информации. Группировка интерфейсно отображает значения выбранных полей, для детальной выборки."
		#define STR0024 "Изменение:"
		#define STR0025 "На этом шаге мы изменяем поля на новые значения."
		#define STR0026 "Итоги:"
		#define STR0027 "На этом шаге система показывает нам все параметры выбора и будущих изменений."
		#define STR0028 "Вы подтверждаете обновление данных согласно сводной таблицы?"
		#define STR0029 "Внимание"
		#define STR0030 "Поля для изменения"
		#define STR0031 "Поиск"
		#define STR0032 "Фильтр"
		#define STR0033 "Поле группировки"
		#define STR0034 "Сводка"
		#define STR0035 "Группировка"
		#define STR0036 "Подготовка данных..."
		#define STR0037 "Подготовка обновления"
		#define STR0038 "ЗАКЛЮЧЕНИЕ: В каталоге STARTPATH создана копия данных, отображаемых на экране, файл "
		#define STR0039 "Отсутствует"
		#define STR0040 "СТАТУС: Обновление не выполнено, так как шаги 4/5 не содержат изменений."
		#define STR0041 "Ошибка обновления"
		#define STR0042 "Обновление..."
		#define STR0043 "Не найдены записи для последующих обновлений. Проверьте конфигурации в предыдущих окнах мастера процедуры."
		#define STR0044 "Проверьте сводку, выбрав одну из опций слева."
		#define STR0045 "Были выбраны следующие поля для изменения: "
		#define STR0046 " (обозреватель шагов 4/5) будут сохранены в таблице "
		#define STR0047 " (поля "
		#define STR0048 " ), подтверждая измененение данного процесса."
		#define STR0049 "В мастере настройки был выбран фильтр, указывающий что только поля из таблицы '"
		#define STR0050 "' соответствующие условию '"
		#define STR0051 "' должны быть обновлены во время работы программы."
		#define STR0052 "Для группировки использовались следующие поля: "
		#define STR0053 "' по '"
		#define STR0054 "(Новый)"
		#define STR0055 "(Старый)"
		#define STR0056 "' эта группа учитывается при обновлении. В ней хранятся изменённые на предыдущем шаге (4/5) данные и обновляются в соответствии с указанной группой."
		#define STR0057 "Для изменения склада и адреса хранения, необходимо установить флажки на поля, которые будут изменяться в документе поступления. Обязательным условием изменения адреса хранения, пользователь должен установить флажок напротив поля склада, поскольку адрес хранения привязан к складу."
		#define STR0058 "При выборе фильтра для массового изменения, пользователь может отобрать нужные ему материалы или другие характеристики, которые будут выборочно изменяться. Настраивается фильтр по признаку, впоследствии массовое изменение применяется только для строк, которые указаны в фильтре."
		#define STR0059 "При выборе полей группировки, пользователь ограничивает итоговые результаты по массовому изменению. Поля группируются в том случае, если используется фильтр из предыдущего окна. Значения из фильтра группируются по другим полям системы и отображаются в следующем окне. В случает отсутствия фильтра и потребности группировки, нажмите кнопку «Дальше»."
		#define STR0060 "Выберите код склада, куда выполняется приемка товара, после этого выберите адрес хранения (спецификация), куда будут размещаться материалы."
		#define STR0061 "Это окно отображает итоги всех предыдущих шагов, какие поля мы использовали, фильтры и группировки. Окно является ознакомительным, если вы уверены в своих данных, нажмите 'Завершить', после чего система приступит к массовому изменению."
		#define STR0062 "Из-за проблем с валидацией следующая строка не была обновлена: "
		#define STR0063 "Массовое изменение"
		#define STR0064 "Массовое изменение – адресация материалов."
		#define STR0065 "Этот инструмент предназначен для массового изменения полей в таблицах документа. Инструмент позволяет быстро заполнить поля по всем строкам документа, согласно критериям выбора."
		#define STR0066 "Выбор"
		#define STR0067 "Поле"
		#define STR0068 "Описание"
		#define STR0069 "Отсутствуют объекты для редактирования."
		#define STR0070 "Все строки были успешно обновлены."
		#define STR0071 "Позиция "
		#define STR0072 "Проверка изменений"
		#define STR0073 "Cвязанных авансов не найдено"
		#define STR0074 "Авансовые платежи"
		#define STR0075 "Дата:"
		#define STR0076 "Накладная"
		#define STR0077 "Выбранные значения"
		#define STR0078 "Текущий курс"
		#define STR0079 "Проверка выбранных записей..."
		#define STR0080 "Группировка элементов..."
	#endif
#endif
