#ifdef SPANISH
	#define STR0001 "Disposición final de residuos"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Borrar"
	#define STR0005 "No se pudo anular la opción."
	#define STR0006 "Datos de las ocurrencias"
	#define STR0007 "Disponibles"
	#define STR0008 "Seleccionadas"
	#define STR0009 "Informe a continuación las cantidades del residuo que se retirarán de cada almacén."
	#define STR0010 "Atención"
	#define STR0011 "El peso informado para la(s) ocurrencia(s) diverge(n) del peso utilizado en la composición de la carga."
	#define STR0012 "Para la ocurrencia "
	#define STR0013 " se informó en el total - "
	#define STR0014 ", debería haberse informado - "
	#define STR0015 "Informe valores válidos."
	#define STR0016 "El residuo presente en esta ocurrencia no tiene este tipo de destinación."
	#define STR0017 "Seleccione otro acontecimiento o vincule el tipo de destinación al residuo."
	#define STR0018 "Formulario del registro"
	#define STR0019 "Archivo"
	#define STR0020 "Código"
	#define STR0021 "Descripción"
	#define STR0022 "Unidad de medida"
	#define STR0023 "Cantidad disponible"
	#define STR0024 "Cantidad seleccionada"
	#define STR0025 "Totalizador"
	#define STR0026 "Totalizador de residuos de la disposición final"
	#define STR0027 "¡Esta funcionalidad estará disponible solamente a partir de la release 12.1.23!"
	#define STR0028 "Atención"
#else
	#ifdef ENGLISH
		#define STR0001 "Final Disposition of Residues"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Delete"
		#define STR0005 "Unable to cancel option."
		#define STR0006 "Occurrences Data"
		#define STR0007 "Available"
		#define STR0008 "Selected"
		#define STR0009 "Complete below the amount of residue to be collected from each Warehouse."
		#define STR0010 "Attention"
		#define STR0011 "The weight informed for the occurrence(s) differ from the weight used in the composition of load."
		#define STR0012 "For occurrence "
		#define STR0013 " informed in total "
		#define STR0014 ", must have been informed - "
		#define STR0015 "Enter valid values."
		#define STR0016 "Residue in this occurrence does not have this type of destination."
		#define STR0017 "Select other occurrence or bind the residue destination type."
		#define STR0018 "Form of Registration "
		#define STR0019 "Register "
		#define STR0020 "Code"
		#define STR0021 "Description"
		#define STR0022 "Unit of Measurement."
		#define STR0023 "Available quantity"
		#define STR0024 "Selected Quantity"
		#define STR0025 "Totalizer"
		#define STR0026 "Total of residues of final disposition"
		#define STR0027 "This functionality is available from release 12.1.23!"
		#define STR0028 "Attention"
	#else
		#define STR0001 "Disposição Final de Resíduos"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Excluir"
		#define STR0005 "Não é possível cancelar a opção."
		#define STR0006 "Dados das Ocorrencias"
		#define STR0007 "Disponíveis"
		#define STR0008 "Selecionadas"
		#define STR0009 "Preencha abaixo as quantidades do resíduo que serão retiradas de cada Armazém."
		#define STR0010 "Atenção"
		#define STR0011 "O peso informado para a(s) ocorrência(s) difere(m) do peso utilizado na composição da carga."
		#define STR0012 "Para a ocorrência "
		#define STR0013 " foi informado no total - "
		#define STR0014 ", deveria ter sido informado - "
		#define STR0015 "Informe valores válidos."
		#define STR0016 "O resíduo presente nesta ocorrência não possui este tipo de destinação."
		#define STR0017 "Selecione outra ocorrência ou vincule o tipo de destinação ao resíduo."
		#define STR0018 "Formulário do Cadastro "
		#define STR0019 "Cadastro "
		#define STR0020 "Codigo"
		#define STR0021 "Descrição"
		#define STR0022 "Unidade de Medida"
		#define STR0023 "Quantidade Disponível"
		#define STR0024 "Quantidade Selecionada"
		#define STR0025 "Totalizador"
		#define STR0026 "Totalizador de resíduos da disposição final"
		#define STR0027 "Esta funcionalidade estará disponível somente a partir da release 12.1.23!"
		#define STR0028 "Atenção"
	#endif
#endif
