#ifdef SPANISH
	#define STR0001 "Informe de las Legislaciones registradas en el sistema."
	#define STR0002 "El usuario puede utilizar la opción Parámetros para la obtención "
	#define STR0003 "de las legislaciones de su interés."
	#define STR0004 "A Rayas"
	#define STR0005 "Administración"
	#define STR0006 "Archivo de requisitos"
	#define STR0007 "ANULADO POR EL OPERADOR"
	#define STR0008 "Federal"
	#define STR0009 "Provincial"
	#define STR0010 "Municipal"
	#define STR0011 "Accionistas"
	#define STR0012 "Comunidad"
	#define STR0013 "Otros"
	#define STR0014 "Requisito..:"
	#define STR0015 "Tipo......: "
	#define STR0016 "Fch. Emisión: "
	#define STR0017 "Fch. Publicación: "
	#define STR0018 "Cod. Resol.: "
	#define STR0019 "Nº Resolución: "
	#define STR0020 "Origen: "
	#define STR0021 "Enlace Relac.: "
	#define STR0022 "Descripción: "
#else
	#ifdef ENGLISH
		#define STR0001 "Legislation report registered in the system."
		#define STR0002 "You can use option Parameters to obtain "
		#define STR0003 "of legislation of your interest."
		#define STR0004 "Z.form "
		#define STR0005 "Administration"
		#define STR0006 "Requirements Registration"
		#define STR0007 "CANCELLED BY OPERATOR  "
		#define STR0008 "Federal"
		#define STR0009 "State   "
		#define STR0010 "Municipal"
		#define STR0011 "Shareholders"
		#define STR0012 "Comunity  "
		#define STR0013 "Other "
		#define STR0014 "Requirement..:"
		#define STR0015 "Type......: "
		#define STR0016 "Dt. Issue: "
		#define STR0017 "Dt. Publication: "
		#define STR0018 "Resol. Cod.: "
		#define STR0019 "Resolution no.: "
		#define STR0020 "Origin: "
		#define STR0021 "Link Relat.: "
		#define STR0022 "Description: "
	#else
		#define STR0001 "Relatório das Legislações cadastradas no sistema."
		#define STR0002 "O usuário poderá utilizar a opcao Parâmetros para a obtenção "
		#define STR0003 "das Legislações de seu interesse."
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0005 "Administração"
		#define STR0006 "Cadastro de Requisitos"
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Cancelado Pelo Operador", "CANCELADO PELO OPERADOR" )
		#define STR0008 "Federal"
		#define STR0009 "Estadual"
		#define STR0010 "Municipal"
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Accionistas", "Acionistas" )
		#define STR0012 "Comunidade"
		#define STR0013 "Outros"
		#define STR0014 "Requisito..:"
		#define STR0015 "Tipo......: "
		#define STR0016 "Dt. Emissão: "
		#define STR0017 "Dt. Publicação: "
		#define STR0018 "Cod. Resol.: "
		#define STR0019 "Num. Resolução: "
		#define STR0020 "Origem: "
		#define STR0021 "Link Relac.: "
		#define STR0022 "Descrição.: "
	#endif
#endif
