#ifdef SPANISH
	#define STR0001 "Falla en la obtencion del comprobante"
	#define STR0002 "Atencion, No fue posible registrar Retiro parcial de caja/Cambio en ECF. Operacion no efectuada."
	#define STR0020 "Salida de caja"
	#define STR0030 "RETIRO DE CAJA"
	#define STR0031 "ENTRADA DE VUELTO"
	#define STR0032 "COBRANZAS"
	#define STR0033 "CORRESPONDIENTES BANCARIOS"
	#define STR0034 "RECARGA DE CELULAR"
	#define STR0035 "As. Caj   :"
	#define STR0036 "As. Superior:"
	#define STR0037 "Suministro de caja"
	#define STR0038 "CIERRE DE CAJA"
	#define STR0039 "CJ.DESTINO"
	#define STR0040 "CJ.ORIGEN"
	#define STR0041 "ESTACION"
	#define STR0042 "NUM.MOV."
	#define STR0043 "RETIRADAS"
	#define STR0044 "(Acumulado)"
	#define STR0045 "VALOR        : R$ "
	#define STR0046 "FECHA         : "
	#define STR0047 "CAJA        : "
	#define STR0048 "PDV          : "
#else
	#ifdef ENGLISH
		#define STR0001 "Failed to get the receipt!"
		#define STR0002 "Attention. Cash Partial Withdrawal/Change could not be registered in ECF. Operation not executed."
		#define STR0020 "Cash Outflow"
		#define STR0030 "EXCESS CASH TRANSFER"
		#define STR0031 "CHANGE ENTRY"
		#define STR0032 "RECEIPTS"
		#define STR0033 "CORRESPONDENT BANKING"
		#define STR0034 "CELL PHONE RECHARGE"
		#define STR0035 "Cash Signature:"
		#define STR0036 "Higher Signature:"
		#define STR0037 "Cash supply"
		#define STR0038 "CASH CLOSING"
		#define STR0039 "CASH DESTINATION"
		#define STR0040 "CASH ORIGIN"
		#define STR0041 "STATION"
		#define STR0042 "TRANSAC.NUM."
		#define STR0043 "WITHDRAWALS"
		#define STR0044 "(Accrued)"
		#define STR0045 "VALUE        : R$ "
		#define STR0046 "DATE: "
		#define STR0047 "CASH: "
		#define STR0048 "PDV: "
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Falha na obtenção do cupão", "Falha na obtenção do cupom" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Atenção, não foi possível registar Sangria/Troco no ECF. Operação não efectuada.", "Atencao, Nao foi possivel registrar Sangria/Troco no ECF. Operacao nao efetuada." )
		#define STR0020 "Saida de Caixa"
		#define STR0030 "SANGRIA"
		#define STR0031 "ENTRADA DE TROCO"
		#define STR0032 "RECEBIMENTOS"
		#define STR0033 "CORRESPONDENTES BANCARIOS"
		#define STR0034 "RECARGA DE CELULAR"
		#define STR0035 "Ass. Caixa   :"
		#define STR0036 "Ass. Superior:"
		#define STR0037 "Suprimento de caixa"
		#define STR0038 "FECHAMENTO DE CAIXA"
		#define STR0039 "CX.DESTINO"
		#define STR0040 "CX.ORIGEM"
		#define STR0041 "ESTACAO"
		#define STR0042 "NUM.MOV."
		#define STR0043 "RETIRADAS"
		#define STR0044 "(Acumulado)"
		#define STR0045 "VALOR        : R$ "
		#define STR0046 "DATA         : "
		#define STR0047 "CAIXA        : "
		#define STR0048 "PDV          : "
	#endif
#endif
