#ifdef SPANISH
	#define STR0001 "Valor inválido"
	#define STR0002 "Parámetro no encontrado"
	#define STR0003 "Configuraciones de parámetros"
	#define STR0004 "Grabar"
	#define STR0005 "Configuraciones"
	#define STR0006 "Configuraciones grabadas"
	#define STR0007 "Error al incluir información en el parámetro"
	#define STR0008 "Salir"
	#define STR0009 "Digite el nombre del parámetro"
	#define STR0010 "Valor del parámetro"
	#define STR0011 "Descripción del parámetro"
#else
	#ifdef ENGLISH
		#define STR0001 "Invalid value"
		#define STR0002 "Parameter not found"
		#define STR0003 "Parameter Configurations"
		#define STR0004 "Save"
		#define STR0005 "Configurations"
		#define STR0006 "Saved Configurations"
		#define STR0007 "Error adding information to parameter"
		#define STR0008 "Exit"
		#define STR0009 "Enter parameter name"
		#define STR0010 "Parameter value"
		#define STR0011 "Parameter description"
	#else
		#define STR0001 "Valor Inválido"
		#define STR0002 "Parâmetro não encontrado"
		#define STR0003 "Configurações de Parâmetros"
		#define STR0004 "Salvar"
		#define STR0005 "Configurações"
		#define STR0006 "Configurações Salvas"
		#define STR0007 "Erro ao inserir informações no parâmetro"
		#define STR0008 "Sair"
		#define STR0009 "Digite o nome do parâmetro"
		#define STR0010 "Valor do parâmetro"
		#define STR0011 "Descrição do parâmetro"
	#endif
#endif
