#ifdef SPANISH
	#define STR0001 "Nivel "
	#define STR0002 "Empresa"
	#define STR0003 "Unidad de negocio"
	#define STR0004 "Sucursal"
	#define STR0005 "Atención, El uso compartido de las tablas deben ser iguales."
	#define STR0006 "¡Atención!"
	#define STR0007 "Por favor, cree el campo LI_SEQ, carácter de 9 posiciones."
	#define STR0008 "A continuación, "
	#define STR0009 "Por favor, en la tabla SIX, modifique el contenido de la orden 1 del índice en SLI: LI_FILIAL+LI_ESTACAO+LI_TIPO+LI_SEQ"
	#define STR0010 "Por favor, en la tabla SX2, modifique el campo X2_UNICO de la clave SLI a: LI_FILIAL+LI_ESTACAO+LI_TIPO+LI_SEQ"
#else
	#ifdef ENGLISH
		#define STR0001 "Level "
		#define STR0002 "Company"
		#define STR0003 "Business Unit"
		#define STR0004 "Branch"
		#define STR0005 "Attention. Table sharing must be the same."
		#define STR0006 "Attention!"
		#define STR0007 "Please create LI_SEQ field, character of 9 positions."
		#define STR0008 "Then, "
		#define STR0009 "Please edit, in SIX table, the content of the order 1 of index in SLI: LI_FILIAL+LI_ESTACAO+LI_TIPO+LI_SEQ"
		#define STR0010 "Please edit, in SX2 table, field X2_UNICO of SLI key for: LI_FILIAL+LI_ESTACAO+LI_TIPO+LI_SEQ"
	#else
		#define STR0001 "Nível "
		#define STR0002 "Empresa"
		#define STR0003 "Unidade de Negócio"
		#define STR0004 "Filial"
		#define STR0005 "Atenção, O compartilhamento das tabelas devem ser iguais."
		#define STR0006 "Atenção!"
		#define STR0007 "Favor criar o campo LI_SEQ, caracter de 9 posições."
		#define STR0008 "Em seguida, "
		#define STR0009 "Favor alterar, na tabela SIX, o conteúdo da ordem 1 do índice em SLI: LI_FILIAL+LI_ESTACAO+LI_TIPO+LI_SEQ"
		#define STR0010 "Favor alterar, na tabela SX2, campo X2_UNICO da chave SLI para: LI_FILIAL+LI_ESTACAO+LI_TIPO+LI_SEQ"
	#endif
#endif
