#ifdef SPANISH
	#define STR0001 "De-A de Empresa y Sucursal no encontrado en la base para CompanyId '"
	#define STR0002 "' e BranchId '"
	#define STR0003 "Parámetro '"
	#define STR0004 "' es obligatorio y no se informó."
	#define STR0005 "Campo 'C7_APROPRM' no existe en el diccionario de datos, en la tabla 'SX3'."
	#define STR0006 "Tarea inicial '"
	#define STR0007 "' no encontrada en De/A."
	#define STR0008 "Tarea inicial '"
	#define STR0009 "Servicio genérico de devolución de movimientos de atribución de gastos con base en el concepto de Proyecto/Tarea de Microsiga Protheus."
	#define STR0010 "Ejemplo de devolución de ente(s)"
	#define STR0011 "WSRECEIVE: Falla al buscar la base de datos del cliente."
	#define STR0012 "WSRECEIVE: Falla al elaborar la devolución del mensaje JSON."
	#define STR0013 "fValField: Falla al abrir tablas del diccionario de datos."
	#define STR0014 "fValidMoviment: ¡Falla al validar parámetros del movimiento!"
	#define STR0015 "fEAIReceb: ¡Falla al validar parámetros del movimiento!"
	#define STR0016 "fConDate: ¡Falla al buscar la fecha de cierre del período!"
	#define STR0017 "fReadSQL: ¡Falla al buscar datos de atribución!"
	#define STR0018 "fClose: ¡Falla al cerrar la tabla de consulta!"
	#define STR0019 "¡Error al consultar Atribuciones de gastos! Error:"
	#define STR0020 "¡La consulta por Creación no es posible en el ente Cuentas por pagar!"
	#define STR0021 "¡La consulta por Registro no es posible en el ente Cuentas por pagar!"
	#define STR0022 "¡La consulta por esta información no está implementada en el ente Cuentas por pagar!"
	#define STR0023 "¡La consulta por Vencimiento no es posible en el ente Factura de entrada!"
	#define STR0024 "¡La consulta por Vencimiento real no es posible en el ente Factura de entrada!"
	#define STR0025 "¡La consulta por Registro no es posible en el ente Factura de entrada!"
	#define STR0026 "¡La consulta por esta información no está implementada en el ente Factura de entrada!"
	#define STR0027 "¡La consulta por Creación no es posible en el ente Baja de requisición!"
	#define STR0028 "¡La consulta por Vencimiento no es posible en el ente Baja de requisición!"
	#define STR0029 "¡La consulta por Vencimiento real no es posible en el ente Baja de requisición!"
	#define STR0030 "¡La consulta por esta información no está implementada en el ente Baja de requisición!"
#else
	#ifdef ENGLISH
		#define STR0001 "From-To of Company and Branch not found in the base for Companyld '"
		#define STR0002 "' and BranchId '"
		#define STR0003 "Parameter '"
		#define STR0004 "' is mandatory and was not informed!"
		#define STR0005 "Field 'C7_APROPRM' not exist int he data dictionary in the table 'SX3'."
		#define STR0006 "Initial task '"
		#define STR0007 "' not found in From/To!"
		#define STR0008 "Initial task '"
		#define STR0009 "Generic service of return of appropriation movement of expenses based on the concept of Project/Task of Microsiga Protheus."
		#define STR0010 "Example of entity(ies) return"
		#define STR0011 "WSRECEIVE: Failure searching database of customer!"
		#define STR0012 "WSRECEIVE: Failure assembling the JSON message return!"
		#define STR0013 "fValField: Failure opening tables of Data Dictionary!"
		#define STR0014 "fValidMoviment: Failure validating parameters of movement!"
		#define STR0015 "fEAIReceb: Failure validating parameters of movement!"
		#define STR0016 "fConDate: Failure searching Period Closing Date!"
		#define STR0017 "fReadSQL: Failure Searching data of appropriation!"
		#define STR0018 "fClose: Failure closing table of query!"
		#define STR0019 "Error querying Appropriations of Expense! Error:"
		#define STR0020 "Query by Creation is not possible in the Payable Accounts entity!"
		#define STR0021 "Query by Entry is not possible in the Payable Accounts entity!"
		#define STR0022 "Query by this information is not possible in the Payable Accounts entity!"
		#define STR0023 "Query by Expiration is not possible in the Inbound Invoice entity!"
		#define STR0024 "Query by Real Expiration is not possible in the Inbound Invoice entity!"
		#define STR0025 "Query by Entry is not possible in the Inbound Invoice entity!"
		#define STR0026 "Query by this information is not implemented in the Inbound Invoice entity!"
		#define STR0027 "Query by Creation is not possible in the Request Written-off entity!"
		#define STR0028 "Query by Expiration is not possible in the Request Written-off entity!"
		#define STR0029 "Query by Real Expiration is not possible in the Request Written-off entity!"
		#define STR0030 "Query by this information is not implemented in the Request Written-off entity!"
	#else
		#define STR0001 "De-Para de Empresa e Filial não encontrado na base para CompanyId '"
		#define STR0002 "' e BranchId '"
		#define STR0003 "Parâmetro '"
		#define STR0004 "' é obrigatório e não foi informado!"
		#define STR0005 "Campo 'C7_APROPRM' não existe no dicionário de dados na tabela 'SX3'."
		#define STR0006 "Tarefa Inicial '"
		#define STR0007 "' não encontrada no De/Para!"
		#define STR0008 "Tarefa Inicial '"
		#define STR0009 "Serviço genérico de retorno de movimentos de apropriação de despesas baseado no no conceito de Projeto/Tarefa do Microsiga Protheus."
		#define STR0010 "Exemplo de retorno de entidade(s)"
		#define STR0011 "WSRECEIVE: Falha ao buscar o banco de dados do cliente!"
		#define STR0012 "WSRECEIVE: Falha ao montar retorno de mensagem JSON!"
		#define STR0013 "fValField: Falha ao abrir tabelas de Dicionario de dados!"
		#define STR0014 "fValidMoviment: Falha ao validar parâmetros de movimento!"
		#define STR0015 "fEAIReceb: Falha ao validar parâmetros de movimento!"
		#define STR0016 "fConDate: Falha ao buscar Data de Fechamento de Periodo!"
		#define STR0017 "fReadSQL: Falha ao Buscar dados de Apropriação!"
		#define STR0018 "fClose: Falha ao fechar tabela de consulta!"
		#define STR0019 "Erro ao consultar Apropriações de Despesa! Erro:"
		#define STR0020 "A Consulta por Criação não é possível na entidade Contas a Pagar!"
		#define STR0021 "A Consulta por Lançamento não é possível na entidade Contas a Pagar!"
		#define STR0022 "A Consulta por esta informação não está implementada na entidade Contas a Pagar!"
		#define STR0023 "A Consulta por Vencimento não é possível na entidade Nota Fiscal de Entrada!"
		#define STR0024 "A Consulta por Vencimento Real não é possível na entidade Nota Fiscal de Entrada!"
		#define STR0025 "A Consulta por Lançamento não é possível na entidade Nota Fiscal de Entrada!"
		#define STR0026 "A Consulta por esta informação não está implementada na entidade Nota Fiscal de Entrada!"
		#define STR0027 "A Consulta por Criação não é possível na entidade Baixa de Requisição!"
		#define STR0028 "A Consulta por Vencimento não é possível na entidade Baixa de Requisição!"
		#define STR0029 "A Consulta por Vencimento Real não é possível na entidade Baixa de Requisição!"
		#define STR0030 "A Consulta por esta informação não está implementada na entidade Baixa de Requisição!"
	#endif
#endif
