#ifdef SPANISH
	#define STR0001 "Registro de la tabla de conceptos"
	#define STR0002 "Registro Borrado"
	#define STR0003 "El Evento de borrado no se transmitió ¿Realmente quiere borrarlo o mantener el evento de borrado para transmision posterior ?"
	#define STR0004 "Borrar"
	#define STR0005 "Mantener"
	#define STR0006 "Diccionario incompatible"
	#define STR0007 "Finalizar"
	#define STR0008 "Proceso aporte Seg. Priv.(CP)"
	#define STR0009 "Proceso IRRF"
	#define STR0010 "Proceso FGTS"
	#define STR0011 "Proceso aporte sindical"
	#define STR0012 "Informaciones de identificación del concepto"
	#define STR0013 "Detalles de las informaciones del concepto"
	#define STR0014 "Concepto"
	#define STR0015 "Comprobante de transmisión"
	#define STR0016 "Registro Incluído"
	#define STR0017 "Registro Alterado"
	#define STR0018 "Registro excluído não transmitido"
	#define STR0019 "Registro excluído transmitido"
#else
	#ifdef ENGLISH
		#define STR0001 "Item table register"
		#define STR0002 "Record Deleted"
		#define STR0003 "The deletion Event was not transmitted. Do you really wish to delete it or keep the deletion event for later transmission?"
		#define STR0004 "Delete"
		#define STR0005 "Keep"
		#define STR0006 "Dictionary Not Compatible"
		#define STR0007 "Close"
		#define STR0008 "Social Sec. Contrib. Process (CP)"
		#define STR0009 "IRRF Process"
		#define STR0010 "FGTS Process"
		#define STR0011 "Union Contrib. Process"
		#define STR0012 "Item identification information"
		#define STR0013 "Item information detailing"
		#define STR0014 "Signature"
		#define STR0015 "Transmission Protocol"
		#define STR0016 "Record Added"
		#define STR0017 "Record Edited"
		#define STR0018 "Deleted record not transmitted"
		#define STR0019 "Deleted record transmitted"
	#else
		#define STR0001 "Cadastro de Tabela de Rubricas"
		#define STR0002 "Registro Excluído"
		#define STR0003 "O Evento de exclusão não foi transmitido. Deseja realmente exclui-lo ou manter o evento de exclusão para transmissão posterior?"
		#define STR0004 "Excluir"
		#define STR0005 "Manter"
		#define STR0006 "Dicionário Incompatível"
		#define STR0007 "Encerrar"
		#define STR0008 "Processo Contrib. Previd.(CP)"
		#define STR0009 "Processo IRRF"
		#define STR0010 "Processo FGTS"
		#define STR0011 "Processo Contrib. Sindical"
		#define STR0012 "Informações de Identificação da Rubrica"
		#define STR0013 "Detalhamento das Informações da Rubrica"
		#define STR0014 "Rubrica"
		#define STR0015 "Protocolo de Transmissão"
		#define STR0016 "Registro Incluído"
		#define STR0017 "Registro Alterado"
		#define STR0018 "Registro excluído não transmitido"
		#define STR0019 "Registro excluído transmitido"
	#endif
#endif
