#ifdef SPANISH
	#define STR0001 "Reintegracion por determinacion judicial"
	#define STR0002 "Registro Incluido"
	#define STR0003 "Registro Modificado"
	#define STR0004 "Registro Borrado"
	#define STR0005 "Visualizar"
	#define STR0006 "El Evento de borrado no se transmitio. ¿Realmente quiere borrarlo o mantener el evento de borrado para transmision posterior ?"
	#define STR0007 "Borrar"
	#define STR0008 "Mantener"
	#define STR0009 "Diccionario incompatible"
	#define STR0010 "Finalizar"
#else
	#ifdef ENGLISH
		#define STR0001 "Reintegration due to Legal Determination"
		#define STR0002 "Record Added"
		#define STR0003 "Record Edited"
		#define STR0004 "Record Deleted"
		#define STR0005 "View"
		#define STR0006 "The deletion Event was not transmitted. Do you really wish to delete it or keep the deletion event for later transmission?"
		#define STR0007 "Delete"
		#define STR0008 "Keep"
		#define STR0009 "Dictionary Not Compatible"
		#define STR0010 "Close"
	#else
		#define STR0001 "Reintegração por Determinação Judicial"
		#define STR0002 "Registro Incluído"
		#define STR0003 "Registro Alterado"
		#define STR0004 "Registro Excluído"
		#define STR0005 "Visualizar"
		#define STR0006 "O Evento de exclusão não foi transmitido. Deseja realmente exclui-lo ou manter o evento de exclusão para transmissão posterior ?"
		#define STR0007 "Excuir"
		#define STR0008 "Manter"
		#define STR0009 "Dicionário Incompatível"
		#define STR0010 "Encerrar"
	#endif
#endif
