#ifdef SPANISH
	#define STR0001 "Registro de cuenta de la parte B"
	#define STR0002 "Asientos en lote"
	#define STR0003 "Reclasificación de la pérdida fiscal"
	#define STR0004 "Solamente Sucursal Matriz o Sucursal SCP tiene permiso de manejo del archivo."
	#define STR0005 "Cuenta de la parte B"
	#define STR0006 "Asientos en la cuenta de la parte B"
	#define STR0007 "Proceso judicial y administrativo de los registros en la Cuenta de la Parte B"
	#define STR0008 "El Proceso judicial y administrativo puede informarse únicamente cuando la modalidad de la cuenta tenga el valor 'Deducción/Compensación del tributo'."
	#define STR0009 "El saldo de la cuenta quedará negativo al hacer efectivo este asiento."
	#define STR0010 "Parámetros"
	#define STR0011 "Tributo"
	#define STR0012 "Identificación de la persona jurídica"
	#define STR0013 "Tributo no permitido para este archivo."
	#define STR0014 "Tributo no registrado."
	#define STR0015 "Tributos de la cuenta de la Parte B"
	#define STR0016 "Identificación de la persona jurídica no informada."
	#define STR0017 "Contenido inválido seleccionado para identificación de la persona jurídica."
	#define STR0018 "Al no informar la Identificación de la persona jurídica, no será posible identificar la tabla dinámica referente al código de asiento en la Parte A de origen."
	#define STR0019 "La fecha final no puede ser mayor que la fecha límite."
	#define STR0020 "La fecha final no puede ser mayor que la fecha de registro en la cuenta de la parte B."
	#define STR0021 "La fecha límite no puede ser menor que la fecha final."
	#define STR0022 "La fecha límite no puede ser menor que la fecha de registro en la cuenta de la parte B."
	#define STR0023 "La fecha de registro en la cuenta de la parte B debe estar incluida entre la fecha final y la fecha límite."
	#define STR0024 "Fecha inicial"
	#define STR0025 "Fecha final"
	#define STR0026 "Descripción"
	#define STR0027 "Mensual"
	#define STR0028 "Trimestral"
	#define STR0029 "Periodicidad"
	#define STR0030 "Valor fijo"
	#define STR0031 "Cuotas fijas"
	#define STR0032 "Porcentaje"
	#define STR0033 "Tipo de valor"
	#define STR0034 "Valor"
	#define STR0035 "Débito"
	#define STR0036 "Crédito"
	#define STR0037 "Constitución de saldo"
	#define STR0038 "Tipo de asiento"
	#define STR0039 "Sí"
	#define STR0040 "No"
	#define STR0041 "Realización de valores prorrogados"
	#define STR0042 "Historial"
	#define STR0043 "Procesando"
	#define STR0044 "Grabando lote"
	#define STR0045 "Fecha inicial no informada."
	#define STR0046 "Fecha inicial no puede ser mayor que fecha final."
	#define STR0047 "La fecha inicial debe estar incluida entre la fecha final y la fecha límite registrada para la cuenta."
	#define STR0048 "Fecha final no informada."
	#define STR0049 "La fecha final no puede ser menor que la fecha inicial."
	#define STR0050 "La fecha final debe estar incluida entre la fecha final y la fecha límite registrada para la cuenta."
	#define STR0051 "No fue posible encontrar el tributo de la cuenta referente al registro de origen/destino de la reclasificación."
	#define STR0052 "Periodicidad no informada."
	#define STR0053 "Contenido inválido seleccionado para periodicidad."
	#define STR0054 "Tipo de valor no informado."
	#define STR0055 "Contenido inválido seleccionado para el tipo de valor."
	#define STR0056 "El campo Valor no puede completarse con valor negativo o cero."
	#define STR0057 "El campo Porcentaje no puede completarse con valor negativo o cero."
	#define STR0058 "Tipo de asiento no informado."
	#define STR0059 "Contenido inválido seleccionado para el tipo de asiento."
	#define STR0060 "Contenido inválido seleccionado para la realización de valores prorrogados."
	#define STR0061 "No se procesaron asientos."
	#define STR0062 "Log de procesamiento"
	#define STR0063 "Asientos confirmados"
	#define STR0064 "Cuenta"
	#define STR0065 "Asiento"
	#define STR0066 "Fecha"
	#define STR0067 "Tipo"
	#define STR0068 "Asientos con inconsistencias"
	#define STR0069 "Cuenta de la parte B de origen no permitida para este proceso. Seleccione una cuenta con la modalidad 'Compensación de pérdida/Base de cálculo negativa'."
	#define STR0070 "La Reclasificación de la pérdida fiscal es aplicable únicamente a las Cuentas de la parte B del tributo IRPJ."
	#define STR0071 "Cuenta de destino"
	#define STR0072 "Fecha del asiento"
	#define STR0073 "Grabando asiento de reclasificación de la pérdida fiscal"
	#define STR0074 "Cuenta de la parte B de destino no permitida para este proceso. Seleccione una cuenta con la modalidad 'Compensación de pérdida/Base de cálculo negativa'."
	#define STR0075 "Cuenta de la parte B de destino no registrada."
	#define STR0076 "Cuenta de la parte B de destino no informada."
	#define STR0077 "Fecha del asiento no informada."
	#define STR0078 "La fecha del asiento debe estar incluida entre la Fecha final y la Fecha límite registrada para la Cuenta de la parte B de origen."
	#define STR0079 "La Fecha del asiento debe estar incluida entre la Fecha final y la Fecha límite registrada para la Cuenta de la parte B de destino."
	#define STR0080 "Cuenta de la parte B no registrada."
	#define STR0081 "Informe una Cuenta de la parte B de destino diferente de la Cuenta de la parte B de origen."
	#define STR0082 "El saldo de la cuenta origen/destino quedará negativo al hacer efectivo este asiento."
	#define STR0083 "No fue posible encontrar el asiento de origen/destino de la reclasificación."
	#define STR0084 "No fue posible encontrar la cuenta referente al asiento de origen/destino de la reclasificación."
	#define STR0085 "Esta operación borrará los asientos de Reclasificación de la pérdida fiscal, tanto en la cuenta origen como en la cuenta destino. ¿Desea confirmar la ejecución?"
	#define STR0086 "Borrado de reclasificación de la pérdida fiscal"
	#define STR0087 "Operación de borrado del asiento no realizada."
	#define STR0088 "Para el Tipo de valor 'Cuotas fijas', el saldo actual de la cuenta debe ser mayor que cero."
	#define STR0089 "Para el Tipo de valor 'Cuotas fijas', solo se permiten asientos que  reduzcan el saldo actual de la cuenta."
	#define STR0090 "Para el Tipo de valor 'Porcentaje', el saldo actual de la cuenta debe ser mayor que cero."
	#define STR0091 "Realización de valores diferidos no informada."
	#define STR0092 "La cuenta tiene registro de origen 'Reclasificación del perjuicio', no será posible modificar la modalidad."
	#define STR0093 "Tributo de la cuenta de la Parte B no registrado."
	#define STR0094 "Tributo de la cuenta de la Parte B no informado."
	#define STR0095 "Cuenta de la Parte B de destino seleccionada no tiene Tributo seleccionado."
	#define STR0096 "Visualizar"
	#define STR0097 "Incluir"
	#define STR0098 "Modificar"
	#define STR0099 "Borrar"
	#define STR0100 "Diccionario incompatible"
	#define STR0101 "Finalizar"
	#define STR0102 "PJ en General"
	#define STR0103 "PJ Financiero"
	#define STR0104 "Sociedades aseguradoras o Entidad abierta de seguridad complementaria"
	#define STR0105 "Atención"
	#define STR0106 "Este registro se generó a consecuencia de la finalización del período y solamente podrá modificarse por medio del Período de cálculo."
	#define STR0107 "Existen registros generados automáticamente en la finalización del Período de cálculo y no pueden borrarse."
	#define STR0108 "El registro no puede incluirse en un período finalizado."
#else
	#ifdef ENGLISH
		#define STR0001 "Register of Part B Account"
		#define STR0002 "Batch entries"
		#define STR0003 "Reclassification of tax loss"
		#define STR0004 "Only Head Office Branch or SCP Branch have permission to handle the register."
		#define STR0005 "Part B Account"
		#define STR0006 "Part B Account Entries"
		#define STR0007 "Legal and Administrative Proceedings of Part B Account Entries"
		#define STR0008 "Legal and Administrative Proceeding may be entered only when account class has value for 'Tax Deduction/Compensation'."
		#define STR0009 "Account balance will be negative once this transaction is performed."
		#define STR0010 "Parameters"
		#define STR0011 "Tax"
		#define STR0012 "Legal Entity Identification."
		#define STR0013 "Tax not allowed for this register."
		#define STR0014 "Tax not registered."
		#define STR0015 "Taxes of Part B Account"
		#define STR0016 "Legal Entity Identification not entered."
		#define STR0017 "Content invalid selected for the Identification of Legal Entity."
		#define STR0018 "When you do not enter the Legal Entity Identification, you will not be able to identify the dynamic table related to the entry code in Part A of origin."
		#define STR0019 "End Date cannot be later than Limit Date."
		#define STR0020 "End Date cannot be later than Date of Entry in Part B Account."
		#define STR0021 "Limit date can not be earlier than End Date."
		#define STR0022 "Limit Date cannot be earlier than Date of Entry in Part B Account."
		#define STR0023 "Date of Entry in Part B Account must be between End Date and Limit Date. "
		#define STR0024 "Start Date"
		#define STR0025 "End Date"
		#define STR0026 "Description"
		#define STR0027 "Monthly"
		#define STR0028 "Quarterly"
		#define STR0029 "Periodicity"
		#define STR0030 "Fixed Value"
		#define STR0031 "Fixed Quotas"
		#define STR0032 "Percentage"
		#define STR0033 "Type of value"
		#define STR0034 "Value"
		#define STR0035 "Debit"
		#define STR0036 "Credit"
		#define STR0037 "Balance Constitution"
		#define STR0038 "Entry Type"
		#define STR0039 "Yes"
		#define STR0040 "No"
		#define STR0041 "Realization of Differed Values"
		#define STR0042 "History"
		#define STR0043 "Processing"
		#define STR0044 "Saving Lot"
		#define STR0045 "Start date not entered."
		#define STR0046 "Start date cannot be later than end date."
		#define STR0047 "Start Date must be between End Date and Limit Date registered for the account. "
		#define STR0048 "End date not entered."
		#define STR0049 "End date cannot be earlier than start date."
		#define STR0050 "End Date must be between End Date and Limit Date registered for the account."
		#define STR0051 "Could not find the account tax related to the reclassification source/target entry."
		#define STR0052 "Periodicity not entered."
		#define STR0053 "Invalid content selected for Periodicity."
		#define STR0054 "Type of value not informed."
		#define STR0055 "Invalid content selected for Type of Value."
		#define STR0056 "Field Value cannot be negative or zero. "
		#define STR0057 "Field Percentage cannot be negative or zero."
		#define STR0058 "Type of Entry not informed."
		#define STR0059 "Invalid content selected for Type of Entry."
		#define STR0060 "Invalid content selected for Realization of Differed Values. "
		#define STR0061 "Entries were not processed."
		#define STR0062 "Processing Log"
		#define STR0063 "Confirmed Entries"
		#define STR0064 "Account"
		#define STR0065 "Entry"
		#define STR0066 "Date"
		#define STR0067 "Type"
		#define STR0068 "Entries with Inconsistencies"
		#define STR0069 "Source Part B Account not allowed for this process. Select a new account of class 'Loss Compensation/Negative Calculation Base'."
		#define STR0070 "Reclassification of Tax Loss is applicable only for IRPJ Tax Part B Accounts."
		#define STR0071 "Target Account"
		#define STR0072 "Entry Date"
		#define STR0073 "Saving Tax Loss Reclassification Entry"
		#define STR0074 "Target Part B Account not allowed for this process. Select a new account of class 'Loss Compensation/Negative Calculation Base'."
		#define STR0075 "Target Part B Account not registered."
		#define STR0076 "Target Part B Account not entered."
		#define STR0077 "Entry Date not entered."
		#define STR0078 "Entry Date must be between End Date and Limit Date registered for source Part B Account."
		#define STR0079 "Entry Date must be between End Date and Limit Date registered for target Part B Account."
		#define STR0080 "Part B Account not registered."
		#define STR0081 "Enter a target Part B Account different from source Part B Account."
		#define STR0082 "Source/target account balance will be negative once this transaction is performed."
		#define STR0083 "Unable to find source/target entry of reclassification."
		#define STR0084 "Unable to find account referring to source/target entry of reclassification."
		#define STR0085 "This operation deletes entries of Tax Loss Reclassification both in source and target accounts. Confirm execution?"
		#define STR0086 "Deletion of Tax Loss Reclassification"
		#define STR0087 "Entry deletion operation not executed."
		#define STR0088 "For 'Fixed Quotas' Type of Value, the current account balance must be higher than zero. "
		#define STR0089 "For 'Fixed Quotas' Type of Value, only entries that reduce the account's current balance are allowed. "
		#define STR0090 "For 'Percentage' Type of Value, the current account balance must be higher than zero."
		#define STR0091 "Realization of Differed Values not entered."
		#define STR0092 "The account has a 'Loss Reclassification' source entry. You cannot change its class."
		#define STR0093 "Part B Account Tax not registered."
		#define STR0094 "Part B Account Tax not entered."
		#define STR0095 "Selected target Part B Account does not have the Tax chosen."
		#define STR0096 "View"
		#define STR0097 "Add"
		#define STR0098 "Edit"
		#define STR0099 "Delete"
		#define STR0100 "Dictionary Not Compatible"
		#define STR0101 "Close"
		#define STR0102 "Legal Entity in General"
		#define STR0103 "Legal Entity Financials"
		#define STR0104 "Insurance Societies or Pending Entity of Complementary Social Security"
		#define STR0105 "Attention"
		#define STR0106 "This entry was generated by the closing of the period and can only be modified through the Calculation Period"
		#define STR0107 "There are entries automatically generated by the closing of the Calculation Period and cannot be deleted."
		#define STR0108 "Cannot add entry in a Closed Period."
	#else
		#define STR0001 "Cadastro de Conta da Parte B"
		#define STR0002 "Lançamentos em Lote"
		#define STR0003 "Reclassificação do Prejuízo Fiscal"
		#define STR0004 "Apenas Filial Matriz ou Filial SCP possui permissão de manipulação do cadastro."
		#define STR0005 "Conta da Parte B"
		#define STR0006 "Lançamentos na Conta da Parte B"
		#define STR0007 "Processo Judicial e Administrativo dos Lançamentos na Conta da Parte B"
		#define STR0008 "O Processo Judicial e Administrativo pode ser informado apenas quando a natureza da conta possuir o valor 'Dedução/Compensação do Tributo'."
		#define STR0009 "O saldo da conta ficará negativo com a efetivação deste lançamento."
		#define STR0010 "Parâmetros"
		#define STR0011 "Tributo"
		#define STR0012 "Identificação da Pessoa Jurídica"
		#define STR0013 "Tributo não permitido para este cadastro."
		#define STR0014 "Tributo não cadastrado."
		#define STR0015 "Tributos da Conta da Parte B"
		#define STR0016 "Identificação da Pessoa Jurídica não informada."
		#define STR0017 "Conteúdo inválido selecionado para Identificação da Pessoa Jurídica."
		#define STR0018 "Ao não informar a Identificação da Pessoa Jurídica, não será possível identificar a tabela dinâmica referente ao código de lançamento na Parte A de origem."
		#define STR0019 "A Data Final não pode ser maior que a Data Limite."
		#define STR0020 "A Data Final não pode ser maior que a Data de Lançamento na Conta da Parte B."
		#define STR0021 "A Data Limite não pode ser menor que a Data Final."
		#define STR0022 "A Data Limite não pode ser menor que a Data de Lançamento na Conta da Parte B."
		#define STR0023 "A Data de Lançamento na Conta da Parte B deve estar compreendida entre a Data Final e a Data Limite."
		#define STR0024 "Data Inicial"
		#define STR0025 "Data Final"
		#define STR0026 "Descrição"
		#define STR0027 "Mensal"
		#define STR0028 "Trimestral"
		#define STR0029 "Periodicidade"
		#define STR0030 "Valor Fixo"
		#define STR0031 "Quotas Fixas"
		#define STR0032 "Percentual"
		#define STR0033 "Tipo de Valor"
		#define STR0034 "Valor"
		#define STR0035 "Débito"
		#define STR0036 "Crédito"
		#define STR0037 "Constituição de Saldo"
		#define STR0038 "Tipo do Lançamento"
		#define STR0039 "Sim"
		#define STR0040 "Não"
		#define STR0041 "Realização de Valores Diferidos"
		#define STR0042 "Histórico"
		#define STR0043 "Processando"
		#define STR0044 "Gravando Lote"
		#define STR0045 "Data Inicial não informada."
		#define STR0046 "Data Inicial não pode ser maior que a Data Final."
		#define STR0047 "A Data Inicial deve estar compreendida entre a Data Final e a Data Limite cadastrada para a conta."
		#define STR0048 "Data Final não informada."
		#define STR0049 "Data Final não pode ser menor que a Data Inicial."
		#define STR0050 "A Data Final deve estar compreendida entre a Data Final e a Data Limite cadastrada para a conta."
		#define STR0051 "Não foi possível encontrar o tributo da conta referente ao lançamento de origem/destino da reclassificação."
		#define STR0052 "Periodicidade não informada."
		#define STR0053 "Conteúdo inválido selecionado para Periodicidade."
		#define STR0054 "Tipo de Valor não informado."
		#define STR0055 "Conteúdo inválido selecionado para Tipo de Valor."
		#define STR0056 "O campo Valor não pode ser preenchido com valor negativo ou zero."
		#define STR0057 "O campo Percentual não pode ser preenchido com valor negativo ou zero."
		#define STR0058 "Tipo do Lançamento não informado."
		#define STR0059 "Conteúdo inválido selecionado para Tipo do Lançamento."
		#define STR0060 "Conteúdo inválido selecionado para Realização de Valores Diferidos."
		#define STR0061 "Não foram processados lançamentos!"
		#define STR0062 "Log de Processamento"
		#define STR0063 "Lançamentos Confirmados"
		#define STR0064 "Conta"
		#define STR0065 "Lançamento"
		#define STR0066 "Data"
		#define STR0067 "Tipo"
		#define STR0068 "Lançamentos com Inconsistências"
		#define STR0069 "Conta da Parte B de origem não permitida para este processo. Selecione uma conta com a natureza 'Compensação de Prejuízo/Base de Cálculo Negativa'."
		#define STR0070 "A Reclassificação do Prejuízo Fiscal é aplicável apenas a Contas da Parte B do Tributo IRPJ."
		#define STR0071 "Conta de Destino"
		#define STR0072 "Data do Lançamento"
		#define STR0073 "Gravando Lançamento de Reclassificação do Prejuízo Fiscal"
		#define STR0074 "Conta da Parte B de destino não permitida para este processo. Selecione uma conta com a natureza 'Compensação de Prejuízo/Base de Cálculo Negativa'."
		#define STR0075 "Conta da Parte B de destino não cadastrada."
		#define STR0076 "Conta da Parte B de destino não informada."
		#define STR0077 "Data do Lançamento não informada."
		#define STR0078 "A Data do Lançamento deve estar compreendida entre a Data Final e a Data Limite cadastrada para a Conta da Parte B de origem."
		#define STR0079 "A Data do Lançamento deve estar compreendida entre a Data Final e a Data Limite cadastrada para a Conta da Parte B de destino."
		#define STR0080 "Conta da Parte B não cadastrada."
		#define STR0081 "Informe uma Conta da Parte B de destino diferente da Conta da Parte B de origem."
		#define STR0082 "O saldo da conta de origem/destino ficará negativo com a efetivação deste lançamento."
		#define STR0083 "Não foi possível encontrar o lançamento de origem/destino da reclassificação."
		#define STR0084 "Não foi possível encontrar a conta referente ao lançamento de origem/destino da reclassificação."
		#define STR0085 "Esta operação irá excluir os lançamentos de Reclassificação do Prejuízo Fiscal tanto na conta de origem quanto na conta de destino. Deseja confirmar a execução?"
		#define STR0086 "Exclusão de Reclassificação do Prejuízo Fiscal"
		#define STR0087 "Operação de exclusão do lançamento não efetuada."
		#define STR0088 "Para o Tipo de Valor 'Quotas Fixas', o saldo atual da conta deve ser maior que zero."
		#define STR0089 "Para o Tipo de Valor 'Quotas Fixas', apenas são permitidos lançamentos que reduzam o saldo atual da conta."
		#define STR0090 "Para o Tipo de Valor 'Percentual', o saldo atual da conta deve ser maior que zero."
		#define STR0091 "Realização de Valores Diferidos não informado."
		#define STR0092 "A conta possui lançamento de origem 'Reclassificação do Prejuízo', não será possível alterar a natureza."
		#define STR0093 "Tributo da Conta da Parte B não cadastrado."
		#define STR0094 "Tributo da Conta da Parte B não informado."
		#define STR0095 "Conta da Parte B de destino selecionada não possui o Tributo escolhido."
		#define STR0096 "Visualizar"
		#define STR0097 "Incluir"
		#define STR0098 "Alterar"
		#define STR0099 "Excluir"
		#define STR0100 "Dicionário Incompatível"
		#define STR0101 "Encerrar"
		#define STR0102 "PJ em Geral"
		#define STR0103 "PJ Financeiro"
		#define STR0104 "Sociedades Seguradoras ou Entidade Aberta de Previdência Complementar"
		#define STR0105 "Atenção"
		#define STR0106 "Este lançamento foi gerado pelo Encerramento do Período e só poderá ser modificado através do Período de Apuração"
		#define STR0107 "Existem lançamentos gerados automaticamente pelo Encerramento do Período de Apuração e não podem ser excluídos."
		#define STR0108 "O lançamento não pode ser inserido em um Período Encerrado."
	#endif
#endif
