#ifdef SPANISH
	#define STR0001 "Trabajador sin vinculo de empleo - Inicio"
	#define STR0002 "Registro incluido"
	#define STR0003 "Registro Modificado"
	#define STR0004 "Registro Borrado"
	#define STR0005 "Visualizar"
	#define STR0006 "Datos del trabajador"
	#define STR0007 "Informaciones de nacimiento"
	#define STR0008 "Informaciones de la libreta de trabajo"
	#define STR0009 "Direccion"
	#define STR0010 "Informaciones Contacto"
	#define STR0011 "Informaciones de Transmision"
	#define STR0012 "Trabajador sin vínculo - Inicio"
	#define STR0013 "Cargo y/o función del trabajador"
	#define STR0014 "Remuneración"
	#define STR0015 "FGTS"
	#define STR0016 "Empresa de origen del dirigente sindical"
	#define STR0017 "Trabajador"
	#define STR0018 "Informaciones del Trabajador"
	#define STR0019 "Informaciones del trabajador extranjero"
	#define STR0020 "Deficiencia"
	#define STR0021 "Dependientes"
	#define STR0022 "Sin Vinculo"
	#define STR0023 "Informaciones del Trabajador Sin Vinculo"
	#define STR0024 "Registro transmitido"
	#define STR0025 "Este evento se encuentra transmitido."
	#define STR0026 "El borrado de este registro se debe hacer por medio del evento S-2900."
	#define STR0027 "Encerramiento"
	#define STR0028 "El Evento de borrado no se transmitio. ¿Realmente quiere borrarlo o mantener el evento de borrado para transmision posterior ?"
	#define STR0029 "Borrar"
	#define STR0030 "Mantener"
	#define STR0031 "Informaciones relacionadas al trabajador cedido"
	#define STR0032 "Información del practicante"
	#define STR0033 "Institución de educación"
	#define STR0034 "Agente de integración"
	#define STR0035 "Supervisor del practicante"
	#define STR0036 "Informaciones complementarias"
	#define STR0037 "Informaciones del registro de identificación civil"
	#define STR0038 "Informaciones del registro general (RG)"
	#define STR0039 "Informaciones del registro nacional de extranjero"
	#define STR0040 "Informaciones del número de registro en órgano de clase (OC)"
	#define STR0041 "Informaciones de la licencia nacional para conducir (CNH)"
	#define STR0042 "Informaciones sobre jubilación"
	#define STR0043 "Protocolo de transmisión"
	#define STR0044 "No se permite borrar el registro del trabajador sin vínculo (s2300), porque existen otros eventos laborales (s2305 o s2399) posteriores al mismo CPF."
	#define STR0045 "Diccionario incompatible"
	#define STR0046 "Finalizar"
	#define STR0047 "Licencia"
	#define STR0048 "Término"
	#define STR0049 "Cambio de CPF"
	#define STR0050 "Información del trabajador inmigrante"
	#define STR0051 "Información referente a Servidor Público en el Ejercicio de Mandato Electivo"
#else
	#ifdef ENGLISH
		#define STR0001 "Worker Without Work Link - Start"
		#define STR0002 "Record Added"
		#define STR0003 "Record Edited"
		#define STR0004 "Record Deleted"
		#define STR0005 "View"
		#define STR0006 "Worker Data"
		#define STR0007 "Information of Birth"
		#define STR0008 "Information of Employee Card"
		#define STR0009 "Address"
		#define STR0010 "Contact Information"
		#define STR0011 "Information of Transmission"
		#define STR0012 "Employee Without Relationship - Start"
		#define STR0013 "Worker Role and Position"
		#define STR0014 "Remuneration"
		#define STR0015 "FGTS"
		#define STR0016 "Origin company of union leader"
		#define STR0017 "Worker"
		#define STR0018 "Employee Information"
		#define STR0019 "Foreigner Worker Information"
		#define STR0020 "Disability"
		#define STR0021 "Dependents"
		#define STR0022 "No relationship"
		#define STR0023 "Worker information with no relationship"
		#define STR0024 "Record Transmitted"
		#define STR0025 "This event was transmitted."
		#define STR0026 "The deletion of this record should be done by event S-2900."
		#define STR0027 "Close"
		#define STR0028 "The deletion Event was not transmitted. Do you really wish to delete it or keep the deletion event for later transmission?"
		#define STR0029 "Delete"
		#define STR0030 "Keep"
		#define STR0031 "Information Related to Assigned Worker"
		#define STR0032 "Intern Information"
		#define STR0033 "Educational institutions"
		#define STR0034 "Integration Agents"
		#define STR0035 "Stage Supervisor"
		#define STR0036 "Complementary Information"
		#define STR0037 "Information of Civil Identification Record"
		#define STR0038 "Information of General Record"
		#define STR0039 "Information of Foreigner National Record"
		#define STR0040 "Information of record number in Class Body (OC)"
		#define STR0041 "Information of National Driver License (CNH)"
		#define STR0042 "Information on Retirement"
		#define STR0043 "Transmission Protocol"
		#define STR0044 "Unable to delete worker record without relationship (s2300), as there are other worker events (s2305 or s2399) later to the same CPF."
		#define STR0045 "Dictionary Not Compatible"
		#define STR0046 "Close"
		#define STR0047 "Leave"
		#define STR0048 "End"
		#define STR0049 "Change of SSN."
		#define STR0050 "Immigrant worker information"
		#define STR0051 "Information related to public servants with an elective office"
	#else
		#define STR0001 "Trabalhador Sem Vínculo de Emprego - Início"
		#define STR0002 "Registro Incluído"
		#define STR0003 "Registro Alterado"
		#define STR0004 "Registro Excluído"
		#define STR0005 "Visualizar"
		#define STR0006 "Dados do Trabalhador"
		#define STR0007 "Informações de Nascimento"
		#define STR0008 "Informações da Carteira de Trabalho"
		#define STR0009 "Endereço"
		#define STR0010 "Informações de Contato"
		#define STR0011 "Informações de Transmissão"
		#define STR0012 "Trabalhador Sem Vínculo - Início"
		#define STR0013 "Cargo e Função do trabalhador"
		#define STR0014 "Remuneração"
		#define STR0015 "FGTS"
		#define STR0016 "Empresa de Origem do Dirigente Sindical"
		#define STR0017 "Trabalhador"
		#define STR0018 "Informações do Trabalhador"
		#define STR0019 "Informações do Trabalhador Estrangeiro"
		#define STR0020 "Deficiência"
		#define STR0021 "Dependentes"
		#define STR0022 "Sem Vínculo"
		#define STR0023 "Informações do Trabalhador Sem Vínculo"
		#define STR0024 "Registro Transmitido"
		#define STR0025 "Este evento encontra-se transmitido."
		#define STR0026 "A exclusão deste registro deverá ser feita através do evento S-2900."
		#define STR0027 "Fechar"
		#define STR0028 "O Evento de exclusão não foi transmitido. Deseja realmente exclui-lo ou manter o evento de exclusão para transmissão posterior ?"
		#define STR0029 "Excuir"
		#define STR0030 "Manter"
		#define STR0031 "Informações Relativas ao Trabalhador Cedido"
		#define STR0032 "Informação do Estagiário"
		#define STR0033 "Instituição de Ensino"
		#define STR0034 "Agente de Integração"
		#define STR0035 "Supervisor do Estágio"
		#define STR0036 "Informações Complementares"
		#define STR0037 "Informações do Registro de Identificação Civil"
		#define STR0038 "Informações do Registro Geral (RG)"
		#define STR0039 "Informações do Registro Nacional de Estrangeiro"
		#define STR0040 "Informações do número de registro em Órgão de Classe (OC)"
		#define STR0041 "Informações da Carteira Nacional de Habilitação (CNH)"
		#define STR0042 "Informações sobre Aposentadoria"
		#define STR0043 "Protocolo de Transmissão"
		#define STR0044 "Não é permitido realizar a exclusão do registro do trabalhador sem vínculo (s2300), pois existem outros eventos trabalhistas (s2305 ou s2399) posteriores para o mesmo CPF."
		#define STR0045 "Dicionário Incompatível"
		#define STR0046 "Encerrar"
		#define STR0047 "Afastamento"
		#define STR0048 "Término"
		#define STR0049 "Mudança de CPF"
		#define STR0050 "Informações do Trabalhador Imigrante"
		#define STR0051 "Informações Relativas a Servidor Público Exercente de Mandato Eletivo"
	#endif
#endif
