#ifdef SPANISH
	#define STR0001 "DATOS_DE_PAGO_GNR_P14"
	#define STR0002 "Informe anulado por el usuario."
	#define STR0003 "ESTADO DESTINATARIO:"
	#define STR0004 "Generando Informe, Espere."
	#define STR0005 "********************************* NO HUBO MOVIMIENTO *********************************"
	#define STR0006 "- DATOS DE PAGO - GNR                             LP1 - MODELO P14"
	#define STR0007 "EMITENTE:"
	#define STR0008 "PAGINA:"
	#define STR0009 "INSCRIPCION EST.:"
	#define STR0010 "DIRECCION:"
	#define STR0011 "C.G.C.:"
	#define STR0012 "PERIODO:  DE"
	#define STR0013 "CIUDAD:"
	#define STR0014 "R/E/P:"
	#define STR0015 "CP:"
	#define STR0016 "EMISION:"
	#define STR0017 "FECHA"
	#define STR0018 "CCD BANCO"
	#define STR0019 "COD AGENCIA"
	#define STR0020 "NUM GNR"
	#define STR0021 "VAL GNR"
	#define STR0022 "VAL DEVOL"
	#define STR0023 "VAL RESARC"
	#define STR0024 "TOTALES DE PLANILLA...................................................................................................................................................."
	#define STR0025 "/"
	#define STR0026 " HASTA "
	#define STR0027 "No se selecciono ninguna sucursal para el procesamiento. Se considerara la sucursal corriente."
	#define STR0028 "TAFR116 - Datos de recaudación - GNR - LP1 - Modelo P14"
#else
	#ifdef ENGLISH
		#define STR0001 "DADOS_DE_RECOLHIMENTO_GNR_P14"
		#define STR0002 "Report canceled by user"
		#define STR0003 "RECIPIENT STATE:"
		#define STR0004 "Generating report, wait."
		#define STR0005 "******************************************* THERE WAS NO TRANSACTION *******************************************"
		#define STR0006 "- COLLECTION DATA - GNR                             LP1 - MODEL P14"
		#define STR0007 "ISSUER:"
		#define STR0008 "PAGE:"
		#define STR0009 "ST. REGISTRATION:"
		#define STR0010 "ADDRESS:"
		#define STR0011 "C.G.C.:"
		#define STR0012 "PERIOD:  FROM"
		#define STR0013 "CITY:"
		#define STR0014 "State:"
		#define STR0015 "Postal Code:"
		#define STR0016 "ISSUE:"
		#define STR0017 "DATE"
		#define STR0018 "CCD BANK"
		#define STR0019 "BRANCH CODE"
		#define STR0020 "GNR NR"
		#define STR0021 "GNR VAL"
		#define STR0022 "RETURN VAL"
		#define STR0023 "REIMBURSEMENT VAL"
		#define STR0024 "TOTAL OF PAYROLL.................................................................................................................................................."
		#define STR0025 "/"
		#define STR0026 " TO "
		#define STR0027 "No branch was selected for this processing. The current branch will be considered."
		#define STR0028 "TAFR116 - Collection Data - GNR - LP1 - P14 Model"
	#else
		#define STR0001 "DADOS_DE_RECOLHIMENTO_GNR_P14"
		#define STR0002 "Relatório cancelado pelo usuário."
		#define STR0003 "ESTADO DESTINATÁRIO:"
		#define STR0004 "Gerando Relatorio, Aguarde."
		#define STR0005 "********************************* NÃO HOUVE MOVIMENTO *********************************"
		#define STR0006 "- DADOS DE RECOLHIMENTO - GNR                             LP1 - MODELO P14"
		#define STR0007 "EMITENTE:"
		#define STR0008 "PÁGINA:"
		#define STR0009 "INSCRIÇÃO EST.:"
		#define STR0010 "ENDEREÇO:"
		#define STR0011 "C.G.C.:"
		#define STR0012 "PERIODO:  DE"
		#define STR0013 "CIDADE:"
		#define STR0014 "UF:"
		#define STR0015 "CEP:"
		#define STR0016 "EMISSÃO:"
		#define STR0017 "DATA"
		#define STR0018 "CCD BANCO"
		#define STR0019 "CÓD AGÊNCIA"
		#define STR0020 "NÚM GNR"
		#define STR0021 "VAL GNR"
		#define STR0022 "VAL DEVOL"
		#define STR0023 "VAL RESSARC"
		#define STR0024 "TOTAIS DA FOLHA...................................................................................................................................................."
		#define STR0025 "/"
		#define STR0026 " ATÉ "
		#define STR0027 "Nenhuma filial foi selecionada para o processamento. Será considerada a filial corrente."
		#define STR0028 "TAFR116 - Dados de Recolhimento - GNR - LP1 - Modelo P14"
	#endif
#endif
