#ifdef SPANISH
	#define STR0001 "Procesando DES - Cómputo MG"
	#define STR0002 "Preparando el entorno..."
	#define STR0003 "Ejecutando el procesamiento..."
	#define STR0004 "Procesamiento anulado"
	#define STR0005 "Haga clic en Finalizar"
	#define STR0006 "¡Atención!"
	#define STR0007 "¡La generación del archivo se anuló con éxito!"
	#define STR0008 "Salir"
	#define STR0009 "Ocurrió un error fatal durante la generación de los registros de la DES - MG"
	#define STR0010 "Por favor, efectúe el reprocesamiento de la DES - MG, si el error persiste entre  en contacto con el administrador de sistemas/soporte TOTVS"
	#define STR0011 "Informaciones procesadas"
	#define STR0012 "Consolidando las informaciones y generando archivo..."
	#define STR0013 "Archivo generado con éxito."
	#define STR0014 "Falla al generar el archivo"
	#define STR0015 "Procesando empresa."
	#define STR0016 "Complete correctamente la información solicitada."
	#define STR0017 "Informaciones necesarias para generar el medio-magnético DES - Cómputo MG."
	#define STR0018 "Para el período seleccionado existen documentos fiscales con código de servicio no informado. Estos documentos no se considerarán. ¿Desea informarlos?"
	#define STR0019 "¿Desea generar la obligación sin finalizar el registro de códigos de servicio?"
	#define STR0020 "Código de Servicio/Actividad municipal por ítem"
	#define STR0021 "¡Atención! Información actualizada con éxito."
	#define STR0022 "No se modificó ningún registro"
	#define STR0023 "Empresa"
	#define STR0024 "Sucursal"
	#define STR0025 "Hora"
	#define STR0026 "Período generado"
	#define STR0027 "a la"
	#define STR0028 "DES Contagem MG - Informe de verificación"
	#define STR0029 "Verificación de los documentos generados en la DES"
	#define STR0030 "¿Desea generar el informe de verificación?"
	#define STR0031 "Factura"
	#define STR0032 "Serie"
	#define STR0034 "RCPJ"
	#define STR0035 "Participante"
	#define STR0036 "Est/Prov/Reg"
	#define STR0037 "Ciudad"
	#define STR0038 "Valor bruto"
	#define STR0039 "Tipo Rec."
	#define STR0043 "Valor"
	#define STR0044 "Recibo"
	#define STR0045 "Tipo Ingreso"
	#define STR0046 "Fecha"
	#define STR0047 "Base de calc."
	#define STR0048 "Alíc."
	#define STR0049 "Cód. Servi"
	#define STR0050 "Alic Simple"
#else
	#ifdef ENGLISH
		#define STR0001 "Processing DES - Contagem MG"
		#define STR0002 "Preparing the Environment..."
		#define STR0003 "Executing Processing..."
		#define STR0004 "Processing canceled."
		#define STR0005 "Click Finish"
		#define STR0006 "Attention!"
		#define STR0007 "File creation successfully canceled!"
		#define STR0008 "Exit"
		#define STR0009 "Fatal error during generation of DES - MG Record(s)"
		#define STR0010 "Reprocess DES - MG, if the error persists, contact the systems administrator / TOTVS support"
		#define STR0011 "Processed information"
		#define STR0012 "Consolidating information and generating file..."
		#define STR0013 "File creation successful."
		#define STR0014 "Failure generating file."
		#define STR0015 "Processing Company."
		#define STR0016 "Fill out properly with the required information."
		#define STR0017 "Information required to create DES - MG magnetic-file "
		#define STR0018 "For the selected period, tax documents found with service code not entered. These documents will not be taken into account. Do you wish to enter them?"
		#define STR0019 "Do you wish to create liability without closing the service codes register?"
		#define STR0020 "City Service/Activity Code per Item"
		#define STR0021 "Attention information updated with success."
		#define STR0022 "No record was edited"
		#define STR0023 "Company"
		#define STR0024 "Branch"
		#define STR0025 "Time"
		#define STR0026 "Generated Period"
		#define STR0027 "to"
		#define STR0028 "DES Contagem MG - Verification report"
		#define STR0029 "Verification of documents generated in DES"
		#define STR0030 "Do you want to generate the verification?"
		#define STR0031 "Invoice"
		#define STR0032 "Series"
		#define STR0034 "EIN"
		#define STR0035 "Employee"
		#define STR0036 "State"
		#define STR0037 "City"
		#define STR0038 "Gross Value"
		#define STR0039 "Rec. Type"
		#define STR0043 "Value"
		#define STR0044 "Receipt"
		#define STR0045 "Revenue Type"
		#define STR0046 "Date"
		#define STR0047 "Basis"
		#define STR0048 "Rate"
		#define STR0049 "Code Serv"
		#define STR0050 "Simple rate"
	#else
		#define STR0001 "Processando DES - Contagem MG"
		#define STR0002 "Preparando o Ambiente..."
		#define STR0003 "Executando o Processamento..."
		#define STR0004 "Processamento cancelado"
		#define STR0005 "Clique em Finalizar"
		#define STR0006 "Atenção!"
		#define STR0007 "A geração do arquivo foi cancelada com sucesso!"
		#define STR0008 "Sair"
		#define STR0009 "Ocorreu um erro fatal durante a geração do(s) Registro(s) da DES - MG"
		#define STR0010 "Favor efetuar o reprocessamento da DES - MG, caso o erro persista entre em contato com o administrador de sistemas / suporte TOTVS"
		#define STR0011 "Informações processadas"
		#define STR0012 "Consolidando as informações e gerando arquivo..."
		#define STR0013 "Arquivo gerado com sucesso."
		#define STR0014 "Falha na geração do arquivo."
		#define STR0015 "Processando Empresa."
		#define STR0016 "Preencha corretamente as informações solicitadas."
		#define STR0017 "Informações necessárias para a geração do meio-magnético DES - Contagem MG."
		#define STR0018 "Para o período selecionado existem documentos fiscais com código de serviço não informado. Esses documentos não serão considerados. Deseja informá-los?"
		#define STR0019 "Deseja gerar a obrigação sem finalizar o cadastro de códigos de serviço?"
		#define STR0020 "Código de Serviço/Atividade Municipal por Item"
		#define STR0021 "Atenção Informações atualizadas com sucesso."
		#define STR0022 "Nenhum registro foi alterado"
		#define STR0023 "Empresa"
		#define STR0024 "Filial"
		#define STR0025 "Hora"
		#define STR0026 "Período Gerado"
		#define STR0027 "à"
		#define STR0028 "DES Contagem MG - Relatório de Conferência"
		#define STR0029 "Conferência dos documentos gerados na DES"
		#define STR0030 "Deseja gerar o relatório de conferência?"
		#define STR0031 "Nota Fiscal"
		#define STR0032 "Série"
		#define STR0034 "CNPJ"
		#define STR0035 "Participante"
		#define STR0036 "Estado"
		#define STR0037 "Cidade"
		#define STR0038 "Valor Bruto"
		#define STR0039 "Tipo Rec."
		#define STR0043 "Valor"
		#define STR0044 "Recibo"
		#define STR0045 "Tipo Receita"
		#define STR0046 "Data"
		#define STR0047 "Base de Calc."
		#define STR0048 "Aliq"
		#define STR0049 "Cod. Servi"
		#define STR0050 "Aliq Simples"
	#endif
#endif
