#ifdef SPANISH
	#define STR0001 "Cálculo ágil"
	#define STR0002 "Contrato"
	#define STR0003 "Filtros"
	#define STR0004 "Datos"
	#define STR0005 "Totalizador"
	#define STR0006 "Número del contrato deseable para el cálculo"
	#define STR0007 "Revisión"
	#define STR0008 "Vigencia"
	#define STR0009 "Valor calculado"
	#define STR0010 "Valor que se calculará en el contrato"
	#define STR0011 "Cliente"
	#define STR0012 "Tienda"
	#define STR0013 "Buscar (F10)"
	#define STR0014 "Marca todos"
	#define STR0015 "Procesando"
	#define STR0016 "Espere"
	#define STR0017 "Mark"
	#define STR0018 "Local de atención"
	#define STR0019 "Descrip. Cliente"
	#define STR0020 "Valor de la planilla"
	#define STR0021 "Saldo de la vigencia"
	#define STR0022 "Valor calcular"
	#define STR0023 "Código TFL"
	#define STR0024 "Total"
	#define STR0025 "Revirtiendo..."
	#define STR0026 "Inclusión del cálculo"
	#define STR0027 "Buscando información..."
	#define STR0028 "Id del formulario de origen:"
	#define STR0029 "Id del campo de origen:"
	#define STR0030 "Id del formulario de error:"
	#define STR0031 "Id del campo de error:"
	#define STR0032 "Id del error:"
	#define STR0033 "Mensaje de error:"
	#define STR0034 "Mensaje de la solución:"
	#define STR0035 "Valor atribuido:"
	#define STR0036 "Valor anterior:"
	#define STR0037 "Valor que se calculará de la planilla."
	#define STR0038 "Tienda utilizada en el cálculo."
	#define STR0039 "Cliente utilizado en el cálculo."
	#define STR0040 "Municipio que se utilizará únicamente para filtro de los locales de atención."
	#define STR0041 "Est/Prov/Reg que se utilizará únicamente para filtro de los locales de atención."
	#define STR0042 "Tienda que se utilizará únicamente para filtro de los locales de atención."
	#define STR0043 "Cliente que se utilizará únicamente para filtro de los locales de atención."
	#define STR0044 "Vigencia que se utilizará en el cálculo."
	#define STR0045 "Salir"
	#define STR0046 "Confirma"
	#define STR0047 "Por favor, seleccione un cliente o tienda, válidos."
	#define STR0048 "Cambio de cliente"
	#define STR0049 "No es posible grabar, por favor, seleccione una planilla e incluya un valor."
	#define STR0050 "Para marcar la planilla recurrente es necesario cambiar la competencia a"
	#define STR0051 "No se puede utilizar cálculo ágil con prorrata configurado."
	#define STR0052 "No se pudo encontrar el contrato activo, sin revisión en marcha."
	#define STR0053 "El valor incluido ("
	#define STR0054 ") es mayor que el saldo de las planillas seleccionadas ("
	#define STR0055 ") no se incluyó ningún valor."
	#define STR0056 "Valor del cálculo"
	#define STR0057 "No se completó ningún valor en las planillas por medirse."
	#define STR0058 "Preparando el cálculo..."
	#define STR0059 "Marcando..."
	#define STR0060 "Realizando los cálculos..."
#else
	#ifdef ENGLISH
		#define STR0001 "Agile Examination"
		#define STR0002 "Contract"
		#define STR0003 "Filters"
		#define STR0004 "Data"
		#define STR0005 "Totalizer"
		#define STR0006 "Contract number desirable for examination"
		#define STR0007 "Revision"
		#define STR0008 "Period"
		#define STR0009 "Examined Value"
		#define STR0010 "Value to be examined in contract"
		#define STR0011 "Customer"
		#define STR0012 "Store"
		#define STR0013 "Search (F10)"
		#define STR0014 "Select all"
		#define STR0015 "Processing"
		#define STR0016 "Wait"
		#define STR0017 "Mark"
		#define STR0018 "Service Location"
		#define STR0019 "Customer Desc."
		#define STR0020 "Spreadsheet Value"
		#define STR0021 "Comp. Balance"
		#define STR0022 "Value to Examine"
		#define STR0023 "TFL Code"
		#define STR0024 "Total"
		#define STR0025 "Reversing..."
		#define STR0026 "Examination Addition"
		#define STR0027 "Searching information..."
		#define STR0028 "Source form id:"
		#define STR0029 "Source field id:"
		#define STR0030 "Error form id:"
		#define STR0031 "Error field id:"
		#define STR0032 "Error id:"
		#define STR0033 "Error message:"
		#define STR0034 "Solution message:"
		#define STR0035 "Attributed value:"
		#define STR0036 "Previous value:"
		#define STR0037 "Value to be examined from spreadsheet."
		#define STR0038 "Store used in examination."
		#define STR0039 "Customer used in examination."
		#define STR0040 "City to be used only as filter for service locations."
		#define STR0041 "State to be used only as filter for service locations."
		#define STR0042 "Store to be used only as filter for service locations."
		#define STR0043 "Customer to be used only as filter for service locations."
		#define STR0044 "Period to be used in examination."
		#define STR0045 "Exit"
		#define STR0046 "Confirm"
		#define STR0047 "Select a valid customer or store."
		#define STR0048 "Customer swap"
		#define STR0049 "Cannot save, select a spreadsheet and enter a value."
		#define STR0050 "To mark the recurring spreadsheet, change the period to"
		#define STR0051 "Cannot use agile examination with set up Pro-Rata."
		#define STR0052 "Could not find the active contract, no review in progress."
		#define STR0053 "Entered value ("
		#define STR0054 ") is higher than the selected spreadsheets balance ("
		#define STR0055 ") no value was entered."
		#define STR0056 "Examination Value"
		#define STR0057 "No value entered in the spreadsheets to be measured."
		#define STR0058 "Preparing Calculation..."
		#define STR0059 "Checking..."
		#define STR0060 "Calculating..."
	#else
		#define STR0001 "Apuração Agil"
		#define STR0002 "Contrato"
		#define STR0003 "Filtros"
		#define STR0004 "Dados"
		#define STR0005 "Totalizador"
		#define STR0006 "Numero do Contrato desejavel para a apuração"
		#define STR0007 "Revisão"
		#define STR0008 "Competência"
		#define STR0009 "Valor Apurado"
		#define STR0010 "Valor a ser apurado no contrato"
		#define STR0011 "Cliente"
		#define STR0012 "Loja"
		#define STR0013 "Buscar (F10)"
		#define STR0014 "Marca Todos"
		#define STR0015 "Processando"
		#define STR0016 "Aguarde"
		#define STR0017 "Mark"
		#define STR0018 "Local de Atendimento"
		#define STR0019 "Descri. Cliente"
		#define STR0020 "Valor da Planilha"
		#define STR0021 "Saldo da Comp."
		#define STR0022 "Valor Apurar"
		#define STR0023 "Codigo TFL"
		#define STR0024 "Total"
		#define STR0025 "Estornando..."
		#define STR0026 "Inclusão da Apuração"
		#define STR0027 "Buscando Informações..."
		#define STR0028 "Id do formulário de origem:"
		#define STR0029 "Id do campo de origem:"
		#define STR0030 "Id do formulário de erro:"
		#define STR0031 "Id do campo de erro:"
		#define STR0032 "Id do erro:"
		#define STR0033 "Mensagem do erro:"
		#define STR0034 "Mensagem da solução:"
		#define STR0035 "Valor atribuído:"
		#define STR0036 "Valor anterior:"
		#define STR0037 "Valor a ser apurado da planilha."
		#define STR0038 "Loja utilizado na apuração."
		#define STR0039 "Cliente utilizado na apuração."
		#define STR0040 "Municipio a ser utilizado apenas para filtro dos locais de atendimento."
		#define STR0041 "Estado a ser utilizado apenas para filtro dos locais de atendimento."
		#define STR0042 "Loja a ser utilizado apenas para filtro dos locais de atendimento."
		#define STR0043 "Cliente a ser utilizado apenas para filtro dos locais de atendimento."
		#define STR0044 "Competencia a ser utilizada na apuração."
		#define STR0045 "Sair"
		#define STR0046 "Confirma"
		#define STR0047 "Por favor selecionar um cliente ou uma loja, valido."
		#define STR0048 "Troca de Cliente"
		#define STR0049 "Não é possivel salvar, por favor selecione uma planilha e insira um valor."
		#define STR0050 "Para marcar a planilha recorrente é necessário mudar a competência para "
		#define STR0051 "Não é possivel utilizar apuração agil com Pro-Rata configurado."
		#define STR0052 "Não foi possivel localizar o contrato ativo, sem revisão em andamento."
		#define STR0053 "O valor inserido ("
		#define STR0054 ") é maior que o saldo das planilhas selecionadas ("
		#define STR0055 ") não foi inserido nenhum valor."
		#define STR0056 "Valor da Apuração"
		#define STR0057 "Nenhum valor foi preenchido nas planilhas a serem medidas."
		#define STR0058 "Preparando a Apuração..."
		#define STR0059 "Marcando..."
		#define STR0060 "Realizando os Calculos..."
	#endif
#endif
