#ifdef SPANISH
	#define STR0001 "Movimiento"
	#define STR0002 "Programada"
	#define STR0003 "Efectivada"
	#define STR0004 "Anulado"
	#define STR0005 "Bco. Conocimiento"
	#define STR0006 "Movimiento"
	#define STR0007 "No se permite modificar el Movimiento efectaudo o anulado."
	#define STR0008 "Asignacion"
	#define STR0009 "Ya existe una programacion para ese armamento"
	#define STR0010 "No hay asignacion para ese armamento, seleccione otro"
	#define STR0011 "¿Desea imprimir el protocolo de entrega?"
	#define STR0012 "Complete el Numero del Formualrio"
	#define STR0013 "Complete la justificacion"
	#define STR0014 "¡El Estatus del armamento no permite movimiento!"
	#define STR0015 "Origen"
	#define STR0016 "Es necesario informar el lugar de origen de la municion"
	#define STR0017 "Es necesario informar la cantidad de municiones para el movimiento"
	#define STR0018 "La cantidad informada es mayor que el del asignado o es superior al saldo disponible para movimiento en el Blister vinculado."
	#define STR0019 "Codigo"
	#define STR0020 "El codigo informado no esta registrado"
	#define STR0021 "Local de Origen es el mismo de destino"
	#define STR0022 "Ente"
	#define STR0023 "Codigo Interno"
	#define STR0024 "Codigo del Local"
	#define STR0025 "Movimiento"
	#define STR0026 "Saldo"
	#define STR0027 "Lote"
	#define STR0028 "Anular"
	#define STR0029 "Confirmar"
	#define STR0030 "No hay asignacion para ese municion, seleccione otro lote"
	#define STR0031 "Para el movimiento de Mantenimiento, Descarte y Finalización, solo será posible seleccionar la Empresa como destino"
	#define STR0032 "Para movimiento de Refuerzo, solo sera posible seleccionar al cliente"
	#define STR0033 "No es posible programar un movimiento con la fecha menor a la database"
	#define STR0034 "La fecha de movimiento no puede ser mayor que la database para que se efectue."
	#define STR0035 "Informe una fecha de retorno"
	#define STR0036 "La fecha de retorno tiene que ser mayor a la database"
	#define STR0037 "Movimiento para implementacion, Codigo: "
	#define STR0038 "Retorno para Empresa, Codigo: "
	#define STR0039 "Espere"
	#define STR0040 "Procesando..."
	#define STR0041 "Mantenimiento incluido con exito."
	#define STR0042 "ATENCION"
	#define STR0043 "El campo de responsable de mantenimiento no esta completo"
	#define STR0044 "El campo tipo de mantenimiento no esta completo"
	#define STR0045 "El campo motivo de mantenimiento no esta completo"
	#define STR0046 "El Arma seleccionada posee un mantenimiento pendiente, borre o finalice el mantenimiento"
	#define STR0047 "Movimiento"
	#define STR0048 "Formulario de Trafico"
	#define STR0049 "Modelo de WORD : "
	#define STR0050 " usado en la integracion no encontrado en el servidor. ¡Impresion anulada!"
	#define STR0051 "Imprimiendo protocolo...."
	#define STR0052 "Guardando Archivo...."
	#define STR0053 "Operacion"
	#define STR0054 "Problemas en la comunicacion con el editor del Protocolo de Recepcion"
	#define STR0055 " Guardado en el Directorio "
	#define STR0056 "Error"
	#define STR0057 "Falla en la creacion de la carpeta "
	#define STR0058 "El operador seleccionado en la linea: "
	#define STR0059 " no esta con la CNV informada"
	#define STR0060 "¡Usuario sin autorizacion para movimiento fuera del contrato!"
	#define STR0061 "¡Contrato invalido para el lugar elegido!"
	#define STR0062 "¡Usuario sin autorizacion para asignar equipamientos adicionales en el contrato!"
	#define STR0063 'No se seleccionó ningún ítem de armamento.'
	#define STR0064 'Informe el motivo para el movimiento.'
	#define STR0065 "Verifique armamentos: La fecha de devolución debe ser mayor o igual a la fecha del movimiento."
	#define STR0066 "La fecha de validez del armamento expiró."
	#define STR0067 "La fecha de devolución debe ser mayor o igual a la fecha del movimiento."
	#define STR0068 "No se permiten movimientos de armamentos entre clientes."
	#define STR0069 "No hay registro con este código en la solapa de Armas."
	#define STR0070 "El arma tiene vínculo con el ítem de la solapa de munición. Registro no puede borrarse."
	#define STR0071 "Informe el origen del movimiento."
	#define STR0072 "Este armamento no está asignado en el origen informado."
	#define STR0073 "Usuario no puede realizar el movimiento de la munición excediendo 3 cargas."
	#define STR0074 "Arma descartada o desactivada"
	#define STR0075 "El armamento seleccionado tiene la situación igual a Desactivada o Descartada"
	#define STR0076 "Chaleco Descartado o Desactivado"
	#define STR0077 "El chaleco seleccionado tiene la situación igual a Desactivado o Descartado"
	#define STR0078 "El arma seleccionada no se encontró o tiene capacidad de munición registrada igual a cero"
	#define STR0079 "Esta consulta es específica y condicionada a la cumplimentación de los campos, por lo tanto, solo funciona en el archivo."
	#define STR0080 "Consulta específica"
	#define STR0081 "Saldo del producto "
	#define STR0082 " indisponible para movimiento"
	#define STR0083 "Chaleco"
	#define STR0084 "Buscar"
	#define STR0085 "Visualizar"
	#define STR0086 "Incluir"
	#define STR0087 "Modificar"
	#define STR0088 "Borrar"
	#define STR0089 "Destinatarios"
	#define STR0090 "Armas"
	#define STR0091 "Municiones"
	#define STR0092 "Chalecos"
	#define STR0093 "Reimprimir protocolo"
	#define STR0094 "Para reimpresión de protocolo que seleccione un ítem del Grid de armas, chalecos o munición"
	#define STR0095 "Movimiento no permite reimprimir el protocolo"
	#define STR0096 "Para reimprimir el protocolo, es necesario que el RDMake U_Tec880ImpProt esté compilado"
#else
	#ifdef ENGLISH
		#define STR0001 "Movement"
		#define STR0002 "Scheduled"
		#define STR0003 "Confirmed"
		#define STR0004 "Canceled"
		#define STR0005 "Bk. Knowledge"
		#define STR0006 "Movement"
		#define STR0007 "Not allowed to edit Effective or Canceled Movements."
		#define STR0008 "Allocation"
		#define STR0009 "There is already a schedule for this weapon"
		#define STR0010 "No allocation for this weapon, select another one"
		#define STR0011 "Do you want to print Delivery Receipt?"
		#define STR0012 "Fill out the Guide Number"
		#define STR0013 "Fill out the Explanation"
		#define STR0014 "The status of the weapon does not allow movement!"
		#define STR0015 "Origin"
		#define STR0016 "Necessary enter a Location of Ammunition Source"
		#define STR0017 "Necessary enter an Amount of Ammunition for Movement"
		#define STR0018 "The amount entered is greater than what was allocated or what is greater than the balance available for the movement in the related Blister."
		#define STR0019 "Code"
		#define STR0020 "The code entered is not related"
		#define STR0021 "Origin location is the same as target"
		#define STR0022 "Entity"
		#define STR0023 "Internal Code"
		#define STR0024 "Location code"
		#define STR0025 "Movement"
		#define STR0026 "Balance"
		#define STR0027 "Lot"
		#define STR0028 "Cancel"
		#define STR0029 "Confirm"
		#define STR0030 "No allocation for this ammunition, select another lot"
		#define STR0031 "For transfer of Maintenance, Discard and Closing, you can only select the Company as destination"
		#define STR0032 "For Enforcement movement, it is only possible to select the Customer"
		#define STR0033 "It is not possible to schedule a movement with date lower than the database"
		#define STR0034 "Movement date cannot be later than database to be effective"
		#define STR0035 "Enter a return date"
		#define STR0036 "Return date must be later than database"
		#define STR0037 "Movement for implementation, Code: "
		#define STR0038 "Return to Company, Code: "
		#define STR0039 "Wait"
		#define STR0040 "Processing..."
		#define STR0041 "Maintenance successfully added."
		#define STR0042 "WARNING"
		#define STR0043 "The field responsible for maintenance is not filled out"
		#define STR0044 "The field maintenance type is not filled out"
		#define STR0045 "The field explanation type is not filled out"
		#define STR0046 "The selected Weapon has outstanding maintenance, Delete or Close  the maintenance"
		#define STR0047 "Movement"
		#define STR0048 "Traffic Guide"
		#define STR0049 "WORD Model: "
		#define STR0050 " used on the integration not found on the server. Canceled Printing!"
		#define STR0051 "Printing Protocol..."
		#define STR0052 "Saving File..."
		#define STR0053 "Operation"
		#define STR0054 "Problems on the communication with the Receiving Protocol editor"
		#define STR0055 " Saved on Directory "
		#define STR0056 "Error"
		#define STR0057 "Failure creating the folder "
		#define STR0058 "The selected Operator on the row: "
		#define STR0059 " does not have CNV filled out"
		#define STR0060 "User with no permission to make transactions outside the contract!"
		#define STR0061 "Contract not valid for chosen location!"
		#define STR0062 "User without permission to allocate additional equipment in contract!"
		#define STR0063 'No weapon item selected!'
		#define STR0064 'Enter Reason for Transaction!'
		#define STR0065 "Check Weapons: Return date must be after or equal to transaction date!"
		#define STR0066 "Weapon Validity Date has expired!"
		#define STR0067 "Return date must be after or equal to transaction date!"
		#define STR0068 "No weapons transactions between Customers allowed!"
		#define STR0069 "No record found with this code in Weapons Tab!"
		#define STR0070 "Weapon linked to ammunition tab item. Cannot delete record."
		#define STR0071 "Enter Transaction Source!"
		#define STR0072 "This weapon is not allocated in the entered Source!"
		#define STR0073 "You cannot execute ammunition transaction with over 3 loads."
		#define STR0074 "Discarded or Deactivated Weapon"
		#define STR0075 "The weapon chosen has status equal to Deactivated or Discarded"
		#define STR0076 "Discarded or Deactivated Body Armour"
		#define STR0077 "The body armour chosen has status equal to Deactivated or Discarded"
		#define STR0078 "The selected weapon was not found or has capacity of ammunition registered as zero"
		#define STR0079 "This query is specific and conditioned to the completion of fields, therefore, it only works in the registration."
		#define STR0080 "Specific Query"
		#define STR0081 "Product balance. "
		#define STR0082 " unavailable for movement"
		#define STR0083 "Body Armour"
		#define STR0084 "Search"
		#define STR0085 "View"
		#define STR0086 "Add"
		#define STR0087 "Edit"
		#define STR0088 "Delete"
		#define STR0089 "Recipients"
		#define STR0090 "Weapons"
		#define STR0091 "Munition"
		#define STR0092 "Armour"
		#define STR0093 "Reprint protocol"
		#define STR0094 "To reprint protocol, select an item of the Weapons, Body Armour or Ammunition grid"
		#define STR0095 "Movement does not allow you to reprint protocol"
		#define STR0096 "To reprint protocol, the RDMake U_Tec880ImpProt is compiled"
	#else
		#define STR0001 "Movimentação"
		#define STR0002 "Agendada"
		#define STR0003 "Efetivada"
		#define STR0004 "Cancelada"
		#define STR0005 "Bco. Conhecimento"
		#define STR0006 "Movimentação"
		#define STR0007 "Não é permitido alterar a Movimentação Efetivada ou Cancelada."
		#define STR0008 "Alocação"
		#define STR0009 "Já existe um agendamento para esse armamento"
		#define STR0010 "Não há alocação para esse armamento, selecione outro"
		#define STR0011 "Deseja Imprimir o Protocolo de Entrega?"
		#define STR0012 "Preencha o Numero da Guia"
		#define STR0013 "Preencha a Justificativa"
		#define STR0014 "O Status do Armamento não permite movimentação!"
		#define STR0015 "Origem"
		#define STR0016 "É Necessario informar o Local de Origem da Munição"
		#define STR0017 "É Necessario informar a quantidade de munições para a Movimentação"
		#define STR0018 "A quantidade informada é maior do que está alocado ou é superior ao saldo disponivel para movimentação no Blister relacionado."
		#define STR0019 "Codigo"
		#define STR0020 "O codigo informado não está relacionado"
		#define STR0021 "Local de Origem é o mesmo de destino"
		#define STR0022 "Entidade"
		#define STR0023 "Codigo Interno"
		#define STR0024 "Codigo do Local"
		#define STR0025 "Movimentação"
		#define STR0026 "Saldo"
		#define STR0027 "Lote"
		#define STR0028 "Cancelar"
		#define STR0029 "Confirmar"
		#define STR0030 "Não há alocação para essa munição, selecione outro lote"
		#define STR0031 "Para movimentação de Manutenção, Descarte e Encerramento, só será possivel selecionar a Empresa como destino"
		#define STR0032 "Para movimentação de Reforço, só será possivel selecionar o cliente"
		#define STR0033 "Não é possivel agendar uma movimentação com data menor que a database"
		#define STR0034 "A data de movimentação não pode ser maior que a database para ser efetivada"
		#define STR0035 "Informe uma data de retorno"
		#define STR0036 "A data de retorno tem que ser maior que a database"
		#define STR0037 "Movimentação para implantação, Codigo: "
		#define STR0038 "Retorno para Empresa, Codigo: "
		#define STR0039 "Aguarde"
		#define STR0040 "Processando..."
		#define STR0041 "Manutenção incluida com sucesso."
		#define STR0042 "ATENÇÃO"
		#define STR0043 "O campo de responsavel pela manutenção não está preenchido"
		#define STR0044 "O campo tipo da manutenção não está preenchido"
		#define STR0045 "O campo motivo da manutenção não está preenchido"
		#define STR0046 "A Arma selecionada possui uma manutenção em aberto, Exclua ou encerre a manutenção"
		#define STR0047 "Movimentação"
		#define STR0048 "Guia de Trafego"
		#define STR0049 "Modelo do WORD : "
		#define STR0050 " usado na integração não encontrado no servidor. Impressão cancelada !"
		#define STR0051 "Imprimindo protocolo...."
		#define STR0052 "Salvando Arquivo...."
		#define STR0053 "Operação"
		#define STR0054 "Problemas na comunicacao com o editor do Protocolo de Recebimento"
		#define STR0055 " Salvo no Diretorio "
		#define STR0056 "Erro"
		#define STR0057 "Falha na criação da pasta "
		#define STR0058 "O Atendente selecionado na linha: "
		#define STR0059 " não está com a CNV preenchida"
		#define STR0060 "Usuário sem permissão para movimentação fora do contrato!"
		#define STR0061 "Contrato invalido para o local escolhido!"
		#define STR0062 "Usuário sem permissão para alocar equipamentos adicionais no contrato!"
		#define STR0063 'Nenhum item de armamento foi selecionado!'
		#define STR0064 'Informe o Motivo para a Movimentação!'
		#define STR0065 "Verifique Armamentos: Data de retorno deve ser maior ou igual que a data da movimentação!"
		#define STR0066 "Data de Validade do Armamento expirou!"
		#define STR0067 "Data de retorno deve ser maior ou igual que a data da movimentação!"
		#define STR0068 "Não são permitidas movimentações de armamentos entre Clientes!"
		#define STR0069 "Não há registro com este código na Aba de Armas!"
		#define STR0070 "Arma possui vinculo com item da aba de munição. Registro não pode ser deletado."
		#define STR0071 "Informe a Origem da Movimentação!"
		#define STR0072 "Esse armamento não está alocado na Origem informada!"
		#define STR0073 "Usuario não pode efetuar a movimentação da munição excedendo 3 cargas."
		#define STR0074 "Arma Descartada ou Desativada"
		#define STR0075 "O armamento escolhido tem situação igual a Desativada ou Descartada"
		#define STR0076 "Colete Descartado ou Desativado"
		#define STR0077 "O colete escolhido tem situação igual a Desativado ou Descartado"
		#define STR0078 "A arma selecionada nao foi localizada ou possui capacidade de munição cadastrada igual a zero"
		#define STR0079 "Essa consulta é específica e condicionada a preenchimento de campos, portanto só funciona no cadastro."
		#define STR0080 "Consulta Específica"
		#define STR0081 "Saldo do produto "
		#define STR0082 " indisponível para movimentação"
		#define STR0083 "Colete"
		#define STR0084 "Pesquisar"
		#define STR0085 "Visualizar"
		#define STR0086 "Incluir"
		#define STR0087 "Alterar"
		#define STR0088 "Excluir"
		#define STR0089 "Destinatários"
		#define STR0090 "Armas"
		#define STR0091 "Munições"
		#define STR0092 "Coletes"
		#define STR0093 "Reimprimir protocolo"
		#define STR0094 "Para reimpressão de protocolo que selecione um item do grid de Armas, Coletes ou Munição"
		#define STR0095 "Movimentação não permite reimpressao de protocolo"
		#define STR0096 "Para reimpressão de protocolo necessário que o RDMake U_Tec880ImpProt esteja compilado"
	#endif
#endif
