#ifdef SPANISH
	#define STR0001 'Reserva de equipos'
	#define STR0002 'Reserva'
	#define STR0003 'Finalizacion de oportunidad'
	#define STR0004 'Generacion del contrato'
	#define STR0005 'Finalizacion de reservas'
	#define STR0006 'Salir'
	#define STR0007 'Proseguir'
	#define STR0008 'Liberacion forzada de reservas'
	#define STR0009 'Procesamiento: Finalizacion'
	#define STR0010 'Anulacion/Liberacion'
#else
	#ifdef ENGLISH
		#define STR0001 'Equipment Reservation'
		#define STR0002 'Reservation'
		#define STR0003 'Opportunity conclusion'
		#define STR0004 'Contract generation'
		#define STR0005 'Reservations closing'
		#define STR0006 'Exit'
		#define STR0007 'Continue'
		#define STR0008 'Forced Release of Reservation'
		#define STR0009 'Processing: Closing'
		#define STR0010 'Cancellation/Release'
	#else
		#define STR0001 'Reserva de Equipamentos'
		#define STR0002 'Reserva'
		#define STR0003 'Finalização da oportunidade'
		#define STR0004 'Geração do contrato'
		#define STR0005 'Encerramento de Reservas'
		#define STR0006 'Sair'
		#define STR0007 'Prosseguir'
		#define STR0008 'Liberação Forçada de Reservas'
		#define STR0009 'Processamento: Encerramento'
		#define STR0010 'Cancelamento/Liberação'
	#endif
#endif
