#ifdef SPANISH
	#define STR0001 "Carga de Carretera"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Cargar"
	#define STR0005 "Revertir"
	#define STR0006 "Leyenda"
	#define STR0007 "Procesando... ¡Por favor espere!"
	#define STR0008 "Estatus"
	#define STR0009 "Pendiente"
	#define STR0010 "Cargado"
	#define STR0011 "Carga Aerea"
	#define STR0012 "Carga Entrega"
	#define STR0013 "Invertir seleccion"
	#define STR0014 "Cargamento de Transporte Fluvial"
	#define STR0015 "Viage - <F4>"
	#define STR0016 "Viaje"
	#define STR0017 "Limite - <F5>"
	#define STR0018 "Limite"
	#define STR0019 "TES"
	#define STR0020 "AVISO"
	#define STR0021 "El  Almacen/Direccion"
	#define STR0022 " del Documento/Serie "
	#define STR0023 " no fueron caregados ..."
	#define STR0024 "OK"
	#define STR0025 "Documento "
	#define STR0026 " no pertenece a esta ruta."
	#define STR0027 "¿ Confirma la utilizacion del documento ?"
	#define STR0028 "¡ Factura no encontrada !"
	#define STR0029 "Informe la sucursal del dcto./nºdcto."
	#define STR0030 "/Serie Dcto ..."
	#define STR0031 "Volumenes:"
	#define STR0032 "Peso Real:"
	#define STR0033 "Peso Cubicado:"
	#define STR0034 "Vlr. Merc.:"
	#define STR0035 "Doctos.:"
	#define STR0036 "Documento: "
	#define STR0037 "Cargamento Entrega Fluvial"
	#define STR0038 "¡Documentos no pueden vincularse a viaje por el cargamento!"
	#define STR0039 "El Documento no pertenece al servicio de transporte y o tipo de transporte del viaje. ¿Desea continuar?"
	#define STR0040 "Si"
	#define STR0041 "No"
	#define STR0042 "Informe el campo "
	#define STR0043 "Vehiculo invalido o no esta utilizandose en el viaje"
	#define STR0044 " es superior a(l) "
	#define STR0045 " del documento"
	#define STR0046 "Existen documentos de cargamento en partes cargados para el documento "
	#define STR0047 "Direccion"
	#define STR0048 "Vehiculos del viaje"
	#define STR0049 "Cod.Vehiculo"
	#define STR0050 "Modelo"
	#define STR0051 "Vehiculos del viaje no encontrados"
	#define STR0052 "El Valor del Frete informado en la carga es superior al del documento."
	#define STR0053 "Flete Total: "
	#define STR0054 "Flete Cargado: "
	#define STR0055 "Flete Restante: "
	#define STR0056 "Es necesario informar el valor del flete"
	#define STR0057 "Este documento necesita recibir el valor restante del flete"
	#define STR0058 "El CRT esta con valor de flete en cero, verifique antes de proseguir la operacion"
	#define STR0059 "No se permite efectuar carga parcial en el transporte nacional"
	#define STR0060 "Carga Transporte Internacional"
	#define STR0061 "Id del formulario de origen:"
	#define STR0062 "Id del campo de origen:"
	#define STR0063 "Id del formulario de error:"
	#define STR0064 "Id del campo de error: "
	#define STR0065 "Id del error: "
	#define STR0066 "Mensaje del error: "
	#define STR0067 "Mensaje de la solucion: "
	#define STR0068 "Valor atribuido: "
	#define STR0069 "Valor anterior: "
	#define STR0070 "Lectura de Cód. de Barras por documento"
	#define STR0071 "Cód. Barras"
	#define STR0072 "Lectura por Cód.Barras - <F8>"
	#define STR0073 "Lectura por Cód.Barras"
	#define STR0074 "Documentos con criterio de prorrateo - "
	#define STR0075 "no pueden vincularse a una Ruta por CP/Cliente."
	#define STR0076 "¡Documento no puede incluirse en este Viaje, porque el lote difiere del lote del documento!"
	#define STR0077 "e-CT no autorizado o no enviado al fisco."
	#define STR0078 "Documento con estatus diferente de 1-Pendiente o 5-Llegada a sucursal"
	#define STR0079 "Documento ya cargado"
	#define STR0080 "Error al ubicar el servicio operativo"
	#define STR0081 "Este documento no puede vincularse a un viaje por medio de la carga"
	#define STR0082 "La región de destino del CTRC no pertenece a la región de la ruta"
	#define STR0083 "Error al ubicar el movimiento de viaje para el documento"
	#define STR0084 "Documento ya está en una Programación de carga:"
	#define STR0085 "Documento bloqueado ..."
	#define STR0086 "Para documentos con criterio de prorrateo, la ruta debe quedarse con contenido en blanco."
	#define STR0087 "Este documento no podrá cargarse porque está configurado como si fuera del 1º trayecto"
	#define STR0088 "¡Factura no encontrada!"
	#define STR0089 "Llegada a la Sucursal / Cliente"
	#define STR0090 "La acción no puede completarse, pues los siguientes manifiestos tienen anulación transmitida:"
	#define STR0091 "La acción no puede completarse, pues los siguientes e-MDF tienen finalización no transmitida:"
#else
	#ifdef ENGLISH
		#define STR0001 "Highway Load"
		#define STR0002 "Search   "
		#define STR0003 "View"
		#define STR0004 "Load    "
		#define STR0005 "Reverse "
		#define STR0006 "Caption"
		#define STR0007 "Processing... Please wait!       "
		#define STR0008 "Status"
		#define STR0009 "Pending"
		#define STR0010 "Loaded   "
		#define STR0011 "Airway Load       "
		#define STR0012 "Delivery Load       "
		#define STR0013 "Invert selection"
		#define STR0014 "River transportation "
		#define STR0015 "Trip - <F4>"
		#define STR0016 "Trip "
		#define STR0017 "Limit - <F5>"
		#define STR0018 "Limit "
		#define STR0019 "TIO"
		#define STR0020 "WARNING"
		#define STR0021 "Warehouse/address "
		#define STR0022 " of document/series "
		#define STR0023 " were not loaded ... "
		#define STR0024 "OK"
		#define STR0025 "Document "
		#define STR0026 " does not belong to this route."
		#define STR0027 "Confirm use of this document? "
		#define STR0028 "Unload branches "
		#define STR0029 "Description"
		#define STR0030 "Unload branch"
		#define STR0031 "Volumes:"
		#define STR0032 "Actual Weight:"
		#define STR0033 "Cubic Weight"
		#define STR0034 "Goods Val.:"
		#define STR0035 "Documents"
		#define STR0036 "Document : "
		#define STR0037 "River Delivery Shipment"
		#define STR0038 "Documents cannot be linked to trip by load!"
		#define STR0039 "Document does not belong to transportation service or trip transportation type. Continue?"
		#define STR0040 "Yes"
		#define STR0041 "No"
		#define STR0042 "Enter the field "
		#define STR0043 "Invalid vehicle or it is being used in trip"
		#define STR0044 " is higher than "
		#define STR0045 " of document!"
		#define STR0046 "There are load documents loaded for the document "
		#define STR0047 "Address"
		#define STR0048 "Trip vehicles"
		#define STR0049 "Vehicle Code"
		#define STR0050 "Model"
		#define STR0051 "Trip vehicles not found"
		#define STR0052 "Freight Value indicated in the shipment is higher than the document's."
		#define STR0053 "Total Freight "
		#define STR0054 "Loaded Freight: "
		#define STR0055 "Remaining Freight: "
		#define STR0056 "Indicating freight value is necessary"
		#define STR0057 "This document has to receive the remaining freight value"
		#define STR0058 "CRT has zeroed value, check before proceeding the operation"
		#define STR0059 "Shipping partially in national transportation is not allowed"
		#define STR0060 "International Transportation Shipment"
		#define STR0061 "Id of the origin form:"
		#define STR0062 "Id of the origin field:"
		#define STR0063 "Id of error form:"
		#define STR0064 "Id of error field: "
		#define STR0065 "Error Id: "
		#define STR0066 "Error message: "
		#define STR0067 "Solution message: "
		#define STR0068 "Value given: "
		#define STR0069 "Previous Value: "
		#define STR0070 "Reading Document Bar Code"
		#define STR0071 "Code Bars"
		#define STR0072 "Reading by Bar Codes - <F8>"
		#define STR0073 "Reading by Bar Codes"
		#define STR0074 "Documents with Apportionment criterion -  "
		#define STR0075 "cannot be associated with a Route per Postal Code/Customer."
		#define STR0076 "Document cannot be added to this trip because the lot is different form the document lot"
		#define STR0077 "CT-e not authorized or not sent to."
		#define STR0078 "Document with status different from 1-Open or 5-Arrival in Branch"
		#define STR0079 "Document already loaded"
		#define STR0080 "Error locating operational service"
		#define STR0081 "This document cannot be attached to a trip through loading"
		#define STR0082 "Destination region of CTRC does not belong to region of route"
		#define STR0083 "Error locating trip transaction for the document"
		#define STR0084 "Document already in a Loading Schedule:"
		#define STR0085 "Document blocked..."
		#define STR0086 "For documents with Apportionment criterion, the Route must remain blank"
		#define STR0087 "This Document cannot be loaded because it is set as being 1st route"
		#define STR0088 "Invoice not found."
		#define STR0089 "Arrival in Branch/Customer"
		#define STR0090 "Action cannot be completed, as the following manifests have non-transmitted cancellation:"
		#define STR0091 "Action cannot be completed, as the following MDF-e have non-transmitted closing:"
	#else
		#define STR0001 "Carregamento Rodoviario"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Carregar"
		#define STR0005 "Estornar"
		#define STR0006 "Legenda"
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Processando... por favor aguarde!", "Processando... Por favor aguarde!" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Estado", "Status" )
		#define STR0009 "Em Aberto"
		#define STR0010 "Carregado"
		#define STR0011 "Carregamento Aereo"
		#define STR0012 "Carregamento Entrega"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Inverter selecção", "Inverter selecao" )
		#define STR0014 "Carregamento Transporte Fluvial"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Viagem - <f4>", "Viagem - <F4>" )
		#define STR0016 "Viagem"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Limite - <f5>", "Limite - <F5>" )
		#define STR0018 "Limite"
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Tes", "TES" )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Aviso", "AVISO" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "O Armazém/morada", "O Armazem/Endereço" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", " do documento/série ", " do Documento/Série " )
		#define STR0023 " não foram carregados ..."
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Ok", "OK" )
		#define STR0025 "Documento "
		#define STR0026 " não pertence a esta rota."
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Cofacturairma a utilização do documento ?", "Confirma a utilização do documento ?" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Filiais De Descarga", "Filiais de Descarga" )
		#define STR0029 "Descrição"
		#define STR0030 "Fil. Descarga"
		#define STR0031 "Volumes:"
		#define STR0032 "Peso Real:"
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Peso Bruto:", "Peso Cubado:" )
		#define STR0034 "Vlr. Merc.:"
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Documentos:", "Doctos.:" )
		#define STR0036 "Documento: "
		#define STR0037 "Carregamento Entrega Fluvial"
		#define STR0038 "Documentos não podem ser vinculados a viagem pelo carregamento!"
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "O documento não pertence ao serviço de transporte e/ou tipo de transporte da viagem. deseja continuar?", "O Documento não pertence ao serviço de transporte e ou tipo de transporte da viagem. Deseja continuar?" )
		#define STR0040 "Sim"
		#define STR0041 "Não"
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Introduza o campo ", "Informe o campo " )
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "Veículo inválido ou não está a ser utilizado na viagem", "Veículo inválido ou não está sendo utilizado na viagem" )
		#define STR0044 " é superior a(ao) "
		#define STR0045 " do documento!"
		#define STR0046 "Existem documentos de carregamento em partes carregados para o documento "
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Morada", "Endereço" )
		#define STR0048 "Veículos da viagem"
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Cod.veículo", "Cód.Veículo" )
		#define STR0050 "Modelo"
		#define STR0051 "Veículos da viagem não encontrados"
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "O valor do frete informado no carregamento é maior que o do documento.", "O Valor do Frete informado no carregamento é maior que o do documento." )
		#define STR0053 "Frete Total: "
		#define STR0054 "Frete Carregado: "
		#define STR0055 "Frete Restante: "
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "É necessário informar o valor do frete", "E necessário informar o valor do frete" )
		#define STR0057 "Este documento precisa receber o valor restante do frete"
		#define STR0058 "O CRT está com valor de frete zerado, verifique antes de prosseguir a operação"
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Não é permitido efectuar carregamento parcial no transporte nacional", "Não é permitido efetuar carregamento parcial no transporte nacional" )
		#define STR0060 "Carregamento Transporte Internacional"
		#define STR0061 "Id do formulário de origem:"
		#define STR0062 "Id do campo de origem:"
		#define STR0063 "Id do formulário de erro:"
		#define STR0064 "Id do campo de erro: "
		#define STR0065 "Id do erro: "
		#define STR0066 "Mensagem do erro: "
		#define STR0067 "Mensagem da solução: "
		#define STR0068 "Valor atribuído: "
		#define STR0069 "Valor anterior: "
		#define STR0070 "Leitura de Cód. de Barras por Documento"
		#define STR0071 "Cód. Barras"
		#define STR0072 "Leitura por Cod.Barras - <F8>"
		#define STR0073 "Leitura por Cod.Barras"
		#define STR0074 "Documentos com criterio de Rateio - "
		#define STR0075 "não podem ser vinculados a uma Rota por Cep/Cliente."
		#define STR0076 "Documento nao poder inserido nesta Viagem pois Lote difere do Lote do Documento!"
		#define STR0077 "CT-e não autorizado ou não enviado para Sefaz."
		#define STR0078 "Documento com Status diferente de 1-Aberto ou 5-Chegada em Filial"
		#define STR0079 "Documento ja carregado"
		#define STR0080 "Erro ao localizar serviço operacional"
		#define STR0081 "Este documento nao pode ser vinculado a uma viagem atraves do carregamento"
		#define STR0082 "A regiao de destino do CTRC nao pertence a regiao da rota"
		#define STR0083 "Erro ao localizar movimento de viagem para o documento"
		#define STR0084 "Documento já está em uma Programação de Carregamento:"
		#define STR0085 "Documento Bloqueado ..."
		#define STR0086 "Para documentos com criterio de Rateio, a Rota deve ficar com conteúdo em branco"
		#define STR0087 "Este Documento nao podera ser carregado pois esta configurado como sendo de 1o. percurso"
		#define STR0088 "Nota fiscal não encontrada !!!"
		#define STR0089 "Chegada em Filial / Cliente"
		#define STR0090 "Ação não pode ser completada, pois os seguintes manifestos possuem cancelamento não transmitido:"
		#define STR0091 "Ação não pode ser completada, pois os seguintes MDF-e posuem encerramento não transmitido:"
	#endif
#endif
