#ifdef SPANISH
	#define STR0001 "Tabla de Horario de Vuelo"
	#define STR0002 "Se opto por cambiar el Codigo de la Region. Esta modificacion limpiara los Aeropuertos ya seleccionados. ¿Continua? "
	#define STR0003 "Proveedor no encontrado"
	#define STR0004 "¡Atencion!"
	#define STR0005 "Aeropuerto de parada no puede ser igual al Aeropuerto de Origen/Destino"
	#define STR0006 "Elija el Aeropuerto"
	#define STR0007 "No existen aeropuertos vinculados a la region: "
	#define STR0008 "Domingo"
	#define STR0009 "Lunes"
	#define STR0010 "Martes"
	#define STR0011 "Miercoles"
	#define STR0012 "Jueves"
	#define STR0013 "Viernes"
	#define STR0014 "Sabado"
	#define STR0015 "Informe "
	#define STR0016 "Elaborando Tabla de Vuelo"
	#define STR0017 "Procesando..."
	#define STR0018 "Tabla de Vuelo"
	#define STR0019 "Semana"
	#define STR0020 "Es obligatorio informar el motivo de desprecio del tiempo de traslado."
	#define STR0021 "¿Desea despreciar el tiempo de Traslado?"
	#define STR0022 "Proveedor: "
	#define STR0023 "Falla en la linea totalizadora de la composicion del flete"
	#define STR0024 "Tabla de flete no encontrada"
	#define STR0025 "Motivo de desprecio del tiempo de traslado"
	#define STR0026 "Buscar"
	#define STR0027 "Visualizar"
	#define STR0028 "Incluir"
	#define STR0029 "Modificar"
	#define STR0030 "Borrar"
	#define STR0031 "Version Protheus"
	#define STR0032 "La version del sistema actual es inferior a 11.5"
	#define STR0033 "¡Actualice el sistema!"
	#define STR0034 "Ok"
#else
	#ifdef ENGLISH
		#define STR0001 "Flight Schedule Grid"
		#define STR0002 "You have chosen to change the Region Code. This change will clear the Airports already selected. Continue? "
		#define STR0003 "Supplier not found"
		#define STR0004 "Attention!"
		#define STR0005 "Stop airport cannot be equal to the Origin/Destination Airport"
		#define STR0006 "Choose Airport"
		#define STR0007 "There are no airports associated to region: "
		#define STR0008 "Sunday"
		#define STR0009 "Monday"
		#define STR0010 "Tuesday"
		#define STR0011 "Wednesday"
		#define STR0012 "Thursday"
		#define STR0013 "Friday"
		#define STR0014 "Saturday"
		#define STR0015 "Enter "
		#define STR0016 "Generating Flight Grid"
		#define STR0017 "Processing..."
		#define STR0018 "Flight Grid"
		#define STR0019 "Week"
		#define STR0020 "You must enter a reason for ignoring the time of transfer."
		#define STR0021 "Do you want to ignore the time of transfer?"
		#define STR0022 "Supplier: "
		#define STR0023 "Fail in total line of the composition of freight"
		#define STR0024 "Freight table not found."
		#define STR0025 "Reason for ignoring time of transfer"
		#define STR0026 "Search"
		#define STR0027 "View"
		#define STR0028 "Add"
		#define STR0029 "Edit"
		#define STR0030 "Delete"
		#define STR0031 "Protheus Version"
		#define STR0032 "Current system version in prior to 11.5"
		#define STR0033 "Update the system!"
		#define STR0034 "OK"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Programação de Horário de Voo", "Grade de Horário de Voo" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Você optou por trocar o Código da Região. Essa alteração irá limpar os Aeroportos já seleccionados. Continua? ", "Você optou por trocar o Codigo da Região. Essa alteração irá limpar os Aeroportos já selecionados. Continua? " )
		#define STR0003 "Fornecedor não encontrado"
		#define STR0004 "Atenção!"
		#define STR0005 "Aeroporto de parada não pode ser igual ao Aeroporto de Origem/Destino"
		#define STR0006 "Escolha o Aeroporto"
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Não existem aeroportos relacionados à região: ", "Não existem aeroportos relacionados a região: " )
		#define STR0008 "Domingo"
		#define STR0009 "Segunda"
		#define STR0010 "Terça"
		#define STR0011 "Quarta"
		#define STR0012 "Quinta"
		#define STR0013 "Sexta"
		#define STR0014 "Sábado"
		#define STR0015 "Informe "
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "A elaborar Programação de Voo", "Elaborando Grade de Voo" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "A processar...", "Processando..." )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Programação de Voo", "Grade de Voo" )
		#define STR0019 "Semana"
		#define STR0020 "É obrigatório informar o motivo por desprezar o tempo de translado."
		#define STR0021 "Deseja desprezar o tempo de Translado?"
		#define STR0022 "Fornecedor: "
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Falha na linha totalizadora da composição do frete", "Falha na linha totalizadora da composicao do frete" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Tabela de frete não encontrada", "Tabela de frete nao encontrada" )
		#define STR0025 "Motivo por desprezar tempo de translado"
		#define STR0026 "Pesquisar"
		#define STR0027 "Visualizar"
		#define STR0028 "Incluir"
		#define STR0029 "Alterar"
		#define STR0030 "Excluir"
		#define STR0031 "Versão Protheus"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "A versão do sistema actual é inferior a 11.5", "Versão do sistema atual é inferior a 11.5" )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Actualize o sistema!", "Atualize o sistema!" )
		#define STR0034 "Ok"
	#endif
#endif
