#ifdef SPANISH
	#define STR0001 "CRT - Conocimiento Internacional"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Incluir"
	#define STR0005 "Modificar"
	#define STR0006 "Borrar"
	#define STR0007 "Imprimir"
	#define STR0008 "Calcula Flete - <F5>"
	#define STR0009 "Calc. Flete"
	#define STR0010 "Servicio: "
	#define STR0011 "Valor del flete en cero"
	#define STR0012 "Falla en la linea totalizadora de la composicion del flete"
	#define STR0013 "CRT"
	#define STR0014 "CRT Grafico"
	#define STR0015 "Leyenda"
	#define STR0016 "Estatus"
	#define STR0017 "Pendiente"
	#define STR0018 "Generado"
	#define STR0019 "Modificado"
	#define STR0020 "Anulado"
	#define STR0021 "Anular"
	#define STR0022 "Recula Flete - <F6>"
	#define STR0023 "Recalc. Flete"
	#define STR0024 "El titulo del documento esta dado de baja o no esta en Cartera"
	#define STR0025 "¡No es posible modificar CRT anulado!"
	#define STR0026 "Sucursal no autorizada para modificar este CRT"
	#define STR0027 "Borrado permitido solamente para documentos con estatus [Pendiente]"
	#define STR0028 "Anulacion permitida solamente para documentos con estatus [Generado] o [Modificado]"
	#define STR0029 "¡No se permite informar productos diferentes para el transporte Internacional!"
	#define STR0030 "¡Documento de transporte "
	#define STR0031 " con el producto "
	#define STR0032 " ya registrado!"
	#define STR0033 "¡Es necesario recalcular el flete!"
	#define STR0034 "¡Total del flete CIF no puede ser cero!"
	#define STR0035 "Porcentaje total del frete por pais diferente del 100%"
	#define STR0036 "¡Datos complementarios no informados!"
	#define STR0037 "¡Aun no se calculo el Flete!"
	#define STR0038 "¿Desea recalcular el flete?"
	#define STR0039 "Si"
	#define STR0040 "No"
	#define STR0041 "¡Flete recalculado con exito!"
	#define STR0042 "Mantenimiento de Documentos - Visualizar"
	#define STR0043 "Componente                      Valor CIF   Valor FOB"
	#define STR0044 "TOTAL DEL FLETE"
	#define STR0045 "Composicion del Flete"
	#define STR0046 "Flete &CIF/FOB"
	#define STR0047 "Flete por &Pais"
	#define STR0048 "NOMBRE Y DIRECCION DEL EMITENTE"
	#define STR0049 "NOMBRE Y DIRECCION DEL DESTINATARIO"
	#define STR0050 "LOCALIDAD Y PAIS DE EMISION"
	#define STR0051 "NOMBRE Y DIRECCION DEL CONSIGNATARIO"
	#define STR0052 "LOCALIDAD DE RESPONSABILIDAD DE LA MERCADERIA"
	#define STR0053 "LOCALIDAD, PAIS Y PLAZO DE ENTREGA"
	#define STR0054 "NOTIFICAR A"
	#define STR0055 "CANTIDAD Y CATEGORIA DE VOLUMENES, MARCAS, NUMEROS"
	#define STR0056 "PESO BRUTO EN Kg"
	#define STR0057 "VOLUMEN EN m3"
	#define STR0058 "VALOR"
	#define STR0059 "GASTOS POR PAGAR - FLETE"
	#define STR0060 "DECLARACION DEL VALOR DE LAS MERCADERIAS"
	#define STR0061 "DOCUMENTOS ADJUNTOS"
	#define STR0062 "INSTRUCCIONES SOBRE FORMALIDADES DE ADUANA"
	#define STR0063 "VALOR DEL FLETE EXTERNO"
	#define STR0064 "VALOR DEL REEMBOLSO CONTRA ENTREGA"
	#define STR0065 "NOMBRE Y FIRMA DEL REMITENTE"
	#define STR0066 "DECLARACIONES Y OBSERVACIONES"
	#define STR0067 "&Factura"
	#define STR0068 "&Datos del C R T"
	#define STR0069 "Datos &Complementarios"
	#define STR0070 "E Recalculo del Flete cambiara el contenido del campo 22"
	#define STR0071 "Generar nuevamente"
	#define STR0072 "Copiar"
	#define STR0073 "No se permite Generar nuevamente un CRT que no se calculo"
	#define STR0074 "No se permite Generar nuevamente un CRT con Carga Parcial"
	#define STR0075 "No se permite borrar un CRT en otra sucursal"
	#define STR0076 "No se permite Anular un CRT que tenga un CRT Complementario relacionado"
	#define STR0077 "Factura ya registrada"
	#define STR0078 "Registrar el Porcentaje de Flete por Pais,"
	#define STR0079 "antes de proseguir con el calculo."
	#define STR0080 "Generado nuevamente"
	#define STR0081 "Confirmar"
	#define STR0082 "Fecha de Correccion"
	#define STR0083 "Documento - <F8>"
	#define STR0084 "Docto."
	#define STR0085 "Carta de Correccion - <F7>"
	#define STR0086 "Carta C."
	#define STR0087 "¡No se permite modificar CRT generado nuevamente!"
	#define STR0088 "Valor informado - <F6>"
	#define STR0089 "Val.Inf."
	#define STR0090 "Tabla de flete no ubicada, ¿desea mostrar todos los componentes del tipo valor informado?"
#else
	#ifdef ENGLISH
		#define STR0001 "CRT - International Knowledge"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Include"
		#define STR0005 "Change"
		#define STR0006 "Exclude"
		#define STR0007 "Print"
		#define STR0008 "Calcullation of Freight - <F5>"
		#define STR0009 "Calc.Freight"
		#define STR0010 "Service: "
		#define STR0011 "Zeroed freight value"
		#define STR0012 "Failure in totalizer line of freight composition"
		#define STR0013 "CRT"
		#define STR0014 "Graphical CRT"
		#define STR0015 "Caption"
		#define STR0016 "Status"
		#define STR0017 "Open"
		#define STR0018 "Generated"
		#define STR0019 "Changed"
		#define STR0020 "Cancelled"
		#define STR0021 "Cancel"
		#define STR0022 "Recalculation of Freight - <F6>"
		#define STR0023 "Recalc.Freight"
		#define STR0024 "Document bill is posted or is not in Portfolio"
		#define STR0025 "Changing CRT canceled is not possible"
		#define STR0026 "Branch not authorized to change this CRT"
		#define STR0027 "Exclusion allowed only for documents with status [Open]"
		#define STR0028 "Cancellation allowed only for documents with status [Generated] or [Changed]"
		#define STR0029 "Indicating different products for international transportation is not allowed!"
		#define STR0030 "Transportation document "
		#define STR0031 " with the product "
		#define STR0032 " already registered!"
		#define STR0033 "Recalculating freight is necessary!"
		#define STR0034 "CIF freight total cannot be zero!"
		#define STR0035 "Total percentage of freight by country - different from 100%"
		#define STR0036 "Complementary data not indicated!"
		#define STR0037 "Freight  was not calculated yet!"
		#define STR0038 "Do you want to recalculate the freight?"
		#define STR0039 "Yes"
		#define STR0040 "No"
		#define STR0041 "Freight successfully recalculated!"
		#define STR0042 "Maintenance of documents - View"
		#define STR0043 "Component                      CIF Value   FOB Value"
		#define STR0044 "FREIGHT TOTAL"
		#define STR0045 "Freight Composition"
		#define STR0046 "CIF/FOB Freight"
		#define STR0047 "Freight by Country"
		#define STR0048 "SENDER'S NAME AND ADDRESS"
		#define STR0049 "RECIPIENT'S NAME AND ADDRESS"
		#define STR0050 "LOCATION AND COUNTRY OF ISSUE"
		#define STR0051 "CONSIGNEE NAME AND ADDRESS"
		#define STR0052 "GOOD RESPONSIBILITY LOCATION"
		#define STR0053 "LOCATION, COUNTRY AND DELIVERY TERM"
		#define STR0054 "NOTIFY "
		#define STR0055 "AMOUNT AND CATEGORY OF VOLUME, BRANDS, NUMBERS"
		#define STR0056 "GROSS WEIGHT IN Kg"
		#define STR0057 "VOLUME IN m3"
		#define STR0058 "VALUE"
		#define STR0059 "PAYABLE EXPENSES - FREIGHT"
		#define STR0060 "STATEMENT OF GOODS VALUE"
		#define STR0061 "ATTACHED DOCUMENTS"
		#define STR0062 "INSTRUCTIONS ABOUT CUSTOMS FORMALITIES"
		#define STR0063 "EXTERNAL FREIGHT VALUE"
		#define STR0064 "REFUND VALUE UPON DELIVERY"
		#define STR0065 "SENDER'S NAME AND SIGNATURE"
		#define STR0066 "STATEMENTS AND OBSERVATIONS"
		#define STR0067 "Invoice"
		#define STR0068 "CRT Data"
		#define STR0069 "Complementary Data"
		#define STR0070 "Freight Recalculation will change the content of field 22"
		#define STR0071 "Regenerate"
		#define STR0072 "Copy"
		#define STR0073 "Regenerating a non-calculated CRT is not allowed"
		#define STR0074 "Regenerating a CRT with Partial Shipment"
		#define STR0075 "Excluding CRT in another branch is not allowed"
		#define STR0076 "Canceling a CRT with a Complementary CRT related is not allowed"
		#define STR0077 "Invoice already registered"
		#define STR0078 "Register the Freight Percentage by Country,"
		#define STR0079 "before proceeding the calculation."
		#define STR0080 "Regenerated"
		#define STR0081 "Confirm"
		#define STR0082 "Correction Letter"
		#define STR0083 "Document - <F8>"
		#define STR0084 "Docum."
		#define STR0085 "Correction Letter - <F7>"
		#define STR0086 "Cor.Let."
		#define STR0087 "You cannot edit Regenerated CRT!"
		#define STR0088 "Entered Value - <F6>"
		#define STR0089 "Ent. Val."
		#define STR0090 "Freight Table not found, do you want to display all component of the value type entered?"
	#else
		#define STR0001 "CRT - Conhecimento Internacional"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Excluir"
		#define STR0007 "Imprimir"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Calcula Frete - <F5>", "Cálcula Frete - <F5>" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Cálc.Frete", "Calc.Frete" )
		#define STR0010 "Serviço: "
		#define STR0011 "Valor do frete zerado"
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Falha na linha totalizadora da composição do frete", "Falha na linha totalizadora da composicao do frete" )
		#define STR0013 "CRT"
		#define STR0014 "CRT Gráfico"
		#define STR0015 "Legenda"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Estado", "Status" )
		#define STR0017 "Em Aberto"
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Criado", "Gerado" )
		#define STR0019 "Alterado"
		#define STR0020 "Cancelado"
		#define STR0021 "Cancelar"
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Novo Cálculo Frete - <F6>", "Recalcula Frete - <F6>" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Novo cálc.Frete", "Recalc.Frete" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "O título do documento está baixado ou não esta em carteira", "O título do documento está baixado ou não esta em Carteira" )
		#define STR0025 "Não é possível alterar CRT cancelado!"
		#define STR0026 "Filial não autorizada para alterar esse CRT"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Exclusão permitida somente para documentos com estado [Em Aberto]", "Exclusão permitida somente para documentos com status [Em Aberto]" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Cancelamento permitido somente para documentos com estado [Criado] ou [Alterado]", "Cancelamento permitido somente para documentos com status [Gerado] ou [Alterado]" )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Não é permitido informar artigos diferentes para o transporte Internacional!", "Não é permitido informar produtos diferentes para o transporte Internacional!" )
		#define STR0030 "Documento de transporte "
		#define STR0031 If( cPaisLoc $ "ANG|PTG", " com o artigo ", " com o produto " )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", " já registado!", " já cadastrado!" )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "É necessário calcular novamente o frete!", "É necessário recalcular o frete!" )
		#define STR0034 "Total do frete CIF não pode ser zero!"
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Percentual total do frete por país diferente de 100%", "Percentual total do frete por pais diferente de 100%" )
		#define STR0036 "Dados complementares não informados!"
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Frete ainda não foi calculado!", "Frete ainda não foi calculado !" )
		#define STR0038 "Deseja recalcular o frete?"
		#define STR0039 "Sim"
		#define STR0040 "Não"
		#define STR0041 "Frete recalculado com sucesso!"
		#define STR0042 "Manutenção de Documentos - Visualizar"
		#define STR0043 "Componente                      Valor CIF   Valor FOB"
		#define STR0044 "TOTAL DO FRETE"
		#define STR0045 "Composição do Frete"
		#define STR0046 "Frete &CIF/FOB"
		#define STR0047 "Frete por &País"
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "NOME E MORADA DO EMETENTE", "NOME E ENDEREÇO DO EMETENTE" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "NOME E MORADA DO DESTINATÁRIO", "NOME E ENDEREÇO DO DESTINATARIO" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "LOCALIDADE E PAÍS DE EMISSÃO", "LOCALIDADE E PAIS DE EMISSAO" )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "NOME E MORADA DO CONSIGNATÁRIO", "NOME E ENDEREÇO DO CONSIGNATARIO" )
		#define STR0052 "LOCALIDADE DE RESPONSABILIDADE DA MERCADORIA"
		#define STR0053 "LOCALIDADE, PAÍS E PRAZO DE ENTREGA"
		#define STR0054 "NOTIFICAR A"
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "QUANTIDADE E CATEGORIA DE VOLUMES, MARCAS, NÚMEROS", "QUANTIDADE E CATEGORIA DE VOLUMES, MARCAS, NUMEROS" )
		#define STR0056 "PESO BRUTO EM Kg"
		#define STR0057 "VOLUME EM m3"
		#define STR0058 "VALOR"
		#define STR0059 "GASTOS A PAGAR - FRETE"
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "DECLARAÇÃO DO VALOR DAS MERCADORIAS", "DECLARACAO DO VALOR DAS MERCADORIAS" )
		#define STR0061 "DOCUMENTOS ANEXOS"
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "INSTRUÇÕES SOBRE FORMALIDADES DE ALFÂNDEGA", "INSTRUCOES SOBRE FORMALIDADES DE ALFANDEGA" )
		#define STR0063 "VALOR DO FRETE EXTERNO"
		#define STR0064 "VALOR DO REEMBOLSO CONTRA ENTREGA"
		#define STR0065 "NOME E ASSINATURA DO REMETENTE"
		#define STR0066 "DECLARAÇÕES E OBSERVAÇÕES"
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "&Factura", "&Fatura" )
		#define STR0068 "&Dados do C R T"
		#define STR0069 "Dados &Complementares"
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "O novo cálculo do frete mudará o conteúdo do campo 22", "O Recalculo do Frete mudara o conteudo do campo 22" )
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Criar novamente", "Regerar" )
		#define STR0072 "Copiar"
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Não é permitido criar novamente um CRT que não foi calculado", "Não é permitido Regerar um CRT que não foi calculado" )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Não é permitido criar novamente um CRT com Carregamento Parcial", "Não é permitido Regerar um CRT com Carregamento Parcial" )
		#define STR0075 "Não é permitido excluir um CRT em outra filial"
		#define STR0076 "Não é permitido Cancelar um CRT que tenha um CRT Complementar relacionado"
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "Fact.Fiscal já cadastrada", "Nota Fiscal já cadastrada" )
		#define STR0078 "Cadastrar o Percentual de Frete por País,"
		#define STR0079 "antes de prosseguir com o cálculo."
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "Criado novamente", "Regerado" )
		#define STR0081 "Confirmar"
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "Carta de Correcção", "Carta de Correção" )
		#define STR0083 "Documento - <F8>"
		#define STR0084 "Docto."
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "Carta de Correcção - <F7>", "Carta de Correcao - <F7>" )
		#define STR0086 "Carta C."
		#define STR0087 "Não é permitido alterar CRT Regerado!"
		#define STR0088 "Valor Informado - <F6>"
		#define STR0089 "Val.Inf."
		#define STR0090 "Tabela de Frete não localizada, deseja apresentar todos componentes do tipo valor informado ?"
	#endif
#endif
