#ifdef SPANISH
	#define STR0001 "Generación cobro servicio adicional"
	#define STR0002 "Visualizar"
	#define STR0003 "Procesar"
	#define STR0004 "Invertir marcación"
	#define STR0005 "Documento del cliente - Visualizar"
	#define STR0006 "Espere..."
	#define STR0007 "Procesando consulta..."
	#define STR0008 "Cliente pagador de flete"
	#define STR0009 "De fecha de emisión de la e-Fact "
	#define STR0010 "A fecha de emisión de la e-Fact"
	#define STR0011 "Ocurrencia"
	#define STR0012 "Servicio"
	#define STR0013 "TES"
	#define STR0014 "Producto fiscal"
	#define STR0015 "Abriendo visualización..."
	#define STR0016 "Fecha de emisión"
	#define STR0017 "Nombre Remit."
	#define STR0018 "Municipio Remit."
	#define STR0019 "Est/Prov/Reg Remit."
	#define STR0020 "Nombre Dest."
	#define STR0021 "Municipio Dest."
	#define STR0022 "Est/Prov/Reg Dest."
	#define STR0023 "Valores acumulados de los documentos seleccionados"
	#define STR0024 "Valores informados por componente de flete"
	#define STR0025 "Tipos de vehículos por componente de flete"
	#define STR0026 "Cant/Valor"
	#define STR0027 "Calcular servicio"
	#define STR0028 "Anular"
	#define STR0029 "Generar documento"
	#define STR0030 "Valores de los componentes de flete"
	#define STR0031 "Tabla de flete"
	#define STR0032 "Totales"
	#define STR0033 "Calculando impuestos..."
	#define STR0034 "Componente de flete de cobro servicio adicional"
	#define STR0035 "Valor calculado"
	#define STR0036 "Digitado"
	#define STR0037 "Calculando composición de flete..."
	#define STR0038 "Comp"
	#define STR0039 "Impuesto"
	#define STR0040 "Digitado + Impuesto"
	#define STR0041 "Generando documento..."
	#define STR0042 "Generando factura de salida..."
	#define STR0043 "Verificando valores de impuestos..."
	#define STR0044 "Grabando lote de facturas (DTP)..."
	#define STR0045 "Grabando documento de transporte (DT6)..."
	#define STR0046 "Grabando composición de flete (DT8)..."
	#define STR0047 "Creando vínculo de factura(s) (DTC) con el documento (DT6)..."
	#define STR0048 "No tiene documento de servicio adicional generado"
	#define STR0049 "Tiene documento de servicio adicional generado para la ocurrencia"
	#define STR0050 "Documentos de servicio adicional"
	#define STR0051 "Docs. Servicio adicional"
	#define STR0052 "Mantenimiento de documentos - Visualizar"
	#define STR0053 "Parámetros"
	#define STR0054 "Anular documento"
	#define STR0055 "Mantenimiento de documentos - Anular"
	#define STR0056 "Abriendo anulación..."
	#define STR0057 "% Val. Proporcional"
	#define STR0058 "Valor proporcional"
	#define STR0059 "Crit. Prorrat. Propor"
	#define STR0060 "Documentos de servicio adicional listados"
	#define STR0061 "Negociacion"
	#define STR0062 "Vis. Documento"
	#define STR0063 "Informaciones fiscales"
	#define STR0064 "Confirmar"
	#define STR0065 "Cerrar"
	#define STR0066 "Ocurrencia disponible para generación de documento de servicio adicional"
#else
	#ifdef ENGLISH
		#define STR0001 "Additional Service Collection Generation"
		#define STR0002 "View"
		#define STR0003 "Process"
		#define STR0004 "Invert selection"
		#define STR0005 "Customer Document - View"
		#define STR0006 "Wait..."
		#define STR0007 "Processing query..."
		#define STR0008 "Freight paying customer"
		#define STR0009 "Date of invoice issue from"
		#define STR0010 "Date of invoice issue to"
		#define STR0011 "Event"
		#define STR0012 "Service"
		#define STR0013 "TIO"
		#define STR0014 "Tax product"
		#define STR0015 "Opening view..."
		#define STR0016 "Issue Date"
		#define STR0017 "Sender Name"
		#define STR0018 "Sender City"
		#define STR0019 "Sender State"
		#define STR0020 "Recip. Name"
		#define STR0021 "Recip. City"
		#define STR0022 "Recip. State"
		#define STR0023 "Accrued values of selected documents"
		#define STR0024 "Values entered by freight component"
		#define STR0025 "Types of vehicles by freight component"
		#define STR0026 "Qty/Value"
		#define STR0027 "Calculate Service"
		#define STR0028 "Cancel"
		#define STR0029 "Generate Document"
		#define STR0030 "Freight Component Values"
		#define STR0031 "Freight table."
		#define STR0032 "Totals"
		#define STR0033 "Calculating Taxes..."
		#define STR0034 "Freight Component of Additional Service Collection"
		#define STR0035 "Calculated Amount"
		#define STR0036 "Entered"
		#define STR0037 "Calculating freight composition..."
		#define STR0038 "Comp"
		#define STR0039 "Tax"
		#define STR0040 "Typed + Tax"
		#define STR0041 "Generating Document..."
		#define STR0042 "Generating Outbound Invoice..."
		#define STR0043 "Checking tax values..."
		#define STR0044 "Saving invoices batch (DTP)..."
		#define STR0045 "Saving transportation document (DT6)..."
		#define STR0046 "Saving freight composition (DT8)..."
		#define STR0047 "Creating bound of invoice(s) (DTC) with document (DT6)..."
		#define STR0048 "No additional service document generated"
		#define STR0049 "Additional service document generated for occurrence"
		#define STR0050 "Additional Service Document"
		#define STR0051 "Additional Service Docs."
		#define STR0052 "Document Maintenance - View"
		#define STR0053 "Parameters"
		#define STR0054 "Cancel Document"
		#define STR0055 "Document Maintenance - Cancel"
		#define STR0056 "Opening cancellation..."
		#define STR0057 "% Proportional Value"
		#define STR0058 "Prop. Value"
		#define STR0059 "Prop. Apportion Crt."
		#define STR0060 "Documents of Additional Services Related"
		#define STR0061 "Negotiation"
		#define STR0062 "View Document"
		#define STR0063 "Fiscal Information"
		#define STR0064 "Confirm"
		#define STR0065 "Close"
		#define STR0066 "Occurrence available for the generation of additional service document"
	#else
		#define STR0001 "Geração Cobrança Serviço Adicional"
		#define STR0002 "Visualizar"
		#define STR0003 "Processar"
		#define STR0004 "Inverter marcação"
		#define STR0005 "Documento do Cliente - Visualizar"
		#define STR0006 "Aguarde..."
		#define STR0007 "Processando consulta..."
		#define STR0008 "Cliente pagador de frete"
		#define STR0009 "Data de emissão NFe de"
		#define STR0010 "Data de emissão NFe até"
		#define STR0011 "Ocorrência"
		#define STR0012 "Serviço"
		#define STR0013 "TES"
		#define STR0014 "Produto fiscal"
		#define STR0015 "Abrindo visualização..."
		#define STR0016 "Data Emissão"
		#define STR0017 "Nome Remet."
		#define STR0018 "Município Remet."
		#define STR0019 "Estado Remet."
		#define STR0020 "Nome Dest."
		#define STR0021 "Município Dest."
		#define STR0022 "Estado Dest."
		#define STR0023 "Valores Acumulados dos Documentos Selecionados"
		#define STR0024 "Valores Informados por Componente de Frete"
		#define STR0025 "Tipos de Veículos por Componente de Frete"
		#define STR0026 "Qtde/Valor"
		#define STR0027 "Calcular Serviço"
		#define STR0028 "Cancelar"
		#define STR0029 "Gerar Documento"
		#define STR0030 "Valores dos Componentes de Frete"
		#define STR0031 "Tabela de Frete"
		#define STR0032 "Totais"
		#define STR0033 "Calculando impostos..."
		#define STR0034 "Componente de Frete de Cobrança Serviço Adicional"
		#define STR0035 "Valor Calculado"
		#define STR0036 "Digitado"
		#define STR0037 "Calculando composição de frete..."
		#define STR0038 "Comp"
		#define STR0039 "Imposto"
		#define STR0040 "Digitado + Imposto"
		#define STR0041 "Gerando documento..."
		#define STR0042 "Gerando Nota Fiscal de Saida..."
		#define STR0043 "Verificando valores de impostos..."
		#define STR0044 "Gravando lote de notas fiscais (DTP)..."
		#define STR0045 "Gravando documento de transporte (DT6)..."
		#define STR0046 "Gravando composição de frete (DT8)..."
		#define STR0047 "Criando vínculo da(s) nota(s) (DTC) com o documento (DT6)..."
		#define STR0048 "Não possui documento de serviço adicional gerado"
		#define STR0049 "Possui documento de serviço adicional gerado para a ocorrência"
		#define STR0050 "Documentos de Serviço Adicional"
		#define STR0051 "Docs. Serviço Adicional"
		#define STR0052 "Manutenção de Documentos - Visualizar"
		#define STR0053 "Parâmetros"
		#define STR0054 "Cancelar Documento"
		#define STR0055 "Manutenção de Documentos - Cancelar"
		#define STR0056 "Abrindo cancelamento..."
		#define STR0057 "% Val.Proporcional"
		#define STR0058 "Valor Proporcional"
		#define STR0059 "Crit.Rat.Propor"
		#define STR0060 "Documentos de Serviço Adicional Relacionados"
		#define STR0061 "Negociação"
		#define STR0062 "Vis. Documento"
		#define STR0063 "Informações Fiscais"
		#define STR0064 "Confirmar"
		#define STR0065 "Fechar"
		#define STR0066 "Ocorrência disponível para geração de documento de serviço adicional"
	#endif
#endif
