#ifdef SPANISH
	#define STR0001 "Declaracion de Carga"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Declarar"
	#define STR0005 "Borrar"
	#define STR0006 "Desea realmente borrar la declaracion "
	#define STR0007 "¿?"
	#define STR0008 "Borrando Declaracion. Por favor espere..."
	#define STR0009 "Sucursal Origen : "
	#define STR0010 "Viaje : "
	#define STR0011 "Declaracion de Carga"
	#define STR0012 "Leyenda"
	#define STR0013 "Pendiente"
	#define STR0014 "Contrato Generado"
	#define STR0015 "Viaje : "
	#define STR0016 "Informe el tipo de separacion de sucursal"
	#define STR0017 "para la declaracion."
	#define STR0018 "¿Separar por Sucursal? "
	#define STR0019 "Informe si debe separar la sucursal "
	#define STR0020 "de origen de los documentos."
	#define STR0021 "¿Separar Sucursal de Origen? "
	#define STR0022 "Descarga"
	#define STR0023 "Destino"
	#define STR0024 "Informe si debe separar por provin-"
	#define STR0025 "cia de la region de calculo."
	#define STR0026 "¿Separar por Provincia? "
	#define STR0027 "Informe si debe separar carga pe-"
	#define STR0028 "ligrosa."
	#define STR0029 "¿Separar Carga Peligrosa? "
	#define STR0030 "¿Separar Regiones Exentas?"
	#define STR0031 "Informe si se debe separar por regiones"
	#define STR0032 "exentas."
	#define STR0033 "¿Imprime Declaracion?"
	#define STR0034 "Informe si Imprime Declaracion"
	#define STR0035 "Imprimir"
	#define STR0036 "¿Separar Region Destino?"
	#define STR0037 "Informe si debe separar region"
	#define STR0038 "destino."
	#define STR0039 "Documentos"
	#define STR0040 "Resumen"
	#define STR0041 "Viaje"
	#define STR0042 "CTRC"
	#define STR0043 "Serie"
	#define STR0044 "Remitente"
	#define STR0045 "i8MDF-e"
	#define STR0046 "DAMDFE"
	#define STR0047 "003 - El e-MDF aun no se trasmitio - espere la transmision."
	#define STR0048 "033 - Cierre de e-MDF no transmitido"
	#define STR0049 "016 - Anulacion de e-MDF no transmitido"
	#define STR0050 "Observacion"
	#define STR0051 "Existen manifiestos pendientes con la misma región de destino. Para manifestar nuevo(s) conocimiento(s) finalice los siguientes Manifiestos: "
	#define STR0052 "Manifiesto de conflicto"
	#define STR0053 "Confirmar"
	#define STR0054 "Anular"
	#define STR0055 "Conocimiento(s) con eMDF finalizado(s) antes de su destino."
	#define STR0056 "Seleccione el(os) Conocimiento(s) que desea incluir en un nuevo eMDF"
	#define STR0057 "Sucursal: "
	#define STR0058 "Solamente documentos con anulación autorizado por la SEFAZ se podrán borrar, realice la transmisión de la anulación antes de continuar."
	#define STR0059 "Manifiesto no generado. Existen documentos no declarados: "
	#define STR0060 "Manifiesto generado, pero existen documentos no declarados: "
	#define STR0061 "No se puede borrar el manifiesto, porque ya se apuntó la operación de salida de la sucursal."
	#define STR0062 "El Manifiesto que se está borrando se generó a partir del proceso de comboy. Por causa de eso, los siguientes Manifiestos también se borrarán:"
	#define STR0063 ". ¿Confirma el borrado de todos los Manifiestos?"
	#define STR0064 "Historial del e-MDF"
	#define STR0065 "Espere"
	#define STR0066 "Procesando..."
	#define STR0067 "Para borrar manifiestos de viajes que están con estatus 'En tránsito' es necesario que el vehículo esté con 'Llegada al cliente o apoyo'."
	#define STR0068 "No se permite generar el Manifiesto para viaje con estatus 'En tránsito' sin el apunte de la operación de  'Llegada al cliente o apoyo'."
	#define STR0069 "horas"
	#define STR0070 "días"
	#define STR0071 "Anulación automática del sistema"
	#define STR0072 "Plazo"
	#define STR0073 "No se permite borrar el manifiesto Plazo para anulación extemporánea del e-MDF no válido."
	#define STR0074 "Verifique el parámetro MV_CEXTMDF"
	#define STR0075 "e-MDF Consulta"
	#define STR0076 "Inclusión Conductor"
#else
	#ifdef ENGLISH
		#define STR0001 "Cargo Manifest"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Manifest  "
		#define STR0005 "Delete "
		#define STR0006 "Do you really want to delete the manifest "
		#define STR0007 "TOTAL"
		#define STR0008 "Deleting Manifest. Please, wait..."
		#define STR0009 "Branch of Origin: "
		#define STR0010 "Trip : "
		#define STR0011 "Cargo Manifest"
		#define STR0012 "Legend"
		#define STR0013 "Pending"
		#define STR0014 "Contract Generated"
		#define STR0015 "Trip : "
		#define STR0016 "FOB"
		#define STR0017 "CIF"
		#define STR0018 "Blank "
		#define STR0019 "Status"
		#define STR0020 "CTRCs Nbr."
		#define STR0021 "Weight charged"
		#define STR0022 "Volumes"
		#define STR0023 "ICMS amount"
		#define STR0024 "Taxed amount "
		#define STR0025 "Non-taxed amount "
		#define STR0026 "Freight amount"
		#define STR0027 "Destination branch"
		#define STR0028 "Origin branch"
		#define STR0029 "Frght type"
		#define STR0030 "Value of merchandise"
		#define STR0031 "Charged weight"
		#define STR0032 "Actual weight"
		#define STR0033 "Vols."
		#define STR0034 "State"
		#define STR0035 "Print   "
		#define STR0036 "City"
		#define STR0037 "Addressee "
		#define STR0038 "State registration"
		#define STR0039 "Documents"
		#define STR0040 "Summar"
		#define STR0041 "Trip "
		#define STR0042 "CTRC"
		#define STR0043 "Series"
		#define STR0044 "Sender "
		#define STR0045 "MDF-e"
		#define STR0046 "DAMDFE"
		#define STR0047 "003 - MDF-e is not yet sent - wait for the transmission"
		#define STR0048 "033 - Termination of MDF-e not sent"
		#define STR0049 "016 - Cancellation of MDF-e not sent"
		#define STR0050 "Note"
		#define STR0051 "There are pending Manifests with the same destination region. To manifest new knowledge, close the Manifests below: "
		#define STR0052 "Conflicting Manifest"
		#define STR0053 "Confirm"
		#define STR0054 "Cancel"
		#define STR0055 "Knowledge with MDF-e closed before of its destination."
		#define STR0056 "Select the Knowledge you want add in a new MDF-e"
		#define STR0057 "Branch: "
		#define STR0058 "Only document with cancellation authorized by SEFAZ can be deleted. Transmit cancellation before continuing."
		#define STR0059 "Manifest not generated. There are unregistered documents: "
		#define STR0060 "Manifest generated, but there are unregistered documents: "
		#define STR0061 "Unable to delete the manifest, as output operation of the Branch has already been registered."
		#define STR0062 "Packing List being deleted was generated from convoy process. Because of this, these Packing Lists are also deleted: "
		#define STR0063 ". Confirm deletion of all Packing Lists?"
		#define STR0064 "MDF-e History"
		#define STR0065 "Wait"
		#define STR0066 "Processing..."
		#define STR0067 "To delete travel manifests with 'In Transit' status, the vehicle must have 'Arrive at Customer or Support'."
		#define STR0068 "You cannot generate the Manifest for the trip with status 'In Transit' without the annotation of the Operation 'Arrival in the Customer or Support'."
		#define STR0069 "hours"
		#define STR0070 "days"
		#define STR0071 "Automatic System Cancellation"
		#define STR0072 "Term"
		#define STR0073 "Unable to delete manifest. Period for late cancellation of the MDF-e is not valid."
		#define STR0074 "Check parameter MV_CEXTMDF"
		#define STR0075 "MDF-e Query"
		#define STR0076 "Driver Addition"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Manifesto De Carga", "Manifesto de Carga" )
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Manifestar"
		#define STR0005 "Excluir"
		#define STR0006 "Deseja realmente excluir o manifesto "
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Total", "TOTAL" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Excluindo manifesto. por favor aguarde...", "Excluindo Manifesto. Por favor aguarde..." )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Filial origem : ", "Filial Origem : " )
		#define STR0010 "Viagem : "
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Manifesto De Carga", "Manifesto de Carga" )
		#define STR0012 "Legenda"
		#define STR0013 "Em Aberto"
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Contrato Criado", "Contrato Gerado" )
		#define STR0015 "Viagem : "
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Fob", "FOB" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Cif", "CIF" )
		#define STR0018 "Em Branco"
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Estado", "Status" )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "No. Ctrcs", "No. CTRCs" )
		#define STR0021 "Peso Cobrado"
		#define STR0022 "Volumes"
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Valor Icms", "Valor ICMS" )
		#define STR0024 "Valor Tributavel"
		#define STR0025 "Valor N. Tributavel"
		#define STR0026 "Valor Frete"
		#define STR0027 "Filial Dest."
		#define STR0028 "Filial Orig."
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Tp.frete", "Tp.Frete" )
		#define STR0030 "Valor Merc."
		#define STR0031 "Peso Cob."
		#define STR0032 "Peso Real"
		#define STR0033 "Vols."
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Uf", "UF" )
		#define STR0035 "Imprimir"
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Concelho", "Cidade" )
		#define STR0037 "Destinatário"
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Insc.estadual", "Insc.Estadual" )
		#define STR0039 "Documentos"
		#define STR0040 "Resumo"
		#define STR0041 "Viagem"
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Ctrc", "CTRC" )
		#define STR0043 "Série"
		#define STR0044 "Remetente"
		#define STR0045 "MDF-e"
		#define STR0046 "DAMDFE"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "003 - O MDF-e ainda não foi transmitido - aguarde a transmissão", "003 - O MDF-e ainda não foi transmitido - aguarde a transmissao" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "033 - Encerramento do MDF-e não transmitido", "033 - Encerramento do MDF-e nao transmitido" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "016 - Cancelamento do MDF-e não transmitido", "016 - Cancelamento do MDF-e nao transmitido" )
		#define STR0050 "Observação"
		#define STR0051 "Existem Manifestos em aberto com a mesma região de destino. Para manifestar novo(s) conhecimento(s) encerre os Manifestos abaixo: "
		#define STR0052 "Manifesto Conflitantes"
		#define STR0053 "Confirmar"
		#define STR0054 "Cancelar"
		#define STR0055 "Conhecimento(s) com MDF-e encerrado(s) antes do seu destino."
		#define STR0056 "Selecione o(s) Conhecimento(s) que deseja incluir em um novo MDF-e"
		#define STR0057 "Filial: "
		#define STR0058 "Somente documentos com cancelamento autorizado pela SEFAZ poderão ser excluídos, realize a transmissão do cancelamento antes de continuar."
		#define STR0059 "Manifesto não gerado. Existem documentos não averbados : "
		#define STR0060 "Manifesto gerado, porém existem documentos não averbados : "
		#define STR0061 "Não é possível excluir o manifesto, pois já foi apontada a operação de saída da Filial."
		#define STR0062 "O Manifesto que esta sendo excluído foi gerado a partir de processo de comboio. Por conta disso, os Manifestos a seguir também serão excluidos: "
		#define STR0063 ". Confirma a exclusão de todos os Manifestos?"
		#define STR0064 "Histórico do MDF-e"
		#define STR0065 "Aguarde"
		#define STR0066 "Processando..."
		#define STR0067 "Para excluir manifestos de viagens que estão com status 'Em Trânsito' é necessário que o veículo esteja com 'Chegada em Cliente ou Apoio'."
		#define STR0068 "Não é permitido gerar o Manifesto para viagem com status 'Em Trânsito' sem o apontamento da Operação de 'Chegada em Cliente ou Apoio'."
		#define STR0069 "horas"
		#define STR0070 "dias"
		#define STR0071 "Cancelamento Automático do Sistema"
		#define STR0072 "Prazo"
		#define STR0073 "Não é permitido excluir o manifesto. Prazo para cancelamento extemporâneo do MDF-e inválido."
		#define STR0074 "Verifique o parâmetro MV_CEXTMDF "
		#define STR0075 "MDF-e Consulta"
		#define STR0076 "Inclusão Condutor"
	#endif
#endif
