#ifdef SPANISH
	#define STR0001 "Monitor - (MDF-e) Manifiesto Electronico Electronico"
	#define STR0002 "Marca/Desmarca Todos"
	#define STR0003 "Fch Manifiesto"
	#define STR0004 "Hr Manifiesto"
	#define STR0005 "Suc. Manif."
	#define STR0006 "Manifiesto"
	#define STR0007 "Suc. Origen"
	#define STR0008 "Viaje"
	#define STR0009 "Retorno Envio da Sefaz"
	#define STR0010 "Retorno Encto da Sefaz"
	#define STR0011 "DAMDFE"
	#define STR0012 "Leyenda"
	#define STR0013 "Monitor"
	#define STR0014 "Estatus de e-MDF"
	#define STR0015 "Transmitir"
	#define STR0016 "Estatus"
	#define STR0017 "Buscar"
	#define STR0018 "Visualizar"
	#define STR0019 "Refresh"
	#define STR0020 "Parametros"
	#define STR0021 "Salir"
	#define STR0022 "La cantidad de registros excede lo maximo permitido por el Monitor del e-MDF, se mostraran: 32600 registros."
	#define STR0023 "¡No existen documentos marcados para transmitir!"
	#define STR0024 "ATENCION"
	#define STR0025 "¿Confirma transmision de documentos marcados?"
	#define STR0026 "Documento con Falla de Comunicacion"
	#define STR0027 "¡No existen documentos marcados para solicitar estatus!"
	#define STR0028 "¡Ningun documento marcado fue transmitido!"
	#define STR0029 "¿Confirma solicitud de estatus de documentos marcados?"
	#define STR0030 "No transmitido"
	#define STR0031 "Manifiesto Aguardando"
	#define STR0032 "MDF. Autorizado"
	#define STR0033 "MDF. No Autorizado"
	#define STR0034 "MDF. con Falla en la Comunicacion"
	#define STR0035 "Encuesta"
	#define STR0036 "OK"
	#define STR0037 "Tamano del XML de Datos superior a 500 Kbytes."
	#define STR0038 "Verifique el Manifiesto "
	#define STR0039 "¡Ejecute el modulo de configuracion del servicio, antes de utilizar esta opcion!!!"
	#define STR0040 "Las siguientes manifiestos se rechazaron, verifique la rutina 'Monitor' para saber los motivos."
	#define STR0041 "Manifiesto de Carga"
	#define STR0042 "Produccion"
	#define STR0043 "Homologacion"
	#define STR0044 "Normal"
	#define STR0045 "Contingencia"
	#define STR0046 "Configuracion realizada con exito"
	#define STR0047 "Hubo un error durante la configuracion"
	#define STR0048 "1-Producción"
	#define STR0049 "2-Homologación"
	#define STR0050 "Version del layout"
	#define STR0051 "Version del layout del evento"
	#define STR0052 "Version del evento"
	#define STR0053 "1-Normal"
	#define STR0054 "2-Contingencia"
	#define STR0055 "Entorno"
	#define STR0056 "Modalidad"
	#define STR0057 "¡Ejecute el modulo de configuracion del servicio, antes de utilizar esta opcion!!!"
	#define STR0058 "Serie de la factura"
	#define STR0059 "Documento Inicial"
	#define STR0060 "Documento Final"
	#define STR0061 "Ningun registro para monitoreo"
	#define STR0062 "e-MDF Encerrado"
	#define STR0063 "Retorno anulacion de la Sefaz"
	#define STR0064 "Serie"
	#define STR0065 "Retorno SEFAZ Inclusion de conductor"
	#define STR0066 "Salir"
	#define STR0067 "Exportar Excel"
	#define STR0068 "Consulta de e-MDF no finalizados"
	#define STR0069 "Efectuando consulta, espere..."
	#define STR0070 "Procesando"
	#define STR0071 "¡La versión del TSS debe ser igual o superior a 2.43!"
	#define STR0072 "Conductor"
	#define STR0073 "Nombre del conductor"
	#define STR0074 "¿Archivo con XML aún no se devolvió por NeoGrid, reprocesar o intentar más tarde?"
	#define STR0075 "Archivo no se devolvió, contacte al soporte, o intente más tarde."
	#define STR0076 "Manifiesto electrónico de documentos fiscales"
	#define STR0077 "Asistente de exportación para archivos XML"
	#define STR0078 "Serie del e-MDF"
	#define STR0079 "e-MDF Inicial"
	#define STR0080 "e-MDF Final"
	#define STR0081 "Esta rutina tiene como objetivo ayudarlo en la  exportación del Manifiesto electrónico de documentos fiscales para archivos en el formato XML"
	#define STR0082 "Pulse en Avanzar para dar continuidad al proceso de exportación de archivos."
	#define STR0083 "Espere, exportando archivos"
	#define STR0084 "Ningún registro encontrado."
	#define STR0085 "No fue posible crear el archivo."
	#define STR0086 "Debe informarse un directorio."
	#define STR0087 "Directorio de destino de los archivos exportados"
	#define STR0088 "Exportar"
	#define STR0089 "Versión del manifiesto"
	#define STR0090 "Horario de verano"
	#define STR0091 "UTC"
	#define STR0092 "1-Si"
	#define STR0093 "2-No"
	#define STR0094 "1-Fernando de Noronha"
	#define STR0095 "2-Brasilia"
	#define STR0096 "3-Manaus"
	#define STR0097 "4-Acre"
	#define STR0098 "Para utilizar el e-MDF en la Serie 3, es necesario ejecutar los updates TMSA11R159, TMSA11R131 y TMSA11R155"
	#define STR0099 "UPDATE del TOTVS Colaboración 2.0 no aplicado. Desactivado el uso del TOTVS Colaboración 2.0"
	#define STR0100 "Cant. de Documentos marcados: "
	#define STR0101 "Cant. Total de documentos: "
	#define STR0102 "Transmitiendo documentos..."
	#define STR0103 "Solicitando estatus de los documentos..."
	#define STR0104 "Utilizar opción Monitor para TOTVS Colaboración."
	#define STR0105 "¿Desea interrumpir el procesamiento?"
	#define STR0106 "Exportar antiguos"
	#define STR0107 "Retorno Finalización/ Anulación del Fisco"
	#define STR0108 "Contrato de transportista"
	#define STR0109 "Devolución del evento Pago SEFAZ"
	#define STR0110 "Estatus del evento de pago"
	#define STR0111 "Evento vinculado con éxito"
	#define STR0112 "Preparado para transmisión"
	#define STR0113 "Envío de evento realizado"
	#define STR0114 "Evento rechazado"
	#define STR0115 "Anulación automática del sistema"
	#define STR0116 "Borrando manifiesto. Por favor, espere..."
	#define STR0117 "Processando MDF-e "
#else
	#ifdef ENGLISH
		#define STR0001 "Monitor - (MDF-e) Electronic Manifest"
		#define STR0002 "Check/Uncheck All"
		#define STR0003 "Dt Manifest"
		#define STR0004 "Tm Manifest"
		#define STR0005 "Manif.Branch"
		#define STR0006 "Manifest"
		#define STR0007 "Bran. Source"
		#define STR0008 "Trip"
		#define STR0009 "Return Sending of Sefaz"
		#define STR0010 "Return Forward of Sefaz"
		#define STR0011 "DAMDFE"
		#define STR0012 "Caption"
		#define STR0013 "Monitor"
		#define STR0014 "MDF-e status"
		#define STR0015 "Send"
		#define STR0016 "Status"
		#define STR0017 "Search"
		#define STR0018 "View"
		#define STR0019 "Refresh"
		#define STR0020 "Parameters"
		#define STR0021 "Exit"
		#define STR0022 "The number of records exceeds the maximum allowed by MDF-e Monitor will be displayed: 32600 registers."
		#define STR0023 "There are no documents selected to send!"
		#define STR0024 "ATTENTION"
		#define STR0025 "Confirm transmission of selected documents?"
		#define STR0026 "Document with Communication Failure"
		#define STR0027 "There are no documents selected to request status!"
		#define STR0028 "No document selected was sent!"
		#define STR0029 "Confirm status request of documents selected?"
		#define STR0030 "Not sent"
		#define STR0031 "Waiting Manifest"
		#define STR0032 "MDF. Authorized"
		#define STR0033 "MDF. Not Authorized"
		#define STR0034 "MDF. with Communication Failure"
		#define STR0035 "Search"
		#define STR0036 "OK"
		#define STR0037 "Size of Data XML is larger than 500 Kbytes."
		#define STR0038 "Check Manifest "
		#define STR0039 "Run the service configuration module before using this option!"
		#define STR0040 "The Manifests below were rejected, check Monitor routine to learn about the reasons."
		#define STR0041 "Cargo Manifest"
		#define STR0042 "Production"
		#define STR0043 "Approval"
		#define STR0044 "Regular"
		#define STR0045 "Contingency"
		#define STR0046 "Configuration successfully made"
		#define STR0047 "Failure during configuration"
		#define STR0048 "1-Production"
		#define STR0049 "2-Homologation"
		#define STR0050 "Layout version"
		#define STR0051 "Event layout version"
		#define STR0052 "Event version"
		#define STR0053 "1-Regular"
		#define STR0054 "2-Contingency"
		#define STR0055 "Environment"
		#define STR0056 "Mode"
		#define STR0057 "Run the service configuration module before using this option!"
		#define STR0058 "Invoice series"
		#define STR0059 "Initial Document"
		#define STR0060 "Final Document"
		#define STR0061 "No register to be monitored"
		#define STR0062 "MDF-e Finished"
		#define STR0063 "Return of Sefaz Cancellation"
		#define STR0064 "Series"
		#define STR0065 "SEFAZ Return Addition of Driver"
		#define STR0066 "Exit"
		#define STR0067 "Export Excel"
		#define STR0068 "MDF-e query not closed"
		#define STR0069 "Query, wait..."
		#define STR0070 "Processing"
		#define STR0071 "TSS Version must be equal to or later than 2.43!"
		#define STR0072 "Driver"
		#define STR0073 "Driver Name"
		#define STR0074 "NeoGrid did not return file with XML, reprocess or try it later?"
		#define STR0075 "File not returned, contact support or try later."
		#define STR0076 "Electronic Manifest of Tax Documents"
		#define STR0077 "Export wizard for XML files"
		#define STR0078 "MDF-e Series"
		#define STR0079 "Initial MDF-e"
		#define STR0080 "Final MDF-e"
		#define STR0081 "This routine aims at helping you during the export of Electronic Manifest of Tax Documents to files in XML format."
		#define STR0082 "Click Next to continue the file export process"
		#define STR0083 "Wait, exporting files"
		#define STR0084 "No record found."
		#define STR0085 "Unable to create file."
		#define STR0086 "Enter a new directory"
		#define STR0087 "Target directory of exported files"
		#define STR0088 "Export"
		#define STR0089 "Manifest Version"
		#define STR0090 "Daylight savings Time:"
		#define STR0091 "UTC"
		#define STR0092 "1-Yes"
		#define STR0093 "2-No"
		#define STR0094 "1-Fernando de Noronha"
		#define STR0095 "2-Brasilia"
		#define STR0096 "3-Manaus"
		#define STR0097 "4-Acre"
		#define STR0098 "To use the MDFe in the Series 3, run the updates TMSA11R159, TMSA11R131 AND TMSA11R155"
		#define STR0099 "UPDATE of TOTVS Collaboration 2.0 not applied. Deactivated TOTVS Collaboration 2.0 use"
		#define STR0100 "Qty. of Selected Documents: "
		#define STR0101 "Total Quantity of Documents: "
		#define STR0102 "Sending documents"
		#define STR0103 "Requesting status of documents..."
		#define STR0104 "Use Monitor option for TOTVS Collaboration."
		#define STR0105 "Do you want to interrupt processing?"
		#define STR0106 "Export old ones"
		#define STR0107 "Sefaz Closg/Cancellation Return"
		#define STR0108 "Carrier Contract"
		#define STR0109 "SEFAZ Payment Event Return"
		#define STR0110 "Payment Event Status"
		#define STR0111 "Event linked successfully"
		#define STR0112 "Ready for Transmission"
		#define STR0113 "Event Sent"
		#define STR0114 "Event rejected"
		#define STR0115 "Automatic System Cancellation"
		#define STR0116 "Deleting Manifest. Wait..."
		#define STR0117 "Processing MDF-e"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Monitor - (MDF-e) Manifesto Electrónico", "Monitor - (MDF-e) Manifesto Eletronico Eletrônico" )
		#define STR0002 "Marca/Desmarca Todos"
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Dt.Manifesto", "Dt Manifesto" )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Hr.Manifesto", "Hr Manifesto" )
		#define STR0005 "Fil. Manif."
		#define STR0006 "Manifesto"
		#define STR0007 "Fil. Origem"
		#define STR0008 "Viagem"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Retorno envio da Sefaz", "Retorno Envio da Sefaz" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Retorno enc. da Sefaz", "Retorno Encto da Sefaz" )
		#define STR0011 "DAMDFE"
		#define STR0012 "Legenda"
		#define STR0013 "Monitor"
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Estado do MDF-e", "Status do MDF-e" )
		#define STR0015 "Transmitir"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Estado", "Status" )
		#define STR0017 "Pesquisar"
		#define STR0018 "Visualizar"
		#define STR0019 "Refresh"
		#define STR0020 "Parâmetros"
		#define STR0021 "Sair"
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "A quantidade de registos excede o máximo permitido pelo Monitor do MDF-e. Serão exibidos: 32600 registos.", "A quantidade de registros excede o máximo permitido pelo Monitor do MDF-e, serão exibidos: 32600 registros." )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Não existem documentos marcados para transmissão.", "Não existem documentos marcados para transmitir!" )
		#define STR0024 "ATENÇÃO"
		#define STR0025 "Confirma transmissão dos documentos marcados?"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Documento com falha de comunicação", "Documento com Falha de Comunicação" )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Não existem documentos marcados para solicitar estado.", "Não existem documentos marcados para solicitar status!" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Nenhum documento marcado foi transmitido.", "Nenhum documento marcado foi transmitido!" )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Confirma solicitação de estado dos documentos marcados?", "Confirma solicitação de status dos documentos marcados?" )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Não transmitido", "Não Transmitido" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Manifesto a aguardar", "Manifesto Aguardando" )
		#define STR0032 "MDF. Autorizado"
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "MDF. não autorizado", "MDF. Não Autorizado" )
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "MDF. com falha na comunicação", "MDF. com Falha na Comunicação" )
		#define STR0035 "Pesquisa"
		#define STR0036 "OK"
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Tamanho do XML de dados superior a 500 Kbytes.", "Tamanho do XML de Dados superior a 500 Kbytes." )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Verifique o manifesto ", "Verifique o Manifesto " )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Execute o módulo de configuração do serviço antes de utilizar esta opção.", "Execute o módulo de configuração do serviço, antes de utilizar esta opção!!!" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Os manifestos abaixo foram recusados. Verifique no procedimento 'Monitor' para saber os motivos.", "Os manifestos abaixo foram recusados, verifique na rotina 'Monitor' para saber os motivos." )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Manifesto de carga", "Manifesto de Carga" )
		#define STR0042 "Produção"
		#define STR0043 "Homologação"
		#define STR0044 "Normal"
		#define STR0045 "Contingência"
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Configuração efectuada com sucesso", "Configuração efetuada com sucesso" )
		#define STR0047 "Houve um erro durante a configuracão"
		#define STR0048 "1-Producao"
		#define STR0049 "2-Homologacao"
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Versão do layout", "Versão do leiaute" )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Versão do layout do evento", "Versão do leiaute do evento" )
		#define STR0052 "Versão do evento"
		#define STR0053 "1-Normal"
		#define STR0054 "2-Contingência"
		#define STR0055 "Ambiente"
		#define STR0056 "Modalidade"
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Execute o módulo de configuração do serviço antes de utilizar esta opção.", "Execute o módulo de configuração do serviço, antes de utilizar esta opção!!!" )
		#define STR0058 If( cPaisLoc $ "ANG|PTG", "Série da factura", "Serie da nota fiscal" )
		#define STR0059 If( cPaisLoc $ "ANG|PTG", "Documento inicial", "Documento Inicial" )
		#define STR0060 If( cPaisLoc $ "ANG|PTG", "Documento final", "Documento Final" )
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Nenhum registo para monitorar", "Nenhum registro à monitorar" )
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "MDF-e encerrado", "MDF-e Encerrado" )
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "Retorno cancelamento da Sefaz", "Retorno Cancelamento da Sefaz" )
		#define STR0064 "Serie"
		#define STR0065 "Retorno SEFAZ Inclusão de Condutor"
		#define STR0066 "Sair"
		#define STR0067 "Exportar Excel"
		#define STR0068 "Consulta de MDF-e não encerrados"
		#define STR0069 "Efetuando consulta, aguarde..."
		#define STR0070 "Processando"
		#define STR0071 "A versão do TSS deve ser igual ou superior a 2.43!"
		#define STR0072 "Motorista"
		#define STR0073 "Nome Motorista"
		#define STR0074 "Arquivo com XML ainda não foi retornado pela NeoGrid, reprocessar ou tentar mais tarde?"
		#define STR0075 "Arquivo não foi retornado, entre em contato com o suporte, ou tente mais tarde."
		#define STR0076 "Manifesto Eletrônico de Documentos Fiscais"
		#define STR0077 "Assistente de Exportação para arquivos XML"
		#define STR0078 "Série do MDF-e"
		#define STR0079 "MDF-e Inicial"
		#define STR0080 "MDF-e Final"
		#define STR0081 "Esta rotina tem como objetivo auxilia-lo na exportação do Manifesto Eletrônico de Documentos Fiscais para arquivos no formato XML"
		#define STR0082 "Pressione Avançar para dar continuidade no processo de exportação para arquivos"
		#define STR0083 "Aguarde, exportando arquivos"
		#define STR0084 "Nenhum registro encontrado."
		#define STR0085 "Não foi possível criar o arquivo."
		#define STR0086 "Deve ser informado um diretório."
		#define STR0087 "Diretório de destino dos arquivos exportados"
		#define STR0088 "Exportar"
		#define STR0089 "Versão do Manifesto"
		#define STR0090 "Horário de Verão"
		#define STR0091 "UTC"
		#define STR0092 "1-Sim"
		#define STR0093 "2-Nao"
		#define STR0094 "1-Fernando de Noronha"
		#define STR0095 "2-Brasilia"
		#define STR0096 "3-Manaus"
		#define STR0097 "4-Acre"
		#define STR0098 "Para a utilização do MDFe no Serie 3 e necessário rodar os updates TMSA11R159, TMSA11R131 e TMSA11R155"
		#define STR0099 "UPDATE do TOTVS Colaboração 2.0 não aplicado. Desativado o uso do TOTVS Colaboração 2.0"
		#define STR0100 "Qtde. de Documentos Marcados: "
		#define STR0101 "Qtde. Total de Documentos: "
		#define STR0102 "Transmitindo documentos..."
		#define STR0103 "Solicitando status dos documentos..."
		#define STR0104 "Utilizar opção Monitor para TOTVS Colaboração."
		#define STR0105 "Deseja interromper o processamento?"
		#define STR0106 "Exportar Antigos"
		#define STR0107 "Retorno Encto/Cancelamento da Sefaz"
		#define STR0108 "Contrato Carreteiro"
		#define STR0109 "Retorno do Evento  Pagamento SEFAZ"
		#define STR0110 "Status do Evento de Pagamento"
		#define STR0111 "Evento Vinculado com sucesso"
		#define STR0112 "Preparado para Transmissão"
		#define STR0113 "Envio Evento Realizado"
		#define STR0114 "Evento rejeitado"
		#define STR0115 "Cancelamento Automático do Sistema"
		#define STR0116 "Excluindo Manifesto. Por favor aguarde..."
		#define STR0117 "Processando MDF-e "
	#endif
#endif
