#ifdef SPANISH
	#define STR0001 "No fue posible registrar el(los) siguiente(s) documentos(s) :"
	#define STR0002 "Monitor de confirmación"
	#define STR0003 "De Fecha de Emisión   "
	#define STR0004 "A Fecha de Emisión  "
	#define STR0005 "Visualizar"
	#define STR0006 "Transmitir"
	#define STR0007 "Marca/Desmarca Pendientes"
	#define STR0008 "Actualice datos en la pantalla"
	#define STR0009 "Comprobación"
	#define STR0010 "Esperando registro"
	#define STR0011 "Falla de comunicación"
	#define STR0012 "Documentos comprobados"
	#define STR0013 "Documentos rechazados"
	#define STR0014 "Esperando anulación"
	#define STR0015 "Falla Comunic. Anul."
	#define STR0016 "Documento anulado"
	#define STR0017 "Anulación recusada"
	#define STR0018 "Anul. Ant. comprobación"
	#define STR0019 "Sucursal"
	#define STR0020 "Estatus de la declaración"
	#define STR0021 "Estatus de anulación de la declaración"
	#define STR0022 "Esperando registro"
	#define STR0023 "Falla de comunicación"
	#define STR0024 "Declaración"
	#define STR0025 "Rechazado"
	#define STR0026 "Esperando anulación"
	#define STR0027 "Falla de comunicación para anulación"
	#define STR0028 "Registro anulado"
	#define STR0029 "Anulación recusada"
	#define STR0030 "Documento anulado antes de la declaración"
	#define STR0031 "Leyenda"
	#define STR0032 "Parámetros"
	#define STR0033 "Refresh"
	#define STR0034 "No existen documentos seleccionados para transmitir."
	#define STR0035 "Espere"
	#define STR0036 "Procesando marcación de los documentos..."
	#define STR0037 "Actualizando exhibición de la información..."
	#define STR0038 "Transmitiendo documentos..."
	#define STR0039 "Limite de sucursales excedido"
	#define STR0040 "Utilice la opción Marcar / Desmarcar para seleccionar todas las sucursales."
	#define STR0041 "Seleccione el tipo de documento"
	#define STR0042 "Confirmar"
	#define STR0043 "Anular"
	#define STR0044 "Seleccione las sucursales"
	#define STR0045 "Marque/Desmarque todos"
#else
	#ifdef ENGLISH
		#define STR0001 "Unable to register the following documents"
		#define STR0002 "Registration monitor"
		#define STR0003 "Issue date from   "
		#define STR0004 "Issue date to  "
		#define STR0005 "View"
		#define STR0006 "Send"
		#define STR0007 "Check/Uncheck pending items"
		#define STR0008 "Update data on screen"
		#define STR0009 "Registration"
		#define STR0010 "Waiting for registration"
		#define STR0011 "Communication failure"
		#define STR0012 "Registered documents"
		#define STR0013 "Rejected documents"
		#define STR0014 "Waiting for cancellation"
		#define STR0015 "Canc communic failure"
		#define STR0016 "Canceled Document"
		#define STR0017 "Cancellation refused"
		#define STR0018 "Prev registration cancel."
		#define STR0019 "Branch"
		#define STR0020 "Registration status"
		#define STR0021 "Registration cancellation status"
		#define STR0022 "Waiting for registration"
		#define STR0023 "Communication failure"
		#define STR0024 "Registered"
		#define STR0025 "Rejected"
		#define STR0026 "Waiting for cancellation"
		#define STR0027 "Cancellation communication failure"
		#define STR0028 "Registration canceled"
		#define STR0029 "Cancellation refused"
		#define STR0030 "Document canceled before registration"
		#define STR0031 "Caption"
		#define STR0032 "Parameters"
		#define STR0033 "Refresh"
		#define STR0034 "No documents selected to send"
		#define STR0035 "Wait"
		#define STR0036 "Processing document selection"
		#define STR0037 "Updating information display"
		#define STR0038 "Sending documents"
		#define STR0039 "Limit of branches exceeded"
		#define STR0040 "Use option Flag/Unflag to select all branches."
		#define STR0041 "Select document type"
		#define STR0042 "Confirm"
		#define STR0043 "Cancel"
		#define STR0044 "Select the Branches"
		#define STR0045 "Flag/ Unflag All"
	#else
		#define STR0001 "Não foi possível averbar o(s) seguinte(s) documentos(s) :"
		#define STR0002 "Monitor de Averbação"
		#define STR0003 "Data de emissão de   "
		#define STR0004 "Data de emissão até  "
		#define STR0005 "Visualizar"
		#define STR0006 "Transmitir"
		#define STR0007 "Marcar/Desmarcar Pendentes"
		#define STR0008 "Atualizar dados na tela"
		#define STR0009 "Averbação"
		#define STR0010 "Aguardando averbação"
		#define STR0011 "Falha de comunicação"
		#define STR0012 "Documentos averbados"
		#define STR0013 "Documentos recusados"
		#define STR0014 "Aguardando cancelamento"
		#define STR0015 "Falha Comunic. Canc."
		#define STR0016 "Documento cancelado"
		#define STR0017 "Cancelamento recusado"
		#define STR0018 "Cancel. Ant. averbação"
		#define STR0019 "Filial"
		#define STR0020 "Status de averbação"
		#define STR0021 "Status de cancelamento de averbação"
		#define STR0022 "Aguardando averbação"
		#define STR0023 "Falha de comunicação"
		#define STR0024 "Averbado"
		#define STR0025 "Recusado"
		#define STR0026 "Aguardando cancelamento"
		#define STR0027 "Falha de comunicação para cancelamento"
		#define STR0028 "Averbação cancelada"
		#define STR0029 "Cancelamento recusado"
		#define STR0030 "Documento cancelado antes da averbação"
		#define STR0031 "Legenda"
		#define STR0032 "Parâmetros"
		#define STR0033 "Refresh"
		#define STR0034 "Não existem documentos selecionados para transmitir."
		#define STR0035 "Aguarde"
		#define STR0036 "Processando marcação dos documentos..."
		#define STR0037 "Atualizando exibição das informações..."
		#define STR0038 "Transmitindo documentos..."
		#define STR0039 "Limite de filiais excedido"
		#define STR0040 "Utilize a opção Marcar / Desmarcar para selecionar todas as filiais."
		#define STR0041 "Selecione o tipo de documento"
		#define STR0042 "Confirmar"
		#define STR0043 "Cancelar"
		#define STR0044 "Selecione as filiais"
		#define STR0045 "Marcar / Desmarcar Todos"
	#endif
#endif
