#ifdef SPANISH
	#define STR0001 "003 - El e-CT-e aún no se transmitió - espere la transmisión"
	#define STR0002 "NO FUE POSIBLE REALIZAR LA ANULACIÓN DEL CONTRATO."
	#define STR0003 "Entre en contacto con la REPOM para que los valores del contrato no queden disponibles para el proveedor."
	#define STR0004 "Si desea interrumpir el contrato automáticamente"
	#define STR0005 "seleccione la opción SÍ."
	#define STR0006 "No fue posible realizar la interrupción del contrato."
	#define STR0007 " Si desea borrar el viaje de todas maneras"
	#define STR0008 "El viaje no puede modificarse, porque el contrato de número: "
	#define STR0009 " está activo en la Operadora de flete y no fue posible anularlo"
	#define STR0010 "Después de borrar el viaje, solo el administrador del sistema conseguirá obtener el número del contrato del REPOM."
	#define STR0011 "Pendiente"
	#define STR0012 "En tránsito"
	#define STR0013 "Llegada a la sucursal"
	#define STR0014 "1No se pudo encontrar viajes con el estatus: 1=Pendiente, 2=En tránsito y 4=Llegada en Sucursal/Cliente."
	#define STR0015 "Para que esta consulta estándar devuelva registros es necesario que exista viajes con estatus: 1=Pendiente, 2=En tránsito y 4=Llegada en Sucursal/Cliente."
#else
	#ifdef ENGLISH
		#define STR0001 "003 - The CT-e was not sent yet - wait for transmission"
		#define STR0002 "UNABLE TO CANCEL CONTRACT!"
		#define STR0003 "Contact REPOM so the values of the contract are not available for the supplier!"
		#define STR0004 "Automatically interrupt the contract"
		#define STR0005 "select YES option!"
		#define STR0006 "Unable to interrupt contract!"
		#define STR0007 " In case you want to delete even so"
		#define STR0008 "The trip cannot be edited as it has contract number: "
		#define STR0009 " is active in the Freight Operation and it was not possible to cancel it"
		#define STR0010 "After execution of the trip, only the system administrator obtains the number of REPOM contract."
		#define STR0011 "Pending"
		#define STR0012 "In Transit"
		#define STR0013 "Arrival at Branch"
		#define STR0014 "Unable to locate Trips with Status: 1=Open, 2=In transit and 4=Arrival at Branch/Customer."
		#define STR0015 "For this default query to return records, there must be Trips with Status: 1=Open, 2=In transit and 4=Arrival at Branch/Customer."
	#else
		#define STR0001 "003 - O CT-e ainda não foi transmitida - aguarde a transmissão"
		#define STR0002 "NÃO FOI POSSÍVEL FAZER O CANCELAMENTO DO CONTRATO!"
		#define STR0003 "Entre em contato com a REPOM para que os valores do contrato não fiquem disponíveis para o fornecedor!"
		#define STR0004 "Caso deseje interromper o contrato automaticamente"
		#define STR0005 "selecione a opção SIM!"
		#define STR0006 "Não foi possível fazer a interrupção do contrato!"
		#define STR0007 " Caso deseje excluir a viagem mesmo assim"
		#define STR0008 "A viagem não pode ser alterada, pois o contrato de numero: "
		#define STR0009 " está ativo na Operadora de Frete e não foi possível cancelá-lo"
		#define STR0010 "Após a exclusão da viagem apenas o administrador do sistema conseguirá obter o número do contrato da REPOM."
		#define STR0011 "Em Aberto"
		#define STR0012 "Em Trânsito"
		#define STR0013 "Chegada em Filial"
		#define STR0014 "Não foi possivel localizar Viagens com Status: 1=Em Aberto, 2=Em Transito e 4=Chegada em Filial/Cliente."
		#define STR0015 "Para esta consulta padrão retornar registros é necessario que exista Viagens com Status: 1=Em Aberto, 2=Em Transito e 4=Chegada em Filial/Cliente."
	#endif
#endif
