#ifdef SPANISH
	#define STR0001 "Visualiza detalles"
	#define STR0002 "Detalles"
	#define STR0003 "XML exportados para"
	#define STR0004 "Ok"
	#define STR0005 "Motivo de la devolución"
	#define STR0006 "Comprobante"
	#define STR0007 "ID Evento"
	#define STR0008 "Entorno"
	#define STR0009 "Estatus del evento"
	#define STR0010 "Retorno de la transmisión"
	#define STR0011 "Número"
	#define STR0012 "Serie"
	#define STR0013 "Refresh"
	#define STR0014 "&Salir"
	#define STR0015 "Monitor - Evento desacuerdo"
	#define STR0016 "Se recomienda borrar el CTE después de confirmar el evento. El CTE continuará con todos sus registros activos hasta que sea borrado."
	#define STR0017 "1-Producción"
	#define STR0018 "2-Homologación"
	#define STR0019 "¡Antes de utilizar esta opción, ejecute el módulo de configuración del servicio!"
	#define STR0020 "Ok"
	#define STR0021 "¡Ninguna eFact encontrada de acuerdo con los parámetros informados!"
#else
	#ifdef ENGLISH
		#define STR0001 "View details"
		#define STR0002 "Details"
		#define STR0003 "XML files exported to"
		#define STR0004 "Ok"
		#define STR0005 "Return Reason"
		#define STR0006 "Protocol"
		#define STR0007 "Event ID"
		#define STR0008 "Environment"
		#define STR0009 "Event Status"
		#define STR0010 "Transmission Return"
		#define STR0011 "Number"
		#define STR0012 "Series"
		#define STR0013 "Refresh"
		#define STR0014 "&Exit"
		#define STR0015 "Monitor - Disagreement Event"
		#define STR0016 "Deleting the CTE after confirming the event is recommended. CTE will continue with all its active entries until it is deleted."
		#define STR0017 "1-Production"
		#define STR0018 "2-Homologation"
		#define STR0019 "Run the service configuration module before using this option!"
		#define STR0020 "Ok"
		#define STR0021 "No e-Invoice found according to the given parameters."
	#else
		#define STR0001 "Visualiza detalhes"
		#define STR0002 "Detalhes"
		#define STR0003 "XML's Exportados para"
		#define STR0004 "Ok"
		#define STR0005 "Motivo do Retorno"
		#define STR0006 "Protocolo"
		#define STR0007 "ID Evento"
		#define STR0008 "Ambiente"
		#define STR0009 "Status do Evento"
		#define STR0010 "Retorno da Transmissão"
		#define STR0011 "Numero"
		#define STR0012 "Serie"
		#define STR0013 "Refresh"
		#define STR0014 "&Sair"
		#define STR0015 "Monitor - Evento Desacordo"
		#define STR0016 "É recomendavel que exclua o CTE após a confirmação do evento. O CTE continuara com todas seus lançamentos ativos até que seja excluido."
		#define STR0017 "1-Produção"
		#define STR0018 "2-Homologação"
		#define STR0019 "Execute o módulo de configuração do serviço, antes de utilizar esta opção!!!"
		#define STR0020 "Ok"
		#define STR0021 "Nenhuma NF-e encontrada de acordo com os parametros informados!"
	#endif
#endif
