#ifdef SPANISH
	#define STR0001 "No se pudo realizar la lectura"
	#define STR0002 "vencido"
	#define STR0003 "no informado."
	#define STR0004 "Credenciales no tienen permiso para utilizar el servicio."
	#define STR0005 "No se encontraron los datos."
	#define STR0006 "no válido"
	#define STR0007 "Valores válidos"
	#define STR0008 "o"
	#define STR0009 "No válidos"
	#define STR0010 "Datos obligatorios para generación"
	#define STR0011 "Dato obligatorio para actualización"
	#define STR0012 "Falla de autenticación"
	#define STR0013 "Credenciales no válidas"
	#define STR0014 "desactivado"
	#define STR0015 "Usted no tiene permiso para acceder a este servidor."
	#define STR0016 "Mensaje"
	#define STR0017 "Su TSS está configurado con autenticación con base en credenciales."
	#define STR0018 "Verifique si su ERP está configurado correctamente con la credencial informada por su TSS."
	#define STR0019 "Servicio no disponible para esta versión del TSS"
#else
	#ifdef ENGLISH
		#define STR0001 "Could not read"
		#define STR0002 "overdue"
		#define STR0003 "not entered"
		#define STR0004 "The credentials do not have permission to use the service."
		#define STR0005 "No data found"
		#define STR0006 "invalid"
		#define STR0007 "Valid values"
		#define STR0008 "or"
		#define STR0009 "invalid"
		#define STR0010 "Data mandatory for generation"
		#define STR0011 "Data mandatory for update"
		#define STR0012 "Authentication failure"
		#define STR0013 "Credentials invalid"
		#define STR0014 "disabled"
		#define STR0015 "You do not have permission to access this server."
		#define STR0016 "Message"
		#define STR0017 "Your TSS is configured with credential-based authentication."
		#define STR0018 "Check if your ERP is correctly configured with the credential provided by your TSS."
		#define STR0019 "Service not available for this TSS version"
	#else
		#define STR0001 "Não foi possível realizar a leitura"
		#define STR0002 "vencido"
		#define STR0003 "não informado"
		#define STR0004 "Credenciais não possuem permissão para utilizar o serviço."
		#define STR0005 "Não foram encontrados os dados"
		#define STR0006 "inválido"
		#define STR0007 "Valores válidos"
		#define STR0008 "ou"
		#define STR0009 "inválidos"
		#define STR0010 "Dados obrigatórios para geração"
		#define STR0011 "Dado obrigatório para atualização"
		#define STR0012 "Falha de autenticação"
		#define STR0013 "Credenciais inválida"
		#define STR0014 "desabilitado"
		#define STR0015 "Você não tem permissão para acessar esse servidor."
		#define STR0016 "Mensagem"
		#define STR0017 "Seu TSS está configurado com autenticação baseado em credenciais."
		#define STR0018 "Verifique se seu ERP está configurado corretamente com a credencial fornecida pelo seu TSS."
		#define STR0019 "Serviço não disponível para essa versão do TSS"
	#endif
#endif
