#ifdef SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Imprimir"
	#define STR0007 "Copiar"
	#define STR0008 "Complemento de proveedores"
	#define STR0009 "Turismo"
	#define STR0010 "Grupo de productos"
	#define STR0011 "Formas de pago"
	#define STR0012 "Formas de pago restringidas"
	#define STR0013 "Formas de pago adicionales"
	#define STR0014 "Definiciones de cobranza"
	#define STR0015 "Departamento de reserva"
	#define STR0016 "Definiciones comerciales"
	#define STR0017 "Archivo de complemento de proveedor"
	#define STR0018 "Formas de pago liberadas"
	#define STR0019 "Informe el plazo y/o Tipo de plazo de reembolso."
	#define STR0020 "Forma de pago informada en"
	#define STR0021 "Cadena GDS"
	#define STR0022 "Atención"
	#define STR0023 "Forma de pago restringida: #1 no está asociada al grupo de productos: #2."
	#define STR0024 "Forma de pago adicional: #1 ya está asociada al grupo de productos: #2."
	#define STR0025 "Grupo de producto no tiene Formas de pago Liberada o Agregada."
	#define STR0026 "Código y tienda del proveedor del informe incompleto."
	#define STR0027 "Verifique el código y tienda del proveedor del informe."
#else
	#ifdef ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Print"
		#define STR0007 "Copy"
		#define STR0008 "Supplier Supplement"
		#define STR0009 "Tourism"
		#define STR0010 "Product Groups"
		#define STR0011 "Payment Methods"
		#define STR0012 "Restricted Payment Methods"
		#define STR0013 "Additional Payment Methods"
		#define STR0014 "Collection Definitions"
		#define STR0015 "Reservation Department"
		#define STR0016 "Commercial Definitions"
		#define STR0017 "Register of Supplier Complement"
		#define STR0018 "Cleared Payment Methods"
		#define STR0019 "Enter Deadline and/or Reimburse Deadline Type."
		#define STR0020 "Payment Term already entered in"
		#define STR0021 "GDS Chain"
		#define STR0022 "Attention"
		#define STR0023 "Payment Method Restricted: #1 is not associated to Products Group: #2."
		#define STR0024 "Additional Payment Method: #1 is already associated to Products Group: #2."
		#define STR0025 "Product Group has no Payment Methods Released or Added."
		#define STR0026 "Code and Store of report supplier incomplete."
		#define STR0027 "Check the Code and Store of report supplier incomplete."
	#else
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Imprimir"
		#define STR0007 "Copiar"
		#define STR0008 "Complemento de Fornecedores"
		#define STR0009 "Turismo"
		#define STR0010 "Grupos de Produtos"
		#define STR0011 "Formas de Pagamentos"
		#define STR0012 "Formas de Pagamentos Restringidas"
		#define STR0013 "Formas de Pagamentos Adicionais"
		#define STR0014 "Definições de Cobrança"
		#define STR0015 "Departamento de Reserva"
		#define STR0016 "Definições Comerciais"
		#define STR0017 "Cadastro de Complemento de Fornecedor"
		#define STR0018 "Formas de Pagamentos Liberadas"
		#define STR0019 "Informe o Prazo e/ou Tipo de Prazo de Reembolso."
		#define STR0020 "Forma de Pagamento já informada em"
		#define STR0021 "Cadeia GDS"
		#define STR0022 "Atenção"
		#define STR0023 "Forma de Pagamento Restringida: #1 não está associada ao Grupo de Produtos: #2."
		#define STR0024 "Forma de Pagamento Adicional: #1 já está associada ao Grupo de Produtos: #2."
		#define STR0025 "Grupo de Produto não possui Formas de Pagamento Liberada ou Adicionada."
		#define STR0026 "Código e Loja do fornecedor de Reporte incompleto."
		#define STR0027 "Verifique o Código e Loja do fornecedor de Reporte."
	#endif
#endif
