#ifdef SPANISH
	#define STR0001 "Conciliación"
	#define STR0002 "Factura de tarjeta de turismo"
	#define STR0003 "Ítems de la factura"
	#define STR0004 "Ítems financieros"
	#define STR0005 "Buscar DR"
	#define STR0006 "Desvincular"
	#define STR0007 "Clasif. Adic."
	#define STR0008 "Visualizar RV"
	#define STR0009 "Resumen"
	#define STR0010 "Conciliación ya efectuada."
	#define STR0011 "Cód. Clasif. "
	#define STR0012 "Clasificar adicional "
	#define STR0013 "Conciliación ya efectuada."
	#define STR0014 "Datos factura"
	#define STR0015 "Conciliación"
	#define STR0016 "Descripción"
	#define STR0017 "Ok"
	#define STR0018 "Procesando..."
	#define STR0019 "¿Desea vincular los ítems aún sin vincular? "
	#define STR0020 "Fecha de emisión de la factura es diferente de la fecha de emisión del IF."
	#define STR0021 "Conciliación está en uso por otro usuario."
#else
	#ifdef ENGLISH
		#define STR0001 "Conciliation"
		#define STR0002 "Tourism Card Invoice"
		#define STR0003 "Invoice Items"
		#define STR0004 "Financial Items"
		#define STR0005 "Research RD"
		#define STR0006 "Dissociate"
		#define STR0007 "Add. Classif."
		#define STR0008 "View VR"
		#define STR0009 "Summary"
		#define STR0010 "Conciliation already executed."
		#define STR0011 "Classif Code "
		#define STR0012 "Classify Additional "
		#define STR0013 "Conciliation already executed."
		#define STR0014 "Invoice Data"
		#define STR0015 "Conciliation"
		#define STR0016 "Description"
		#define STR0017 "Ok"
		#define STR0018 "Processing..."
		#define STR0019 "Associate items not associated? "
		#define STR0020 "Invoice issue date other than IF issue date."
		#define STR0021 "Reconciliation is in use by other user."
	#else
		#define STR0001 "Conciliação"
		#define STR0002 "Fatura de Cartão de Turismo"
		#define STR0003 "Itens da Fatura"
		#define STR0004 "Itens Financeiros"
		#define STR0005 "Pesquisar DR"
		#define STR0006 "Desassociar"
		#define STR0007 "Classif.Adic."
		#define STR0008 "Visualizar RV"
		#define STR0009 "Resumo"
		#define STR0010 "Conciliação já efetivada."
		#define STR0011 "Cód. Classif. "
		#define STR0012 "Classificar Adicional "
		#define STR0013 "Conciliação já efetivada."
		#define STR0014 "Dados Fatura"
		#define STR0015 "Conciliação"
		#define STR0016 "Descrição"
		#define STR0017 "Ok"
		#define STR0018 "Processando..."
		#define STR0019 "Deseja associar os itens ainda não associados? "
		#define STR0020 "Data de emissão da Fatura diferente da data de emissão do IF."
		#define STR0021 "Conciliação está em uso por outro usuário."
	#endif
#endif
