#ifdef SPANISH
	#define STR0001 "Visualizar"
	#define STR0002 "Modificar"
	#define STR0003 "Borrar"
	#define STR0004 "Cerrar"
	#define STR0005 "Error al realizar la compensación entre carteras."
	#define STR0006 "Error al realizar la compensación con la Cobranza anticipada (RA)."
	#define STR0007 "Error al realizar la compensación con el Pago anticipado (PA)."
	#define STR0008 "Mensajes"
	#define STR0009 "Espere mientras se genera el informe."
	#define STR0018 "No vinculado"
	#define STR0019 "Vinculado"
	#define STR0020 "Aprobado"
	#define STR0021 "Existe solamente un ítem de la factura vinculado al Documento de reserva, si realmente desea desvincularlo, debe borrar el registro de conciliación aérea."
	#define STR0022 "No se permite desvincular todos los ítems de una única vez."
	#define STR0023 "Seleccione algún ítem de la factura para realizar la desvinculación."
	#define STR0026 "Conciliación  aérea"
	#define STR0027 "Modificar"
	#define STR0028 "Reversión realizada con éxito."
	#define STR0029 "Concreción realizada con éxito."
	#define STR0030 "Atención"
	#define STR0033 "Visión financiera"
	#define STR0034 "Seleccione algún ítem de la factura para realizar la desvinculación."
	#define STR0035 "El valor informado en la factura ( #1[Valor factura]# ) es divergente del calculado en los ítems financieros ( #2[Valor factura]# )."
	#define STR0044 "Divergente"
	#define STR0045 "No divergente"
	#define STR0046 "Aprobado total"
	#define STR0047 "Aprobado parcial"
	#define STR0048 "No aprobado"
	#define STR0052 "Atención"
	#define STR0072 "Ítem de la factura #1[Nº de la factura]# está con divergencia de FOP/Moneda. Ajuste el Registro de venta antes de vincular."
	#define STR0081 "Informe las modalidades de los ítems listados en la conciliación."
	#define STR0084 "Estados financieros Agencia"
	#define STR0085 "Informe Financ. Cliente"
	#define STR0086 "No se podrá revertir la realización, por los siguientes motivos:"
	#define STR0087 "Ítem financiero #1[ Ítem financiero ]# ya finalizado."
	#define STR0088 "Ítem financiero #1[ Ítem financiero ]# forma parte del cálculo #2[ Nº  Cálculo ]#."
	#define STR0089 "Verifique el archivo de 'Parámetros fiscales y financieros' si los códigos de Modalidades están correctos."
	#define STR0090 "Modalidad en blanco."
	#define STR0091 "Modalidad #1[código modalidad]# no registrada en la sucursal #2[Código sucursal]#."
	#define STR0092 "Verifique el registro de Modalidades en la sucursal informada."
	#define STR0093 "Error al grabar el log."
	#define STR0094 "Entre en contacto con el administrador del sistema"
	#define STR0095 "Error al generar el título por pagar, proceso se revertirá."
	#define STR0096 "Error al grabar título por cobrar."
	#define STR0097 "Error al generar la factura por pagar, proceso se revertirá."
	#define STR0098 "Informe las modalidades solicitadas."
	#define STR0101 "Espere, marcando ítems..."
	#define STR0102 "Opciones disponibles:"
	#define STR0103 "1) Anula la marcación de los ítems"
	#define STR0104 "2) Marca todos los ítems pendientes, incluso ítems con ajustes"
	#define STR0105 "3) Marca todos los ítems pendientes que no tienen ajustes generados"
	#define STR0106 "Marcar ítems"
	#define STR0107 "1-Anular"
	#define STR0108 "2-Con ajuste"
	#define STR0109 "3-Sin ajuste"
	#define STR0110 " Algunos ítems no se marcaron porque están con divergencia de FOP."
	#define STR0111 " Algunos ítems no se marcaron porque no tienen todas las modalidades informadas."
	#define STR0112 " Se detectaron registros con divergencia en el valor neto."
	#define STR0113 "ATENCIÓN"
	#define STR0114 "Conciliación de metas"
	#define STR0115 "Ítems financieros liberados en el ítem de la factura #1[ítem factura]# ya se calcularon o finalizaron."
	#define STR0116 "Revierta la facturación o cálculo antes de continuar."
	#define STR0117 "Divergencia de valor neto."
	#define STR0118 "Se encontraron divergencias durante el proceso. ¿Desea visualizar las divergencias?"
	#define STR0119 "Salir"
	#define STR0120 "Divergencia de FOP/Moneda"
	#define STR0123 "¿Desea visualizar las divergencias?"
	#define STR0125 "Se perderán todas las modificaciones en registros de ajustes. ¿Desea continuar con la modificación del Registro de ventas?"
	#define STR0126 "'Su código de usuario no está vinculado a un vendedor o Agente. No es posible acceder a esta rutina.'"
	#define STR0127 "Registro de ventas"
	#define STR0129 "¿Desea visualizar el registro de venta '#1[ Num. RV ]#' ítem '#2[ Id Item ]#'?"
	#define STR0138 "Ítem de la factura #1[Nº de la Factura]# aprobado. La operación no está permitida."
	#define STR0142 "El ítem de la factura #1[ítem factura]# tiene ajuste de FOP, ¿desea revertir el ajuste?"
	#define STR0155 'Error al actualizar el estatus.'
	#define STR0156 'Error al desvincular el ítem.'
	#define STR0157 "Error al revertir la liberación de los ítems financieros."
	#define STR0159 "Verifique las siguientes modalidades antes de hacer efectivo:"
	#define STR0160 "Modalidad para generación de la factura por pagar"
	#define STR0161 "Documento de reserva"
	#define STR0162 "Acuerdo proveedor, aplicación: "
	#define STR0163 "Doc. Reserva: #1[Doc. Reserva]#, Ítem: #2[Ítem]#, Sec.: #3[Secuencia]#"
	#define STR0164 "Pendiente de Eval."
	#define STR0165 "Ítem com error durante el vínculo. Por favor, desvincule el ítem y vincule nuevamente."
	#define STR0173 "Error al transferir título a la sucursal actual."
#else
	#ifdef ENGLISH
		#define STR0001 "View"
		#define STR0002 "Edit"
		#define STR0003 "Delete"
		#define STR0004 "Close"
		#define STR0005 "Error compensating portfolios"
		#define STR0006 "Erro ao realizar a compensação com o Recebimento Antecipado (RA)."
		#define STR0007 "Erro ao realizar a compensação com o Pagamento Antecipado (PA)."
		#define STR0008 "Messages"
		#define STR0009 "Aguarde enquanto o demonstrativo é gerado."
		#define STR0018 "Not Associate"
		#define STR0019 "Associate"
		#define STR0020 "Approved"
		#define STR0021 "Existe apenas um item da fatura associado ao Documento de Reserva, caso realmente deseje realizar a desassociação deverá ser realizada a exclusão do registro de conciliação aérea."
		#define STR0022 "Unable disassociate all items at once."
		#define STR0023 "Select an invoice item for disassociation."
		#define STR0026 "Air Conciliation"
		#define STR0027 "Edit"
		#define STR0028 "Reversal successfully completed."
		#define STR0029 "Execution successfully completed."
		#define STR0030 "Attention"
		#define STR0033 "Financial view"
		#define STR0034 "Select an invoice item for disassociation."
		#define STR0035 "Value entered in invoice (#1[Invoice Value]# ) differs from that calculated in financial items (#2[Invoice Value]# )."
		#define STR0044 "Divergent"
		#define STR0045 "Not Divergent"
		#define STR0046 "Total Approved"
		#define STR0047 "Partial Approved"
		#define STR0048 "Not Approved"
		#define STR0052 "Attention"
		#define STR0072 "Invoice Item #1[invoice number]# has FOP/Currency divergence. Adjust the Sales Record before linking it."
		#define STR0081 "Enter the nature of items listed in conciliation."
		#define STR0084 "Bank Branch Fin. Stat."
		#define STR0085 "Customer Fin. Dem."
		#define STR0086 "Unable to execute by the following reasons:"
		#define STR0087 "Financial Item #1[ Financial Item o ]# already finished."
		#define STR0088 "Item Financeiro #1[ Item financeiro ]# faz parte da Apuração #2[ Num. Apuração ]#."
		#define STR0089 "Verifique o cadastro de 'Parâmetros Fiscais e Financeiros' se os códigos de Naturezas estão corretos."
		#define STR0090 "Blank class."
		#define STR0091 "Class #1[class code]# not registered in branch #2[branch code]#."
		#define STR0092 "Check the Classes register at the branch entered."
		#define STR0093 "Error saving log."
		#define STR0094 "Contact the System administrator"
		#define STR0095 "Error generating bill payable, process is reversed."
		#define STR0096 "Error saving bill receivable."
		#define STR0097 "Error generating bill payable, process is reversed."
		#define STR0098 "Enter requested natures."
		#define STR0101 "Wait, selecting items..."
		#define STR0102 "Available options:"
		#define STR0103 "1) Cancels registration of items"
		#define STR0104 "2) Select all pending items including items with adjustment"
		#define STR0105 "3) Select all pending items without generated adjustment"
		#define STR0106 "Select Items"
		#define STR0107 "1-Canceled"
		#define STR0108 "2-With adjustment"
		#define STR0109 "3-Without adjustment"
		#define STR0110 " Some items were not selected as they have FOP divergence."
		#define STR0111 " Some items were not selected as they do not have all natures informed."
		#define STR0112 " Records with divergence in net value were detected."
		#define STR0113 "ATTENTION"
		#define STR0114 "Goals Conciliation"
		#define STR0115 "Financial Items released in the item of invoice #1[invoice item]# already calculated or finalized."
		#define STR0116 "Reverse invoicing or calculation before proceeding."
		#define STR0117 "Divergence of net value."
		#define STR0118 "Divergences found during process. View divergence(s)?"
		#define STR0119 "Exit"
		#define STR0120 "FOP/currency divergence"
		#define STR0123 "Do you want to view divergences?"
		#define STR0125 "All changes in adjustment records are lost. Proceed with change of Sales Record?"
		#define STR0126 "'Seu código de usuário não está relacionado com um Vendedor ou Agente. You will not be able to access this routine"
		#define STR0127 "Sales Record"
		#define STR0129 "View record of sales '#1[ Num. RV ]#' item '#2[ Id Item ]#'?"
		#define STR0138 "Invoice item #1[Invoice No.]# already approved. This operation not allowed."
		#define STR0142 "The invoice item #1[invoice item]# has FOP adjustment, reverse adjustment?"
		#define STR0155 'Error updating status.'
		#define STR0156 'Error disassociating item.'
		#define STR0157 "Error reversing release of financial items."
		#define STR0159 "Check classes below before execution:"
		#define STR0160 "Nature used for generation of payable bill"
		#define STR0161 "Reservation Document"
		#define STR0162 "Supplier agreement, application: "
		#define STR0163 "Res. doc.: #1[Doc. Reserv]#, Item: #2[Item]#, Seq.: #3[Seq]#"
		#define STR0164 "Eval. Pending"
		#define STR0165 "Item com erro durante associação. Favor desassociar o item e associar novamente."
		#define STR0173 "Error transferring bill to the current branch"
	#else
		#define STR0001 "Visualizar"
		#define STR0002 "Alterar"
		#define STR0003 "Excluir"
		#define STR0004 "Fechar"
		#define STR0005 "Erro ao realizar a compensação entre carteiras."
		#define STR0006 "Erro ao realizar a compensação com o Recebimento Antecipado (RA)."
		#define STR0007 "Erro ao realizar a compensação com o Pagamento Antecipado (PA)."
		#define STR0008 "Mensagens"
		#define STR0009 "Aguarde enquanto o demonstrativo é gerado."
		#define STR0018 "Não Associado"
		#define STR0019 "Associado"
		#define STR0020 "Aprovado"
		#define STR0021 "Existe apenas um item da fatura associado ao Documento de Reserva, caso realmente deseje realizar a desassociação deverá ser realizada a exclusão do registro de conciliação aérea."
		#define STR0022 "Não é permetido desassociar todos os itens de uma única vez."
		#define STR0023 "Selecione algum item da fatura para realizar a desassociação."
		#define STR0026 "Conciliação Aérea"
		#define STR0027 "Alterar"
		#define STR0028 "Estorno realizado com sucesso."
		#define STR0029 "Efetivação realizada com sucesso."
		#define STR0030 "Atenção"
		#define STR0033 "Visão Financeira"
		#define STR0034 "Selecione algum item da fatura para realizar a desassociação."
		#define STR0035 "O valor informado na fatura ( #1[Valor Fatura]# ) é divergente do calculado nos itens financeiros ( #2[Valor Fatura]# )."
		#define STR0044 "Divergente"
		#define STR0045 "Não Divergente"
		#define STR0046 "Aprovado Total"
		#define STR0047 "Aprovado Parcial"
		#define STR0048 "Não Aprovado"
		#define STR0052 "Atenção"
		#define STR0072 "Item da fatura #1[Num. da fatura]# está com divergência de FOP/Moeda, ajuste o Registro de venda antes de associar."
		#define STR0081 "Informe as naturezas dos itens listados na conciliação."
		#define STR0084 "Dem. Financ. Agencia"
		#define STR0085 "Dem. Financ. Cliente"
		#define STR0086 "Não será possível desefetivar pelos seguintes motivos:"
		#define STR0087 "Item Financeiro #1[ Item financeiro ]# já finalizado."
		#define STR0088 "Item Financeiro #1[ Item financeiro ]# faz parte da Apuração #2[ Num. Apuração ]#."
		#define STR0089 "Verifique o cadastro de 'Parâmetros Fiscais e Financeiros' se os códigos de Naturezas estão corretos."
		#define STR0090 "Natureza em branco."
		#define STR0091 "Natureza #1[codigo natureza]# não cadastrada na filial #2[Código filial]#."
		#define STR0092 "Verifique o cadastro de Naturezas na filial informada."
		#define STR0093 "Erro ao gravar o log."
		#define STR0094 "Entre em contato com o administrador do sistema"
		#define STR0095 "Erro ao gerar o título a pagar, processo será estornado."
		#define STR0096 "Erro ao gravar titulo receber."
		#define STR0097 "Erro ao gerar o fatura a pagar, processo será estornado."
		#define STR0098 "Informe as naturezas solicitadas."
		#define STR0101 "Aguarde, marcando itens..."
		#define STR0102 "Opções disponíveis:"
		#define STR0103 "1) Cancela a marcação dos itens"
		#define STR0104 "2) Marca todos os itens em aberto, incluindo itens com acertos"
		#define STR0105 "3) Marca todos os itens em aberto que não possuem acertos gerados"
		#define STR0106 "Marcar itens"
		#define STR0107 "1-Cancelar"
		#define STR0108 "2-Com acerto"
		#define STR0109 "3-Sem acerto"
		#define STR0110 " Alguns itens não foram marcados por estarem com divergência de FOP."
		#define STR0111 " Alguns itens não foram marcados por não conter todas as naturezas informadas."
		#define STR0112 " Foi detectado registros com divergência no valor líquido."
		#define STR0113 "ATENÇÃO"
		#define STR0114 "Conciliação de Metas"
		#define STR0115 "Itens financeiros liberados no item da fatura #1[item fatura]# já foram apurados ou finalizados."
		#define STR0116 "Estorne o faturamento ou apuração antes de prosseguir."
		#define STR0117 "Divergência de valor líquido."
		#define STR0118 "Encontrada(s) divergência(s) durante o processo. Deseja visualizar a(s) divergência(s)?"
		#define STR0119 "Sair"
		#define STR0120 "Divergência de FOP/Moeda"
		#define STR0123 "Deseja visualizar as divergências?"
		#define STR0125 "Todas alterações em registros de acertos serão perdidas. Deseja prosseguir com a alteração do Registro de Vendas?"
		#define STR0126 "'Seu código de usuário não está relacionado com um Vendedor ou Agente. Não será possível acessar essa rotina.'"
		#define STR0127 "Registro de Vendas"
		#define STR0129 "Deseja visualizar o registro de venda '#1[ Num. RV ]#' item '#2[ Id Item ]#'?"
		#define STR0138 "Item da fatura #1[Num. da fatura]# já aprovado. Operação não é permitida."
		#define STR0142 "O item da fatura #1[item fatura]# possui acerto de FOP, deseja estornar o acerto?"
		#define STR0155 'Erro ao atualizar status.'
		#define STR0156 'Erro ao desassociar o item.'
		#define STR0157 "Erro ao estornar a liberação dos itens financeiros."
		#define STR0159 "Verifique as naturezas abaixo antes da efetivação:"
		#define STR0160 "Natureza para geração da fatura a pagar"
		#define STR0161 "Documento de Reserva"
		#define STR0162 "Acordo fornecedor, aplicação: "
		#define STR0163 "Doc. reserva: #1[Doc. Reserva]#, Item: #2[Item]#, Seq.: #3[Sequencia]#"
		#define STR0164 "Pendente Aval."
		#define STR0165 "Item com erro durante associação. Favor desassociar o item e associar novamente."
		#define STR0173 "Erro ao transferir título para a filial corrente."
	#endif
#endif
