#ifdef SPANISH
	#define STR0001 "Id del formulario de origen:"
	#define STR0002 "Id del campo de origen: "
	#define STR0003 "Id del formulario de error: "
	#define STR0004 "Id del campo de error: "
	#define STR0005 "Id del error: "
	#define STR0006 "Mensaje de error: "
	#define STR0007 "Mensaje de solución: "
	#define STR0008 "Valor atribuido: "
	#define STR0009 "Valor anterior: "
	#define STR0010 "Solo se pueden incluir documentos de reserva con el proveedor de Report igual al proveedor de la conciliación."
	#define STR0011 "Documento de reserva ya incluido en esta conciliación."
	#define STR0012 "Falla al actualizar los ítems financieros del documento de reserva #1/#2/#3. Este no se incluirá en la conciliación."
	#define STR0013 "Un documento de reserva de parcialidad no se debe conciliar por medio de la conciliación que lo generó."
	#define STR0014 "Un documento de reserva de No Show no se debe conciliar por medio de la conciliación que lo generó."
	#define STR0015 "Concilie el documento de reserva en otra conciliación."
	#define STR0016 "No se pudo incluir uno o más documentos de reserva por estar con la moneda diferente de los demás DRs de esta conciliación."
#else
	#ifdef ENGLISH
		#define STR0001 "Id of the origin form:"
		#define STR0002 "Id of the origin field: "
		#define STR0003 "Id of error form: "
		#define STR0004 "Error field Id: "
		#define STR0005 "Error Id: "
		#define STR0006 "Error message: "
		#define STR0007 "Solution message: "
		#define STR0008 "Value assigned: "
		#define STR0009 "Previous value: "
		#define STR0010 "Only reservation documents with report supplier equal to reconciliation supplier can be included."
		#define STR0011 "Reservation document already added to this reconciliation."
		#define STR0012 "Failure updating financial items of reservation document #1/#2/#3. It will not be added to conciliation"
		#define STR0013 "A Reservation Document of Partiality cannot be conciled through conciliation generating it."
		#define STR0014 "A Reservation Document of No Show cannot be conciled through conciliation generating it."
		#define STR0015 "Concile Document of Reservation in other conciliation."
		#define STR0016 "Unable to add one or more Documents of Reservation as they have currency different than the other DRs of this conciliation."
	#else
		#define STR0001 "Id do formulário de origem:"
		#define STR0002 "Id do campo de origem: "
		#define STR0003 "Id do formulário de erro: "
		#define STR0004 "Id do campo de erro: "
		#define STR0005 "Id do erro: "
		#define STR0006 "Mensagem do erro: "
		#define STR0007 "Mensagem da solução: "
		#define STR0008 "Valor atribuído: "
		#define STR0009 "Valor anterior: "
		#define STR0010 "Apenas Documentos de Reserva com Fornecedor de Report igual ao Fornecedor da Conciliação podem ser incluídos."
		#define STR0011 "Documento de Reserva já incluído nesta conciliação."
		#define STR0012 "Falha ao atualizar os Itens Financeiros do Documento de Reserva #1/#2/#3. Ele não será inserido na conciliação."
		#define STR0013 "Um Documento de Reserva de Parcialidade não pode ser conciliado através da conciliação que o gerou."
		#define STR0014 "Um Documento de Reserva de No Show não pode ser conciliado através da conciliação que o gerou."
		#define STR0015 "Concilie o Documento de Reserva em outra conciliação."
		#define STR0016 "Não foi possível incluir um ou mais Documentos de Reserva por estarem com a moeda diferente dos demais DRs desta conciliação."
	#endif
#endif
