#ifdef SPANISH
	#define STR0001 "ACTUALIZACIÓN DE DICCIONARIOS Y TABLAS"
	#define STR0002 "Esta rutina tiene como función Modificar el tamaño de los campos de LOG del ítem de SC y de "
	#define STR0003 "Pedido de compras"
	#define STR0004 "Este proceso debe ejecutarse de modo EXCLUSIVO, es decir, no deben haber otros"
	#define STR0005 "usuarios o jobs utilizando el sistema.  Es extremadamente recomendable que se haga una"
	#define STR0006 "COPIA DE SEGURIDAD  de los DICCIONARIOS  y de la  BASE DE DATOS antes de esta actualización, para que si"
	#define STR0007 "ocurren eventuales fallas, esta copia de seguridad se restaure."
	#define STR0008 "¿Confirma la actualización de los diccionarios?"
	#define STR0009 "Actualizando"
	#define STR0010 "Espere, actualizando..."
	#define STR0011 "Actualización concluida."
	#define STR0012 "Actualización no realizada."
	#define STR0013 "Empresa: "
	#define STR0014 "Diccionario de datos - "
	#define STR0015 "Actualizando campos/índices"
	#define STR0016 "Hubo un error desconocido durante la actualización de la tabla: "
	#define STR0017 ". Verifique la integridad del diccionario y de la tabla."
	#define STR0018 "ATENCIÓN"
	#define STR0019 "Hubo un error desconocido durante la actualización de la estructura de la tabla: "
	#define STR0020 "Inicio de la actualización del SX3"
	#define STR0021 "Modificado el tamaño del campo "
	#define STR0022 "Actualizando campos de tablas (SX3)..."
	#define STR0023 "Final de la actualización del SX3"
	#define STR0024 "No se pudo abrir SM0 exclusivo."
	#define STR0025 "Pantalla para múltiples selecciones de Empresas/Sucursales"
	#define STR0026 "Seleccione las empresas para actualización"
	#define STR0027 "Empresa"
	#define STR0028 "Todos"
	#define STR0029 "Marca/Desmarca todos"
	#define STR0030 "Invertir selección"
	#define STR0031 "Confirma la selección"
	#define STR0032 "Salir de la selección"
	#define STR0033 "¡No fue posible la apertura de la tabla de empresas de forma exclusiva!"
	#define STR0034 "LOG DE ACTUALIZACIÓN DE LOS DICCIONARIOS"
	#define STR0035 "Actualización concluida."
	#define STR0036 "&Invertir"
	#define STR0037 "Máscara empresa ( ?? )"
	#define STR0038 "&Marcar"
	#define STR0039 "Marcar utilizando máscara ( ?? )"
	#define STR0040 "&Desmarcar"
	#define STR0041 "Desmarcar utilizando máscara ( ?? )"
#else
	#ifdef ENGLISH
		#define STR0001 "UPDATING OF DICTIONARY AND TABLES"
		#define STR0002 "This routine has function Edit size of fields of LOG of item and of "
		#define STR0003 "Purchase order."
		#define STR0004 "This process must be run in EXCLUSIVE mode, that it cannot have others"
		#define STR0005 "users of  jobs using system. It is extremely reccommended that you do a"
		#define STR0006 "DICTIONARY BACKUP and DATABASE before updating, so"
		#define STR0007 "in case there are failures, this backup must be restored."
		#define STR0008 "Check dictionary updating ?"
		#define STR0009 "Updating"
		#define STR0010 "Wait, updating..."
		#define STR0011 "Updating concluded."
		#define STR0012 "Updating not executed."
		#define STR0013 "Company: "
		#define STR0014 "Data dictionary - "
		#define STR0015 "Updating fields/indexes"
		#define STR0016 "Unknown error during table updating: "
		#define STR0017 ". Check the integrity of table and dictionary."
		#define STR0018 "NOTIFICATION"
		#define STR0019 "Unknown error during updating of table structure: "
		#define STR0020 "Updating Start of SX3"
		#define STR0021 "Field size edited "
		#define STR0022 "Updating Table Fields (SX3)..."
		#define STR0023 "Updating End of SX3"
		#define STR0024 "You cannot open exclusive SM0."
		#define STR0025 "Screen fpr Multiple Selections of Companies/Branches"
		#define STR0026 "Select Company(ies) for Updating"
		#define STR0027 "Company"
		#define STR0028 "All"
		#define STR0029 "Select/Clear All"
		#define STR0030 "Invert Selection"
		#define STR0031 "Confirm Selection"
		#define STR0032 "Abandon Selection"
		#define STR0033 "Unable to open the companies table in an exclusive mode."
		#define STR0034 "DICTIONARY UPDATING LOG"
		#define STR0035 "Updating concluded."
		#define STR0036 "&Invert"
		#define STR0037 "Company Mask ( ?? )"
		#define STR0038 "&Select"
		#define STR0039 "Select using mask ( ?? )"
		#define STR0040 "&Clear"
		#define STR0041 "Clear using mask ( ?? )"
	#else
		#define STR0001 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
		#define STR0002 "Esta rotina tem como função Alterar o tamanho dos campos de LOG de item de SC e de "
		#define STR0003 "Pedido de compras."
		#define STR0004 "Este processo deve ser executado em modo EXCLUSIVO, ou seja não podem haver outros"
		#define STR0005 "usuários  ou  jobs utilizando  o sistema.  É extremamente recomendavél  que  se  faça um"
		#define STR0006 "BACKUP  dos DICIONÁRIOS  e da  BASE DE DADOS antes desta atualização, para que"
		#define STR0007 "caso ocorra eventuais falhas, esse backup seja ser restaurado."
		#define STR0008 "Confirma a atualização dos dicionários ?"
		#define STR0009 "Atualizando"
		#define STR0010 "Aguarde, atualizando ..."
		#define STR0011 "Atualização Concluída."
		#define STR0012 "Atualização não Realizada."
		#define STR0013 "Empresa : "
		#define STR0014 "Dicionário de dados - "
		#define STR0015 "Atualizando campos/índices"
		#define STR0016 "Ocorreu um erro desconhecido durante a atualização da tabela : "
		#define STR0017 ". Verifique a integridade do dicionário e da tabela."
		#define STR0018 "ATENÇÃO"
		#define STR0019 "Ocorreu um erro desconhecido durante a atualização da estrutura da tabela : "
		#define STR0020 "Inicio da Atualizacao do SX3"
		#define STR0021 "Alterado o Tamanho do campo "
		#define STR0022 "Atualizando Campos de Tabelas (SX3)..."
		#define STR0023 "Final da Atualizacao do SX3"
		#define STR0024 "Não foi possível abrir SM0 exclusivo."
		#define STR0025 "Tela para Múltiplas Seleções de Empresas/Filiais"
		#define STR0026 "Selecione a(s) Empresa(s) para Atualização"
		#define STR0027 "Empresa"
		#define STR0028 "Todos"
		#define STR0029 "Marca / Desmarca Todos"
		#define STR0030 "Inverter Seleção"
		#define STR0031 "Confirma a Seleção"
		#define STR0032 "Abandona a Seleção"
		#define STR0033 "Não foi possível a abertura da tabela de empresas de forma exclusiva."
		#define STR0034 "LOG DA ATUALIZACAO DOS DICIONÁRIOS"
		#define STR0035 "Atualizacao concluida."
		#define STR0036 "&Inverter"
		#define STR0037 "Máscara Empresa ( ?? )"
		#define STR0038 "&Marcar"
		#define STR0039 "Marcar usando máscara ( ?? )"
		#define STR0040 "&Desmarcar"
		#define STR0041 "Desmarcar usando máscara ( ?? )"
	#endif
#endif
