#ifdef SPANISH
	#define STR0001 "Este programa tiene como objetivo ajustar los diccionarios de datos en función del BOPS 147220. "
	#define STR0002 "¡Esta rutina debe procesarse en modo exclusivo! "
	#define STR0003 "¡Haga una copia de seguridad de los diccionarios y de la base de datos antes del procesamiento!"
	#define STR0004 "BOPS 147220/V2.0 Log Anvisa "
	#define STR0005 "Actualizador de base"
	#define STR0006 "Anular"
	#define STR0007 "Continuar"
	#define STR0008 "¡Operación anulada!"
	#define STR0009 "Archivos Texto (*.TXT) |*.txt|"
	#define STR0010 "Verificando la integridad de los diccionarios..."
	#define STR0011 "Empresa: "
	#define STR0012 "Inicio - Diccionario de datos"
	#define STR0013 "Analizando el diccionario de datos..."
	#define STR0014 "Final - Diccionario de datos"
	#define STR0015 "Inicio Actualizando Estructuras "
	#define STR0016 "Actualizando estructuras. Espere... ["
	#define STR0017 "¡Atención!"
	#define STR0018 "Ocurrió un error desconocido durante la actualización de la tabla: "
	#define STR0019 ". Verifique la integridad del diccionario y de la tabla."
	#define STR0020 "Continuar"
	#define STR0021 "Ocurrió un error desconocido durante la actualización de la estructura de la tabla: "
	#define STR0022 "Final. Actualizando estructuras "
	#define STR0023 "Inicio - Abriendo tablas"
	#define STR0024 "Final - Abriendo tablas"
	#define STR0025 "Actualización concluida."
	#define STR0026 "Log de la actualización "
	#define STR0027 "Actualización concluida."
	#define STR0028 "¡No fue posible la apertura de la tabla de empresas de forma exclusiva!"
	#define STR0029 "OK"
	#define STR0030 ". Verifique la integridad del diccionario y de la tabla."
#else
	#ifdef ENGLISH
		#define STR0001 "This program adjusts data dictionaries in accordance with BOPS 147220. "
		#define STR0002 "This routine must be processed in exclusive mode! "
		#define STR0003 "Make a backup of dictionaries and database before processing!"
		#define STR0004 "BOPS 147220/V2.0 Log Anvisa "
		#define STR0005 "Base Updater"
		#define STR0006 "Cancel"
		#define STR0007 "Continue"
		#define STR0008 "Operation canceled!"
		#define STR0009 "Text files (*.TXT) |*.txt|"
		#define STR0010 "Checking dictionary integrity..."
		#define STR0011 "Company: "
		#define STR0012 "Start - Data Dictionary"
		#define STR0013 "Analyzing Data Dictionary..."
		#define STR0014 "End - Data Dictionary"
		#define STR0015 "Start Updating Structures "
		#define STR0016 "Updating structures. Wait... ["
		#define STR0017 "Attention!"
		#define STR0018 "There was an unknown error during table update: "
		#define STR0019 ". Check dictionary and table integrity."
		#define STR0020 "Continue"
		#define STR0021 "An unknown error occurred during table structure update: "
		#define STR0022 "End Updating Structures "
		#define STR0023 "Start - Opening Tables"
		#define STR0024 "End - Opening Tables"
		#define STR0025 "Update Completed."
		#define STR0026 "Update Log "
		#define STR0027 "Update Completed."
		#define STR0028 "Company table could not be opened in exclusive mode!"
		#define STR0029 "OK"
		#define STR0030 ". Check dictionary and table integrity."
	#else
		#define STR0001 "Este programa tem como objetivo ajustar os dicionários de dados em função do BOPS 147220. "
		#define STR0002 "Esta rotina deve ser processada em modo exclusivo! "
		#define STR0003 "Faça um backup dos dicionários e base de dados antes do processamento!"
		#define STR0004 "BOPS 147220/V2.0 Log Anvisa "
		#define STR0005 "Atualizador de Base"
		#define STR0006 "Cancelar"
		#define STR0007 "Prosseguir"
		#define STR0008 "Operaçao cancelada!"
		#define STR0009 "Arquivos Texto (*.TXT) |*.txt|"
		#define STR0010 "Verificando integridade dos dicionários...."
		#define STR0011 "Empresa : "
		#define STR0012 "Inicio - Dicionario de Dados"
		#define STR0013 "Analisando Dicionario de Dados..."
		#define STR0014 "Fim - Dicionario de Dados"
		#define STR0015 "Inicio Atualizando Estruturas "
		#define STR0016 "Atualizando estruturas. Aguarde... ["
		#define STR0017 "Atencao!"
		#define STR0018 "Ocorreu um erro desconhecido durante a atualizacao da tabela : "
		#define STR0019 ". Verifique a integridade do dicionario e da tabela."
		#define STR0020 "Continuar"
		#define STR0021 "Ocorreu um erro desconhecido durante a atualizacao da estrutura da tabela : "
		#define STR0022 "Fim Atualizando Estruturas "
		#define STR0023 "Inicio - Abrindo Tabelas"
		#define STR0024 "Fim - Abrindo Tabelas"
		#define STR0025 "Atualização Concluída."
		#define STR0026 "Log da Atualização "
		#define STR0027 "Atualizacao Concluída."
		#define STR0028 "Nao foi possivel a abertura da tabela de empresas de forma exclusiva !"
		#define STR0029 "Ok"
		#define STR0030 ". Verifique a integridade do dicionario e da tabela."
	#endif
#endif
