#ifdef SPANISH
	#define STR0001 "Este programa tiene como objetivo ajustar los diccionarios de datos para la "
	#define STR0002 "implementacion de la mejora vinculada con las publicaciones de precios.   "
	#define STR0003 "Implementando Configurador de publicaciones de precios."
	#define STR0004 "Actualizador de Base"
	#define STR0005 "Anular"
	#define STR0006 "Proseguir"
	#define STR0007 "¡Operacion anulada!"
	#define STR0008 "Verificando integridad de los diccionarios...."
	#define STR0009 "Empresa : "
	#define STR0010 "Inicio - Verificando claves primarias e indices..."
	#define STR0011 "Verificando claves primarias e indices..."
	#define STR0012 "Final - Verificando claves primarias e indices..."
	#define STR0013 "Inicio - Analizando Diccionario de Preguntas..."
	#define STR0014 "Analizando Diccionario de Preguntas..."
	#define STR0015 "Final - Analizando Diccionario de Preguntas..."
	#define STR0016 "Inicio - Diccionario de Archivos"
	#define STR0017 "Actualizando Diccionario de Archivos..."
	#define STR0018 "Final - Diccionario de Archivos"
	#define STR0019 "Inicio - Diccionario de Datos"
	#define STR0020 "Analizando Diccionario de Datos..."
	#define STR0021 "Final - Diccionario de Datos"
	#define STR0022 "Inicio - Parametros"
	#define STR0023 "Analizando Parametros..."
	#define STR0024 "Final - Parametros"
	#define STR0025 "Inicio - Disparadores"
	#define STR0026 "Analizando Disparadores..."
	#define STR0027 "Final - Disparadores"
	#define STR0028 "Inicio - indices"
	#define STR0029 "Analizando archivos de indices. "
	#define STR0030 "Final - indices"
	#define STR0031 "Inicio - Consultas Estandares"
	#define STR0032 "Analizando consultas estandares..."
	#define STR0033 "Final - Consultas Estandares"
	#define STR0034 "Inicio - Ajustando menus"
	#define STR0035 "Final - Ajustando menus"
	#define STR0036 "Inicio - Abriendo Tablas"
	#define STR0037 "Final - Abriendo Tablas"
	#define STR0038 "Actualizacion Concluida."
	#define STR0039 "Log de la Actualizacion "
	#define STR0040 "Actualizacion Concluida."
	#define STR0041 "Planilla"
	#define STR0042 "Planilla de informacion de precio para composicion del precio sugerido"
	#define STR0043 "¿De Fecha?"
	#define STR0044 "Fecha inicial para composicion de los datos de gestion"
	#define STR0045 "¿A Fecha?"
	#define STR0046 "Fecha final para composicion de los datos de gestion"
	#define STR0047 "Categorias"
	#define STR0048 "Publicacion de Precios"
	#define STR0049 "Items de las Publicaciones de Precios"
	#define STR0050 "Publicaciones vs. Sucursales"
	#define STR0051 "Sucursal"
	#define STR0052 "Sucursal de Control"
	#define STR0053 "Codigo"
	#define STR0054 "Codigo de la publicacion"
	#define STR0055 "Codigo que identifica la publicacion de precios"
	#define STR0056 "Descripcion"
	#define STR0057 "Descripcion de la publicacion"
	#define STR0058 "Descripcion que identifica la publicacion de precios."
	#define STR0059 "Fecha Inicial"
	#define STR0060 "Fecha inicial vigencia"
	#define STR0061 "Fecha inicial de vigencia para la lista de precios"
	#define STR0062 "Hora Inicial"
	#define STR0063 "Hora inicial vigencia"
	#define STR0064 "Hora inicial de vigencia para la lista de precios"
	#define STR0065 "Grup Sucursales"
	#define STR0066 "Grupo de Sucursales"
	#define STR0067 "Grupo de sucursales para la generacion de la lista de precios"
	#define STR0068 "¿Lista Activa?"
	#define STR0069 "¿Lista Activa?"
	#define STR0070 "Indica si la lista de precios debe generarse activa o no"
	#define STR0071 "Codigo de la publicacion"
	#define STR0072 "Codigo que identifica la publicacion de precios."
	#define STR0073 "Item"
	#define STR0074 "Item de la publicacion"
	#define STR0075 "Item de publicacion de precios."
	#define STR0076 "Producto"
	#define STR0077 "Codigo del Producto"
	#define STR0078 "Codigo del producto que conforma la publicacion de precios."
	#define STR0079 "Descripcion del Producto"
	#define STR0080 "Precio actual para el producto."
	#define STR0081 "Prec Sugerido"
	#define STR0082 "Precio Sugerido"
	#define STR0083 "Cod. Sucursal"
	#define STR0084 "Codigo de la Sucursal"
	#define STR0085 "Codigo de la sucursal que participa de la publicacion."
	#define STR0086 "Lote de la Gestion de Calculo de Precio"
	#define STR0087 "Lote de la Gestion"
	#define STR0088 "¿Publicacion hecha efectiva?"
	#define STR0089 "¿Hecho Efectivo?"
	#define STR0090 "Indica si la publicacion ya se hizo efectiva para esta sucursal."
	#define STR0091 "Sucursal + Publicacion"
	#define STR0092 "Sucursal + Publicacion + Item"
	#define STR0093 "Sucursal + Publicacion + Cod. Sucursal"
	#define STR0094 "Producto "
	#define STR0095 "Producto  "
	#define STR0096 "Descripcion"
	#define STR0097 "Grupo"
	#define STR0098 "Archivo Nuevo"
	#define STR0099 "Descripcion"
	#define STR0100 "¡Atencion!"
	#define STR0101 "¡No se pudo abrir la tabla de empresas en forma exclusiva!"
	#define STR0102 "El menu del modulo CONTROL DE TIENDAS se actualizo."
	#define STR0103 "No fue necesario actualizar el menu modulo CONTROL DE TIENDAS."
	#define STR0104 "Archivos Texto (*.TXT) |*.txt|"
	#define STR0105 "Planilla de elaboracion de precio para "
	#define STR0106 "composicion del precio sugerido."
	#define STR0107 "Fecha inicial para composicion de los"
	#define STR0108 "datos de gestion."
	#define STR0109 "Fecha final para composicion de los"
	#define STR0110 "¿A Fecha?"
	#define STR0111 "¿Seleccionar Categorias?"
	#define STR0112 "Si"
	#define STR0113 "Codigo que identifica la publicacion"
	#define STR0114 "de precios."
	#define STR0115 "Descripcion que identifica la publicacion"
	#define STR0116 "Fecha inicial de vigencia para la"
	#define STR0117 "lista de precios."
	#define STR0118 "Hora inicial de vigencia para la"
	#define STR0119 "Grupo de sucursales para la generacion de la lista"
	#define STR0120 "Indica si la lista de precios debe "
	#define STR0121 "generarse activa o no."
	#define STR0122 "¿Hecha Efectiva?"
	#define STR0123 "1=Hecha Efectiva;2=Parcialmente efectiva;3=En composicion"
	#define STR0124 "Indica el estatus de la publicacion de precio."
	#define STR0125 "de precio."
	#define STR0126 "Codigo del producto que conforma la publica"
	#define STR0127 "cion de precios."
	#define STR0128 "Descripcion del producto que compone la"
	#define STR0129 "publicacion de precios."
	#define STR0130 "Prc. Actual"
	#define STR0131 "Precio Actual"
	#define STR0132 "Precio sugerido para el producto de acuerdo con "
	#define STR0133 "planilla de formacion de precios."
	#define STR0134 "Codigo que identifica la publicacion de"
	#define STR0135 "Codigo de la sucursal que participa de la "
	#define STR0136 "publicacion."
	#define STR0137 "Lot.Gest.Prc"
	#define STR0138 "Codigo del lote de Gestion de Calculo de Precio "
	#define STR0139 "para control de efectivizacion."
	#define STR0140 "Pub.Efectiva"
	#define STR0141 "Indica si la publicacion ya se hizo efectiva "
	#define STR0142 "para esta sucursal."
	#define STR0143 "Producto"
	#define STR0144 "Sucursal + Cod. Sucursal + Lote"
#else
	#ifdef ENGLISH
		#define STR0001 "This program adjusts data dictionaries for "
		#define STR0002 "implementing improvements related to price publishing.   "
		#define STR0003 "Implementing price publishing Configurator."
		#define STR0004 "Base Updater"
		#define STR0005 "Cancel"
		#define STR0006 "Proceed"
		#define STR0007 "Operation Canceled!"
		#define STR0008 "Checking dictionaries integrity...."
		#define STR0009 "Company : "
		#define STR0010 "Start - Checking primary keys and indices..."
		#define STR0011 "Checking primary keys and indices..."
		#define STR0012 "End - Checking primary keys and indices..."
		#define STR0013 "Start - Analyzing Question Dictionary..."
		#define STR0014 "Analyzing Question Dictionary..."
		#define STR0015 "End - Analyzing Question Dictionary..."
		#define STR0016 "Start - Files Dictionary"
		#define STR0017 "Analyzing Files Dictionary..."
		#define STR0018 "End - Files Dictionary"
		#define STR0019 "Start - Data Dictionary"
		#define STR0020 "Analyzing Data Dictionary..."
		#define STR0021 "End - Data Dictionary"
		#define STR0022 "Start - Parameters"
		#define STR0023 "Analyzing Parameters..."
		#define STR0024 "End - Parameters"
		#define STR0025 "Start - Triggers"
		#define STR0026 "Analyzing Triggers..."
		#define STR0027 "End - Triggers"
		#define STR0028 "Start - indices"
		#define STR0029 "Analyzing indices files. "
		#define STR0030 "End - indices"
		#define STR0031 "Starto - Standard Queries"
		#define STR0032 "Analyzing standard queries..."
		#define STR0033 "End - Standard Queries"
		#define STR0034 "Start - Adjusting menus"
		#define STR0035 "End - Adjusting menus"
		#define STR0036 "Start - Opening Tables"
		#define STR0037 "End - Opening Tables"
		#define STR0038 "Update Completed."
		#define STR0039 "Update Log "
		#define STR0040 "Update Completed."
		#define STR0041 "Worksheet"
		#define STR0042 "Price information worksheet to make up the price suggested"
		#define STR0043 "Date from?"
		#define STR0044 "Initial date to make up management data"
		#define STR0045 "Date to?"
		#define STR0046 "Final date to make up management data"
		#define STR0047 "Categories"
		#define STR0048 "Price Publications"
		#define STR0049 "Items of Price Publications"
		#define STR0050 "Publications x Branches"
		#define STR0051 "Branch"
		#define STR0052 "Control Branch"
		#define STR0053 "Code"
		#define STR0054 "Publication Code"
		#define STR0055 "Code that identifies price publication."
		#define STR0056 "Description"
		#define STR0057 "Publication Description"
		#define STR0058 "Description that identifies price publication."
		#define STR0059 "Initial Date"
		#define STR0060 "Initial Effective Date"
		#define STR0061 "Initial effective date for price list."
		#define STR0062 "Initial Time"
		#define STR0063 "Initial Effective Time"
		#define STR0064 "Initial effective time for price list."
		#define STR0065 "Branch Grp."
		#define STR0066 "Branch Group"
		#define STR0067 "Branch group to generate price list."
		#define STR0068 "Active Lt.?"
		#define STR0069 "Active List?"
		#define STR0070 "Indicates whether price list must be generated active."
		#define STR0071 "Publication Code"
		#define STR0072 "Code that identifies price publication."
		#define STR0073 "Item"
		#define STR0074 "Publication Item"
		#define STR0075 "Item of price publication."
		#define STR0076 "Product"
		#define STR0077 "Product Code"
		#define STR0078 "Code of the product that makes up price publication."
		#define STR0079 "Product Description"
		#define STR0080 "Current price for the product."
		#define STR0081 "Suggested Prc"
		#define STR0082 "Suggested Price"
		#define STR0083 "Branch Cd."
		#define STR0084 "Branch code"
		#define STR0085 "Code of the branch that participates in publication."
		#define STR0086 "Pricing Management Lot"
		#define STR0087 "Management Lot"
		#define STR0088 "Publication Confirmed?"
		#define STR0089 "Confirmed?"
		#define STR0090 "Indicates whether publication has already been confirmed for this branch."
		#define STR0091 "Branch + Publication"
		#define STR0092 "Branch + Publication + Item"
		#define STR0093 "Branch + Publication + Branch Cd."
		#define STR0094 "Product "
		#define STR0095 "Product  "
		#define STR0096 "Description"
		#define STR0097 "Group"
		#define STR0098 "Register New"
		#define STR0099 "Description"
		#define STR0100 "Attention!"
		#define STR0101 "Company table could not be opened in exclusive mode!"
		#define STR0102 "Menu of SIGALOJA module already updated."
		#define STR0103 "Menu of SIGALOJA module did not require update."
		#define STR0104 "Text files (*.TXT) |*.txt|"
		#define STR0105 "Pricing worksheet to "
		#define STR0106 "make up the suggested price."
		#define STR0107 "Initial date to make up"
		#define STR0108 "management data."
		#define STR0109 "Final date to make up"
		#define STR0110 "Date to?"
		#define STR0111 "Select Categories?"
		#define STR0112 "Yes"
		#define STR0113 "Code that identifies price"
		#define STR0114 "publication."
		#define STR0115 "Description that identifies publication."
		#define STR0116 "Initial effective date for"
		#define STR0117 "price list."
		#define STR0118 "Initial effective time for"
		#define STR0119 "Branch group to generate list"
		#define STR0120 "Indicates whether price list must be"
		#define STR0121 "generated active"
		#define STR0122 "Confirmed?"
		#define STR0123 "1=Confirmed;2=Partially confirmed;3=Under composition"
		#define STR0124 "Indicates price publication status."
		#define STR0125 "price."
		#define STR0126 "Code of the product that makes up"
		#define STR0127 "price publication."
		#define STR0128 "Description of the product that makes up"
		#define STR0129 "price publication."
		#define STR0130 "Current Prc."
		#define STR0131 "Current Price"
		#define STR0132 "Price suggested for the product according to"
		#define STR0133 "pricing worksheet."
		#define STR0134 "Code that identifies publication"
		#define STR0135 "Code of the branch that participates in"
		#define STR0136 "publication."
		#define STR0137 "Prc.Man.Lot"
		#define STR0138 "Pricing Management Lot Code "
		#define STR0139 "for effectiveness control."
		#define STR0140 "Pub.Confirm?"
		#define STR0141 "Indicates whether publication has already been confirmed"
		#define STR0142 "for this branch."
		#define STR0143 "Product"
		#define STR0144 "Branch + Branch Code + Lot"
	#else
		#define STR0001 "Este programa tem como objetivo ajustar os dicionários de dados para a "
		#define STR0002 "implementação da melhoria relacionada a publicações de preços.   "
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "A implementar o configurador de publicações de preços.", "Implementando Configurador de publicações de preços." )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Actualizador de Base", "Atualizador de Base" )
		#define STR0005 "Cancelar"
		#define STR0006 "Prosseguir"
		#define STR0007 "Operação cancelada!"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "A verificar a integridade dos dicionários....", "Verificando integridade dos dicionários...." )
		#define STR0009 "Empresa : "
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Início - A verificar as chaves primárias e índices...", "Início - Verificando chaves primárias e índices..." )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "A verificar as chaves primárias e índices...", "Verificando chaves primárias e índices..." )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Fim - A verificar as chaves primárias e índices...", "Fim - Verificando chaves primárias e índices..." )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Início - A analisar o Dicionário de Perguntas...", "Início - Analisando Dicionario de Perguntas..." )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "A analisar o Dicionário de Perguntas...", "Analisando Dicionario de Perguntas..." )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Fim - A analisar o Dicionário de Perguntas...", "Fim - Analisando Dicionario de Perguntas..." )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Início - Dicionário de Ficheiros", "Início - Dicionario de Arquivos" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "A analisar o Dicionário de Ficheiros...", "Analisando Dicionario de Arquivos..." )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Fim - Dicionário de Ficheiros", "Fim - Dicionario de Arquivos" )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Início - Dicionário de Dados", "Início - Dicionario de Dados" )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "A analisar os Dicionário de Dados...", "Analisando Dicionario de Dados..." )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Fim - Dicionário de Dados", "Fim - Dicionario de Dados" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Início - Parâmetros", "Início - Parametros" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "A analisar os parâmetros...", "Analisando Parametros..." )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Fim - Parâmetros", "Fim - Parametros" )
		#define STR0025 "Início - Gatilhos"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "A analisar os gatilhos...", "Analisando Gatilhos..." )
		#define STR0027 "Fim - Gatilhos"
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Início - Índices", "Início - índices" )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "A analisar os ficheiros de índices. ", "Analisando arquivos de índices. " )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Fim - Índices", "Fim - índices" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Início - Consultas Padrão", "Início - Consultas Padroes" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "A analisar as consultas padrão...", "Analisando consultas padroes..." )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Fim - Consultas Padrão", "Fim - Consultas Padroes" )
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Início - A ajustar os menus", "Início - Ajustando menus" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Fim - A ajustar os menus", "Fim - Ajustando menus" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Início - A abrir as tabelas", "Início - Abrindo Tabelas" )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Fim - A abrir as tabelas", "Fim - Abrindo Tabelas" )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Actualização concluída.", "Atualização Concluída." )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Log da Actualização ", "Log da Atualização " )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Actualização concluída.", "Atualizacao Concluída." )
		#define STR0041 "Planilha"
		#define STR0042 "Planilha de informação de preço para composição do preço sugerido"
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "De data?", "Data de?" )
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Data de início para a composição dos dados gerenciais", "Data de início para composição dos dados gerenciais" )
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Até a data até?", "Data até?" )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Data de término para a composição dos dados gerenciais", "Data de término para composição dos dados gerenciais" )
		#define STR0047 "Categorias"
		#define STR0048 "Publicações de Preços"
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Itens das publicações de preços", "Itens das publicações de Preços" )
		#define STR0050 "Publicações X Filiais"
		#define STR0051 "Filial"
		#define STR0052 "Filial de Controle"
		#define STR0053 "Código"
		#define STR0054 "Código da publicação"
		#define STR0055 "Código que identifica a publicação de preços"
		#define STR0056 "Descrição"
		#define STR0057 "Descrição da publicação"
		#define STR0058 "Descrição que identifica a publicação de preços."
		#define STR0059 "Data Inicial"
		#define STR0060 "Data início vingência"
		#define STR0061 "Data de início de vigência para a tabela de preços"
		#define STR0062 "Hora Inicial"
		#define STR0063 "Hora início vingência"
		#define STR0064 "Hora de início de vigência para a tabela de preços"
		#define STR0065 "Grp. Filiais"
		#define STR0066 "Grupo de Filiais"
		#define STR0067 "Grupo de filiais para a geração da tabela de preços"
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Tab.Activa?", "Tab.Ativa?" )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Tabela Activa?", "Tabela Ativa?" )
		#define STR0070 "Indica se a tabela de preços deverá ser gerada ativa ou não"
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Código da publicação", "Código da publicacão" )
		#define STR0072 "Código que identifica a publicação de preços."
		#define STR0073 "Item"
		#define STR0074 "Item da publicação"
		#define STR0075 "Item de publicação de preços."
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Artigo", "Produto" )
		#define STR0077 If( cPaisLoc $ "ANG|PTG", "Código do Artigo", "Código do Produto" )
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "Código do artigo que compõe a publicação de preços.", "Código do produto que compõe a publicação de preços." )
		#define STR0079 If( cPaisLoc $ "ANG|PTG", "Descrição do Artigo", "Descrição do Produto" )
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "Preço actual para o artigo.", "Preço atual para o produto." )
		#define STR0081 "Prc Sugerido"
		#define STR0082 "Preço Sugerido"
		#define STR0083 "Cód. Filial"
		#define STR0084 "Código da Filial"
		#define STR0085 "Código da filial que participa da publicação."
		#define STR0086 "Lote da Gestão de Precificação"
		#define STR0087 "Lote da Gestão"
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "Publicação efectivada?", "Publicação efetivada?" )
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "Efectivado?", "Efetivado?" )
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "Indica se a publicação já foi efectivada para esta filial.", "Indica se a publicação já foi efetivada para esta filial." )
		#define STR0091 "Filial + Publicação"
		#define STR0092 "Filial + Publicação + Item"
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "Filial + Publicação + Cód. Filial", "Filial + Publicação + Cod. Filial" )
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Artigo ", "Produto " )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Artigo  ", "Produto  " )
		#define STR0096 If( cPaisLoc $ "ANG|PTG", "Descrição", "Descricão" )
		#define STR0097 "Grupo"
		#define STR0098 If( cPaisLoc $ "ANG|PTG", "Regista Novo", "Cadastra Novo" )
		#define STR0099 If( cPaisLoc $ "ANG|PTG", "Descrição", "Descricao" )
		#define STR0100 If( cPaisLoc $ "ANG|PTG", "Atenção!", "Atencao !" )
		#define STR0101 If( cPaisLoc $ "ANG|PTG", "Não foi possível a abertura da tabela de empresas de forma exclusiva!", "Nao foi possivel a abertura da tabela de empresas de forma exclusiva !" )
		#define STR0102 If( cPaisLoc $ "ANG|PTG", "O menu do módulo SIGALOJA foi actualizado.", "O menu do módulo SIGALOJA foi atualizado." )
		#define STR0103 If( cPaisLoc $ "ANG|PTG", "Não foi necessário actualizar o menu módulo SIGALOJA.", "Não foi necessário atualizar o menu módulo SIGALOJA." )
		#define STR0104 If( cPaisLoc $ "ANG|PTG", "Registo Texto (*.TXT) |*.txt|", "Arquivos Texto (*.TXT) |*.txt|" )
		#define STR0105 "Planilha de formação de preço para "
		#define STR0106 "composição do preço sugerido."
		#define STR0107 "Data de início para composição dos"
		#define STR0108 "dados gerenciais."
		#define STR0109 "Data de término para composição dos"
		#define STR0110 If( cPaisLoc $ "ANG|PTG", "Até a data?", "Data ate?" )
		#define STR0111 If( cPaisLoc $ "ANG|PTG", "Seleccionar categorias?", "Selecionar Categorias?" )
		#define STR0112 "Sim"
		#define STR0113 "Código que identifica a publicação"
		#define STR0114 "de preços."
		#define STR0115 "Descrição que identifica a publicação"
		#define STR0116 "Data de início de vigência para a"
		#define STR0117 "tabela de preços."
		#define STR0118 "Hora de início de vigência para a"
		#define STR0119 "Grupo de filiais para geração da tabela"
		#define STR0120 "Indica se a tabela de preços deverá ser"
		#define STR0121 If( cPaisLoc $ "ANG|PTG", "gerada activa ou não.", "gerada ativa ou não." )
		#define STR0122 If( cPaisLoc $ "ANG|PTG", "Efectivada?", "Efetivada?" )
		#define STR0123 If( cPaisLoc $ "ANG|PTG", "1=Efectivada;2=Parcialmente efectivada;3=Em composição", "1=Efetivada;2=Parcialmente efetivada;3=Em composicao" )
		#define STR0124 If( cPaisLoc $ "ANG|PTG", "Indica o estado da publicação de preço.", "Indica o status da publicação de preço." )
		#define STR0125 "de preço."
		#define STR0126 If( cPaisLoc $ "ANG|PTG", "Código do artigo que compõe a publica", "Código do produto que compõe a publica" )
		#define STR0127 "ção de preços."
		#define STR0128 If( cPaisLoc $ "ANG|PTG", "Descrição do artigo que compõe a", "Descrição do produto que compõe a" )
		#define STR0129 "publicação de preços."
		#define STR0130 If( cPaisLoc $ "ANG|PTG", "Prc. Actual", "Prc. Atual" )
		#define STR0131 If( cPaisLoc $ "ANG|PTG", "Preço Actual", "Preço Atual" )
		#define STR0132 If( cPaisLoc $ "ANG|PTG", "Preço sugerido para o artigo conforme", "Preço sugerido para o produto conforme" )
		#define STR0133 "planilha de formação de preços."
		#define STR0134 "Código que identifica a publicação de"
		#define STR0135 If( cPaisLoc $ "ANG|PTG", "Código da filial que participa da", "Código da Filial que participa da" )
		#define STR0136 "publicação."
		#define STR0137 "Lot.Gest.Prc"
		#define STR0138 "Código do lote da Gestão de Precificação "
		#define STR0139 If( cPaisLoc $ "ANG|PTG", "para controlo de efectivação.", "para controle de efetivação." )
		#define STR0140 If( cPaisLoc $ "ANG|PTG", "Pub.Efectiva?", "Pub.Efetiva?" )
		#define STR0141 If( cPaisLoc $ "ANG|PTG", "Indica se a publicação já foi efectivada", "Indica se a publicação já foi efetivada" )
		#define STR0142 "para esta filial."
		#define STR0143 If( cPaisLoc $ "ANG|PTG", "Artigo", "Produto" )
		#define STR0144 If( cPaisLoc $ "ANG|PTG", "Filial + Cód. Filial + Lote", "Filial + Cod. Filial + Lote" )
	#endif
#endif
