#ifdef SPANISH
	#define STR0001 "¿Desea efectuar la actualización del Diccionario? ¡Esta rutina debe utilizarse de modo exclusivo! ¡Haga una copia de seguridad de los diccionarios y de la Base de datos antes de la actualización para eventuales falhas de actualización!"
	#define STR0002 "Atención"
	#define STR0003 "Actualización del diccionario"
	#define STR0004 "Procesando"
	#define STR0005 "¡Espere! Preparación de los archivos..."
	#define STR0006 "Verificando integridad de los diccionarios..."
	#define STR0007 "Empresa: "
	#define STR0008 "Atualizando estructuras. Espere... ["
	#define STR0009 "]"
	#define STR0010 "¡Atención!"
	#define STR0011 "¡No fue posible la apertura de la tabla de empresas de forma exclusiva!"
	#define STR0012 "Ok"
	#define STR0013 "Archivos texto"
	#define STR0014 "Ocurrió un error desconocido durante la actualización de la tabla: "
	#define STR0015 ". Verifique la integridad del diccionario y de la tabla."
	#define STR0016 "Continuar"
	#define STR0017 "Ocurrió un error desconocido durante la actualización de la estructura de la tabla: "
	#define STR0018 "Log de la actualización"
	#define STR0019 "Actualización concluida."
	#define STR0020 "Actualizando parámetros..."
	#define STR0021 "Parámetro actualizado:"
	#define STR0022 "Parámetro"
	#define STR0023 "existente en el diccionario de datos."
#else
	#ifdef ENGLISH
		#define STR0001 "Do you want to update Dictionary? Use this routine in exclusive mode! Backup the dictionaries and the database prior to updating, to prevent contingent update failure!"
		#define STR0002 "Attention"
		#define STR0003 "Dictionary Update"
		#define STR0004 "Processing"
		#define STR0005 "Wait! File preparation..."
		#define STR0006 "Checking dictionary integrity..."
		#define STR0007 "Company: "
		#define STR0008 "Updating structures. Wait... ["
		#define STR0009 "]"
		#define STR0010 "Attention!"
		#define STR0011 "Company table could not be opened in exclusive mode!"
		#define STR0012 "Ok"
		#define STR0013 "Text Files"
		#define STR0014 "There was an unknown error during table update: "
		#define STR0015 ". Check dictionary and table integrity."
		#define STR0016 "Continue"
		#define STR0017 "An unknown error occurred during table structure update: "
		#define STR0018 "Update Log "
		#define STR0019 "Update completed."
		#define STR0020 "Updating parameters..."
		#define STR0021 "Parameter updated:"
		#define STR0022 "Parameter"
		#define STR0023 "already in data dictionary."
	#else
		#define STR0001 "Deseja efetuar a atualização do Dicionário? Esta rotina deve ser utilizada em modo exclusivo! Faça um backup dos dicionários e da Base de Dados antes da atualização para eventuais falhas de atualização!"
		#define STR0002 "Atenção"
		#define STR0003 "Atualização do Dicionário"
		#define STR0004 "Processando"
		#define STR0005 "Aguarde! Preparação dos arquivos..."
		#define STR0006 "Verificando integridade dos dicionários..."
		#define STR0007 "Empresa : "
		#define STR0008 "Atualizando estruturas. Aguarde... ["
		#define STR0009 "]"
		#define STR0010 "Atenção!"
		#define STR0011 "Não foi possível a abertura da tabela de empresas de forma exclusiva!"
		#define STR0012 "Ok"
		#define STR0013 "Arquivos Texto"
		#define STR0014 "Ocorreu um erro desconhecido durante a atualização da tabela : "
		#define STR0015 ". Verifique a integridade do dicionário e da tabela."
		#define STR0016 "Continuar"
		#define STR0017 "Ocorreu um erro desconhecido durante a atualização da estrutura da tabela : "
		#define STR0018 "Log da atualização "
		#define STR0019 "Atualização concluída."
		#define STR0020 "Atualizando parâmetros..."
		#define STR0021 "Parâmetro atualizado:"
		#define STR0022 "Parâmetro"
		#define STR0023 "já existente no dicionário de dados."
	#endif
#endif
