#ifdef SPANISH
	#define STR0001 "ACTUALIZACION DE DICCIONARIOS Y TABLAS"
	#define STR0002 "La funcion de esta rutina es actualizar los diccionarios del sistema ( SX?/SIX )"
	#define STR0005 "Este proceso se debe ejecutar en modo EXCLUSIVO, es decir, no deben estar otros"
	#define STR0006 "usuarios o jobs estan utilizando el sistema.  Es extremamente recomendable que se haga una"
	#define STR0007 "BACKUP de los DICCIONARIOS y de la BASE DE DATOS antes de esta actualizacion. "
	#define STR0008 "¿Confirma la actualizacion de los diccionarios?"
	#define STR0009 "Actualizando"
	#define STR0010 "Espere, actualizando ..."
	#define STR0011 "Actualizacion concluida."
	#define STR0012 "Actualizacion no realizada."
	#define STR0013 "Archivos texto"
	#define STR0014 "Actualizacion de la empresa "
	#define STR0015 " no efectuada."
	#define STR0016 "Empresa"
	#define STR0024 "LOG DE ACTUALIZACION DE LOS DICCIONARIOS"
	#define STR0025 " Datos entorno"
	#define STR0026 " Empresa/Sucursal...: "
	#define STR0027 " Nombre empresa...: "
	#define STR0028 " Nombre sucursal...: "
	#define STR0029 " Fecha / Hora inicial.: "
	#define STR0030 " Version.............: "
	#define STR0031 " Usuario TOTVS .....: "
	#define STR0032 " Fecha / Hora final: "
	#define STR0033 "Actualizacion concluida."
	#define STR0043 "Inicio de la actualizacion"
	#define STR0054 "Seleccione la(s) empresa(s) para actualizacion"
	#define STR0055 "Todos"
	#define STR0056 "Pantalla para multiple seleccion de Empresas/Sucursales"
	#define STR0057 "&Invertir"
	#define STR0073 "El tamano del campo "
	#define STR0074 " no se actualizo y se mantuvo en ["
	#define STR0075 "   porque pertenece al grupo de campos ["
	#define STR0076 "Se creo el campo "
	#define STR0077 " esta con el "
	#define STR0078 " con el contenido"
	#define STR0079 "que se sustituira por el NUEVO contenido"
	#define STR0080 "ACTUALIZACION DE DICCIONARIOS Y TABLAS"
	#define STR0081 "Si"
	#define STR0082 "No"
	#define STR0083 "Si p/todos"
	#define STR0084 "No p/todos"
	#define STR0085 "Diferencia de contenido - SX3"
	#define STR0086 "Diccionario de parametros - "
	#define STR0087 "¿Confirma la accion [Si p/Todos] ?"
	#define STR0088 "Se selecciono la opcion NO REALIZAR ninguna modificacion en el SX3 que sea diferente de la base y NO MOSTRAR mas la pantalla de aviso."
	#define STR0089 "¿Confirma esta accion [No p/todos]?"
	#define STR0090 "Se modifico el campo "
	#define STR0091 " de ["
	#define STR0092 "            para ["
	#define STR0093 "Actualizando campos de tablas (SX3)..."
	#define STR0094 "Final de la actualizacion"
	#define STR0095 ' esta con el contenido'
	#define STR0096 ', que se sustituira por el NUEVO contenido '
	#define STR0097 '¿Desea sustituirlo? '
	#define STR0098 'Confirmar sustitucion de contenido'
	#define STR0099 'Se modifico el parametro '
	#define STR0100 ' de ['
	#define STR0101 ' a ['
	#define STR0102 'Se incluyo el parametro '
	#define STR0103 ' Contenido ['
	#define STR0104 'Actualizando archivos (SX6)...'
	#define STR0105 'Final de actualizacion del SX6'
	#define STR0106 "Marca/Desmarca todos"
	#define STR0109 "Se modifico la consulta estandar "
	#define STR0110 "Actualizando Consultas Estandar (SXB)..."
	#define STR0111 'Inicio de actualizacion del SX6'
	#define STR0112 'El parametro '
	#define STR0114 "Se incluyo la consulta estandar "
	#define STR0115 "Mascara empresa ( ?? )"
	#define STR0116 "Marcar usando mascara ( ?? )"
	#define STR0117 "Desmarcar usando mascara ( ?? )"
	#define STR0118 "Confirma la seleccion"
	#define STR0119 "Abandona la seleccion"
	#define STR0120 "No fue posible abrir la tabla "
	#define STR0121 "de empresas (SM0)."
	#define STR0122 "de empresas (SM0) de forma exclusiva."
	#define STR0123 "ATENCION"
	#define STR0124 "Direccion AGA"
	#define STR0125 "Funcionalidad de venta fuera del estado"
	#define STR0126 "Indice modificado "
	#define STR0127 "Plazo de entrega de la tienda al cliente"
	#define STR0128 "Direccion"
	#define STR0129 "¿VFE?"
	#define STR0130 "¿Venta fuera de Est/Prov/Reg?"
	#define STR0131 "Sucursal del pedido"
	#define STR0132 "Sucursal"
	#define STR0133 "Sucursal + RpcFil"
	#define STR0134 "Codigo entid+CEP"
	#define STR0135 "Indice creado "
	#define STR0136 "Indice modificado "
	#define STR0137 "Actualizando indices..."
	#define STR0138 "Final de la actualizacion"
	#define STR0139 "Hubo un error desconocido durante la actualizacion de la tabla: "
	#define STR0140 ". Verifique la integridad del diccionario y de la tabla."
	#define STR0141 "Hubo un error desconocido durante la actualizacion de la estructura de la tabla: "
	#define STR0142 "Desmarcar usando mascara ( ?? )"
	#define STR0143 "&Desmarcar"
	#define STR0144 "&Marcar"
	#define STR0145 "Invertir seleccion"
	#define STR0146 "&Invertir"
	#define STR0147 "Pantalla para multiple seleccion de Empresas/Sucursales"
	#define STR0148 "Seleccione la(s) empresa(s) para actualizacion"
	#define STR0149 "Entrega"
	#define STR0150 "1=Retira Posterior;2=Retira;3=Entrega"
	#define STR0151 "Sucursal del sistema."
	#define STR0152 "De CP"
	#define STR0153 "A CP"
	#define STR0154 "Sucursal Stock"
	#define STR0155 "Sucursal de reserva de stock"
	#define STR0156 "Lugar stock"
	#define STR0157 "Lugar de reserva de stock"
	#define STR0158 "Dias Reserva"
	#define STR0159 "Dias de reserva de stock"
	#define STR0160 "Rango de CP"
	#define STR0161 "Se creo clave unica de la tabla "
	#define STR0162 "Se modifico clave unica de la tabla "
	#define STR0163 "Se incluyo la tabla "
	#define STR0164 "Actualizando archivos (SX2)..."
	#define STR0165 "De CP+A CP"
	#define STR0166 "Diccionario de indices - "
	#define STR0167 "Diccionario de archivos - "
	#define STR0168 "Sucursal VFE"
	#define STR0169 "Inicio de la actualizacion"
	#define STR0170 "Helps de campos"
	#define STR0171 "Actualizando Helps de campo..."
	#define STR0172 "Indica si es una operacion de Venta fuera del Est/Prov/Reg."
	#define STR0173 "Se actualizo el Help de campo "
	#define STR0174 "Sucursal donde se genera el pedido de ventas para entrega."
	#define STR0175 "Sucursal del sistema"
	#define STR0176 "CP Inicial del intervalo de CP"
	#define STR0177 "CP Final del intervalo de CP"
	#define STR0178 "Sucursal de reserva de stock"
	#define STR0179 "Lugar de stock (Almacen)"
	#define STR0180 "Indica los dias de reserva"
	#define STR0181 "Sucursal de entrega al realizar una operacion de VFE"
	#define STR0182 "Plazo de entrega"
	#define STR0183 "Plazo de entrega"
	#define STR0184 "Final de la actualizacion"
#else
	#ifdef ENGLISH
		#define STR0001 "TABLE AND DICTIONARY UPDATE"
		#define STR0002 "Does this routine update system dictionaries ( SX?/SIX )"
		#define STR0005 "This process must be run in EXCLUSIVE mode, that is, other"
		#define STR0006 "users or jobs using the system cannot exist.  You must make"
		#define STR0007 "BACKUP of DICTIONARIES and DATABASE before this update. "
		#define STR0008 "Confirm dictionary update?"
		#define STR0009 "Updating"
		#define STR0010 "Wait, updating ..."
		#define STR0011 "Update Completed."
		#define STR0012 "Update not Performed."
		#define STR0013 "Text Files"
		#define STR0014 "Company Update "
		#define STR0015 " not made."
		#define STR0016 "Company"
		#define STR0024 "DICTIONARY UPDATE LOG"
		#define STR0025 " Environment Data"
		#define STR0026 " Company/Branch...: "
		#define STR0027 " Company Name.......: "
		#define STR0028 " Branch Name........: "
		#define STR0029 " Start Date/Time: "
		#define STR0030 " Version.............: "
		#define STR0031 " TOTVS User .......: "
		#define STR0032 " End Date/Time: "
		#define STR0033 "Update completed."
		#define STR0043 "Start of Update"
		#define STR0054 "Select Companies for Update"
		#define STR0055 "All"
		#define STR0056 "Screen for Multiple Selections of Companies/Branches"
		#define STR0057 "&Invert"
		#define STR0073 "Field size "
		#define STR0074 " not updated and kept in ["
		#define STR0075 "   because it belongs to field group ["
		#define STR0076 "Created field "
		#define STR0077 " is with the "
		#define STR0078 " with the content"
		#define STR0079 "to be replaced with the NEW content"
		#define STR0080 "TABLE AND DICTIONARY UPDATE"
		#define STR0081 "Yes"
		#define STR0082 "No"
		#define STR0083 "Yes for All"
		#define STR0084 "No for All"
		#define STR0085 "Content difference - SX3"
		#define STR0086 "Dictionary of parameters - "
		#define STR0087 "Do you confirm the action [Yes for All]?"
		#define STR0088 "The option DO NOT MAKE any change in SX3 that is different from the base and DO NOT SHOW warning screen anymore was selected."
		#define STR0089 "Do you confirm this action [No for All]?"
		#define STR0090 "Changed field "
		#define STR0091 " from ["
		#define STR0092 "            to ["
		#define STR0093 "Updating Table Fields (SX3)..."
		#define STR0094 "End of Update"
		#define STR0095 ' is with the content'
		#define STR0096 'to be replaced with the NEW content '
		#define STR0097 'Replace it? '
		#define STR0098 'Confirm content replacement'
		#define STR0099 'Parameter was changed '
		#define STR0100 ' from ['
		#define STR0101 ' to ['
		#define STR0102 'Parameter was added '
		#define STR0103 ' Content ['
		#define STR0104 'Updating Files (SX6)...'
		#define STR0105 'End of SX6 Update'
		#define STR0106 "Select / Clear All"
		#define STR0109 "Standard query was changed "
		#define STR0110 "Updating Standard Queries (SXB)..."
		#define STR0111 'Start of SX6 Update'
		#define STR0112 'Parameter '
		#define STR0114 "Standard query was added "
		#define STR0115 "Company Mask (?? )"
		#define STR0116 "Select by using mask (?? )"
		#define STR0117 "Clear by using mask (?? )"
		#define STR0118 "Confirm selection"
		#define STR0119 "Quit selection"
		#define STR0120 "Table could not be opened "
		#define STR0121 "of companies (SM0)."
		#define STR0122 "of companies (SM0) exclusively."
		#define STR0123 "ATTENTION"
		#define STR0124 "Address AGA"
		#define STR0125 "Functionality of Sales Outside State"
		#define STR0126 "Index changed "
		#define STR0127 "Delivery term of store for customer"
		#define STR0128 "Address"
		#define STR0129 "VFE?"
		#define STR0130 "Sale out of State?"
		#define STR0131 "Order branch"
		#define STR0132 "Branch"
		#define STR0133 "Branch + RpcFil"
		#define STR0134 "Code ent+Postal Code"
		#define STR0135 "Index created "
		#define STR0136 "Index changed "
		#define STR0137 "Updating indexes..."
		#define STR0138 "End of Update"
		#define STR0139 "There was an unknown error during table update: "
		#define STR0140 ". Check dictionary and table integrity."
		#define STR0141 "An unknown error occurred during table structure update: "
		#define STR0142 "Clear by using mask (?? )"
		#define STR0143 "&Clear"
		#define STR0144 "&Select"
		#define STR0145 "Invert Selection"
		#define STR0146 "&Invert"
		#define STR0147 "Screen for Multiple Selections of Companies/Branches"
		#define STR0148 "Select Companies for Update"
		#define STR0149 "Delivery"
		#define STR0150 "1=Later withdraw; 2=Withdraw; 3=Delivery"
		#define STR0151 "System Branch"
		#define STR0152 "Postal Code from"
		#define STR0153 "Postal code to"
		#define STR0154 "Stock Branch"
		#define STR0155 "Branch of stock reservation"
		#define STR0156 "Stock Local"
		#define STR0157 "Stock reservation local"
		#define STR0158 "Days Reservation"
		#define STR0159 "Stock reservation days"
		#define STR0160 "Range of Postal Codes"
		#define STR0161 "Table unique key was created "
		#define STR0162 "Table unique key was changed "
		#define STR0163 "Table was added "
		#define STR0164 "Updating Files (SX2)..."
		#define STR0165 "Postal code from+Postal code to"
		#define STR0166 "Index dictionary - "
		#define STR0167 "File dictionary - "
		#define STR0168 "Branch VFE"
		#define STR0169 "Start of Update"
		#define STR0170 "Field Helps"
		#define STR0171 "Updating field helps..."
		#define STR0172 "Indicates whether Sales operation is Out of State."
		#define STR0173 "Field help updated "
		#define STR0174 "Branch where sales order is generated for delivery."
		#define STR0175 "System branch"
		#define STR0176 "First Postal Code of range of Postal Codes"
		#define STR0177 "Last Postal Code of range of Postal Codes"
		#define STR0178 "Branch of stock reservation"
		#define STR0179 "Stock location (Warehouse)"
		#define STR0180 "It indicates the reservation days"
		#define STR0181 "VFE operation delivery branch"
		#define STR0182 "Time for Delivery"
		#define STR0183 "Delivery Term"
		#define STR0184 "End of Update"
	#else
		#define STR0001 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
		#define STR0002 "Esta rotina tem como função fazer  a atualização  dos dicionários do Sistema ( SX?/SIX )"
		#define STR0005 "Este processo deve ser executado em modo EXCLUSIVO, ou seja não podem haver outros"
		#define STR0006 "usuários  ou  jobs utilizando  o sistema.  É extremamente recomendavél  que  se  faça um"
		#define STR0007 "BACKUP  dos DICIONÁRIOS  e da  BASE DE DADOS antes desta atualização. "
		#define STR0008 "Confirma a atualização dos dicionários ?"
		#define STR0009 "Atualizando"
		#define STR0010 "Aguarde, atualizando ..."
		#define STR0011 "Atualização Concluída."
		#define STR0012 "Atualização não Realizada."
		#define STR0013 "Arquivos Texto"
		#define STR0014 "Atualização da empresa "
		#define STR0015 " não efetuada."
		#define STR0016 "Empresa"
		#define STR0024 "LOG DA ATUALIZACAO DOS DICIONÁRIOS"
		#define STR0025 " Dados Ambiente"
		#define STR0026 " Empresa / Filial...: "
		#define STR0027 " Nome Empresa.......: "
		#define STR0028 " Nome Filial........: "
		#define STR0029 " Data / Hora Inicio.: "
		#define STR0030 " Versao.............: "
		#define STR0031 " Usuario TOTVS .....: "
		#define STR0032 " Data / Hora Final.: "
		#define STR0033 "Atualizacao concluida."
		#define STR0043 "Inicio da Atualizacao"
		#define STR0054 "Selecione a(s) Empresa(s) para Atualização"
		#define STR0055 "Todos"
		#define STR0056 "Tela para Múltiplas Seleções de Empresas/Filiais"
		#define STR0057 "&Inverter"
		#define STR0073 "O tamanho do campo "
		#define STR0074 " nao atualizado e foi mantido em ["
		#define STR0075 "   por pertencer ao grupo de campos ["
		#define STR0076 "Criado o campo "
		#define STR0077 " está com o "
		#define STR0078 " com o conteúdo"
		#define STR0079 "que será substituido pelo NOVO conteúdo"
		#define STR0080 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
		#define STR0081 "Sim"
		#define STR0082 "Não"
		#define STR0083 "Sim p/Todos"
		#define STR0084 "Não p/Todos"
		#define STR0085 "Diferença de conteúdo - SX3"
		#define STR0086 "Dicionário de parâmetros - "
		#define STR0087 "Confirma a ação [Sim p/Todos] ?"
		#define STR0088 "Foi selecionada a opção de NÃO REALIZAR nenhuma alteração no SX3 que esteja diferente da base e NÃO MOSTRAR mais a tela de aviso."
		#define STR0089 "Confirma esta ação [Não p/Todos]?"
		#define STR0090 "Alterado o campo "
		#define STR0091 " de ["
		#define STR0092 "            para ["
		#define STR0093 "Atualizando Campos de Tabelas (SX3)..."
		#define STR0094 "Final da Atualizacao"
		#define STR0095 ' está com o conteúdo'
		#define STR0096 ', que é será substituido pelo NOVO conteúdo '
		#define STR0097 'Deseja substituir ? '
		#define STR0098 'Confirmar substituição de conteúdo'
		#define STR0099 'Foi alterado o parâmetro '
		#define STR0100 ' de ['
		#define STR0101 ' para ['
		#define STR0102 'Foi incluído o parâmetro '
		#define STR0103 ' Conteúdo ['
		#define STR0104 'Atualizando Arquivos (SX6)...'
		#define STR0105 'Final da Atualizacao do SX6'
		#define STR0106 "Marca / Desmarca Todos"
		#define STR0109 "Foi Alterada a consulta padrao "
		#define STR0110 "Atualizando Consultas Padroes (SXB)..."
		#define STR0111 'Inicio da Atualizacao do SX6'
		#define STR0112 'O parâmetro '
		#define STR0114 "Foi incluída a consulta padrão "
		#define STR0115 "Máscara Empresa ( ?? )"
		#define STR0116 "Marcar usando máscara ( ?? )"
		#define STR0117 "Desmarcar usando máscara ( ?? )"
		#define STR0118 "Confirma a Seleção"
		#define STR0119 "Abandona a Seleção"
		#define STR0120 "Não foi possível a abertura da tabela "
		#define STR0121 "de empresas (SM0)."
		#define STR0122 "de empresas (SM0) de forma exclusiva."
		#define STR0123 "ATENÇÃO"
		#define STR0124 "Endereco AGA"
		#define STR0125 "Funcionalidade de Venda Fora do Estado"
		#define STR0126 "Índice alterado "
		#define STR0127 "Prazo de entrega da loja para o cliente"
		#define STR0128 "Endereço"
		#define STR0129 "VFE?"
		#define STR0130 "Venda fora de Estado?"
		#define STR0131 "Filial do Pedido"
		#define STR0132 "Filial"
		#define STR0133 "Filial + RpcFil"
		#define STR0134 "Codigo entid+CEP"
		#define STR0135 "Índice criado "
		#define STR0136 "Índice alterado "
		#define STR0137 "Atualizando índices..."
		#define STR0138 "Final da Atualizacao"
		#define STR0139 "Ocorreu um erro desconhecido durante a atualização da tabela : "
		#define STR0140 ". Verifique a integridade do dicionário e da tabela."
		#define STR0141 "Ocorreu um erro desconhecido durante a atualização da estrutura da tabela : "
		#define STR0142 "Desmarcar usando máscara ( ?? )"
		#define STR0143 "&Desmarcar"
		#define STR0144 "&Marcar"
		#define STR0145 "Inverter Seleção"
		#define STR0146 "&Inverter"
		#define STR0147 "Tela para Múltiplas Seleções de Empresas/Filiais"
		#define STR0148 "Selecione a(s) Empresa(s) para Atualização"
		#define STR0149 "Entrega"
		#define STR0150 "1=Retira Posterior;2=Retira;3=Entrega"
		#define STR0151 "Filial do Sistema"
		#define STR0152 "Cep de"
		#define STR0153 "Cep ate"
		#define STR0154 "Filial Estoq"
		#define STR0155 "Filial de reserva de estq"
		#define STR0156 "Local Estoq"
		#define STR0157 "Local de reserva de Estoq"
		#define STR0158 "Dias Reserva"
		#define STR0159 "Dias de reserva de Estoq"
		#define STR0160 "Range de CEP"
		#define STR0161 "Foi criada   chave unica da tabela "
		#define STR0162 "Foi alterada chave unica da tabela "
		#define STR0163 "Foi incluída a tabela "
		#define STR0164 "Atualizando Arquivos (SX2)..."
		#define STR0165 "Cep de+Cep ate"
		#define STR0166 "Dicionário de índices - "
		#define STR0167 "Dicionário de arquivos - "
		#define STR0168 "Filial VFE"
		#define STR0169 "Inicio da Atualizacao"
		#define STR0170 "Helps de Campos"
		#define STR0171 "Atualizando Helps de Campos ..."
		#define STR0172 "Indica se e uma operacao de Venda Fora do Estado."
		#define STR0173 "Atualizado o Help do campo "
		#define STR0174 "Filial onde sera gerado o pedido de vendas para entrega."
		#define STR0175 "Filial do sistema"
		#define STR0176 "CEP Inicial do range de CEPs"
		#define STR0177 "CEP Final do range de CEPs"
		#define STR0178 "Filial de reserva de estoque"
		#define STR0179 "Local de estoque (Armazem)"
		#define STR0180 "Indica os dias de reserva"
		#define STR0181 "Filial de entrega ao realizar uma operacao de VFE"
		#define STR0182 "Prazo para Entrega"
		#define STR0183 "Prazo Entreg"
		#define STR0184 "Final da Atualizacao"
	#endif
#endif
