#ifdef SPANISH
	#define STR0001 "Update UPDPCP16"
	#define STR0002 "Integracion con APS Totvs"
	#define STR0003 "Seguimiento del ajuste de cada tabla:"
	#define STR0004 "Atencion: para que pueda efectuarse el ajuste, ¡NINGUN usuario puede estar utilizando el sistema!"
	#define STR0005 "Esta rutina tiene por objetivo preparar los entornos seleccionados para actualizacion, para que se encuentren aptos para procesar todas las funcionalidades de la integracion con la aplicacion APS Totvs."
	#define STR0006 "Antes de iniciar la actualizacion, debe leer y aceptar los siguientes terminos y condiciones. Despues de aceptarlos, puede proseguir con la actualizacion."
	#define STR0007 "AVISO:"
	#define STR0008 "Este compatibilizador procesara actualizaciones en los diccionarios de datos de la(s) empresa(s) seleccionada(s) creando de esta manera una nueva tabla con sus respectivos indices y campos."
	#define STR0009 "IMPORTANTE: El funcionamiento de la integracion dependerá, ademas del procesamiento de este update, de configuracion del parametro MV_APS. Mas detalles disponibles en el boletin que acompana este update."
	#define STR0010 "OBSERVACION: La actualizacion se procesara para no impactar en las funcionalidades existentes en el sistema."
	#define STR0011 "Libre"
	#define STR0012 "¡SIGAMAT.EMP con problemas!"
	#define STR0013 "SIGAPCP - Update"
	#define STR0014 "Anular"
	#define STR0015 "&Avanzar >>"
	#define STR0016 "¡Bienvenido!"
	#define STR0017 "¡Lea con atencion!"
	#define STR0018 "Lei y estou enterado."
	#define STR0019 "Codigo"
	#define STR0020 "Empresa"
	#define STR0021 "Procesamiento total del ajuste:"
	#define STR0022 "Actualizaciones realizadas:"
	#define STR0023 "Ejecucion del ajuste"
	#define STR0024 "Procesamiento parcial del ajuste:"
	#define STR0025 "¡Ajuste finalizado!"
	#define STR0026 "¡Ajuste de tablas finalizado!"
	#define STR0027 "Seleccione la empresa"
	#define STR0028 "Grabar Log"
	#define STR0029 "&Finalizar"
	#define STR0030 "¡SIGAMAT.EMP en uso!"
	#define STR0031 "Ejecutando compatibilizador para la empresa: "
	#define STR0032 "Inicializando entorno para la empresa "
	#define STR0033 "Espere..."
	#define STR0034 "Filtrando registros para procesamiento..."
	#define STR0035 ">> Ajuste iniciado el "
	#define STR0036 ", a las "
	#define STR0037 "LOG del update "
	#define STR0038 "Empresa: "
	#define STR0039 "Resultado final de la ejecucion del UPD:"
	#define STR0040 "Actualizando el archivo "
	#define STR0041 " / Sucursal: "
	#define STR0042 "*Ajuste realizado en las tablas de la empresa "
	#define STR0043 "Finalizando entorno para la empresa "
	#define STR0044 "Archivos de Log (*.LOG) |*.log|"
	#define STR0045 "Este LOG se salvo automaticamente como "
	#define STR0046 "en el directorio de los SX."
	#define STR0047 "La extension '.LOG' se agrego al archivo que se grabo del directorio seleccionado ("
	#define STR0048 "Procesando pedido de venta numero "
	#define STR0049 "Inicializando el compatibilizador "
	#define STR0050 "Actualizando estructura de la base de datos"
	#define STR0051 "Actualizada la estructura fisica de los archivos: "
	#define STR0052 "Actualizando estructura fisica del archivo "
	#define STR0053 "Falla al actualizar la estructura fisica del archivo "
	#define STR0054 "Se crearon nuevas tablas: "
	#define STR0055 "Se crearon novos campos para las tablas: "
	#define STR0056 "Se crearon nuevos indices: "
#else
	#ifdef ENGLISH
		#define STR0001 "Update UPDPCP16"
		#define STR0002 "Integration with APS TOTVS"
		#define STR0003 "Progress of each table adjustment:"
		#define STR0004 "Attention: To make the adjustment, NO user can use the system!"
		#define STR0005 "This routine prepares the environments selected for update to enable them to process all functionalities of the integration with APS TOTVS application."
		#define STR0006 "Before starting the update, you must read and accept the following terms and conditions. Once you accept them, you can proceed with the update."
		#define STR0007 "NOTE:"
		#define STR0008 "This compatibility program processes updates in data dictionaries of companies selected, thus creating a new table with respective indexes and fields."
		#define STR0009 "IMPORTANT: Integration depends on the configuration of the parameter MV_APS besides the processing of this update. Further details are available in the newsletter that comes with this update."
		#define STR0010 "NOTE: Update is processed in order not to impact functionalities that already exist in the system."
		#define STR0011 "Free"
		#define STR0012 "SIGAMAT.EMP with problems!"
		#define STR0013 "SIGAPCP - Update"
		#define STR0014 "&Cancel"
		#define STR0015 "&Next >>"
		#define STR0016 "Welcome!"
		#define STR0017 "Read carefully!"
		#define STR0018 "I have read it and I am aware of it."
		#define STR0019 "Code"
		#define STR0020 "Company "
		#define STR0021 "Adjustment total processing:"
		#define STR0022 "Updates performed:"
		#define STR0023 "Adjustment execution"
		#define STR0024 "Adjustment partial processing:"
		#define STR0025 "Adjustment completed!"
		#define STR0026 "Table adjustment completed!"
		#define STR0027 "Select the company"
		#define STR0028 "&Save Log"
		#define STR0029 "&Finish"
		#define STR0030 "SIGAMAT.EMP in use!"
		#define STR0031 "Running compatibility program for the company: "
		#define STR0032 "Starting environment for the company "
		#define STR0033 "Wait..."
		#define STR0034 "Filtering records for processing..."
		#define STR0035 ">> Adjustment started on "
		#define STR0036 ", "
		#define STR0037 "LOG of update "
		#define STR0038 "Company: "
		#define STR0039 "Final result of UPD execution:"
		#define STR0040 "Updating file "
		#define STR0041 " / Branch: "
		#define STR0042 "*Adjustment made in company tables "
		#define STR0043 "Closing environment for the company "
		#define STR0044 "Log files (*.LOG) |*.log|"
		#define STR0045 "This LOG was automatically saved as "
		#define STR0046 " in SX directory."
		#define STR0047 "The extension '.LOG' was added to the file, which was saved from the directory chosen ("
		#define STR0048 "Processing sales order number "
		#define STR0049 "Starting compatibility program "
		#define STR0050 "Updating database structure"
		#define STR0051 "File physical structure updated: "
		#define STR0052 "Updating file physical structure "
		#define STR0053 "Failure to update file physical structure "
		#define STR0054 "New tables created: "
		#define STR0055 "New fields created for tables: "
		#define STR0056 "New indexes created: "
	#else
		#define STR0001 "Update UPDPCP16"
		#define STR0002 "Integração com APS Totvs"
		#define STR0003 "Andamento do ajuste de cada tabela:"
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Atenção: Para que o ajuste possa ser efetuado NENHUM utilizador pode estar a utilizar o sistema!", "Atenção: para que o ajuste possa ser efetuado NENHUM usuário pode estar utilizando o sistema!" )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Esta rotina tem como objetivo preparar os ambientes seleccionados para atualização para que estes estejam aptos a processarem todas as funcionalidades da integração com o aplicativo APS Totvs.", "Esta rotina tem como objetivo preparar os ambientes selecionados para atualização para que estes estejam aptos a processarem todas as funcionalidades da integração com o aplicativo APS Totvs." )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Antes de iniciar a actualização, você deve ler e aceitar os termos e as condições a seguir. Após aceitá-los, você pode prosseguir com a actualização.", "Antes de iniciar a atualização, você deve ler e aceitar os termos e as condições a seguir. Após aceitá-los, você pode prosseguir com a atualização." )
		#define STR0007 "AVISO:"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Este compatibilizador irá processar as actualizações nos dicionários de dados da(s) empresa(s) seleccionada(s) criando assim uma nova tabela com seus respectivos índices e campos.", "Este compatibilizador irá processar atualizações nos dicionários de dados da(s) empresa(s) selecionada(s) criando assim uma nova tabela com seus respectivos índices e campos." )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "IMPORTANTE: O funcionamento da integração dependerá, além do processamento deste update, da configuração do parâmetro MV_APS. Mais detalhes disponíveis no boletim que acompanha este update.", "IMPORTANTE: O funcionamento da integração dependerá, além do processamento deste update, da configuração do parâmetro MV_APS. Maiores detalhes disponíveis no boletim que acompanha este update." )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "OBSERVAÇÃO: A actualização será processada de forma a não impactar nas funcionalidades já existentes no sistema.", "OBSERVAÇÃO: A atualização será processada de forma a não impactar nas funcionalidades já existentes no sistema." )
		#define STR0011 "Livre"
		#define STR0012 "SIGAMAT.EMP com problemas!"
		#define STR0013 "SIGAPCP - Update"
		#define STR0014 "&Cancelar"
		#define STR0015 "&Avançar >>"
		#define STR0016 "Bem-Vindo!"
		#define STR0017 "Leia com atenção!"
		#define STR0018 "Li e estou ciente."
		#define STR0019 "Código"
		#define STR0020 "Empresa"
		#define STR0021 "Processamento total do ajuste:"
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Actualizações realizadas:", "Atualizações realizadas:" )
		#define STR0023 "Execução do ajuste"
		#define STR0024 "Processamento parcial do ajuste:"
		#define STR0025 "Ajuste finalizado!"
		#define STR0026 "Ajuste das tabelas finalizado!"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Seleccione a empresa", "Selecione a empresa" )
		#define STR0028 "&Salvar Log"
		#define STR0029 "&Finalizar"
		#define STR0030 "SIGAMAT.EMP em uso!"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "A executar compatibilizador para a empresa: ", "Executando compatibilizador para a empresa: " )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "A inicializar o ambiente para a empresa ", "Inicializando ambiente para a empresa " )
		#define STR0033 "Aguarde..."
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "A filtrar os registos para processamento...", "Filtrando registros para processamento..." )
		#define STR0035 ">> Ajuste iniciado em "
		#define STR0036 ", as "
		#define STR0037 "LOG do update "
		#define STR0038 "Empresa: "
		#define STR0039 "Resultado final da execução do UPD:"
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "A actualizar o registo ", "Atualizando o arquivo " )
		#define STR0041 " / Filial: "
		#define STR0042 "*Ajuste feito nas tabelas da empresa "
		#define STR0043 If( cPaisLoc $ "ANG|PTG", "A encerrar o ambiente para a empresa ", "Encerrando ambiente para a empresa " )
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Registos de Log (*.LOG) |*.log|", "Arquivos de Log (*.LOG) |*.log|" )
		#define STR0045 "Este LOG foi salvo automaticamente como "
		#define STR0046 If( cPaisLoc $ "ANG|PTG", " no diretório dos SXs.", " no diretorio dos SXs." )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "A extenção '.LOG' foi adicionada ao registo que foi salvo do diretório escolhido (", "A extencao '.LOG' foi adicionada ao arquivo, que foi salvo do diretorio escolhido (" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "A processar o pedido de venda número ", "Processando pedido de venda número " )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "A inicializar o compatibilizador ", "Inicializando o compatibilizador " )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "A actualizar a estrutura do banco de dados", "Atualizando estrutura do banco de dados" )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Actualizada a estrutura física dos registos: ", "Atualizada a estrutura física dos arquivos: " )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "A actualizar a estrutura física do registo ", "Atualizando estrutura física do arquivo " )
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "Falha ao actualizar a estrutura física do registo ", "Falha ao atualizar a estrutura física do arquivo " )
		#define STR0054 "Criadas novas tabelas: "
		#define STR0055 "Criados novos campos para as tabelas: "
		#define STR0056 "Criados novos índices: "
	#endif
#endif
