#ifdef SPANISH
	#define STR0001 "ACTUALIZACION DE DICCIONARIOS Y TABLAS"
	#define STR0002 "La funcion de esta rutina es actualizar los diccionarios del sistema ( SX?/SIX )"
	#define STR0003 "Este proceso se debe ejecutar en modo EXCLUSIVO, es decir, no deben haber otros"
	#define STR0004 "usuarios o jobs utilizando el sistema.  Es extremamente recomendable que se haga una"
	#define STR0005 "COPIA DE SEGURIDAD de los DICCIONARIOS  y de la  BASE DE DATOS antes de esta actualizacion, porque si "
	#define STR0006 "ocurren eventuales fallas, esta copia de seguridad podra restaurarse."
	#define STR0007 "*OFF"
	#define STR0008 "¿Confirma la actualizacion de los diccionarios?"
	#define STR0009 "Espere, actualizando..."
	#define STR0010 "Actualizando"
	#define STR0011 "Actualizacion realizada."
	#define STR0012 "UPDMILE"
	#define STR0013 "Actualizacion no realizada."
	#define STR0014 "UPDMILE"
	#define STR0015 "Actualizacion concluida."
	#define STR0016 "Actualizacion no realizada."
	#define STR0017 "Actualizacion no realizada."
	#define STR0018 "UPDMILE"
	#define STR0019 "Actualizacion no realizada."
	#define STR0020 "UPDMILE"
	#define STR0021 "Archivos texto"
	#define STR0022 "TCGetBuild"
	#define STR0023 " no efectuada."
	#define STR0024 "Actualizacion de la empresa "
	#define STR0025 "Empresa: "
	#define STR0026 " - "
	#define STR0027 " ..."
	#define STR0028 "Diccionario de parametros"
	#define STR0029 "LOG DE ACTUALIZACION DE LOS DICCIONARIOS"
	#define STR0030 " Datos entorno"
	#define STR0031 " --------------------"
	#define STR0032 " Empresa/Sucursal...: "
	#define STR0033 " Nombre empresa...: "
	#define STR0034 " Nombre sucursal...: "
	#define STR0035 " Fecha base...........: "
	#define STR0036 " / "
	#define STR0037 " Fecha / Hora Inicio: "
	#define STR0038 " Environment........: "
	#define STR0039 " StartPath..........: "
	#define STR0040 "StartPath"
	#define STR0041 " RootPath...........: "
	#define STR0042 "RootPath"
	#define STR0043 " Version.............: "
	#define STR0044 " Usuario TOTVS .....: "
	#define STR0045 " Computer Name......: "
	#define STR0046 " Datos Thread"
	#define STR0047 " --------------------"
	#define STR0048 " Usuario de la red....: "
	#define STR0049 " Estacion............: "
	#define STR0050 " Programa inicial...: "
	#define STR0051 " Environment........: "
	#define STR0052 " Conexion............: "
	#define STR0053 " / "
	#define STR0054 " Fecha/Hora final.: "
	#define STR0055 "Mono AS"
	#define STR0056 "Actualizacion concluida."
	#define STR0057 "Inicio de la actualizacion"
	#define STR0058 " Contenido ["
	#define STR0059 "Se incluyo el parametro "
	#define STR0060 "Actualizando archivos (SX6)..."
	#define STR0061 "Final de la actualizacion"
	#define STR0062 "LBOK"
	#define STR0063 "LBNO"
	#define STR0064 "??"
	#define STR0065 "??"
	#define STR0066 "Pantalla para multiple seleccion de Empresas/Sucursales"
	#define STR0067 "Seleccione la(s) empresa(s) para actualizacion"
	#define STR0068 "Empresa"
	#define STR0069 "Todos"
	#define STR0070 "&Invertir"
	#define STR0071 "Invertir seleccion"
	#define STR0072 "Empresa"
	#define STR0073 "?"
	#define STR0074 "?"
	#define STR0075 "Máscara empresa ( ? )"
	#define STR0076 "&Marcar"
	#define STR0077 "Marcar usando máscara ( ? )"
	#define STR0078 "&Desmarcar"
	#define STR0079 "Desmarcar usando mascara ( ? )"
	#define STR0080 "Confirma la seleccion"
	#define STR0081 "Abandona la seleccion"
	#define STR0082 "No fue posible abrir la tabla "
	#define STR0083 "ATENCION"
	#define STR0084 "de empresas (SM0) de forma exclusiva."
	#define STR0085 "de empresas (SM0)."
#else
	#ifdef ENGLISH
		#define STR0001 "TABLE AND DICTIONARY UPDATE"
		#define STR0002 "Does this routine update system dictionaries ( SX?/SIX )"
		#define STR0003 "This process must be run in EXCLUSIVE mode, that is, other"
		#define STR0004 "users or jobs using the system.  You must make"
		#define STR0005 "BACKUP of DICTIONARIES and DATABASE before this update "
		#define STR0006 "in order to restore this backup in case of failures."
		#define STR0007 "*OFF"
		#define STR0008 "Confirm dictionary update?"
		#define STR0009 "Wait, updating ..."
		#define STR0010 "Updating"
		#define STR0011 "Update Completed."
		#define STR0012 "UPDMILE"
		#define STR0013 "Update not Performed."
		#define STR0014 "UPDMILE"
		#define STR0015 "Update Completed."
		#define STR0016 "Update not Performed."
		#define STR0017 "Update not Performed."
		#define STR0018 "UPDMILE"
		#define STR0019 "Update not Performed."
		#define STR0020 "UPDMILE"
		#define STR0021 "Text Files"
		#define STR0022 "TCGetBuild"
		#define STR0023 " not made."
		#define STR0024 "Company Update "
		#define STR0025 "Company: "
		#define STR0026 " - "
		#define STR0027 " ..."
		#define STR0028 "Dictionary of parameters"
		#define STR0029 "DICTIONARY UPDATE LOG"
		#define STR0030 " Environment Data"
		#define STR0031 " --------------------"
		#define STR0032 " Company/Branch...: "
		#define STR0033 " Company Name.......: "
		#define STR0034 " Branch Name........: "
		#define STR0035 " Database...........: "
		#define STR0036 " / "
		#define STR0037 " Start Date/Time: "
		#define STR0038 " Environment........: "
		#define STR0039 " StartPath..........: "
		#define STR0040 "StartPath"
		#define STR0041 " RootPath...........: "
		#define STR0042 "RootPath"
		#define STR0043 " Version.............: "
		#define STR0044 " TOTVS User .....: "
		#define STR0045 " Computer Name......: "
		#define STR0046 " Thread Data"
		#define STR0047 " --------------------"
		#define STR0048 " Network User....: "
		#define STR0049 " Station............: "
		#define STR0050 " Initial Program...: "
		#define STR0051 " Environment........: "
		#define STR0052 " Connection............: "
		#define STR0053 " / "
		#define STR0054 " End Date/Time: "
		#define STR0055 "Mono AS"
		#define STR0056 "Update completed."
		#define STR0057 "Start of Update"
		#define STR0058 " Content ["
		#define STR0059 "Parameter was added "
		#define STR0060 "Updating Files (SX6)..."
		#define STR0061 "End of Update"
		#define STR0062 "LBOK"
		#define STR0063 "LBNO"
		#define STR0064 "??"
		#define STR0065 "??"
		#define STR0066 "Screen for Multiple Selections of Companies/Branches"
		#define STR0067 "Select Companies for Update"
		#define STR0068 "Company"
		#define STR0069 "All"
		#define STR0070 "&Invert"
		#define STR0071 "Invert Selection"
		#define STR0072 "Company"
		#define STR0073 "?"
		#define STR0074 "?"
		#define STR0075 "Company Mask (?? )"
		#define STR0076 "&Select"
		#define STR0077 "Select by using mask (?? )"
		#define STR0078 "&Clear"
		#define STR0079 "Clear by using mask (?? )"
		#define STR0080 "Confirm selection"
		#define STR0081 "Quit selection"
		#define STR0082 "Table could not be opened "
		#define STR0083 "ATTENTION"
		#define STR0084 "of companies (SM0) exclusively."
		#define STR0085 "of companies (SM0)."
	#else
		#define STR0001 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
		#define STR0002 "Esta rotina tem como função fazer  a atualização  dos dicionários do Sistema ( SX?/SIX )"
		#define STR0003 "Este processo deve ser executado em modo EXCLUSIVO, ou seja não podem haver outros"
		#define STR0004 "usuários  ou  jobs utilizando  o sistema.  É extremamente recomendavél  que  se  faça um"
		#define STR0005 "BACKUP  dos DICIONÁRIOS  e da  BASE DE DADOS antes desta atualização, para que caso "
		#define STR0006 "ocorra eventuais falhas, esse backup seja ser restaurado."
		#define STR0007 "*OFF"
		#define STR0008 "Confirma a atualização dos dicionários ?"
		#define STR0009 "Aguarde, atualizando ..."
		#define STR0010 "Atualizando"
		#define STR0011 "Atualização Realizada."
		#define STR0012 "UPDMILE"
		#define STR0013 "Atualização não Realizada."
		#define STR0014 "UPDMILE"
		#define STR0015 "Atualização Concluída."
		#define STR0016 "Atualização não Realizada."
		#define STR0017 "Atualização não Realizada."
		#define STR0018 "UPDMILE"
		#define STR0019 "Atualização não Realizada."
		#define STR0020 "UPDMILE"
		#define STR0021 "Arquivos Texto"
		#define STR0022 "TCGetBuild"
		#define STR0023 " não efetuada."
		#define STR0024 "Atualização da empresa "
		#define STR0025 "Empresa : "
		#define STR0026 " - "
		#define STR0027 " ..."
		#define STR0028 "Dicionário de parâmetros"
		#define STR0029 "LOG DA ATUALIZACAO DOS DICIONÁRIOS"
		#define STR0030 " Dados Ambiente"
		#define STR0031 " --------------------"
		#define STR0032 " Empresa / Filial...: "
		#define STR0033 " Nome Empresa.......: "
		#define STR0034 " Nome Filial........: "
		#define STR0035 " DataBase...........: "
		#define STR0036 " / "
		#define STR0037 " Data / Hora Inicio.: "
		#define STR0038 " Environment........: "
		#define STR0039 " StartPath..........: "
		#define STR0040 "StartPath"
		#define STR0041 " RootPath...........: "
		#define STR0042 "RootPath"
		#define STR0043 " Versao.............: "
		#define STR0044 " Usuario TOTVS .....: "
		#define STR0045 " Computer Name......: "
		#define STR0046 " Dados Thread"
		#define STR0047 " --------------------"
		#define STR0048 " Usuario da Rede....: "
		#define STR0049 " Estacao............: "
		#define STR0050 " Programa Inicial...: "
		#define STR0051 " Environment........: "
		#define STR0052 " Conexao............: "
		#define STR0053 " / "
		#define STR0054 " Data / Hora Final.: "
		#define STR0055 "Mono AS"
		#define STR0056 "Atualizacao concluida."
		#define STR0057 "Inicio da Atualizacao"
		#define STR0058 " Conteúdo ["
		#define STR0059 "Foi incluído o parâmetro "
		#define STR0060 "Atualizando Arquivos (SX6)..."
		#define STR0061 "Final da Atualizacao"
		#define STR0062 "LBOK"
		#define STR0063 "LBNO"
		#define STR0064 "??"
		#define STR0065 "??"
		#define STR0066 "Tela para Múltiplas Seleções de Empresas/Filiais"
		#define STR0067 "Selecione a(s) Empresa(s) para Atualização"
		#define STR0068 "Empresa"
		#define STR0069 "Todos"
		#define STR0070 "&Inverter"
		#define STR0071 "Inverter Seleção"
		#define STR0072 "Empresa"
		#define STR0073 "?"
		#define STR0074 "?"
		#define STR0075 "Máscara Empresa ( ?? )"
		#define STR0076 "&Marcar"
		#define STR0077 "Marcar usando máscara ( ?? )"
		#define STR0078 "&Desmarcar"
		#define STR0079 "Desmarcar usando máscara ( ?? )"
		#define STR0080 "Confirma a Seleção"
		#define STR0081 "Abandona a Seleção"
		#define STR0082 "Não foi possível a abertura da tabela "
		#define STR0083 "ATENÇÃO"
		#define STR0084 "de empresas (SM0) de forma exclusiva."
		#define STR0085 "de empresas (SM0)."
	#endif
#endif
