#ifdef SPANISH
	#define STR0001 "Mantenimiento de Sustituciones"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Imprimir"
	#define STR0007 "¡No se permitira modificar pues el periodo ya se encuentra cerrado!"
	#define STR0008 "¡No se permitira modificacion pues ya hubo integracion con Valores Futuros! ¡Borre y realice nuevamente el asiento!"
	#define STR0009 "¡No se permitira borrar pues ya hubo integracion con Valores Futuros y el periodo ya se encuentra cerrado!"
	#define STR0010 "Mantenimiento de Sustituciones"
	#define STR0011 "¡Los datos de la Sustitucion"
	#define STR0012 " ya se encuentran cerrados!"
	#define STR0013 "El periodo para pago informado "
	#define STR0014 "INFO"
	#define STR0015 "¡El valor a pagar se grabo con exito en Valores Futuros!"
	#define STR0016 "Valores Futuros"
	#define STR0017 "Categoría del SUSTITUTO debe ser 0-Miembro o 1-Miembro en comisión, si la opción del hecho generador fuera 3 - Ejercicio acumulativo."
	#define STR0018 " - Categoria: "
	#define STR0019 "¡Atención!"
	#define STR0020 "Error"
	#define STR0021 "¡Ejecute los procedimientos del mensaje anterior! "
	#define STR0022 "¡La fecha FINAL debe ser superior o igual a la fecha INICIAL!"
	#define STR0023 "¡Origen Automatico! ¡No se permite el mantenimiento!"
	#define STR0024 "¡El sustituto informado es el mismo sustituido!"
	#define STR0025 "¡El registro que estaba en valores futuros tambien se excluyo!"
	#define STR0026 "Modifique la matrícula del sustituto O del sustituido."
	#define STR0027 "Modifique la fecha Inicial o la fecha final de la sustitución."
	#define STR0028 "Modifique la opción del hecho generador o modifique la matrícula del sustituto para un Miembro - categoría 0 o 1."
	#define STR0029 "Verifique el período seleccionado."
	#define STR0030 "Sucursal/Matrícula:"
#else
	#ifdef ENGLISH
		#define STR0001 "Maintenance of Replacements"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Edit"
		#define STR0005 "Delete"
		#define STR0006 "Print"
		#define STR0007 "It is not allowed to edit because the period is already closed!"
		#define STR0008 "It is not allowed to edit because there is already integration with future values! Delete and redo the transaction"
		#define STR0009 "It is not allowed to delete because there was already integration with future values and period is already closed!"
		#define STR0010 "Maintenance of Replacements"
		#define STR0011 "Replacement Data"
		#define STR0012 " is already closed!"
		#define STR0013 "The period for payment entered "
		#define STR0014 "Info"
		#define STR0015 "Value to pay was recorded successfully on future values!"
		#define STR0016 "Future Values"
		#define STR0017 "SUBSTITUTE category must be 0 - Member of 1 - Member at will, when option of generator factor is 3 - Cumulative Job!"
		#define STR0018 " - Category: "
		#define STR0019 "Attention!"
		#define STR0020 "Error"
		#define STR0021 "Run procedures of previous message. "
		#define STR0022 "Substitution END date must be later than or equal to START date!"
		#define STR0023 "Automatic Origin! Maintenance is not allowed!"
		#define STR0024 "The indicated substitute is the one that was substituted!"
		#define STR0025 "The record that was in Future Values was also deleted!"
		#define STR0026 "Edit registration of substitute or of the substituted."
		#define STR0027 "Edit start or end date of substitution."
		#define STR0028 "Edit Generator Factor option OR edit registration of substitute for a Member - category 0 or 1."
		#define STR0029 "Check selected period."
		#define STR0030 "Branch/Registration:"
	#else
		#define STR0001 "Manutenção de Substituições"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Imprimir"
		#define STR0007 "Não será permitido alterar pois o período já se encontra fechado!"
		#define STR0008 "Não será permitido alteração pois já houve integração com Valores Futuros! Exclua e refaça o lançamento!"
		#define STR0009 "Não será permitido excluir pois já houve integração com Valores Futuros e o período já se encontra fechado!"
		#define STR0010 "Manutenção de Substituições"
		#define STR0011 "Dados da Substituição"
		#define STR0012 " já se encontra fechado!"
		#define STR0013 "O período para pagamento informado "
		#define STR0014 "INFO"
		#define STR0015 "O valor a ser pago foi gravado com sucesso em Valores Futuros!"
		#define STR0016 "Valores Futuros"
		#define STR0017 "Categoria do SUBSTITUTO dever ser 0-Membro ou 1-Membro em Comissão, quando a opção do fato gerador for 3 - Exercício Cumulativo!"
		#define STR0018 " - Categoria: "
		#define STR0019 "Atenção!"
		#define STR0020 "Erro"
		#define STR0021 "Execute os procedimentos da mensagem anterior! "
		#define STR0022 "A data FINAL da Substituição deve ser maior ou igual a data INICIAL!"
		#define STR0023 "Origem Automática! Não é permitida manutenção!"
		#define STR0024 "O substituto informado é o próprio substituído!"
		#define STR0025 "O registro que estava em Valores Futuros também foi excluído!"
		#define STR0026 "Altere a matrícula do substituto OU do substituído."
		#define STR0027 "Altere a data Inicial ou data Final da Substituição."
		#define STR0028 "Altere a opção do Fato Gerador OU altere a matricula do substituto para um Membro - categoria 0 ou 1."
		#define STR0029 "Verifique o período Selecionado."
		#define STR0030 "Filial/Matrícula: "
	#endif
#endif
