#ifdef SPANISH
	#define STR0001 "Mantenimiento de los Candidatos"
	#define STR0002 "Visualizar"
	#define STR0003 "Mantenimiento"
	#define STR0004 "Modelo de Curriculos"
	#define STR0005 "Datos del Curriculo"
	#define STR0006 "Requisitos de los Concursos del Curriculo"
	#define STR0007 "Funciones del Curriculo"
	#define STR0008 "Requisitos del Curriculo / Funcion"
	#define STR0009 "Reclasificar"
	#define STR0010 "Incl.Plan.Pago."
	#define STR0011 "Borra Item Designacion"
	#define STR0012 "Confirma el borrado del item de designacion  ? La fecha de designacion y pose tambien se borraran."
	#define STR0013 "No se encontro item para ser borrado."
	#define STR0014 "Confirma la Reclasificacion para "
	#define STR0015 "Reclasificacion disponible solo para Pasante"
	#define STR0016 "Reclasificacion disponible solo para Modificacion"
	#define STR0017 'Datos de los Concursos del Curriculo'
	#define STR0018 "Disponible"
	#define STR0019 "Admitido"
	#define STR0020 "Servidor"
	#define STR0021 "Utilizar la opcion Reclasifica en 'Acciones Relacionadas'"
	#define STR0022 "Hubo la publicación del ítem, por lo tanto, este no podrá borrarse."
	#define STR0023 "Borrado con exito."
	#define STR0024 "Desistencia"
	#define STR0025 "Ya existe fecha de nombramiento/pose/ejercicio. No puede incluirse la desistencia."
	#define STR0026 "La situación actual no permite la desistencia."
	#define STR0027 "Fecha de la desistencia"
	#define STR0028 "Fecha inválida."
	#define STR0029 'Desistencia disponible únicamente para pasante'
	#define STR0030 'Desistencia disponible únicamente para modificación'
	#define STR0031 "Utilizar el botón desistencia en 'Acciones relacionadas'"
	#define STR0032 "Concurso vinculado al candidato en la línea"
	#define STR0033 "Concurso:"
	#define STR0034 "Sucursal de la función:"
	#define STR0035 "Función:"
	#define STR0036 "Seleccione otro concurso."
	#define STR0037 "Función no está registrada para el concurso y sucursal informada."
	#define STR0038 "La función seleccionada no tiene requisitos registrados."
	#define STR0039 "La sucursal informada no está registrada en el concurso informado:"
	#define STR0040 "Usuario sin acceso a la sucursal seleccionada. Por favor, seleccione otra sucursal."
	#define STR0041 "¡Atención!"
	#define STR0042 "Publicación"
	#define STR0043 "Verifique el registro en la rutina de Generación Doc de Actos/Resoluciones (VDFM020)."
#else
	#ifdef ENGLISH
		#define STR0001 "Candidate Maintenance"
		#define STR0002 "View"
		#define STR0003 "Maintenance"
		#define STR0004 "Résumé Model"
		#define STR0005 "Résumé Data"
		#define STR0006 "Résumé Contest Requirements"
		#define STR0007 "Résumé Functions"
		#define STR0008 "Résumé/Function Requirements"
		#define STR0009 "Reclassify"
		#define STR0010 "Add Payroll "
		#define STR0011 "Deletes item nomination"
		#define STR0012 "Confirm the deletion of nomination item? The date of nomination and tenure can also be deleted."
		#define STR0013 "No item was found to delete."
		#define STR0014 "Confirm reclassification to "
		#define STR0015 "Reclassification available only to trainee"
		#define STR0016 "Reclassification available only for modification"
		#define STR0017 'Résumé Contest Data'
		#define STR0018 "Available"
		#define STR0019 "Admitted"
		#define STR0020 "Server"
		#define STR0021 "Use reclassify button in Related Actions"
		#define STR0022 "Item already published. Unable to delete it."
		#define STR0023 "Successfully deleted."
		#define STR0024 "Abandonment"
		#define STR0025 "There already is nomination/tenure/fiscal year. Unable to add abandonment."
		#define STR0026 "Current status does not enable waiver."
		#define STR0027 "Abandonment Date"
		#define STR0028 "Invalid Date."
		#define STR0029 'Abandonment available only for Intern'
		#define STR0030 'Abandonment available only for Edition'
		#define STR0031 "Use Abandonment Button in Related Features"
		#define STR0032 "Contest already linked to the applicant in the line "
		#define STR0033 "Contest: "
		#define STR0034 "Branch of the Function: "
		#define STR0035 "Function: "
		#define STR0036 "Choose other Contest."
		#define STR0037 "Function is not registered of the contest and branch informed. "
		#define STR0038 "The Function chosen does not have Requests Registered."
		#define STR0039 "The branch informed is not registered in the Contest informed: "
		#define STR0040 "User without access to branch chosen. Please choose other branch."
		#define STR0041 "Warning!"
		#define STR0042 "Publication"
		#define STR0043 "Check the record in routine Decrees/Ordinances Doc Generation (VDFM020)."
	#else
		#define STR0001 "Manutenção dos Candidatos"
		#define STR0002 "Visualizar"
		#define STR0003 "Manutenção"
		#define STR0004 "Modelo de Curriculos"
		#define STR0005 "Dados do Curriculo"
		#define STR0006 "Requisitos dos Concursos do Curriculo"
		#define STR0007 "Funções do Curriculo"
		#define STR0008 "Requisitos do Curriculo / Função"
		#define STR0009 "Reclassificar"
		#define STR0010 "Incl.Fol.Pagto."
		#define STR0011 "Exclui Item Nomeação"
		#define STR0012 "Confirma a exclusão do item de nomeação ? A data de nomeação e posse também serão excluídas."
		#define STR0013 "Não foi encontrado item para ser excluido."
		#define STR0014 "Confirma a Reclassificação para "
		#define STR0015 "Reclassificação disponivel apenas para Estagiário"
		#define STR0016 "Reclassificação disponivel apenas para Alteração"
		#define STR0017 'Dados dos Concursos do Curriculo'
		#define STR0018 "Disponível"
		#define STR0019 "Admitido"
		#define STR0020 "Servidor"
		#define STR0021 "Utilizar o Botão Reclassifica em 'Ações Relacionadas'"
		#define STR0022 "Já houve a publicação do Item, portanto ele não poderá ser excluído."
		#define STR0023 "Excluído com sucesso."
		#define STR0024 "Desistência"
		#define STR0025 "Já existe data de nomeação/posse/exercício. Não pode inserir a desistência."
		#define STR0026 "A situação atual não permite a desistência."
		#define STR0027 "Data da Desistência"
		#define STR0028 "Data inválida."
		#define STR0029 'Desistência disponível apenas para Estagiário'
		#define STR0030 'Desistência disponível apenas para Alteração'
		#define STR0031 "Utilizar o Botão Desistência em 'Ações Relacionadas'"
		#define STR0032 "Concurso já vinculado ao candidato na linha "
		#define STR0033 "Concurso: "
		#define STR0034 "Filial da Função: "
		#define STR0035 "Função: "
		#define STR0036 "Escolha outro Concurso."
		#define STR0037 "Função não está cadastrada para o concurso e filial informada. "
		#define STR0038 "A Função escolhida não possui Requisitos Cadastrados."
		#define STR0039 "A filial informada não está cadastrada no concurso informado: "
		#define STR0040 "Usuario sem acesso a filial escolhida. Favor escolher outra filial."
		#define STR0041 "Atenção!"
		#define STR0042 "Publicação"
		#define STR0043 "Verifique o registro na rotina de Geração Doc de Atos/Portarias (VDFM020)."
	#endif
#endif
