#ifdef SPANISH
	#define STR0001 "Oportunidad de negocios"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Incluir"
	#define STR0005 "Modificar"
	#define STR0006 "Busca cliente"
	#define STR0007 "Anular interes"
	#define STR0008 "Codigo"
	#define STR0009 "Tienda"
	#define STR0010 "Nombre"
	#define STR0011 "CNPJ/CPF"
	#define STR0012 "E-mail"
	#define STR0013 "Telefono"
	#define STR0014 "<<< FILTRAR >>>"
	#define STR0015 "Salir"
	#define STR0016 "OK"
	#define STR0017 "Campana"
	#define STR0018 "Fase"
	#define STR0019 "Vendedor"
	#define STR0020 "Tipo de contacto"
	#define STR0021 "Tipo de medio"
	#define STR0022 "Marca"
	#define STR0023 "Modelo"
	#define STR0024 "Color"
	#define STR0025 "Banco"
	#define STR0026 "Motivo anulacion"
	#define STR0027 "Filtro"
	#define STR0028 "No existen datos para esta busqueda."
	#define STR0029 "Atencion"
	#define STR0030 "¡Los datos del cliente (Codigo Cliente / Tienda) son necesarios para la proxima fase de la oportunidad!"
	#define STR0031 "¡Cliente informado no encontrado en el archivo de clientes!"
	#define STR0032 "Imposible Borrar el registro. ¡Interes ya relacionado en Atendimiento!"
	#define STR0033 "Fase financiacion"
	#define STR0034 "Agencia"
	#define STR0035 "Telefono"
	#define STR0036 "Linea de credito"
	#define STR0037 "Nombre banco"
	#define STR0038 "Nombre gerente"
	#define STR0039 "Ciudad"
	#define STR0040 "Opcionales"
	#define STR0041 "Visual.Atencion"
	#define STR0042 "Imposible modificar la Fase del interes. ¡La Fase digitada no es una Fase Final!"
	#define STR0043 "¡Imposible abrir atención y facturación directa al mismo tiempo!"
	#define STR0044 "¡Prospect informado no encontrado en el registro de prospects!"
	#define STR0045 "¡Es necesario seleccionar un Cliente o Prospect!"
	#define STR0046 "Prospect"
	#define STR0047 "Convertir Prospect en Cliente"
	#define STR0048 "¿Desea convertir el Prospect en Cliente?"
	#define STR0049 "¡Este Prospect ya se convirtió en Cliente!"
	#define STR0050 "Fase del interés no esta activa. ¡Imposible continuar!"
	#define STR0051 "Replicar"
	#define STR0052 "Cant. por replicar"
	#define STR0053 "Imposible modificar la Fase del interés. ¡Verifique la secuencia de las fases!"
	#define STR0054 "¡Usuario sin permiso!"
	#define STR0055 "Los siguientes intereses están vinculados a los ítems borrados en la atención"
	#define STR0056 "Sucursal"
	#define STR0057 "Atención"
	#define STR0058 "Ítem"
	#define STR0059 "Estatus"
	#define STR0060 "¿Desea limpiar los vínculos para utilizar los intereses en el futuro?"
	#define STR0061 "Limpiar filtros"
	#define STR0062 "No considerar campos en el filtro"
	#define STR0063 "Informe los campos de la tabla VDM que"
	#define STR0064 "no se considerarán en el filtro."
	#define STR0065 "¡No existen Intereses vinculados al código de vendedor del usuario conectado!"
	#define STR0066 "INTERESES SIN ETAPA INFORMADA"
	#define STR0067 "INTERESES EN LA(S) ETAPA(S):"
	#define STR0068 "INTERESES EN LA(S) ETAPA(S) INACTIVA(S):"
	#define STR0069 "INTERESES EN LA(S) ETAPA((S) SIN COLOR INFORMADO:"
	#define STR0070 "Oportunidades/Intereses"
	#define STR0071 "Anular"
	#define STR0072 "Seleccione todos los Intereses que se desea anular"
	#define STR0073 "No seleccionado"
	#define STR0074 "Seleccionado para anulación"
	#define STR0075 "Interés anulado"
	#define STR0076 "Interés con atención"
	#define STR0077 "Anulación"
	#define STR0078 "Imposible seleccionar este interés, pues ya tiene Atención vinculada."
	#define STR0079 "Imposible seleccionar este interés, pues ya está anulado."
	#define STR0080 "Por favor, seleccione uno o más intereses para la anulación."
	#define STR0081 "Embudo de intereses"
	#define STR0082 "INTERESES ACTIVOS ( DENTRO DE LA FECHA LÍMITE )"
	#define STR0083 "INTERESES NO ANULADOS"
	#define STR0084 "INTERESES ANULADOS"
	#define STR0085 "Fecha del interés"
	#define STR0086 "Motivo de la anulación"
	#define STR0087 "Etapa automática - Cambio de estatus de la atención"
	#define STR0088 "Esta etapa de interés es automática. ¡Imposible utilizar!"
	#define STR0089 "Banco de conocimiento"
	#define STR0090 "Imposible borrar el registro. ¡Interés anulado!"
	#define STR0091 "Etapa del interés no está vinculada a Vehículos/Máquinas. ¡Imposible continuar!"
	#define STR0092 "Etapa del interés debe ser de la 1ª Etapa del embudo. ¡Imposible continuar!"
	#define STR0093 "Etapa del interés debe ser la misma o la próxima etapa del embudo. ¡Imposible continuar!"
	#define STR0094 "Generar agenda CEV"
	#define STR0095 "Vincular agenda CEV"
	#define STR0096 "¡Código no válido!"
	#define STR0097 "Cliente"
	#define STR0098 "Prospect"
	#define STR0099 "Objetivo"
	#define STR0100 "Vincula con el interés:"
	#define STR0101 "NUEVO"
	#define STR0102 "No existen agendas del cliente para realizar la relación."
	#define STR0103 "Relación de agenda CEV"
#else
	#ifdef ENGLISH
		#define STR0001 "Business Opportunity"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Add"
		#define STR0005 "Edit"
		#define STR0006 "Search Customer"
		#define STR0007 "Cancel Interest"
		#define STR0008 "Code"
		#define STR0009 "Store"
		#define STR0010 "Name"
		#define STR0011 "SSN/EIN"
		#define STR0012 "E-mail"
		#define STR0013 "Telephone Number"
		#define STR0014 "<< FILTER >>"
		#define STR0015 "Exit"
		#define STR0016 "OK"
		#define STR0017 "Campaign"
		#define STR0018 "Phase"
		#define STR0019 "Sales Representative"
		#define STR0020 "Type of Contact"
		#define STR0021 "Media Type"
		#define STR0022 "Brand"
		#define STR0023 "Model"
		#define STR0024 "Color"
		#define STR0025 "Bank"
		#define STR0026 "Reason for Cancellation"
		#define STR0027 "Filter"
		#define STR0028 "There are no data for this search!"
		#define STR0029 "Attention"
		#define STR0030 "Customer data (Customer / Store Code) required for the next phase of the opportunity!"
		#define STR0031 "Entered Customer not found in Customer Register!"
		#define STR0032 "Excluding file is impossible. Interest is already related in Service!"
		#define STR0033 "Financing Phase"
		#define STR0034 "Branch"
		#define STR0035 "Phone"
		#define STR0036 "Credit Line"
		#define STR0037 "Bank Name"
		#define STR0038 "Manager Name"
		#define STR0039 "City"
		#define STR0040 "Optional"
		#define STR0041 "Visual Service"
		#define STR0042 "It is impossible to edit Interest Phase. Typed Phase is not a Final Phase!"
		#define STR0043 "Cannot simultaneously open Service and Direct Invoicing!"
		#define STR0044 "Entered Prospect not found on prospects register!"
		#define STR0045 "You must select a Customer or Prospect!"
		#define STR0046 "Prospect"
		#define STR0047 "Convert Prospect in Customer"
		#define STR0048 "Convert Prospect in Customer?"
		#define STR0049 "This Prospect was already converted to Customer!"
		#define STR0050 "Interest phase is not active. Cannot continue!"
		#define STR0051 "Replicate"
		#define STR0052 "Qty. to Reply"
		#define STR0053 "It is impossible to edit Interest Phase. Check Phases sequence."
		#define STR0054 "User not permission!"
		#define STR0055 "The interests below are related to items deleted in the Service"
		#define STR0056 "Branch"
		#define STR0057 "Service"
		#define STR0058 "Item"
		#define STR0059 "Status"
		#define STR0060 "Clean the relationships to use these interests in the future?"
		#define STR0061 "Clean Filter"
		#define STR0062 "Fields disregarded in the Filter"
		#define STR0063 "Enter Fields of VCM Table that"
		#define STR0064 "are disregarded in the Filter."
		#define STR0065 "No interests related to seller code of logged user"
		#define STR0066 "INTERESTS WITH NO STAGE ENTERED"
		#define STR0067 "INTERESTS IN STAGES:"
		#define STR0068 "INTERESTS IN INACTIVE STAGES:"
		#define STR0069 "INTERESTS IN STAGES WITHOUT COLOR:"
		#define STR0070 "Opportunities/Interests"
		#define STR0071 "Cancel"
		#define STR0072 "Select all the Interest you want to cancel"
		#define STR0073 "Not Selected"
		#define STR0074 "Selected to cancel"
		#define STR0075 "Interest already canceled"
		#define STR0076 "Interest with Service"
		#define STR0077 "Cancellation"
		#define STR0078 "Unable to select this Interest, because it already has a Service."
		#define STR0079 "Unable to select this Interest, because it is already canceled. "
		#define STR0080 "Select one or more Interests to cancel"
		#define STR0081 "Interest Pipeline"
		#define STR0082 "INTERESSES ATIVOS ( DENTRO DA DATA LIMITE )"
		#define STR0083 "INTERESSES NÃO CANCELADOS"
		#define STR0084 "INTERESSES CANCELADOS"
		#define STR0085 "Data do Interesse"
		#define STR0086 "Motivo do Cancelamento"
		#define STR0087 "Automatic Phase - Change of Service Status"
		#define STR0088 "This Interest phase is automatic. Unable to use it!"
		#define STR0089 "Knowledge Base"
		#define STR0090 "Deleting record is impossible. Interest already canceled!"
		#define STR0091 "Interest Phase is not related to Vehicles/Machines. Unable to continue!"
		#define STR0092 "Phase of Interest must be from the 1st Stage of the Funnel. Cannot continue!"
		#define STR0093 "Phase of Interest must be from the same or the next Stage of the Funnel. Cannot continue!"
		#define STR0094 "Generate CEV Schedule"
		#define STR0095 "Relate CEV Schedule"
		#define STR0096 "Invalid code."
		#define STR0097 "Customer"
		#define STR0098 "Prospect"
		#define STR0099 "Objective"
		#define STR0100 "Relate with Interest:"
		#define STR0101 "NEW"
		#define STR0102 "There are no Customer Schedules to make the relationship."
		#define STR0103 "CEV Schedule Relationship"
	#else
		#define STR0001 "Oportunidade de Negócios"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Pesquisa Cliente"
		#define STR0007 "Cancelar Interesse"
		#define STR0008 "Código"
		#define STR0009 "Loja"
		#define STR0010 "Nome"
		#define STR0011 "CNPJ/CPF"
		#define STR0012 "E-mail"
		#define STR0013 "Telefone"
		#define STR0014 "<<< FILTRAR >>>"
		#define STR0015 "Sair"
		#define STR0016 "OK"
		#define STR0017 "Campanha"
		#define STR0018 "Fase"
		#define STR0019 "Vendedor"
		#define STR0020 "Tipo de Contanto"
		#define STR0021 "Tipo de Midia"
		#define STR0022 "Marca"
		#define STR0023 "Modelo"
		#define STR0024 "Cor"
		#define STR0025 "Banco"
		#define STR0026 "Motivo Cancelamento"
		#define STR0027 "Filtro"
		#define STR0028 "Não existem dados para este pesquisa!"
		#define STR0029 "Atenção"
		#define STR0030 "Os dados do cliente (Código Cliente / Loja) são necessários para a próxima fase da oportunidade!"
		#define STR0031 "Cliente informado não encontrado no cadastro de clientes!"
		#define STR0032 "Impossivel Excluir o registro. Interesse já relacionado no Atendimento!"
		#define STR0033 "Fase Financiam."
		#define STR0034 "Agencia"
		#define STR0035 "Telefone"
		#define STR0036 "Linha de credito"
		#define STR0037 "Nome Banco"
		#define STR0038 "Nome Gerente"
		#define STR0039 "Cidade"
		#define STR0040 "Opcionais"
		#define STR0041 "Visual.Atendimento"
		#define STR0042 "Impossivel alterar a Fase do interesse. A Fase digitada não é uma Fase Final!"
		#define STR0043 "Impossível abrir Atendimento e Faturamento Direto ao mesmo tempo!"
		#define STR0044 "Prospect informado não encontrado no cadastro de prospects!"
		#define STR0045 "Necessário selecionar um Cliente ou Prospect!"
		#define STR0046 "Prospect"
		#define STR0047 "Converter Prospect em Cliente"
		#define STR0048 "Deseja converter o Prospect em Cliente?"
		#define STR0049 "Este Prospect já foi convertido para Cliente!"
		#define STR0050 "Fase do Interesse não esta ativa. Impossível continuar!"
		#define STR0051 "Replicar"
		#define STR0052 "Qtd. a Replicar"
		#define STR0053 "Impossível alterar a Fase do interesse. Verifique a sequencia das Fases!"
		#define STR0054 "Usuário sem permissão!"
		#define STR0055 "Os Interesses abaixo estão relacionados a Itens excluidos no Atendimento"
		#define STR0056 "Filial"
		#define STR0057 "Atendimento"
		#define STR0058 "Item"
		#define STR0059 "Status"
		#define STR0060 "Deseja limpar os relacionamentos para utilizar os Interesses futuramente?"
		#define STR0061 "Limpar Filtros"
		#define STR0062 "Cpos desconsiderar no Filtro"
		#define STR0063 "Informe os Campos da Tabela VDM que"
		#define STR0064 "serão desconsiderados no Filtro."
		#define STR0065 "Não existem Interesses relacionados ao código de vendedor do usuário logado!"
		#define STR0066 "INTERESSES SEM FASE INFORMADA"
		#define STR0067 "INTERESSES NA(S) FASE(S):"
		#define STR0068 "INTERESSES NA(S) FASE(S) INATIVA(S):"
		#define STR0069 "INTERESSES NA(S) FASE(S) SEM COR INFORMADA:"
		#define STR0070 "Oportunidades/Interesses"
		#define STR0071 "Cancelar"
		#define STR0072 "Selecione todos os Interesses que se deseja Cancelar"
		#define STR0073 "Não Selecionado"
		#define STR0074 "Selecionado para Cancelamento"
		#define STR0075 "Interesse já Cancelado"
		#define STR0076 "Interesse com Atendimento"
		#define STR0077 "Cancelamento"
		#define STR0078 "Impossivel selecionar este Interesse, pois o mesmo já possui Atendimento vinculado."
		#define STR0079 "Impossivel selecionar este Interesse, pois o mesmo já esta Cancelado."
		#define STR0080 "Favor selecionar um ou mais Interesses para o Cancelamento."
		#define STR0081 "Funil Interesses"
		#define STR0082 "INTERESSES ATIVOS ( DENTRO DA DATA LIMITE )"
		#define STR0083 "INTERESSES NÃO CANCELADOS"
		#define STR0084 "INTERESSES CANCELADOS"
		#define STR0085 "Data do Interesse"
		#define STR0086 "Motivo do Cancelamento"
		#define STR0087 "Fase Automática - Mudança de Status do Atendimento"
		#define STR0088 "Esta Fase do Interesse é automática. Impossível utilizar!"
		#define STR0089 "Banco de Conhecimento"
		#define STR0090 "Impossivel Excluir o registro. Interesse já Cancelado!"
		#define STR0091 "Fase do Interesse não esta relacionada a Veículos/Máquinas. Impossível continuar!"
		#define STR0092 "Fase do Interesse deve ser da 1ª Etapa do Funil. Impossível continuar!"
		#define STR0093 "Fase do Interesse deve ser da mesma ou da próxima Etapa do Funil. Impossível continuar!"
		#define STR0094 "Gerar Agenda CEV"
		#define STR0095 "Relacionar Agenda CEV"
		#define STR0096 "Código inválido!"
		#define STR0097 "Cliente"
		#define STR0098 "Prospect"
		#define STR0099 "Objetivo"
		#define STR0100 "Relaciona com o Interesse: "
		#define STR0101 "NOVO"
		#define STR0102 "Não existem Agendas do Cliente para fazer o relacionamento."
		#define STR0103 "Relacionamendo de Agenda CEV"
	#endif
#endif
