#ifdef SPANISH
	#define STR0001 "Comisión de consorcios y seguros - Generación de las cuotas y Fact."
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Generar Fact."
	#define STR0005 "Anular Fact."
	#define STR0006 "Comisión liberada"
	#define STR0007 "Leyenda"
	#define STR0008 "Cuotas"
	#define STR0009 "Consorcio sin Fact."
	#define STR0010 "Consorcio con Fact."
	#define STR0011 "Seguro sin Fact."
	#define STR0012 "Seguro con Fact."
	#define STR0013 "Fch. Liberación"
	#define STR0014 "Atención"
	#define STR0015 "Consorcio"
	#define STR0016 "Seguro"
	#define STR0017 "SALIR"
	#define STR0018 "¿Generar cuotas para?"
	#define STR0019 "Fch. Inicial venta"
	#define STR0020 "Fch. Final venta"
	#define STR0021 "Administradora"
	#define STR0022 "Aseguradora"
	#define STR0023 "Estatus"
	#define STR0024 "Generar"
	#define STR0025 "Es necesario informar la Administradora del consorcio."
	#define STR0026 "Es necesario informar el Indicador del consorcio (STATUS)."
	#define STR0027 "Es necesario informar la Aseguradora del seguro."
	#define STR0028 "Es necesario informar el Indicador del seguro (ESTATUS)."
	#define STR0029 "Vendedor"
	#define STR0030 "Cliente"
	#define STR0031 "Adm"
	#define STR0032 "Grupo"
	#define STR0033 "Cuota"
	#define STR0034 "Póliza"
	#define STR0035 "Corredora"
	#define STR0036 "Generación de cuotas"
	#define STR0037 "Ventas en el período:"
	#define STR0038 "Seleccionar cuotas del período:"
	#define STR0039 "a"
	#define STR0040 "OK"
	#define STR0041 "Total selección:"
	#define STR0042 "Datos adicionales para emisión de la Fact. de comisión:"
	#define STR0043 "Cond. Pago"
	#define STR0044 "Banco"
	#define STR0045 "TES"
	#define STR0046 "Modalidad"
	#define STR0047 "Producto"
	#define STR0048 "Observación"
	#define STR0049 "Vencimiento"
	#define STR0050 "Valor"
	#define STR0051 "Venta"
	#define STR0052 "¡Ninguna venta abierta de consorcio en el período!"
	#define STR0053 "¡Ninguna venta abierta de seguro en el período!"
	#define STR0054 "Total"
	#define STR0055 "Parcial"
	#define STR0056 "¡Factura/Serie no generada!"
	#define STR0057 "Confirma la anulación de la factura?"
	#define STR0058 "¡Factura/Serie no generada! ¡Imposible anular!"
	#define STR0059 "Valor de la cuota"
	#define STR0060 "¡Es necesario informar una o más cuotas!"
	#define STR0061 "¡Es necesario informar un TES para generación de la factura de comisión!"
	#define STR0062 "¡Es necesario informar un producto para formar parte de la factura de comisión!"
	#define STR0063 "¡Es necesario informar la condición de pago de la factura de comisión!"
	#define STR0064 "¡Es necesario informar el Cliente/Tienda!"
	#define STR0065 "Generar cuotas"
	#define STR0066 "Cond. Pago:"
	#define STR0067 "Banco:"
	#define STR0068 "Cliente:"
	#define STR0069 "TES:"
	#define STR0070 "Modalidad:"
	#define STR0071 "Producto:"
	#define STR0072 "Observación interna Fact DMS"
	#define STR0073 "Tp.Cliente:"
	#define STR0074 "Ind.Presencia:"
	#define STR0075 "Vendedor:"
	#define STR0076 "Serv.Divers."
	#define STR0077 "Nº Pedido"
	#define STR0078 "Es necesario informar el Número del pedido."
	#define STR0079 "Es necesario informar el Indicador de servicios diversos (ESTATUS)"
	#define STR0080 "Tp.Servicio"
	#define STR0081 "Referencia"
	#define STR0082 "Ninguna venta abierta de Servicios diversos en el período."
	#define STR0083 "Servicios diversos sin Fact."
	#define STR0084 "Servicios diversos con Fact."
	#define STR0085 "Prestación de servicios diversos"
	#define STR0086 "Es necesario informar campo vendedor."
	#define STR0087 "Mensaje Fact"
	#define STR0088 "Liberación de crédito de clientes referente a la sucursal y tipo seleccionado anterior"
	#define STR0089 "Solicitud pendiente liberación"
	#define STR0090 "Solicitud liberada  esperando utilización"
	#define STR0091 "Solicitud rechazada"
	#define STR0092 "¿Desea solicitar liberación?"
	#define STR0093 "¡Cliente sin límite de crédito!"
	#define STR0094 "Filtros estándar"
	#define STR0095 "Consorcios"
	#define STR0096 "Seguros"
	#define STR0097 "Servicios diversos"
#else
	#ifdef ENGLISH
		#define STR0001 "Commission of Purchasing Pool and Insurance - Generation of Installments and Invoice"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Generate Invoice"
		#define STR0005 "Cancel Invoice"
		#define STR0006 "Commission Released"
		#define STR0007 "Caption"
		#define STR0008 "Installments"
		#define STR0009 "Purchasing Pool without Invoice"
		#define STR0010 "Purchasing Pool with Invoice"
		#define STR0011 "Insurance without Invoice"
		#define STR0012 "Insurance with Invoice"
		#define STR0013 "ReleaseDt."
		#define STR0014 "Attention"
		#define STR0015 "Consortium"
		#define STR0016 "Insurance"
		#define STR0017 "EXIT"
		#define STR0018 "Issue installments for?"
		#define STR0019 "Initial Sale Dt."
		#define STR0020 "Final Sale Dt."
		#define STR0021 "Provider"
		#define STR0022 "Insurance Company"
		#define STR0023 "Status"
		#define STR0024 "Generate"
		#define STR0025 "Enter the Purchasing Pool Administrator."
		#define STR0026 "Enter the Purchasing Pool Indicator (STATUS)."
		#define STR0027 "Enter Insurance Company."
		#define STR0028 "Enter the Insurance Indicator (STATUS)."
		#define STR0029 "Sales Representative"
		#define STR0030 "Customer"
		#define STR0031 "Pre-employment"
		#define STR0032 "Group"
		#define STR0033 "Quota"
		#define STR0034 "Policy"
		#define STR0035 "Broker"
		#define STR0036 "Installments Generation"
		#define STR0037 "Sales in period:"
		#define STR0038 "Select period installments:"
		#define STR0039 "to"
		#define STR0040 "OK"
		#define STR0041 "Selection total:"
		#define STR0042 "Additional data for issuing Invoice commission:"
		#define STR0043 "Paymt Term"
		#define STR0044 "Bank"
		#define STR0045 "TIO"
		#define STR0046 "Class"
		#define STR0047 "Product"
		#define STR0048 "Note"
		#define STR0049 "Due Date"
		#define STR0050 "Value"
		#define STR0051 "Sales"
		#define STR0052 "No Purchasing Pool sale open in period!"
		#define STR0053 "No Insurance sale open in period!"
		#define STR0054 "Total"
		#define STR0055 "Partial"
		#define STR0056 "Invoice/Series not generated!"
		#define STR0057 "Confirm Invoice cancellation?"
		#define STR0058 "Invoice/Series not generated! Cannot cancel it!"
		#define STR0059 "Installment Value"
		#define STR0060 "Enter one or more installments!"
		#define STR0061 "Enter a TIO to create commission Invoice!"
		#define STR0062 "Enter a Product to create commission Invoice!"
		#define STR0063 "Enter the Commission Invoice Payment Term!"
		#define STR0064 "Enter the Customer/Store!"
		#define STR0065 "Generate Installments"
		#define STR0066 "Paymt Term:"
		#define STR0067 "Bank:"
		#define STR0068 "Customer:"
		#define STR0069 "TIO:"
		#define STR0070 "Class:"
		#define STR0071 "Product:"
		#define STR0072 "NF DMS Internal Note"
		#define STR0073 "Customer Tp.:"
		#define STR0074 "Attendance Ind.:"
		#define STR0075 "Sales representative:"
		#define STR0076 "Other Srv."
		#define STR0077 "Order No."
		#define STR0078 "Enter the order number"
		#define STR0079 "Enter Indicator of Several Services (STATUS)."
		#define STR0080 "Service Tp."
		#define STR0081 "Reference"
		#define STR0082 "No Several Services pending sales in period!"
		#define STR0083 "Several Services without NF"
		#define STR0084 "Several Services with NF"
		#define STR0085 "Several Services Rendering"
		#define STR0086 "Enter sales rep!"
		#define STR0087 "INV Message"
		#define STR0088 "Customers Credit Release referring to Branch and Type selected above"
		#define STR0089 "Request Pending Release"
		#define STR0090 "Request released and awaiting usage"
		#define STR0091 "Request Rejected"
		#define STR0092 "Request Release?"
		#define STR0093 "Customer without Credit Limit!"
		#define STR0094 "Default Filter"
		#define STR0095 "Consortium"
		#define STR0096 "Insurance"
		#define STR0097 "Various Services"
	#else
		#define STR0001 "Comissão de Consórcios e Seguros - Geração das Parcelas e NF"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Gerar NF"
		#define STR0005 "Cancelar NF"
		#define STR0006 "Comissão Liberada"
		#define STR0007 "Legenda"
		#define STR0008 "Parcelas"
		#define STR0009 "Consórcio sem NF"
		#define STR0010 "Consórcio com NF"
		#define STR0011 "Seguro sem NF"
		#define STR0012 "Seguro com NF"
		#define STR0013 "Dt.Liberação"
		#define STR0014 "Atenção"
		#define STR0015 "Consórcio"
		#define STR0016 "Seguro"
		#define STR0017 "SAIR"
		#define STR0018 "Gerar parcelas para?"
		#define STR0019 "Dt.Inicial Venda"
		#define STR0020 "Dt.Final Venda"
		#define STR0021 "Administradora"
		#define STR0022 "Seguradora"
		#define STR0023 "Status"
		#define STR0024 "Gerar"
		#define STR0025 "Necessário informar a Administradora do Consórcio."
		#define STR0026 "Necessário informar o Indicador do Consórcio (STATUS)."
		#define STR0027 "Necessário informar a Seguradora do Seguro."
		#define STR0028 "Necessário informar o Indicador do Seguro (STATUS)."
		#define STR0029 "Vendedor"
		#define STR0030 "Cliente"
		#define STR0031 "Adm"
		#define STR0032 "Grupo"
		#define STR0033 "Quota"
		#define STR0034 "Apolice"
		#define STR0035 "Corretora"
		#define STR0036 "Geração de Parcelas"
		#define STR0037 "Vendas no período:"
		#define STR0038 "Selecionar parcelas do período:"
		#define STR0039 "a"
		#define STR0040 "OK"
		#define STR0041 "Total seleção:"
		#define STR0042 "Dados adicionais para emissão da NF de comissão:"
		#define STR0043 "Cond.Pagto"
		#define STR0044 "Banco"
		#define STR0045 "TES"
		#define STR0046 "Natureza"
		#define STR0047 "Produto"
		#define STR0048 "Observação"
		#define STR0049 "Vencimento"
		#define STR0050 "Valor"
		#define STR0051 "Venda"
		#define STR0052 "Nenhuma venda aberta de Consórcio no periodo!"
		#define STR0053 "Nenhuma venda aberta de Seguro no periodo!"
		#define STR0054 "Total"
		#define STR0055 "Parcial"
		#define STR0056 "NF/Serie não gerada!"
		#define STR0057 "Confirma o cancelamento da NF:"
		#define STR0058 "NF/Serie não gerada! Impossível cancelar!"
		#define STR0059 "Valor da Parcela"
		#define STR0060 "Necessário informar uma ou mais parcelas!"
		#define STR0061 "Necessário informar um TES para geração da NF de comissão!"
		#define STR0062 "Necessário informar um Produto para compor a NF de comissão!"
		#define STR0063 "Necessário informar a Condição de Pagamento da NF de comissão!"
		#define STR0064 "Necessário informar o Cliente/Loja!"
		#define STR0065 "Gerar Parcelas"
		#define STR0066 "Cond.Pagto:"
		#define STR0067 "Banco:"
		#define STR0068 "Cliente:"
		#define STR0069 "TES:"
		#define STR0070 "Natureza:"
		#define STR0071 "Produto:"
		#define STR0072 "Observação Interna NF DMS"
		#define STR0073 "Tp.Cliente:"
		#define STR0074 "Ind.Presença:"
		#define STR0075 "Vendedor:"
		#define STR0076 "Srv.Divers."
		#define STR0077 "Nro.Pedido"
		#define STR0078 "Necessário informar o Numero do Pedido."
		#define STR0079 "Necessário informar o Indicador dos Serviços Diversos (STATUS)"
		#define STR0080 "Tp.Serviço"
		#define STR0081 "Referencia"
		#define STR0082 "Nenhuma venda aberta de Serviços Diversos no periodo!"
		#define STR0083 "Serviços Diversos sem NF"
		#define STR0084 "Serviços Diversos com NF"
		#define STR0085 "Prestação de Serviços Diversos"
		#define STR0086 "Necessario informar campo vendedor!"
		#define STR0087 "Mensagem NF"
		#define STR0088 "Liberação de Crédito de Clientes referente a Filial e Tipo selecionado acima"
		#define STR0089 "Solicitação Pendente Liberação"
		#define STR0090 "Solicitação Liberada e aguardando utilização"
		#define STR0091 "Solicitação Rejeitada"
		#define STR0092 "Deseja Solcitar Liberação?"
		#define STR0093 "Cliente sem Limite de Crédito!"
		#define STR0094 "Filtro Padrão"
		#define STR0095 "Consórcios"
		#define STR0096 "Seguros"
		#define STR0097 "Serviços Diversos"
	#endif
#endif
