#ifdef SPANISH
	#define STR0001 "Comisiones de Vehiculos"
	#define STR0002 "ADMINISTRACION"
	#define STR0003 "A RAYAS"
	#define STR0004 "Imprime Comisiones"
	#define STR0005 "Espere... Leyendo Facturacion de Vehiculos..."
	#define STR0006 "Sin ModVta"
	#define STR0007 "Nuevos Stock"
	#define STR0008 "Seminuevos"
	#define STR0009 "Fact. Directa "
	#define STR0010 "Especiales "
	#define STR0011 "VDI       "
	#define STR0012 "Consignado"
	#define STR0013 "Ficha de Vehiculos"
	#define STR0014 "F I C H A    D E    V E H I C U L O S"
	#define STR0015 "0                              Valor     %                  "
	#define STR0016 "0                        Ganancia      Perdida         Saldo"
	#define STR0017 "Intermediacion"
	#define STR0018 "Fact.Directa"
	#define STR0019 "Nuevo"
	#define STR0020 "Usado"
	#define STR0021 "Venta"
	#define STR0022 "Pago de Comision"
	#define STR0023 "Fch. Vta  nº Fact.       Cliente           Modelo    Chasis  Vl Vehic.  Base Comis Com Vended Pago  Com"
	#define STR0024 "Fch. Vta  nº Fact.       Cliente           Modelo    Chasis  Vl Vehic.  Base Comis Com Superv"
	#define STR0025 "Fch. Vta  nº Fact.       Cliente           Modelo    Chasis  Vl Vehic.  Base Comis ComGerente"
	#define STR0026 "PERIODO............."
	#define STR0027 " a "
	#define STR0028 "VENDEDOR............"
	#define STR0029 "SUPERVISOR.........."
	#define STR0030 "GERENTE............."
	#define STR0031 "MODALIDAD DE LA VENTA."
	#define STR0032 "Total de la Modalidad "
	#define STR0033 "Total del Vendedor "
	#define STR0034 "Total Supervisor  "
	#define STR0035 "Total Gerente     "
	#define STR0036 "(continuacion...)"
	#define STR0037 "VENDEDOR............."
	#define STR0038 "SUPERVISOR..........."
	#define STR0039 "GERENTE.............."
	#define STR0040 "MODALIDAD DE LA VENTA.."
	#define STR0041 "Total de la Modalidad"
	#define STR0042 "    DIRECTORIA           GERENTE DEL SECTOR          VENDEDOR     "
	#define STR0043 "Modal.Vta"
	#define STR0044 "Cod.Vent"
	#define STR0045 "Vendedor"
	#define STR0046 "Emision "
	#define STR0047 "Fact./Serie"
	#define STR0048 "Cliente"
	#define STR0049 "Modelo"
	#define STR0050 "Chasis"
	#define STR0051 "Val. Negoc"
	#define STR0052 "Base Ven"
	#define STR0053 "%Com Ven"
	#define STR0054 "Comis Vent"
	#define STR0055 "Base Ger"
	#define STR0056 "%Com Ger"
	#define STR0057 "Comis Ger"
	#define STR0058 "Comis Sup"
	#define STR0059 "V Pagado Ven"
	#define STR0060 "V Pagado Ger"
	#define STR0061 "V Pagado Sup"
	#define STR0062 "Historial"
	#define STR0063 "¿Desea realmente actualizar las fechas de Pago de Comision?"
	#define STR0064 "Fecha Pago Comision de "
	#define STR0065 " para "
	#define STR0066 "Vendedor de "
	#define STR0067 "Valor Comision del Vendedor   de "
	#define STR0068 "Valor Comision del Gerente    de "
	#define STR0069 "Valor Comision del Supervisor de "
	#define STR0070 "Historial"
	#define STR0071 "Las"
	#define STR0072 "el Usuario"
	#define STR0073 "modifico en el Chasis"
	#define STR0074 " "
	#define STR0075 "No existen datos en este periodo!"
	#define STR0076 "Atencion"
#else
	#ifdef ENGLISH
		#define STR0001 "Vehicle Commission"
		#define STR0002 "MANAGEMENT"
		#define STR0003 "Z-FORM"
		#define STR0004 "Print Commissions"
		#define STR0005 "Wait... Reading Invoicing of Vehicles."
		#define STR0006 "No SaleModel"
		#define STR0007 "New Stocks"
		#define STR0008 "Semi new"
		#define STR0009 "Direct Inv "
		#define STR0010 "Special "
		#define STR0011 "VDI       "
		#define STR0012 "Consignee"
		#define STR0013 "Vehicle Card"
		#define STR0014 "V E H I C L E   C A R D"
		#define STR0015 "0                              Value     %                  "
		#define STR0016 "0                        Profit         Loss           Balance"
		#define STR0017 "Mediation"
		#define STR0018 "Direct Inv."
		#define STR0019 "New"
		#define STR0020 "Second hand"
		#define STR0021 "Sales"
		#define STR0022 "Commission Payment"
		#define STR0023 "Sale Dt.  NF Nr.         Customer           Model    Chassis  Vl Vehicle Base Comis Com Salesm Paym Com"
		#define STR0024 "Sale Dt.  NF Nr.         Customer           Model    Chassis  Vl Vehicle Base Comis Com Superv"
		#define STR0025 "Sale Dt.  NF Nr.         Customer           Model    Chassis  Vl Vehicle Base Comis ManagerCom"
		#define STR0026 "PERIOD................."
		#define STR0027 " to "
		#define STR0028 "SALESMAN................."
		#define STR0029 "SUPERVISOR................."
		#define STR0030 "MANAGER.................."
		#define STR0031 "SALE MODALITY"
		#define STR0032 "Modality Total: "
		#define STR0033 "Salesman Total "
		#define STR0034 "Supervisor Total  "
		#define STR0035 "Manager Total     "
		#define STR0036 "(continuation...)"
		#define STR0037 "SALESMAN................."
		#define STR0038 "SUPERVISOR................."
		#define STR0039 "MANAGER.................."
		#define STR0040 "SALE MODALITY"
		#define STR0041 "Modality Total:"
		#define STR0042 "    ADMINISTRATION            MANAGER OF THE SECTOR            SALESMAN     "
		#define STR0043 "Sale Modal."
		#define STR0044 "Sale Code"
		#define STR0045 "Salesman"
		#define STR0046 "Issue "
		#define STR0047 "NF/Series"
		#define STR0048 "Customer"
		#define STR0049 "Model"
		#define STR0050 "Chassis"
		#define STR0051 "Negot Vl"
		#define STR0052 "Sale Base"
		#define STR0053 "% Sale Com"
		#define STR0054 "Sale Comiss"
		#define STR0055 "Man Base"
		#define STR0056 "%Man Com"
		#define STR0057 "Man Comiss"
		#define STR0058 "Sup Comiss"
		#define STR0059 "Sal Paid V"
		#define STR0060 "Man Paid V"
		#define STR0061 "Sup Paid V"
		#define STR0062 "History"
		#define STR0063 "Do you really want to update commission payment dates?"
		#define STR0064 "Commission Payment Date from "
		#define STR0065 " to "
		#define STR0066 "Salesman "
		#define STR0067 "Salesman Commission Value of "
		#define STR0068 "Manager Commission Value   of "
		#define STR0069 "Supervisor Commission Value   of "
		#define STR0070 "History"
		#define STR0071 "'As"
		#define STR0072 "the User"
		#define STR0073 "changed in Chassis"
		#define STR0074 ""
		#define STR0075 "There is no datum in this period!"
		#define STR0076 "Attention!"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Comissões de Veículos", "Comissoes de Veiculos" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Administração", "ADMINISTRACAO" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Código de Barras", "ZEBRADO" )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Imprime Comissões", "Imprime Comissoes" )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Aguarde... A ler facturamentos de veículos...", "Aguarde... Lendo Faturamentos de Veiculos..." )
		#define STR0006 "Sem ModVda"
		#define STR0007 "Novos Estq"
		#define STR0008 "Semi-Novos"
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Ft Directo ", "Ft Direto " )
		#define STR0010 "Especiais "
		#define STR0011 "VDI       "
		#define STR0012 "Consignado"
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Ficha de Veículos", "Ficha de Veiculos" )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "F I C H A    D E    V E Í C U L O S", "F I C H A    D E    V E I C U L O S" )
		#define STR0015 "0                              Valor     %                  "
		#define STR0016 "0                        Ganho         Perda           Saldo"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Intermediação", "Intermediacao" )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Fact.Directo", "Fat.Direto" )
		#define STR0019 "Novo"
		#define STR0020 "Usado"
		#define STR0021 "Venda"
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Pagamento de Comissão", "Pagamento de Comissao" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Data Vda  nro.Factura         Cliente           Modelo    Chassi  Vl Veículo Base Comis Com Vended Pagto Com", "Data Vda  nro.NF         Cliente           Modelo    Chassi  Vl Veiculo Base Comis Com Vended Pagto Com" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Data Vda  nro.Factura         Cliente           Modelo    Chassi  Vl Veículo Base Comis Com Superv", "Data Vda  nro.NF         Cliente           Modelo    Chassi  Vl Veiculo Base Comis Com Superv" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Data Vda  nro.Factura         Cliente           Modelo    Chassi  Vl Veículo Base Comis ComGerente", "Data Vda  nro.NF         Cliente           Modelo    Chassi  Vl Veiculo Base Comis ComGerente" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "PERÍODO.............", "PERIODO............." )
		#define STR0027 " a "
		#define STR0028 "VENDEDOR............"
		#define STR0029 "SUPERVISOR.........."
		#define STR0030 "GERENTE............."
		#define STR0031 "MODALIDADE DA VENDA."
		#define STR0032 "Total da Modalidade "
		#define STR0033 "Total do Vendedor "
		#define STR0034 "Total Supervisor  "
		#define STR0035 "Total Gerente     "
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "(continuação...)", "(continuacao...)" )
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "VENDEDOR............", "VENDEDOR............." )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "SUPERVISOR..........", "SUPERVISOR..........." )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "GERENTE.............", "GERENTE.............." )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "MODALIDADE DA VENDA.", "MODALIDADE DA VENDA.." )
		#define STR0041 "Total da Modalidade"
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "    DIRETORIA            GERENTE DO SECTOR            VENDEDOR     ", "    DIRETORIA            GERENTE DO SETOR            VENDEDOR     " )
		#define STR0043 "Modal.Vda"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Cód.Vend", "Cod.Vend" )
		#define STR0045 "Vendedor"
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Emissão ", "Emissao " )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Factura/Série", "NF/Serie" )
		#define STR0048 "Cliente"
		#define STR0049 "Modelo"
		#define STR0050 "Chassi"
		#define STR0051 "Vl Negoc"
		#define STR0052 "Base Ven"
		#define STR0053 "%Com Ven"
		#define STR0054 "Comiss Vend"
		#define STR0055 "Base Ger"
		#define STR0056 "%Com Ger"
		#define STR0057 "Comiss Ger"
		#define STR0058 "Comiss Sup"
		#define STR0059 "V Pago Ven"
		#define STR0060 "V Pago Ger"
		#define STR0061 "V Pago Sup"
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "Histórico", "Historico" )
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "Deseja realmente actualizar as datas de Pagamento de Comissão?", "Deseja realmente atualizar as datas de Pagamento de Comissao?" )
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "Da Data Pagto Comissão ", "Data Pagto Comissao de " )
		#define STR0065 " para "
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "Do Vendedor ", "Vendedor de " )
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Do Valor Comissão do Vendedor ", "Valor Comissao do Vendedor   de " )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Do Valor Comissão do Gerente ", "Valor Comissao do Gerente    de " )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Do Valor Comissão do Supervisor ", "Valor Comissao do Supervisor de " )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Histórico", "Historico" )
		#define STR0071 "'As"
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "o Utilizador", "o Usuario" )
		#define STR0073 "alterou no Chassi"
		#define STR0074 ""
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Não existem dados neste período!", "Nao existem dados neste periodo!" )
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Atenção!", "Atencao!" )
	#endif
#endif
