#ifdef SPANISH
	#define STR0001 "Stock de Vehiculos"
	#define STR0002 "A Rayas"
	#define STR0003 "Administracion"
	#define STR0004 " Dias SucursalAtu SucCompra Fact        Digitacion Emision Proveedor Marca / Modelo            Ano  Chasis             Color           Vlr Unitario   Flete   s/Correccion  c/Correccion Ind.Correccion Situac Placa    ClaFis   Ejes"
	#define STR0005 "Espere ... Generando Indices del Archivo de Trabajo..."
	#define STR0006 "T O T A L   D E   "
	#define STR0007 "N A C I O N A L E S   N U E V O S    "
	#define STR0008 "N A C I O N A L E S   U S A D O S  "
	#define STR0009 "I M P O R T A D O S   N U E V O S  "
	#define STR0010 "I M P O R T A D O S   U S A D O S"
	#define STR0011 "T O T A L   G E N E R A L   D E   V E H I C U L O S"
	#define STR0012 "Stock"
	#define STR0013 "Remesa "
	#define STR0014 "Transfer"
	#define STR0015 "Transfer"
	#define STR0016 "Reservad"
	#define STR0017 "T o t a l  d e  S t o c k                         "
	#define STR0018 "T o t a l  d e  R e m e s a                       "
	#define STR0019 "T o t a l  d e  C o n s i g n a d o               "
	#define STR0020 "T o t a l  d e T r a n s f e r i d o              "
	#define STR0021 "T o t a l  d e  R e s e r v a d o                 "
	#define STR0022 "Dias"
	#define STR0023 "Item"
	#define STR0024 "F"
	#define STR0025 "Emision"
	#define STR0026 "Marca/Modelo"
	#define STR0027 "Ano/Mod"
	#define STR0028 "Chasis"
	#define STR0029 "Color"
	#define STR0030 "Vlr Unit."
	#define STR0031 "Icms Subs"
	#define STR0032 "Pis/Cofins"
	#define STR0033 "Flete"
	#define STR0034 "s/Correccion"
	#define STR0035 "c/Correccion"
	#define STR0036 "Tabla"
	#define STR0037 "Indice"
	#define STR0038 "Correccion"
	#define STR0039 "FCSdas"
	#define STR0040 "Situac"
	#define STR0041 "Matricula"
	#define STR0042 "Totales"
	#define STR0043 "Cantidad"
	#define STR0044 "   N a c i o n a l e s"
	#define STR0045 "   I m p o r t a d o s"
	#define STR0046 "Total de Color "
	#define STR0047 "T O T A L  D E L  M O D E L O   ( "
	#define STR0048 "Modelo = ( "
	#define STR0049 " )"
	#define STR0050 "Rem. Prop. en Terc."
	#define STR0051 "¿Marca ?   "
	#define STR0052 "¿Fecha?    "
	#define STR0053 "U S A D O S  E N  S T O C K"
	#define STR0054 "¿Estado del Vehiculo? "
	#define STR0055 "Cod Modelo"
	#define STR0056 "Clas Fiscal"
	#define STR0057 "Dist Ejes"
	#define STR0058 "De Sucursal"
	#define STR0059 "A Sucursal"
	#define STR0060 "N U E V O S   E N   S T O C K"
	#define STR0061 "Consignación"
	#define STR0062 "Atención"
	#define STR0063 "ChaInt"
	#define STR0064 "no se encontró en el Archivo de vehículos."
	#define STR0065 "V E H Í C U L O S   N U E V O S"
	#define STR0066 "V E H Í C U L O S   U S A D O S"
	#define STR0067 "¿Util. TES que mueve stock?"
	#define STR0068 "¿Lista vehículos inmovilizados?"
	#define STR0069 "Sí"
	#define STR0070 "No"
	#define STR0071 "Ambos"
	#define STR0072 "Nuevo"
	#define STR0073 "Utilizado"
	#define STR0074 "Días SucAct SucCompra Fact Digitac Emisión Proveedor Marca / Modelo Año Chasis Color Val Unitario Flete s/Correcc c/Correcc Ind.Correcc Situac Matrícula ClaFis Ejes"
#else
	#ifdef ENGLISH
		#define STR0001 "Vehicles Stock"
		#define STR0002 "Z.Form"
		#define STR0003 "Management"
		#define STR0004 " Branch DaysAtu FilPurch Invoice    Typing    Issue   Supplier   Brand / Model             Year Chassis            Color         Unit Value     Freight w/o Correct w/Correct  Ind.Correct  Status Board    ClaFis   Axis"
		#define STR0005 "Please, wait. Generating Work File Indexes..."
		#define STR0006 "T O T A L     "
		#define STR0007 "N A T I O N A L  -  B R A N D  N E W "
		#define STR0008 "N A T I O N A L  -  2 N D  H A N D "
		#define STR0009 "I M P O R T E D  -  B R A N D  N E W "
		#define STR0010 "I M P O R T E D  -  2 N D  H A N D"
		#define STR0011 "G R A N D   T O T A L   -   V E H I C L E S"
		#define STR0012 "Stock"
		#define STR0013 "Remittance "
		#define STR0014 "Transfer"
		#define STR0015 "Transfer"
		#define STR0016 "Reserved"
		#define STR0017 "S t o c k  T o t a l                     "
		#define STR0018 "R e m i t t a n c e  T o t a l                     "
		#define STR0019 "C o n s i g n e e  T o t a l               "
		#define STR0020 "T r a n s f e r e d  T o t a l               "
		#define STR0021 "R e s e r v e d  T o t a l                 "
		#define STR0022 "Days"
		#define STR0023 "Item"
		#define STR0024 "Invoice"
		#define STR0025 "Issue"
		#define STR0026 "Brand/Model"
		#define STR0027 "Year/Mod"
		#define STR0028 "Chassis"
		#define STR0029 "Color"
		#define STR0030 "Unit Vl."
		#define STR0031 "Subs Icms"
		#define STR0032 "Pis/Cofins"
		#define STR0033 "Freight"
		#define STR0034 "wt/Correction"
		#define STR0035 "w/Correction"
		#define STR0036 "Table"
		#define STR0037 "Index"
		#define STR0038 "Correction"
		#define STR0039 "NFSdas"
		#define STR0040 "Status"
		#define STR0041 "License Plate"
		#define STR0042 "Totals"
		#define STR0043 "Amount"
		#define STR0044 "   N a t i o n a l"
		#define STR0045 "   I m p o r t e d"
		#define STR0046 "Total Color "
		#define STR0047 "T O T A L  MODEL  ( "
		#define STR0048 "Model = ( "
		#define STR0049 " )"
		#define STR0050 "Rem. Prop. in Third."
		#define STR0051 "Brand ?   "
		#define STR0052 "Date?    "
		#define STR0053 "U S E D I N S T O C K"
		#define STR0054 "Vehicle State? "
		#define STR0055 "Model Code"
		#define STR0056 "Tax Class"
		#define STR0057 "Axes Dist"
		#define STR0058 "Branch from"
		#define STR0059 "Branch To"
		#define STR0060 "N E W I N S T O C K"
		#define STR0061 "Consignment"
		#define STR0062 "Attention"
		#define STR0063 "Chaint"
		#define STR0064 "not found in Vehicles Register!"
		#define STR0065 "N E W  V E H I C L E S"
		#define STR0066 "S E C O N D  H A N D  V E H I C L E S"
		#define STR0067 "Use TIO moving Stock?"
		#define STR0068 "Lists Fixed Vehicles?"
		#define STR0069 "Yes"
		#define STR0070 "No"
		#define STR0071 "Both"
		#define STR0072 "New"
		#define STR0073 "Used"
		#define STR0074 "Days CurrBranch PurchBranch Inv Typing Issue Supplier Brand / Model Year Chassis Color Unit Value Freight Corrected Not Corrected Correction Ind Status License Plate FisCla Axis"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Stock De Veiculos", "Estoque de Veiculos" )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Administração", "Administracao" )
		#define STR0004 " Dias FilialAtu FilCompra NF        Digitação Emissão Fornecedor Marca / Modelo            Ano  Chassi             Cor           Vlr Unitário   Frete   s/Correção  c/Correção Ind.Correção Situac Placa    ClaFis   Eixos"
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Aguarde... Gerando Indices Do Arquivo De Trabalho...", "Aguarde... Gerando Indices do Arquivo de Trabalho..." )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "T o t a l   d e   ", "T O T A L   D E   " )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "N a c i o n a i s   n o v o s    ", "N A C I O N A I S   N O V O S    " )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "N a c i o n a i s   u s a d o s  ", "N A C I O N A I S   U S A D O S  " )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "I m p o r t a d o s   n o v o s  ", "I M P O R T A D O S   N O V O S  " )
		#define STR0010 "I M P O R T A D O S   U S A D O S"
		#define STR0011 "T O T A L   G E R A L   D E   V E I C U L O S"
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Stock", "Estoque" )
		#define STR0013 "Remessa "
		#define STR0014 "Transfer"
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Transfer.", "Transfer" )
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Reserv.", "Reservad" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "T o t a l  d e  S t o c k                     ", "T o t a l  d e  E s t o q u e                     " )
		#define STR0018 "T o t a l  d e  R e m e s s a                     "
		#define STR0019 "T o t a l  d e  C o n s i g n a d o               "
		#define STR0020 "T o t a l  d e T r a n s f e r i d o              "
		#define STR0021 "T o t a l  d e  R e s e r v a d o                 "
		#define STR0022 "Dias"
		#define STR0023 "Item"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Fact.", "NF" )
		#define STR0025 "Emissão"
		#define STR0026 "Marca/Modelo"
		#define STR0027 "Ano/Mod"
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Chassis", "Chassi" )
		#define STR0029 "Cor"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Vlr.Unit.", "Vlr Unit." )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "ICMS Subs.", "Icms Subs" )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "PIS/COFINS", "Pis/Cofins" )
		#define STR0033 "Frete"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "s/Correcção", "s/Correção" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "c/Correcção", "c/Correção" )
		#define STR0036 "Tabela"
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Índice", "Indice" )
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Correcção", "Correção" )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "FSdas", "NFSdas" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Situaç", "Situac" )
		#define STR0041 "Placa"
		#define STR0042 "Totais"
		#define STR0043 "Quantidade"
		#define STR0044 "   N a c i o n a i s"
		#define STR0045 "   I m p o r t a d o s"
		#define STR0046 "Total de Cor "
		#define STR0047 "T O T A L  D O  M O D E L O   ( "
		#define STR0048 "Modelo = ( "
		#define STR0049 " )"
		#define STR0050 "Rem. Prop. em Terc."
		#define STR0051 "Marca ?   "
		#define STR0052 "Data ?    "
		#define STR0053 If( cPaisLoc $ "ANG|PTG", "U S A D O S  E M   S T O C K ", "U S A D O S  E M  E S T O Q U E" )
		#define STR0054 If( cPaisLoc $ "ANG|PTG", "Estado do veículo ? ", "Estado do Veículo ? " )
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Cód.Modelo", "Cod Modelo" )
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "Class. Fiscal", "Class Fiscal" )
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "Dist.eixos", "Dist Eixos" )
		#define STR0058 "Filial De"
		#define STR0059 "Filial Até"
		#define STR0060 "N O V O S   E M   E S T O Q U E"
		#define STR0061 "Consignação"
		#define STR0062 "Atenção"
		#define STR0063 "ChaInt"
		#define STR0064 "não encontrado no Cadastro de Veículos!"
		#define STR0065 "V E I C U L O S   N O V O S"
		#define STR0066 "V E I C U L O S   U S A D O S"
		#define STR0067 "Util. TES que movimenta Estoq.?"
		#define STR0068 "Lista Veículos imobilizados?"
		#define STR0069 "Sim"
		#define STR0070 "Não"
		#define STR0071 "Ambos"
		#define STR0072 "Novo"
		#define STR0073 "Usado"
		#define STR0074 " Dias FilialAtu FilCompra NF        Digitação Emissão Fornecedor Marca / Modelo            Ano  Chassi             Cor         Vlr Unitário     Frete   s/Correção  c/Correção Ind.Correção Situac Placa    ClaFis   Eixos"
	#endif
#endif
