#ifdef SPANISH
	#define STR0001 "Consulta de vehiculos"
	#define STR0002 "No"
	#define STR0003 "Si"
	#define STR0004 "Fct-Vt"
	#define STR0005 "Rastreo del vehiculo"
	#define STR0006 "Visualiza registro del vehiculo"
	#define STR0007 "Progreso de vehiculo"
	#define STR0008 "Simulacion / Venta futura"
	#define STR0009 "Simulacion"
	#define STR0010 "Estado del vehiculo"
	#define STR0011 "Marca"
	#define STR0012 "Descripción"
	#define STR0013 "Grupo del modelo"
	#define STR0014 "Modelo"
	#define STR0015 "Tipo de color"
	#define STR0016 "Color"
	#define STR0017 "Tienda"
	#define STR0018 "Tipo"
	#define STR0019 "Ano inicial"
	#define STR0020 "Ano final"
	#define STR0021 "Combustible"
	#define STR0022 "Valor Inicial"
	#define STR0023 "Valor Final"
	#define STR0024 "KM Maxima"
	#define STR0025 "Opcionales"
	#define STR0026 "Actualizar"
	#define STR0027 "Actualizacion"
	#define STR0028 "Dias"
	#define STR0029 "Marca/Modelo"
	#define STR0030 "Valor"
	#define STR0031 "Fab/Mod"
	#define STR0032 "Opcionales Fabrica"
	#define STR0033 "Chasis"
	#define STR0034 "Matricula"
	#define STR0035 "Km"
	#define STR0036 "Prev.Entrega"
	#define STR0037 "Observacion"
	#define STR0038 "Fisica"
	#define STR0039 "Stock"
	#define STR0040 "En Transito"
	#define STR0041 "Remesa Entrada"
	#define STR0042 "Consignado"
	#define STR0043 "Comercial"
	#define STR0044 "Normal"
	#define STR0045 "Reservados"
	#define STR0046 "Bloqueados"
	#define STR0047 "Seleccione el tipo de atencion y Modelo/Color del vehiculo deseado"
	#define STR0048 "Foto(s)/Video(s) del vehiculo"
	#define STR0049 "Venta Futura"
	#define STR0050 "Atencion"
	#define STR0051 "Informe el tipo de atencion."
	#define STR0052 "Informe el Modelo/Color deseados."
	#define STR0053 "Usuario sin permiso para visualizar el bonos del vehiculo."
	#define STR0054 "Bonos Vigente"
	#define STR0055 "¡Vehiculo no seleccionado!"
	#define STR0056 "¡Marca/Modelo/Color no seleccionados!"
	#define STR0057 "Bonos Utilizado"
	#define STR0058 "Tipo de Bonos"
	#define STR0059 "Vigencia de Bonos"
	#define STR0060 "Banco de Conocimiento"
	#define STR0061 "Pedido"
	#define STR0062 "Proveedor"
	#define STR0063 "Cliente"
	#define STR0064 "Estatus no valido"
	#define STR0065 "Sin transaccion de compra"
	#define STR0066 "Vehiculo ya vendido"
	#define STR0067 "¡No se puede seleccionar vehiculo!"
	#define STR0068 "Tipo de vehiculo"
	#define STR0069 "¡Usuario no tiene permiso para utilizar este vehiculo!"
	#define STR0070 "¡Vehiculo no encontrado!"
	#define STR0071 "Automática"
	#define STR0072 "Promocion"
	#define STR0073 "Imposible seleccionar el Vehiculo. ¡Se alcanzo la cantidad maxima permitida por Atencion!"
	#define STR0074 "Usuario sin permiso para Atencion de Vehiculo Nuevo."
	#define STR0075 "Usuario sin permiso para Antecion de Vehiculo Usado."
	#define STR0076 "Bonos"
	#define STR0077 "Pagado"
	#define STR0078 "Bono del vehiculo"
	#define STR0079 "Parametros/Columnas"
	#define STR0080 "Secuencia"
	#define STR0081 "Columna"
	#define STR0082 "Columnas Default"
	#define STR0083 "COLUNAS NÃO UTILIZADAS"
	#define STR0084 "COLUNAS UTILIZADAS"
	#define STR0085 "Columnas utilizadas en la consulta de vehiculos"
	#define STR0086 "Total"
	#define STR0087 "Totales"
	#define STR0088 "Configuración"
	#define STR0089 "Tiene configuración"
	#define STR0090 "Leyenda"
	#define STR0091 "No seleccionado"
	#define STR0092 "Seleccionado"
	#define STR0093 "Fecha FDD"
	#define STR0094 "Filtros"
	#define STR0095 "Est/Prov/Reg Tiendas"
	#define STR0096 "De días"
	#define STR0097 "A días"
	#define STR0098 "Fotos/Videos"
	#define STR0099 "Remesa Salida"
	#define STR0100 "Rem.Entrada"
	#define STR0101 "Rem.Salida"
	#define STR0102 "Cantidad"
	#define STR0103 "Fch.Pedido"
	#define STR0104 "Información de atención"
	#define STR0105 "Pedido de fábrica"
#else
	#ifdef ENGLISH
		#define STR0001 "Vehicle Query"
		#define STR0002 "No"
		#define STR0003 "Yes"
		#define STR0004 "Im-Vd"
		#define STR0005 "Vehicle Tracking"
		#define STR0006 "View Vehicle Register"
		#define STR0007 "Vehicle Progress"
		#define STR0008 "Simulation / Future Sales"
		#define STR0009 "Simulation"
		#define STR0010 "Vehicle State"
		#define STR0011 "Brand"
		#define STR0012 "Description"
		#define STR0013 "Model Group"
		#define STR0014 "Model"
		#define STR0015 "Type of Color"
		#define STR0016 "Color"
		#define STR0017 "Unit"
		#define STR0018 "Type"
		#define STR0019 "Initial Year"
		#define STR0020 "Final Year"
		#define STR0021 "Fuel"
		#define STR0022 "Initial Value"
		#define STR0023 "Final Value"
		#define STR0024 "Maximum Mileage"
		#define STR0025 "Optional Items"
		#define STR0026 "Update"
		#define STR0027 "Update"
		#define STR0028 "Days"
		#define STR0029 "Brand/Model"
		#define STR0030 "Value"
		#define STR0031 "Manuf./Mod."
		#define STR0032 "Factory Optional Items"
		#define STR0033 "Chassis"
		#define STR0034 "License Plate"
		#define STR0035 "Mileage"
		#define STR0036 "Delivery Estimate"
		#define STR0037 "Note"
		#define STR0038 "Individual"
		#define STR0039 "Inventory"
		#define STR0040 "In transit"
		#define STR0041 "Remittance Inflow"
		#define STR0042 "Consigned"
		#define STR0043 "Commercial"
		#define STR0044 "Regular"
		#define STR0045 "Reserved"
		#define STR0046 "Blocked"
		#define STR0047 "Select the Service Type and Vehicle Model/Color."
		#define STR0048 "Vehicle Image(s)/Video(s)"
		#define STR0049 "Future Sale"
		#define STR0050 "Attention"
		#define STR0051 "Enter the service type."
		#define STR0052 "Enter the Model/Color."
		#define STR0053 "User without permission to View Vehicle Bonus."
		#define STR0054 "Effective Bonus"
		#define STR0055 "Vehicle not selected!"
		#define STR0056 "Brand/Model/Color not selected!"
		#define STR0057 "Bonus Used"
		#define STR0058 "Bonus Type"
		#define STR0059 "Bonus Validity"
		#define STR0060 "Knowledge Base"
		#define STR0061 "Order"
		#define STR0062 "Supplier"
		#define STR0063 "Customer"
		#define STR0064 "Invalid status."
		#define STR0065 "No purchase transaction."
		#define STR0066 "Vehicle already sold."
		#define STR0067 "This vehicle cannot be selected."
		#define STR0068 "Vehicle Type"
		#define STR0069 "User is not allowed to use this vehicle!"
		#define STR0070 "Vehicle not found!"
		#define STR0071 "Automatic"
		#define STR0072 "Promotion"
		#define STR0073 "Impossible to select Vehicle. Maximum amount per service has been reached!"
		#define STR0074 "User without permission for New Vehicle Services."
		#define STR0075 "User without permission for Used Vehicle Services."
		#define STR0076 "Bonus"
		#define STR0077 "Paid"
		#define STR0078 "Vehicle Bonus"
		#define STR0079 "Parameters/Columns"
		#define STR0080 "Sequence"
		#define STR0081 "Column"
		#define STR0082 "Default Columns"
		#define STR0083 "NOT USED COLUMNS"
		#define STR0084 "USED COLUMNS"
		#define STR0085 "Used columns on vehicle search"
		#define STR0086 "Total"
		#define STR0087 "Totals"
		#define STR0088 "Configuration"
		#define STR0089 "It has Configuration"
		#define STR0090 "Caption"
		#define STR0091 "Not Selected"
		#define STR0092 "Selected"
		#define STR0093 "FDD Date"
		#define STR0094 "Filters"
		#define STR0095 "FU Stores"
		#define STR0096 "Days from"
		#define STR0097 "Days To"
		#define STR0098 "Photos/Videos"
		#define STR0099 "Remittance Outflow"
		#define STR0100 "Rem.Inflow"
		#define STR0101 "Rem.Outflow"
		#define STR0102 "Quantity"
		#define STR0103 "Order Date"
		#define STR0104 "Service information"
		#define STR0105 "Factory Order"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Consulta de Veículos", "Consulta de Veiculos" )
		#define STR0002 "Não"
		#define STR0003 "Sim"
		#define STR0004 "Ft-Vd"
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Rastreamento do Veículo", "Rastreamento do Veiculo" )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Visualiza Registo do Veículo", "Visualiza Cadastro do Veiculo" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Progresso de Veículo", "Progresso de Veiculo" )
		#define STR0008 "Simulação / Venda Futura"
		#define STR0009 "Simulação"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Estado do Veículo", "Estado do Veiculo" )
		#define STR0011 "Marca"
		#define STR0012 "Descrição"
		#define STR0013 "Grupo do Modelo"
		#define STR0014 "Modelo"
		#define STR0015 "Tipo de Cor"
		#define STR0016 "Cor"
		#define STR0017 "Loja"
		#define STR0018 "Tipo"
		#define STR0019 "Ano Inicial"
		#define STR0020 "Ano Final"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Combustível", "Combustivel" )
		#define STR0022 "Valor Inicial"
		#define STR0023 "Valor Final"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "KM Máxima", "KM Maxima" )
		#define STR0025 "Opcionais"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Actualizar", "Atualizar" )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Actualização", "Atualização" )
		#define STR0028 "Dias"
		#define STR0029 "Marca/Modelo"
		#define STR0030 "Valor"
		#define STR0031 "Fab/Mod"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Opcionais Fábrica", "Opcionais Fabrica" )
		#define STR0033 "Chassi"
		#define STR0034 "Placa"
		#define STR0035 "KM"
		#define STR0036 "Prev.Entrega"
		#define STR0037 "Observação"
		#define STR0038 If( cPaisLoc $ "ANG|PTG", "Física", "Fisica" )
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Stock", "Estoque" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Em trânsito", "Em Transito" )
		#define STR0041 "Remessa Entrada"
		#define STR0042 "Consignado"
		#define STR0043 "Comercial"
		#define STR0044 "Normal"
		#define STR0045 "Reservados"
		#define STR0046 "Bloqueados"
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Seleccione o Tipo de Atendimento e Modelo/Cor do Veículo desejado", "Selecione o Tipo de Atendimento e Modelo/Cor do Veiculo desejado" )
		#define STR0048 "Foto(s)/Video(s) do Veículo"
		#define STR0049 "Venda Futura"
		#define STR0050 "Atenção"
		#define STR0051 "Informe o Tipo de Atendimento."
		#define STR0052 "Informe o Modelo/Cor desejados."
		#define STR0053 "Usuário sem permissão para Visualizar o Bonus do Veiculo."
		#define STR0054 "Bonus Vigente"
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Veículo não seleccionado!", "Veiculo não selecionado!" )
		#define STR0056 If( cPaisLoc $ "ANG|PTG", "Marca/Modelo/Cor não seleccionados!", "Marca/Modelo/Cor não selecionados!" )
		#define STR0057 "Bonus Utilizado"
		#define STR0058 "Tipo do Bonus"
		#define STR0059 "Vigência do Bonus"
		#define STR0060 "Banco de Conhecimento"
		#define STR0061 "Pedido"
		#define STR0062 "Fornecedor"
		#define STR0063 "Cliente"
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "Estado inválido", "Status invalido" )
		#define STR0065 "Sem transação de compra"
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "Veículo ja Vendido", "Veiculo ja Vendido" )
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "Veículo não pode ser seleccionado!", "Veiculo não pode ser selecionado!" )
		#define STR0068 If( cPaisLoc $ "ANG|PTG", "Tipo do Veículo", "Tipo do Veiculo" )
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "Utilizador não permitido para utilizar esse veículo!", "Usuario não permitido para utilizar esse veiculo!" )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", "Veículo não encontrado!", "Veiculo não encontrado!" )
		#define STR0071 "Automática"
		#define STR0072 "Promoção"
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Impossível seleccionar o veículo. A quantidade máxima permitida por Atendimento foi atingida.", "Impossivel selecionar o Veiculo. A quantidade máxima permitida por Atendimento foi atingida!" )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Utilizador sem permissão para Atendimentos de Veículo Novo.", "Usuário sem permissão para Atendimentos de Veiculo Novo." )
		#define STR0075 If( cPaisLoc $ "ANG|PTG", "Utilizador sem permissão para Atendimentos de Veículo Usado.", "Usuário sem permissão para Atendimentos de Veiculo Usado." )
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "Bónus", "Bonus" )
		#define STR0077 "Pago"
		#define STR0078 If( cPaisLoc $ "ANG|PTG", "Bónus do Veículo", "Bonus do Veiculo" )
		#define STR0079 "Parametros/Colunas"
		#define STR0080 "Sequência"
		#define STR0081 "Coluna"
		#define STR0082 "Colunas Default"
		#define STR0083 "COLUNAS NÃO UTILIZADAS"
		#define STR0084 "COLUNAS UTILIZADAS"
		#define STR0085 "Colunas utilizadas na Consulta de Veiculos"
		#define STR0086 "Total"
		#define STR0087 "Totais"
		#define STR0088 "Configuração"
		#define STR0089 "Possui Configuração"
		#define STR0090 "Legenda"
		#define STR0091 "Não Selecionado"
		#define STR0092 "Selecionado"
		#define STR0093 "Data FDD"
		#define STR0094 "Filtros"
		#define STR0095 "UF Lojas"
		#define STR0096 "Dias De"
		#define STR0097 "Dias Ate"
		#define STR0098 "Fotos/Videos"
		#define STR0099 "Remessa Saída"
		#define STR0100 "Rem.Entrada"
		#define STR0101 "Rem.Saída"
		#define STR0102 "Quantidade"
		#define STR0103 "Dt.Pedido"
		#define STR0104 "Informações de Atendimento"
		#define STR0105 "Pedido Fabrica"
	#endif
#endif
