#ifdef SPANISH
	#define STR0001 "Bloqueo de saldo WMS"
	#define STR0002 "Saldo"
	#define STR0003 "Ítems Bloqueo de saldo WMS"
	#define STR0004 "Bloqueo de lote"
	#define STR0005 "Modelo no válido ([VAR01])"
	#define STR0006 "Documento para el bloqueo de saldo no se informó."
	#define STR0007 "Motivo para el bloqueo de saldo no se informó."
	#define STR0008 "Producto [VAR01] / almacén [VAR02]: bloqueo solicitado ([VAR03]) es superior al saldo ([VAR04])."
	#define STR0009 "Componentización"
	#define STR0010 "No se seleccionaron todos los componentes para bloquear el producto [VAR01]."
	#define STR0011 "Productos en falta:"
	#define STR0012 "¡Cantidad múltiple de los componentes en lotes inválida! Ve nuevamente las cantidades del producto [VAR01] del lote/Sublote: '[VAR02]'."
	#define STR0013 "¡Existen informaciones no válidas en el formulario!"
	#define STR0014 "Problema en la concreción de los datos: "
	#define STR0015 "Saldo por ubicación WMS"
	#define STR0016 "¡Existen informaciones no válidas en el formulario!"
#else
	#ifdef ENGLISH
		#define STR0001 "WMS balance block"
		#define STR0002 "Balance"
		#define STR0003 "WMS balance block items"
		#define STR0004 "Lot Blockage"
		#define STR0005 "Invalid model ([VAR01])"
		#define STR0006 "Document for balance block not entered."
		#define STR0007 "Reason for balance block not entered."
		#define STR0008 "Product [VAR01] / warehouse [VAR02]: block requested ([VAR03]) is greater than the balance ([VAR04])."
		#define STR0009 "Composition"
		#define STR0010 "Not all compositions were selected to block product [VAR01]."
		#define STR0011 "Missing products:"
		#define STR0012 "Multiple quantity of components in lots not valid! Review amounts of product [VAR01] of lot/sub-lot: [VAR02]"
		#define STR0013 "There is invalid information in the form!"
		#define STR0014 "Problem confirming data: "
		#define STR0015 "Balance by WMS address"
		#define STR0016 "Invalid information in the form."
	#else
		#define STR0001 "Bloqueio de Saldo WMS"
		#define STR0002 "Saldo"
		#define STR0003 "Itens Bloqueio de Saldo WMS"
		#define STR0004 "Bloqueio de Lote"
		#define STR0005 "Modelo inválido ([VAR01])"
		#define STR0006 "Documento para o bloqueio de saldo não foi informado."
		#define STR0007 "Motivo para o bloqueio de saldo não foi informado."
		#define STR0008 "Produto [VAR01] / armazém [VAR02]: bloqueio solicitado ([VAR03]) é maior que o saldo ([VAR04])."
		#define STR0009 "Componentização"
		#define STR0010 "Não foram selecionados todos os componentes para bloquear o produto [VAR01]."
		#define STR0011 "Produtos faltantes:"
		#define STR0012 "Quantidade multipla dos componentes em lotes inválida! Rever quantidades do produto [VAR01] do Lote/Sub-Lote: '[VAR02]'."
		#define STR0013 "Existem informações inválidos no formulário!"
		#define STR0014 "Problema na efetivação dos dados: "
		#define STR0015 "Saldo por endereço WMS"
		#define STR0016 "Existem informações inválidas no formulário!"
	#endif
#endif
