#ifdef SPANISH
	#define STR0001 "Reabastecimiento"
	#define STR0002 "Procesar"
	#define STR0003 "Seleccionar"
	#define STR0004 "Visualizar"
	#define STR0005 "Modificar"
	#define STR0006 "Pedidos"
	#define STR0007 "Norma"
	#define STR0008 "Ctd saldo"
	#define STR0009 "Cant. Prev"
	#define STR0010 "Cant. Reab"
	#define STR0011 "Producto"
	#define STR0012 "no registrado en los Datos adicionales del producto (SB5)."
	#define STR0013 "no tiene Zona de almacenamiento informada (SB5)."
	#define STR0014 "no se puede almacenar en la Zona de almacenamiento"
	#define STR0015 "Procesando reabastecimiento..."
	#define STR0016 "No hay servicio de reabastecimiento registrado."
	#define STR0017 "Seleccione por lo menos un ítem para procesar el reabastecimiento."
	#define STR0018 "¡Valor inválido! La cantidad para reabastecimiento de esta ubicación no puede ser superior a "
	#define STR0019 "No fue posible reabastecer toda la cantidad a la ubicación [VAR01] para el producto [VAR02]."
	#define STR0020 "No fue posible reabastecer ninguna cantidad a la ubicación [VAR01] para el producto [VAR02]."
	#define STR0021 "Reabastecimento generado con éxito."
	#define STR0022 "Buscar"
#else
	#ifdef ENGLISH
		#define STR0001 "Refueling"
		#define STR0002 "Process"
		#define STR0003 "Select"
		#define STR0004 "View"
		#define STR0005 "Edit"
		#define STR0006 "Orders"
		#define STR0007 "Rule"
		#define STR0008 "Qty Balance"
		#define STR0009 "Prev Qty"
		#define STR0010 "Reab Qty"
		#define STR0011 "Product"
		#define STR0012 "not registered in the Product Additional Data (SB5)."
		#define STR0013 "does not have indicated Warehouse Zone (SB5)."
		#define STR0014 "cannot be stored in Warehouse Zone"
		#define STR0015 "Processing Resupply..."
		#define STR0016 "No resupply service registered."
		#define STR0017 "Select at least one item to process resupply."
		#define STR0018 "Value not valid! The quantity to resupply this address cannot be above "
		#define STR0019 "Could not resupply entire quantity for address [VAR01] for product [VAR02]."
		#define STR0020 "Could not resupply any quantity for address [VAR01] for product [VAR02]."
		#define STR0021 "Resupply generation successful."
		#define STR0022 "Search"
	#else
		#define STR0001 "Reabastecimento"
		#define STR0002 "Processar"
		#define STR0003 "Selecionar"
		#define STR0004 "Visualizar"
		#define STR0005 "Alterar"
		#define STR0006 "Pedidos"
		#define STR0007 "Norma"
		#define STR0008 "Qtd Saldo"
		#define STR0009 "Qtd Prev"
		#define STR0010 "Qtd Reab"
		#define STR0011 "Produto"
		#define STR0012 "não cadastrado nos Dados Adicionais do Produto (SB5)."
		#define STR0013 "não possui Zona de Armazenagem informada (SB5)."
		#define STR0014 "não pode ser armazenado na Zona de Armazenagem"
		#define STR0015 "Processando Reabastecimento..."
		#define STR0016 "Não existe um serviço de reabastecimento cadastrado."
		#define STR0017 "Selecione ao menos um item para processar o reabastecimento."
		#define STR0018 "Valor inválido! A quantidade para reabastecimento deste endereço não pode ser superior a "
		#define STR0019 "Não foi possível reabastecer toda a quantidade para o endereço [VAR01] para o produto [VAR02]."
		#define STR0020 "Não foi possível reabastecer nenhuma quantidade para o endereço [VAR01] para o produto [VAR02]."
		#define STR0021 "Reabastecimento gerado com sucesso."
		#define STR0022 "Pesquisar"
	#endif
#endif
