#ifdef SPANISH
	#define STR0001 "Monitor de volumen Crossdocking"
	#define STR0002 "Monitor"
	#define STR0003 "Generar pedido"
	#define STR0004 "Volumen Crossdoking"
	#define STR0005 "Montar volumen"
	#define STR0006 "Revertir volumen"
	#define STR0007 "Ítems del volumen"
	#define STR0008 "Revert. Ítem volumen"
	#define STR0009 "Ubicación no tiene ningún volumen montado para generar pedido."
	#define STR0010 "¡Parámetro MV_CODVOL inexistente! Entre en contacto con el administrador del sistema."
	#define STR0011 "Ubicación no tiene saldo disponible en la dirección para montaje de volúmenes."
	#define STR0012 "Generar volumen"
#else
	#ifdef ENGLISH
		#define STR0001 "Crossdocking Volume Monitor"
		#define STR0002 "Monitor"
		#define STR0003 "Create Order"
		#define STR0004 "Crossdocking Volume"
		#define STR0005 "Assemble Volume"
		#define STR0006 "Reverse Volume"
		#define STR0007 "Volume Items"
		#define STR0008 "St. Item Volume"
		#define STR0009 "Address has no volume assembled to create order."
		#define STR0010 "Parameter MV_CODVOL does not exist. Contact System administrator."
		#define STR0011 "Address has no balance available for volume assembly."
		#define STR0012 "Generate Volume"
	#else
		#define STR0001 "Monitor de Volume Crossdocking"
		#define STR0002 "Monitor"
		#define STR0003 "Gerar Pedido"
		#define STR0004 "Volume Crossdoking"
		#define STR0005 "Montar Volume"
		#define STR0006 "Estornar Volume"
		#define STR0007 "Itens do Volume"
		#define STR0008 "Est. Item Volume"
		#define STR0009 "Endereço não possui nenhum volume montado para gerar pedido."
		#define STR0010 "Parâmetro MV_CODVOL inexistente! Avise o Administrador do sistema!"
		#define STR0011 "Endereço não possui saldo disponível para montagem de volumes."
		#define STR0012 "Gerar Volume"
	#endif
#endif
