#ifdef SPANISH
	#define STR0001 "¡Recno inválido!"
	#define STR0002 "¡Lock no se realizó!"
	#define STR0003 "¡Unlock no se realizó!"
	#define STR0004 "¡No se informaron datos para búsqueda!"
	#define STR0005 "La ubicación destino [VAR01] está bloqueada."
	#define STR0006 "Estructura física [VAR01] no registrada. (DC8)"
	#define STR0007 "Producto [VAR01] no tiene secuencia de abastecimiento para Almacén/Estructura [VAR02]/[VAR03]. (DC3)"
	#define STR0008 "Producto [VAR01] no está registrado para la zona de almacenamiento [VAR02]. (SB5,DCH)"
	#define STR0009 "Movimiento de [VAR01] para la dirección [VAR02], excediendo la capacidad de almacenamiento."
	#define STR0010 "Capacidad total de la ubicación de [VAR01]."
	#define STR0011 "Ubicación tiene saldo de [VAR01]."
	#define STR0012 "Entrada prevista de [VAR01]."
	#define STR0013 "Ubicación [VAR01] en uso por otro producto y tipo de control de ubicación no permite mezclar productos (DC3)."
	#define STR0014 "Ubicación [VAR01] en uso por otro lote y tipo de control de ubicación no permite mezclar lotes (DC3)."
	#define STR0015 "Salida prevista de [VAR01]."
	#define STR0016 "Existen actividades por ejecutar que comprometen el saldo del producto [VAR01] en la ubicación [VAR02]."
	#define STR0017 "Saldo del producto [VAR01] en la ubicación [VAR02] es insuficiente para movimiento."
	#define STR0018 "La ubicación destino [VAR01] no se registró."
	#define STR0019 "No se generó actividad para la tarea [VAR01]"
	#define STR0020 "La ubicación origen [VAR01] está bloqueada."
	#define STR0021 "La ubicación origen [VAR01] está con bloqueo de salida."
	#define STR0022 "La ubicación origen [VAR01] está con bloqueo de inventario."
	#define STR0023 "Ubicación destino [VAR01] está con bloqueo de entrada."
	#define STR0024 "Ubicación destino [VAR01] está con bloqueo de inventario."
	#define STR0025 "Ubicación [VAR01] está bloqueada para inventario."
	#define STR0026 "No existe saldo en la ubicación: [VAR01] para el producto: [VAR02]"
	#define STR0027 "Parámetros no informados."
	#define STR0028 "SIGAWMS - OS [VAR01] - Producto: [VAR02] - Id. OS: [VAR03] - Id. Movimiento: [VAR04] - Id. Operación: [VAR05]."
	#define STR0029 "Verifique las excepciones de las ubicaciones origen ([VAR01])"
	#define STR0030 "Verifique las excepciones de las ubicaciones destino ([VAR01])"
	#define STR0031 "No se encontró el saldo por ubicación del unitizador [VAR01]."
	#define STR0032 "Norma de la ubicación de destino no se registró."
	#define STR0033 "La dirección no debe recibir el saldo del movimiento. Motivo:"
	#define STR0034 "No se encontró el saldo de los productos recibidos en el unitizador [VAR01]."
	#define STR0035 "Problema al actualizar el ID origen para las relaciones del movimiento."
	#define STR0036 "Exceso del peso máximo compatible con la dirección."
	#define STR0037 "Exceso del volumen máximo compatible con la dirección."
	#define STR0038 "No se encontró el saldo en stock con la información:"
	#define STR0039 "Ubicación: [VAR01]"
	#define STR0040 "Producto: [VAR01]"
	#define STR0041 "Lote: [VAR01]"
	#define STR0042 "Sublote: [VAR01]"
	#define STR0043 "Unitizador [VAR01]"
	#define STR0044 "Problema al actualizar el ID movimiento para las relaciones del movimiento."
	#define STR0045 "Existen reservas y/o reservas que comprometen el saldo del producto [VAR01] en el almacén [VAR02] y dirección [VAR03]."
	#define STR0046 "¡Ubicación [VAR01] exclusiva para el producto [VAR02]!"
	#define STR0047 "Producto(s)"
	#define STR0048 "y otros"
	#define STR0049 "no tiene secuencia de abastecimiento para la estructura de la dirección informada ([VAR01])."
	#define STR0050 "Producto [VAR01] no tiene secuencia de abastecimiento para la estructura de la dirección informada ([VAR02])."
#else
	#ifdef ENGLISH
		#define STR0001 "Recno not valid!"
		#define STR0002 "Lock not executed!"
		#define STR0003 "UnLock not executed!"
		#define STR0004 "Search data not entered!"
		#define STR0005 "Destination address [VAR01] blocked."
		#define STR0006 "Physical structure [VAR01] not registered. (DC8)"
		#define STR0007 "Product [VAR01] has no supply sequence for Warehouse/Structure [VAR02]/[VAR03]. (DC3)"
		#define STR0008 "Product [VAR01] not registered for storage zone [VAR02]. (SB5,DCH)"
		#define STR0009 "Movement of [VAR01] for address [VAR02] exceeding storage capacity."
		#define STR0010 "Total capacity of address of [VAR01]."
		#define STR0011 "Address has balance of [VAR01]."
		#define STR0012 "Inflow of [VAR01] expected."
		#define STR0013 "Address [VAR01] in use by another product and addressing type does not allow mixing products (DC3)."
		#define STR0014 "Address [VAR01] in use by another batch and addressing type does not allow mixing batches (DC3)."
		#define STR0015 "Outflow of [VAR01] expected."
		#define STR0016 "There are activities to run that compromise product balance [VAR01] in address [VAR02]."
		#define STR0017 "Balance of product [VAR01] in address [VAR02] not sufficient for transaction."
		#define STR0018 "Destination address [VAR01] not registered."
		#define STR0019 "No activity generated for task [VAR01]"
		#define STR0020 "Origin address [VAR01] blocked."
		#define STR0021 "Source address [VAR01] has outflow block."
		#define STR0022 "Source address [VAR01] has inventory block."
		#define STR0023 "Target address [VAR01] has inflow block."
		#define STR0024 "Target address [VAR01] has inventory block."
		#define STR0025 "Address [VAR01] blocked for inventory."
		#define STR0026 "No balance in address: [VAR01] for product: [VAR02]"
		#define STR0027 "Parameters not entered."
		#define STR0028 "SIGAWMS - SO [VAR01] - Product: [VAR02] - ID SO: [VAR03] - Transaction ID: [VAR04] - Operation ID: [VAR05]."
		#define STR0029 "Check exception of the origin addresses ([VAR01])"
		#define STR0030 "Check exception of the destination addresses ([VAR01])"
		#define STR0031 "No balance found for unitizer address [VAR01]."
		#define STR0032 "Target address norm not registered!"
		#define STR0033 "The address cannot receive the balance of the movement. Reason:"
		#define STR0034 "No balance of products received in unitizer [VAR01]."
		#define STR0035 "Problem when updating the origin ID for movement relationships"
		#define STR0036 "Maximum weight supported of the address exceeded."
		#define STR0037 "Maximum weight supported of the address exceeded."
		#define STR0038 "Could not find stock balance with the information:"
		#define STR0039 "Address: [VAR01]"
		#define STR0040 "Product: [VAR01]"
		#define STR0041 "Lot: [VAR01]"
		#define STR0042 "Sub-lot [VAR01]"
		#define STR0043 "Unitizer: [VAR01]"
		#define STR0044 "Problem when updating the ID movement for relationships of the movement."
		#define STR0045 " Reservations and/or allocations compromising balance of product [VAR01] in the warehouse [VAR02] and address [VAR03]."
		#define STR0046 "Address [VAR01] exclusive for product [VAR02]!"
		#define STR0047 "Products"
		#define STR0048 "and others"
		#define STR0049 "do not have fueling sequence for the entered address structure ([VAR01])."
		#define STR0050 "Product [VAR01] does not have fueling sequence for entered address structure ([VAR02])."
	#else
		#define STR0001 "Recno invalido!"
		#define STR0002 "Lock não foi efetuado!"
		#define STR0003 "UnLock não foi efetuado!"
		#define STR0004 "Dados para busca não foram informados!"
		#define STR0005 "Endereço destino [VAR01] está bloqueado."
		#define STR0006 "Estrutura física [VAR01] não cadastrada. (DC8)"
		#define STR0007 "Produto [VAR01] não possui sequência de abastecimento para Armazém/Estrutura [VAR02]/[VAR03]. (DC3)"
		#define STR0008 "Produto [VAR01] não está cadastrado para a zona armazenagem [VAR02]. (SB5,DCH)"
		#define STR0009 "Movimentação de [VAR01] para o endereço [VAR02] excedendo a capacidade de armazenagem."
		#define STR0010 "Capacidade total do endereço de [VAR01]."
		#define STR0011 "Endereço possui saldo de [VAR01]."
		#define STR0012 "Entrada prevista de [VAR01]."
		#define STR0013 "Endereço [VAR01] em uso por outro produto e tipo de endereçamento não permitir misturar produtos (DC3)."
		#define STR0014 "Endereço [VAR01] em uso por outro lote e tipo de endereçamento não permite misturar lotes (DC3)."
		#define STR0015 "Saída prevista de [VAR01]."
		#define STR0016 "Existem atividades a executar que comprometem o saldo do produto [VAR01] no endereço [VAR02]."
		#define STR0017 "Saldo do produto [VAR01] no endereço [VAR02] insuficiente para movimentação."
		#define STR0018 "Endereço destino [VAR01] não cadastrado."
		#define STR0019 "Não foi gerado atividade para a tarefa [VAR01]"
		#define STR0020 "O endereço origem [VAR01] está bloqueado."
		#define STR0021 "O endereço origem [VAR01] está com bloqueio de saída."
		#define STR0022 "O endereço origem [VAR01] está com bloqueio de inventário."
		#define STR0023 "Endereço destino [VAR01] está com bloqueio de entrada."
		#define STR0024 "Endereço destino [VAR01] está com bloqueio de inventário."
		#define STR0025 "Endereço [VAR01] está bloqueado para inventário."
		#define STR0026 "Não existe saldo no endereço: [VAR01] para o produto: [VAR02]"
		#define STR0027 "Parâmetros não informados."
		#define STR0028 "SIGAWMS - OS [VAR01] - Produto: [VAR02] - Id. OS: [VAR03] - Id. Movimento: [VAR04] - Id. Operação: [VAR05]."
		#define STR0029 "Verifique as excessões dos endereços origem ([VAR01])"
		#define STR0030 "Verifique as excessões dos endereços destido ([VAR01])"
		#define STR0031 "Não foi encontrado o saldo por endereço do unitizador [VAR01]."
		#define STR0032 "Norma do endereço destino não cadastrada!"
		#define STR0033 "O endereço não pode receber o saldo do movimento. Motivo:"
		#define STR0034 "Não foi encontrado o saldo dos produtos recebidos no unitizador [VAR01]."
		#define STR0035 "Problema ao atualizar o ID origem para os relacionamentos do movimento."
		#define STR0036 "Estouro do peso máximo suportado do endereço."
		#define STR0037 "Estouro do volume máximo suportado do endereço."
		#define STR0038 "Não foi encontrado o saldo em estoque com as informações:"
		#define STR0039 "Endereço: [VAR01]"
		#define STR0040 "Produto: [VAR01]"
		#define STR0041 "Lote: [VAR01]"
		#define STR0042 "Sub-lote: [VAR01]"
		#define STR0043 "Unitizador: [VAR01]"
		#define STR0044 "Problema ao atualizar o ID movimento para os relacionamentos do movimento."
		#define STR0045 " Existem reservas e/ou empenhos que comprometem o saldo do produto [VAR01] no armazém [VAR02] e endereço [VAR03]."
		#define STR0046 "Endereço [VAR01] exclusivo para o produto [VAR02]!"
		#define STR0047 "Produto(s) "
		#define STR0048 " e outros"
		#define STR0049 " não possui(em) sequência de abastecimento para a estrutura do endereço informado ([VAR01])."
		#define STR0050 "Produto [VAR01] não possui sequência de abastecimento para a estrutura do endereço informado ([VAR02])."
	#endif
#endif
