#ifdef SPANISH
	#define STR0001 "¡No se informaron datos para búsqueda!"
	#define STR0002 "¡Datos no encontrados!"
	#define STR0003 "¡Clave duplicada!"
	#define STR0004 "Carga [VAR01] registrada en el embarque de expedición [VAR02]."
	#define STR0005 "Pedido [VAR01] registrado en el embarque de expedición [VAR02]."
	#define STR0006 "Lista de embarque [VAR01] registrado en el embarque de expedición [VAR02]."
	#define STR0007 "Factura [VAR01] serie [VAR02] registrada en el embarque de expedición [VAR03]."
	#define STR0008 "Carga [VAR01] no se encuentra en el almacén [VAR02] ni ubicación [VAR03]."
	#define STR0009 "Pedido [VAR01] no se encuentra en el almacén [VAR02] ni ubicación [VAR03]."
	#define STR0010 "Lista de embarque [VAR01] no se encuentra en el almacén [VAR02] ni ubicación [VAR03]."
	#define STR0011 "Factura [VAR01] serie [VAR02] no se encuentra en el almacén [VAR03] ni ubicación [VAR04]."
	#define STR0012 "Carga [VAR01] no tiene pedidos con productos liberados para facturación."
	#define STR0013 "Pedido [VAR01] no tiene productos liberados para facturación."
	#define STR0014 "Lista de embarque [VAR01] no tiene volúmenes liberados para facturación."
	#define STR0015 "Factura [VAR01] serie [VAR02] no generada."
	#define STR0016 "Cantidad informada superior a la cantidad pendiente por embarcarse."
	#define STR0017 "¡Producto pertenece a un volumen, informe el volumen!"
	#define STR0018 "Producto no registrado en el embarque de expedición [VAR01]"
	#define STR0019 "Volumen embarcado en el embarque de expedición [VAR01]"
	#define STR0020 "Volumen [VAR01] no registrado para el embarque de expedición [VAR02]"
	#define STR0021 "Cantidad informada superior a la cantidad embarcada."
	#define STR0022 "Información no encontrada en el embarque de expedición [VAR01]"
	#define STR0023 "Ítem sin cantidad para reversión."
#else
	#ifdef ENGLISH
		#define STR0001 "Search data not entered."
		#define STR0002 "Data not found!"
		#define STR0003 "Duplicate key!"
		#define STR0004 "Cargo [VAR01] already registered in the dispatch shipping [VAR02]."
		#define STR0005 "Order [VAR01] already registered in the dispatch shipping [VAR02]."
		#define STR0006 "Shipping packing list [VAR01] already registered in the dispatch shipping [VAR02]."
		#define STR0007 "Invoice [VAR01] series [VAR02] already registered in the dispatch shipping [VAR03]."
		#define STR0008 "Load [VAR01] not found in warehouse [VAR02] and address [VAR03]."
		#define STR0009 "Order [VAR01] not found in warehouse [VAR02] and address [VAR03]."
		#define STR0010 "Shipment Packing List [VAR01] not found in warehouse [VAR02] and address [VAR03]."
		#define STR0011 "Invoice [VAR01] serial [VAR02] not found in warehouse [VAR03] and address [VAR04]."
		#define STR0012 "Cargo [VAR01] does not have orders with products released for invoicing."
		#define STR0013 "Order [VAR01] does not have products released for invoicing."
		#define STR0014 "Shipping packing list [VAR01] does not have volumes released for invoicing."
		#define STR0015 "Invoice [VAR01] series [VAR02] not generated."
		#define STR0016 "Quantity informed greater than the pending quantity to be shipped."
		#define STR0017 "Product belongs to a volume, enter the volume!"
		#define STR0018 "Product not registered in the dispatch shipping [VAR01]"
		#define STR0019 "Volume already shipped in the dispatch shipping [VAR01]"
		#define STR0020 "Volume [VAR01] not registered in the dispatch shipping [VAR02]."
		#define STR0021 "Quantity informed is greater than quantity available."
		#define STR0022 "Information not found in the shipment [VAR01]"
		#define STR0023 "Item without quantity to reverse."
	#else
		#define STR0001 "Dados para busca não foram informados!"
		#define STR0002 "Dados não encontrados!"
		#define STR0003 "Chave duplicada!"
		#define STR0004 "Carga [VAR01] já cadastrada no embarque de expedição [VAR02]."
		#define STR0005 "Pedido [VAR01] já cadastrado no embarque de expedição [VAR02]."
		#define STR0006 "Romaneio de embarque [VAR01] já cadastrado no embarque de expedição [VAR02]."
		#define STR0007 "Nota-Fiscal [VAR01] série [VAR02] já cadastrada no embarque de expedição [VAR03]."
		#define STR0008 "Carga [VAR01] não se encontra no armazém [VAR02] e endereço [VAR03]."
		#define STR0009 "Pedido [VAR01] não se encontra no armazém [VAR02] e endereço [VAR03]."
		#define STR0010 "Romaneio de embarque [VAR01] não se encontra no armazém [VAR02] e endereço [VAR03]."
		#define STR0011 "Nota-Fiscal [VAR01] série [VAR02] não se encontra no armazém [VAR03] e endereço [VAR04]."
		#define STR0012 "Carga [VAR01] não possui pedidos com produtos liberados para faturamento."
		#define STR0013 "Pedido [VAR01] não possui produtos liberados para faturamento."
		#define STR0014 "Romaneio de embarque [VAR01] não possui volumes liberados para faturamento."
		#define STR0015 "Nota-Fiscal [VAR01] série [VAR02] não gerada."
		#define STR0016 "Quantidade informada superior a quantidade pendente a ser embarcada."
		#define STR0017 "Produto pertence a um volume, informe o volume!"
		#define STR0018 "Produto não cadastrado no embarque de expedição [VAR01]"
		#define STR0019 "Volume já embarcado no embarque de expedição [VAR01]"
		#define STR0020 "Volume [VAR01] não cadastrado para o embarque de expedição [VAR02]"
		#define STR0021 "Quantidade informada superior a quantidade embarcada."
		#define STR0022 "Informações não localizadas no embarque de expedição [VAR01]"
		#define STR0023 "Item sem quantidade para estorno."
	#endif
#endif
