#ifdef SPANISH
	#define STR0001 "Seleccione"
	#define STR0002 "Doc. Entrada"
	#define STR0003 "Mov. Interno"
	#define STR0004 "Apunt. Produccion"
	#define STR0005 "Reversión"
	#define STR0006 "Montaje Unitizador"
	#define STR0007 "Almacén"
	#define STR0008 "Ubicación"
	#define STR0009 "¿Confirma la salida?"
	#define STR0010 "Ítems Unitiz."
	#define STR0011 "Unitizador"
	#define STR0012 "Informe el producto"
	#define STR0013 "Lote"
	#define STR0014 "Sublote"
	#define STR0015 "Cant."
	#define STR0016 "Informe el Unitiz."
	#define STR0017 "Tipo Unitiz."
	#define STR0018 "El unitizador no tiene ítems."
	#define STR0019 "Reversión Mnt. Unitiz"
	#define STR0020 "¡Atención!"
	#define STR0021 "Seleccione el tipo de reversión"
	#define STR0022 "Unitiz. Completo"
	#define STR0023 "Producto Unitiz."
	#define STR0024 "¡Almacén inválido!"
	#define STR0025 "¡Almacén no controla unitización!"
	#define STR0026 "¡Ubicación no válida!"
	#define STR0027 "¡No existe demanda de unitización 'Pendiente' o 'En Marcha' para almacén [VAR01] y ubicación [VAR02]!"
	#define STR0028 "¡Etiqueta no válida!"
	#define STR0029 "Producto [VAR01] no tiene saldo disponible para montaje del unitizador."
	#define STR0030 "Producto [VAR01] no tiene cantidad en el unitizador para reversión."
	#define STR0031 "Producto/Lote [VAR01]/[VAR02] no tiene saldo disponible para montaje del unitizador."
	#define STR0032 "Producto/Lote [VAR01]/[VAR02] no tiene cantidad en el unitizador para reversión."
	#define STR0033 "Producto/Rastro [VAR01]/[VAR02] no tiene saldo disponible para montaje del unitizador."
	#define STR0034 "Produto/Rastro [VAR01]/[VAR02] no tiene cantidad en el unitizador para reversión."
	#define STR0035 "Ítems Unitizador"
	#define STR0036 "Procesando"
	#define STR0037 "¿Confirma la ubicación del unitizador [VAR01]?"
	#define STR0038 "El unitizador no tiene ítems para la ubicación."
	#define STR0039 "Generar OS Ubic."
	#define STR0040 "La OS de este unitizador se generó."
	#define STR0041 "Mont/Desmont"
	#define STR0042 "Calidad"
#else
	#ifdef ENGLISH
		#define STR0001 "Select"
		#define STR0002 "Inflow Doc"
		#define STR0003 "Internal Trans"
		#define STR0004 "Production Punches"
		#define STR0005 "Reversal"
		#define STR0006 "Unitizer Assemble"
		#define STR0007 "Warehouse"
		#define STR0008 "Address"
		#define STR0009 "Confirm outflow?"
		#define STR0010 "Unitiz. Items"
		#define STR0011 "Unitizer"
		#define STR0012 "Enter the product"
		#define STR0013 "Batch"
		#define STR0014 "Sub-batch"
		#define STR0015 "Qty."
		#define STR0016 "Enter Unitiz."
		#define STR0017 "Unitiz. Type"
		#define STR0018 "Unitizer has no items."
		#define STR0019 "Unitiz. Assemble Reversal"
		#define STR0020 "Attention!"
		#define STR0021 "Choose type of reversal"
		#define STR0022 "Complete Unitiz."
		#define STR0023 "Unitiz. Product"
		#define STR0024 "Warehouse not valid!"
		#define STR0025 "Warehouse does not control unitizer!"
		#define STR0026 "Address not valid!"
		#define STR0027 "No Pending Demand of Unitization or In Progress for warehouse [VAR01] and address [VAR02]!"
		#define STR0028 "Invalid label!"
		#define STR0029 "Product [VAR01] has no balance available for unitizer assembly."
		#define STR0030 "Product [VAR01] has no quantity in the unitizer for reversal."
		#define STR0031 "Product/Batch [VAR01]/[VAR02] has no balance available for unitizer assembly."
		#define STR0032 "Product/Batch [VAR01]/[VAR02] has no quantity in the unitizer for reversal."
		#define STR0033 "Product/Track [VAR01]/[VAR02] has no balance available for unitizer assembly."
		#define STR0034 "Product/Track [VAR01]/[VAR02] has no quantity in the unitizer for reversal."
		#define STR0035 "Unitizer Items"
		#define STR0036 "Processing"
		#define STR0037 "Confirm unitizer addressing [VAR01]?"
		#define STR0038 "The unitizer does not have items for addressing."
		#define STR0039 "Generate Address SO"
		#define STR0040 "The SO of this unitizer has already been generated."
		#define STR0041 "Assembly/Disassemble"
		#define STR0042 "Quality"
	#else
		#define STR0001 "Selecione"
		#define STR0002 "Doc. Entrada"
		#define STR0003 "Mov. Interna"
		#define STR0004 "Apont. Producao"
		#define STR0005 "Estorno"
		#define STR0006 "Montagem Unitizador"
		#define STR0007 "Armazem"
		#define STR0008 "Endereco"
		#define STR0009 "Confirma a saida?"
		#define STR0010 "Itens Unitiz."
		#define STR0011 "Unitizador"
		#define STR0012 "Informe o Produto"
		#define STR0013 "Lote"
		#define STR0014 "Sub-Lote"
		#define STR0015 "Qtde"
		#define STR0016 "Informe o Unitiz."
		#define STR0017 "Tipo Unitiz."
		#define STR0018 "O unitizador nao possui itens."
		#define STR0019 "Estorno Mnt. Unitiz"
		#define STR0020 "Atencao!"
		#define STR0021 "Escolha o tipo de estorno"
		#define STR0022 "Unitiz. Completo"
		#define STR0023 "Produto Unitiz."
		#define STR0024 "Armazem invalido!"
		#define STR0025 "Armazem nao controla unitizacao!"
		#define STR0026 "Endereco invalido!"
		#define STR0027 "Nao existe Demanda de Unitizacao 'Pendente' ou 'Em Andamento' para armazem [VAR01] e endereco [VAR02]!"
		#define STR0028 "Etiqueta invalida!"
		#define STR0029 "Produto [VAR01] nao possui saldo disponivel para montagem de unitizador."
		#define STR0030 "Produto [VAR01] nao possui quantidade no unitizador para estorno."
		#define STR0031 "Produto/Lote [VAR01]/[VAR02] nao possui saldo disponivel para montagem de unitizador."
		#define STR0032 "Produto/Lote [VAR01]/[VAR02] nao possui quantidade no unitizador para estorno."
		#define STR0033 "Produto/Rastro [VAR01]/[VAR02] nao possui saldo disponivel para montagem de unitizador."
		#define STR0034 "Produto/Rastro [VAR01]/[VAR02] nao possui quantidade no unitizador para estorno."
		#define STR0035 "Itens Unitizador"
		#define STR0036 "Processando"
		#define STR0037 "Confirma enderecamento do unitizador [VAR01]?"
		#define STR0038 "O unitizador nao possui itens para o enderecamento."
		#define STR0039 "Gerar OS End."
		#define STR0040 "A OS deste unitizador já foi gerada."
		#define STR0041 "Mont/Desmont"
		#define STR0042 "Qualidade"
	#endif
#endif
