#ifdef SPANISH
	#define STR0001 "Parámetros del WMS"
	#define STR0002 "Integración logística"
	#define STR0003 "S=Sí"
	#define STR0004 "N=No"
	#define STR0005 "Fecha del Protheus diferente de la fecha del sistema"
	#define STR0006 "Reabastecimiento hasta completar el picking"
	#define STR0007 "Considera múltiples ubicaciones de picking"
	#define STR0008 "Modifica norma para total restante de la reserva"
	#define STR0009 "Refresh del monitor de servicios (en segundos)"
	#define STR0010 "Reabastecimiento de ubicaciones de picking totalmente vacíos"
	#define STR0011 "Prioriza en la reserva de mercaderías"
	#define STR0012 "E=Ubicación más próxima"
	#define STR0013 "V=Fecha de validez más próxima"
	#define STR0014 "Habilita validaciones en la reversión de servicio WMS en la rutina Ejec. de servicios"
	#define STR0015 "Habilita validación del movimiento de WMS en la rutina de transferencia"
	#define STR0016 "Nueva reversión del WMS por el IDDCF"
	#define STR0017 "Montaje de volumen"
	#define STR0018 "Número secuencial de las etiquetas de volumen"
	#define STR0019 "¿Utiliza verificación en la expedición?"
	#define STR0020 "1=Utiliza y bloquea facturación hasta concluir"
	#define STR0021 "2=Utiliza y permite facturación antes de la conclusión"
	#define STR0022 "3=No utiliza"
	#define STR0023 "Campos de la tabla SB5 que el Wizard de complemento productos debe considerar"
	#define STR0024 "Ejecución de servicios RDMAKE vía radiofrecuencia debe modificar el estatus del servicio"
	#define STR0025 "Bloquea solo items con divergencia"
	#define STR0026 "Reinicio automático de las tareas interrumpidas"
	#define STR0028 "Permite seleccionar múltiples tareas"
	#define STR0029 "0=Ninguno"
	#define STR0030 "1=Reserva"
	#define STR0031 "2=Ubicar"
	#define STR0032 "3=Ambos"
	#define STR0033 "Método de descarga cuando utiliza múltiples tareas"
	#define STR0034 "0=Dic.Destino+Producto+Lote+Sublote"
	#define STR0035 "1=Inverso de carga, con productos, lotes con misma ubicación de destino"
	#define STR0036 "Nivel final de ubicación que se muestra en las rutinas de RF"
	#define STR0037 "Nivel inicial de ubicación que se muestra en las rutinas de RF"
	#define STR0038 "Número de conteos que el verificador puede ejecutar"
	#define STR0039 "1=Sí"
	#define STR0040 "2=No"
	#define STR0041 "Utiliza radiofrecuencia"
	#define STR0042 "Tiempo en milisegundos que el sistema quedará en pausa hibernando"
	#define STR0043 "Tiempo en milisegundos que el sistema quedará en pausa activa"
	#define STR0044 "Informa ubicación al acceder a la opción de Convocación RF"
	#define STR0045 "Activa tratamiento de hibernación"
	#define STR0046 "Solicita confirmación del lote en las operaciones con RF"
	#define STR0047 "Unidad de medida utilizada"
	#define STR0048 "1=1a.UM"
	#define STR0049 "2=2a.UM"
	#define STR0050 "3=Unitizador"
	#define STR0051 "4=UMI"
	#define STR0052 "Directorio de los documentos/logs"
	#define STR0053 "Actividad por ejecutar"
	#define STR0054 "Actividad automática"
	#define STR0055 "Actividad ejecutada"
	#define STR0056 "Actividad interrumpida"
	#define STR0057 "Actividad manual"
	#define STR0058 "Actividad con problemas"
	#define STR0059 "Muestra descripción del producto en el recolector RF para los procesos de verificación"
	#define STR0060 "Cantidad de tolerancia para separación por mayor"
	#define STR0061 "Finaliza separación/reabastecimiento"
	#define STR0062 "Permite modificar número de lote en la separación RF"
	#define STR0063 "1=No"
	#define STR0064 "2=Sí"
	#define STR0065 "3=Confirmación"
	#define STR0066 "Secuencia para determinar la secuencia de ejecución de los servicios"
	#define STR0067 "Regla para componer la prioridad de convocación"
	#define STR0068 "Determina la orden de separación solo despues de la conclusión de la carga/documento"
	#define STR0069 "Tipo de convocación para radiofrecuencia"
	#define STR0070 "1=Actividad"
	#define STR0071 "2=Tarea/Producto"
	#define STR0072 "3=Tarea/Completa"
	#define STR0073 "Local (Depósito) Control de calidad"
	#define STR0074 "Vínculo entre depósito y ubicación"
	#define STR0075 "Número documento transferencia automática"
	#define STR0076 "Activa la verificación de movimientos para productos con rastro y/o ubicación"
	#define STR0077 "Agrupa ítems del mismo lote y sublote"
	#define STR0078 "Realiza la nueva liberación del pedido para la última ubicación"
	#define STR0079 "Permite saldo negativo"
	#define STR0080 "Tolerancia para cálculos con la 1 UM"
	#define STR0081 "Fecha último cierre del stock"
	#define STR0082 "Código de la formula estándar utilizada para completar los lotes"
	#define STR0083 "Utiliza concepto de lote único"
	#define STR0084 "Utiliza Lotes/Sublotes con la fecha de validez vencida"
	#define STR0085 "Utiliza trazabilidad de los lotes de producción"
	#define STR0086 "Tipo de control de ubicación para WMS"
	#define STR0087 "3=Tal vez"
	#define STR0088 "Evalua capacidad de las ubicaciones"
	#define STR0089 "Descripción de ubicación para ubicaciones generadas"
	#define STR0090 "Genera bloqueo de stock para productos que controlan rastro o ubicación"
	#define STR0091 "Productos pueden usar control de ubicación física"
	#define STR0092 "Al ocurrir una reversión de movimiento con control de ubicación se debe"
	#define STR0093 "0=Redistribuir"
	#define STR0094 "1=Ubicación original"
	#define STR0095 "2=Preguntar"
	#define STR0096 "Realiza procesos WMS considerando la carga"
	#define STR0097 "1=Procesos por carga"
	#define STR0098 "2=Procesos por documento/serie"
	#define STR0099 "Utiliza carga"
	#define STR0100 "Tipo de control de ubicación en bloque fraccionado"
	#define STR0101 "1=Para completar ubicaciones completamente llenas"
	#define STR0102 "2=Solo si el saldo mas cantidad es menor que la capacidad"
	#define STR0103 "Direcciones parcialmente llenas deben informarse totalmente"
	#define STR0104 "Mezcla Lote/Sublote en el nivel"
	#define STR0105 "Nivel de Conf. Bloque que se considerará en el control de ubicación"
	#define STR0106 "Nivel para mezcla Lote/Sub/Lote"
	#define STR0107 "Parámetros"
	#define STR0108 "Parámetros WMS"
	#define STR0109 "WMS General"
	#define STR0110 "RF (Radiofrecuencia)"
	#define STR0111 "Control de ubicación"
	#define STR0112 "En bloque"
	#define STR0113 "Control de lote"
	#define STR0114 "Stock"
	#define STR0115 "Facturación"
	#define STR0116 "Carga"
	#define STR0117 "Calidad"
	#define STR0118 "Log"
	#define STR0119 "Integración logística"
	#define STR0120 "Realiza la verificación WMS con RF de forma que bloquea solo ítems con divergencia"
	#define STR0121 "1=Inverso de la carga"
	#define STR0123 "&Grabar"
	#define STR0124 "Grabar parámetros"
	#define STR0125 "&Cerrar"
	#define STR0126 "Cerrar"
	#define STR0127 ".T.=Sí"
	#define STR0128 ".F.=No"
	#define STR0129 "4=Uso y liberación debe ser Manual después de concluir la Verificación"
	#define STR0130 "1=Ubicaciones totalmente vacías"
	#define STR0131 "2=Ubicaciones parcialmente llenas"
	#define STR0132 "3=Parcialmente llenas sin mezclar lotes"
	#define STR0133 "4=Comparte Ubicac. Productos diferentes"
	#define STR0134 "¿Elabora volumen al final de la separación?"
	#define STR0135 "Realiza automáticamente la distribución producto con pedido compra"
	#define STR0136 "Bloquea saldo hasta la finalización del control de ubicación"
	#define STR0137 "Muestra la descripción detallada de la ubicación en las pantallas del recolector RF"
	#define STR0138 "Almacén de falta de verificación de recepción"
	#define STR0139 "Almacén de exceso de verificación de recepción"
	#define STR0140 "Ubicación de falta de verificación de recepción"
	#define STR0141 "Tipo de movimiento de entrada en el almacén de exceso"
	#define STR0142 "Servicio para movimientos de entrada en el almacén de exceso"
	#define STR0143 "Elabora volumen de movimientos agrupados en la elaboración durante la separación"
	#define STR0144 "Secuencial de lista de embarque"
	#define STR0145 "Restringir lista de embarque por cliente y tienda"
	#define STR0146 "Utiliza secuencia automática en la lista de embarque "
	#define STR0147 "Solicitar función del Recurso en la Convocatoria"
	#define STR0148 "Agrupación de la carga"
	#define STR0149 "0=No agrupa"
	#define STR0150 "1=Agrupa por carga"
	#define STR0151 "2=Agrupa por Carga/Cliente"
	#define STR0152 "Agrupación"
	#define STR0153 "Actividades"
	#define STR0154 "Integración WMS"
	#define STR0155 "Tipo de movimiento de retirada del almacén actual"
	#define STR0156 "Servicio para movimiento de retirada del almacén actual"
	#define STR0157 "Tipo de movimiento de entrada en el almacén de falta"
	#define STR0158 "Servicio para movimiento de entrada en el almacén de falta"
	#define STR0159 "Ubicación de exceso de la verificación de de recepción"
	#define STR0160 "0=No utiliza"
	#define STR0161 "1=Prorrateo directo"
	#define STR0162 "2=Prorrateo proporcional"
	#define STR0163 "3=Prorrateo unidad + Proporcional"
	#define STR0164 "4=Prorrateo directo pedido de venta + Proporcional plan de distribución"
	#define STR0165 "0=No valida"
	#define STR0166 "1=Valida Ant Facturación"
	#define STR0167 "2=Valida Post Facturación"
	#define STR0168 "3- Valida ambos"
	#define STR0169 "Tipo de movimiento producción para montaje WMS"
	#define STR0170 "Recepción"
	#define STR0171 "Tipo de movimiento de requisición para producción en el montaje WMS"
	#define STR0172 "Bloquea en la lista de embarque los volúmenes ubicados"
	#define STR0173 "Tipo de movimiento de baja de solicitud en la separación WMS"
	#define STR0174 "Tipo estándar al finalizar una ocurrencia"
	#define STR0175 "1=Documento de entrada"
	#define STR0176 "2=Documento de salida"
	#define STR0177 "3=Movimiento interno"
	#define STR0178 "Regresa siempre a la primera función del operador en la búsqueda de las actividades pendientes"
	#define STR0179 "Utiliza job en las integraciones de servicios con ejecución automática"
	#define STR0180 "No efectúa convocación si no encuentra regla de convocación definida"
	#define STR0181 "Visualizar búsqueda de saldo para el alcance"
	#define STR0182 "Visualizar búsqueda de ubicaciones para el almacenamiento"
	#define STR0183 "Mostrar los mensajes de resuministro"
	#define STR0184 "Tipo de movimiento de requisición para pedidos generados automáticamente a partir de volúmenes crossdocking"
	#define STR0185 "TES de salida para pedidos generados automáticamente a partir de volúmenes crossdocking"
	#define STR0186 "Ejecución automática solamente para pedido completo"
	#define STR0187 "Permite generar embarque de expedición vía recolector"
	#define STR0188 "Permite suministro de la ubicación picking con estructuras picking de cantidad mínima de alcance mayor"
	#define STR0189 "Muestra descripción del producto en el recolector RF para los procesos de movimiento"
	#define STR0190 "Límite de ubicaciones de picking ocupadas"
	#define STR0191 "Bloquear verificación de productos no informados en la factura previa o documento de entrada."
	#define STR0192 "Solicitar la fecha de validez del lote en la verificación si no se encuentra previamente informada."
#else
	#ifdef ENGLISH
		#define STR0001 "WMS Parameters"
		#define STR0002 "Logistic Integration"
		#define STR0003 "S=Yes"
		#define STR0004 "N=No"
		#define STR0005 "Protheus Date different than system date"
		#define STR0006 "Resupply until complete picking"
		#define STR0007 "Consider multiple Picking addresses"
		#define STR0008 "Changes rule for pick up total remaining "
		#define STR0009 "Services monitor refresh (in seconds)"
		#define STR0010 "Resupply picking addresses totally blank"
		#define STR0011 "Prioritize in the goods pick up"
		#define STR0012 "E=Next address"
		#define STR0013 "V=Next validity date"
		#define STR0014 "Enables validation in the WMS service reversal in the Services run routine"
		#define STR0015 "Enables the WMS transaction validation in the transfer routine"
		#define STR0016 "New reversal of WMS by IDDCF"
		#define STR0017 "Volume Assembly"
		#define STR0018 "Sequential number of the volume labels"
		#define STR0019 "Use conference in shipping?"
		#define STR0020 "1=Use and block invoicing until concluding"
		#define STR0021 "2=Use and allow invoicing before conclusion"
		#define STR0022 "3=Does not use"
		#define STR0023 "Fields of SB5 table that must be considered by Products Complement Wizard"
		#define STR0024 "Execution of RDMAKE services via frequency radio must change the service status"
		#define STR0025 "Blocks only items with divergence"
		#define STR0026 "Resume interrupted tasks automatically"
		#define STR0028 "Enable selecting multiple tasks"
		#define STR0029 "0=None"
		#define STR0030 "1=Pick up"
		#define STR0031 "2=Address"
		#define STR0032 "3=Both"
		#define STR0033 "Unloading method when using multiple tasks"
		#define STR0034 "0=Add.Destin+Product+Lot+SubLot"
		#define STR0035 "1=Load reverse, with products, lots with the same destination address"
		#define STR0036 "Address End Level to be display in RF routines"
		#define STR0037 "Address Start Level to be display in RF routines"
		#define STR0038 "Counting numbers the conferencing can perform"
		#define STR0039 "1=Yes"
		#define STR0040 "2=No"
		#define STR0041 "Uses Frequency Radio"
		#define STR0042 "Time in milliseconds the system will be paused, hibernating"
		#define STR0043 "Time in milliseconds the system will be paused, on"
		#define STR0044 "Inform location when accessing RF Call option"
		#define STR0045 "Activates Hibernation Treatment"
		#define STR0046 "Request batch confirmation in RF operations"
		#define STR0047 "Unit of measurement used"
		#define STR0048 "1=1st.UM"
		#define STR0049 "2=2nd.UM"
		#define STR0050 "3=Unitizer"
		#define STR0051 "4=UMI"
		#define STR0052 "Documents/logs directory"
		#define STR0053 "Activity to be run"
		#define STR0054 "Automatic Activity"
		#define STR0055 "Run Activity"
		#define STR0056 "Activity Interrupted"
		#define STR0057 "Manual Activity"
		#define STR0058 "Activity with Problems"
		#define STR0059 "Display the description of the product in the RF collector for verification processes"
		#define STR0060 "Quantity of tolerance for separation "
		#define STR0061 "Finishes separation/resupply"
		#define STR0062 "Enables to change lot number in RF separation"
		#define STR0063 "1=No"
		#define STR0064 "2=Yes"
		#define STR0065 "3=Confirmation"
		#define STR0066 "Sequential to determine the services running sequence"
		#define STR0067 "Rule to compound the call priority"
		#define STR0068 "Determines the separation order only after the load/document conclusion"
		#define STR0069 "Call type for frequency radio"
		#define STR0070 "1=Activity"
		#define STR0071 "2=Task/Product"
		#define STR0072 "3=Task/Complete"
		#define STR0073 "Local (Warehouse) Quality Control"
		#define STR0074 "Binding between warehouse and location"
		#define STR0075 "Automatic transfer document number"
		#define STR0076 "Activates the transactions checking for Products with Trace and/or Location"
		#define STR0077 "Groups items of the same lot and sub lot"
		#define STR0078 "Performs the release of the order for the last address"
		#define STR0079 "Allows negative balance"
		#define STR0080 "Tolerance for calculation with 1 UM"
		#define STR0081 "Inventory closing last date"
		#define STR0082 "Default formula code used to fill in batches"
		#define STR0083 "Uses single lot concept "
		#define STR0084 "Uses Lots/Sub-Lots  with expired validity date"
		#define STR0085 "Use Production Batch Traceability"
		#define STR0086 "Type of WMS Address"
		#define STR0087 "3=Maybe"
		#define STR0088 "Evaluates addresses capacity"
		#define STR0089 "Address description for generated addresses"
		#define STR0090 "Generates the inventory block for products controlling trace or location"
		#define STR0091 "Products can use physical location control"
		#define STR0092 "When a movement reversal with location control happens, you must"
		#define STR0093 "0=Redistribute"
		#define STR0094 "1=Original Location"
		#define STR0095 "2=Question"
		#define STR0096 "Runs WMS processes considering load"
		#define STR0097 "1=Processes per load"
		#define STR0098 "2=Processes per document/series"
		#define STR0099 "Uses Load"
		#define STR0100 "Type of fractionated blocked address"
		#define STR0101 "1=To complete address completely full"
		#define STR0102 "2=Only whether the balance plus quantity is smaller than the capacity"
		#define STR0103 "Addresses must be fully completed"
		#define STR0104 "Mixtures Lot/Sub Lot in the Level"
		#define STR0105 "Blocked Check. Level to be considered in the Address"
		#define STR0106 "Level for Lot/Sub/Lot Mixture"
		#define STR0107 "Parameters"
		#define STR0108 "WMS Parameters"
		#define STR0109 "WMS General"
		#define STR0110 "RF (Frequency Radio)"
		#define STR0111 "Address Control"
		#define STR0112 "Blocked"
		#define STR0113 "Lot Control"
		#define STR0114 "Inventory"
		#define STR0115 "Invoicing"
		#define STR0116 "Load"
		#define STR0117 "Quality"
		#define STR0118 "Log"
		#define STR0119 "Logistic Integration"
		#define STR0120 "Performs the WMS checking with RF, so it only blocks the items with divergence"
		#define STR0121 "1=Load Reverse"
		#define STR0123 "&Save"
		#define STR0124 "Save Parameters"
		#define STR0125 "&Close"
		#define STR0126 "Close"
		#define STR0127 ".T.=Yes"
		#define STR0128 ".F.=No"
		#define STR0129 "4=Use and release must be Manual after finishing the Check"
		#define STR0130 "1=Addresses completely empty"
		#define STR0131 "2=Addresses partially full"
		#define STR0132 "3=Partially full without mixing badges"
		#define STR0133 "4=Share add. different products"
		#define STR0134 "Assemble Volume at end of Sorting?"
		#define STR0135 "Automatically Distributes Product with Purchase Order"
		#define STR0136 "Block balance to addressing closing"
		#define STR0137 "It displays the detailed address description on RF collector screens"
		#define STR0138 "Receipt checking shortage warehouse"
		#define STR0139 "Receipt checking excess warehouse"
		#define STR0140 "Address of receipt checking lack"
		#define STR0141 "Type of inflow movement in the surplus warehouse"
		#define STR0142 "Service for inflow movement in  the surplus warehouse"
		#define STR0143 "Assemble volume of accrued movements in the assemble during separation"
		#define STR0144 "Shipment packing list sequence"
		#define STR0145 "Restrict packing list of shipment by customer and store"
		#define STR0146 "Use automatic sequence in packing list"
		#define STR0147 "Request function of Resource in Call"
		#define STR0148 "Cargo grouping"
		#define STR0149 "0=Not group"
		#define STR0150 "1=Groups per Cargo"
		#define STR0151 "2=Groups per Cargo/Customer"
		#define STR0152 "Grouping"
		#define STR0153 "Activities"
		#define STR0154 "WMS Integration"
		#define STR0155 "Type of removal movement of current warehouse"
		#define STR0156 "Service for removal movement of current warehouse"
		#define STR0157 "Type of absence inflow movement in warehouse"
		#define STR0158 "Service for absence inflow movement in warehouse"
		#define STR0159 "Address of receipt verification surplus"
		#define STR0160 "0=Not Used"
		#define STR0161 "1=Direct Proration"
		#define STR0162 "2=Proportional Proration"
		#define STR0163 "3=Proration Unit + Proportional"
		#define STR0164 "4=Sales Order Direct Proration + Proportional Distribution Plan"
		#define STR0165 "0=Not Validated"
		#define STR0166 "1=Validated Prev Invoicing"
		#define STR0167 "2=Validates Post Invoicing"
		#define STR0168 "3=Validates Both"
		#define STR0169 "Type of production movement for WMS assembly"
		#define STR0170 "Receipt"
		#define STR0171 "Type of movement of request for WMS assembly production"
		#define STR0172 "Blocks in addressed volumes packing list"
		#define STR0173 "Type of request write-off transaction in WMS separation"
		#define STR0174 "Default type when closing an occurrence"
		#define STR0175 "1=Inbound Document"
		#define STR0176 "2=Outbound Document"
		#define STR0177 "3=Internal Transaction"
		#define STR0178 "Always return to the first role of the operator in the search of pending activities"
		#define STR0179 "It uses job in integration of services with automatic execution"
		#define STR0180 "No call when there is no rule of call defined"
		#define STR0181 "View search of balance for the picking"
		#define STR0182 "View search of address for storing"
		#define STR0183 "Display resupply messages"
		#define STR0184 "Type of movement of request for orders automatically generated from crossdocking volumes"
		#define STR0185 "Outflow TIO of movement of request for orders automatically generated from crossdocking volumes"
		#define STR0186 "Automatically execution only for full order"
		#define STR0187 "Enable the generation of dispatch shipping via collector"
		#define STR0188 "Enable supply of picking address with picking structures of minimum quantity of major picking"
		#define STR0189 "Display the description of the product in the RF collector for movement processes"
		#define STR0190 "Limit of busy picking addresses"
		#define STR0191 "Allow checking products not entered in proforma invoice or incoming document?"
		#define STR0192 "Request batch expiration date while checking if not previously entered."
	#else
		#define STR0001 "Parâmetros do WMS"
		#define STR0002 "Integração Logística"
		#define STR0003 "S=Sim"
		#define STR0004 "N=Não"
		#define STR0005 "Data do Protheus diferente da data do sistema"
		#define STR0006 "Reabastecimento até completar o picking"
		#define STR0007 "Considera Múltiplos Endereços de Picking"
		#define STR0008 "Altera norma para total restante do apanhe"
		#define STR0009 "Refresh do monitor de serviços (em segundos)"
		#define STR0010 "Reabaste endereços de picking totalmente vazios"
		#define STR0011 "Prioriza no apanhe de mercadorias"
		#define STR0012 "E=Endereço mais próximo"
		#define STR0013 "V=Data de validade mais próxima"
		#define STR0014 "Habilita vallidações no estorno do serviço WMS na rotina Exec. de serviços"
		#define STR0015 "Habilita validação do movimento do WMS na rotina de transferência"
		#define STR0016 "Novo estorno do WMS pelo IDDCF"
		#define STR0017 "Montagem de Volume"
		#define STR0018 "Número sequencial das etiquetas de volume"
		#define STR0019 "Usa conferência na expedição?"
		#define STR0020 "1=Usa e bloqueia faturamento ate concluir"
		#define STR0021 "2=Usa e permite faturamento antes da conclusão"
		#define STR0022 "3=Não usa"
		#define STR0023 "Campos da tabela SB5 que devem ser considerados pelo Wizard de Complemento Produtos"
		#define STR0024 "Execução de serviços RDMAKE via rádio frequência, deve alterar o status do serviço"
		#define STR0025 "Bloqueia somente itens com divergência"
		#define STR0026 "Reinício automático das tarefas interrompidas"
		#define STR0028 "Permite selecionar múltiplas tarefas"
		#define STR0029 "0=Nenhum"
		#define STR0030 "1=Apanhe"
		#define STR0031 "2=Endereçar"
		#define STR0032 "3=Ambos"
		#define STR0033 "Método de descarga quando utiliza múltiplas tarefas"
		#define STR0034 "0=End.Destino+Produto+Lote+SubLote"
		#define STR0035 "1=Inverso da Carga,com produtos,lotes com mesmo endereço de destino"
		#define STR0036 "Nível Final do Endereço a ser mostrado nas rotinas de RF"
		#define STR0037 "Nível Inicial do Endereço a ser mostrado nas rotinas de RF"
		#define STR0038 "Número de contagens que o conferente pode executar"
		#define STR0039 "1=Sim"
		#define STR0040 "2=Não"
		#define STR0041 "Utiliza Rádio Frequência"
		#define STR0042 "Tempo em milissegundos em que o sistema ficará em pausa hibernando"
		#define STR0043 "Tempo em milissegundos em que o sistema ficará em pausa acordado"
		#define STR0044 "Informa localização ao acessar opção de Convocação RF"
		#define STR0045 "Ativa Tratamento de Hibernação"
		#define STR0046 "Solicita confirmação do lote nas operações com RF"
		#define STR0047 "Unidade de medida utilizada"
		#define STR0048 "1=1a.UM"
		#define STR0049 "2=2a.UM"
		#define STR0050 "3=Unitizador"
		#define STR0051 "4=UMI"
		#define STR0052 "Diretório dos documentos/logs"
		#define STR0053 "Atividade a executar"
		#define STR0054 "Atividade Automática"
		#define STR0055 "Atividade Executada"
		#define STR0056 "Atividade Interrompida"
		#define STR0057 "Atividade Manual"
		#define STR0058 "Atividade com Problemas"
		#define STR0059 "Apresenta descrição do produto no coletor RF para os processos de conferência"
		#define STR0060 "Quantidade de tolerância para separação a maior"
		#define STR0061 "Finaliza separação/reabastecimento"
		#define STR0062 "Permite alterar nro lote na separação RF"
		#define STR0063 "1=Não"
		#define STR0064 "2=Sim"
		#define STR0065 "3=Confirmação"
		#define STR0066 "Sequencial para determinar a sequência de execução dos serviços"
		#define STR0067 "Regra para compor a prioridade de convocação"
		#define STR0068 "Determina a ordem de separação somente após a conclusão da carga/documento"
		#define STR0069 "Tipo de convocação para rádio frequência"
		#define STR0070 "1=Atividade"
		#define STR0071 "2=Tarefa/Produto"
		#define STR0072 "3=Tarefa/Completa"
		#define STR0073 "Local (Almoxarifado) Controle de Qualidade"
		#define STR0074 "Amarração entre almoxarifado e localização"
		#define STR0075 "Número documento transferência automática"
		#define STR0076 "Ativa a verificação de movimentações para Produtos com Rastro e/ou Localização"
		#define STR0077 "Aglutina itens do mesmo lote e sub-lote"
		#define STR0078 "Realiza a reliberação do pedido para o último endereço"
		#define STR0079 "Permite saldo negativo"
		#define STR0080 "Tolerância para cálculos com a 1 UM"
		#define STR0081 "Data último fechamento do estoque"
		#define STR0082 "Código da fórmula default utilizada para preenchimento dos lotes"
		#define STR0083 "Utiliza conceito de lote único"
		#define STR0084 "Utiliza Lotes/Sub-Lotes com a data de validade vencida"
		#define STR0085 "Utiliza Rastreabilidade dos Lotes de Produção"
		#define STR0086 "Tipo de Endereçamento para WMS"
		#define STR0087 "3=Talvez"
		#define STR0088 "Avalia capacidade dos endereços"
		#define STR0089 "Descrição do endereço para endereços gerados"
		#define STR0090 "Gera bloqueio de estoque para produtos que controlam rastro ou localização"
		#define STR0091 "Produtos podem usar controle de localização física"
		#define STR0092 "Ao ocorrer um estorno de movimento com controle de localização deve-se"
		#define STR0093 "0=Redistribuir"
		#define STR0094 "1=Localização Original"
		#define STR0095 "2=Perguntar"
		#define STR0096 "Realiza processos WMS considerando carga"
		#define STR0097 "1=Processos por carga"
		#define STR0098 "2=Processos por documento/série"
		#define STR0099 "Utiliza Carga"
		#define STR0100 "Tipo de endereçamento blocado fracionado"
		#define STR0101 "1=Para complentar endereços completamente cheios"
		#define STR0102 "2=Somente se o saldo mais quantidade for menor que a capacidade"
		#define STR0103 "Endereços parcialmente cheios deverão ser preenchidos por completo"
		#define STR0104 "Mistura Lote/Sub-Lote no Nível"
		#define STR0105 "Nível da Conf.Blocado a ser considerado no Endereçamento"
		#define STR0106 "Nível para Mistura Lote/Sub/Lote"
		#define STR0107 "Parâmetros"
		#define STR0108 "Parâmetros WMS"
		#define STR0109 "WMS Geral"
		#define STR0110 "RF (Rádio Frequência)"
		#define STR0111 "Controle de Endereço"
		#define STR0112 "Blocado"
		#define STR0113 "Controle de Lote"
		#define STR0114 "Estoque"
		#define STR0115 "Faturamento"
		#define STR0116 "Carga"
		#define STR0117 "Qualidade"
		#define STR0118 "Log"
		#define STR0119 "Integração Logística"
		#define STR0120 "Realiza a conferência WMS com RF de forma que bloqueia somente itens com divergência"
		#define STR0121 "1=Inverso da Carga"
		#define STR0123 "&Salvar"
		#define STR0124 "Salvar Parâmetros"
		#define STR0125 "&Fechar"
		#define STR0126 "Fechar"
		#define STR0127 ".T.=Sim"
		#define STR0128 ".F.=Não"
		#define STR0129 "4=Usa e liberação deve ser Manual após conclusão da Conferência"
		#define STR0130 "1=Endereços totalmente vazios"
		#define STR0131 "2=Endereços parcialmente cheios"
		#define STR0132 "3=Parcialmente cheios sem misturar lotes"
		#define STR0133 "4=Compartilha end. produtos diferentes"
		#define STR0134 "Monta Volume no Final da Separação?"
		#define STR0135 "Efetua Automaticamente a Distribuição Produto com Pedido Compra"
		#define STR0136 "Bloqueia saldo até encerramento do endereçamento"
		#define STR0137 "Apresenta a descrição detalhada do endereço nas telas de coletor RF"
		#define STR0138 "Armazém de falta da conferência de recebimento"
		#define STR0139 "Armazém de excesso da conferência de recebimento"
		#define STR0140 "Endereço de falta da conferência de recebimento"
		#define STR0141 "Tipo de movimentação de entrada no armazém de excesso"
		#define STR0142 "Serviço para movimentos de entrada no armazém de excesso"
		#define STR0143 "Monta volume de movimentos aglutinados na montagem durante a separação"
		#define STR0144 "Sequencial romaneio de embarque"
		#define STR0145 "Restringir romaneio de embarque por cliente e loja"
		#define STR0146 "Utiliza sequência automática no romaneio de embarque"
		#define STR0147 "Solicitar função do Recurso na Convocação"
		#define STR0148 "Aglutinação da carga"
		#define STR0149 "0=Não Aglutina"
		#define STR0150 "1=Aglutina por Carga"
		#define STR0151 "2=Aglutina por Carga/Cliente"
		#define STR0152 "Aglutinação"
		#define STR0153 "Atividades"
		#define STR0154 "Integração WMS"
		#define STR0155 "Tipo de movimentação de retirada do armazém atual"
		#define STR0156 "Serviço para movimento de retirada do armazém atual"
		#define STR0157 "Tipo de movimentação de entrada no armazém de falta"
		#define STR0158 "Serviço para movimento de entrada no armazém de falta"
		#define STR0159 "Endereço de excesso da conferência de recebimento"
		#define STR0160 "0=Não Utiliza"
		#define STR0161 "1=Rateio Direto"
		#define STR0162 "2=Rateio Proporcional"
		#define STR0163 "3=Rateio Unidade + Proporcional"
		#define STR0164 "4=Rateio Direto Pedido de Venda + Proporcional Plano de Distribuição"
		#define STR0165 "0=Não Valida"
		#define STR0166 "1=Valida Ant Faturamento"
		#define STR0167 "2=Valida Pos Faturamento"
		#define STR0168 "3=Valida Ambos"
		#define STR0169 "Tipo de movimentação produção para montagem WMS"
		#define STR0170 "Recebimento"
		#define STR0171 "Tipo de movimentação de requisição para produção na montagem WMS"
		#define STR0172 "Bloqueia no romaneio volumes endereçados"
		#define STR0173 "Tipo de movimentação de baixa de requisição na separação WMS"
		#define STR0174 "Tipo padrão ao encerrar uma ocorrência"
		#define STR0175 "1=Documento de Entrada"
		#define STR0176 "2=Documento de Saída"
		#define STR0177 "3=Movimento Interno"
		#define STR0178 "Retorna sempre para primeira função do operador na busca das atividades pendentes"
		#define STR0179 "Utiliza job nas integrações de serviços com execução automática"
		#define STR0180 "Não efetua convocação quando não encontrar regra de convocação definida"
		#define STR0181 "Visualizar busca de saldo para o apanhe"
		#define STR0182 "Visualizar busca de endereços para a armazenagem"
		#define STR0183 "Exibir as mensagens de reabastecimento"
		#define STR0184 "Tipo de mov. de requisição para pedidos gerados automaticamente a partir de volumes crossdocking"
		#define STR0185 "TES de saída para pedidos gerados automaticamente a partir de volumes crossdocking"
		#define STR0186 "Execução automática somente para pedido completo"
		#define STR0187 "Permite gerar embarque de expedição via coletor"
		#define STR0188 "Permite abastecimento do endereço picking com estruturas picking de qtde minima de apanhe maior"
		#define STR0189 "Apresenta descricao do produto no coletor RF para os processos de movimentação"
		#define STR0190 "Limite de endereços de picking ocupados"
		#define STR0191 "Bloquear conferência de produtos não informados na pre-nota ou documento de entrada."
		#define STR0192 "Solicitar a data de validade do lote na conferência caso não encontre-se previamente informada."
	#endif
#endif
