#ifdef SPANISH
	#define STR0001 "WS Jurídico contencioso"
	#define STR0002 "Sugerencia de valores del análisis"
	#define STR0003 "Reprocesar publicación"
	#define STR0004 "Realiza la importación en lote de publicaciones"
	#define STR0005 'Procesando'
	#define STR0006 "Actualización de modelo"
	#define STR0007 "¡No hay campos informados para grabar en el modelo!"
	#define STR0008 "Vincular publicación no localizada"
	#define STR0009 "Obtiene la etapa procesal"
	#define STR0010 "extracto de garantía"
	#define STR0011 "Genera el extracto de la Garantía"
	#define STR0012 "Genera el archivo XML e-social"
	#define STR0013 "Marca incidente"
	#define STR0014 "El incidente informado no se encuentra en la base de datos."
	#define STR0015 "El proceso informado no se encuentra en la base de datos."
	#define STR0016 "Incidente vinculado con éxito."
	#define STR0017 "Incidente desvinculado con éxito"
	#define STR0018 ": Acceso negado."
	#define STR0019 "Sin permiso para PUT en JURA289."
	#define STR0020 "Obtiene la oficina del correspondiente"
	#define STR0021 "extracto de gastos"
	#define STR0022 "Busca secuencial juzgado"
	#define STR0023 "Lista subsidios solicitados"
#else
	#ifdef ENGLISH
		#define STR0001 "WS Litigation Legal"
		#define STR0002 "Suggestion of Survey Values"
		#define STR0003 "Reprocess publication"
		#define STR0004 "Import in publications batch"
		#define STR0005 'Processing'
		#define STR0006 "Model updating"
		#define STR0007 "No fields completed to be saved in the model!"
		#define STR0008 "Link publication not found"
		#define STR0009 "Get procedure phase"
		#define STR0010 "Collateral statement"
		#define STR0011 "Generate collateral statement"
		#define STR0012 "Generate e-Social XML file"
		#define STR0013 "Incident arrow"
		#define STR0014 "Incident not found in database!"
		#define STR0015 "Source procedure not found in database!"
		#define STR0016 "Incident linked successfully!"
		#define STR0017 "Incident unlinked successfully!"
		#define STR0018 ": Access denied."
		#define STR0019 "No permission for PUT in JURA289."
		#define STR0020 "Get correspondent firm"
		#define STR0021 "expense statement"
		#define STR0022 "Search court sequential"
		#define STR0023 "Requested subsidies list"
	#else
		#define STR0001 "WS Jurídico Contencioso"
		#define STR0002 "Sugestão de Valores do Levantamento"
		#define STR0003 "Reprocessar publicação"
		#define STR0004 "Realiza a importação em lote de publicações"
		#define STR0005 'Processando'
		#define STR0006 "Atualização de modelo"
		#define STR0007 "Não há campos preenchidos para serem salvos no modelo!"
		#define STR0008 "Vincular publicação não localizada"
		#define STR0009 "Obtém a Fase Processual"
		#define STR0010 "extrato de garantia"
		#define STR0011 "Gera o extrato da Garantia"
		#define STR0012 "Gera o arquivo XML e-social"
		#define STR0013 "Seta incidente"
		#define STR0014 "O incidente informado não foi localizado na base de dados!"
		#define STR0015 "O proesso origem informado não foi localizado na base de dados!"
		#define STR0016 "Incidente vinculado com sucesso!"
		#define STR0017 "Incidente desvinculado com sucesso!"
		#define STR0018 ": Acesso negado."
		#define STR0019 "Sem permissão para PUT em  JURA289."
		#define STR0020 "Obtém o escritório do correspondente"
		#define STR0021 "extrato de despesa"
		#define STR0022 "Busca sequencial vara"
		#define STR0023 "Lista subsídios solicitados"
	#endif
#endif
