#ifdef SPANISH
	#define STR0001 "WebService para prueba API"
	#define STR0002 "Descarga Arch. Adjunto vía LegalDesk"
	#define STR0003 "Conversión de PDF a Texto"
	#define STR0004 "Análisis de PDF del cuentas por pagar"
	#define STR0005 "Crea anexo"
	#define STR0006 "Eliminación del anexo"
	#define STR0007 "Archivo no existe"
	#define STR0008 "No fue posible crear la carpeta /thf. Error:"
	#define STR0009 "No fue posible cargar el archivo"
	#define STR0010 "WSPfsApi"
	#define STR0011 "Verifique si el documento seleccionado está correcto."
	#define STR0012 "Verifique si el ejecutable pdftotext.exe se encuentra en la carpeta del AppServer"
	#define STR0013 "Error al leer el archivo"
	#define STR0014 "WorkSite"
	#define STR0015 "Documentos en destaque - Fluig"
	#define STR0016 "Archivo adjunto copiado con éxito."
	#define STR0017 "Error al crear el archivo en el spool."
	#define STR0018 "Clave primaria no válida [#1]"
	#define STR0019 "No fue posible encontrar el archivo"
	#define STR0020 "No fue posible crear la carpeta #1 Error: #2"
	#define STR0021 "Busca a Estrutura do MVC"
	#define STR0022 "Busca dados do campo"
	#define STR0023 "Busca os dados do modelo"
	#define STR0024 "Busca a lista de opções de um campo tipo F3"
	#define STR0025 "Busca o registro específico de um campo tipo F3"
	#define STR0026 "Erro ao montar a estrutura do modelo."
	#define STR0027 "É necessário passar o modelo a ser consultado."
	#define STR0028 "O campo informado não existe no ambiente!"
	#define STR0029 "Informe um modelo!"
	#define STR0030 "O modelo informado não é MVC!"
#else
	#ifdef ENGLISH
		#define STR0001 "WebService for API test"
		#define STR0002 "Download attachment via LegalDesk"
		#define STR0003 "Convert PDF to Text"
		#define STR0004 "Accounts Payable PDF Analysis"
		#define STR0005 "Create attachment"
		#define STR0006 "Delete attachment"
		#define STR0007 "File does not exist"
		#define STR0008 "Unable to create folder /thf. Error:"
		#define STR0009 "Could not load the file"
		#define STR0010 "WSPfsApi"
		#define STR0011 "Check if the selected document is correct"
		#define STR0012 "Check if executable pdftotext.exe is in AppServer folder"
		#define STR0013 "Error reading file"
		#define STR0014 "WorkSite"
		#define STR0015 "Highlighted documents - Fluig"
		#define STR0016 "Attachment copied successfully."
		#define STR0017 "Error creating file in spool."
		#define STR0018 "Primary key invalid [#1] "
		#define STR0019 "Could not locate file"
		#define STR0020 "Unable to create folder #1 Error: #2"
		#define STR0021 "Search MVC Structure"
		#define STR0022 "Search field data"
		#define STR0023 "Search template data"
		#define STR0024 "Search options list of an F3 type field."
		#define STR0025 "Search specific record of an F3 type field."
		#define STR0026 "Error when assembling model structure."
		#define STR0027 "You need to convey the model to be queried."
		#define STR0028 "Field entered does not exist in the environment!"
		#define STR0029 "Enter a template!"
		#define STR0030 "Template entered is not MVC!"
	#else
		#define STR0001 "WebService para teste API"
		#define STR0002 "Download anexo via LegalDesk"
		#define STR0003 "Conversão de PDF para Texto"
		#define STR0004 "Analise de PDF do Contas a pagar"
		#define STR0005 "Cria anexo"
		#define STR0006 "Exclusão do anexo"
		#define STR0007 "Arquivo não existe"
		#define STR0008 "Não foi possível criar a pasta /thf. Erro:"
		#define STR0009 "Não foi possível carregar o arquivo"
		#define STR0010 "WSPfsApi"
		#define STR0011 "Verifique se o documento selecionado está correto"
		#define STR0012 "Verifique se o executável pdftotext.exe se encontra na pasta do AppServer"
		#define STR0013 "Erro ao ler o arquivo"
		#define STR0014 "WorkSite"
		#define STR0015 "Documentos em Destaque - Fluig"
		#define STR0016 "Anexo copiado com sucesso."
		#define STR0017 "Erro ao criar o arquivo no spool."
		#define STR0018 "Chave primária inválida [#1]"
		#define STR0019 "Não foi possível localizar o arquivo"
		#define STR0020 "Não foi possível criar a pasta #1 Erro: #2"
		#define STR0021 "Busca a Estrutura do MVC"
		#define STR0022 "Busca dados do campo"
		#define STR0023 "Busca os dados do modelo"
		#define STR0024 "Busca a lista de opções de um campo tipo F3"
		#define STR0025 "Busca o registro específico de um campo tipo F3"
		#define STR0026 "Erro ao montar a estrutura do modelo."
		#define STR0027 "É necessário passar o modelo a ser consultado."
		#define STR0028 "O campo informado não existe no ambiente!"
		#define STR0029 "Informe um modelo!"
		#define STR0030 "O modelo informado não é MVC!"
	#endif
#endif
